### ISSUE TITLE
Java: New Feature: OpenAI o1 model support

### ISSUE THREAD

**Issue by evmin** [microsoft/semantic-kernel#10015]
---
name: Feature request
about: Suggest an idea for this project

---

OpenAI o1 model introduced a number of unique parameters incompatible with other models (1) :

- Developer Message as opposed to System Message
- reasoning_effort parameter
- max_completion_tokens

With o1 being released as GA we need to add the model support as soon as reasonable.

This overlaps with Bug report (2).

1. [o1 announcement](https://github.com/microsoft/semantic-kernel/issues/9749)
2. [SK BUG 9749](https://github.com/microsoft/semantic-kernel/issues/9749)

**Comment by markwallace-microsoft** [comment]
Created issue in th java repo: https://github.com/microsoft/semantic-kernel-java/issues/280
