### ISSUE TITLE
Unable to extract semantic memory in sample app chatapp

### ISSUE THREAD

**Issue by poweihuang0817** [microsoft/semantic-kernel#1002]
**Describe the bug**
There are some error log in chatgpp.
Unable to extract semantic memory for LongTermMemory: The JSON value could not be converted to SemanticKernel.Service.Skills.SemanticChatMemoryItem. Path: $.items[2].details | LineNumber: 0 | BytePositionInLine: 189.. Continuing...
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by TaoChenOSU** [comment]
Hello!

Thanks for your feedback!

This is expected as we cannot rely on the models to generate Json blocks of correct format each time.
