### ISSUE TITLE
Notebook '04-context-variables-chat' not working

### ISSUE THREAD

**Issue by riedgar-ms** [microsoft/semantic-kernel#1021]
**Describe the bug**

Just checked out the code, and going through the notebooks in `samples/notebooks/python`, I'm finding that `04-context-variables-chat.ipynb` isn't working. 

**To Reproduce**

On running the authentication cell, I get an error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 10
      8 # Configure AI service used by the kernel
      9 if useAzureOpenAI:
---> 10     api_key, endpoint = sk.azure_openai_settings_from_dot_env()
     11     kernel.add_text_completion_service("dv", AzureTextCompletion("text-davinci-003", api_key, endpoint))
     12 else:

ValueError: too many values to unpack (expected 2)

**Expected behavior**

This should work.... like the similar cells in the other notebooks (e.g. 02).... I can see that the API calls are different

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win11
 - IDE: Jupyter notebooks / Python 3.11
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

N/A

**Comment by craigomatic** [comment]
@alexchaomander can you take a look please?

**Comment by alexchaomander** [comment]
Thanks for creating the fix in #1022 @riedgar-ms ! Looking forward to having that land soon
