### ISSUE TITLE
resource file should be embedded in the project

### ISSUE THREAD

**Issue by EashShow** [microsoft/semantic-kernel#1032]
"vocab.bpe", and "encoder.json" shoud be embedded into the project "Connectors.AI.OpenAI"
and this project read these files from embedded resource, not from the OS file system.
It will be easy to call this package.

**Comment by evchaki** [comment]
@EashShow , we decided to leave these out due to the size of the files.  That way the kernel stays streamlined.  We will add more tokenizers using the same approach in the future.  If you want to embed these files you will need to make a custom version of the connector.
