### ISSUE TITLE
Select Vector(s) From Qdrant

### ISSUE THREAD

**Issue by EashShow** [microsoft/semantic-kernel#1055]
I want to add this feature to this project.
Assigned to me?

**Comment by evchaki** [comment]
@EashShow  - feel free to do a PR.  What scenario are you looking to solve?

**Comment by EashShow** [comment]
I want to select all vectors to view, then to update, to delete...

**Comment by EashShow** [comment]
I've submitted the code in #1057 , what else do I need to do in this PR?

**Comment by nacharya1** [comment]
Closing this apart of bug bug #970. Thanks for submitting the PR.
