### ISSUE TITLE
Java: Properly resolve issues in java/spotbugs-exclude.xml

### ISSUE THREAD

**Issue by dsgrieve** [microsoft/semantic-kernel#1113]
**Describe the bug**
The bug patterns being excluded in java/spotbugs-exlude.xml should be addressed in the code. 

**To Reproduce**
1. checkout the experimental-java branch
2. cd java
3. ./mvnw clean verify -Pbug-check

**Expected behavior**
There should not be a `spotbugs-exclude.xml`. We should not get any spotbugs errors when compiling with -Pbug-check. 
NOTE: This isn't entirely true. There may be issues that we just cannot resolve, or we may know better than spotbugs. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by d3r3kk** [comment]
See #1604

**Comment by d3r3kk** [comment]
Closed. PR #4800
