### ISSUE TITLE
Implement SequentialPlanner in Copilot ChatApp

### ISSUE THREAD

**Issue by thomasgobin** [microsoft/semantic-kernel#1137]
For the needs of a prototype, I had to chain actions (and so functions).
Currently, only ActionPlanner is supported in the Copilot ChatApp. 
I have updated the app to support both (ActionPlanner and SequentialPlanner).
I am going to submit a PR for this change to be supported if it makes sense.

**Comment by hathind-ms** [comment]
Thanks @thomasgobin! We'd love to have your PR to add SequentialPlanner support. cc - @teresaqhoang

**Comment by thomasgobin** [comment]
Hi, PR has just been updated #1139

**Comment by teresaqhoang** [comment]
PR's been merged! See [Enabling Sequential Planner
](https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/copilot-chat-app/webapi#enabling-sequential-planner) on setup instructions
