### ISSUE TITLE
Tests fail when running build.sh on mac

### ISSUE THREAD

**Issue by unicomp21** [microsoft/semantic-kernel#114]
What docker image should I be using when running build.sh?

**Comment by timlaverty** [comment]
@dluc

**Comment by dluc** [comment]
@unicomp21 [build.sh](https://github.com/microsoft/semantic-kernel/blob/main/build.sh) is a shortcut script to compile the C# code, running the code style checkers, running all the unit and integrations tests. 

You **won't need Docker**.  You can also ignore the script if you like: as long as you have either .NET 6 or 7 installed on your machine, these steps are equivalent to the build script.

To run code style and build the code locally, similarly to the continuous integration pipeline:
```
cd dotnet
dotnet build --configuration Release
```
This will also generate a local nuget, in case you're testing something new.

To run unit and integration tests:
```
cd dotnet
dotnet test --configuration Release
```

**Comment by unicomp21** [comment]
Thanks!
