### ISSUE TITLE
Error: Invalid request: The request is not valid, HTTP status: 404. Details: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

### ISSUE THREAD

**Issue by Tangroo** [microsoft/semantic-kernel#1144]
I try to deploy the copilot chat app, use AzureOpenAI, and try to chat after deployment, but when I send a message to it, an error "Error: Invalid request: The request is not valid, HTTP status: 404. Details: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again." 
will be reported. What is the reason for this?
![1684741461742](https://github.com/microsoft/semantic-kernel/assets/48377330/15d014d2-5a11-4155-b84c-a06f7894f75f)

**Comment by hathind-ms** [comment]
Based on the provided image, it doesn't look like your `REACT_APP_BACKEND_URI` is update to your deployed instance, it is still pointing to `localhost`. 

cc - @glahaye

**Comment by shree12312** [comment]
> I try to deploy the copilot chat app, use AzureOpenAI, and try to chat after deployment, but when I send a message to it, an error "Error: Invalid request: The request is not valid, HTTP status: 404. Details: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again." will be reported. What is the reason for this? ![1684741461742](https://user-images.githubusercontent.com/48377330/239838799-15d014d2-5a11-4155-b84c-a06f7894f75f.jpg)

Hey man, did you create the deployments for the models that you will need to run copilot?
if not then go ahead and do that, that should solve the problem, the names for deployments should be the same as the model names...

**Comment by Tangroo** [comment]
> Are you able to use the endpoint in the Azure OpenAI playground?

yes, I used
![image](https://github.com/microsoft/semantic-kernel/assets/48377330/54024c25-1bc2-41c1-9d8c-f91b86f1a663)

**Comment by Tangroo** [comment]
> 



> Based on the provided image, it doesn't look like your `REACT_APP_BACKEND_URI` is updated to your deployed instance, it is still pointing to `localhost`.
> 
> cc - @glahaye

**Comment by Tangroo** [comment]
> Based on the provided image, it doesn't look like your `REACT_APP_BACKEND_URI` is updated to your deployed instance, it is still pointing to `localhost`.
> 
> cc - @glahaye

I deployed it locally, both webapi and webapp were deployed locally

**Comment by Tangroo** [comment]
> > I try to deploy the copilot chat app, use AzureOpenAI, and try to chat after deployment, but when I send a message to it, an error "Error: Invalid request: The request is not valid, HTTP status: 404. Details: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again." will be reported. What is the reason for this? ![1684741461742](https://user-images.githubusercontent.com/48377330/239838799-15d014d2-5a11-4155-b84c-a06f7894f75f.jpg)
> 
> Hey man, did you create the deployments for the models that you will need to run copilot? if not then go ahead and do that, that should solve the problem, the names for deployments should be the same as the model names...

Excuse me, what do you mean by model? I just configured the environment locally first, then directly deployed the webapi and webapp of copilot chat locally, then created an authentication app on Azure according to the README for authentication, then opened Azure OpenAI, and configured the key and endpoint of AzureOpenAI to webapi, all follow the steps on the README. Are there any other models that need to be deployed?

**Comment by Tangroo** [comment]
sorry, it's my fault, I didn't deploy the semantic kernel to the Azure. I only deployed the copilot-chat app.

**Comment by Tangroo** [comment]
I can chat with it now, but I feel that the quality of his answer is not as high as chatgpt3.5. What is the reason? I used AzureOpenAI, gpt-35-turbo

**Comment by glahaye** [comment]
Poor response quality could be due to the prompts used within the chat skill.

@TaoChenOSU ? @adrianwyatt ?

**Comment by craigomatic** [comment]
> I can chat with it now, but I feel that the quality of his answer is not as high as chatgpt3.5. What is the reason? I used AzureOpenAI, gpt-35-turbo

Experimenting with different prompts would be the best way to improve the responses. It's currently biased towards a long running chat scenario which may not be best for your scenario.

The current way to modify the prompt used  is to tweak the values in [appsettings.json](https://github.com/microsoft/semantic-kernel/blob/8ea63f4783c1fe1a03829d8989918c21750c0442/samples/apps/copilot-chat-app/webapi/appsettings.json#L146). You may have to do this and restart the aspnet app, not sure if changes will be picked up while it's running.

I'm going to close this for now as it seems the 404 issue has been resolved, feel free to reopen if not and/or to open a new issue if you aren't able to get the prompts to behave the way you want them to.

**Comment by klentoy** [comment]
> sorry, it's my fault, I didn't deploy the semantic kernel to the Azure. I only deployed the copilot-chat app.

How did you do this?
