### ISSUE TITLE
get response error

### ISSUE THREAD

**Issue by Codingsaikou** [microsoft/semantic-kernel#1148]
Unable to generate bot response. Details: Error: 400: => Unknown error (UnknownError): Something went wrong: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy.
![image](https://github.com/microsoft/semantic-kernel/assets/56782630/b7151160-0d3a-482c-af8d-16e1b77a62dd)

**Comment by TaoChenOSU** [comment]
Hello! Thanks for posting the issue here!

Are you able to access your OpenAI endpoint outside of the Copilot chat sample app?

**Comment by Codingsaikou** [comment]
> Do you mind providing a screenshot of the `AIService` section of your appsettings.json file (cover the key and endpoint if there is any)? In addition, can you also provide the stack trace of where the error occurred from the webapi if there is any?

AIService:
![image](https://github.com/microsoft/semantic-kernel/assets/56782630/86c9a7eb-d6f9-4708-944b-ad5c5fceee7a)

**Comment by Codingsaikou** [comment]
> Do you mind providing a screenshot of the `AIService` section of your appsettings.json file (cover the key and endpoint if there is any)? In addition, can you also provide the stack trace of where the error occurred from the webapi if there is any?
is it right?  What else do I need to provide
![image](https://github.com/microsoft/semantic-kernel/assets/56782630/f5fbaa19-b1a3-4f6e-84e7-f62681a72b5d)

**Comment by feiyun0112** [comment]
did you used a proxy to access api.openai.com

if so, you need to modify the code to use the same proxy

**Comment by Codingsaikou** [comment]
> access api.openai.com

yeah, i used a proxy to access api.openai.com through Postman

Could you tell me where to modify th code to use the same proxy

**Comment by feiyun0112** [comment]
set environment variable `HTTPS_PROXY`

https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-7.0

**Comment by Codingsaikou** [comment]
> set environment variable `HTTPS_PROXY`
> 
> https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-7.0

thanks, i can get response now
