### ISSUE TITLE
Allow custom semantic backend?

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/semantic-kernel#115]
Hi folks, currently `semantic kernel` only allows us to use either `OpenAI` or `Azure OpenAI` as `TextCompletion` or `Embedding` backends. Is it possible for your team to add support for a customized `TextCompletion` backend? It will be helpful for developers who host their own GPT or AICG service.

## use case

```csharp
// my customized semantic backend
ITextCompletionClient myGossipTextClientInstance

IBackendConfig myGossipTextClientConfig

// suggested API to add config to kernel
kernel.Config.AddTextCompletionBackend(myGossipTextClientConfig, myGossipTextClientInstance)
```

**Comment by timlaverty** [comment]
Hi @LittleLittleCloud , thanks for sending feedback.  We are actively working on better multi-model and multi-modal support and will have an update on this shortly.

**Comment by LittleLittleCloud** [comment]
@timlaverty Thanks, looking forward to having this functionality in semantic kernel.

**Comment by dluc** [comment]
@LittleLittleCloud as @timlaverty we're actively working on this. 

In the meantime, just in case you are blocked, by the design the kernel allows to plug in any function that implements the [ISKFunction](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel/Orchestration/ISKFunction.cs) interface. So, only if this is urgent, this is one available path to integrate any model not yet supported.

**Comment by craigomatic** [comment]
@dluc This is now supported as of this PR https://github.com/microsoft/semantic-kernel/pull/161 right?

**Comment by evchaki** [comment]
This is now in the main branch, @LittleLittleCloud thanks for the feedback!
