### ISSUE TITLE
Welcome page "Preview your app locally" takes me to wrong README

### ISSUE THREAD

**Issue by pierceboggan** [microsoft/semantic-kernel#1186]
**Describe the bug**
Clicking "Run local preview (F5)" button on welcome page opens README from Teams Toolkit extension

![image](https://github.com/microsoft/semantic-kernel/assets/1091304/c7bd3e5d-ee50-4c7a-802b-d11421147d80)
![image](https://github.com/microsoft/semantic-kernel/assets/1091304/48f0e28c-7b6d-4aa0-8f70-60eb92cda392)

**To Reproduce**
1. Install Semantic Kernel extension in VS Code.
2. On extension welcome page, click "Run local preview (F5)"

**Expected behavior**
Instructions on debugging Semantic Kernel app locally show.

Instead, Teams Toolkit README shows.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: VS Code

**Comment by markwallace-microsoft** [comment]
Hi @pierceboggan 
the command being triggered will attempt to load the README from the current workspace, it is assuming you have created one of the SK starters and that is in your current workspace.

Is the README you are seeing from the current workspace?

The description of this step needs to be improved, we will work on improving this.

**Comment by markwallace-microsoft** [comment]
This is fixed in the latest VS Code extensions
