### ISSUE TITLE
Feature Matrix should have an icon legend

### ISSUE THREAD

**Issue by fyndor** [microsoft/semantic-kernel#1187]
The feature matrix markdown file utilizes 3 icons: the check mark, the X, and the counterclockwise icon.  I think the check mark and X are self-explanatory, but I do not know what the counterclockwise icon is trying to represent.  An icon legend somewhere on the page would be beneficial.  I don't mind making the change myself and creating a pull-request, but I don't actually know what it represents so I am unable to do so at this time.

**Comment by awharrison-28** [comment]
This is an easy request :) PR is out

**Comment by fyndor** [comment]
Thanks for the PR

**Comment by fyndor** [comment]
Page looks good, thanks again for the PR
