### ISSUE TITLE
OpenAI / copilot plugin support?

### ISSUE THREAD

**Issue by rsloggett-prmaconsulting** [microsoft/semantic-kernel#1222]
With all the announcements surrounding copilot development at Build 2023, with semantic kernel referenced as part of that AI stack, I'm wondering what the relationship is between the OpenAI plugin standard that is being promoted and semantic kernel. It looks like "plugin" in the current semantic kernel is not the same thing as the OpenAI plugin model. Does anyone have a view on how to best go about integrating an OpenAI plugin with semantic kernel? Is this something that is planned to become part of the samples - seems like a really strong scenario that will increase the value proposition of leveraging semantic kernel and increase the scenarios in which a given plugin can be used.

**Comment by evchaki** [comment]
@rsloggett-prmaconsulting  - check this out - https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.AI.OpenAI and https://github.com/microsoft/semantic-kernel/blob/main/samples/dotnet/kernel-syntax-examples/Example21_ChatGPTPlugins.cs -- these should get you started on calling an OpenAI plugin from SK.  You can also try this out using the copilot app - https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/copilot-chat-app

**Comment by goyanx** [comment]
Hi @evchaki , Can you use this with gpt-3.5-turbo or just for gpt-4 ?

**Comment by lemillermicrosoft** [comment]
Please let us know if you are still having issues here.
