### ISSUE TITLE
Implement OpenPlugin

### ISSUE THREAD

**Issue by jeffrschneider** [microsoft/semantic-kernel#1236]
Plugin Service Providers like OpenAI, Microsoft, Google, LangChain have inconsistent interfaces to their plugin runtimes, making it very difficult to test plugins. This issue requests that you offer a standard interface to your "tool selector" function. Doing so will enable the use of cross platform test harnesses. 

Specifically, we request that you create an OpenPlugin binding:
https://github.com/LegendaryAI/openplugin

**Comment by shawncal** [comment]
We on the SK team do not anticipate implementing support for this, though it sounds like a good extension if you or the community would like to build it!

Closing for now.
