### ISSUE TITLE
Unable to load chats. Details: Error: 401: Unauthorized

### ISSUE THREAD

**Issue by XunLi-Nick** [microsoft/semantic-kernel#1237]
After deploying to Azure, log in to AAD and enter Loading Chats with an error message: Unable to load chats Details: Error: 401: Unauthorized
![image](https://github.com/microsoft/semantic-kernel/assets/45253930/5215c865-acdb-40a9-8d8e-88f04f7209a3)

**Comment by TaoChenOSU** [comment]
Hello!

There are multiple authorization options for the web service: https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/webapi/appsettings.json#L68.

Depending on how you configure it, you will have to set up your Web App differently: https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/copilot-chat-app#start-the-webapp-frontend-application. Please refer to section 1 part 2.

**Comment by craigomatic** [comment]
@XunLi-Nick were you able to get unblocked?

**Comment by TaoChenOSU** [comment]
Closing now as it appears this issue has been resolved. Please reopen as needed.
