### ISSUE TITLE
Invalid Request 400 Error Running Notebooks

### ISSUE THREAD

**Issue by ryankmcintyre** [microsoft/semantic-kernel#1244]
**Describe the bug**
I'm using Azure OpenAI and going through the notebook samples. When executing the 02-running-prompts-from-file.ipynb notebook against a deployment using the gpt-35-turbo model, the result is `Error: Invalid request: The request is not valid, HTTP status: 400`. Switching to the text-davinci-003 model succeeds. Similar to issue #649.

**To Reproduce**
Steps to reproduce the behavior:  See above description

**Suggestion**
Perhaps add some language to that notebook sample stating which models are supported.

**Comment by alexchaomander** [comment]
To use the gpt-35-turbo model (which is a ChatCompletion model) you need to make sure you use the ChatCompletion API 

I try to show this off in the updated Python notebooks: https://github.com/microsoft/semantic-kernel/pull/1242

**Comment by lemillermicrosoft** [comment]
Please re-open if you are still having issue.

**Comment by ryankmcintyre** [comment]
It was more of a suggestion to update the sample/docs to include the model dependency to hopefully save future users some frustration. Not an issue with the sample itself, it works fine.
