### ISSUE TITLE
The QDrant memory 'SaveInformationAsync' method is failing to save new text with new id.

### ISSUE THREAD

**Issue by Jawahar-Mariappan** [microsoft/semantic-kernel#1253]
**Describe the bug**
In KernelSyntaxExamples project, the class 'Example19_Qdrant' explains how to use QDrant vector database to save text and run semantic search. 

Internally, the method 'SaveInformationAsync' checks, if the qdrant data store contains a record with the provided metadata ID. The method 'QdrantVectorDbClient.GetVectorByPayloadIdAsync' search for the record by given metadata ID.

If the text is new then the search response returned is empty. JSON Serialiser is failing to deserialise the empty string due to below attribute defined recently.

internal sealed class SearchVectorsResponse : QdrantResponse
{
    internal sealed class ScoredPoint
    {
        [JsonPropertyName("id")]
        **[JsonNumberHandling(JsonNumberHandling.WriteAsString)]**
        public string Id { get; }
--
--
}

**To Reproduce**
Insert a new text to QDrant vector database.

**Expected behavior**
Text should be inserted without any failure.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by craigomatic** [comment]
This has been resolved in #1313 - please reopen if you continue to experience issues
