### ISSUE TITLE
No skill in python to get topic summary, action items

### ISSUE THREAD

**Issue by cloudbow** [microsoft/semantic-kernel#1263]
Please provide skills for topic summary , action items in python

**Comment by craigomatic** [comment]
Have you taken a look at the semantic skills folder? 

Topic summary is there and should be callable from python which if your content is under token limits may help unblock you a little: https://github.com/microsoft/semantic-kernel/tree/main/samples/skills/SummarizeSkill

**Comment by nacharya1** [comment]
@cloudbow  can you confirm if this resolved your ask?

**Comment by cloudbow** [comment]
Let me check

**Comment by matthewbolanos** [comment]
Closing this issue since it was created several months ago.
