### ISSUE TITLE
Python: Add Postgres with pgvector as a Memory Store for Python

### ISSUE THREAD

**Issue by cschadewitz** [microsoft/semantic-kernel#1270]
I would like to add Postgres with pgvector as a Memory Store to the Python implementation to give parity for the addition to .net in #945

**Comment by cschadewitz** [comment]
[WIP](https://github.com/microsoft/semantic-kernel/compare/main...cschadewitz:semantic-kernel:python_postgres_memory_store)

Taking a different approach from the .net implementation:
collections as postgres schemas as opposed to collection being another column in the table
currently the metadata column is just storing the text field, however, I plan to change it to jsonb and store all additional existing fields (minus key and embedding) and other metadata if #1271 was given the go ahead

**Comment by 1983Thai** [comment]
https://github.com/google/omaha/commit/306056c976ba29182019839fdf41410321c3765c

**Comment by alexchaomander** [comment]
Thanks for helping bring this in to Python!

**Comment by cschadewitz** [comment]
Absolutely, I am very excited to help get this up to par with the .net implementation. I do have a few questions though relating to implementation:
1. What is the difference/purpose of the key and id fields in the memory record, is one intended to be an app level identifier while the other is the p key in the db?
2. Is the external source intended to be the original source of the record or source from which it was last pulled?
3. What is the purpose of the different record types, reference vs local?
4. Currently, on both this [WIP](https://github.com/microsoft/semantic-kernel/compare/main...cschadewitz:semantic-kernel:python_postgres_memory_store) and the PR that I am helping with #769, the embedding dimensions are set at collection creation time (which doesnt mesh with the current MemStoreBase signature), so I could add it to the constructor but wanted to ensure that there wouldnt be a need to have the same instance work with collections containing embeddings dimensions of different sizes.
5. With regards to the use of pg schemas to delineate collections, open to opinions on that since I know it doesnt match the C# implementation.

Just trying to make sure I understand the expectations so that your team's reviewing experience is as easy as possible. Let me know any thoughts or concerns @alexchaomander
