### ISSUE TITLE
Add metadata as a field in the MemoryRecord class in Python

### ISSUE THREAD

**Issue by cschadewitz** [microsoft/semantic-kernel#1271]
Add metadata as a field in the python memory record class.
This would improve parity between the implementations.

The field would be a dict[str, str | int | bool | list[str]] this would allow for a flexible usage of the field and would mesh well with Pinecone's db record [metadata](https://docs.pinecone.io/docs/metadata-filtering) implementation and could be stored in other dbs as Json or JSONb 

Furthermore, the text, description and other such fields on the python memory record class could be moved to this dict as well similar to the [.net Memory Record class](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel.Abstractions/Memory/MemoryRecord.cs)

**Comment by alexchaomander** [comment]
Good catch! We will add.  This is already in C# so Python needs to catch up

**Comment by cschadewitz** [comment]
I see that you assigned to @awharrison-28 but if youd like I would be happy to work on this along side the pinecone memory store implementation that I have taken over and the postgres memory store implementation that I have all but finished. 

Either way, I'll prep branches for changes against those memory stores to go in after this feature.

**Comment by awharrison-28** [comment]
@cschadewitz thanks for the offer. This is a really quick one to put out, so I'll take care of it asap.

**Comment by awharrison-28** [comment]
@cschadewitz PR is live, please take a look to make sure it covers what you need for Pinecone and Postgres :)

**Comment by cschadewitz** [comment]
@awharrison-28 I'll take a look this evening and let you know if I have any suggestions. Thanks for getting this in place so quickly!

**Comment by cschadewitz** [comment]
@awharrison-28, sorry it took so long for me to get to this but it looks good to me! Thanks again!
