### ISSUE TITLE
add persistence for ChatPromptTemplate

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#1272]
Chat-based services sometimes need to manage individual conversations organized into sessions.
Like ChatGPT below.
![image](https://github.com/microsoft/semantic-kernel/assets/69464062/067bc5d7-fb1b-40bd-8850-b0d98eb59f32)

I don't think there is a feature in the current semantic kernel that allows me to recall a past conversation and immediately start the next input. I guess I have to store the history in JSON or YAML and iterate over the add_*_message.

```python
# Current SK
prompt_template = sk.ChatPromptTemplate(
    "{{$user_input}}", kernel.prompt_template_engine, prompt_config
)

for role, msg in history:
    if role == "user":
        prompt_template.add_user_message(msg)
    ...
```

I think it would be easier to use if the past history was immediately loaded into the _messages of the prompt_template without this replay.

```python
# Feature request
prompt_template = sk.ChatPromptTemplate(
    "{{$user_input}}", kernel.prompt_template_engine, prompt_config
)
prompt_template.load_messages(...)
```

**Comment by 1983Thai** [comment]
AlephZ-ai:main

**Comment by eavanvalkenburg** [comment]
This is really an important one, because this will allow one to create Azure Functions with SK that have history backed, I implemented this myself for Cosmos in Langchain, would love to see that here as well!

**Comment by matthewbolanos** [comment]
This will be supported with our integration with the new Assistants API, so closing out this issue.
