### ISSUE TITLE
KernelHttpServer returns 400 and message access denied (401) code invalid_organization when using AIService.OpenAI

### ISSUE THREAD

**Issue by andreas-deruiter** [microsoft/semantic-kernel#1274]
**Describe the bug**
When configured using an OpenAI key, the KernelHttpServer always returns Access Denied when you call it to invoke a function. 

**To Reproduce**

1. Start the KernelHttpServer
2. Call REST API to invoke a function:

POST http://localhost:7071/api/skills/FunSkill/invoke/Joke HTTP/1.1
x-ms-sk-completion-backend: 1
x-ms-sk-completion-endpoint: 
x-ms-sk-completion-key: YOUR_API__KEY
x-ms-sk-completion-model: text-davinci-003

{"value":"clippy","inputs":[{"key":"style","value":"Bill & Ted"}]}

This returns:

HTTP/1.1 400 Bad Request
Connection: close
Date: Tue, 30 May 2023 13:07:28 GMT
Server: Kestrel
Transfer-Encoding: chunked

Access denied: The request is not authorized, HTTP status: 401 - Detail: 
Status: 401 (Unauthorized)
ErrorCode: invalid_organization

Content:
{
    "error": {
        "message": "",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_organization"
    }
}

Headers:
Date: Tue, 30 May 2023 13:07:29 GMT
Connection: keep-alive
Vary: REDACTED
X-Request-ID: REDACTED
Strict-Transport-Security: REDACTED
CF-Cache-Status: REDACTED
Server: cloudflare
CF-RAY: REDACTED
Alt-Svc: REDACTED
Content-Type: application/json; charset=utf-8
Content-Length: 151

**Expected behavior**
Expected behavior would be that the function would return:

HTTP/1.1 200 OK
Connection: close
Content-Type: application/json; charset=utf-8
Date: Tue, 30 May 2023 13:10:50 GMT
Server: Kestrel
Transfer-Encoding: chunked

{
  "value": "\nQ: What did Bill and Ted say when Clippy asked if it could help them with their history report?\nA: \u0022Be excellent to each other!\u0022",
  "state": [
    {
      "key": "INPUT",
      "value": "\nQ: What did Bill and Ted say when Clippy asked if it could help them with their history report?\nA: \u0022Be excellent to each other!\u0022"
    },
    {
      "key": "style",
      "value": "Bill \u0026 Ted"
    }
  ]
}

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**
The problem is caused by a bug in the _ConfigureKernelBuilder() in SemanticKernalFactory.cs. When the AI service is AIService.OpenAI, the third given parameter when configuring the OpenAI text completion service is the ServiceId, but it should be the Organization ID. The ServiceId should be given as the fourth parameter.

**Comment by craigomatic** [comment]
Thank you, fixing now...

**Comment by craigomatic** [comment]
This should now be fixed with PR #1279 - could you please verify @andreas-deruiter ?

**Comment by craigomatic** [comment]
Closing as I believe this was verified resolved in related issue #1303
