### ISSUE TITLE
Kernel DI bug:  HTTP status: 404

### ISSUE THREAD

**Issue by gpww** [microsoft/semantic-kernel#1329]
**Describe the bug**
something wrong with DI of  SemanticKernel builder  WithOpenAIChatCompletionService

1.clone https://github.com/jimbobbennett/console-gpt
2. upgate Microsoft.SemanticKernel to 0.13.277.1-preview or higher 
3. you can get this error:  Invalid request: The request is not valid, HTTP status: 404
4. copilot chat sample app has the same problem

replace the following code can fix this problem temporarily：
    services.AddSingleton<IKernel>(serviceProvider => Kernel.Builder
       .WithOpenAIChatCompletionService(openAIOptions.ChatModel, openAIOptions.Key)
       .WithOpenAIChatCompletionService(openAIOptions.TextModel, openAIOptions.Key)
       .Build());

to:

IKernel kernel = Kernel.Builder
        .WithOpenAIChatCompletionService(openAIOptions.ChatModel, openAIOptions.Key)
        .WithOpenAITextCompletionService(openAIOptions.TextModel, openAIOptions.Key)
        .Build();

    ConsoleGPTService._semanticKernel= kernel;//微软源码有bug，临时方案

**Comment by nhandangt** [comment]
@gpww Where is this file that we should change? Can I have a path or file name, please?

**Comment by nacharya1** [comment]
@gpww thanks for raising this. We searched and couldnt find this reference. If you are able to see this persisting please respond and we will take another look. We are closing this as no repo.
