### ISSUE TITLE
Unused variables in ActionPlanner.CreatePlanAsync

### ISSUE THREAD

**Issue by xbotter** [microsoft/semantic-kernel#1332]
I am trying to understand the principle of ActionPlanner through the source code, but I found that some of the statements in the source code seem to have no effect.

**L124 & L133-L134 in the following code snippet.**
https://github.com/microsoft/semantic-kernel/blob/6a270273ee6a2bc27baaa9c8157416b7c10716a7/dotnet/src/Extensions/Planning.ActionPlanner/ActionPlanner.cs#L124-L134

**Comment by craigomatic** [comment]
@lemillermicrosoft looks like maybe some remnants of a prior implementation that could be removed?

@xbotter feel free to submit a PR cleaning this up

**Comment by lemillermicrosoft** [comment]
Agreed, I think this could be cleaned up. cc @dluc
