### ISSUE TITLE
Bad random responses from GPT-3

### ISSUE THREAD

**Issue by securigy** [microsoft/semantic-kernel#1337]
I was following examples on this page, despite that I already successfully implemented and launched 2 desktop products based on OpenAI API:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/README.md

I pasted the provided code into a simple WinForms app, with some cosmetic modifications, where the prompt is provided by a user instead of hardcoded prompt:

When I run, I get the following results - see screenshots. It is bazaar... the results both from Azure OpenAI and from OpenAI are really random and have nothing to do with prompt... Either SemanticKernel is not ready for the show time, or the provided example is coded incorrectly...

Any ideas?

The code:

```csharp
private async void PromptSummatyRibbonBtn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            using (Log.VerboseCall())
            {
                SimplePromptForm form = new SimplePromptForm();
                if (form.ShowDialog() == DialogResult.OK)
                {
                    try
                    {
                        RichEditCtrl.Text = "";

                        var builder = new KernelBuilder();

                        if (form.Azure == true)
                        {
                            builder.WithAzureTextCompletionService(
                                     "text-davinci-003",                  // Azure OpenAI Deployment Name
                                     "https://azuresemantickernel.openai.azure.com/", //"https://contoso.openai.azure.com/", // Azure OpenAI Endpoint
                                     "a1bcd2e345678f9xxxxx");      // Azure OpenAI Key
                        }
                        else
                        {
                            // Alternative using OpenAI
                            builder.WithOpenAITextCompletionService(
                                     "text-davinci-003",               // OpenAI Model name
                                     "sk-AB1c234d56e789xxxxx");     // OpenAI API Key
                        }

                        var kernel = builder.Build();

                        // One line TLDR with the fewest words.";
                        string prompt = form.Prompt;

                        var summarize = kernel.CreateSemanticFunction(prompt);

                        string text1 = @"1st Law of Thermodynamics - Energy cannot be created or destroyed.\n" +
                               "2nd Law of Thermodynamics - For a spontaneous process, the entropy of the universe increases\n" +
                               "3rd Law of Thermodynamics - A perfect crystal at zero Kelvin has zero entropy.";

                        string text2 = @"1. An object at rest remains at rest, and an object in motion remains in motion at constant speed and in a straight line unless acted on by an unbalanced force.\n" +
                                "2. The acceleration of an object depends on the mass of the object and the amount of force applied.\n" +
                                "3. Whenever one object exerts a force on another object, the second object exerts an equal and opposite on the first.";

                        SKContext summary1 = await summarize.InvokeAsync(text1);
                        
                        SKContext summary2 = await summarize.InvokeAsync(text2);

                        RichEditCtrl.Text = String.Format("Prompt: {0}\n\nSummary1: {1}\n\nSummary2: {2}", prompt, summary1.Result, summary2.Result);

                        // Expected Output:
                        //   Energy conserved, entropy increases, zero entropy at 0K.
                        //   Objects move in response to forces.
                    }
                    catch (Exception ex)
                    {
                        Log.Verbose(ex);
                    }
                }
            }
        }
```

**Expected behavior**
Energy conserved, entropy increases, zero entropy at 0K.
Objects move in response to forces.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/22898824/37a68880-783f-4d17-a522-ad55b9c0243f)
![image](https://github.com/microsoft/semantic-kernel/assets/22898824/469c81bb-efba-4022-bd39-f74a687f249f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IDE: VS2022
 - NuGet Package Version 0.15.2305

**Additional context**

**Comment by lukasz-appstream** [comment]
Weird behavior, but:
 - based on "Prompt" value on the screenshots it's not  `"One line TLDR with the fewest words."` but `"Summarize the following..."`, Semantic Kernel doesn't influence that in your code.
 -  regardless if it's `One line TLDR with the fewest words` or the other one - it's missing `input` variable, in the example you've mentioned there is
 ```
 var prompt = @"{{$input}}
One line TLDR with the fewest words.";
```

**Comment by securigy** [comment]
strange... but I guess the CreateSemanticFunction requires this kind of form of input...
 I asked chatGPT what this line means...
`var prompt = @"{{$input}}
One line TLDR with the fewest words.";`

and it says:

**_In .NET 7, the line you provided initializes a string variable named prompt using a verbatim string literal.

The @"{{$input}} denotes a verbatim string literal, which means that escape sequences (such as \n for a new line) are ignored, and the string is interpreted as-is. In this case, it appears to be a placeholder for the value of $input.

The rest of the string, "One line TLDR with the fewest words.", is a regular string that follows the verbatim string. It represents the actual content of the prompt variable and describes a one-line summary (TLDR) with a few words.

Overall, the line seems to be defining a string variable that combines a placeholder ({{$input}}) and a brief description in .NET 7._**

Anyway, noting special, but that's what expected by the sematic function...
I tried it and it worked...

**Comment by lchmielewski** [comment]
@securigy I'm not sure why you're asking ChatGPT about Semantic Kernel syntax. It is a newer concept and not within the knowledge of the model.

If you're interested in learning how to write templated prompts, I recommend Semantic Kernel docs:

https://learn.microsoft.com/en-us/semantic-kernel/prompt-engineering/your-first-prompt#writing-a-more-powerful-templated-prompt

**Comment by alexchaomander** [comment]
@securigy I'd also recommend reading this doc too to help you understand the prompt templating language!

https://github.com/microsoft/semantic-kernel/blob/main/docs/PROMPT_TEMPLATE_LANGUAGE.md

**Comment by alexchaomander** [comment]
Closing this for now, but let us know if you still run into this issue @securigy !
