### ISSUE TITLE
Remote Extension Host Fails on Codespaces off of main

### ISSUE THREAD

**Issue by gblikas** [microsoft/semantic-kernel#1347]
**Describe the bug**

(As of `main` branch, today) After 5 minutes activity, the error “Remote Extension host terminated unexpectedly 3 times within the last 5 minutes.” Is displayed. 

**To Reproduce**
1. Go to “Code”
2. Click on “Codespaces”
3. Click on “Create codespace on main”
4. wait till codespace is created
5. Wait 5 minutes - edit files, whatever
6. See error 

**Expected behavior**

This error seems to mess with codespace setup. While not immediately clear, it looks like it interferes with the notebooks; they are not loaded properly.

**Desktop (please complete the following information):**
 - OS: codespaces
 - IDE: VS Code (via Codespace)
 - As per devcontainer folder 
 - (Current hash) 134906aa3926e2f6515ec9e2bb9e5a32246b1650

**Comment by craigomatic** [comment]
Following up on this as we got a different, potentially related report over at #1891 - are you still seeing the same issue with the current main @gblikas?

**Comment by gblikas** [comment]
> Following up on this as we got a different, potentially related report over at #1891 - are you still seeing the same issue with the current main @gblikas?

@craigomatic nope! Doesn’t mean it’s fixed tho, just not reproducible.

**Comment by lemillermicrosoft** [comment]
@alliscode anyone on your team that is familiar with our codespaces setup that could confirm whether this is an issue?

**Comment by gblikas** [comment]
@lemillermicrosoft played around with the codespace settings a bit and it seems to be related to the size/level of the codespace. For instance, upgrading to a 8-core seems to have resolved the issue _sometimes_, but using the default 2-core causes the issue more often.

**Comment by matthewbolanos** [comment]
Closing this issue since it was created several months back. Please reopen if it's still an issue.
