### ISSUE TITLE
Make MaxTokens optional

### ISSUE THREAD

**Issue by anthonypuppo** [microsoft/semantic-kernel#1362]
Some LLM's, such as ChatGPT, default to using the remaining context window if the maximum amount of tokens is not included in the request. For such models it would be beneficial to not pass the max tokens argument every time if the intention is to get the most elaborate response possible. This is of course possible by calculating remaining tokens, but is a pain (and performance hit) to constantly calculate the remaining tokens (assuming you even get it right).

**Comment by alexchaomander** [comment]
Thanks for making the PR! And for the great discussion about this during Office Hours!
