### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by vnesterovsky** [microsoft/semantic-kernel#1374]
While dealing with Hebrew in SK we found that it often switches to English.

Such problem happens for many skills.
We found that it's enough to add a sentence to prompts to answer in Hebrew to address it.
Unfortunately, in many cases it means we need to clone existing skills to do the customization.

I suggest introducing a generic customization, something like a variable, that can be substituted into skills to provide orders like (but not limited to) language preference.

**Comment by stephentoub** [comment]
I wonder if this should be tied in with https://github.com/microsoft/semantic-kernel/issues/1226#issuecomment-1564221001.  Basically have a CultureInfo on the SKContext, with that CultureInfo defaulting to CultureInfo.CurrentCulture, but overridable on a case by case basis.  Functions can then refer to that culture for a variety of things, including in this case language information.

**Comment by lemillermicrosoft** [comment]
Closing as I believe this was resolved with #1519.
