### ISSUE TITLE
Renaming config.json to skconfig.json ?

### ISSUE THREAD

**Issue by agoncal** [microsoft/semantic-kernel#1375]
I was having a look at the samples and didn't first undersstand what `config.json` was supposed to configure. Then I realized that is was used to configure SK. The file usually seats next to an `skprompt.txt` file. If `config.json` is only meant to configure SK, why not renaming the file to `skconfig.json` (reminds the `tsconfig.json` for configuring TS)?

WDYT?

**Comment by alexchaomander** [comment]
I think it's a sensible idea! Thanks for bringing it up. The team can definitely consider it!

@shawncal @dluc @hathind-ms for visibility

**Comment by shawncal** [comment]
Hi @agoncal, good suggestion! We're evaluating a few new prompt formats right now, and there should be a good alternative available soon.

We don't intend to change this now, but rather to supercede it with other OSS prompt formats. Closing.
