### ISSUE TITLE
chat-summary-webapp-react appears to allow any model name and suggests text-davinci-003, but that model does not work

### ISSUE THREAD

**Issue by mattmazzola** [microsoft/semantic-kernel#1382]
**Describe the bug**

When going through [chat-summary-webapp-react](https://learn.microsoft.com/en-us/semantic-kernel/samples-and-solutions/simple-chat-summary)
The documentation says "enter in the model" which makes it seem like any model would work.

It also suggests "text-davinci-003" as the form element placeholder value.

However, `text-davinci-003` does not work

**To Reproduce**
1. Start local Azure Function Server `func start --csharp`
2. Start Chat Application `yarn start`
3. Enter OpenAI/Azure OpenAI keys
4. Click "Save"

**Actual Behavior**

Alert error, see screenshots

**Expected behavior**

- Placeholder should suggest a chat based model such as `gpt-3.5-turbo`

**Screenshots**

## Azure OpenAI

![image](https://github.com/microsoft/semantic-kernel/assets/2856501/7676a0b1-6290-4d0a-b303-3e1facd66e31)

## OpenAI

![image](https://github.com/microsoft/semantic-kernel/assets/2856501/ab6f7d07-0df5-417d-88e5-c50eb782bebf)

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: VS Code
 - NuGet Package Version (Using KernelHttpServer so kind of not applicable, but )
 ```
    <PackageReference Include="Microsoft.SemanticKernel" Version="0.15.230531.5-preview" />
    <PackageReference Include="Microsoft.SemanticKernel.Skills.Document" Version="0.15.230531.5-preview" />
    <PackageReference Include="Microsoft.SemanticKernel.Skills.MsGraph" Version="0.15.230531.5-preview" />
    <PackageReference Include="Microsoft.SemanticKernel.Skills.Web" Version="0.15.230531.5-preview" />
```

**Additional context**

**Comment by craigomatic** [comment]
Fair suggestion, I'm not sure that the list APIs we call give back details on the type of completion endpoint (chat/text). 

This is what it looks like for Azure OpenAI: https://learn.microsoft.com/en-us/rest/api/cognitiveservices/azureopenaistable/models/list?tabs=HTTP#model

OpenAI seems even less informative: https://platform.openai.com/docs/api-reference/models/list

There was similar feedback posted over here: https://github.com/microsoft/semantic-kernel/issues/752#issuecomment-1572765677

@teresaqhoang any thoughts?

**Comment by mattmazzola** [comment]
> do you want to use a text completion model with the sample apps or is a text completion model good enough?

In my opinion, because the behavior of the models is very similar then choosing text or chat does not matter much. I think the goal of the learner is to understand Semantic Kernels behavior not the model's behavior.

I think a factor that could influence the decision is [pricing](https://openai.com/pricing#language-models). 

**I think gpt-3.5-turbo is 10x cheaper than davinci. Given developers have to use their own keys and services for learning I could see argument made that ALL defaults across all samples calling completion should be switched to gpt-3.5-turbo to save developers money.**

This avoids the user wondering why some samples use normal completion endpoint / text-davinci-003 and others use chat/completion endpoint with gpt-3.5-turbo. They may think it has something to do with SK, but really it was stale code likely duplicated

model | price
--- | ---
gpt-3.5-turbo | $0.002 / 1K tokens
text-davinci-003 | $0.0200 / 1K tokens

**Comment by teresaqhoang** [comment]
Totally, that's exactly why we switched from TextCompletion models to ChatCompletion models. 

I merged a PR: https://github.com/microsoft/semantic-kernel/pull/1448/files to update our samples to point to ChatCompletion models, so you should see the latest changes if you pull main. Thanks for catching this bug! Feel free to re-open if the issue persists.
