### ISSUE TITLE
Unable to load shared library 'libSkiaSharp' or one of its dependencies in the DALL-E notebook

### ISSUE THREAD

**Issue by hsm207** [microsoft/semantic-kernel#1384]
**Describe the bug**
running:

```
// Create a semantic function that generate a random image description.
var genImgDescription = kernel.CreateSemanticFunction(
    "Think about an artificial object correlated to number {{$input}}. " +
    "Describe the image with one detailed sentence. The description cannot contain numbers.", 
    maxTokens: 256, temperature: 1);

var random = new Random().Next(0, 200);
var imageDescription = await genImgDescription.InvokeAsync($"{random}");

// Use DALL-E 2 to generate an image. OpenAI in this case returns a URL (though you can ask to return a base64 image)
var imageUrl = await dallE.GenerateImageAsync(imageDescription.Result.Trim(), 512, 512);

await SkiaUtils.ShowImage(imageUrl, 512, 512);
```

throws:

> Error: System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
> ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
> /home/vscode/.nuget/packages/microsoft.dotnet-interactive/1.0.430602/tools/net7.0/any/runtimes/linux-x64/native/libSkiaSharp.so: cannot open shared object file: No such file or directory
> /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libSkiaSharp.so: cannot open shared object file: No such file or directory
> /home/vscode/.nuget/packages/skiasharp/2.88.3/lib/net6.0/libSkiaSharp.so: cannot open shared object file: No such file or directory
> /home/vscode/.nuget/packages/microsoft.dotnet-interactive/1.0.430602/tools/net7.0/any/runtimes/linux-x64/native/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
> /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
> /home/vscode/.nuget/packages/skiasharp/2.88.3/lib/net6.0/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
> /home/vscode/.nuget/packages/microsoft.dotnet-interactive/1.0.430602/tools/net7.0/any/runtimes/linux-x64/native/libSkiaSharp: cannot open shared object file: No such file or directory
> /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libSkiaSharp: cannot open shared object file: No such file or directory
> /home/vscode/.nuget/packages/skiasharp/2.88.3/lib/net6.0/libSkiaSharp: cannot open shared object file: No such file or directory
> /home/vscode/.nuget/packages/microsoft.dotnet-interactive/1.0.430602/tools/net7.0/any/runtimes/linux-x64/native/liblibSkiaSharp: cannot open shared object file: No such file or directory
> /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/liblibSkiaSharp: cannot open shared object file: No such file or directory
> /home/vscode/.nuget/packages/skiasharp/2.88.3/lib/net6.0/liblibSkiaSharp: cannot open shared object file: No such file or directory
> 
> at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
> at SkiaSharp.SKImageInfo..cctor() in D:\a\1\s\binding\Binding\SKImageInfo.cs:line 46
> --- End of inner exception stack trace ---
> at SkiaSharp.SKImageInfo..ctor(Int32 width, Int32 height) in D:\a\1\s\binding\Binding\SKImageInfo.cs:line 68
> at Submission#5.SkiaUtils.ShowImage(String url, Int32 width, Int32 height)
> at Submission#8.<<Initialize>>d__0.MoveNext()
> --- End of stack trace from previous location ---
> at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

**To Reproduce**
Open the [07-DALL-E-2.ipynb](https://github.com/microsoft/semantic-kernel/blob/main/samples/notebooks/dotnet/07-DALL-E-2.ipynb) and run each cell until before the "Let's play a guessing" game section

**Expected behavior**
A random image should appear

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Debian 11
 - IDE: VS Code
 - NuGet Package Version: 6.6.0.61

**Additional context**

> .NET SDK:
>  Version:   7.0.302
>  Commit:    990cf98a27
> 
> Runtime Environment:
>  OS Name:     debian
>  OS Version:  11
>  OS Platform: Linux
>  RID:         debian.11-x64
>  Base Path:   /usr/share/dotnet/sdk/7.0.302/
> 
> Host:
>   Version:      7.0.5
>   Architecture: x64
>   Commit:       8042d61b17
> 
> .NET SDKs installed:
>   7.0.302 [/usr/share/dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> 
> Other architectures found:
>   None
> 
> Environment variables:
>   DOTNET_ROOT       [/usr/local/dotnet/current]
> 
> global.json file:
>   /workspaces/semantic-kernel/global.json
> 
> Learn more:
>   https://aka.ms/dotnet/info
> 
> Download .NET:
>   https://aka.ms/dotnet/download

**Comment by alexchaomander** [comment]
Thanks for bringing this up!

@dluc can you take a look at this?

**Comment by dluc** [comment]
I can repro the issue on Ubuntu and I tried adding `SkiaSharp.NativeAssets.Linux`, unfortunately that doesn't fix the problem. 

Test 1

```
#r "nuget: Microsoft.SemanticKernel, 0.21.230828.2-preview"
#r "nuget: SkiaSharp.NativeAssets.Linux, 2.88.6"
```

Test 2
```
#r "nuget: Microsoft.SemanticKernel, 0.21.230828.2-preview"
#r "nuget: SkiaSharp, 2.88.6"
#r "nuget: SkiaSharp.NativeAssets.Linux, 2.88.6"
```

It's an issue with SkiaSharp on Linux and I don't think there's anything we can do about it. Given that it affects only the documentation, I don't think this is a bug, and I would close the issue as a known limitation of .NET notebooks on Linux. If someone could suggest alternative libraries to render images we could give test them.

**Comment by dluc** [comment]
FYI I tried also copying the missing .so file where the code is looking for, and ended up with more errors about libc version.  Using Ubuntu22LTS
