### ISSUE TITLE
Allow external tokenizer when splitting text

### ISSUE THREAD

**Issue by gramhagen** [microsoft/semantic-kernel#1387]
I'd like to use tiktoken or HuggingFace tokenizer when splitting text using the python text chunker.

Example usage:
```
from semantic_kernel.text.text_chunker import split_plaintext_lines
import tiktoken

encoding = tiktoken.get_encoding('cl100k_base')
token_counter = lambda x: len(encoding.encode(x))
lines = split_plaintext_lines(text=text, max_token_per_line=256, token_counter=token_counter)
```

Related Issues:
#1240 
#478

**Comment by alexchaomander** [comment]
Thanks for adding the PR! We'll definitely take a look. We definitely need to add more text chunking capabilities in SK

**Comment by matthewbolanos** [comment]
Closing since this was created several months ago. Please reopen if you still want the enhancement.
