### ISSUE TITLE
Redis Connector failing when initialized as in sample

### ISSUE THREAD

**Issue by HSven1611** [microsoft/semantic-kernel#1404]
**Describe the bug**
When using the newly introduces redis connector as described in the quickstart it crashes when accessing the memory.

_This is just a documentation issue as far as I see it._

**To Reproduce**
1. initialize redis connector as in sample
2. try to access memory

> Exception:
>  Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter[0]
>       [OnTurnError] **unhandled error : Cannot access a disposed object.**
>       Object name: 'DELL5B70FK3(SE.Redis-v2.6.96.30123)'.
>       System.ObjectDisposedException: Cannot access a disposed object.
>       Object name: 'DELL5B70FK3(SE.Redis-v2.6.96.30123)'.
>          at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor`1 processor, Object 
> [...]

I think it eventually disposes something the redis memory connector needs to work. In my application there is some time between initialization and usage as I'm waiting for some user input.

**Fix**
remove using before Connection multiplexer. 

old:
```cs
using ConnectionMultiplexer connectionMultiplexer = await ConnectionMultiplexer.ConnectAsync("localhost:6379");
```

new:
```cs
ConnectionMultiplexer connectionMultiplexer = await ConnectionMultiplexer.ConnectAsync("localhost:6379");
```

**Expected behavior**
Should not crash and access the memory.

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: VS2022
 - NuGet Package: Microsoft.SemanticKernel.Connectors.Memory.Redis 
 - NuGet Package version: 0.15.230609.2-preview

**Additional context**
Sample code in quick Start 2. seems broken
[Redis Connector quickstart](https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.Memory.Redis)

**Comment by JadynWong** [comment]
The document simply demonstrates how to use it quickly, similar to [Example47_Redis.cs](https://github.com/microsoft/semantic-kernel/blob/main/samples/dotnet/kernel-syntax-examples/Example47_Redis.cs). `ConnectionMultiplexer` should typically be used as a singleton in an application, as a best practice. It is recommended to dispose the instance after use. Additionally, when writing this README.md, I instinctively believed that users should first understand how to use `ConnectionMultiplexer`.

https://github.com/microsoft/semantic-kernel/blob/e4781e51d4e8fea5f6beb85823272e305183372c/samples/dotnet/kernel-syntax-examples/Example47_Redis.cs#L12-L77
