### ISSUE TITLE
When following the tutorial, naming the python file openai.py makes a circular import 

### ISSUE THREAD

**Issue by Fiwex** [microsoft/semantic-kernel#1406]
**Describe the bug**
When following : https://github.com/microsoft/semantic-kernel/blob/e4781e51d4e8fea5f6beb85823272e305183372c/python/README.md if the python file is named openai.py, it will cause a : ImportError: cannot import name 'OpenAITextCompletion' from partially initialized module 'semantic_kernel.connectors.ai.open_ai' (most likely due to a circular import) (path/venv/lib/python3.11/site-packages/semantic_kernel/connectors/ai/open_ai/__init__.py).

**To Reproduce**
Follow https://github.com/microsoft/semantic-kernel/blob/e4781e51d4e8fea5f6beb85823272e305183372c/python/README.md
Name the python file openai.py

**Expected behavior**
Working without circular import.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
Not yet

**Comment by alexchaomander** [comment]
Thanks for calling this out! We'll put it on our backlog to investigate

**Comment by nacharya1** [comment]
@mkarle - can you please look into this?

**Comment by mkarle** [comment]
Try naming the file something other than `openai.py`.  The same thing would happen if you named your file `logging.py` or any other top-level module that semantic kernel uses. Trying to see if there's a way to avoid this but I haven't found anything.

**Comment by mkarle** [comment]
There doesn't seem to be a way aound it. You'll just need to rename the file.
