### ISSUE TITLE
Guardrails for C# https://github.com/ShreyaR/guardrails

### ISSUE THREAD

**Issue by itmilos** [microsoft/semantic-kernel#1409]
[

Are we going to have something like https://github.com/ShreyaR/guardrails for c# ?

](https://github.com/ShreyaR/guardrails)

**Comment by alexchaomander** [comment]
I think it's very important! Something similar to guardrails will be very important for production deployments!

**Comment by nacharya1** [comment]
@itmilos  thanks for raising this. We are currently exploring https://github.com/microsoft/typechat to solve for this but will keep this in consideration.

**Comment by nagarajmarisamy** [comment]
Is there any update in this request?
