### ISSUE TITLE
GitHub Repo Q&A Bot - FunctionNotFound: Function `textmemoryskill.recall` not found

### ISSUE THREAD

**Issue by kboro** [microsoft/semantic-kernel#141]
**Describe the bug**

GitHub Repo Q&A Bot Sample app returns following error:

Something went wrong. Please try again.
Details: {Bad Request => FunctionNotFound: Function `textmemoryskill.recall` not found}

**To Reproduce**

start API function
start github-qna-webapp-react

In Application:

Provide GIT repo details
Ask question in Bot Window

**Expected behavior**
Bot responds without error

**Screenshots**

<img width="476" alt="image" src="https://user-images.githubusercontent.com/28050787/226957865-8c873183-da1e-4bb1-9f7e-5fcf46435b87.png">

**Desktop (please complete the following information):**
 - OS: Windows11
 - IDE: VS Code

**Comment by craigomatic** [comment]
Thank you for the report, taking a look...

**Comment by TaoChenOSU** [comment]
Thanks for your report! 
Could you please confirm that you have selected a valid embedding model in the Setup section?

**Comment by kboro** [comment]
Hello, regarding embedding model I found that I couldnt choose anything from drop-down list (greyedout) but I could add to .env file. Is there  any specific model I should define?

Im using Azure OpenAI

**Comment by TaoChenOSU** [comment]
Do you have an embedding mode deployed on your endpoint?

**Comment by kboro** [comment]
That was it - missing embedding model on my endpoint

Thank you @TaoChenOSU !
