### ISSUE TITLE
Keep user intent in current language for Azure Search query

### ISSUE THREAD

**Issue by methodidacte** [microsoft/semantic-kernel#1410]
I am working with a french imported document, using Azure Search for memory. I can see in the prompt that the document isn't used for the bot's answer. Looking at the search query, I discover that the user intent is translated in english and the queryLanguage is en-US (default value of the API).

?api-version=2021-04-30-Preview&searchMode=Any&search=User intent: According to best practices, is it always necessary to use the administrator account?&queryType=Semantic&queryLanguage=en-us&$top=100

Could it be possible to keep the intent in the current language spoken by the bot and adapt the queryLanguage parameter ? I try to find where this search query is build but don't find it in the code.

**Comment by methodidacte** [comment]
![image](https://github.com/microsoft/semantic-kernel/assets/17197079/1c296b8b-0c07-4325-9e52-f3c788270b0e)

The parameter is in the file https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.Memory.AzureCognitiveSearch/AzureCognitiveSearchMemory.cs. I don't know how to identify the correct culture from the chat and change the value dynamicly.

**Comment by JadynWong** [comment]
Based on PR #1174, I think this package(semantic query) may be deprecated, and eventually implemented by embedding vector search.

**Comment by alexchaomander** [comment]
@dluc can you comment on whether the semantic search package is going to be replaced with Azure Cognitive Search?

**Comment by nacharya1** [comment]
@dluc - can you provide some more details to help on this question.

**Comment by lemillermicrosoft** [comment]
Latest code does not hardcode en-us https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.Memory.AzureCognitiveSearch/AzureCognitiveSearchMemoryStore.cs
