### ISSUE TITLE
Plugins: Integration with MS Viva Sales

### ISSUE THREAD

**Issue by itmilos** [microsoft/semantic-kernel#1415]
Connector to MS Viva Sales and skills for it's capabilities.  ref. https://www.microsoft.com/en-ww/microsoft-viva/sales

**Comment by itmilos** [comment]
I am currently working on developing an AI Agent that aims to assist operators in their work. Integrating MS Viva meeting summaries into MS Teams has the potential to significantly enhance their productivity. Additionally, in the future, I plan to create a plugin that enables background recording, similar to the functionality provided by (https://www.bloks.app/).

**Comment by alexchaomander** [comment]
Thanks for the additional context! I've added it to our backlog!

**Comment by matthewbolanos** [comment]
Closing this issue since it was created several months ago. Please create a new issue if you'd still like this integration.
