### ISSUE TITLE
SharePoint List Connector

### ISSUE THREAD

**Issue by glenchao** [microsoft/semantic-kernel#142]
Add a new SharePoint List Connector.  Happy to contribute a PR for this :)

Example feature SharePoint List Connector would unlock: 
"Create a SharePoint List of action items with these fields: <field1>, <field2>, <field3>, from the last email I got from xxxx"

**Comment by alexchaomander** [comment]
Thanks for sharing this idea @glenchao! We'd be happy to receive a PR from you!

**Comment by evchaki** [comment]
@glenchao looking forward to your PR.  I will close this for now.
