### ISSUE TITLE
DevContainer - missing required .NET 7.0 SDK for Polyglot notebook extension

### ISSUE THREAD

**Issue by pjirsa** [microsoft/semantic-kernel#1421]
**Describe the bug**
*.ipynb files opened with Polyglot notebook extension throw an error. This extension now requires .NET 7.0 in order to work. It appears that .NET 7.0 SDK is not installed to dev container.

**To Reproduce**
1. Open repo in Codespace or local dev container.
2. Load any *.ipynb file.
3. Poloyglot notebook extension displays an error message stating that .NET 7.0 is now required.

**Expected behavior**
.NET 7.0 should be installed automatically to dev container and extensions should work normally.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/2207109/12ed4771-1450-4753-bc73-7ff7a64c50b5)

**Comment by alexchaomander** [comment]
Thanks for adding this PR to fix this! We'll take a look!
