### ISSUE TITLE
Support Tesseract / OCR in Copilot Example

### ISSUE THREAD

**Issue by davearlin** [microsoft/semantic-kernel#1440]
Thanks to the community for these great examples. I added some support for rasterized image document importing in the Copilot example. Would be happy to submit a PR for this.  The only question I have is whether or not to add the fairly large (~20MB) english training data file required or to simply add a readme.md with instructions on adding it to the "tessdata" folder that is now part of the CopilotChatWebApi project.

**Comment by alexchaomander** [comment]
@davearlin Would love to see a PR! I think rather than including it in the main repo, could you include documentation in a README for how to get download it?

**Comment by glahaye** [comment]
PR made it in.
