### ISSUE TITLE
Example41_HttpClientUsage  it is invalid 

### ISSUE THREAD

**Issue by fanheshe** [microsoft/semantic-kernel#1445]
**Describe the bug**

**To Reproduce**
`
 Example41_HttpClientUsage.Run();
 Console.Read();

 OpenAIClientBase
 this.Client = new OpenAIClient(apiKey, options);
`
This will explain that the previously modified httpclient has been overwritten again

![image](https://github.com/microsoft/semantic-kernel/assets/46515201/44bb8a23-dc7a-4415-b67a-eb00ee5c0409)

No matter how I modify it continues to work

**Comment by JadynWong** [comment]
I think the `BaseAddress` may not affect the request connection. The completed URI path is already included in the constructed HttpRequestMessage.

https://github.com/Azure/azure-sdk-for-net/blob/c6253cc7c7d1d9d9e69a5983b10491b3960ef29a/sdk/openai/Azure.AI.OpenAI/src/Custom/OpenAIClient.cs#L576-L609

**Comment by fanheshe** [comment]
ofqdD55EymvjbtzFektzjS45KzNw

**Comment by fanheshe** [comment]
How can I implement a custom httpclient

**Comment by JadynWong** [comment]
I guess you want to use some proxy openai services? If so, here are some of my suggestions.

1. Implement your own `ITextCompletion` or `IChatCompletion`. [Example16_CustomLLM.cs](https://github.com/microsoft/semantic-kernel/blob/main/samples/dotnet/kernel-syntax-examples/Example16_CustomLLM.cs)
2. Go to the `https://github.com/Azure/azure-sdk-for-net` repository to raise this issue and inquire if the Azure team will support these proxy services from OpenAI. If they do support [this](https://github.com/Azure/azure-sdk-for-net/blob/c6253cc7c7d1d9d9e69a5983b10491b3960ef29a/sdk/openai/Azure.AI.OpenAI/src/Custom/OpenAIClient.cs#L123-L134), I think it should be easy.  (It's better)
3. A quick temporary solution with `HttpClientHttpMessageHandler`
```csharp
serviceCollection.AddTransient<MyHttpMessageHandler>();
//Registration of a named HttpClient.
serviceCollection.AddHttpClient("test-client")
    .ConfigurePrimaryHttpMessageHandler<MyHttpMessageHandler>();
    
serviceCollection.AddTransient<IKernel>((sp) =>
{
    var factory = sp.GetRequiredService<IHttpClientFactory>();

    var kernel = Kernel.Builder
        .WithOpenAIChatCompletionService("<model-id>", "<api-key>", httpClient: factory.CreateClient("test-client"))
        .Build();

    return kernel;
});
    
private class MyHttpMessageHandler : HttpClientHandler
{
    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        if (request.RequestUri != null && request.RequestUri.Host.Equals("api.openai.com", StringComparison.OrdinalIgnoreCase))
        {
            request.RequestUri = new Uri($"https://openai.yourproxy.com{request.RequestUri.PathAndQuery}");
        }

        return base.SendAsync(request, cancellationToken);
    }
}
```

**Comment by UlyssesWu** [comment]
> 2. Go to the https://github.com/Azure/azure-sdk-for-net repository to raise [this](https://github.com/Azure/azure-sdk-for-net/blob/c6253cc7c7d1d9d9e69a5983b10491b3960ef29a/sdk/openai/Azure.AI.OpenAI/src/Custom/OpenAIClient.cs#L123-L134) issue and inquire if the Azure team will support these proxy services from OpenAI. If they do support this, I think it should be easy. (It's better)

This can aslo be done with some Reflection magic😉 like this (pseudocode)

``` csharp
dynamic c = new OpenAIChatCompletion(...); //find a way to get or create this
c.Client._endpoint = new Uri(yourEndpoint);
c..Client._tokenCredential = DelegatedTokenCredential.Create(...);
```
