### ISSUE TITLE
Suggestion to add sequential plan executor to library

### ISSUE THREAD

**Issue by mattmazzola** [microsoft/semantic-kernel#1451]
I was learning about the planner capabilities by going through the [Book creator sample](https://learn.microsoft.com/en-us/semantic-kernel/samples-and-solutions/book-creator) and the [Example12_SequentialPlanner](https://github.com/microsoft/semantic-kernel/blob/main/samples/dotnet/kernel-syntax-examples/Example12_SequentialPlanner.cs#L194-L234)

I thought it was odd that this type of code

https://github.com/microsoft/semantic-kernel/blob/f31c58bf7a0541405c1b98a0ec329e0ef9a2f093/samples/dotnet/kernel-syntax-examples/Example12_SequentialPlanner.cs#L194-L234

was not part of the library. I expected these common use cases to be abstracted.

I actually expected the first `PoetrySamplesAsync` which uses a different method of running the plan to run it to completion, but from what I saw it only ran the first step of the plan.

https://github.com/microsoft/semantic-kernel/blob/f31c58bf7a0541405c1b98a0ec329e0ef9a2f093/samples/dotnet/kernel-syntax-examples/Example12_SequentialPlanner.cs#L55

The other EmailSamplesAsync and BookSamplesAsync using a different method of calling `ExecutePlanAsync`

**ExecutePlanAsync mixes stopwatch timing, step counting, and printing of log messages which can distract from the core purpose of the example which is to teach developers how to sequentially execute a plan.**

**I would propose the library has a built in sequential execution implemented as a generator** like so 

```csharp
async IAsyncEnumerable<(ContextVariables, Plan, int)> ExecutePlanSequentiallyAsync(
    IKernel kernel,
    Plan plan,
    string input = "")
{
    // for each plan step, invoke step and yield state
    for (int stepIndex = 0; plan.HasNextStep; stepIndex = +1)
    {
        if (string.IsNullOrEmpty(input))
        {
            plan = await kernel.StepAsync(plan);
        }
        else
        {
            plan = await kernel.StepAsync(input, plan);
        }

        yield return (plan.State, plan.Steps.ElementAt(stepIndex), stepIndex);
    }
}
```

You can then separate the SK responsibility of plan execution from the Application responsibilities (in the case of example) such as writing logs before and after, or breaking after desired step max

```csharp
PrintStep("Execute Plan:");
var planExecutor = ExecutePlanSequentiallyAsync(kernel, plan);
await foreach (var (state, step, stepIndex) in planExecutor)
{
    PrintStep($"Step {stepIndex + 1}: {plan.Name} {step.Name}");
    Console.WriteLine(state.ToString());
    Console.WriteLine();
}

PrintStep($"Plan Complete");
```

What do you think about an approach like this?

**Comment by lemillermicrosoft** [comment]
There are multiple ways to invoke a plan right now.

// Run Entire Plan
`plan.InvokeAsync(context) // context or input`
`kernel.RunAsync(plan) // context or input optional`

// Step through a Plan
`plan.InvokeNextStepAsync(context)`
`plan.RunNextStepAsync(kernel, context)`
`kernel.StepAsync(plan) //context or input optional`

PoetrySamplesAsync should run the entire plan. 

```
======== Sequential Planner - Create and Execute Poetry Plan ========
Original plan:
 Goal: Write a poem about John Doe, then translate it into Italian.

 Steps:
  - WriterSkill.ShortPoem INPUT='John Doe is a friendly guy who likes to help others and make them smile. He enjoys reading books and playing games and always tries to be kind and polite.'
  - WriterSkill.Translate INPUT='' language='Italian'
Result:
- John Doe è un tipo simpatico che ama dare una mano
Legge e gioca e saluta tutti quelli che può
Ma a volte si mette nei guai per essere troppo gentile e dolce
Come quando ha offerto di massaggiare i piedi di uno sconosciuto sulla strada
```
