### ISSUE TITLE
Python: basic planner generated plan sometimes contains generated text that is not json de-serializable.

### ISSUE THREAD

**Issue by awharrison-28** [microsoft/semantic-kernel#1469]
The python basic planner sometimes generates text that is not json de-serializable. This manifests as additional text beyond the generated plan. 

Ex:

```
{
    "input": "Valentine's Day Date Ideas",
    "subtasks": [
        {"function": "WriterSkill.Brainstorm"},
        {"function": "WriterSkill.Translate", "args": {"language": "French"}},
        {"function": "TextSkill.uppercase"}
    ]
}
additional text....
```

Some proposals for resolving this issue are:

1. Add stop sequences to ensure that once the json is rendered, additional text generation is halted. This has a downside where it is not guaranteed that the new text will appear in a certain form or pattern.
2. Created a regex to extract the json from the generated text. This is a little more wasteful of tokens, but better guarantees that the json plan will be captured without any additional information. This will also require that the kernel be dependent on the `regex` pip package as `re` does not support recursive matching.

**Comment by alexchaomander** [comment]
This might be a good way to show off the new functions capability from OpenAI.

https://github.com/microsoft/semantic-kernel/issues/1450

If someone is using a ChatCompletion model, the first call to generate the plan can be done by providing ChatCompletion the create_plan "function". According to their docs, it's a more reliable way to create the expected JSON output.
