### ISSUE TITLE
Need a simple starting sample

### ISSUE THREAD

**Issue by VenkateshSrini** [microsoft/semantic-kernel#1473]
Hi All,

I'm starting with Semantic Kernel. I need a simple example to start. Can you please point me to one. I need it .NET.

Regards

**Comment by alexchaomander** [comment]
You can take a look at the samples in our repo!

We have console apps that show off the syntax: https://github.com/microsoft/semantic-kernel/tree/main/samples/dotnet/kernel-syntax-examples

We have Jupyter notebooks: https://github.com/microsoft/semantic-kernel/tree/main/samples/notebooks/dotnet
