### ISSUE TITLE
Unable to gather the deployment name from the env file

### ISSUE THREAD

**Issue by diptesh-bose** [microsoft/semantic-kernel#1474]
**Describe the bug**

**To Reproduce**
1. Go to 'samples/notebooks/python/00-getting-started.ipynb'

**Expected behavior**

**Screenshots**
AssertionError: Azure OpenAI deployment name not found in .env file

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: Jupyter Notebook
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**
It would be good if a working example is made available. (with some hypothetical data)

**Comment by darkKnightsrvani** [comment]
Can you make sure if you have the following settings in your local .env file ?
Note: the repo, by default , comes with [.env.example](https://github.com/microsoft/semantic-kernel/blob/main/samples/notebooks/python/.env.example) and you have to create a copy of it on your local and rename it to .env  and set the below values .

AZURE_OPENAI_API_KEY="<OPEN API KEY>"
AZURE_OPENAI_ENDPOINT="https://<AZURE OPENAPI ENDPOINT>"
AZURE_OPENAI_DEPLOYMENT_NAME="<AZURE OPEN API DEPLOYMENT NAME>"

**Comment by nacharya1** [comment]
@diptesh-bose - this has now been resolved. Please let us know if you are still experiencing issues.

**Comment by KSHAMIN** [comment]
> @diptesh-bose - this has now been resolved. Please let us know if you are still experiencing issues.

I am getting this error: `AttributeError: module 'semantic_kernel' has no attribute 'azure_openai_settings_from_dot_env'`
Are there any new changes made in the library?

**Comment by carrickcheah** [comment]
**Is it mean ,azure_openai_settings_from_dot_env is not listed, indicating it does not exist in semantic_kernel module?
How to Solve? :-)**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], [line 1](vscode-notebook-cell:?execution_count=7&line=1)
----> [1](vscode-notebook-cell:?execution_count=7&line=1) deployment, api_key, endpoint = sk.azure_openai_settings_from_dot_env()

AttributeError: module 'semantic_kernel' has no attribute 'azure_openai_settings_from_dot_env'

======================================================
['Kernel', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'connectors', 'const', 'contents', 'exceptions', 'filters', 'functions', 'kernel', 'kernel_pydantic', 'kernel_types', 'prompt_template', 'reliability', 'schema', 'services', 'template_engine', 'utils']
