### ISSUE TITLE
Passing output of step to next in SequentialChain 

### ISSUE THREAD

**Issue by gopitk** [microsoft/semantic-kernel#1476]
I want to rewrite a Langchain SimpleSequentialChain (in Python) where I am looking at a chain of semantic functions and call them sequentially. The output of the 1st function needs to be passed as input context in the second function. 

How do I do this? Here is my code snippet (tried to use the $input as well as some other name for the context vars in the prompts below):

```
# prompt template 1
first_prompt = "What is the best name to describe \
    a company that makes {{ $product }}?"

# Semantic Function 1
func_one = kernel.create_semantic_function(first_prompt, temperature=0.9)

# prompt template 2
second_prompt = "Write a 20 words description for the following \
    company:{{ $company }}"

# Semantic Function 2
func_two = kernel.create_semantic_function(second_prompt, temperature=0.9)

# Now call functions in order
answer = await kernel.run_async(func_one, func_two, input_str="Queen Size Sheet Set")
print(answer)
```

The code is working and getting some output but likely not passing output of 1st function to the second. Also what is the procedure to debug/trace how these functions are called, the variables passed and what is sent to the LLM (gpt3.5 turbo chat completions in this case).

**Comment by lemillermicrosoft** [comment]
What is the output? Why do you think the output is not passing from the first to the second? What happens if you name both of the variables in your `*_prompt` as `{{ $input }}`?

**Comment by gopitk** [comment]
Output is :

A multinational technology company known for its innovative hardware and software products, including smartphones, laptops, and operating systems.

On langchain I get a description that looks more what is approp for the product. 

Regal Linens is a premium provider of high-quality linens for hotels, restaurants, and home use, offering a wide range of colors and sizes.'

No major difference when I use $input as the prompt var. That is one reason I wanted some kind of trace to see what is being sent to the LLM in the 2nd step.

**Comment by gopitk** [comment]
Hi @lemillermicrosoft  - I retried with $input and now seem to get proper result. I was reasonably sure I had tried it. Anyway it does seem like if I use $input in both the prompt it seems to be chaining properly. I do suggest to add this info to the documents to use $input as I dont believe I could find it without going into the library source. 

I also have a more general SequentialChain I am trying to rewrite it for SK where there is a need to define output context variable so that I can pass things between elements in the chain more flexibly (like pass output of 1st stage to 2,3,4. And pass output of stage 3 to Stage 5 in the sequential chain). Is this supported in Semantic Kernel? If so, can you please share a python sample? In LC it is done by specifying a output_key in the LLMChain.

**Comment by lemillermicrosoft** [comment]
Here are some links of where this is documented:

https://github.com/microsoft/semantic-kernel/blob/main/docs/PROMPT_TEMPLATE_LANGUAGE.md#function-calls

https://github.com/microsoft/semantic-kernel/blob/e30229a0a572d2f429d5630b30a57a2d4cc2636b/samples/notebooks/python/02-running-prompts-from-file.ipynb#LL43C4-L43C4

**Comment by gopitk** [comment]
Closing this issue. Thanks for the inputs. 

Summary: 

SimpleSequentialChain : Works fine when using $input as the variable
SequentialChain (where you need more flexibility in chaining stages): Needs a workaround currently to copy the step output to a different context variable name in a Native function.
