### ISSUE TITLE
OpenAI functions

### ISSUE THREAD

**Issue by wayne-o** [microsoft/semantic-kernel#1480]
They aren't available in AZ OpenAi yet but the extended context plus the ability to train it to use functions seems to have some overlap (WRT the latter) - I am just wondering what changes can be made to SK to adopt this new capability - could it potentially simplify things? Or are the features not quite the same? 

Cheers

w

**Comment by craigomatic** [comment]
We're working on it: #1450

**Comment by lemillermicrosoft** [comment]
Closing as duplicate.
