### ISSUE TITLE
Sequential Planner: Plan parsing failed: Invalid plan: Failed to parse plan xml.

### ISSUE THREAD

**Issue by mtechvance** [microsoft/semantic-kernel#1483]
**Describe the bug**
When using the sequential planner with an open api plugin, the payload attribute value in the plan xml is not properly escaped. It uses '/' escapes instead of the xml accepted &quot; escape. I overrode the sequential planner default prompt and added one additional line to it to have it properly escape the quotes.

'2. Quotes inside of xml attributes should be escaped with '&quot;'.'

**To Reproduce**
1. Import an OpenAPI plugin that has a post request with a payload
2. Create a SequentialPlanner
3. Create a plan with a goal that will call the open api plugin function that has a payload
4. Error should occur on Run or Invoke

**Expected behavior**
Plan parsing succeeds

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: Visual Studio 2022
 - 0.15.230609.2-preview

**Additional context**

- I started with the OpenAPI doc found [here](https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/search/7.1/search.json) for Dev Ops search 
- An example of valid function XML would be this
`<plan>
    <function.CodeSearch.codesearchresults_post organization="MyOrg"
                                                project="Proj"
                                                api_version="7.1-preview.1"
                                                server_url="https://almsearch.dev.azure.com/"
                                                payload="{&quot;searchText&quot;:&quot;test&quot;,&quot;$top&quot;:3,&quot;filters&quot;:{&quot;Repository/Project&quot;:[&quot;Proj&quot;],&quot;Repository/Repository&quot;:[&quot;Repo&quot;]}}"
                                                content_type="application/json"
                                                appendToResult="RESULT__TOP_THREE_RESULTS" />
</plan>`
- Truncated call stack
Plan parsing failed: Invalid plan: Failed to parse plan xml.[2023-06-14T16:14:49.628Z] Executed 'Functions.PerformCodeSearch' (Failed, Id=c1362f61-e771-4075-971d-6c39adf551b4, Duration=12217ms)
[2023-06-14T16:15:38.997Z] System.Private.CoreLib: Exception while executing function: Functions.PerformCodeSearch. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Invalid plan: Plan parsing error, invalid XML)
[2023-06-14T16:15:38.997Z] Result: Plan parsing failed: Invalid plan: Failed to parse plan xml.
Exception: Microsoft.SemanticKernel.Planning.PlanningException: Invalid plan: Failed to parse plan xml.
[2023-06-14T16:15:38.998Z]  ---> Microsoft.SemanticKernel.Planning.PlanningException: Invalid plan: Plan parsing error, invalid XML
[2023-06-14T16:15:38.998Z]  ---> System.Xml.XmlException: 'searchText' is an unexpected token. Expecting whitespace. Line 2, position 177.

**Comment by lemillermicrosoft** [comment]
Can you share the result of the prompt? You can capture the rendered result in debug logs, see `Rendered prompt:` and then run manually to see the xml (Sorry, I thought we were logging that already but I don't think so).

**Comment by mtechvance** [comment]
@lemillermicrosoft 
This was the original code
```
var planner = new SequentialPlanner(kernel);
var plan = await planner.CreatePlanAsync(goal);
var result = await kernel.RunAsync(contextVariables, plan);
```
I added this to get the rendered prompt
```
var goal = $"Search the code for '{inputs.SearchText}' and return the top three results by listing the file name and path. The project is 'MyProject', the organization is 'MyOrg', and the repository is 'MyRepo'.";
var promptTemplateEngine = new PromptTemplateEngine();
var renderedPrompt = await promptTemplateEngine.RenderAsync(goal, kernel.CreateNewContext());
logger.LogInformation(renderedPrompt);
```
Which output this 
"Search the code for 'AminoStartup' and return the top three results by listing the file name and path. The project is 'MyProject', the organization is 'MyOrg', and the repository is 'MyRepo'."

Is that what you're asking for? Sorry if there was any confusion on my part.

**Comment by lemillermicrosoft** [comment]
Not quite, if you search the repository, you'll see the kernel will emit a debug log with the rendered prompt for any semantic function call. `this._log.LogDebug("Rendered prompt: {0}", result);`

So, whatever logger you give to the kernel, enable the Debug level and you will see the rendered prompt when `SequentialPlanner` does `var planResult = await this._functionFlowFunction.InvokeAsync(this._context).ConfigureAwait(false);`

**Comment by mtechvance** [comment]
I am using this [open api doc](https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/search/7.1/search.json). I only had to change operation ids in it to remove white spaces. Let me know if this was not what you are asking for.

Here is the rendered prompt

> Create an XML plan step by step, to satisfy the goal given.
> To create a plan, follow these steps:
> 0. The plan should be as short as possible.
> 1. From a <goal> create a <plan> as a series of <functions>.
> 2. Before using any function in a plan, check that it is present in the most recent [AVAILABLE FUNCTIONS] list. If it is not, do not use it. Do not assume that any function that was previously defined or used in another plan or in [EXAMPLES] is automatically available or compatible with the current plan.
> 3. Only use functions that are required for the given goal.
> 4. A function has a single 'input' and a single 'output' which are both strings and not objects.
> 5. The 'output' from each function is automatically passed as 'input' to the subsequent <function>.
> 6. 'input' does not need to be specified if it consumes the 'output' of the previous function.
> 7. To save an 'output' from a <function>, to pass into a future <function>, use <function.{FunctionName} ... setContextVariable: "<UNIQUE_VARIABLE_KEY>"/>
> 8. To save an 'output' from a <function>, to return as part of a plan result, use <function.{FunctionName} ... appendToResult: "RESULT__<UNIQUE_RESULT_KEY>"/>
> 9. Append an "END" XML comment at the end of the plan.
> 
> [EXAMPLES]
> [AVAILABLE FUNCTIONS]
> 
>   EmailConnector.LookupContactEmail:
>     description: looks up the a contact and retrieves their email address
>     inputs:
>     - input: the name to look up
> 
>   EmailConnector.EmailTo:
>     description: email the input text to a recipient
>     inputs:
>     - input: the text to email
>     - recipient: the recipient's email address. Multiple addresses may be included if separated by ';'.
> 
>   LanguageHelpers.TranslateTo:
>     description: translate the input to another language
>     inputs:
>     - input: the text to translate
>     - translate_to_language: the language to translate to
> 
>   WriterSkill.Summarize:
>     description: summarize input text
>     inputs:
>     - input: the text to summarize
> 
> [END AVAILABLE FUNCTIONS]
> 
> <goal>Summarize the input, then translate to japanese and email it to Martin</goal>
> <plan>
>   <function.WriterSkill.Summarize/>
>   <function.LanguageHelpers.TranslateTo translate_to_language="Japanese" setContextVariable="TRANSLATED_TEXT" />
>   <function.EmailConnector.LookupContactEmail input="Martin" setContextVariable="CONTACT_RESULT" />
>   <function.EmailConnector.EmailTo input="$TRANSLATED_TEXT" recipient="$CONTACT_RESULT"/>
> </plan>
> 
> [AVAILABLE FUNCTIONS]
> 
>   _GLOBAL_FUNCTIONS_.GetEmailAddress:
>     description: Gets email address for given contact
>     inputs:
>     - input: the name to look up
> 
>   _GLOBAL_FUNCTIONS_.SendEmail:
>     description: email the input text to a recipient
>     inputs:
>     - input: the text to email
>     - recipient: the recipient's email address. Multiple addresses may be included if separated by ';'.
> 
>   AuthorAbility.Summarize:
>     description: summarizes the input text
>     inputs:
>     - input: the text to summarize
> 
>   Magician.TranslateTo:
>     description: translate the input to another language
>     inputs:
>     - input: the text to translate
>     - translate_to_language: the language to translate to
> 
> [END AVAILABLE FUNCTIONS]
> 
> <goal>Summarize an input, translate to french, and e-mail to John Doe</goal>
> <plan>
>     <function.AuthorAbility.Summarize/>
>     <function.Magician.TranslateTo translate_to_language="French" setContextVariable="TRANSLATED_SUMMARY"/>
>     <function._GLOBAL_FUNCTIONS_.GetEmailAddress input="John Doe" setContextVariable="EMAIL_ADDRESS"/>
>     <function._GLOBAL_FUNCTIONS_.SendEmail input="$TRANSLATED_SUMMARY" recipient="$EMAIL_ADDRESS"/>
> </plan>
> 
> [AVAILABLE FUNCTIONS]
> 
>   _GLOBAL_FUNCTIONS_.NovelOutline :
>     description: Outlines the input text as if it were a novel
>     inputs:
>     - input: the title of the novel to outline
>     - chapterCount: the number of chapters to outline
> 
>   Emailer.EmailTo:
>     description: email the input text to a recipient
>     inputs:
>     - input: the text to email
>     - recipient: the recipient's email address. Multiple addresses may be included if separated by ';'.
> 
>   Everything.Summarize:
>     description: summarize input text
>     inputs:
>     - input: the text to summarize
> 
> [END AVAILABLE FUNCTIONS]
> 
> <goal>Create an outline for a children's book with 3 chapters about a group of kids in a club and then summarize it.</goal>
> <plan>
>   <function._GLOBAL_FUNCTIONS_.NovelOutline input="A group of kids in a club called 'The Thinking Caps' that solve mysteries and puzzles using their creativity and logic." chapterCount="3" />
>   <function.Everything.Summarize/>
> </plan>
> 
> [END EXAMPLES]
> 
> [AVAILABLE FUNCTIONS]
> 
> CodeSearch.codesearchresults_post:
>   description: Provides a set of results for the search text.
>   inputs:
>     - organization: The name of the Azure DevOps organization. (required)
>   - project: Project ID or project name (required)
>   - api_version: Version of the API to use.  This should be set to '7.1-preview.1' to use this version of the api. (required)
>   - server_url: server-url (default value: https://almsearch.dev.azure.com/)
>   - payload: The Code Search Request. (required)
>   - content_type: Content type of REST API request body.
> 
> [END AVAILABLE FUNCTIONS]
> 
> <goal>Search the code for 'MySearchText' and return the top three results by listing the file name and path. The project is 'MyProject', the organization is 'MyOrg', and the repository is 'MyRepo'.</goal>

**Comment by lemillermicrosoft** [comment]
Thanks this help. Can you confirm which model you are using?

**Comment by mtechvance** [comment]
The chat completion service is gpt-4 and the text embedding generation service is text-embedding-ada-002.

**Comment by lemillermicrosoft** [comment]
```
[Theory]
[InlineData(@"<plan> <function.CodeSearch.codesearchresults_post organization=""MyOrg"" project=""Proj"" api_version=""7.1-preview.1"" server_url=""https://almsearch.dev.azure.com/"" payload=""{&quot;searchText&quot;:&quot;test&quot;,&quot;$top&quot;:3,&quot;filters&quot;:{&quot;Repository/Project&quot;:[&quot;Proj&quot;],&quot;Repository/Repository&quot;:[&quot;Repo&quot;]}}"" content_type=""application/json"" appendToResult=""RESULT__TOP_THREE_RESULTS"" /> </plan>")]
[InlineData("<plan>\n  <function.CodeSearch.codesearchresults_post organization=\"MyOrg\" project=\"MyProject\" api_version=\"7.1-preview.1\" payload=\"{&quot;searchText&quot;: &quot;MySearchText&quot;, &quot;filters&quot;: {&quot;pathFilters&quot;: [&quot;MyRepo&quot;]} }\" setContextVariable=\"SEARCH_RESULTS\"/>\n</plan><!-- END -->")]
[InlineData("<plan>\n  <function.CodeSearch.codesearchresults_post organization=\"MyOrg\" project=\"MyProject\" api_version=\"7.1-preview.1\" server_url=\"https://almsearch.dev.azure.com/\" payload=\"{ 'searchText': 'MySearchText', 'filters': { 'Project': ['MyProject'], 'Repository': ['MyRepo'] }, 'top': 3, 'skip': 0 }\" content_type=\"application/json\" appendToResult=\"RESULT__TOP_THREE_RESULTS\" />\n</plan><!-- END -->")]
public void CanCreatePlanWithOpenApiPlugin(string planText)
{
    // Arrange
    var functions = new List<(string name, string skillName, string description, bool isSemantic, string result)>()
    {
        ("codesearchresults_post", "CodeSearch", "Echo an input", true, "Mock Echo Result"),
    };
    this.CreateKernelAndFunctionCreateMocks(functions, out var kernel);

    // Act
    var plan = planText.ToPlanFromXml(string.Empty, kernel.CreateNewContext());

    // Assert
    Assert.NotNull(plan);
    Assert.Equal(1, plan.Steps.Count);
    Assert.Equal("CodeSearch", plan.Steps[0].SkillName);
    Assert.Equal("codesearchresults_post", plan.Steps[0].Name);
}
```

Thanks, good to know. I'm still having trouble getting a repro. Based on your description, it seems like the 3rd test in this theory is the scenario you are having issue with. Thoughts?

**Comment by mtechvance** [comment]
I will see if I can get a small repro project up and running first thing in the morning.

**Comment by lemillermicrosoft** [comment]
Thanks for the repo app. Yeah, this error sounds like #159 which has a PR published now for improvements. If you have any more issue with the previous error please re-open or file a new issue. Will close this one as duplicate for now, otherwise.
