### ISSUE TITLE
SequentialPlanner + OpenAPI Plugin;

### ISSUE THREAD

**Issue by mtechvance** [microsoft/semantic-kernel#1485]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by lemillermicrosoft** [comment]
Need more context, thinking it's related to the other two already open.
