### ISSUE TITLE
SequentialPlanner + OpenAPI Plugin: Variable keys are blanked out in payload

### ISSUE THREAD

**Issue by mtechvance** [microsoft/semantic-kernel#1487]
**Describe the bug**
Variable names that start with a $ in an OpenAPI document specifically in the payload have their names set to an empty string before being submitted as an HttpRequest. This causes the HttpRequest to fail. 

**To Reproduce**
1. Import an OpenAPI plugin that contains variable names that start with $ such as '$top'
2. Create a plan using a sequential planner
3. Execute the plan
4. Http call fails

**Expected behavior**
The variable names should not be set to empty string

**Screenshots**

- Here you can see the variable is set in the plan step parameters
![Variable is set](https://github.com/microsoft/semantic-kernel/assets/95925478/f7f2ed4a-f988-4b28-86f9-7b204b6cc4e5)
- Here you can see the variable name has been blanked out. This is inside of the ExecuteAsync method in the private method RegisterRestApiFunction of the KernelOpenApiExtensions
![Variable name removed](https://github.com/microsoft/semantic-kernel/assets/95925478/ae6519e4-4f50-465d-8068-0a811dd05018)

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: Visual Studio 2022
 - 0.15.230609.2-preview

**Additional context**

- I started with the OpenAPI doc found [here](https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/search/7.1/search.json) for Dev Ops search. It uses properties such as $top and $orderby in the code search http call

**Comment by lemillermicrosoft** [comment]
@mtechvance -- published a PR to improve this. Would appreciate confirmation this would resolve your issue.
