### ISSUE TITLE
Python: Review Examples in Learning Documentation

### ISSUE THREAD

**Issue by awharrison-28** [microsoft/semantic-kernel#1490]
The following files need review:

- [x] [Quick start guide](https://review.learn.microsoft.com/en-us/semantic-kernel/get-started/quick-start-guide/?toc=%2Fsemantic-kernel%2Ftoc.json&branch=matthew-plugins-updates&tabs=python)

- [x] [Supported languages](https://review.learn.microsoft.com/en-us/semantic-kernel/get-started/supported-languages?branch=matthew-plugins-updates)
- [x] [Overview of kernel](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/?branch=matthew-plugins-updates&tabs=python)
- [x] [Understanding plugins](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/plugins?branch=matthew-plugins-updates&tabs=python)
- [x] [Creating semantic functions](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/semantic-functions?branch=matthew-plugins-updates&tabs=python)

The following files need code samples:
- [ ] [Creating native functions](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/native-functions?branch=matthew-plugins-updates&tabs=python)
- [ ] [Chaining functions](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/chaining-functions?branch=matthew-plugins-updates&tabs=python)
- [ ] [Planner](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/planner?branch=matthew-plugins-updates&tabs=Csharp)
- [ ] [out-of-the-box plugins](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/out-of-the-box-plugins?branch=matthew-plugins-updates&tabs=Csharp%2Cpython)

**Comment by nacharya1** [comment]
Closing as document now have python code samples
