### ISSUE TITLE
Bug(may be): about running Sample of dotNET notebooks by using Azure OpenAI

### ISSUE THREAD

**Issue by AwesomeYuer** [microsoft/semantic-kernel#1499]
**Describe the bug**
when I running the cell of ` step 4 Load and Run a Skill` in `00-getting-started.ipynb` , got the error as below:
`
Error: Invalid request: The request is not valid, HTTP status: 400
`
the version of Microsoft.SemanticKernel nuget package is: `0.15.230531.5-preview`

at the runtime I try to use `fiddler` to capture the traffic, but capture nothing.

**To Reproduce**
1. config `settings.json` for use `azure` when run all the cells in `0-AI-settings.ipynb`
2. run the cells in `00-getting-started.ipynb` one by one
3. after run the cell of ` step 4 Load and Run a Skill` , see error:
`
Error: Invalid request: The request is not valid, HTTP status: 400
`

**Expected behavior**
running succeed 
I remember  that an old version of semantic-kernel can running  succeed, such as `Microsoft.SemanticKernel, 0.12.207.1-preview`

**Screenshots**

![image](https://github.com/microsoft/semantic-kernel/assets/1026479/945d6d66-92e9-4b17-a946-2158ab5876dd)

![image](https://github.com/microsoft/semantic-kernel/assets/1026479/967aacc6-80dd-42fc-b2ca-399dc744e72f)

![image](https://github.com/microsoft/semantic-kernel/assets/1026479/711bb80f-335d-491f-ace2-3179c8d9a441)

**Desktop (please complete the following information):**
 - OS: Windows 11 OR WSL2
 - IDE: VSCode
 - NuGet Package Version : Microsoft.SemanticKernel, 0.15.230531.5-preview

**Additional context**

**Comment by lemillermicrosoft** [comment]
It looks like you are using an embeddings model but the samples are written to use a text completion model. Can you re-open if changing that to a text completion model still doesn't work?

**Comment by AwesomeYuer** [comment]
@lemillermicrosoft
Thanks for your feedback.

I changed to use `text completion` ,  it works properly!

Would you help to answer another question for me as below:

https://github.com/microsoft/semantic-kernel/discussions/1513
