### ISSUE TITLE
Semantic Kernel Postgres memory Error

### ISSUE THREAD

**Issue by flatluna** [microsoft/semantic-kernel#1504]
**Describe the bug**
 Get this error: "Method 'Create' in type 'Pgvector.Npgsql.VectorTypeHandlerResolverFactory' from assembly 'Pgvector, Version=0.1.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation."

**To Reproduce**
1) Install version 0.15.230609.2 for Microsoft.SemanticKernel and Microsoft.SemanticKernel.Connectors.Memory.Postgres NUGET packages
2) Create postgres db in Azure and pass connectionString

 string connectionString = "Server=xxxxxxpostgres.database.azure.com;Database=db;Port=5432;User Id=YYY;Password={};Ssl Mode=VerifyFull;";

3) Run this .NET statement 
using PostgresMemoryStore memoryStore = await PostgresMemoryStore.ConnectAsync(connectionString, vectorSize: 1536);

**Expected behavior**
Should get the PostgresMemoryStore-  memoryStore . Refer to this sample from this REPO

**samples/dotnet/kernel-syntax-examples/Example39_Postgres.cs**

**Screenshots** 

**Additional context**

**Comment by JadynWong** [comment]
I have not encountered this error. I see that you are using it based on azure postgres. I'm sorry I don't have the "Azure Database for PostgreSQL" resource available. But I see that their documentation was recently updated to support the pgvector extension. , and the syntax to enable it is the same. Note that it is necessary to use "Azure Database for PostgreSQL - Flexible Server" to support pgvector. 

https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-use-pgvector

Would you like to try testing it in docker first to see if it works?

---
If you are using "Azure Database for PostgreSQL" it may not be relevant to your problem.

For what it's worth, I tested it based on the free "Azure Cosmos DB for PostgreSQL" and it worked fine except for a difference in the syntax for enabling the pgvector extension, after executing it manually. 

`SELECT CREATE_EXTENSION('vector');`  or `CREATE EXTENSION vector;`

I need a way to figure out exactly which statement to execute to enable the pgvector extension.

https://learn.microsoft.com/en-us/azure/cosmos-db/postgresql/howto-use-pgvector

**Comment by flatluna** [comment]
> 

With the latest version using Server=vectordb.postgres.database.azure.com the problem disappeared. However, now I am getting this error 

Could not load type 'System.Data.Common.DbDataSource' from assembly 'Npgsql, Version=7.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.

I am going to try also with the Cosmos Postgres.

Thank you,

**Comment by JadynWong** [comment]
I'm guessing it might be an assembly conflict issue. Check your build log for any warnings?

**Comment by matthewbolanos** [comment]
Closing this issue since it's been awhile without getting the assembly conflict issue information
