### ISSUE TITLE
GetNearestMatchesAsync() in dotnet CosmosDB connector doesn't leverage CosmosDB's built-in vector search

### ISSUE THREAD

**Issue by 1yefuwang1** [microsoft/semantic-kernel#1514]
The [GetNearestMatchesAsync()](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.Memory.CosmosDB/CosmosMemoryStore.cs#L256) in  dotnet CosmosDB connector uses brute-force approach to calculate similarity instead of using CosmosDB's built-in [vector search](https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/vector-search).
It would be an enhancement to leverage built-in vector search performance-wise.

**Comment by lukasz-appstream** [comment]
I was also thinking about it, but vector search is currently available only in Azure CosmosDB for MongoDB. The CosmosDB connector in Semantinc Kernel  relies on native SQL syntax. So, it would be a big decision to commit to CosmosDB for MongoDB just for this feature.

However, I think it's worth considering this enhancement as a separate connector specifically built for CosmosDB for MongoDB. That way, developers can choose the connector based on their needs.

What do you think?

**Comment by lemillermicrosoft** [comment]
Agreed @lukasz-appstream  -- since CosmosDB connector is gone now, closing this issue.
