### ISSUE TITLE
KeyError: 'is_reference' running search on Chroma 

### ISSUE THREAD

**Issue by gopitk** [microsoft/semantic-kernel#1535]
I have an existing persisted Chroma DB populated with data and embeddings (external to this program through a langchain script)

I am have attached this vectorstore to SK to do some Q&A and RAG and can see the collections and records loaded. However when I try to do a semantic search I get the following error:

`KeyError: 'is_reference' `

Code snippet is;

```
from semantic_kernel.connectors.memory.chroma import ChromaMemoryStore
kernel.register_memory_store(memory_store=ChromaMemoryStore(persist_directory="outdoors"))

....

result = await kernel.memory.search_async(collection="lesson", limit=1, min_relevance_score=0.3, query=query)
```
When I register_memory_store I seem to get 1 collection and about 1210 embeddings. However I get an error in search_async. 

There is a large trace. But here is the relevant piece of error 

```
File ~/miniconda3/envs/llmapp/lib/python3.9/site-packages/semantic_kernel/connectors/memory/chroma/utils.py:65, in <listcomp>(.0)
     40     memory_records = [
     41         (
     42             MemoryRecord(
   (...)
     59         )
     60     ]
     61 else:
     62     memory_records = [
     63         (
     64             MemoryRecord(
---> 65                 is_reference=metadata["is_reference"],
     66                 external_source_name=metadata["external_source_name"],
     67                 id=metadata["id"],
     68                 description=metadata["description"],
     69                 text=document,
     70                 embedding=None,
     71                 additional_metadata=metadata["additional_metadata"],
     72                 key=id,
     73                 timestamp=metadata["timestamp"],
     74             )
     75         )
     76         for id, document, metadata in zip(
     77             results["ids"][0],
     78             results["documents"][0],
     79             results["metadatas"][0],
     80         )
     81     ]
     82 return memory_records

KeyError: 'is_reference'
```

Looks like my existing DB may not have some metadata as it was created outside SK. Is this mandatory or is there a way to have this optional and  not look for this metadata?

**Comment by nacharya1** [comment]
@gopitk  - this was resolved with a fix we did, can you confirm if this issue is still persistenting for you?

**Comment by gopitk** [comment]
@nacharya1 - Is there a PR link that fixed this issue?

**Comment by nacharya1** [comment]
@gopitk - checking and closing this issue for now as we believe it was resolved in the later releases.
Let me know if it still persists for you.

**Comment by raibd** [comment]
Hello, I am having this same issue, I already have the latest version.
