### ISSUE TITLE
Prompt Template Language could support comments

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#1536]
- A comment might leave context or direction for a reader or future maintener.
- A comment can be eliminated from the template during processing (prior to context variable substitution)
- Comments might be restricted to line-level
- A potental candidate for comment syntax might be a common comment expression that isn't commonly utilized in prompt engineering: "//"

**Comment by evchaki** [comment]
@crickman - good idea here, adding comments to prompt templates would be ideal

**Comment by crickman** [comment]
@evchaki - Thanks for the triage.  The scope here is sufficiently focused, I can take action.  Will follow-up w/ Shawn, Devis, et al for consensus on comment syntax.  I think we don't want to choose something with possibility of overlapping with semantic formatting.  (I'm not sure if my original suggestion is necessarily sufficient: //)

**Comment by crickman** [comment]
Note to self: Verify an action in light of yaml template strategy.

**Comment by crickman** [comment]
@hario90 - This may align with your current efforts on the yaml template:

[The SDK may need to be adjusted to handle comments, depending on how it extracts values from yaml files.](https://teams.microsoft.com/l/message/19:meeting_MjlhNDI4N2EtY2M3Yi00Nzk0LTkzMTItMjg5YmFlZTcyMjA4@thread.v2/1688748928367?context=%7B%22contextType%22%3A%22chat%22%7D)

**Comment by matthewbolanos** [comment]
This is now supported with Handlebars
