### ISSUE TITLE
RedisMemoryStore : ERR unknown command 'FT.INFO', with args beginning with: 'MyCollection' 

### ISSUE THREAD

**Issue by KapteinBabbalas** [microsoft/semantic-kernel#1537]
When trying to use RedisMemoryStore to upload memories I get ERR unknown command 'FT.INFO', with args beginning with: 'MyCollection'  

**To Reproduce**
I have tested this with Azure Cache and locally with Redis running in docker.
`
        Config.GetSection("Redis").Bind(redisConfig);
        IDatabase redis = BuildRedis(redisConfig);

        var kernel = new KernelBuilder()
            .WithAzureTextCompletionService(deploymentName: kernelSettings.TextCompletionDeployment,
                endpoint: kernelSettings.Endpoint, apiKey: kernelSettings.ApiKey)
            //Memory
            .WithAzureTextEmbeddingGenerationService(kernelSettings.TextEmbeddingDeployment, kernelSettings.Endpoint,
                kernelSettings.ApiKey)
            .WithMemoryStorage(new RedisMemoryStore(redis, 1536))
            //Chat
            .WithAzureChatCompletionService(kernelSettings.ChatCompletionDeployment, kernelSettings.Endpoint,
                kernelSettings.ApiKey)
            .Build();`

I get this error:
 StackExchange.Redis.RedisServerException: ERR unknown command 'FT.INFO', with args beginning with: 'MyCollection' 
    at NRedisStack.Auxiliary.ExecuteAsync(IDatabaseAsync db, SerializedCommand command)
   at NRedisStack.SearchCommandsAsync.InfoAsync(RedisValue index)
   at Microsoft.SemanticKernel.Connectors.Memory.Redis.RedisMemoryStore.DoesCollectionExistAsync(String collectionName, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SaveInformationAsync(String collection, String text, String id, String description, String additionalMetadata, CancellationToken cancellationToken)

**Desktop:**
 - OS: Windows
 - IDE: Rider
 - NuGet Package Version : 0.16.230615.1-preview

**Comment by JadynWong** [comment]
Hi, Do you use a local RedisStack or Azure Cache For Redis Bussiness pricing tier?

It requires the RediSearch module. 

https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.Memory.Redis/README.md

https://azuremarketplace.microsoft.com/en-us/marketplace/apps/garantiadata.redis_enterprise_1sp_public_preview?tab=Overview

**Comment by KapteinBabbalas** [comment]
I was testing with a local instance and Azure Cache with Standard pricing.
Will give it another go with enterpize

Thank you for the quick response.
