### ISSUE TITLE
Hooks for logging/replay of skills.

### ISSUE THREAD

**Issue by danpere** [microsoft/semantic-kernel#154]
Since skills can be built out of other skills, I would like to get detailed logging information on what skills get called in the process of running a skill and what values it produced both for understanding what happened and for replay for unit testing skills. For example, given a skill calling out to another skill `expensiveComputation` like
```
The answer is {{expensiveComputation}}. What is the question?
```
I would like to have a way to get a log showing the value return by the native skill `expensiveComputation` (the actual prompt is given to the `ILogger` although it would also be nice to have a structured way to get it). Something like
```json
{
    "skills": {
        "expensiveComputation": "42"
    },
    "prompt": "The answer is 42. What is the question?"
}
```
Although if `expensiveComputation` were a semantic skill with its own nested computations, then maybe there could be further nesting in the log. Furthermore, once this log existed it could be used to mock those skills so the computation wouldn't have to be redone when wanting to test other parts of the system. In addition to avoiding expensive computation, this could be particularly useful if those skills require filesystem or other access that isn't available when testing.

I do not think the specific log format is appropriate to this project. Instead, I was looking for the lowest impact way to adjust the APIs to allow for this functionality to be built in client code. It looks like [`PromptTemplateEngine`](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel/TemplateEngine/PromptTemplateEngine.cs) is where the relevant work is done, but simply putting in my own version without modifying this project doesn't work as it relies on `internal` members of `Block` to perform its computations. One option would be to make those members `public`, but in the interest of limiting new externally visible APIs, I've made [a branch](https://github.com/microsoft/semantic-kernel/compare/main...danpere:semantic-kernel:feature/prompt-template-engine-logging-hooks) which adds `virtual` methods to `PromptTemplateEngine` at the point where it computes the values of the blocks which could be used to either record the values computed or overriding the computation with a different value read from a log (and modifies `KernelBuilder` to make it easier to drop in a different `PromptTemplateEngine` implementation). These extension points could probably be used for other uses I haven't thought of as well.

If this solution is acceptable, I can make a PR, but the contributing guidelines requested I make a feature request to discuss first, and I'm not sure my solution is actually the best way to handle this, anyway.

**Comment by danpere** [comment]
Yes, we have a logger attached and can observe this information is not logged. Looking through the code, I see [a line](https://github.com/microsoft/semantic-kernel/blob/4250bfb8bdf69beb70840060c580c085f7634990/dotnet/src/SemanticKernel/TemplateEngine/Blocks/CodeBlock.cs#L79) that prints the block content to the log, but nothing printing the result of running the blog (just the complete result of filling in the entire template). If the information did appear in the log, then I guess parsing the log would be an option. I guess the replay could probably be done in a generalized way with some reflection magic... Are you suggesting that would be the perferred solution?

**Comment by danpere** [comment]
I coded up the [reflection magic](https://github.com/danpere/semantic-kernel/blob/feature/log-skills/dotnet/src/SemanticKernel.IntegrationTests/TemplateLanguage/ProxySkillTests.cs) version of this. As native skills at that level are dealing with `object`s and not `string`s, some care would be necessary to deal with equality and (de)serialization to actually use that code. This seems quite hacky compared to including support for something along these lines in the library.

**Comment by danpere** [comment]
[Here's a branch](https://github.com/microsoft/semantic-kernel/compare/main...danpere:semantic-kernel:feature/log-skill-invocations) that just adds logging calls and includes a test case demonstrating how to parse the log to build a simple replay solution. This is a lot simpler and less invasive than my other attempts.

**Comment by microsoftShannon** [comment]
@dluc Can you take a look at this issue?

**Comment by danpere** [comment]
Apologies, I discussed this with @dluc outside of this thread. The recently added API `IKernel.RegisterCustomFunction()` which was used in the branch I linked in my previous comment, along with making a custom implementation of `ISKFunction` is sufficient to achieve this goal without further modifications to the SemanticKernel library, so I will close this issue. (Note that the branch I linked actually accidentally uses an `internal` `SKFunction` constructor, but it's straightforward to make a new subtype of `ISKFunction` instead.)

**Comment by intelligentestech** [comment]
@danpere -- can you provide your implementation of the ISKFunction?

**Comment by danpere** [comment]
> @danpere -- can you provide your implementation of the ISKFunction?

Not sure what you're looking for. I believe I've linked all of my code in my previous comments.

**Comment by intelligentestech** [comment]
> 

Sorry, I guess I'm just seeing it. The branch you linked makes modifications to the core SK.

**Comment by danpere** [comment]
Apologies, you're right. It looks like I indeed never posted the final version publicly. Sorry, the code I wrote is Microsoft internal so I can't point to it, but I can probably pull out the relevant bits without too much trouble... but I won't be able to get back to this in the next couple weeks, so the basic idea is that you can use `kernel.Skills.GetFunctionsView()` to enumerate all of the skills and `kernel.RegisterCustomFunction()` to replace any skill with your own implementation which can just delegate its entire implementation to the original `ISKFunction` except whatever you want to change (in this case, intercepting the values for logging/replay).

**Comment by danpere** [comment]
@intelligentestech Actually, I managed to clean it up quickly, here's the code:
https://github.com/microsoft/semantic-kernel/compare/main...danpere:semantic-kernel:feature/log-skill-proxy
