### ISSUE TITLE
Microsoft Guidance integration/implementation

### ISSUE THREAD

**Issue by MithrilMan** [microsoft/semantic-kernel#1541]
Do you plan to integrate your prompt template with the feature implemented in the mirosoft guidance project? https://github.com/microsoft/guidance

Both these project are under the microsoft organization, it would be a pity to waste what you can theoretically achieve with guidance, that's a python native library.
Any plan to do something like that?
I've to say in my project I've currently implemented my own integrations from scratch because C# ecosystem is lackluster in this regard, it has very few low level libraries, but I would be happy to use a library if it implements what I need, and one of these is a prompt template engine like guidance.
Actually I'm experimenting with Fluid/Liquid template but I don't want to reinvent the wheel if there is a chance to reuse something more established and battle tested

Thanks

**Comment by alexchaomander** [comment]
@JTremb Just saw this! Thank you for the initial PR! We definitely would love to work well with Guidance and this can go a long way to making sure the projects complement one another!

@MithrilMan are you primarily using C#?

**Comment by alexchaomander** [comment]
@MithrilMan Appreciate the desire to have more of these great features inside C#! There's a vibrant community there but they often have to sit on the sidelines for all the exciting things happening in ML. SK hopefully helps change that!

In terms of Guidance, I'm not sure where C# fits into their own roadmap. The project was started by a couple of researchers at Microsoft and to their credit, they've gotten some good adoption and interest! From our side, we want to unify as much as we can from these projects into SK so that there is a consistent developer story for those building with AI in their apps.

If there are specific features you'd like to see implemented, please let us know!

**Comment by charleslbryant** [comment]
@alexchaomander [Guidance](https://github.com/microsoft/guidance) allows more expression in prompt template. If I had to call out features after my first look, I would vote for more logic control flow.

For example at any point during execution the language model can be used to generate text (using the {{gen}} command) or make logical control flow decisions (the {{#select}}...{{or}}...{{/select}} command). In SK I can run multiple prompts to simulate {{gen}} in SK and I can maybe mix multiple plugins and C# to get logic control, but Guidance is more elegant in this regard for some use cases and it gives me the ability to better encapsulate my intent as a prompt engineer in a single prompt template. 

Guidance's token healing is interesting. Also, the Guidance section on Agents that can await input was exciting to read about and it generated new ideas in my head. 

Overall, Guidance is Python and I'm ride or die C#, Guidance is not intuitive to me and the syntax is distracting when I'm reading it, but it grew on me and the more I read it the more I wanted it in SK.

Don't get me wrong, I **love** SK, it's my jam, and I realize we are all on a new ride with much to learn, prioritize, and do but from a prompt template perspective Guidance is something I would love to see in SK. I'm a mere mortal amongst you LLM gods, but if I could provide some value in bringing a new prompt template experiences to SK, I would love to be a part of any discussion and work to make it happen.

**Comment by evchaki** [comment]
Closing for now as the PR is closed.

**Comment by MithrilMan** [comment]
@evchaki the PR was unrelated because I was talking about a C# implementation while the PR was for python
