### ISSUE TITLE
When return multiple results in `RecallAsync`, `JsonSerializer.Serialize`'s unicode escape ruins all results with non-ASCII characters

### ISSUE THREAD

**Issue by UlyssesWu** [microsoft/semantic-kernel#1549]
https://github.com/microsoft/semantic-kernel/blob/835761629224277b60cc1453a29860b7de540942/dotnet/src/SemanticKernel/CoreSkills/TextMemorySkill.cs#L123

When `memories` are filled with texts in Chinese or Japanese and `limit > 1`, it returns something like `["\u6211\u73B0\u5728\u5728\u65B0\u52A0\u5761\u751F\u6D3B","\u6211\u8001\u5BB6\u5E7F\u897F"]`

When passing this result to GPT (like the example below), the response quality will be severely degraded. (It may still reply with correct answer sometimes, but not always.)

https://github.com/microsoft/semantic-kernel/blob/835761629224277b60cc1453a29860b7de540942/samples/dotnet/kernel-syntax-examples/Example15_MemorySkill.cs#L82-L94

I was upset but came up with a quick solution: I made a native function like this:
``` csharp
        [SKFunction("convert multiple results to one string")]
        public string ParseResult(string input)
        {
            if (input.StartsWith("["))
            {
                var list = JsonSerializer.Deserialize<List<string>>(input);
                if (list != null) return string.Join("\r\n", list);
            }
            return input;
        }
```

I soon realized that the grammer like this (chained invokes) is not supported in prompt template at all:
```
About me: {{Util.ParseResult {{recall '耗子尾汁，好好反思'}} }}
```
nor is the following (provide multiple arguments for functions in prompt template):
```
 {{recall '😠' limit:2}}
```

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
