### ISSUE TITLE
Hacky workaround to get token usage from chat completions api response

### ISSUE THREAD

**Issue by singhk97** [microsoft/semantic-kernel#1565]
I am trying to get the token usage data from the response of a call to the OpenAI's chat completion api but it doesn't seem possible. Here are the details:

`IChatCompletion.GetChatCompletionsAsync` returns a list of `IChatResult` objects. It represents the response from OpenAI's chat completion API. The issue is that this interface does not have the `ModelResult` property which contains token usage data. Hence, there's no way to get the token usage data when using the chat completion api. In contrast, the `ITextCompletion.GetCompletionsAsync` returns a list of `ITextResult` objects which do contain the `ModelResult` property. 

Looking deeper into the code, it looks like the concrete object type of `IChatResult` which is the internal class `ChatResult` has the `ModelResult` property. So then I was able to cast the `IChatResult` to a `ITextResult` and access that property:

![Screenshot 2023-06-19 174511](https://github.com/microsoft/semantic-kernel/assets/115390646/f35b9bd4-f21c-4cff-8b4c-4b53253263c1)

There should be a simple fix for this.

**Comment by craigomatic** [comment]
@RogerBarreto any thoughts here?

**Comment by RogerBarreto** [comment]
@singhk97, Addressing the well spotted problem.
