### ISSUE TITLE
Allow coreskill:  httpskill  to accept optional headers 

### ISSUE THREAD

**Issue by darkKnightsrvani** [microsoft/semantic-kernel#1567]
File : python/semantic_kernel/core_skills/http_skill.py 
Httpskill currently doesnt allow callers to add additional headers . For instance , if the user wants to pass bearer token to the post call , 
user should be able to pass the bearer token via context variable to the httpskill.

If this is an acceptable feature , I am happy to make the change.

```[tasklist]
### Tasks
```

**Comment by darkKnightsrvani** [comment]
Working on the PR now .

**Comment by nacharya1** [comment]
@darkKnightsrvani - wondering if you have any progress on this? We would love to see this PR and review it.

**Comment by moonbox3** [comment]
Keeping this issue open as it is on our backlog.
