### ISSUE TITLE
Java: Minimal set of getting started samples

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#1572]
Create a minimal set of samples which demonstrate features of the SK for Java SDK

Proposal for changing sample structure is documented here: https://microsoft.sharepoint.com/teams/semantic-kernel/Shared%20Documents/Engineering/Design/2023.06-Kernel-Examples-Redesign.docx?web=1

**Comment by d3r3kk** [comment]
@johnoliver @milderhc @dsgrieve  Please define "minimal set" this  sprint so we can whittle it down over the next few.

**Comment by d3r3kk** [comment]
I think we have achieved "minimal set". We will open specific issues for new demo materials as we continue development on Java SK.
