### ISSUE TITLE
Java: API - Minimal unit test coverage

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#1577]

**Comment by d3r3kk** [comment]
Duplicate of #1584

**Comment by d3r3kk** [comment]
Still some investigation to be done here. Moving to post-beta / Oct+ timeframe.

**Comment by d3r3kk** [comment]
Removing, will add more specific testing targets once the Java SK hits RC1.0. The team will specifically define what "minimal" means and meet or exceed that level.
