### ISSUE TITLE
Java: Core - CoreSkills partity

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#1579]
Merge core-skills package back into core

**Comment by brunoborges** [comment]
I think we discussed this in the ADR and we will keep core skills in its own package.

@markwallace-microsoft confirm?

**Comment by d3r3kk** [comment]
Core skills will be kept in their own package, as per the ADR. If we need to change this, please let us know and re-open the task to spark discussion.
