### ISSUE TITLE
Java: Core - Services implementation

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#1582]

**Comment by d3r3kk** [comment]
Identify each service that we have not ported, and enumerate each as an issue to replace this 'umbrella' issue.

**Comment by d3r3kk** [comment]
- [ ] Image Generation
- [ ] Hugging Face
- [ ] Custom Service (?)

**Comment by d3r3kk** [comment]
- Image generation exists as #1573 
- Hugging Face exists as #1588 
- Custom/any models created as #2286
