### ISSUE TITLE
Java: Core - Rewrite how native skill functions are invoked

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#1586]
Parity with .Net PR https://github.com/microsoft/semantic-kernel/pull/1133

**Comment by d3r3kk** [comment]
Discuss where Java needs to fill any gaps, or if we've satisfied this already.

**Comment by brunoborges** [comment]
@markwallace-microsoft I believe this is a good example of "not Java idiomatic". Besides, we sort of support this through other mechanisms.

I'll move to the backlog for now.

**Comment by d3r3kk** [comment]
Completed with other V1.0 work in progress.
