### ISSUE TITLE
Improve Planner prompt to support invalid ASK

### ISSUE THREAD

**Issue by gogodjzhu** [microsoft/semantic-kernel#159]
It appears that the Microsoft.SemanticKernel.CoreSkills.SemanticFunctionConstants.FunctionFlowFunctionDefinition prompt always attempts to generate a plan for a given goal, even if there are no appropriate skills available to fulfill it. This can result in some absurd plans being generated.

To address this, there are two potential options:

1. Return an error message when there are no suitable skills available to fulfill the goal. This would help prevent the generation of ridiculous plans and provide feedback to the user that the goal cannot be accomplished with the current set of skills. 
2. Leave the plan verification task to the user. 

Thx.

**Comment by evchaki** [comment]
Closing with PR now in main

**Comment by evchaki** [comment]
There is still additional work to be done.  Opening this back up
