### ISSUE TITLE
"Too many inputs for model None. The max number of inputs is 1" when using AzureTextEmbeddings

### ISSUE THREAD

**Issue by jansenbe** [microsoft/semantic-kernel#16]
**Describe the bug**

`GenerateEmbeddingsAsync` is designed pass in multiple text parts to optimize the number of roundtrips, however it (today) only works using one text input. When you pass in more you'll get this error message back from Azure OpenAI:

```json
{
  "error": {
    "message": "Too many inputs for model None. The max number of inputs is 1.  We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**To Reproduce**

```csharp
var kernel = Kernel.Builder.Build();

kernel.Config.AddAzureOpenAIEmbeddingsBackend(
    "embedding",                    // config label
    "text-embedding-ada-002",     // Azure OpenAI *Deployment ID*
    "https://contoso.openai.azure.com/", // Azure OpenAI *Endpoint*
    "<Azure OpenAI key>");

BackendConfig embeddingsBackendCfg = kernel.Config.GetEmbeddingsBackend("embedding");
var embeddingGenerator = new AzureTextEmbeddings(
        embeddingsBackendCfg.AzureOpenAI.DeploymentName,
        embeddingsBackendCfg.AzureOpenAI.Endpoint,
        embeddingsBackendCfg.AzureOpenAI.APIKey,
        embeddingsBackendCfg.AzureOpenAI.APIVersion,
        kernel.Log);

var embedding = await embeddingGenerator.GenerateEmbeddingsAsync(
                         new List<string> { "Text 1 to vectorize", "text 2 to vectorize" }
                         );
```

**Expected behavior**
Add a `GenerateEmbeddingAsync` equivalent that request a string as input. For now throw a `NotSupportedException` exception when Azure OpenAI is used in the `GenerateEmbeddingsAsync` method clarifying for the developer to use the other method for the time being.

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: Visual Studio
 - NuGet Package Version: 0.8

**Comment by awharrison-28** [comment]
Hi @jansenbe. `GenerateEmbeddingAsync(string text)` does currently exist. Noting this, instead of throwing a `NotSupportedException`, we will address the expected behavior by emulating batching using `GenerateEmbeddingAsync` to loop over list of input strings to `GenerateEmbeddingsAsync`.

This will provide a smoother transition when Azure OpenAI implements batching as a feature for embedding endpoints.

**Comment by jansenbe** [comment]
@awharrison-28 : that makes sense, do note that you need to combine that with some level of throttling support as you'll be throttled really soon (at least I did when using my Azure OpenAI key).

**Comment by dluc** [comment]
@jansenbe good point, could you join the PR review, e.g. download the PR branch and see if it addresses your scenario?

PR: https://github.com/microsoft/semantic-kernel/pull/19

To download the branch, see the button top-right

<img width="167" alt="image" src="https://user-images.githubusercontent.com/371009/222780057-687b97d5-6281-4815-9cc2-0d0b66c79ff1.png">
