### ISSUE TITLE
Python: Integrate chat stream into kernel

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#1606]
I checked 2 PRs(#1115, #1316) for streaming. Both PRs are defining `kernel = sk.Kernel()` but not using them at all.
Current chat streaming is complex to use with `Kernel`. 

hope streaming can be used via kernel like below
```python
kernel = sk.Kernel()
kernel.add_chat_service(
        "gpt-3.5-turbo",
        sk_oai.AzureChatCompletion(
            "gpt-35-turbo",
            os.environ.get("AZURE_OPENAI_ENDPOINT"),
            os.environ.get("AZURE_OPENAI_KEY"),
        ),
    )
skills = kernel.import_semantic_skill_from_directory(skill_dir, skill)
kernel.run_stream_async(skill["TranslationSkill"]["toEnglish"], input_vars=...)
```

**Comment by alexchaomander** [comment]
Thanks for the feedback @joowon-dm-snu! It's good feedback that we can improve the interface. Putting this on the backlog for @awharrison-28 and @mkarle to review when they are back from vacation!

**Comment by joowon-dm-snu** [comment]
Thank you. If it's not a high priority, I'll open a PR myself. I want to use it as soon as possible :).

Currently, I'm using a temporary method where I can simply append the code into `kernel.run_stream_async` with minimal additional code to implement.
```python
skills = kernel.import_semantic_skill_from_directory(skill_dir, skill)
func = skills["TranslationSkill"]["toEnglish"]

# Get the closure variables as function's config does not saved in `SKFunctionBase` itself.
closure_vars = func._function.__closure__  
for var in closure_vars:
    if isinstance(var.cell_contents, SemanticFunctionConfig):
        function_config = var.cell_contents
        break
request_settings = func._chat_request_settings
client = func._ai_service

prompt = await function_config.prompt_template.render_async(context)

...
```
If your team want this to be more accurate, it seems like `SKFunctionBase` should add new function, `invoke_stream_async`. But this might take a bit longer than former one, so if it's okay, I can quickly open the former PR and gradually add the necessary functions to SKFunctionBase. 

I'm curious what you think about that.

**Comment by alexchaomander** [comment]
I personally think it makes sense and would be a nice interface to add. 

@dluc what do you think?

**Comment by joowon-dm-snu** [comment]
I opened PR with my temporal method!
