### ISSUE TITLE
Breaking change dependency introduced

### ISSUE THREAD

**Issue by Woland2k** [microsoft/semantic-kernel#1617]
**Describe the bug**

In this commit, dependency was changed from 6.0.0 to 7.0.0 
https://github.com/microsoft/semantic-kernel/commit/aa80f3026fba1b56bd171ec049e2aa694a328916

Is this really needed? It becomes a breaking change for us since we use 6.0.0 versions of DLLs throughout the project.

**Comment by alexchaomander** [comment]
Thanks for bringing this up! @shawncal can you check?

**Comment by markwallace-microsoft** [comment]
Fixed: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/Directory.Packages.props#L19
