### ISSUE TITLE
CC: Delete conversation with bot

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#1642]
The user should be able to delete a conversation with a bot (and other users). The UX should follow the same patterns established by Microsoft Teams. This means _only_ deleting the conversation for the current user and maintaining the conversation for any other users.

**Comment by teresaqhoang** [comment]
@alliscode @matthewbolanos Gina's actively working on this; the deletion part has been implemented and tested but she has some edge cases she needs to take care of https://github.com/orgs/microsoft/projects/852?pane=issue&itemId=30423531

**Comment by teresaqhoang** [comment]
V1 is done - any user that is apart of the chat can delete the chat; it will delete the chat for all users

https://github.com/microsoft/chat-copilot/pull/193
