### ISSUE TITLE
.Net: Document how to pass correlation IDs in Semantic Kernel

### ISSUE THREAD

**Issue by chipalost** [microsoft/semantic-kernel#1648]
Add a means of attaching developer defined properties to a prompt. These properties should follow the prompt, and be accessible, throughout the SK call stack (eg. in a custom backend or connector).

The scenario that drives this request is implementation of a correlation ID so that prompt requests can be traced and timed to measure performance. Simply adding a correlation ID to prompts may be sufficient to implement the perf scenario; however, it's believed there are other scenarios that need different types of associated properties or objects. A more robust implementation may be a developer accessible property bag that follows prompts.

**Comment by matthewbolanos** [comment]
Updating this issue to capture the need to document how to achieve this scenario.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
