### ISSUE TITLE
.Net: Streaming support for semantic functions on IKernel

### ISSUE THREAD

**Issue by chipalost** [microsoft/semantic-kernel#1649]
> [!IMPORTANT]  
> Labeled **Urgent** because it will require a breaking change.

Add streaming APIs to IKernel, in addition to the work that's been done for ITextCompletion and IChatCompletion. 
Add streaming from SK Functions

```[tasklist]
### Child issues
- [x] [Update PrePost hooks examples and implementations to suffice this Issue completely](https://github.com/microsoft/semantic-kernel/issues/2730)
```

**Comment by mozher** [comment]
> 
> 
> 
> 
> 
> Add streaming APIs to IKernel, in addition to the work that's been done for ITextCompletion and IChatCompletion. 
> Add streaming from SK Functions
>

**Comment by matthewbolanos** [comment]
@dluc mentioned that streaming of chat completion wasn't working (yet)
