### ISSUE TITLE
python-preview bug fix for `6-memory-and-embeddings`

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#165]
**Describe the bug**
fix some codes for running `semantic-kernel/samples/notebooks/python/6-memory-and-embeddings.ipynb`
`memories = await kernel.memory.search_async(memory_collection_name, ask, limit=5, min_relevance_score=0.77)`
will returns empty list because there is missing codes in `semantic-kernel/python/semantic_kernel/memory/semantic_text_memory.py`

and output printing parts should be changed.

**To Reproduce**
run `semantic-kernel/samples/notebooks/python/6-memory-and-embeddings.ipynb`

**Expected behavior**
`semantic-kernel/samples/notebooks/python/6-memory-and-embeddings.ipynb` runs well

**Screenshots**
![image](https://user-images.githubusercontent.com/69464062/227905521-5f97eca8-f1f3-4d6c-9f44-82d434e9187f.png)

**Desktop (please complete the following information):**
 - OS: Mac M1
 - IDE: VS code
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by alexchaomander** [comment]
Merged!
