### ISSUE TITLE
Multiple responses that don't need to be parsed

### ISSUE THREAD

**Issue by chipalost** [microsoft/semantic-kernel#1658]
SK allows for multiple responses to be returned for one request; however, it appends all responses into one string. This makes it hard to interact with any one particular response as they must first be parsed into individual responses.

An alternative could be returning an array of ContextVariables or an array of Context objects, each of which containing its own result.
- Context.ContextVariables[].Result
- Context[].ContextVariables.Result

**Comment by chipalost** [comment]
In theory, SK already supports this. A developer should be able to iterate through a collection of responses. For example, Kernel.RunAsync() returns SKContext and you should then be able to iterate through ModelResults which is part of the SKContext.

Unfortunately, it looks like we have a bug where all responses are being appended to a string which is then provided as each of the responses contained in ModelResults.

**Comment by shawncal** [comment]
@RogerBarreto looks like ModelResults isn't getting filled in properly. Can you take a look please?

**Comment by RogerBarreto** [comment]
@shawncal @chipalost. I could not find this behavior in the current Model Results although I found another unwanted behavior.

Each ModelResult is actually including all the choices (Prompt Results) and is not clear from which ModelResult is which choice.

I will open a small PR to make it clear in a ModelResult 1:1 Choice
