### ISSUE TITLE
.Net: Provide tokenizers for connectors

### ISSUE THREAD

**Issue by chipalost** [microsoft/semantic-kernel#1659]
Different models have different ways to limit the number of calls (eg. tokens/sec, input vs. output tokens). A client needs to project token usage so it does not hit a limit, which results in throttling and a poor user experience. Some way to understand the limits and how quickly a client is approaching it would allow the client to be proactive (eg. slowing down requests is better than getting stopped in the middle of a long running request).

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
