### ISSUE TITLE
HTTP status: 401

### ISSUE THREAD

**Issue by cherchyk** [microsoft/semantic-kernel#1660]
From time to time, I have 401 errors (Azure OpenAI).

I've completed the previous steps. 
<img width="198" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1703275/5a53f9ac-e3a6-4aa3-b2cb-3dcc0650ca4b">

and I would have 401 from time to time, but after running cell a couple of times, I would get a response
<img width="1178" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1703275/4ec0a2b7-4464-4682-835f-05c0229113ad">
(I changed the prompt in this specific example to give me JSON so it's different)
<img width="1318" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1703275/d2fb8eea-3639-49c4-bdce-47a490d66677">

in #6-Memory-and-embedding step, I keep getting 401 all the time
<img width="1233" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1703275/ae9d3a67-e50a-4f2b-832b-cdbbc8c221b4">

**Comment by teresaqhoang** [comment]
@cherchyk this seems like a throttling issue, a couple followup questions:
- Have you checked your Azure OpenAI quota limits? 
- Has notebook 6 ever run successfully for you?

**Comment by glahaye** [comment]
@cherchyk  I was not able to reproduce this on my side.

Make sure you provide proper credentials in your settings.json by running steps 0 and 00.

Also, try with the latest version as some changes have been put in.

Let us know whether you are still experiencing the issue.
