### ISSUE TITLE
Python: optional role message for streaming

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#1667]
@alexchaomander 
Current version of streaming results starts with "assistant:" by snippet below

```python
# semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion.py
async def complete_stream_async(
    self, prompt: str, request_settings: CompleteRequestSettings
):
    ...
    
    async for chunk in response:
            text, index = _parse_choices(chunk)
    ...

def _parse_choices(chunk):
    message = ""
    if "role" in chunk.choices[0].delta:
        message += chunk.choices[0].delta.role + ": "
    if "content" in chunk.choices[0].delta:
        message += chunk.choices[0].delta.content

    index = chunk.choices[0].index
    return message, index
```
It makes its response starts with "asstistant: 하이퍼 바이저는 호스트 시스템에서 다수의 게스트 OS를...".

However, in actual use case, we don't need the role message "assistant: ". most cases need to replace it with a different proper noun. To do that, I need to check the output generated through the kernel and remove it like below.
```python
async for completion in self._kernel.run_stream_async(function, input_vars=ctx):
    if completion != "assistant: ":
        yield completion
```
Therefore, it would be great to have the ability to control the role message using an optional parameter.

**Comment by alexchaomander** [comment]
Tagging @awharrison-28 to look at this when she's back from vacation!
