### ISSUE TITLE
.Net: Token limit aware templating

### ISSUE THREAD

**Issue by chipalost** [microsoft/semantic-kernel#1676]
Different sections of a prompt template are unaware of the number of tokens other sections are using. When combined, the size of a final prompt can easily blow past input token limits.  A means for setting limits on the size of different sections of a prompt template would help developers allocate tokens to more important parts of the template while creating a final template that stays within an allowable token range.

**Comment by rysweet** [comment]
this especially can show up when using {{recall}} - because the recalll is embedded in the prompt you can't check how big the thing is before you decide if it should be included.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
