### ISSUE TITLE
Async functions should accept and respect cancellation tokens

### ISSUE THREAD

**Issue by chipalost** [microsoft/semantic-kernel#1677]
Skills/plugins are async functions, but they can't take a cancellation token. Not only should those functions accept a cancellation token, it should be passed down and respected through chains of functions. Apparently there is a PR that fixes this. It's a large breaking change (in a good way) which needs careful planning about how/when it's introduced.

**Comment by shawncal** [comment]
Fixed with https://github.com/microsoft/semantic-kernel/pull/1195
