### ISSUE TITLE
delegate_inference raise error in python-preview branch

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#168]
**Describe the bug**
while run `pytest .` in `semantic-kernel/python/tests`

```
@staticmethod
def infer_delegate_type(function) -> DelegateTypes:
    # Get the function signature
    function_signature = signature(function)
    awaitable = iscoroutinefunction(function)

    for name, value in DelegateInference.__dict__.items():
        if name.startswith("infer_") and hasattr(
>               value.__wrapped__, "_delegate_type"
        ):
E           AttributeError: 'staticmethod' object has no attribute '__wrapped__'

../semantic_kernel/orchestration/delegate_inference.py:240: AttributeError
======================================================================================= short test summary info =======================================================================================
FAILED test_text_skill.py::test_can_be_imported - AttributeError: 'staticmethod' object has no attribute '__wrapped__'
FAILED test_text_skill.py::test_can_be_imported_with_name - AttributeError: 'staticmethod' object has no attribute '__wrapped__'
===================================================================================== 2 failed, 9 passed in 0.23s =====================================================================================
```

**To Reproduce**
1. Go to `semantic-kernel/python/tests`
2. run ``pytest .`

**Expected behavior**
this test should not raise error

**Screenshots**
![image](https://user-images.githubusercontent.com/69464062/227978163-eae76bbf-0644-4f39-9091-22514ede19a1.png)

**Desktop (please complete the following information):**
 - OS: Mac M1
 - IDE: VS Code
 - Python version: 3.9.13

**Additional context**

**Comment by jjhenkel** [comment]
Ah yep, I think that's the issue. Let me just test your proposed changes and, if it works and helps us be a little bit more robust to various Python version, I'm happy to take them! Thank you for your time on this! 

(I think, some point soon, we'll have a discussion and pick a minimum Python version we're looking to support. But until then, robustness to older versions is great)

**Comment by alexchaomander** [comment]
Merged!
