### ISSUE TITLE
.Net: Crash in creating index in Pinecone with CreateIndexAsync

### ISSUE THREAD

**Issue by securigy** [microsoft/semantic-kernel#1719]
In all examples that involve memory store Microsoft requires to create index either somewhere outside of manual through the code with CreateIndexAsync. I used to have index in Pinecone that I previously deleted a while back and my other program that works with pinecone shows that it has no indexes.

However, when I execute the following code with SK, I get exception Bad Request (400) on the line of:  pinecone.CreateIndexAsync
I know that my API key is correct it works with another program.

Any clues?

                `
                string apiKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
                string pineconeEnvironment = "us-west1-gcp-free";

                PineconeMemoryStore memoryStore = new(pineconeEnvironment, apiKey);
                using var pinecone = new PineconeClient(pineconeEnvironment, apiKey);

                try
                {
                    // Create new index
                    await pinecone.CreateIndexAsync(new("Index1")
                    {
                        Dimension = 1536,
                        PodType = PodType.S1X1,
                        Metric = IndexMetric.Cosine
                        //SourceCollection = "pinecone-test" 
                    });
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }`

This is the desktop app.
 - OS: Win11
 - IDE: [e.g. VS2022
 - NuGet Package Version Microsoft.SemanticKernel  0.17.230636.1-preview
The same version for other SK related modules.

**Comment by securigy** [comment]
I resolved the BadRequest because Pinecone accepts the index names in small letters only (no capitals - total weirdness).
However, the following line in the example 38 throws exception that index must be created manually or through API, which I did and the index state is RanToCompletion. So why is it failing?

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
