### ISSUE TITLE
ITextEmbeddingGeneration is not compatible with Embedding<double>

### ISSUE THREAD

**Issue by xbotter** [microsoft/semantic-kernel#1725]
https://github.com/microsoft/semantic-kernel/blob/49e20107b9fdd1f9896fba9197428c659ad61038/dotnet/src/SemanticKernel.Abstractions/AI/Embeddings/ITextEmbeddingGeneration.cs#L10

ITextEmbeddingGeneration is limited to `Embedding<float>`, which may cause some precision loss for models that generate `Embedding<double>`. 

Is there a solution to this problem?

**Comment by lemillermicrosoft** [comment]
No solution right now, putting on the backlog.

**Comment by matthewbolanos** [comment]
Closing this issue since there doesn't appear to be a solution with the existing AI services.
