### ISSUE TITLE
When using Time Skill SK throws error {"Invalid plan: Plan parsing error, invalid JSON"}

### ISSUE THREAD

**Issue by sandeepvootoori** [microsoft/semantic-kernel#1736]
**Describe the bug**
I am trying to use time skill but SK throws exception {"Invalid plan: Plan parsing error, invalid JSON"}.
Inner Exception : '{' is invalid after a single JSON value. Expected end of data. LineNumber: 6 | BytePositionInLine: 0.

**To Reproduce**
Use time skill and try to ask for "What is tomorrows date?" and it starts failing. It doesn't happen 100% of the time but happens pretty frequently.

**Desktop :**
 - OS:  Windows
 - IDE: Visual Studio
 - NuGet Package Version 0.17.230626.1-preview/0.16.230615.1-preview happens on both

**Comment by lemillermicrosoft** [comment]
I assume this is ActionPlanner? If so, known issue #1726

**Comment by sandeepvootoori** [comment]
> I assume this is ActionPlanner? If so, known issue #1726

It is.

Thank you, will follow the other issue.

**Comment by lemillermicrosoft** [comment]
Closing as duplicate of resolved issue.
