### ISSUE TITLE
Add syntax example to Python API reference

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#1747]
Inline code snippets from the syntax examples to explain how to use the Python APIs.

**Comment by kinfey** [comment]
okay , maybe I can help

**Comment by nacharya1** [comment]
@kinfey - are you still looking into this? If so could you please add target dates for completion?

**Comment by kinfey** [comment]
> @kinfey - are you still looking into this? If so could you please add target dates for completion?

I will merge it on Next Monday

**Comment by nacharya1** [comment]
@kinfey - where you able to merge this?

**Comment by kinfey** [comment]
yes ,give me  more 2 days

**Comment by matthewbolanos** [comment]
Closing so we can create new issues for docs later
