### ISSUE TITLE
Allow to run functions with .NET 7 (SK VS Code Extension)

### ISSUE THREAD

**Issue by jpiquot** [microsoft/semantic-kernel#1749]
**Describe the bug**
When attempting to execute a skill within the Visual Studio Code extension for Semantic Kernel, an error occurs, prompting the installation of .NET 6 when .NET 7 is present on the machine.

**To Reproduce**
1. Install .NET 6 and .NET 7 on the machine.
2. Run a skill in SK extension for VS Code

**Expected behavior**
Should run without any error. 

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/6775094/85b0e5e0-c2c2-46ba-8091-1c2eea051b1c)

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: VS Code
 - Latest version from main branch

**Additional context**

C:\Dev>dotnet --list-sdks
6.0.118 [C:\Program Files\dotnet\sdk]
6.0.411 [C:\Program Files\dotnet\sdk]
7.0.304 [C:\Program Files\dotnet\sdk]
7.0.400-preview.23274.1 [C:\Program Files\dotnet\sdk]
8.0.100-preview.4.23260.5 [C:\Program Files\dotnet\sdk]
C:\Dev>dotnet --version
8.0.100-preview.4.23260.5

**Comment by evchaki** [comment]
@jpiquot  - thank you for bringing up this bug.  The team is looking into it - @matthewbolanos

**Comment by markwallace-microsoft** [comment]
Hi @jpiquot 
I'm trying to reproduce this issue.

I have tested with just .Net 7 installed i.e.

```
PS C:\> dotnet --list-sdks
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.304 [C:\Program Files\dotnet\sdk]
PS C:\> dotnet --version
7.0.304
```

And I am not seeing the issue. If I add .Net 6 I get the same behaviour.

In your instructions to reproduce the say _Install .NET 6 and .NET 7 on the machine_ This seems to conflict with the ask in the title of the issue.

Is there any other information you can share to help me to reproduce this issue?

**Comment by glahaye** [comment]
Can't repro this issue. Closing after weeks without further input. @jpiquot Feel free to re-open with more detail if you encounter this problem again.
