### ISSUE TITLE
ChatStore:Cosmos:ChatParticipantsContainer web app config setting is missing

### ISSUE THREAD

**Issue by vman** [microsoft/semantic-kernel#1771]
**Describe the bug**
`ChatStore:Cosmos:ChatParticipantsContainer` config setting is missing from the bicep template for the web app.

This makes the web app deployment fail when deployed to Azure. 

Very similar to this issue reported previously for the `ChatMemorySources` config setting:
https://github.com/microsoft/semantic-kernel/issues/1402#issuecomment-1594908023

**Comment by evchaki** [comment]
@vman - thank you for letting us know about this - we are looking into it now.

**Comment by teresaqhoang** [comment]
Fixed here @vman: https://github.com/microsoft/semantic-kernel/pull/1780
