### ISSUE TITLE
OpenAPI skill should support empty or relative server URLs

### ISSUE THREAD

**Issue by gitri-ms** [microsoft/semantic-kernel#1782]
We currently do not support parsing OpenAPI specs that are missing the `servers` array or use relative server URLs. Both of these cases are permitted by the [OpenAPI 3.0 specification](https://swagger.io/docs/specification/api-host-and-base-path/) so we should also support them.
(See #1546 for more context)

**Comment by nacharya1** [comment]
@SergeyMenshykh  - can you please investigate into this.

**Comment by nacharya1** [comment]
@dmytrostruk - please look into per side discussion.
