### ISSUE TITLE
Add System.Linq.Async to memory connectors

### ISSUE THREAD

**Issue by dluc** [microsoft/semantic-kernel#1784]
Since memory connectors heavily rely on `IAsyncEnumerable` it would be nice having IAsyncEnumerable extension methods like `FirstOrDefaultAsync` available out of the box. IAsyncEnumerable extension methods are available via package `System.Linq.Async` which is quite hard to find. 

For instance when using SK memory in a notebook, one shouldn't have to use `#r "nuget: System.Linq.Async, 6.0.1"`.

Suggestion: add `System.Linq.Async` to all memory connectors, to make it easier to work with SK memory.

**Comment by stephentoub** [comment]
We could; the majority of these APIs are also trivial to implement, though, e.g. you mention FirstOrDefaultAsync, and we already have that here:
https://github.com/microsoft/semantic-kernel/blob/5cae28540187139af3a9f8e04e0f72ccbeb8ddd4/dotnet/src/InternalUtilities/src/Linq/AsyncEnumerable.cs#L39-L47

**Comment by shawncal** [comment]
I'm thinking we add this as a package reference in the MS.SemanticKernel metapackage. That way, it'll be available for anyone wanting the recommended set of packages to get started out of the box, but it won't bulk up the individual packages unnecessarily.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
