### ISSUE TITLE
.Net: Use Multiple Models in a Single Kernel

### ISSUE THREAD

**Issue by davisar** [microsoft/semantic-kernel#1787]
When developing skills that will be used in a plan (or a kernel in general) there isn't a way to indicate the type or version of model required for the skill. Currently this means that there's only a single model or each type (text completion, chat, etc) available for all skills in the kernel to use.

The downside of the current implementation is that if even a single skill that is loaded and might be used needs to use an advanced (and expensive) model like gpt4 then _all_ of the skills now have to operate at that cost rather than utilizing a simpler model for simpler skills. There's also no way for skills to indicate their model preferences, so even to an end-user who can look at the semantic skill's text there's not a good way to tell someone consuming the skill what models may be needed in order to run the skill and have it output desirable content (it requires experimentation).

The feature change would enable the following:
1. Multiple Completion services would be able to be added to a kernel. The first type of each service would establish the default which skills would use, and the remainder would need to be specified by the skill in some way (ex: either via a key name set when the skill is registered or by specifying a detail like the serviceId)
2. Skills would be able to request a specific version of a service, for example the "Foo" or "text-ada-001" registration of the TextCompletionService.
3. Semantic Skills would be able to specify a model preference via config which would be used to request the specific version of the service via (2).

Proposed Examples:
```
IKernel kernel = new KernelBuilder()
            .WithLogger(loggerFactory.CreateLogger<IKernel>())
            .WithCompletionService(kernelSettings)
            .WithAzureTextCompletionService(deploymentName, endpoint, apiKey, lookupKey: "Foo")
            .WithAzureChatCompletionService
            .Build();
...
(config.json):
{
  "schema": 1,
  "description": "Create Widget",
  "type": "completion",
  "completion": {
    "preferred_service": "Foo"
    "max_tokens": 100,
    "temperature": 0.9,
    "top_p": 0.0,
    "presence_penalty": 0.0,
    "frequency_penalty": 0.0
  },
  "input": {
    "parameters": [
      {
        "name": "input",
        "description": "Widget Type",
        "defaultValue": ""
      }
    ]
  }
}
```

I found: 
This [which seems to indicate that the serviceId might be able to be used for this functionality, but it doesn't appear to be used currently](https://github.com/microsoft/semantic-kernel/blob/5cae28540187139af3a9f8e04e0f72ccbeb8ddd4/dotnet/src/SemanticKernel.Abstractions/Services/INamedServiceProvider.cs#L13C16-L13C16)
The ["Default Services" Property](https://github.com/microsoft/semantic-kernel/blob/5cae28540187139af3a9f8e04e0f72ccbeb8ddd4/dotnet/src/SemanticKernel.Abstractions/SemanticFunctions/PromptTemplateConfig.cs#L145) which is a list and appears to be on the config object, but I wasn't able to find any real usage of it. Maybe this was intended to be able to indicate a service ID?

**Comment by ashikns** [comment]
If you create a semantic function using SemanticTools VS Code extension, it will include a `default_backends` in the config.json. See https://github.com/microsoft/teams-ai/blob/d753c5c40f8d03d8c2b639f3dd7baa8f68241db8/js/samples/04.q.questBot/src/prompts/help/config.json.

However this doesn't seem to be respected by the C# sdk as of now.

**Comment by markwallace-microsoft** [comment]
It is possible to specify the `ServiceId` to use for a semantic function, see `SemanticFunctionTests.ItUsesServiceIdWhenProvidedAsync`. We want to expand this functionality in the near future.
