### ISSUE TITLE
copilot-chat-app azure deploy. Users who are not from the current tenant cannot log in properly.

### ISSUE THREAD

**Issue by huangchao-shanghai** [microsoft/semantic-kernel#1788]
**Describe the bug**
copilot-chat-app azure deploy. Users who are not from the current tenant cannot log in properly.
After logging in, it will return to the page before the login, and report the following error.
`AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type`
The Azure deployment was done using the script below.
[semantic-kernel](https://github.com/microsoft/semantic-kernel/tree/main)/[samples](https://github.com/microsoft/semantic-kernel/tree/main/samples)/[apps](https://github.com/microsoft/semantic-kernel/tree/main/samples/apps)/[copilot-chat-app](https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/copilot-chat-app)/[deploy](https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/copilot-chat-app/deploy)
/deploy-webapp.ps1

The application was registered as a Single Page Application (SPA) type
I suspect that the problem was caused by the command below. #1711 
```
Write-Host "Updating AAD App registration..."
az ad app update --id $ApplicationClientId --web-redirect-uris "https://$webappUrl"
```

**Expected behavior**
Users from different tenants can also log in normally.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/3233883/e000d503-43e2-4970-8a67-759c2608728d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 -Browser:  Edge

**Additional context**

**Comment by vman** [comment]
Faced this one as well. Current manual workaround is the go back to the AAD app and reconfigure it as a Single Page App and set the web app url manually as the redirect url.

**Comment by gitri-ms** [comment]
Looking into this

**Comment by gitri-ms** [comment]
Working on a fix for this. In the meantime, the workaround is to:
1. Remove the following line from `deploy-webapp.ps1` / `deploy-webapp.sh`:
```
az ad app update --id $ApplicationClientId --web-redirect-uris "https://$webappUrl"
```
2. After deploying, go to your app registration in the Azure portal and add your frontend URL as a redirect URI for the SPA platform type
