### ISSUE TITLE
Copilot Chat: Really bad lag in multiuser chat

### ISSUE THREAD

**Issue by gitri-ms** [microsoft/semantic-kernel#1796]
**Describe the bug**
After engaging in multiuser chat for 20-30 minutes, I started experiencing serious lag that effectively rendered the application unusable:
- When I tried to type a character in the text box, it would take ~15 seconds to appear
- When I tried to send a message, it took over a minute to send and appear in the conversation. Then my message disappeared from the conversation when it rendered other messages that had come in, before reappearing after them.
- Eventually, i could not interact with the web app at all -- clicking around on the app (such as selecting a conversation or the text box) did nothing
- After several minutes, I was able to resume interaction, but the UI didn't update with any new messages until I refreshed the page.

I also saw this error banner:
![image](https://github.com/microsoft/semantic-kernel/assets/51341242/22f9414a-c048-42ba-9c53-a3eab91879d5)

**Desktop (please complete the following information):**
 - OS: Win11 / edge
 - IDE: n/a
 - NuGet Package Version: 0.16.230615.1-preview

**Comment by TaoChenOSU** [comment]
Did you have the developer tool opened with the Webapp? I have seen very bad lag when I have the browser console opened with the webapp.
