### ISSUE TITLE
Java: TimeSkillTest fail when non US local

### ISSUE THREAD

**Issue by agoncal** [microsoft/semantic-kernel#1819]
**Describe the bug**

When executing `./mvnw clean install` the `TimeSkillTest` fails with several Local assertions:

- `testNow` fails because it expects `Sunday, January 12, 2025 9:15 AM` but gets `Sunday, January 12, 2025 9:15 am` (notice uppercase `AM` and lower case `am`)
- `testToday` fails because it expects `Sunday, January 12, 2025` but gets `Sunday, 12 January 2025`
- `testDate`
- `testHour`
- `testTime`
- `testDateMatchingLastDayName`
- `daysAgo`

To fix the tests, one way is to force the local in the Surefire plugin:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>${maven.surefire-plugin.version}</version>
    <configuration>
        <argLine>-Duser.language=en -Duser.region=US</argLine>
    </configuration>
</plugin>
```

**Expected behavior**
Tests should pass even if the local is different from US.

**Comment by nacharya1** [comment]
@markwallace-microsoft  - can you please take a look at this.

**Comment by agoncal** [comment]
With https://github.com/microsoft/semantic-kernel/pull/1526 being merged, tests are passing regardless of the local
