### ISSUE TITLE
Maximum Context length Surpassed while using Sequential Planner

### ISSUE THREAD

**Issue by animeshj9** [microsoft/semantic-kernel#1831]
**Describe the bug**

We are trying to create an Azure DevOps connector using Azure DevOps's openapi.json specification file. I keep running into context length exceeded errors. Is this because the openapi.json file is too big? or has too many functions within it?

How can I go about reducing the context length for the sequential planner? Is there a way to make sure we don't surpass the context length when importing openapi json files?

Does this mean that the more skills I import / register, the more I'm going to see this error?

Appreciate the help! 

```
Something went wrong while rendering the semantic function or while executing the text completion. Function: SequentialPlanner_Excluded.funcb8f56bd3dfa84937821f8793cd3d222e. Error: Invalid request: The request is not valid, HTTP status: 400. Details: This model's maximum context length is 8192 tokens. However, your messages resulted in 8282 tokens. Please reduce the length of the messages.
[2023-07-04T00:01:43.744Z] Status: 400 (model_error)
[2023-07-04T00:01:43.746Z] ErrorCode: context_length_exceeded
[2023-07-04T00:01:43.748Z]
[2023-07-04T00:01:43.755Z] Content:
[2023-07-04T00:01:43.758Z] {
  "error": {
    "message": "This model's maximum context length is 8192 tokens. However, your messages resulted in 8282 tokens. Please reduce the length of the messages.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}
```

**To Reproduce**
1. Import an openapi.json specification file for azure devops - [Azure DevOps WorkItemTracking openapi.json spec file](https://gist.github.com/animeshj9/512ce9daa890e05c0f2b548adb18e565)
2. Create a sequential planner along with a few other skills. 
3. ` var plan = await planner.CreatePlanAsync(goal);` will throw the below errors and result in a plan with 0 steps.

**Screenshots**
![SemanticKernelError](https://github.com/microsoft/semantic-kernel/assets/6694373/5c8f423c-fd16-4124-84e9-a3f3a9bb721a)

**Expected behavior**
A plan is created using the available skills.

*Note: I have been able to create a plan, but it intermittently works. Most of the time, it fails with the context length exceeded error.*

**Desktop (please complete the following information): **
 - OS: Windows
 - IDE:Visual Studio
 - NuGet Package Version - 0.16.230615.1-preview, 0.17.230629.1-preview

**Additional context**
WIthout the openapi spec file, the planner works fine. So it seems that the ADO openapi skill is the culprit. I have tried to reduce the number of functions from the openapi file, it still throws the error. I even trimmed the file down to the one API I need, it still threw. So I am now very confused about what is causing this error.

**Comment by animeshj9** [comment]
Thanks @evchaki . Please let us know when the blog is posted. Thanks!

**Comment by lemillermicrosoft** [comment]
Hey @animeshj9 ,

To adjust the `MaxTokens` allowed, you can make use of the [SequentialPlannerConfig](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/SequentialPlannerConfig.cs). The default value is set to 1024. If you reduce this value, you might achieve workable plans. For guidance on overriding this value, take a look at the [EmailSample](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example12_SequentialPlanner.cs) and other examples.

Here's an example of how to set `MaxTokens`:

```csharp
planner = new SequentialPlanner(kernel, new SequentialPlannerConfig { MaxTokens = maxTokens });
```

Furthermore, if you're interested, we have a blog post that discusses utilizing a memory store to filter and limit the functions accessible to the planner. You can find it here: [Semantic Kernel Planners: Sequential Planner](https://devblogs.microsoft.com/semantic-kernel/semantic-kernel-planners-sequential-planner/).

For leveraging memory and embeddings to identify pertinent skills within the planner, it's important to set the 'Memory' property in the planner configuration. Here's an example of how to do it:

```csharp
// IMPORTANT: To use memory and embeddings to find relevant skills in the planner, set the 'Memory' property on the planner config.
var planner = new SequentialPlanner(kernel, new SequentialPlannerConfig { RelevancyThreshold = 0.5, Memory = kernel.Memory });
```

Feel free to explore these options and let us know if you have any further questions or need assistance.

**Comment by lemillermicrosoft** [comment]
Closing issue as designed.

**Comment by lemillermicrosoft** [comment]
Closing as designed.
