### ISSUE TITLE
.Net: Upgrade Microsoft.Graph to version >= 5.0.0 for compatibility with Microsoft.TeamsFx

### ISSUE THREAD

**Issue by jpiquot** [microsoft/semantic-kernel#1836]
Can we update the SemanticKernel reference to Microsoft.Graph (4.51.0) for compatibility with Microsoft.TeamsFx, which requires Microsoft.Graph version 5.6.0 or higher?

![image](https://github.com/microsoft/semantic-kernel/assets/6775094/bead6e5c-4ab4-4a72-9bba-d530dc4df9dd)

**Comment by nacharya1** [comment]
@gitri-ms  - can you take a look to increase the higher dependency version on MS Graph, semantic-kernel/dotnet/Directory.Packages.props at main · microsoft/semantic-kernel (github.com)](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/Directory.Packages.props#L40)

**Comment by Ryangr0** [comment]
This is by far not the only endpoint that the beta version of Graph adds. This would be extremely awesome and has far reaching consequences for business applications acting within Azure.

**Comment by formulahendry** [comment]
Have same issue here, and Microsoft.TeamsFx are used by lots of Teams App developers.
@nacharya1 @gitri-ms Do we have timeline for upgrading Microsoft.Graph?

**Comment by gitri-ms** [comment]
I don't have an ETA here, as this item was moved to the backlog and I've been asked to prioritize other work in the short term. It does look like this could be a non-trivial task, as there are a number of [breaking changes from v4 to v5](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md) so it will require a thorough test pass.

I'm okay keeping it assigned to me in case I can fit it in, but if it needs to be prioritized, might be best to distribute to someone else @nacharya1

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
