### ISSUE TITLE
.Net: Filtering out RestApiOperation before registering them in RegisterOpenApiSkillAsync

### ISSUE THREAD

**Issue by Poltuu** [microsoft/semantic-kernel#1837]
I would like to be able to filter `RestApiOperation` from a `OpenApiDocument` before registering them.
The current method `RegisterOpenApiSkillAsync` does not let me filter out skills before registering.

My use case is that I would like to add GET skills only to a kernel but NOT POTS/PUT/DELETE.

I can do a PR where I add another argument to the method to let the user filter, but that probably means to add it to all the methods from `KernelOpenApiExtensions`, and break the api.

**Comment by animeshj9** [comment]
This would be really helpful. Had an incident the other day when AI delete some work items from our ADO instance because the openapi.json file gave it information about the delete APIs as well.

**Comment by nacharya1** [comment]
@Poltuu  - thanks for this request, we will take look into this.

**Comment by Poltuu** [comment]
Super. I'm more than happy to help if needed

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
