### ISSUE TITLE
Service not found error when using QA sample

### ISSUE THREAD

**Issue by IIFE** [microsoft/semantic-kernel#1839]
**Describe the bug**
I've tried to use the example provided here:
https://github.com/thinktecture-labs/semantic-kernel-semanticsearch/tree/main

However when I plug in my OpenAI key and try to run it, I receive the following error:
```
Microsoft.SemanticKernel.KernelException: 'Service not found: Service of type Microsoft.SemanticKernel.AI.Embeddings.ITextEmbeddingGeneration and name <NONE> not registered.'
```

The error occurs immediately after:
```
var kernel = new KernelBuilder()
    .Configure(c =>
    {
        c.AddOpenAITextEmbeddingGenerationService("ada", "text-embedding-ada-002", config["OpenAi:ApiKey"]);
        c.AddOpenAITextCompletionService("davinci-openai", "text-davinci-003", config["OpenAi:ApiKey"]);
    })
    .WithMemoryStorage(store)
    .Build();
```

Any idea on what may be causing this error please?

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: Visual Studio 2022
 - NuGet Package Version: 0.17.230704.3-preview

**Comment by nacharya1** [comment]
@IIFE  - thanks for raising this. We will investigate into this behavior.

**Comment by mesgar** [comment]
I'm facing the same problem!
If I'm not wrong I think this is where the problem occurs: the cast
<img width="1043" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/10726024/fdfb8b33-4b4f-41b9-abad-2e79439bba90">

and thats why this: 
<img width="1048" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/10726024/209eb464-4deb-4224-b016-bf312214ff07">
isn't working!

**Comment by IIFE** [comment]
Yeah taking the `.WithMemoryStorage(memoryStore)` line doesn't cause the crash, so definitely something to do with setting the memory storage. Hopefully we can get a resolution to continue experimenting with the library. Thanks :)

**Comment by mesgar** [comment]
@IIFE 
A temporary workaround is to download the source code and add the following code to SemanticKernel > Kernel.cs file line 279 and compile it.
it works fine for me.
```csharp

// == Added by me ===============================================================
if (typeof(T) == typeof(ITextEmbeddingGeneration))
{
    name ??= this.Config.DefaultServiceId;

    if (!this.Config.TextEmbeddingGenerationServices.TryGetValue(name, out Func<IKernel, IEmbeddingGeneration<string, float>> factory))
    {
        throw new KernelException(KernelException.ErrorCodes.ServiceNotFound, $"'{name}' text embedding service not available");
    }

    var serv = factory.Invoke(this);
    return (T)serv;
}
// ==============================================================================
```

**Comment by craigomatic** [comment]
It looks like that repository (which was not created by the SK team) is using a very old version of SK:

<img width="562" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/146438/eb3b21d8-336c-46b1-9929-bee3369847a5">

In the bug report I see v17.x nuget listed, did you update to a more recent nuget?

**Comment by IIFE** [comment]
I'm using the latest version of SK, and still the same issue.

**Comment by solarblade60** [comment]
I am facing this issue as well, following the Semantic Kernel documentation: https://learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/?tabs=Csharp

```
// Set Simple kernel instance
IKernel kernel = KernelBuilder.Create();

Kernel.Builder
.WithAzureTextCompletionService(
    "my-finetuned-Curie",                   // Azure OpenAI *Deployment Name*
    "",    // Azure OpenAI *Endpoint*
    ""           // Azure OpenAI *Key*
)
.WithAzureChatCompletionService(
    "gpt-.5-turbo",                   // Azure OpenAI *Deployment Name*
    "",    // Azure OpenAI *Endpoint*
    ""           // Azure OpenAI *Key*
);

string skPrompt = @"WRITE EXACTLY ONE JOKE or HUMOROUS STORY ABOUT THE TOPIC BELOW

JOKE MUST BE:
- G RATED
- WORKPLACE/FAMILY SAFE
NO SEXISM, RACISM OR OTHER BIAS/BIGOTRY

BE CREATIVE AND FUNNY. I WANT TO LAUGH.
+++++

{{$input}}
+++++

";

var promptConfig = new PromptTemplateConfig
{
    Completion =
    {
        MaxTokens = 1000,
        Temperature = 0.9,
        TopP = 0.0,
        PresencePenalty = 0.0,
        FrequencyPenalty = 0.0,
    }
};

var promptTemplate = new PromptTemplate(
    skPrompt,
    promptConfig,
    kernel
);

var functionConfig = new SemanticFunctionConfig(promptConfig, promptTemplate);
var jokeFunction = kernel_2.RegisterSemanticFunction("FunSkill", "Joke", functionConfig);

var result = await jokeFunction.InvokeAsync("time travel to dinosaur age");
```

![image](https://github.com/microsoft/semantic-kernel/assets/22247230/5fe938fe-97c6-4665-a752-f1818f04e4b2)

**Comment by glahaye** [comment]
@IIFE Try using this code instead. It works for me:

var kernel = new KernelBuilder()
    .WithOpenAIChatCompletionService("gpt-3.5-turbo", ApiKey)
    .WithOpenAITextEmbeddingGenerationService("text-embedding-ada-002", ApiKey)
    .WithMemoryStorage(store)
    .Build();

**Comment by wrharper-AASP** [comment]
I think the idea is to not use an embedding on purpose.

**Comment by nacharya1** [comment]
Did the above resolve the issue for everyone or are you still facing the same behaviour?

**Comment by wrharper-AASP** [comment]
I'm not really sure why this is in my notfication history, but our team needs to REMOVE embeddings.
```
var kernel = new KernelBuilder()
.WithOpenAIChatCompletionService("gpt-3.5-turbo", ApiKey)
//.WithOpenAITextEmbeddingGenerationService("text-embedding-ada-002", ApiKey) <--- this shouldn't be required....
.WithMemoryStorage(store)
.Build();
```

**Comment by glahaye** [comment]
@IIFE We haven't heard back from you regarding this in a while and the problem can't be reproduced when using only Microsoft libraries so I am going ahead and closing this issue. Don't hesitate to ask for more information if you should need more, though.
