### ISSUE TITLE
OpenAI Service Error Encountered with Planner Functionality

### ISSUE THREAD

**Issue by chaowl2** [microsoft/semantic-kernel#1845]
I encountered an error while attempting to use the Planner function from the example notebook in Python. The error message indicates that the OpenAI service failed to complete the prompt due to exceeding the maximum context length of the model.

Error Message: Error: (<ErrorCodes.ServiceError: 6>, 'OpenAI service failed to complete the prompt', InvalidRequestError(message="This model's maximum context length is 4097 tokens, however you requested 5998 tokens (4998 in your prompt; 1000 for the completion). Please reduce your prompt; or completion length.", param=None, code=None, http_status=400, request_id=None))

 - OS: Mac
 - IDE: VS Code
 
![Screenshot 2023-07-05 at 10 22 53 AM](https://github.com/microsoft/semantic-kernel/assets/93566354/44bdfca1-916e-47c7-a139-fe473e3ecb02)

**Comment by nacharya1** [comment]
@chaowl2 - thanks for raising we will look into this.

**Comment by nacharya1** [comment]
@chaowl2 - can you confirm which model and service you are using?

**Comment by lemillermicrosoft** [comment]
Closing as no-repro.
