### ISSUE TITLE
Action Planner - Allow to exclude Plugins/Functions

### ISSUE THREAD

**Issue by sandeepvootoori** [microsoft/semantic-kernel#1851]
**Describe the bug**
Please create a way to exclude plugins/functions when using Action Planner. I am able to do this on Sequential and Stepwise Planners but not from Action Planner.

**Comment by sandeepvootoori** [comment]
@microsoftShannon

**Comment by nacharya1** [comment]
@sandeepvootoori  - thanks for raising this. we will take a look into this.
