### ISSUE TITLE
ry(...).getChildren is not a function when trying to create a new Plan through sk extension

### ISSUE THREAD

**Issue by dipteshbosedxc** [microsoft/semantic-kernel#1868]
**Describe the bug**
ry(...).getChildren is not a function when trying to create a new Plan through sk extension

**To Reproduce**
1. Go to 'sk extension in vs code'
2. Click on 'Plans section'
4. See error : ry(...).getChildren is not a function

**Expected behavior**
Should allow to create a plan as described in this video : https://www.youtube.com/watch?v=QqnaggRV3oE

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/138042190/ecfcd1bc-a5fd-41d7-bba4-5951e3a439d1)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - IDE: [e.g.  VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by evchaki** [comment]
@dipteshbosedxc  - this should now be fixed.
