### ISSUE TITLE
python: sync plan object with c#

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#1875]
Currently, the Python planner is less implemented than C#. 
It seems to be significantly behind in priority, so I'm planning to work on #1486 based on the current C# version. 
Is there another person working on it?

**Comment by alexchaomander** [comment]
Yes @awharrison-28 is working on this! Specifically bringing the Plan Object Model to Python

**Comment by joowon-dm-snu** [comment]
aha sounds good 🚀
