### ISSUE TITLE
Stepwise Planner doesn't updates Context Variables from actions

### ISSUE THREAD

**Issue by akshaykokane** [microsoft/semantic-kernel#1894]
**Describe the bug**
Stepwise Planner doesn't  take context variable from previous step/action

**To Reproduce**
1. Create 2 native functions 
2.  Function 1 fetches data and say sets context[Variable1]
3. Function 2 uses context[Variable1] to summarize the data
4. Create sstepwise plan using Stepwise Planner
5. Planner plans Action 1 -> Function1 and Action 2 -> Function2
5. [bug] Function 2, will not able to find context[Variable1], as Action 1, didn't update the original context

**Expected behavior**
Chaining of functions should respect context variables set by previous function

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] - Windows
 - IDE: [e.g. Visual Studio, VS Code] - Visual Studio
 - NuGet Package Version [e.g. 0.1.0] - 0.17.230704.3-preview

**Additional context**

**Comment by akshaykokane** [comment]
Fix : https://github.com/microsoft/semantic-kernel/issues/1894

**Comment by craigomatic** [comment]
> Fix : #1894

Off by one error :) I think you meant to link #1893

**Comment by lemillermicrosoft** [comment]
Right now it's kind of by design. The intent is that the model will populate parameters defined based on the previous step observation. We want to avoid 'hidden' outputs in contexts.
