### ISSUE TITLE
Update examples and notebooks to stop using text-davinci-003

### ISSUE THREAD

**Issue by gitri-ms** [microsoft/semantic-kernel#1896]
Several of our kernel examples and notebooks still use `text-davinci-003`, which is being retired by Azure OpenAI and is no longer supported for new deployments. We should update these to use a more current model.

**Comment by sneha-afk** [comment]
Would you suggest migrating to `gpt-3.5-turbo`?

**Comment by craigomatic** [comment]
> Would you suggest migrating to `gpt-3.5-turbo`?

For the samples, we will most likely move them to gpt-35-turbo as it's currently the lowest cost and most available model.

gpt-35-turbo is likely a good option for your solutions also. If you are using any of the planners you may want to consider gpt4 if you have access to it, as it will typically result in better outcomes.

**Comment by sneha-afk** [comment]
[According to OpenAI](https://platform.openai.com/docs/deprecations/2023-07-06-gpt-and-embeddings), the replacement for the models that served the v1/completions endpoint like the `davinci` text completion models will be `gpt-3.5-turbo-instruct`, which has not yet been released.

**Comment by glahaye** [comment]
PR for this: #2307

**Comment by glahaye** [comment]
Closed with PR #2307
