### ISSUE TITLE
ActionPlanner Bug on version: 0.17.230704.3-preview

### ISSUE THREAD

**Issue by EricChen-01** [microsoft/semantic-kernel#1898]
**Describe the bug**
Action Planner will not set the context variables to plan's auto generated 'parameter' field once the plan is started. 

**To Reproduce**
1. Create a basic Action Planner with any skill (a joke skill is sufficient). **MUST BE ON 0.17.230704.3-preview**
2. Print out the planner and check the 'parameter' field.
3. Within the joke skill ensure that you print out the context.
4. You will see that the variables in 'parameter' and the context are 2 totally different sets.

**Expected behavior**
Context printed out should be the same as the 'parameter' field in the planner.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/76068901/210fafc9-8325-4942-afe3-1ba8da16e074)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio]
 - NuGet Package Version [e.g. 0.17.230704.3-preview]

**Comment by nacharya1** [comment]
@EricChen-01 - thanks for raising this, we are looking into what you are observing.

**Comment by lemillermicrosoft** [comment]
Acknowledged. This is a bug.
