### ISSUE TITLE
Copilot Chat: How do we add plugins to Copilot sample app?

### ISSUE THREAD

**Issue by samleegithub** [microsoft/semantic-kernel#1900]
How do we add plugins to Copilot sample app?

I see references to Github, Clarna, Jira and Microsoft Graph in ChatController.cs but I don't see any documentation on how to enable them.

**Comment by TaoChenOSU** [comment]
Hi @samleegithub, 

Could you please clarify if you want to add more available plugins to Copilot Chat, or enable one of the existing ones from the UI?

If it is the former, you can only do it programmatically. We are working on making it easier for developers to create and add plugins to Copilot Chat. Stay tuned!

If it is the later, to enable a plugin, all you need to do is to click on the icon highlighted below and enable the plugins you would like to try out (note that some plugins will require you to enter additional credentials). Have fun!
![image](https://github.com/microsoft/semantic-kernel/assets/12570346/ef6d438d-aab5-44d8-a4de-522bc42601d3)

**Comment by samleegithub** [comment]
@TaoChenOSU Main reason for the ask was the former: I want to be able to add a custom plugin.

But thanks for letting me know how to enable a plugin in the UI. It'll let me test out stepwise planner with the plugins.

**Comment by TaoChenOSU** [comment]
Closing for now. Reopen if necessary.

**Comment by samleegithub** [comment]
@TaoChenOSU One more question. Can we add a feature in Copilot Chat to add new plugins using the UI? We could use the same flow that OpenAI uses for ChatGPT for plugins. You just need to specify the URL of the plugin API.

**Comment by TaoChenOSU** [comment]
@samleegithub Yes, we do have plans to convert CC plugins to ChatGPT plugin model: https://github.com/microsoft/semantic-kernel/issues/1964
