### ISSUE TITLE
Completion API not available anymore on Azure OpenAI service

### ISSUE THREAD

**Issue by wmeints** [microsoft/semantic-kernel#1918]
**Describe the bug**
We're using the Azure OpenAI Service on Azure to generate completions. As of July 5 2023 the completion models are no longer available. However, Semantic Kernel only seems to support completion based skills. This means that I can't use the library anymore.

I worked around the limitation by using OpenAI directly. But they too decided to deprecate the completion API. Lucky for us, OpenAI removes the support in 2024.

**Expected behavior**
Semantic Kernel should start supporting chat based skills instead of completion based skills.

**Desktop (please complete the following information):**
 - OS: Windows 11 22h2
 - IDE: VSCode
 - NuGet Package Version: 0.17.230704.3-preview

**Comment by craigomatic** [comment]
While you cannot deploy new text completion models (ie: text-davinci-003) you should be able to continue using already deployed instances until 2024 ([ref](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/legacy-models)) - however the chat completion models are cheaper, faster (with the exception of gpt4) and more capable, so this is a good time to swap over :)

The simplest option to use the chat completion models (gpt-35-turbo or gpt4) is to configure your kernel instance with the `WithAzureChatCompletion` extension method and this will allow your existing skills to continue to function as they did with text completion endpoints: https://github.com/microsoft/semantic-kernel/blob/9532c210bf4eb98f71fdb93f8112b7c4f6e33d8b/dotnet/src/Connectors/Connectors.AI.OpenAI/OpenAIKernelBuilderExtensions.cs#L236

There's a small sample over here that demonstrates this also: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example27_SemanticFunctionsUsingChatGPT.cs

**Comment by wmeints** [comment]
Thanks for checking it out!

**Comment by nacharya1** [comment]
@wmeints thanks for raising. Wanted to check this is working you for now.

**Comment by nacharya1** [comment]
@wmeints, closing this issue as we believe the sample above should help you out. Let me us know if you need anything else.
