### ISSUE TITLE
.Net: Planner: Possible alternative design (C#)

### ISSUE THREAD

**Issue by nschuessler** [microsoft/semantic-kernel#1920]
**Describe the bug**
In trying to implement a skill that returns a list of profile names i.e.

```
[SKFunction, Description("Returns a list of profile names.")]
Task<List<string>> GetProfileNamesAsync()
{
     // ...
}
```

The `SequentialPlanner` at least throws exception.  This is because only primitive types are supported. Upon search of the source code to return structured data (such as a list of items) apparently `JSON` serialization into `string` seems to be the technique.

Although it may have been considered and rejected already, I think it would be better to use dependency injection (i.e. `Microsoft.Extensions.DependencyInjection`) to provide extensibility for plans. Plans would take a collection of `ISkill`s and each skill would be annotated with `[SkFunction]` and `[Description]` attributes.  Skill method return types would be primitives or are interface that must be JSON serializable.

The reasons are:
1) The Semantic Kernel team probably doesn't want to take on all the work on building a parallel extensibility mechanism when there is one. Team resources could be better spent on the planning and AI portions of the project.
2) Many problems have already been worked out by the dependency injection. e.g. generics, complex structures.
3) Serializing/deserializing json on local API boundaries, including data validation on parsed input, would lead to serious performance problems
4) Serializing to JSON loses type safety that dependency injection infrastructure can handle.  E.g.

```
[SKFunction, Description("Sorts profile names.")]
Task<List<string>> SortProfileNames(List<string> profileNames)
{
    // ...
}
```

JSON serialization can be enforced on various objects by using the `where x: IJsonSerializable` with the SDK defining `IJsonSerializable`

p.s. I would recommend async API that also allows serialization to and from byte streams (for performance reasons).

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: Visual Studio
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by nacharya1** [comment]
@shawncal tagging for follow up

**Comment by matthewbolanos** [comment]
@alliscode, is this now supported now that we have complex object support for planners?

**Comment by matthewbolanos** [comment]
Closing since plugins now use a DI model on the kernel
