### ISSUE TITLE
Planning: More built in plans to handle basic operations

### ISSUE THREAD

**Issue by nschuessler** [microsoft/semantic-kernel#1921]
In creating a simple skill to add two numbers, I had to add a helper skill to convert from `int` to `double` (in C#). Here is the code:

```
namespace Something
{
    public class LocalSkills
    {
        public LocalSkills()
        {
        }

        [SKFunction, Description("Converts a number to a double")]
        public double ConvertToDouble(int number)
        {
            return (double)number;
        }

        [SKFunction, Description("Adds two numbers together")]

        public double Add(double number1, double number2)
        {
            return number1 + number2; 
        }
    }
}
```

This is in use with `SequentialPlanner`.

If you ask `Please add 4.0 and 6.0` the `Add` function is sufficient.
But if you ask `Please add 4 and 6` then the `ConvertToDouble` function is required otherwise an exception is thrown.
IMHO these should be part of the standard skills so duplicating this by each developer is not required.

**Comment by nschuessler** [comment]
Actually, on the latest library (currently 0.17.230704.3-preview) this actually works now.  Checking the version that was with the original sample to see if it is there.

**Comment by nschuessler** [comment]
I don't have a repro now :( sorry for the spam.

**Comment by nacharya1** [comment]
No worries, glad to hear this is now working for you.
