### ISSUE TITLE
Using WebSearchEngineSkill in Planner not working

### ISSUE THREAD

**Issue by mohamedcherifmo** [microsoft/semantic-kernel#193]
**Describe the bug**
I added the WebSearchEngineSkill to the planner (including it as a NativeSkill), the plan comes out correctly however when executing the plan the following error occurs:
An error occurred when attempting to access a disposed object named 'System.Net.Http.HttpClient'

**To Reproduce**
1. Add the following to the RegisterNativeSkills
` if(ShouldLoad(nameof(WebSearchEngineSkill), skillsToLoad))
        {
            using BingConnector connector = new("BING_API_KEY");
            var webSearchSkill = new WebSearchEngineSkill(connector);
            _ = kernel.ImportSkill(webSearchSkill, nameof(WebSearchEngineSkill));
        }`
2. Create a plan with the following body
`{
    "value": "What's the tallest building in Europe?",
    "skills": ["WebSearchEngineSkill", "FunSkill", "summarizeskill"]
}`
3. Invoke the plan

**Expected behavior**
The result should be displayed from search

**Comment by mohamedcherifmo** [comment]
I fixed the issue by adding the HttpClient in SearchAsync instead of in the constructor
The new constructor now is
`
public BingConnector(string apiKey, ILogger<BingConnector>? logger = null)
    {
        this._logger = logger ?? NullLogger<BingConnector>.Instance;
        this._apiKey = apiKey;
    }`

and the function is:
`
public async Task<string> SearchAsync(string query, CancellationToken cancellationToken = default)
    {
        Uri uri = new($"https://api.bing.microsoft.com/v7.0/search?q={Uri.EscapeDataString(query)}&count=1");
        this._logger.LogDebug("Sending request: {0}", uri);
        try
        {
            var newhttpClient = new HttpClient();
            newhttpClient.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", this._apiKey);
            HttpResponseMessage response = await newhttpClient.GetAsync(uri, cancellationToken);
            response.EnsureSuccessStatusCode();
`

**Comment by dluc** [comment]
@lemillermicrosoft could you take a look? if this is happening here, the same bug might be with other dependencies created by ctors in other skills

**Comment by dluc** [comment]
@evchaki new bug to track

**Comment by lemillermicrosoft** [comment]
It appears this is specific to `KernelHttpServer` and @mohamedcherifmo was able to get around it. Another potential solution is to manage the lifetime of the connector such that it isn't disposed. I don't think we will be doing more with `KernelHttpServer` so will close this for now. cc @craigomatic for visibility.
