### ISSUE TITLE
Add Log Traces Messages

### ISSUE THREAD

**Issue by GalRabin** [microsoft/semantic-kernel#1949]
# Description

## Is your feature request related to a problem? Please describe.
The application currently lacks sufficient LogTrace messages related to OpenAI calls. Without these, it's difficult to efficiently debug and monitor applications that we intend to deliver to our customers.

## Describe the solution you'd like
I propose that we add more LogTrace messages that will indicate when specific OpenAI calls are made. These should be added to the following invocations:

1. Function Invoke
2. Kernel Invoke
3. Planner Invoke
4. Chain Invoke

## Describe alternatives you've considered
Without adding these LogTrace messages, our ability to debug and monitor our applications effectively is compromised.

## Additional context
The inclusion of these LogTrace messages would greatly enhance our visibility into the operation of these key parts of our software, thereby allowing us to ensure maximum functionality and reliability for our customers.

**Comment by shawncal** [comment]
We believe this is resolved with #1905. Closing; please create a new Issue if more tracing is needed. Thanks for the feedback!
