### ISSUE TITLE
Can one use Skills with AddOpenAIChatCompletion?

### ISSUE THREAD

**Issue by Woland2k** [microsoft/semantic-kernel#195]
**Describe the bug**
It looks like ChatCompletion was introduced in the latest checkin, however it doesn't seem to support skills. Is that by design or would that be enabled in the future?

**Desktop (please complete the following information):**
 - NuGet Package Version 0.9.61

**Comment by evchaki** [comment]
@Woland2k can you provide a use case for doing this?  You can use the client directly also for this.

**Comment by Woland2k** [comment]
All I really after is ability to use gpt-3.5-turbo model with skills defined same way as for text completion.

**Comment by microsoftShannon** [comment]
@dluc can you take a look?

**Comment by Woland2k** [comment]
> > @Woland2k can you provide a use case for doing this? You can use the client directly also for this.
> 
> A usecase in my eyes would be, so I could tell the model to
> 
> * go create files.
> * go through files and
> * make embedings for them, and so on.
> 
> (or am I on a completly wrong path and it already can do these things?)

Not sure we're talking about the same thing ... it might be that chat completion is not suitable for skills definition.

**Comment by dluc** [comment]
@Woland2k this is now possible, e.g. from https://github.com/microsoft/semantic-kernel/blob/main/samples/dotnet/kernel-syntax-examples/Example26_SemanticFunctionsUsingChatGPT.cs

```csharp
IKernel kernel = new KernelBuilder().WithLogger(ConsoleLogger.Log).Build();

// Note: we use Chat Completion and GPT 3.5 Turbo
kernel.Config.AddAzureChatCompletionService("id", "gpt-35-turbo", "https://....openai.azure.com/", "...API KEY...");
// ^^^

var func = kernel.CreateSemanticFunction("List the two planets closest to '{{$input}}', excluding moons, using bullet points.");

var result = await func.InvokeAsync("Jupiter");
Console.WriteLine(result);
```
