### ISSUE TITLE
Copilot Chat: Please update the documentation to change directory to webapp folder, prior running yarn commands (this is the folder that contains package.json)

### ISSUE THREAD

**Issue by dipteshbosedxc** [microsoft/semantic-kernel#1951]
**Describe the bug**

**To Reproduce**
1. Go to '[...](https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/README.md)'
2. Click on 'Line 109'

**Expected behavior**
Please mention in the documentation that the yaml commands will look for package.json file that is located inside the webapp folder, and not in webapi. This could be confusing for those that are updating the .env (environment file) manually and not through the terminal.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/138042190/79befdd4-9050-4b88-a253-2dc4823f9478)

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by TaoChenOSU** [comment]
Issue addressed by https://github.com/microsoft/semantic-kernel/pull/1953.
