### ISSUE TITLE
Python: Training NLP model using a CSV data source.

### ISSUE THREAD

**Issue by IIFE** [microsoft/semantic-kernel#1968]
Hi.

Does SK provide a way to train the NLP model (e.g., `text-davinci-003`) using a CSV data source? Similar to how `langchain` CSV agent from https://python.langchain.com/docs/modules/agents/toolkits/csv. Doesn't have to be CSV in particular, JSON or another structured data source would be good as well.

Thanks.

**Comment by am831** [comment]
Is anyone already working on this? If not can I work on this? Thanks

**Comment by nacharya1** [comment]
@am831 it would be great if you can work on this, would love to see a pr

**Comment by am831** [comment]
@nacharya1 I opened a draft PR yesterday, I also just read your blog post about using natural language to execute SQL queries. I am curious how these two features might fit together within the kernel since they are quite similar

**Comment by nacharya1** [comment]
@am831 can you link number here and we can evaluate
cc: @crickman

**Comment by am831** [comment]
@nacharya1 Yes it's PR #2385

**Comment by lemillermicrosoft** [comment]
Great idea. Closing for now as not part of roadmap.
