### ISSUE TITLE
Python: C# porting for multiple native function arguments

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#1977]
Porting #1195 to Python makes native functions much easier to use.

**Comment by evchaki** [comment]
@joowon-dm-snu  - thank you for bringing this up.  It would be great to have this in Python.  Feel free to do a PR to bring this over.

**Comment by matthewbolanos** [comment]
Closing as a duplicate of [#3307](https://github.com/microsoft/semantic-kernel/issues/3307)
