### ISSUE TITLE
Method not found: 'Int32 Microsoft.SemanticKernel.AI.TextCompletion.CompleteRequestSettings.get_MaxTokens()'.

### ISSUE THREAD

**Issue by rafael-sotelo** [microsoft/semantic-kernel#1980]
This is my configuration

`var kernel = Kernel.Builder
                .WithOpenAITextCompletionService("text-davinci-003", openKey)
                .WithLogger(logger)
                .Build();`

And when I try:
`var planner = new SequentialPlanner(kernel);
        var goal = command.Problem;
        var plan = await planner.CreatePlanAsync(goal);`
        
        Im getting the error:
        
        Method not found: 'Int32 Microsoft.SemanticKernel.AI.TextCompletion.CompleteRequestSettings.get_MaxTokens()'.

What I'm missing ?

**Comment by feiyun0112** [comment]
did you use lastest nuget packages? 

MaxTokens had been changed to `int?`  type

[https://github.com/microsoft/semantic-kernel/commit/450f1d3a11eb95d6975da33f581d3997bed42906](https://github.com/microsoft/semantic-kernel/commit/450f1d3a11eb95d6975da33f581d3997bed42906)
