### ISSUE TITLE
Python: Add Redis memory connector 

### ISSUE THREAD

**Issue by sneha-afk** [microsoft/semantic-kernel#1981]
I would like to implement the Redis memory connector within Python to match up with the existing connector in .NET. Thank you!

**Comment by alexchaomander** [comment]
Go for it! We would love to see it!

**Comment by evchaki** [comment]
@sneha-afk  - once you create the PR please add the link back in here for tracking.

**Comment by sneha-afk** [comment]
> @sneha-afk - once you create the PR please add the link back in here for tracking.

Hello, the PR is #2132 , thank you!
