### ISSUE TITLE
Python: gpt-4 not available for chat_gpt_api.py

### ISSUE THREAD

**Issue by xieliaing** [microsoft/semantic-kernel#1983]
**Describe the bug**
changed "gpt-3.5-turbo" to "gpt-4" in chat_gpt_api.py file at line 21:

kernel.add_chat_service(
    "chat-gpt", sk_oai.OpenAIChatCompletion("gpt-3.5-turbo", api_key, org_id)
)

**To Reproduce**
1. Go to 'chat_gpt_api.py' example
2. Click on line 21, change "gpt-3.5-turbo" to "gpt-4"
3. in CLI, type in "python chat_gpt_api.py" to execute the file
4. You will see User:> and type some messages to start the chat
5. The system will return the following message:
```
Mosscap:> Error: (<ErrorCodes.ServiceError: 6>, 'OpenAI service failed to complete the chat', InvalidRequestError(message='The model: `gpt-4` does not exist', param=None, code='model_not_found', http_status=404, request_id=None))
```

**Expected behavior**
Expect the chatbot return message from OpenAI's gpt4 model 

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/9838639/f2b6bcbe-5b98-4043-9601-403ceebc6cf3)

**Platform**
 - OS: Windows10 
 - IDE: CLI
 - Language:  Python
 - Source: main branch of the repository as of 2023-07-12

**Additional context**
tried "gpt-4", "gpt-4-0613", "gpt-4-32k" and "gpt-4-32k-0613", none of them work. Based on OpenAI [GPT guideline](https://platform.openai.com/docs/models/gpt-4), gpt-4 shares the same end point with gpt-3-turbo, so I expect gpt-4 should be working in the example as well.

**Comment by xieliaing** [comment]
> 

I am a paying customer of OpenAI for both API and ChatGPT, and I can use GPT4 using OpenAI's API in python.

**Comment by nacharya1** [comment]
@xieliaing - thanks for raising this we will investigate to see if can repo this behaviour.

**Comment by awharrison-28** [comment]
Hi @xieliaing I am unable to repro your issue. I changed my lines 19-21 of `chat_gpt_api.py` to 

````
api_key, org_id = sk.openai_settings_from_dot_env()
kernel.add_chat_service(
    "gpt-4", sk_oai.OpenAIChatCompletion("gpt-4", api_key, org_id)
)
```

Is this still an issue for you?

**Comment by xieliaing** [comment]
> Hi @xieliaing I am unable to repro your issue. I changed my lines 19-21 of `chat_gpt_api.py` to
> 
> ```
> api_key, org_id = sk.openai_settings_from_dot_env()
> kernel.add_chat_service(
>     "gpt-4", sk_oai.OpenAIChatCompletion("gpt-4", api_key, org_id)
> )
> ```
> 
> Is this still an issue for you?

interesting, I still encounter the same ERROR message as before.

**Comment by xieliaing** [comment]
Just got notice from OpenAI that as part of GA of GPT-4, I can now use GPT-4 from API. So even if GPT-4 API has been available to paying customers since July 6th, it is not available at once for all paying customer. Just tried and the sample works under GPT-4 now, closing the issue.

```python
(base) D:\Temp\semantic-kernel-xl\python\samples\kernel-syntax-examples>python chat_gpt4_api.py
User:> hello
Mosscap:> Greetings, kind soul! It is indeed a pleasure to make your acquaintance on this fine occasion. How might the humble Mosscap be of service to you today? Is there a particular query that has brought you to my digital doorstep, or perhaps a need for guidance that has led you to seek my counsel? Regardless of the reason, rest assured that I am here to assist you to the best of my abilities.
```
