### ISSUE TITLE
Python: API documentation

### ISSUE THREAD

**Issue by appvin** [microsoft/semantic-kernel#1985]
Hi, everyone, SK is powerful but I feel a little cluttered about the documents. For example, I didn't know textchunker before I searched in this repo. 
Is there one document contains all the modules SK has? like Langchain does:
![image](https://github.com/microsoft/semantic-kernel/assets/24713659/65b77baa-cbc1-49cc-809f-1d3351f2045e)
Thanks

**Comment by nacharya1** [comment]
@matthewbolanos  - sharing the feedback and suggestion on the docs as input for the updates you are working on.

**Comment by matthewbolanos** [comment]
Thanks for adding me; we are in progress of adding API reference documentation. Once that's up we can close this issue.

**Comment by matthewbolanos** [comment]
We now have API references for .NET which can be found here: https://learn.microsoft.com/en-us/dotnet/api/microsoft.semantickernel?view=semantic-kernel-dotnet 

We're currently tracking the python API reference here: #2899

**Comment by moonbox3** [comment]
Adding some Python samples here that need updating: https://learn.microsoft.com/en-us/semantic-kernel/prompts/saving-prompts-as-files?tabs=python, cc: @matthewbolanos

**Comment by moonbox3** [comment]
Initial Python docs were published.
