### ISSUE TITLE
Python: Add CosmosDB Memory Connector

### ISSUE THREAD

**Issue by SebasX5** [microsoft/semantic-kernel#1996]
I would like to create the CosmosDB connector in the Python to match with the connector in the .NET

**Comment by shawncal** [comment]
CosmosDB is being removed from .Net, in favor of Azure Congitive Search which is better suited for vector serach.

**Comment by human06** [comment]
> CosmosDB is being removed from .Net, in favor of Azure Congitive Search which is better suited for vector serach.

AM new to Semantic, however, I have done all my implementation with Cosmo,  Do you recommend rewriting 
and if you can explain why Cognative search is better than Cosmo !? thx
