### ISSUE TITLE
Python: Add SQlite Memory Connector

### ISSUE THREAD

**Issue by 1yefuwang1** [microsoft/semantic-kernel#1998]
I find from feature matrix that SQlite connector is supported in C# but not in Python yet.
I'd like to contribute if no one is already working on it.

**Comment by alexchaomander** [comment]
Go for it! Would be a great addition.

**Comment by 1yefuwang1** [comment]
Just to give an update. I think I can get a PR ready this week.

**Comment by 1yefuwang1** [comment]
Hi @awharrison-28 @nacharya1, do you mind reviewing the PR at your convenience?

**Comment by nacharya1** [comment]
@1yefuwang1  FYI: We recently updated our contributing guidelines [here](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#adding-plugins-and-memory-connectors , stating we are not directly adding plugin and connectors directly into the SDK repository. We are encouraging the community to host their own plugins and connectors separately in their own repositories. At the time we are exploring how we can provide a way to discover plugins and connectors and should have an update soon. I am going to close this issue given our change in contribution guidelines.
