### ISSUE TITLE
Using Azure OpenAI: The request is not valid, HTTP status: 400

### ISSUE THREAD

**Issue by hunterjam** [microsoft/semantic-kernel#2001]
**Describe the bug**
I have signed up for Azure Open AI. I have created an Azure OpenAI resource. I created deployments for the models: gpt-35-turbo and text-embedding-ada-002. I successfully tested the Chat and Completions within Azure AI Studio playground. I configured the settings.json file with the model, endpoint, and apikey. When I run any of the dotnet notebooks, I encounter an error when making a call to the kernel:
Error: Invalid request: The request is not valid, HTTP status: 400
OR 
Error: Microsoft.SemanticKernel.AI.AIException: Invalid request: The request is not valid, HTTP status: 404

**To Reproduce**
1. Run the 0-AI-settings.ipynb (bool useAzureOpenAI = true;) I also tried both deployment models. 
2. Run the 00-getting-started.ipynb

**Expected behavior**
I expect to see a joke using "time travel to dinosaur age"

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/31451884/e105b81d-5b01-49a9-8fa4-d885f74ec6af)
![image](https://github.com/microsoft/semantic-kernel/assets/31451884/706a39d6-f65d-4579-be10-44e365302436)

**Platform**
 - OS: [Windows]
 - IDE: [VS Code]
 - Language: [C#]
 - Source: [nuget: Microsoft.SemanticKernel, 0.17.230626.1-preview]

**Additional context**
I did not experience any issues using an Open AI key.

**Comment by samleegithub** [comment]
Since you are using gpt-35-turbo, you should change "WithAzureTextCompletionService" to "WithAzureChatCompletionService".

**Comment by hunterjam** [comment]
@samleegithub --- Perfect. Thank you.

For the 06-memory-and-embeddings.ipynb, I had to modify the deployment parameter within WithAzureTextEmbeddingGenerationService from "text-embedding-ada-002" to the variable model. Otherwise, a 404 error is generated. 

Original:
![image](https://github.com/microsoft/semantic-kernel/assets/31451884/a276c4a8-8fc2-4823-80c1-b938a05be34e)

Should be:
![image](https://github.com/microsoft/semantic-kernel/assets/31451884/8dbe8efa-7402-4feb-80f9-83d27fba3d59)
