### ISSUE TITLE
Copilot Chat: Extend OcrOptions in Copilot sample app to include Cognitive Services / Form Recognizer 

### ISSUE THREAD

**Issue by davearlin** [microsoft/semantic-kernel#2008]
I've recently added in the ability to read in rasterized image formats as part of the document import functionality within the Copilot sample application using the Tesseract open source library.  I'd like to add Cognitive Services as another option and possibly some of the other major cloud provider OCR services since I occasionally work with those when building .NET backends.

**Comment by TaoChenOSU** [comment]
Hi @davearlin, thanks for your contribution! Please submit your PR when it's ready.

**Comment by glahaye** [comment]
Resolved with https://github.com/microsoft/chat-copilot/pull/26
