### ISSUE TITLE
SK and Model Compatibility

### ISSUE THREAD

**Issue by Escoto** [microsoft/semantic-kernel#2015]
Hi!

Working with `Azure OpenAI` I had some troubles getting the samples to work (`..\samples\notebooks\dotnet\00-getting-started.ipynb`). I tried multiple Models and I could only make the samples work with the `Davinci Models`. Is it that the `SK` only works with Davinci? or is there a list of compatible Models I didn't find? 

If it is the case that `SK` only works with `Davinci Models`, can we add that as a requirement?

**Comment by nacharya1** [comment]
@Escoto  thanks for letting us know, we are looking into updating the samples to reflect text completion models.

**Comment by matthewbolanos** [comment]
@momuno, would you be able to update the requirements in the notebooks to make it clear which models are supported?

**Comment by momuno** [comment]
Yes.  It looks right now that text-completion models are no longer available via Azure OpenAI.  Only in OpenAI.  The notebooks may need a bigger revamp than just a supported-model update.  

To address this specific issue, I can put a not in the samples about this and see if I can suggest a temporary workaround... like only use OpenAI?

**Comment by nacharya1** [comment]
that works @momuno , @matthewbolanos any concerns?

**Comment by momuno** [comment]
Addressing specific dotnet issue and azure openai models here: https://github.com/microsoft/semantic-kernel/pull/2815
More expansive model compatibility consolidation task created here: https://github.com/microsoft/semantic-kernel/issues/2814

**Comment by markwallace-microsoft** [comment]
We have to move away from text completion models by the end of the year.

**Comment by matthewbolanos** [comment]
Samples have been moved to chat completion models
