### ISSUE TITLE
Java: Blog post announcement for Java SK release 0.2.6-alpha

### ISSUE THREAD

**Issue by brunoborges** [microsoft/semantic-kernel#2025]
```[tasklist]
### Tasks
- [x] Access to the SK instance in DevBlogs
- [x] Write down draft
- [x] Review draft
- [x] Publish blog
- [x] Announce publicly
```

**Comment by brunoborges** [comment]
@alexchaomander can you please grant @johnoliver `Author` role to the SK instance on DevBlogs please?

**Comment by alexchaomander** [comment]
@shawncal @matthewbolanos ^ Can you grant that to John?

**Comment by agoncal** [comment]
@brunoborges looks like you can close this one ;o) https://devblogs.microsoft.com/semantic-kernel/introducing-semantic-kernel-for-java/
