### ISSUE TITLE
GitHub Repo Q&A Bot Sample Public git download errors 

### ISSUE THREAD

**Issue by arikbidny** [microsoft/semantic-kernel#2041]
Hi, 
After successfully configuring Azure OpenAI with ChatGPT3.5 Turbo and Ada for embedding, I am encountering an error while downloading a public repository.

**Expected behavior**
To download and embed a public repository

**Screenshots**
<img width="1928" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/10271005/ae85ebbd-5cf3-4c67-8554-ea298db21624">

**Platform**
 - OS: MAC
 - IDE: VSCode

**Comment by TaoChenOSU** [comment]
Hello @arikbidny, 

Thanks for reporting the issue! 

We had taken a note on the issue and worked on a PR: https://github.com/microsoft/semantic-kernel/pull/2117.

The PR should solve the problem you reported. Please try again after the PR is merged. Let us know if you see more issues :)

Thanks!

**Comment by glahaye** [comment]
@arikbidny please pull the latest version of the code. It contains the fix to your problem.

If you still encounter problems, feel free to either re-open this issue or create a new one.
