### ISSUE TITLE
Python: Code Interpreter Plugin

### ISSUE THREAD

**Issue by samleegithub** [microsoft/semantic-kernel#2062]
Hello Semantic Kernel Team!

Are there any plans to implement a sandboxed python execution plugin similar to OpenAI's Code Interpreter plugin?

https://openai.com/blog/chatgpt-plugins#code-interpreter

https://www.youtube.com/watch?v=O8GUH0_htRM

https://www.youtube.com/watch?v=_njf22xx8BQ

**Comment by samleegithub** [comment]
@alexchaomander Was this the open-source implementation of the Python Code Interpreter Plugin that you were looking into?

https://github.com/iamgreggarcia/codesherpa

**Comment by alexchaomander** [comment]
Yup it's that one! Would be great to have an SK implementation!

**Comment by matthewbolanos** [comment]
Closing since users should leverage OpenAI's code interpreter
