### ISSUE TITLE
Copilot Chat: Python: Is the documentation and code updated for the option to add custom plugin - samples/apps/copilot-chat-app

### ISSUE THREAD

**Issue by dipteshbosedxc** [microsoft/semantic-kernel#2066]
**Describe the bug**
Wanted to check if the code for samples/apps/copilot-chat-app is updated that enables the option to add custom plugin manifest files / HTTP url as mentioned in this video - https://www.youtube.com/watch?v=W_xF8PcdT78

**To Reproduce**

**Expected behavior**
Ability to add a custom plugin as described in the video here: https://youtu.be/W_xF8PcdT78?t=157

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/138042190/f3bc103b-a3f9-48bb-9d8e-a9bf73689248)

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by alexchaomander** [comment]
This is going to be reflected in the new Chat Copilot app here within the next couple days!

https://github.com/microsoft/chat-copilot/tree/main

**Comment by dipteshbosedxc** [comment]
> This is going to be reflected in the new Chat Copilot app here within the next couple days!
> 
> https://github.com/microsoft/chat-copilot/tree/main

![image](https://github.com/microsoft/semantic-kernel/assets/138042190/7e719e0c-19d2-432a-9ead-8e89e58c1b7d)
I am trying the Math plugin but it throws an error as attached. Any recommendation on troubleshooting such issues...

**Comment by dipteshbosedxc** [comment]
Could this be a case of missing StepwisePlanner in the new copilot that supports custom plugin?

**Comment by matthewbolanos** [comment]
We are actively taking a look at this! @teresaqhoang for visibility.

**Comment by teresaqhoang** [comment]
@dipteshbosedxc The `Cannot convert undefined or null to object` error is fixed in this PR: https://github.com/microsoft/chat-copilot/pull/72, will update this thread once it's merged.

I'm also working on Planner stabilization, which should handle the other 400 error and you can track that work here: https://github.com/orgs/microsoft/projects/852?pane=issue&itemId=32649122

**Comment by teresaqhoang** [comment]
@dipteshbosedxc all the planner stabilization work should be in now! If you pull the latest from main in https://github.com/microsoft/chat-copilot, these errors should be transient.

**Comment by teresaqhoang** [comment]
Closing this issue as resolved. Feel free to reopen if you continue to run into any issues.
