### ISSUE TITLE
How to change system message when use skprompt.txt with Chat Completion API

### ISSUE THREAD

**Issue by heavenwing** [microsoft/semantic-kernel#2068]
When use semantic function which from skprompt.txt file, how to change system message?

I noticed that the default system message always is: You are an AI assistant that helps people find information.

**Comment by nacharya1** [comment]
@heavenwing can you confirm if you are referring to the copilot chat app or is this question in reference to something else? Thanks

**Comment by heavenwing** [comment]
@nacharya1 I'm not referring to any sample app. 

When I run debug semantic functions in VSCode using the Semantic Kernel extension, I found the output window print below information:

```
AI Provider: AzureOpenAI
Model: gpt-35-turbo-0301
Chat System Message: You are an AI assistant that helps people find information.
Execute: AdoSkill.UserStoryImproverEN
```

But I cannot change this Chat System Message from the semantic function config file (config.json).

Also I wonder when I use these semantic functions in my AI-apps, if it use this default system message.

**Comment by nacharya1** [comment]
@matthewbolanos can you take a look into this question?
