### ISSUE TITLE
Implement online debugger and telemetry similar to LangSmith

### ISSUE THREAD

**Issue by alexminza** [microsoft/semantic-kernel#2070]
https://docs.smith.langchain.com/#introduction

> LangSmith is a platform for building production-grade LLM applications.

> It lets you debug, test, evaluate, and monitor chains and intelligent agents built on any LLM framework and seamlessly integrates with LangChain, the go-to open source framework for building with LLMs.

> LangSmith is developed by LangChain, the company behind the open source LangChain framework.

* Overview https://docs.smith.langchain.com/overview
* Quick Start https://docs.smith.langchain.com/evaluation/quickstart

**Comment by evchaki** [comment]
@alexminza  - we just added a number of PR check-ins for telemetry #2218 .  Let us know if this solves your needs.

**Comment by alexminza** [comment]
It seems that LangSmith could be integrated with Semantic Kernel:

> LangSmith lets you instrument any LLM application, no LangChain required. This aids in debugging, evaluating, and monitoring your app, without needing to learn any particular framework's unique semantics.

https://github.com/langchain-ai/langsmith-cookbook/blob/main/tracing-examples/traceable/tracing_without_langchain.ipynb
