### ISSUE TITLE
'KernelConfig' does not contain a definition for 'AddAzureOpenAICompletionBackend'

### ISSUE THREAD

**Issue by arix008** [microsoft/semantic-kernel#208]
Getting this error when trying to run the notebooks in VS Code.

Error: (14,19): error CS1061: 'KernelConfig' does not contain a definition for 'AddAzureOpenAICompletionBackend' and no accessible extension method 'AddAzureOpenAICompletionBackend' accepting a first argument of type 'KernelConfig' could be found (are you missing a using directive or an assembly reference?)
(16,19): error CS1061: 'KernelConfig' does not contain a definition for 'AddOpenAICompletionBackend' and no accessible extension method 'AddOpenAICompletionBackend' accepting a first argument of type 'KernelConfig' could be found (are you missing a using directive or an assembly reference?)

The notebooks were running earlier but suddenly it is throwing this error - not sure what I'm missing. Please see below screenshot.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/96107082/228504337-d500584b-b96f-4328-8edf-30a1f2b50a56.png">

**Comment by alexchaomander** [comment]
If you re using the newest nuget version `0.9.61.1-preview`, the APIs have changed. This PR updates them: https://github.com/microsoft/semantic-kernel/pull/206

**Comment by tynguyen** [comment]
This also happened to me this afternoon. After looking around, I found that the following line installs the latest version of Microsoft.SemanticKernel.
```
#r "nuget: Microsoft.SemanticKernel, *-*"
```
To fix the issue, you can simply checkout this repo to get updated notebooks.

**Comment by alexchaomander** [comment]
#206 landed! Closing this issue

**Comment by aditmer** [comment]
The APIs in the Getting-Started-Notebook are not compatible with version 0.9 of the Nuget package.  I had to specify 0.8.56.1-preview to get it to run.

**Comment by alexchaomander** [comment]
@aditmer This is a good catch! That notebook needs to be updated to include the change in the API

**Comment by arix008** [comment]
Thanks everyone! It was indeed the version of nuget that was causing this issue. The proper version as pointed out by @aditmer is working fine.
