### ISSUE TITLE
Request: Support Complex C# objects for SKFunction input parameters and output return types

### ISSUE THREAD

**Issue by efficienthacks** [microsoft/semantic-kernel#2081]
I've asked this on the public community office hours and it looks like there isn't anything in development yet for this.  This issue is similar to https://github.com/microsoft/semantic-kernel/pull/1195 by @stephentoub , however instead of having multiple input parameters with primitive type, I'd like to define methods that have complex objects (that are easily serialized/deserialized) as input params and return values.

Here is an example:
```cs
    [SKFunction]
    //Is there any way to support POCO return types so that it automatically serializes the object?
    public string GetReportsOfAlias([Description("The aliases to get direct reports of"), SKName("input")] string alias)
    {
        //Would have liked to return "IEnumerable<Employee>" instead of a json string
        return JsonSerializer.Serialize(_reports[alias]);
    }
```

It would be nice to just have:
```cs
    [SKFunction]
    public IEnumerable<Employee> GetReportsOfAlias([Description...] string alias)
    {
        return _reports[alias];
    }
```

and then have the library automatically deserialize the input and serialize the output with JsonSerializer

A full working example is in a Polyglot notebook in case there is another suggestion to go about this: https://gist.github.com/efficienthacks/775bb94d727abbb7aec4b699f981dfac

My actually scenario consists of multiple of these 'native' methods, so without this feature, I'd have to create new methods, change the input/output parameters, then manually deserialize input at the start the method and serialize the output at the end of the method.

**Comment by efficienthacks** [comment]
Idea for the auto-serialization of return values: let the user override the way the return values get Converted.  e.g. allow some form of customization in SKFunction::GetParameterMarshalerDelegate

Not sure how to auto-deserialize input values yet

**Comment by evchaki** [comment]
@shawncal - can you add the plans for this.

**Comment by dmytrostruk** [comment]
Hi @efficienthacks , in this PR (https://github.com/microsoft/semantic-kernel/pull/2864) we have added FunctionResult/KernelResult models which will allow to return not only strings but complex types as well. Here is usage example:
https://github.com/microsoft/semantic-kernel/blob/07e792df4df7f3f9377dc84477d944e7cf70bd2b/dotnet/src/SemanticKernel.UnitTests/Functions/SKFunctionTests2.cs#L985-L1004

Could you please confirm if this implementation covers your case?

**Comment by dmytrostruk** [comment]
@efficienthacks I will close this issue, since it looks like your scenario is already covered, as mentioned in previous comment, and currently exists in `main` branch. If current functionality doesn't cover your case, feel free to re-open this issue or create a new one. Thanks!
