### ISSUE TITLE
Python: AzureCognitiveSearch Connector tests report an unclosed client

### ISSUE THREAD

**Issue by shawncal** [microsoft/semantic-kernel#2087]
> Fatal error on SSL transport
> protocol: <asyncio.sslproto.SSLProtocol object at 0x000002BCE91574C0>
> transport: <_SelectorSocketTransport closing fd=956>
> Traceback (most recent call last):
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 924, in write
>     n = self._sock.send(data)
> OSError: [WinError 10038] An operation was attempted on something that is not a socket
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
>     self._transport.write(chunk)
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 930, in write
>     self._fatal_error(exc, 'Fatal write error on socket transport')
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 725, in _fatal_error
>     self._force_close(exc)
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 737, in _force_close
>     self._loop.call_soon(self._call_connection_lost, exc)
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 753, in call_soon
>     self._check_closed()
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed
> Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x000002BCE9154100>
> Unclosed connector
> connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002BCE922E5C0>, 83369.296)]']
> connector: <aiohttp.connector.TCPConnector object at 0x000002BCE9157400>
> Fatal error on SSL transport
> protocol: <asyncio.sslproto.SSLProtocol object at 0x000002BCE91561A0>
> transport: <_SelectorSocketTransport closing fd=944>
> Traceback (most recent call last):
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 924, in write
>     n = self._sock.send(data)
> OSError: [WinError 10038] An operation was attempted on something that is not a socket
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
>     self._transport.write(chunk)
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 930, in write
>     self._fatal_error(exc, 'Fatal write error on socket transport')
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 725, in _fatal_error
>     self._force_close(exc)
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 737, in _force_close
>     self._loop.call_soon(self._call_connection_lost, exc)
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 753, in call_soon
>     self._check_closed()
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed
> Fatal error on SSL transport
> protocol: <asyncio.sslproto.SSLProtocol object at 0x000002BCE9157730>
> transport: <_SelectorSocketTransport closing fd=916>
> Traceback (most recent call last):
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 924, in write
>     n = self._sock.send(data)
> OSError: [WinError 10038] An operation was attempted on something that is not a socket
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
>     self._transport.write(chunk)
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 930, in write
>     self._fatal_error(exc, 'Fatal write error on socket transport')
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 725, in _fatal_error
>     self._force_close(exc)
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 737, in _force_close
>     self._loop.call_soon(self._call_connection_lost, exc)
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 753, in call_soon
>     self._check_closed()
>   File "C:\Users\abharris\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed

**Comment by nacharya1** [comment]
Fixed with last week's package per Devis.
