### ISSUE TITLE
Python: Plan Object Errors

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#2094]
**Describe the bug**
While implementing Sequential planner, found some errors in plan objects.
Plus, it looks like `Plan.add_variables_to_context`does not propagate variables well.

checking #1916 can help you to understand situation

**To Reproduce**
run this file in PR branch [link](https://github.com/microsoft/semantic-kernel/pull/1916/files#diff-cb0be0602bc73419d9694921f015718e3a45485dd005327ff57ca79ad8aac14b)

**Platform**
 - OS: Mac M1
 - IDE: VS Code
 - Language: Python3.9
 - Source: #1916 branch

**Comment by evchaki** [comment]
@joowon-dm-snu - thank you for finding this.  We will look at the bug.

**Comment by joowon-dm-snu** [comment]
@evchaki  i'm fixing it on #2223 so it's good to close this issue!
