### ISSUE TITLE
Python: Porting test helper for integration tests

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#2095]
C# supports an integration testing helper that retrieves skills from a sample directory in [here](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/IntegrationTests/TestHelpers.cs)
To make it easier to add integration tests in Python, it would be beneficial to implement a similar concept.

**Comment by evchaki** [comment]
@joowon-dm-snu - great idea!  We will take a look at this.

**Comment by matthewbolanos** [comment]
Closing this since this was created several months ago
