### ISSUE TITLE
Python Weaviate memory store improvements

### ISSUE THREAD

**Issue by gramhagen** [microsoft/semantic-kernel#2100]
**Describe the bug**
There are a few issues with the weviate memory store python impl 

1. there is no way to pass embedded options during instantiation of weaviate
2. 1. upsert will not update a record if it already exists
3. class names are 'titlized' so checking if a class with a different capitalization exists can fail even though it is equivalent
4. missing unit test cases
5. related, but semantic_text_memory does not support returning embeddings

I have been making a few modifications during development and can add some test cases around these. But I wanted to start an issue to discuss the work before I started a PR.

**Platform**
 - OS: Ubuntu on WSL
 - IDE: VS Code
 - Language: Python
 - Source: main branch of repository

**Comment by evchaki** [comment]
@gramhagen - thank you for bringing this issue up.  We will take a look.
