### ISSUE TITLE
.Net: Planner and plan token usage

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/semantic-kernel#2106]
We would like to show users token usages after the planner creates a plan and the plan finishes executing the steps.
Currently, this is not supported by the kernel. Will need to look into that.

**Comment by matthewbolanos** [comment]
@TaoChenOSU, is this now possible with the work that you did?

**Comment by matthewbolanos** [comment]
@TaoChenOSU, are we able to close this one?

**Comment by TaoChenOSU** [comment]
The token usage is captured but since we have two planners that are very different in the way they plan and execute. It may require some extra effort for the users to find the usage information.
 
The handlebars planner calls the completion client directly, so the usage information is captured there. When the handlebars planner executes a plan, each function will contain the usage information, i.e. the usage information is attached to the function.

The function calling stepwise planner creates an initial plan using a prompt-based function, so the usage information is captured within the prompt-based function. And when it executes the plan, token usage information will be contained within the functions.

**Comment by TaoChenOSU** [comment]
Token usage is captured as measurements in metrics. Read more about it here: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/docs/TELEMETRY.md

**Comment by TaoChenOSU** [comment]
> @TaoChenOSU, are we able to close this one?

We can track token usage now, by functions and connectors. Planners can be a combination of both so users might need to perform some manual filtering through telemetry data.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
