### ISSUE TITLE
Where do I need to go to use "the Copilot stack"?

### ISSUE THREAD

**Issue by damc** [microsoft/semantic-kernel#2112]
I watched this video: https://www.youtube.com/watch?v=FyY0fEO5jVY that talk about "Copilot stack" and I've read few news about this, but nothing of it says where I need to go to start using it. So, where do I need to go if I let's say want to create an AI agent app on top of "the Copilot stack"?

I understand that the semantic kernel is a part of the Copilot stack (correct me if I'm wrong), but where is the rest of it?

**Comment by matthewbolanos** [comment]
I'd recommend checking out https://github.com/microsoft/chat-copilot. This is a reference application that has been built using Semantic Kernel to replicate the Copilot stack with plugins and foundational models.
