### ISSUE TITLE
Java: VolatileMemoryStore does not follow reactive pattern

### ISSUE THREAD

**Issue by dsgrieve** [microsoft/semantic-kernel#2113]
**Describe the bug**
I think I may have done VolatileMemoryStore in a bad way. The pattern there is "do the logic, then return a Mono.whatever". The problem with this, I think and I could be wrong, is that this is basically a sync pattern with an async return. What if someone calls one of these methods but never blocks on the Mono? I think this needs to be fixed so that the logic happens as part of the reactive stream. In other words, "Mono.fromCallable(() -> do the logic here)".

**Expected behavior**
I expect the logic (add/remove something from VMS) to happen as part of the reactive stream, not as part of creating the stream.

**Comment by d3r3kk** [comment]
Corrected/fixed.
