### ISSUE TITLE
Can not start kernelhttpserver

### ISSUE THREAD

**Issue by xboxeer** [microsoft/semantic-kernel#212]
**Describe the bug**
I followed the instruction of running kernelhttpserver but keeps receiving this exception:
[2023-03-29T16:01:35.028Z] Found C:\Users\zy418\Documents\Visual Studio 2022\semantic-kernel\samples\dotnet\KernelHttpServer\KernelHttpServer.csproj. Using for user secrets file configuration.
[2023-03-29T16:01:37.317Z] A host error has occurred during startup operation 'a5a93bd4-cb49-4c0f-80b6-f299af6af6fb'.
[2023-03-29T16:01:37.319Z] Microsoft.Azure.WebJobs.Extensions.Http: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. 系统找不到指定的文件(System can not find the specific file)。.
Value cannot be null. (Parameter 'provider')

**To Reproduce**
Just following this [document](https://github.com/microsoft/semantic-kernel/tree/main/samples/dotnet/KernelHttpServer) to start the kernelserver

**Expected behavior**
Server should run successfully

**Screenshots**
met error message below: 
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/5089150/228600388-72741155-608c-4414-a976-e3a3fa42cc76.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: VS Code
<img width="703" alt="image" src="https://user-images.githubusercontent.com/5089150/228599694-6fba81bd-a9f3-4a9f-8ca3-5678e9934bcc.png">
 - func tool version: 
 - 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/5089150/228599939-c3f3140d-3698-4b7d-bf3d-1ff42cc77094.png">

**Additional context**

**Comment by tynguyen** [comment]
[This](https://github.com/Azure/azure-functions-core-tools/issues/3115) seems to be the main cause. 
It runs well on my machine so I would recommend uninstall `.NET` SDK and reinstall it. Make sure install `.NET v7` to use notebooks.

**Comment by xboxeer** [comment]
> [This](https://github.com/Azure/azure-functions-core-tools/issues/3115) seems to be the main cause. It runs well on my machine so I would recommend uninstall `.NET` SDK and reinstall it. Make sure install `.NET v7` to use notebooks.

Thanks for the prompt :)! I reinstalled my .net  sdk and azure function tool and now it works.
