### ISSUE TITLE
Copilot Chat: copilot-chat-app Start-Backend.sh is refering to non-existing directory

### ISSUE THREAD

**Issue by Rsimk** [microsoft/semantic-kernel#2149]
**Describe the bug**
when starting locally  sample apps "copilot-chat-app" Start-Backend.sh refers to non-existing directory "../WebApi".

**To Reproduce**
1. Following steps in README.md in scripts directory to start app locally on Bash "3. Run Copilot Chat"
2. After running "Start.sh" there is error "that ../WebApi is non-existing"

**Expected behavior**
I would expect script Start-Backend.sh is referring to "../webapi" instead.

**Platform**
 - OS: WSL2 Ubuntu 20.04.6 LTS

**Comment by matthewbolanos** [comment]
@Rsimk, do you mind sharing which directory you're attempting to run the script from?

**Comment by Rsimk** [comment]
The script is run from scripts directory. The misspelled directory name is in https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/scripts/Start-Backend.sh script. That script is started from another script: https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/scripts/Start.sh.

**Comment by glahaye** [comment]
This problem should now be fixed.

Note that Copilot Chat has been renamed and moved to its own repo:
https://github.com/microsoft/chat-copilot/

The start-up scripts have been modified too (in part to address this issue).

If you ever encounter further issues, please do not hesitate to report them in the new repo!
