### ISSUE TITLE
Using semantic kernel in offline/on-premise environment

### ISSUE THREAD

**Issue by IIFE** [microsoft/semantic-kernel#2155]
Hi.

Is it at all possible to use semantic kernel in an offline mode, without using Azure/Open APIs? For example if I had a Q&A AI model like `Tapex` installed locally, can I use semantic kernel with the model so that I can ask questions about a tabular data source?

Thanks.

**Comment by alexchaomander** [comment]
Yes! Semantic Kernel supports you running on your own custom LLM endpoints! 

See: 
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example16_CustomLLM.cs

Of course, you'd have to use local memory stores as well, so you just have to choose from the options that support that!

**Comment by Kakolukia91** [comment]
Many thanks for the reply @alexchaomander - that seems useful.

I guess my follow up question would be how would I make my custom LLM use a pre-trained model (like `Tapex` for example)?

Still new to the AI ecosystem so hopefully my question makes sense :). Essentially my use case is that I want to use an AI model to ask questions about tabular data using natural language. However, my environment is an on-premise desktop one, based in .NET/C++. So ideally I'd want to run an AI solution locally and interact with it from .NET/C++. While the example you've provided is useful, I'm not sure how I can adapt it so that the question input is sent to a pre-trained AI model.

Thanks.

**Comment by IIFE** [comment]
(Sorry I just realized I replied using my personal GitHub account, re-replying here as original account 😄 )

Many thanks for the reply @alexchaomander - that seems useful.

I guess my follow up question would be how would I make my custom LLM use a pre-trained model (like `Tapex` for example)?

Still new to the AI ecosystem so hopefully my question makes sense :). Essentially my use case is that I want to use an AI model to ask questions about tabular data using natural language. However, my environment is an on-premise desktop one, based in .NET/C++. So ideally I'd want to run an AI solution locally and interact with it from .NET/C++. While the example you've provided is useful, I'm not sure how I can adapt it so that the question input is sent to a pre-trained AI model.

Thanks.

**Comment by alexchaomander** [comment]
So in short, you'd need to download one of the models (i.e. Llama 2) and host your own local endpoint. That can be done with any language but probably you'd have the best support for Python. Then you can point the Semantic Kernel to that endpoint to get the output. For your use case about interfacing with tabular data, you'd want to explore which local models are best suited for that task.

**Comment by IIFE** [comment]
Thanks again @alexchaomander 

The main challenge I've got is I'm not sure how to adapt the C# example in order to point it to a local model? Unfortunately Python is not an option for me hence why I'm looking into Semantic Kernel as it's the only option I've come across where C# seems to be supported, just not sure how to set it up in  away where I can use a local model.

**Comment by alexchaomander** [comment]
I would look at ONNX runtime as a way to load and then host a model in a language like C# or C++ https://onnxruntime.ai/

But that assumes that the model is ONNX runtime compatible which you'd have to check. 

I'll bring up to the team the need to show off more examples for using local models!

**Comment by IIFE** [comment]
Awesome thanks @alexchaomander - more concrete examples would definitely be very helpful 👍.

Looking forward to it.

**Comment by evchaki** [comment]
@IIFE  - great thread!  I am closing this for now, if you run into new issues when you are working on your project let us know.
