### ISSUE TITLE
.Net: Using sqlite memory storage with greek text  stores data with unicode escaping making memory search not possible

### ISSUE THREAD

**Issue by giannik** [microsoft/semantic-kernel#2160]
I am using sqlite memory storage to store some greek text to use for memories. here is an example :

```
  var kernel = Kernel.Builder
               .WithLogger(_logger)
               .WithMemoryStorage(await SqliteMemoryStore.ConnectAsync(dbPath))
               .Build();



  await kernel.Memory.SaveInformationAsync(index, id: document.ContentItemId, text: result  );
```

Here is a sample of thegreek  text i am saving : 

```
Content.ContentItem.FullText:Γιατί LearnNow τωρα <p>Στη σημερινή σύγχρονη διαρκώς εξελισσόμενη πραγματικότητα δημιουργούνται διαρκώς ανάγκες
```

But when i open the table to see the content in column metadata from sqllite browser it is not stored in original format . Here is a sample how it looks in the database: 

```
Content.ContentItem.FullText:\u0393\u03B9\u03B1\u03C4\u03AF LearnNow \u03C4\u03C9\u03C1\u03B1 \u003Cp\u003E\u03A3\u03C
```

When trying to search the memories using greek asks it produces no result .

Should'nt the data be stored in the original format to work ? 

Or am i doing something wrong ?

**Comment by evchaki** [comment]
@shawncal does anything stand out here?

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
