### ISSUE TITLE
Flow planner / execution agent for Copilot

### ISSUE THREAD

**Issue by yan-li** [microsoft/semantic-kernel#2164]
Copilots are often regarded as agents which offer various functionalities like commanding, Q&A, collaboration, suggestion, etc.

And to productize these features in intelligent and reliable ways, the orchestration layer of Copilot would require the following capabilities.
1) De-composite the goal/question into multiple subgoals, which is also known as Plan in the semantic kernel world.
2) Leverage the available skills, execute the plan in multi-step, multi-pass way, including interaction with users to get clarification on the goal, input for skills/functions, and authorization for actions when needed.

To fulfill so, I'd like to introduce a flow planner / execution agent.

The "Planner" part which automatically de-composites the task into multiple steps could be of lower priority.
Instead, for each Copilot some predefined flows could be provided, and the "Executor" part should be responsible of orchestrate these flows execution reliably, by resolving the dependencies, pass the parameters and try achieving the goal of each step with available skills in ReAct style, similar as how it is being described in [ReAct: Synergizing Reasoning and Acting in Language Models](https://arxiv.org/abs/2210.03629).

The planner would include the following parts.
1. Data model for the flow, steps
2. Execution agent which resolves dependencies, determine execution order, maintain context scope
3. ReAct execution engine for each step
4. Status tracker so the Copilots are re-entrant and would resume the work as user provides more input.

The new planner should also provide the flexibility of support versatile skills, including semantic functions, native functions and skills requires chat interaction in an easier to use way. 

![image](https://github.com/microsoft/semantic-kernel/assets/35783676/36264606-6aa5-4fd9-99ee-14b448b7617e)

**Comment by slreznit** [comment]
Curious to see comparison of this new Flow planner and the Stepwize planner recently added.

**Comment by yan-li** [comment]
> @yan-li, Curious to see comparison of this new Flow planner and the Stepwize planner recently added.
> 
> Any plans to add it to the Chat Copilot app?

The major differences are 
- support orchestration of multi-step flow (StepWise planner supports a single goal) 
- make it Chat friendly for multi-step execution (The observation of stepwise planner is limited to result from non chat skills).
- more complicated execution modes; for example, in real world flow, a step in the flow could be either optional or executed multiple times, and the planner would work with user to decide that.

And yes once this extension is available will try to make it a planner option for chat-copilot to better explain how to utilize the planner in Copilot apps.
