### ISSUE TITLE
.Net: Enhancement of ISemanticTextMemory.SaveInformationAsync for bulk data processing

### ISSUE THREAD

**Issue by Nurgo** [microsoft/semantic-kernel#2168]
Hi,

I've been working with SemanticKernel and I appreciate all the hard work you've put into this amazing project.

I'm currenly encountering a limitation with the ISemanticTextMemory.SaveInformationAsync method which only processes one text segment at a time, causing many calls to OpenAI's APIs when indexing large documents.

Would it be possible to modify this function to allow batch processing in a single call? Since IEmbeddingGeneration.GenerateEmbeddingsAsync already supports batching, it might be a feasible and impactful improvement.

Thanks for considering this suggestion.

**Comment by evchaki** [comment]
@dluc  can you take a look at this one?

**Comment by dluc** [comment]
@Nurgo since we're doing an important refactoring and evolution of the memory in a separate repo, I copied the issue here: https://github.com/microsoft/semantic-memory/issues/26 - Thanks!

If that's fine I would close this one, and follow up in the Semantic Memory repo. Thanks!

**Comment by dluc** [comment]
Bulk upload is supported in the new solution, we can continue the conversation over at the new repo is required.
