### ISSUE TITLE
Copilot Chat: .Net: Copilot Chat for Azure Kubernetes Service (AKS)

### ISSUE THREAD

**Issue by victor-v-rad** [microsoft/semantic-kernel#2179]
Hi Team,

Currently, Copilot Chat supports deployment on Azure but not on Azure Kubernetes Service (AKS). Kubernetes could be a more preferable infrastructure for many clients. Please consider adding deployment on AKS

<img width="1159" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/106504/a8d13968-311a-43b6-a24b-8abe46d561c2">

Thank you, 
Semantic Kernel is awesome!

**Comment by matthewbolanos** [comment]
Would you be interested in creating a PR to add this additional template? If so, we can then add it to our public documentation. If you do create a new PR, please submit it to our new repo for Chat Copilot: https://github.com/microsoft/chat-copilot

**Comment by victor-v-rad** [comment]
Thank you @matthewbolanos for suggesting to create a PR. I would be happy to work on it but I have limited time at my disposal.

**Comment by matthewbolanos** [comment]
Closing since we don't have plans to create another deployment mechanism for CC
