### ISSUE TITLE
Java: SKContext builder brings a default memory instead of Kernel's

### ISSUE THREAD

**Issue by brunoborges** [microsoft/semantic-kernel#2183]
> constructed the context myself, but SKBuilders.context().build(kernel) also doesn't use the kernel's memory because the default in the builder is not null

[Originally posted on Discord](https://discord.com/channels/1063152441819942922/1103386471345422536/1132932284660584448).

**Comment by dlwildschut** [comment]
The Builder for DefaultSKContext is initialized in https://github.com/microsoft/semantic-kernel/blob/experimental-java/java/semantickernel-core/src/main/java/com/microsoft/semantickernel/orchestration/DefaultSKContext.java#L41 with a NullMemory.
In https://github.com/microsoft/semantic-kernel/blob/experimental-java/java/semantickernel-core/src/main/java/com/microsoft/semantickernel/orchestration/DefaultSKContext.java#L93 the check memory == null is always false, therefore it never uses the kernel's memory.

**Comment by dsgrieve** [comment]
.NET have been discussing memories in kernel vs context. Need to see where things stand on their side.
