### ISSUE TITLE
Java: Add sample to explain saveReferenceAsync vs saveInformationAsync

### ISSUE THREAD

**Issue by brunoborges** [microsoft/semantic-kernel#2185]
> I also mistakenly used saveReferenceAsync instead of saveInformationAsync, it would maybe be nice to have an example showing how to use the different query results

[Discord](https://discord.com/channels/1063152441819942922/1103386471345422536/1132932284660584448)

**Comment by d3r3kk** [comment]
No longer existing in this state in SK for .NET or Java. Closing.
