### ISSUE TITLE
Java: NativeSKFunction assumes return from method invocation is a String or SKContext

### ISSUE THREAD

**Issue by dsgrieve** [microsoft/semantic-kernel#2190]
**Describe the bug**
The method NativeSKFunction.getFunction(Method, Object) invokes the method and maps the return value to either an SKContext or a String. But there are cases where the return value could be a List<String>. In PR #1999, a workaround was put in place which looks to see if the return value is an Iterable and, if so, takes the first element. This is not correct either.

**To Reproduce**
Take PR #1999  and comment out the block
```
if (it instanceof Iterable) {
    // Handle return from things like Mono<List<?>>
    // from {{function 'input'}} as part of the prompt.
    it = ((Iterable<?>) it).iterator().next();
}
```
Rerun Example15_MemoryStore
This will result in a ClassCastException in the call `context.update((String)it)`

**Expected behavior**
 Ideally, the context should be updated with all of the content of the return value.

**Comment by d3r3kk** [comment]
Return types are typed in Java now. Completed as part of the V1 overhaul.
