### ISSUE TITLE
Python: Simplify Error Handling under KernelException

### ISSUE THREAD

**Issue by awharrison-28** [microsoft/semantic-kernel#2194]
This work follows agreements made in ADR on Error Handling: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0004-error-handling.md

The work consists of **removing all existing SK exception types except the SKException and throwing SKException instead.**
See https://github.com/microsoft/semantic-kernel/pull/2158

**Comment by eavanvalkenburg** [comment]
For python this means, moving away from error codes, and instead creating a exception hierarchy under KernelException, for all the different cases, and making sure that a raise in code is always done with the `raise KernelException from exc` syntax, this helps developer understand what went wrong and where.

**Comment by eavanvalkenburg** [comment]
@matthewbolanos this will means breaking changes, please move into pre-v1 work, does not have to be ready for beta.
