### ISSUE TITLE
.Net: Prompt Chaining not working

### ISSUE THREAD

**Issue by oferze** [microsoft/semantic-kernel#2201]
**The bug**
Using the current [Prompt chaining](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/README.md#prompt-chaining) example, the output is `Energy conserved.` instead of `ΔE = 0, ΔSuniv > 0, S = 0 at 0K.`

Could it be that `kernel.RunAsync()` only takes the last function passed in the params?

**To reproduce**
1. Follow the `Get Started with Semantic Kernel` page, paste the relevant code (base program + the Prompt chaining example), and use your OpenAI key.
2. Run the program.
3. See the output.

**Expected behavior**
An output of `ΔE = 0, ΔSuniv > 0, S = 0 at 0K.`

**Platform**
 - OS: Windows 10
 - IDE: Visual Studio 17.6.5
 - Language: C#; .NET Core 7.0 Console App
 - Source: Microsoft.SemanticKernel, 0.18.230725.3-preview ; main branch of repository

**Comment by evchaki** [comment]
@oferze - the last step in this chain is to summarize the math, the LLM will do this in different ways, so this should be correct.

**Comment by oferze** [comment]
Ok then, so the comment at the last line of the code block, `// Output: ΔE = 0, ΔSuniv > 0, S = 0 at 0K.`, is incorrect.
