### ISSUE TITLE
.Net: improve Redis memory store constructor

### ISSUE THREAD

**Issue by sneha-afk** [microsoft/semantic-kernel#2208]
As discussed in #2132 , it would be helpful to allow the user to customize the vector attributes used in similarity searching, and also create a `RedisMemoryStore` instance from a connection string than having to make the database instance first.

I will implement these features by adding parameters to the constructor and overloading the existing constructor, thank you!

**Comment by evchaki** [comment]
@sneha-afk - thanks for putting in the PR.
