### ISSUE TITLE
Add Security filters for trimming results in Azure Cognitive Search

### ISSUE THREAD

**Issue by glahaye** [microsoft/semantic-kernel#2209]
More information on security filters:
https://learn.microsoft.com/en-us/azure/search/search-security-trimming-for-azure-search

This is required by a "big customer" (name withheld for privacy reasons) to support strict requirements on data isolation at the chat session level within their product at a scale that goes beyond the maximum number of indexes that ACS can handle. The filters could help return just the data related to certain groups, for example.

**Comment by dluc** [comment]
We are working on filters in the next major version of Semantic Memory, which is being developed here https://github.com/microsoft/semantic-memory. The repo is not ready for production use, but you can find information about the next stage, which will address this (and other) issues with the current approach in SK.

The new memory schema will support filters on `tags`:

```csharp
/// <summary>
    /// Optional Searchable Key=Value tags (string => string[] collection)
    /// 
    /// Multiple values per keys are supported.
    /// e.g. [ "Collection=Work", "Project=1", "Project=2", "Project=3", "Type=Chat", "LLM=AzureAda2" ]
    /// 
    /// Use cases:
    ///  * collections, e.g. [ "Collection=Project1", "Collection=Work" ] 
    ///  * folders, e.g. [ "Folder=Inbox", "Folder=Spam" ]
    ///  * content types, e.g. [ "Type=Chat" ]
    ///  * versioning, e.g. [ "LLM=AzureAda2", "Schema=1.0" ]
    ///  * etc.
    /// </summary>
    public NameValueCollection Tags { get; set; } = new();
```

and there will be a new `owner` field too. These new fields will allow to filter by user within the same index, and create virtual collections like grouping by type, by project, etc.

In a few weeks we will update SK to work with the new Semantic Memory (which can also be deployed as a standalone service), providing also data migration guidelines, to move from an existing ACS index to the new schema.

**Comment by glahaye** [comment]
This is in place with Kernel Memory
