### ISSUE TITLE
.NET: Recreate GitHub QA as a plugin.

### ISSUE THREAD

**Issue by EricChen-01** [microsoft/semantic-kernel#2219]
Update and bundle the old sample app for [GitHub QA sample](https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/github-qna-webapp-react) into a plugin. 

I plan on working on this with a friend (Will tag him here at a later date.)

**Comment by EricChen-01** [comment]
This will be my first open-source contribution! Let me know any tips and ways to improve!

**Comment by matthewbolanos** [comment]
This sounds like a great idea! Can't wait to see your PR.

**Comment by hopedonn** [comment]
> Update and bundle the old sample app for [GitHub QA sample](https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/github-qna-webapp-react) into a plugin.
> 
> I plan on working on this with a friend (Will tag him here at a later date.)

Here!

**Comment by EricChen-01** [comment]
Hi! what should the process of the pull request be? I currently have the code in my personal repo but im not sure where it will live within this repository

**Comment by EricChen-01** [comment]
I have provided the link to the repo: https://github.com/EricChen-01/GitHubQAChatGPTPlugin

**Comment by matthewbolanos** [comment]
Closing since we are currently not adding new plugins to the main repo
