### ISSUE TITLE
.Net: Connector to AWS Kendra (Open Search) for Vector DB

### ISSUE THREAD

**Issue by davearlin** [microsoft/semantic-kernel#2227]
For those developers that are working with a .NET stack, but deploying to AWS.  It would be beneficial to add a connector similar to the Cognitive Search, Qdrant and other VectorDB connectors.    Happy to work on this if this is acceptable.   If so,  I'll likely create another issue similarly for Google Cloud's Vertex AI Matching Engine.

**Comment by evchaki** [comment]
@davearlin - this sounds great.  Please submit a PR and we will review it and push it into main when it is ready.  Feel free to create the Kendra and Vertex connectors.

**Comment by jeffrey-fontenot** [comment]
Hello @davearlin  - curious if this is something you are moving forward with - I have a need for these memory connectors as well.

**Comment by davearlin** [comment]
> Hello @davearlin - curious if this is something you are moving forward with - I have a need for these memory connectors as well.

Yes, I do plan on starting this over the next couple of days.  Got a little too tied up with the day job these past couple of weeks.

**Comment by jeffrey-fontenot** [comment]
Great to hear! Thanks @davearlin

**Comment by nacharya1** [comment]
@davearlin and @jeffrey-fontenot FYI: We recently updated our contributing guidelines [here](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#adding-plugins-and-memory-connectors , stating we are not directly adding plugin and connectors directly into the SDK repository. We are encouraging the community to host their own plugins and connectors separately in their own repositories. At the time we are exploring how we can provide a way to discover plugins and connectors and should have an update soon. I am going to close this issue given our change in contribution guidelines.
