### ISSUE TITLE
.Net: ISemanticTextMemory.GetAllAsync(string collection, CancellationToken cancellationToken = default(CancellationToken))

### ISSUE THREAD

**Issue by simone-devoti** [microsoft/semantic-kernel#2268]
I think it will be useful to add a method that let's you get all of the elements of a vector database collection.
One implementation can be to perform the similarity search with a fixed prebuilt embedding, like [0,0,0,...,0]
It would be cool to also add search results limits and pagination if possible

I think it will be awesome to also add a Search method that let's you search given an embedding instead of a text query

**Comment by nacharya1** [comment]
@simone-devoti thanks for suggesting this idea. We will look into this. Feel free to suggest a PR if you want to get us started.

**Comment by matthewbolanos** [comment]
Closing this issue since our current plan is to align with the Open AI chat retrieval plugin
