### ISSUE TITLE
Python: Wikipedia search connector

### ISSUE THREAD

**Issue by sneha-afk** [microsoft/semantic-kernel#2272]
Wikipedia has its [MediaWiki API](https://www.mediawiki.org/wiki/API:Opensearch#API_documentation) that allows for queries returning information and article links. Having this feature would complement the new Bing and Google connectors. 

 I would like to work on making a connector for this, thank you!

**Comment by evchaki** [comment]
@sneha-afk  - great idea - feel free to do a PR, this would be great to pull in.

**Comment by nacharya1** [comment]
@sneha-afk FYI: We recently updated our contributing guidelines [here](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#adding-plugins-and-memory-connectors , stating we are not directly adding plugin and connectors directly into the SDK repository. We are encouraging the community to host their own plugins and connectors separately in their own repositories. At the time we are exploring how we can provide a way to discover plugins and connectors and should have an update soon. I am going to close this issue given our change in contribution guidelines.
