### ISSUE TITLE
Rank `skills` for `planner` to select appropriate skills

### ISSUE THREAD

**Issue by tynguyen** [microsoft/semantic-kernel#228]
There are already a couple of similar (if not duplicated) `skills` for certain tasks and as we move forwards, there are gonna more and more duplicated skills. This results in inconsistent performance. 

I wonder if we can somehow enable `planner` to score and keep updating on how well a `skill` performs for a certain task so that next time when it selects a `skill`, it knows what is the best to choose from?

**Comment by lemillermicrosoft** [comment]
https://github.com/microsoft/semantic-kernel/discussions/170 explains recent changes that might help here.

We're also actively developing and designing refactor for Planner and looking to include the ability to supply your own examples (to help prioritize certain functions/skills based on your scenarios). If you've got any other feedback or ideas on how this would be helpful, please share!

**Comment by evchaki** [comment]
Closing this as the updates are in progress
