### ISSUE TITLE
Python: chat completion config does not propagate stop sequence to ai services

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#2301]
**Describe the bug**
similar with #1880, stop sequences are not passed into ai_services.

<img width="915" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/69464062/25874b9b-e738-4331-9764-37ef3f143ffb">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by joowon-dm-snu** [comment]
temporal solution commit: https://github.com/microsoft/semantic-kernel/pull/2223/commits/bc61d2e6183c4d47669aa7edf4a2a6f9ac4dd4ca

**Comment by nacharya1** [comment]
@joowon-dm-snu  thanks for raising this. @lemillermicrosoft / @awharrison-28 could you take a look into this?

**Comment by moonbox3** [comment]
Closing this as the following issue is no longer relevant. The execution settings have been redone since then. If you have a new issue with the latest code, please file a new GitHub issue. Thank you.
