### ISSUE TITLE
Python only: Update examples and notebooks to stop using text-davinci-003

### ISSUE THREAD

**Issue by glahaye** [microsoft/semantic-kernel#2309]
Several of our kernel examples and notebooks still use text-davinci-003, which is being retired by Azure OpenAI and is no longer supported for new deployments. We should update these to use a more current model such as gpt-35-turbo.

This has been done already on the .Net side: #2307

**Comment by karthikmurali60** [comment]
@glahaye @shawncal can i work on this issue? I'd love to contribute.

**Comment by glahaye** [comment]
@karthikmurali60 Absolutely!

Refer to #2307 (the .Net equivalent).

Feel free to break this down into one PR for the notebooks and one for the examples if doing everything is too much work.

Thanks!

**Comment by crickman** [comment]
@glahaye This was recently merged.  Does it overlap this issue?

**Comment by crickman** [comment]
https://github.com/microsoft/semantic-kernel/pull/2359

**Comment by awharrison-28** [comment]
#2359 got most of the references to text-davinvi-003, but missed notebooks 10 and 11. There may be some new kernel-syntax-examples that need to be looked as well.

**Comment by matthewbolanos** [comment]
Closed since this was addressed
