### ISSUE TITLE
Have wrapper to initialize either OpenAI or Azure OpenAI in KernelSyntaxExamples

### ISSUE THREAD

**Issue by glahaye** [microsoft/semantic-kernel#2310]
Right now, some of the examples require OpenAI (through WithOpenAIChatCompletionService) while others require Azure Open AI (through WithAzureChatCompletionService).

So, unless you access accounts with both services, you have to modify the code to have all the examples to work.

This could be mitigated by initializing kernels with whichever service is configured in the settings,

**Comment by JadynWong** [comment]
Related Suggestion. Would it be possible to improve running of KernelSyntaxExamples by using a `switch` or something that allows you to choose which examples you want to run. I think most developers don't want to run all examples every time. 

In some PRs, you can see developers commenting out other examples to run just one. And forget to uncomment them when committing.
