### ISSUE TITLE
.Net: Implement SQLServer MemoryStore

### ISSUE THREAD

**Issue by kbeaugrand** [microsoft/semantic-kernel#2312]
Following [this article](https://devblogs.microsoft.com/azure-sql/vector-similarity-search-with-azure-sql-database-and-openai/), it seems that it could be possible to have a memory store using vectors on SQL server.

**Comment by kbeaugrand** [comment]
I'm interested to create a PR on that topic (already started an implementation).

**Comment by evchaki** [comment]
@kbeaugrand thanks for starting a PR for this!

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
