### ISSUE TITLE
.Net: Lock in a plan [Parent Issue]

### ISSUE THREAD

**Issue by evchaki** [microsoft/semantic-kernel#2314]
Need to have the ability to lock in a plan that is pre-defined by a developer.  The plan can call plugins and prompts just like the dynamic plan that is returned by a planner.

When an ask is created from a user and comes into the kernel, the next step should be to look at the vector database to see if it can find a locked in place based on a description or ask set that the plan can achieve.  If no plan can be found, then the next step is the normal flow of allowing a dynamic planner to process as normal.

Needed for .net, python and java kernels
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/issues/2566
- [ ] https://github.com/microsoft/semantic-kernel/issues/2567
```

**Comment by lemillermicrosoft** [comment]
> Need to have the ability to lock in a plan that is pre-defined by a developer. The plan can call plugins and prompts just like the dynamic plan that is returned by a planner.

This is done and available in the kernel (at least in .Net, not positive about java+python).

> When an ask is created from a user and comes into the kernel, the next step should be to look at the vector database to see if it can find a locked in place based on a description or ask set that the plan can achieve.

This seems like something the copilot chat sample app could implement today. I want to confirm whether there is expectation that the kernel is doing more than it is capable of doing in .Net today.

**Comment by nacharya1** [comment]
I believe for .net SDK we dont need anything else. I have created items for python and java to ensure we have parity in design/capabilities. 

We have assigned work in Chat Copilot to demonstrate 1) how a plan can be saved 2)plan can be evaluated apart of the incoming ask 3) generate a new plan if saved plan is not appropriate. 

cc: @teresaqhoang

**Comment by lemillermicrosoft** [comment]
Closing this as .Net work is done. Other items will remain open.
