### ISSUE TITLE
[Memory] Milvus Memory Connector - dotnet [community candidate]

### ISSUE THREAD

**Issue by nacharya1** [microsoft/semantic-kernel#2316]

**Comment by roji** [comment]
Note: I've submitted #2694 which implements this.

**Comment by nacharya1** [comment]
@roji FYI: We recently updated our contributing guidelines [here](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#adding-plugins-and-memory-connectors , stating we are not directly adding plugin and connectors directly into the SDK repository. We are encouraging the community to host their own plugins and connectors separately in their own repositories. At the time we are exploring how we can provide a way to discover plugins and connectors and should have an update soon. I am going to close this issue given our change in contribution guidelines.
