### ISSUE TITLE
qustion: WithAzureCognitiveSearchMemory completed removed

### ISSUE THREAD

**Issue by kenakamu** [microsoft/semantic-kernel#2319]
Hi team,
I have a quick question about Azure Cognitive Search. 

I see WithAzureCognitiveSearchMemory has been removed after 0.18 version and start supporting Vector Search. 
Do we have any reason to completely remove the semantic search capability? Or do we still have a way to use Semantic Search without WithAzureCognitiveSearchMemory?

**Comment by nacharya1** [comment]
hi @kenakamu we moved the WithAzureCognitiveSearchMemory to a separate package to help with isolation and efficiency. You can find the nuget package you need here > https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.Memory.AzureCognitiveSearch/0.19.230804.2-preview

**Comment by nacharya1** [comment]
let us know if you have issues.

**Comment by stz92** [comment]
Hi,

maybe I'm missing something, but AzureSearchServiceKernelBuilderExtensions.cs, the file containing WithAzureCognitiveSearchMemory(), was completely removed in commit 5024744. https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.Memory.AzureCognitiveSearch/0.19.230804.2-preview does not contain this function. How can I use Azure Cognitive Search with Semantic Search with the SemanticSDK?

**Comment by JimMullennix** [comment]
Also experiencing the same thing with 0.21.230823.2-preview.  No WithAzureCognitiveSearchMemory() available.
