### ISSUE TITLE
Implement Planner Skill In Python

### ISSUE THREAD

**Issue by renrut** [microsoft/semantic-kernel#232]
### Feature Request:
Implement the planner skill. @alexchaomander said it wasn't being worked on internally, so I've started on it. Opening this as a tracker for semantic kernel planning skill implementation in the Python branch. I've been working on it and hoping to get a PR out soon, but wanted to make sure I was on the same page stylistically with the team.

### Scope:
Current scope is planning skill feature parity with the [main branch](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel/CoreSkills/PlannerSkill.cs) (although maybe a few commits behind)...

**Comment by jjhenkel** [comment]
Yes, thank you @renrut! Excited to see it --- there may be a good bit of churn here as we work on making the SK `python-preview` branch more "idiomatic python" (as the original code comes from a "direct from C# port" I did, so it's not very pythonic yet).

There's also a bunch of active work in the C# branch that has/will have implications for us here. (Things like an overhaul of the prompt template language and upgrades to the model backends to better support chat/images/etc.) Happy to do a review and help point out what might have changed/be changing when you have a PR out!

**Comment by renrut** [comment]
Okay. No worries, happy to hold off for now!

@jjhenkel - I was also scoping more of a direct port as well for planning since I was keen to get the python branch working with it.

**Comment by jjhenkel** [comment]
@renrut totally can appreciate the idea to direct port, it worked decent enough for the rest of the repo! Thanks for being patient with us here as we work through both bringing things up to parity and moving the port towards something that looks more like reasonable Python code!

**Comment by alexchaomander** [comment]
@renrut we have this PR in review now that introduces the Plan object model! 
https://github.com/microsoft/semantic-kernel/pull/255

Definitely follow along there

**Comment by lemillermicrosoft** [comment]
Just the object model though, one step in a series of work that will end up removing the PlannerSkill.

**Comment by lemillermicrosoft** [comment]
> @renrut we have this PR in review now that introduces the Plan object model! #255
> 
> Definitely follow along there

Just the object model though, one step in a series of work that will end up removing the PlannerSkill.

**Comment by dluc** [comment]
quick update: the team is looking into this, we'll share updates in the following weeks.

**Comment by chuanzhubin** [comment]
Looking forward to the progress of the Python version

**Comment by alexchaomander** [comment]
Closed with #597
