### ISSUE TITLE
Python: semantic kernel returns empty string 

### ISSUE THREAD

**Issue by teamsdeveloper** [microsoft/semantic-kernel#2320]
When I invoke my function, I got empty string.

makeOrderFunction.invoke_async(context=context)

I am using python and semantic-kernel 0.3.5.dev0

**Comment by glahaye** [comment]
Hi @teamsdeveloper 

Can you provide more detail? What does your function look like? Can you provide its code?

**Comment by teamsdeveloper** [comment]
# Skill from directory and function
 skills_directory = "./skills"
 orderFunctions = kernel.import_semantic_skill_from_directory(skills_directory, "OrderSkill")
 makeOrderFunction = orderFunctions["MakeOrder"]

# Context
context = kernel.create_new_context()
context["menu"] = json.dumps(products)
context["cart"] = json.dumps(cart)
context["chat_history"] = chat_history

# Semantic function invocation
context["user_input"] = ask
bot_answer = await makeOrderFunction.invoke_async(context=context)

Function invocation is not stable. It returns sometimes a string and sometimes an empty string.

**Comment by teamsdeveloper** [comment]
Any solution to fix this issue?

**Comment by lemillermicrosoft** [comment]
> Function invocation is not returning stable output.

This is often typical with LLMs depending on your configuration settings. Can you share the prompt and configuration settings?

**Comment by matthewbolanos** [comment]
Closing since this was created several months ago.
