### ISSUE TITLE
Python: Provide methods to register single native function to the kernel in Python SDK

### ISSUE THREAD

**Issue by blackchoey** [microsoft/semantic-kernel#2321]
I want to register a native function to the kernel when using the Python SDK. In .NET, the kernel has `RegisterCustomFunction` method to register a function. But in Python, seems there's only an `import_skill` method available, which requires me to declare a class with the native function in it.

The current experience of registering a native function:
``` python
class Test:
    @sk_function(name="getLightStatus")
    def get_light_status(self) -> str:
        return "off"

kernel.import_skill(Test())
```

The expected experience I want is:
``` python
@sk_function(name="getLightStatus")
def get_light_status() -> str:
    return "off"

kernel.register_native_function(get_light_status)
```

**Comment by joowon-dm-snu** [comment]
@alexchaomander I've opened a PR, how does this look?

**Comment by alexchaomander** [comment]
@joowon-dm-snu Nice! Thank you for the first pass of the implementation! I agree that having it be easy to import native functions in Python would be great. We might need to tweak the naming of it, but will discuss with the team!
