### ISSUE TITLE
.Net: Review updated docs on Semantic Kernel for .NET

### ISSUE THREAD

**Issue by nacharya1** [microsoft/semantic-kernel#2327]
The following files need review:

- [x]  [Quick start guide](https://review.learn.microsoft.com/en-us/semantic-kernel/get-started/quick-start-guide/?toc=%2Fsemantic-kernel%2Ftoc.json&branch=matthew-plugins-updates&tabs=Csharp)
- [x]  [Supported languages](https://review.learn.microsoft.com/en-us/semantic-kernel/get-started/supported-languages?branch=matthew-plugins-updates)
- [x]  [Overview of kernel](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/?branch=matthew-plugins-updates&tabs=Csharp)
- [x]  [Understanding plugins](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/plugins?branch=matthew-plugins-updates&tabs=Csharp)
- [x]  [Creating semantic functions](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/semantic-functions?branch=matthew-plugins-updates&tabs=Csharp)

- [x]  [Creating native functions](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/native-functions?branch=matthew-plugins-updates&tabs=Csharp)
- [x]  [Chaining functions](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/chaining-functions?branch=matthew-plugins-updates&tabs=Csharp)
- [x]  [Planner](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/planner?branch=matthew-plugins-updates&tabs=Csharp)

**Comment by matthewbolanos** [comment]
Closing since the docs have been reviewed and updated where there were breaking changes.
