### ISSUE TITLE
.Net: cl100k_base tokenizer

### ISSUE THREAD

**Issue by anthonypuppo** [microsoft/semantic-kernel#2334]
The existing [GPT3Tokenizer](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.AI.OpenAI/Tokenizers/GPT3Tokenizer.cs) class uses p50k_base encoding. GPT-3.5, GPT-4, and text-embedding-ada-002 all rely on cl100k_base encoding.

The below table is extracted from the [OpenAI notebook](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb) on token counting.

| Encoding name | OpenAI models |
| ------------- | ------------- |
| cl100k_base | gpt-4, gpt-3.5-turbo, text-embedding-ada-002 |
| p50k_base | Codex models, text-davinci-002, text-davinci-003 |
| r50k_base (or gpt2) | GPT-3 models like davinci |

**Comment by anthonypuppo** [comment]
[SharpToken](https://github.com/dmitry-brazhenko/SharpToken)

**Comment by nacharya1** [comment]
@dluc are you able to look into this?
