### ISSUE TITLE
.Net: Example06_TemplateLanguage - Function `time.Date` not found

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#2361]
**Describe the bug**
It appears semantic functions can no longer call functions from within the templated prompt.

**To Reproduce**
1. Run Example06_TemplateLanguage

**Expected behavior**
Semantic function invokes successfully

**Actual behavior**
--- Semantic Function result
fail: object[0]
      Function `time.Date` not found
fail: object[0]
      Function `time.Time` not found
fail: object[0]
      Something went wrong while rendering the semantic function or while executing the text completion. Function: _GLOBAL_FUNCTIONS_.func244da18178204cf08035d2f58a0236a6. Error: Function not found: Function `time.Date` not found
      Microsoft.SemanticKernel.TemplateEngine.TemplateException: Function not found: Function `time.Date` not found

**Platform**
 - OS: Windows
 - IDE:  VS Code
 - Language: C#
 - Source: main (138080abb7b402ede14c7a2833a3154ffe3f3719)

**Additional context**

**Comment by matthewbolanos** [comment]
This is also impacting the following samples:
- https://learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/native-functions?tabs=Csharp
- https://learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/chaining-functions?tabs=Csharp
