### ISSUE TITLE
SK Tools extension: Unable to find any AOAI resources

### ISSUE THREAD

**Issue by HaoHoo** [microsoft/semantic-kernel#2370]
**Describe the bug**
My MSA account has some Azure Subscriptions and joined Microsoft AAD as a guest. But it looks like Microsoft change the policy to deny queries by guest accounts. So I can't sign in and locate the Azure OpenAI resources anymore.

The Azure tenant can sign in with the Azure tools extension and list all subscriptions.
These AOAI resources can use by code normally. For example, I can use them by .env file in the code.

**To Reproduce**
1. Get an Azure subscription account and join Microsoft AAD as a guest.
2. Click on 'AI Endpoints' and switch to Azure OpenAI. Click 'Sign in' by the account selected in step 1.
3. See error.

**Expected behavior**
SK Tools extension can skip the directory which can't be queried and try to other directories.

**Screenshots**

**Platform**
 - OS: Mac (I think it happened on all OS)
 - IDE: VS Code (I think it happened on all IDE)
 - Language: Python (I think it happened with all languages)
 - Source: Semantic Kernel Tools Extention v0.9.1

**Additional context**
This issue was also found in Vision Studio, Azure OpenAI Studio, Cognitive Services Content Moderator, and Form Recognizer Studio.

**Comment by nacharya1** [comment]
@hario90  - are you able to look into this?

**Comment by matthewbolanos** [comment]
Closed because we are currently putting the VS Code extension in maintenance mode.
