### ISSUE TITLE
When will the typescript version come out?

### ISSUE THREAD

**Issue by lynancy** [microsoft/semantic-kernel#2371]
When will the typescript version come out?

**Comment by evchaki** [comment]
@lynancy - we have a branch here (https://github.com/microsoft/semantic-kernel/tree/experimental-typescript) with TypeScript and this is sponsored by the community.  If you would like the submit PRs to get it going please check out the CONTRIBUTING guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)

**Comment by matthewbolanos** [comment]
We currently don't have timelines for the typescript version of Semantic Kernel.

**Comment by afshinm** [comment]
I'm working on a Typescript version of Semantic Kernel in this repo (unofficial port): https://github.com/semantickernel/semantic-kernel-js

Documentation is hosted on this website https://kerneljs.com/. I'd like to get your feedback/comments.
