### ISSUE TITLE
Adding Azure CosmosDB Mongo vCore as a datastore.

### ISSUE THREAD

**Issue by aayush3011** [microsoft/semantic-kernel#2375]
I will be adding Azure CosmosDB Mongo vCore as a data store. Mongo vCore now supports vector search on embeddings, and it can be used to seamlessly integrate your AI-based applications with your data stored in the Azure ComsosDB. More details about Mongo vCore can be found here https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/vector-search.

**Comment by evchaki** [comment]
@aayush3011 - thanks for creating this.  Once you have the PR started please add it to this issue for tracking.

**Comment by kshitijcode** [comment]
Helo @evchaki , Can you please assign this to me?

**Comment by kshitijcode** [comment]
@lemillermicrosoft @dluc Is it already assigned or can I pick this one up?

**Comment by evchaki** [comment]
@kshitijcode thanks for picking this up and creating a PR!

**Comment by aayush3011** [comment]
@kshitijcode Is this feature already done, I have the PR here for it. https://github.com/microsoft/semantic-kernel/pull/2990

**Comment by nacharya1** [comment]
@awharrison-28 - can you review the PR for this issue #2990. See if it aligns with the outline we discussed with MongoDB team.

**Comment by aayush3011** [comment]
The PR is merged - https://github.com/microsoft/semantic-kernel/pull/2990
