### ISSUE TITLE
.Net: The 'file' scheme is not supported

### ISSUE THREAD

**Issue by ninshu25** [microsoft/semantic-kernel#2376]
**Describe the bug**
When prompting this line I am receiving the following error:
CODE:
var key1 = kernel.Memory.SaveInformationAsync("chroma-test", text: "british short hair", id: Guid.NewGuid().ToString());

ERROR:
The 'file' scheme is not supported.

The source of the error seems to be coming from Microsoft.SemanticKernel.Abstractions

**Platform**
 - Windows C# asp.net core v6

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
