### ISSUE TITLE
Java: The Java implementation doesn't have a way to use different OpenAI models for semantic functions.

### ISSUE THREAD

**Issue by relango** [microsoft/semantic-kernel#2387]
**Describe the bug**
The Java implementation doesn't have a way to use different OpenAI models for semantic functions.

**To Reproduce**
When building kernel we can register multiple TextCompletion services using different models with different serviced.

```
Kernel kernel = SKBuilders.kernel()
            .withAIService("GPT4", gpt4TextCompletion, false, Gpt4TextCompletion.class)
            .withAIService("GPT3.5", gpt4TextCompletion, false, Gpt35TextCompletion.class)
            .build();
```
But at runtime, it seems to register the first AI Service as default and always uses it for all Semantic functions.
Looking at [DefaultCompletionSKFunction](https://github.com/microsoft/semantic-kernel/blob/experimental-java/java/semantickernel-core/src/main/java/com/microsoft/semantickernel/orchestration/DefaultCompletionSKFunction.java#L240), aiService lookup is hard coded to use `null` value for name, so it always uses one default text completion service.
          
Also, we are supposed to provide serviceId in completion config json, but [PromptTemplateConfig](https://github.com/microsoft/semantic-kernel/blob/experimental-java/java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/PromptTemplateConfig.java) doesn't have a `serviceId` field to read from json and use it in code.

**Expected behavior**
We should have a way to provide `serviceId` for semantic functions and able to register different openai models with different serviceId. So that we can use different OpenAI models for semantic functions at runtime.

**Screenshots**
NA

**Platform**
- Java

**Additional context**

**Comment by evchaki** [comment]
@d3r3kk - FYI on this one.

**Comment by relango** [comment]
@evchaki @d3r3kk Any idea when this will be added? Can I send a PR with the fix?

**Comment by dsgrieve** [comment]
@relango Certainly you can send a PR with a fix! See https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md for details.

**Comment by relango** [comment]
Thanks @dsgrieve @evchaki @d3r3kk . Here is [PR](https://github.com/microsoft/semantic-kernel/pull/2417) to add this feature. Can you please review it?

**Comment by d3r3kk** [comment]
@johnoliver please review/close.

**Comment by d3r3kk** [comment]
Closed - handled by https://github.com/microsoft/semantic-kernel/pull/3366
