### ISSUE TITLE
Python: Is the relevancy documentation here: https://learn.microsoft.com/en-us/semantic-kernel/chat-copilot/customizing-chat-copilot?tabs=AzureOpenAI#:~:text=If%20using%20gpt%2D3.5%2Dturbo%2C%20we%20also%20recommend%20changing%20CopilotChatPlanner.cs%20to%20initialize%20SequentialPlanner%20with%20a%20RelevancyThreshold%3B%20no%20change%20is%20required%20if%20using%20gpt%2D4.0. still relevant?

### ISSUE THREAD

**Issue by dipteshbosedxc** [microsoft/semantic-kernel#2389]
**Describe the bug**
Is the relevancy documentation here: https://learn.microsoft.com/en-us/semantic-kernel/chat-copilot/customizing-chat-copilot?tabs=AzureOpenAI#:~:text=If%20using%20gpt%2D3.5%2Dturbo%2C%20we%20also%20recommend%20changing%20CopilotChatPlanner.cs%20to%20initialize%20SequentialPlanner%20with%20a%20RelevancyThreshold%3B%20no%20change%20is%20required%20if%20using%20gpt%2D4.0. still relevant?

Isn't the code updated to take care of this setting dynamically? 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by matthewbolanos** [comment]
@momuno, now that the relevancy threshold is configurable in appsettings, would you be able to update this doc article?

**Comment by matthewbolanos** [comment]
Closing since the doc article has been updated
