### ISSUE TITLE
Sample notebook move into language folders, but guide document is not update, so can not find file when following learning guide

### ISSUE THREAD

**Issue by demongodYY** [microsoft/semantic-kernel#2393]
### here is folder sample notebooks move to 
<img width="723" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/17036920/c67e14a0-530b-4d48-b676-9ec8904f782b">
<img width="439" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/17036920/23526bb6-55fd-4b8f-891a-df43fc864bc9">

### here is guide link
<img width="1921" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/17036920/c46c7f3d-a5a0-4c30-ad19-be8a71f783bd">

**Comment by matthewbolanos** [comment]
Thanks for letting us know! The docs have been fixed :)
