### ISSUE TITLE
[StepwisePlanner] add config Stepwise Planner to prevent the final response from being generated by the LLM

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#2394]
Currently, when running the Stepwise Planner, I always receive the final response generated by the LLM. 
However, in cases where I want to consistently generate answers using a hard-coded approach or utilize the planner as an API caller (such as when using native_functions), this becomes unnecessary.

Here is an example. planner executed right function but final output was not i intended. 
```python
class ConditionalChat:
    @sk_function(
        name="offer_assistance",
        description="Generating a chat to respond to a user who don't know what to do.",
    )
    def offer_assistance(self, context: SKContext) -> str:
        return "I can help you with options below! how about asking me one from the list"

goal = "..."
plan = planner.create_plan(goal)
result = asyncio.run(plan.invoke_async()) # will call ConditionalCaht.offer_assistance

print(result.result) 
# Current result is "The user can choose from the following options ... " 
# Because planner writes final answer to answer user's question
# But I expected "I can help you with options below! how about asking me one from the list"
```

It can be solved by adding config and change `ExecutePlanAsync` like below
```c#
//semantic-kernel/dotnet/src/Extensions/Planning.StepwisePlanner/StepwisePlanner.cs
    public async Task<SKContext> ExecutePlanAsync(
        [Description("The question to answer")]
        string question,
        [Description("List of tool descriptions")]
        string functionDescriptions,
        SKContext context)
    {
        var stepsTaken = new List<SystemStep>();
        if (!string.IsNullOrEmpty(question))
        {
            for (int i = 0; i < this.Config.MaxIterations; i++)
            {
                ...
                if (!string.IsNullOrEmpty(nextStep.FinalAnswer))
                {
                    // Suggestion
                    if (this.Config.UseAgentFinalAnswer)
                    {
                        context.Variables.Update(nextStep.FinalAnswer);
                    }
                    else
                    {
                        context.Variables.Update(stepsTaken[-2].Observation);
                    }
```

**Comment by joowon-dm-snu** [comment]
@lemillermicrosoft could you check this idea too?

**Comment by lemillermicrosoft** [comment]
So when you create the plan, it's given the entire conversation history as a quesiton/goal? Have you tried to create a plan where the quesiont/goal has more context, e.g. 'Given this conversation history: {{$history}}, respond to most recent user message.'

Additionally, you can parse out the steps after execution and take whichever Observation you want. Would that be satisfactory? I worry about having too much scenario specific logic like that in the object.

**Comment by joowon-dm-snu** [comment]
@lemillermicrosoft 

In fact, this issue has no relevance to the chat history or context I'm suggesting. 
It seems I gave a wrong example, so I made slight modifications. What I wanted was for the Plan's Final Answer to be the result (observation) of the executed Action itself. 
The scope of influence was also limited to a single finalAnswer rather than every step's observation.

Currently, the planner writes a new `Final Answer` based on the latest `Observation`. Therefore, the final output tends to differ from what I expected. I wanted to use the planner as a kind of data-fetcher, so I felt this was unnecessary and thus made the suggestion. There are also difficulties in maintaining a consistent Chat Persona when using only some features of the copilot through the planner, due to cost/time constraints.

However, it's true that as plan things get more complex, they become harder to use. 
So, it's okay if the content of this Issue or other comments are not accepted. Please consider it as one of the ideas :)

**Comment by d3r3kk** [comment]
@johnoliver please investigate any need for Java SK to implement/have parity here.

**Comment by matthewbolanos** [comment]
Closing this since the stepwise planner will be replaced with the new function calling stepwise planner. Please create a new issue if the new stepwise planner has the same issue.
