### ISSUE TITLE
.Net: Cancelling IChatCompletion.GenerateMessageStreamAsync() throws InvalidOperationException

### ISSUE THREAD

**Issue by takeo-iw** [microsoft/semantic-kernel#2398]
**Describe the bug**
I'm cancelling streaming the response from IChatCompletion.GenerateMessageStreamAsync().
I call CancellTokenSource.Cancel(), i will get InvalidOperationException.

**To Reproduce**
1. Call GenerateMessageStreamAsync()
<img width="831" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/108264521/301557c3-cbd2-4c50-b856-e22663caf184">

2. Call Cancel() by button click event etc.
<img width="410" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/108264521/067ff2ee-bc8a-4497-a19d-8acf94dcda7b">

3. Cancel() throws InvalidOperationException (see Screenshots)

**Expected behavior**
Cancellation can be evaluated by IsCancelRequested and raises an OperationCanceledException exception.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/108264521/0451986b-c758-44ff-9d6b-7985fadff2c2)

**Platform**
 - OS: Mac
 - IDE: VS Code
 - Language: C# (Blazor)
 - Source: 
<img width="699" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/108264521/7ccd7cf0-6479-4e14-9b33-008a3f7aee9b">

**Comment by nacharya1** [comment]
@takeo-iw, thanks for raising this and the follow up message. We will investigate on our side as well.

**Comment by matthewbolanos** [comment]
@RogerBarreto, do you know if this has been resolved in 1.0.1?

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
