### ISSUE TITLE
InvokeAsync method returns "Error: Invalid request: The request is not valid, HTTP status: 404"

### ISSUE THREAD

**Issue by erose-nerdio** [microsoft/semantic-kernel#2418]
Describe the bug
Whenever I call ".InvokeAsync" It errors with
"Error: Invalid request: The request is not valid, HTTP status: 404".
It's a similar error to https://github.com/microsoft/semantic-kernel/issues/1539, except I am using text-davinci-003 and the issue still isn't resolved.

Desktop (please complete the following information):

OS: Windows
IDE: Microsoft Visual Studio
NuGet Package Version "nuget: Microsoft.SemanticKernel, 0.18.230725.3-preview"

**Comment by craigomatic** [comment]
This might be happening because the notebooks were switched from text completion (text-davinci-003) to chat completion (gpt-35-turbo or gpt-4) in https://github.com/microsoft/semantic-kernel/pull/2307

Do you have a deployment of gpt-35-turbo you can try instead of text-davinci-003?

**Comment by erose-nerdio** [comment]
> This might be happening because the notebooks were switched from text completion (text-davinci-003) to chat completion (gpt-35-turbo or gpt-4) in #2307
> 
> Do you have a deployment of gpt-35-turbo you can try instead of text-davinci-003?

I'm running the WithAzureTextCompletionService method before building. I tried using chat completion with gpt-35-turbo (which I have deployed) instead, but the issue persists.

**Comment by lemillermicrosoft** [comment]
Need more details for repro.
