### ISSUE TITLE
No module named 'semantic_kernel' in Azure Machine Learning Prompt Flow.

### ISSUE THREAD

**Issue by teamsdeveloper** [microsoft/semantic-kernel#2422]
I tried to import semantic kernel like below in Azure Machine Learning Prompt Flow.
import semantic_kernel as sk

But I got below error:
No module named 'semantic_kernel'.

How to use semantic kernel in azure machine learning prompt flow.

**Comment by matthewbolanos** [comment]
Thanks for reaching out! The out-of-the-box runtime environments in prompt flow are purposefully kept fairly lean. If you want to use other PIP packages, you'll need to create a [custom runtime environment](https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-customize-environment-runtime?view=azureml-api-2) and make sure all of your needed PIP packages are described in the requirements.txt file (including Semantic Kernel).

As part of the Semantic Kernel team's efforts to integrate with the rest of the Microsoft ecosystem, we'll be blogging and documenting how to use Prompt Flow and Semantic Kernel together next week. Keep an eye out for it!

**Comment by teamsdeveloper** [comment]
Thank you. I have successfully created custom environment for semantic kernel, created prompt flow and added a step for summarization, and it worked fine.

**Comment by nacharya1** [comment]
@teamsdeveloper thats great to hear! thanks for letting us know.
