### ISSUE TITLE
.Net: qdrant memory remove error.Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. 

### ISSUE THREAD

**Issue by Sam--Shan** [microsoft/semantic-kernel#2432]
**Describe the bug**
save data like kernel.Memory.SaveInformationAsync("db1","content","key")
and remove it by removeAsync("db1","key")

error thow like 'Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. '

**Platform**
 - OS: windows11
 - IDE: Visual Studio 
 - Language: C#
 - Source: 
 Microsoft.SemanticKernel.Connectors.Memory.Qdrant version-0.19.230804.2-preview
https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.Memory.Qdrant/0.19.230804.2-preview

![259907514-2dabfc96-74c2-43b8-b1cb-e67f2908c708](https://github.com/microsoft/semantic-kernel/assets/10590637/9e04f8d3-e7be-4b4a-acdf-79c7892706d6)

**Comment by Sam--Shan** [comment]
#https://github.com/microsoft/semantic-kernel/issues/970#issuecomment-1675391181

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
