### ISSUE TITLE
Support better logging and observability for function chains

### ISSUE THREAD

**Issue by calvdee** [microsoft/semantic-kernel#2433]
Complex chains could benefit from the integration of logging / observability, both out-of-the-box and in in a way that can be customized. This would allow developers to better debug function chains.

**Comment by nacharya1** [comment]
@calvdee, thanks for raising this. We recently made update to support end to end telemetry and observability. 
See this blog post for more information > https://devblogs.microsoft.com/semantic-kernel/unlock-the-power-of-telemetry-in-semantic-kernel-sdk/
