### ISSUE TITLE
Java: Naming conventions in SKBuilders class

### ISSUE THREAD

**Issue by agoncal** [microsoft/semantic-kernel#2436]
When using the `SKBuilders` class I find myself getting confused with "what is a service and what is not?". Basically, the `chatCompletion` method returns a `ChatCompletion` and the method is called `chatCompletion`. But, the `textCompletionService` method returns a `TextCompletion` but is suffixed with `Service`:

```java
public class SKBuilders {

  public static TextCompletion.Builder textCompletionService()
  public static ChatCompletion.Builder chatCompletion()
  public static EmbeddingGeneration.Builder<String> textEmbeddingGenerationService()

}
```

Shouldn't `Service` be abandoned and just have:

```java
public class SKBuilders {

  public static TextCompletion.Builder textCompletion()
  public static ChatCompletion.Builder chatCompletion()
  public static EmbeddingGeneration.Builder<String> textEmbeddingGeneration()

}
```

PS: somehow related to #2437

**Comment by d3r3kk** [comment]
Open for discussions between the teammembers and resolution for Sept.
