### ISSUE TITLE
Java: Naming conventions in Builder interface

### ISSUE THREAD

**Issue by agoncal** [microsoft/semantic-kernel#2437]
The `Builder` interface has two methods, one starting with `with` and the other one with `set`:

```java
interface Builder extends SemanticKernelBuilder<ChatCompletion> {
  Builder withOpenAIClient(OpenAIAsyncClient client);
  Builder setModelId(String modelId);
}
```

This is confusing because most of the build methods start with `with` and not `set`. For example `withDefaultAIService`, `withOpenAIClient` but `setModelId`:

```java
Kernel kernel = SKBuilders.kernel()
  .withDefaultAIService(SKBuilders.textCompletionService()
    .setModelId("text-davinci-003")
    .withOpenAIClient(client)
    .build())
  .build();
```

It will feel more natural to have `with` on both methods. WDYT?

```java
interface Builder extends SemanticKernelBuilder<ChatCompletion> {
  Builder withOpenAIClient(OpenAIAsyncClient client);
  Builder withModelId(String modelId);
}
```

PS: somehow related to #2436

**Comment by dsgrieve** [comment]
Java recently went through the builders for consistency. We settled on "with" for a "uses" relationship, like OpenAIAsyncClient, and "set" for things that were more like state or properties of the thing being built. But even then it's a grey area. 
@johnoliver's PR: https://github.com/microsoft/semantic-kernel/pull/2270
My original proposal on improving the builder experience is here: https://discord.com/channels/1063152441819942922/1134166165422362704

**Comment by d3r3kk** [comment]
Open for discussions between the teammembers and resolution for Sept.

**Comment by agoncal** [comment]
Solved with https://github.com/microsoft/semantic-kernel/pull/2575
