### ISSUE TITLE
.Net: Inconsistent behavior of settings in \dotnet\src\Connectors\Connectors.AI.OpenAI\AzureSdk\ClientBase.cs

### ISSUE THREAD

**Issue by andhesky** [microsoft/semantic-kernel#2441]
> [!IMPORTANT]  
> Labeled **Urgent** because it may require a breaking change. Please downgrade if this is not the case.

**Describe the bug**
The APIs that take CompleteRequestSettings make a Verify.NotNull call while the APIs that take ChatRequestSettings accept a null value and just use the defaults

Throw on null settings:
InternalGetTextResultsAsync
InternalGetTextStreamingResultsAsync

Accept null settings as default:
InternalGetChatResultsAsync
InternalGetChatStreamingResultsAsync
InternalGetChatResultsAsTextAsync
InternalGetChatStreamingResultsAsTextAsync

Other implementations of ITextCompletion are also inconsistent. HuggingFace ignores nulls (and ignores settings completely). Oobabooga will throw a null reference exception.

**To Reproduce**
n/a

**Expected behavior**
All APIs should behave the same on null settings.

**Screenshots**
n/a

**Platform**
 - OS: n/a
 - IDE: n/a
 - Language: C#
 - Source: Azure.AI.OpenAI version 1.0.0-=beta.6

**Additional context**
n/a

**Comment by nacharya1** [comment]
@RogerBarreto, are you able to look into this?

**Comment by markwallace-microsoft** [comment]
The code was changed to use `AIRequestSettings` and this issue should be resolved
