### ISSUE TITLE
Template Engine: Function calls in templates should support multiple named args

### ISSUE THREAD

**Issue by shawncal** [microsoft/semantic-kernel#2445]
When you call a function in a prompt template, you can only specify one string as an arg. Functions, however, support many named arguments! In the template engine, when a "CodeBlock" is found, we should look for all named arguments and populate the ContextVariables accordingly.

**Comment by nacharya1** [comment]
@hario90 - can you confirm if this issue is now closed based on target date or needs to be pushed out.
