### ISSUE TITLE
Copilot Chat: E2E Sample - Saved plans, Recall and Turn by Turns w/ Plugins

### ISSUE THREAD

**Issue by nacharya1** [microsoft/semantic-kernel#2450]
```[tasklist]
### Saved Plans + Recall
- [ ] https://github.com/microsoft/semantic-kernel/issues/2581
```
```[tasklist]
### Turn by Turn
- [ ] https://github.com/microsoft/semantic-kernel/issues/2582
```

**Comment by teresaqhoang** [comment]
See [Saved Plans.loop](https://microsoft.sharepoint.com/:fl:/s/c04bdb84-0acf-4cd0-9574-d3d16b4a9a06/Ea4tNIcWRllEsBxafJZXyXQBhLV3utFh3xdoRBMOHleR3Q?e=Ex8EFT&nav=cz0lMkZzaXRlcyUyRmMwNGJkYjg0LTBhY2YtNGNkMC05NTc0LWQzZDE2YjRhOWEwNiZkPWIhbnNrOUtjd3ZFVXl6R29ySGVQT1JCME42Q2Q3c1ItaE1ybkpHRXlOMEFEbVJJWGJhNVpLOVFxdG5iUEljcHpNaCZmPTAxTjdNQ0RTNU9GVTJJT0ZTR0xGQ0xBSEMyUFNMRlBTTFUmYz0lMkYmZmx1aWQ9MSZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHh0YVdOeWIzTnZablF1YzJoaGNtVndiMmx1ZEM1amIyMThZaUZ1YzJzNVMyTjNka1ZWZVhwSGIzSklaVkJQVWtJd1RqWkRaRGR6VWkxb1RYSnVTa2RGZVU0d1FVUnRVa2xZWW1FMVdrczVVWEYwYm1KUVNXTndlazFvZkRBeFRqZE5RMFJUV1VOWlYwaE5Va0pHUzBSU1JGbzBVVTVNTXpSRE0xVkpUMGslM0QlMjIlMkMlMjJpJTIyJTNBJTIyYjhmNjY3NTQtYjViNy00N2RiLWJkNDItOTJjOTUzMjZkNjBmJTIyJTdE) for notes on the CIBC demo

**Comment by teresaqhoang** [comment]
Demo branch: https://github.com/microsoft/semantic-kernel/compare/main...lemillermicrosoft:semantic-kernel:811_customer_loan

**Comment by teresaqhoang** [comment]
Moving to backlog in favor due to Scale testing

**Comment by matthewbolanos** [comment]
Closing since we will not be adding additional new features to Chat Copilot
