### ISSUE TITLE
[Semantic Kernel Tools extension] Support ActionPlanner and StepwisePlanner

### ISSUE THREAD

**Issue by formulahendry** [microsoft/semantic-kernel#2462]
In current Semantic Kernel Tools VS Code extension, it seems to only support creating and running SequentialPlanner.
Do we have plan to support ActionPlanner and StepwisePlanner?

**Comment by nacharya1** [comment]
@formulahendry - can you provide more information to the scenario you are trying to test or validate with the additional planners? 
cc: @matthewbolanos

**Comment by matthewbolanos** [comment]
We are currently deprecating the action planner and stepwise planner in favor of the new Handlebars and V2 Stepwise planner, so I'll close out this issue.
