### ISSUE TITLE
Extend IKernel.GetService<> to non AI services

### ISSUE THREAD

**Issue by yan-li** [microsoft/semantic-kernel#2463]
Today IKernel.GetService<> only supports AI services. 
```
/// <summary>
/// Get one of the configured services. Currently limited to AI services.
/// </summary>
/// <param name="name">Optional name. If the name is not provided, returns the default T available</param>
/// <typeparam name="T">Service type</typeparam>
/// <returns>Instance of T</returns>
T GetService<T>(string? name = null) where T : IAIService;
```

Extending it as well as registration process would make skill authoring more friendly to derive dependencies from IKernel.

**Comment by yan-li** [comment]
Hi @nacharya1 here are some pseudo code for expected dependency injection experience. 

Current
```
IAPIClient client = ...
var skillA = new ASkill(client)
var skillB = new BSkill(client)
kernel.ImportSkills(...)
```

Expected
```
IAPIClient client = ...
kernel.RegisterService<IAPIClient>(client)
var skillA = new ASkill(kernel)
var skillB = new BSkill(kernel)
kernel.ImportSkills(...)

public class ASkill
{
  IAPIClient client;
  public ASkill(IKernel kernel)
  {
     this.client = kernel.GetService<IAPIClient>();
  }
}
```

The implementation could be extending current GetService interface on IKernel so devs could have similar experience as other dotnet apps.

Also for reference: https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection

**Comment by matthewbolanos** [comment]
@stephentoub, I believe your most recent PR addresses this.

**Comment by stephentoub** [comment]
> @stephentoub, I believe your most recent PR addresses this.

yup
