### ISSUE TITLE
How to generate embeddings using Semantic Kernel

### ISSUE THREAD

**Issue by animeshj9** [microsoft/semantic-kernel#2469]
Hello. I want to create a custom memory index on Azure Cognitive Search (i.e. not using the structure that SK offers). 
How can I go about uploading my data into a custom ACS index **with embeddings** and use ACS's vector search.

Using `kernel.Memory.SaveInformationAsync` or `kernel.Memory.SearchAsync` only seem to work with the index created by SK.
Is there any way to do it with SK or should I use Azure Search client and Azure openAPI clients to generate embeddings and store it on ACS. 

Thanks!

**Comment by nacharya1** [comment]
@animeshj9 - thanks for raising this. We will look into this supporting this in a future release.
FYI: @dluc

**Comment by animeshj9** [comment]
Thank you @nacharya1. For now, we are using the 'AdditionalMetadataField' to store a Json Serialized text for the information we want to retrieve based on the searchable fields. 

@nhandangt

**Comment by animeshj9** [comment]
@nacharya1 @dluc - Do we have any links to work items or something for me to follow? Thanks! :)

**Comment by lallgaurav** [comment]
@nacharya1 Any update on this feature asks? Kindly share eta in case there is a plan to fix it.
Also wondering why we made AdditionalMetadataField type as string and not complex type, as we have a need to store json object. This is limiting us to perform filter on this field in case we want to use any of the properties of the complex object type.

**Comment by dluc** [comment]
I would suggest starting from our new memory solution at https://github.com/microsoft/semantic-memory - Custom schemas are not there yet but we have a plan to support them and many more features coming.
If you prefer using the current SK Memory, I think the fastest way would be using something like SK Indexer (part of Chat Copilot) to bulk upload your data. The indexer is now using the new memory, but earlier versions used the SK Memory I believe.

**Comment by brendenpetersen** [comment]
@animeshj9 Does the [AzureCognitiveSearchMemoryStore](https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/connectors/memory/azure_cognitive_search/azure_cognitive_search_memory_store.py#L33) not do what you are looking for? It connects to an existing/custom ACS, but I'm not sure how to integrate it with your own ACS index's custom schema; from [here](https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/connectors/memory/azure_cognitive_search/utils.py#L101) it looks like the schema is hardcoded.

Related announcement with link to video: https://devblogs.microsoft.com/semantic-kernel/announcing-semantic-kernel-integration-with-azure-cognitive-search/

**Comment by animeshj9** [comment]
@brendenpetersen - We were not able to use the AzureCognitiveMemorySearchStore for this - the schema is hardcoded and there isnt an easy way to create a custom schema. We used https://github.com/microsoft/semantic-memory as suggested by @dluc .

@lallgaurav will have more information as he is the one who implemented this for us.

**Comment by brendenpetersen** [comment]
@lallgaurav That would be great if you could provide any input, we are in the same boat but have not yet tried the semantic-memory repository.

**Comment by lallgaurav** [comment]
@brendenpetersen yes, we are leveraging Semantic Memory (I believe it got renamed to Kernel Memory). It has a provision for specifying tags which is a kind of work around for Custom schema though not very efficient as it does in-memory filtering. I am hopeful that Semantic Memory team will fix it in its upcoming release.
@dluc any eta by when this issue will get fixed?

**Comment by markwallace-microsoft** [comment]
The work to support custom schema is in progress, here is a link to the ADR https://github.com/microsoft/semantic-kernel/issues/5887

Closing this issue as we have backlog tasks to track this enhancement.
