### ISSUE TITLE
.Net: Populate ParameterViewType for semantic and native functions.

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#2480]
I have a typed native function like this. The ParameterView for this function returns a ParameterViewType of null.  

[SKFunction]
void DoubleToString(double x) {}

 
Is the ParameterViewType ever set? I would expect it to be ParameterViewType.Number

Today we only set these values via `RegisterRestApiFunction` -- we should make sure these are populated consistently.

**Comment by matthewbolanos** [comment]
This is now fixed
