### ISSUE TITLE
DiversitySampling with Memory for DocumentQA

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#2484]
For document QA, when using Memory and filtering solely by relevance_score, you end up with results that are mostly from similar sections of the same document. However, when a comprehensive answer considering the overall content is necessary, utilizing various parts from diverse documents rather than just including sections from a single document in the prompt can be beneficial.

After reading the provided [link](https://towardsdatascience.com/enhancing-rag-pipelines-in-haystack-45f14e2bc9f5), I found it to be a good idea and propose integrating it as a feature used in conjunction with Memory. 

This post introduces the concepts of DiversityRanker and LostInTheMiddleRanker. The concept of LostInTheMiddleRanker is closely related to the overall structure of prompts, so I didn't include it in this proposal for now, as it might be challenging to integrate solely with Memory.

Implementation code in haystack is [here](https://github.com/deepset-ai/haystack/blob/main/haystack/nodes/ranker/diversity.py)

**Comment by evchaki** [comment]
@dluc can you take a look at this one and provide any comments.

**Comment by dluc** [comment]
Thanks for the ideas, could you copy/move this ticket over at https://github.com/microsoft/semantic-memory/issues ?

**Comment by joowon-dm-snu** [comment]
> Thanks for the ideas, could you copy/move this ticket over at https://github.com/microsoft/semantic-memory/issues ?

@dluc  sure!

**Comment by matthewbolanos** [comment]
Closing since the issue was copied over
