### ISSUE TITLE
.Net: Filter for memory search

### ISSUE THREAD

**Issue by HSven1611** [microsoft/semantic-kernel#2485]
I need some sort of prefiltering for my embedded documents that is more sophisticated than only having different indexes. Our customer has multiple products in multiple product categories and also multiple versions of the same product over the past time. I need to specify some sort of combination of those categories before searching otherwise I might end up with, say 10 top results but they all are for another product so filtering after search does not work.

Best case would be some sort of prefiltering based on the metadata of the entries.

As SK supports multiple vector DBs this might need to have some sort of fallback implementation if the underlying DB does not support additional query parameters.

Maybe the open-ai plugin implementation could be used as a blueprint for this:
https://github.com/openai/chatgpt-retrieval-plugin/blob/main/datastore/providers/redis_datastore.py#L221

**Comment by lukasz-appstream** [comment]
@HSven1611 We did it for QDrant (but extendible to other DBs) in our fork and are trying to merge it, although it's apparently waiting for some major architecture changes before we can continue...

https://github.com/microsoft/semantic-kernel/pull/1481

**Comment by evchaki** [comment]
@HSven1611 , thank you for bringing this up, we have work in process to make this easier for you.  You should be able to start doing filtering in a few more weeks.

**Comment by cbscientist** [comment]
What's the status on this? My use case also requires pre-filtering of the documents in an ACS index, so I'm curious to know if there has been any progress here.

**Comment by matthewbolanos** [comment]
@dluc has implemented filtering in the [Semantic Memory](https://github.com/microsoft/kernel-memory) project. Does this address your needs?

**Comment by HSven1611** [comment]
I think it does. We worked around this issue by using multiple indices for now.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
