### ISSUE TITLE
.Net: c#: kernel.Memory.SaveInformationAsync fails silently without throwing an exception

### ISSUE THREAD

**Issue by HSven1611** [microsoft/semantic-kernel#2486]
**Describe the bug**
When we do many calls to kernel.Memory.SaveInformationAsync in a row we end up getting warnings and then errors due to the API responding with an error signaling to many requests. How can I get this thrown as an exception and not just as a log with the Save Method returning successfully? The way it works right now, I end up saving 200 datasets and having only 100 in my redis.

**To Reproduce**
1. initialize kernel with redis memory
2. save many many (like 200) small entries to the db very fast
3. watch the log output
4. check redis for actual entries
5. see different count of entries in redis as what you tried to save

**Expected behavior**
Right now exceptions are only logged to the logger but not thrown. Semantic Kernel prints a warning as soon as the open ai api responds telling SK that too many requests happened and SK backs up and tries again, logging this as a warning. After a couple of tries it logs an error and stops trying.
I need the information this did fail in my code to be able to handle retires in my own.

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio
 - Language: C#
 - Source: dotnet-0.19.230804.2-preview

**Additional context**
It seems the issue happens due to open ai not allowing unlimited requests and SK not throwing but retrying and than stopping. A flag telling SK to throw instead of retrying defaulting to false would be a nice backwards compatible solution.

**Comment by nacharya1** [comment]
@SergeyMenshykh - can you look into this question/comment apart of the error handling work you are doing.

**Comment by SergeyMenshykh** [comment]
Hi @HSven1611, thanks for reporting the issue; it helps us improve SK.

I tried to reproduce the problem by making 1000 parallel SaveInformationAsync calls but I couldn't. Could you please update SK to the latest version and try to reproduce the issue again? Additionally, if possible, could you create a simple console application that replicates the problem and share it with us?

**Comment by HSven1611** [comment]
Hi

I've just realized, this retry behavior also occurs when interacting with e.g. chat completion api. I'd love to have an option to flag if I want the semantic kernel to retry if (as I'd assume) the api responds "with too many requests" or if I'd like it to fail and throw so I'm able to handle this on my own.

I'll try to get a demo code to reproduce the overall issue today or tomorrow.

**Comment by HSven1611** [comment]
I'vemanaged to reproicude the behavoir sortof. 

I've reduced the token count for the ada model to 10k. This makes the error appear much faster, also depending on your PC it occurs faster or slower. What I see is that it starts generating embeddings super fast, then the last console statement appearing very early and all the errors being postet afterwards.

> Disclaimer: logs are from multiple runs so timestaps are messed up

Errors look like this in the beginning:

```
<4>19:33:04 Program[0] Error executing action [attempt 1 of 1]. Reason: TooManyRequests. Will retry after 9000ms
<4>19:33:04 Program[0] Error executing action [attempt 1 of 1]. Reason: TooManyRequests. Will retry after 9000ms
```

And after a short while 

```
<3>19:33:14 Program[0] Error executing request, max retry count reached. Reason: TooManyRequests
<3>19:33:14 Program[0] Error executing request, max retry count reached. Reason: TooManyRequests
```

Then 

```
<2>19:37:45 Program[0] Throttling: Too many requests, HTTP status: 429
<2>19:37:45 Program[0] Throttling: Too many requests, HTTP status: 429
```

And then the software crashes.

As already stated we'd like the kernel to have an option to make him throw as soon as the API returns the too many requests the first time to be able to react to this and maybe inform the user. As is right now the user needs to wait for quite a while without any idea of what's going on.

I've also seen this behavior in calls to completion aswell as said 3 hours ago :-)

```cs
// See https://aka.ms/new-console-template for more information
using Microsoft.Extensions.Logging;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.Memory.Sqlite;



var memoryStore = await SqliteMemoryStore.ConnectAsync("storage.db");
var kernelConfig = new KernelConfig();


var loggerFactory = LoggerFactory.Create(builder =>
{
    builder.AddSystemdConsole(opts =>
    {
        opts.TimestampFormat = "HH:mm:ss ";
    });
    builder.AddFilter("Default", LogLevel.Debug);
});
var logger = loggerFactory.CreateLogger(nameof(Program));

logger.LogInformation("Logger ready.");

var endpoint = "https://westeurope.api.cognitive.microsoft.com/";
var apiKey = "YOUR_API_KEY";
var kernel = new KernelBuilder()
    .WithLogger(logger)
    .WithConfiguration(kernelConfig)
    .WithMemoryStorage(memoryStore)
    .WithAzureChatCompletionService(
        deploymentName: "gpt-35-turbo",
        endpoint: endpoint,
        apiKey: apiKey)
    .WithAzureTextEmbeddingGenerationService(
        deploymentName: "text-embedding-ada-002",
        endpoint: endpoint,
        apiKey: apiKey)
    .Build();

Console.WriteLine("Go?");
Console.ReadLine();

var runs = 200;
var parallel = 10;

Parallel.For(0, runs, new ParallelOptions() { MaxDegreeOfParallelism = 10 }, async i =>
{
    logger.LogInformation("paragraph: " + i.ToString());
    var paragraph = LoremNET.Lorem.Sentence(100, 300);
    try
    {

        await kernel.Memory.SaveInformationAsync("demo", paragraph, Guid.NewGuid().ToString());
    }
    catch (Exception ex)
    {
        logger.LogCritical(ex.Message);
    }
});

Console.WriteLine("DONE *************************************************************************************************************************************************************************************************************************************************************************");

Console.ReadLine();
```

**Comment by HSven1611** [comment]
What I've also found is

```cs
new KernelBuilder()
    .WithRetryHandlerFactory(new NullHttpRetryHandlerFactory())   
```

This seems to solve the issue but then every so and so number of calls a single call just takes quite long and I do not get any log information put out.

This is what I've did now: (I've also premade the random text to make sure this is not what taxes so long)

```cs
// See https://aka.ms/new-console-template for more information
using Microsoft.Extensions.Logging;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.Memory.Sqlite;
using Microsoft.SemanticKernel.Reliability;
using System.Collections.Concurrent;

var memoryStore = await SqliteMemoryStore.ConnectAsync("storage.db");
var kernelConfig = new KernelConfig();


var loggerFactory = LoggerFactory.Create(builder =>
{
    builder.AddSystemdConsole(opts =>
    {
        opts.TimestampFormat = "HH:mm:ss ";
    });
    builder.AddFilter("*", LogLevel.Trace);
});
var logger = loggerFactory.CreateLogger(nameof(Program));

logger.LogInformation("Logger ready.");

var endpoint = "https://westeurope.api.cognitive.microsoft.com/";
var apiKey = "YOUR_API_KEY";
var kernel = new KernelBuilder()
    .WithRetryHandlerFactory(new NullHttpRetryHandlerFactory())
    .WithLogger(logger)
    .WithConfiguration(kernelConfig)
    .WithMemoryStorage(memoryStore)
    .WithAzureChatCompletionService(
        deploymentName: "gpt-35-turbo",
        endpoint: endpoint,
        apiKey: apiKey)
    .WithAzureTextEmbeddingGenerationService(
        deploymentName: "text-embedding-ada-002",
        endpoint: endpoint,
        apiKey: apiKey)
    .Build();

Console.WriteLine("Go?");
Console.ReadLine();

var runs = 200;
var parallel = 10;

ConcurrentBag<string> paragraphs = new ConcurrentBag<string>();
Parallel.For(0, runs, new ParallelOptions() { MaxDegreeOfParallelism = 10 }, async i =>
{
    var paragraph = LoremNET.Lorem.Sentence(100, 300); 
    paragraphs.Add(paragraph);
});

Console.WriteLine("GO!");

await Parallel.ForEachAsync(paragraphs, async (paragraph, _) =>
{
    try
    {
        await kernel.Memory.SaveInformationAsync("demo", paragraph, Guid.NewGuid().ToString());
    }
    catch (Exception ex)
    {
        logger.LogCritical(ex.Message);
    }
}
);

Console.WriteLine("DONE *************************************************************************************************************************************************************************************************************************************************************************");

Console.ReadLine();
```

**Comment by HSven1611** [comment]
Is there some sort of docs about how the kernel handles this retry things? It seems kind of odd the way it works.

**Comment by SergeyMenshykh** [comment]
@HSven1611 Thank you for providing the repro steps; they have helped us to identify and resolve the issue.

The problem you encountered was the result of two retry policies used by SK. One retry policy was configured within SK itself, while the other, was provided by the Azure SDK by default. 

Now, with both policies disabled, your code will start throwing exceptions, enabling you to handle them yourself. If you wish to utilize SK's retry feature, you can easily configure it using the `KernelBuilder.WithHttpHandlerFactory`, `KernelBuilder.WithRetryPolly`, or `KernelBuilder.WithRetryBasic` extension methods. Here are a few examples: [Example08_RetryHandler](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example08_RetryHandler.cs).

The fix will be released early next week.
