### ISSUE TITLE
.Net: Executing planner.CreatePlanAsync(ask) in .NET Framework 4.6.2 results in a PlatformNotSupportedException

### ISSUE THREAD

**Issue by sannyg0701** [microsoft/semantic-kernel#2487]
**Describe the bug**
Running the example here https://github.com/MicrosoftDocs/semantic-kernel-docs/blob/main/samples/dotnet/04-Planner/Program.cs in a .NET Framework 4.6.2 Console application results in a PlatformNotSupportedException

**To Reproduce**
Run the following code in a .NET Framework 4.6.2 Console application
```
var kernel = Kernel.Builder
     .WithOpenAITextEmbeddingGenerationService("text-embedding-ada-002", apiKey)
     .WithOpenAIChatCompletionService("gpt-3.5-turbo", apiKey)
     .Build();
var mathPlugin = kernel.ImportSkill(new MathPlugin(), "MathPlugin");

var planner = new SequentialPlanner(kernel);

var ask = "I have $2130.23. How much would I have after it grew by 24% and after I spent $5 on a latte?";
var plan = planner.CreatePlanAsync(ask).Result;

Console.WriteLine("Plan:\n");
Console.WriteLine(JsonSerializer.Serialize(plan, new JsonSerializerOptions { WriteIndented = true }));

var result = plan.InvokeAsync().Result;

Console.WriteLine("Plan results:");
Console.WriteLine(result.Result.Trim());
```

**Expected behavior**
I am expecting the "ask" to be deciphered correctly and the MathPlugin gets called and generates the appropriate response.

**Screenshots**

![Error1](https://github.com/microsoft/semantic-kernel/assets/50372924/1f016f99-a842-4060-bad7-eea39067fcad)
![Error2](https://github.com/microsoft/semantic-kernel/assets/50372924/d9d8f443-f2bb-4f71-9cb2-ae66ce35f031)

**Platform**
 - OS: Windoes
 - IDE: Visual Studio 17.4.4
 - Language: C#
 - Source: Microsoft.SemanticKernel nuget package version 0.19.230804.2-preview

**Additional context**

**Comment by nacharya1** [comment]
@lemillermicrosoft can you take a look into this?

**Comment by lemillermicrosoft** [comment]
Last I knew we didn't support .Net Framework 4.6.2 -- can you confirm/deny @shawncal 

cc @SergeyMenshykh the author of `NonDisposableHttpClientHandler`

**Comment by lemillermicrosoft** [comment]
Also to confirm this is not a planner specific issue, can you confirm/deny whether you can run any semantic functions @sannyg0701 ?

**Comment by lemillermicrosoft** [comment]
Closing for now as no-repro. Please re-open as appropriate.
