### ISSUE TITLE
Feature: Can we make it possible to run with no embeddings?

### ISSUE THREAD

**Issue by wrharper-AASP** [microsoft/semantic-kernel#2488]
I am looking for ways to modify the kernel.cs file to process even with no embedding defined.

Example:
IKernel kernel = Kernel.Builder
            .WithOpenAIChatCompletionService(GPT35_Turbo_16K, ChatGPTKey)
            .WithMemoryStorage(memoryStore)
            .Build();

should be possible without using embedding. I know there are cons to this, but I would still like to make this possible.

**Comment by wrharper-AASP** [comment]
1st error:
Function1. Microsoft.SemanticKernel.Core: Service not found: Service of type Microsoft.SemanticKernel.AI.Embeddings.ITextEmbeddingGeneration and name <NONE> not registered.

fixed by added to kernel.cs:
```
        // == Added by me ===============================================================
        if (typeof(T) == typeof(ITextEmbeddingGeneration))
        {
            name ??= this.Config.DefaultServiceId;

            if (!this.Config.TextEmbeddingGenerationServices.TryGetValue(name, out Func<IKernel, IEmbeddingGeneration<string, float>> factory))
            {
                throw new KernelException(KernelException.ErrorCodes.ServiceNotFound, $"'{name}' text embedding service not available");
            }

            var serv = factory.Invoke(this);
            return (T)serv;
        }
        // ==============================================================================
```

2nd error:
Exception while executing function: Function1. Microsoft.SemanticKernel.Core: Service not found: '__SK_DEFAULT' text embedding service not available.

**Comment by wrharper-AASP** [comment]
After looking further into this, no embeddings are working with AI by default but not Redis Similarity search. So, this has to be an issue with the https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.Memory.Redis/RedisMemoryStore.cs

**Comment by wrharper-AASP** [comment]
I have found a way to make this possible, will reopen tomorrow if it does not work.

**Comment by stz92** [comment]
Could you share how to work without embeddings?

**Comment by wrharper-AASP** [comment]
I only had a problem with the Redis Embedding link. It was tricky to follow it because Redis itself requires its own embedding which cannot be avoided, but you can't stop OpenAI's embeddings.
It is a little strange that you still have to define a valid one when making the kernel though. My guess is because they did WAYYYYY too much abstract programming.
There is already a boolean built in, it is just optional.
![image](https://github.com/microsoft/semantic-kernel/assets/117128832/37dd554e-87e4-4975-8893-38eb06f94a42)

**Comment by dsgrieve** [comment]
According to the class documentation, `withEmbeddings` means: "If true, the embedding will be returned in the memory record". This is not the same as the 'no embeddings' that you want.

**Comment by wrharper-AASP** [comment]
ok, this is still an issue then. The code is a little confusing to read since this is now a 3rd meaning for embeddings within it.

**Comment by dsgrieve** [comment]
What problem does 'run with no embeddings' solve?

**Comment by wrharper-AASP** [comment]
1. Embedding for Redis algorithm (required) due to: https://redis.io/docs/interact/search-and-query/search/vectors/ can't do vecorfields without it?
2. Embedding for OpenAI (which should be possible to turn off/what I need)
3. what dsgrieve said: withEmbeddings means: "If true, the embedding will be returned in the memory record"

It is simply just a feature required by our Team. They believe you can get different results via "unstructured data", and this is likely true.

The code needs to be a little clearer too about what Embedding they mean at the time.

**Comment by dsgrieve** [comment]
Does https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.Memory.Redis help?

**Comment by wrharper-AASP** [comment]
no because 
    .WithOpenAITextEmbeddingGenerationService("text-embedding-ada-002", Env.Var("OPENAI_API_KEY"))
should not be required....

**Comment by wrharper-AASP** [comment]
Microsoft.SemanticKernel.Memory -> SearchAsync is what is used by Redis.
    /// <param name="withEmbeddings">Whether to return the embeddings of the memories found.</param>

Ok, it does link to MemoryRecord... but if you do say no to embeddings in memory records than it shouldn't be using embeddings as expected? This appears to be working as intended.

It is only OpenAI that is the problem then, not Redis now.

**Comment by wrharper-AASP** [comment]
![image](https://github.com/microsoft/semantic-kernel/assets/117128832/9a3f67f4-b1ab-41fe-bd4e-fefa3859d42f)
Tried bypassing the text completion with this param, but it is still giving the same error even without using Redis:
Exception while executing function: Microsoft.SemanticKernel.Core: Service not found: '__SK_DEFAULT' text embedding service not available.

**Comment by nacharya1** [comment]
@dluc or @crickman can you provide any guidance on this issue/question.

**Comment by wrharper-AASP** [comment]
any status on this one?

**Comment by lemillermicrosoft** [comment]
By definition, a MemoryRecord needs an embedding. So it is not possible to use a MemoryStore that returns MemoryRecords without having an embeddings service to generate embeddings. Closing as designed. If you can explain the scenario more, why you want to use Redis MemoryStore but without embeddings service, that could help. It sounds like you can just build your own data connector.
