### ISSUE TITLE
Python Azure Cognitive Search Connector expects existing ACS to have few fields which are required in code

### ISSUE THREAD

**Issue by kshitijcode** [microsoft/semantic-kernel#2492]
I was trying to use AzureCognitiveSearchMemoryStore to query an existing Azure Cognitive Search resource not created through SK. 

When I was trying to query it using 

` result = await connector.get_nearest_match_async("oaisyllabus-vector-index-new", results[0])`

I got errors that the search document doesn't have the following fields 

Id
Text
ExternalSourceName
Description
AdditionalMetadata
IsReference

Since my existing source doesn't have fields of the same name it was failing. On further debugging, I found these values to be hard coded in the connector code

SEARCH_FIELD_ID = "Id"
SEARCH_FIELD_TEXT = "Text"
SEARCH_FIELD_EMBEDDING = "Embedding"
SEARCH_FIELD_SRC = "ExternalSourceName"
SEARCH_FIELD_DESC = "Description"
SEARCH_FIELD_METADATA = "AdditionalMetadata"
SEARCH_FIELD_IS_REF = "IsReference"

Is this as by design that we cannot use existing ACS fields ? If no , then should we look for a way to parameterize it?

I am happy to raise a PR to make these corrections based on the way we proceed.

**Comment by evchaki** [comment]
@kshitijcode thanks for finding this.  @awharrison-28 - would you like @kshitijcode  to do a PR based on the info above?

**Comment by moonbox3** [comment]
Closing this issue as the related PR has been closed. If there is further work needed around this please re-open an issue. Thank you.
