### ISSUE TITLE
Python: Add Python Sample for using AzureCognitiveSearchMemoryStore with OpenAI embeedings

### ISSUE THREAD

**Issue by kshitijcode** [microsoft/semantic-kernel#2493]
I spent more than 2 days figuring this out and get this working since the ACS implementation is different from VoltalileMemoryStore and we don't have any existing samples for Azure Cognitive Search Memory Store.  I want to add Python Sample for using AzureCognitiveSearchMemoryStore with OpenAI embeddings.  I am happy to raise a PR for the same.

**Comment by alexchaomander** [comment]
Feel free to create a sample! We have this one in @dluc's own repo but I agree that having something in the main SK repo would be nice! https://github.com/dluc/Azure-Cognitive-Search-20230720

**Comment by kshitijcode** [comment]
@alexchaomander added the same , kindly review :)
