### ISSUE TITLE
Java: Example17_ChatGPT error during compilation

### ISSUE THREAD

**Issue by slmnpk** [microsoft/semantic-kernel#2501]
I am getting this error while compiling /Example17_ChatGPT.java, please advise.

./Example17_ChatGPT.java:3: error: package com.azure.ai.openai does not exist
import com.azure.ai.openai.OpenAIAsyncClient;
                          ^
./Example17_ChatGPT.java:4: error: cannot find symbol
import com.microsoft.semantickernel.Kernel;
                                   ^
  symbol:   class Kernel
  location: package com.microsoft.semantickernel
./Example17_ChatGPT.java:5: error: cannot find symbol
import com.microsoft.semantickernel.SKBuilders;
                                   ^

**Comment by dsgrieve** [comment]
@slmnpk Are you building just the examples? What is your command line?

**Comment by slmnpk** [comment]
i am trying the code in online java compilers to run this sample.

**Comment by dsgrieve** [comment]
@slmnpk I'm not familiar with how to do that, but it looks like you are missing some dependencies. The release process ensures that all the examples build, so the issue must be in your configuration.

**Comment by d3r3kk** [comment]
Closing due to age and no response received.
