### ISSUE TITLE
`github-qna-webapp-react app` doesn't seem to actually interact with the downloaded repository

### ISSUE THREAD

**Issue by pavlovcik** [microsoft/semantic-kernel#2506]
**Describe the bug**
The `github-qna-webapp-react` app doesn't seem to actually interact with the downloaded repository.

**To Reproduce**
1. I set up the app according to the documentation, 
2. I downloaded https://github.com/microsoft/semantic-kernel
3. I asked the same question in the tutorial video "how do I get started with the book creator sample?"
4. The response shows that it is not aware of the downloaded repo. I tried with multiple repositories.

**Expected behavior**
I expected the response to be similar to what is in the video:

> The Book Creator Sample is a demonstration of how the Semantic Kernel can be used to create plans for functions to run. The app allows you to enter in a topic, and the Planner will create a plan for the functions to run based on the ask. You can see the plan along with the results. The Book Creator Sample is intended for educational purposes only and should not
be used in any production use case.

**Screenshots**

<img width="919" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/4975670/04d05055-16ac-48e9-8db2-f431fd8ac360">

> To get started with the book creator sample, you can follow these steps:
> 
> 1. Clone the GitHub repository to your local machine using the command `git clone `. Replace `` with the URL of the GitHub repository where the book creator sample is located.
> 
> 2. Once the repository is cloned, navigate to the project directory using the command `cd `. Replace `` with the name of the directory where the repository was cloned.
> 
> 3. Install any necessary dependencies by running the command `npm install` or `yarn install`, depending on your package manager.
> 
> 4. After the dependencies are installed, you can start the book creator sample by running the command `npm start` or `yarn start`.
> 
> 5. Open your web browser and navigate to `http://localhost:3000` to access the book creator sample.
> 
> Note: These steps are general guidelines and may vary depending on the specific repository and project structure. It's always a good idea to check the repository's documentation or README file for any specific instructions or requirements.

**Platform**
 - OS: MacOS 13.4.1 (c) (22F770820d)
 - IDE: N/A
 - Language: N/A
 - Source: I downloaded the dependencies according to the documentation, which included brew and a package from the Microsoft website.

**Comment by evchaki** [comment]
@gitri-ms - can you take a look at this.

**Comment by crickman** [comment]
Ok, I found the root cause.  The container/index name being queried doesn't match the one written to.

Fix incoming.

**Comment by crickman** [comment]
https://github.com/microsoft/semantic-kernel/pull/2569

**Comment by pavlovcik** [comment]
### Shell Log

I am running the latest version.

```sh
Last login: Sat Aug 26 22:16:25 on ttys011
github-qna-webapp-react $ pwd
~/microsoft/semantic-kernel/samples/apps/github-qna-webapp-react
github-qna-webapp-react $ git pull
git Already up to date.
github-qna-webapp-react $ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
github-qna-webapp-react $ git rev-parse HEAD
4b2b93d8b0d4d95150c0b7387de0f3b0420f7768
github-qna-webapp-react $
```
### Screenshot

The software is unable to understand the README.

<img width="1552" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/4975670/4741578d-5e10-4f66-9e97-233a0b881bd2">

### Referenced Material

The README is in the repository.

https://github.com/ubiquity/ubiquibot/blob/development/README.md

### Chat Completion Model
gpt-3.5-turbo

### Embeddings Model
text-embedding-ada-002

**Comment by pavlovcik** [comment]
Following up

**Comment by crickman** [comment]
Thanks.  Were you able to get a better result with the original case or are both cases not providing the expected result?

**Comment by pavlovcik** [comment]
> Thanks.  Were you able to get a better result with the original case 

Yes it worked as expected

**Comment by pavlovcik** [comment]
Hi there I'm following up
