### ISSUE TITLE
Python: OpenAITextCompletion does not accept logger parameter defined in TextCompletionClientBase interface in python SDK

### ISSUE THREAD

**Issue by blackchoey** [microsoft/semantic-kernel#2509]
**Describe the bug**
In Python SDK, the `TextCompletionClientBase` class declares `complete_async` function accepts 3 parameters: `prompt`, `settings` and `logger`.
But in `OpenAITextCompletion` which implements the interface, it only accepts 2 parameters: `prompt` and `settings`.

So following code will throw error:
```
text_completion_client = kernel.get_ai_service(TextCompletionClientBase)(kernel)
result = await text_completion_client.complete_async(
    prompt_template.text, request_settings, NullLogger()
)
```

The key problem here is: if we only pass 2 parameters to the function, it works but type checking will fail. If we pass 3 parameters to satisfy the type checking, the code won't workk.

Related code in the repository:
https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/connectors/ai/text_completion_client_base.py#L15-L20
https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_completion.py#L57-L59

**To Reproduce**
Repro with below sample code
```
text_completion_client = kernel.get_ai_service(TextCompletionClientBase)(kernel)
result = await text_completion_client.complete_async(
    prompt_template.text, request_settings, NullLogger()
)
```

**Expected behavior**
I can successfully call the function as well as pass type checking.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/16605901/47a3f69b-3b9e-4023-9a65-a0f89c7a993d)

**Platform**
 - OS: Windows
 - IDE: VSCode
 - Language: Python
 - Source: pip package version 0.3.7.dev0

**Comment by evchaki** [comment]
@blackchoey  - thank you for reporting this.  @mkarle  - can you take a look and see what is going on here.

**Comment by juliomenendez** [comment]
I created a PR that might solve this issue. Waiting for reviews.
