### ISSUE TITLE
Calling native functions  with db calls  causes issues with MultipleActiveResultSets

### ISSUE THREAD

**Issue by giannik** [microsoft/semantic-kernel#2512]
Currently to import native skills in kernel you must manuall inject the dependencies like so : 
```
 kernel.ImportSkill( new GlobalVariablesSkill(
                contentHandleManager:sp.GetRequiredService<IContentHandleManager>(),
                contentManager:sp.GetRequiredService<IContentManager>()

            ),  nameof(GlobalVariablesSkill));

```

these services require calls to an sql server database . 

Here is the native function : 

```
public sealed class GlobalVariablesSkill
{

    private readonly   IContentHandleManager _contentHandleManager;
    private readonly   IContentManager _contentManager;

    public GlobalVariablesSkill(IContentHandleManager contentHandleManager, IContentManager contentManager)
    {
        _contentHandleManager = contentHandleManager;
        _contentManager = contentManager;
    }



    [SKFunction, Description("Get a global variable value")]
    public async Task<string> GetAsync( [Description("Variable name")] string variable)
    {
       var contentItemId= await _contentHandleManager.GetContentItemIdAsync("alias:" + variable);
       if (string.IsNullOrEmpty(contentItemId))
       {
           return null;
       }
       var contentItem = await _contentManager.GetAsync(contentItemId );
       if (contentItem == null)
       {
           return null;
       }
        //get the value of the text field named "Value"
       return contentItem.Content?.Workspacevariable.Content.Text.ToString() ?? null;

    }


}

```

My issuse is thate when calling this native function twice in a semantic function : eg : 

```

{{ GlobalVariablesSkill.Get "param1" }}


{{ GlobalVariablesSkill.Get "param2" }}

```

i get a database error from database '' The connection does not support MultipleActiveResultSets."
if i change the connection string to support  MultipleActiveResultSets =True then it works .

If i make only 1 call to {{ GlobalVariablesSkill.Get "param1" }} within the semantic function it works. 

Any ideas  ? 
My guess is that because im manually injecting the required services to the native function this is happening.

Ideally i would like to not have to change my connection string settings to allow multiple calls the native functions.

**Comment by giannik** [comment]
maybe if we could DI importing skills like : 
```
 kernel.ImportSkill<IGlobalVariablesSkill>
```
and let the DI engine resolve dependencies , it might be solved ?

**Comment by gingters** [comment]
In your Function class, you don't want to have a singleton DB connection (or EF Context) captured in a service class like your content classes, but you want to inject an `IServiceScopeFactory` into the class.

Within the invocation of your function, you create a new DI scope on the scope factory, and from the ServiceProvider on that scope you then retrieve both your `IContentManager` and your `IContentHandleManager` (hopefully they are both registered as scoped).

That way each callback from the LLM into your database will use a new connection from the .NET internal connection pool and you don't have multiple queries at the same time on the very same connection (assuming your service classes use an EF context or a db connection that get injected through normal .NET DI means).

**Comment by giannik** [comment]
@gingters thank you. 
That seems to fix it !
