### ISSUE TITLE
.Net: Improve resource disposal 

### ISSUE THREAD

**Issue by JadynWong** [microsoft/semantic-kernel#2513]
@JadynWong good point. Unfortunately, that is the problem in Kernel, which we want to fix in future PRs. There is an idea to remove resource disposal in Kernel for instances that were passed through `KernelBuilder`, so the caller will be responsible for disposal. In this case we will be able to remove `IDisposable` interface from Kernel at all.

_Originally posted by @dmytrostruk in https://github.com/microsoft/semantic-kernel/pull/2211#discussion_r1284530727_
            
Due to the Kernel cascading resource disposal, this may cause the following problems.

In chat-copilot, `IKernel` is registered as scoped lifetime with DI, `MemoryStore` is registered as singleton lifetime, and whenever `IKernel` is disposed, it tries to dispose all internal instances that implement `IDisposable`. This results in the instances inside the MemoryStore that implement `IDisposable` being disposed of after the first request, unless the application is restarted.

https://github.com/microsoft/chat-copilot/blob/d5a0d464c2b9871db73fd73e577be767d3287dc6/webapi/Extensions/SemanticKernelExtensions.cs#L50

https://github.com/microsoft/chat-copilot/blob/d5a0d464c2b9871db73fd73e577be767d3287dc6/webapi/Extensions/SemanticKernelExtensions.cs#L242

https://github.com/microsoft/semantic-kernel/blob/fce878c6d8dc62452b78b74b033277e44527af8c/dotnet/src/SemanticKernel/Kernel.cs#L250

https://github.com/microsoft/semantic-kernel/blob/fce878c6d8dc62452b78b74b033277e44527af8c/dotnet/src/SemanticKernel/Memory/SemanticTextMemory.cs#L132

**Comment by evchaki** [comment]
@JadynWong  - thank you for raising this item.  @dmytrostruk  / @gitri-ms  can you take a look at this and respond.

**Comment by dmytrostruk** [comment]
This is a known issue, and we are going to resolve it soon. There is also parallel work to remove `MemoryStore` dependency from Kernel and use it as separate plugin, which will also resolve particular issue with `MemoryStore` disposal.

**Comment by gitri-ms** [comment]
@dmytrostruk Seems like you've got a good handle on this so I'm going to remove myself and move it to the SK project. If there's anything that needs to happen on the Apps side when you bring in the fix, let me know and I can help with that.

**Comment by matthewbolanos** [comment]
Memory store has been removed from the kernel so this should be resolved now
