### ISSUE TITLE
utilization of one planner within another

### ISSUE THREAD

**Issue by pi-curst** [microsoft/semantic-kernel#2524]
I'm thinking of using the Stepwise planner for my data retrieval from search plugins. Once I've got the data, I'd like to switch over to a Sequential planner to handle arithmetics/ dataframe related operations. Can we make one planner work inside the other?

**Comment by nacharya1** [comment]
@lemillermicrosoft to provide guidance on best approach for this.

**Comment by lemillermicrosoft** [comment]
Yeah, you should be able to do this! I've done this personally by creating a Skill with two functions, one that calls SequentialPlanner to create[+ invoke] a plan and the other that uses StepwisePlanner. I then expose those two skills to ActionPlanner to route to the most appropriate function depending on the ask.
