### ISSUE TITLE
.Net: Sequential Planner results are always prepended with a newline character

### ISSUE THREAD

**Issue by takeo-iw** [microsoft/semantic-kernel#2525]
**Describe the bug**
I tried notebook 05-using-the-planner, planner results are always prepended with a newline character.
I also tried a simple my process, but the result was the same.

**To Reproduce**
Try notebook 05-using-the-planner, and see results below.
You can see the blank line.
![image](https://github.com/microsoft/semantic-kernel/assets/108264521/128611a8-5931-48c0-9a13-783a51c9d2c3)

**Expected behavior**
Output the original return value of the function verbatim.

**Screenshots**

**Platform**
 - OS: Mac
 - IDE: VS Code
 - Language:  C#
 - Source: Microsoft.SemanticKernel 0.20.230821.4-preview

**Additional context**
I tried a simple my process. Function return "Long sleeve shirt", but results are prepended with a newline character.
![image](https://github.com/microsoft/semantic-kernel/assets/108264521/5a939619-60f3-4ed4-bbf5-db4890fb5fbd)
![image](https://github.com/microsoft/semantic-kernel/assets/108264521/2a013231-df73-42dd-83da-b5830a021821)
![image](https://github.com/microsoft/semantic-kernel/assets/108264521/f7d0df86-51ab-4b5e-b595-ebfc30a6d37a)

**Comment by nacharya1** [comment]
@lemillermicrosoft can you investigate if this a bug or provide guidance around this behaviour.
