### ISSUE TITLE
.Net: Unable to find native functions in SK VSCode Extension (Experimental Feature - Native Functions in Semantic prompts)

### ISSUE THREAD

**Issue by hario90** [microsoft/semantic-kernel#2529]
**Describe the bug**
(This issue was originally posted by @jcf0419 and was transferred to a private project and couldn't be transferred back. Posting again here for visibility.)

I followed the settings update to enable the experimental feature via this videos: https://www.youtube.com/watch?v=0OVQRcnDDL0 (Thanks for all the hard work posting updates Alex Chao and Mark! I'm a huge fan of the work being done here!) and restarted vscode.

I have a C# console app that has many registered native functions but when hitting Control+Space in the {{ }} area of a skprompt.txt file only the included functions show up.

Here is an example native function from my project that resides in the same namespace as my semantic skills which I can run successfully using the SK vscode extension:

```
[SKFunction, Description("Execute a query that pulls the schema of the entire database")]
public string GetDatabaseSchema([Description("the database name")] string memory_db_name)
{
    var input = @"WITH RECURSIVE base AS (
                    SELECT 
                        name AS table_name, 
                        replace(replace(trim(substr(sql, instr(sql, '(')+1, length(sql) - instr(sql, '(') - 1)), char(10), ''), char(13), '') AS column_definition
                    FROM sqlite_master 
                    WHERE type='table'
                )";

    var dbPath = Path.Combine(Directory.GetCurrentDirectory(),"hal-process","State",memory_db_name);

    using SqliteConnection connection = new(dbPath);
    connection.Open();
    using SqliteCommand command = new(input, connection);
    using SqliteDataReader reader = command.ExecuteReader();
    DataTable result = new();
    result.Load(reader);
    return result.ToString();
}
```

**To Reproduce**
1. Enable Experimental Feature to include Native Functions
2. Open skprompt.txt file and attempt to browse included native functions in the curly braces {{}} via control space
3. Notice no native functions showing.

**Expected behavior**
3. See my GetDatabaseSchema function

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/7981019/888c353d-3fc9-4ae0-ac3e-d3b5d0cec4f4)
![image](https://github.com/microsoft/semantic-kernel/assets/7981019/d6f107a1-9a18-446b-bdca-c5b67de2297c)

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#
 - Source: 

```
"Microsoft.CognitiveServices.Speech" Version="1.28.0" 
"Microsoft.Extensions.Hosting" Version="8.0.0-preview.2.23128.3" 
"Microsoft.Extensions.Logging" Version="8.0.0-preview.2.23128.3" 
"Microsoft.Extensions.Logging.Console" Version="8.0.0-preview.2.23128.3" 
"Microsoft.SemanticKernel" Version="0.18.230725.3-preview" 
"Microsoft.SemanticKernel.Connectors.AI.OpenAI" Version="0.18.230725.3-preview" 
"Microsoft.SemanticKernel.Connectors.Memory.Pinecone" Version="0.18.230725.3-preview" 
"Microsoft.SemanticKernel.Connectors.Memory.Sqlite" Version="0.19.230804.2-preview" 
"NAudio" Version="2.1.0" 
"NetCoreAudio" Version="1.7.0" 
"SSH.NET" Version="2020.0.2" 
"System.Speech" Version="7.0.0" 
"Twilio" Version="6.10.1" 


Thanks for looking into this!

Jeff
```

**Comment by hario90** [comment]
Hi @jcf0419,

Your skills may not show up in intellisense for several reasons that I can think of:
1. The skill class is not public (I have a PR to change this. Methods will still need to be public.)
2. Your skill's constructor has an unexpected constructor - empty constructors and constructors taking 1 parameter with type `IKernel` are the expected constructor types.
3. You need to build the DLL again and uncheck + check the experimental feature in user settings to clear cache and get the extension to use the latest DLL
4. Try matching the version of `Microsoft.SemanticKernel.Connectors.Memory.Sqlite` to the version of `Microsoft.SemanticKernel`. I don't think this is the cause of your issue but generally the connectors should match the version of Semantic Kernel that you're using.
5. There was an exception that occurred while the extension tried to import your skill. To verify this was the case you'll need to check dev tools for the error log "Unable to load native skills from".

To open dev tools in VS Code, go to Help > Toggle Developer Tools. In the console tab, search for the text "Unable to load native skills from". This will print the assembly it tried to load from and the exception message.  (My PR has a change to surface this error as an error pop up with the skill that failed to load if a specific skill failed to load, the exception message and the inner exception message.)

If the exception message is there but isn't very helpful, you can try to see if any skills can load individually to isolate the issue. If any of the skills fail to load, the extension will stop importing any unloaded skills after that.  It's possible that an issue in one of your skills is preventing other skills from loading. One thing you can do is try to isolate each native skill in your project to see if they can load individually by commenting out the `[SKFunction]` attribute on each function on the other skills. Follow the steps in 3 each time you try loading a different skill.

Additionally, check the constructor method of each skill. Another reason an exception may occur is if you try to get a service from the kernel in a constructor that takes a kernel as an argument, e.g.:
```
 public ChatSkill(IKernel kernel)
    {
        // Set up the chat completion and history - the history is used to keep track of the conversation
        // and is part of the prompt sent to ChatGPT to allow a continuous conversation
        this._chatCompletion = kernel.GetService<IChatCompletion>();
        this._chatHistory = this._chatCompletion.CreateNewChat("Be a helpful assistant");
    }
```
This won't work currently with the extension because the kernel passed to the constructor by the extension won't have services registered to it. This is something I'll look into how to fix.

**Comment by hario90** [comment]
Hi @jcf0419,

We released a new version of the extension that should help with troubleshooting. Additionally, if your native functions were in a non-public class, they should be discovered with the newest version.

To view the logs, in the Output tab, select "Semantic Kernel" from the dropdown. Then when you type CTRL + SPACE within curly brackets in a skprompt.txt file, you should see any exceptions if they occur within the output window.


![Image](https://github.com/microsoft/semantic-kernel/assets/7981019/15d2d59a-a1fd-46fe-a093-9db97517c4c2)

**Comment by jcf0419** [comment]
Hey @hario90 

No luck on my end..

I![IMG-20230828-WA0000.jpg](https://github.com/microsoft/semantic-kernel/assets/11797742/1a36cc64-8273-447a-99fd-9194af40dea2)

Does it looks for native functions included just in the namespace or does it have to be added to the kernel in the a project somehow? Does it work in folder that has many projects?

**Comment by hario90** [comment]
Thanks for this information, I was able to reproduce the issue and it appears to be related to the .csproj file being in a nested folder. I'll create another PR to fix this so that nested .csproj files can be discovered and also add more logging to the assembly discovery process. 

The current logic for determining the DLL locations relies on the .csproj name unless `AssemblyName` node(s) are found within the .csproj file. Thus, I wouldn't recommend renaming your DLL any other way when using this experimental feature. I'll update this thread once the update to the extension is out. Thanks for your patience!

To answer your question, the extension creates its own instance of the kernel so any configurations you do on your instance won't be applied to the extension's instance. The extension will use the endpoint config data that you set through the extension.

**Comment by hario90** [comment]
Hi @jcf0419, we released another update to the extension with the fix for nested C# projects. Please let us know if the fix worked for you!

**Comment by jcf0419** [comment]
I'm still getting an issue loading the native functions - note only the hal.dll has native functions in it's namespace:

Here is the output from the extension log in vscode:

Finding project assemblies.
Found the following *.csproj files: hal-ui.csproj, hal-backend.csproj, hal.csproj
Didn't find assembly names in hal-ui.csproj. Assembly name is assumed to be hal-ui.dll
Didn't find assembly names in hal-backend.csproj. Assembly name is assumed to be hal-backend.dll
Didn't find assembly names in hal.csproj. Assembly name is assumed to be hal.dll

=============================

Getting custom native skills from c:\Users\jcf04\Documents\repos\Hal\hal-ui\bin\Debug\net8.0\hal-ui.dll, c:\Users\jcf04\Documents\repos\Hal\hal-process\bin\Debug\net8.0\hal.dll
Unable to load native skills from c:\Users\jcf04\Documents\repos\Hal\hal-ui\bin\Debug\net8.0\hal-ui.dll. Details: $Unable to load one or more of the requested types.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621). Inner Exception: $
Unable to load native skills from c:\Users\jcf04\Documents\repos\Hal\hal-process\bin\Debug\net8.0\hal.dll. Details: $Unable to load one or more of the requested types.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Extensions.Logging.Console, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.. Inner Exception: $

**Comment by jcf0419** [comment]
@hario90 

From those logs - this line looks interesting.

`Unable to load native skills from c:\Users\jcf04\Documents\repos\Hal\hal-process\bin\Debug\net8.0\hal.dll. Details: $Unable to load one or more of the requested types.`

**Comment by hario90** [comment]
@jcf0419 Thanks for the troubleshooting info and sorry for the delay. I'm able to repro this locally. This is a known exception (ReflectionTypeLoadException) that occurs when using reflection to get the types in an assembly and one of the types isn't loading. In my case, it is likely due to having projects that share dependencies while the extension currently doesn't have a way to know about the shared dependencies yet.

I'm not sure if it's the same issue that you have though. Either way, @markwallace-microsoft will be taking this issue over. I've shared my repro steps and sounds like he has some ideas he can try out.

**Comment by jcf0419** [comment]
Sounds good. I'll try to support testing this until resolved :)

**Comment by matthewbolanos** [comment]
The VS Code extension is now in maintenance mode, so we will not be picking up this issue
