### ISSUE TITLE
Python: C++ programing language suport

### ISSUE THREAD

**Issue by JustinKJChen** [microsoft/semantic-kernel#2540]
We just see C#, Python and Java programing language. Will you have C++ support?

**Comment by alexchaomander** [comment]
Currently no plans to have a C++ version of the Kernel but if there is interest from the community, let us know! What sort of scenarios / use cases do you have in mind where a C++ Kernel would be important?

**Comment by JustinKJChen** [comment]
We built copilot plugin for service level in Windows 11. Service level without UX prefer C++ than C#.

**Comment by evchaki** [comment]
@JustinKJChen you can host SK as a service and pass the requests to that end point with your plugin running in the service also.
