### ISSUE TITLE
.NET : Add .NET Sample for using AzureCognitiveSearchMemoryStore with OpenAI embeddings

### ISSUE THREAD

**Issue by kshitijcode** [microsoft/semantic-kernel#2541]
Similar to https://github.com/microsoft/semantic-kernel/issues/2493
We don't have any existing samples for Azure Cognitive Search Memory Store in . NET. I want to add  .NET Sample for using AzureCognitiveSearchMemoryStore with OpenAI embeddings. I am happy to raise a PR for the same.

**Comment by nacharya1** [comment]
@kshitijcode would love to see this PR. Feel free to submit one.
