### ISSUE TITLE
Disappearance of AzureCognitiveSearchMemory

### ISSUE THREAD

**Issue by neel015** [microsoft/semantic-kernel#2544]
**Describe the bug**
`AzureCognitiveSearchMemory` was deleted from the repository. This had implementations from `ISemanticTextMemory`

**Earlier**
The `SearchAsync` method of `AzureCognitiveSearchMemory` could query the cognitive search without the need of an Open AI Embeddings Model.

**Now**- 
The `AzureCognitiveSearchMemory` has been removed, and everything is driven via `SemanticTextMemory` - even the cognitive search. The `SemanticTextMemory` requires an embedding endpoint to be present.

**Expected behavior**
Adding Capability/ Document Capability to query `AzureCognitiveSearch` without the need of an embeddings model.
This is a feature which was removed without documentation?

**Comment by nacharya1** [comment]
@dluc can you provide some guidance to this?

**Comment by dluc** [comment]
The earlier memory skill was based exclusively on Azure Cognitive Search "Semantic Search", which is very expensive and was a temporary step towards using only "Vector Search" once publicly available. The intent is/was to align all SK memory stores on the same approach for portability.
In the new memory solution being developed at https://github.com/microsoft/semantic-memory we will revisit this, allowing to leverage each storage engine features at best, e.g. supporting hybrid search, in this case Text Search + Semantic Search + Vector Search. The work is in progress :-)

**Comment by matthewbolanos** [comment]
Closed because of the switching capability provided by dluc

**Comment by lakshya-mishra** [comment]
Hi @matthewbolanos and @dluc , is "AzureCognitiveSearchMemoryStore" available on Python?? If yes, please let me know, I'm unable to find it..
