### ISSUE TITLE
.Net: Improve error messages

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#2559]
## Acceptance Criteria
**As an** engineer working on SK
**I want SK to** have consistent and useful error messages
**So that** SK consumer code can easily detect the root cause of errors

## Technical Scope
* Review all exceptions thrown by all SK components and verify whether the error messages in these exceptions are informative and contain sufficient information to convey the cause of the error.
* Change the message and all required details if necessary.
* Consider localizing the error messages.

## Additional Details/Asks
* https://github.com/microsoft/semantic-kernel/pull/2546#discussion_r1304082305

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
