### ISSUE TITLE
.Net: Add ability to use FLAT algorithm in next release.

### ISSUE THREAD

**Issue by wrharper-AASP** [microsoft/semantic-kernel#2561]
Currently I have made a custom version to work around this, but we will need the ability to stay up to date with new releases without doing this.

Source: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.Memory.Redis/RedisMemoryStore.cs
Line: 269

This should be a parameter instead. There are situations where our team needs these to be options that can be modified instead of being set in stone.

This should be an easy integration since it is already possible and partly built in.

**Comment by nacharya1** [comment]
@wrharper-AASP please a send a pr and we would love to review the proposed changes.

**Comment by wrharper-AASP** [comment]
I would have to upload the entire project because I basically just created an alternate chain. There are better ways to do it than what I did.

My recommendation is adding a param to: public async Task CreateCollectionAsync(string collectionName, CancellationToken cancellationToken = default)
so that it is something like:
```
public async Task CreateCollectionAsync(string collectionName, VectorAlgo vectorIndexAlgorithm, CancellationToken cancellationToken = default)
    {
        FTCreateParams ftCreateParams = FTCreateParams.CreateParams().On(IndexDataType.HASH).Prefix($"{collectionName}:");
        Schema schema = new Schema()
            .AddTextField("key")
            .AddTextField("metadata")
            .AddNumericField("timestamp")
            .AddVectorField("embedding", vectorIndexAlgorithm, new Dictionary<string, object> {
                    {"TYPE", DefaultVectorType},
                    {"DIM", this._vectorSize},
                    {"DISTANCE_METRIC", this._vectorDistanceMetric},
                });

        await this._ft.CreateAsync(collectionName, ftCreateParams, schema).ConfigureAwait(false);
    }
```

**Comment by wrharper-AASP** [comment]
oh, and keep the original too so people can do it either way as an alternative.
This would keep projects from breaking while also making it as a new feature. That would be the safest way I can think of.

**Comment by wrharper-AASP** [comment]
I'm also not really sure why ConfigureAwait(false) is used so much. If this isn't used properly it can create deadlocks.

**Comment by JadynWong** [comment]
If you upgrade to [dotnet-0.20.230821.4-preview](https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-0.20.230821.4-preview), I think it'll be supported.

https://github.com/microsoft/semantic-kernel/pull/2211

**Comment by JadynWong** [comment]
Did you check out PR#2211?

https://github.com/microsoft/semantic-kernel/blob/4b2b93d8b0d4d95150c0b7387de0f3b0420f7768/dotnet/src/Connectors/Connectors.Memory.Redis/RedisMemoryStore.cs#L40

**Comment by wrharper-AASP** [comment]
Ok, I found a way to link it. Now I don't have to write custom code anymore. 👍 
The only issue left now is how can you make embeddings optional?
It looks like this is already in progress though:
https://github.com/microsoft/semantic-kernel/issues/2488#issuecomment-1686687799
