### ISSUE TITLE
Java: searchAsync does not limit the number of results

### ISSUE THREAD

**Issue by dsanchor** [microsoft/semantic-kernel#2572]
**Describe the bug**

When running a search in memory and limiting the results to certain number, I have noticed that this limit is not taken into account.

For instance, if I set a limit of 4 results, I am getting result entries above that number.

**To Reproduce**
1. Create a Kernel with Memory (AzureCognitiveSearchMemory in this case)

        String modelId="gpt-35-turbo";
        String acsEndpoint="yourAcsEndpoint";
        String acsApiKey="yourAcsApiKey";
        Kernel kernel = SKBuilders.kernel()
                .withDefaultAIService(SKBuilders.chatCompletion()
                        .setModelId(modelId)
                        .withOpenAIClient(client)
                        .build())
                .withMemory(new AzureCognitiveSearchMemory(acsEndpoint, acsApiKey))
                .build();

2. Perform a search using this kernel:

        String collection = "yourcollection";
        String query = "yourquery";
        int limit= 10;
        System.out.println("Limit is " + limit);
        List<MemoryQueryResult> result = kernel.
                                            .getMemory()
                                            .searchAsync(collection, 
                                                query, limit, 0.7, false)
                                            .block();
        System.out.println("Returning " + result.size() + " results");

**Expected behavior**
The search should return an amount of result entries below or equals than the limit set.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/18459098/ab0be9f0-11b6-46b9-a3a6-fd4467c8b4fb)

**Platform**
 - OS: Linux
 - IDE: VS Code
 - Language: Java
 - Source: 0.2.8-alpha

**Comment by dsanchor** [comment]
This can also be reproduced with [Example14_SemanticMemory.java](java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example14_SemanticMemory.java). You must change the query to: _What is in the README?_

In the sample, the limit is set to 2. The result you get contains 3 entries.

See output:

<img width="955" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/18459098/bbf10aec-b159-4184-bbc8-7c997315f6e8">

**Comment by kshitijcode** [comment]
@dsgrieve Can I pick this up ?

**Comment by dsgrieve** [comment]
@kshitijcode Absolutely! Just follow https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md
