### ISSUE TITLE
.Net: Per chunk header support in the TextChunker

### ISSUE THREAD

**Issue by anthonypuppo** [microsoft/semantic-kernel#2573]
Update the TextChunker with a header property that gets prepended to generated chunks. This will help enhance RAG systems (such as helping to maintain source context after chunking).

https://github.com/microsoft/semantic-kernel/pull/2574

**Comment by nacharya1** [comment]
@dluc \ @crickman can you take look into this request.

**Comment by crickman** [comment]
https://github.com/microsoft/semantic-kernel/pull/2574
