### ISSUE TITLE
.Net: adding chat completion and settings to Oobabooga connector

### ISSUE THREAD

**Issue by jsboige** [microsoft/semantic-kernel#2583]
The [following PR](https://github.com/microsoft/semantic-kernel/pull/2229) was proposed to improve the Oobabooga completion provider, adding its chat completion counter part, and introducing settings for fine grained control on text and chat completions.

**Comment by nacharya1** [comment]
@jsboige  FYI: We recently updated our contributing guidelines [here](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#adding-plugins-and-memory-connectors , stating we are not directly adding plugin and connectors directly into the SDK repository. We are encouraging the community to host their own plugins and connectors separately in their own repositories. At the time we are exploring how we can provide a way to discover existing and new plugins and connectors and should have an update soon. I am going to close this issue given our change in contribution guidelines.
