### ISSUE TITLE
.Net: [dotnet] Is there a way to get the "final" prompt sent to OAI Api from a Semantic function?

### ISSUE THREAD

**Issue by luismanez** [microsoft/semantic-kernel#2585]
We are using different semantic functions and we like the flexibility they provide with the skprompt.txt files. However, for audit/log purposes we'd like to get the final prompt that the semantic function is sending to OpenAI API, but I don't see it possible (happy to probe me wrong XD).

Another option is at least to get the raw content of the skprompt.txt file, and use the PromptTemplateEngine to get that final prompt, but don't see it possible either.

Thanks!

**Comment by nacharya1** [comment]
@luismanez, we have this available apart the telemetry offering available in Semantic Kernel to learn more on how to set this up see > https://devblogs.microsoft.com/semantic-kernel/unlock-the-power-of-telemetry-in-semantic-kernel-sdk/

**Comment by luismanez** [comment]
Thanks @nacharya1 didn´t realise the prompt was also available in there (watched Dmytro Struk video too).

However, in my opinion, depending on the telemetry framework to get something so "owner" of the function seems a bit unnatural to me.

I mentioned log/audit, but is not just that. My function is also having a History variable with latest 5 messages, and I need to store the generated prompts in my DB. I really think the SemanticFunction object should expose the Prompt template somehow.

Thanks again.

**Comment by nacharya1** [comment]
@luismanez - we have #1714 in PR review which will help provide the hooks to capture "Get: Prompt generated by the current Kernel TemplateEngine before calling the LLM" and post hooks are slated for work apart of #2324.

**Comment by bilalchraibi** [comment]
@nacharya1 Is it possible to have an example on how to get the prompt that will be sent to the LLM using SK?

Thanks

**Comment by mohammedtabish0** [comment]
> [bilalchraibi](/bilalchraibi)

+1

**Comment by mohammedtabish0** [comment]
> @nacharya1 Is it possible to have an example on how to get the prompt that will be sent to the LLM using SK?
> 
> Thanks

+1

**Comment by luismanez** [comment]
This can be done now using the ```IPromptFilter``` interface, handling the ```OnPromptRendered``` method. I have some samples in this repo I created for a community event:
https://github.com/luismanez/netcoreconf-bcn-2024/blob/main/src/CozyKitchen/HostedServices/Demo07/FunctionFilterHostedService.cs

**Comment by SabriKorkmaz** [comment]
@luismanez your repo is excellent, many thanks!
