### ISSUE TITLE
Python: .Net: Cannot get ai service without passing base class

### ISSUE THREAD

**Issue by Chris-hughes10** [microsoft/semantic-kernel#2589]
**Describe the bug**
I would like to be able to retrieve an ai service, but the service is not returned. Looking at the source code, this is because the check is hardcoded to the base class, rather than checking for subclasses.

**To Reproduce**
```
import semantic_kernel as sk

kernel = sk.Kernel()
kernel.add_chat_service("azure_gpt35_chat_completion", AzureChatCompletion(deployment_name=OPENAI_DEPLOYMENT_NAME, endpoint=OPENAI_ENDPOINT, api_key=OPENAI_API_KEY))

kernel.get_ai_service(AzureChatCompletion, service_id='azure_gpt35_chat_completion')
# Raises ValueError

```

**Expected behavior**
The service is returned

**Additional context**
it would be even better to be able to get the service only passing the id, it is already clunky having to pass the type

**Comment by moonbox3** [comment]
This is complete as of #5077. We've introduced an AI Service Selector class, and you can get the service via `kernel.get_service(service_id)`.
