### ISSUE TITLE
Python: Implement skill for python REPL

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#2592]
As shown by the code interpreter of GPT-4, defining a problem in code through the concept of a Planner or Agent and utilizing the execution results in connection with LLM can help to handle more issues easily and accurately, especially in tasks related to numbers.

It would be great if a python REPL was added to the CoreSkill so that the Planner can utilize it.
The addition of this skill can be better utilized when linked with #2385.

**Comment by joowon-dm-snu** [comment]
Although some code overlaps, the reason I opened it again as a different PR is mentioned in #2593.

**Comment by nacharya1** [comment]
@joowon-dm-snu thanks for creating the issue to align to your PR.
cc: @awharrison-28
