### ISSUE TITLE
SequentialPlanner not working -- Hallucinating functions

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#2606]
kernel.CreateSemanticFunction("{{$input}}", functionName: "askquestion", description: "Asks a question of the AI");
var planner = new SequentialPlanner(kernel);
Plan plan = await planner.CreatePlanAsync("What is the weather in Seattle?");
Console.WriteLine(plan.ToPlanString());

and it fails with:

Failed to find function 'getWeather' in skill 'getWeather'.

Is there any way to say "no, really, the only functions I have are the ones I told you about?!
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/issues/2831
- [ ] [Consider] Support multiple attempts at plan creation using error context in request
```

**Comment by lemillermicrosoft** [comment]
cc @stephentoub

**Comment by Chris-hughes10** [comment]
I think that part of the reason for this is that the temperature is internally hardcoded as 0.8. I have been getting massive variations in my plans, most of them are not correct

**Comment by matthewbolanos** [comment]
Closing since the sequential planner will be replaced by the handlebars planner
