### ISSUE TITLE
.Net: Operation not supported by RestApiOperationRunner

### ISSUE THREAD

**Issue by juantonioso** [microsoft/semantic-kernel#2634]
Hello! I'm working on a plugin to call an API. I have a POST method written in C#. Given that is only a POST action I don't get a response back so I had to add that 'plain/text' on OpenApiResponseWithBody. When testing in Swagger UI the content is printed as string saying that the POST method was successfully done. However when using that same function on the chat copilot app and with Sequential Planner I get the following error:

Unable to generate bot response. Details: Error: 400: Bad Request => Function invoke error: Error occurred while running plan step: The media type of the RestartVirtualMachine operation is not supported by RestApiOperationRunner.

The result in Swagger UI is this one:
<img width="1237" alt="Screenshot 2023-08-22 at 20 52 42" src="https://github.com/microsoft/chat-copilot/assets/142958361/017408fc-fdcf-49b4-b9e5-c3317cd55875">

What could I change to avoid this error? Thank you

**Comment by matthewbolanos** [comment]
This should now be fixed with the latest gen-4 and gen-5 planners
