### ISSUE TITLE
Python: Separate the integration point for Azure CosmosDB and MongoDB

### ISSUE THREAD

**Issue by prakul** [microsoft/semantic-kernel#2639]
The issue [#2591](https://github.com/microsoft/semantic-kernel/issues/2591) asking for MongoDB integration in Semantic Kernel was closed on Aug 28, calling it a duplication of Azure CosmosDB integration already in progress (issue [#2375](https://github.com/microsoft/semantic-kernel/issues/2375)). This decision needs to be revisited on multiple fronts.

1. Vector search in Azure Cosmos and MongoDB have different interfaces ([link](https://github.com/microsoft/semantic-kernel/issues/2591#issuecomment-1696049159)) and are not compatible.

2. By representing two separate products as one creates confusion and leads to a bad user experience. The [PR](https://github.com/microsoft/semantic-kernel/pull/2560/files#diff-b165a067b86131ac682b85ef035607c6c7f836f4498a1557a31da314ffe70616R32-R33) mentions an api_type parameter (with options azuremongodb and mongodbatlas) which is defaulting to Azure. Apart from being factually and semantically incorrect, this seems highly problematic to me as there might be a situation where the MongoDB user starts using this expecting it to be MongoDB and gets confused when the product doesn't work as expected, since it defaults to Azure CosmosDB.

3. [Azure Cosmos DB  provides an API compatible with MongoDB, PostgreSQL, and Apache Cassandra](https://azure.microsoft.com/en-us/products/cosmos-db), which have a vector database offering of their own. Currently Azure CosmosDB exposes the [vector capability for MongoDB in CosmosDB](https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/vector-search) and [vector capability for Postgres in CosmosDB](https://learn.microsoft.com/en-us/azure/cosmos-db/postgresql/howto-use-pgvector). It may also expose the vector db functionality for Cassandra in the future. The community needs to discuss these various Interfaces.

4. Currently, Postgres contains a standalone integration - [Postgres Semantic Kernel integration](https://github.com/microsoft/semantic-kernel/tree/main/python/semantic_kernel/connectors/memory/postgres), and that seems like the right architecture to me. Merging MongoDB with Azure CosmosDB would be akin to removing the Postgres integration and providing it as an API parameter in the Azure CosmosDB integration.

The asks:
The scope of #2560 should be restricted to Azure CosmosDB, which was the original intent of issue #2375 (Adding Azure CosmosDB Mongo vCore as a datastore). MongoDB should be a separate integration, just like Postgres and others. Towards that end, #2591 should be reopened so the community can work on a MongoDB integration.

**Comment by nacharya1** [comment]
Closing this issue and we will work from #2591 per our discussion today.
