### ISSUE TITLE
Feature Request: ITextCompletion wrappers to support IChatCompletion constructs

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#2640]
Opened in context of #2504 -- so the changes could be specific for StepwisePlanner and its implementation of Text and Chat completion support or more generic in kernel or abstractions.

**Comment by andhesky** [comment]
I need this wrapper for another purpose, so I went ahead and finished the implementation. PR linked above.

**Comment by matthewbolanos** [comment]
Closing since text completion will be deprecated
