### ISSUE TITLE
.Net: Azure OpenAI deployment not found for hard-coded embeddings model in notebook

### ISSUE THREAD

**Issue by momuno** [microsoft/semantic-kernel#2642]
**Describe the bug**
API deployed model does not exist.

**To Reproduce**
1. Go to '/dotnet/notebooks and set configuration json to use Azure OpenAI.
2. In your Azure OpenAI account, deploy a custom named embeddings model (not the same name as the model)
3. Go to '/dotnet/notebooks/06-memory-and-embeddings.ipynb'
4. Run sections through "Manually adding memories"
5. See error

**Expected behavior**
Section should run without error.  Code is using an assumed embeddings deployment model for Azure OpenAI, when user could create own deployment with different name.  Solution likely to include deployed embeddings model name in the config file, and change code in notebook to reference that model, instead of a hard-coded assumed model.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/64985898/23f84fbd-f4c5-42f5-a342-ada6dff895f6)
![image](https://github.com/microsoft/semantic-kernel/assets/64985898/5a4a5aa4-dbda-4a69-875b-51e6704ff957)

**Platform**
 - OS: Windows 11
 - IDE: VS Code
 - Language: .NET Environment, C#
 - Source: dotnet release 21...

**Comment by sammiie** [comment]
Azure Configuration Check:

Verify that your Azure configuration is correctly set up, including the resource group, Azure OpenAI service, and deployment. Ensure that the deployment you are looking for is deployed and accessible.
Check Hard-Coded Model Name:

Review the code in your notebook where the hard-coded embeddings model name is used. Ensure that the model name matches the actual model name in Azure. Be cautious of any typos or discrepancies.
Authentication and Permissions:

Ensure that you have the correct authentication and permissions to access the Azure resources. Check if you need to use service principals, tokens, or other authentication methods.
Resource Group and Location:

Confirm that the Azure resources related to your Azure OpenAI deployment, including the embeddings model, are in the correct resource group and location.
Error Handling:

Implement robust error handling in your notebook code to capture and log any errors or exceptions that occur when looking for the Azure deployment.
Test with Azure SDK:

Consider using the Azure SDK for .NET or the appropriate SDK for your programming language to programmatically interact with your Azure resources, including the embeddings model. This can help ensure that the model is accessible and correctly configured.
Diagram Structure:

A simplified diagram illustrating the process of resolving the issue:

sql
+----------------------------------+
|    Azure OpenAI Deployment      |
|                                  |
|   +---------------------------+  |
|   |     Azure Configuration   |  |
|   |                           |  |
|   | - Resource Group         |  |
|   | - Azure OpenAI Service   |  |
|   | - Deployment             |  |
|   |       ...                 |  |
|   +---------------------------+  |
|                                  |
|   +---------------------------+  |
|   |     Notebook Environment  |  |
|   |                           |  |
|   | - Hard-Coded Model Name  |  |
|   | - Authentication          |  |
|   | - Error Handling          |  |
|   |       ...                 |  |
|   +---------------------------+  |
|                                  |
|   +---------------------------+  |
|   |    Azure SDK for .NET     |  |
|   |                           |  |
|   | - Programmatic Access     |  |
|   | - Validation              |  |
|   |       ...                 |  |
|   +---------------------------+  |
|                                  |
+----------------------------------+
In this diagram:

The "Azure OpenAI Deployment" is the target resource you're trying to access.
The "Azure Configuration" includes Azure configurations, resource groups, and deployments.
The "Notebook Environment" represents your notebook's code and configurations, including the hard-coded model name, authentication, and error handling.
The "Azure SDK for .NET" can be used to programmatically access Azure resources and validate the deployment's accessibility. Proper error handling and validation help prevent and address the issue of not finding the Azure deployment for the hard-coded embeddings model.

**Comment by matthewbolanos** [comment]
Closing so we can make new docs issues later
