### ISSUE TITLE
.Net: Semantic Kernel dependency on .net 7.0 instead of 6.0

### ISSUE THREAD

**Issue by Woland2k** [microsoft/semantic-kernel#2646]
**Describe the bug**
The issue described in https://github.com/microsoft/semantic-kernel/issues/1793 has been reintroduced in this commit:
https://github.com/microsoft/semantic-kernel/commit/55dc7942e5aa54e55222927f42a792cc09b7c3c2

Mainly by adding dependency to the 7.0 version: 
`<PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="7.0.2" />`

**Comment by nacharya1** [comment]
@dmytrostruk - can you take a look into this?
