### ISSUE TITLE
Python: MISHOTOKEN

### ISSUE THREAD

**Issue by Rajmund666** [microsoft/semantic-kernel#2658]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by nacharya1** [comment]
I dont see any action here, will be closing. Please provide more context if we need to take further investigation.
