### ISSUE TITLE
Python: update pydantic version > 2

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#2667]
Many of the latest packages frequently use `pydantic > 2`.
But current pydantic in semantic-kernel use pydantic = "<2", causing ongoing version conflicts. 
I suggest updating the package.

**Comment by joowon-dm-snu** [comment]
`chromadb` is using pydantic (>=1.9,<2.0).
The update is being carried out [here](https://github.com/chroma-core/chroma/issues/893). It would be great if SK could also be version-updated once this is done.

**Comment by zooba** [comment]
Also worth checking whether you're using any features that actually changed. If you can get away without the version constraint at all, it makes your package more widely usable.

**Comment by cramatt** [comment]
Can't use because of this issue 😭
