### ISSUE TITLE
SemanticTextMemory supports storing text or external source name but not both?

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#2677]
Azure Cognitive Search can store both the source name and the text, which enables citations from the LLM.  But it seems SemanticTextMemory doesn't provide any methods that support including both the text and the source name; SaveInformationAsync stores the text but not the source, and SaveReferenceAsync stores the source but not the text.

Have I misunderstood how this is supposed to work?

**Comment by fortunkam** [comment]
Also running into this issue.  It causes problems when using `{{recall Some_value}}` in the prompts (as it returns the Text field by default which is not populated in `SaveReferenceAsync`)

The following code snippet is wired up to a Azure Cognitive Search and works fine if I add memory items using `save_information_async` but not `save_reference_async`.   I can see in the index the Text field is empty.

```
sk_prompt = """
    Using the following information

    ###
    Information:
    - {{recall $user_input}}
    ###
    
    Answer the following question

    Question: {{$user_input}}
    """.strip()

context[sk.core_skills.TextMemorySkill.COLLECTION_PARAM] = ACS_INDEX_NAME
context[sk.core_skills.TextMemorySkill.RELEVANCE_PARAM] = 0.8
context["user_input"] = ask

print(await kernel.prompt_template_engine.render_async(template_text=sk_prompt, context=context))
```

This returns....

```
Using the following information

    ###
    Information:
    - None
    ###
    
    Answer the following question

    Question: What is the fax number?
```

The None value is returned from the Index following a successful lookup.  (I can call `kernel.memory.search_async` and it returns a result)

**Comment by nacharya1** [comment]
@crickman - can you take a look into this.

**Comment by crickman** [comment]
Thank you for reporting the difference in behavior between _save-information_ and _save-reference_.   I will reproduce what has been reported and work with the team to determine how to support the exepected behavior and reply to this issue.
