### ISSUE TITLE
.Net: Why is AzureCognitiveSearchMemoryRecord public?

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#2678]
It doesn't appear to be used in any public surface area... nothing gives you back an instance and nothing accepts an instance, so there's nothing meaningful you can do with it.

Is there supposed to be public surface area on AzureCognitiveSearchMemoryStore that accepts or returns one?

**Comment by crickman** [comment]
Neither semantic-kernel, nor semantic-memory has been rigorous on differentiating public from internal contracts.  I suspect we could contruct a laundry list of candidates for internal scoping.

Was a specific concern or impact about exposing AzureCognitiveSearchMemoryRecord?

**Comment by stephentoub** [comment]
> I suspect we could contruct a laundry list of candidates for internal scoping

We should definitely do that.

**Comment by crickman** [comment]
Followed-up with Shawn and created https://github.com/microsoft/semantic-kernel/issues/2752 to track.
