### ISSUE TITLE
encoder.json/vocab.bpe show up in every project that uses SK

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#2679]
Bringing in the Microsoft.SemanticKernel nuget package causes these files to show up in the consuming application:
![image](https://github.com/microsoft/semantic-kernel/assets/2642209/8889bec5-bd34-495e-9b57-a4d50d315f80)
and they end up in the output directory for the application, regardless of whether the app is using the tokenizer or not.
![image](https://github.com/microsoft/semantic-kernel/assets/2642209/c90f7e44-caaf-451e-80f7-09a41a614dbe)

I'd opened https://github.com/microsoft/semantic-kernel/pull/1800 to turn them into assembly resources instead, so that they'd simply be part of the assembly and not separate files, but it was closed due to a lack of a decision about what to do with it.

**Comment by anthonypuppo** [comment]
Echoing my comment on #1800 

Bringing up [SharpToken](https://github.com/dmitry-brazhenko/SharpToken) as this would solve 1) embedding of the tokenization resource files 2) extracting the tokenization logic to a separate package (maybe wrapped as an official SK package in the future) and 3) bug https://github.com/microsoft/semantic-kernel/issues/2334.

**Comment by lemillermicrosoft** [comment]
One other option could be to move the tokenizer into an extension package for OpenAI connector.
