### ISSUE TITLE
Java: API - Being able to create a OpenAIClientProvider without a ClientType

### ISSUE THREAD

**Issue by agoncal** [microsoft/semantic-kernel#2681]
Today the `OpenAIClientProvider` constructor requires two parameters: configuration and client type

```java
public OpenAIClientProvider(
    Map<String, String> configuredSettings, @Nullable ClientType clientType) {
  this.configuredSettings = Collections.unmodifiableMap(configuredSettings);
  this.clientType = clientType;
}
```

That means that you need to know which client you are aiming:

```java
OpenAIClientProvider provider = new OpenAIClientProvider((Map) properties, ClientType.OPEN_AI);
OpenAIClientProvider provider = new OpenAIClientProvider((Map) properties, ClientType.AZURE_OPEN_AI);
```

But when you look at the `OpenAIClientProvider`, you find several places where the client type is tested to be null (`if (clientType == null)`). This makes sense because if you don't aim for a specific client type, `OpenAIClientProvider` will check for all the types.

Wouldn't it make sense to have a second constructor without client type so we don't have to invoke it with `new OpenAIClientProvider((Map) properties, null)`:

```java
public OpenAIClientProvider(Map<String, String> configuredSettings) {
  this.configuredSettings = Collections.unmodifiableMap(configuredSettings);
}

public OpenAIClientProvider(
    Map<String, String> configuredSettings, @Nullable ClientType clientType) {
  this.configuredSettings = Collections.unmodifiableMap(configuredSettings);
  this.clientType = clientType;
}
```

**Comment by sammiie** [comment]
To address the issue of being able to create an OpenAIClientProvider without specifying a ClientType, you can modify the design to allow for default values or optional parameters. Below, I'll provide a code example and a diagram to illustrate the solution.

Issue Explanation:

The current design requires specifying a ClientType when creating an OpenAIClientProvider, which might not be necessary for all use cases. The goal is to allow the creation of an OpenAIClientProvider without explicitly specifying a ClientType.

Solution:

Default ClientType:
Modify the constructor of the OpenAIClientProvider class to have a default ClientType. If a ClientType is not explicitly provided, it will default to a predefined value.
java

public class OpenAIClientProvider {
    private ClientType clientType;

    // Default constructor with a default ClientType
    public OpenAIClientProvider() {
        this.clientType = ClientType.DEFAULT; // Replace with an appropriate default value
    }

    // Constructor that accepts a ClientType
    public OpenAIClientProvider(ClientType clientType) {
        this.clientType = clientType;
    }

    // Other methods and properties
    // ...
}
Optional Parameter:
Alternatively, you can use the builder pattern or optional parameters in Java to create an OpenAIClientProvider without specifying a ClientType. This provides flexibility and clarity in the client code.
java

public class OpenAIClientProvider {
    private ClientType clientType;

    private OpenAIClientProvider(ClientType clientType) {
        this.clientType = clientType;
    }

    public static class Builder {
        private ClientType clientType = ClientType.DEFAULT; // Default value

        public Builder clientType(ClientType clientType) {
            this.clientType = clientType;
            return this;
        }

        public OpenAIClientProvider build() {
            return new OpenAIClientProvider(clientType);
        }
    }

    // Other methods and properties
    // ...
}
Diagram Structure:

A simplified diagram illustrating the solution:

sql

+-----------------------------------+
|     Java Application              |
|                                   |
|   +-----------------------------+ |
|   | OpenAIClientProvider        | |
|   |                             | |
|   | - clientType: ClientType   | |
|   |                             | |
|   | +-------------------------+ | |
|   | | Constructor with       | | |
|   | | Default ClientType    | | |
|   | +-------------------------+ | |
|   |                             | |
|   | +-------------------------+ | |
|   | | Constructor with       | | |
|   | | Provided ClientType   | | |
|   | +-------------------------+ | |
|   |                             | |
|   | +-------------------------+ | |
|   | | Builder Pattern        | | |
|   | | or Optional Parameters | | |
|   | +-------------------------+ | |
|   |                             | |
|   +-----------------------------+ |
|                                   |
+-----------------------------------+
In this diagram:

The "Java Application" can create an OpenAIClientProvider using either the default constructor with a default ClientType or the builder pattern/optional parameters constructor to specify a ClientType explicitly.
This design allows flexibility when creating an OpenAIClientProvider, as it can be instantiated with or without specifying a ClientType, depending on the requirements of the client code.

**Comment by d3r3kk** [comment]
Not going to exist this way in the V1.0 version of SK for Java.
