### ISSUE TITLE
ChatHistory should not derive from `List<ChatMessageBase>`

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#2687]
(1)
It's confusing for a consumer, as you then see methods on `ChatHistory` like `Add(ChatMessageBase)`, but you can't new-up a ChatMessageBase as it's abstract.  `ChatHistory` should expose on it whatever API surface area it needs and implementing whatever collection interfaces make sense, and the storage for it should be an implementation detail contained in the class.

(2)
(It's extra strange that not only does `ChatHistory` derive from `List<ChatMessageBase>`, it also exposes a `List<ChatMessageBase> Messages` property that just returns `this`.)

(3)
Also, why is the type called "ChatMessageBase"?  If it's the type that consumers are intended to work with, and connectors are supposed to create their own private implementations to hand out, it should likely just be "ChatMessage".

(4)
Why is there an "SKChatMessage" that's public in Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk?

**Comment by nacharya1** [comment]
@shawncal - can you take a look into this question/request.
