### ISSUE TITLE
Support full API in Chroma client

### ISSUE THREAD

**Issue by adiherzog** [microsoft/semantic-kernel#2700]
The Chroma client only implements a subset of what Chroma has to offer. It would be very handy if the entire API was implemented.

Usage guide: https://docs.trychroma.com/usage-guide
API reference: https://docs.trychroma.com/api-reference

I'm mainly missing these two things:

* It's not possible to use the embedding creation that is supported by Chroma. At the moment the embeddings have to be provided by the caller when adding something to the DB.
* It's not possible to delete (or search) documents based on a metadata query (see https://docs.trychroma.com/usage-guide#deleting-data-from-a-collection).

**Comment by askfenn** [comment]
This would require changing how metadata is added. With chroma's python library metadata is added as a dictionary like:
```` python
collection.add(
	#text and ids etc.. here
	metadata = {"A metadata_field": "some value",
				"another metadata_field": "another value"}
)
````
A similar way of adding metadata in SK would be great, and would allow for (as you have mentioned) search similar to this:
```` python
collection.query(
    #other search parameters
    where={"metadata_field": "is_equal_to_this"},
)
````

**Comment by adiherzog** [comment]
Yeah, I guess [IMemoryStore](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel.Abstractions/Memory/IMemoryStore.cs) would need to be extended to support metadata queries for both matching and deletion endpoints.

**Comment by dmytrostruk** [comment]
Hi @adiherzog !

> I think the `ChromaClient` class should be a standalone NuGet package (ideally maintained by the Chroma project). Then it could implement the full Chroma API, no matter which subset is needed in semantic kernel.

That's correct. It would be great if there will be standalone NuGet package with Chroma .NET SDK, so we can re-use it. Currently, we implemented only the functionality, which is required for `IMemoryStore` in order to be used with Semantic Kernel.

Please, let us know if we can close this issue in case your question/proposal is resolved. Thank you!

**Comment by adiherzog** [comment]
I'll close the issue, as it does not make sense to use the semantic kernel repository for the full C# client implementation. It needs to be separate. Thanks for helping with the clarification.
