### ISSUE TITLE
Python: Azure credentials cleared when creating AzureCognitiveSearchMemoryStore instance

### ISSUE THREAD

**Issue by zooba** [microsoft/semantic-kernel#2701]
https://github.com/microsoft/semantic-kernel/blob/c4ef6ab227fc967ab12291cc862852e66d6d75ae/python/semantic_kernel/connectors/memory/azure_cognitive_search/utils.py#L56-L57

The two lines above are clearing the arguments passed to the function, which means that it's impossible to construct a `AzureCognitiveSearchMemoryStore` instance using anything other than an admin key. This rules out using Managed Identity.

My workaround is to pass `admin_key=ManagedIdentityCredential().get_token("https://search.azure.com/.default").token`. This is already similar to how I'm handling Azure OpenAI auth, so it's no big deal, it's just not clearly documented anywhere.

**Comment by zooba** [comment]
Correction: my workaround is to monkeypatch `semantic_kernel.connectors.memory.azure_cognitive_search.azure_cognitive_search_memory_store.get_search_index_async_client` to return my own client.

The MSI token doesn't work as an admin key because it needs to be passed with an Authorization header.

**Comment by crickman** [comment]
https://github.com/microsoft/semantic-kernel/pull/2740
