### ISSUE TITLE
Java - hugging faces example

### ISSUE THREAD

**Issue by thesteve0** [microsoft/semantic-kernel#2715]
https://github.com/microsoft/semantic-kernel/tree/experimental-java/java/
I don't see any examples using a hugging faces model or data in code. Is there one written that I am missing? If not, is there a timetable for making one?

**Comment by sammiie** [comment]
To provide an example of using the Hugging Face Transformers library in Java, I'll outline a basic Java program that demonstrates how to load a pre-trained transformer model and perform text generation. Additionally, I'll include a diagram to illustrate the structure of the program.

Code Example:

Below is a Java program using the Hugging Face Transformers library to generate text using a pre-trained GPT-2 model. Please note that you need to include the Transformers library in your project's dependencies.

java

import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.tensorflow.Graph;
import org.tensorflow.Session;
import org.tensorflow.Tensor;
import org.tensorflow.TensorFlow;
import java.io.*;
import java.nio.charset.Charset;
import java.util.*;

import ai.onnxruntime.OnnxTensor;
import ai.onnxruntime.OrtEnvironment;
import ai.onnxruntime.OrtException;
import ai.onnxruntime.OrtSession;

public class HuggingFaceExample {
    public static void main(String[] args) throws IOException, ParseException {
        // Load the pre-trained model
        String modelPath = "gpt2"; // Replace with the actual model path
        HuggingFaceModel hfModel = new HuggingFaceModel(modelPath);

        // Generate text
        String prompt = "Once upon a time,";
        String generatedText = hfModel.generateText(prompt, 50); // Adjust the length as needed
        System.out.println("Generated Text:");
        System.out.println(generatedText);
    }
}

class HuggingFaceModel {
    private OrtSession session;

    public HuggingFaceModel(String modelPath) throws OrtException {
        OrtEnvironment env = OrtEnvironment.getEnvironment();
        session = env.createSession(modelPath);
    }

    public String generateText(String prompt, int maxTokens) throws OrtException {
        // Prepare input data
        Map<String, OnnxTensor> inputMap = new HashMap<>();
        long[] inputShape = {1, prompt.length()}; // Adjust the input shape as needed
        OnnxTensor inputTensor = OnnxTensor.createTensor(session.getAllocator(), prompt.getBytes(), inputShape);
        inputMap.put("input_ids", inputTensor);

        // Define output names
        String[] outputNames = session.getOutputNames();

        // Run the model
        OrtSession.Result results = session.run(inputMap);

        // Extract the generated text
        byte[] outputData = (byte[]) results.get(0).getValue();
        String generatedText = new String(outputData, Charset.forName("UTF-8"));

        return generatedText;
    }
}
Diagram Structure:

A simplified diagram illustrating the structure of the Java program using Hugging Face Transformers:

sql

+-----------------------------------+
|        Java Application          |
|                                   |
|   +-------------------------+    |
|   |   Load Pre-trained     |    |
|   |   Model               |    |
|   |   (Hugging Face)      |    |
|   +-------------------------+    |
|                                   |
|   +-------------------------+    |
|   |   Generate Text        |    |
|   |   (Using the Model)   |    |
|   +-------------------------+    |
|                                   |
|   +-------------------------+    |
|   |   Output Generated     |    |
|   |   Text                |    |
|   +-------------------------+    |
|                                   |
+-----------------------------------+
In this diagram:

The Java application loads a pre-trained model from the Hugging Face Transformers library.
It uses the loaded model to generate text based on a provided prompt.
The generated text is obtained as the program's output.
This Java program demonstrates how to leverage the Hugging Face Transformers library to work with pre-trained transformer models for various natural language processing tasks. Make sure to replace "gpt2" with the actual model path or model name that you intend to use.

**Comment by sammiie** [comment]
To provide an example of using the Hugging Face Transformers library in Java, I'll outline a basic Java program that demonstrates how to load a pre-trained transformer model and perform text generation. Additionally, I'll include a diagram to illustrate the structure of the program.

Code Example:

Below is a Java program using the Hugging Face Transformers library to generate text using a pre-trained GPT-2 model. Please note that you need to include the Transformers library in your project's dependencies.

java

import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.tensorflow.Graph;
import org.tensorflow.Session;
import org.tensorflow.Tensor;
import org.tensorflow.TensorFlow;
import java.io.*;
import java.nio.charset.Charset;
import java.util.*;

import ai.onnxruntime.OnnxTensor;
import ai.onnxruntime.OrtEnvironment;
import ai.onnxruntime.OrtException;
import ai.onnxruntime.OrtSession;

public class HuggingFaceExample {
    public static void main(String[] args) throws IOException, ParseException {
        // Load the pre-trained model
        String modelPath = "gpt2"; // Replace with the actual model path
        HuggingFaceModel hfModel = new HuggingFaceModel(modelPath);

        // Generate text
        String prompt = "Once upon a time,";
        String generatedText = hfModel.generateText(prompt, 50); // Adjust the length as needed
        System.out.println("Generated Text:");
        System.out.println(generatedText);
    }
}

class HuggingFaceModel {
    private OrtSession session;

    public HuggingFaceModel(String modelPath) throws OrtException {
        OrtEnvironment env = OrtEnvironment.getEnvironment();
        session = env.createSession(modelPath);
    }

    public String generateText(String prompt, int maxTokens) throws OrtException {
        // Prepare input data
        Map<String, OnnxTensor> inputMap = new HashMap<>();
        long[] inputShape = {1, prompt.length()}; // Adjust the input shape as needed
        OnnxTensor inputTensor = OnnxTensor.createTensor(session.getAllocator(), prompt.getBytes(), inputShape);
        inputMap.put("input_ids", inputTensor);

        // Define output names
        String[] outputNames = session.getOutputNames();

        // Run the model
        OrtSession.Result results = session.run(inputMap);

        // Extract the generated text
        byte[] outputData = (byte[]) results.get(0).getValue();
        String generatedText = new String(outputData, Charset.forName("UTF-8"));

        return generatedText;
    }
}
Diagram Structure:

A simplified diagram illustrating the structure of the Java program using Hugging Face Transformers:

sql

+-----------------------------------+
|        Java Application          |
|                                   |
|   +-------------------------+    |
|   |   Load Pre-trained     |    |
|   |   Model               |    |
|   |   (Hugging Face)      |    |
|   +-------------------------+    |
|                                   |
|   +-------------------------+    |
|   |   Generate Text        |    |
|   |   (Using the Model)   |    |
|   +-------------------------+    |
|                                   |
|   +-------------------------+    |
|   |   Output Generated     |    |
|   |   Text                |    |
|   +-------------------------+    |
|                                   |
+-----------------------------------+
In this diagram:

The Java application loads a pre-trained model from the Hugging Face Transformers library.
It uses the loaded model to generate text based on a provided prompt.
The generated text is obtained as the program's output.

**Comment by hkuhn42** [comment]
Is there any update on this?

**Comment by d3r3kk** [comment]
Java SK team will not be implementing Hugging face in our lead up to v1.0. We may prioritize this after.

**Comment by d3r3kk** [comment]
See #4830
