### ISSUE TITLE
.Net: IChatStreamingResult should not derive from IChatResult and ITextStreamingResult should not derive from ITextResult

### ISSUE THREAD

**Issue by andhesky** [microsoft/semantic-kernel#2730]
In my opinion, it is too easy to accidentally get non-streaming completions. A call to IChatCompletion.GetStreamingChatCompletionsAsync() returns an IChatStreamingResult and if you are just using intellisense it is easy to write code that would not stream. For example:
```C#
        var sb = new StringBuilder();
        await foreach (IChatStreamingResult result in results)
        {
            ChatMessageBase message = await result.GetChatMessageAsync();
            sb.Append(message.Content);
        }
```
However, you almost always want the code
```C#
        var sb = new StringBuilder();
        await foreach (IChatStreamingResult result in results)
        {
            await foreach (ChatMessageBase message in result.GetStreamingChatMessageAsync())
            {
                sb.Append(message.Content);
            }
        }
```

It is easy to mistakenly call the non-streaming API of the streaming interface when you want streaming, and I am not sure there is a valid use case where you would want to call that API.

If IChatStreamingResult just didn't implement IChatResult then callers would be driven to the "pit of success" of calling the intended API.

I am not suggesting to change the underlying implementation classes (ChatStreamingResult & TextCompletionStreamingResult). The class can still implement both interfaces since the implementation is not exposed to callers directly only the interfaces.

**Comment by sammiie** [comment]
To address the issue of IChatStreamingResult deriving from IChatResult and ITextStreamingResult deriving from ITextResult, we can refactor the class hierarchy to achieve a more logical and maintainable structure. Let's use code examples and a diagram to illustrate the proposed solution.

Issue Explanation:

The current class hierarchy suggests that streaming result interfaces (IChatStreamingResult and ITextStreamingResult) inherit from non-streaming result interfaces (IChatResult and ITextResult), which might not align with the intended design.

Solution:

We propose separating streaming and non-streaming result interfaces to clarify the hierarchy:

Revised Class Hierarchy:

csharp

// Non-streaming result interfaces
public interface IChatResult
{
    // Common chat result properties
    // ...
}

public interface ITextResult
{
    // Common text result properties
    // ...
}

// Streaming result interfaces
public interface IChatStreamingResult : IChatResult
{
    // Additional properties or methods specific to chat streaming
    // ...
}

public interface ITextStreamingResult : ITextResult
{
    // Additional properties or methods specific to text streaming
    // ...
}
Explanation:

Non-streaming Result Interfaces:

IChatResult and ITextResult remain as non-streaming result interfaces, defining properties and methods common to both non-streaming chat and text results.
Streaming Result Interfaces:

IChatStreamingResult and ITextStreamingResult now directly inherit from their respective non-streaming result interfaces (IChatResult and ITextResult).
This separation makes it clear that streaming result interfaces extend the non-streaming ones, providing additional properties or methods specific to streaming scenarios.
Diagram Structure:

A simplified diagram illustrating the revised class hierarchy:

sql

+----------------------------------+
|          Non-streaming          |
|           Result Interfaces     |
|                                  |
|     +---------------+            |
|     |  IChatResult  |            |
|     |               |            |
|     +---------------+            |
|                                  |
|     +---------------+            |
|     |  ITextResult  |            |
|     |               |            |
|     +---------------+            |
|                                  |
+----------------------------------+
                 |
                 |
                 V
+----------------------------------+
|          Streaming               |
|          Result Interfaces       |
|                                  |
|     +-----------------+          |
|     | IChatStreaming  |          |
|     |   Result        |          |
|     |                 |          |
|     +-----------------+          |
|                                  |
|     +-----------------+          |
|     | ITextStreaming  |          |
|     |   Result        |          |
|     |                 |          |
|     +-----------------+          |
|                                  |
+----------------------------------+
In this diagram:

Non-streaming result interfaces (IChatResult and ITextResult) are positioned at the top.
Streaming result interfaces (IChatStreamingResult and ITextStreamingResult) inherit directly from their respective non-streaming result interfaces, representing a clear and organized class hierarchy.
This revised structure provides a more logical and maintainable hierarchy, ensuring that streaming result interfaces extend their non-streaming counterparts while accommodating additional properties or methods specific to streaming scenarios.

**Comment by evchaki** [comment]
@andhesky - thanks for the feedback, we will take a look

**Comment by markwallace-microsoft** [comment]
Link to https://github.com/microsoft/semantic-kernel/issues/1649
