### ISSUE TITLE
.Net: ADR proposal for the Semantic Kernel v1.0 project and folder structure

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#2733]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/pull/2668
```

**Comment by sammiie** [comment]
Here, I'll provide a simplified example of what such a proposal might look like using plain text, but typically ADRs are written in a structured document format.

ADR Proposal: Semantic Kernel v1.0 Project and Folder Structure

Context:
The Semantic Kernel v1.0 project aims to provide a robust and flexible foundation for natural language processing and understanding. This ADR outlines the proposed folder structure and key architectural decisions for organizing project files.

Decision:
We propose the following folder structure for the Semantic Kernel v1.0 project:

arduino

SemanticKernel/
├── src/
│   ├── Native/
│   │   ├── Core/
│   │   ├── Components/
│   │   ├── ...
│   ├── Semantic/
│   │   ├── Chat/
│   │   ├── Extractors/
│   │   ├── ...
├── tests/
│   ├── UnitTests/
│   ├── IntegrationTests/
├── docs/
├── config/
├── tools/
Rationale:

src/: The source code for the project is organized under the "src/" directory. It's further divided into "Native" for core functionality and "Semantic" for semantic processing modules.

Native/: This folder contains core components of the Semantic Kernel. It includes the core logic, components, and any shared libraries.

Semantic/: Semantic processing modules are placed under this directory. Each module (e.g., "Chat," "Extractors") has its subfolder.

tests/: Testing is an integral part of this project. The "tests/" directory is divided into "UnitTests" for individual component testing and "IntegrationTests" for testing interactions between components.

docs/: Documentation is essential for understanding and using the Semantic Kernel. This folder contains documentation files, guides, and API reference documents.

config/: Configuration files, such as "config.json" and "skprompt.txt" for semantic skills, are stored here.

tools/: Any development tools, scripts, or utilities related to the project are placed in this directory.

Consequences:

This folder structure provides a clear organization of project files, making it easier for developers to locate and work on specific components.
It encourages modularity by dividing the project into "Native" and "Semantic" sections.
Testing is well-structured, enabling comprehensive test coverage.
Documentation is centralized and easily accessible for both developers and users.
Status:
This proposal is accepted and will be implemented for the Semantic Kernel v1.0 project.

Diagram Structure:

A visual representation of the proposed folder structure:

lua

SemanticKernel
|
|-- src
|   |-- Native
|   |   |-- Core
|   |   |-- Components
|   |   |-- ...
|   |-- Semantic
|       |-- Chat
|       |-- Extractors
|       |-- ...
|
|-- tests
|   |-- UnitTests
|   |-- IntegrationTests
|
|-- docs
|
|-- config
|
|-- tools
The diagram provides a clear visual representation of the folder structure outlined in the ADR proposal.

**Comment by markwallace-microsoft** [comment]
Moving this out. Planning to meet @shawncal this week to see can we finalise this.

**Comment by matthewbolanos** [comment]
Closing since the status is "Sprint: Done"
