### ISSUE TITLE
.Net: Depending on the code path used semantic functions will have different max tokens

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#2738]
Noticed this while create a new integration test

Calling `Kernel.InvokeSemanticFunctionAsync`, the max tokens will default to 256. If you call `Kernel.CreateSemanticFunction` the max tokens will not be set. Proposed fix is to use null as the default value as the property is optional.

Here's the documentation for OpenAI: 

https://platform.openai.com/docs/api-reference/completions/create#max_tokens
`max_tokens` `integer or null` `Optional` `Defaults to 16`
The maximum number of [tokens](https://platform.openai.com/tokenizer) to generate in the completion.

https://platform.openai.com/docs/api-reference/chat/create#max_tokens
`max_tokens` `integer or null` `Optional` `Defaults to inf`
The total length of input tokens and generated tokens is limited by the model's context length.

**Comment by sammiie** [comment]
In your integration test, you've observed that semantic functions encounter varying maximum token limits based on the code path used. This inconsistency can lead to unexpected behavior or errors, and it needs to be resolved.

Solution: Dynamic Token Management

1. Token Configuration:

Start by defining a token configuration system that allows you to set and adjust token limits dynamically based on specific code paths or scenarios.
2. Token Management Module:

Implement a token management module within your codebase. This module will be responsible for tracking and allocating tokens for semantic functions.
3. Code Path Identification:

Develop a mechanism to identify the code path currently being executed. This can be achieved using conditional statements, flags, or any appropriate method based on your application's architecture.
4. Token Allocation:

When a semantic function is invoked, consult the token management module to determine the maximum token limit for that specific code path.
5. Dynamic Adjustment:

Allow the token management module to dynamically adjust token limits based on the code path. This can involve reading from configuration files, databases, or other sources that store token limit information.
6. Diagram Structure:

Create a diagram to illustrate the flow of token management and code path identification. This can help visualize how tokens are allocated dynamically.
Here's a simplified diagram structure to explain the concept:

sql
+---------------------------------------------------+
|               Application Code                    |
|                                                 |
|    +-----------+           +--------------+      |
|    | Code Path | ------->  | Token Mgmt   |      |
|    |  Identifier|           |   Module     |      |
|    +-----------+           +--------------+      |
|                                                 |
|                                                 |
|    +-----------+           +--------------+      |
|    | Semantic  | ------->  |  Semantic    |      |
|    |   Function|           |   Function   |      |
|    +-----------+           +--------------+      |
|                                                 |
|                                                 |
|    +-----------+           +--------------+      |
|    | Code Path | ------->  | Token Mgmt   |      |
|    |  Identifier|           |   Module     |      |
|    +-----------+           +--------------+      |
|                                                 |
+---------------------------------------------------+
In this diagram:

The "Application Code" contains different code paths.
"Code Path Identifier" determines the current code path.
The "Token Management Module" dynamically adjusts token limits based on the code path.
"Semantic Functions" consult the token management module to determine the maximum token limit for their execution.
With this dynamic token management approach, you can ensure that semantic functions always operate within the appropriate token limits, regardless of the code path being used.

**Comment by lemillermicrosoft** [comment]
Related to #1362
