### ISSUE TITLE
[Always] Unable to run sample app [Simple chat summary] cause front page error

### ISSUE THREAD

**Issue by zijeibo64270** [microsoft/semantic-kernel#274]
**Describe the bug**
[Simple chat summary] Setup page has error: If you want to write it to the DOM, pass a string instead: filled="true" or filled {value.toString()}. at svg

**To Reproduce**
Follow the doc: 
https://learn.microsoft.com/en-us/semantic-kernel/samples/localapiservice
https://learn.microsoft.com/en-us/semantic-kernel/samples/simplechatsummary 
local API service has been up, but when I visit the http://localhost:3000, it's not work

**Expected behavior**

**Screenshots**
local api service:
![image](https://user-images.githubusercontent.com/120881998/229365772-7f139e60-3235-45f2-baeb-cb4a601f6406.png)
setup page before save:
![image](https://user-images.githubusercontent.com/120881998/229365531-4964e52d-0767-4b5b-8b2a-c28383f6d07c.png)
setup page after save:
![image](https://user-images.githubusercontent.com/120881998/229365577-ad900b2e-972e-4b52-b277-31a3064d5c4b.png)
dependencies versions:
![image](https://user-images.githubusercontent.com/120881998/229365548-fc39b1a0-6c17-4f67-b95c-c046ba36d039.png)
run command yarn start withot error:
![image](https://user-images.githubusercontent.com/120881998/229365602-5469e1bb-c68a-4045-aa68-91879827f754.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - IDE: VS Code
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by zijeibo64270** [comment]
I try run on macos follow by the doc, still always reproduce

**Comment by dluc** [comment]
@craigomatic

**Comment by shaulimaya** [comment]
You need to copy the .env.example to .env to fill your data
Close all tabs related to the client and run again yarn start

**Comment by zijeibo64270** [comment]
> 

seems not this reason, after copy the .env.example to .env and fill data, still has some error
![image](https://user-images.githubusercontent.com/120881998/229521295-b80cc3d4-8890-4a53-84c7-de8d121d88ec.png)

**Comment by zijeibo64270** [comment]
> You need to copy the .env.example to .env to fill your data Close all tabs related to the client and run again yarn start

seems not this reason, after copy the .env.example to .env and fill data, still has some error
![image](https://user-images.githubusercontent.com/120881998/229521594-e03ef7de-5006-4ac1-89f2-03653cf3988c.png)

**Comment by shaulimaya** [comment]
> > You need to copy the .env.example to .env to fill your data Close all tabs related to the client and run again yarn start
> 
> seems not this reason, after copy the .env.example to .env and fill data, then restart the app, still has some error ![image](https://user-images.githubusercontent.com/120881998/229521594-e03ef7de-5006-4ac1-89f2-03653cf3988c.png)

It fixed the undefined issue

**Comment by craigomatic** [comment]
Closing as this seems resolved (and we will work to improve the first run experience of the samples)
