### ISSUE TITLE
Custom endpoint support 

### ISSUE THREAD

**Issue by rohitgabriel** [microsoft/semantic-kernel#2744]
In our case, the Azure OpenAI API's are published to the Azure APIM API gateway so the only way to call the Azure openAI api's is to call a custom endpoint on a custom domain. To call the api's exposed on the api gateway we have to pass the following:
HTTP header - subscriber-application-key
User access Token (JWT token)

Note that this is not an onprem proxy, the Azure open AI api's are published on the API gateway to apply extra controls. We do not get Azure OpenAI key to pass. Only the subscriber application key

**Comment by markwallace-microsoft** [comment]
@rohitgabriel We have a document which describes how to use Semantic Kernel together with APIM, see: https://learn.microsoft.com/en-us/semantic-kernel/deploy/use-ai-apis-with-api-management

Have you seen this and are still having issues?

**Comment by rohitgabriel** [comment]
Thanks for the link, will let you know after testing

**Comment by rohitgabriel** [comment]
Following the document has been helpful, thanks, this can be closed

**Comment by rohitgabriel** [comment]
No more assistance needed

**Comment by markwallace-microsoft** [comment]
Updated document: https://jordanbeandev.com/how-to-set-up-an-asp-net-core-api-to-call-an-azure-openai-instance-that-is-behind-azure-api-management-and-requires-both-a-subscription-key-an-oauth2-access-token-using-semantic-kernel-c/
