### ISSUE TITLE
Python: Add a feature to specify service id for a semantic function

### ISSUE THREAD

**Issue by awharrison-28** [microsoft/semantic-kernel#2751]
---
name: Semantic functions should have a service ID
about: Allows a semantic function config to include an LLM service id. Parallels an existing feature in .NET SK introduced in https://github.com/microsoft/semantic-kernel/pull/2739. The original issue was brought up in https://github.com/microsoft/semantic-kernel/issues/2228. 

---

**Comment by moonbox3** [comment]
Closing as no longer needed.
