### ISSUE TITLE
.Net: Clearly define public API and differentiate internal contracts

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#2752]
> [!IMPORTANT]  
> Labeled **Urgent** because it will require a breaking change if any contracts need to change. Please lower the priority if this is not the case.

As part of the transition from preview to production, it may make sense to reduce public surface area.  Even though this is an open source project, people taking dependencies (for whatever reason) on internal contracts that are incorrectly scoped will not be delighted as changes progress.

**Goal: Scope classes that do not have `public `intent as `internal`:**

Example: AzureCognitiveSearchMemoryRecord  - https://github.com/microsoft/semantic-kernel/issues/2678

**Comment by crickman** [comment]
Sounds good, I was just the messenger on this one (@stephentoub )

**Comment by markwallace-microsoft** [comment]
@stephentoub We have review the SK abstractions only. We'll look more broadly.

**Comment by SergeyMenshykh** [comment]
The SK RC4 public interface was reviewed with the https://apiview.dev/ tool, and all problems were recorded in this issue: https://github.com/microsoft/semantic-kernel/issues/4269
