### ISSUE TITLE
Python: Simple App and Book Creator Sample Apps don't connect to Azure Open AI because of Status Error 400

### ISSUE THREAD

**Issue by andrehe001** [microsoft/semantic-kernel#2757]
**Describe the bug**
Both sample apps, simple app and book creator app don't connect to Azure OpenAI because of content filter violations ("the response was filtered due to the prompt triggering Azure OpenAI content management policy").

**To Reproduce**
1. start apps with "yarn start"
2. Enter Azure OoenAI Data
3. Click "Save"

**Expected behavior**

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/13762183/6bef27e9-c8f6-44e2-92ec-bddfa535667e)
**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by evchaki** [comment]
@andrehe001 - we will be removing this sample.
