### ISSUE TITLE
.Net: Python: Memory store upgrades for Milvus 2.3 

### ISSUE THREAD

**Issue by roji** [microsoft/semantic-kernel#2759]
Milvus 2.3 was [recently released](https://github.com/milvus-io/milvus/releases/tag/v2.3.0); the current memory store connectors currently target Milvus 2.2 (both Python and .NET), and this issue tracks leveraging new 2.3 features to make them better:

* [Upsert](https://milvus.io/docs/upsert_entities.md), which should map nicely to the equivalent SK IMemoryStore API (we currently do delete-then-insert)
* [Range search](https://milvus.io/docs/within_range.md#Conduct-a-Range-Search), which can be used to execute the `minRelevanceScore` parameter to GetNearestMatchAsync (this is currently done client-side, which is problematic especially in its interaction with limit).
* [Raw Vectors in Search Returns](https://github.com/milvus-io/milvus/releases/tag/v2.3.0): when `withEmbeddings` is true for GetNearestMatchesAsync, the connector currently does an extra Query roundtrip to Milvus to fetch the vectors, since they couldn't be returned from Search; it seems that this is now at least partially possible.

Note: figure out the backwards compat and versioning story, i.e. would a new version of the connector that's compatible with 2.3 be expected to also work with 2.2.

/cc @filip-halt @stephentoub @luisquintanilla

**Comment by evchaki** [comment]
@roji - feel free to do a PR to update this to the latest version.  Thanks for bringing this up.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.

**Comment by roji** [comment]
Note that this isn't a .NET issue - it's a Python one (wrong labeling).

**Comment by moonbox3** [comment]
@roji this is a little bit tricky as Milvus doesn't always have the latest builds for Windows. There is a way to handle various versions in our poetry file, but the memory related upgrades aren't our highest priority right now as we move to getting other base functionality ready for Python v1.

**Comment by moonbox3** [comment]
Closing as we support Milvus 2.3 in Python.
