### ISSUE TITLE
ActionPlanner - Reponse cannot parse regex sometimes

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#2767]
Chat copilot experiencing issues with ActionPlanner not giving valid plan.

Repro Details:
Model: TBD
Functions: GithubPlugin
Ask: List open pull requests

- [ ] Reproduced

**Comment by matthewbolanos** [comment]
Closing since the action planner has been replaced with OpenAI function calling.

**Comment by maxupp** [comment]
The bug is still around in Python, so would you mind keeping this open?
