### ISSUE TITLE
[Consider] SequentialPlanner - Should semantic function more reliably return no plan rather than hallucinated plan even though end user result is the same

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#2768]

**Comment by douglasware** [comment]
Seems like the first focus should be to get it and the rest of the bits refactored to use the Function Calling feature. Removing the formatting instructions from the skill prompt itself seems to make a bug difference.

**Comment by lemillermicrosoft** [comment]
Yes, this is great example of where Function Calling may yield improvements. That work is active in #1450 and related issues. 

Function Calling Feature does not apply to all completion implementations, however, so, still something we should consider outside of that functionality.

**Comment by matthewbolanos** [comment]
Closing since the sequential planner has been replaced with the new Handlebars planner
