### ISSUE TITLE
Remove Dependencies on Azure.AI.OpenAI and Azure.Core for Open AI connectors

### ISSUE THREAD

**Issue by douglasware** [microsoft/semantic-kernel#2770]
The dependency on Azure.AI.OpenAI outsources key abstractions and underlying features in a way that is disadvantageous to the pluggability goals of SK and corrupts the design accordingly.

**Comment by SergeyMenshykh** [comment]
Thanks, @douglasware, for sharing your feedback. We always strive to improve SK.

Could you please share more details about the Azure.AI.OpenAI features that undermined SK's pluggability and corrupted the design? 

If you could point us to particular places in SK source code where you think the issues reside, it would be helpful for us to quickly locate and prioritize corresponding fixes.

**Comment by evchaki** [comment]
@douglasware  - let us know if you have any additional details to share here.
