### ISSUE TITLE
.Net: PromptTemplateEngine with empty parameters is hardcoded in StepwisePlanner

### ISSUE THREAD

**Issue by neodenit** [microsoft/semantic-kernel#2774]
There is no way to initialize **StepwisePlanner** and pass **PromptTemplateEngine** (and its logger) into it.
https://github.com/microsoft/semantic-kernel/blob/cfebcaec6c1656f2c129ca3e40442c0ace9495e5/dotnet/src/Extensions/Planning.StepwisePlanner/StepwisePlanner.cs#L65C59-L65C59

E.g., it is not possible to do something like this:

```
var kernel = new KernelBuilder()
            .WithPromptTemplateEngine(new PromptTemplateEngine(ConsoleLogger.LoggerFactory))
            .Build();

        StepwisePlanner planner = new(kernel);
```

**Comment by lemillermicrosoft** [comment]
Great catch, already on it! Thank you.

**Comment by lemillermicrosoft** [comment]
Will definitely re-connect the logging. The implementation and prompts though are built with PromptTemplateEngine in mind, so not sure whether it makes sense to allow overriding that right now.
