### ISSUE TITLE
.Net: Add timestamp field to ISemanticTextMemory interface methods

### ISSUE THREAD

**Issue by dmytrostruk** [microsoft/semantic-kernel#2792]
Currently, in `MemoryRecord` class, which inherits `DataEntryBase`, it's possible to set `Timestamp` field which then can be saved in vector DB. 
It's possible to save this field only when using concrete `MemoryStore` implementation directly, while there is no way how to set this field when using `MemoryStore` through the Kernel.

Suggestion:
Extend methods of `ISemanticTextMemory` - `SaveInformationAsync` and `SaveReferenceAsync` to accept `timestamp` field, so it can be passed to MemoryStore and saved with other record data.

**Comment by DmitryLukyanov** [comment]
@markwallace-microsoft , it's still relevant. Timestamp argument is missed: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel.Core/Memory/SemanticTextMemory.cs#L53
