### ISSUE TITLE
.Net: Weaviate memory connector fails to save information when id is not uuid

### ISSUE THREAD

**Issue by gkarka** [microsoft/semantic-kernel#2793]
**Describe the bug**
Weaviate requires a uuid as the id of a record but the .NET connector implementation does not take care. The result is that an exception is thrown on the http call when trying to save the record due to failing HTTP status code with error message "weaviate body.objects.0.id in body must be of type uuid". 

**To Reproduce**
1. Go to KernelSyntaxExamples project
2. On Example15_TextMemorySkill class uncomment the line initializing the store with Weaviate Memory Store
3. Set user secrets according to README.md for the following keys:

```
dotnet user-secrets set "OpenAI:ChatModelId" "..."
dotnet user-secrets set "OpenAI:EmbeddingModelId" "..."
dotnet user-secrets set "OpenAI:ApiKey" "..."
dotnet user-secrets set "Weaviate:Endpoint" "..."
dotnet user-secrets set "Weaviate:Port" "..."
dotnet user-secrets set "Weaviate:ApiKey" "..."
```
4. Comment out all other examples on Program.cs and run
5. See error

**Expected behavior**
The implementation should abstract away the details of the underlying store.

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio
 - Language: C#
 - Source: main branch of repository

**Additional context**
Python implementation seems to handle this properly.

**Comment by nacharya1** [comment]
thanks @crickman  for picking this up to investigate.

**Comment by crickman** [comment]
@gkarka - Thank you for calling this out.  I will look into this and provide fix.

**Comment by crickman** [comment]
https://github.com/microsoft/semantic-kernel/tree/sample-key2guid

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
