### ISSUE TITLE
.Net: Line endings not taken into account by TextChunker.cs

### ISSUE THREAD

**Issue by Nurgo** [microsoft/semantic-kernel#2794]
I think I have found a bug in _TextChunker.cs_ : you are using _NormalizeLineEndings()_ which turns all line endings into "\n". But in _s_plaintextSplitOptions_ and _s_markdownSplitOptions_, you use "\n\r" to search for line endings. As a result, line endings are not taken into account for text splitting.

**Platform**
 - Language: [e.g. C#]
 - Source: main branch of repository

**Comment by lemillermicrosoft** [comment]
Split takes into account any of the characters in the string:

```
int index = input.Slice(pos, input.Length - 1 - pos).IndexOfAny(separators);
```
