### ISSUE TITLE
.Net: AzureCognitiveSearch Memory Connector throws Azure.*

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#2803]
**Describe the bug**
The AzureCognitiveSearch memory connector used to throw SKException when attempting to read from a non existent index.

https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.Memory.AzureCognitiveSearch

Now it throws: Azure.RequestFailedException

**What to the other connectors throw?***

**To Reproduce**
Call ISemanticTextMemory.SearchAsync for a container that doesn't exist.

**Expected behavior**
We well defined exception can be caught.

**Platform**
 - OS: Any
 - IDE: N/A
 - Language: C#
 - Source: main branch of repository

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
