### ISSUE TITLE
Python: Pydantic package <2?

### ISSUE THREAD

**Issue by payneio** [microsoft/semantic-kernel#2812]
Our project requires a recent version of Pydantic (>2) however it looks like SK pins the Pydantic version to < 2. Can this be upgraded?

The commit where this happened is: [https://github.com/microsoft/semantic-kernel/commit/ca6548a441dad547f209491bf5293a12009eb768](https://github.com/microsoft/semantic-kernel/commit/ca6548a441dad547f209491bf5293a12009eb768)

**Comment by joowon-dm-snu** [comment]
`chromadb` is blocking pydantic updates. #2667

**Comment by payneio** [comment]
Looks like they'll have a fix on Monday!

**Comment by quangngoc** [comment]
Do you have any plan to support pydantic v2?

**Comment by dmytrostruk** [comment]
@quangngoc We will add support for pydantic v2 in the nearest future.
