### ISSUE TITLE
.Net: Unicode escape sequences consume too many tokens when using WebSearchEngineSkill (BingConnector) in StepwisePlanner

### ISSUE THREAD

**Issue by takeo-iw** [microsoft/semantic-kernel#2820]
**Describe the bug**
I'm using WebSearchEngineSkill (BingConnector) in StepwisePlanner.
It return an unexpected token over error by Unicode escape sequences.
This becomes a serious problem when using multi-byte characters like Japanese.

**To Reproduce**
The following example does not generate an error, but it does show that more tokens are returned than expected.
<img width="611" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/108264521/2c36004e-1d76-4254-ba58-09edb3f2314a">

This console log is as follows.
<img width="887" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/108264521/0b5d63fb-9f65-4479-a5c4-62bc775a4f8c">
<img width="887" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/108264521/f2c1fac4-2710-49c8-8028-7253c659eed7">
<img width="886" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/108264521/87cbff5a-c069-4dd6-bfde-3aaa860dec4f">
<img width="890" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/108264521/4b64157c-bad3-40a5-bbde-d8997b9b6c3b">

The escaped string is a Telugu language and Japanese language.

It's return more unicode escape sequences when I use Japanese prompt as below.
<img width="883" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/108264521/cfb61fc1-3528-4e3a-be69-57c8d898d589">
　　:
<img width="673" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/108264521/5220a02e-8c95-434c-8cd5-4b2d502c3da7">

The number of tokens will be exceeded in no time.

**Expected behavior**
To work without converting to unicode escape sequences.

**Platform**
 - OS: Mac
 - IDE: VS Code
 - Language: C#
 - Source:  
<img width="829" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/108264521/f246baab-8ff0-4551-bd43-8c91ee23708d">

**Comment by lemillermicrosoft** [comment]
`MaxTokens` configuration parameter is to configure the max tokens to allow in generated prompts and completions within the planner. It does not restrict the output of the plan execution.

**Comment by huyqta** [comment]
Hi, any update for this issue? I'm also facing this now. Is there any option to render response without unicode escape by some specific languages such as Vietnamese or Finnish or Arabian? The output is only plain text, how can it be HTML or Markdown so I can render it on page. If you have any idea to do, please share with me. Thank you so much!

**Comment by yuezhishun** [comment]
@huyqta
I've encountered the same issue.If you trust the search results, you can refrain from encoding the search results.
 [Check here](https://github.com/yuezhishun/semantic-kernel/blob/f4930ba63c1150b45b6f612ec05cf6c6b0c8a432/dotnet/src/Plugins/Plugins.Web/WebSearchEnginePlugin.cs#L59)
