### ISSUE TITLE
Abstractions cleanup

### ISSUE THREAD

**Issue by nacharya1** [microsoft/semantic-kernel#2830]
- [ ] .Net: Move classes in SkillDefinition, Orchestration, Http package to SK Core
- [ ] .Net: 

Reference document: https://microsoft.sharepoint.com/:w:/r/teams/semantic-kernel/_layouts/15/Doc.aspx?sourcedoc=%7B8EE910B1-C8CD-4DC1-B175-8FF9F35E22D1%7D&file=2023.09-Semantic%20Kernel%20DotNet%20Naming%20and%20Abstraction%20Changes.docx&action=default&mobileredirect=true&share=IQGxEOmOzcjBTbF1j_nzXiLRAfQw1zk23jhqlc1uKvtBj4Y

**Comment by nacharya1** [comment]
Review validity of Abstractions package
Are types in Abstrations actually “abstract”?
Are they sufficient for a developer to implement SKFunctions with only this nuget reference?

**Comment by markwallace-microsoft** [comment]
I think the work to verify "Are they sufficient for a developer to implement SKFunctions with only this nuget reference?" should be a separate task.

**Comment by SergeyMenshykh** [comment]
All classes and interfaces from the `SemanticKernel.Abstractions` project were evaluated to determine whether they should remain there or not. The final ask, 'Are they sufficient for a developer to implement SKFunctions with only this NuGet reference?' has been moved to a separate task."https://github.com/microsoft/semantic-kernel/issues/3020.
