### ISSUE TITLE
Python: PromptTemplateConfig.from_dict clobbers default CompletionConfig values

### ISSUE THREAD

**Issue by ascander** [microsoft/semantic-kernel#2851]
**Describe the bug**

Initializing `PromptTemplateConfig` via the `from_dict` method clobbers default `CompletionConfig` values.

**To Reproduce**

Run the following snippet in a notebook or test:

```python
from semantic_kernel.semantic_functions.prompt_template_config import PromptTemplateConfig

base_completion_config = PromptTemplateConfig.CompletionConfig()
updated_completion_config = PromptTemplateConfig.from_dict({ "completion": { "max_tokens": 666 }}).completion

base_completion_config.temperature == updated_completion_config.temperature
```

**Expected behavior**

Default values (eg. `number_of_responses = 1`) for the completion config will be unchanged in the updated config.

**Actual behavior**

Default values are overwritten with `None`, which causes downstream failures.

**Platform**
 - OS: Mac
 - IDE: Neovim
 - Language: Python
 - Source: `main` branch of repository

**Additional context**

Found this while attempting to use `SequentialPlanner` which did not inherit the default value of `1` for the `completion.number_of_responses` setting.

I'm happy take on the implementation for a fix. I have a local fork that fixes this behavior by delegating to `dataclasses.replace` instead of explicitly overwriting completion setting keys. If that's a suitable fix, I'd like to add tests, etc. before submitting the PR.

**Comment by alexchaomander** [comment]
Thank you for bringing this up! @mkarle can you take a look at this and @ascander's PR here https://github.com/microsoft/semantic-kernel/pull/2857
