### ISSUE TITLE
Java: Enable plan validation in the SequentialPlanner

### ISSUE THREAD

**Issue by lnavarette** [microsoft/semantic-kernel#2855]
We've been using the experimental java branch with the SequentialPlanner. Sometimes, the LLM will return a plan that uses some example skills we don't implement in our project. 

For example, the plan might look like

```
Steps:
  - CustomSkill.MyCustomSemanticFunction ...
  - Emailer.EmailTo ...
```

where we have implemented `CustomSkill.MyCustomSemanticFunction` but not `Emailer.EmailTo`

It happens infrequently (we have the temperature set to 0 and see it <5% of the time in our tests), so I tried to implement logic in our project to inspect the resulting `Plan` to check if any of the steps weren't available to the kernel, but the steps on the plan are not accessible. 

I assume this will be a common problem; I could see a few different ways to approach it:
* Make the steps accessible (even a read-only list or copied list) so that the consumer can do the validation
* Add some validation method on the `Plan` itself for a user to check if it's executable and retry creation if it is not 
* Perform some validate plan and/or retry creation as part of the plan creation to reduce the likelihood of consumers getting back a plan that can't be executed.

**Comment by evchaki** [comment]
@johnoliver - we have this feature in .net, can you take a look and see if we have this in Java to stop making up plugins that are not there. - @alliscode  can provide more details here also.

**Comment by johnoliver** [comment]
We will take a look at implementing this our side, @alliscode is this the correct code to be looking at:

https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Planners/Planners.Core/Sequential/SequentialPlanParser.cs#L171

**Comment by lnavarette** [comment]
Is this something you'd be open to contributions on if it becomes a high priority for us before it becomes a high priority for you?

**Comment by johnoliver** [comment]
@lnavarette Yes we are absolutely open to contributions, feel free to message in the discord if you want to discuss it, I believe the validation model c# side is at: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Planners/Planners.Core/Sequential/SequentialPlanParser.cs#L171 so can replicate that, and if there is any other validation you think we can do let us know.

**Comment by d3r3kk** [comment]
Closing as we are not planning on implementing planners right now. Instead we will be implementing tool calling for the V1 release line.
