### ISSUE TITLE
Python: Add Token Tracking to all AI Service Bases

### ISSUE THREAD

**Issue by awharrison-28** [microsoft/semantic-kernel#2858]
---
name: Token Tracking for all AI Services
about: 

This Issue extends the work started by https://github.com/microsoft/semantic-kernel/pull/2844. 

```
    _prompt_tokens: int = 0
    _completion_tokens: int = 0
    _total_tokens: int = 0
```

Should be added to chat_completion_base, text_completion_base, and embedding_base and the values populated by all AI services (google palm, HF, etc.)
---

**Comment by devadigapratham** [comment]
Would love to work on this!

**Comment by alliscode** [comment]
Hi @devadigapratham, thanks for offering to work on this! We're currently looking at the options for how to get this added to SK in python and dot net. We'll let you know when we decide on our path forward, thanks!

**Comment by moonbox3** [comment]
Closing this issue as we currently track usage in Python.
