### ISSUE TITLE
Support of Fallbacks

### ISSUE THREAD

**Issue by RicardoNiepel** [microsoft/semantic-kernel#2860]
---
name: Support of Fallbacks*
about: The feature of Fallbacks for throttling or other API errors, long inputs or Fallback to better models, like LangChain supports it. 

---

**Comment by anthonypuppo** [comment]
Think the [retry](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example08_RetryHandler.cs) example might be what you're looking for?

**Comment by nacharya1** [comment]
@RicardoNiepel, let me know if the sample doesnt give you what you are looking for.

**Comment by nacharya1** [comment]
got it, that makes sense. will add it to the backlog and/or free to propose a PR.

**Comment by markwallace-microsoft** [comment]
@matthewbolanos We can consider supporting this as part of the multiple LLM story
