### ISSUE TITLE
Python: Integration test cases for Prompt Flow

### ISSUE THREAD

**Issue by nacharya1** [microsoft/semantic-kernel#2877]
Define a set of tests to that ensure SK+PF integration remains stable between releases. Partner with PF team

**Comment by matthewbolanos** [comment]
The integration tests should test for the following:

- [ ] Instantiation of a kernel in a Prompt flow Python node
- [ ] Adding an Azure Chat Completion service using an Prompt flow connection object
- [ ] Adding of a plugin (with both native and semantic functions)
- [ ] Running of planners with the plugin (Sequential and Stepwise)
- [ ] Returning the result back to prompt flow

**Comment by matthewbolanos** [comment]
SK has been integrated into Prompt flow
