### ISSUE TITLE
.Net: Clean up Semantic Function code in Kernel Abstractions/Core

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#2887]
- [x] .Net: Remove IServiceConfig.cs
- [x] .Net: Move SemanticFunctions to separate package
- [x] .Net: Obsolete PromptTemplateConfig.Type
- [x] .Net: Obsolete PromptTemplateConfig.DefaultServices
- [ ] .Net: Obsolete PromptTemplateConfig.Input
- [x] .Net: Obsolete PromptTemplateConfig.Completion
- [ ] .Net: Clean up KernelSemanticFunctionExtensions
- [ ] .Net: Revisit naming of IPromptTemplate

Reference document: https://microsoft.sharepoint.com/:w:/r/teams/semantic-kernel/_layouts/15/Doc.aspx?sourcedoc=%7B8EE910B1-C8CD-4DC1-B175-8FF9F35E22D1%7D&file=2023.09-Semantic%20Kernel%20DotNet%20Naming%20and%20Abstraction%20Changes.docx&action=default&mobileredirect=true&share=IQGxEOmOzcjBTbF1j_nzXiLRAfQw1zk23jhqlc1uKvtBj4Y

**Comment by stephentoub** [comment]
This is done
