### ISSUE TITLE
Python: `NullLogger` function signatures need to match the function signatures of `logger.Logger` object. 

### ISSUE THREAD

**Issue by Jibola** [microsoft/semantic-kernel#2889]
**Describe the bug**
`NullLogger` function signatures need to match the function signatures of `logger.Logger` object. 
* As seen in this https://github.com/microsoft/semantic-kernel/pull/2818/files/99cdd2523c2c299143f0e6780dabcbdbb7ae2414#r1327326272 implementation. When a user attempts to leverage logging behavior, it will raise an error due to the `NullLogger` expecting different parameters

**To Reproduce**
1. Import `NullLogger` in code
2. Assign it to a variable
3. Attempt to use it similar to how `Logger` would be used, (logger.debug("%s", "string"))

```
>       self._logger.debug(
            "matched_count=%s, upserted_count=%s",
            bulk_update_result.matched_count,
            bulk_update_result.upserted_count,
        )
E       TypeError: debug() takes 2 positional arguments but 4 were given
```

**Expected behavior**
The expected behavior should be that `NullLogger` does nothing and raises no error

**Comment by nacharya1** [comment]
@awharrison-28. FYI this is linked to the Mango DB connector request.

**Comment by Jibola** [comment]
Put up a PR that I believes mitigates this issue: #2892
