### ISSUE TITLE
Python: Add http header parameter in AzureChatCompletion function

### ISSUE THREAD

**Issue by alexChiu127** [microsoft/semantic-kernel#2895]
For python, could we add http header parameter in AzureChatCompletion function? We need to pass "X-User-Id" when calling Azure open AI chat complete function. 
In C# version, we can pass a httpcllient parameter to WithAzureChatCompletionService.

**Comment by eavanvalkenburg** [comment]
This is now possible by using the AsyncAzureOpenAI option for the AzureChatCompletion class, thereby you create your own instance of the OpenAI client class with the required settings, including additional headers. @alexChiu127 does that work for you or do you also expect to be able to use a parameters on the AzureChatCompletion class itself?
