### ISSUE TITLE
Python: Milvus: consider using static rather than dynamic fields for the Semantic Kernel metadata

### ISSUE THREAD

**Issue by roji** [microsoft/semantic-kernel#2901]
In #1941, @filip-halt added a Python memory store implementation for the Milvus vector database; #2694 (pending) does the same for .NET. A Semantic Kernel memory store needs to support storing various metadata fields alongside the vector data: a timestamp, an optional external source name, additional metadata, and so on. The Python connector implements these metadata fields as [Milvus dynamic schema fields](https://milvus.io/docs/dynamic_schema.md); this means that the fields aren't defined up-front in the schema, but are added dynamically (and stored behind the scenes as JSON on the special `$meta` field).

Since the SK metadata fields are known in advance and do not change, I think it should be considered to switch representing them as regular, static schema fields instead. Dynamic fields aren't as well-supported in various ways; and importantly, AFAIK it's not possible to define an index over them (so efficiently filtering by metadata isn't possible).

As of now the .NET PR (#2694) was done via dynamic schema to align with the Python connector; but I believe both connectors should be changed to use static fields.

/cc @filip-halt @yhmo @weianweigan @stephentoub @awharrison-28 @ajcvickers

**Comment by nacharya1** [comment]
@lemillermicrosoft will update as he working on this already.

**Comment by lemillermicrosoft** [comment]
For now this is staying in the backlog, feedback from @filip-halt would be appreciaed.

**Comment by eavanvalkenburg** [comment]
This was actually done.
