### ISSUE TITLE
.Net: Stepwise planner context missing variables in native functions

### ISSUE THREAD

**Issue by fizgig** [microsoft/semantic-kernel#2906]
**Describe the bug**
Stepwise planner context missing variables

**To Reproduce**
1. Create a stepwise planner with context variables, e.g. name, id
2. Create a native function that has an SKContext parameter 
3. Invoke the plan
4. Set a break point in the native function the context is passed into, all context variables are removed and an empty INPUT variable is added

**Expected behavior**
All context variables should be present

**Screenshots**

![image](https://github.com/microsoft/semantic-kernel/assets/1848733/53980e4d-c650-4d0a-922e-d626be1285a8)

![Screenshot 2023-09-20 141731](https://github.com/microsoft/semantic-kernel/assets/1848733/38711b07-cf02-45ef-af94-c65fbf489bd4)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - C#
 - Microsoft.SemanticKernel 0.24.230918.1-preview 

**Additional context**
It works with Sequential Planner with nearly the same code
![image](https://github.com/microsoft/semantic-kernel/assets/1848733/c12094db-6d1d-47f2-b67d-6ab99e31a5c2)

**Comment by lemillermicrosoft** [comment]
You should not pull variables from context like that any longer. Instead, you should just define the parameters you want on the method signature.

**Comment by fizgig** [comment]
I was getting intermittent type mismatches or null variables with that approach so I moved them out of the method signature.  Where should I set some token claims as variables, still in the context but pull them in with the method signature?  Somewhere else?

**Comment by fizgig** [comment]
I tried a few approaches and it works fine with sequential planner, it can call a user lookup skill or grab the value from the context.  For stepwise planner it's literally making up a name and account ID (John Doe and 123456789).
