### ISSUE TITLE
.Net: Update planner formatting to accommodate ParameterView.IsRequired

### ISSUE THREAD

**Issue by gitri-ms** [microsoft/semantic-kernel#2915]
> [!IMPORTANT]  
> Labeled **High** because it will not require a breaking change, but it's very important to complete by v1.0.0

IsRequired field is being added to ParameterView in the function calling PR (#2842). We should update planners accordingly.

**Comment by matthewbolanos** [comment]
@gitri-ms and @teresaqhoang, is this already done in the new connectors?
