### ISSUE TITLE
.Net: Stream response should not skip white space

### ISSUE THREAD

**Issue by anthonypuppo** [microsoft/semantic-kernel#2921]
**Describe the bug**
The current Azure OpenAI streaming implementation skips white space (ie. space character token ID 220). All non-empty tokens should be streamed, including space characters. This is rare as most tokens are prefixed with a space by default, but still an issue in some cases (such as formatted markdown, code, etc).

**To Reproduce**
1. Generate a response that would include space tokens (any sort of code)
2. Space tokens are skipped

**Expected behavior**
Stream all non-empty generated tokens.

**Screenshots**
N/A

**Platform**
 - OS: All
 - IDE: All
 - Language: C#
 - Source: Introduced in #2917

**Comment by nacharya1** [comment]
@RogerBarreto , can you take a look into this and see if it is a bug and update appropriately.
