### ISSUE TITLE
Python: Faulty context variable resolution in SequentialPlanner

### ISSUE THREAD

**Issue by llperez** [microsoft/semantic-kernel#2933]
**Describe the bug**

In certain plans, the mechanism for resolving variables is not being applied correctly with functions that take more than one parameter.

Consider a simple case using `semantic_kernel.core_skills.MathSkill`: "Calculate (10 + 2) - (8 + 7)". The resulting plan (from gpt-3.5-turbo-16k-0613) is:

```
Function: mathskill.Add
Input vars: {'input': '10', 'amount': '2'}
Output vars: ['SUM1']

Function: mathskill.Add
Input vars: {'input': '8', 'amount': '7'}
Output vars: ['SUM2']

Function: mathskill.Subtract
Input vars: {'input': '$SUM1', 'amount': '$SUM2'}
Output vars: ['RESULT__FINAL_ANSWER']
```

The plan is correct. But when it comes to evaluation, the last step fails because it doesn't resolve `amount` to the corresponding result, leaving the string value `'$SUM2'` unresolved.

**To Reproduce**

```
planner = SequentialPlanner(kernel=kernel)
kernel.import_skill(MathSkill(), "mathskill")
plan = asyncio.run(planner.create_plan_async("Calculate (10 + 2) - (8 + 7)"))
result = asyncio.run(kernel.run_async(plan))
for index, step in enumerate(plan._steps):
   print("\nFunction: " + step.skill_name + "." + step._function.name)
   print("Input vars: " + str(step.parameters.variables))
   print("Output vars: " + str(step._outputs))

print("Result: " + str(result))
```

The final output is:
```
Result: Error: (<ErrorCodes.FunctionInvokeError: 8>, 'Error occurred while running plan step: Context amount provided is not in numeric format: $SUM2', ValueError('Context amount provided is not in numeric format: $SUM2'))
```

**Expected behavior**

`$SUM2` should resolve `15`, leading to a final plan result of `-3`.

**Platform**
 - OS: Windows 10
 - IDE: VSCode
 - Language: Python
 - Source: 0.3.13.dev0

**Additional context**

I tried investigating this further by creating a plugin class with the following functions:

```
class MyMathPlugin:
    @sk_function(
        description="Adds two numbers together",
        name="add",
    )
    @sk_function_context_parameter(
        name="input",
        description="The first number to add",
    )
    @sk_function_context_parameter(
        name="number2",
        description="The second number to add",
    )
    def add(self, context: SKContext) -> str:
        return str(float(context["input"]) + float(context["number2"]))
    
    @sk_function(
        description="Subtract two numbers",
        name="subtract",
    )
    @sk_function_context_parameter(
        name="input",
        description="The first number to subtract from",
    )
    @sk_function_context_parameter(
        name="number2",
        description="The second number to subtract away",
    )
    def subtract(self, context: SKContext) -> str:
        print(str(context.dict()['variables']))
        input = float(context["input"])
        number2 = float(context["number2"])
        out = str(input - number2)
        print(f'{input} - {number2} => {out}')
        return out
```

The printed dictionary is as follows:
```
{'variables': {'input': '12.0', 'number2': '$SUM2', 'sum1': '12.0', 'sum2': '15.0'}}
```

Interestingly, `input` is resolved correctly and there is a `sum2` variable with the actual result of what `number2` should be. 
```[tasklist]
### Tasks
```

**Comment by rajib76** [comment]
I am also getting the same error

**Comment by amritpal-singh-98** [comment]
Also having the same issue, causing `SequentialPlanner` to be unusable.

The problems seems to be in the `get_next_step_variables` method of the `Plan` class:

https://github.com/microsoft/semantic-kernel/blob/b2bbd410c07739767b5aad48961a8ced5b4cf4a4/python/semantic_kernel/planning/plan.py#L403-L415

On line 407, the dictionary _key_ (`param_var`) is incorrectly passed to the `expand_from_variables` method instead of the corresponding dictionary _value_. Thus, the value never gets expanded from the literal string `"$SUM2"` (for example).

Here is some a corrected version of the same code:

```python
# At this stage, 
# step.parameters.variable = {'amount': '$SUM2', ... }
# variables.variables = {'amount': '15', ... }
# self._state.variables = {'amount': '15', ... }

for param_name, param_val in step.parameters.variables.items():
    if param_name in step_variables:
        continue

    if param_name in variables:
        step_variables.set(param_name, param_val)
    elif param_name in self._state:
        step_variables.set(param_name, self._state[param_name])
    else:
        expanded_value = self.expand_from_variables(variables, param_val)
        # Prefer to use the original casing if the casefolded value is the same
        if expanded_value.casefold() != param_val.casefold():
            step_variables.set(param_name, expanded_value)
```

This fixes the bug for my use-case, with context variables now being correctly resolved (but I've not tested beyond that!).

@dluc , @matthewbolanos - I'm new to the codebase, would appreciate a review to see if this solves the bug here. :blush:

**Comment by juliomenendez** [comment]
@amritpal-singh-98 thank you for the corrected version. I updated the `Plan` code and ran the original example code of this issue and it looks to fix it. I created a PR with your change and another fix required to make it all work and mentioned you in it for reference. Thanks!

This is the output now with my PR:
```bash
Function: mathskill.Add
Input vars: {'input': '10', 'amount': '2'}
Output vars: ['SUM1']

Function: mathskill.Add
Input vars: {'input': '8', 'amount': '7'}
Output vars: ['SUM2']

Function: mathskill.Subtract
Input vars: {'input': '$SUM1', 'amount': '$SUM2'}
Output vars: ['RESULT__FINAL_ANSWER']
Result: -3
```
