### ISSUE TITLE
Python: Documentation with broken links

### ISSUE THREAD

**Issue by hghalebi** [microsoft/semantic-kernel#2934]
**Describe the bug**
in this notebook
https://github.com/microsoft/semantic-kernel/blob/main/python/notebooks/01-basic-loading-the-kernel.ipynb
Just at the beginning, there is this phrase:

> See [DEV_SETUP.md](https://github.com/microsoft/semantic-kernel/blob/python/DEV_SETUP.md) for more information. 

which the link is borken.

**Comment by markwallace-microsoft** [comment]
Fixed: https://github.com/microsoft/semantic-kernel/commit/53758dc9bceafd4657b820dba6559e3d08ca7d0b
