### ISSUE TITLE
.Net: Allow instances of ISKFunction to be used with different Kernel instances

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#2936]
> [!IMPORTANT]  
> Labeled **Urgent** because it will require a breaking change.
```[tasklist]
### Tasks
- [ ] Create ADR for ISKFunction to be used with different Kernel
```

**Comment by markwallace-microsoft** [comment]
The code to register a function with a Kernel is implemented as follows

```csharp
    public ISKFunction RegisterCustomFunction(ISKFunction customFunction)
    {
        Verify.NotNull(customFunction);

        customFunction.SetDefaultFunctionCollection(this.Functions);
        this._functionCollection.AddFunction(customFunction);

        return customFunction;
    }
```

The call to `customFunction.SetDefaultFunctionCollection(this.Functions)` causes the `ISKFunction` instance to be linked to the current Kernel instance. This means it cannot be reused. 

The means we cannot reuse an `ISKFunction` instance and we have to recreate these. This can be an expensive operation e.g. for semantic functions which rely on a prompt template which will need to be parsed multiple times.

**Comment by matthewbolanos** [comment]
@alliscode, we'll likely need your help to know if this is a problem needing solving for v1.0.0

**Comment by markwallace-microsoft** [comment]
This is resolved and the current methods that link a semantic function to a kernel instance are now obsolete
