### ISSUE TITLE
.Net Delete bulk vector points with Qdrant provider error

### ISSUE THREAD

**Issue by simone-devoti** [microsoft/semantic-kernel#2944]
**Describe the bug**
If we try to delete 10.000 elements from the semantic kernel memory vai Qdrant the cancellation takes too much time (4+ minutes) or just breaks because we overload the server with requests.

![image](https://github.com/microsoft/semantic-kernel/assets/90269198/4def4415-353f-4880-8e20-4008519870e9)

**To Reproduce**
1. Use Qdrant memory connector
2. Upload 10000 elements
3. Delete them using `IMemoryStore.RemoveRangeAsync` or `IKernel.Memory.RemoveAsync`

**Expected behavior**
Delete all of the elements with just one call (available in Qdrant)

**Additional context**
The bulk delete is possible right now If we have the native Qdrant element Ids using the method `QdrantVectorDbClient.DeleteVectorsByIdAsync`.
The problem is that the native IDs in Qdrant are different from the one used in Semantic Kernel Memory.
So in order to get the native Ids I need to do a call each

**Current ugly solution**
Use additionalmetadata field from SemanticKernel as filter for Qdrant native delete.
In Qdrant we can bulk delete via multiple native IDs or via filters

**Comment by simone-devoti** [comment]
For now you can do the bulk delete using the native qdrant capabilities:

Where `objectsIds` are the ids of the elements stored in Semantic Kernel

```
using var httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.Add("api-key", qdrantSecrets.ApiKey);

var data = new
{
        filter = new
        {
               must = new[]
               {
                      new 
                      {
                              key= "id",
                              match = new 
                              {
                                    any = objectsIds
                              }
                       }
                }
        }
};

var jsonData = JsonSerializer.Serialize(data);
var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

var response = await httpClient.PostAsync($"{qdrantSecrets.Url}/collections/{collectionId}/points/delete", content);

if (!response.IsSuccessStatusCode)
{
           var message = $"Failed to bulk delete qdrant elements. Collection: {collectionId}";
           logger.LogError(message);

           throw new Exception(message);
}
```

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
