### ISSUE TITLE
.Net: StepwisePlanner - Get informed about thoughts, actions and obervations

### ISSUE THREAD

**Issue by HSven1611** [microsoft/semantic-kernel#2951]
For a more transparent approach I need to be able to present the working process of stepwiseplanner to my user. A user story might look loke this:

`As a User I want to get updated about the process of plan execution so that I do not have to wait sort of blind until the plan execution finished.`

As this information is already being put out on the logger, it should be a quick win to expose this as an event that I can subscribe to. This should not affect performance that bad because if I do not like to subscribe, the event would simply not being fired.

E.g. here an action is being logged: https://github.com/microsoft/semantic-kernel/blob/086ef88a5218f8a265eff82814981412ce1270f6/dotnet/src/Extensions/Planning.StepwisePlanner/StepwisePlanner.cs#L142C49-L142C49 this could easily be extended by an event being fired.

Best case: We do get Events specifically for Thoughts, Actions and Observations as this would enable us to provide a much more immersive user experience.

**Comment by Mano1192** [comment]
This would be great! Being able to post or display the MRKL/ReAct thought process to the user in the UI is going to provide a much higher level of user trust in Agent use in my use case. I will be eagerly waiting for this one as its a blocker currently on one of our stepwise planner agents we would like to roll out.

**Comment by shivmohith** [comment]
Yes, I am also eagerly waiting for this feature. This will help in providing a better user experience.

**Comment by matthewbolanos** [comment]
This should now be possible with hooks! [In this sample](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example57_KernelHooks.cs), we demonstrate how you can create pro/post hooks on your functions. You could then use this information to provide updates to the user on what the planner is actively doing.
