### ISSUE TITLE
.Net: OpenSearch/ElasticSearch memory storage support

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/semantic-kernel#2957]
ElasticSearch can support vector search, and the number of vector dims max to 2048 since 8.8 version

https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.8.0.html

OpenSearch: https://opensearch.org/platform/search/vector-database.html

**Comment by mikkel-busch** [comment]
We have a functioning IMemoryStore based on Elasticsearch would you be interested in PR?

**Comment by giannik** [comment]
> We have a functioning implementation of IMemoryStore based on Elasticsearch would you be interested in PR?

Is this available for trying out ? Im interested in elatic search memeory from semantic kernel .

**Comment by hobbsax1** [comment]
Would really like to see an ES8 memory store in SK and Kernel Memory too.  Have environments where AzureAISearch is not an option.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
