### ISSUE TITLE
.Net: Memory and document structure for semantic search should be extensible

### ISSUE THREAD

**Issue by gingters** [microsoft/semantic-kernel#2958]
This feature request could be a bit bigger.

As suggested in one of the last public SK office hours, it would be great if the memory management for semantic searches would be more extensible and more pluggable.

Some use cases that were discussed were as follows:
- allow control of the collections used for document storage & retrieval
- allow consuming of document stores created with LangChain (be able to use the document format from there)
- allow asynchronous transformation of the original document before indexing (similiar to HyDE, but more like HyQE: Hypothetical Question Embeddings, you send the document to a model to generate a few questions about the document, and the questions will get indexed while the original document or a reference to that content is stored as metadata)
- allow asynchronous re-transformation of documents after retrieval, before passing them back to the model (same scenario, the document was transformed at indexing, now we found the questions and need to return the original documents content, but we only stored a reference and need to fetch the contents from somewhere over a network)

This would mean introducing a new interface (i.e. `DocumentTransformer`) with two async methods that are called before storage and after retrieval. Or two distinct interfaces with a single method each.

My idea would be to register the transformer implementation type with the corresponding adapter. If a transformer is registered, the new methods would be called before passing the document to the adapter or after the adapter returned the found document. This of course means that the adapters must not make assumptions about the structure of the documents itself, as they might now work on LangChain documents that will be transformed to SK documents (or vice versa).

**Comment by matthewbolanos** [comment]
@dluc, do you have thoughts on the recommendation by @gingters?

**Comment by dluc** [comment]
please see https://github.com/microsoft/semantic-kernel/issues/1044

* more control for collections/indexes should be already available, would love hearing some feedback
* async transformation is available :-) see how the pipelines work, plus the ability to develop custom pipelines
* consuming docs ingested by other solutions: work in progress

**Comment by tonyqus** [comment]
> async transformation is available :-) see how the pipelines work, plus the ability to develop custom pipelines

Where is the documentation of custom pipelines? I searched https://learn.microsoft.com/en-us/semantic-kernel/. But I cannot find any related pages
