### ISSUE TITLE
Python: Retrieval Core Skill

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/semantic-kernel#2959]
Currently there is a `memory` and `text memory skill`, but I think it would make sense to also have a `retriever` skill, which get's instantiated with whichever store connection needed, and also has the required fields, including the field names in the actual store in the init, and just supplies a `retrieve` function. 

This means you can easily connect any database/vector store fully in the construction of this skill, and you do not have to adhere to the exact specs of the memory stores (of course some of the underlying code from the memory store can be shared). 

I see in many cases that the team and skills to build a good vector store/search index are very different then the ones building SK apps and plugins, so it makes sense to have them be able to just handover the specs from the index building team to the SK building team. 

It also provides an easier onramp for new memory stores by first creating just a retrieval store, before also implementing construct and writes functions.

**Comment by moonbox3** [comment]
@eavanvalkenburg is this work item still relevant?
