### ISSUE TITLE
Python: change variables getter to be more pytonic

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/semantic-kernel#2962]
I just noticed that the `.get` method of the `context.variables` object gives back a tuple[bool, str], this is very unpytonic (clearly straight port from the .net world), would be good to change this to the same signature as all other collection `.get` methods in Python, with None being returned if nothing is present, and the actual object if it is, potentially including optionally passing in a default so that it is even more predictable for a python dev.

**Comment by matthewbolanos** [comment]
@eavanvalkenburg, would you be interested in contributing a PR to fix this? I would agree that this would be a great addition.

**Comment by eavanvalkenburg** [comment]
@matthewbolanos just did that monday, #3039

**Comment by dluc** [comment]
on it, overall it's a welcome improvement, only a few bugs to iron out then we can merge
