### ISSUE TITLE
Python: Feature: Add extenstion for Azure OpenAI On Your Data

### ISSUE THREAD

**Issue by johnliu55-msft** [microsoft/semantic-kernel#2998]
Since C# has supported this feature (#2392), is there a plan to support this in Python?

**Comment by matthewbolanos** [comment]
Yes, we would like to support this. Would you be interested in submitting a PR to add this functionality?

**Comment by johnliu55-msft** [comment]
Sure! I suppose this feature should be implemented as an AI connector just like the dotnet implementation?

**Comment by johnliu55-msft** [comment]
I noticed that the Python implementation **lacks a user-friendly way to support multiple AI connectors/LLM models**, which is a crucial dependency of supporting Azure OpenAI on your data. The reason behind this is if we implemented the feature as an AI connector, then this AI connector should only be used by certain semantic functions. For instance, the planner should never use the connector to generate a plan.

On the other hand, the dotnet implementation has [`ServiceId`](https://github.com/microsoft/semantic-kernel/issues/1787#issuecomment-1752917767) to configure the connector to use for each semantic function.

Seems like there are some issues tracking this dependency, but seems like they are mostly for dotnet:
- #3041
- #1787

I'm happy to implement this `ServiceId` feature for Python if it's required.

**Comment by johnliu55-msft** [comment]
@matthewbolanos Seems like the dotnet version has introduced the [`ModelSettings`](https://github.com/microsoft/semantic-kernel/blob/18ffc4bf2f2b57d3c58381e8d961e3757ce0c991/dotnet/src/SemanticKernel.Core/TemplateEngine/PromptTemplateConfig.cs#L88) attribute to the `PromptTemplateConfig` class to specify the AI connector to use for the given semantic function. Will this `ModelSettings` abstraction be added to Python's implementation?

**Comment by matthewbolanos** [comment]
Yes, our current plan is to bring ModelSettings into the Python version of Semantic Kernel

**Comment by eavanvalkenburg** [comment]
This is in there, including samples.
