### ISSUE TITLE
Java: Issue with getStreamingChatCompletionsAsync() and getChatCompletionsStream() methods after integrating semantic-kernel

### ISSUE THREAD

**Issue by thomaspeng90s** [microsoft/semantic-kernel#3001]
I encountered an issue after integrating semantic-kernel into my project. When attempting to use the ChatCompletion to call the methods getStreamingChatCompletionsAsync() or getChatCompletionsStream(), I receive the following error:
```
com.azure.core.exception.HttpResponseException: Status code 400, "{
  "error": {
    "message": "None is not of type 'object' - 'logit_bias'",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
"
```
Upon investigation, I found that semantic kernel is currently using the azure-ai-openai dependency version 1.0.0-beta.2:
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-ai-openai</artifactId>
    <version>1.0.0-beta.2</version>
</dependency>

However, it appears that the SDK has already been upgraded to version 1.0.0-beta.5. When I directly reference the 1.0.0-beta.5 version, the methods work as expected.

I would appreciate any guidance or solutions to this issue. Thank you.

**Comment by thomaspeng90s** [comment]
I've found that this error only occurs when I import semantickernel-connectors, which is still at version 0.2.7-alpha.

**Comment by matthewbolanos** [comment]
@johnoliver, looks like the version needs to be updated for the connector library.

**Comment by johnoliver** [comment]
@thomaspeng90s we are updating all our packages to the latest client, however we reorganised our packaging structure so `semantickernel-connectors` is a deprecated package, in favour of pulling in a specific connector such as `semantickernel-connectors-memory-jdbc` or  `semantickernel-connectors-memory-azurecognitivesearch`

**Comment by d3r3kk** [comment]
Putting this onto the backlog as we have decided to hold back on implementing streaming until post-V1.0 release.

**Comment by d3r3kk** [comment]
Streaming is not planned in the 1.0.0 release of Java Semantic Kernel.
