### ISSUE TITLE
When using Sequential Planner for first time, getting index not found exception for Azure Cognitive Search

### ISSUE THREAD

**Issue by akshaykokane** [microsoft/semantic-kernel#3015]
**Describe the bug**
When using Sequential Planner for first time, getting following exceptions.
>

```
The index 'planning-skfunctionsmanual' for service 'test-search-bn' was not found.
Status: 404 (Not Found)

Content:
{"error":{"code":"","message":"The index 'planning-skfunctionsmanual' for service 'est-search-bn' was not found."}}

```
**To Reproduce**
1. Create Sequential Planner
2. User Azure Cognitive Search has Memory
3. When, Planner try to find relevant plugins for user's ask, it fails because as its first time it cannot see 'planning-skfunctionsmanual' index.
4. Catch Block should catch 404, but the status code is empty.

**Expected behavior**
- Crates new ''planning-skfunctionsmanual' index in ACS

**Comment by matthewbolanos** [comment]
Are you able to share how you setup your connector? It looks like it may have not been configured correctly so SK cannot find the index.

**Comment by akshaykokane** [comment]
```
          
var memory = new AzureCognitiveSearchMemoryStore(acsConfigProvider.GetACSURL(), acsConfigProvider.GetACSTokenCredentials());

IKernel kernel = Kernel.Builder
                .WithAzureChatCompletionService(azOpenAIConfig.GetModelConfiguration().ChatDeploymentName, endpoint, key)
                .WithAzureTextEmbeddingGenerationService(azOpenAIConfig.GetModelConfiguration().EmbeddingDeploymentName, endpoint, key)
                .WithMemoryStorage(memory)

```

**Comment by alliscode** [comment]
It looks like the connector is looking for the 404 response which is no longer what the ACS exception contains. We will take a look at fixing this. @akshaykokane, if you would like to submit a PR for this we would be happy to take it. Thanks!

**Comment by jhST** [comment]
Could it be because the CreateCollectionAsync method is empty?

https://github.com/microsoft/semantic-kernel/blob/8d6cc3e9513ef038458ae9739abbd11ee0b6b666/dotnet/src/Connectors/Connectors.Memory.AzureCognitiveSearch/AzureCognitiveSearchMemoryStore.cs

**Comment by matthewbolanos** [comment]
Closing since the sequential planner is being replaced by the function calling version
