### ISSUE TITLE
Allow switching/hybdrid between Semantic and Vector Index in Azure Cogntive Search

### ISSUE THREAD

**Issue by akshaykokane** [microsoft/semantic-kernel#3016]
- Currently, the TextSemanticMemory, uses only Vector Index for searching. But it has shown, in some cases semantic search or hybrid search outperforms Vector index search (src: https://techcommunity.microsoft.com/t5/azure-ai-services-blog/azure-cognitive-search-outperforming-vector-search-with-hybrid/ba-p/3929167)
- Allow in Semantic Kernel memory to decide which search strategy to use on Azure Cognitive Search Index

**Comment by matthewbolanos** [comment]
@dluc, would this be a good scenario to use the new Semantic Memory service?

**Comment by dluc** [comment]
please see https://github.com/microsoft/semantic-kernel/issues/2544
