### ISSUE TITLE
.Net: Verify abstractions are sufficient for custom SKFunctions

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#3020]
> [!IMPORTANT]  
> Labeled **Urgent** because it will require a breaking change if any contracts need to change. Please lower the priority if this is not the case.

Verify that existing abstractions in the `SemanticKernel.Abstractions` nuget package are sufficient for a developer to implement SKFunctions with only this nuget reference.

This is continuatin of the https://github.com/microsoft/semantic-kernel/issues/2830 task.

```[tasklist]
### Tasks
- [ ] AI Connectors (we believe this is already possible based on community additions)
- [ ] SKFunctions
- [ ] Plugins
```

**Comment by matthewbolanos** [comment]
@markwallace-microsoft, does this make sense as something that Ben's team could/should investigate for us?

**Comment by matthewbolanos** [comment]
Next step is to create a SK sample app that demonstrates that you can use the abstractions to create a new extensions.
