### ISSUE TITLE
StepwisePlanner can get stuck when waiting for action.

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#3027]
There's a state where the model comes back with a [THOUGHT] but no [ACTION]. You coax it along by adding an action block in the history.

 

                if (lastStep is not null && string.IsNullOrEmpty(lastStep.Action))
                {
                    this._logger?.LogWarning("No response from LLM, expected Action");
                    chatHistory.AddUserMessage(Action);
                }

 

The model will then emit the JSON blob for the action but when you get to ParseResult(string input) the input doesn't have the [ACTION] that you emitted. As a result, it doesn't execute the action.

**Comment by matthewbolanos** [comment]
Closing since the stepwise planner has been replaced with the function calling version.
