### ISSUE TITLE
enhance StepwisePlanner to support customizing ai function call

### ISSUE THREAD

**Issue by linkaiyu** [microsoft/semantic-kernel#3028]
Motivation:

The current planners send the registered function meta data to ai to get a THOUGHT. 

Since user questions are unpredictable, the application won't be able to implement all callback functions upfront. Even the application can implement as many functions as possible, it would run into the problem of having to send a large number of function meta data in the request, taking up a lot of tokens.

Requested features: 

A planner (based on the functionality of StepwisePlanner or updated StepwisePlanner) that supports these additional features:

Support a callback function or an event for application to return function meta data information. This would let application to search a vector db for available functions based on the given description.
 Support plugin step before the StepwisePlanner step. This would allow application to send a customized request or instructions to ai to get THOUGHT  from ai on what kind of function it needs to be in place.
Support application to programmatically control what function information is sent to ai. This will save tokens when the application has a large number of functions but does not need to be sent over to ai every time user asks a question.
 
Explanation:

Developers can keep adding functions data to the store in a separate work from the application. And deploy the implementation to the application folder. 

The planner does not need to know how many or what functions exist in the store and in the deployment folder.

When the application starts, the planner does not need to preregister callback functions for ai function call.

The first question the planner sends to ai is the instruction for it to review/analyze the user question and provide the THOUGHT on what information it needs to successfully respond, and format the THOUGHT in such a json structure such that it contains description, function name, function parameter which is a list of name value pair.

When the planner receives the first response back from ai, it parses the response, use the description and function name to search the vector db for possible callback functions. 
 
If found, include the function meta info in the instructions to ai (just like the current StepwisePlanner does). Send the request to ai just like the first time the current StepwisePlanner does.

If not found, then just send the original question to ai.

When ai returns the response with function call information, the planner dynamically loads the function and execute to provide the OBSERVATION.

The rest is the same with the current StepwisePlanner.

 In summary, the new planner basically adds one step in front of the current StepwisePlanner to solicit possible function call information from ai, and dynamically generate the function information for ai.
 
Benefit:

1. would allow applications to use the planner in a generic way such that new functions can be added over the time without having to modify application code to register functions. 

2. the application can cover much wider area of user request, 

3. this would reduce tokens used in the query.
 
AI Hallucination:

There might be an issue with ai being hallucinating. This problem should be mitigated by providing instructions to ai with the format of the function. If ai is hallucinating, the planner would end up not finding the matching function in the vector db. In this case, it would just be ignored.

It is possible that ai is hallucinating and the function information in the THOUGHT might coincide with the existing function in the vector db, I guess it might be a small chance. A good description of the function might reduce the odds.

**Comment by lemillermicrosoft** [comment]
> Support a callback function or an event for application to return function meta data information. This would let application to search a vector db for available functions based on the given description.

See [GetAvailableFunctionsAsync ](https://github.com/microsoft/semantic-kernel/blob/8c0729679319e086f84be2296de811ce319d2690/dotnet/src/Planners/Planners.Core/PlannerConfigBase.cs#L48C8-L48C8) and [SemanticMemoryConfig](https://github.com/microsoft/semantic-kernel/blob/8c0729679319e086f84be2296de811ce319d2690/dotnet/src/Planners/Planners.Core/PlannerConfigBase.cs#L40C33-L40C54) options available that enables this kind of functionality.

> AI Hallucination:

Yeah, you beat me to it :). While there is room for exploring the addition of a Planner that updates the System message with a different manual of functions on every turn of the wheel, there might be complications there with hallucinations due to unlisted functions being used previously in the chat. But also potentially solvable.

You can wrap a StepwisePlanner or any planner in a native plugin and do these kings of things though. Would be glad to walk through some examples. Here is a quick one. You could imagine involving the chat history or other context as well in this callback.

```csharp
[SKFunction, Description("Respond to a message.")]
public async Task<SKContext> RespondTo(string message, string history)
{
    var planner = new StepwisePlanner(
        this._kernel,
        new StepwisePlannerConfig() { 
            GetAvailableFunctionsAsync = async () => { return await this.GetMyRelevantFunctions(message);}}
        );

    // Respond to the history with prompt
    var plan = planner.CreatePlan($"{history}\n---\nGiven the conversation history, respond to the most recent message.");
        var result = await plan.InvokeAsync();

    return result;
}

private async Task<IEnumerable<SKFunction>> GetMyRelevantFunctions(string userMessage)
{
    IEnumerable<SKFunction> functions;
    // ... Populate your functions based on the useMessage
    return functions;
}
```

**Comment by matthewbolanos** [comment]
This has now been done with the new function calling stepwise planner in .NET
