### ISSUE TITLE
Python:  Changing the kernel's text completion service doesn't affect the ai services used by semantic functions

### ISSUE THREAD

**Issue by sarapiscitelli** [microsoft/semantic-kernel#3033]
## Bug Description
Semantic functions remain connected to the initial text completion service, even if such service has been removed from the kernel.    
When using the same kernel, if a text completion service is added to the kernel, then removed, and a new text completion service is added, the semantic skills in the kernel are not updated accordingly. All semantic skills continue to use the removed service. 
Specifically during this process, it can be observed that the attribute '_ai_service' in the [class SKFunction](https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/orchestration/sk_function.py) is not updated with the new instance of the service TextCompletionClientBase.   

The only way to work around it, for me, has been to reimport all semantic skills in the kernel every time the text completion service changes. This ensures that the semantic skills are consistently updated with the services within the kernel.   
But is this what one should do if they want to update an AI service in the kernel? Perhaps it would be more appropriate to update them automatically instead of relying on the user to remember to re-import the skills if they decide to change a specific AI service.    

Is there perhaps another way to update a text completion service in the semantic kernel to make it work?

## To Reproduce
1. Considering the example provided in [samples/python/04-Serializing-Semantic-Functions](https://github.com/MicrosoftDocs/semantic-kernel-docs/tree/main/samples/python/04-Serializing-Semantic-Functions), modify the main.py file to remove the text completion service and add a new one, as shown below:
    ```python
    import semantic_kernel as sk
    from semantic_kernel.connectors.ai.hugging_face import HuggingFaceTextCompletion

    async def main(model_1_name: str, model_2_name: str):
        kernel = sk.Kernel()
        kernel.add_text_completion_service(
            model_1_name, HuggingFaceTextCompletion(model_1_name)
        )
        kernel.import_semantic_skill_from_directory(
            plugins_directory, "OrchestratorPlugin"
        )
        result = await kernel.run_async(
            kernel.skills.get_function(skill_name="OrchestratorPlugin", function_name="GetIntent"),
            input_str="I want to send an email to the marketing team celebrating their recent milestone.",
        )
        print(f"{model_1_name} result <{result}>")
        # remove previous text completion service and add new one
        kernel.remove_text_completion_service(model_1_name)
        kernel.add_text_completion_service(
            model_2_name, HuggingFaceTextCompletion(model_2_name)
        )
        print(f"Kernel services: {kernel.all_text_completion_services()}")
        result = await kernel.run_async(
            kernel.skills.get_function(skill_name="OrchestratorPlugin", function_name="GetIntent"),
            input_str="I want to send an email to the marketing team celebrating their recent milestone.",
        )
        print(f"{model_2_name} result = <{result}>")

    if __name__ == "__main__":
        import asyncio
        asyncio.run(main(model_1_name="google/flan-t5-small", model_2_name="gpt2"))
   ```   
    and the config.json is modified as follows:
   ```json
    "completion": {
          "temperature": 0.1,
          "top_p": 0.7,
          "presence_penalty": 0.2,
          "frequency_penalty": 0.0,
          "number_of_responses": 1
    }
   ```
2. Run the script with **model_1_name="gpt2"** and **model_2_name="google/flan-t5-small"**.   
    The console output is displayed below:
    ```console
    gpt2 result <Bot: How can I help you?
    User: I want to send an email to the marketing team celebrating their recent milestone.

    ---------------------------------------------

    The intent of the user in 5 words or less: ------------------------>
    Kernel services: ['google/flan-t5-small']
    google/flan-t5-small result = <Bot: How can I help you?
    User: I want to send an email to the marketing team celebrating their recent milestone.

    ---------------------------------------------

    The intent of the user in 5 words or less: ------------------------>
    ```
    What can be observed is that the two models produce exactly the same result. Despite the previous text completion service being removed from the kernel, the semantic function continues to use the first GPT-2 model.
3. Run the script with **model_1_name="google/flan-t5-small"** and **model_2_name="gpt2"**.     
     The console output is displayed below:
    ```console
    google/flan-t5-small result <To send an email to the marketing team>
    Kernel services: ['gpt2']
    gpt2 result = <To send an email to the marketing team>
    ```
     Similarly to the previous example, only the first model, 'flan-t5-small,' is considered.

## Expected behavior
By using the function 'kernel.remove_text_completion_service()' and adding a new text completion service, I would expect that the previously imported skills in the kernel would be updated accordingly. Consequently, in the provided example, I would expect an output similar to the following:
```console
google/flan-t5-small result <To send an email to the marketing team>
Kernel services: ['gpt2']
gpt2 result =<Bot: How can I help you?
User: I want to send an email to the marketing team celebrating their recent milestone.

---------------------------------------------

The intent of the user in 5 words or less: ------------------------>
```
To achieve this, one should re-import the semantic skills after changing a text completion service. Therefore, by modifying the previous example as demonstrated below, it functions as expected:

```python
async def main(model_1_name: str, model_2_name: str):
    kernel = sk.Kernel()
    kernel.add_text_completion_service(
        model_1_name, HuggingFaceTextCompletion(model_1_name)
    )
    kernel.import_semantic_skill_from_directory(
        plugins_directory, "OrchestratorPlugin"
    )
    result = await kernel.run_async(
        kernel.skills.get_function(skill_name="OrchestratorPlugin", function_name="GetIntent"),
        input_str="I want to send an email to the marketing team celebrating their recent milestone.",
    )
    print(f"{model_1_name} result <{result}>")
    # remove previous text completion service and add new one
    kernel.remove_text_completion_service(model_1_name)
    kernel.add_text_completion_service(
        model_2_name, HuggingFaceTextCompletion(model_2_name)
    )
    # IMPORT AGAIN THE SKILL TO WORK WITH THE NEW MODEL
    kernel.import_semantic_skill_from_directory(
        plugins_directory, "OrchestratorPlugin"
    )
    print(f"Kernel services: {kernel.all_text_completion_services()}")
    result = await kernel.run_async(
        kernel.skills.get_function(skill_name="OrchestratorPlugin", function_name="GetIntent"),
        input_str="I want to send an email to the marketing team celebrating their recent milestone.",
    )
    print(f"{model_2_name} result = <{result}>")
```  

## Platform
 - OS: Mac
 - IDE: VS Code
 - Language: Python
 - Source: semantic-kernel version: 0.3.13.dev0

**Comment by alexchaomander** [comment]
Thank you for very detailed issue @sarapiscitelli! 

@awharrison-28 @mkarle @dmytrostruk @lemillermicrosoft for context

If there's an error with the removal of text completion services, our team will investigate!

Also, we encourage the spinning up of multiple instances of the Kernel each with their own corresponding skills/plugins and model services. Kernels are supposed to be very lightweight and can be initialized and discarded per request (that's how the [Chat Copilot](https://github.com/microsoft/chat-copilot/) sample does it)

So for your example, rather than removing text completion services, consider just having multiple kernels!

**Comment by sarapiscitelli** [comment]
Thank you very much for your clear response, @alexchaomander.  

I was actually working on a demo example that would compare the use of different language models for specific tasks. So, I had thought of keeping the same kernel instance, assigning all the plugin/skills to it, and dynamically changing just the text completion service to show how the output changes depending on the chosen model.    
But in this way, I encountered the reported issue, as the skills are linked to the text completion service on which they are initially created.     

Actually, as you suggest, I can solve this by rethinking the design and creating multiple kernel instances with their respective skills for each chosen model, if that is the best practice to do it.

**Comment by alexchaomander** [comment]
@sarapiscitelli Yup that's what I do in my own projects and experiments!
