### ISSUE TITLE
Allow to pass the model/deployment name through config.json for functions

### ISSUE THREAD

**Issue by sandeepvootoori** [microsoft/semantic-kernel#3034]
Please allow passing of model/deployment name through config.json of the skills. The reason for this is it will make it easy for development and make it easy to use different models based on needs of a function. If the model is not present in the config, kernel should execute the function using kernel model instance.

**Comment by sandeepvootoori** [comment]
This will also probably be very helpful for people who want to use  GPT 4 for planner and use GPT 3.5 for functions. They can just instantiate the kernel with GPT 4 and setup all functions with 3.5

**Comment by matthewbolanos** [comment]
Looping in @markwallace-microsoft who is looking at this now :)

**Comment by markwallace-microsoft** [comment]
This work is being tracked via this issue: https://github.com/microsoft/semantic-kernel/issues/3041

I've added this issue as a related issue so will close this now.
