### ISSUE TITLE
Python: Cannot connect to remote Chroma DB

### ISSUE THREAD

**Issue by snelson3** [microsoft/semantic-kernel#3046]
**Describe the bug**
The ChromaMemoryStore class uses an outdated method of connecting to a remote chroma DB, which does not work with any recently released version of ChromaDB

**To Reproduce**
Run the following Python code with the most current versions of semantic_kernel and chromadb that are available on pypi
```
from semantic_kernel.connectors.memory.chroma import ChromaMemoryStore
from chromadb.config import Settings
mem = ChromaMemoryStore(client_settings=Settings(chroma_api_impl="rest", chroma_server_host="xxx.xxx.xxx.xxx", chroma_server_http_port="8000"))
```

See the following error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Settings' is not defined
>>> from chromadb.config import Settings
>>> mem = ChromaMemoryStore(client_settings=Settings(chroma_api_impl="rest", chroma_server_host="xxx.xxx.xxx.xxx", chroma_server_http_port="8000"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/snelson3/opt/anaconda3/lib/python3.9/site-packages/semantic_kernel/connectors/memory/chroma/chroma_memory_store.py", line 73, in __init__
    self._client = chromadb.Client(self._client_settings)
  File "/Users/snelson3/opt/anaconda3/lib/python3.9/site-packages/chromadb/__init__.py", line 143, in Client
    api = system.instance(API)
  File "/Users/snelson3/opt/anaconda3/lib/python3.9/site-packages/chromadb/config.py", line 259, in instance
    fqn = self.settings.require(key)
  File "/Users/snelson3/opt/anaconda3/lib/python3.9/site-packages/chromadb/config.py", line 171, in require
    val = self[key]
  File "/Users/snelson3/opt/anaconda3/lib/python3.9/site-packages/chromadb/config.py", line 180, in __getitem__
    raise ValueError(LEGACY_ERROR)
ValueError: You are using a deprecated configuration of Chroma.

If you do not have data you wish to migrate, you only need to change how you construct
your Chroma client. Please see the "New Clients" section of https://docs.trychroma.com/migration.
________________________________________________________________________________________________

If you do have data you wish to migrate, we have a migration tool you can use in order to
migrate your data to the new Chroma architecture.
Please `pip install chroma-migrate` and run `chroma-migrate` to migrate your data and then
change how you construct your Chroma client.

See https://docs.trychroma.com/migration for more information or join our discord at https://discord.gg/8g5FESbj for help!

**Expected behavior**
The connection to work

**Platform**
 - OS: Mac
 - IDE: NA
 - Language: Python
 - Source: pip package version semantic_kernel-0.3.13.dev0

**Additional context**
It looks like [this](https://github.com/microsoft/semantic-kernel/issues/2050) PR may have been supposed to solve this issue? But it was closed in July and I still see the issue present in the master branch and the most recent Pypi release.

**Comment by GaiusRed** [comment]
As a workaround, you can set the `chroma_api_impl` setting to "chromadb.api.fastapi.FastAPI"

```
from semantic_kernel.connectors.memory.chroma import ChromaMemoryStore
from chromadb.config import Settings
mem = ChromaMemoryStore(client_settings=Settings(chroma_api_impl="chromadb.api.fastapi.FastAPI", chroma_server_host="xxx.xxx.xxx.xxx", chroma_server_http_port="8000"))
```

**Comment by moonbox3** [comment]
Closing this issue as the related PR has been closed. If you continue to have problems, please re-open a new GitHub issue, thanks.
