### ISSUE TITLE
Java: Extend CognitiveSearchMemoryStore with custom MemoryRecord Mapper

### ISSUE THREAD

**Issue by dantelmomsft** [microsoft/semantic-kernel#3060]
- MemoryRecord mapping logic in AzureCognitiveSearchMemoryStore.getNearestMatchesAsync method can't be extended. Cognitive Search field names are hardcoded in [AzureCognitiveSearchMemoryRecord](https://github.com/microsoft/semantic-kernel/blob/experimental-java/java/connectors/semantickernel-connectors-memory-azurecognitivesearch/src/main/java/com/microsoft/semantickernel/connectors/memory/azurecognitivesearch/AzureCognitiveSearchMemoryRecord.java).

- I would suggest to provide an extensibility mechanism for custom cognitive search index field mapping while still preserving the MemoryRecord contract. An idea could be to add an overloaded getNearestMatchesAsync method which accepts a mapper function parameter like this: Function<SearchDocument,MemoryRecord> memoryRecordMapper. An example how you could implement it's [here](https://github.com/Azure-Samples/azure-search-openai-demo-java/blob/9c78923ada996d6d97736561334f62dfa906238d/app/backend/src/main/java/com/microsoft/openai/samples/rag/ask/approaches/semantickernel/memory/CustomAzureCognitiveSearchMemoryStore.java#L72)... and you can use it (+/-) like [this](https://github.com/Azure-Samples/azure-search-openai-demo-java/blob/9c78923ada996d6d97736561334f62dfa906238d/app/backend/src/main/java/com/microsoft/openai/samples/rag/ask/approaches/semantickernel/JavaSemanticKernelWithMemoryApproach.java#L118)

- This can be useful in scenario where you don't have full control (different teams, different implementations) of both vector store indexing and vector similarity search processes (which is my use case ).

**Comment by johnoliver** [comment]
Fix merged, will go out in the next release
