### ISSUE TITLE
.Net: C# TextChunker customizability

### ISSUE THREAD

**Issue by rnortje-sygnia** [microsoft/semantic-kernel#3076]
The current TextChunker uses the following hardcoded separators to split lines.  Defined as:

private static readonly string?[] s_plaintextSplitOptions = new[] { "\n\r", ".", "?!", ";", ":", ",", ")]}", " ", "-", null };
private static readonly string?[] s_markdownSplitOptions = new[] { ".", "?!", ";", ":", ",", ")]}", " ", "-", "\n\r", null };

The public methods does not allow one to specify your own separators. The above is problematic for instances like ours where the decimal point in numbers is a ".". Therefore given text like "The return of X is 0.5%" the chunker will see "The return of X is 0." as a line.  This causes some paragraphs to cut off at critical points. Though this can be solved to an extend by overlaps, we have various instances where this causes vectors on content to cut off like this. 

Is it possible that public functions be made available where these can be specified by the caller. What would be nice is if they remain strings and not char. we can then specify ". ". i.e a full stop followed by a space as a valid sentence breakpoint. This will make the TextChunker much more usable. It would also be nice if this can be specified as part of the runtime configuration settings.

**Comment by alliscode** [comment]
Hi @rnortje-sygnia thanks for submitting this. Would you be interested in submitting a PR to fix this issue?

**Comment by rnortje-sygnia** [comment]
Would love to but do not have the capacity to do this at this stage, at least not in a reasonable timeframe.

**Comment by matthewbolanos** [comment]
We'll be removing the text chunker from v1.0.0 of Semantic Kernel, so I'm closing this issue.

**Comment by matthewbolanos** [comment]
I may have spoken too soon! We're reopening this issue and hoping to find a new home for the TextChunker. In the meantime, we'll be marking as experimental.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
