### ISSUE TITLE
.Net: Add overloads for Polly v8 ResiliencePipeline

### ISSUE THREAD

**Issue by anthonypuppo** [microsoft/semantic-kernel#3079]
Polly v8 was [officially released](https://www.thepollyproject.org/2023/09/28/polly-v8-officially-released/) with an associated [migration guide](https://www.pollydocs.org/migration-v8.html). The `Reliability.Polly` project should be updated to support the newly released `ResiliencePipeline`.

**Comment by stephentoub** [comment]
The reliability support in SK has been replaced by relying on standard DI mechanisms, eg you can now use Microsoft.Extensions.Http.Resilience with SK, and it supports the latest versions of polly.
