### ISSUE TITLE
.Net: Transition to Polly.Core

### ISSUE THREAD

**Issue by anthonypuppo** [microsoft/semantic-kernel#3081]
Needs to be done after #3079.

The `Polly` package supports both v7 and v8 API's. The new `Polly.Core` package only supports v8 and is recommended for new projects (see [getting started](https://www.pollydocs.org/getting-started.html) and [migration guide](https://www.pollydocs.org/migration-v8.html)).

**Comment by stephentoub** [comment]
The reliability support in SK has been replaced by relying on standard DI mechanisms, eg you can now use Microsoft.Extensions.Http.Resilience with SK, and it supports the latest versions of polly.
