### ISSUE TITLE
python: prompt_template_config need change

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#309]
**Describe the bug**
use `import_semantic_skill_from_directory(kernel, skill_dir, skill)` function and if its config has no stop_sequence in it,
will raise error if its skill is really used by kernel.

![image](https://user-images.githubusercontent.com/69464062/229849278-d46a6286-764c-4684-be9c-99682eef5ff4.png)

I'll open PR, and this bug only need one line changed. see you at PR

**To Reproduce**
use `import_semantic_skill_from_directory(kernel, skill_dir, skill)`
and use skill with it.

**Expected behavior**
even though user didn't provide stop_sequence in config.json, it should be run anyway

**Screenshots**
check screenshot above

**Desktop (please complete the following information):**
 - OS: Mac M1
 - IDE: VS code
 - python 3.11

**Additional context**

**Comment by jjhenkel** [comment]
Thanks for this! I think I just ran into the same thing (and have a separate fix for it, but we should fix it in both places): [see this PR](https://github.com/microsoft/semantic-kernel/pull/317).

**Comment by jjhenkel** [comment]
@alexchaomander I think we can close this now, our fix was merged earlier and now @joowon-dm-snu's fix is merged as well. (Doubly fixed!)
