### ISSUE TITLE
Support for AWS BedRock

### ISSUE THREAD

**Issue by VenkateshSrini** [microsoft/semantic-kernel#3094]
I would like to know how to add AWS Bedrock support to Semantic kernel

**Comment by dmytrostruk** [comment]
Hi @VenkateshSrini !
We have an example how to add your own implementation of AI Connector here:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example16_CustomLLM.cs

We also have a couple of implemented AI Connectors, which you can use as a reference:
https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.AI.HuggingFace
https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.AI.Oobabooga
https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.AI.OpenAI

One note: at the moment we are not adding new Connectors to this repository. We encourage to create separate repositories for SK Connectors and share it with us - so we will be able to add it to our README file as a reference. 

Please let me know if you have any other questions. Thanks a lot!

**Comment by VenkateshSrini** [comment]
Can you give me some links on step by step process to create connectors please @dmytrostruk ?

**Comment by dmytrostruk** [comment]
@VenkateshSrini I'm not sure if we have a step-by-step guideline how to create Connectors. I would be happy to provide answers if you have some specific questions.

If you are interested in implementing C# Connector, then you will have to create your C# class and implement `ITextCompletion` interface, which is mandatory to be able to inject your connector in Kernel. In case AI provider supports Chat API, then your class can also implement `IChatCompletion` interface.

C# implementation example:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.AI.OpenAI/ChatCompletion/AzureChatCompletion.cs

If you want to implement AI Connector in SK Python version, you will need to create Python class, which inherits from `ChatCompletionClientBase, TextCompletionClientBase` base classes.

Python implementation example:
https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion.py

As mentioned in previous comment, we encourage to create new Connectors in your own repositories and share link with us - so we will be able to share your link in our README file as useful reference.

Please let me know if this information is helpful. Thank you!

**Comment by VenkateshSrini** [comment]
Thank you

**Comment by stekiri** [comment]
@dmytrostruk, did I understand correctly that there exists a README file listing connectors from 3rd party repositories? I didn't find it, but maybe I didn't search long enough 😅
