### ISSUE TITLE
Python: get_async() method in SemanticTextMemory lacks the required 'with_embedding' argument when using the MemoryStoreBase get_async() method

### ISSUE THREAD

**Issue by sarapiscitelli** [microsoft/semantic-kernel#3097]
## Bug
When calling the `get_async()` method from an instance of the `SemanticTextMemory` class, there is a missing required positional argument: `with_embedding`.  This problem arises because the `SemanticTextMemory` class relies on an instance of the `MemoryStoreBase` class, which in itself requires the `with_embedding` parameter.

Below is the error shown in the console output:
```console
Traceback (most recent call last):
  File "..lib/python3.10/site-packages/semantic_kernel/memory/semantic_text_memory.py", line 126, in get_async
    record = await self._storage.get_async(collection_name=collection, key=key)
TypeError: ChromaMemoryStore.get_async() missing 1 required positional argument: 'with_embedding'
```

## To Reproduce
Run the following code:
```python
import asyncio
import semantic_kernel as sk
import semantic_kernel.connectors.ai.hugging_face as sk_hf

from semantic_kernel.connectors.memory.chroma import ChromaMemoryStore

async def main():
    kernel = sk.Kernel()
    # add text embedding service
    kernel.add_text_embedding_generation_service("sentence-transformers/all-MiniLM-L6-v2",
                                                 sk_hf.HuggingFaceTextEmbedding("sentence-transformers/all-MiniLM-L6-v2"))
    
    kernel.register_memory_store(memory_store=ChromaMemoryStore())
    await kernel.memory.save_information_async(collection="collection_test", id="test_id", text="test")
    res = await kernel.memory.get_async("collection_test", "test_id")
    # To avoid raising an error, replace the line above with the following line.
    # res = await kernel.memory._storage.get_async("collection_test", "test_id", with_embedding=False)
    print(res)

if __name__ == "__main__":
    asyncio.run(main())
```
If you use the with_embedding parameter as shown below:
```python
res = await kernel.memory.get_async("collection_test", "test_id", with_embedding=False)
```
You will encounter the following error:
```console
res = await kernel.memory.get_async("collection_test", "test_id", with_embedding=False)
TypeError: SemanticTextMemory.get_async() got an unexpected keyword argument 'with_embedding'
```
Currently, to avoid this error, I have directly called the get_async() method using the _storage instance of the SemanticTextMemoryBase class (`res = await kernel.memory._storage.get_async("collection_test", "test_id", with_embedding=False)`). However, I don't believe it is secure to call the method directly from the private `_storage` instance.

### Additional Context 
Looking at the definitions of the Python classes: [SemanticTextMemory](https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/memory/semantic_text_memory.py) and [MemoryStoreBase](https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/memory/memory_store_base.py), it can be observed that the function SemanticTextMemory.get_async() calls the method MemoryStoreBase.get_async() without providing the required argument `with_embedding`.   
Below, the definitions of the Python classes used in semantic kernel:
```python

class SemanticTextMemory(SemanticTextMemoryBase):
    _storage: MemoryStoreBase

    async def get_async(
        self,
        collection: str,
        key: str,
    ) -> Optional[MemoryQueryResult]:
        
        record = await self._storage.get_async(collection_name=collection, key=key)


class MemoryStoreBase(ABC):
    @abstractmethod
    async def get_async(
        self, collection_name: str, key: str, with_embedding: bool
    ) -> MemoryRecord:
    ...

class ChromaMemoryStore(MemoryStoreBase):
    async def get_async(
            self, collection_name: str, key: str, with_embedding: bool
        ) -> MemoryRecord:
    ...
```   
I believe there might be a straightforward error in the definition of interfaces.  I'm not sure if you are already working on it, as I couldn't find any open issues.       
However, currently, all the memory connector classes within 'semantic_kernel.connectors.memory' are causing this error.

**Platform**
 - OS: Mac
 - IDE: VS Code
 - Language: Python
 - Source: main branch of repository (semantic-kernel-0.3.13.dev0)

**Comment by moonbox3** [comment]
We're removing the kernel's tie to one memory store as of #5143. Plugins can now contain multiple "memories." This should be fixed once that PR goes in.
