### ISSUE TITLE
Support MAC M2 distribution

### ISSUE THREAD

**Issue by mavilleg** [microsoft/semantic-kernel#3108]
Support of dev container and semantic kernel for M1/M2 users. 

Thanks

**Comment by matthewbolanos** [comment]
@mavilleg, are you able to share which existing dev container you would like support for with M1/M2 users?

**Comment by mavilleg** [comment]
All, basically any sample from semantic kernel are not running by default on new ship from Apple because its await a different processor, same think for the dev containers that are based images that does not run on Macc. For testing/validating the approach from macc user it's a bit hard as you have to build your own application from starts without having the ability to comprehend the different concepts from those samples.

**Comment by matthewbolanos** [comment]
Thanks for letting me know, I'll try experimenting myself with my M1 Macbook and get back to you.

**Comment by matthewbolanos** [comment]
Was not able to repro on my M1 Macbook
