### ISSUE TITLE
Python: Need to resolve the conflict between device and device_map parameters in huggingface/pipelines.

### ISSUE THREAD

**Issue by sangyeop-kim** [microsoft/semantic-kernel#3110]
```python
import semantic_kernel.connectors.ai.hugging_face as sk_hf

chat = sk_hf.HuggingFaceTextCompletion(
    "NousResearch/Llama-2-7b-chat-hf", pipeline_kwargs=dict(device_map='auto')
)
```

To load a large-size model from Hugging Face, as stated above, we need to use the device_map parameter in transformers/pipelines.

In pipelines, it is explicitly stated, "Do not use `device_map` AND `device` at the same time as they will conflict." 

Thus, when using device_map, we must set the device value to None.

Currently, in the hf_text_completion.py file, there is no handling for None, as it just converts device parameter to a string  This section of the code seems to need modification to address this issue.

[link](https://github.com/microsoft/semantic-kernel/blob/dd70084999298a7196c0a5fd70377168aff8ec54/python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_completion.py#L67)
```python
self.device = (
            "cuda:" + str(device)
            if device >= 0 and torch.cuda.is_available()
            else "cpu"
        )
```

I think we just need to add something like  "if self.device is not None:"

**Comment by matthewbolanos** [comment]
@sangyeop-kim, would you be interested in creating a PR for the fix you described?
