### ISSUE TITLE
.Net: Powershell Planner

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3112]

**Comment by matthewbolanos** [comment]
@dmytrostruk, perhaps we make this a sample

**Comment by dmytrostruk** [comment]
FYI
Feature branch: https://github.com/microsoft/semantic-kernel/tree/feature-powershell-planning
PR: https://github.com/microsoft/semantic-kernel/pull/2702

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
