### ISSUE TITLE
Python: HTTP Post to Azure Function '.../planner/execute' results in "TypeError: __init__() got an unexpected keyword argument 'goal'"

### ISSUE THREAD

**Issue by nDimension** [microsoft/semantic-kernel#3123]
**Describe the bug**
HTTP Post to Azure Function '.../planner/execute' results in "TypeError: __init__() got an unexpected keyword argument 'goal'"

**To Reproduce**
1. Deploy the SK Python kernel_http_server sample to an Azure Function
2. HTTP post to '...api/planner/createplan' returns plan json as expected.
3. HTTP post to '/planner/execute/{maxsteps}' endpoint with the json 'state' response 
4. See error "HTTP Post to Azure Function '.../planner/execute' results in "TypeError: __init__() got an unexpected keyword argument 'goal'"

**Expected behavior**
The Azure Function should return the results of the plan. 

**Platform**
 - OS: [Windows]
 - IDE: [ VS Code]
 - Language: [Python]
 - Source: [samples -> python -> kernel_http_server]

**Additional context**
I believe this could be because the __init__  method signature  of the 'Plan' class in plan.py does not contain a 'goal' parameter, whereas in kernel_server.py, plan is instantiated with a goal keyword. 

I apologize in advance if this report is clunky or incorrect in some other way, as this is my first github bug report.

**Comment by AdarshAcharya5** [comment]
https://github.com/microsoft/semantic-kernel/blob/bdc517d0f80e0f0896a8f1fc01d4327848c74937/samples/python/kernel_http_server/utils/kernel_server.py#L147C9-L147C14
The problem seems to be here, the arguments don't match the updated structure Plan object in plan.py.

**Comment by matthewbolanos** [comment]
We're currently in the process of deprecating this sample, so I will go ahead and close this issue.
