### ISSUE TITLE
.Net: PasswordString to string type error

### ISSUE THREAD

**Issue by rajeshradhakrishnanmvk** [microsoft/semantic-kernel#3124]
**Describe the bug**
While using openai, getting an error in "0-AI-settings.ipynb notebook. NOTE: if the settings.json already exists

Error: (95,26): error CS0029: Cannot implicitly convert type 'Microsoft.DotNet.Interactive.PasswordString' to 'string'
(100,26): error CS0029: Cannot implicitly convert type 'Microsoft.DotNet.Interactive.PasswordString' to 'string'

**To Reproduce**
1. Go to '0-AI-settings.ipynb'
2. Create the settings.json file in ./config folder
3. Click on 'Run Step 1 & Step 2'
4. Scroll down to '....'
5. See error

Error: (95,26): error CS0029: Cannot implicitly convert type 'Microsoft.DotNet.Interactive.PasswordString' to 'string'
(100,26): error CS0029: Cannot implicitly convert type 'Microsoft.DotNet.Interactive.PasswordString' to 'string'
Error: (1,7): error CS0103: The name 'Settings' does not exist in the current context
(2,7): error CS0103: The name 'Settings' does not exist in the current context
(3,7): error CS0103: The name 'Settings' does not exist in the current context
(6,8): error CS0103: The name 'Settings' does not exist in the current context

**Expected behavior**
 no errors

**Screenshots**
not applicabale

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C# ployglot notebook
 - Source:  https://github.com/microsoft/semantic-kernel.git
**Additional context**
Error: (95,26): error CS0029: Cannot implicitly convert type 'Microsoft.DotNet.Interactive.PasswordString' to 'string'
(100,26): error CS0029: Cannot implicitly convert type 'Microsoft.DotNet.Interactive.PasswordString' to 'string'

**Comment by dmytrostruk** [comment]
@rajeshradhakrishnanmvk Thanks for reporting, the work is in progress and fix will be available soon.
