### ISSUE TITLE
.Net: nodebook sample for 1.0.0-beta

### ISSUE THREAD

**Issue by kenakamu** [microsoft/semantic-kernel#3125]
Please add notebook samples for dotnet 1.0.0-beta. That still using the preview and there are several code doesn't work as it is.

**Comment by dmytrostruk** [comment]
@kenakamu Thanks for reporting. All notebook samples for dotnet 1.0.0-beta will be updated today.

**Comment by dmytrostruk** [comment]
@kenakamu Meanwhile, you can check our syntax examples, they are aligned with new version `1.0.0-beta1`:
https://github.com/microsoft/semantic-kernel/tree/main/dotnet/samples/KernelSyntaxExamples
