### ISSUE TITLE
.Net: Move plan stepping logic to Kernel.RunAsync

### ISSUE THREAD

**Issue by madsbolaris** [microsoft/semantic-kernel#3144]
> [!IMPORTANT]  
> Labeled **High** because it will not require a breaking change, but it's very important to complete by v1.0.0

**Comment by Alerinos** [comment]
RunAsync returns a new type, previously I could use Result. Now there is no documentation on how I can receive the data. Can I ask for help?
My Code:
```cs
        var mySummarizeFunction = kernel.CreateSemanticFunction(prompt); //maxTokens: 8000
        var myOutput = await kernel.RunAsync(context, mySummarizeFunction);
        var output1 = JsonSerializer.Deserialize<Output1>(myOutput.Result);
```

**Comment by RogerBarreto** [comment]
@matthewbolanos Was looking quickly at this one, and seems that we are moving away from this approach as the Kernel as a bag will only execute one function at a time and any pipelining will still be responsibility of a plan or a advanced prompt template engine like handlebars.

**Comment by RogerBarreto** [comment]
Dropping this as we changed the cope of running pipelines from kernel
