### ISSUE TITLE
.Net: Revisit namespaces and type placement

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#3151]
> [!IMPORTANT]  
> Labeled **Urgent** because it may require a breaking change.

(Metapoint: Try rewriting all the examples without using `var` and seeing how many namespaces need to be imported to successfully compile.)

- [x] (1)
To do anything meaningful with memory now I need both:
```C#
using Microsoft.SemanticKernel.Memory; // for ISemanticTextMemory, unless I rely exclusively on var
using Microsoft.SemanticKernel.Plugins.Memory; // for MemoryBuilder and friends
```
plus a using for whatever store I'm using it if it's not the VolatileMemoryStore, e.g.
```C#
using Microsoft.SemanticKernel.Connectors.Memory.AzureCognitiveSearch;
```
That's three `using`s just to create an `ISemanticTextMemory`.  Can these be consolidated?

- [x] (2)
To do anything meaningful with planning, I now need both:
```C#
using Microsoft.SemanticKernel.Planners; // for the actual planner
using Microsoft.SemanticKernel.Planning; // for Plan
```
The difference between "Planners" and "Planning" is also very subtle.  Can these be consolidated?

- [x] (3)
It looks like Microsoft.SemanticKernel.Diagnostics exists now just for `SKException`, `HttpOperationException`, and `Telemetry`.  Do we need this namespace at all?  Can we move these types somewhere else, like moving `SKException` to the root `Microsoft.SemanticKernel` namespace?

- [x] (4)
Similarly, can we consolidate Microsoft.SemanticKernel.Events with something else? "Events" is pretty broad; the types here are specific to pre/post hooks with plan execution, right?

- [ ] (5) 
Why do we need Microsoft.SemanticKernel.Plugins.Core? Can't those just move down into Plugins?

- [x] (6)
We should also move "extensions" types to the namespace with the types they extend. For example, it looks like ImageGenerationServiceExtensions, TextEmbeddingServiceExtensions, TextCompletionServiceExtensions, only have extension methods and those only apply to `IAIService` in Microsoft.SemanticKernel.Services... can they move there?  And can they be consolidated into an AIServicesExtensions class?  And `OpenAIModelResultExtensions` has methods that operate only on `Microsoft.SemanticKernel.Orchestration.ModelResult`... can it move there?

- [x] (7)
What is MemoryConfiguration and why does it live in the root namespace?

- [x] (8)
The main thing I do with an `IKernel` (which lives in the root namespace) is `InvokeAsync` on it, and to get a useful result from it, I need to access its `KernelResult`, which now lives in `Microsoft.SemanticKernel.Orchestration`.  I suggest at least `KernelResult` and `FunctionResult` move to be next to `IKernel` and `ISKFunction` in the root namespace.  And at that point, the `Orchestration` namespace contains very little and should likely be consolidated with something else.

- [x] (9)
Microsoft.SemanticKernel.TemplateEngine contains just a single type (`IPromptTemplateEngine`) and then a sub `Basic` namespace. Can everything in `Basic` just move up?

- [x] (10)
`Microsoft.SemanticKernel.Reliability` appears to solely be about HTTP and retries. Why is this separate from `Microsoft.SemanticKernel.Http`?  Can we consolidate them?

- [x] (11)
https://github.com/microsoft/semantic-kernel/issues/3173

**Comment by dmytrostruk** [comment]
@stephentoub Thanks for very useful feedback!

(1) `Microsoft.SemanticKernel.Memory` and `Microsoft.SemanticKernel.Plugins.Memory` - this is just transient phase, while we marked Memory related methods and properties in Kernel as `Obsolete`. In next versions, all memory-related functionality will be placed in `Plugins.Memory` package and use one root namespace `Microsoft.SemanticKernel.Plugins.Memory`.

Regarding Memory Stores (`Microsoft.SemanticKernel.Connectors.Memory.AzureCognitiveSearch`) - they are placed in their own packages, so namespace is based on `Microsoft.SemanticKernel` + folder path of concrete Memory store. We either have to place all of them under one package or use the same namespace for all of them (does it respect namespace naming conventions?). Which way is better here?

(2-5) I think these can be fixed.

(6) 
> We should also move "extensions" types to the namespace with the types they extend.

In case of `OpenAIModelResultExtensions` - it contains extension methods for `Microsoft.SemanticKernel.Orchestration.ModelResult`, but the logic of these methods is applicable only to OpenAI-related functionality. In this case shouldn't it be placed under `Microsoft.SemanticKernel.Connectors.AI.OpenAI` namespace? (to align namespace with actual class location).

(7) `MemoryConfiguration` will be removed in future versions when we remove Memory-related functionality from Kernel. I marked its methods as `Obsolete`, but I should probably also mark as `Obsolete` the class itself.

(8-11) I think these can be fixed.

**Comment by matthewbolanos** [comment]
Will need some additional feedback from Stephen so we can split this into multiple issues and provide a better estimate.

**Comment by stephentoub** [comment]
> Regarding Memory Stores (Microsoft.SemanticKernel.Connectors.Memory.AzureCognitiveSearch) - they are placed in their own packages, so namespace is based on Microsoft.SemanticKernel + folder path of concrete Memory store. We either have to place all of them under one package or use the same namespace for all of them (does it respect namespace naming conventions?). Which way is better here?

I certainly wouldn't say they all need to be in the same package; that's both limiting and infeasible for something that's meant to have external plug-ins all playing in the same design. If we believe conflicts in naming of types between plug-ins is going to happen, then they should be in their own namespaces, though my expectation was that it would be rare to have such conflicts and we'd actively encourage folks to use a prefix on their type names, e.g. it'd be `Microsoft.SemanticKernel.Connectors.Memory.AzureCognitiveSearchMemoryStore` rather than `Microsoft.SemanticKernel.Connectors.Memory.AzureCognitiveSearch.MemoryStore`, at which point there shouldn't be conflicts. 

That said, my comment was more concerned about consolidating from 3 down to 2 rather than from 3 down to 1, and from your comments it sounds like that's already in the works, which is good.

> In case of OpenAIModelResultExtensions - it contains extension methods for Microsoft.SemanticKernel.Orchestration.ModelResult, but the logic of these methods is applicable only to OpenAI-related functionality. In this case shouldn't it be placed under Microsoft.SemanticKernel.Connectors.AI.OpenAI namespace? (to align namespace with actual class location).

Yes, you're right, it makes sense to have the extension types in the namespace with which they're most closely aligned.

**Comment by dmytrostruk** [comment]
> that will also mean that if you haven't otherwise imported that namespace, you may not see them in IntelliSense in VS while exploring and seeing what you can add

Regarding this, looks like IntelliSense will show you which extension methods from different namespaces are available:
![image](https://github.com/microsoft/semantic-kernel/assets/13853051/0d6deee3-4fd1-44b8-8ace-55463448ab22)

**Comment by stephentoub** [comment]
> > that will also mean that if you haven't otherwise imported that namespace, you may not see them in IntelliSense in VS while exploring and seeing what you can add
> 
> Regarding this, looks like IntelliSense will show you which extension methods from different namespaces are available

If you have this enabled:
<img width="448" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/2642209/9ceeb123-7962-4803-b683-76fb2a22acd3">

Note, though, that the option also has some issues: note that some of those extensions aren't actually applicable to the thing you're dot'ing off of, which it will realize the moment you select the extension and it imports the namespace, at which point you'll get an error because the extension isn't actually valid.  So some folks turn this off.

I'm also not sure of the experience here in VS Code.

**Comment by dmytrostruk** [comment]
Yeah, that's interesting issue :)
I'm fine with both options, since they are better than keeping extension methods in root namespace.

**Comment by stephentoub** [comment]
> The "KernelBuilder" class is a builder, not a collection. Adding the "Add" methods to it would imply that it has collection capabilities, allowing it to register or have many instances of the same SK component types. This is the case for SK connectors but might not be the case for the other dependencies/components such as the logger factory, retry policy, and prompt template engine.

I think this just adds to the idea that the Kernel should not itself be a DI container.  We should either:
a) Have Kernel take a dependency on Microsoft.Extensions.DependencyInjection and have it simply wrap a ServiceCollection. Developers can populate a ServiceCollection however they like, including using AddXx extension we provide on ServiceCollection, which then let's them work both with or without Kernel, e.g. a developer can use AddAzureChatCompletion in their ASP.NET application to register the IChatCompletion they want to use throughout the app, and they don't need to think or know anything about Kernel.  Or
b) Remove the concept of services from Kernel entirely.
