### ISSUE TITLE
.Net: When running a plan with Kernel.RunAsync, the KernelResult.Metadata only contains information about the plan function.

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#3157]
**Describe the bug**
After running a plan that invokes plugins, the resulting KernelResult should contain metadata about the functions (plugins) called in the plan. Instead, it only contains metadata about the plan plugin.

**To Reproduce**
1. Register at least one plugin in the kernel.
2. Create a plan with a goal that will invoke the plugin.
3. Run the plan with `kernel.RunAsync(plan)`
4. Examine the KernelResult object returned from running the plan and notice that metadata is only present for 1 plugin which is the plan plugin.

**Expected behavior**
Metadata should exist for all of the plugins invoked in the plan execution.

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by matthewbolanos** [comment]
Closing this since KernelResult no longer exists.
