### ISSUE TITLE
.Net: Find a more permanent home for plugins/connectors that don't live in SK

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3162]
Need to create a strategy/examples that demonstrate how the community can create separate repos for plugins and connectors so that they don't need to live in the core Semantic Kernel repo.

**Comment by matthewbolanos** [comment]
Initial example of "external" connector can be Oobabooga.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
