### ISSUE TITLE
.Net: Can we remove Kernel.Builder?

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#3169]
The property is just defined as:
```C#
public static KernelBuilder Builder => new();
```

Two problems:
1) This creates two different ways to do the exact same thing: `Kernel.Builder` vs `new KernelBuilder()`.
2) Properties like this are generally expected to return singletons, which this is not nor can it be since it's mutable.

Can we just delete the static `Builder` property?

**Comment by markwallace-microsoft** [comment]
We should obsolete this to start with
