### ISSUE TITLE
.Net: Need to be able to "break glass" with AzureChatCompletion and friends

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#3182]
Abstractions are great, but they're invariably the lowest common denominator of the things they're abstracting / wrapping, and at some point you often need to "break glass" and get at functionality from the thing being wrapped (especially if new features are added to the underlying thing and not yet exposed through the wrapper).  Today, AzureChatCompletion and OpenAIChatCompletion don't make that possible as they don't expose the underlying OpenAIClient and model ID they're wrapping.  That means in a situation where you have an IChatCompletion and want to test whether it's an AzureChatCompletion and do something special in that case, you have no good way to get at that underlying information, and instead need to also pass around the OpenAIClient.

We should expose both the OpenAIClient and model ID used to construct the instance publicly on these types. The properties are already there (`Client` and `ModelId`), they're just private; we can make them public.  Then code that really needs them can do:
```C#
IChatCompletion completion = ...;
if (completion is AzureChatCompletion azureCompletion)
{
    Use(azureCompletion.Client, azureCompletion.ModelId);
}
```
Etc.

(There's an argument to be made that exposing these ties the implementation to using OpenAIClient, but it's already tied in that manner because it accepts it into the constructor. If we were really concerned, such that maybe in the future the completion object would only use an OpenAIClient if one were provided but otherwise would use a different mechanism, we could make the Client property nullable.)

**Comment by dmytrostruk** [comment]
> There's an argument to be made that exposing these ties the implementation to using OpenAIClient, but it's already tied in that manner because it accepts it into the constructor

My initial feedback for this was to avoid exposing `OpenAIClient` parameter through constructor. We could expose in constructor only plain properties, that are required (ModelId, Endpoint etc.), so in this case if Azure .NET SDK has breaking changes, it won't mean that SK has breaking changes as well, which is the case at the moment. I'm wondering if it makes sense or it's fine to expose models from libraries we depend on?


> We should expose both the OpenAIClient and model ID used to construct the instance publicly on these types.

How to recognize which parameters need to be publicly exposed, should it be the same properties which were passed through constructor? Does it mean that we also need to expose `Endpoint` and `ApiKey` properties for read-only purposes?

**Comment by stephentoub** [comment]
> Does it mean that we also need to expose Endpoint and ApiKey properties for read-only purposes?

Endpoint and ApiKey are used only as an alternative to passing in an OpenAIClient and are used to create the OpenAIClient, so exposing the OpenAIClient itself is sufficient.

> I'm wondering if it makes sense or it's fine to expose models from libraries we depend on?

There's some risk to exposing that dependency, but I think there's even more risk to not allowing access to the underlying implementation that's almost by definition going to evolve at a faster rate than the abstractions that wrap it (even if SK moves as fast as possible, it can't possibly adapt to additions to OpenAIClient before those additions on OpenAIClient ship). Given the speed at which this stuff is evolving, it seems pretty important to enable that flexibility.  But, it'd be worth sync'ing with the Azure SDK folks to understand what plans are around breaking changes in this area (regardless of it being exposed).

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
