### ISSUE TITLE
.Net: Does IKernel / Kernel need to store an IPromptTemplateEngine?

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#3191]
There are 0 calls to KernelBuilder.WithPromptTemplateEngine anywhere in the code base... including tests.

The only direct use of Kernel's ctor that accepts a prompt template engine is in a test that then completely ignores the constructed kernel.

Kernel itself does not use the PromptTemplateEngine (though its constructor apparently thinks it's so important it stores it into the same field twice).

PromptTemplate has a ctor `public PromptTemplate(string template, PromptTemplateConfig promptTemplateConfig, IKernel kernel)` that's used 0 times in the whole codebase, and all it does anyway is just delegate to the ctor that takes an IPromptTemplateEngine instead of an IKernel.

In the entire repo there are only 5 call sites that use `.PromptTemplateEngine`, 1 of which is the above ctor and 2 of which are tests of RegisterSemanticFunction. The remaining 2 uses are in the CreateSemanticFunction and ImportSemanticFunctionsFromDirectory extension methods, which take an IKernel but could easily accept an IPromptTemplateEngine as well.

What's the benefit of having this top-level in IKernel?  Why can't it be just another entry in the ServiceCollection?

I'm looking at IKernel from the perspective of trying to understand what it really is. And once you look past the cruft, it seems like it's really just:
- a holder for services, which is suspect: https://github.com/microsoft/semantic-kernel/issues/3151#issuecomment-1763229144
- a holder for functions, for which there's already a dedicated FunctionsCollection
- a method for invoking functions

and I'm wondering if maybe IKernel/Kernel as types should go away: code can just pass around a ServiceCollection and a FunctionCollection as needed, and have a static RunAsync method somewhere that's purely about the invocation.

**Comment by SergeyMenshykh** [comment]
That's exactly what I thought about all the time. Here's the same idea from our latest design review meting:
![image](https://github.com/microsoft/semantic-kernel/assets/68852919/5cc44db9-10d1-4040-a420-d2355d1f6ba4)
