### ISSUE TITLE
.Net: i can't run code in "get started c#"

### ISSUE THREAD

**Issue by L261173157** [microsoft/semantic-kernel#3193]
in [Get Started with Semantic Kernel](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/README.md#get-started-with-semantic-kernel-) ,I can't run the code of c#.
1. var summarize = kernel.CreateSemanticFunction(prompt, maxTokens: 100); in this line,CreateSemanticFunction method dont have parameter maxtokens.
2. Console.WriteLine(await summarize.InvokeAsync(text1)); in this line,InvokeAsync, no string parameter.

How can i do in this case?

**Comment by dmytrostruk** [comment]
@L261173157 Thanks for reporting. There were some syntax/API changes in recent versions of SK. We will update README file as soon as possible. 

Meanwhile, for testing and experimentation you can use our notebooks:
https://github.com/microsoft/semantic-kernel/tree/main/dotnet/notebooks

You can also follow our syntax examples here:
https://github.com/microsoft/semantic-kernel/tree/main/dotnet/samples/KernelSyntaxExamples

**Comment by L261173157** [comment]
> @L261173157 Thanks for reporting. There were some syntax/API changes in recent versions of SK. We will update README file as soon as possible.
> 
> Meanwhile, for testing and experimentation you can use our notebooks: https://github.com/microsoft/semantic-kernel/tree/main/dotnet/notebooks
> 
> You can also follow our syntax examples here: https://github.com/microsoft/semantic-kernel/tree/main/dotnet/samples/KernelSyntaxExamples

thank you for your replay，i will try it
