### ISSUE TITLE
.Net: How can IKernel possibly be implemented?

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#3195]
`IKernel` has a `CreateNewContext` method that's required to be implemented by any implementation. It's defined to return an `SKContext`, which only has an internal constructor.  That means it's impossible for anything outside of Microsoft.SemanticKernel.Abstractions to actually implement this abstraction.

**Comment by matthewbolanos** [comment]
Closing since IKernel has been removed
