### ISSUE TITLE
.Net: semantic-kernel extension for VSCode does not provide tokens

### ISSUE THREAD

**Issue by joslat** [microsoft/semantic-kernel#3196]
**Issue:**
Executing a skill works except the tokens, getting: 
"Tokens:
	Tokenization logic is not available."

**To reproduce:**
I have tried SK Tools for VSCode in 2 computers, with up to date VSCode and SK Tools extension.
I then connect an Azure AI endpoint, no issue there.
I create a sample app, sk-csharp-hello-world which comes with FunSkill...
From SK I access/select gpt4 model or gpt3.5.
Execute the skill giving it the inputs.
The skill executes properly, except the tokens, no matter what model I get always:
"Tokens:
	Tokenization logic is not available."
	
The only reference to this issue is at https://marketplace.visualstudio.com/items?itemName=ms-semantic-kernel.semantic-kernel
where it says that tokenization logic is only provided for "known models". We are talking about GPT-3.5 and GPT-4 so I assume that is not the reason...

I have repeated the steps in different computers, with different accounts and different azure tenants. 
The same happens.

Any recommendation on what to do?

**Expected behavior**
I get the tokens :)
![issue01](https://github.com/microsoft/semantic-kernel/assets/9831011/c95cbbf6-4ba6-4556-acf5-de97911c9a16)

**Screenshots**

**Platform**
 - OS: windows 11
 - IDE: VS Code
 - Language: C#
 - Source:NuGet package version 0.9.5, https://marketplace.visualstudio.com/items?itemName=ms-semantic-kernel.semantic-kernel

**Additional context**
tried it from zero on another computer, the same happens

**Comment by markwallace-microsoft** [comment]
Hi @joslat thanks for reporting this issue, I'll take a look today.

**Comment by markwallace-microsoft** [comment]
We are using https://www.nuget.org/packages/SharpToken to compute token counts and we need to upgrade the version we depend on. We should be able to post an updated release this week.

**Comment by joslat** [comment]
That sounds fantastic, thank you so much!!!

**Comment by markwallace-microsoft** [comment]
@joslat version 0.9.6 has been published. If you still have problems please re-open the issue.

**Comment by joslat** [comment]
Hi, tried with two environments/set-ups, the same keeps happening.

**Comment by joslat** [comment]
Can you please reopen? I do not seem to be able to...

**Comment by markwallace-microsoft** [comment]
@joslat 

1. Can you confirm you are using the 0.9.6 version of the VS Code extension?
2. What model version of `gpt-4` are you using?

The only thing I can think of is that the `gpt-4` model version you have differs from what I am using.

I just tested and this is what I get

![image](https://github.com/microsoft/semantic-kernel/assets/127216156/4cc20fc4-e7ff-4f5a-83f7-e8d72ef79811)

**Comment by joslat** [comment]
version of the VS Code Tools: 0.9.6 (from October 17th)
gpt-4 model version: 0613
Also, the Azure OpenAI is hosted in Switzerland North.

**Comment by joslat** [comment]
@markwallace-microsoft Where do you have the Azure OpenAI resource deployed? let me know and will reproduce it with the same exact features...
What I do is create a new SK app after signing in to Azure,
![image](https://github.com/microsoft/semantic-kernel/assets/9831011/1da5361a-a8c2-427d-88fe-3764d0a7e8b3)
Does this step-by-step issue reproduction work from your side? 
(starting vs code, logging into Azure, creating a new app with "hello sk world" as in the image and executing the joke semantic function)

vs code is latest, just in case the hello world is using net6.0, and the sdk I have installed is 6.0.416 (checked with dotnet --info)

**Comment by joslat** [comment]
Thanks a ton @markwallace-microsoft !!
Sounds good, no pressure, I know how much load you have on top so let me know if I can help... What I know is that on the KernelResponse, deep into the JSON there is the Usage with the Tokens... so the information is there ;)

Also let me know If I can do any test that can ease the load on you. Happy to give back.

**Comment by markwallace-microsoft** [comment]
@joslat I believe the problem is that we are erroneously passing the deployment id to SharpToken instead of the model id. Everythign works for me because out deployment id matches the model id i.e. `gpt-4`. But in your case the deployment id looks to be `gpt4`.  I'm investigating a fix.

**Comment by joslat** [comment]
It works like a charm now! Thanks a TON @markwallace-microsoft & Team!!
