### ISSUE TITLE
.Net: STREAMLIT Samples

### ISSUE THREAD

**Issue by calapsss** [microsoft/semantic-kernel#3213]
Make streamlit examples in the samples folder. This will definitely get more eyeballs for the project.  Willing to PR.
```[tasklist]
### Tasks
```

**Comment by calapsss** [comment]
Noted, I am adding a simple streamlit app we built for our class.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
