### ISSUE TITLE
.Net: The operation was cancelled because it exceeded the configured timeout of 0:01:40

### ISSUE THREAD

**Issue by MarkusMeyer13** [microsoft/semantic-kernel#3223]
**Describe the bug**

I'm using Microsoft.SemanticKernel version="1.0.0-beta2"
The `InvokeAsync` method raises an exception:

>The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.

StackTrace:  
>   at Azure.Core.Pipeline.ResponseBodyPolicy.ThrowIfCancellationRequestedOrTimeout(CancellationToken originalToken, CancellationToken timeoutToken, Exception inner, TimeSpan timeout)
   at Azure.Core.Pipeline.ResponseBodyPolicy.<ProcessAsync>d__5.MoveNext()
   at Azure.Core.Pipeline.RedirectPolicy.<ProcessAsync>d__7.MoveNext()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__5.MoveNext()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__5.MoveNext()
   at Azure.Core.HttpPipelineExtensions.<ProcessMessageAsync>d__0.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.AI.OpenAI.OpenAIClient.<GetChatCompletionsAsync>d__17.MoveNext()
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.<RunRequestAsync>d__29`1.MoveNext()
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.<InternalGetChatResultsAsync>d__19.MoveNext()
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.<InternalGetChatResultsAsTextAsync>d__22.MoveNext()
   at Microsoft.SemanticKernel.SemanticFunction.<RunPromptAsync>d__36.MoveNext()
   at Microsoft.SemanticKernel.SemanticFunction.<InvokeAsync>d__17.MoveNext()

**To Reproduce**

This is the C# code which produces the exception:  

```csharp
static async Task<string?> Summarize(string openAiDeploymentName, string openAiEndPoint, string openAiKey, string prompt, string data)
{
    try
    {
        var builder = new KernelBuilder();
        builder.WithAzureChatCompletionService(openAiDeploymentName, openAiEndPoint, openAiKey);
        var kernel = builder.Build();

        var summarize = kernel.CreateSemanticFunction(prompt, requestSettings: new OpenAIRequestSettings() { Temperature = 0.1 });

        // 'data' has a length of 8993
        var result = await summarize.InvokeAsync(data, kernel).ConfigureAwait(false);

        return result.GetValue<string>();
    }
    catch (Exception e)
    {
        await Console.Out.WriteLineAsync(e.Message);
        throw;
    }
}
```

Used model:  
>Model name: gpt-35-turbo-16k
Model version: 0613
Version update policy: Once a new default version is available.
Deployment type: Standard
Content Filter: Default
Tokens per Minute Rate Limit (thousands): 5
Rate limit (Tokens per minute): 5000
Rate limit (Requests per minute): 60

The data to summarize has a length of 8993 characters.
The timeout does not happen if the length is e.g. 4000 characters.

1. Run code
2. Wait for the result
3. TimeOut exception occurs

**Expected behavior**
`InvokeAsync` shall return a valid result also for longer strings.

**Screenshots**

<img width="962" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/8818198/f82ac000-afd7-45ef-8cc5-bdef97b2fd4e">

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#

**Additional context**

**Comment by matthewbolanos** [comment]
@MarkusMeyer13, does providing a custom HTTP client to the kernel with a different timeout fix the issue?

**Comment by MarkusMeyer13** [comment]
I solved the timeout issue by increasing the timeout value with `OpenAIClientOptions`:

```csharp
var clientOptions = new OpenAIClientOptions();
clientOptions.Retry.MaxRetries = 1;
clientOptions.Retry.NetworkTimeout = TimeSpan.FromMinutes(4);
var openAIClient = new OpenAIClient(new Uri(openAiEndPoint), new AzureKeyCredential(openAiKey), clientOptions);

var builder = new KernelBuilder();
builder.WithAzureChatCompletionService(openAiDeploymentName, openAIClient);
var kernel = builder.Build();
```
