### ISSUE TITLE
.Net: How to output error messages to [OBSERVATION] in native functions

### ISSUE THREAD

**Issue by hyam1567** [microsoft/semantic-kernel#3224]
My native function raises an exception with a message when an error occurs.
`throw new Exception( "Argument must not be a negative number" );`

However, this error message is not output to [OBSERVATION].
In the log, the exception message always looks like this.
`2023-xx-xx xx:xx:xx.xxxx|INFO|Microsoft.SemanticKernel.Planners.StepwisePlanner|Observation: Error invoking action MyPlugin.Sqrt : Exception has been thrown by the target of an invocation.`

I need a way to output error messages to [OBSERVATION].

**Comment by matthewbolanos** [comment]
@gitri-ms, do you know if our new planner is able to handle exceptions like this?
