### ISSUE TITLE
Python: Is there any tutorial about "How to Use predefined plans"

### ISSUE THREAD

**Issue by rxdaozhang** [microsoft/semantic-kernel#3225]
Is there any Python version tutorial about "How to Use predefined plans" mentioned in "Automatically orchestrate AI with planners". That will help me a lot.Thx.
By the way. I would like to know when will the Python SDK 1.0 and API references be released?

**Comment by aeharriman** [comment]
I also would appreciate this.

**Comment by lfbraz** [comment]
+1

**Comment by moonbox3** [comment]
Closing this issue as we're tracking the ask in #1745. 

The Python SDK is now in beta. We're shooting to have v1.0.0 done by middle of May.
