### ISSUE TITLE
Make plugins more descriptive, leverage all properties in plugin manifest (ai-plugin.json) when importing plugin

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/semantic-kernel#3233]
In general, Plugins don't leverage a descriptive [Description] attribute.  SK reads the [Description] attribute off of SKFunctions but not Plugins

OpenAPI Connectors currently ignore the data that's provided in the ai-plugin.json file, save for the URL to the OpenAPI spec.

- Need to automate the import of fields like name_for_model and description_for_model that would be especially helpful to the planner when identifying relevant functions to plan
- Related: [Issue #2459](https://github.com/microsoft/semantic-kernel/issues/2459), Lisa did some investigation on how this could help improve planner performance (memory)

**Comment by teresaqhoang** [comment]
Porting some notes from @matthewbolanos / @lemillermicrosoft 

There's more here to do, too for v1.1? (non-breaking changing?)
- Need a plugin class to store this information in the kernel
- In the future, we need to provide a plugin manifest file that includes this top level information for semantic/native functions
- Need a generic ImportPlugin API that can handle importing native and semantic functions in one plugin.

**Comment by matthewbolanos** [comment]
This has now been resolved now that the KernelPlugin class has been introduced
