### ISSUE TITLE
.Net: GPT4All connector

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/semantic-kernel#3234]
I think it would be a good idea to add a C# connector for gpt4all

list if bindings:
https://github.com/nomic-ai/gpt4all/tree/main/gpt4all-bindings
I think it might be a good idea

**Comment by KSemenenko** [comment]
I helped to fix nuget packgae build for gpt4all, so I will do PR with connector =)

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
