### ISSUE TITLE
Java: Prompt template config file fails silently when format is invalid

### ISSUE THREAD

**Issue by gdong42** [microsoft/semantic-kernel#3238]
Currently, if the JSON file for the semantic function template configuration is invalid, such as having an unknown field, SK does not parse the configuration and does not provide any visible errors or warnings. I encountered a situation where the configuration did not take effect, and after spending some time to debug, I was able to identify the root cause. It was due to I had a typo in the field and the deserialization of the JSON configuration ignored any parsing errors and discarded the error information.

https://github.com/microsoft/semantic-kernel/blob/d16b3ebf5144c47b44a4979fcd805724e1a4aff5/java/semantickernel-api/src/main/java/com/microsoft/semantickernel/extensions/KernelExtensions.java#L171C1-L175C1

It would be nice to show the user when the provided configuration file is invalid, along with the parsing error information.

**Comment by evchaki** [comment]
@gdong42  - thanks for finding this.  We will have the team take a look.

**Comment by johnoliver** [comment]
This is fixed in the latest code, fix will go out in the next release
