### ISSUE TITLE
Is anyone monitoring the microsoft/semantic-kernel-starters branch? I need some help in publishing the plugins from local machine to azure

### ISSUE THREAD

**Issue by dipteshbosedxc** [microsoft/semantic-kernel#3240]
I have been trying to publish the azure-function folder to Azure in the plugin starter repo. While the OpenAPI swagger works fine...the AI manifest is not responding. Hence, I am not able to use any published Azure Function Plugin through Copilot. Please provide a documentation.

**Comment by diptesh-bose** [comment]
Appreciate an update to this
