### ISSUE TITLE
.Net: BingConnector configurable endpoint

### ISSUE THREAD

**Issue by kuhndj67** [microsoft/semantic-kernel#3243]
Ability to configure bingconnector uri to support contoso custom search api v7 endpoints.. Right now uri is hard coded in BingConnector:
public async Task<string> SearchAsync(string query, CancellationToken cancellationToken = default(CancellationToken))
        {
            Uri uri = new Uri("https://api.bing.microsoft.com/v7.0/search?q=" + Uri.EscapeDataString(query) + "&count=1");

**Comment by SOE-YoungS** [comment]
This is added in #3357

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
