### ISSUE TITLE
.Net: When using OpenAI function calling return the function response using the `function` role

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#3248]
The available Chat roles [here](https://github.com/microsoft/semantic-kernel/blob/18ffc4bf2f2b57d3c58381e8d961e3757ce0c991/dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/AuthorRole.cs#L4) do not include a 'function' role, which is required when sending the function response back to the model ([docs](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling#managing-the-flow-with-functions)).

In this [sample](https://github.com/microsoft/semantic-kernel/blob/b6c32ed114f97d4f88325f5ba288200cc124494a/dotnet/samples/KernelSyntaxExamples/Example59_OpenAIFunctionCalling.cs#L102) it is using the "Assistant" role to do this but that's not the correct role

**Comment by lavinir** [comment]
Some additional notes to the function calling flow:
* According to the spec, the message coming back from the assistant which includes details on which function to call, should be appended to the ChatHistory and sent back in the next call along with the Function response (with the function role) [reference](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling)

**Comment by markwallace-microsoft** [comment]
Resolved by https://github.com/microsoft/semantic-kernel/pull/3421
