### ISSUE TITLE
.Net: Chat doesn't work when adding Azure AD authentication

### ISSUE THREAD

**Issue by rouissis** [microsoft/semantic-kernel#3288]
**Describe the bug**
Can't create any chat when user is authenticated using Azure AD

**To Reproduce**
1. Configure the app registrations (locally https://github.com/microsoft/chat-copilot/blob/main/README.md#optional-enable-backend-authentication-via-azure-ad or for Azure https://learn.microsoft.com/en-us/semantic-kernel/chat-copilot/deploy-to-azure#prerequisites)
2. Add the configuration to your environment (local or Azure)
3. Run the app (or Deploy if on Azure)

**Expected behavior**
When running the app we expect to be able to create chats like below :
![image](https://github.com/microsoft/semantic-kernel/assets/122818970/8dd4fe77-5488-4df5-a962-5cf712b9776f)

**Screenshots**
Instead, we get this empty window :
![image](https://github.com/microsoft/semantic-kernel/assets/122818970/037ab9f0-2838-4f77-898f-79596bb21207)
And when we click + > New chat session, nothing happens.

**Platform**
 - OS: Windows, or Azure
 - IDE: VS Code locally, or Azure
 - Language: C#
 - Source: Chat Copilot package latest version

**Additional context**

**Comment by matthewbolanos** [comment]
Thanks for reporting the issue. Do you mind opening the inspect window in your browser and sharing any errors that you might find? This will help us diagnose the issue.

**Comment by rouissis** [comment]
Hi Matthew,

Thank you for following up. Here are the errors I get on the inspect window :
- :40443/maintenanceStatus:1 : Failed to load resource: the server responded with a status of 401 ()
- FetchClient.ts:58 : POST https://login.microsoftonline.com/04a4a394-5e9c-4f97-a562-c326a1ca45d4/oauth2/v2.0/token 400 (Bad Request)
 And every time I click on new chat we keep getting this error : 
FetchClient.ts:58 : POST https://login.microsoftonline.com/04a4a394-5e9c-4f97-a562-c326a1ca45d4/oauth2/v2.0/token 400 (Bad Request)

![image](https://github.com/microsoft/semantic-kernel/assets/122818970/a52920d1-a493-4013-99ba-630aa6d3a93f)

**Comment by glahaye** [comment]
@rouissis This looks like an incorrectly configured AAD setup.

Are you still experiencing the issue?  Have you tried with the latest version of Chat Copilot?

**Comment by rouissis** [comment]
Hi Gil,

You are correct, there was an issue with our AAD app registrations. After recreating them, the authentication worked, unfortunately the bing search plug in doesn't work. 
I'll try the latest version of Chat Copilot, otherwise I'll create a bug for that issue specifically. Thanks!

**Comment by rouissis** [comment]
Hi Gil,

You are correct, there was an issue with our AAD app registrations. After recreating them, the authentication worked, unfortunately the bing search plug in doesn't work.
I'll try the latest version of Chat Copilot, otherwise I'll create a bug for that issue specifically. Thanks!

**Comment by glahaye** [comment]
There is already a bug open for the bing search plugin: https://github.com/microsoft/chat-copilot/issues/549
