### ISSUE TITLE
Python: Memory Store supports a hybrid search in weaviate over nearest Vector matches which the current implements

### ISSUE THREAD

**Issue by jungwookim** [microsoft/semantic-kernel#3290]
Hi folks!

I'm experimenting features of a long term memory store with weaviate. Currently, it supports the nearest vector search (See: https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/memory/semantic_text_memory.py#L152) all over the storages but as far as I know, some of vector databases such as weaviate are capable of "hybrid" search. So, I would memory store to have hybrid search to extend a searching ability.

I want to hear the voice of folks.

**Comment by alexchaomander** [comment]
I commented on the PR! Overall I think it's good to have and should be supported. There's the Kernel Memory project (https://github.com/microsoft/kernel-memory) that @dluc @crickman and others are building but it'll likely take some time before a Python client supporting hybrid search is available. Adding this inside the Text Memory Skill could be a good interim solution

**Comment by jungwookim** [comment]
I have been looking on the Kernel Memory and looking forward to supporting a Python client! Any chances to contribute it, I will!

In the mean while, I hope #3329 can be a short time solution as you mentioned.

**Comment by alliscode** [comment]
This will come in with the updated memory connector abstraction soon.
