### ISSUE TITLE
.Net: Azure function calling missing 'enum' support for parameters

### ISSUE THREAD

**Issue by lavinir** [microsoft/semantic-kernel#3292]
Current implementation does not have support for indicating a closed list of 'enum' values used in the FunctionDefinition. As per the supported Function Calling Schema in Azure OpenAI. See examples [here](https://techcommunity.microsoft.com/t5/azure-ai-services-blog/function-calling-is-now-available-in-azure-openai-service/ba-p/3879241)

**Expected behavior**
Add support for defining enum values for a function parameter.

**Platform**
 - Language: [C#]
 - Source: [latest nuget preview, main branch of repository]

**Additional context**

**Comment by matthewbolanos** [comment]
Today we don't currently support the enum type for SKFunctions. Before we get enum support for Azure OpenAI function calling, we need to get arbitrary object types for SKFunctions (both input and outputs). We've started to look into this.
