### ISSUE TITLE
Python: In kernel.py, we swallow exceptions when they shouldn't be. 

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3296]
Customer report: today in kernel.py, we swallow exceptions when they shouldn't be. 

![image](https://github.com/microsoft/semantic-kernel/assets/1409190/74ee121b-cd88-4308-9b1e-1e03f24e6a1f)

**Comment by eavanvalkenburg** [comment]
This was fixed in #2948, so they should upgrade to a newer version of SK!
