### ISSUE TITLE
Python: Add support for multiple native function arguments of many types

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3307]
This is issue to make sure that the Python SDK confirms to this ADR: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0003-support-multiple-native-function-args.md

If this ADR is already supported, please close this issue.

**Comment by eavanvalkenburg** [comment]
This was done as part of the broader python work with kernel arguments
