### ISSUE TITLE
Python: Error handling improvements

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3308]
This issues is to capture any work to conform to this ADR: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0004-error-handling.md#error-handling-improvements

If this is already complete in Python, please close this issue.

**Comment by moonbox3** [comment]
Closing this issue as the work to implement more Pythonic exceptions/error handling is complete (as of the beta).
