### ISSUE TITLE
Python: Kernel/Function Handlers

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3309]
This issue is to capture any work for the Python SDK to adhere to this ADR: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0005-function-execution-handlers.md#kernelfunction-handlers

If this is already complete, please close this issue.

**Comment by joowon-dm-snu** [comment]
#3063

**Comment by joowon-dm-snu** [comment]
@matthewbolanos i can take this issue but no auth to assign my self here.
and #3063 should be merged first to get further steps!

**Comment by moonbox3** [comment]
Closing this issue as we're tracking the work in #3038.
