### ISSUE TITLE
Python: Dynamic payload building for PUT and POST RestAPI operations and parameter namespacing

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3310]
This issue is to capture any work for the Python SDK to adhere to this ADR: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0006-open-api-dynamic-payload-and-namespaces.md

If this is already complete, please close this issue.

**Comment by moonbox3** [comment]
This is now present in SK Python 1.0.0+
