### ISSUE TITLE
Python: Refactor to support generic LLM request settings

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3312]
This issue is to capture any work necessary for the Python SDK to conform to this ADR: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0008-support-generic-llm-request-settings.md#refactor-to-support-generic-llm-request-settings

If this is already complete, please close this issue.

**Comment by eavanvalkenburg** [comment]
I started working on this.

**Comment by eavanvalkenburg** [comment]
@markwallace-microsoft @dmytrostruk @lemillermicrosoft @stephentoub question to you all on this one, this is implementing the pattern described in decision 0008, one thing I ran into is that for Azure different API versions require/accept different arguments and will throw an error when a "unknown" argument is given, my thinking now is to add the control of that to the specific request settings class (and not for instance the client class) and to do that by adding api_version to the AzureChatRequestSettings class and then having a dict that tells the (tentativally named, have to check if there is a equivalent func in dotnet) `prepare_settings_dict` function which fields to exclude or include, three questions: 1) what do you guys think? 2) is there something like this in dotnet and if so where? and 3) can this be added to de decision?

**Comment by eavanvalkenburg** [comment]
This is merged.
