### ISSUE TITLE
Python: OpenAI Function Calling Support

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3313]
This issue is to capture any work necessary to support this ADR: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0010-openai-function-calling.md

If this is already done, please close this issue.

**Comment by eavanvalkenburg** [comment]
you can assign me, just [this](https://github.com/microsoft/semantic-kernel/pull/3226) piece left for now, will have to revisit once context is gone.

**Comment by eavanvalkenburg** [comment]
@matthewbolanos this can be closed
