### ISSUE TITLE
Python: Replace SKContext as Function/Kernel result type with FunctionResult and KernelResult models

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3314]
This issue is to capture any work necessary to align to this ADR: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0011-function-and-kernel-result-types.md

If this is already complete, please close this issue.

**Comment by eavanvalkenburg** [comment]
isn't this the same as #4565 @matthewbolanos

**Comment by moonbox3** [comment]
I agree that it is the same as #4565. Let's close this item.
