### ISSUE TITLE
Python: SK prompt syntax for chat completion roles

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3318]
This issue is to track the work necessary to align with this ADR: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0014-chat-completion-roles-in-prompt.md

If this is already complete, please close this issue.

**Comment by rewrlution** [comment]
I can take a look into this one.

**Comment by moonbox3** [comment]
As of #5077 the user can now add their own xml to add messages directly in ChatHistory. Closing this work item.
