### ISSUE TITLE
Python: Create v1 proposal sample

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3325]
To validate what is necessary to get to V1 for Python, we need to create a similar set of samples as what is available here: https://github.com/matthewbolanos/sk-v1-proposal

The samples should highlight the main changes being made to the kernel.

**Comment by eavanvalkenburg** [comment]
On it!

**Comment by eavanvalkenburg** [comment]
Have a look here: https://github.com/matthewbolanos/sk-v1-proposal/tree/main/python

**Comment by matthewbolanos** [comment]
Marking this as complete
