### ISSUE TITLE
.Net: IImageGeneration  support prompt and negative_prompt

### ISSUE THREAD

**Issue by MayueCif** [microsoft/semantic-kernel#3328]
Regarding IImageGeneration, I want to extend SK to support Stable-Diffusion. How should I do this?
GenerateImageAsync has only one description parameter and does not support prompt and negative_prompt enough. Are you considering rewriting this method? Or can I only use description = prompt $$ negative_prompt to achieve this?

**Comment by matthewbolanos** [comment]
Thanks for sharing your use case. I'm currently doing an audit on various models to make sure we can support them. I will use this as a test case and follow up once we have a plan.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
