### ISSUE TITLE
I can't save my api key to the book sample page

### ISSUE THREAD

**Issue by cometbus** [microsoft/semantic-kernel#333]
Something went wrong.

Details:
Error: Error: Not Found => <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /undefined/api/skills/funskill/invoke/joke</pre>
</body>
</html>

**Comment by yongboyang** [comment]
I encountered the same issue.

**Comment by kotharthar** [comment]
Copy `.env.example` as `.env` in the sample project folder.

I think the sample code load the environment file to read `REACT_APP_FUNCTION_URI`. 

It is not hardcoded in the project source code, so missing `.env` file results in undefined host path.

**Comment by yongboyang** [comment]
It works now. Thank you very much.

发自我的 iPhone

在 2023年4月6日，12:04，Thar Htet ***@***.***> 写道：

﻿

Copy .env.example as .env in the sample project folder.

I think the sample code load the environment file to read REACT_APP_FUNCTION_URI.

It is not hardcoded in the project source code, so missing .env file results in undefined host path.

**Comment by craigomatic** [comment]
Sorry about the hassle here, we've updated the sample readmes to make it clearer with this PR: https://github.com/microsoft/semantic-kernel/pull/382
