### ISSUE TITLE
Python: prepare for OpenAI v1.0 package

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/semantic-kernel#3330]
OpenAI is working on a 1.0 version of their package that we rely on heavily to call openai models, the interfaces are changing (for the better), current work can be seen here: https://github.com/openai/openai-python/tree/v1

**Comment by alexchaomander** [comment]
@eavanvalkenburg agree that this should be worked on! Other projects like AutoGen are already preparing their latest releases for this change
