### ISSUE TITLE
.Net: FR: Support Typesense as Vector Database

### ISSUE THREAD

**Issue by HazyFish** [microsoft/semantic-kernel#3337]
[Typesense](https://typesense.org/) is an open source, typo tolerant search engine that supports vector/semantic search. It would be great if semantic kernel would support that as a vector database for memory.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
