### ISSUE TITLE
Request: TypeScript support (~C# parity)

### ISSUE THREAD

**Issue by jsegeren** [microsoft/semantic-kernel#334]
Hi - we have a project using Next.JS and would love to leverage SK on the backend.
A full TypeScript port (ideally 1:1 parity with C#) would be truly valuable and appreciated. 

As part of this, a NPM distribution of the TS SDK (i.e. https://registry.npmjs.org).

Happy to discuss/explain the scenarios more. 
Thanks!

**Comment by evchaki** [comment]
@jsegeren , parity would be great for C#.  If you want to help with that effort we would love to get PRs from you in this branch - https://github.com/microsoft/semantic-kernel/tree/experimental-typescript

**Comment by lokk3d** [comment]
+1 on this feature, really interesting! I'll try to participate in the typescript branch

**Comment by indiejoseph** [comment]
+1

**Comment by matthewbolanos** [comment]
Closing since we currently do not have plans to add a TypeScript version of the SDK. This may change in the future.

**Comment by itpropro** [comment]
Any updates on TypeScript support @matthewbolanos ? If we are even supporting Java, there is no reason, why (the Microsoft owned) TypeScript has no support as the most used programming language.
