### ISSUE TITLE
.Net: [looking to contribute] Where to write additional tests - python

### ISSUE THREAD

**Issue by xavierdurawa** [microsoft/semantic-kernel#3340]
I'd like to begin contributing to the project (preferably on the Python side where I have more experience and eventually move to .net) but it looked like most of the issues already had assignees or de facto assignees. I thought adding tests would be a useful place to contribute and to learn.  Was hoping someone might be able to give a nudge or a point in the right direction concerning where additional tests would be needed/helpful.  Or if there is another task you'd recommend, I'd be happy to take a look. Thanks!

**Comment by xavierdurawa** [comment]
Any suggestions on where to start?

**Comment by moonbox3** [comment]
@xavierdurawa let me take a look. If you see anything, before I have a chance to look, that could benefit from tests, don't hesitate to file an issue and then work on it yourself.

If you want a good intro task, you can finish the last few items on https://github.com/microsoft/semantic-kernel/issues/2309. It looks like a few of the notebooks still need to be updated from text-davinci-003 to a new model.

**Comment by matthewbolanos** [comment]
Thanks for the recommendation @moonbox3! Will close this issue for now.
