### ISSUE TITLE
Python: emantic_kernel.kernel_exception.KernelException: (<ErrorCodes.FunctionTypeNotSupported: 3>, "Invalid function type detected, unable to infer DelegateType.

### ISSUE THREAD

**Issue by AliRaza190** [microsoft/semantic-kernel#3356]
I am trying to import a native function in my kernel. Whenever I set the return type of the function as int,str,bool or float, it works but it doesn't work when I set the return type of json for my usecase.
Follwing is native_function.py
`from semantic_kernel import Kernel
from semantic_kernel.skill_definition import sk_function
from semantic_kernel.orchestration.sk_context import SKContext
import json
import ast 
import requests
import pandas as pd

class CSVLoader:
    
    def __init__(self,kernel:Kernel) -> None:
        self._kernel=kernel

    @sk_function(
        description="This will load a CSV file and return the dataframe",
        name="loadcsv",
        input_description="This is a string which is the filename of CSV file",
    )
    async def LoadCSV(self, input: str) -> json:
        df=pd.read_csv(input)
        output=df.to_json()
        return output`

**Comment by almariscal** [comment]
Hi! Is there any option to return variables such as json or dataframes or is it supposed to be able in the future?

I want to query SQL Databases but I am stuck as I cannot return the query results. Thanks!

**Comment by naqviali505** [comment]
Use SKContext to create context variables. which works in the same way as dict. Return SKContext variable. You can read the example notebook from the github repo.

**Comment by eavanvalkenburg** [comment]
I'm closing this, mostly because the new code that is now in main no longer relies on delegate handling, so most of these issues should be fine. One note is that json is not a valid type in python so not sure what you are aiming for...
