### ISSUE TITLE
.Net: Microsoft.SemanticKernel.Plugins.Memory.dll is delay-signed or test-signed assembly

### ISSUE THREAD

**Issue by ksjoberg** [microsoft/semantic-kernel#3382]
**Describe the bug**
The assembly Microsoft.SemanticKernel.Plugins.Memory.dll fails to load on a Windows Server machine:
```
Could not load file or assembly 'Microsoft.SemanticKernel.Plugins.Memory' or one of its dependencies. 
Strong name signature could not be verified. The assembly may have been tampered with, or it was delay
signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045) 
```
Checking the assembly with `sn.exe -v` yields:
```
sn -v Microsoft.SemanticKernel.Plugins.Memory.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Microsoft.SemanticKernel.Plugins.Memory.dll is a delay-signed or test-signed assembly
```

**To Reproduce**
1. Verify that verification skipping is disabled, i.e. `sn.exe -Vl` for your architecture (x86/x64) shows
```
sn.exe -Vl

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

No verification entries registered
```
2. Load the assembly into a runtime that verifies strongname signatures.

**Expected behavior**
The assembly should load without issues.

**Platform**
 - OS: Windows
 - Language: C#
 - Source: beta1, beta4

**Comment by RogerBarreto** [comment]
The Microsoft assemblies signed only in the release packages.

To get a strong name, you need to follow this steps:

1. Download the nuget package [Microsoft.SemanticKernel.Plugins.Memory 1.0.0-beta6](https://www.nuget.org/packages/Microsoft.SemanticKernel.Plugins.Memory/1.0.0-beta6)


![Image](https://github.com/microsoft/semantic-kernel/assets/19890735/57b7dd88-5870-4397-820b-3de310b62d97)


2. Rename microsoft.semantickernel.plugins.memory.1.0.0-beta6.**nupkg** to microsoft.semantickernel.plugins.memory.1.0.0-beta6.**zip**
3. Extract it
4. Get the assembly file `Microsoft.SemanticKernel.Plugins.Memory.dll` from the `lib/netstandard2.0` folder
5. Check for the strong name like you did.

```
F:\check-assembly-strongname> sn -v Microsoft.SemanticKernel.Plugins.Memory.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'Microsoft.SemanticKernel.Plugins.Memory.dll' is valid
```

**Comment by RogerBarreto** [comment]
Closing this issue, for now.

Thanks for the feedback.

**Comment by Wopienkaatwork** [comment]
Hi @RogerBarreto  I've just tried that and I still get: 
C:\Users\WernerWopienka\Downloads\microsoft.semantickernel.plugins.memory.1.0.0-beta6\lib\netstandard2.0>sn -v Microsoft.SemanticKernel.Plugins.Memory.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Microsoft.SemanticKernel.Plugins.Memory.dll is a delay-signed or test-signed assembly

**Comment by RogerBarreto** [comment]
@Wopienkaatwork , please what was the Nuget Package you attempted to download from ?

Ensure you got it from here: [Microsoft.SemanticKernel.Plugins.Memory 1.0.0-beta6](https://www.nuget.org/packages/Microsoft.SemanticKernel.Plugins.Memory/1.0.0-beta6)

**Comment by Wopienkaatwork** [comment]
@RogerBarreto ,  yes I took the link you provided, downloaded the nuget file, renamed it to zip, extracted it and used the vs2022 cmd prompt: 
C:\Users\WernerWopienka\Downloads\microsoft.semantickernel.plugins.memory.1.0.0-beta6\lib\netstandard2.0>
sn -v Microsoft.SemanticKernel.Plugins.Memory.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Microsoft.SemanticKernel.Plugins.Memory.dll is a delay-signed or test-signed assembly
I also tried it via the nuget explorer with the same result.

**Comment by ksjoberg** [comment]
I second this, just downloaded beta6 and tested:
```
> sn -v Microsoft.SemanticKernel.Plugins.Memory.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Microsoft.SemanticKernel.Plugins.Memory.dll is a delay-signed or test-signed assembly

$ sha256sum Microsoft.SemanticKernel.Plugins.Memory.dll
76a701d0aced588b01eeaaf9ca4a187766911d0d0b79e3102fb9d68c7d3417ee  Microsoft.SemanticKernel.Plugins.Memory.dll
```

**Comment by RogerBarreto** [comment]
Ok, will look deeper into this.
