### ISSUE TITLE
Python: Adding parameters to a function called from chat_completion_with_function_call

### ISSUE THREAD

**Issue by MatsGej** [microsoft/semantic-kernel#3391]
I adapted the function call example with my own function. I can get it too work if I add my contextual parameters to the chat text. But I just want the chat_completion_with_function_call to kick off the function and add my parameters to the context using context.variable. I do that in the example code like this
async def chat(context: sk.SKContext) -> Tuple[bool, sk.SKContext]:
    try:
        user_input = input("User:> ")
        context.variables["user_input"] = user_input

      context.variables["location"] = "56.87756462283162,14.81065140489338"
      context.variables["language"] = "swedish"
      context.variables["category"] = ["museum"]
      context.variables["user"] = "Mats"

    context = await chat_completion_with_function_call(
        kernel,
        chat_skill_name="ChatBot",
        chat_function_name="Chat",
        context=context,
        functions=functions,
        context_vars=context_vars,
    )

The function is called,  but the variables I set are not in the context object. 

I am using python 11 on a windows 11 machine

**Comment by matthewbolanos** [comment]
Are you able to share why the function is taking both context and context_vars? It should only take one of them.

**Comment by matthewbolanos** [comment]
The other thing I'd add... is that function calling doesn't use the variables in the context unless it's somewhere in the actual prompt. You need to take all of the variables and make sure they are outputted to the prompt so that the LLM knows of their value.

**Comment by MatsGej** [comment]
That is not a very effective way of doing this. It will increase the token count. 

This is the code of the function that is called where I was trying to get the context variables directly from the context object.

    @sk_function(
        description="Get interesting places ",
        name="get_interesting_places",    
     async def get_interesting_places(self, initial_value_text: str, context: "SKContext") -> str:

        places = await get_interesting_places (context["currentLocation"], context["category"], context["language"], context["sender"])
        return dumps(places)   

I can do this using the basic openai function calling without semantic kernel, but I want to use other features in semantic kernel at the same time. But first I need to get this working properly.
