### ISSUE TITLE
.Net: Add Support for "dall-e-3" Model in OpenAIImageGeneration Class

### ISSUE THREAD

**Issue by Nurgo** [microsoft/semantic-kernel#3435]
Hi,

I propose we add support for the "dall-e-3" model within the `OpenAIImageGeneration` class. The integration seems straightforward and the benefit to the users would be substantial, allowing them to utilize the latest in image generation technology.

Proposed Change:
- Update the `OpenAIImageGeneration` class to include "dall-e-3" model support.
- Introduce a "modelId" parameter in the constructor to select the desired image generation model, similar to how it is currently handled for text generation models in the library.

This enhancement would allow for seamless use of "dall-e-3" for image generation tasks, maintaining the library's relevance and utility.

Thank you for considering this request.

**Comment by Alerinos** [comment]
@Nurgo Have you found a way to use SK and Dalle 3?

**Comment by Alerinos** [comment]
@Nurgo 
Thanks for the information. I found an alternative, here is the support and it's ready.
https://github.com/betalgo/openai

**Comment by Nurgo** [comment]
@Alerinos Thanks for the information.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.

**Comment by Nurgo** [comment]
This problem doesn't seem to have been solved, as `OpenAITextToImageService` still doesn't support Dall-E3.
