### ISSUE TITLE
.Net: 05-using-the-planner.ipynb DotNet notebook fails in CodeSpaces 

### ISSUE THREAD

**Issue by Rickcau** [microsoft/semantic-kernel#3461]
**Describe the bug**

**To Reproduce**
1. Fork the repo
2. Create a CodeSpace
3. Make sure your CodeSpace is using the .NET Interactive Kernel
4. Change the settings.json file to point to your Azure OpenAI endpoint
5. Verify that Notebooks 00 - 04 Run as expected, no issues.
6. Open the 05-using-theplanner.ipynb notebook. Run cells 1 - 3 making sure the run without error. 
7. Now, run cell 4, it will error out with the following error: "Error: Microsoft.SemanticKernel.Diagnostics.SKException: Unable to create plan for goal with available functions."
8. 
**Expected behavior**
I expect the notebook to run without error.

**Screenshots**
If applicable, add screenshots to help explain your prob![Semantic 05NB failure](https://github.com/microsoft/semantic-kernel/assets/17052492/689f729c-b5c6-438e-beae-866275df70ba)

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [GitHub CodeSpaces, VS Code]
 - Language: [C#, Python, Juptyer Notebooks, Semantic Kernel]
 - Source: [semantic-kernel main branch of repository]

**Additional context**
Just trying to get this repo working in a codespace for demo purposes and to help customers learn Semantic Kernel.  I am a CSA for MSFT and this is my personal GitHub account.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
