### ISSUE TITLE
.Net: Prompt execution settings can be used when rendering a prompt

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#3466]
As an SK developer I can tune my planner asks based on the execution settings that will be used so that I can optimise use of available AI services.

**Comment by matthewbolanos** [comment]
@markwallace-microsoft, is this done already?

**Comment by markwallace-microsoft** [comment]
Not implemented yet, but should be very easy, will move to sprint 17

**Comment by markwallace-microsoft** [comment]
@matthewbolanos This is going to be a more involved change than I had anticipated and it will need an ADR.

The task was created originally as a follow up to some feedback on one of the planner code reviews so the ask is internal. Are customers asking for this? If not, I'd recommend moving this to the backlog until we have a clear requirement.

**Comment by markwallace-microsoft** [comment]
To implement this we can:

1. Add support for ambient kernel settings which will be managed by SK
2. Add a new interface which prompt templates will interface if they support using execution settings when rendering

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
