### ISSUE TITLE
Python: Prompt Template Loading not loading template due to unknown character on Windows.

### ISSUE THREAD

**Issue by LukasDauterman** [microsoft/semantic-kernel#3471]
**Describe the bug**

I have several prompt templates with very noisy natural language in them, and semantic kernel fails to load the template. 

I give me an error saying " UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 21425: character maps to <undefined>"

The trace points to line 793 in kernel.py:

`            
            # Load Prompt Template

            with open(prompt_path, "r") as prompt_file:

                template = PromptTemplate(

                    prompt_file.read(), self.prompt_template_engine, config

                )
`

This looks like its caused by reading the prompt file using the default windows charact mapping functionality. 

**My Fix**
I can resolve the issue by modifying the open statements in kernel.py on lines 792 and 788 by adding a  encoding='utf-8' argument, and it runs as expected.

**To Reproduce**

1. Create a template with utf-8 characters that are not in default windows open file parser character mapping.

2. Try and load it using import_semantic_skill_from_directory.

**Expected behavior**

I expect the template to load given a potentially wide range of input characters.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/3969402/52ec9659-2291-4029-9106-33db126f03c5)

**Platform**
 - OS: Windows 11
 - IDE: Visual studio Code
 - Language: Python
 - Source: pip package

**Additional context**

**Comment by matthewbolanos** [comment]
Thank you for identifying the problem and the proposed fix. Would you be able to add your fix as a PR so that we can get it merged in?

**Comment by LukasDauterman** [comment]
Yes I can, let me work on getting it in.

**Comment by alliscode** [comment]
Closing issue as it's no longer relevant.

**Comment by afrancoc2000** [comment]
This is also happening to me loading a plugin, the change in this case is in ln 334 of kernel_plugin.py, it's also fixed by setting the encoding to utf-8. @matthewbolanos I can add the fix, should I also create a PR?

**Comment by sakesun** [comment]
This problem still exists

**Comment by sakesun** [comment]
On Windows, set environment variable "PYTHONUTF8" = "1" to workaround this problem.
