### ISSUE TITLE
Dynamic native functions

### ISSUE THREAD

**Issue by DrEight** [microsoft/semantic-kernel#3473]
How can I create a set of native functions discovered at runtime ?

**Comment by matthewbolanos** [comment]
Are you able to share more about the scenario you're describing? You should be able to create native functions at runtime with the register function.

**Comment by DrEight** [comment]
In my app, the user can create a kind function accessible via a rest call. If he/she wants I would like to let him/her to decorate the function with a text description and so the function can became a 'native function' in a LLM agent. 
The concept is that the function is created runtime by a user. I hope I made myself clear.

**Comment by stephentoub** [comment]
The name is evolving, but today you can write things like:
```C#
ISKFunction sayHello= SKFunction.Create((string name) => $"Hello, {name}", functionName: "Say hello", description: "Says hello to the specified name");
```
and then you can register that with the kernel.  The delegate supplied to Create can do effectively anything.

Is that what you're asking for?  Or if not, can you describe what the above would need to support to achieve what you're asking for?

**Comment by DrEight** [comment]
yes, this is what I was searching for. Thanks

**Comment by stephentoub** [comment]
> yes, this is what I was searching for. Thanks

You're welcome.

**Comment by aherrick** [comment]
@stephentoub  can you help me understand an example of how you'd use the sayHello function? 

I've only seen the "DateTime" example, but what are the additional code lines similar to the "DateTime" example? Thanks!

**Comment by stephentoub** [comment]
> @stephentoub can you help me understand an example of how you'd use the sayHello function?
> I've only seen the "DateTime" example, but what are the additional code lines similar to the "DateTime" example? Thanks!

This is going to change slightly with some refactorings happening right now (it'll get simpler), but the simplest way to invoke it is just:
```C#
using Microsoft.SemanticKernel;

ISKFunction sayHello = SKFunction.Create((string name) => $"Hello, {name}");

var kernel = new KernelBuilder().Build();
Console.WriteLine(await kernel.RunAsync("Andrew", sayHello));
```
