### ISSUE TITLE
.Net: Change SK's instrumentation to follow open telemetry best practices

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#3490]
The instrumentation currently used by SK, e.g.
https://github.com/microsoft/semantic-kernel/blob/9e7f5506f4074160d5e5f735ff566d63048f1ec4/dotnet/src/SemanticKernel.Core/Functions/InstrumentedSKFunction.cs#L50-L65
appears to diverge from documented open telemetry best practices.

Some suggestions:
- **Units.** The unit is currently milliseconds, but the guidelines at https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md#instrument-units state "When instruments are measuring durations, seconds (i.e. s) SHOULD be used.". These metrics should be changed to be seconds.
- **Casing**. OT uses lowercase across the board for all standardized names, but SK is using PascalCasing. These metrics should be changed to be lowercase.
- **Attributes**. SK is creating a new metric for each named function. That's not how OT's semantic conventions are structured. For example, there's not one metric for each server an HTTP client talks to; instead, there's a single `http.client.request.duration` metric (https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md#metric-httpclientrequestduration), and it has a bunch of attributes applied to it.  The same should be done for SK, where there's one defined metric for all functions and then attributes are applied when a function is invoked, e.g. instead of `SK.PluginName.FunctionName.ExecutionTime`, it'd be `sk.functions.duration`, then with an attribute like `function_name` applied as part of signaling the metric.

It would be good to examine all the examples in the semantic-conventions repo and update SK's use accordingly.

**Comment by stephentoub** [comment]
At a higher-level, I'm concerned about the WithInstrumentation methods in general, for two reasons:
1. I shouldn't need to change my code in order for things like function invocation to produce metrics.
2. With the more plugin-oriented model the system is moving to, there frequently won't even be a good place to call such methods.

But... if we do the suggestions above, such that we no longer have a named metric per function and instead just treat the function as an attribute on each logged value, then we shouldn't need such a WithInstrumentation anyway.  We just need to find somewhere to raise the relevant metrics, for example as part of whatever routines are responsible for invoking the pre/post hooks.

**Comment by dmytrostruk** [comment]
@stephentoub Thanks, these are very good points. 
Regarding `WithInstrumentation` methods, they were implemented because of the requirement to have an ability to enable/disable telemetry on user side explicitly. We can re-think how this requirement can be achieved. 

We should also think, whether it makes sense to provide some API for telemetry, which will be similar for .NET, Python and Java versions of SK or it's better to implement telemetry for each SK version in a way, that is more friendly to specific programming language/framework. In my opinion, second option should be better, but at the same time, we will sacrifice consistency between .NET/Python/Java versions of SK.

**Comment by stephentoub** [comment]
Thanks.

> they were implemented because of the requirement to have an ability to enable/disable telemetry on user side explicitly. We can re-think how this requirement can be achieved.

Can you elaborate? The requirement is to be able to enable/disable telemetry at what scope, and how does this differ from the meters used in other places, like those used by HttpClient, Dns, ASP.NET, etc.?

> second option should be better

Ideally I think there's nothing in the .NET API about the metrics at all, and the right things "just happen".  Having to explicitly opt-in to them on a per function basis will mean in practice that very few users get any metrics at all.

**Comment by tarekgh** [comment]
CC @noahfalk @JamesNK @CodeBlanch if you have any feedback.

**Comment by CodeBlanch** [comment]
@dmytrostruk How the metrics API works, it just no-ops if there isn't a listener. So you typically don't need something like "WithInstrumentation" in the library being instrumented. Just instrument and then it is up to the user/app to listen if they want any information (opt-in).

PS: Tracing/`ActivitySource` works the same way. If you try to start an `Activity` and there is no listener, it returns `null`.

**Comment by stephentoub** [comment]
Most of this has now been addressed. Remaining piece is to make WithInstrumentation vanish...
