### ISSUE TITLE
.Net: Accessing SKChatMessage.FunctionCall throws exception when the OpenAI model does not return a function call

### ISSUE THREAD

**Issue by alexminza** [microsoft/semantic-kernel#3492]
**Describe the bug**
When streaming the chat response and checking if the OpenAI model returned a function call accessing `SKChatMessage.FunctionCall` throws `NotSupportedException`.

```
Exception has occurred: CLR/System.NotSupportedException
Exception thrown: 'System.NotSupportedException' in System.Private.CoreLib.dll: 'Function call is not supported'
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.SKChatMessage.get_FunctionCall()
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ChatStreamingResultExtensions.<GetOpenAIStreamingFunctionResponseAsync>d__0.MoveNext()
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ChatStreamingResultExtensions.<GetOpenAIStreamingFunctionResponseAsync>d__0.MoveNext()
   ...
```

Reference: https://github.com/microsoft/semantic-kernel/pull/3246

**To Reproduce**
Code similar to [Example59_OpenAIFunctionCalling.cs](https://github.com/RogerBarreto/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example59_OpenAIFunctionCalling.cs#L160)

```csharp
var chatCompletionResults = this.Chat.GetStreamingChatCompletionsAsync(
    chat: chatHistory,
    requestSettings: requestSettings,
    cancellationToken: cancellationToken);

await foreach (var chatCompletionResult in chatCompletionResults)
{
    await foreach (var chatMessageStream in chatCompletionResult.GetStreamingChatMessageAsync(cancellationToken))
    {
        if (!string.IsNullOrEmpty(chatMessageStream.Content))
            yield return chatMessageStream.Content;
    }

    var functionResponse = await chatCompletionResult.GetOpenAIStreamingFunctionResponseAsync();
    yield break;
}
```

**Expected behavior**
`SKChatMessage.FunctionCall` should return `null` instead.

**Platform**
 - OS: macOS Sonoma 14.1.1
 - IDE: VS Code 1.84.2
 - Language: C# 7.0.403
 - Source: Microsoft.SemanticKernel 1.0.0-beta6

**Comment by RogerBarreto** [comment]
The current PR with update to Azure Beta 9, resolves that problem.

[SKChatMessage Nullable FunctionCall property](https://github.com/microsoft/semantic-kernel/pull/3467/files#diff-62c520875792d279838c07efa8935e886f723034721ffd273b25a9cc3b9b612aR89)
