### ISSUE TITLE
.Net: Allow the possibility to change the selected request settings on the pre-hook

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#3494]
## Motivation

This will allow scenarios where a sk developer will be able to change the `AIRequestSettings` before function execution based in the any of the values exposed in the eventargs, including prompt size.

Original ask:

> Hi, I have my prompt and configuration defined in skprompt and config files. However I would like to setup max_tokens value on run of the function as it depends on the length of the input.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
