### ISSUE TITLE
After upgrading to beta6, my OpenAI plugin doesn't work anymore

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/semantic-kernel#3495]
**Describe the bug**
I have a .NET console application using an OpenAI plugin which worked just fine until today, when I upgraded the project to beta6. Now, the following code:

```
const string pluginManifestUrl = "https://semantickernel-unitedstatesdata.azurewebsites.net/api/.well-known/ai-plugin.json";
await kernel.ImportOpenApiPluginFunctionsAsync("UnitedStatesPlugin", new Uri(pluginManifestUrl));
```

returns the following exception:

```
Exception has occurred: CLR/Microsoft.OpenApi.Readers.Exceptions.OpenApiUnsupportedSpecVersionException
An exception of type 'Microsoft.OpenApi.Readers.Exceptions.OpenApiUnsupportedSpecVersionException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'OpenAPI specification version '' is not supported.'
   at Microsoft.OpenApi.Readers.ParsingContext.Parse(YamlDocument yamlDocument)
   at Microsoft.OpenApi.Readers.OpenApiYamlDocumentReader.<ReadAsync>d__3.MoveNext()
   at Microsoft.OpenApi.Readers.OpenApiTextReaderReader.<ReadAsync>d__3.MoveNext()
   at Microsoft.OpenApi.Readers.OpenApiStreamReader.<ReadAsync>d__3.MoveNext()
   at Microsoft.SemanticKernel.Functions.OpenAPI.OpenApi.OpenApiDocumentParser.<ParseAsync>d__1.MoveNext()
   at Microsoft.SemanticKernel.Functions.OpenAPI.Extensions.KernelOpenApiPluginExtensions.<RegisterOpenApiPluginAsync>d__3.MoveNext()
   at Microsoft.SemanticKernel.Functions.OpenAPI.Extensions.KernelOpenApiPluginExtensions.<ImportOpenApiPluginFunctionsAsync>d__1.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in D:\src\events\Codemotion2023\SemanticKernel\SemanticKernel.OpenAIPlugin\Program.cs:line 23
```

I've tried to upgrade my OpenAI plugin to use OpenAPI 3.0.1 and to switch to the YAML format, but nothing changed.

**Expected behavior**
I didn't see any breaking change around OpenAI plugins (other than the new name of the method to import them), so I expect them to still work after upgrading to beta6.

**Platform**
 - OS: Windows
 - IDE: Visual Studio Code
 - Language: C#
 - Source: NuGet package, version 1.0.0-beta6

**Comment by alliscode** [comment]
Hi @qmatteoq, sorry about the issue you're experiencing. I believe the problem is that as of beta6, there is an import method specifically for OpenAPI specs which is used to load an OpenAPI spec directly (without an ai-plugin.json), and a separate import method for OpenAI plugins that use an ai-plugin.json.

Can you change `ImportOpenApiPluginFunctionsAsync` to `ImportOpenAIPluginFunctionsAsync` and let us klnow if that fixes your issue?

**Comment by qmatteoq** [comment]
Hello @alliscode , thanks for the support! I tried but it doesn't seem to work. I've changed the import code to:

```
const string openApiUrl = "https://semantickernel-unitedstatesdata.azurewebsites.net/api/swagger.json";
await kernel.ImportOpenAIPluginFunctionsAsync("UnitedStatesPlugin", new Uri(openApiUrl));
```

However, I'm getting now the following exceptions:

```
Exception has occurred: CLR/Microsoft.SemanticKernel.Diagnostics.SKException
An exception of type 'Microsoft.SemanticKernel.Diagnostics.SKException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Unexpected API type '' found in Open AI manifest.'
```

Moreover, I would like to understand better why my previous code doesn't work anymore. Shouldn't the ai-plugin.json manifest continue to be supported, so that Semantic Kernel can be fully compatible with OpenAI plugins?

Thanks!

**Comment by zaneduffield** [comment]
I also get this error when testing an OpenAI plugin with the latest commit in [microsoft/chat-copilot](https://github.com/microsoft/chat-copilot) (which is using SK beta6).

**Comment by jordanbean-msft** [comment]
I see this issue as well

**Comment by qmatteoq** [comment]
I'm truly sorry @alliscode, I realize only know what you meant. Indeed, I didn't catch the difference between OpenAI and OpenAPI in the name of the method, so I was using `ImportOpenApiPluginFunctionsAsync()` to import an OpenAI plugin. I switched to `ImportOpenAIPluginFunctionsAsync()` and now everything works as expected. Sorry for the trouble!

**Comment by jordanbean-msft** [comment]
agreed, this fixed the issue, I was playing with the Chat Copilot demo app and had to change the code to fix this.

**Comment by matthewbolanos** [comment]
Glad to hear this fixed the issue.
