### ISSUE TITLE
Python: Fix broken notebooks and update integration tests

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#3514]
Following notebooks are only partially working

1. `10-multiple-results-per-prompt.ipynb`
1. `11-streaming-completions.ipynb`

As part of this task integration tests must be extended to cover the scenarios covered by the notebooks.

Also configuration to use Azure should be set once in the .env file

**Comment by john0isaac** [comment]
I'm working on this
