### ISSUE TITLE
Any roadmap/plan for LLM Agent support?

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/semantic-kernel#3529]
As title

**Comment by matthewbolanos** [comment]
Yes! In fact, we're already started releasing an experimental package that leverages the OpenAI Assistants API to support agent scenarios. I'd recommend reading [this blog post](https://devblogs.microsoft.com/semantic-kernel/semantic-kernels-ignite-release-beta8-for-the-net-sdk/#start-developing-openai-assistants-with-semantic-kernel) to see the latest integration with assistants. Please give it a whirl and let us know what you think in the [discussion board](https://github.com/microsoft/semantic-kernel/discussions/3393) we created for it.

It's probably also worth sharing our overall plan for supporting agents (and multi-agent scenarios). We've written a series of blog posts that outline our current strategy and experiments that are influencing our future implementation with agents. If you're interested in reading more, check them out here:
- [OpenAI Assistants: The future of Semantic Kernel](https://devblogs.microsoft.com/semantic-kernel/assistants-the-future-of-semantic-kernel/)
- [OpenAI Assistants: A first look into using OpenAI Assistants with Semantic Kernel](https://devblogs.microsoft.com/semantic-kernel/assistants-a-first-look-into-using-openai-assistants-with-semantic-kernel/)
- [OpenAI Assistants: The power of templated assistants](https://devblogs.microsoft.com/semantic-kernel/openai-assistants-the-power-of-templated-assistant-instructions/)

**Comment by matthewbolanos** [comment]
I'm going to go ahead and close this issue since we currently have experimental support :)
