### ISSUE TITLE
.Net: Can we delete AggregatePartitionedResultsAsync?

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#3537]
It's a public extension method that only appears to be used by the ConversationSummaryPlugin.  Can it be moved to be a private member of ConversationSummaryPlugin?  A github search doesn't reveal any additional meaningful usage outside of SK, and this looks like a very niche helper.

**Comment by markwallace-microsoft** [comment]
Yes, that makes sense. I've marked it as urgent and assigned it to a sprint so it makes for v1.0 cut-off

**Comment by stephentoub** [comment]
I'll throw up a PR for it.

**Comment by stephentoub** [comment]
> I'll throw up a PR for it.

Scratch that, the extension depends on FunctionResult.Context, which isn't accessible in that assembly.  This will need to wait until @SergeyMenshykh's changes land.

**Comment by stephentoub** [comment]
I take that back. The conversation summary plugin is the only place it's used and doesn't rely on that support. Should be easy...
