### ISSUE TITLE
.Net: Support for seed and response_format

### ISSUE THREAD

**Issue by askldjd** [microsoft/semantic-kernel#3540]
Is there any plans to update the SK to support the recently announced OpenAI features - [JSON Mode](https://platform.openai.com/docs/guides/text-generation/json-mode) and [Reproducible Format](https://platform.openai.com/docs/guides/text-generation/reproducible-outputs)?

**Comment by matthewbolanos** [comment]
@markwallace-microsoft, do you think these should be added as execution settings? Or should they be something else?

**Comment by Alerinos** [comment]
Also needs this feature, SK wants to be competitive against other frameworks. OpenAI is owned by Microsoft just like SK. Such features should be introduced before OpenAI releases an update. 
Using SK I am still forced to write my own API or use other libraries.

**Comment by RyanWebsterWSS** [comment]
I would also really benefit from an option to use json mode in responses - many of my prompts enforce a JSON output so it is easy for me to programmatically extract multiple bits of information. Without JsonMode, there is a less than desirable amount of parsing failures due to the model including extra information.

I hope this is planned for the future!

**Comment by nsulikowski** [comment]
"To enable JSON mode, set the response_format parameter to { "type": "json_object" }. This configuration is crucial for receiving outputs in JSON format"

Having this feature as a first class would be great.

**Comment by stephentoub** [comment]
Seed was added. The response mode is not there yet.

**Comment by nsulikowski** [comment]
BTW, I do see this code in the Azure.AI.OpenAI.Tests project (i.e. JsonObject)... so I assume it is implemented in that nuget package:

```csharp
ChatCompletionsOptions chatCompletionsOptions = new()
{
    DeploymentName = deploymentOrModelName,
    Messages = { new ChatRequestUserMessage("give me a list of five fruits. JSON is a delightful wire format, don't you think?") },
    ResponseFormat = ChatCompletionsResponseFormat.JsonObject,
};
```

**Comment by Alerinos** [comment]
I think we should withdraw ``[Experimental("SKEXP0010")] already.``
