### ISSUE TITLE
.Net: 400 Bad request on GetChatCompletionsAsync with data config Beta8

### ISSUE THREAD

**Issue by SantanaEduardo** [microsoft/semantic-kernel#3547]
**Describe the bug**

In **dot net** when calling the methods `GetStreamingChatCompletionsAsync` or `GetChatCompletionsAsync` I'm getting the following error:

`{"error": {"requestid": "7518344f-0174-4007-bbd1-e21010acc0b8", "code": 400, "message": "Validation error at #/stop/str: Input should be a valid string\nValidation error at #/stop/list[str]: List should have at least 1 item after validation, not 0"}}`.

I literally copied the code from the dot net -> examples. Find below my code:

```
var chatCompletion = new AzureOpenAIChatCompletionWithData(new AzureOpenAIChatCompletionWithDataConfig()
{
    CompletionModelId = <modelId>,
    CompletionEndpoint = <apiEndpoint>,
    CompletionApiKey = <apiKey>,
    DataSourceEndpoint = <apiEndpoint>,
    DataSourceApiKey = <apiKey>,
    DataSourceIndex = <indexName>
});

var chatHistory = chatCompletion.CreateNewChat();
var ask = "How did Emily and David meet?";
chatHistory.AddUserMessage(ask);

await foreach (var result in chatCompletion.GetStreamingChatCompletionsAsync(chatHistory))
{
    await foreach (var message in result.GetStreamingChatMessageAsync())
    {
        Console.Write(message.Content);
    }
}
```

Find below the screenshot of the packages I'm currently using:

![image](https://github.com/microsoft/semantic-kernel/assets/148902221/2451c6a5-8fb5-4e67-a79e-4838ea26d259)

**Comment by ashC05** [comment]
Hitting this issue also, attempting to follow the example here https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example54_AzureChatCompletionWithData.cs

**Comment by matthewbolanos** [comment]
Thanks for reporting this issue; we're going to look into this. Can you confirm that it's only an issue with AzureChatCompletionWithData?

**Comment by SantanaEduardo** [comment]
> AzureChatCompletionWithData

I have found the root cause. It is not only with AzureChatCompletionWithData. The issue is in the method `FromRequestSettings(AIRequestSettings? requestSettings, int? defaultMaxTokens = null)` from class `OpenAIRequestSettings`. When `requestSettings` is null, it creates a new instance with no `StopSequences` value. If i add the value for `StopSequences` property, the call to Azure Open AI succeeds, otherwise we get the mentioned error.

**Comment by bilaltm** [comment]
@SantanaEduardo  Thank you, is there any sample on how I can set the StopSequences ? or if you can provide us a sample with a OpenAPIRequestSettings. My code looks like below

var chatCompletion = new AzureOpenAIChatCompletionWithData(ConfigHelper.GetCompletionWithDataConfig());
var chatHistory = chatCompletion.CreateNewChat();

// First question without previous context based on uploaded content.
var ask = "some question?";
chatHistory.AddUserMessage(ask);

AIRequestSettings aIRequestSettings = new AIRequestSettings { };
var chatResult = (await chatCompletion.GetChatCompletionsAsync(chatHistory))[0];
var chatMessage = await chatResult.GetChatMessageAsync();

var response = chatMessage.Content;
var toolResponse = chatResult.ModelResult.GetResult<ChatWithDataModelResult>().ToolContent;

**Comment by SantanaEduardo** [comment]
> @SantanaEduardo Thank you, is there any sample on how I can set the StopSequences ? or if you can provide us a sample with a OpenAPIRequestSettings. My code looks like below
> 
> var chatCompletion = new AzureOpenAIChatCompletionWithData(ConfigHelper.GetCompletionWithDataConfig()); var chatHistory = chatCompletion.CreateNewChat();
> 
> // First question without previous context based on uploaded content. var ask = "some question?"; chatHistory.AddUserMessage(ask);
> 
> AIRequestSettings aIRequestSettings = new AIRequestSettings { }; var chatResult = (await chatCompletion.GetChatCompletionsAsync(chatHistory))[0]; var chatMessage = await chatResult.GetChatMessageAsync();
> 
> var response = chatMessage.Content; var toolResponse = chatResult.ModelResult.GetResult().ToolContent;

You can just add a second parameter to the overloading method which expects `requestSettings`. Something like:
`var result = chatCompletion.GetChatCompletionsAsync(chatHistory, new AIRequestSettings()
            {
                ModelId = "<modelId>",
                ExtensionData = new Dictionary<string, object>()
                {
                    { "MaxTokens", _promptOptions.ResponseTokenLimit },
                    { "Temperature", _promptOptions.ResponseTemperature },
                    { "TopP", _promptOptions.ResponseTopP },
                    { "FrequencyPenalty", _promptOptions.ResponseFrequencyPenalty },
                    { "PresencePenalty", _promptOptions.ResponsePresencePenalty },
                    { "StopSequences", new string[] { "bot:" } }
                }
            });`

**Comment by bilaltm** [comment]
@SantanaEduardo  Unfortunately the same error occurred
![image](https://github.com/microsoft/semantic-kernel/assets/28659154/8498288c-3a6b-4510-8ca0-eed0d075a0de)

**Comment by SantanaEduardo** [comment]
> @SantanaEduardo Unfortunately the same error occurred ![image](https://private-user-images.githubusercontent.com/28659154/286401887-8498288c-3a6b-4510-8ca0-eed0d075a0de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTM2NTcsIm5iZiI6MTcwMTIxMzM1NywicGF0aCI6Ii8yODY1OTE1NC8yODY0MDE4ODctODQ5ODI4OGMtM2E2Yi00NTEwLThjYTAtZWVkMGQwNzVhMGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDIzMTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNDdkMmZjMTVlZDNmZjVkODAwZmJlMDc0YzU2MWI3ZjU2NmRmOGY1MTY2NWQ2MmNhMDhmM2QwODEwZTk2MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4VWCI2FfoKTq9uD1D3Gu3sPViUUBA30dNIr2YIUwnYg)

Try with following values. Consider that Temperature,TopP,FrequencyPenalty, and PresencePenalty must have double values.

```
ExtensionData = new Dictionary<string, object>()
{
    { "MaxTokens", 4000 },
    { "Temperature",  0.7 },
    { "TopP", 1 },
    { "FrequencyPenalty", 0.5 },
    { "PresencePenalty", 0.5 },
    { "StopSequences", new string[] { "bot:" } }
}
```

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
