### ISSUE TITLE
.Net: Refactor hooks support to match v1.0 design

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#3579]
The ultimate goal here is to get rid of FunctionInvokingHandler and FunctionInvokedHandler properties of SKContext so that when I remove the rest of properties we can easily drop SKContext class. We also need to have the hooks design extensible so that, as Matthew said yesterday, it's easy to add new hooks in future without breaking changes. That leads to the design where the hooks modeled as kernel properties and functions just call them on kernel instance that is passed to them through InvokeAsync method. Feel free to give me a call to discuss the details.
```[tasklist]
### Tasks
- [ ] Eliminate FunctionInvokingHandler and FunctionInvokedHandler
- [ ] Ensure new hooks can be easily added without introducing a breaking change
```

**Comment by matthewbolanos** [comment]
@markwallace-microsoft, has this already been completed?

**Comment by matthewbolanos** [comment]
Going to go ahead and mark as closed since the status is "done"; reopen if it's not done.
