### ISSUE TITLE
.Net: GetOpenAIFunctionResponse is not able to identify right Function intermittently

### ISSUE THREAD

**Issue by sanket-t-shah** [microsoft/semantic-kernel#3581]
**Describe the bug**
I've 2 Plugins each having a single function within, hosted on Azure BLOB Storage. These Prompts are attached with Semantic Kernel during initialization. Based on the user query, GetChatCompletionsAsync() should be able to identify the right Semantic Function to be invoked.

This functionality has a hit / miss ratio of 50% and most of the times, it's not able to identify function at all. To resolve this, need to restart code.

**To Reproduce**
1. Have multiple Plugins associated with Semantic Kernel.
2. Use Completions endpoint through GetChatCompletionsAsync() function for the fix query.
3. Check the value of GetOpenAIFunctionResponse(). It should return Function name to be invoked.
4. OpenAIFunctionResponse comes blank 50% of the time.

**Expected behavior**
Right Semantic Function to be invoked should be identified.

**Platform**
 Semantic Kernel Version: 1.0.0-beta8 (.NET)

**Comment by matthewbolanos** [comment]
Are you able to share the semantic information of the plugins/functions so we could try to reproduce? In particular...
- Function name
- Function descriptioin
- Function parameters

**Comment by matthewbolanos** [comment]
Closing this for the time being; please reopen if you have additional details to share.
