### ISSUE TITLE
.Net: Semantic Kernel GetFunction().Describe().Parameters doesn't return parameters always

### ISSUE THREAD

**Issue by sanket-t-shah** [microsoft/semantic-kernel#3583]
**Describe the bug**
We've a need to pass parameters to Semantic Function based on chat conversation flow. For doing the same, we are trying to get list of parameters through code `_Kernel.Functions.GetFunction("PluginName", "FunctionName").Describe().Parameters`. This list is not returned consistently (~80%).

**To Reproduce**
1. Get Plugin Name and Function Name through GetOpenAIFunctionResponse() function.
2. Try to get Function Parameters using `_Kernel.Functions.GetFunction("PluginName", "FunctionName").Describe().Parameters`.
3. Check value of Parameters.

**Expected behavior**
Semantic Function Parameters should be returned consistently.

**Platform**
Semantic Kernel: 1.0.0-beta8 (.NET)

**Comment by matthewbolanos** [comment]
Can you confirm that you are explicitely describing the parameters in the PromptTemplateConfig object? We recently made a change where we no longer automatically retrieve the parameters from the template because we could not support it for all templating languages (e.g., Handlebars)

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
