### ISSUE TITLE
.Net: SKFunction cancellation

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#3586]
Considering that the pre/post hook functionality will be implemented by the SKFunction class, it is essential to ensure a suitable model for handling function execution cancellation scenarios.

The function caller requires a method to determine if the function was cancelled due to a pre/post hook. This can be represented as an IsCancelled property of the FunctionResult class, or the function can throw an OperationCancelledException.

If we choose to represent it using the OperationCancelledException and need to differentiate between natural cancellations, such as a timeout, and user-initiated cancellations, we can consider using a custom exception called SKFunctionCancelledException.

We should avoid modeling the cancellation by simply returning null from InvokeAsync or returning an instance of the FunctionResult class with a null value, as this would not allow for distinguishing between cancellations and cases where the function naturally returns null.

CC: @markwallace-microsoft @RogerBarreto @stephentoub

**Comment by RogerBarreto** [comment]
When thinking about adding a property consider it to be an enum or a complex type se we can know 
Things like:

| Status    | Reason                  |
|-----------|-------------------------|
| Cancelled | Pre Hook Cancellation   |
| Skipped   | Pre Hook Skip Triggered |
| Succeeded | Function Executed       |
| Failed    | Function Failed         |
| Timedout  | Function Timed out      |

**Comment by stephentoub** [comment]
This was done
