### ISSUE TITLE
AttributeError: 'KernelConfig' object has no attribute 'add_openai_completion_backend'

### ISSUE THREAD

**Issue by ihoment-lys** [microsoft/semantic-kernel#361]
**Describe the bug**
AttributeError: 'KernelConfig' object has no attribute 'add_openai_completion_backend'

**To Reproduce**
Use the python-preview branch to execute kernel.config.add_openai_completion_backend and report an error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/73272214/230536563-1b1ff30f-d8e2-47d1-80a9-a50c7d124dc8.png)
**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by dluc** [comment]
@ihoment-lys we've update the kernel API to support any model so some methods now have a more generic name. Could you try this?

> kernel.config.add_text_backend(...)

See also the examples in the README here https://github.com/microsoft/semantic-kernel/blob/python-preview/python/README.md

**Comment by ihoment-lys** [comment]
Running a simple prompt, the error is as follows
![image](https://user-images.githubusercontent.com/73272214/230812009-7f6323c9-7fac-46ed-b5eb-b52d6f2bab89.png)

**Comment by dluc** [comment]
@ihoment-lys could you include the code to reproduce the error?

**Comment by ihoment-lys** [comment]
After the code was updated to the latest version, the problem has been solved Illegal thank you
