### ISSUE TITLE
Disable all unwanted functions in creating `PlannerSkill`

### ISSUE THREAD

**Issue by tynguyen** [microsoft/semantic-kernel#362]
**Describe the bug**

I created a semantic function that summarizes given input  and returns outputs in JSON, for example: 
_**Input**_
I am single mom and working full-time. Do I qualify for any tax credits? 
_**Expected output**_
{
"subject": "first person",
"descriptions": ["female", "work full-time", "single mom"],
"purpose": "tax credit benefits" 
}

**Issue**
However, it always fails due to `BucketOutputs` function which is, by default, included at the end of a plan.
![image](https://user-images.githubusercontent.com/5508237/230602295-5c484297-6490-4de1-834e-79d5d4fc1a79.png)

![image](https://user-images.githubusercontent.com/5508237/230602375-bdc812b7-0ed8-4768-b5d7-aad2cde8e2c9.png)

 I tried to set `Parameters.BucketCount` to be `"1"` but it did not work (known in https://github.com/microsoft/semantic-kernel/issues/345) 
If I exclude this `BucketOutputs` function by setting `Parameters.ExcludedFunctions` to be `BucketOutputs`, another issue occurs

**_GLOBAL_FUNCTIONS_.Length causes this issue**
![image](https://user-images.githubusercontent.com/5508237/230601363-490002d2-b334-407a-857b-fd021f95b05b.png)
**Issue because of _GLOBAL_FUNCTIONS_.Length**
![image](https://user-images.githubusercontent.com/5508237/230601190-89e26823-fc25-462b-ae8c-1da21ba89d73.png)

What do you think a good solution for this? 
Should we enable developers to create a planner with only `skills` that they want?

**Comment by lemillermicrosoft** [comment]
What model are you using? While we are striving to make things functional with GPT3.5 the target for these scenarios is really GPT4.

We'll be removing the BucketOutputs function -- if this functionality is needed in a plan developers will need to supply their own skill.

**Comment by tynguyen** [comment]
@lemillermicrosoft : I’m using ‘text-devinci-03’.

**Comment by RogerBarreto** [comment]
## This is a temporary approach and we will keep looking into the issue. 

Hi @tynguyen as a temporary solution you can Override skills using this approach. Sometimes just improving the description (Attribute) of Function can have the desirable outcome.

i.e:
```
public class OverrideSkill
{
    private readonly PlannerSkill _plannerSkill;

    [SKFunction("This successfully overrided the Bucket skill.")]
    [SKFunctionName("BucketOutputs")]
    [SKFunctionInput(Description = "The output from a function that needs to be parse into buckets.")]
    [SKFunctionContextParameter(Name = PlannerSkill.Parameters.BucketCount, Description = "The number of buckets.",
        DefaultValue = "")]
    [SKFunctionContextParameter(
        Name = PlannerSkill.Parameters.BucketLabelPrefix,
        Description = "The target label prefix for the resulting buckets. " +
                      "Result will have index appended e.g. bucketLabelPrefix='Result' => Result_1, Result_2, Result_3",
        DefaultValue = "Result")]
    public async Task<SKContext> BucketOutputsAsync(string input, SKContext context)
    {
        return await this._plannerSkill.BucketOutputsAsync(input, context);
    }

    public OverrideSkill(IKernel kernel, int maxTokens = 1024)
    {
        this._plannerSkill = new PlannerSkill(kernel, maxTokens);
    }
}

kernel.ImportSkill(new OverrideSkill(kernel));
```


Regarding the Length error, try adding the Core TextSkill to the kernel. 
```
kernel.ImportSkill(new TextSkill());
```

**Comment by tynguyen** [comment]
that works. Great thanks, @RogerBarreto
