### ISSUE TITLE
chat-summary-webapp-react cannot save the settings for Azure OpenAI

### ISSUE THREAD

**Issue by yanxiaodi** [microsoft/semantic-kernel#363]
**Describe the bug**
I'm running the chat-summary-webapp-react demo app but cannot save the settings.

The first problem is that we need to rename `.env.example` as `.env`, which is not clear in the documents.

But still cannot save the settings.

**To Reproduce**
1. Go to 'http://localhost:7071'
2. Choose Azure OpenAI
3. Type the key, deployment name, and endpoint
4. Click on 'Save'
6. See errors "ModelNotAvailable", "Unauthorized". Sometimes can list the deployed models but cannot save the settings, e.g. "Model xxx not available on xxx endpoint"

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3395915/230606286-fe115c5c-7f1d-4c17-a0e2-700fa427b016.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IDE: VS Code
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by dluc** [comment]
@craigomatic @hathind-ms

**Comment by microsoftShannon** [comment]
We're looking at this one now.

**Comment by evchaki** [comment]
@yanxiaodi - are you still having this issue?  cc: @craigomatic

**Comment by yanxiaodi** [comment]
@evchaki I'll try it today and let you know. Thanks!

**Comment by yanxiaodi** [comment]
@evchaki it works now. I think it works only with `text-davinci-003`? I tried gpt-4 but got an error:
![image](https://github.com/microsoft/semantic-kernel/assets/3395915/f5c2b9f7-ec74-4db3-a834-2ecbee39372b)
![image](https://github.com/microsoft/semantic-kernel/assets/3395915/4e5a133f-669c-4cef-98e6-cb3acda49692)

Is it expected? Thanks.

**Comment by craigomatic** [comment]
We just updated the samples to support chat completion models, ie: gpt35 turbo and gpt4 with PR #1279 so if you pull the latest code you should be able to get it to work with gpt4.

I will close this for now as it appears the original issue was resolved. Please reopen if needed!
