### ISSUE TITLE
Python: Chinese Windows Encoding Must Use GBK

### ISSUE THREAD

**Issue by Claireluyingling** [microsoft/semantic-kernel#3643]
**Describe the bug**
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8a in position 2: illegal multibyte sequence

**To Reproduce**
The general encoding uses utf8, but the Chinese Windows system seems to need to change the encoding to GBK to run properly.

**Expected behavior**
Adapt the Chinese Windows utf8 encoding format.

![Error](https://github.com/microsoft/semantic-kernel/assets/91041009/e1652a38-5630-49f1-8ecd-acc9f588d9ec)
![GBK](https://github.com/microsoft/semantic-kernel/assets/91041009/16106d34-e123-419f-a179-388ffda52a2f)

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: Python

**Comment by moonbox3** [comment]
Closing this issue as it is stale. Please recreate an issue if you continue to have a problem. Thanks.

**Comment by sakesun** [comment]
On Windows, set environment variable "PYTHONUTF8" = "1" to workaround this problem.
