### ISSUE TITLE
.Net: Multi Modality Support

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#3675]
## Semantic Kernel should be extensible to support Multi Modal AIServices.

This issue includes all work needed to get a plan and implementation to a stable and extensible API to support Multi Modality.

- ADR Preparation
- Rethink ITextCompletion, IChatCompletion, IImageGeneration into one singular and abstract `IAIService`
- Abstractions that can represent any type, including value and complex types.
- Streaming and NonStreaming abstraction support should also be considered in the design.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
