### ISSUE TITLE
Python: OpenAI Python Library dependency

### ISSUE THREAD

**Issue by afbarbaro** [microsoft/semantic-kernel#3684]
What's the plan to support the v1 of the ([OpenAI Python Library](https://github.com/openai/openai-python)). The project that I'm working on uses both SK and OpenAI but SK only allows old versions as its dependencies (>=0.27,<=0.29)

**Comment by alexchaomander** [comment]
This is being worked on here! https://github.com/microsoft/semantic-kernel/pull/3555

**Comment by matthewbolanos** [comment]
Closing as a duplicate!
