### ISSUE TITLE
.Net: Audit use of interfaces vs concrete collection types in public surface area for consistency

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#3698]

**Comment by markwallace-microsoft** [comment]
Review use of collection interfaces versus concrete collection types to ensure we are being consistent.

**Comment by RogerBarreto** [comment]
Verified across the whole code base. Didn't find any

**Comment by stephentoub** [comment]
> Verified across the whole code base. Didn't find any

What didn't you find?

**Comment by stephentoub** [comment]
Add an example, PromptTemplateConfig uses List:
https://github.com/microsoft/semantic-kernel/blob/6ad5d2662c170fbd9ecb8bdc96ee920a9cff5e24/dotnet/src/SemanticKernel.Abstractions/PromptTemplate/PromptTemplateConfig.cs#L55
while OpenAIPromptExecutionSettings uses IList:.
https://github.com/microsoft/semantic-kernel/blob/6ad5d2662c170fbd9ecb8bdc96ee920a9cff5e24/dotnet/src/Connectors/Connectors.OpenAI/OpenAIPromptExecutionSettings.cs#L59
Is there a good reason for the difference?
