### ISSUE TITLE
.Net: Implement proper batching for PostgreSQL batch vector insert

### ISSUE THREAD

**Issue by georg-jung** [microsoft/semantic-kernel#3705]
### Motivation and Context

The current implementation of `Microsoft.SemanticKernel.Connectors.Memory.Postgres.PostgresMemoryStore`'s `IAsyncEnumerable<string> UpsertBatchAsync(string collectionName, IEnumerable<MemoryRecord> records, CancellationToken cancellationToken)` does not use proper batching, despite the name suggests. Instead, it uses the same logic as `UpsertAsync` but in a `foreach` loop.

  1. Why is this change required?
    i. The current implementation results in mediocre performance.
    ii. One point of using PostgreSQL as a vector store is ACID. The current implementation is not transactional in nature.
  2. What problem does it solve?
    i. The proposed batching implementation improves performance and is transactional.
  3. What scenario does it contribute to?
    i. Using PostgreSQL as a vector database.
  4. ~~If it fixes an open issue, please link to the issue here.~~

---

I already have an implementation ready: <https://github.com/microsoft/semantic-kernel/compare/main...georg-jung:semantic-kernel:postgres-batch-insert?expand=1>

It would however add an API and change the existing behaviour. Thus, I decided to create this issue first instead of a PR in line with the contribution guidelines.

Added API: `IPostgresDbClient.cs`

```diff
     /// <summary>
     /// Upsert entry into a table.
     /// </summary>
     /// <param name="tableName">The name assigned to a table of entries.</param>
     /// <param name="key">The key of the entry to upsert.</param>
     /// <param name="metadata">The metadata of the entry.</param>
     /// <param name="embedding">The embedding of the entry.</param>
     /// <param name="timestamp">The timestamp of the entry. Its 'DateTimeKind' must be <see cref="DateTimeKind.Utc"/></param>
     /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
     /// <returns></returns>
     Task UpsertAsync(string tableName, string key, string? metadata, Vector? embedding, DateTime? timestamp, CancellationToken cancellationToken = default);

+    /// <summary>
+    /// Upsert entries into a table.
+    /// </summary>
+    /// <param name="tableName">The name assigned to a table of entries.</param>
+    /// <param name="entries">The entries to upsert in a batch operation.</param>
+    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
+    /// <returns></returns>
+    Task UpsertBatchAsync(string tableName, IEnumerable<PostgresMemoryEntry> entries, CancellationToken cancellationToken = default);
```

Changed behaviour:
* In the current implementation of `PostgresMemoryStore.UpsertBatchAsync`, the entries are upserted ony-by-one while the consumer asynchronously enumerates the `IAsyncEnumerable<string>` return value.
  * In my proposed implementation, the entries would be upserted in one batch (as the name suggests). The first value of the `IAsyncEnumerable` is returned after the batch insertion already completed.
  * In the existing implementation, one could break the enumeration and thus just insert some of the batch's entries.
  * In the existing implementation, if inserting one of the entries fails, all entries that have been inserted before persist in the database.  In my proposed implementation, either all or none of the batch's entries will be inserted.
  * I think the proposed behaviour is similar to what `QdrantMemoryStore.UpsertBatchAsync` does.
  * I think this is in line with what one would except from an `UpsertBatch` command against a DBMS like Postgres.

---

### Results

I performed some simple benchmarks to measure the impact of my changes. They suggest my proposed batch inserting code results in a 10-50x speedup as well as a 10-fold reduction of memory usage when inserting 1k vectors. My benchmark setup is available [here](https://github.com/georg-jung/SemanticKernelBenchmarkPostgresBatchInsert).

Results from a GitHub Actions runner can be seen [here](https://github.com/georg-jung/SemanticKernelBenchmarkPostgresBatchInsert/actions/runs/7005427316/job/19055135965).

<details>
<summary>GitHub Actions benchmark results (10x speedup)</summary>

    // * Summary *

    BenchmarkDotNet v0.13.10, Ubuntu 22.04.3 LTS (Jammy Jellyfish)
    AMD EPYC 7763, 1 CPU, 4 logical and 2 physical cores
    .NET SDK 8.0.100
      [Host] : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2
      After  : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2
      Before : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2

| Method | Job    | BuildConfiguration | Mean      | Error     | StdDev   | Median    | Allocated  |
|------- |------- |------------------- |----------:|----------:|---------:|----------:|-----------:|
| Insert | After  | LocalBuild         |  51.03 ms |  1.418 ms | 4.069 ms |  49.41 ms |  492.39 KB |
| Insert | Before | Default            | 556.18 ms | 10.228 ms | 9.567 ms | 555.52 ms | 4914.77 KB |

    // * Warnings *
    MultimodalDistribution
      Benchmarks.Insert: After -> It seems that the distribution can have several modes (mValue = 2.89)
</details>

I also performed these benchmarks on my local machine, where the impact was even bigger:

<details>
<summary>Local benchmark results (47x speedup)</summary>

    // * Summary *

    BenchmarkDotNet v0.13.10, Windows 11 (10.0.22631.2715/23H2/2023Update/SunValley3)
    AMD Ryzen 7 PRO 4750U with Radeon Graphics, 1 CPU, 16 logical and 8 physical cores
    .NET SDK 8.0.100
      [Host] : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2
      After  : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2
      Before : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2

| Method | Job    | BuildConfiguration | Mean       | Error     | StdDev    | Gen0      | Allocated  |
|------- |------- |------------------- |-----------:|----------:|----------:|----------:|-----------:|
| Insert | After  | LocalBuild         |   121.0 ms |   3.52 ms |  10.15 ms |         - |  497.16 KB |
| Insert | Before | Default            | 5,761.0 ms | 114.58 ms | 140.72 ms | 2000.0000 | 4994.88 KB |

    // * Warnings *
    MultimodalDistribution
      Benchmarks.Insert: After -> It seems that the distribution can have several modes (mValue = 3)

</details>

---

### Further thoughts

* My benchmarks currently just cover a quite simple scenario. They insert the same 512-dimensional vector with values [0, 1, 2, ...] exactly 1k times. Results may vary depending on vector dimensionality, number of vectors inserted, existing indices on the target table as well as distribution of vectors in vector space.
* I think there is more about `PostgresMemoryStore` that could be optimized. Some of that could be easier if the [`Pgvector`](https://www.nuget.org/packages/Pgvector) dependency is upgraded to `0.2.0`.

**Comment by georg-jung** [comment]
@matthewbolanos Not sure how your backlog etc. is exactly organized, I just noticed there is a "Community PRs" bucket and it does contain at least one issue (not a PR). Thus, just in case that isn't obvious, I just wanted to mention that my implementation of what I outlined above is already [finished](https://github.com/microsoft/semantic-kernel/compare/main...georg-jung:semantic-kernel:postgres-batch-insert?expand=1). I didn't create a PR right away though because that's what the contribution guideslines suggest.

If you already triaged the issue, does it make sense to send a PR at this point?

I guess if your team looks at the backlog to decide what becomes part of an upcoming sprint, it might not be immediatly clear that this issue isn't an implementation task but rather a review task 🤔.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.

**Comment by georg-jung** [comment]
Yes, I think this is still relevant. It looks like the current Semantic Kernel .NET 1.x pgvector connector still does not implement proper batching.
