### ISSUE TITLE
Python: move to python standard logging approach

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/semantic-kernel#3711]
SK currently does not use the standard approach to logging compared to python best practices and many other packages, where each file that needs to log creates a logger and uses it in code, instead it is passing around a object or when nothing is passed creating a NullLogger, this should not be the way. 

Preferred is, at the top of every file that needs it:
```python
import logging
log: logging.Logger = logging.getLogger(__name__)
```
Potentially with something like this to control log levels based on env and for specific subpackages (some packages are very chatty): https://github.com/openai/openai-python/blob/9f828cb1ea7c22a6388fcd71b5de1a0dde3a9a9f/src/openai/_utils/_logs.py#L16

**Comment by juliomenendez** [comment]
I can give this change a try if nobody else is working on it.

**Comment by juliomenendez** [comment]
@eavanvalkenburg I made the changes for this issue. Happy to work with you through any feedback you might have on it.

**Comment by xiazhengtao** [comment]
It seems like you're suggesting a more standard and centralized approach to logging in your project, aligning with Python best practices. Indeed, using a logger per module or class can be a clean and scalable way to handle logging. Here's how you can structure your logging in a more conventional manner:

1. **Import Logging Module:**
   Import the logging module at the top of each file that needs to log.

   ```python
   import logging
   ```

2. **Create Logger Object:**
   At the top of each file, create a logger object specific to that module using `getLogger(__name__)`.

   ```python
   log: logging.Logger = logging.getLogger(__name__)
   ```

3. **Configure Logging (Optional):**
   You can configure the logging behavior globally based on your environment or specific requirements. This can include setting log levels, adding handlers, or configuring formatters.

   ```python
   logging.basicConfig(level=logging.DEBUG)
   ```

4. **Usage in Code:**
   Use the logger (`log` in this case) to log messages throughout the code.

   ```python
   log.debug("This is a debug message")
   log.info("This is an info message")
   log.warning("This is a warning message")
   log.error("This is an error message")
   log.critical("This is a critical message")
   ```

   The benefit of this approach is that you can control the logging level at a more granular level. For example, you can set the logging level for a specific module or package independently.

   ```python
   logging.getLogger("your_module").setLevel(logging.DEBUG)
   ```

   Additionally, you can use environment variables or configuration files to control logging behavior.

   ```python
   import os

   log_level = os.getenv("LOG_LEVEL", "INFO")
   logging.basicConfig(level=logging.getLevelName(log_level))
   ```

Remember that consistency in logging practices across your project makes it easier to manage and understand. This approach also allows for better control over logging behavior, making it adaptable to different environments and needs.
