### ISSUE TITLE
Python: pythonic naming

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/semantic-kernel#3713]
---
name: Feature request
about: Suggest an idea for this project

---

I noticed that many names in the python version are based on the three c# version and they seem quite un-pythonic, some examples: ParameterView (call it what it is: Parameter) and the whole skill collection setup with a readonly version, which to me never seemed necessary in python. 

It would make the developer experience much better when moving to naming and structure that is more pythonic!

**Comment by matthewbolanos** [comment]
@eavanvalkenburg, we should grab some time with you and @moonbox3 to review the naming for all of the classes / methods now that we are close to finishing up the renmaing in C#. I'll grab some time to review next week.

**Comment by moonbox3** [comment]
We're handling this as of v1-beta. Tracking other smaller issues from this conversation as individual work items. Closing this work item.
