### ISSUE TITLE
.Net: In FunctionCallingStepWise planner, replace chat completion calls with KernelFuntion

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3734]
Ensure that the prompt functions are generic enough to support function calling. Once it is, leverage prompt functions to make the necessary chat completions for the plan generation and run step promopts.

This will allow developers to adjust model and execution settings with the AISelectionService and also ensure that our Handlebars template engine is generic enough.

**Comment by gitri-ms** [comment]
@matthewbolanos @markwallace-microsoft - Should we remove the v1 tag on this? Since I believe we've punted the remaining work on this item.

**Comment by matthewbolanos** [comment]
Yes, that's a good idea!
