### ISSUE TITLE
"Haiku" in readme has too many syllables

### ISSUE THREAD

**Issue by flarn2006** [microsoft/semantic-kernel#375]
// Output => Robots protect us all
//           No harm to humans they bring
//           Peaceful coexistence

That’s 6-7-6. A haiku is 5-7-5. Not the best example to showcase this technology; reminds me of Google’s botched Bard announcement.

**Comment by alexchaomander** [comment]
This is a good catch! Thank you for finding it!

**Comment by dluc** [comment]
LLMs and math :-) we'll update the docs soon, thanks for the report!
