### ISSUE TITLE
.Net: Bug: dotnet README Instructions Invalid

### ISSUE THREAD

**Issue by JasonMCreighton** [microsoft/semantic-kernel#3750]
**Describe the bug**
The OpenAIPromptExecutionSettings object is not available. 

**To Reproduce**
1. Install Microsoft.SemanticKernel from nuget (defaults to 1.0.0-beta8)
2. Copy code into IDE
3. See error

**Expected behavior**
The README code should execute with minimal changes

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: 1.0.0-beta8

**Additional context**
Pull request attached

**Comment by matthewbolanos** [comment]
Everything is up-to-date in the repo. We'll be publishing this class later today when we publish our release candidate to NuGet
