### ISSUE TITLE
.Net KernelFunctionArguments cleanup

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#3761]
This task tracks feedback to address provided on the https://github.com/microsoft/semantic-kernel/pull/3752 PR:
- ~~Make FunctionResult immutable - https://github.com/microsoft/semantic-kernel/pull/3770~~
- ~~Consider making the 'arguments' parameter of the IPromptTemplate.RenderAsync optional - https://github.com/microsoft/semantic-kernel/pull/3773~~
- ~~Pass Kernel to FunctionResult instead of CultureInfo - https://github.com/microsoft/semantic-kernel/pull/3779~~
- ~~Consolidate the GetTypeConverter method into a shared file to use by both KernelFunctionFromMethod and FunctionResult class - https://github.com/microsoft/semantic-kernel/pull/3860~~.
- ~~Decide what to do with the public const string InputParameterName = "input" property - https://github.com/microsoft/semantic-kernel/issues/3887~~.
- ~~Rename KernelFunctionArguments into KernelArguments - https://github.com/microsoft/semantic-kernel/pull/3769~~
- ~~Use the KernelArguments class instead of IDictionary<string, string> - https://github.com/microsoft/semantic-kernel/pull/3776/files~~
- ~~Make sure the syntax of supplying KernelFunctionArguments is supported:
      var result = await kernel.InvokeAsync(textPlugin["AppendDay"], new()
      {
          ["input"] = "Today is: ",
          [ "day"] = DateTimeOffset.Now.ToString("dddd", CultureInfo.CurrentCulture),
      }); - https://github.com/microsoft/semantic-kernel/pull/3985/files~~

**Comment by matthewbolanos** [comment]
Closing issue since its status is marked "done"
