### ISSUE TITLE
Typo in `ConnectAsync` (Connectors.Memory.Sqlite/Database.cs)

### ISSUE THREAD

**Issue by tynguyen** [microsoft/semantic-kernel#379]
https://github.com/microsoft/semantic-kernel/blob/1e72692591a49a129d37820ef7f899b34842cf0c/dotnet/src/Connectors/Connectors.Memory.Sqlite/Database.cs#L26

Should it be 
`
var connection = new SqliteConnection($"Data Source={filename};");  
`
instead?

**Comment by dluc** [comment]
@shawncal
