### ISSUE TITLE
.Net: Kernel Syntax Examples: Add option to run from Terminal in README

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/semantic-kernel#3790]
**Describe the bug**
The README under the KernelSyntaxExamples lists a couple of options to run the examples. But it doesn't include the option to run it from the terminal, which is a common use case.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by Siddharth1605** [comment]
I'd like to work on this task/issue, can anyone assign it to me
