### ISSUE TITLE
.Net: Example61_MultipleLLMs - Unclear which model is being used 

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/semantic-kernel#3798]
**Describe the bug**
> A clear and concise description of what the bug is.

The name says the first model should be used, but it's unclear which model is actually being used in RunByFirstModelIdAsync.
 ![image](https://github.com/microsoft/semantic-kernel/assets/125500434/776e934d-e0a6-4e4b-99f6-ed128e1afbf9)

Also, when running by model Id, say the user has configured gpt-4 with both AOI and OI, which one would be selected? 
![image](https://github.com/microsoft/semantic-kernel/assets/125500434/70e5d94b-8ddb-442e-98fb-938a9373dc7f)

**To Reproduce**
> Steps to reproduce the behavior:

```
dotnet user-secrets set "OpenAI:ApiKey" "..."
dotnet user-secrets set "OpenAI:ModelId" "gpt-3.5-turbo"

dotnet user-secrets set "AzureOpenAI:ChatDeploymentName" "..."
dotnet user-secrets set "AzureOpenAI:Endpoint" "https://... .openai.azure.com/"
dotnet user-secrets set "AzureOpenAI:ApiKey" "..."
dotnet user-secrets set "AzureOpenAI:ChatModelId" "gpt-35-turbo"
```

Run Example61 in KernelSyntaxExamples

**Expected behavior**
> A clear and concise description of what you expected to happen.

Currently, result just prints out the models that were added to execution settings. 

![image](https://github.com/microsoft/semantic-kernel/assets/125500434/3ffb7029-6860-4445-8d31-3d1cfd069f5d)

Maybe add some lines where we parse the Kernel to see the executing model and write to Console?

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: VS Code Terminal
 - Language: C#
 - Source: V1 Release Candidate Bug Bash

**Additional context**

Why are the first two samples using `InvokePromptAsync` but the last one creates a `PromptTemplateConfig` and then uses the kernel to invoke the function? 
![image](https://github.com/microsoft/semantic-kernel/assets/125500434/ded8acb4-e1f0-4e22-a1ed-3c9011751c48)

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
