### ISSUE TITLE
.Net: PostgresMemoryStore throws Method not found exception when used with Npgsql 8 / Pgvector 0.2

### ISSUE THREAD

**Issue by njallain** [microsoft/semantic-kernel#3803]
When PostgresMemoryStore is created with an NpgsqlDataSource from Npgsql 8.0, searching will throw an exception:

`System.MissingMethodException: Method not found: 'Void Pgvector.Vector..ctor(Single[])'.`

- create a project with dependencies on Npgsql 8 and Pgvector 0.2.0
- create an NpgsqlDataSource and configure it with UseVector()
- create PostgresMemoryStore using the data source
- run any search with the memory store

**Platform**
 - OS: Mac/Linux
 - IDE: VS Code
 - Language: C#
 - Source: Nuget package 1.0.0-beta8

**Comment by rogeriorfp** [comment]
The Vector(float[]) constructor was removed, the only available now are Vector(ReadOnlyMemory<float>) and Vector(string). So on line 173 of PostgresMemoryStore.cs file the call for the method GetOrCreateArray could be removed, but the pgvector version must be updated to 0.2.0

**Comment by crickman** [comment]
Thank you @rogeriorfp - looking at the package update now.

**Comment by crickman** [comment]
I'm seeing the array implicitly converted to `ReadOnlyMemory`, I don't believe a code change is necessary.

<img width="603" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/66376200/1185a0ac-f210-4b6d-b70e-88a4eff01e79">

**Comment by crickman** [comment]
@njallain - I'm not sure if this is relevent, but it may be worth double checking: The SK memory connector defines its own schema.

If configuring your data-source introduces a different schema, there might be compatibility issues.

**Comment by rogeriorfp** [comment]
> I'm seeing the array implicitly converted to `ReadOnlyMemory`, I don't believe a code change is necessary.
> 
> <img alt="image" width="603" src="https://private-user-images.githubusercontent.com/66376200/290026411-1185a0ac-f210-4b6d-b70e-88a4eff01e79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Mjk5NzcsIm5iZiI6MTcwMjQyOTY3NywicGF0aCI6Ii82NjM3NjIwMC8yOTAwMjY0MTEtMTE4NWEwYWMtZjIxMC00YjZkLWI3MGUtODhhNGVmZjAxZTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAxMDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMWRlYzc0ZGQ3ODQ2ZTgwYWU5NWI1ZjljYzFhMGE2NWU1MmRlNjMzZDZlNTMxMTE4MWQ3MzE5M2U3ZDdiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gv9lypZWjrLVqGiqXNzQ5Q-e4JztI4H9uJGpsqUQV1g">

I didn't know that. Thanks!
