### ISSUE TITLE
.Net: Name Function rather than Prompt Template

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/semantic-kernel#3805]
I think it would make more sense to name the Function rather than the prompt template
 
![image](https://github.com/microsoft/semantic-kernel/assets/125500434/d24769eb-7874-4ef5-bfef-7d2edf87cc5a)
 
It's not clear that the `Name` property in `PromptTemplateConfig` ties to the Function until you drill down to the comments, so maybe change this property key to "FunctionName"
![image](https://github.com/microsoft/semantic-kernel/assets/125500434/0a79881b-44dc-4b0f-95a4-a8c3efb8f20c)

**Comment by matthewbolanos** [comment]
We _may_ rename the property to FunctionName, _but_ we need to keep the JsonPropertyName "name" because it needs to align with the prompt schema. This _may_ cause confusion, so @markwallace-microsoft is going to have a think about it.

**Comment by matthewbolanos** [comment]
Going to close this since we believe it'll be confusing if the JSON property is different than the class property
