### ISSUE TITLE
.Net: Improve error handling in Example26_AADAuth

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#3809]
When running Example26_AADAuth, if the authenticated user does not have access to the resource, the output from the example is:

`exited with code -1.`

If one is debugging this example from Visual Studio then it's easy enough to understand the issue, but if running from the command line then this is insufficient. We should catch any error and print the message to the console.

**Comment by glahaye** [comment]
The console actually DOES print ample error information.  Closing.
