### ISSUE TITLE
.Net: Example60_AdvancedMethodFunctions.cs - improve clarity

### ISSUE THREAD

**Issue by gitri-ms** [microsoft/semantic-kernel#3824]
At first glance, this example contains a single method call and all of the code hidden away in regions. Should move the code from `MethodFunctionsChainingAsync` into the main `RunAsync` method.

I wonder if this sample was originally intend to show multiple different "advanced" features and then simplified to just one (chaining). Might want to rename to reflect that, e.g. `Example60_NativeFunctionChanging`.

Also the term "native function" should be used instead of "method function".

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
