### ISSUE TITLE
.Net: KernelSyntaxExamples should not require ModelId to be configured.

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#3826]
Chat based completions use the `ChatModelId` configuration and not-chat based completions use `ModelId`. Since we are no longer using non-chat based completions, we should not require a `ModelId` to be configured.

**Comment by markwallace-microsoft** [comment]
This issue will be fully resolved by this PR https://github.com/microsoft/semantic-kernel/pull/4284
