### ISSUE TITLE
.NET: Kernel syntax Example 07: Need Google resource to run

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/semantic-kernel#3831]
**Describe the bug**
Example 07 requires a Google resource to run, which we don't have. Worth documenting where devs can create one.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
