### ISSUE TITLE
.Net: Example30_ChatWithPrompts.cs - needs updating

### ISSUE THREAD

**Issue by gitri-ms** [microsoft/semantic-kernel#3838]
- TLDR code snippet in comments is out of date, should be removed
- This example uses the ChatCompletion object. Do we want to remove that, since it is not the recommended way of running prompts?

**Comment by gitri-ms** [comment]
There are also several references in the comments to the resource files, e.g. `28-system-prompt.txt` -- the `28` should be changed to `30`

**Comment by glahaye** [comment]
The code snippet in the comments is already gone.

I fixed the file names in comments in #4459 

As for ditching the ChatCompletion object and using kernel.InvokeAsync() instead, it feels it would take away from what the sample is trying to illustrate. @matthewbolanos Comments on this?
