### ISSUE TITLE
.Net: FunctionMetadata isn't populating PluginName 

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/semantic-kernel#3855]
**Describe the bug**

PluginName isn't populated in Function.Metadata in kernel object (see screenshot below) though Plugin.Name is populated at the top level.

**To Reproduce**
1. Run Example65_HandlebarsPlanner in KernelSyntaxExamples
2. Put a breakpoint at line 95 (after plugin import)
3. Inspect the kernel.Plugins[0].Functions[0]
4. Look at the `Metadata` property

**Expected behavior**

PluginName should be populated in Function.Metadata

It's populated when you explicitly call `GetFunctionsMetadata`, but I would expect this would be initialized when the function is created.
![image](https://github.com/microsoft/semantic-kernel/assets/125500434/adf83718-d10a-4d3a-a870-435cfccde306)

**Screenshots**

![image](https://github.com/microsoft/semantic-kernel/assets/125500434/837627e7-cc0b-40f3-b1e9-9a3c5bc1aef5)

**Platform**
 - OS: Windows
 - IDE:VS Code
 - Language: C#
 - Source: V1 Release Candidate

**Additional context**

**Comment by stephentoub** [comment]
KernelFunction is no longer tied to a particular plugin, so the metadata retrieved directly from the KernelFunction doesn't have a plugin name available.  If you get the metadata from the plugin, then it can populate it. You can also do `new KernelFunctionMetadata(function.Metadata) { PluginName = "..." }`.

**Comment by stephentoub** [comment]
@markwallace-microsoft, your PR around removing PluginName from KernelFunctionMetadata was closed. Are you still re-evaluating things there?

**Comment by matthewbolanos** [comment]
Decided not to do this so that functions can be part of multiple plugins.
