### ISSUE TITLE
.Net: Should the FunctionResult class be made generic instead of using GetResult<T>

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3863]
If we changed `FunctionResult` to `FunctionResult<T>`, in the future, we could enable scenarios described in [option 3 of Roger's ADR](https://github.com/RogerBarreto/semantic-kernel/blob/baadfba005d92ccc76ef61a206c33a2860b81dbd/docs/decisions/0024-multi-modal-service-support.md#option-3---gives-back-what-you-asked). It would also drive further parallelism with `IAsyncEnumerable<T>` in the streaming code paths.

The new class would look something like this...

```csharp
public sealed class FunctionResult<T> : FunctionResult
{
    internal T? Value { get; private set; } = null;
    public T? GetValue()
    {
        if (this.Value is null)
        {
            return default;
        }

        return typedResult;
    }
    public FunctionResult(string functionName, T? value, CultureInfo culture)
        : this(functionName)
    {
        this.Value = value;
        this.Culture = culture;
    }
    public override string ToString()
    {
        return ConvertToString(this.Value, this.Culture) ?? string.Empty;
    }
}
```

As a consequence (benefit?), the `InvokeAsync()` methods would need to be updated to `InvokeAsync<T>()` to match `InvokeStreamingAsync<T>()`.

In the future, the `InvokeAsync<T>()` method could use the generic to determine which type (if multiple are supported) to return back to the user.

**Comment by stephentoub** [comment]
@matthewbolanos, what APIs would have `FunctionResult<T>` as a return type, and where would the `T` come from?

**Comment by matthewbolanos** [comment]
Mostly created this to make sure we discussed all of the proposed changes in the larger ADR Roger created; I can be told this is unnecessary.

From what I can tell, only `KernelFunction`'s `InvokeAsync()` returns back a `FunctionResult` today, so I believe that'd be the only one that would need to be updated to return back `FunctionResult<T>()`.

Today, you already have to provide T when you call `GetValue<T>()`, so callers today already have this information (except in the case where you just need to use `ToString()` on the `FunctionResult`.

As I see it, the con of making this change is that it makes the simple case a bit more complicated...
`Console.WriteLine(kernel.InvokeAsync("pluginName","functionName")` vs `Console.WriteLine(kernel.InvokeAsync<string>("pluginName","functionName")`

But as a benefits...
1. We could inspect the `T` during `InvokeAsync<T>()` in the future to perform marshalling
2. It drives parallelism with `InvokeStreamingAsync<T>()`
3. You no longer need to pass `T` into `GetValue()`

**Comment by RogerBarreto** [comment]
Using generic extension methods might bring some advantages to this scenario.

- Kernel.InvokeAsync<T>
- KernelFunction.InvokeAsync<T>

Basically the idea is, if the `sk developer` don't need to use the `FunctionResult.Metadata` (Most of the times), you can get it right away with one less allocation: 

Current end user XP `Example60_AdvancedFunctions.cs`
```
var result = await kernel.InvokeAsync(functions["Function1"]);
var customType = result.GetValue<MyCustomType>()!;
Console.WriteLine(customType.Number); // 2
Console.WriteLine(customType.Text); // From Function1 + From Function2
```
Proposed
```
var customType = await kernel.InvokeAsync<MyCustomType>(functions["Function1"]);
Console.WriteLine(customType.Number); // 2
Console.WriteLine(customType.Text); // From Function1 + From Function2
```
