### ISSUE TITLE
.Net: Content in ChatMessage is a string; the latest version of OpenAI APIs treats it as a string or array

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3874]

**Comment by RogerBarreto** [comment]
Content in ChatMessage is still a string.

![image](https://github.com/microsoft/semantic-kernel/assets/19890735/8b9077d8-5d3b-456b-9c3d-d2f08348a42b)

What became an array was the new property `tool_calls` over the deprecated single `function_call`

**Comment by matthewbolanos** [comment]
When you send a multi-modal payload, it becomes an array:

![Image](https://github.com/microsoft/semantic-kernel/assets/1409190/27870485-4d49-4690-b937-f6a875fb21e5)
