### ISSUE TITLE
Python: After upgrading OpenAI SDK to 1.0+ in 0.4.0.dev0, some sample notebooks fail to run

### ISSUE THREAD

**Issue by moonbox3** [microsoft/semantic-kernel#3897]
**Describe the bug**
After upgrading OpenAI SDK to 1.0+ in 0.4.0.dev0, some sample notebooks fail to run.

**To Reproduce**
1. Get latest SK code
2. Open a sample Jupyter notebook like `00-getting-started.ipynb`.
3. Attempt to run the `Option 2: using Azure OpenAI` code cell.
4. You should see an error similar to:

```
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
/home/workspace/semantic-kernel/python/notebooks/00-getting-started.ipynb Cell 7 line 5
      [1](vscode-notebook-cell://wsl%2Bubuntu-20.04/home/workspace/semantic-kernel/python/notebooks/00-getting-started.ipynb#W6sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0) from semantic_kernel.connectors.ai.open_ai import AzureChatCompletion
      [3](vscode-notebook-cell://wsl%2Bubuntu-20.04/home/workspace/semantic-kernel/python/notebooks/00-getting-started.ipynb#W6sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2) deployment, api_key, endpoint = sk.azure_openai_settings_from_dot_env()
----> [5](vscode-notebook-cell://wsl%2Bubuntu-20.04/home/workspace/semantic-kernel/python/notebooks/00-getting-started.ipynb#W6sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4) kernel.add_chat_service("chat_completion", AzureChatCompletion(deployment, endpoint, api_key))

ValidationError: 1 validation error for url
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='<scrubbed>', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/url_parsing
```

The error looks related to missing keyward args for the `AzureChatCompletion` object.

**Expected behavior**
There should be no failures. All notebooks may need some form of updating.

**Comment by rewrlution** [comment]
I can take this one.

**Comment by rewrlution** [comment]
In notebook 11, I observed an inconsistency for the `complete_chat_stream_async()` method.

The "chat completion base client" accepts a list of `ChatMessage` as an input.

For "Google Palm chat completion", it accepts a `Tuple`: https://github.com/microsoft/semantic-kernel/blob/37f2760fdd146d49780e5fff859a2b79c39b7661/python/semantic_kernel/connectors/ai/google_palm/services/gp_chat_completion.py#L78

For "OpenAI chat completion", it accepts a `Dict`: https://github.com/microsoft/semantic-kernel/blob/37f2760fdd146d49780e5fff859a2b79c39b7661/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L88

**Comment by rewrlution** [comment]
In notebook 10, HuggingFace text completion model returns a lot of new lines between texts:

<img width="1150" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/147449498/45a53b43-e451-4f0e-91aa-23610afc6c58">

**Comment by rewrlution** [comment]
In notebook 09, the `reference_check()` function runs forever, this happens for both OpenAI and AzureOpenAI.

<img width="898" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/147449498/de0cecc4-dedf-471e-9369-9129eea43440">

**Comment by rewrlution** [comment]
In notebook 08, I noticed that the `ContextVariables` only accept `String` type:
<img width="1440" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/147449498/da6a7400-ff2f-4974-90f7-1c9cfd05670b">

Therefore, I updated the notebook cell from:

**Comment by rewrlution** [comment]
In notebook 07, it threw a validation error for `TextMemorySkill` since its default value is not a string. Hence, I need to update the source code of the skill.

**Comment by ShuaibAhmadShuaib** [comment]
Hi, I am also facing same issue. Details are below down

Name: semantic-kernel
Version: 0.4.5.dev0

api_key="************"
endpoint="https://myopenai321.openai.azure.com"
deployment_name="gtp-35-turbo"


{
	"name": "ValidationError",
	"message": "1 validation error for url
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='1a760ea95ca64d88991c55e7e9f7f920', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/url_parsing",
	"stack": "---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[10], line 9
      6 deployment_name=\"gtp-35-turbo\"
      8 kernel = sk.Kernel()
----> 9 kernel.add_chat_service(\"aiiva-chat\", AzureChatCompletion(deployment_name,endpoint, api_key))

File c:\\Users\\DS198QF\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\semantic_kernel\\connectors\\ai\\open_ai\\services\\azure_chat_completion.py:241, in AzureChatCompletion.__init__(self, deployment_name, endpoint, base_url, api_version, api_key, ad_token, ad_token_provider, default_headers, async_client, use_extensions, log, **kwargs)
    238     logger.warning(\"The 'logger' argument is deprecated. Please use the `logging` module instead.\")
    240 if base_url and isinstance(base_url, str):
--> 241     base_url = HttpsUrl(base_url)
    242 if use_extensions and endpoint and deployment_name:
    243     base_url = HttpsUrl(f\"{str(endpoint).rstrip('/')}/openai/deployments/{deployment_name}/extensions\")

File c:\\Users\\DS198QF\\AppData\\Local\\Programs\\Python\\Python310\\lib\\typing.py:957, in _BaseGenericAlias.__call__(self, *args, **kwargs)
    954 if not self._inst:
    955     raise TypeError(f\"Type {self._name} cannot be instantiated; \"
    956                     f\"use {self.__origin__.__name__}() instead\")
--> 957 result = self.__origin__(*args, **kwargs)
    958 try:
    959     result.__orig_class__ = self

ValidationError: 1 validation error for url
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='1a760ea95ca64d88991c55e7e9f7f920', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/url_parsing"
}
