### ISSUE TITLE
Function parameter descriptions are populated with names when reading from OpenAPI defintion

### ISSUE THREAD

**Issue by maniratnam123** [microsoft/semantic-kernel#390]
Semantic function parameter descriptions are populated with names when reading from OpenAPI defintion.

**OpenAPI endpoint parameters have description populated already. The library method should use that instead.**

https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs#L303

**Comment by maniratnam123** [comment]
I have a PR open if this change is approved.

https://github.com/microsoft/semantic-kernel/pull/392

**Comment by shawncal** [comment]
PR merged. Thanks for the contribution @maniratnam123!
