### ISSUE TITLE
Python: AzureChatCompletion raising validation error when 

### ISSUE THREAD

**Issue by andrewldesousa** [microsoft/semantic-kernel#3900]
**Describe the bug**
I am trying to create AzureChatCompletion instance in Python but am getting a validation error when passing the following endpoint https://app-name-here.openai.azure.com/

I have code based on [this code sample](https://github.com/MicrosoftDocs/semantic-kernel-docs/tree/main/samples/python/02-Adding-AI-Services). I am able to successfully run the sample if I use OpenAI as the `GLOBAL__LLM_SERVICE` instead.

```
  File "C:\Users\adesousa\source\sk-demo\main.py", line 23, in main
    AzureChatCompletion(
  File "C:\Users\adesousa\source\sk-demo\venv\Lib\site-packages\semantic_kernel\connectors\ai\open_ai\services\azure_chat_completion.py", line 133, in __init__
    super().__init__(
  File "pydantic\decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic\decorator.py", line 133, in pydantic.decorator.ValidatedFunction.call
  File "pydantic\decorator.py", line 130, in pydantic.decorator.ValidatedFunction.init_model_instance
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Init
base_url
  invalid or missing URL scheme (type=value_error.url.scheme)
```

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: Python

**Comment by eavanvalkenburg** [comment]
can you add the code you used? @andrewldesousa

**Comment by SunXnuS** [comment]
I'm experiencing the same.

**Comment by andrewldesousa** [comment]
@eavanvalkenburg 

Hmmm - i tried again and can't replicate. 

maybe it was resolved by this commit https://github.com/microsoft/semantic-kernel/commit/0982e3f2719635743a5fe03ec7ba67dd8758eec6?

**Comment by andrewldesousa** [comment]
Yep - seems like it was resolved recently? I can replicate it with an older install of `semantic-kernel`

Just running the code sample [here](https://github.com/MicrosoftDocs/semantic-kernel-docs/tree/main/samples/python/02-Adding-AI-Services) using the `AzureOpenAI` and `chat-completion` settings will result in the validation issue on the older version.

**Comment by eavanvalkenburg** [comment]
so, this is fixed and can be closed then? @andrewldesousa

**Comment by andrewldesousa** [comment]
yep!

**Comment by ShuaibAhmadShuaib** [comment]
I am also experiencing same issue. Details are below down.

Name: semantic-kernel
Version: 0.4.5.dev0

api_key="************"
endpoint="https://myopenai321.openai.azure.com"
deployment_name="gtp-35-turbo"
kernel = sk.Kernel()
kernel.add_chat_service("aiiva-chat", AzureChatCompletion(deployment_name,endpoint, api_key))

{
	"name": "ValidationError",
	"message": "1 validation error for url
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='1a760ea95ca64d88991c55e7e9f7f920', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/url_parsing",
	"stack": "---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[10], line 9
      6 deployment_name=\"gtp-35-turbo\"
      8 kernel = sk.Kernel()
----> 9 kernel.add_chat_service(\"aiiva-chat\", AzureChatCompletion(deployment_name,endpoint, api_key))

File c:\\Users\\DS198QF\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\semantic_kernel\\connectors\\ai\\open_ai\\services\\azure_chat_completion.py:241, in AzureChatCompletion.__init__(self, deployment_name, endpoint, base_url, api_version, api_key, ad_token, ad_token_provider, default_headers, async_client, use_extensions, log, **kwargs)
    238     logger.warning(\"The 'logger' argument is deprecated. Please use the `logging` module instead.\")
    240 if base_url and isinstance(base_url, str):
--> 241     base_url = HttpsUrl(base_url)
    242 if use_extensions and endpoint and deployment_name:
    243     base_url = HttpsUrl(f\"{str(endpoint).rstrip('/')}/openai/deployments/{deployment_name}/extensions\")

File c:\\Users\\DS198QF\\AppData\\Local\\Programs\\Python\\Python310\\lib\\typing.py:957, in _BaseGenericAlias.__call__(self, *args, **kwargs)
    954 if not self._inst:
    955     raise TypeError(f\"Type {self._name} cannot be instantiated; \"
    956                     f\"use {self.__origin__.__name__}() instead\")
--> 957 result = self.__origin__(*args, **kwargs)
    958 try:
    959     result.__orig_class__ = self

ValidationError: 1 validation error for url
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='1a760ea95ca64d88991c55e7e9f7f920', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/url_parsing"
}

**Comment by sidaxt** [comment]
> I am also experiencing same issue. Details are below down.
> 
> Name: semantic-kernel Version: 0.4.5.dev0
> 
> api_key="************" endpoint="https://myopenai321.openai.azure.com" deployment_name="gtp-35-turbo" kernel = sk.Kernel() kernel.add_chat_service("aiiva-chat", AzureChatCompletion(deployment_name,endpoint, api_key))
> 
> { "name": "ValidationError", "message": "1 validation error for url Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='1a760ea95ca64d88991c55e7e9f7f920', input_type=str] For further information visit https://errors.pydantic.dev/2.5/v/url_parsing", "stack": "--------------------------------------------------------------------------- ValidationError Traceback (most recent call last) Cell In[10], line 9 6 deployment_name="gtp-35-turbo" 8 kernel = sk.Kernel() ----> 9 kernel.add_chat_service("aiiva-chat", AzureChatCompletion(deployment_name,endpoint, api_key))
> 
> File c:\Users\DS198QF\AppData\Local\Programs\Python\Python310\lib\site-packages\semantic_kernel\connectors\ai\open_ai\services\azure_chat_completion.py:241, in AzureChatCompletion.**init**(self, deployment_name, endpoint, base_url, api_version, api_key, ad_token, ad_token_provider, default_headers, async_client, use_extensions, log, **kwargs) 238 logger.warning("The 'logger' argument is deprecated. Please use the `logging` module instead.") 240 if base_url and isinstance(base_url, str): --> 241 base_url = HttpsUrl(base_url) 242 if use_extensions and endpoint and deployment_name: 243 base_url = HttpsUrl(f"{str(endpoint).rstrip('/')}/openai/deployments/{deployment_name}/extensions")
> 
> File c:\Users\DS198QF\AppData\Local\Programs\Python\Python310\lib\typing.py:957, in _BaseGenericAlias.**call**(self, *args, **kwargs) 954 if not self._inst: 955 raise TypeError(f"Type {self._name} cannot be instantiated; " 956 f"use {self.**origin**.**name**}() instead") --> 957 result = self.**origin**(*args, **kwargs) 958 try: 959 result.**orig_class** = self
> 
> ValidationError: 1 validation error for url Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='*******************', input_type=str] For further information visit https://errors.pydantic.dev/2.5/v/url_parsing" }

Is this issue resolved? @ShuaibAhmadShuaib
