### ISSUE TITLE
.Net: Isolate Handlebars Kernel System helpers in their own class + add Categories filter for KernelSystemHelpers (i.e., KernelHelperCategories) 

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/semantic-kernel#3947]
When registering helpers we should follow the same pattern as is used here https://github.com/Handlebars-Net/Handlebars.Net.Helpers. 

We don't want to put everything into a single class as indicated by using private static helper methods.

When registering these helpers with the template engine, there should be calls that look something like this:
```
KernelPromptHelpers.Register(handlebarsContext);
KernelPluginHelpers.Register(handlebarsContext);
KernelContextHelpers..Register(handlebarsContext);
```

Can probably also use `RegisterCustomHelpers` from `Handlebars.Net.Helpers` library for their built-in argument handling

Other notes
+ add option to filter KernelSystemHelpers (i.e., KernelHelperCategories) 
+ Should also consider standardizing the naming conventions for these helpers, i.e., 'Message' instead of 'message' since the built in Handlebars library helpers use PascalCase

**Comment by markwallace-microsoft** [comment]
Closing as obsolete
