### ISSUE TITLE
AuthorRole has different type for streaming/non-streaming content

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3948]
<img width="1192" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1409190/61994abd-da26-4196-990d-9b39c62528b6">

Streaming is AuthorRole?
Non-streaming is AuthorRole

**Comment by RogerBarreto** [comment]
That's right, in streaming the AuthorRole will come only in one of the first chunks not all.
