### ISSUE TITLE
It'd be nice if there was an extension method on IAsyncEnumerable<ModelContent> to get non-stream result

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3949]
In this example, I've shown how it'd be nice to get the final result without having to create the final object myself.

<img width="541" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1409190/100b402e-52d8-4f54-8bbd-e38bf1d26b71">

Since this is what the alternative looks like...
<img width="1107" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1409190/82d68c66-41e9-4196-9d8f-eb9f102798f2">

**Comment by RogerBarreto** [comment]
I thought on something similar to this when I did the Streaming brainstorm, but that would be a overkill at the time.

Basically, the connectors services could provide a method builder where they could use the streaming input to create the non-streaming content.
