### ISSUE TITLE
CreateFunctionFromPromptYamlResource doesn't get the resource from the right assembly

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3951]
If you try to use CreateFunctionFromPromptYamlResource, it throws an error because it looks for the resource in the Functions.Yaml assembly (not the developers current project)

**Comment by stephentoub** [comment]
I'd suggest revisiting having these CreateFunctionFromPromptXxResource methods at all.  Using Assembly.GetCallingAssembly is not a very reliable solution, e.g. it's impacted by inlining, an intermediate caller that gets introduced (e.g. an extension method to simplify the call) might mess up what assembly is viewed as the calling one, etc.
