### ISSUE TITLE
There should be helper methods to make printing streaming results less verbose

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3961]
<img width="462" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1409190/2121c957-af04-4f8e-97e8-f57c0b944a9c">

**Comment by RogerBarreto** [comment]
# There are some approaches to this:

From most verbose to lesser.

## 1. Extension Method Accepts an `IEnumerable<StreamingChatMessage>`
```csharp
var streamingChatMessages = new List<StreamingChatMessage>();
await foreach (var message in chatCompletion.GetStreamingChatMessageContents(...))
{
     streamingChatMessages.Add(message);
     Console.Write(message.Role.HasValue ? message.Role.Value + " > " : string.Empty);
     Console.Write(message.Content)
}

// ChatMessage AddMessage will have a build logic
var chatMessage = chatCompletion.GetChatMessageContent(streamingChatMessages)
chatHistory.AddMessage(chatMessages);
```
## 2. Chat History - AddMessage Accepts an `IEnumerable<StreamingChatMessage>`
```
var streamingChatMessages = new List<StreamingChatMessage>();
await foreach (var message in chatCompletion.GetStreamingChatMessageContents(...))
{
     streamingChatMessages.Add(message);
     Console.Write(message.Role.HasValue ? message.Role.Value + " > " : string.Empty);
     Console.Write(message.Content)
}
chatHistory.AddMessage(streamingChatMessages);
```
## 3. Chat History - Embbeded Stash/Build
Chat history will stash internally the streaming chat contents and will add as a complete message when  `AddMessageFromStash()` is triggered.
```
await foreach (var message in chatCompletion.GetStreamingChatMessageContents(...))
{
     chatHistory.StashStreamingMessage(message);
     Console.Write(message.Role.HasValue ? message.Role.Value + " > " : string.Empty);
     Console.Write(message.Content)
}
chatHistory.AddMessageFromStash();
```

Thoughts?

**Comment by dmytrostruk** [comment]
As for me, Option 2 looks like a possible solution. In this case, method `AddMessage` will do an aggregation of streaming data and construct new `ChatMessageContent` for next request. Although maybe we need to name the method like `chatHistory.AddStreamingMessages` for better understanding. 

Option 1 doesn't look like the model we have today, when you need to add response to chat history first, before making next request. So, it may be confusing. 

I'm not sure about Option 3, since stash maintenance behind the scenes may be very confusing. Users will be forced to clear stash manually, and it's unclear what is the state of stash at specific period of time. I would avoid that approach.

**Comment by stephentoub** [comment]
How about something like:
```diff
public class ChatHistory
{
+   public static IAsyncEnumerable<T> AddStreamingMessage<T>(IAsyncEnumerable<T> streamingMessageContents) where T : StreamingChatMessageContent;
}
```
which would then be consumed like:
```C#
await foreach (var message in chatHistory.AddStreamingMessage(chatCompletion.GetStreamingChatMessageContents(...)))
{
     Console.Write(message.Content)
}
```
?

**Comment by RogerBarreto** [comment]
@stephentoub The problem is that if the sk developer wants to use the streaming message to update his UI he don't need to perform two calls to the server side. So while interating over the IASyncEnumerable and use its chunks to build the whole object after.

**Comment by RogerBarreto** [comment]
YOu are right, I didn't notice t returs back the IASyncEnumerable, makes sense, thanks!
