### ISSUE TITLE
.Net: Many methods and interfaces are marked as Experimental in RC1

### ISSUE THREAD

**Issue by marcominerva** [microsoft/semantic-kernel#3968]
**Describe the bug**
After updating to RC1, I have noticed that many methods, interfaces and event some classes are marked as `Experimental `for example:

```
[Experimental("SKEXP0011")]
public static KernelBuilder WithAzureOpenAITextEmbeddingGeneration(

[Experimental("SKEXP0001")]
public interface ITextEmbeddingGeneration : IEmbeddingGeneration<string, float>

[Experimental("SKEXP0055")]
public static class TextChunker
```

**To Reproduce**
Update Sematic Kernel library to RC1

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/3522534/c54c7820-e4f0-44d5-9e79-dba11007d790)

**Platform**
 - OS: Windows
 - IDE: Visual Studio 2022
 - Language: C# with .NET 8.0
 - Source: Microsoft.SemanticKernel v1.0.0-rc1

**Comment by kinfey** [comment]
using ignore to skip

#pragma warning disable SKEXP0052
#pragma warning disable CS1061
#pragma warning disable SKEXP0011
#pragma warning disable SKEXP0026

**Comment by marcominerva** [comment]
Thank you... But the point is not how to skip these errors... But why are these classes, method and interfaces now experimental?

**Comment by marcominerva** [comment]
OK, so, for example, If today I want to use Embeddings, the only way is to use the `WithAzureOpenAITextEmbeddingGeneration` method, disabling the experimental error, knowing that in version 1.0.0, could this method be removed at all? Or there is a recommended upgrade path?

**Comment by stephentoub** [comment]
> OK, so, for example, If today I want to use Embeddings, the only way is to use the WithAzureOpenAITextEmbeddingGeneration method, disabling the experimental error, knowing that in version 1.0.0, could this method be removed at all? Or there is a recommended upgrade path?

It'll be there in 1.0.0. It's [Experimental] because its possible its shape will change _after_ 1.0.0. If it does, I expect there will be a clear upgrade path. @matthewbolanos can speak more to plans and timelines here, but clearly denoting what's stable vs what's not is particularly important from a binary compatibility perspective.

**Comment by matthewbolanos** [comment]
Yes, that's correct. We are using the [Experimental] tag for anything we want to keep in the future, but are unsure if the interface might change (and potentially require a breaking change). The embedding services, for example, may require some subtle renaming of the classes/methods to align with Azure AI and HuggingFace.

Everything _not_ marked experimental is expected to not have any breaking changes going forward. Early next year, our goal is to make as many things non-Experimental to gaurantee no future breaking changes.

**Comment by matthewbolanos** [comment]
Going to be closing; expect the experimental attributes to disapear over time
