### ISSUE TITLE
.Net: Is WithLoggerFactory still necessary?

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3976]
With the `WithServices()` pattern you can create a new logger like so...

```csharp
services
        .AddTransient<Kernel>(sp => new KernelBuilder()
            .WithServices(c =>
            {
                c.AddLogging(c => c.AddConsole().SetMinimumLevel(LogLevel.Information));
                c.AddOpenAIChatCompletion("gpt-4", apiKey);
            })
            .WithPlugins(plugins => plugins.AddPluginFromObject<LightPlugin>())
            .Build()
        )
```

Because of this, do we still need `WithLoggerFactory`? (I'll be updating all of the samples/docs to reflect the new pattern)

**Comment by stephentoub** [comment]
It's not _necessary_. @markwallace-microsoft had suggested keeping both it and Kernel.LoggerFactory as shortcuts. I don't have a strong opinion either way.

**Comment by stephentoub** [comment]
I've removed it https://github.com/microsoft/semantic-kernel/pull/4023 as part of addressing the API review feedback.

**Comment by glorious-beard** [comment]
Can you add back `WithLoggerFactory`? Or some way to add an `ILoggerFactory` to the `ILoggingBuilder` in `AddLogging`? If we already have logging configured or a pre-configured logger system is gets injected, it doesn't really make sense to re-configure logging all over again just for the semantic kernel.

**Comment by WeihanLi** [comment]
> If we already have logging configured or a pre-configured logger system is gets injected, it doesn't really make sense to re-configure logging all over again just for the semantic kernel.

Maybe we could use `builder.Services.AddSingleton<ILoggerFactory>()` to inject the `loggerFactory`?

**Comment by stephentoub** [comment]
> Edit: Taking a closer look at the source code... is the general idea that we can just directly add an existing ILoggerFactory to the services exposed by the ILoggingBuilder?

Yes. Any mechanism for injecting the ILoggerFactory into the IServiceCollection will work.  You can do this with a kernel builder as you've noted, e.g.
```C#
IKernelBuilder builder = Kernel.CreateBuilder();
builder.Services.AddLogging(c => c.AddConsole());
Kernel kernel = builder.Build();
```
or you can get the Kernel from the DI container directly and it'll automatically pick up everything else registered in DI, e.g.
```C#
serviceCollection.AddKernel(); // adds Kernel as a transient service
serviceCollection.AddLogging(c => c.AddConsole());
IServiceProvider services = serviceCollection.BuildServiceProvider();
Kernel kernel = services.GetServices<Kernel>();
```

**Comment by dmytrostruk** [comment]
Closing this issue, since `WithLoggerFactory` method is not required anymore. 
@glorious-beard feel free to create a new issue in case you need any further assistance. Thank you!

**Comment by crazyfox55** [comment]
Can someone update the documentation to show the correct way to add logging?

https://github.com/microsoft/semantic-kernel/blob/5953beb8b6a747b0534b8f908f49118eb1c635ae/dotnet/docs/TELEMETRY.md
