### ISSUE TITLE
.Net: [Sample organization] Rethink on how KernelExamples should be presented.

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#3977]
Remove the numbering of examples as they don't represent a strong meaning except for an identification.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/issues/3999
- [ ] https://github.com/microsoft/semantic-kernel/issues/3978
```

**Comment by stephentoub** [comment]
Beyond just the gaps, there's not much rhyme or reason as to what the numbers are. They've just grown organically over time. It'd be nice if the whole examples thing was completely redone, with a markdown write-up that weaves a story from getting started through all the scenarios to the most complex, with references to the relevant portions of the runnable project. Some of the examples can also be simplified significantly; less is often more.

**Comment by matthewbolanos** [comment]
Finished with the reorganization of the "concept" samples
