### ISSUE TITLE
.Net: Create a connector for Azure MaaS

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3992]
Create a connector that supports models provided by Azure MaaS. In particular...
- Microsoft Phi 3
- Microsoft Phi 2 
- Microsoft Ph 1.5
- Llama3
- Llama2

**Comment by ElieTaillard** [comment]
I believe it would be beneficial to create a generic connector that would support not only the mentioned models, but also other models available on Azure. Such a connector would offer greater flexibility and extensibility, making it easier to integrate new models in the future without requiring major modifications
