### ISSUE TITLE
.Net: Smoke test vector databases using existing tests

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3997]

**Comment by TaoChenOSU** [comment]
Validated the following connectors: chroma, MongoDB, Milvus, and Weaviate.
Unable to create a Postgre instance due to lack of permission.

**Comment by TaoChenOSU** [comment]
Most READMEs of the memory connectors are out of date. Need to update them as well.

**Comment by TaoChenOSU** [comment]
Closing this item. Created this new one to track the Postgres memory connector test: https://github.com/microsoft/semantic-kernel/issues/4253
