### ISSUE TITLE
.Net SDK IntelliSense - MemoryBuilder.WithAzureOpenAITextEmbeddingGeneration wrong signature

### ISSUE THREAD

**Issue by joshgreenwald** [microsoft/semantic-kernel#4011]
The IntelliSense in the C# SDK for MemoryBuilder.WithAzureOpenAITextEmbeddingGeneration is out of order.

IntelliSense lists the method signature as:
MemoryBuilder.WithAzureOpenAITextEmbeddingGeneration(deploymentName, endpoint, apiKey, modelId)

However, the correct order is:
MemoryBuilder.WithAzureOpenAITextEmbeddingGeneration(deploymentName, modelId, endpoint, apiKey)

**Comment by matthewbolanos** [comment]
@markwallace-microsoft, I believe this will be resolved once you make modelId optional.

**Comment by markwallace-microsoft** [comment]
Yes, this if fixed in RC4
