### ISSUE TITLE
.Net: [KernelPromptTemplate] Support primitives in values

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#4015]
Today, 'KernelPromptTemplate' requires all values, such as 28 in the expression {{p.f a='28'}}, to be wrapped in single or double quotes. Considering that it's being updated to support primitives - https://github.com/microsoft/semantic-kernel/pull/4013, it would be logical to expect the expression to be like this: {{p.f a=28}}, where the value 28 is specified without single or double quotes and eventually passed to the function as is, without unnecessary string-to-int conversion.

**Comment by markwallace-microsoft** [comment]
Moving to backlog until we get feedback from customers that this change is required

**Comment by markwallace-microsoft** [comment]
Closing as stale
