### ISSUE TITLE
.Net: KernelFunction.Metadata.Parameters is empty for semantic functions

### ISSUE THREAD

**Issue by dluc** [microsoft/semantic-kernel#4016]
```csharp
var skPrompt = """
Question: {{$input}}

Answer: {{memory.ask $input}}

Translate the answer to {{$language}}
""";

KernelFunction myFunction = kernel.CreateFunctionFromPrompt(skPrompt);

Console.WriteLine("Params count: " + myFunction.Metadata.Parameters.Count);
```

Expected output
```
Params count: 2
```

Actual
```
Params count: 0
```

**Comment by feiyun0112** [comment]
You must provide "InputVariables"

[https://github.com/microsoft/semantic-kernel/blob/755405aa87bdc46b7669f6c00d856a78925f8540/dotnet/src/SemanticKernel.Abstractions/PromptTemplate/PromptTemplateConfig.cs#L83](https://github.com/microsoft/semantic-kernel/blob/755405aa87bdc46b7669f6c00d856a78925f8540/dotnet/src/SemanticKernel.Abstractions/PromptTemplate/PromptTemplateConfig.cs#L83)


You can use Yaml prompt

[https://github.com/microsoft/semantic-kernel/blob/755405aa87bdc46b7669f6c00d856a78925f8540/dotnet/src/Functions/Functions.UnitTests/Yaml/Functions/KernelFunctionYamlTests.cs#L14](https://github.com/microsoft/semantic-kernel/blob/755405aa87bdc46b7669f6c00d856a78925f8540/dotnet/src/Functions/Functions.UnitTests/Yaml/Functions/KernelFunctionYamlTests.cs#L14)

```
private readonly string _yamlNoExecutionSettings = @"
    template_format: semantic-kernel
    template:        Say hello world to {{$name}} in {{$language}}
    description:     Say hello to the specified person using the specified language
    name:            SayHello
    input_variables:
      - name:          name
        description:   The name of the person to greet
        default:       John
      - name:          language
        description:   The language to generate the greeting in
        default: English
";
```

**Comment by markwallace-microsoft** [comment]
This is fixed in RC4
