### ISSUE TITLE
Unit test failed (` SQLite Error 8: 'attempt to write a readonly database'.`)

### ISSUE THREAD

**Issue by tynguyen** [microsoft/semantic-kernel#402]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5508237/231066680-6c132d34-c4fc-4ef0-ae41-52c4c82988fd.png)

Issue occurs when attempting to create a `collection` or `upsert` records to the database. For example, `/semantic-kernel/dotnet/src/Connectors/Connectors.UnitTests/Memory/Sqlite/SqliteMemoryStoreTests.cs:line 587`
 
This could have something to do with the  read/write permission on my pc too. I'm not sure.

**Comment by awharrison-28** [comment]
Hi @tynguyen I am unable to repro this issue locally, so it might have to do with the your read/write permissions. I did find some cleanup errors in the unit tests though while trying.

I am currently refactoring the SqliteMemoryStore to avoid manually managing the connection. This should make the unit tests cleaner in general.

**Comment by tynguyen** [comment]
Thanks @awharrison-28 . Closed as it irreproducible.

**Comment by awharrison-28** [comment]
@tynguyen just wanted to follow up here, https://github.com/microsoft/semantic-kernel/pull/425 should address the unit test issues I discovered that were caused by unclosed connections. I don't think will solve what you described in this issue unfortunately.
