### ISSUE TITLE
Missing package for RC1 and RC2 for Microsoft.SemanticKernel.Planners.Core

### ISSUE THREAD

**Issue by alkampfergit** [microsoft/semantic-kernel#4020]
After updating to RC1 or RC2 I've noticed that the package [Microsoft.SemanticKernel.Planners.Core](https://www.nuget.org/packages/Microsoft.SemanticKernel.Planners.Core/1.0.0-beta8) has no version for RC. This means that SequentialPlanner is not usable anymore, since if you use the one from beta8 it does not work due to the breaking changes.

I'd like to understand if it is a bug (package publishing went bad) or if the package is really removed from the RC and how we can use the classes originalli in Planners.Core.

**To Reproduce**
Create a solution, reference Microsoft.SemanticKernel.Planners.Core, try to use sequentialPlanner and it does not compile because it still search IKernel interface.

**Expected behavior**
In Nuget I'm expecting package Microsoft.SemanticKernel.Planners.Core to be aligned with RC.

**Comment by alkampfergit** [comment]
Actually if we open the solution we can see that we have only Handlebars implementation of the planner, the one of OpenAi has no test and seems to have no planner. 

![image](https://github.com/microsoft/semantic-kernel/assets/358545/9dbc3e17-32e4-4e85-8154-0475a7534440)

This is the situation of the tag dotnet-1.0.0-beta8 where we can see that we actually have the old name of the project that actually depends on handlebars.

> This suggests me that the project was renamed but no deprecation was done in package in nuget repository leading to this confusion

![image](https://github.com/microsoft/semantic-kernel/assets/358545/8b0fa6bd-1bbe-4afd-8339-94bf32c8d60d)

**Comment by jkbim** [comment]
It seems to be an issue of the _Microsoft.SemanticKernel.Planners.Core_ not just having been published, e.g. the `IKernel` interface have been removed in the main branch of _Planners.Core_ 2 weeks ago and in the _Microsoft.SemanticKernel.Abstractions_ rc3 published package but Planners.Core beta8 still relies on `IKernel` and is the latest package available on Nuget.

**Comment by DM-98** [comment]
I can't instantiate StepwisePlanner since kernel.Build() gives a Kernel and not IKernel as required for instantiation.. What is the workaround / packages to use?

**Comment by matthewbolanos** [comment]
Thanks for raising this. Our current plan is to keep the old planners <1.0 because the new ones (Handlebars and FunctioncallingStepwise) perform much better during our internal testing. I will be providing a blog later this evening on the steps required to migrate from the previous planners to the new ones.
