### ISSUE TITLE
How to set the api base/url of the openai model using OpenAITextCompletion

### ISSUE THREAD

**Issue by HuntZhaozq** [microsoft/semantic-kernel#4021]
**Describe the bug**
I am trying to use OpenAITextCompletion with the local model using openai api. But the setting of OpenAITextCompletion only contains the `model_name` and `api_key`. Then, it makes an connection error to openai.

So, how to set the `api_base` to get access to the local model url?

**To Reproduce**
api_key, org_id = sk.openai_settings_from_dot_env()
self.kernel.add_text_completion_service("dv", OpenAITextCompletion(self.config["model"], api_key, org_id))

**Comment by markwallace-microsoft** [comment]
Hi @HuntZhaozq take a look at this sample https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example52_ApimAuth.cs#L48 
It shows how to inject your own `OpenAIClient` with a custom uri.
