### ISSUE TITLE
.Net: Chroma reference sample needs to be updated and verified

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#4026]
Below is the as from the community

1. Update sample README to match the current pattern
2. Verify the reference sample works

Hello! My task is to migrate the followign python code to C#:
        client = chromadb.PersistentClient(path=os.getcwd()) # I understand that there is no in-memory implementation in C#
        embedding_func = OpenAIEmbeddingFunction(api_key='OPENAI_API_KEY', model_name='text-embedding-ada-002')
        collection = client.get_collection(name='content', embedding_function=embedding_func)
        query_result = data.query(query_texts=question, n_results=max_len//CHUNK_MAX_TOKENS, include=['documents'])

I have installed https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.Memory.Chroma/1.0.0-rc2 and tried to apply the sample from https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.Memory.Chroma as a starting point:
#pragma warning disable SKEXP0022
            Kernel kernel = new KernelBuilder()
                .WithOpenAITextEmbeddingGenerationService("text-embedding-ada-002", "OPENAI_API_KEY")
                .WithMemoryStorage(new ChromaMemoryStore("http://localhost:8000"))
                .Build();
#pragma warning restore SKEXP0022
But none of these two .With* methods are available. Could you please help to convert the Python code to C# or give me the link to an up-to-date tutorial?

**Comment by mr-shevchenko** [comment]
I'm using
https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.OpenAI/1.0.0-rc4
https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.Chroma/1.0.0-rc4

I follow the sample https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.Memory.Chroma to get results of semantic search in my ASP.NET Core WebApp:

```
#pragma warning disable SKEXP0022, SKEXP0052, SKEXP0011, SKEXP0003
            var memoryWithChroma = new MemoryBuilder()
                .WithChromaMemoryStore("http://localhost:8000")
                .WithLoggerFactory(loggerFactory)
                .WithOpenAITextEmbeddingGeneration("text-embedding-ada-002", Program.OpenAIKey)
                .Build();

            var memoryResults = memoryWithChroma.SearchAsync(collection: "content", query: question, limit: maxTokens / Program.ChunkMaxTokens);

            var results = new List<string>();

            await foreach (MemoryQueryResult memoryResult in memoryResults) // exception occurs here!!!
            {
                results.Add(memoryResult.Metadata.Text);
            }
#pragma warning restore SKEXP0022, SKEXP0052, SKEXP0011, SKEXP0003
```

But the exception is thrown:

```
Microsoft.SemanticKernel.KernelException
  Message=Unable to deserialize memory record metadata.
   at Microsoft.SemanticKernel.Connectors.Chroma.ChromaMemoryStore.GetMetadataForMemoryRecord(List`1 metadatas, Int32 recordIndex)
...
```

**Comment by mr-shevchenko** [comment]
**UPDATE:**

If I populate Chroma HTTP via Python code this way:

```
collection.add(
    ids = [str(uuid.uuid4())],
    documents = [chunk['CONTENT']],
    metadatas = {'URL': chunk['URL']}
)
```
then there is no exception with C# code:
```
#pragma warning disable SKEXP0022, SKEXP0011, SKEXP0003
            var memoryWithChroma = new MemoryBuilder()
                .WithChromaMemoryStore(Program.ChromaEndpoint)
                .WithLoggerFactory(loggerFactory)
                .WithOpenAITextEmbeddingGeneration("text-embedding-ada-002", Program.OpenAIKey)
                .Build();

            var memoryResults = memoryWithChroma.SearchAsync(collection: "content", query: question, limit: maxTokens / Program.ChunkMaxTokens, withEmbeddings: true);

            var results = new List<string>();

            await foreach (MemoryQueryResult memoryResult in memoryResults)
            {
                results.Add(memoryResult.Metadata.Text);
            }
#pragma warning restore SKEXP0022, SKEXP0011, SKEXP0003
```
But memoryResult.Metadata is always empty:

![image](https://github.com/microsoft/semantic-kernel/assets/64322872/b46f9974-e64d-4b09-8847-50a5fa65b23a)

How can I get text results of semantic search?

**Comment by Raudar** [comment]
Hi everyone, looks like we are getting the same issue as well.... 

Can anyone tell me what we can be doing wrong (I'm following the same steps from https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.Memory.Chroma as well) or if there is any kind of workaround?

**Comment by RogerBarreto** [comment]
Try using the interfaces save implementations to add the content to the memory database.

Looking into the details of Chrome, the implementations uses the [`upsert` endpoint](https://docs.trychroma.com/reference/Collection#upsert) in [here](https://github.com/microsoft/semantic-kernel/blob/05334dd4fad1456b1ed060b6f777c9dd63b25ecb/dotnet/src/Connectors/Connectors.Memory.Chroma/Http/ApiSchema/Internal/UpsertEmbeddingsRequest.cs#L30) to persist the data into the memory with the metadata and there is no implemetation using the `add` endpoint.

When using the current interfaces ensure you use something similar to the [Example14](https://github.com/microsoft/semantic-kernel/blob/05334dd4fad1456b1ed060b6f777c9dd63b25ecb/dotnet/samples/KernelSyntaxExamples/Example14_SemanticMemory.cs#L135) `SaveReferenceAsync` or `SaveInformationAsync` and how it actually persist data in Chroma.

Inspecting how the payload is sent to chroma for metadatas make sure it follows something similar to this:

```
{"ids":["https://github.com/microsoft/semantic-kernel/blob/main/README.md"],"embeddings":[[...]],"metadatas":[
{
    "is_reference":true,
    "external_source_name":"GitHub",
    "id": "https://github.com/microsoft/semantic-kernel/blob/main/README.md",
    "description": "README: Installation, getting started, and how to contribute",
    "text":"",
    "additional_metadata": ""
}]}
```
