### ISSUE TITLE
Support for Chroma embedding database

### ISSUE THREAD

**Issue by dluc** [microsoft/semantic-kernel#403]
Add support for Chroma https://docs.trychroma.com/

> Chroma is the open-source embedding database. Chroma makes it easy to build LLM apps by making knowledge, facts, and skills pluggable for LLMs.

**Comment by joowon-dm-snu** [comment]
does anyone work on this feature in your team?

**Comment by alexchaomander** [comment]
Thanks for creating a PR for this already @joowon-dm-snu!
