### ISSUE TITLE
.Net: Handlebars universal split helper

### ISSUE THREAD

**Issue by rnortje-sygnia** [microsoft/semantic-kernel#4070]
We found that the handlebars planner sometime hallucinates universal helpers. In our case it is the split function that takes a string and splits it using some delimiter. From the Discord chat it seems that requesting these to be added is simpler than trying to force the LLM not to include them.

**Comment by teresaqhoang** [comment]
Yeah I hear you, there will be changes coming in [PR #4017 .Net: Handlebars Prompt Template Helpers](https://github.com/microsoft/semantic-kernel/pull/4017/files#diff-7eb9a35210ae510f40ecde8fd286cc88de929e37e6309e2f9af7cc6f590d4e80)  that will allow users to easily add custom helpers when using the Handlebars Prompt Template Factory. 

You can reference the HandlebarsPlanner as example of how to do this, where `RegisterCustomCreatePlanHelpers` is a callback passed when initializing `PromptTemplateOptions` in `HandlebarsPlanner.cs`.
