### ISSUE TITLE
Invalid parameter count for function. 0 were specified but 3 are required.

### ISSUE THREAD

**Issue by sanchez** [microsoft/semantic-kernel#4073]
**Describe the bug**
I have noticed a weird interaction which I believe should not exist. I have a function which takes 3 doubles as inputs and creates a point in 3d space. I am using HandleBars Planner and if I prompt for `create a point where X=5, Y=3, Z=1` then I get a Microsoft.SemanticKernel.KernelException with the message: `Invalid parameter count for function ConstructPoint. 0 were specified but 3 are required.` The interesting thing is if I inspect the plan before it is executed then the `_template` property has the following value:

(I have replaced all the backticks in the `_template` output with `---` just to help with readability)

```handlebars
{{set "x" 5}}
{{set "y" 3}}
{{set "z" 1}}
---

2. Use the `{{PointPlugin-ConstructPoint}}` helper to create the point:
---handlebars
{{set "point" (PointPlugin-ConstructPoint x y z)}}
---

3. Print the result using the `{{json}}` helper:
---handlebars
{{json point}}
---

Putting it all together, the complete Handlebars template would look like this:

---handlebars
{{!-- Step 1: Initialize the variables --}}
{{set "x" 5}}
{{set "y" 3}}
{{set "z" 1}}

{{!-- Step 2: Create the point --}}
{{set "point" (PointPlugin-ConstructPoint x y z)}}

{{!-- Step 3: Print the result --}}
{{json point}}
```

Which would appear to line up with my request?

Even more interesting is if I prompt for `create a new point where X=5, Y=3, Z=1` then the `_template` property on the plan is a bit more different:

```handlebars
{{!-- Step 1: Create a new point with X=5, Y=3, Z=1 --}}
{{set "newPoint" (PointPlugin-ConstructPoint x=5 y=3 z=1)}}

{{!-- Step 2: Print the new point to the screen --}}
{{json (get "newPoint")}}
```

The second plan executes and outputs a JSON serialization of the point correctly.

Thanks,
Daniel

**Comment by matthewbolanos** [comment]
@teresaqhoang, since this scenario works with named arguments, it looks like it's probably just a bug with the positional arguments logic.

**Comment by teresaqhoang** [comment]
Definitely weird behavior, thanks for calling this out @sanchez! Can you share the function you're using so I can test locally? If not, can we schedule a call to do some parallel debugging?

**Comment by teresaqhoang** [comment]
Ahh @sanchez, @matthewbolanos caught this:

In the template you provided above, there's imbedded handlebars templates in the examples, so the parser is identifying `{{PointPlugin-ConstructPoint}}` as a plan step and trying to invoke the function without any arguments. We'll file this as a bug on our backlog 

```
{{set "x" 5}}
{{set "y" 3}}
{{set "z" 1}}
---

2. Use the `{{PointPlugin-ConstructPoint}}` helper to create the point:
---handlebars
{{set "point" (PointPlugin-ConstructPoint x y z)}}
---

3. Print the result using the `{{json}}` helper:
---handlebars
{{json point}}
---
```

**Comment by matthewbolanos** [comment]
Ended up running into this myself with the following generated plan

---
Plugins.MathSolver: Information: Plan: {{set "startNumber" 23}}
---

2. Create a variable to store the ending number, which is 35.
---handlebars
{{set "endNumber" 35}}
---

3. Calculate the number of terms in the sequence by subtracting the starting number from the ending number and adding 1.
---handlebars
{{set "numTerms" (Add (Subtract (get "endNumber") (get "startNumber")) 1)}}
---

4. Calculate the sum of the sequence using the formula: sum = (n/2) * (firstTerm + lastTerm), where n is the number of terms, firstTerm is the starting number, and lastTerm is the ending number.
---handlebars
{{set "sum" (Multiply (Divide (get "numTerms") 2) (Add (get "startNumber") (get "endNumber")))}}
---

5. Output the result using the `{{json}}` helper.
---handlebars
{{json (get "sum")}}
---

The complete template would look like this:
---handlebars
{{set "startNumber" 23}}
{{set "endNumber" 35}}
{{set "numTerms" (Add (Subtract (get "endNumber") (get "startNumber")) 1)}}
{{set "sum" (Multiply (Divide (get "numTerms") 2) (Add (get "startNumber") (get "endNumber")))}}
{{json (get "sum")}}

**Comment by sanchez** [comment]
[semantic-learning.zip](https://github.com/microsoft/semantic-kernel/files/13656156/semantic-learning.zip)

Attaching my code here just in case it can help further. One thing I have noticed is that with the handlebars planner I have lost a lot of "smarts" that I used to have before adding in handlebars. A good example is that try the prompt `turn the light on`, which should trigger the LightPlugin, however the planner isn't able to work out the state to be passed into the function argument unless I do something like: `set the light to newState=true`

**Comment by matthewbolanos** [comment]
@teresaqhoang, I'm finding that this happens _much_ more with gpt-3.5-turbo-0613.

@sanchez, until we get a proper fix, you may want to try gpt-4. I'm finding that the behavior is much more inline with what we're expecting.

**Comment by teresaqhoang** [comment]
Okay, planning to test the Planner with these models more closely today:

- gpt-4 (0613
- gpt-4-32k (0613)
- gpt-4 (1106)

Will keep y'all updated

**Comment by sanchez** [comment]
The `modelId` I have been using is `chatgpt-4k`, sorry is there a different modelId I should be using?

**Comment by teresaqhoang** [comment]
No, that's what I've been testing with too. Do you have the latest changes pulled? We merged a PR last night with improvements to the Handlebars Template Factory, so make sure you have those! 

I'll continue to test the positional args logic

**Comment by sanchez** [comment]
I still get the same exception, with the same handlebars execution `_template` as before. Using RC4

**Comment by sanchez** [comment]
Sorry, I have just realized I am not using RC4 and the version rolled back automatically because of #4257

**Comment by teresaqhoang** [comment]
@sanchez are you still seeing the same exception?

**Comment by sanchez** [comment]
Still testing sorry, something I have noticed is that if I omit the `name=value` and just go for a more natural language approach I get an error but I don't think that is related to this ticket?

**Comment by teresaqhoang** [comment]
@sanchez I removed the `get` helper altogether as part of our V1 release, so there should be less complexities with variable access. Hopefully this helps reduce some of the errors you're seeing related to syntax?

**Comment by teresaqhoang** [comment]
@sanchez closing this as resolved, please reopen if issue persists
