### ISSUE TITLE
.Net: Handlebars fail to process correctly result of asynchronous functions (when return type is Task<...>)

### ISSUE THREAD

**Issue by Gwenn-B** [microsoft/semantic-kernel#4076]
**Describe the bug**
When a kernel function return type is `Task<T>` (ex: `Task<string>`), the planner call it synchronously [here](https://github.com/microsoft/semantic-kernel/blob/755405aa87bdc46b7669f6c00d856a78925f8540/dotnet/src/Planners/Planners.Handlebars/Handlebars/HandlebarsTemplateEngineExtensions.cs#L434)
`FunctionResult result = function.InvokeAsync(kernel, new KernelArguments(state), cancellationToken: cancellationToken).GetAwaiter().GetResult();`

So, in result.Value is of `T` type, not `Task<T>` type

But the code then tries to Serialize and [Deserialize](https://github.com/microsoft/semantic-kernel/blob/755405aa87bdc46b7669f6c00d856a78925f8540/dotnet/src/Planners/Planners.Handlebars/Handlebars/HandlebarsTemplateEngineExtensions.cs#L445) using the [metadata type](https://github.com/microsoft/semantic-kernel/blob/755405aa87bdc46b7669f6c00d856a78925f8540/dotnet/src/Planners/Planners.Handlebars/Handlebars/HandlebarsTemplateEngineExtensions.cs#L439) (which is `Task<T>`)

So deserialization fails, trying to deserialize a `T` value on a `Task<T>` type

**To Reproduce**
1. Register a native KernelFunction with a `Task<T>` return type
2. create a plan with Handlebars that will uses this function
3. try to execute the plan

**Expected behavior**
Deserialize return type using `T` and not `Task<T>`

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: SemanticKernel RC3

**Comment by teresaqhoang** [comment]
This should be fixed in PR #4017 ! I added a `TryGetTaskResultType` extension method to the Type class
