### ISSUE TITLE
.Net: Convert Azure OpenAI FunctionDefinition to SK KernelFunction

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/semantic-kernel#4087]
Currently, `KernelFunction` can be transformed into an Azure OpenAI `FunctionDefinition`. Additionally, it would be beneficial if semantic-kernel supports the reverse process, making it easier for users to incorporate an OpenAI FunctionDefinition into the semantic kernel.

link to OpenAI `FunctionDefinition`
- https://learn.microsoft.com/en-us/dotnet/api/azure.ai.openai.functiondefinition?view=azure-dotnet-preview

**Comment by LittleLittleCloud** [comment]
> What would it mean to invoke such a KernelFunction?
Do you mean the converted `KernelFunction` won't be associated with an actual method so it's not clear on how to invoke it?

**Comment by stephentoub** [comment]
>> What would it mean to invoke such a KernelFunction?

> Do you mean the converted KernelFunction won't be associated with an actual method so it's not clear on how to invoke it?

I'm trying to understand what it is you're asking for. Given an arbitrary FunctionDefinition, all you know is metadata about the function in question: there's no code behind it, there's nothing to actually run.

So I'm trying to understand what it is you're actually looking to do.  Are you actually asking to get the original KernelFunction that was used to populate that FunctionDefinition? i.e. you want a variation of:
https://github.com/microsoft/semantic-kernel/blob/37f2760fdd146d49780e5fff859a2b79c39b7661/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/OpenAIPluginCollectionExtensions.cs#L20-L24
that takes a plugin collection and a FunctionDefinition and finds the associated KernelFunction from that collection?

Higher level, what's the scenario you're trying to achieve?

**Comment by matthewbolanos** [comment]
When I talked to @LittleLittleCloud, it sounded like their scenario was that they built a bunch of OpenAI functions already and would like to import them into a kernel as a plugin so that they don't need to rebuild it.

**Comment by stephentoub** [comment]
> When I talked to @LittleLittleCloud, it sounded like their scenario was that they built a bunch of OpenAI functions already and would like to import them into a kernel as a plugin so that they don't need to rebuild it.

I'd like to better understand what this means.  @LittleLittleCloud, can you elaborate?

**Comment by LittleLittleCloud** [comment]
I am currently integrating semantic kernel as an infrastructure interface for seamless interaction with LLM. Within my codebase, I have a dependency on Azure.AI.OpenAI.OpenAIClient, and I am in the process of transitioning those code to use either `OpenAIChatCompletion` or `AzureOpenAIChatCompletion`.

The main gap lies in the function_call aspect, where I have numerous function_call objects defined by `Azure.AI.OpenAI.FunctionDefinition`. To bring these `function_call` objects into `OpenAIChatCompletion` or `AzureOpenAIChatCompletion`, I  need to convert Azure.AI.OpenAI.FunctionDefinition into a format compatible with the semantic kernel. Unfortunately, there is currently no out-of-the-box solution available for this conversion.

To resolve the gap, converting `FunctionDefinition` to either `KernelFunction` or `OpenAIFunction` would work. Personally I lean towards to `KernelFunction`, because the function_definition object may convert to other function_definition format in the future.

**Comment by LittleLittleCloud** [comment]
> How did you get those FunctionDefinitions?

They are from various sources, I have a list of pre-defined `FunctionDefinition` that are created by the source generator. (for example, [here](https://github.com/LittleLittleCloud/AgentChat/blob/51f0f77888b4e6cd870a0a40f28d5a63c95d95e0/src/AgentChat.DotnetInteractiveService/DotnetInteractiveFunction.cs#L73). Or passed from constructor when creating an agent.[here](https://github.com/LittleLittleCloud/AgentChat/blob/51f0f77888b4e6cd870a0a40f28d5a63c95d95e0/src/AgentChat.OpenAI/GPTAgent.cs#L22)

For now every `FunctionDefinition` must be associated with an invoke function when passing towards an [agent](https://github.com/LittleLittleCloud/AgentChat/blob/51f0f77888b4e6cd870a0a40f28d5a63c95d95e0/src/AgentChat.OpenAI/GPTAgent.cs#L22). However, that restriction might be lifted in the future.

> KernelFunction is a representation of something that can be executed: it has an InvokeAsync method to invoke the code.

Then maybe converting to `OpenAIFunction` or `KernelFunctionMetaData` would be a better option, where a function definition isn't necessarily associated with an invoke function? After all, all I need is to convert `FunctionDefinition` to sk-support format so it can be consumed by  `OpenAIChatCompletion` or `AzureOpenAIChatCompletion`😊.

**Comment by stephentoub** [comment]
Thanks.

What I'm still missing is, FunctionDefinition is the Azure SDK's representation of just a function name/parameters to be sent as part of a tool call option. Why start from that in the first place?  If you're generating source, why generate the FunctionDefinition only and try to then convert it to something else rather than starting from the more general thing and then either deriving a FunctionDefinition from it or generating both the more general thing and the FunctionDefinition... why _only_ generate the FunctionDefinition and then try to convert it?
