### ISSUE TITLE
Upgrade Azure.AI.OpenAI dependency

### ISSUE THREAD

**Issue by dluc** [microsoft/semantic-kernel#4094]
Current:
```
<PackageVersion Include="Azure.AI.OpenAI" Version="1.0.0-beta.9" />
```

Request: `1.0.0-beta.10` released  on 12/6, or whatever the last is.

See also: https://github.com/microsoft/kernel-memory/issues/190

Thanks

**Comment by stephentoub** [comment]
https://github.com/microsoft/semantic-kernel/pull/4089

**Comment by dluc** [comment]
dupe of https://github.com/microsoft/semantic-kernel/issues/3972
