### ISSUE TITLE
.Net: string createPlanPromptTemplate can be made optional for the HandlebarsPlan constructor

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4103]
Today the constructor for the `HandlebarsPlan` is the following

```csharp
public HandlebarsPlan(string generatedPlan, string createPlanPromptTemplate)
{
    this._template = generatedPlan;
    this.Prompt = createPlanPromptTemplate;
}
```

My assumption is that the createPlanPromptTemplate is used for retry/self-healing logic in the future (?). Because the user might now have the original create plan prompt, this parameter can be made optional. If it's not provided the self-healing logic will not be avaialble.

**Comment by teresaqhoang** [comment]
I added to Prompt to the plan object so users can easily inspect it if they needed to. Will consider your point though when implementing the retry logic
