### ISSUE TITLE
There should be a `GetFunctionsMetadata()` method on `KernelPlugin`

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4105]
The old planners had the ability to apply filtering to plugins before creating a plan.

In V1.0.0, I should be able to achieve this by doing the following...

1. Create a new `KernelPlugin` (**without adding to a kernel**)
2. Populate a vector DB with the function metadata
3. Perform a vector DB search using the user query to retrieve the relevant functions
4. Create and import a new `KernelPlugin` into the kernel
5. Run the planner on the kernel with the subset of functions.

Unfortunately step 2 is not possible because the `GetFunctionsMetadata()` only exists on plugins added to a kernel via `kernel.Plugins.GetFunctionsMetadata()`.

**Comment by matthewbolanos** [comment]
@markwallace-microsoft, assigned this one to you since you just touched `KernelPlugin`. Feel free to take yourself off if someone else should do it.

**Comment by matthewbolanos** [comment]
@markwallace-microsoft, was able to satisfy my scenario by just enumerating over the functions in the plugin, so now I'm actually not sure if this is necessary or not. Keeping it as a v1.0+ item just in case we think this is valuable later.

**Comment by stephentoub** [comment]
This exists for an enumerable of plugins:
https://github.com/microsoft/semantic-kernel/blob/37f2760fdd146d49780e5fff859a2b79c39b7661/dotnet/src/SemanticKernel.Abstractions/Functions/KernelPluginExtensions.cs#L82-L96
so if you don't want to enumerate yourself, you can do (the very unintuitive):
```C#
new[] { plugin }.GetFunctionsMetadata()
```
I agree it would make sense to add it as an instance method to KernelPlugin, if for no other reasons than:
a) I don't want folks to write the above :)
b) If you iterate through a plugin's functions yourself to get the metadata, it's easy to neglect to create a new metadata instance that has the plugin's name populated
