### ISSUE TITLE
Python: sk_function Log is optional but not checked when used, gives error

### ISSUE THREAD

**Issue by benharrell** [microsoft/semantic-kernel#4106]
https://github.com/microsoft/semantic-kernel/blob/37f2760fdd146d49780e5fff859a2b79c39b7661/python/semantic_kernel/orchestration/sk_function.py#L152

if you pass 'auto' for function calling but don't pass functions during kernel run this line will give an error

NoneType object has no attribute warning

obviously this is because Log is None....

**Comment by juliomenendez** [comment]
This issue should go away if my PR moving to Python standard logging practices is approved #4115
