### ISSUE TITLE
.Net Agent - Support Logging

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#4109]
Support standard logging throughout agent framework.

**Comment by ThirstyJarek** [comment]
@matthewbolanos just wondering if there's any info on when this might get done? Currently there does not seem to be any way to pass a logger into the Agent object, so it seems like we cannot log the internal operations like you can with the other objects like KernelPlugin or Kernal.

**Comment by crickman** [comment]
Thank you for supporting the priority for this task @ThirstyJarek.  I drafted an update before the new year holiday and am iming to get this in for the next package release (sometime this week).

**Comment by ThirstyJarek** [comment]
Great to hear, thanks!
