### ISSUE TITLE
.Net Agent - Support Clone operation for IAssistant

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#4110]
Align with Kernel.Clone()

**Comment by crickman** [comment]
@SergeyMenshykh - Can you consider this as part of the larger agent design?

**Comment by SergeyMenshykh** [comment]
@crickman - it would be good to understand scenarios it's needed for to design it properly and consider other available options to model it.

**Comment by crickman** [comment]
Will re-evaulate in the new agent framework.
