### ISSUE TITLE
$.input' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.

### ISSUE THREAD

**Issue by aherrick** [microsoft/semantic-kernel#4114]
I just started getting this exception as of today. Nothing has changed on my end. I'm not even using any of Open AI tech, strictly Azure AI.

If I resubmit with the same query, it goes through fine. What might be going on here?

This is how I'm building up my Memory Builder search:

```
            var acsMS = new AzureCognitiveSearchMemoryStore(azureCognitiveSearchConfig.Endpoint, azureCognitiveSearchConfig.Key);
            var azureAIMemoryService = new MemoryBuilder()
                  //.WithLoggerFactory(ConsoleLogger.LoggerFactory)
                  .WithAzureOpenAITextEmbeddingGeneration(azureCognitiveSearchConfig.DeploymentName, azureCognitiveSearchConfig.ModelName, azureOpenAIConfig.Endpoint, azureOpenAIConfig.Key)
                  .WithMemoryStore(acsMS)
                  .Build();
```

// fails here:
`    await foreach (var result in azureAIMemoryService.SearchAsync(chatDto.ChatType.ToString(), chatDto.Query, limit: 3, minRelevanceScore: 0.5))`

**Comment by ShashankInteli** [comment]
how  you configured it??
