### ISSUE TITLE
.Net Bug Service Selector is ignoring ExecutionSettings from Invoke Async Calls.

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#4127]
**Describe the bug**

When using function/kernel `InvokeAsync` the any `ExecutionSettings` provided in the `KernelArguments` are being ignored.

https://github.com/microsoft/semantic-kernel/blob/1c1da87b2ad35a891578362c3917d1bf49c621a0/dotnet/src/SemanticKernel.Abstractions/Services/OrderedAIServiceSelector.cs#L23

```diff
- var executionSettings = function.ExecutionSettings;
+ var executinoSettings = (arguments.ExecutionSettings is not null)
+     ? new List<PromptExecutionSettings> { arguments.ExecutionSettings }
+     : function.ExecutionSettings;
```

## Open Question

@SergeyMenshykh `kernelArguments.ExecutionSettings` is a single element while the `function.ExecutionSettings` is a `List`. 

IMO we should consider passing a list of execution settings to the KernelArguments to be as flexible as when initializing prompt functions.

```


```

**Comment by markwallace-microsoft** [comment]
The `KernelArguments.ExecutionSettings` is an override that will replace whatever the service selector provides. The `Function.ExecutionSettings` is to allow developers to fine tune a prompt to work with different models. 

The service selector allows developer to add any arbitrary logic they want to build the execution settings. So I think this is enough flexibility until we learn of use cases which cannot be supported using the above.

**Comment by RogerBarreto** [comment]
@markwallace-microsoft 

If I'm invoking a function in a kernel with multiple services I might want to set a configuration that could have multiple outcomes (list) in the KernelArguments depending on what is the modelId used, today I'm not able to do so using the InvokeAsync, just in the function configuration.

**Comment by markwallace-microsoft** [comment]
Here's the scenario we want to support

```csharp
KernelBuilder builder = new();
builder.Services.AddKeyedSingleton<ITextGenerationService>("service1", mockTextCompletion1.Object);
builder.Services.AddKeyedSingleton<ITextGenerationService>("service2", mockTextCompletion2.Object);
Kernel kernel = builder.Build();

KernelFunction function = KernelFunctionFactory.CreateFromPrompt("Prompt");

var result1 = await kernel.InvokeAsync(function, new(new OpenAIPromptExecutionSettings { ServiceId = "service1", MaxTokens = 1000 }));
var result2 = await kernel.InvokeAsync(function, new(new OpenAIPromptExecutionSettings { ServiceId = "service2", MaxTokens = 2000 }));
```

**Comment by RogerBarreto** [comment]
We might consider adding support for those:

```
var result1 = await kernel.InvokeAsync(function, new(new [] { 
        new OpenAIPromptExecutionSettings { ServiceId = "service1", MaxTokens = 1000 },
        new OpenAIPromptExecutionSettings { ServiceId = "service2", MaxTokens = 2000 }
    )
);
```
