### ISSUE TITLE
.Net: Better troubleshoot problems

### ISSUE THREAD

**Issue by alkampfergit** [microsoft/semantic-kernel#4143]
I've created three plugins, two are C# functions the latter is a skernel.txt prompt. One extract audio from mp4, the other use OpenAI whisper to extract transcript the latter summarize the timeline of the video.

I'm not using planner, but simple chat functions (as I saw in demo project) using the AutoInvokeKernelFunctions

```csharp
OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
{
    FunctionCallBehavior = FunctionCallBehavior.AutoInvokeKernelFunctions
};
```

Sometimes everything went perfectly good. If I enable trace I can see that the last plugin was invoked using the transcript taken from the second plugin.

![image](https://github.com/microsoft/semantic-kernel/assets/358545/f02f8f20-b86a-4666-8177-1c79ad9c43c3)

Sometimes, with the very same code, it does not work. The OpenAI whisper plugin gets called perfectly, but when it is time to invoke the third plugin I have a warning because the transcript parameter is empty, and from trace I can indeed verify that the prompt sent to LLM does not have any data.

![image](https://github.com/microsoft/semantic-kernel/assets/358545/d2761672-2634-4bd8-b488-4a2e34249765)

Now I need to troubleshoot this kind of problem, understanding why sometimes it does not work, maybe my plugin description is not so good, but nevertheless I wonder why sometimes it works sometimes not.

I'd like to have more information about the prompt used to determine parameters, I'd like to copy and paste directly into Azure Api playground to verify what happens if I change description of plugin or plugin parameters.

**Comment by stephentoub** [comment]
> I'd like to have more information about the prompt used to determine parameters, I'd like to copy and paste directly into Azure Api playground to verify what happens if I change description of plugin or plugin parameters.

If you want to see exactly what the OpenAIClient is putting on the wire as part of the HTTP request, you can try injecting an appropriate logger to do so, e.g.
```C#
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Http.Logging;
using Microsoft.Extensions.Logging;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.AI.OpenAI;

KernelBuilder builder = new();
builder.AddOpenAIChatCompletion("gpt-3.5-turbo", Environment.GetEnvironmentVariable("YourAPIKeyForOpenAI")!);
builder.Services.AddLogging(c => c.AddConsole().SetMinimumLevel(LogLevel.Trace));
builder.Services.ConfigureHttpClientDefaults(c => c.AddLogger(s => new RequestBodyLogger(s.GetRequiredService<ILogger<RequestBodyLogger>>())));

Kernel kernel = builder.Build();
kernel.Plugins.Add(new KernelPlugin("TimeFunctions", new[]
{
    kernel.CreateFunctionFromMethod(() => DateTime.UtcNow.ToString("R"), "GetCurrentUtcTime"),
}));

var settings = new OpenAIPromptExecutionSettings { FunctionCallBehavior = FunctionCallBehavior.AutoInvokeKernelFunctions };

Console.WriteLine(await kernel.InvokePromptAsync("What time is it in New York City?", new(settings)));

sealed class RequestBodyLogger(ILogger logger) : IHttpClientAsyncLogger
{
    public async ValueTask<object?> LogRequestStartAsync(HttpRequestMessage request, CancellationToken cancellationToken = default)
    {
        logger.LogTrace("Request: {Request}", request);
        logger.LogTrace("Request content: {Content}", await request.Content!.ReadAsStringAsync(cancellationToken));
        return default;
    }

    public object? LogRequestStart(HttpRequestMessage request) => null;
    public void LogRequestStop(object? context, HttpRequestMessage request, HttpResponseMessage response, TimeSpan elapsed) { }
    public ValueTask LogRequestStopAsync(object? context, HttpRequestMessage request, HttpResponseMessage response, TimeSpan elapsed, CancellationToken cancellationToken = default) => default;
    public void LogRequestFailed(object? context, HttpRequestMessage request, HttpResponseMessage? response, Exception exception, TimeSpan elapsed) { }
    public ValueTask LogRequestFailedAsync(object? context, HttpRequestMessage request, HttpResponseMessage? response, Exception exception, TimeSpan elapsed, CancellationToken cancellationToken = default) => default;
}
```

**Comment by alkampfergit** [comment]
Thanks a lot for the example

Il dom 10 dic 2023, 21:04 Stephen Toub ***@***.***> ha
scritto:

**Comment by matthewbolanos** [comment]
@alkampfergit, please reopen this issue if the sample is not sufficient.

**Comment by alkampfergit** [comment]
Actually I've implemented a sligtly modified version and everything works as expected.
