### ISSUE TITLE
.Net: Handlebars planner doesn't use the previous plan and previous error.

### ISSUE THREAD

**Issue by kbeaugrand** [microsoft/semantic-kernel#4144]
**Describe the bug**
The handlebars planner don't use previous plan and previous error when creating a plan.

**To Reproduce**
1. Using Math plugin
2. Tying to create a complexe plan
3. Some errors can occur
4. Plans are not updated.

**Expected behavior**
The previous plan should taken in account to avoid reproduce the same error.

**Screenshots**
N/A

**Platform**
 - OS: N/A
 - IDE: N/A
 - Language: C#
 - Source: main branch

**Additional context**

**Comment by sanchez** [comment]
Is this related to #4072 ?

**Comment by kbeaugrand** [comment]
> Is this related to #4072 ?

Don't think so.

**Comment by teresaqhoang** [comment]
Hi @kbeaugrand, thanks so much for your PR! I had retry logic tracked as one of the enhancements to look at next in #4252. 

Marking this as `vnext` and will take a look after we've burned down our V1 Release priorities
