### ISSUE TITLE
.Net: Sample notebooks require DotNet 8

### ISSUE THREAD

**Issue by PaulStubbs** [microsoft/semantic-kernel#4149]
**Describe the bug**
Sample notebooks do not open when using a docker container. DotNet version 8 is required by Polyglot Notebooks. The devcontainer.json file should be bumped from 7 to 8.

**To Reproduce**
1. Launch workspace in a docker container
2. open the notebook /dotnet/notebooks/0-AI-settings.ipynb
3. Error tells you that DotNet 7 is not supported

**Expected behavior**
The notebook file should open.

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#
 - Source: main branch of repository

**Additional context**
Fix is to update /.devcontainer/devcontainer.json to version 8
		"ghcr.io/devcontainers/features/dotnet:1": {
			"version": "8"
		},

**Comment by glahaye** [comment]
Thank you for bringing this up.  PR #4201 is out now to take care of this.
