### ISSUE TITLE
.Net: Function calling passes empty arguments to a prompt function

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/semantic-kernel#4164]
**Describe the bug**
I have a sample project which uses Semantic Kernel which includes 3 plugins:

- A plugin with two native functions, which are used to retrieve statistical data about the United States
- A plugin with a prompt function, which is used to generate a business mail

My goal is to process the following prompt:

```
Write a mail to share the population of the United States in 2015. Then add also, among the population, how many people identified themselves as male. Don't share approximations, please share the exact numbers.
```

In order to get a response, I need Semantic Kernel to use all the three plugins I've loaded. As such, I've enabled function calling in the following way:

```
OpenAIPromptExecutionSettings settings = new()
{
    FunctionCallBehavior = FunctionCallBehavior.AutoInvokeKernelFunctions
};

var chatHistory = new ChatHistory();
chatHistory.AddUserMessage("Write a paragraph to share the population of the United States in 2015. Then add also, among the population, how many people identified themselves as male. Don't share approximations, please share the exact numbers.");

var chatCompletionService = kernel.Services.GetService<IChatCompletionService>();
var result = await chatCompletionService.GetChatMessageContentAsync(chatHistory, settings, kernel);
```

The code works, but the outcome is partially correct. I can see that the two native functions are properly called, while the prompt function to write a business mail don't. The text of the mail has been clearly generated by the LLM without following any of the instructions I have in my prompt function.
I've switched to manual function calling to better debug what's going on with the following code:

```
OpenAIPromptExecutionSettings settings = new()
{
    FunctionCallBehavior = FunctionCallBehavior.EnableKernelFunctions
};

var chatHistory = new ChatHistory();
chatHistory.AddUserMessage("Write a paragraph to share the population of the United States in 2015. Then add also, among the population, how many people identified themselves as male. Don't share approximations, please share the exact numbers.");

var chatCompletionService = kernel.Services.GetService<IChatCompletionService>();
var result = await chatCompletionService.GetChatMessageContentAsync(chatHistory, settings, kernel);

//as long as the content is null, it means that the chat completion service is waiting for a function call to be processed
var functionCall = ((OpenAIChatMessageContent)result).GetOpenAIFunctionResponse();
while (functionCall != null)
{
    KernelFunction pluginFunction;
    KernelArguments arguments;
    kernel.Plugins.TryGetFunctionAndArguments(functionCall, out pluginFunction, out arguments);
    var functionResult = await kernel.InvokeAsync(pluginFunction!, arguments!);
    Console.WriteLine(functionResult.GetValue<string>());
    chatHistory.AddFunctionMessage(functionResult.GetValue<string>(), functionResult.Function.Name);

    result = await chatCompletionService.GetChatMessageContentAsync(chatHistory, settings, kernel);
    functionCall = ((OpenAIChatMessageContent)result).GetOpenAIFunctionResponse();
}


Console.WriteLine(result.Content);
Console.ReadLine();
```

By analyzing the functions that are defined, I can see that the problem lies in the prompt function. If the two native functions are called with the proper input parameter (year = 2015), the prompt function is called with an empty argument. Instead, it should receive as parameter, the output of the two previous functions.

I can clearly see this by printing the output of each function:

![image](https://github.com/microsoft/semantic-kernel/assets/1230332/ded8baf6-84a2-4a7f-b663-03f9e771608c)

You can notice how the first two outputs are correct, while the last one is complaining that the prompt function didn't receive any text as input.

If I use the same exact plugins with a HandlebarPlanner, instead of using function calling, everything works as expected.

**To Reproduce**
The sample project is available here https://github.com/qmatteoq/SemanticKernel-Demos/tree/rc/SemanticKernel.Orchestration

**Expected behavior**
All the three plugins I've loaded into the kernel are used to generate the response to my prompt.

**Platform**
- OS: Windows
- IDE: Visual Studio 2022 (17.8.3)
- Language: C#
- Source: NuGet package version RC3

**Comment by darakawa** [comment]
Same happened to me when function imported from directory was called (without planner, call behavior set to auto, RC3).

**Comment by matthewbolanos** [comment]
This sounds like it could be an issue with passing the input schema to function calling for prompt functions.

**Comment by stephentoub** [comment]
The problem is here:
https://github.com/microsoft/semantic-kernel/blob/46f3dbc737e52085a399040d3858cdbb93cac3b3/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/OpenAIFunction.cs#L146-L155

For whatever reason, the "input" parameter lacks both a type and a schema, and as a result this if block doesn't add the parameter to the FunctionDefinition, and the model is effectively told the function is parameterless.

I'm not sure if that means:
a) This logic needs to change (e.g. to produce a default type like string when none is defined)
b) The prompt import logic needs to change to always provide a type/schema
c) The config is somehow incorrect
d) Something else so cool I don't even know about it
e) More than one of the above

cc: @markwallace-microsoft, @alliscode

**Comment by matthewbolanos** [comment]
I believe we only "auto-create" the parameters for semantic-kernel template types. In these scenarios, the parameter is always a string, so I think we can do (b) and update the prompt import logic to always set the type/schema to string.
