### ISSUE TITLE
.Net: Make it easier to import heterogenous plugins (native functions + prompts)

### ISSUE THREAD

**Issue by DM-98** [microsoft/semantic-kernel#4168]
**Describe the bug**
It's not possible to import both native functions and semantic functions in one plugin the way the documentations & github code examples do it. Sources used:
- https://learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/plugins/native-functions/using-the-skfunction-decorator?tabs=Csharp#finding-a-home-for-your-native-functions
- https://github.com/MicrosoftDocs/semantic-kernel-docs/blob/main/samples/dotnet/09-Calling-Nested-Functions-in-Native-Functions/Program.cs

The bug happens when trying to do:
```
MutatedKernel.ImportPluginFromPromptDirectory(Path.Combine(Directory.GetCurrentDirectory(), "Plugins", "LandbrugnetPlugin"));
MutatedKernel.ImportPluginFromType<LandbrugnetPlugin>();
```
Exception:
`ArgumentException: An item with the same key has already been added. Key: LandbrugnetPlugin` 

**Expected behavior**
I expect to have a LandbrugnetPlugin-folder and in that folder, I have a .cs file (native functions live in that), and also subfolders (semantic functions) where their config & skprompt live.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/10290906/bcf079ea-012c-4e14-86fe-2050086dd761)
![image](https://github.com/microsoft/semantic-kernel/assets/10290906/db85023d-cf9d-4064-8969-4c196e48f864)

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio
 - Language: C#
 - Source: `<PackageReference Include="Microsoft.SemanticKernel" Version="1.0.0-rc3" />`

**Additional context**
I asked Discord, and they can't seem to help either, so I thought to create this issue. Anything helps, thanks!

I found a workaround though:
```
KernelPlugin landbrugnetPlugin = (KernelPlugin)MutatedKernel.ImportPluginFromPromptDirectory(Path.Combine(Directory.GetCurrentDirectory(), "Plugins", "LandbrugnetPlugin"));

IKernelPlugin landbrugnetPluginWithNativeFunctions = MutatedKernel.CreatePluginFromType<LandbrugnetPlugin>();
landbrugnetPlugin.AddFunctions(landbrugnetPluginWithNativeFunctions);
```

**Comment by noeltupas** [comment]
A previous version of the SDK allowed this (1.0.0-beta4), assuming it simply checked for key existence and added to the plugin's functions vs what it's doing now. 

I too would appreciate having this ability again. Was intuitive for us to be able to augment Semantic functions with Native ones in our workflows.

**Comment by markwallace-microsoft** [comment]
You can merge the plugins together by using the KernelPluginFactory.CreateFromFunctions method
