### ISSUE TITLE
.Net: When using Dependency Injection (DI), I'm seeing planning/processing of native functions try to include function parameters that should have been resolved by DI.

### ISSUE THREAD

**Issue by jordanbean-msft** [microsoft/semantic-kernel#4174]
**Describe the bug**
When using Dependency Injection (DI), I'm seeing planning/processing of native functions try to include function parameters that should have been resolved by DI.

**To Reproduce**
```csharp
 [KernelFunction, Description("...")]
 [return: Description("...")]
 public async Task<string> HistoricalWeatherLookupAsync(
     [Description("...")] double latitude,
     [Description("...")] double longitude,
     [Description("...")] int monthOfYear,
     [FromServices]DaprClient daprClient,
     ILogger logger,
     CancellationToken cancellationToken)
 {
```

Here is a print out of part of the plan.

```json
{
    "name": "HistoricalWeatherLookupPlugin_HistoricalWeatherLookup",
    "description": "...",
    "parameters": {
      "type": "object",
      "required": ["latitude", "longitude", "monthOfYear", "daprClient"],
      "properties": {
        ...
        "monthOfYear": {
          "type": "integer",
          "description": "..."
        },
        "daprClient": {
          "type": "object",
          "properties": {
            "JsonSerializerOptions": {
              "type": "object",
              "properties": {
                "Converters": { "$ref": "#/$defs/iListOfJsonConverter" },
                ...
```

This results in a huge number of extra tokens being used to try and deal with a parameter that OpenAI is not meant to resolve itself.

**Expected behavior**
In this example, I would have expected the `DaprClient` parameter to be resolved via DI (the `FromServices` attribute is how you indicate in a MVC controller that a parameter should be resolved via DI instead of passed in by the caller). The `ILogger` parameter does get resolved correctly. 

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: rc3

**Additional context**
Of course, I can move this parameter to the constructor and it does get resolved via DI.

```csharp
public class HistoricalWeatherLookupPlugin(DaprClient daprClient)
{
```

Is the function parameter DI pattern supported or only via the constructor?

**Comment by stephentoub** [comment]
> Is the function parameter DI pattern supported or only via the constructor?

[KernelFunction]s do not currently satisfy arguments from the IServiceProvider.  It's something that could be added fairly simply, with a bit of additional code right here:
https://github.com/microsoft/semantic-kernel/blob/a5a4b7f3f7bbe441ef674f67801a43eaac720738/dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromMethod.cs#L331-L333
it just hasn't been done yet due to lack of motivating scenarios. @SergeyMenshykh and I were discussing this earlier this week, actually.

cc: @matthewbolanos, @markwallace-microsoft

**Comment by stephentoub** [comment]
> This results in a huge number of extra tokens being used to try and deal with a parameter that OpenAI is not meant to resolve itself.

Ah... this part would require more code to address.  What I mentioned above would retrieve the service from the IServiceProvider and use the result to fulfill the [KernelFunction] method's argument, but it would not handle changing what metadata for that function gets sent as part of function calling.  That would be a much larger / more impactful change that would require more thought about how to generalize it.
