### ISSUE TITLE
.Net: Handlebars planner does not pass context variables in kernel functions

### ISSUE THREAD

**Issue by alessandro-avila** [microsoft/semantic-kernel#4196]
I'm running an application leveraging on the HandlebarsPlan Planner.
The application is about getting energy values from devices. Those values are retrieved from a CosmosDb instance through Native Functions.
I import the following functions into my plugin:
[Kernel Functions]
- PreProcess: to extract single IDs / values from the user's request.
- PostProcess: additional context to provide to the model before returning a response back to the user.
- JsonObjectToArray: given a json as input, provides an array with values for a specific variable, extracted from the user's request.

[Native Functions]
- RetrieveEnergyDataBySiteAndDeviceAsync: invokes CosmosDB queries to get data from the storage.
- ...
- ...

Here's the generated Handlebars template (I omit customer sensitive data):
```
{!-- Step 1: Initialize the siteId, deviceId and startDate --}}
{{set "siteId" "[the-site-id]"}}
{{set "deviceId" "[the-device-id]"}}
{{set "startDate" "[the-date-from-the-user-request"}}

{{!-- Step 2: Retrieve the energy consumption data for the device --}}
{{set "energyData" (EnergyData-RetrieveEnergyDataBySiteAndDevice siteId=(get "siteId") deviceId=(get "deviceId") startDate=(get "startDate"))}}

{{!-- Step 3: Convert the energy data to an array of numbers --}}
{{set "energyArray" (EnergyManagerPlugin-JsonObjectToArray input=(get "energyData"))}}

{{!-- Step 4: Sum the energy consumption data --}}
{{set "totalEnergy" (MathOps-SumStringArray input=(get "energyArray"))}}

{{!-- Step 5: Generate the final response for the user --}}
{{json (EnergyManagerPlugin-PostProcess result=(get "totalEnergy") chatHistory="how much energy did device '[the-device-id]' consumed since '[startDate]'?")}}
```

The template seems totally fine to me.
During planner execution, the C# native method in **Step2** is returning a json object.
The json object should then be passed to the Kernel Function in **Step 3** whose skprompt.txt is:
```
Given a json as input describing an array of devices, provide an array with the values of the Energy variable.

Example of input: [{"id":"1","Energy ":1},{"id":"2","Energy ":2},{"id":"3","Energy ":3.2},{"id":"4","Energy ":4},{"id":"5","Energy ":5}]
Example of output: [1, 2, 3.2, 4, 5]

This is the json input:

### START JSON
{{$input}}
### END JSON

Remember to return only the array of values!
```

config.json:
```
{
	"schema": 1,
	"description": "Given a json as input, return a list of numbers containg all the values for the requested variable.",
	"models": [
		{
			"max_tokens": 2048,
			"temperature": 0,
			"top_p": 0.0,
			"presence_penalty": 0.0,
			"frequency_penalty": 0.0
		}
	],
	"input": {
		"parameters": [
			{
				"name": "input",
				"description": "A json object, representing values for devices",
				"defaultValue": ""
			}
		]
	}
}
```

Here seems that the **$input** context variable is not assigned any value, indeed, in the following step (**Step 4**), the input parameter for the **SumStringArray** method is equal to: "It seems like you've forgotten to provide the JSON input between the START JSON and END JSON makers".

SumStringArray method:
```
[KernelFunction, Description("Do the sum of an array of numbers.")]
public double SumStringArray(
[Description("Array of numbers as string")] string input
)
{
    logger.LogInformation("Executing {FunctionName} function. Params: {parameters}", nameof(SumStringArray), string.Join(", ", input));

    var array = JsonConvert.DeserializeObject<double[]>(input);
    var result = (long)(array ?? Array.Empty<double>()).Sum();

    logger.LogInformation("result={result}.", result);
    return result;
}
```

I tried to change return value for the RetrieveEnergyDataBySiteAndDevice (string / object) but I faced the same issue.

UPDATE: i changed the **Step 3** function into a native one, but a similar issue happens on the last step: the **$chatHistory** variable is empty.

**Platform**
 - OS: Windows
 - IDE: Visual Studio 2022
 - Language: C#
 - Source: Semantic Kernel 1.0.0-rc3
 - NET 8.0

**Comment by matthewbolanos** [comment]
@teresaqhoang, do you know if your latest PR fixes this? The tl;dr is that it looks like the output isn't correctly being sent as the "input" param of a prompt funciton.

**Comment by alessandro-avila** [comment]
I thought that i should provide a skprompt written in Handlebars syntax; however, according to the docs, I'm supposed to work with natural language:
```
/// <summary>
/// Allow to define a prompt function passing in the definition in natural language, i.e. the prompt template.
/// </summary>
/// <param name="promptTemplate">Plain language definition of the prompt function, using SK template language</param>
/// <param name="promptConfig">Prompt template configuration.</param>
/// <param name="loggerFactory">Logger factory</param>
/// <returns>A function ready to use</returns>
public static KernelFunction Create(
    IPromptTemplate promptTemplate,
    PromptTemplateConfig promptConfig,
    ILoggerFactory? loggerFactory = null)
{ ... }
```

**Comment by teresaqhoang** [comment]
I think this is related to some API changes that haven't been addressed in the Handlebars Planner yet (e.g., pivot to `KernelArguments`, strong typing of `OpenAIChatMessageContent` for semantic function results, etc.), so the result of the `RetrieveEnergyDataBySiteAndDevice` isn't being recognized after the function is invoked.

I haven't had a chance to revisit the HandlebarsPlanner since these changes, but the work in my PR #4017 maps all the arguments and handlebars execution variables into one property bag, so it should address this issue as well as other bugs I found related to function result handling.

Hopefully the PR will be merged today!

**Comment by teresaqhoang** [comment]
Currently, we explicitly start the planner with no initial context or property bag. If you wanted to 

> I thought that i should provide a skprompt written in Handlebars syntax; however, according to the docs, I'm supposed to work with natural language:
> 
> ```
> /// <summary>
> /// Allow to define a prompt function passing in the definition in natural language, i.e. the prompt template.
> /// </summary>
> /// <param name="promptTemplate">Plain language definition of the prompt function, using SK template language</param>
> /// <param name="promptConfig">Prompt template configuration.</param>
> /// <param name="loggerFactory">Logger factory</param>
> /// <returns>A function ready to use</returns>
> public static KernelFunction Create(
>     IPromptTemplate promptTemplate,
>     PromptTemplateConfig promptConfig,
>     ILoggerFactory? loggerFactory = null)
> { ... }
> ```

Are you trying to invoke the planner or create your own semantic function?

**Comment by teresaqhoang** [comment]
@alessandro-avila we pushed a lot of improvements to output / input parsing in Handlebars Prompt templates with the V1 release, so I'm going to close this out as I haven't heard any further issues. 

Feel free to re-open if you're still seeing the issue!
