### ISSUE TITLE
.Net: Cache Generic Types Extraction - Handlebars

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/semantic-kernel#4202]
When creating the function manual for the Handlebars Planner, we extract the result type for all generics. This is a method I added in [TypeExtensions.cs](https://github.com/microsoft/semantic-kernel/pull/4017/files#diff-00a8498789195284ae627bf8e64f4c765b2626d1c197c60e1869632960f207b5)

Currently, it's a very expensive operation, and we are temporarily living with the overhead since it doesn't impact the public API space, but Stephen suggested putting a cache in place, e.g. a static readonly ConcurrentDictionary that maps the input to the output, so that you only need to compute the answer for a given type once. 

Two use cases:
1. Parsing a function's result using its expected return type in [KernelFunctionHelpers](https://github.com/microsoft/semantic-kernel/pull/4017/files#diff-0f9ade1599bd2c775dee97e950bf160717c1a7cd7e501f44db1b4823a002dc59)
2. To show the actual expected type when rendering the available functions manual in the HandlebarsPlanner CreatePlan prompt (so the planner is more effective at mapping inputs/outputs between functions)
See [KernelParameterMetadtaExtensions](https://github.com/microsoft/semantic-kernel/pull/4017/files#diff-2a162f0d7dac6969c1f99e9d78f94417eb0d6c0a5673f1de1edd971d39f75543)

The first case is not that important anymore with the new FunctionResult and its ValueType we can leverage.

**Comment by matthewbolanos** [comment]
Closing since development on the Handlebars is on pause as we develop a Python planner
