### ISSUE TITLE
.Net: Execution settings don't appear to be honored

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4208]
I have the following function. The temperature is set at `2`, but when I run it, the temperature is not being set for the OpenAI settings. In the picture, you can see that the temperature is `2` and the max tokens is `4000`, but the OpenAI settings object only has `MaxTokens`

<img width="539" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1409190/742a3019-ccae-4224-88e6-02eff22d45ab">

What's weird is that `MaxTokens` _is_ being set. It's also strange that the `JsonPropertyName` attribute doesn't seem to be used, i.e., `MaxTokens` works, but `max_tokens` does not.

```csharp
var chat = kernel.CreateFunctionFromPrompt(
    new PromptTemplateConfig()
    {
        Template = @"{{ConversationSummaryPlugin.SummarizeConversation $history}}
        User: {{$request}}
        Assistant: ",
        TemplateFormat = "semantic-kernel",
        InputVariables = [
            new() { Name = "history", Description = "The history of the conversation.", IsRequired = false, Default = "" },
            new() { Name = "request", Description = "The user's request.", IsRequired = true }
        ],
        ExecutionSettings = [
            new() {
                // Default settings for all models
                ExtensionData = new() {
                    { "MaxTokens", 1000 },
                    { "Temperature", 2 }
                }
            },
            new() {
                // Settings for gpt-3.5-turbo
                ModelId = "gpt-3.5-turbo",
                ExtensionData = new() {
                    { "MaxTokens", 4000 },
                    { "Temperature", 2 }
                }
            },
            new() {
                // Settings for gpt-4
                ModelId = "gpt-4-1106-preview",
                ExtensionData = new() {
                    { "MaxTokens", 8000 },
                    { "Temperature", 2 }
                }
            }
        ]
    }
);
```

**Comment by matthewbolanos** [comment]
Nevermind; user error...

**Comment by markwallace-microsoft** [comment]
Use `OpenAIPromptExecutionSettings` instead

**Comment by stephentoub** [comment]
> Use `OpenAIPromptExecutionSettings` instead

Why can't the base be used?

**Comment by stephentoub** [comment]
I get nervous any time we have an abstraction but then say you have to know exactly which implementation of that abstraction is in use in order to be successful. That's often an indication that something is broken. I might be misunderstanding, but this looks like a case where I should be able to just use the abstraction... why isn't it working?
