### ISSUE TITLE
.Net: When creating a KernelFunction, you should be able to get the execution settings in the method signature.

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4210]
This is not a v1.0.0 blocker because you can already get the execution settings from `KernelArguments`, but it's weird to get `KernelArguments` _just_ to get execution settings. Especially when the other properties are marshalled for you.

```csharp
public class TestPlugin
{
    [KernelFunction]
    public async Task<string> TestFunction(Kernel kernel, string input, PromptExecutionSettings executionSettings)
    {
        var chat = kernel.CreateFunctionFromPrompt(
            new PromptTemplateConfig()
            {
                Name = "Chat",
                Description = "Chat with the assistant.",
                Template = input,
                TemplateFormat = "semantic-kernel",
            }
        );

        return (await kernel.InvokeAsync<string>(chat))!;
    }
}
```

**Comment by stephentoub** [comment]
KernelArgument now contains a dictionary of prompt execution settings rather than a single instance. What is the intended behavior here?

**Comment by matthewbolanos** [comment]
The dictionary is used by the AI Selector service to pick the "right" settings. This change was made because at the time of invocation, it might not be clear which model/settings will be available or should be used.

**Comment by stephentoub** [comment]
> The dictionary is used by the AI Selector service to pick the "right" settings. This change was made because at the time of invocation, it might not be clear which model/settings will be available or should be used.

Right. But the AI selector today is not normally used for the invocation of one of these methods. Does this mean that if someone includes PromptExecutionSettings in their method's signature, the intent then is to invoke the AI selector and pass its result as the argument?

**Comment by stephentoub** [comment]
cc: @alliscode, who opened https://github.com/microsoft/semantic-kernel/issues/4456

**Comment by matthewbolanos** [comment]
Ah! I see what you're saying. This should theoretically be handled beforehand by the AI Service Selector. The AI Selector Service should be triggered during function invocation and return back the chosen model and a single PromptExecutionSettings object. This PromptExecutionSettings object should be the one that's passed into the function.

**Comment by stephentoub** [comment]
> The AI Selector Service should be triggered during function invocation and return back the chosen model and a single PromptExecutionSettings object.

The AI selector service requires you to specify the type of service you need. There is no such required service here.  What exactly would that call look like and where would it be?  I don't see how this works.

**Comment by matthewbolanos** [comment]
Closing as not necessary
