### ISSUE TITLE
Need documentation on usecase of semantic kernel on chat to pdf and sorted functions for this to do it in dotnet 

### ISSUE THREAD

**Issue by PrashantKashid2408** [microsoft/semantic-kernel#422]
**Describe the bug**
So the issue is I need to make a Q&A app for my specific data where user can give any kind of text in pdf format. I need to perform this in my old dotnet framework project. I saw same kind of functionality in sample code of github repo Q&A but the code is in React and there is no any documentation where I can train semantic kernel to speak on my provided pdf data. So please give me any related documentation to do it or detailed use of embedding of given data and memories in sementic kernel
**To Reproduce**

**Expected behavior**
I want to provide data to semantic kernel and it will responce related to my data only like If I upload a book in pdf and user will be like talking to author.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by craigomatic** [comment]
While the frontend is react, all the magic in that sample is happening in the backend via dotnet. Take a look at https://github.com/microsoft/semantic-kernel/blob/ccb9c26039f5562be22242354a5639116ff5ada5/samples/dotnet/github-skills/GitHubSkill.cs#L163

For PDF you would need to run a similar partitioning strategy over it to what we've implemented for markdown, and perhaps something more sophisticated if there are tables or images that you want to generate embeddings for also.

Another place that might be helpful to look is a small data ingestion library I have begun work on over here: https://github.com/craigomatic/sk-ingest (it does not yet have anything PDF specific, although that is high on my list of priorities to add)

**Comment by evchaki** [comment]
@PrashantKashid2408 - check out https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/copilot-chat-app you can upload a PDF and do Q&A over it
