### ISSUE TITLE
.Net: When turning a plugin into an OpenAI plugin, payload property is introduced

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4223]
When using a normal plugin with native functions, I can write code that looks like the following:

```csharp
double answer = await kernel.InvokeAsync<double>(
"MathPlugin", "Sqrt",
    new() {
        { "number1", 12 }
    }
);
Console.WriteLine($"The square root of 12 is {answer}.");
```

But when I turn that same plugin into a REST service, the arguments get wrapped in a payload property which makes it difficult to call. (I'm only assuming this is what it'll look like since I get an error saying that this isn't supported yet)

```csharp
double answer = await kernel.InvokeAsync<double>(
"MathPlugin", "Sqrt",
    new() {
        { "payload" , new Dictionary<string, object> {
            { "number1", 12 }
        }}
    }
);
Console.WriteLine($"The square root of 12 is {answer}.");
```

This could cause issues with planners and function calling because it makes calling REST services more complicated for the LLM.

The payload property should be removed and the child properties flattened out as individual parameters for KernelArguments to fill out.

If this cannot be finished by v1.0, we should make the OpenAPI package experimental.

**Comment by SergeyMenshykh** [comment]
It's possible to pass the arguments as a flat list as with other plugins, the functionality is there. It just needs to be activated through the [EnableDynamicPayload](https://github.com/SergeyMenshykh/semantic-kernel/blob/46f3dbc737e52085a399040d3858cdbb93cac3b3/dotnet/samples/KernelSyntaxExamples/Example22_OpenAIPlugin_AzureKeyVault.cs#L74C29-L74C29) property. More details in the [Dynamic payload... ADR](https://github.com/SergeyMenshykh/semantic-kernel/blob/46f3dbc737e52085a399040d3858cdbb93cac3b3/dotnet/samples/KernelSyntaxExamples/Example22_OpenAIPlugin_AzureKeyVault.cs#L74C29-L74C29)

We should make this the default behavior for consistency with other plugins and use the 'payload' property only for RestApi plugins with text/plain context, as OpenApi metadata does not advertise parameters for those.

**Comment by matthewbolanos** [comment]
This is great news! Yes, we should make this the default behavior.

**Comment by SergeyMenshykh** [comment]
The OpenAPI functionality has been updated to have the dynamic behavior enabled by default.

**Comment by lemillermicrosoft** [comment]
What work needs to be done to make it so the package is not marked as experimental? @matthewbolanos @SergeyMenshykh @markwallace-microsoft
