### ISSUE TITLE
Can PromptExecutionSettings become immutable

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#4224]

**Comment by markwallace-microsoft** [comment]
There is a limit as to what the extension data supports
```
System.InvalidOperationException : The extension data property 'System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Object].ExtensionData' is invalid. It must implement 'IDictionary<string, JsonElement>' or 'IDictionary<string, object>', or be 'JsonObject'.
```

**Comment by stephentoub** [comment]
> There is a limit as to what the extension data supports
> 
> ```
> System.InvalidOperationException : The extension data property 'System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Object].ExtensionData' is invalid. It must implement 'IDictionary<string, JsonElement>' or 'IDictionary<string, object>', or be 'JsonObject'.
> ```

What is this in reference to? I'm not sure how this relates to the settings being immutable. Did we dismiss that possibility and it means a KernelFunction's settings can end up being changed?
