### ISSUE TITLE
.Net: System.MissingMethodException: 'Method not found: Azure.AI.OpenAI.ChateMesssage Azure.AI.OpenAI.ChatChoice.Get_Message()'

### ISSUE THREAD

**Issue by Cobra86** [microsoft/semantic-kernel#4245]
**Describe the bug**
Encountering a System.MissingMethodException error when incorporating the Azure.AI.OpenAI package into my .NET 8 console application. The issue persists even after attempting different versions of the Azure.AI.OpenAI package.

**To Reproduce**

1. Run the provided .NET 8 console application.
2. Ensure the Azure OpenAI configuration is set up.
3. Observe the occurrence of the System.MissingMethodException error.

```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.AI.ChatCompletion;

var builder = new KernelBuilder()
    .AddAzureOpenAIChatCompletion("DeploymentName", "ModelID", "EndPoint", "APIKey")
    .Build();

var Messages = new ChatHistory("You are an AI agent");

Messages.AddAssistantMessage("Hi How can I Help?");
Messages.AddUserMessage("Hi");

ChatMessageContent response = await builder.Services
    .GetService<IChatCompletionService>()
    .GetChatMessageContentAsync(Messages);
```

**Expected behavior**
I need to use both packages in the same project.

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio 22 Enterprise 
 - Language: C#,
 - Source: Azure.AI.OpenAI 1.0.0-beta.11 and Microsoft.SemanticKernel 1.0.0-rc3

**Comment by feiyun0112** [comment]
![image](https://github.com/microsoft/semantic-kernel/assets/10190938/47ff7f46-f01b-486d-963b-9655e4babb3c)


please remove Azure.AI.OpenAI nuget Reference

**Comment by markwallace-microsoft** [comment]
Semantic Kernel RC4 depends on Azure.AI.OpenAI 1.0.0-beta.11 so please upgrade to that release.

**Comment by RogerBarreto** [comment]
Quite similar to the issue: https://github.com/microsoft/semantic-kernel/issues/4262

Update all your packages to use the latest RC4, and ensure if you use directly of the dependencies that RC4 uses like `Azure.AI.OpenAI` to be the same version.

![image](https://github.com/microsoft/semantic-kernel/assets/19890735/d8175925-de93-4d7d-939f-ee812476305d)

RC4, uses Azure beta 11
![image](https://github.com/microsoft/semantic-kernel/assets/19890735/8d64c17a-84ee-4da3-8673-93e0eea611ab)
