### ISSUE TITLE
.Net: OpenAIChatCompletionService has optional ILoggerFactory

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/semantic-kernel#4248]
**Describe the bug**

1. The `OpenAIChatCompletionService` takes an `ILoggerFactory` as an optional argument: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.OpenAI/ChatCompletion/OpenAIChatCompletionService.cs
2. The kernel builder extension `AddOpenAIChatCompletion` gets the `ILoggerFactory` from the `serviceProvider` using `GetService()`: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.OpenAI/OpenAIServiceCollectionExtensions.cs#L963
3. If an application doesn't register an `ILoggerFactory`, `GetService()` will return `null`, resulting in a `NullLogger`: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L35

The result of above is that nothing will get logged at the OpenAI connectors if the application doesn't set up a `ILoggerFactory`. And example of this is KernelSyntaxExample 59: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example59_OpenAIFunctionCalling.cs

Question is: is this something we want, or we need to explicitly let developers know how they need to configure their application to get logs from the connectors.

**To Reproduce**
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by stephentoub** [comment]
> And example of this is KernelSyntaxExample 59: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example59_OpenAIFunctionCalling.cs

That example does configure a logger. Are you saying it's not being picked up?

**Comment by TaoChenOSU** [comment]
Yes, it configures a logger, but the OpenAIClient needs a LoggerFactory.

**Comment by stephentoub** [comment]
OpenAIClient doesn't take one. The Azure SDK's tracing is via an EventSource, which is process global.

**Comment by TaoChenOSU** [comment]
> OpenAIClient doesn't take one. The Azure SDK's tracing is via an EventSource, which is process global.

Sorry, I meant our [OpenAIChatCompletionService](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.OpenAI/ChatCompletion/OpenAIChatCompletionService.cs)

**Comment by stephentoub** [comment]
I don't understand. It does take one:
https://github.com/microsoft/semantic-kernel/blob/db251dd6133d4d4f36e121fb9832402ee5a4bf1a/dotnet/src/Connectors/Connectors.OpenAI/ChatCompletion/OpenAIChatCompletionService.cs#L35
and if someone uses the add method, it pulls it from the DI container:
https://github.com/microsoft/semantic-kernel/blob/db251dd6133d4d4f36e121fb9832402ee5a4bf1a/dotnet/src/Connectors/Connectors.OpenAI/OpenAIServiceCollectionExtensions.cs#L275
which means in the example 59 your referenced, a logger is being provided:
https://github.com/microsoft/semantic-kernel/blob/db251dd6133d4d4f36e121fb9832402ee5a4bf1a/dotnet/samples/KernelSyntaxExamples/Example59_OpenAIFunctionCalling.cs#L24
What's missing? We should certainly fix problems here, I just don't understand what the pdoblem is. :-)

**Comment by TaoChenOSU** [comment]
> I don't understand. It does take one:
> 
> https://github.com/microsoft/semantic-kernel/blob/db251dd6133d4d4f36e121fb9832402ee5a4bf1a/dotnet/src/Connectors/Connectors.OpenAI/ChatCompletion/OpenAIChatCompletionService.cs#L35
> 
> 
> and if someone uses the add method, it pulls it from the DI container:
> https://github.com/microsoft/semantic-kernel/blob/db251dd6133d4d4f36e121fb9832402ee5a4bf1a/dotnet/src/Connectors/Connectors.OpenAI/OpenAIServiceCollectionExtensions.cs#L275
> 
> 
> which means in the example 59 your referenced, a logger is being provided:
> https://github.com/microsoft/semantic-kernel/blob/db251dd6133d4d4f36e121fb9832402ee5a4bf1a/dotnet/samples/KernelSyntaxExamples/Example59_OpenAIFunctionCalling.cs#L24
> 
> 
> What's missing? We should certainly fix problems here, I just don't understand what the pdoblem is. :-)

I misread the code. `AddLogging` adds a LoggerFactory to the service in addition to the logger. So all is fine!
