### ISSUE TITLE
.Net: [Handlebars Planner] V1.1 Enhancements 

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/semantic-kernel#4252]
Implement:
- Token selection bias, [Medium]
- Refactor CreatePlan to use streaming rather than completion (to avoid timeout) [Low]

Completed:
- ~Partial override support [Urgent] - Can use this issue for tracking: #4067~
- ~Retry logic (Consider using Prompt property in Plan object)~, 
- ~All [HandlebarsPlannerOptions](https://github.com/microsoft/semantic-kernel/blob/8f9eaeb7c45d9729d873406c30681e24978382cc/dotnet/src/Planners/Planners.Handlebars/Handlebars/HandlebarsPlannerOptions.cs#L13)~,
- ~Handle when the LLM returns "mixed" content (i.e., handlebar code blocks and non-code blocks)~
- ~Enforce stricter variable access patterns. i.e., model tries to use $variable rather than just variable. Also need to troubleshoot why some arguments aren't evaluating to their value in the template on render. (See the "concat" helper in KernelSystemHelpers for work around).~
    - ~Related #4293~

**Comment by markwallace-microsoft** [comment]
@teresaqhoang Can you elaborate on the "Retry logic" task?

For context, we have removed all custom retry logic from the SK core and instead allow SK to work well with standard resiliency patterns.

**Comment by strikene** [comment]
@teresaqhoang    Are the features mentioned in #4293  available in 1.5?

**Comment by teresaqhoang** [comment]
Yes, it was included in [Release 1.4](https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-1.4.0) with commit https://github.com/microsoft/semantic-kernel/commit/6652ce61c20ef8081a5dd3cc211a53e933d53e15 .Net: Configurable Handlebars Planner prompt (https://github.com/microsoft/semantic-kernel/pull/4918)

**Comment by matthewbolanos** [comment]
Closing since development on the Handlebars is on pause as we develop a Python planner
