### ISSUE TITLE
.Net: Missing Microsoft.SemanticKernel.Connectors.AI.OpenAI release for RC4

### ISSUE THREAD

**Issue by sanchez** [microsoft/semantic-kernel#4257]
I have tried to upgrade from RC3 to RC4 and noticed there is no RC4 release for Microsoft.SemanticKernel.Connectors.AI.OpenAI package. Additionally when I try to use the RC3 version with RC4 of Semantic Kernel, I get the following compile error:

![image](https://github.com/microsoft/semantic-kernel/assets/5264697/71512b05-6320-4244-980b-af39efbfacd9)

**Comment by kiatyao9595** [comment]
Same issue i am facing here, hope it can be resolve ASAP :(

**Comment by kiatyao9595** [comment]
Same issue that i am facing. Realize the is alot of conflict when using SemanticKernel  and KernelMemory.Core together

**Comment by kiatyao9595** [comment]
> I have tried to upgrade from RC3 to RC4 and noticed there is no RC4 release for Microsoft.SemanticKernel.Connectors.AI.OpenAI package. Additionally when I try to use the RC3 version with RC4 of Semantic Kernel, I get the following compile error:
> 
> ![image](https://private-user-images.githubusercontent.com/5264697/290389496-71512b05-6320-4244-980b-af39efbfacd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzIyODUsIm5iZiI6MTcwMjUzMTk4NSwicGF0aCI6Ii81MjY0Njk3LzI5MDM4OTQ5Ni03MTUxMmIwNS02MzIwLTQyNDQtOTgwYi1hZjM5ZWZiZmFjZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMDUzMzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmE0ODA3ZjcyYzU5YjkzM2RhNDBkOTNjOTlmZDliZDUwZGY1NDFlMTUxYzk4OGQ0MDc1MTI5ODhiYTFiYTE1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QotvgI50cgzOuuX66tHK72RZzyMu35GhYXu60Q41Cb8)

If you downgrade to RC3, it would work. But definitely not a long term solution

**Comment by strikene** [comment]
i have the same error  .
Reference to type 'PromptExecutionSettings' claims it is defined in 'Microsoft.SemanticKernel.Abstractions', but it could not be found roll back to RC3 or beta8

**Comment by rogeriorfp** [comment]
> I have tried to upgrade from RC3 to RC4 and noticed there is no RC4 release for Microsoft.SemanticKernel.Connectors.AI.OpenAI package. Additionally when I try to use the RC3 version with RC4 of Semantic Kernel, I get the following compile error:
> 
> ![image](https://private-user-images.githubusercontent.com/5264697/290389496-71512b05-6320-4244-980b-af39efbfacd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDEyNDUsIm5iZiI6MTcwMjU0MDk0NSwicGF0aCI6Ii81MjY0Njk3LzI5MDM4OTQ5Ni03MTUxMmIwNS02MzIwLTQyNDQtOTgwYi1hZjM5ZWZiZmFjZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMDgwMjI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTFkNGM0OWIxN2Q3ZjBjZGNjYWNjMDY4ZDgxOTBlMDJlOTkxMWNiYTQ3NGMwNDE4MzRiNWEwOTVkMzUwNDY5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.InXXZWX-f_ofXu4ODwaDB-gZaLpPE86rWiBfzmJ0SpM)

The RC4 version for Microsoft.SemanticKernel.Connectors.AI.OpenAI package is Microsoft.SemanticKernel.Connectors.OpenAI package. (Without AI on the namespace)

**Comment by markwallace-microsoft** [comment]
Old versions are now marked as deprecated in Nuget with pointers to the new versions
