### ISSUE TITLE
.Net RC.4 not sync upgrade to Microsoft.SemanticKernel.Connectors.Memory.Qdrant has some promblems

### ISSUE THREAD

**Issue by kinfey** [microsoft/semantic-kernel#4262]
**Describe the bug**

`
var textEmbedding = new AzureOpenAITextEmbeddingGenerationService("AOAI Deployment Model","AOAI Endpoint", "Your key");
 
 
var qdrantMemoryBuilder = new MemoryBuilder();
qdrantMemoryBuilder.WithTextEmbeddingGeneration(textEmbedding);
qdrantMemoryBuilder.WithQdrantMemoryStore("http://localhost:6333", 1536);

`

**To Reproduce**
when I build it ,it shows that 

Error: (17,1): error CS7069: Reference to type 'MemoryBuilder' claims it is defined in 'Microsoft.SemanticKernel.Plugins.Memory', but it could not be found

**Comment by qihangnet** [comment]
@kinfey, I understand the confusion; however, this is not a bug. The package you’re referencing was deprecated as of the RC4 version. Please use Microsoft.SemanticKernel.Connectors.Qdrant as its replacement. For further details and guidance, see the discussion in issue #4230 which outlines the transition process.
