### ISSUE TITLE
.Net: Make it easier to set service ID for prompts

### ISSUE THREAD

**Issue by strikene** [microsoft/semantic-kernel#4263]
**Describe the bug**
There is no serviceid in OpenAIPromptExecutionSettingsHow do I specify the model that the KernelFunction runtime selects? I have four models that are all GPT4, but I have different uses and token limitations. Do you force me to use a selector?

**Platform**
 - Language: C#

**Comment by markwallace-microsoft** [comment]
@strikene 

So previously you could do this

```csharp
        var result = await kernel.InvokePromptAsync(
           prompt,
           new(new PromptExecutionSettings()
           {
               ServiceId = serviceId
           }));
```

We changed the `KernelArguments` so now you can pass in multiple execution settings as Dictionary, so now the sam ething looks like this:

```csharp
        KernelArguments arguments = new();
        arguments.ExecutionSettings = new Dictionary<string, PromptExecutionSettings>()
        {
            { serviceId, new PromptExecutionSettings() }
        };
        var result = await kernel.InvokePromptAsync(prompt, arguments);
        Console.WriteLine(result.GetValue<string>());
```

We know this is very verbose, so we are going to add an extension method to streamline this.

**Comment by strikene** [comment]
> @strikene
> 
> So previously you could do this
> 
> ```cs
>         var result = await kernel.InvokePromptAsync(
>            prompt,
>            new(new PromptExecutionSettings()
>            {
>                ServiceId = serviceId
>            }));
> ```
> 
> We changed the so now you can pass in multiple execution settings as Dictionary, so now the sam ething looks like this:`KernelArguments`
> 
> ```cs
>         KernelArguments arguments = new();
>         arguments.ExecutionSettings = new Dictionary<string, PromptExecutionSettings>()
>         {
>             { serviceId, new PromptExecutionSettings() }
>         };
>         var result = await kernel.InvokePromptAsync(prompt, arguments);
>         Console.WriteLine(result.GetValue<string>());
> ```
> 
> We know this is very verbose, so we are going to add an extension method to streamline this.

HI
thank you for you help
 At the moment it looks like we can only specify the serviceid at invoke time, but we would rather specify the serviceid when creating a semantic function as before it look like this
 KernelFunction isk = this._Kernel._SK_Kernel.CreateFunctionFromPrompt(
     promptTemplate: this.Prompt_CategorizeUserIntent,
     executionSettings: new OpenAIPromptExecutionSettings()
     {
         Temperature = 0.1f,
        // ServiceId = OpenAIUseType.ChatCompletion.ToString()
     });

**Comment by markwallace-microsoft** [comment]
Closing stale issues
