### ISSUE TITLE
Python notebook 06-memory-and-embeddings - Add document to Azure Index failing

### ISSUE THREAD

**Issue by tvriesde** [microsoft/semantic-kernel#4268]
**Describe the bug**

Current notebook implementation fails at:

from semantic_kernel.connectors.memory.azure_cognitive_search import AzureCognitiveSearchMemoryStore

azure_ai_search_api_key, azure_ai_search_url = sk.azure_aisearch_settings_from_dot_env()

#text-embedding-ada-002 uses a 1536-dimensional embedding vector
kernel.register_memory_store(
    memory_store=AzureCognitiveSearchMemoryStore(
        vector_size=1536,
        search_endpoint=azure_ai_search_url,
        admin_key=azure_ai_search_api_key
    )
)

**To Reproduce**
1. Create a GitHub codespace
2. install dependencies pip install azure-core --pre --upgrade, pip install azure-search--pre --upgrade, pip install azure-search-documents --pre --upgrade
3. Configure .env parameters
4. Run notebook 6

**Expected behavior**
Index should be created in Seach index

**Screenshots**
ImportError: cannot import name 'HnswVectorSearchAlgorithmConfiguration' from 'azure.search.documents.indexes.models'

**Platform**
GitHub codespace
and
Local machine Windows 11

**Additional context**
Perhaps its a matter of installing the right dependencies but this is not documented clearly.

**Comment by moonbox3** [comment]
Hi @tvriesde, thank you for reporting the issue. In our Python [DEV_SETUP.md](https://github.com/microsoft/semantic-kernel/blob/main/python/DEV_SETUP.md#using-poetry), we suggest using Poetry to manage dependencies. In the [poetry.lock](https://github.com/microsoft/semantic-kernel/blob/fb9a43ea0af4417bbee9d64766b89ee6c5c14c98/python/poetry.lock#L313C14-L313C45) file, which list the dependencies that Poetry will install/use when running `poetry install`, we can see we're running a valid version (looks to be a version after what @surjray posted). 

When I run the `06-memory-and-embeddings` Jupyter notebook, I see this result:

![image](https://github.com/microsoft/semantic-kernel/assets/35585003/12062969-b392-48e1-93da-140d3219d81b)

![image](https://github.com/microsoft/semantic-kernel/assets/35585003/a32cfe74-06c7-47f8-962e-13ff4c9df949)

**Comment by moonbox3** [comment]
We haven't heard back in a while. Please feel free to re-open if you have any further problems.
