### ISSUE TITLE
Python: Notebook 05-using-the-planner throws xml string parsing error

### ISSUE THREAD

**Issue by moonbox3** [microsoft/semantic-kernel#4271]
**Describe the bug**
While trying to create the plan for a sequential planner, the `create_plan_async` throws: 

PlanningException: (<ErrorCodes.InvalidPlan: 1>, 'Failed to parse plan xml string: \'<xml><plan>\n    \n    <function.WriterSkill.Brainstorm input="Date ideas" setContextVariable="IDEAS"/>\n    \n    <function.WriterSkill.ShortPoem input="Valentine\'s day" setContextVariable="POEM"/>\n    \n    <function.WriterSkill.AcronymGenerator input="Valentine\'s day" setContextVariable="ACRONYM"/>\n    \n    <function.WriterSkill.Translate language="French" input="$POEM" setContextVariable="TRANSLATED_POEM"/>\n    \n    <function.TextSkill.uppercase input="$TRANSLATED_POEM" setContextVariable="UPPERCASE_POEM"/></xml>\'', None)

**To Reproduce**
1. Either get latest code or reference the SK Python 0.4.2.dev0 package.
2. Open the `05-using-the-planner` notebook.
3. If running latest code, comment out the pip install of the package. If running the package, make sure it's 0.4.2.dev0. Run the notebook.
4. In the sequential planner section, you will see the xml parsing error.

**Expected behavior**
No error. The xml string should parse correctly.

**Screenshots**

**Platform**
 - OS: Windows running WSL2 Ubuntu 22.04
 - IDE: VSCode
 - Language: Python
 - Source: latest code or PyPI package 0.4.2.dev0.

**Comment by moonbox3** [comment]
Looks like if I target an OpenAI model like "gpt-4" it kind of works. When I target "gpt-35-turbo" as is by default, it doesn't work. Even with gpt-4, I see this, which doesn't look right:

Given a goal or topic description generate a list of ideas : {'variables': {'input': ''}}
Generic function, unknown purpose : {'variables': {'input': ''}}
Translate the input into a language of your choice : {'variables': {'input': ''}}
Convert a string to uppercase. : {'variables': {'input': ''}}

**Comment by tbhamidipati** [comment]
@moonbox3 Using SK Python 0.4.3.dev0 package fixes this issue.

**Comment by moonbox3** [comment]
Thank you for confirming, @tbhamidipati. I will close the issue.
