### ISSUE TITLE
.Net: CreatePlanPrompt.handlebars Error with json schema

### ISSUE THREAD

**Issue by mickaelropars** [microsoft/semantic-kernel#4281]
**Describe the bug**
getSchemaReturnTypeName method need 2 arguments , has defined in HandlebarsPromptTemplateExtensions.cs

so you need to update the handlebars prompt 

replace 
{{~#if ReturnParameter.Schema}} {{getSchemaReturnTypeName ReturnParameter}}

by 
{{~#if ReturnParameter.Schema}} {{getSchemaReturnTypeName ReturnParameter ReturnParameter.Schema}}

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: rc4

**Comment by teresaqhoang** [comment]
Fixed in https://github.com/microsoft/semantic-kernel/pull/4343
