### ISSUE TITLE
.Net: System.NullReferenceException: 'Object reference not set to an instance of an object.' when try to get the IChatCompletionService

### ISSUE THREAD

**Issue by Cobra86** [microsoft/semantic-kernel#4289]
**Describe the bug**
After updating to RC4, I implemented the necessary changes in the code. However, I encountered two errors during execution.

1. System.NullReferenceException: 'Object reference not set to an instance of an object.'
```
ChatMessageContent response = await builder.Services
.GetService<IChatCompletionService>().GetChatMessageContentAsync(Messages);
```

2. System.UriFormatException: 'Invalid URI: The format of the URI could not be determined.'
```
ChatMessageContent response = await builder.GetRequiredService<IChatCompletionService>()
.GetChatMessageContentAsync(Messages);
```

**To Reproduce**
Run this code in .NET 8 console app 
```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.ChatCompletion;

var builder = Kernel.CreateBuilder()
    .AddAzureOpenAIChatCompletion("DeploymentName", "ModelID", "test.test.com", "APIKey")
    .Build();

var Messages = new ChatHistory("You are an AI agent");

Messages.AddAssistantMessage("Hi How can I Help?");
Messages.AddUserMessage("Hi");

ChatMessageContent response = await builder.Services
    .GetService<IChatCompletionService>()
    .GetChatMessageContentAsync(Messages);
```

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio 22
 - Language: C#
 - Source: NuGet Package Microsoft.SemanticKernel 1.0.0-rc4

**Comment by markwallace-microsoft** [comment]
@Cobra86 we made modeId optional so can you remove this?

I'd recommend using named arguments.
