### ISSUE TITLE
.Net: RC4 - Could not load type 'Microsoft.SemanticKernel.IKernelPlugin' from assembly 'Microsoft.SemanticKernel.Abstractions

### ISSUE THREAD

**Issue by sandeepvootoori** [microsoft/semantic-kernel#4292]
**Describe the bug**
Unable to execute yaml prompts using kernel.invoke/kernel.invokepromptasync in RC4 

**To Reproduce**
Both of the below code snippets are failing with "could not load type 'Microsoft.SemanticKernel.IKernelPlugin' from assembly 'Microsoft.SemanticKernel.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3'"

```
Kernel kernel = Kernel.CreateBuilder().AddAzureOpenAIChatCompletion(_openAISettings.TransformerModelName, openAIClient).Build();
using StreamReader reader = new(Assembly.GetExecutingAssembly().GetManifestResourceStream("PublixChatbot.YAMLPlugins.tst.yaml")!);
var results= await kernel.InvokePromptAsync(reader.ReadToEnd(), new(new OpenAIPromptExecutionSettings() { MaxTokens = 150 }),templateFormat:"handlebars",promptTemplateFactory: new HandlebarsPromptTemplateFactory());
```

```         
Kernel kernel = Kernel.CreateBuilder().AddAzureOpenAIChatCompletion(_openAISettings.TransformerModelName, openAIClient).Build();
using StreamReader reader = new(Assembly.GetExecutingAssembly().GetManifestResourceStream("PublixChatbot.YAMLPlugins.tst.yaml")!);
                KernelFunction prompt = kernel.CreateFunctionFromPromptYaml(
                                            reader.ReadToEnd(),
                                            promptTemplateFactory: new HandlebarsPromptTemplateFactory()
                                        );
var intent = await kernel.InvokeAsync(prompt, new(new OpenAIPromptExecutionSettings() { MaxTokens = 150 }));
```

**Expected behavior**
Should work with a valid result

**Platform**
 - OS: [Windows, ]
 - IDE: [Visual Studio]
 - Language: [C#,]
 - Source: [rc4]

**Comment by markwallace-microsoft** [comment]
@sandeepvootoori It sounds like you are using a mix of rc3 and rc3 packages. We renamed some packages between this versions and a few people have run into this problem. Can you check?

**Comment by sandeepvootoori** [comment]
> @sandeepvootoori It sounds like you are using a mix of rc3 and rc3 packages. We renamed some packages between this versions and a few people have run into this problem. Can you check?

This was it, thank you. Somehow one of the packages was stuck on RC3

**Comment by stephentoub** [comment]
Closing as resolved, thanks
