### ISSUE TITLE
Bad SQLite database name
Assignees: kbeaugrand
Labels: 

### ISSUE THREAD

**Issue by kbeaugrand** [microsoft/semantic-kernel#430]
SQLite database is not created with the expected name. 
Instead of the expected file name, we get a file name "{filename}" created in the current directory. 
This issue occurs because the argumement is not passed correctly to the format function.

**Comment by awharrison-28** [comment]
Hi @kbeaugrand. Thank you for posting. We are aware of the issue,- it is addressed in https://github.com/microsoft/semantic-kernel/pull/425.
