### ISSUE TITLE
.Net: Use automatic function invocation in the function calling stepwise planner

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#4300]
Currently the function calling stepwise planner is doing its own manual handling of tool responses. We should reimplement it in terms of automatic function calling, and if there are features missing in the automatic function calling support, add whatever features are necessary to make it work. Having two different implementations is far from ideal, and the stepwise planner's handling currently isn't as robust (as of https://github.com/microsoft/semantic-kernel/pull/4258).

**Comment by stephentoub** [comment]
cc: @gitri-ms

**Comment by matthewbolanos** [comment]
Closing as completed
