### ISSUE TITLE
.Net RC4: StreamingKernelContent.InnerContent doesn't contain anymore the actual text, but an object

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/semantic-kernel#4303]
**Describe the bug**
Before RC4, I was able to use the new streaming capabilities of the kernel like this:

```
var results = kernel.InvokePromptStreamingAsync("Which is the latest version of Semantic Kernel from Microsoft?", new KernelArguments(settings));
await foreach (var result in results)
{
    Console.Write((result.InnerContent)
}   
```

Now, instead, `InnerContent` appears to not be anymore a string with the partial text that was generated, but an object, which type is different based on the model you're using. In my case, since I'm using Azure OpenAI, I had to change my code like this:

```
var results = kernel.InvokePromptStreamingAsync("Which is the latest version of Semantic Kernel from Microsoft?", new KernelArguments(settings));
await foreach (var result in results)
{
    Console.Write((result.InnerContent as Azure.AI.OpenAI.StreamingChatCompletionsUpdate).ContentUpdate);
} 
```

Is this expected? This approach introduces in the code a dependability on the AI service you use.

**To Reproduce**
You can find the full sample here: https://github.com/qmatteoq/SemanticKernel-Demos/blob/rc/SemanticKernel.BuiltinPlugins/Program.cs

**Expected behavior**
I can use the InvokePromptStreamingAsync() method without changing the code based on the AI service I'm using.

**Platform**
 - OS: Windows
 - IDE: Visual Studio 2022 17.8.3
 - Language: C#
 - Source: NuGet package version 1.0 RC4

**Comment by RogerBarreto** [comment]
@qmatteoq Using streaming in the abstraction level you can just use directly:

Using `InnerContent` is considered breaking glass approach where you intend to intentionally access the underlying representation and therefore casting is necessary.

To resolve your scenario you can work with the abstractions like below:

1. Not using the innercontent at all
```
var results = kernel.InvokePromptStreamingAsync("Which is the latest version of Semantic Kernel from Microsoft?", new KernelArguments(settings));
await foreach (var result in results)
{
    Console.Write(result);
}   
```

2. If you are using a ChatModel you can also use the generic approach casting it to a ChatMessage
```
var results = kernel.InvokePromptStreamingAsync<StreamingChatMessageContent>("Which is the latest version of Semantic Kernel from Microsoft?", new KernelArguments(settings));
await foreach (var result in results)
{
    Console.Write(result.Content!);
}
```

**Comment by stephentoub** [comment]
> Console.Write(result)

And, for completeness, this is implicitly using ToString(), which you can also use explicitly.
