### ISSUE TITLE
.Net Agent - Expose internal dialog and max-depth for plug-in model

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#4313]
When agents are interacting as plugins for another agent, the internal dialog isn't exposed.  While this is fine for the initial experimental phase, it warrants further refinement.

Also consider a "max-depth" concept for how long this type of conversation is allowed to run.

**Comment by joslat** [comment]
This is much needed - thanks @crickman for bringing this forward!
Aside from maxdepth, how about the number of "interactions" too? that would be very convenient to identify and avoid never ending feedback loops...

**Comment by crickman** [comment]
I hear you!

**Comment by crickman** [comment]
Currently addressing in active Agent ADR: https://github.com/microsoft/semantic-kernel/blob/adr_agent_architecture/docs/decisions/0039-agent-interactions.md

**Comment by crickman** [comment]
https://github.com/microsoft/semantic-kernel/pull/5725
