### ISSUE TITLE
.Net: Add connector for AWS Bedrock

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#4335]
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Bedrock/TBedrockClient.html

**Comment by stekiri** [comment]
After reading https://github.com/microsoft/semantic-kernel/issues/3094, I was wondering if there is still hope for the Bedrock connector to make it into the main repo? That would be soooo sweet 🙏

**Comment by fbouteruche** [comment]
Hi @stephentoub do you need help with this one? I'd love to give it a hand.

**Comment by stephentoub** [comment]
@markwallace-microsoft?

**Comment by as14692** [comment]
@stephentoub @markwallace-microsoft  We are planning to work on this. Could you please update the status regarding this issue.

**Comment by stephentoub** [comment]
> [@stephentoub](https://github.com/stephentoub) [@markwallace-microsoft](https://github.com/markwallace-microsoft) We are planning to work on this. Could you please update the status regarding this issue.

Awesome. @markwallace-microsoft ?

**Comment by Beau-Gosse-dev** [comment]
@stephentoub Should we plan to fork this repo and open a PR adding the Bedrock connectors here? https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors

**Comment by markwallace-microsoft** [comment]
@Beau-Gosse-dev we'd be delighted to have this contribution. I'm adding @RogerBarreto as he has been working with contributors on some of the new connectors.

We will create a feature branch for this work to allow multiple smaller PR's which will be easier to review and merge.
Some information about this process: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0031-feature-branch-strategy.md

**Comment by RogerBarreto** [comment]
@Beau-Gosse-dev, please follow the instructions provided by @markwallace-microsoft above.

Feature branch for Amazon Bedrock was created, on the next PR's please target this `branch` [https://github.com/microsoft/semantic-kernel/tree/feature-connectors-amazon](https://github.com/microsoft/semantic-kernel/tree/feature-connectors-amazon)

Thanks for the contribution!

**Comment by Beau-Gosse-dev** [comment]
Thanks so much @markwallace-microsoft and @RogerBarreto ! 

One question right away, will we be able to take a dependency on the AWS SDK for Bedrock? [source code](https://github.com/aws/aws-sdk-net/tree/main/sdk/src/Services/BedrockRuntime), [nuget](https://www.nuget.org/packages/AWSSDK.BedrockRuntime/)

**Comment by markwallace-microsoft** [comment]
> Thanks so much @markwallace-microsoft and @RogerBarreto !
> 
> One question right away, will we be able to take a dependency on the AWS SDK for Bedrock? [source code](https://github.com/aws/aws-sdk-net/tree/main/sdk/src/Services/BedrockRuntime), [nuget](https://www.nuget.org/packages/AWSSDK.BedrockRuntime/)

That should be fine

**Comment by halllo** [comment]
I am also very interested in this. Will it suffice to add a class in the connectors namespace and implement IChatCompletion?

**Comment by Beau-Gosse-dev** [comment]
@halllo , we're currently doing an internal review of these changes before submitting them to this main repo. We'd appreciate your feedback if you have any: https://github.com/as14692/semantic-kernel/pull/1

**Comment by as14692** [comment]
@markwallace-microsoft @RogerBarreto @stephentoub Submitted first [PR](https://github.com/microsoft/semantic-kernel/pull/7587) for ChatCompletionService and TextGenerationService. Please review.
