### ISSUE TITLE
.Net packages targets question

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/semantic-kernel#4347]
Opened as issue for visibility

### Discussed in https://github.com/microsoft/semantic-kernel/discussions/3971

<div type='discussions-op-text'>

<sup>Originally posted by **WeihanLi** December  5, 2023</sup>
Since .NET Standard is replaced with new .NET 
https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/

So do we still need to target for `netstandard2.0`, we have to reference some may not needed packages in the runtime such as `Microsoft.Bcl.AsyncInterfaces`/`System.Memory` etc which would cause package version conflict more easily, while for `net8.0`(take this for an example) these packages are not necessary to be a dependency since the framework includes these packages.

From the packages like `System.Text.Json`/`Microsoft.Extensions.DependencyInjection`, they add `net6.0`/`net8.0` targets more than `netstandard2.0`, I also noticed that the new package `Microsoft.Extensions.Http.Resilience` had removed `netstandard2.0` target, is this the correct way?

![image](https://github.com/microsoft/semantic-kernel/assets/7604648/c926da10-6061-4d88-830d-ae7f69642661)

I'm not sure which is the correct way to go from my limited knowledge, so here's the question, should we re-consider the target framework for the packages?
</div>

**Comment by stephentoub** [comment]
Folks still need to be able to use SK with .NET Framework, which means it needs a target of either netstandard2.0 or something specific to .NET Framework, like net462, and there's not much reason to replace the former with the latter. It can also target net8.0, but that would be in addition to, not instead of, netstandard2.0.
