### ISSUE TITLE
.Net: Importing Prompts gives exception

### ISSUE THREAD

**Issue by dmm-l-mediehus** [microsoft/semantic-kernel#4348]
**Describe the bug**
Exception thrown when trying to Add prompts to the kernel by doing:
```
kernelBuilder.Plugins.AddFromPromptDirectory("Prompts");
```
Exception:
`Unhandled exception. Microsoft.SemanticKernel.KernelException: A function named argument must contain a name and value separated by a '=' character.`

**To Reproduce**
1. Create prompts following the [Microsoft docs](https://learn.microsoft.com/en-us/semantic-kernel/prompts/saving-prompts-as-files?tabs=Csharp#creating-the-files-for-your-prompt)
2. Add this line: at the kernelbuilder: `kernelBuilder.Plugins.AddFromPromptDirectory("Prompts");`
3. Run the app

**Expected behavior**
Expected to import prompts (config.json & skprompt.txt)

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/125255354/ddf4b71c-5417-457b-bc45-7732dd054de8)
![image](https://github.com/microsoft/semantic-kernel/assets/125255354/dfe548f9-54fd-4501-b0e3-cedd3b0f48a5)

**Platform**
 - OS: Windows 11
 - IDE: VS
 - Language: C#
 - Source: 
```
<PackageReference Include="Microsoft.SemanticKernel" Version="1.0.0-rc4" />
```

**Additional context**
I tried many different ways of importing the prompt, i.e.:
- `kernelBuilder.Plugins.AddFromPromptDirectory("Prompts");`
- `kernelBuilder.Plugins.AddFromPromptDirectory(Path.Combine(Directory.GetCurrentDirectory(), "Prompts"));`
- `kernelBuilder.Plugins.AddFromPromptDirectory("./Prompts");`
- `kernelBuilder.Plugins.AddFromPromptDirectory(".");`
- `kernelBuilder.Plugins.AddFromPromptDirectory("Prompts", "PromptsPlugin");`
- `kernelBuilder.Plugins.AddFromPromptDirectory(Directory.GetCurrentDirectory());`
- etc. - and even tried after .Build() on the Kernel directly; `kernel.ImportPluginFromPromptDirectory("Prompts");`, etc.

The structure of each `config.json`:
```
{
	"schema": 1,
	"type": "completion",
	"description": "Korrekturlæser det angivne input tekst, retter stavefejl og grammatik.",
	"execution_settings": {
		"default": {
			"max_tokens": 10000,
			"temperature": 0.0,
			"top_p": 0.0
		}
	},
	"input_variables": [
		{
			"name": "input",
			"description": "Teksten, som skal korrekturlæses.",
			"required": true
		}
	]
}
```

The structure of each `skprompt.txt`:
```
You are an expert in proofreading, and you must correct spelling and grammar errors from the input text. 
You must retain the structure and formatting. 

The text to be proofread is:
+++++
{{$input}}
+++++

Important: Always respond in danish.
```

**Comment by dmm-l-mediehus** [comment]
Solved by fixing a variable inside the skprompt from: `{{MemoryPlugin.search Folketal}}` to `{{MemoryPlugin.search $input}}`. The exception didn't hint it for me.

**Comment by supreettare** [comment]
{{MemoryPlugin.search $input}} How to pass a second parameter? For ex. Tags or Filters?
