### ISSUE TITLE
Python: StepwisePlanner v2 Python Support

### ISSUE THREAD

**Issue by maxupp** [microsoft/semantic-kernel#4353]
Is Python support for the handlebars planners coming in the near future? Highly interested in the new StepwisePlanner version.

**Comment by matthewbolanos** [comment]
Yes! This is planned with the v1.0 version of the Python SDK.

**Comment by matthewbolanos** [comment]
We're _hoping_ to get it done by end of February, but this might be aggressive considering all of the v1 changes that are required. As we get more confident on timelines, we'll be sharing them with the community.

**Comment by moonbox3** [comment]
Closing this issue as we're already tracking the work via other work items in our backlog.

The Python SDK is now in beta and we're aiming to land the v1.0.0 SDK by middle of May.
