### ISSUE TITLE
.Net: Use memory connectors without embedding generation service

### ISSUE THREAD

**Issue by luisquintanilla** [microsoft/semantic-kernel#4367]
I have a scenario where my embeddings are precomputed, so I don't want / need to use `WithAzureTextEmbeddingGenerationService`. It'd be great to be able to have overloads or other mechanisms for being able to use the connectors without also requiring the use of the embedding generation service.

https://github.com/Azure-Samples/qdrant-azure/blob/f16c3b7e7125afb6cb410f2419d399809c66f5fd/samples/dotnet/csharp/get-started.ipynb

**Comment by stephentoub** [comment]
> I have a scenario where my embeddings are precomputed

Both the embeddings in the database / vector store and the embedding vector with which you're searching? Can you elaborate on the scenario? When a search needs to be performed, you're getting an embedding vector via a different means? Thanks.

**Comment by luisquintanilla** [comment]
Using the notebook in the issue description, where I'm just using the Qdrant SDK directly. 

## Add data

```csharp
var data = new[] 
{
    new PointStruct
    {
        Id = 1,
        Vectors = new [] {0.10022575f, -0.23998135f},
        Payload = 
        {
            ["title"] = "The Lion King"
        }
    },
//...
}

await client.UpsertAsync("movie_collection",data);
```

## Query data

> Search for data using embedding vectors for the query "A movie that's fun for the whole family".

```csharp
await client.SearchAsync("movie_collection",new [] {0.12217915f, -0.034832448f }, limit:3)
```

In both of these cases, where vectors are expected, I'm just passing in the precomputed vectors as `float[]`.

With SK, I like the magic it does for me behind the scenes with computing these embeddings but as far as I know, you *have* to use the embedding generation service. It's not optional. 

If there is a way to do that already though, I'd appreciate a link to a sample and we can close this issue.

**Comment by stephentoub** [comment]
Thanks. In that case it sounds like you want to use an IMemoryStore rather than ISemanticTextMemory? The former is the abstraction for the vector db, whereas the latter marries that with an embedding service. So eg you want to use IMemoryStore.GetNearestMatchesAsync, I think?
