### ISSUE TITLE
.Net: Error CS7069 Reference to type 'IKernelBuilder' claims it is defined in 'Microsoft.SemanticKernel.Core', but it could not be found

### ISSUE THREAD

**Issue by MikeYeager** [microsoft/semantic-kernel#4369]
**Describe the bug**
When adding Kernel memory to a Semantic Kernel project, get the following compiler error: Error CS7069 Reference to type 'IKernelBuilder' claims it is defined in 'Microsoft.SemanticKernel.Core', but it could not be found

**To Reproduce**
1. Create a new Console application (.NET 8)
2. Add Microsoft.SemanticKernel 1.0.1 and Microsoft.KernelMemory.Core 0.22.231217.1 NuGet packages
3. Add the following lines of code to Program.cs
            var kernelBuilder = Kernel.CreateBuilder();

            kernelBuilder.Services
                    .AddAzureOpenAIChatCompletion(
                    "",
                    "",
                    "");

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/7063813/8dd089c0-61a5-4df4-9cbf-648ed2503c3f)

**Platform**
 - OS: Windows 11 Pro
 - IDE: Visual Studio 2022 Community
 - Language: C#
 - Source: Microsoft.SemanticKernel 1.0.1 and Microsoft.KernelMemory.Core 0.22.231217.1

**Comment by dmytrostruk** [comment]
@MikeYeager Yes, `IKernelBuilder` is now located in `SemanticKernel.Abstractions` package. Did you try to use latest version of Kernel Memory package - `0.23.231218.1`?
https://www.nuget.org/packages/Microsoft.KernelMemory.Core/

It has latest updates from SK packages, and it should resolve the issue.

**Comment by rogeriorfp** [comment]
> @MikeYeager Yes, `IKernelBuilder` is now located in `SemanticKernel.Abstractions` package. Did you try to use latest version of Kernel Memory package - `0.23.231218.1`? https://www.nuget.org/packages/Microsoft.KernelMemory.Core/
> 
> It has latest updates from SK packages, and it should resolve the issue.

That's right, i had the same problem and  KM version `0.23.231218.1` solved the issue

**Comment by dmytrostruk** [comment]
@rogeriorfp Thank you for confirmation!

**Comment by MikeYeager** [comment]
Back from vacation. I just tried the latest 0.23.231224.1 and I can confirm it solves the issue.

**Comment by budgier** [comment]
doesnt work

**Comment by dmytrostruk** [comment]
Hi @budgier ! Could you please describe the error in more detail? Thanks in advance!

**Comment by budgier** [comment]
> Hi @budgier ! Could you please describe the error in more detail? Thanks in advance!

OS: Windows 10
IDE: Visual Studio 2022 Community
Language: C# 12.0
Source: Microsoft.SemanticKernel 1.0.1 and Microsoft.KernelMemory.Core 0.26.240104.1

Error:
CS7069	Reference to type 'KernelBuilder' claims it is defined in 'Microsoft.SemanticKernel.Core', but it could not be found

**Comment by dmytrostruk** [comment]
> error appears when trying to construct **FlowOrchestrator** Orchestrator = new (kernelbuilder

Could you please also share the package version of `FlowOrchestrator` you are using as well as the code snippet that doesn't work? That would be very helpful, thank you!

**Comment by budgier** [comment]
> > error appears when trying to construct **FlowOrchestrator** Orchestrator = new (kernelbuilder
> 
> Could you please also share the package version of `FlowOrchestrator` you are using as well as the code snippet that doesn't work? That would be very helpful, thank you!

..\.nuget\packages\microsoft.semantickernel.experimental.orchestration.flow\1.0.0-beta8\

`IKernelBuilder kernelbuilder = Kernel.CreateBuilder()
		.AddOpenAIChatCompletion("gpt-4-1106-preview", "xxxxxxxxxxxx");
  Kernel kernel =  kernelbuilder.Build();
FlowOrchestrator Orchestrator = new (kernelbuilder ,
	await FlowStatusProvider.ConnectAsync(new VolatileMemoryStore()).ConfigureAwait(false)
);
`

**Comment by rogeriorfp** [comment]
> > > error appears when trying to construct **FlowOrchestrator** Orchestrator = new (kernelbuilder
> > 
> > 
> > Could you please also share the package version of `FlowOrchestrator` you are using as well as the code snippet that doesn't work? That would be very helpful, thank you!
> 
> ...nuget\packages\microsoft.semantickernel.experimental.orchestration.flow\1.0.0-beta8\
> 
> `IKernelBuilder kernelbuilder = Kernel.CreateBuilder() .AddOpenAIChatCompletion("gpt-4-1106-preview", "xxxxxxxxxxxx"); Kernel kernel = kernelbuilder.Build(); FlowOrchestrator Orchestrator = new (kernelbuilder , await FlowStatusProvider.ConnectAsync(new VolatileMemoryStore()).ConfigureAwait(false) ); `

Update both Microsoft.SemanticKernel.Experimental.Orchestration.Flow and Microsoft.SemanticKernel to version 1.1.0

[OrchestrationFlow](https://www.nuget.org/packages/Microsoft.SemanticKernel.Experimental.Orchestration.Flow)
[SemanticKernel](https://www.nuget.org/packages/Microsoft.SemanticKernel)

**Comment by budgier** [comment]
now its OK
