### ISSUE TITLE
GetAllAsync() in CosmosDB connector does not return all records

### ISSUE THREAD

**Issue by JohnMasen** [microsoft/semantic-kernel#437]
**Describe the bug**
GetAllAsync() in CosmosDB connector does not return all records.
This issue also impacts GetNearestMatchAsync() as it does not count all the records in the comparation.

**To Reproduce**
1. Create Instance of CosmosDBStorage
2. Execute GetAllAsync() on the instance

**Expected behavior**
returns all memory instance stored in cosmosDB

**Additional context**
The root cause is code not reading all result from cosmosDB

Current code:
``` C#
        var items = await iterator.ReadNextAsync(cancel).ConfigureAwait(false); //only reads first batch of results

        foreach (var item in items)
        {
            var vector = System.Text.Json.JsonSerializer.Deserialize<float[]>(item.EmbeddingString);

            if (vector != null)
            {
                yield return MemoryRecord.FromJson(
                    item.MetadataString,
                    new Embedding<float>(vector),
                    item.Id,
                    item.Timestamp);
            }
        }
```

correct code:
``` C#
        while (iterator.HasMoreResults) //read all result in batch 
        {
            var items = await iterator.ReadNextAsync(cancel).ConfigureAwait(false);

            foreach (var item in items)
            {
                var vector = System.Text.Json.JsonSerializer.Deserialize<float[]>(item.EmbeddingString);

                if (vector != null)
                {
                    yield return MemoryRecord.FromJson(
                        item.MetadataString,
                        new Embedding<float>(vector),
                        item.Id,
                        item.Timestamp);
                }
            }
        }

```

**Comment by JohnMasen** [comment]
Actually, a stored procedure should be more efficient, I'm working on an improved version of CosmosDB which uses UDF and StoredProcedure.

**Comment by awharrison-28** [comment]
Thank you so much! Looking forward to the improvements.

**Comment by awharrison-28** [comment]
PR for your suggested fix for now https://github.com/microsoft/semantic-kernel/pull/452

**Comment by JohnMasen** [comment]
Thanks for your fix.
I've finished changing CosmosDB to use server side UDF, this could greatly reduces network IO. As CosmosDb connector does not have unit tests. Now I'm refactorying the unit tests to create a basic test class for IMemoryStore, this can make futher connector easier to implement unit test.
