### ISSUE TITLE
.Net: Arguments of System.Windows.Media.Color type in Native function

### ISSUE THREAD

**Issue by hyam1567** [microsoft/semantic-kernel#4375]
Native function no longer accepts arguments of type System.Windows.Media.Color.
In beta, it was working correctly.

[ KernelFunction ]
[ Description( "Set background color" ) ]
public string SetBackgroundColor(
	[ Description( "Color" ) ] System.Windows.Media.Color color )
{
}

Goal:
Make the background black.

Exception:
System.FormatException
  HResult=0x80131537
  Message=Token is not valid.
  Source=PresentationCore
  StackTrace:
   at MS.Internal.Parsers.ParseColor(String color, IFormatProvider formatProvider, ITypeDescriptorContext context)

Log:
SetBackgroundColor
Function arguments:
{"color":"{
    "ColorContext": {
      "ProfileUri": null
    },
    "A": 255,
    "R": 0,
    "G": 0,
    "B": 0,
    "ScA": 1,
    "ScR": 0,
    "ScG": 0,
    "ScB": 0
  }"}

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio 2022
 - Language: C#
 - Source: Semantic Kernel 1.0.1

**Comment by RogerBarreto** [comment]
You need to provide in the arguments the name matching the argument in your function:

```csharp
new KernelArguments() { ["color"] = yourColor };
```

One example that worked for me:

```csharp
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
    }

    private async void Button_Click(object sender, RoutedEventArgs e)
    {
        var builder = Kernel.CreateBuilder();
        builder.Plugins.AddFromType<MyPlugin>();
        var kernel = builder.Build();

        var colorString = await kernel.InvokeAsync<string>("MyPlugin", "NativeMethod", new KernelArguments() { ["color"] = Color.FromRgb(0, 0, 0) });

        TextBlock textBlock = new TextBlock
        {
            Text = colorString
        };

        Grid mainGrid = new Grid();
        mainGrid.Children.Add(textBlock);

        this.Content = mainGrid;
    }
}

public class MyPlugin
{
    [KernelFunction]
    [Description("Set background color")]
    public string NativeMethod([Description("Color")] Color color)
    {
        return JsonSerializer.Serialize(color);
    }
}
```

**Comment by stephentoub** [comment]
Who created the arguments in this example? Was it the LLM as part of a plan or function calling? There was a preview or two where JSON deserialization was used to support the LLM calling functions with complex types. That support was temporarily removed due to regressions, but it should be coming back soon.
cc:@dehoward, @SergeyMenshykh
