### ISSUE TITLE
.Net: Make default role for chat completion connectors configurable

### ISSUE THREAD

**Issue by MaxAkbar** [microsoft/semantic-kernel#4377]
**Describe the bug**
When starting a chat using a CreateFunctionFromPrompt and then passing it as a parameter to the kernel, the default message is system. 

**To Reproduce**
To reproduce this, please run the code below. This code works for GPT-4, but not if we use it to point to other APIs based on OpenAI API standards like Mistral.

To make the code work, explicitly mark the prompt in XML. Uncomment the prompt in the example below.

```
public static class Example05_InlineFunctionDefinition
{
    public static async Task RunAsync()
    {
        var openAIModelId = "mistral-tiny"; 
        var openAIApiKey = "API_KEY"; 
        var kernelBuilder = Kernel.CreateBuilder();
        kernelBuilder.Services.ConfigureHttpClientDefaults(b =>
            b.ConfigurePrimaryHttpMessageHandler(() => new MyRedirectingHandler()))
            .AddOpenAIChatCompletion(
                modelId: openAIModelId,
                apiKey: openAIApiKey);
        var kernel = kernelBuilder.Build();
        var promptTemplate = "tell me a joke";
        // To make this work use an XML prompt
        //var promptTemplate = @"<message role=""user"">Tell me a joke</message>";
        var excuseFunction = kernel.CreateFunctionFromPrompt(promptTemplate, new OpenAIPromptExecutionSettings() { MaxTokens = 100, Temperature = 0.4, TopP = 1 });
        var result = await kernel.InvokeAsync(excuseFunction);
        Console.WriteLine(result.GetValue<string>());
    }
    private sealed class MyRedirectingHandler : DelegatingHandler
    {
        public MyRedirectingHandler() : base(new HttpClientHandler()) { }
        protected override async Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request, CancellationToken cancellationToken)
        {
            request.RequestUri = new UriBuilder(request.RequestUri!) { Host = "api.mistral.ai" }.Uri;

            var message = await base.SendAsync(request, cancellationToken);

            if (!message.IsSuccessStatusCode)
            {
                var content = await message.Content.ReadAsStringAsync(cancellationToken);

                Console.WriteLine($"Error: {message.StatusCode} - {content}");
            }
            return message;
        }
    }
}
```

**Expected behavior**
If I run the code above, I expect the code to execute, and I get the result back from the LLM.

**Actual Reskult**
```
Running Example05_InlineFunctionDefinition...
Error: BadRequest - {"object":"error","message":"Expected last role to be user but got RoleEnum.system","type":"internal_error_proxy","param":null,"code":"1000"}
```

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio 2022 Community Edition
 - Language: C#
 - Source: main branch of repository as of today

**Comment by matthewbolanos** [comment]
Oh interesting! You're using the OpenAI connector to connect with Mistral by changing the host. Since we can't change the default message role without introducing a breaking change, we may need to apply a fix by introducing a Mistral specific connector.

Thank you for reporting.

**Comment by MaxAkbar** [comment]
@matthewbolanos, does it just need a connector? If so, I can help.

**Comment by matthewbolanos** [comment]
@markwallace-microsoft / @RogerBarreto, does @MaxAkbar's proposal make sense? If so, y'all open to him submitting a PR for it?

**Comment by brandonh-msft** [comment]
I would add that this is doubly confusing and "smells like a bug" when one sets `OpenAIPromptExecutionSettings.ChatSystemPrompt` then uses a chat completion endpoint straight-up via `k.InvokePromptStreamingAsync(message, new(settings)))` where `message` is the exact prompt text (not a template).

I'm seeing that my defined `ChatSystemPrompt` gets thrown away completely and then `message` gets sent through with `role: system`

**Comment by dmytrostruk** [comment]
@brandonh-msft Thanks for reporting, I added fix in this PR: https://github.com/microsoft/semantic-kernel/pull/4994
