### ISSUE TITLE
Java: Add a Spring Boot Starter

### ISSUE THREAD

**Issue by SandraAhlgrimm** [microsoft/semantic-kernel#4380]
To ease the use of Semantic Kernel in Spring projects, let's add a Spring Boot starter.
```[tasklist]
### Tasks
- [x] Java: Add new module for Spring Boot starter
- [x] Java: Add at least one integration test
```

**Comment by SandraAhlgrimm** [comment]
@shawncal please assign it to me, as I already discussed it with @johnoliver and @jdubois

**Comment by geoffreylgv** [comment]
Hi @markwallace-microsoft @johnoliver @matthewbolanos @shawncal @stephentoub 
Any updates on this PR ?

**Comment by SandraAhlgrimm** [comment]
Hi @d3r3kk, I am working on it with @johnoliver guidance

**Comment by SandraAhlgrimm** [comment]
https://github.com/microsoft/semantic-kernel/pull/4401

**Comment by d3r3kk** [comment]
@dsgrieve please have a conversation with @SandraAhlgrimm about upgrading this PR to V1 so we can accept the contribution. Thanks!
