### ISSUE TITLE
Python: JSON mode support for GPT4T 1106 / GPT35T 1106

### ISSUE THREAD

**Issue by slm-2015** [microsoft/semantic-kernel#4382]
Hi, is JSON mode for GPT4 Turbo 1106 / GPT35 Turbo 1106 supported by SK? If so, apologies, can someone give me a pointer on how to add it to the config.json file? I couldn't find anything in the SK docs to help me.
Thanks, Simon.

**Comment by Krzysztof318** [comment]
This parameter is not bundled yet in source.

**Comment by slm-2015** [comment]
ok, thanks for the quick update. Cheers.

**Comment by slm-2015** [comment]
Just checking in on this one - is it now possible set JSON mode in the C# library? thanks v much.

**Comment by alliscode** [comment]
@moonbox3 is this still needed?

**Comment by moonbox3** [comment]
@alliscode this looks to be dotnet specific? In Python one can set the [response_format](https://github.com/microsoft/semantic-kernel/blob/1345b565fbc4ffd8372c21bc4b26a8c26494b04b/python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/open_ai_prompt_execution_settings.py#L58) as `json_object`.
