### ISSUE TITLE
.Net: exception on using AssistantBuilder to create IAssistant

### ISSUE THREAD

**Issue by deepinderdeol** [microsoft/semantic-kernel#4389]
I have the latest packages.

**With this code:**
var assistant = await new AssistantBuilder()
                .WithOpenAIChatCompletion(openAIModel, openAI_Key)
                .FromTemplate(assistant_definition)
                .BuildAsync();

**I am seeing the following exception:** 
_Could not load file or assembly 'Microsoft.SemanticKernel.Connectors.OpenAI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3'. The system cannot find the file specified._

I get the exception only if creating an Assistant is the first thing I do in my solution.

If I first run some other non-Assistants workflow, like chat/function-calling etc. and then choose to use Assistants then no exception is thrown. Maybe at this time the assembly is already loaded so creating an assistant works??

Possibly some assembly mismatch between the Experimental.Assistants and other v1 packages?

**Comment by markwallace-microsoft** [comment]
@deepinderdeol Can you switch to using this package https://www.nuget.org/packages/Microsoft.SemanticKernel.Experimental.Agents/1.0.1-alpha

We re-renamed the assistants package to agents.

See: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Experimental/Agents/AgentBuilder.cs

**Comment by markwallace-microsoft** [comment]
@alliscode Can we remove the old assistants code now?

**Comment by deepinderdeol** [comment]
Issue is fixed after switching to Agents package. Thanks @markwallace-microsoft 

**Unrelated to this issue** - maybe this is already possible or is being considered, I think it would be good if chat-history could be passed in when invoking the agent thread, something like this so the manager can consider past interactions when invoking workers:
var agentMessages = thread.InvokeAsync(manager_agent, userQuery, **chatHistory**);
