### ISSUE TITLE
.Net: BUG Microsoft.SemanticKernel.Connectors.Memory.Qdrant Package isn't marked as deprecated on Nuget 

### ISSUE THREAD

**Issue by yashworlikar** [microsoft/semantic-kernel#4398]
**Describe the bug**
Microsoft.SemanticKernel.Connectors.Memory.Qdrant is currently deprecated but isn't marked as such on Nuget.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Nuget package manager 
2. Search "SemanticKernel Qdrant"
3. See issue

**Expected behaviour**

Microsoft.SemanticKernel.Connectors.Memory.Qdrant should be marked as deprecated like other memory packages and point towards the Microsoft.SemanticKernel.Connectors.Qdrant 1.0.1-alpha package 

**Screenshots**

![Qdrant packages](https://github.com/microsoft/semantic-kernel/assets/142771948/2160fe2b-d767-4c61-bd2b-83e9cb596827)

![Deprecated packages](https://github.com/microsoft/semantic-kernel/assets/142771948/54df1b7d-46b5-4ad2-882c-96b8402194a7)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#

**Comment by dmytrostruk** [comment]
@yashworlikar Thanks for reporting this issue, it should be fixed now:
<img width="569" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/13853051/0bd59ac6-4b44-4695-a392-fced8eeada32">

Later, we will unlist deprecated packages so they won't appear in search, but it will be possible to install them if needed. 

For now, I will close this issue, but feel free to re-open it or create a new one in case this problem will appear again. Thank you!
