### ISSUE TITLE
.Net: 0613 models tools not recognized

### ISSUE THREAD

**Issue by rcoccia** [microsoft/semantic-kernel#4399]
I sent a completion call with ToolCallBehavior set
everything is fine with a 1106 model  but when I switch to a 0613 model (gpt4-8k) I receive the following error
Content:
{
  "error": {
    "message": "Unrecognized request arguments supplied: tool_choice, tools",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

1106 understand "tools" and "functions"
0613 knows only "functions"
SK seems support only "tools" at GA (ChatCompletionsOptions has the Function fields leveraged up to RC but now ToolCallBehavior implementations use only the Tools field despite to the model type)

understood that function is deprecated against tools but this is really a breaking change
Unfortunately I'm forced to stay on the 0613 model.. Any idea?

**Comment by stephentoub** [comment]
Are you using OpenAI or Azure OpenAI? IIRC, the latter has such an issue with gpt4 0603 that the corresponding model on OpenAI didn't have, and that also is fine with gpt-3.5-turbo 0603 on both services.

**Comment by kenakamu** [comment]
i have the same issue that I use AOAI gpt-4-32k 0603 model. any workaround for this rather than using rc3?

**Comment by rcoccia** [comment]
> Are you using OpenAI or Azure OpenAI? IIRC, the latter has such an issue with gpt4 0603 that the corresponding model on OpenAI didn't have, and that also is fine with gpt-3.5-turbo 0603 on both services.

I use aoi in Sweden region

**Comment by stephentoub** [comment]
@trrwilson, multiple folks hitting tools not working with gpt-4 on Azure OpenAI.

**Comment by kboom** [comment]
This is definitely broken in `semantic-kernel` since I can use tools using the same model through the native Azure Open AI library!

**Comment by kenakamu** [comment]
any update on this? Is this more AOAI issue?

**Comment by stephentoub** [comment]
> Is this more AOAI issue?

Yes

**Comment by kenakamu** [comment]
Then there is nothing we can do in SK side.. shall we close the issue?

**Comment by stephentoub** [comment]
I think the only thing that could be done on the SK side would be providing some option that would cause it to fallback to using the obsoleted functions support instead of the recommended tools support.  It'd be much better if Azure OpenAI fixed this in the model, though.

**Comment by ChristianWeyer** [comment]
> I can confirm the preview of gpt-4 in Azure Open AI (1106-Preview) works well (but 0603 did not, 32k or not)

How did you get the GPT-4 preview model in Azure OpenAI? I cannot see it in the list...
