### ISSUE TITLE
.Net: Support endpoints that haven't moved to "tools" yet from "functions"

### ISSUE THREAD

**Issue by ssccinng** [microsoft/semantic-kernel#4402]
**Describe the bug**

**To Reproduce**
https://github.com/ssccinng/SKTest/blob/master/SKTest4/Program.cs

Using the code in the document and making some modifications

**Expected behavior**
![image](https://github.com/microsoft/semantic-kernel/assets/22047352/054babd9-6dab-46b4-9954-95d2c0fb8fd6)

It will work properly in the old version

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/22047352/813dbb14-2eff-4a3e-98d1-7499c2c4453e)

function_call=None

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: [NuGet package version 1.0.1
 - 
Is there any new setting or is there a problem with the functionality?

**Comment by stephentoub** [comment]
I get a 404 from your repo link. Is it public? Or is there a better link?

**Comment by ssccinng** [comment]
> I get a 404 from your repo link. Is it public? Or is there a better link?

Sorry for forgetting to modify the visibility https://github.com/ssccinng/SKTest/blob/master/SKTest4/Program.cs

**Comment by stephentoub** [comment]
What is it you're rerouting calls to view that handier that's running on localhost? Does it understand tool_calls?

**Comment by ssccinng** [comment]
> What is it you're rerouting calls to via that handier that's running on localhost? Does it understand tool_calls?

chatglm3. The rc3 version can work properly


RC3
![image](https://github.com/microsoft/semantic-kernel/assets/22047352/afe22680-502b-475d-bb80-35fb6ca26cc6)

1.0.1 
![image](https://github.com/microsoft/semantic-kernel/assets/22047352/1846bf20-907f-47b8-9e02-c66dfde8a1ff)

It looks like it won't run properly in the official version

https://github.com/ssccinng/SKTest/tree/master/RC3Glm
https://github.com/ssccinng/SKTest/tree/master/101Glm

**Comment by stephentoub** [comment]
OpenAI's function calling APIs are now deprecated in favor of using tool calls, which is what SK now uses. It sounds like chatglm3 doesn't currently support tools.

**Comment by ssccinng** [comment]
> OpenAI's function calling APIs are now deprecated in favor of using tool calls, which is what SK now uses. It sounds like chatglm3 doesn't currently support tools.

That's true, thank you for the answer. Can the old plan be included as an optional option in the settings?

**Comment by stephentoub** [comment]
cc: @matthewbolanos, @markwallace-microsoft

**Comment by matthewbolanos** [comment]
@ssccinng, I see that you're getting this to "work" by adding a custom HttpClientHandler that changes the hostname to point to chatglm3. In the short term, could the HttpClientHandler also update the request to change "tools" to "functions"?

@markwallace-microsoft, if this works, perhaps this is a scalable way to introduce more connectors.

**Comment by ssccinng** [comment]
> @ssccinng, I see that you're getting this to "work" by adding a custom HttpClientHandler that changes the hostname to point to chatglm3. In the short term, could the HttpClientHandler also update the request to change "tools" to "functions"?
> 
> @markwallace-microsoft, if this works, perhaps this is a scalable way to introduce more connectors.

I tested it and it looks fine, but I'm not sure if I covered all the situations

`public class ChatGlmClientHandler : HttpClientHandler
{
    static JsonObject ChangeToolCall2FunctionCall(JsonObject data)
    {
        var node = data["tools"].AsArray().Select(s => { var res = s["function"]; s.AsObject().Remove("function"); return res; });
        data.Remove("tools");

        JsonArray jsonArray = [.. node];
        data.Add("functions", jsonArray);

        data.Remove("tool_choice");
        data.Add("function_call", "auto");

        var messages = data["messages"].AsArray();
        string functionName = "";
        foreach (JsonObject mNode in messages)
        {
            if (mNode["tool_calls"] != null)
            {
                 var toolCalls = mNode["tool_calls"].AsArray();
                 mNode.Remove("tool_calls");
                    foreach (JsonObject tNode in toolCalls)
                    {
                        if (tNode["function"] == null)
                        {
                            continue;
                        }
                        var fNode = tNode["function"];
                        tNode.Remove("function");
                        tNode.Remove("id");
                        tNode.Remove("type");

                        functionName = fNode["name"].ToString();

                        mNode["function_call"] = fNode;
                        break;
                    }
            }
            if (mNode["role"].ToString() == "tool")
            {
                mNode["role"] = "function";

                mNode["name"] = functionName;

                mNode.Remove("tool_name");
                // mNode.Remove("tool_call_id");


            }
           
        }

        return data;
    }

    static JsonObject ChangeFunctionCall2ToolCall(JsonObject data)
    {
       var cArray = data["choices"].AsArray();
        foreach (var cNode in cArray)
        {
            var mNode = cNode["message"].AsObject();
            var fnode = mNode["function_call"];
            mNode.Remove("function_call");

            JsonObject tnode = new JsonObject();

            tnode["id"] = $"call_{Random.Shared.Next(100000000)}";
            tnode["type"] = "function";
            tnode["function"] = fnode;

            mNode.Add("tool_calls", new JsonArray(tnode));

            if (cNode["finish_reason"].ToString() == "function_call")
            {
                cNode["finish_reason"] = "tool_calls";
            }

        }

        return data;
    }

    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        if (request.RequestUri.LocalPath == "/v1/chat/completions")
        {
            request.RequestUri = new Uri("http://localhost:8000/v1/chat/completions");
        }
        Console.WriteLine(request.Content.ReadAsStringAsync().Result);
        await Console.Out.WriteLineAsync();
        var data = await request.Content.ReadFromJsonAsync<JsonObject>();
        
        var function_call = ChangeToolCall2FunctionCall(data);


        request.Content = JsonContent.Create(function_call);
        Console.WriteLine(request.Content.ReadAsStringAsync().Result);
        await Console.Out.WriteLineAsync();

        var res = await base.SendAsync(request, cancellationToken);
        Console.WriteLine(await res.Content.ReadAsStringAsync());
        await Console.Out.WriteLineAsync();

        data = await res.Content.ReadFromJsonAsync<JsonObject>();
        var tool_call = ChangeFunctionCall2ToolCall(data);
        
        res.Content = JsonContent.Create(tool_call);
        Console.WriteLine( await res.Content.ReadAsStringAsync());
        await Console.Out.WriteLineAsync();

        return res;
    }
}`

**Comment by matthewbolanos** [comment]
Thank you for testing this! This looks like you covered all of the bases to me. I'll share this with engineering as we formalize our plans to support more connectors at scale.
