### ISSUE TITLE
.Net: dotnet/samples/KernelSyntaxExamples/Getting_Started /Step4_Dependency_Injection.cs not compiling

### ISSUE THREAD

**Issue by delbert** [microsoft/semantic-kernel#4406]
hello everyone,

should this sample be compiling ok, right now?

the statement:  collection.AddSingleton<ILoggerFactory>(ConsoleLogger.LoggerFactory);

is flagged because ConsoleLogger is not at the proper visability level.

thanks for any help

**Comment by dmytrostruk** [comment]
Hi @delbert ! 
All samples don't produce compilation errors for me. `ConsoleLogger` from `RepoUtils` namespace is internal, but it's located in the same assembly as `Step4_Dependency_Injection` example class, so should not be a problem.

Could you please provide more info about your environment?

**Comment by delbert** [comment]
DOH!  thanks Dmytro!  i was trying to build outside of the repo to avoid having to accommodate all of the 44 projects in the main solution.  i didn't realize RepoUtils was covering the ConsoleLogger from Microsoft.Extensions.Logging.  i appreciate the quick response.  have great Holidays!

**Comment by delbert** [comment]
.
