### ISSUE TITLE
.Net: Add overload to Kernel.InvokePromptAsync to support ChatHistory directly or add Kernel.InvokeChatAsync(ChatHistory)

### ISSUE THREAD

**Issue by Jenscaasen** [microsoft/semantic-kernel#4410]
Hello,
i am aware that the ChatHistory can be provided within the KernelArguments, but it is not intuitive. The alternative to invoking a ChatHistory with an LLM was using the OpenAIService directly, but with the Mistral Connector and possibly more Connectors coming in the future, one could also rely on invoking a ChatHistory into whatever IChatCompletionService is present in the Kernel.

The feature, if you choose to accept it, can be implemented by me via PR.

**Comment by dmytrostruk** [comment]
Hi @Jenscaasen ! We need to think about scalability, because `ChatHistory` is not the only option we would like to support. Kernel should work with different data types, including text, chat, image, video, audio etc. In case we add support for `ChatHistory` object, we should probably add the same for other data types, and I'm not sure it's a goal at the moment.

In case you know that in your application you work with `ChatHistory` in most cases, it's still possible to create an extension method on your side that will accept `ChatHistory`. Let me know what you think about it.

**Comment by Jenscaasen** [comment]
> Hi @Jenscaasen ! We need to think about scalability, because `ChatHistory` is not the only option we would like to support. Kernel should work with different data types, including text, chat, image, video, audio etc. In case we add support for `ChatHistory` object, we should probably add the same for other data types, and I'm not sure it's a goal at the moment.
> 
> In case you know that in your application you work with `ChatHistory` in most cases, it's still possible to create an extension method on your side that will accept `ChatHistory`. Let me know what you think about it.

yes that will work as well. Can be closed

**Comment by dmytrostruk** [comment]
Closing for now, feel free to re-open this issue or create a new one. Thanks!

**Comment by Jenscaasen** [comment]
I want to make a suggestion to you about that, based on what i had to implement so far in other products

GPT-4-Turbo-V does show that an image input is just a URL. Whisper shows that a voice input is just a URL. OS-Models show that Video inputs are just URLs. Same goes for outputs.
On top of that, most models require to ingest your files from a publically available URL, and offer multi-media results as publically available URLs (temporarily)

First, extend class KernelContent with a enum ContentType (TEXT, VIDEO, AUDIO, IMAGE)

Then, implement this:


interface IPublicStorageProvider
{
//returns a GUID as a file identifier
public string SaveMedia(string url, string contentType);
public string SaveMedia(byte[] data, string contentType);

//copies file to a public location for a limited time or creates a SAS Token for the time and returns the URL
public string GetPublicUrl(string fileIdentifier, TimeSpan duration);
}


This interface could now be used as BlobStorageProvider, that uses Azure Blob storage to save files and Azure Table to save the mapping between a GUID a file and their contentType (which is important to set at the public / SAS blob for proper client side download handling)

In KernelContent, the content field now contains this value:  {publiccontent:GUID}

With a IPublicStorageProvider registered in the Kernel, before giving a call to a  IChatCompletionService or ITextGenerationService, this content can be resolved by the IPublicStorageProvider into a proper URL, so the LLM can handle it without you exposing URLs when persisting the KernelContent


Enabling KernelContent to hold Media Information would automatically also benefit ChatHistories, making multi-modal calls easier across LLM providers

**Comment by aherrick** [comment]
@Jenscaasen how might you go about including the "Chat History" object in a prompt? For example I have a current QA prompt that looks like this:

```
Use the following pieces of context to answer the question at the end. If you don't know the answer, don't try to make up an answer and answer with 'I don't know'. Answer in the language that used for the question.

{{$context}}

Question: {{$input}}
Answer:
```

Would it be just a simple as having another variable for "{{chathistory}} and including that with a prompt of "Here is the previous chat history from the conversation: "

**Comment by Jenscaasen** [comment]
> @Jenscaasen how might you go about including the "Chat History" object in a prompt? For example I have a current QA prompt that looks like this:
> 
> ```
> Use the following pieces of context to answer the question at the end. If you don't know the answer, don't try to make up an answer and answer with 'I don't know'. Answer in the language that used for the question.
> 
> {{$context}}
> 
> Question: {{$input}}
> Answer:
> ```
> 
> Would it be just a simple as having another variable for `${{chathistory}}` and deserialize the messages and including that with a prompt of "Here is the previous chat history from the conversation: "

With prompt templates i do not know. The only 2 options i know of are using an  AzureOpenAIChatCompletionService service, this has an overload to use a ChatHistory, and supplying the history as "messages" in KernelArguments, like they do here:
https://github.com/microsoft/semantic-kernel-starters/blob/main/sk-csharp-hello-world/Program.cs

maybe that's outdated, since it says RC3
