### ISSUE TITLE
Azure Open AI is behind closed door.

### ISSUE THREAD

**Issue by meetrais** [microsoft/semantic-kernel#4414]
I was very enthusiastic to try semantic-kernel code but looks like Azure Open AI service is behind closed doors accessible to only corporate accounts. Please consider removing dependency on Azure Open AI or make Azure Open AI "open" to use.

**Comment by dmytrostruk** [comment]
Hi @meetrais ! Thank you for your feedback.

The integration with Azure OpenAI service is implemented as a connector, which means that Semantic Kernel core functionality doesn't have a dependency on Azure OpenAI, and it's possible to use AI provider of your choice.

Here is an example of using OpenAI directly:
https://github.com/microsoft/semantic-kernel/blob/240a2cbeaccc2e9562fa9aa82c856f74c5b5ace4/dotnet/samples/KernelSyntaxExamples/Getting_Started/Step5_Chat_Prompt.cs#L16

This example shows how to use Hugging Face Inference API or locally hosted model:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example20_HuggingFace.cs

The following example shows how to use your own integration with any AI provider of your choice:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example16_CustomLLM.cs

Please let me know if examples above unblocked you to work with Semantic Kernel functionality. Thanks a lot!

**Comment by meetrais** [comment]
@dmytrostruk Thank you, I will give it a try.
