### ISSUE TITLE
.Net: 'KernelBuilder' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by ZviGirsh** [microsoft/semantic-kernel#4416]
**Describe the bug**
When I tried to run Getting Started C# example https://github.com/microsoft/semantic-kernel/tree/main/dotnet

**To Reproduce**
1. Create console app
2. Add nuget Microsoft.SemanticKernel latest version 1.0.1
3. See error: 'KernelBuilder' is inaccessible due to its protection level

**Comment by dmytrostruk** [comment]
@ZviGirsh Thanks for reporting this issue!
PR with fix is here: https://github.com/microsoft/semantic-kernel/pull/4417
