### ISSUE TITLE
Python: Some Plugins need enhancements

### ISSUE THREAD

**Issue by meetrais** [microsoft/semantic-kernel#4419]
I started playing with Semantic-Kernel code in Python. Skills concept is so interesting however it needs enhancements. Below are some issues I noticed while testing "action_planner.py" code.

 #TextSkill
ask = "Whats the position of character O in the word Orange?"
error - 'Function not available: text.index_of'

#MathSkill
ask = "Whats would be result if I multiply 25 with 4?"
error - 'Function not available: math.multiply'

**Comment by moonbox3** [comment]
Note: "Skills" are called "Plugins" now.
