### ISSUE TITLE
.Net: Is it possible to bring the sequential planner back to V1.0 and beyond

### ISSUE THREAD

**Issue by strikene** [microsoft/semantic-kernel#4422]
In fact, the 'handlebar' in V1 is not as easy to use as the original sequential planning, and it is better to use sequential planning in many tasks and scheduling, although I agree that the 'handlebar' is definitely more powerful, but at the moment the 'handlebar' is not the best choice.

Can we keep the original sequential plan but bring it back into V1 without adding any features changes?

The following features are currently missing from the 'handlebar', which are already available in the Sequence Planner
1. Parameters are passed between multiple 'handlebar' plans
2. Modify the variables in Plan

     This issue was mentioned in 
     - #4252 
     - #4293 
     
3. Add an expertise generation plan 

As an example, we mentioned the Azure subscription ID in the conversation, which is written to memory. In sequence planning we can generate the right tasks with a simple template, but it is difficult to add such information on the 'handlebars'.

String RequestToPlan = @"
Past memories (format: [memory type] <label>: <details>):
{{$memories}}
INTENT: {{$UserIntent}}"

memories = [ChatMemory] AzureSubscriptionid: 0000-000000-0000-000
UserIntent=  The region where the resource are distributed in Azure
I have a custom Azure plugin for this functionality
 [KernelFunction()]
 [Description("Getting an available subscription is the first step in your operation against Azure, " +
             "The function returns a list in JSON containing the display name and SubscriptionId(GUID) of the subscription, respectively ." +
             "where 'SubscriptionId' is required for subsequent Azure-related operations")]
 public async Task<String> GetAvailableSubscriptions()
[KernelFunction()]
[Description("Get resource that already exist under the given azure subscription ID." +
                    "The function returns a list in JSON containing the Name , Location , ResourceId , kind of the Resource, respectively .")]
public async Task<String> GetResource(
    [Description("Specify the subscription ID(GUID), which is required .you can got ID form 'GetAvailableSubscriptions'")] String SubscriptionId)

**Comment by matthewbolanos** [comment]
From what I can tell, most (if not all) of the issues are related to the fact that input parameters are hardcoded in the Handlebars plans. Is this correct? If we made them parameterized, would that address your needs? (i.e.., if the Handlebars planner created a plan with parameters for the inputs), or would there still be scenarios that couldn't be supported?

**Comment by blinchi** [comment]
In my case, the sequential planner returns the result of the last call to the API and then I sends it to another prompt to get the desired result by stream. With the handlebar or stepwise planner, it always returns the answer to what was requested and not the result of the API, without being able to get that response in stream.

**Comment by strikene** [comment]
> From what I can tell, most (if not all) of the issues are related to the fact that input parameters are hardcoded in the Handlebars plans. Is this correct? If we made them parameterized, would that address your needs? (i.e.., if the Handlebars planner created a plan with parameters for the inputs), or would there still be scenarios that couldn't be supported?

HI

I'm sorry, I replied too late. I just took a three-week sabbatical.
Parameterization is a must, after all, the handlebar cannot decompose complex tasks 100% correctly, and parameterized inputs/outputs can perform complex tasks better because we can decompose them and then combine them. The sequence planner really does a great job of this
