### ISSUE TITLE
Python: MongoDBAtlasMemoryStore import error

### ISSUE THREAD

**Issue by Krsnadeva** [microsoft/semantic-kernel#4433]
**Describe the bug**
from semantic_kernel.connectors.memory.mongodb_atlas import MongoDBAtlasMemoryStore
throws error from motor import MotorCommandCursor, core, motor_asyncio
ImportError: cannot import name 'MotorCommandCursor' from 'motor' 
**To Reproduce**
from semantic_kernel.connectors.memory.mongodb_atlas import MongoDBAtlasMemoryStore

**Expected behavior**
Import with no errors.

**Screenshots**
here is the full trace:
(.venv) PS C:\Users\krsna\OneDrive\__RND__\SEMANTIC-KERNEL> & c:/Users/krsna/OneDrive/__RND__/SEMANTIC-KERNEL/.venv/Scripts/python.exe c:/Users/krsna/OneDrive/__RND__/SEMANTIC-KERNEL/run3.py
Traceback (most recent call last):
  File "c:\Users\krsna\OneDrive\__RND__\SEMANTIC-KERNEL\run3.py", line 12, in <module>
    from semantic_kernel.connectors.memory.mongodb_atlas import MongoDBAtlasMemoryStore
  File "C:\Users\krsna\OneDrive\__RND__\SEMANTIC-KERNEL\.venv\Lib\site-packages\semantic_kernel\connectors\memory\mongodb_atlas\__init__.py", line 1, in <module>
    from semantic_kernel.connectors.memory.mongodb_atlas.mongodb_atlas_memory_store import (
  File "C:\Users\krsna\OneDrive\__RND__\SEMANTIC-KERNEL\.venv\Lib\site-packages\semantic_kernel\connectors\memory\mongodb_atlas\mongodb_atlas_memory_store.py", line 7, in <module>
    from motor import MotorCommandCursor, core, motor_asyncio
ImportError: cannot import name 'MotorCommandCursor' from 'motor' (C:\Users\krsna\OneDrive\__RND__\SEMANTIC-KERNEL\.venv\Lib\site-packages\motor\__init__.py)
(.venv) PS C:\Users\krsna\OneDrive\__RND__\SEMANTIC-KERNEL>

**Platform**
 - OS: WIN11
 - IDE: VS Code
 - Language: Python
 - Source: pip install semantic-kernel

**Additional context**
It might be a mongodb atlas error, i searched and there was an issue with motor and python 3.11 (i am using 3.11.6)

**Comment by Krsnadeva** [comment]
hey fellas, i got a simple fix,
in the file mongodb_atlas_memory_store.py
remove:
  MotorCommandCursor from  the import at line 7 (this is the line with the error)
  from motor import MotorCommandCursor, core, motor_asyncio
  now is like this: 
  from motor import core, motor_asyncio

then add:
  from motor.motor_asyncio import AsyncIOMotorCommandCursor

now around line 285:
  from this:
    cursor: MotorCommandCursor = self.database[collection_name].aggregate(pipeline)
  to this:
    cursor: AsyncIOMotorCommandCursor =self.database[collection_name].aggregate(pipeline)

it works now.

**Comment by Jibola** [comment]
Hey @Krsnadeva. I looked into your issue and the fix is correct. Based on whether or not `tornado` is installed the `MotorCommandCursor` will appear. A short-term for those doing `pip install semantic-kernel` is to additionally run `pip install tornado`. 

For the additional error you've run into, I've provided a fix that will properly query based on the `min_relevance_score` being provided.

**Comment by eavanvalkenburg** [comment]
this class has changed a lot, please refile a bug if this is still a issue
