### ISSUE TITLE
.Net Not possible add InternalsVisible to connectors projects for unit testing purposes

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#4436]
**Describe the bug**

Due to shared classes not shared library in AI.Connectors project, this is impossible to add InternalsVisibleTo to more than one connector project. This is inconvenient for unit testing, as I then have to choose whether to make the internal class public or not test it at all. And currently I am working on a Gemini connector implementation.

**To Reproduce**

Add below lines to connector project other than OpenAi for example to HuggingFace AI connectors project.
`<ItemGroup>
    <InternalsVisibleTo Include="SemanticKernel.Connectors.UnitTests" />
  </ItemGroup>`

**Expected behavior**

Internals from all connectors projects visible to Connectors.UnitTest project.

**Comment by dmytrostruk** [comment]
@Krzysztof318 Is it possible to access internal types or members with reflection in your case? You can also create a new test project for Gemini connector if you want to use `InternalsVisibleTo` flag. (e.g. `Connectors.Gemini.UnitTests`).

**Comment by Krzysztof318** [comment]
I wasn't sure what rules you have so I didn't want to create a new test project. But if it's not a problem I'll create an additional project, I prefer this solution to reflection.
