### ISSUE TITLE
Private repos on the GitHub Q&A sample

### ISSUE THREAD

**Issue by mahomedalid** [microsoft/semantic-kernel#444]
I would want to use the GitHub Q&A sample with private repositories. 

## Details

I have a local prototype of this feature, I would like to put a PR, but in the contributing guidelines talks about "Get agreement from the team and the community that your proposed change is a good one."

### Screenshots of the prototype

Adding a PAT Token option in the REACT app:

![image](https://user-images.githubusercontent.com/952392/231893968-91ae41ac-c053-4776-92c5-0cb3e5f9679c.png)

Adding the PAT Token to the GitHubSkill:

![image](https://user-images.githubusercontent.com/952392/231894047-55c079fd-795a-4672-b932-f12744a8d36c.png)

Allow the Download skill to modify headers:

![image](https://user-images.githubusercontent.com/952392/231894099-9a0a7fab-2c7b-477a-b642-cedbb9ef639f.png)

**Comment by dluc** [comment]
@hathind-ms @timlaverty this sounds a great add

**Comment by shawncal** [comment]
@mahomedalid Yeah, please do!

**Comment by mahomedalid** [comment]
@shawncal  added a PR, need to solve a conflict and also add some unit tests.

**Comment by evchaki** [comment]
@mahomedalid let us know if you have any questions about your PR so we can pull it in

**Comment by mahomedalid** [comment]
@evchaki  I solved the conflicts multiple times, but there were multiple times of days updates on the repo, so I put that on-hold. I will do it again today.

> @mahomedalid let us know if you have any questions about your PR so we can pull it in

**Comment by mahomedalid** [comment]
@evchaki everything is up to date and green now. Let me know if I can do anything else.
