### ISSUE TITLE
Proposal: Use fluent assertions in unit tests

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#4443]
Hi, it would be nice if we could use fluent assertions in the unit tests, it is convenient and increases the readability of the code. However, I do not want to write tests myself using fluent assertions without your permission.

Is there agreement on your part to use fluent assertions in tests?

**Comment by stephentoub** [comment]
> it is convenient and increases the readability of the code

Personally, I find it actually makes the code harder to understand. Matter of preference.

**Comment by Krzysztof318** [comment]
Sure, I understand. OK, I'll use the classic assertions in that case.

**Comment by dmytrostruk** [comment]
I agree, classic assertions are more readable for me, I would leave it as it is. Will close this issue for now. @Krzysztof318 thanks for proposal!
