### ISSUE TITLE
.Net: FunctionCallingStepwisePlanner: Passing Null as an Argument to External Plugin

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/semantic-kernel#4445]
**Describe the bug**

Most of the time, the FunctionCallingStepwisePlanner passes null as the argument to the external plugin, while occasionally it does pass a value to the arguments.

**To Reproduce**

Develop a sample application incorporating native code for an external plugin. Utilize the FunctionCallingStepwisePlanner to pass values to the external plugin.

here my sample code 
In this example, I supplied the city name to the external plugin.
https://github.com/rvinothrajendran/MicrosoftSemanticKernelSamples/tree/main/SKSampleCSharp/FunctionCallingStepwiseDemo

**Expected behavior**
It is mandatory to provide a value to the function each time.

**Screenshots**

**Platform**
 - OS:  Windows 11
 - IDE: Visual Studio
 - Language: C#
 - Source: Microsoft.SemanticKernel.Planners.OpenAI - 1.0.1-preview

**Comment by matthewbolanos** [comment]
@rvinothrajendran, after looking at your repo, it looks like your native function uses KernelArguments to get the necessary inputs. Unfortunately, using this pattern makes it impossible for a planner or automatic function calling to know which properties to pass in.

To fix this, you'll want to explicitly define the input parameters in the method signature (in your case "input"). As a sample, you can refer to the learn docs here: https://learn.microsoft.com/en-us/semantic-kernel/agents/plugins/using-the-kernelfunction-decorator?tabs=Csharp#creating-the-remaining-math-functions.

**Comment by rvinothrajendran** [comment]
@matthewbolanos Thank you 
You're right. But what I'm asking is whether the API should only support one way. Currently, the API does support both ways. However, there's a problem – half the time, using KernelArguments works, but the other half, it fails, and that's causing confusion.

**Comment by matthewbolanos** [comment]
Unfortunately, I don't think we can throw an error at this point since it would introduce a breaking change to the interface. We may be able to explore adding warnings though. In the meantime, I want to improve our docs so its more clear what the preferred approach is (and why).
