### ISSUE TITLE
Support injecting PromptExecutionSettings into KernelFunction directly.

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#4456]
Currently, to get access to the `PromptExecutionSettings` from within a `KernelFunction`, you need to add a parameter of type `KernelArguments` and then use it's `ExecutionSettings` property. One of the issues with this is that injecting `KernelArguments` into a function can encourage using it to access other arguments rather than creating parameters on the function. For example, doing this:

```
[KernelFunction, Description("Take the square root of a number")]
public static double Sqrt(KernelArguments arguments)
{
    return Math.Sqrt(arguments["number1"]);
}
``` 

rather than this:

```
[KernelFunction, Description("Take the square root of a number")]
public static double Sqrt([Description("The number to take a square root of")] double number1)
{
    return Math.Sqrt(number1);
}
```

The first example should be avoided because Semantic Kernel does not have the metadata that it needs to use the function effectively in planners.

To help with the confusion this causes, we should support injecting `PromptExecutionSettings` into a `KernelFunction` directly as in:

```
[KernelFunction, Description("Take the square root of a number")]
public static double Sqrt([Description("The number to take a square root of")] double number1, PromptExecutionSettings executionSettings)
{
    // Do something with execution settings
    return Math.Sqrt(number1);
}
```

**Comment by stephentoub** [comment]
Duplicate of https://github.com/microsoft/semantic-kernel/issues/4210?

**Comment by alliscode** [comment]
Yup, looks that way :) Thanks!
