### ISSUE TITLE
.Net: SK v1.0 in a .Net Core 3.1 Project: Exception Info: System.PlatformNotSupportedException: EventLog access is not supported on this platform

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#4460]
Is .Net 8.0 a requirement for using SK v1.0?
We're trying to migrate to SK 1.0 from preview in a .net core 3.1 project, but facing this exception.
Not directly from SK lib, but seems something underneath SK triggered it.
 
As seen below, the story is that SK 1.0.1 forces to use Microsoft.Extensions.DependencyInjection.Abstractions 8.0.0, in turn we have to upgrade almost all Microsoft.Extensions.XXXX libs to 8.0.0, which does seem broken for .net core 3.1, even I managed to get things compile, but when run, failed at startup while processing the DI with the exception mentioned in the title.
 
Appreciated if we could get some help to make it work without having to upgrade our stack to .net 8, it's in our plan, but would be better not blocking the SK v1.0 adoption first.
 
Similar to this issue found online, which seems due to compatibility between .NET Core 3.1 and Microsoft.Extensions.Logging 7.0.0+
https://stackoverflow.com/questions/74472659/exception-info-system-platformnotsupportedexception-eventlog-access-is-not-sup

**Comment by stephentoub** [comment]
> Is .Net 8.0 a requirement for using SK v1.0?

No. It relies on the 8.0 versions of some nuget packages, but it works fine with NET Framework, NET 6.0, etc.

Can you share a standalone repro?

**Comment by SergeyMenshykh** [comment]
Closing the issue because the app plans to migrate from the already unsupported .NET 3.1 to .NET 8.
