### ISSUE TITLE
Python: add truncation methods to chat history

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/semantic-kernel#4463]
In a long chat conversation you want to be able to truncate the message history, either by deleting specific messages, oldest messages or by replacing (a set of) messages with a summary, this should be easy and transparent. Related to #3559

**Comment by eavanvalkenburg** [comment]
This can now be started on the Chathistory object, @matthewbolmatt this would be a great one for the community to pick up!

**Comment by alliscode** [comment]
This is a dupe of #6770
