### ISSUE TITLE
.Net: Support for .NET 6 runtime

### ISSUE THREAD

**Issue by Woland2k** [microsoft/semantic-kernel#4481]
**Describe the bug**
I can see that solution was updated to .NET 8.0. It now makes it difficult to run in .NET6 based solutions.
https://github.com/microsoft/semantic-kernel/commit/c025402245f87629a5b49411d66e1cfad2048ee5

More specifically: PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0"

Now requires version 8 instead of 6.

Are you still planning to support version 6?

**Comment by stephentoub** [comment]
That's only about the nuget package version for that component. SK still targets netstandard2.0, works great with .NET Framework, works great with .NET 6, etc. In fact, you'll see in this repo currently most of the test projects are targeting net6.0.

**Comment by Woland2k** [comment]
Yeah, however my solution has a dependency on Microsoft.Extensions.DependencyInjection 6.0.0, which prevents SemanticKernel from running within a project as it has a dependency on 8.0.0 version due to that LTS checkin.

**Comment by stephentoub** [comment]
> Yeah, however my solution has a dependency on Microsoft.Extensions.DependencyInjection 6.0.0, which prevents SemanticKernel from running within a project as it has a dependency on 8.0.0 version due to that LTS checkin.

What prevents your application from using a newer version of that nuget package? i.e. why have you locked it to not use anything newer?

**Comment by Woland2k** [comment]
It is a product that is distributed to many clients and it has dependency on 6.0.0 version of abstractions (which is pretty default for .NET6). It also is extended by use of plugin system, but the core dependency needs to be 6.0.0.

<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />

https://github.com/VirtoCommerce/vc-platform/blob/dev/src/VirtoCommerce.Platform.Core/VirtoCommerce.Platform.Core.csproj

There is .NET8 version that will be released end of the month, but I would prefer to have a plugin that uses Semantic for the .NET6 (it worked fine with beta semantic before).

Hope this explains things a bit.

**Comment by stephentoub** [comment]
> but the core dependency needs to be 6.0.0

But the csproj only specifies a lower bound:
https://github.com/VirtoCommerce/vc-platform/blob/dev/src/VirtoCommerce.Platform.Core/VirtoCommerce.Platform.Core.csproj#L30
What's enforcing it also as an upper bound?

In any event, the version won't be lowered. SK has a heavy dependency now on the keyed DI support that was introduced in the 8.0 version of the nuget package.  It had its own bespoke DI container previously that provided naming support, but that meant it didn't integrate well with anything else in the Microsoft.Extensions.DependencyInjection ecosystem... now it does.

**Comment by Woland2k** [comment]
Compile generates dependency file which is what used to load the 6.0.0 DLL (VirtoCommerce.Platform.Web.deps.json) when web app is started, so it won't pick 8.0.0 version. 

Let me see if we can make a .NET6 release of the product with new dependencyinjection libraries.

Hopefully SK becomes a bit more stable with a 1.x release in terms of dependencies.
