### ISSUE TITLE
.Net: Better document how to use existing registered dependencies with kernel

### ISSUE THREAD

**Issue by rosieks** [microsoft/semantic-kernel#4482]
Right now Kernel use separate instance of service provider. That make it hard to consume already registered dependencies. It would be nice to have way to use existing service provider. Something like that:

```csharp
    services
        .AddDbContext<MyDbContext>()
        .AddTransient<MyPluginThatUseMyDbContext>()
        .AddKernelMemory(builder =>
         {
            builder.UseAzureOpenAITextGeneration(...);
         })
        .AddSemanticKernel(builder =>
        {
            builder.UseAzureOpenAIChatCompletion(...);
            builder.Plugins.AddFromType<MyPluginThatUseMyDbContext>();
            builder.Plugins.AddFromType<MemoryPlugin>();
        })
```

**Comment by stephentoub** [comment]
You can write that as something like this:
```C#
    services
        .AddDbContext<MyDbContext>()
        .AddTransient<MyPluginThatUseMyDbContext>()
        .AddKernelMemory(builder =>
         {
            builder.UseAzureOpenAITextGeneration(...);
         })
        .AddKernel()
        .AddAzureOpenAIChatCompletion(...)
        .AddSingleton<KernelPlugin>(KernelPluginFactory.CreateFromType<MyPluginThatUseMyDbContext>())
        .AddSingleton<KernelPlugin>(KernelPluginFactory.CreateFromType<MemoryPlugin>());
```

The AddKernel method registers a transient Kernel as well as a transient KernelPluginCollection. The latter will find all registered KernelPlugins and add them into the collection, which will then be brought into the Kernel, along with all of the other registered services.

**Comment by rosieks** [comment]
Ahh, I just noticed that there is parity of extensions methods and they are both available for `IKernelBuilder` as well as `IServiceCollection`. Then maybe it's just matter of documenting how to integrate with existing application rather than how to make simple console app.

**Comment by rosieks** [comment]
@stephentoub
I just noticed that this code doesn't work:

```csharp
services.AddSingleton<Kernel>(serviceProvider =>
{
    Kernel k = new(serviceProvider);
    k.Plugins.AddFromType<MyPluginThatUseMyDbContext>();
    k.Plugins.AddFromType<MemoryPlugin>();
    return k;
});
```

Instead it has to be something like that. Otherwise serviceProvider is null and Plugins collectionn has no knowledge about service provider of owning kernel:
```csharp
services.AddSingleton<Kernel>(serviceProvider =>
{
    Kernel k = new(serviceProvider);
    k.Plugins.AddFromType<MyPluginThatUseMyDbContext>(serviceProvider: serviceProvider);
    k.Plugins.AddFromType<MemoryPlugin>(serviceProvider: serviceProvider);
    return k;
});
```

**Comment by rosieks** [comment]
As I understand the lifecycle of plugins is same as the kernel in this scenario? So if I use DbContext which is scoped then I cannot register kernel as singleton but rather scoped or transient? How it influence performance? Does initialization of kernel do some intensive work or it's just matter of memory allocations?

**Comment by stephentoub** [comment]
AddKernel registers Kernel as transient. The Kernel ctor does very little work:
https://github.com/microsoft/semantic-kernel/blob/4778b0fd30546321f62e44e55142af4528c36ea6/dotnet/src/SemanticKernel.Abstractions/Kernel.cs#L48-L70

**Comment by rosieks** [comment]
It looks like using Kernel both with plugins and DI is not so intuitive and confusing. I wonder if adding `ImportPluginFromType` to KernelBuilder wouldn't be beneficial anyway. Then the whole setup would be much simpler:

```csharp
services.AddTransient<MyPlugin1>();
services.AddScoped<MyPlugin2>();
services.AddAzureOpenAIChatCompletion(...);
services.AddKernel()
    .ImportPluginFromType<MyPlugin1>()
    .ImportPluginFromType<MyPlugin2>()
```

Or something like that

**Comment by noeltupas** [comment]
@stephentoub Question here: Injecting a Transient Kernel into a Singleton component essentially makes the Kernel a Singleton. Is Kernel usage still considered thread safe at this point? Documentation suggests that the Kernel should not be a Singleton, however our consuming component must remain Singleton.

**Comment by stephentoub** [comment]
> Is Kernel usage still considered thread safe at this point? Documentation suggests that the Kernel should not be a Singleton, however our consuming component must remain Singleton.

It depends what you do with it. If all you're doing is querying it for services, using its invocation methods, reading from it, etc., totally fine. And in that regard, it's fine to have Kernel as a singleton. But Kernel also exposes some mutable members, e.g. the list of prompt filters, and mutating those is not thread-safe... even if the actual act of modifying (e.g. adding to the list) wouldn't corrupt the data structures in the face of race conditions, logically it doesn't make sense, e.g. if two different uses want to use two different sets of filters, both sharing the same Kernel instance doesn't work.  So, if you want to register Kernel as a singleton, that's totally fine, but then any uses where you need to mutate it should instead call `kernel = kernel.Clone()` to first get a copy, which you can then party on to your heart's content.

**Comment by noeltupas** [comment]
> > Is Kernel usage still considered thread safe at this point? Documentation suggests that the Kernel should not be a Singleton, however our consuming component must remain Singleton.
> 
> It depends what you do with it. If all you're doing is querying it for services, using its invocation methods, reading from it, etc., totally fine. And in that regard, it's fine to have Kernel as a singleton. But Kernel also exposes some mutable members, e.g. the list of prompt filters, and mutating those is not thread-safe... even if the actual act of modifying (e.g. adding to the list) wouldn't corrupt the data structures in the face of race conditions, logically it doesn't make sense, e.g. if two different uses want to use two different sets of filters, both sharing the same Kernel instance doesn't work. So, if you want to register Kernel as a singleton, that's totally fine, but then any uses where you need to mutate it should first clone, e.g. `var myPersonalKernel = singletonKernel.Clone()`, to first get a copy, which you can then party on to your heart's content.

Awesome. Thank you for the knowledge share! Much appreciated. Allows us to simplify our code to a significant degree! 👍

**Comment by matthewbolanos** [comment]
Closing now that we have a sample that demonstrates how to use DI with Semantic Kernel: https://github.com/microsoft/semantic-kernel/tree/main/dotnet/samples/Demos/HomeAutomation

This should be able to provide the standard patterns we recommend when using DI and a kernel
