### ISSUE TITLE
Python: Invoking Skill More than once hangs the Kernel

### ISSUE THREAD

**Issue by wnwanne** [microsoft/semantic-kernel#4492]
**Describe the bug**
When trying to invoke a skill again in a notebook, the kernel hangs and continues to run with no completion eventually timing out.

**To Reproduce**
1. Go to "02-running-prompts-from-file.ipynb"
2. Run through notebook, then change the input text and re-run the last cell where you generate a joke

**Expected behavior**
The output should update or display something

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: Python

**Comment by moonbox3** [comment]
@wnwanne, thanks for reporting the issue. It looks like the async joke invoke works with multiple calls. I will look into why the sync invoke is hanging.

**Comment by moonbox3** [comment]
@wnwanne when working with Jupyter notebooks and asyncio, Jupyter already runs its own event loop. This means that when we try to manage another event loop, which is the case with the current code, it can lead to conflicts or unexpected behaviors like the hanging issue you're seeing. I would recommend we make a chance to run the code asynchronously, as shown in commented out example:

```
result = await jokeFunction.invoke_async("time travel to dinosaur age")
print(result)
```

I can make this update, unless you want to.

**Comment by wnwanne** [comment]
thanks for this!
