### ISSUE TITLE
.Net: Document how to create an agent with OpenAI Assistants on learn.microsoft.com

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4500]
### OUT OF SCOPE
The following pages need to be updated to reflect the updates to agents:
- [ ]  https://github.com/MicrosoftDocs/semantic-kernel-pr/blob/main/semantic-kernel/concepts/agents.md
- [ ] https://learn.microsoft.com/en-us/semantic-kernel/get-started/quick-start-guide?pivots=programming-language-csharp (update sample to use ChatCompletionAgent)
- [ ] https://github.com/MicrosoftDocs/semantic-kernel-pr/blob/main/semantic-kernel/integrations/index.md (should have a table for agent support across languages)
- [ ] All pages under https://github.com/MicrosoftDocs/semantic-kernel-pr/blob/main/semantic-kernel/plugins (should update all samples to use ChatCompletionAgent)

### IN SCOPE
An "Agent Framework" section should be introduced that includes a thoughtful progression, as well as:
- [X] https://github.com/MicrosoftDocs/semantic-kernel-pr/blob/main/semantic-kernel/concepts/agents/chatcompletion.md
- [X] https://github.com/MicrosoftDocs/semantic-kernel-pr/blob/main/semantic-kernel/concepts/agents/assistants.md

**Comment by crickman** [comment]
https://learn.microsoft.com/en-us/semantic-kernel/frameworks/agent
