### ISSUE TITLE
[Docs] In COMMUNITY.md link of calendar-APAC.ics 

### ISSUE THREAD

**Issue by siliang-j-1225** [microsoft/semantic-kernel#4506]
**Describe the bug**
In COMMUNITY.md, clicking the link `[calendar-APAC.ics](https://aka.ms/sk-community-calendar-apac)`  will still download `calendar.ics` instead of `calendar-apac.ics`

**To Reproduce**
1. Go to 'COMMUNITY.md'
2. Click on '[calendar-APAC.ics](https://aka.ms/sk-community-calendar-apac)'
3. Check the downloaded .ics file

**Expected behavior**
The correct .ics file should be downloaded

**Screenshots**
na

**Platform**
 - OS: windows
 - IDE: edge
 - Language: not related
 - Source: not related

**Additional context**
na

**Comment by matthewbolanos** [comment]
It looks like both community events are in the same ICS file, so if you download the file it should work (you'll get all of the community events). We should update the COMMUNITY.md file to make this more clear.
