### ISSUE TITLE
.Net: Update docs to remove references to SKFunction

### ISSUE THREAD

**Issue by jitendra-25** [microsoft/semantic-kernel#4511]
What is the difference between the [SKFunction] and [KernelFunction] attributes? 
1. On this document it is mentioned to use SKFunction attribute on ReadTextAsync method inside the DocumentPlugin - https://learn.microsoft.com/en-us/semantic-kernel/agents/plugins/?tabs=Csharp
2. While on this document it is mentioned to use KernelFunction attribute on SendEmailAsync method inside the EmailPlugin - https://learn.microsoft.com/en-us/semantic-kernel/agents/

So, when should I use which attribute? Please clarify, also provide any documentation link if available.

Thanks,
Jitendra

**Comment by stephentoub** [comment]
[SKFunction] was renamed to [KernelFunction]. Docs that still refer to "SKFunction" should be updated to "KernelFunction", as the former no longer exists.

**Comment by matthewbolanos** [comment]
Changed the name of the issue to reflect the need to update the docs.

**Comment by jitendra-25** [comment]
Thanks for the clarification.

**Comment by RegRom** [comment]
Why is this issue closed as completed? The docs are still referencing SKFunction, example below:

https://learn.microsoft.com/en-us/semantic-kernel/agents/plugins/?tabs=Csharp
