### ISSUE TITLE
Add ability to serialize automated function calling

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4521]
Today, the automated function calling feature parallelizes the functions that are called by the LLM. In most cases, this is the preferred pattern. There are some cases, however, where you need to guarantee that the functions are called sequentially.

For example, when giving the LLM functions to manipulate GUI (e.g., Microsoft Word), each function needs to happen one at a time because it's not possible to paralyze mouse clicks or keyboard presses. If you _do_ try to paralyze the requests, the following will result:

Prompt: "Can you create a numbered list of 10 funny jokes?"

<img width="1281" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1409190/ade039f2-0103-4e6b-ae46-0347dea3a9bd">

**Comment by stephentoub** [comment]
By parallelize, you mean actually running them concurrently?  It doesn't do that; it doesn't serialize their invocation, running them one after the other:
https://github.com/microsoft/semantic-kernel/blob/f5ec4b7178d635cd3bf1b01b15c3843db16cbe18/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L302
https://github.com/microsoft/semantic-kernel/blob/f5ec4b7178d635cd3bf1b01b15c3843db16cbe18/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L350

Maybe I've misunderstood, or maybe something else is going on in your example?

**Comment by matthewbolanos** [comment]
Hmmm... your right; something else must be going on in my sample... I had assumed we were already paralyzing the tool calls. I'll go ahead and close this and reopen it once I figure out what's going on.
