### ISSUE TITLE
.Net:  Need the last step of a chain execution supporting "Streaming experience" output (IAsyncEnumxxx?)

### ISSUE THREAD

**Issue by waynebaby** [microsoft/semantic-kernel#4537]
It appears that we can only receive the result as a whole if the call is not a chat. However, when doing reports generation and other big tasks with user operating, the waiting time on the client side can exceed 100-200 seconds, which is painful. 

If the last execution of a chain call happens to be a semantic function, an immediate response with streaming output would greatly enhance the user experience.

if there is a way to do that already,  then I am sorry. :D

**Comment by matthewbolanos** [comment]
Are you able to explain what you mean by when you say "if the call is not a chat"? You should be able to stream the last step in the process if it's a semantic function (or _any_ function that has a streaming return type).

**Comment by matthewbolanos** [comment]
In this example, we show how you can stream the result: https://github.com/MicrosoftDocs/semantic-kernel-docs/blob/main/samples/dotnet/04-Templatizing-Prompts/Program.cs. Can you see if this addresses your needs?

**Comment by waynebaby** [comment]
@matthewbolanos another 1000 thanks for pointing out the feature. It is what I need.
Root cause of the condition was it was 1.0.1 new but for dependency I cannot update my beta version to it yet.

I am trying to close this issue and hope it is not rude.
