### ISSUE TITLE
Python: Unable to use dataSources with AzureOpenAIService to get tool and assistant messages

### ISSUE THREAD

**Issue by andrewldesousa** [microsoft/semantic-kernel#4538]
**Describe the bug**
Hey team - had a question regarding utilizing dataSources with the AzureOpenAIService ChatCompletion API and would appreciate some help.
 
By trying to pass dataSource in the extraBody, I receive a 400 error. Does this test actually represent a valid use of the data sources? i was thinking maybe it just hasn't been caught here because the network request is being mocked. https://github.com/microsoft/semantic-kernel/blob/111a550e45cf2859494d478c403c1daa874885c4/python/tests/unit/ai/open_ai/services/test_azure_chat_completion.py#L28
 
What I found was that the API accepts dataSource as a root level key in the body and I am able to complete a request successfully but am unable to retrieve the "tool" message. seems like tool message processing is built around this extra body setting - https://github.com/microsoft/semantic-kernel/blob/ec5be3ebbd54d6f9b9f5bbdc507a494a72177f3f/python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py#L335C1-L336C1
 
To work around this, I am passing an empty extraBody but having a hard time retrieving the content from the AzureChatWithDataStreamResponse.

**To Reproduce**
Attempt to leverage dataSources with the Azure Chat Completion API. You can use code similar to the code in the unit test that I provided in the first link.

**Expected behavior**
I would like to retrieve the tool and assistant message from the API.

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: Python
 - Source: semantic-kernel==0.4.4.dev0

**Comment by moonbox3** [comment]
Hi @sarah-widder do you have any guidance? Thank you!
