### ISSUE TITLE
Python: Add plugin class that can hold multiple types of functions (e.g., native and prompts)

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4560]
This should also be used as an opportunity to bring all "skill_collection" classes together

**Comment by moonbox3** [comment]
Planning to introduce the KernelPlugin (base class) and the DefaultKernelPlugin, along with unit tests, in this first iteration. Once we move to support the KernelFunction then we can also introduce the KernelFunctionMetadata. I think at that point it makes sense updating the code to start using the DefaultKernelPlugin.

**Comment by moonbox3** [comment]
Also waiting for further review on #4595 so I can commit to main and then push a PR for the KernelPlugin as it depends upon the rename.

**Comment by moonbox3** [comment]
Refactoring PluginCollection classes will be done in #4667
