### ISSUE TITLE
Python: Create ADR for things that are now automatically handled by other SDKs in .NET (i.e., retry, http handler, logging)

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4562]
Several features were removed from the .NET SDK since they already had existing implementations in the .NET ecosystem (e.g., retry handlers). In Python, we should identify if a similar strategy should be used for these different pieces of technology.

**Comment by eavanvalkenburg** [comment]
@matthewbolanos do we have a list of what these are? 

- retry logic
- http handler?
- logging -> this is done using the stdlib in python, do we need a ADR for that?

cc: @moonbox3

**Comment by moonbox3** [comment]
Closing as not relevant for Python.
