### ISSUE TITLE
Python: Replace SKContext with Kernel and KernelArguments (KernelArguments is a replacement for ContextVariables)

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4565]
In the .NET SDK, all of the method signatures were updated to take a Kernel object and KernelArguments object instead of SKContext. This PR is to both update all the method signatures and deprecate SKContext and Context variables.

**Comment by eavanvalkenburg** [comment]
@matthewbolanos i was looking into this, but there doesn't seem to be a ADR associated with this, or did I miss it, did see the ADR for function result but that is the other side of the equation afaic!
