### ISSUE TITLE
.Net: Proposal: Sanitize input by stripping invalid characters instead of throwing exception

### ISSUE THREAD

**Issue by igochkov** [microsoft/semantic-kernel#4567]
**Describe the bug**
The current implementation of `ValidPluginName` (line 61) and `ValidFunctionName` (line 75) methods in `Functions.OpenAPI/Diagnostics/Verify.cs` throws an argument invalid name exception when the input name contains invalid characters. This behavior prevents using certain naming conventions like those used in GitHub's REST API OpenAPI Description, which allows characters such as `/` and `-` in their `operationId` fields.

**To Reproduce**
The issue can be reproduced by passing a string containing invalid characters (according to the current validation rules) to the `ValidPluginName` or `ValidFunctionName` methods.

Example:
```csharp
// This will throw an exception due to the presence of '/' and '-'.
ValidPluginName("issues/create-milestone");
ValidFunctionName("issues/create-milestone");
```

**Expected behavior**
Instead of throwing an exception, it would be better if the method sanitizes the input by removing any characters that do not match the validation regex (`s_asciiLettersDigitsUnderscoresRegex`).

For example, if we provide `"issues/create-milestone"` as an input, the method should return `"issuescreatemilestone"` or other sanitized version using Pascal or Camel case, removing the `/` and `-` characters.

**Platform**
 - OS: -
 - IDE: -
 - Language: C#
 - Source: Microsoft.SemanticKernel.Plugins.OpenApi package, version 1.0.1-alpha

**Additional context**
This update is vital for maintaining compatibility with APIs that have different naming conventions. By sanitizing input, you can ensure the methods are more flexible and can handle a broader range of valid identifiers used by such external systems.

For reference, here is the [GitHub's REST API OpenAPI Description](https://github.com/github/rest-api-description)

Thank you for considering this improvement.

**Comment by mehrandvd** [comment]
In the current implementation, the `ValidPluginName` function performs two distinct validations:
1. It checks if the plugin name is valid.
2. It ensures that the plugin name is not a duplicate.

```csharp
internal static void ValidPluginName(...)
{
    NotNullOrWhiteSpace(pluginName);
    if (!s_asciiLettersDigitsUnderscoresRegex.IsMatch(pluginName))
    {
        ThrowArgumentInvalidName("plugin name", pluginName, paramName);
    }

    if (plugins is not null && plugins.Contains(pluginName))
    {
        throw new ArgumentException($"A plugin with the name '{pluginName}' already exists.");
    }
}
```

To improve readability and maintainability, I suggest splitting this into two separate methods:

```csharp 
ValidPluginName(string? pluginName)
{
  // ...
}
NotDuplicatedPlugin(string pluginName, IReadOnlyKernelPluginCollection plugins)
{
   // ..
}
```

Currently, when we want to validate a plugin, we're calling these validations in place:

```csharp
Verify.NotNull(kernel);
Verify.ValidPluginName(pluginName, kernel.Plugins);
```

This pattern is consistent across all usages of `Verify.ValidPluginName` (10 references).

![image](https://github.com/microsoft/semantic-kernel/assets/5070766/aea329fc-3b9c-4d52-9cc3-74b1812701d1)

To streamline this process, it would be beneficial to have a single method that performs all these validations:

```csharp
void ValidPlugin(string? pluginName, IReadOnlyKernelPluginCollection plugins)
{
  Verify.NotNull(kernel);
  Verify.ValidPluginName(pluginName);
  Verify.NotDuplicatedPlugin(pluginName, kernel.Plugins)
}
```

This approach not only simplifies the validation process but also enhances code readability and maintainability.

**Comment by mehrandvd** [comment]
I’m eager to take on this issue.
