### ISSUE TITLE
.Net: kernel.Plugins.GetFunctionsMetadata() not returning the expected plugins

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#4568]
**Describe the bug**
My latest question has to do with the response from kernel.Plugins.GetFunctionsMetadata() AfTER I have configured my kernele as follows. The API lists only functions of the TimePlugin, while it seems I am loading many other plugins and functions. Can you help?

```
    Dictionary<string, KernelPlugin> plugins = new Dictionary<string, KernelPlugin>();
    var pluginPath = Path.Combine(System.IO.Directory.GetCurrentDirectory(), "..", "Plugins");
    foreach (var plugin in new string[] { "WriterPlugin", "TranslatePlugin" })
    {
        Console.WriteLine($"Loading ${pluginPath}${plugin}");
        plugins.Add(plugin, kernel.CreatePluginFromPromptDirectory(Path.Combine(pluginPath, plugin)));
    }
    plugins.Add("EmailPlugin", kernel.CreatePluginFromType<EmailPlugin>());
    #pragma warning disable SKEXP0050
    kernel.ImportPluginFromType<TimePlugin>();    
    const string WeatherFunctionDef = @"
    Today is: {{time.Date}}
    If today is in the summer, Seattle weather is warm and balmy.
    If today is not in the summer, Seattle weather is cold and rainy.
    ";
    kernel.CreateFunctionFromPrompt(
        WeatherFunctionDef, 
        new OpenAIPromptExecutionSettings() { MaxTokens = 100 },
        functionName: "Weather",
        description: "Get Seattle weather forecast");
```

**Comment by stephentoub** [comment]
>  AfTER I have configured my kernele as follows.

The example code is adding a bunch of plugins to a dictionary that's then ignored.

It's also calling `kernel.CreateFunctionFromPrompt`, which creates the function but doesn't add it to the kernel.

The only line that's actually adding something to the kernel is `kernel.ImportPluginFromType<TimePlugin>();`, which is why it only lists the TimePlugin when asking for the metadata.

**Comment by mrochon** [comment]
Thanks. That solved a bunch of my problems (like; why was the plan not executing?). When would I use CreatePlugin APIs? (and feel free to close the issue).

**Comment by stephentoub** [comment]
> Thanks. That solved a bunch of my problems

Great. 

> When would I use CreatePlugin APIs?

If you didn't have a kernel yet, or if you were creating a plugin to add to many different kernels (eg adding the plugin to a DI container), or if you were creating a usable library that offered KernelPlugin instances someone could just add to their kernel, or other such things. The general pattern that's been established is there's a Create method that's the workhorse and just creates the thing, there's a corresponding Add method that uses Create and adds it to a plugin collection, and there's a corresponding Import that uses Create/Add to create the thing and bring it into the kernel (adding it to its plugin collection).

**Comment by stephentoub** [comment]
> feel free to close the issue

👍
