### ISSUE TITLE
.Net: ADR for AI connector support

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#4577]
The purpose of this task is to create an ADR to describe our AI Connector strategy and how new AI Connectors can be contributed.

Below are a series of user stories that must be addressed by the ADR.

### Strategy
As a developer using Semantic Kernel I can use AI Connectors that access LLM's deployed in the Cloud e.g. OpenAI, Azure OpenAI, Hugging Face, ... or deployed locally so that I can configure by application to use the optimum LLM or to run completely offline.

1. Our strategy should allow us to maximise the reuse of AI Connector implementations e.g. if we can configure the same connector to work with online and offline deployments that is a win.
1. Developers should be able to deploy and use local models easily.

### Contributing an AI Connector
As a contributor to Semantic Kernel I can read the documentation which describes how to contribute an AI connector so that I can understand the development process and requirements to have a new AI Connector included in a Semantic Kernel release

1. Describe how we successfully co-develop AI connectors with the community. 
1. We want to avoid receiving huge PR's that are very difficult to review.
1. We want to ensure each AI connector includes a defined level of unit tests and integration tests.

### P0 LLMs
1. Phi-2 (Microsoft)
1. Gemini (Google)
1. Llama + function calling (Facebook)
1. Claude (Anthropic)
1. Multi-modal models (e.g., Stable Diffusion)

### Deployment types
1. Azure AI
1. Hugging face
1. Local
    - [LM Studio - Discover, download, and run local LLMs](https://lmstudio.ai/)
    - Ollama
    - Pure C# (e.g., LlamaSharp or ONNX runtime)
1. Bedrock (Amazon)

**Comment by Krzysztof318** [comment]
So... If I understand correctly you prefer connector project per one model (or model faimily) (even if has multiple deployment types) than project per deployment (one project contains multiple models)?

**Comment by RogerBarreto** [comment]
As I understand is a Connector per platform/API definition, so a connector can support the same model on a specific platform. 
i.e:

```
LMStudio -> Phi-2
HuggingFace -> Phi-2
```

**Comment by Krzysztof318** [comment]
@RogerBarreto thanks for clarification I was wondering if the "googlevertexai connector" way is ok.

**Comment by RogerBarreto** [comment]
@Krzysztof318, will review your PR today and give you a better feedback, is a big one, this one may be graduated to a feature branch later on.

**Comment by Krzysztof318** [comment]
@RogerBarreto I would appreciate for dedicated branch, it will also be more convenient for me to maintain small PRs.
