### ISSUE TITLE
.Net 1.0.1: Cannot mock KernelFunction.InvokeAsync

### ISSUE THREAD

**Issue by jimmy-vo-librestream** [microsoft/semantic-kernel#4589]
### Discussed in https://github.com/microsoft/semantic-kernel/discussions/4575

<div type='discussions-op-text'>

<sup>Originally posted by **jimmy-vo-librestream** January 10, 2024</sup>
I am working on upgrading 1.0.0-beta8 to 1.0.1, and I found it is not possible to mock Kenel, Function, or Pluggin. For example I have an extension function that my business logic calling to:
```
    public static async Task<string> InvokePromptAsync(
        this Kernel kernel,
        KernelArguments variables,
        string template,
        OpenAIPromptExecutionSettings requestSettings,
        CancellationToken cancellationToken = default)
    {
        KernelFunction skFunction = kernel.CreateFunctionFromPrompt(template, requestSettings);
        var result = await kernel.InvokeAsync<string>(skFunction, variables, cancellationToken);
        return result!;
    }
```
In 1.0.0-beta8, I was able to mock `ISKFunction`, `IReadOnlyFunctionCollection`, and `IKernel`. But they are removed in 1.0.1. `KernelFunction` is now an abstract class with internal constructor, so there is no way I can create a `MockKernelFunction` that wraps KernelFunction and overrides `ValueTask<FunctionResult> InvokeCoreAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)`.

I am currious how you guys do it?
</div>
```[tasklist]
### Tasks
```

**Comment by markwallace-microsoft** [comment]
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionFromMethodTests1.cs
