### ISSUE TITLE
.Net Embeddings generation interface extend

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#4591]
The current IEmbeddingGeneration service lacks multimodal support.
And also methods in this interface should accept execution settings param like other interfaces.

**Comment by markwallace-microsoft** [comment]
@Krzysztof318 `IEmbeddingGenerationService` is currently experimental so we do plan to extend this.

Can you provide some more detail on your use case?

**Comment by Krzysztof318** [comment]
Hi @markwallace-microsoft 

As example I pick VertexAI embedding service. [LINK to multimodal embeddings](https://cloud.google.com/vertex-ai/docs/generative-ai/embeddings/get-multimodal-embeddings)
1. Interface method should allow passing optional execution settings as that is do in ITextGenerationService. For example textembedding-gecko has params about auto truncating to long data.
2. Interface method should return complex object with metadata similar as ITextGenerationService. Textembedding-gecko returns some statistics.
3. Interface should also allow passing complex object instead only text [LINK to example class in PR](https://github.com/microsoft/semantic-kernel/pull/4536/files#diff-8077a149657edbb0c14c498dea8f86d4982d3e2117775d33280b82fe564b985a). This will allow us to use embedding service with multi modal embedding models.

**Comment by guillaume86** [comment]
My use case is requesting different dimensions from OpenAI embeddings API, the ExecutionSettings pattern is a lot more flexible than declaring every case with different serviceIds up front.
