### ISSUE TITLE
.Net: How to force GPT to ask for parameter value before actually calling the function ?

### ISSUE THREAD

**Issue by nssidhu** [microsoft/semantic-kernel#4593]
I am using the below code which works perfectly if question has the parameter value, for example weather service.
but in case user does not provide the value for city, i want gpt should comback and ask for paramter value and then invoke it after getting value from user. How can i achieve that, what else need to be done with code below ?

var builder = Kernel.CreateBuilder( );
builder.Services.AddAzureOpenAIChatCompletion(aoaiModel, aoaiEndpoint, aoaiApiKey);
builder.Plugins.AddFromType<DateTimePlugin>();
builder.Plugins.AddFromType<WeatherPlugin>();
kernel = builder.Build();
var chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();
OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
{
    ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions
};
var chatResult = chatCompletionService.GetStreamingChatMessageContentsAsync(
    history,
    executionSettings: openAIPromptExecutionSettings,
    kernel: kernel);

=====================================================================================

**Comment by markwallace-microsoft** [comment]
@nssidhu Can you verify this is your scenario?

1. You are using a plugin 
     1. The first plugin function can prompt the user for some input
     2. The second plugin function will perform an action but requires the user input
3. You invoke the AI with a question which will cause the AI 
     1. Invoke the first plugin function to get the user input
     2. Invoke the second plugin function and pass in the user input
     3. Return the response returned from the second function

Thanks.

**Comment by nssidhu** [comment]
That would be hardwiring things. I have seen those sample, the ask here is different.
I was relying on AutoInvoke, so expectation was that Chapt would determine that plugin/function requires a city name and user has not provided, so chatGPT should ask for the city name and once user provide that it should continue with execution.

**Comment by deepinderdeol** [comment]
I think I had read somewhere in SK documentation a while ago that parameter description should say that it is required - however, I have not seen this work ever with SK. LLM never asks for missing information.

Before trying SK I had also experimented with Azure OpenAI.NET and there in the function-definition you could specify the required parameters. This worked well and the LLM would ask the user for missing parameters before executing a function/tool.
Here is an example that shows this - see how **getWeatherTool** is defined and **location** is a required parameter.
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/tests/Samples/ChatTools.cs
