### ISSUE TITLE
VSCode Extension: Allow selecting OpenAI Base URL to allow custom endpoint provides (vLLM, llama.cpp, LM Studio)

### ISSUE THREAD

**Issue by septagram** [microsoft/semantic-kernel#4601]
Please allow specifying a different OpenAI base URL in the AI Endpoints panel in the extension, without or along with the OpenAI API key. When using open source models, serving endpoints with e.g., vLLM, the models can often be expected to behave differently than the OpenAI models and require a bit of prompt engineering for best results.

The difference with #4152 in that this is a specific request for the VSCode extension.

**Comment by markwallace-microsoft** [comment]
@septagram We currently don't have any plans to update the VSCode extension but if we can look at this request.
