### ISSUE TITLE
Python: Context Result is the same for multiple inquiries.

### ISSUE THREAD

**Issue by HuskyDanny** [microsoft/semantic-kernel#4606]
**Describe the bug**
I am running 4 inquiries to get llm response by asyncio.gather(). And output the response into a dataset for RAGAS evaluation.

But the results are all the same from Context.Result. But the propmt and the response is matched when debugging into each pair. And you can see the 'context' and 'query' from the result is consistent, but the 'answer' which is SKContext is always pointing to one of the response.
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/5c2361e1-3d74-49b3-9ad3-5a3866f23bab)

Notes : 0,1,2 corresponds to {'answer':response.result, 'context':combined_documents, 'question':query} from invoke_rag()

**To Reproduce**

Please ignore the collection, and get_docs() function which is used for vector search.
```
from config import kernel
from prompts import query_expansion_function, chat_function
from semantic_kernel.orchestration.context_variables import ContextVariables

async def invoke_rag(query : str, collection : str):
    context = kernel.create_new_context(ContextVariables(query))
    context["chat_history"] = " "

    await query_expansion_function.invoke_async(context=context)

    docs = get_docs(query=context.result, original_query=query, collection=collection)
    combined_documents = combine_documents(docs)

    context['context'] = combined_documents

    response = await kernel.run_async(chat_function, input_context=context)

    return {'answer':response.result, 'context':combined_documents, 'question':query}
    
 async def invoke_rag_async(query, collection):
  try:
      result = await invoke_rag(query=query, collection=collection)
      return result['answer'], result['context'].split('&&&'), result['question'], None
  except Exception as e:
      return None, None, None, e

async def prepare_dataset():
   questions = ["How to get the row count of a column?", 
             "What is retention, and how to use it in clickhouse",
             "How to write a subquery",
             "How to calculate the number of values of the argument with the best performance?"]
   collection = "clickhouse_sql_reference_docs_3000chunk200overlapp"
    tasks = []
    for i in range(len(questions)):
        question = questions[i]
        tasks.append(invoke_rag_async(query=question, collection=collection))

    # Run all tasks concurrently
    results = await asyncio.gather(*tasks)
    return results

results = asyncio.run(prepare_dataset())
```

**Expected behavior**
Each question should match to its answer, not all questions match to the same answer.

**Screenshots**

**Platform**
 - Language: python
 - Source: semantic-kernel==0.4.5.dev0
**Additional context**

**Comment by moonbox3** [comment]
Hi @HuskyDanny, similar to my previous message, as we move to v1.0.0, we have made a lot of changes to the code. We've removed the context in favor of kernel arguments. Please try the latest code and if you exprience an issue, file a new issue. Thank you.
