### ISSUE TITLE
.Net: Providing alternate HttpClient parameter to WithAzureOpenAITextEmbeddingGeneration does not work

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/semantic-kernel#4608]
https://github.com/microsoft/semantic-kernel/blob/9b45e609eb10bde6e0c23c85488cd4c5c2f53ce8/dotnet/src/Connectors/Connectors.OpenAI/OpenAIMemoryBuilderExtensions.cs#L28-L44

The `httpClient` parameter passed has the same name as the lambda parameter and therefore gets ignored.  The two HttpClient parameters need to have different names and then get coalesced.

The workaround is to use WithHttpClient prior to calling WithAzureOpenAITextEmbeddingGeneration.

**Comment by SergeyMenshykh** [comment]
The issue has been fixed - https://github.com/microsoft/semantic-kernel/pull/4609
