### ISSUE TITLE
.Net: C# InvokeStreamingAsync doesn't behave as expected

### ISSUE THREAD

**Issue by santanor** [microsoft/semantic-kernel#4627]
**Describe the bug**
I was following [Example67_KernelStreaming](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example67_KernelStreaming.cs) and I noticed `InvokeStreamingAsync` doesn't behave as expected. At least for me. 

**To Reproduce**
I have a prompt that takes around 10s to complete. The prompt has 2 native functions embedded in the `skprompt.txt` that take around `0.3s` each to complete. I mention this in case you find it helpful.

I then created a Kernel and called it twice, once with `InvokeAsync` and another one with `InvokeStreamingAsync` 

``` C#

var result = await agent.Kernel.InvokeAsync(PromptFolder, ChatFunction, args);

// It takes around 10 seconds to get here. All good, that's how long the prompt takes. 
var resultValue = result.GetValue<string>();

```

``` C# 
await foreach (var update in agent.Kernel.InvokeStreamingAsync<string>(PromptFolder, ChatFunction, args))
{
     // I would expect to start hitting this point soon after the kernel is launched. However it takes 
     // as long as without streaming to get here.
     yield return update;
 }
```

**Expected behavior**
I would expect the second snippet to start yielding updates pretty much immediately. Instead it takes around 10s to start yielding and when it does it blurts our the entire response in a quick loop. 

It doesn't yield everything in one iteration, I checked. 

**Platform**
 - OS: Mac
 - IDE: Rider
 - Language: C#
 - Source: NuGet package version 1.0.1. Also tested on 1.1.0
 - Model: GPT4

**Comment by Krzysztof318** [comment]
Hi, try chec again on latest SK release 1.1
Could you show your skprompt content?

**Comment by santanor** [comment]
Hi @Krzysztof318 

Same behaviour on 1.1. I'm using GPT4. I've tried with `0613` and `1106-preview`.

I can show a bit of the prompt, but I'll remove some things that identify the customer if that's ok with you. Those bits are just text, so it shouldn't affect the prompt too much. 

***I'm also including comments with `//` to explain what certain things do. `//` comments aren't included in the prompt when it runs*** 


```
Some lengthy description that tells the agent how to behave

You can use the following questions and answers as an example on how to answer questions. They provide with guidance as to how to answer questions and the tone of the answers.

Sample questions and answers:

// This is a native function that uses AzureAISearchMemoryStore to RAG 5 examples. This completes in around 0.3s
{{ qna.RetrieveQnA question=$input numQuestions="5"}}



This is the chat history between you and the user:

// This native function retrieves the chat history from a Cosmos. It also completes in 0.4s
{{ history.RetrieveChat $sessionId}}

// This is just the text input from the user
{{$input}} 

Your response should be the next message in the conversation. Only include one message. Avoid including JSON in your response. 

```

It's also worth mentioning that the Kernel has been configured to make use of a `DataSource`, in case that affects it in any way. 

``` C#
var config = new AzureOpenAIChatCompletionWithDataConfig()
{
       CompletionEndpoint = openAiConf["Endpoint"],
       CompletionApiKey = openAiConf["Key"],
       CompletionApiVersion = openAiConf["ApiVersion"],
       CompletionModelId = openAiConf["Deployment"],
       DataSourceEndpoint = dataSourceConf["Endpoint"],
       DataSourceIndex = dataSourceConf["IndexName"],
       DataSourceApiKey = dataSourceConf["Key"]
};

// This is the logger provider that comes from the API app. It'd be nice to use it to log the kernel
var existingLoggerProvider = _serviceProvider.GetRequiredService<ILoggerProvider>();

var kernelBuilder = Kernel.CreateBuilder();
kernelBuilder.Services
    .AddAzureOpenAIChatCompletion(config:config)
    .AddLogging(c => c.AddProvider(existingLoggerProvider))
    .AddAzureOpenAITextEmbeddingGeneration(openAiConf["Embeddings"], openAiConf["Endpoint"], openAiConf["Key"]);
        
Kernel = kernelBuilder.Build();
```

**Comment by Krzysztof318** [comment]
Maybe any proxy issue like here [LINK](https://stackoverflow.com/questions/68193327/c-sharp-httpclient-getasync-ignore-httpcompletionoption-responseheadersread)

**Comment by santanor** [comment]
M... that doesn't seem to be it :( I tried with a local version and a deployed version (AppService)

**Comment by Krzysztof318** [comment]
Have you resolved this problem?

**Comment by santanor** [comment]
Let's close it for now, I still see a difference between doing a request to AOAI in stream mode and through SK. But I don't have enough information to argue against closing the issue.
