### ISSUE TITLE
Python: Refactor prompt_template and prompt_template_config to match dotnet

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4630]
In the .NET SDK, the classes required to use semantic functions were all refactored to simplify the creation of them. During this change, semantic functions were also renamed to "prompts."

This issue is to complete the rename and to re-align the classes with those that are found in .NET.

**Comment by eavanvalkenburg** [comment]
This can be commenced once the first working version of KernelArguments is in the feature branch for that.
