### ISSUE TITLE
Python: Add AI service selector to Python

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4631]
In the .NET SDK, an AI Service Selector was added so that a prompt template could be resolved to the correct model (in case there are multiple).

This issue should track the following work:
- Introduce the AI Service Selector class
- Provide a default implementation of the AI Service Selector (replicate the same logic as the .NET version)
- Allow users to register custom service selectors on the kernel

**Comment by eavanvalkenburg** [comment]
This can be commenced once the first version of KernelArguments is in the feature branch

**Comment by eavanvalkenburg** [comment]
@matthewbolanos this will be in the beta, you can move it up.
