### ISSUE TITLE
Python: Unify code paths for prompt (semantic function) and native functions

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4633]
In .NET, prompts and native functions use the same underlying KernelFunction class to ensure they behave the same. This issue is to replicate this. If there aren't any functional changes because of this issue (i.e., the interface stays the same), then this issue should be ranked lower.

**Comment by moonbox3** [comment]
This work will be done as part of #4667. Closing this issue.

**Comment by moonbox3** [comment]
Breaking this out into a separate item again, to try and avoid a giant PR with the Plugin/PluginCollection work.
