### ISSUE TITLE
Python: Provide support for YAML serialization of prompts (combine config.json and skprompt.txt)

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4640]

**Comment by eavanvalkenburg** [comment]
This can be commenced once the first version of KernelArguments is in the feature branch #4565

**Comment by jeffrey-m-johnson** [comment]
I'd be interested in taking a shot at this one.

**Comment by matthewbolanos** [comment]
@jeffrey-m-johnson, can you reach out either @eavanvalkenburg (EU time zone) or @moonbox3 (EST time zone)? One or both of them can help you get started on this feature!

**Comment by jeffrey-m-johnson** [comment]
I'm CST, so I think I'll chat with @moonbox3 first

**Comment by eavanvalkenburg** [comment]
How is this one going @jeffrey-m-johnson ?
