### ISSUE TITLE
Python: planner using Huggingface

### ISSUE THREAD

**Issue by RvTechiNNovate** [microsoft/semantic-kernel#4652]
**Describe **
i am trying to use planner using hugging face model like zypher_7b , but i am getting below error

**Error**
Error: ('Hugging Face completion failed', TypeError("Pipeline.__call__() missing 1 required positional argument: 'inputs'"), None)

**Code**
import regex
from semantic_kernel.planning.basic_planner import BasicPlanner
from semantic_kernel.connectors.ai.hugging_face import HuggingFaceTextCompletion
import semantic_kernel as sk
import asyncio
print("check1")

kernel = sk.Kernel()

model_name='NousResearch/Llama-2-70b-chat-hf'

huggingface=HuggingFaceTextCompletion(model_name)

print("model-loaded")

kernel.add_chat_service("huggingface",huggingface)
kernel.import_skill(sk.core_skills.MathSkill(), 'math')

planner = BasicPlanner()

ask = f"""what is the sum of 1 and 3?"""

async def fun():
    plan= await planner.create_plan_async(ask,kernel)
    print(plan.generated_plan)
    
    result= await planner.execute_plan_async(plan, kernel)
    print(result)

asyncio.run(fun())

**Platform**
 - OS: Linux
 - Language: Python]

**Additional context**
In Open Ai  working prefect , but in huggingFace it giving error

**Comment by chinchaun** [comment]
I found the same error trying to run 07-hugging-face-for-plugins.ipynb

```
Something went wrong in pipeline step 0. During function invocation: 'p_EQWgyNSJrxWKuviY.f_mBBXxDzLLiXDsaRx'.
Error description: '('Hugging Face completion failed',
TypeError("TextGenerationPipeline.__call__() missing 1 required positional argument: 'text_inputs'"), None)'
gpt2 completed prompt with: 'Error: ('Hugging Face completion failed',
TypeError("TextGenerationPipeline.__call__() missing 1 required positional argument: 'text_inputs'"), None)'
```

When debugging what's going on this is where is breaking
when this function is invoked `output = await kernel.run(my_function, input_vars=context.variables)`

it breaks in this line of code `context = await func.invoke(input=None, context=context, **kwargs)`

**Comment by eavanvalkenburg** [comment]
@RvTechiNNovate @chinchaun I noticed from both your logs that there are different expected inputs for different model types, the one we currently use is text_inputs and apparently some use inputs instead. I'm now testing a fix. One other note, currently we don't support ChatModels from Hugging Face, so this line `kernel.add_chat_service("huggingface",huggingface)` should change to `kernel.add_text_completion_service("huggingface",huggingface)`. However we don't have good testing for HF, so I'm seeing if I can add some of that.
