### ISSUE TITLE
Python: Clarification about `get_request_settings_class`

### ISSUE THREAD

**Issue by bastbu** [microsoft/semantic-kernel#4654]
**Describe the bug**

With the upgrade of SK Python `0.4.4.dev` there was a breaking change to our custom implementation of `TextCompletionClientBase`. Whereas the `TextCompletionClientBase` does not contain an abstract method `get_request_settings_class`, creating a semantic function with the custom text completion is not possible without defining that function.

I could not find documentation around the expectation for defining this function.

**To Reproduce**

Running the following code will produce an error (`'CustomTextCompletion' object has no attribute 'get_request_settings_class'`):

```py
from typing import Any, AsyncGenerator, List, Optional, Union
from semantic_kernel.connectors.ai.open_ai.request_settings.open_ai_request_settings import (
    OpenAIRequestSettings,
)
from semantic_kernel.connectors.ai.text_completion_client_base import (
    TextCompletionClientBase,
)
from semantic_kernel.connectors.ai.open_ai.services.azure_text_completion import AzureTextCompletion
import semantic_kernel as sk


class CustomTextCompletion(TextCompletionClientBase):
    def __init__(self) -> None:
        self.inner = AzureTextCompletion(base_url="<redacted>", api_key="<redacted>", deployment_name="<redacted>")

    async def complete_async(self, prompt: str, settings: OpenAIRequestSettings, logger: Optional[Any] = None) -> Union[str, List[str]]:
        return await self.inner.complete_async(prompt=prompt, settings=settings, logger=logger)

    async def complete_stream_async(self, prompt: str, settings: OpenAIRequestSettings, logger: Optional[Any] = None) -> AsyncGenerator[Union[str, List[str]], None]:
        return self.inner.complete_stream_async(prompt=prompt, settings=settings, logger=logger)

kernel = sk.Kernel()
kernel.add_text_completion_service(service_id="default", service=CustomTextCompletion())

prompt_config = sk.PromptTemplateConfig()
prompt_template = sk.PromptTemplate("{{$input}}", kernel.prompt_template_engine, prompt_config)
function_config = sk.SemanticFunctionConfig(prompt_config, prompt_template)
function = kernel.register_semantic_function("default", "default", function_config)
```

Adding an implementation for `def get_request_settings_class(self) -> type[AIRequestSettings]` to the class addresses the issue.

**Expected behavior**

This does not throw an error, as in `v0.4.3.dev`. As an alternative, it would be great to have some documentation on what changes are required for implementing a custom text (or chat) completion client. Specifically, this would be about documenting the requirements for adding an implementation for `get_request_settings_class(self) -> type[AIRequestSettings]`.

**Platform**
 - OS: WSL2 on Windows 11
 - IDE: VS Code
 - Language: Python
 - Source: pip, `v0.4.4.dev`

**Comment by eavanvalkenburg** [comment]
Thanks for reaching out, we have been making a lot of changes as we move towards v1. This one is indeed expected in each service because we now parse whatever settings are being passed to the right class by calling this function and then taking AIRequestSettings object and passing that to the specific class for your service. Of course when that is already the right class it should that step. In one of the py samples this is explained as well, but do let me know if you need additional help on this.

**Comment by bastbu** [comment]
Thanks for the clarification. When I looked through the samples (also by doing a full-text search) I did not find one that mentions `get_request_settings_class`. Could you link the mentioned example for future reference?

If implementing `get_request_settings_class` is now required, should it be part of the `TextCompletionClientBase` abstract base class to indicate that this implementation is required?

**Comment by eavanvalkenburg** [comment]
This sample uses it directly: https://github.com/microsoft/semantic-kernel/blob/de9b8d87040febb45bcd445cbcee03fde2e4df37/python/samples/kernel-syntax-examples/azure_chat_gpt_api.py#L42 and it is part of the AIServiceClientBase class (https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/connectors/ai/ai_service_client_base.py), which underpins all service types, the TextCompletionClientBase acts more like a mixin, thanks for raising this, I will have a look to see how we can clarify the setup, naming and documentation for this! The AIServiceClientBase also has a field for the ai_model_id which will become more important as we start adding pieces service selector methods, which will use/expect that field to be present.
