### ISSUE TITLE
.Net: Specify clearly what parameters OpenAIClient accepts

### ISSUE THREAD

**Issue by Alerinos** [microsoft/semantic-kernel#4656]
according to the "documentation" to use open AI api we need to use TOKEN.DOMAIN, this is misleading because the token itself is enough.

https://github.com/Azure/azure-sdk-for-net/tree/Azure.AI.OpenAI_1.0.0-beta.9/sdk/openai/Azure.AI.OpenAI#key-concepts

In my opinion there should be two separate classes that define what they are, open AI only accepts the token and Azure URI.

I lost two hours before I realized that the documentation is misleading. Below is the thread where I struggled with the problem. Unfortunately, it is very poorly described and I had to arrive at the problem by trial and error methods.

(https://github.com/microsoft/semantic-kernel/issues/4594)

**Comment by markwallace-microsoft** [comment]
@Alerinos can you please open this issue here https://github.com/Azure/azure-sdk-for-net/issues as it needs to be handled by the Azure.AI.OpenAI team. Thanks.
