### ISSUE TITLE
Python: `Plan.describe()` raises an error if `function` param in the __init__ is `None`

### ISSUE THREAD

**Issue by nikdon** [microsoft/semantic-kernel#4658]
**Describe the bug**

`semantic_kernel.planning.plan.Plan.describe` function raises an error if protected field `_function` is `None`. It is due to the missed check in the function before calling `self._fucntion.describe()`. A `None` check is implemented for other functions where `_function` is used, but not here.

**To Reproduce**

```python
from semantic_kernel.planning import Plan


plan = Plan(name="test")
assert plan._function is None
description = plan.describe()  # raises AttributeError: 'NoneType' object has no attribute 'describe'
```

**Expected behavior**

There should be a check if `self._function` is None and an appropriate handler for this case.

As an additional thing, `__init__` can be changed as well

```python
class Plan(SKFunctionBase):
...
    def __init__(
        ...
        function: Optional[SKFunctionBase] = None,
    ):
        self._function = None if function is None else function  # => self._function = function
```

**Platform**
 - Language: Python
 - Source: pip, v0.4.5.dev0

**Comment by nikdon** [comment]
Related to #4587

**Comment by moonbox3** [comment]
Thanks for reporting the issue @nikdon. Would you like to create a PR with this fix? Thanks for your help!
