### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by micuentadecasa** [microsoft/semantic-kernel#466]
I would like to have a Docker version of the semantic-kernel, in this way it can be integrated with other dockers to create complex solutions, i.e. mixing it with a docker of redis for embedding knowledge, with a docker of MySql, etc.

It will be great if it is based on Ubuntu, or any other Linux variant.

Regards.

**Comment by evchaki** [comment]
@micuentadecasa , good suggestion. Please create a PR with a Docker file and we will check it out.

**Comment by evchaki** [comment]
Closing this for now.  Translated to backlog item.
