### ISSUE TITLE
.Net: Plugin function inspection combines class details instead of isolating interface details.

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/semantic-kernel#4668]
**Describe the bug**
A class inherits from both `Interface1` and `Interface2`. In the `ImportPluginFromObject` method, when I pass an `Interface1` object to the function and inspect the plugin functions, I observe that it includes details from both interfaces.

**To Reproduce**
Follow the steps

**Define the plugins** 

<img width="653" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/16264167/2a4c9553-2fb3-485d-aa87-829a69d54e52">

**ImportPluginFromObject**

<img width="583" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/16264167/05d7780f-0086-4b06-aa96-997d0fbd984a">

**Expected behavior**

Import only Interface1 Objects in the Plugin Function Inspection

**Platform**
 - OS: Windows 1
 - IDE: Visual Studio
 - Language: C#
 - Source:  <PackageReference Include="Microsoft.SemanticKernel" Version="1.0.1" />

**Comment by stephentoub** [comment]
ImportPluginFromObject uses all public methods on the object, regardless of what interfaces those methods may also satisfy.

**Comment by rvinothrajendran** [comment]
While it may make sense from a plugin perspective, as a developer using the API, it can be quite confusing. It might be clearer not to allow objects created by the interface and perhaps throw an exception in such cases.

**Comment by rvinothrajendran** [comment]
Certainly, I grasp the concept behind the functions, and it's a sound recommendation to establish a new API for interface support. In the interim, I've generated a community NuGet package to aid in implementing "ImportPluginFromInterface."
https://www.nuget.org/packages/AzureAI.Community.Microsoft.Semantic.Kernel.PlugIn.Interface 😎
