### ISSUE TITLE
0.12 nuget version

### ISSUE THREAD

**Issue by Woland2k** [microsoft/semantic-kernel#467]
Love the work on reducing dependency requirements, that forced us to fork and recompile libraries ourselves and with this update we can revert back to using standard nugets. The problem is that they're not released yet. So the question is when do we expect release of nuget 0.12 packages?

**Comment by evchaki** [comment]
@Woland2k , thanks for bringing this up, we will have a new package later today.

**Comment by Woland2k** [comment]
@evchaki thank you for the update!

**Comment by Woland2k** [comment]
Everything works as expected, great job making the changes!
