### ISSUE TITLE
Prompt templates : Create a liquid template renderer (alternative to handlebars)

### ISSUE THREAD

**Issue by giannik** [microsoft/semantic-kernel#4670]
Im trying to introduce i liquid renderer  by following the handlebars template renderer 
so i create an implementation of IPromptTemplateFactory  and IPromptTemplate
In the LiquidPromptTemplateFactory i need to inject another service that is passed  to LiquidPromptTemplate to handle the rendering 
```
public class LiquidPromptTemplateFactory: IPromptTemplateFactory
{
    private readonly ILiquidTemplateManager _liquidTemplateManager;

    public LiquidPromptTemplateFactory(ILiquidTemplateManager liquidTemplateManager)
    {
        _liquidTemplateManager = liquidTemplateManager;
    }
    public static string LiquidTemplateFormat => "liquid";
    public bool TryCreate(PromptTemplateConfig templateConfig, [UnscopedRef] out IPromptTemplate result)
    {
        if (templateConfig.TemplateFormat.Equals(LiquidTemplateFormat, System.StringComparison.Ordinal))
        {
            result = new LiquidPromptTemplate(templateConfig,_liquidTemplateManager) ;
            return true;
        }

        result = null;
        return false;
    }
}
```

I am also registering this on startup so DI can picke it and properly resolve 

```
  services.AddScoped<IPromptTemplateFactory, LiquidPromptTemplateFactory>();
```
Is this approach correct ?

I could'nt find in the SK code DI registration for the other  IPromptTemplateFactory's (KernelPromptTemplateFactory, HandlebarsPromptTemplateFactory)
 
so Im wondering if im doing it correctly .
Also can you please tell me anything else needed for this to work ?
Thank you

**Comment by markwallace-microsoft** [comment]
@giannik You don't need to register the template factory with the kernel to use it but that might be an interesting extension for us to consider.

But for now you can explicitly pass this as a parameter when creating the function

```
        var function = kernel.CreateFunctionFromPrompt(
            promptConfig: new PromptTemplateConfig()
            {
                Template = prompt,
                TemplateFormat = templateFormat,
                Name = "MyFunction",
            },
            promptTemplateFactory: promptTemplateFactory
        );
```

Here's a full sample showing how to do this: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example64_MultiplePromptTemplates.cs

**Comment by giannik** [comment]
thanks @markwallace-microsoft
