### ISSUE TITLE
Python: URL Validation AzureChatCompletion/Semantic Kernel

### ISSUE THREAD

**Issue by ShuaibAhmadShuaib** [microsoft/semantic-kernel#4675]
I am experiencing url validation issue while using AzureChatCompletion/Semantic Kernal . Details are below down.

Name: semantic-kernel
Version: 0.4.5.dev0

api_key="************"
endpoint="https://myopenai321.openai.azure.com/"
deployment_name="gtp-35-turbo"
kernel = sk.Kernel()
kernel.add_chat_service("aiiva-chat", AzureChatCompletion(deployment_name,endpoint, api_key))

{
"name": "ValidationError",
"message": "1 validation error for url
Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='*********', input_type=str]
For further information visit https://errors.pydantic.dev/2.5/v/url_parsing",
"stack": "---------------------------------------------------------------------------
ValidationError Traceback (most recent call last)
Cell In[10], line 9
6 deployment_name="gtp-35-turbo"
8 kernel = sk.Kernel()
----> 9 kernel.add_chat_service("aiiva-chat", AzureChatCompletion(deployment_name,endpoint, api_key))

File c:\Users\DS198QF\AppData\Local\Programs\Python\Python310\lib\site-packages\semantic_kernel\connectors\ai\open_ai\services\azure_chat_completion.py:241, in AzureChatCompletion.init(self, deployment_name, endpoint, base_url, api_version, api_key, ad_token, ad_token_provider, default_headers, async_client, use_extensions, log, **kwargs)
238 logger.warning("The 'logger' argument is deprecated. Please use the logging module instead.")
240 if base_url and isinstance(base_url, str):
--> 241 base_url = HttpsUrl(base_url)
242 if use_extensions and endpoint and deployment_name:
243 base_url = HttpsUrl(f"{str(endpoint).rstrip('/')}/openai/deployments/{deployment_name}/extensions")

File c:\Users\DS198QF\AppData\Local\Programs\Python\Python310\lib\typing.py:957, in _BaseGenericAlias.call(self, *args, **kwargs)
954 if not self._inst:
955 raise TypeError(f"Type {self._name} cannot be instantiated; "
956 f"use {self.origin.name}() instead")
--> 957 result = self.origin(*args, **kwargs)
958 try:
959 result.orig_class = self

ValidationError: 1 validation error for url
Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='*******************', input_type=str]
For further information visit https://errors.pydantic.dev/2.5/v/url_parsing"
}

**Comment by eavanvalkenburg** [comment]
Hi @ShuaibAhmadShuaib thanks for checking here, the first thing I notice is that you do not use keywords for the arguments for the AzureChatCompletion class, that one has multiple ways of instantiating (endpoint, base_url, with_extensions, openaiClient) so it not expects that, I think that might fix your issue as well, since the right things are validated then.

**Comment by moonbox3** [comment]
Closing this item as it's related to keyword arg usage.
