### ISSUE TITLE
.Net Microsoft.SemanticKernel.HttpOperationException:  "Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'. 

### ISSUE THREAD

**Issue by TRybina132** [microsoft/semantic-kernel#4679]
**Describe the bug**
I'm using IChatComplitionService with Azure OpenAI gpt-35-turbo-16k 0613 model. When user asked for something that requires calling function of plugin, it will respond as expected. But after this response when `IChatComplitionService.GetStreamingChatMessageContentsAsync` called next time, this exception will be thrown:
```csharp
Microsoft.SemanticKernel.HttpOperationException: Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'.
Status: 400 (model_error)

Content:
{
  "error": {
    "message": "Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'.",
    "type": "invalid_request_error",
    "param": "messages.[10].role",
    "code": null
  }
}

```

**To Reproduce**
1. Add any plugin to kernel
2. Get IChatComplitionService  from kernel instance
3. Call `IChatComplitionService.GetStreamingChatMessageContentsAsync` or `GetChatMessageContentAsync` method with user message that will require executing plugin method.
4. Response is received
5. Repeat step 3
6. Exception is thrown

Here is how it done in my code:
```csharp
_chatHistory.AddUserMessage("Write email to test@gmail.com");
// Response is returned
 var chatCompletionResult =
            _chat.GetChatMessageContentAsync(_chatHistory, _promptExecutionSettings, Kernel);

_chatHistory.AddUserMessage("Write email to test@gmail.com");
// Exception is thrown
 var chatCompletionResult2 =
            _chat.GetChatMessageContentAsync(_chatHistory, _promptExecutionSettings, Kernel);
```

**Expected behavior**
Chat response generating without thrown exception

**Platform**
 - OS: Windows, Mac
 - Language: C#
 - Source: Microsoft.SemanticKernel 1.1.0
 
**Additional context**
It seems that messages with role `AuthorRole.Tool` in chat history cause this problem. As temporary solution I just deleting all messages with `AuthorRole.Tool` role from chat history before generating response. After deleting messages no exception.
```csharp
var toolsMessages = _chatHistory.Where(m => m.Role == AuthorRole.Tool).ToList();
        foreach (var m in toolsMessages)
        {
            _chatHistory.Remove(m);
        }
```

There was similar bug like in this issue https://github.com/microsoft/semantic-kernel/issues/4556#issuecomment-1897844440

**Comment by matthewbolanos** [comment]
Can you confirm if you are using auto function calling? Or are you manually calling the functions?

**Comment by TRybina132** [comment]
> Can you confirm if you are using auto function calling? Or are you manually calling the functions? I'm interested in knowing what code path you are using to generate the chat history since it looks like it's not being created correctly.

Yes, I'm using auto function calling. And I initialize chat history like this `_chatHistory = new ChatHistory();`

**Comment by rliberoff** [comment]
We are having the same problem with the `FunctionCallingStepwisePlanner`.

The error says:

```json
Microsoft.SemanticKernel.HttpOperationException: 'An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_0F3u0c9PktCz3RRDtF9hqnh9
Status: 400 (model_error)
```

The planner configuration is:

```csharp
var plannerConfig = new FunctionCallingStepwisePlannerOptions
{
    MaxTokens = options.PlannerMaxTokens,
    MaxIterations = options.PlannerMaxIterations,
    SemanticMemoryConfig = new SemanticMemoryConfig
    {
        Memory = memory,
    },
    ExecutionSettings = new OpenAIPromptExecutionSettings
    {
        User = request.UserId,
    },
};
```

The model we are using is GPT-3.5-1106

Thank you.

**Comment by tdashworth** [comment]
I am experiencing the same issue with Azure Open AI (GPT-4), auto function calling although I am persisting the `ChatHistory` in Cosmos DB after each generation and rebuilding next user prompt. 

I'm using version 1.5.0.
