### ISSUE TITLE
.Net: Runtime error when using SK with InProcess Function App System.Text.Json Assembly not found.

### ISSUE THREAD

**Issue by Rickcau** [microsoft/semantic-kernel#4690]
**Describe the bug**
Create an InProcess Azure Function App based on .NET 6.0 LTS.  Make sure you are using dependency injection, which means you will have a startup.cs file (it can be very basic).  Build the solution and run it in debug mode to make sure it runs without issue.  Now, simply add the SK Packaging via NuGet Package manager.  You can use version 8.0.0 or 8.0.1 the issue exists with both.  Now, start the solution in Debug mode.  You will now get the following error messages:

Error configuring services in an external startup class.
[2024-01-21T19:42:12.601Z] Error configuring services in an external startup class. api-transcriptservice: Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
[2024-01-21T19:42:12.651Z] A host error has occurred during startup operation 'd8297326-2e1e-4c92-87ee-1de883d6d8d9'.
[2024-01-21T19:42:12.651Z] Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. api-transcriptservice: Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')

If you manually add the System.Text.Json assembly and recompile the error persists.  I need the ability to use the SK from an InProcess Azure Function.  My testing works fine from a console app. 

**To Reproduce**
1. Create a .NET 6.0 InProcess Azure Function that uses Dependency Injection.
2. Run and test it to make sure it's working as expected
3. Now, simply added the Semantic Kernel NuGet Package and compile and run again.
4. See error above.

**Expected behavior**
I expect it to compile and run without any errors, specifically since I am not doing anything with the SK yet.  Also, this works fine from a console app.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/17052492/c971768b-4d59-409f-8e18-90280706c403)

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio Community Edition
 - Language: C#
 - Source: Semantic Kernel 8.0.0 or 8.0.1

**Additional context**
If I manually install the System.Text.Json assembly I'd expect this runtime error to be fixed.  It appears that the assembly needs to be copied to the bin folder, but since I am using .NET 6.0 System.Text.Json is built into the .NET 6.0 so there is no need to copy that file to the runtime directory.

**Comment by stephentoub** [comment]
Yes, SK depends on the System.Text.Json 8.0.0 version of the nuget package, and the in-proc Azure Functions model (which is no longer recommended) requires the 6.0 version. The out-of-proc model should work fine.

https://azure.microsoft.com/en-us/updates/ga-azure-functions-supports-net-8-in-the-isolated-worker-model/

cc: @paulyuk

**Comment by markwallace-microsoft** [comment]
Hi @Rickcau, thanks for creating the issue. Based on Stephens response we aren't planning to make any changes, can we close this?
