### ISSUE TITLE
.Net: Function calling failing with 1106 (GTP 4 or 3.5) in some regions - API requests/response 

### ISSUE THREAD

**Issue by frbar** [microsoft/semantic-kernel#4694]
**Describe the bug**
Function calling is not working anymore.

```
{
  "error": {
    "message": "Invalid value for 'content': expected a string, got null.",
    "type": "invalid_request_error",
    "param": "messages.[2].content",
    "code": null
  }
}
```

**To Reproduce**
It fails just with basic function calling (not using any planner).

**Screenshots**

**Platform**
 - OS: Windows 10
 - IDE: Visual Studio
 - Language: C#
 - Source: 1.0.1 (nuget)

**Additional context**
LLM: Azure OpenAI 
Version: GPT-4-Turbo-Preview 1106 / GPT-3.5-Turbo 1106
Region: UK South

**Analysis**

Doesn't seem to be a Semantic Kernel issue, however I post here for visibility as I see what I think are many related issues.

It works if I intercept the request/response (using a custom HttpClient) and convert the payload to a deprecated contract.

Ex:

Request

![image](https://github.com/microsoft/semantic-kernel/assets/16399900/99f88dd1-f8bf-4b08-ae06-c42c1ec68206)

Response

![image](https://github.com/microsoft/semantic-kernel/assets/16399900/e49550b6-c2ed-48bd-8580-0c18fcc4cd93)

If Semantic Kernel is doing additional calls, then more changes have to be performed on the request and response. I can add details if needed.

**Comment by Krzysztof318** [comment]
Hi, this issue is known already. https://github.com/microsoft/semantic-kernel/issues/4556

**Comment by frbar** [comment]
With Semantic Kernel .NET 1.1.0 and without the fix, nothing happens (but no error). Here is the response:

```
{
  "id": "chatcmpl-8jmYek5R2BNHdziIxKhc1Wef8KKls",
  "object": "chat.completion",
  "created": 1705922108,
  "model": "gpt-4",
  "prompt_filter_results": [ REDACTED ],
  "choices": [
    {
      "index": 0,
      "finish_reason": "tool_calls",
      "message": {
        "role": "assistant"
      },
      "content_filter_results": {}
    }
  ],
  "usage": {
    "prompt_tokens": 619,
    "completion_tokens": 13,
    "total_tokens": 632
  }
}
```



With the fix (payload rewrite), it works.

Makes me think of this issue: https://github.com/microsoft/semantic-kernel/issues/4671 - with the payload rewrite, it works again too.

**Comment by matthewbolanos** [comment]
Thanks for reporting, as @Krzysztof318, this has been reported in #4556, so I'll close this as a duplicate.

**Comment by SophisticatedConsulting** [comment]
Hi.
I seem to have the same issue in Switzerland North as of yesterday (worked previously)... even simply prompts result in 

{
  "error": {
    "message": "Invalid value for 'content': expected a string, got null.",
    "type": "invalid_request_error",
    "param": "messages.[0].content",
    "code": null
  }
}

I have tried multiple chat models all with the same outcome.
