### ISSUE TITLE
System.TypeLoadException: 'Could not load type 'Microsoft.SemanticKernel.Http.HttpOperationException' 

### ISSUE THREAD

**Issue by githubuserchn** [microsoft/semantic-kernel#4695]
I  am getting the following error

System.TypeLoadException: Could not load type 'Microsoft.SemanticKernel.Http.HttpOperationException' from assembly 'Microsoft.SemanticKernel.Abstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3

when I call "SearchAsync" method of Microsoft.SemanticKernel.Memory.ISemanticTextMemory.

The "SearchAsync" method is called in native plugin code.

The method signature is:

/// <summary>
/// Find some information in memory
/// </summary>
/// <param name="collection">Collection to search</param>
/// <param name="query">What to search for</param>
/// <param name="limit">How many results to return</param>
/// <param name="minRelevanceScore">Minimum relevance score, from 0 to 1, where 1 means exact match.</param>
/// <param name="withEmbeddings">Whether to return the embeddings of the memories found.</param>
/// <param name="kernel">The <see cref="Kernel"/> containing services, plugins, and other state for use throughout the operation.</param>
/// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
/// <returns>Memories found</returns>
public IAsyncEnumerable<MemoryQueryResult> SearchAsync(
    string collection,
    string query,
    int limit = 1,
    double minRelevanceScore = 0.7,
    bool withEmbeddings = false,
    Kernel? kernel = null,
    CancellationToken cancellationToken = default);
Please note that I installed "Microsoft.SemanticKernel.Abstractions" version 1.1.0....

Any suggestions to resolve this issue?

**Comment by matthewbolanos** [comment]
I believe you may be using an older package that's trying to use HttpOperationException. HttpOperationException no longer exists. Can you make sure all of your Semantic Kernel packages have been updated to the latest?

**Comment by markwallace-microsoft** [comment]
@githubuserchn We renamed some packages before reaching 1.0/1.1 so it's possible you are referencing a package with an old name.

**Comment by githubuserchn** [comment]
Thanks Matt/Mark...

I try re-creating the app with latest semantic kernel v1.1.0 packages and share feedback....

**Comment by githubuserchn** [comment]
Hi Matt/Mark.

I recreated the app with latest semantic kernel v1.1.0 packages. My findings below:

The "SearchAsync" function works when using VolatileMemoryStore(). The code snippets below:

public static IServiceCollection InjectSemanticKernelServices(this IServiceCollection services)
        {
		#pragma warning disable SKEXP0003, SKEXP0011, SKEXP0052, SKEXP0026
            try
                {
                services.AddOpenAIChatCompletion("text-embedding-ada-002", "open ai api key here", "", "gpt-3.5-turbo-16k");
                services.AddOpenAITextEmbeddingGeneration("text-embedding-ada-002", "open ai api key hereopen ai api key here", "", "gpt-3.5-turbo-16k");
                var kernelMemory = new MemoryBuilder()                     
                     **.WithMemoryStore(new VolatileMemoryStore())**
                     //.WithMemoryStore(new QdrantMemoryStore("http://localhost:6333/", 1536))
                    .WithOpenAITextEmbeddingGeneration("text-embedding-ada-002", "open ai api key here")
                    .Build();
                _ = services.AddScoped<ISemanticTextMemory>((serviceprovider) =>
                {  
                    return (ISemanticTextMemory)kernelMemory;
                });
Packages used:
![image](https://github.com/microsoft/semantic-kernel/assets/111283111/0ddaac6a-c09e-48d8-93cc-64e7b7f4d9be)


But when QdrantMemoryStore is used:

public static IServiceCollection InjectSemanticKernelServices(this IServiceCollection services)
        {
		#pragma warning disable SKEXP0003, SKEXP0011, SKEXP0052, SKEXP0026
            try
                {
                services.AddOpenAIChatCompletion("text-embedding-ada-002", "open ai api key here", "", "gpt-3.5-turbo-16k");
                services.AddOpenAITextEmbeddingGeneration("text-embedding-ada-002", "open ai api key hereopen ai api key here", "", "gpt-3.5-turbo-16k");
                var kernelMemory = new MemoryBuilder()                     
                     //.WithMemoryStore(new VolatileMemoryStore())
                     **.WithMemoryStore(new QdrantMemoryStore("http://localhost:6333/", 1536))**
                    .WithOpenAITextEmbeddingGeneration("text-embedding-ada-002", "open ai api key here")
                    .Build();
                _ = services.AddScoped<ISemanticTextMemory>((serviceprovider) =>
                {  
                    return (ISemanticTextMemory)kernelMemory;
                });


 I am getting the error:
System.TypeLoadException: Could not load type 'Microsoft.SemanticKernel.Http.HttpOperationException' from assembly 'Microsoft.SemanticKernel.Abstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3'.

StackTrace Contains:

   at Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore.GetNearestMatchesAsync(String collectionName, ReadOnlyMemory`1 embedding, Int32 limit, Double minRelevanceScore, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore.GetNearestMatchesAsync(String collectionName, ReadOnlyMemory`1 embedding, Int32 limit, Double minRelevanceScore, Boolean withEmbeddings, CancellationToken cancellationToken)+System.IAsyncDisposable.DisposeAsync()
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.DisposeAsync()
   at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SearchAsync(String collection, String query, Int32 limit, Double minRelevanceScore, Boolean withEmbeddings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SearchAsync(String collection, String query, Int32 limit, Double minRelevanceScore, Boolean withEmbeddings, Kernel kernel, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36

Packages Used:
![image](https://github.com/microsoft/semantic-kernel/assets/111283111/632c86a9-e3dd-479f-abb3-386179e427a4)


Any suggestions to resolve the issue encountered when using Microsoft.SemanticKernel.Connectors.Memory.Qdrant package?

With Regards

**Comment by githubuserchn** [comment]
The updated Package contents here:

![image](https://github.com/microsoft/semantic-kernel/assets/111283111/89d9a789-372c-4271-ad90-fcf5fc8918ff)

**Comment by markwallace-microsoft** [comment]
@githubuserchn The QDrant package has been renamed so you need to use this package https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.Qdrant/1.2.0-alpha

The older package is incompatible with the latest SK core and abstractions packages
