### ISSUE TITLE
Python: Error in tool_message for sk_chat_completion_async function

### ISSUE THREAD

**Issue by gpickett** [microsoft/semantic-kernel#4697]
**Describe the bug**
The tool_message isn't correctly mapping the url of retrieved documents

**To Reproduce**
1. try running the sk_chat_completion_async function and print tool_message
2. notice the url isnt the url for the retrieved document
3. Other metadata is incorrect as well

**Expected behavior**
I expected the correct metadata to be returned with the actual retrieved document url stored inside tool_message

**Screenshots**
Below screenshots show where we run pdb and where tool_message is printed
![image](https://github.com/microsoft/semantic-kernel/assets/122489228/9dce8859-d237-493d-98c0-a9ea35b20de9)

![image](https://github.com/microsoft/semantic-kernel/assets/122489228/cd417846-ed7f-434b-bb94-31236a64fc13)

**Platform**
 - OS: Windowws
 - IDE: VS code
 - Language: python

**Comment by andrewldesousa** [comment]
Here is the processing code:
```
async for message in chat_completion.complete_chat_stream_async(chat_messages, settings):
        tool_message = await message.get_tool_message()
        response = {
                "id": "",
                "model": "",
                "created": 0,
                "object": "",
                "choices": [{
                    "messages": []
                }],
                "apim-request-id": "",
                'history_metadata': history_metadata
            }

        response["id"] = str(uuid.uuid4())
        response["model"] = AZURE_OPENAI_MODEL_NAME
        response["created"] = int(time.time())
        response["object"] = "extensions.chat.completion.chunk"
        response["apim-request-id"] = headers.get("apim-request-id")
        response["choices"][0]["messages"].append({
            "role": "tool",
            "content": tool_message
        })
        
        yield format_as_ndjson(response)

        async for deltaText in message:
            response = {
                "id": "",
                "model": "",
                "created": 0,
                "object": "",
                "choices": [{
                    "messages": []
                }],
                "apim-request-id": "",
                'history_metadata': history_metadata
            }

            response["id"] = str(uuid.uuid4())
            response["model"] = AZURE_OPENAI_MODEL_NAME
            response["created"] = int(time.time())
            response["object"] = "extensions.chat.completion.chunk"
            response["apim-request-id"] = headers.get("apim-request-id")
            response["choices"][0]["messages"].append({
                "role": "assistant",
                "content": deltaText
            })
            
            yield format_as_ndjson(response)
```

my .env looks like this:
AZURE_SEARCH_SERVICE=byc-search
AZURE_SEARCH_INDEX=index name
AZURE_SEARCH_KEY=
AZURE_SEARCH_USE_SEMANTIC_SEARCH=False
AZURE_SEARCH_SEMANTIC_SEARCH_CONFIG=default
AZURE_SEARCH_INDEX_IS_PRECHUNKED=False
AZURE_SEARCH_TOP_K=5
AZURE_SEARCH_ENABLE_IN_DOMAIN=False
AZURE_SEARCH_CONTENT_COLUMNS=content
AZURE_SEARCH_FILENAME_COLUMN=title
AZURE_SEARCH_TITLE_COLUMN=title
AZURE_SEARCH_URL_COLUMN=title
AZURE_SEARCH_VECTOR_COLUMNS=
AZURE_SEARCH_QUERY_TYPE=simple
AZURE_SEARCH_PERMITTED_GROUPS_COLUMN=
AZURE_SEARCH_STRICTNESS=3
AZURE_OPENAI_RESOURCE=
AZURE_OPENAI_MODEL=gpt-35-turbo-16k
AZURE_OPENAI_KEY=
AZURE_OPENAI_MODEL_NAME=gpt-35-turbo-16k
AZURE_OPENAI_TEMPERATURE=0
AZURE_OPENAI_TOP_P=1.0
AZURE_OPENAI_MAX_TOKENS=1000
AZURE_OPENAI_STOP_SEQUENCE=
AZURE_OPENAI_SYSTEM_MESSAGE=You are an AI assistant that helps people find information.
AZURE_OPENAI_PREVIEW_API_VERSION=2023-12-01-preview
AZURE_OPENAI_STREAM=True
AZURE_OPENAI_ENDPOINT=https://byc-aoai.openai.azure.com/
AZURE_OPENAI_EMBEDDING_NAME=
AZURE_COSMOSDB_ACCOUNT=
AZURE_COSMOSDB_DATABASE=db_conversation_history
AZURE_COSMOSDB_CONVERSATIONS_CONTAINER=conversations
AZURE_COSMOSDB_ACCOUNT_KEY=

**Comment by moonbox3** [comment]
@gpickett We've release a Python beta package. Please try the new code and if you continue to experience a problem either re-open this issue or file a new issue. Thank you.
