### ISSUE TITLE
.Net: Handlebars planner should create plans that are configurable

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4698]
Today, the input properties of a handlebars plan are hard coded. This makes it difficult for the plans to be reused with different inputs. This feature request is to determine how the initial prompt can be updated to make the input parameters dynamic.

Related issues: 
- #4422 
- #4293

**Comment by matthewbolanos** [comment]
Closing as a duplicate of #4422

**Comment by teresaqhoang** [comment]
Will use this for tracking. 

Related issues: 
- #4422 
- #4293

**Comment by teresaqhoang** [comment]
Done https://github.com/microsoft/semantic-kernel/issues/4698
