### ISSUE TITLE
Errors in native functions not bubbling up via the SKContext

### ISSUE THREAD

**Issue by jansenbe** [microsoft/semantic-kernel#47]
**Describe the bug**

Imagine I do have a semantic skill (named `QuestionAnswer`) using a template like this

```text
Question: {{$INPUT}}

<Input>
{{MySkill1.GetQuestionContext $INPUT}}
{{MySkill2.GetQuestionContext $INPUT}}
</Input>
```

and I'm using this semantic skill like this:

```csharp
var output = await kernel.RunAsync(myContext, qaSkill["QuestionAnswer"]);
if (!output.ErrorOccurred)
{
    Console.WriteLine(output);
}
else
{
    Console.WriteLine($"Error: {output.LastErrorDescription}");
}
```

When then an error happens in one of the native functions it's not bubbling up via the `SKContext` instance. Today the error is logged
(https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel/TemplateEngine/Blocks/CodeBlock.cs#L134-L140), but would be beneficial for application using SK to understand something went wrong.

**To Reproduce**
1. Create two simple native skills and throw exception in them
2. Use them in a simple template and test

**Expected behavior**
The outputted `SKContext` should show that an error has happened and the `LastErrorDescription` should show the error text. It's fine to keep completing the template, but the app using SK has to know as the net result is that most likely a different prompt is created generating an unexpected output.

**Comment by alexchaomander** [comment]
Thanks for raising the issue @jansenbe! 

@dluc @shawncal for vis

**Comment by dluc** [comment]
Thanks @jansenbe also for the code to repro. I found the source of the bug in `CodeBlock` and sent our a bugfix PR. 
Could you test https://github.com/microsoft/semantic-kernel/pull/52 and see if it solves your scenario?

**Comment by dluc** [comment]
The issue should be fixed, let us know otherwise. Thanks!
