### ISSUE TITLE
.Net: Investigate if we should fix the PluginName in the KernelFunction metadata

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#4706]
Currently the `PluginName` in the `KernelFunction` metadata only get's set then you call `KernelPlugin.GetFunctionsMetadata()`.

The reason it is implemented like this is so we can add the same function to multiple plugins.

One disadvantage of this approach is that if you use the function invoking/invoked event handlers the function metadata doesn't contain the plugin name.

The goal of this task is to investigate alternate options.

**Comment by Nurgo** [comment]
I agree, the plugin name should be available somewhere in `FunctionInvokingContext` and `FunctionInvokedContext`.

**Comment by markwallace-microsoft** [comment]
Closed by https://github.com/microsoft/semantic-kernel/pull/5422
