### ISSUE TITLE
Python: Chat completion endpoint cannot remember its previous message using SK

### ISSUE THREAD

**Issue by HuskyDanny** [microsoft/semantic-kernel#4707]
**Describe the bug**
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/33ab5f58-d40e-4781-993f-7152cb29016d)
With this request, llm should answer my last question. But it says it doesn;t know. Is ChatPromptTemplate with chat completion endpoint supposed to remember the previous messages or I should manually added them in the latest user prompt?

**To Reproduce**

This is my code for setting up, basically it add the previous messages into the ChatPromptTemplate.
```
system_message = """
You are a technical supporter that help users' questions, you should give 1-2 sentences to explain the answer and code examples for the question based on only the following contexts.
You may find the contexts provide information for multiple potential answers, you can give up to 3 most relevant answers separated by numbers like 1. 2. 3.

Follow this pattern to answer the question:
Contexts:
- Document path_title1 : page_content1
&&&
- Document path_title2 : page_content2

Question: question

Answer: answer
"""

prompt_template = """
Contexts:
{{$context}}

Question: {{$input}}
"""

def preprocess_messages(messages : list):
    transformed_messages = []
    transformed_messages.append({"role": "system", "message": system_message})
    for message in messages:
      role = "assistant" if message["role"] == "bot" else message["role"]
      transformed_message = {"role": role, "message": message["content"]}
      if (role != "system"):
        transformed_messages.append(transformed_message)
    return transformed_messages

def create_chat_prompt_template_instance(kernel : Kernel, messages : list = []):
    req_settings = sk_oai.AzureChatRequestSettings(max_tokens=2000, temperature=0, extension_data={"chat_system_prompt": system_message})
    req_settings.unpack_extension_data()
    config = PromptTemplateConfig(completion=req_settings)
    template = ChatPromptTemplate(prompt_template, kernel.prompt_template_engine, config)
    if (messages and len(messages) > 0):
      processed_messages = preprocess_messages(messages)
      for message in processed_messages:
        template.add_message(message["role"], message["message"])
    function_config = SemanticFunctionConfig(config, template)
    return kernel.register_semantic_function("ChatBot", "rag_chat", function_config)

  # simplified calling
  messages = [{"content": "Q1", "role": "user"}, {"content": "A1", "role": "bot"},{"content": "Q2", "role": "user"}]
  query=messages[-1]['content']
  context['context'] = combined_documents
  context['input'] = query

  previous_messages = messages[:-1]
  chat_function = create_chat_prompt_template_instance(kernel=kernel, messages=previous_messages)

  response = await kernel.run_async(chat_function, input_context=context)
```

**Expected behavior**
It should be able to recall the last message

Chat completion takes a list of messages
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/88e62be8-d05c-4175-a303-05f3f483fc2e)
Response saying don't know previous message
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/d270c98a-2026-42a7-a559-03ce2c0aafa3)

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by HuskyDanny** [comment]
It seems like different wording will bring gpt's memory back, this is confusing

![image](https://github.com/microsoft/semantic-kernel/assets/40053881/b0f33e9c-4fad-439f-b591-72618680f66e)

**Comment by eavanvalkenburg** [comment]
@HuskyDanny why are you recreating the whole kernel and chat_prompt_template etc before every call? You could use the ChatPromptTemplate.restore method instead of you manually loading the message one by one. I also made an issue #4711 because I see the double system_prompt which is not the ideal way. The function by default will add the response message to the chat_prompt_template. The actual response from GPT is something that might or might not be due to this code, always hard to check, if you have access to the OAI Studio on azure you might be able to replay the same conversation to see what happens, it might also be that recent jailbreaks have led to hardening of the behaviour for these kinds of introspective questions, hard to determine. Could you see if actual content questions about previous messages do work?

**Comment by HuskyDanny** [comment]
Thanks for answering @eavanvalkenburg.

1. I tried to use restore but a non-attribute error about the chat_system_prompt came out : https://github.com/microsoft/semantic-kernel/issues/4705. So I decided to manually load the messages for the tryout.
2. Good suggestion on the reply on OAI studio. And if you see my last comment just before you, I can get the memory by changing the wording to "Summarize the conversation", but if you see my original post, "What was my previous message" didn't work.

**Comment by moonbox3** [comment]
@HuskyDanny we've release the SK Python beta. It includes a chat history, that gets parsed and included with the prompt. Please try this and if you experience a new issue, feel free to re-open or create a new GitHub issue. Thank you.

**Comment by HuskyDanny** [comment]
Hi All, I came back to update the semantic kernel and found that many functions and components got updated. Do we have a track of the difference for each new release and examples on how to modify from previous version?

**Comment by eavanvalkenburg** [comment]
@HuskyDanny we posted a couple of blogs [here](https://devblogs.microsoft.com/semantic-kernel/) to explain a bit more of the reasoning, and we try to keep the samples and notebooks up to date as much as we can, so you can use those to get started, there is indeed a ton of new ways of working, but we hope that the overall experience once you get used to it is much better!
