### ISSUE TITLE
Python: clarify use of AIServiceClientBase vs *CompletionClientBase classes

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/semantic-kernel#4710]
We became aware that the current approach is not 100% clear, and a custom class should inherit both from AIServiceClientBase and one or more of the *CompletionClientBase classes, those latter classes now act more like mixins providing the abstract methods that are expected from a certain type of service client. While AIServiceClientBase is used across clients and has fields and logic that we use for 1) matching request settings classes to the service and 2) the ai_model_id which in the future will also be used for service selection logic.

Two things todo:
1) decide on naming convention
2) improve documentation/samples

**Comment by moonbox3** [comment]
@eavanvalkenburg can we close this?
