### ISSUE TITLE
.Net: Python: improve chat_system_prompt default and messages behaviour for OpenAIChatRequestSettings

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/semantic-kernel#4711]
**Describe the bug**
There is a default system message in the OpenAIChatRequestSettings class that get's loaded into the ChatPromptTemplate when instantiating with OpenAI or AzureChatRequestSettings, this is not controlable or transparent.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by HuskyDanny** [comment]
Any plans on this? I think this is quite urgent and basic function for chat based QA scenario. Currently, it is a bit messy like how we override and **not appending** the default system message located in OpenAIChatRequestSettings class.

And the ChatPromptTemplate.restore() is buggy to add system message as mentioned in the [#4705](https://github.com/microsoft/semantic-kernel/issues/4705)

**Comment by eavanvalkenburg** [comment]
@HuskyDanny just created a PR for this, have a look and let me know if you think this will solve your issues as well!

**Comment by HuskyDanny** [comment]
Thanks! This resolves and now it is much more consistent to use restore and __init__
