### ISSUE TITLE
.Net: Add options to adjust the FunctionCallingStepwisePlanner initial plan generation token limit 

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/semantic-kernel#4717]
Currently, the only way to adjust the token limit for the FunctionCallingStepwisePlanner initial plan generation is by providing another prompt via the config: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Planners/Planners.OpenAI/Stepwise/FunctionCallingStepwisePlanner.cs#L31.

The current token limit is set at 256: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Planners/Planners.OpenAI/Stepwise/GeneratePlan.yaml#L31, which is too small for longer plans. 

Customers can copy the default prompt from the file above and adjust the token limit. However, this is not a sustainable approach as the default prompt may get updated for improved performance, but customers won't get the benefits since they are maintaining the prompt themselves.

**Comment by matthewbolanos** [comment]
Closing as development on the function calling stepwise planner is on pause as we move customers to automatic function calling
