### ISSUE TITLE
Python: Stepwise planner not working properly | best practice?

### ISSUE THREAD

**Issue by skim0011** [microsoft/semantic-kernel#4718]
I don't know if it's from Bing's poor search performance or planner's error.
Is there any good example of stepwise planner? I want to see a good scenario of stepwise planner. so far, I don't see a much difference with sequence planner.

**Problem 1**
ask = """How many total championships combined do the top 5 teams in the NBA have? """
![image](https://github.com/microsoft/semantic-kernel/assets/156260712/a7d746fc-08ef-4bdd-b450-16701b23b0f8)

**Problem 2** – not executing the plan
ask = """ Tomorrow is Valentine's day. I need to come up with a few date ideas.
 Write it in French. Convert the text to uppercase.
""" 
![image](https://github.com/microsoft/semantic-kernel/assets/156260712/9cf28b8f-938d-48f6-8203-03942df326d6)

**Problem 3**– no plans here
ask = """ Tomorrow is Valentine's day. I need to come up with a few date ideas.
 Write it in French. Convert the text to uppercase.
""" 
![image](https://github.com/microsoft/semantic-kernel/assets/156260712/5e96fb30-e389-497f-a2a8-36074d1b45a8)

**Comment by matthewbolanos** [comment]
It looks like our web plugin might not be working as expected (based on the observation in the prompt); we'll likely take a pass at improving it in a month or so.
