### ISSUE TITLE
.Net: Create AI connector for ONNX ML.net

### ISSUE THREAD

**Issue by DavidParks8** [microsoft/semantic-kernel#472]
---
name: Feature request
about: Project samples

---

It would be immensely helpful for the community if there were an example which used ML.net and an ONNX model. Such a sample could accelerate the use of this library, and its appeal to the overall community that wants to self-host their model.

**Comment by evchaki** [comment]
@DavidParks8 thanks for the suggestion, feel free to do a PR as an example if you can.

**Comment by matthewbolanos** [comment]
@DavidParks8, I wanted to follow up and see if you were interested in helping us create an AI connector for ONNX models

**Comment by evchaki** [comment]
Closing this for now, great idea, feel free to submit a PR.
