### ISSUE TITLE
.Net: Handlebars Planner Failing to Parse JSON Array

### ISSUE THREAD

**Issue by rithvikb23** [microsoft/semantic-kernel#4721]
I have an openapi plugin to get a list of people that hold a certain asset. When loading the openapi spec the handlebars planner is failing to parse the plan as the handlebars planner is incorrectly parsing the template. The openapi spec is rather complex with many fields and complex data types, but is still appropriately formatted and I have tested it in a swagger editor however the plan is failing. The planner is failing to parse the json array in step 2 below.

Here is the current step by step by the planner:
Goal: "What is my exposure to AAPL, id 123"

Handlebars Plan:
{{!-- Step 1: Set your necessary parameters --}}
{{set "id" "123"}}

{{!-- Step 2: Set your symbol(AAPL) in a fieldValues array --}}
{{set "fieldValues" (array "AAPL")}}

{{!-- Step 3: Set your applied filters --}}
**{{set "appliedFiltersArray" (array (json{ "op": "EQLT", "field": "exposure_ss", "id": "1", "fieldValues": fieldValues}))}}**

{{!-- Step 4: Invoke the PositionCrossReferencePlugin helper and store the result --}}
{{set "response" (PositionCrossReferencePlugin-getPositionCrossReference id=id faId=(array faId) appliedFilters=appliedFiltersArray)}}

**Expected behavior**
When loading this saved plan the issue is in step 2 with parsing the json array. I am given the error
**Plan creation failed. Error: Reached unparseable token in expression: )}}**
**HandlebarsDotNet.HandlebarsParserException: Reached unparseable token in expression: )}}**

 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: NuGet package version 1.1.0, pip package

Are json array handling in the handlebars planner currently not supported? Or is there a workaround?

**Comment by joslat** [comment]
@rithvikb23 did you find any workaround to this?

**Comment by teresaqhoang** [comment]
The error is a syntax error by the model here:  `json{ "op": "EQLT", "field": "exposure_ss", "id": "1", "fieldValues": fieldValues}`. I wondering if adding an example directly to the `json` helper definition in the prompt will help. 

We recently added more direction to better guide the model in creating initial variables. Can you pull the latest changes and see if your planner results have improved? 

If not, please reply to this thread with:
- openapi spec
- The CreatePlan prompt template
- Resulting plan 

And I'll help troubleshoot

**Comment by teresaqhoang** [comment]
Hi @rithvikb23 following up to see if you're still seeing this issue

**Comment by teresaqhoang** [comment]
Closing as stale - feel free to re-open if issue persists
