### ISSUE TITLE
.Net: Functions are not loading for AddFromPromptDirectory

### ISSUE THREAD

**Issue by shadakshari-s** [microsoft/semantic-kernel#4724]
I am trying to build a console application to explore Semantic Kernel. Getting "System.Collections.Generic.KeyNotFoundException" exception.

**Exception message**: The plugin collection does not contain a plugin and/or function with the specified names. Plugin name - 'SummarizePlugin', function name - 'GetIntent'.

**StackTrace**:    at Microsoft.SemanticKernel.KernelPluginExtensions.GetFunction(IReadOnlyKernelPluginCollection plugins, String pluginName, String functionName)
   at Microsoft.SemanticKernel.Kernel.InvokeAsync(String pluginName, String functionName, KernelArguments arguments, CancellationToken cancellationToken)
   at Program.<\<Main\>$>d__0.MoveNext() in D:\Learning\Code\SKSummarize\Program.cs:line 22

**Package versions being used**
*Microsoft.SemanticKernel* = Tried both 1.0.1 and Latest Stable 1.1.0
*.NET* = net8.0

**Code**
```csharp
using Microsoft.SemanticKernel;

var pluginsDirectory = Path.Combine("D:\\Learning\\Code\\SKSummarize", "Plugins");

var kernelBuilder = Kernel.CreateBuilder();
kernelBuilder.AddOpenAIChatCompletion("gpt-3.5-turbo", "");
kernelBuilder.Plugins.AddFromPromptDirectory(pluginsDirectory, "SummarizePlugin");
//kernelBuilder.Plugins.AddFromPromptDirectory("./Plugins/SummarizePlugin");
var kernel = kernelBuilder.Build();

Console.WriteLine("Enter your question (type 'EXIT' to close the chat):");
var userPrompt = Console.ReadLine();
while (!userPrompt.Equals("exit", StringComparison.OrdinalIgnoreCase))
{
    if (string.IsNullOrEmpty(userPrompt))
    {
        Console.WriteLine("You didn't provide your query. Enter your query (type 'EXIT' to close the chat):");
        userPrompt = Console.ReadLine();
        continue;
    }

    var response = await kernel.InvokeAsync(
                        "SummarizePlugin",
                        "GetIntent",
                        new() {
                            { "input", userPrompt },
                            { "options", "salutation,hr_queries,complaint,Appreciation,hr_tranactional,other" }
                        }
                    );

    //Console.WriteLine($"Intent: {await skService.GetIntent(userPrompt)}");
    Console.WriteLine($"Intent: {response}");

    Console.WriteLine("Enter your query (type 'EXIT' to close the chat):");
    userPrompt = Console.ReadLine();
}

Console.WriteLine("Press any key to exit.");
Console.ReadKey();
```

**Plugins folder structure**
<img width="222" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/8627669/51b6b7d8-e680-4783-aff8-6731f1d25c62">

Any help is much appreciated!

Regards
Shada

**Comment by shadakshari-s** [comment]
I found what I was doing incorrectly.
The code `kernelBuilder.Plugins.AddFromPromptDirectory(pluginsDirectory, "SummarizePlugin");` treats *SummarizePlugin* as function name.
Correct code to use `kernelBuilder.Plugins.AddFromPromptDirectory(Path.Combine(pluginsDirectory, "SummarizePlugin"));` $\to$ instead of passing *plugin folder name* as second parameter, pass *full path to the plugin* as first parameter itself.

**Comment by PrintsCharming** [comment]
Thank you @shadakshari-s this was the missing piece for me.
