### ISSUE TITLE
.NET: Missing support for passing the 'user' field part of SK C#  ChatCompletionsOptions and CompletionsOptions

### ISSUE THREAD

**Issue by slreznit** [microsoft/semantic-kernel#4734]
**Describe the bug**
Azure OpenAI API support passing the 'user' field part of ChatCompletionsOptions
SK currently doesn't expose this field in C# and Gen-AI application developers cannot specify this field.
I believe SK Java has support [here](https://github.com/microsoft/semantic-kernel/blob/f959256229c7d0d821d1df5c8b112ced10ddd5ac/java/semantickernel-api/src/main/java/com/microsoft/semantickernel/textcompletion/CompletionRequestSettings.java#L99C1-L100C1) and not sure about SK Python yet.
This field is important as it is used to provide security coverage against threats including in Microsoft Azure OpenAI, and we should unblock and encourage Gen-AI & Copilot applications developers to populate this field.

**To Reproduce**

1. Create app using Azure.AI.OpenAI C# SDK, you are able to populate the user field in ChatCompletionsOptions & CompletionsOptions 
3. Create app using SK C#, there is no such option

**Expected behavior**
Gen-AI app developers should be able to populate the user field per request.
This is important to support multi-user applications e.g. a Copilot or Bot that is hosted as a service and used by multiple users that log-in and interact with it. SK [Chat-Copilot](https://github.com/microsoft/chat-copilot) is a good example for that.

**Screenshots**
https://github.com/microsoft/semantic-kernel/blob/f959256229c7d0d821d1df5c8b112ced10ddd5ac/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L717
![image](https://github.com/microsoft/semantic-kernel/assets/30771358/a5f5b7d8-d38b-497f-86e6-af346f547aa8)

https://github.com/microsoft/semantic-kernel/blob/f959256229c7d0d821d1df5c8b112ced10ddd5ac/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L751
![image](https://github.com/microsoft/semantic-kernel/assets/30771358/7347a775-0b11-4409-9aeb-ad6d46e1ece0)

**Platform**
 - Language: [C#, Python?]

**Additional context**

OpenAI:
- https://platform.openai.com/docs/api-reference/chat/create#chat-create-user
- https://platform.openai.com/docs/guides/safety-best-practices/end-user-ids
Azure OpenAI:
- [Azure OpenAI Service REST API reference - Azure OpenAI | Microsoft Learn](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions)

**Comment by slreznit** [comment]
Created PR:
https://github.com/microsoft/semantic-kernel/pull/4736

**Comment by markwallace-microsoft** [comment]
PR has been merged
