### ISSUE TITLE
.Net: MemoryBuild doesn't work with httpClient - 'The SSL connection could not be established, see inner exception.'

### ISSUE THREAD

**Issue by zioalex** [microsoft/semantic-kernel#4739]
**Describe the bug**
MemoryBuild doesn't work with httpClient param behing a corporate proxy with custom SSL certificate chain.

---> Azure.RequestFailedException: The SSL connection could not be established, see inner exception.                    ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.            ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown      

This is the code used:
```

            var handler = new HttpClientHandler();
            handler.CheckCertificateRevocationList = false;
            using var httpClient = new HttpClient(handler);

            var memoryBuilder = new MemoryBuilder()
                                .WithAzureOpenAITextEmbeddingGeneration(
                                "gpg35turbo", //"ingen51-dialogpt-medium-gpt4-4",
                                "gpt-35-turbo",
                                _endpoint, // Azure OpenAI Endpoint
                                _apiKey, // Azure OpenAI Key
                                httpClient: httpClient
                                )
                                .WithMemoryStore(new VolatileMemoryStore());

       
            var memory = memoryBuilder.Build();

            Console.WriteLine("SAVING 'about me' TEXT AS INFORMATION...");
            const string aboutMeCollection = "AboutMe";
            await memory.SaveInformationAsync(
                aboutMeCollection,
                "My name is Mike.",
                "info1");
```

**To Reproduce**
1. Run the code in VS

**Expected behavior**
Specifying a custom httpClient I would expect this to work as it does for a normal KernelBuilder()

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/3593840/f7e19458-0343-4549-bca5-f6040b7ecafd)

**Platform**
 - OS: Windows
 - IDE: VS
 - Language: C#
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**
Full error details
```
Microsoft.SemanticKernel.Http.HttpOperationException
  HResult=0x80131500
  Message=The SSL connection could not be established, see inner exception.
  Source=Microsoft.SemanticKernel.Connectors.AI.OpenAI
  StackTrace:
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.ClientCore.<RunRequestAsync>d__36`1.MoveNext()
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.ClientCore.<GetEmbeddingsAsync>d__24.MoveNext()
   at Microsoft.SemanticKernel.AI.Embeddings.EmbeddingGenerationExtensions.<GenerateEmbeddingAsync>d__0`2.MoveNext()
   at Microsoft.SemanticKernel.Memory.SemanticTextMemory.<SaveInformationAsync>d__3.MoveNext()
   at SKCodePresents.Program.<Memories>d__7.MoveNext() in C:\Users\s0vp8h\OneDrive - Swiss Reinsurance Company Ltd\Documents\Training_Course_ebooks\AI_ML\Code_magazine\Semantic_kernel_intro\SKCodePresents\SKCodePresents\Program.cs:line 232
   at SKCodePresents.Program.<Main>d__2.MoveNext() in C:\Users\s0vp8h\OneDrive - Swiss Reinsurance Company Ltd\Documents\Training_Course_ebooks\AI_ML\Code_magazine\Semantic_kernel_intro\SKCodePresents\SKCodePresents\Program.cs:line 33

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
RequestFailedException: The SSL connection could not be established, see inner exception.

Inner Exception 2:
HttpRequestException: The SSL connection could not be established, see inner exception.

Inner Exception 3:
AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown
```

**Comment by mamift** [comment]
I just wanted to mention that his also affects `Kernel` and `KernelBuilder` classes.

I just downloaded the semantic kernel start repo (as of [this commit](https://github.com/microsoft/semantic-kernel-starters/commit/f3771acc94f652cf4330966530c413297337b23c)) and just running the `sk-csharp-hello-world` project after configuring appSettings with your own API key throws the same exception (I am also behind a corporate proxy).

![image](https://github.com/microsoft/semantic-kernel/assets/2508444/0427f2b4-fdda-46c1-9c2b-bc2ae0a4b4d0)

**Comment by ebolinger-pinc** [comment]
Hi @JuliusJacobsohnWilo, try building an HttpCllient & HttpHandler with `CheckCertificateRevocationList = false` from the original post above.  Then pass that `httpClient` into the "With" functions:

`.WithOpenAITextEmbeddingGeneration("text-embedding-3-large", apikey, httpClient: httpClient)`

This [recommendation](https://github.com/microsoft/semantic-kernel/discussions/66#discussioncomment-7467841) worked for me to get 03-semantic-function-inline.ipynb running behind a corporate proxy.
