### ISSUE TITLE
.Net: Provide complete function call updates in streaming prompts with EnableKernelFunction

### ISSUE THREAD

**Issue by kboom** [microsoft/semantic-kernel#4743]
---
name: Feature request
about: Provide complete function call updates in streaming prompts with EnableKernelFunction

---

Today, using "EnableKernelFunction" rather than "AutoInvokeKernelFunction" with a streaming chat prompt forces us to also process the updates to the function calls manually which is quite difficult and something that should be handled by the library. If we don't, then we also lose all the tool calls, so this becomes useless (since AI is expecting a response we don't know how to give).

My proposal is to extend `StreamingChatMessageContent` with the list of **full** tool calls the moment they have been discovered. I know that today we're providing "tool chunks" with incomplete arguments and so on just the way we do with actual text responses, but this is difficult to process, and sort of defeats the purpose of using SK in the first place (this can be done through calling OpenAI APIs directly). This way the caller could simply collect the calls that can be readily used, without the trouble of going through [all this](https://github.com/microsoft/semantic-kernel/blob/240a2cbeaccc2e9562fa9aa82c856f74c5b5ace4/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L405-L592) - this would be as simple as adding to some stack and taking to a stack to execute.

Non-automatic function calling is a requirement in many cases, since we need to run some checks, ask for consent and so on. Moreover, having it defined this way would allow to call functions the moment they are available, and do that in parallel. None of these things happen in SK today, I think.

**Comment by jamesburton** [comment]
This is still broken ... I can call tool functions with C# Semantic Kernel against local models (ollama) but these same routines fail in streaming mode as the calls are not submitted in a single chunk.  I even receive the <tool_calls>...</tool_calls> but this does not trigger automatic evaluation.
