### ISSUE TITLE
Python: Switch to using defusedxml instead of xml.etree

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#4754]

**Comment by eavanvalkenburg** [comment]
Also had to be done for chat message content now.

**Comment by eavanvalkenburg** [comment]
@matthewbolanos please add to pre-v1 work!

**Comment by moonbox3** [comment]
Complete as of #5077

**Comment by moonbox3** [comment]
@eavanvalkenburg why re-open? it's not complete as of #5077?

**Comment by eavanvalkenburg** [comment]
no, that was done with built-in xml package, not defusedxml, but I will pick that up.
