### ISSUE TITLE
Add support for a "detail" parameter when passing an ImageContent into ChatHistory.

### ISSUE THREAD

**Issue by vivanenko** [microsoft/semantic-kernel#4759]
ImageContent should have "Detail" parameter which accepts values "high", "low" or "auto".

The detail parameter in the model offers three choices: low, high, or auto, to adjust the way the model interprets and processes images. The default setting is auto, where the model decides between low or high based on the size of the image input.
<img width="705" alt="Знімок екрана 2024-01-26 о 17 57 22" src="https://github.com/microsoft/semantic-kernel/assets/7206405/73912e12-6a7c-4d8a-8e05-3959cd39414b">

https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/gpt-with-vision#detail-parameter-settings-in-image-processing-low-high-auto

**Comment by Krzysztof318** [comment]
But does this param will be applicable for other vision models, not only the openai models? I think this param should be passed as a metadata.

**Comment by dmytrostruk** [comment]
> I think that can be done with an imageContent metadata. I will add this to the openai connector later on.

@Krzysztof318  We need to think if we want to use metadata for these purposes or introduce new type for OpenAI specific image content (e.g. `OpenAIImageContent` and keep it in OpenAI Connector.

We already have similar scenario with `ChatMessageContent` and then `OpenAIChatMessageContent` that contains OpenAI specific properties like `ToolCalls`. 

The right answer for question _"which approach to use, metadata or derived type?"_ can be taken from usage perspective.

With metadata approach, this is how it's going to look like for user:
```csharp
chatHistory.AddUserMessage(new ChatMessageContentItemCollection
{
    new TextContent("What’s in this image?"),
    new ImageContent(new Uri(ImageUri), metadata: new Dictionary<string, object?> { { "detail", "high" } })
});
```

With derived type approach, it will be a little bit simpler and most importantly - strongly-typed:
```csharp
chatHistory.AddUserMessage(new ChatMessageContentItemCollection
{
    new TextContent("What’s in this image?"),
    new OpenAIImageContent(new Uri(ImageUri)) { Detail = "high" }
});
```

`ImageContent` is currently sealed, and I believe it's a mistake. When I added `AudioContent`, initially I made it `sealed` as well, but then I reverted this change exactly for this scenario. I think we could do the same for `ImageContent`.

So, before any implementation, I would recommend evaluating both approaches and choose one that will be the best in terms of usage.

**Comment by Krzysztof318** [comment]
Okay @dmytrostruk I will hold on with implementing this. Please keep in mind when you will think about solution that one more property may be needed. For example gemini rest api required providing a mime type with image request. Now I have used metadata "mime_type" to support the gemini vision model.

**Comment by Krzysztof318** [comment]
@dmytrostruk Have you thought about supporting derived and generic solution (metadata). Similar as it is done for ExecutionSettings? (We can pass openaipromptexecutionsetting or base class promptexecutionsettings with extra json data)

**Comment by dmytrostruk** [comment]
> @dmytrostruk Have you thought about supporting derived and generic solution (metadata). Similar as it is done for ExecutionSettings? (We can pass openaipromptexecutionsetting or base class promptexecutionsettings with extra json data)

This could be one of the possible solutions as well.

**Comment by NickDrouin** [comment]
Hi, with the GA release of GPT4 with vision on Azure last week,  `gpt-4-turbo-2024-04-09`, has this moved forward?  I'm happy to contribute something if there is a clear path forward, but feel a bit too far removed to make design calls in this area. 

In the short term, is there a way to work-around and set/force the detail level?

**Comment by stephentoub** [comment]
> With derived type approach, it will be a little bit simpler and most importantly - strongly-typed:

We need to be thinking about consumers not knowing which service they're using, otherwise the abstractions fall apart. If this is on an OpenAI-specific content, then how do I specify detail to be used if possible if the target service understands it?

**Comment by dmytrostruk** [comment]
> We need to be thinking about consumers not knowing which service they're using, otherwise the abstractions fall apart. If this is on an OpenAI-specific content, then how do I specify detail to be used if possible if the target service understands it?

That's actually interesting, because when I invoke `IChatCompletionService` or `Kernel`, I usually pass instance of `OpenAIPromptExecutionSettings`, because I need to configure `temperature` and other OpenAI-specific parameters. An abstraction still works, because in one place of application I can call OpenAI and in other I can call Hugging Face. 

But case when developer doesn't know which service will be used - should be handled as well. Maybe property bag will work better after all. For `PromptExecutionSettings`, we have `ExtensionData` and I think it's (de)serialized correctly to include all necessary parameters. We can follow similar approach for `ImageContent`. I also think this should be covered not only for `ImageContent`, but for other `Content` classes as well, to support API for multiple AI providers at the same time.

Tagging @RogerBarreto , since he is working on graduating `Content` classes at the moment, and it's probably a good timing to consider this requirement as well.

**Comment by RogerBarreto** [comment]
@dmytrostruk Thanks for the tagging. This is an important topic and I follow also your suggestion on making an specialization on the `ImageContent` from the connector size and `unsealing` it already proposed in the #6319. 

[ImageContent Graduation](https://github.com/microsoft/semantic-kernel/pull/6319/files#diff-a122a929d0ddc07714a2a7dbe567ec7a063898c994aec34895e8c44de463b36f)

## On the subject of abstract configurations

### Thinking on how Kernel can support the other Service Modality types which bring us back to:
- `UbberService<TInput, TOutput>` analysis
- Add missing service abstractions to Kernel `switch` logic

#### Add Kernel support for other `Service` modality types

Currently we have the `PromptExecutionSettings` abstraction that is currently being used for `ChatCompletion` and `TextGeneration`, the same way can have leverage that abstraction for `ImageGeneration` and other different modalities. 

For this use case:  `OpenAIImageGenerationExecutionSettings` where exposes properties like `Detail` for generation.

#### Kernel Multiple Modalities Discovery 

This can be used from Semantic Kernel perspective to identify which existing service does support that type as a discovery option 

i.e:

`IServiceSelector` would check for the current services that support that setting type (`OpenAIImageGenerationExecutionSettings`).
