### ISSUE TITLE
Python: Semantic function .invoke() hangs on multiple calls

### ISSUE THREAD

**Issue by sarah-widder** [microsoft/semantic-kernel#4762]
**Describe the bug**
In the Python library, the synchronous call `.invoke()` on semantic functions does not seem to be internally handling the async call correctly. It works for a single call, but calling multiple times in a loop, it seems to freeze when it actually gets to `await self._function` on the subsequent call and execution does not continue.

**To Reproduce**
1. Invoke a semantic function with `.invoke()` in a loop.
2. See execution hangs after several calls.

**Expected behavior**
Each successive call to invoke should complete properly.

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: VSCode
 - Language: Python
 - Source: pip package version 0.4.5.dev0

**Additional context**
This test function reproduces the error for me:
```
def test():
    kernel = sk.Kernel()
    aoai_settings_dict = azure_openai_settings_from_dot_env_as_dict(include_deployment=True, include_api_version=True)
    kernel.add_chat_service("chat_completion", AzureChatCompletion(**aoai_settings_dict))
    prompt_config = sk.PromptTemplateConfig()
    prompt_template = sk.ChatPromptTemplate(
        "{{$user_input}}", kernel.prompt_template_engine, prompt_config
    )

    function_config = sk.SemanticFunctionConfig(prompt_config, prompt_template)
    chat_function = kernel.register_semantic_function(f"testfn", f"testfn", function_config)
    while True:
        text = input("Enter text: ")
        context = kernel.create_new_context()
        context['user_input'] = text
        result = chat_function.invoke(context=context)
        print(result.result)

**Comment by moonbox3** [comment]
Hi @sarah-widder, we've decided to remove support related to running functions synchronously. The PR for that work is [here](https://github.com/microsoft/semantic-kernel/pull/4796). Closing this issue.
