### ISSUE TITLE
.Net: (Python) - Allow HTTP URLs - with security warning

### ISSUE THREAD

**Issue by tarockey** [microsoft/semantic-kernel#4763]
As an option, it would be great to be able to connect to Azure OpenAI using a HTTP URL - when working with Enterprise customers who use a jump-box to connect to OpenAI, they may use HTTP urls within their intranet, which Semantic Kernel currently throws an exception about.
Ideally, it would be good to be able to set a flag, acknowledging that HTTP is less secure, and then still allow the calls to be made.

**Comment by markwallace-microsoft** [comment]
@tarockey This is currently possible, take a look at this article https://www.developerscantina.com/p/semantic-kernel-open-source-llms/ and skip down to the section where a custom `HttpClient` is being configured.

**Comment by markwallace-microsoft** [comment]
@tarockey Please re-open if your issue persists
