### ISSUE TITLE
.Net: generating parameter schema with enum types

### ISSUE THREAD

**Issue by colombod** [microsoft/semantic-kernel#4767]
when a function is using a parameter that is an `Enum` like:
```cs
    public enum MyEnum
    {
        ValueA,
        ValueB
    }
```

the schema produced by semantic kernel serialising `KernelParameterMetadata` will be :
```
{
 "enum":["ValueA","ValueB"]
}
```
according to the OpenAi documentation [here](https://platform.openai.com/docs/guides/function-calling) enums look like this:

![Image](https://github.com/microsoft/semantic-kernel/assets/375556/ef60e3fb-173c-47d2-9657-37d906eef6ed)

in  that case a parameter of type MyEnum should have been represented in the schema as: 
```js
{
 "type": "string"
 "enum":["ValueA","ValueB"]
}
```

in .NET `Enums` cannot extend string (like in typescript) in the [dotnet iinteractive](https://github.com/dotnet/interactive/blob/7b66b9f76838c0b391c3ee1827d8bccc30eecc6a/src/Microsoft.DotNet.Interactive.AIUtilities/GptFunction.cs#L187) we provided a specific handling of `Enum` to align with OpenAI docs.

 What are you thoughts?

**Comment by markwallace-microsoft** [comment]
@colombod I'd like to find out more about what you are doing in .Net interactive to see can we adopt the same approach

**Comment by colombod** [comment]
> [@colombod](https://github.com/colombod) I'd like to find out more about what you are doing in .Net interactive to see can we adopt the same approach

To be honest I think your approach is correct from JSonSchema point of you. might be worth having some tests to cover `enum` in tool signature and also some integration test to verify that `gpt` calls will honour that. What do you think?
