### ISSUE TITLE
.Net: Dependency Injection using Plugins

### ISSUE THREAD

**Issue by KapteinBabbalas** [microsoft/semantic-kernel#4768]
I have a Plugin that has some dependecies on other service to get real-time information.

I can only register a Plugin by type. The Kernel has it's own isolated service collection . This now forces me to duplicate all my dependency registrations in my normal application and then again in the kernel builder.

Is there another way and am I missing something?

The Plugin:
![image](https://github.com/MicrosoftDocs/semantic-kernel-docs/assets/2060705/7c2e7030-ae5e-4309-8e2f-b02200a8c9d1)

I'm injecting the IKernelBuilder
![image](https://github.com/MicrosoftDocs/semantic-kernel-docs/assets/2060705/6e782d9b-d588-42fc-a52c-b675b7fe904c)

The only solution that works is injecting the plugin and passing as object.
![image](https://github.com/microsoft/semantic-kernel/assets/2060705/a19e1dbf-11dd-45da-9ee1-c15a12e728c1)

**Comment by KapteinBabbalas** [comment]
With the help of Copilot I made this little feature of my own, but maybe there is something in the framework like this already that I'm missing.

 I Inject my (my Own) Plugin Resolver:
![image](https://github.com/microsoft/semantic-kernel/assets/2060705/45fb8223-4140-4f56-bf6b-1b65d74aceb1)

This is the code usage - now my dependencies are registered together
![image](https://github.com/microsoft/semantic-kernel/assets/2060705/c3fc45c6-62ef-433b-86ab-15ff2b33933e)


And The code itself
![image](https://github.com/microsoft/semantic-kernel/assets/2060705/310361f3-cb22-4aee-aa0d-789edffcb5ea)

![image](https://github.com/microsoft/semantic-kernel/assets/2060705/9917742d-5072-49dc-8f2c-86bbce48f4f2)

![image](https://github.com/microsoft/semantic-kernel/assets/2060705/a6817d77-a14b-4f46-8ebf-9dbd23dcbcd3)

**Comment by rosieks** [comment]
I had the same issue - take a look on that: https://github.com/microsoft/semantic-kernel/issues/4482

**Comment by stephentoub** [comment]
> I'm injecting the IKernelBuilder

Can you inject the Kernel instead? Kernel's constructor takes an IServiceProvider, and if you register it with DI (either yourself or using the AddKernel method), it'll compose itself from the services in DI, including any plugins you may have registered.

You can also register a plugin with the kernel after it's been constructed, so you should be able to inject the Kernel, call ImportPluginFromType, and the construction of that plugin type will resolve what it needs from the IServiceProvider the Kernel was constructed with.

**Comment by DavidNorena** [comment]
@stephentoub 

somehow this code doesnt work

```
        var kernelBuilder = services.AddKernel()
            .AddOpenAIChatCompletion(modelName, apiKey);

        // services.AddTransient<Kernel>(); // even uncommenting this dont work
        kernelBuilder.Plugins.Services.AddTransient<Kernel>();

        kernelBuilder.Plugins.AddFromType<ConversationSummaryPlugin>();
        kernelBuilder.Plugins.AddFromType<PaymentLinkPlugin>();

        // plugin that needs the kernel as dependency fails to resolve
        kernelBuilder.Plugins.AddFromType<KnowledgeRetrievalPlugin>();
```

do i need to add something additional to the services so it knows how to resolve the kernel ?

**Comment by stephentoub** [comment]
I don't understand from that snippet what it is you're trying to achieve. Can you share a small standalone repro?

**Comment by DavidNorena** [comment]
thanks for your quick response, maybe is a bug I should report, but it is maybe related to this issue.
Im trying to use the kernel inside the DI container of a asp.net api using .net 8, so I can inject services from my application into the plugin when needed.

I don't now if that is the best approach, but I need the kernel to execute some custom logic inside a Plugin, that is the reason why I inject it in the KnowledgeRetrievalPlugin

The issue is even when I register the kernel using the .AddKernel() as suggested in the examples and when I configure my services or at least the kernel services like mentioned before:

```
        var kernelBuilder = services.AddKernel()
            .AddOpenAIChatCompletion(modelName, apiKey);

        kernelBuilder.Plugins.Services.AddTransient<Kernel>();

        kernelBuilder.Plugins.AddFromType<ConversationSummaryPlugin>();
        kernelBuilder.Plugins.AddFromType<PaymentLinkPlugin>();

        // plugin that needs the kernel as dependency fails to resolve
        kernelBuilder.Plugins.AddFromType<KnowledgeRetrievalPlugin>();
```

The issue is that, it is failing without throwing an exception, so Im not able to follow where the exception is thrown

and the only reason for it to fail is when I inject the Kernel into the plugin

public class KnowledgeRetrievalPlugin
(
    Kernel kernel, // removing this injection allows my code to execute normally
    IKernelMemory memory
)

**Comment by DavidNorena** [comment]
@stephentoub maybe is there another way to register the Plugins when they depend on the kernel itself ? or is that a bad approach ?

**Comment by DavidNorena** [comment]
@KapteinBabbalas I hope my code for injecting services works for you maybe you need to reconsider everything discussed in this tread to solve this issue.

@stephentoub you are not only faster to reply but man ! you figure it out even quickly

It worked !

```
        var kernelBuilder = services
            .AddOpenAIChatCompletion(modelName, apiKey);
            
        services.AddTransient(sp =>
        {
            var kernelMemory = sp.GetService<IKernelMemory>() ??
                throw new InvalidOperationException("KernelMemory object not found in service provider");

            Kernel kernel = new(sp);

            kernel.Plugins.AddFromType<ConversationSummaryPlugin>();
            kernel.Plugins.AddFromType<PaymentLinkPlugin>();

            // Note: To avoid a service resolution error, when injecting Kernel object
            // into plugins we better create the plugin manually
            kernel.ImportPluginFromObject(new KnowledgeRetrievalPlugin(kernel, kernelMemory));
            return kernel;
        });
```

@stephentoub do you belive I should raise a issue, because in the way I see this code solves the situation, but that infinite loop should be addressed no ?

**Comment by stephentoub** [comment]
You're welcome.

>  do you belive I should raise a issue, because in the way I see this code solves the situation, but that infinite loop should be addressed no ?

How would you expect it to be "addressed"?

Also, what does your plugin need the Kernel for?  Can you instead add the Kernel as an argument to your [KernelFunction] method rather than having the plugin wrap it?

**Comment by KapteinBabbalas** [comment]
> thanks for your quick response, maybe is a bug I should report, but it is maybe related to this issue. Im trying to use the kernel inside the DI container of a asp.net api using .net 8, so I can inject services from my application into the plugin when needed.
> 
> I don't now if that is the best approach, but I need the kernel to execute some custom logic inside a Plugin, that is the reason why I inject it in the KnowledgeRetrievalPlugin
> 
> The issue is even when I register the kernel using the .AddKernel() as suggested in the examples and when I configure my services or at least the kernel services like mentioned before:
> 
> ```
>         var kernelBuilder = services.AddKernel()
>             .AddOpenAIChatCompletion(modelName, apiKey);
> 
>         kernelBuilder.Plugins.AddFromType<ConversationSummaryPlugin>();
>         kernelBuilder.Plugins.AddFromType<PaymentLinkPlugin>();
> 
>         // plugin that needs the kernel as dependency fails to resolve
>         kernelBuilder.Plugins.AddFromType<KnowledgeRetrievalPlugin>();
> ```
> 
> The issue is that, it is failing without throwing an exception, so Im not able to follow where the exception is thrown
> 
> and the only reason for it to fail is when I inject the Kernel into the plugin
> 
> public class KnowledgeRetrievalPlugin ( Kernel kernel, // removing this injection allows my code to execute normally IKernelMemory memory )
> 
> Update:
> 
> All the service resolution inside the plugin work, except for injecting the kernel Im I missing something like
> 
> services.AddSingleton(kernel) ?
> 
> Update 2:
> 
> Kernel resolves in other places, but not inside the plugin why ?

I think the plugin is supposed to be used by the Kernel or KernelBuilder, not the otherway around. Your plugin will be invoked by the AI to do stuff.  This is how I register the kernel / kernal builder (in my own code) so I I can resolve them both if needed: 
![image](https://github.com/microsoft/semantic-kernel/assets/2060705/54376edc-5313-404a-8963-b1512ada57be)

**Comment by ekjuanrejon** [comment]
so if i want to create a prompt function and execute how do i use the kernel? I'm getting the loop

**Comment by ekjuanrejon** [comment]
in my plugin i want to create a prompt function use kernel.CreatePromptFunction
