### ISSUE TITLE
.Net Provide common error codes in KernelException

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#4769]
Hi, a KernelException is thrown in many places in the code, but only with message and the optional inner exception.
We should have property of list of error codes in the KernelExeption. And an additional class which contains all error codes with their description. Something like below from handlerbars example but not using codes in the message.
```cs
ex.Message.Contains(nameof(HandlebarsPlannerErrorCodes.InsufficientFunctionsForGoal), StringComparison.CurrentCultureIgnoreCase)
            || ex.Message.Contains(nameof(HandlebarsPlannerErrorCodes.HallucinatedHelpers), StringComparison.CurrentCultureIgnoreCase)
            || ex.Message.Contains(nameof(HandlebarsPlannerErrorCodes.InvalidTemplate), StringComparison.CurrentCultureIgnoreCase))
```

**Comment by markwallace-microsoft** [comment]
@SergeyMenshykh what do you think about this proposal?
