### ISSUE TITLE
Update Tokenizer to use Microsoft.ML.Tokenizers library

### ISSUE THREAD

**Issue by luisquintanilla** [microsoft/semantic-kernel#478]
The existing tokenizer implementation supports only GPT models. The [Microsoft.ML.Tokenizers](https://www.nuget.org/packages/Microsoft.ML.Tokenizers/0.21.0-preview.22621.2) package provides a [BPE](https://huggingface.co/course/chapter6/5) tokenizer implementation which can be used with GPT models. In addition though, you can also load your own vocabulary files for use with other models that support BPE tokenization.

Here is a related sample that loads custom vocab files for GPT-2 from HuggingFace.

https://gist.github.com/luisquintanilla/bc91de8668cfa7c3755b20329fadd027

[API Documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.ml.tokenizers.tokenizer?view=ml-dotnet-preview)

**Comment by evchaki** [comment]
@luisquintanilla , thanks for the suggestion, we will take a look.

**Comment by dluc** [comment]
thanks for the info, work in progress

**Comment by lemillermicrosoft** [comment]
#2809 and #2147 made it easier to bring any tokenizer for use. #2840 demonstrates these capabilities specifically with MicrosoftML and DeepDev token counters along existing demonstration with SharpToken.

**Comment by luisquintanilla** [comment]
Thanks for these changes @lemillermicrosoft. They look great. Feel free to close this when the PR merges.

**Comment by KokinSok** [comment]
Fantastic Utility, Thank You!

What class supports the BERT Type Tokenizers? Same sort of thing as [FastBertTokenizer](https://github.com/georg-jung/FastBertTokenizer) and [BertTokenizer](https://github.com/NMZivkovic/BertTokenizers)?

Would be fantastic to use one class for all the main models atm.

Thank You!

**Comment by KashMoneyMillionaire** [comment]
is there any sort of cross-team effort (between https://github.com/dotnet/machinelearning and https://github.com/microsoft/semantic-kernel) to get the dotnet version of semantic kernel only using ML.NET tokenizers? This seems like it was a first step, so trying to track progress of further work. I see that dotnet semantic kernel uses 4 different tokenizer libraries: 
![image](https://github.com/microsoft/semantic-kernel/assets/5257880/77fa5aa2-5e36-416e-8c31-57f486f2886e)

**Comment by stephentoub** [comment]
> I see that dotnet semantic kernel uses 4 different tokenizer libraries (from microsoft/semantic-kernel/dotnet/Directory.Packages.props)

That's just in the samples. The actual SK libraries don't use any of them.

**Comment by KashMoneyMillionaire** [comment]
Ahh, that makes sense. I saw SharpToken was only used in samples but FastBert was used in code, so stopped there. That was my 2nd question though - do the samples need different tokenizers, or should we be pushing them to use the ML.NET tokenizer libraries? Or should we be removing those libraries from the `dotnet/Directory.Packages.props` and just put them straight in the `dotnet/samples/KernelSyntaxExamples/KernelSyntaxExamples.csproj`?

**Comment by stephentoub** [comment]
Our collective goal is that all relevant tokenizers end up in Microsoft.ML.Tokenizers so that it's a one-stop shop for tokenization needs in .NET. Microsoft.ML.Tokenizers now provides a Tiktoken implementation, so SK wouldn't need DeepDev or SharpToken, but it doesn't yet have a BERT tokenizer. Different models need different tokenizers; tiktoken is what's used by OpenAI's models. We could probably at this point refine the sample that's using DeepDev and SharpToken to not, but really all that sample is showing is that you can use different libraries within the delegate passed to TextChunker.

**Comment by KashMoneyMillionaire** [comment]
Love it, that makes a lot of sense. I've been diving into these two repos and roadmaps and plans and docs over the last few days, and I got the sense that was the goal, but was difficult to find a definitive place essentially saying that. I'm assuming the [ML.NET Roadmap](https://github.com/dotnet/machinelearning/blob/main/ROADMAP.md) is out of date, but that the [ML.NET Milestones](https://github.com/dotnet/machinelearning/milestone/16) are up to date. Any pointers on the best place to find info similar to that for SK?

Thanks for the time clarifying!
