### ISSUE TITLE
Python: chat_gpt_api_function_calling.py is blank 

### ISSUE THREAD

**Issue by alexaca79** [microsoft/semantic-kernel#4783]
**Describe the bug**
Mosscap responds blank in the chat_gpt_api_function_calling.py script 

**To Reproduce**
1. downloaded chat_gpt_api_function_calling.py  updated sk to 0.4.7 
2. changed the .env + plugin directory 
3. ran chat_gpt_api_function_calling.py 

**Expected behavior**
expecting a response from the LLM  to work through the plugin 

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/6887930/f8c1ca7c-31c2-4873-a5a6-6d9d38d15242)

**Platform**
 - OS: Windows
 - IDE: Vs Code 
 - Language: Python
 - Source:  git + recent python sk package 
 -
**Additional context** 
needing to add
< openapi_plugin = register_openapi_plugin(kernel, 
                                         plugin_name="open-ai-product-endpoint",
                                         openapi_document =  "https://www.klarna.com/us/shopping/public/openai/v0/api-docs") > 

 to allow for this plugin to be called as well to expand usage  

also I've double checked the .env to ensure there is a connection to AzureOpenAI  using AZURE_OPENAI_DEPLOYMENT_NAME="gpt-4-turbo"

**Comment by evchaki** [comment]
@alexaca79 try this with the new 0.9 and let us know if it is working for you.
