### ISSUE TITLE
.Net: Unable to configure DataSource as much as a vanilla HTTP request to OpenAI

### ISSUE THREAD

**Issue by santanor** [microsoft/semantic-kernel#4787]
**Describe the bug**
Semantic Kernel offers the ability to connect to a DataSource by using AzureOpenAIChatCompletionWithDataConfig I can't see a way to edit some of the parameters such as the `querytype`. 

```
        
        var config = new AzureOpenAIChatCompletionWithDataConfig()
        {
            CompletionEndpoint = openAiConf["Endpoint"] ?? string.Empty,
            CompletionApiKey = openAiConf["Key"] ?? string.Empty,
            CompletionApiVersion = openAiConf["ApiVersion"] ?? string.Empty,
            CompletionModelId = openAiConf["Deployment"] ?? string.Empty,
            DataSourceEndpoint = dataSourceConf["Endpoint"] ?? string.Empty,
            DataSourceIndex = dataSourceConf["IndexName"] ?? string.Empty,
            DataSourceApiKey = dataSourceConf["Key"] ?? string.Empty
        };
```

In a basic OpenAI request there are a lot of parameters that one can play around with, fields mapping, query type, topn.... 

```
"dataSources": [
    {
      "type": "AzureCognitiveSearch",
      "parameters": {
        "endpoint": "",
        "indexName": "",
        "semanticConfiguration": "default",
        "queryType": "semantic",
        "fieldsMapping": {
        "contentFieldsSeparator": "\n",
        "contentFields": [
            "content"
        ],
        "filepathField": "filepath",
        "titleField": "title",
        "urlField": "url",
        "vectorFields": [
            "contentVector"
        ]
        },
        "inScope": true,
        "roleInformation": "You are an AI assistant that helps people find information.",
        "filter": null,
        "strictness": 3,
        "topNDocuments": 2,
        "key": "",
        "embeddingDeploymentName": ""
      }
    }
```

I tried putting them in the `execution_settings` of the config.json, but no luck. 

Am I missing something? Any ideas?

**Expected behavior**
It would be nice to be able to edit those parameters in some way. 

**Platform**
 - OS: Mac
 - IDE: Rider
 - Language: C#
 - Source: NuGet 1.1.0

**Additional context**

**Comment by dmytrostruk** [comment]
Hi @santanor, thank you for reporting this issue! `AzureOpenAIChatCompletionWithData` related classes will be obsolete soon, as we will replace it with functionality that is available in Azure .NET SDK. There is a possibility to set query type and other related properties:
![image](https://github.com/microsoft/semantic-kernel/assets/13853051/82d66a2e-a198-4ff8-955f-69301fe92a65)

I will notify you here as soon as this functionality will be ready. Thanks again!

**Comment by dmytrostruk** [comment]
To do:
- [ ] Mark current Azure `*WithData` classes as obsolete.
- [ ] For Azure with data functionality use Azure .NET SDK: https://github.com/Azure/azure-sdk-for-net/tree/49b0ace48d35cb4b2ace93b517036b660fc12ca4/sdk/openai/Azure.AI.OpenAI#use-your-own-data-with-azure-openai

**Comment by MitaWinata** [comment]
hi, any update ?
