### ISSUE TITLE
.Net: [.Net] KernelSyntaxExamples README needs updated

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/semantic-kernel#4791]
**Describe the bug**
> A clear and concise description of what the bug is.

KernelSyntaxExamples README still details the steps to run the .Net Kernel examples using Program.cs, but @RogerBarreto converted them to tests in [this PR](https://github.com/microsoft/semantic-kernel/commit/b99b780eca883b8d954b6ed3d3335f0723c36120). 

**Expected behavior**
> A clear and concise description of what you expected to happen.

[README](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/README.md) needs updated to guide users in:
- running .Net Kernel examples as integration tests 
- configuring tests appropriately.

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#
 - Source: main branch of repository

**Comment by glahaye** [comment]
Solved as KernelSyntaxExamples has been redistributed among samples
