### ISSUE TITLE
GitHub Repo Q&A Bot sample app error

### ISSUE THREAD

**Issue by pauldotyu** [microsoft/semantic-kernel#480]
**Describe the bug**
Attempt to download the `microsoft/semantic-kernel` repo using the "GitHub Repo Q&A Bot" sample app results in an error with the message: "Bad Request => Positive number required. (Parameter 'bufferSize') Actual value was 0.

**To Reproduce**
1. Clone the repo using macOS m1
2. Start the KernelHttpServer using `func start --csharp` command
3. Copy `.env.example` as `.env` and populate with Azure OpenAI completion and embeddings model details (as defaults)
4. Run `yarn install && yarn start` to start the sample app
5. Go through the setup (values should be defaulted)
6. Enter GitHub Respoitory URL: `https://github.com/microsoft/semantic-kernel`
7. Enter Branch Name: `main`

**Expected behavior**
Embeddings should be downloaded

**Screenshots**
![image](https://user-images.githubusercontent.com/45927715/232567386-e2ce60ef-91a1-4e40-8300-eb2524a8589f.png)

**Desktop (please complete the following information):**
 - OS: macOS (M1)
 - IDE: VS Code
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

NodeJS and Azure Function Core Tools versions.

```bash
$ node -v                   
v18.7.0

$ func --version     
4.0.5095
```

**Comment by craigomatic** [comment]
Which model are you using for embeddings? ada-002?

**Comment by pauldotyu** [comment]
> Which model are you using for embeddings? ada-002?

Correct. I've deployed the `text-embedding-ada-002` model and set the deployment name to be the same name as the model.

**Comment by evchaki** [comment]
@pauldotyu thanks for bringing this up, we have filed a bug on this and will take a look to see what is going on with it.

**Comment by evchaki** [comment]
@craigomatic  can you take a look at this

**Comment by evchaki** [comment]
@matthewbolanos  can you take a look and see if this repros for you?

**Comment by craigomatic** [comment]
Closing this for now, please reopen if needed.
