### ISSUE TITLE
.Net: [Agents] Improve existing SK agent functionality

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#4831]
- Rename the Agent class to AssistanceAgent? [confirmation required]
- Inherit AssistanceAgent class from KernelAgent abstract one.
- Refactor AssistanceAgent to work with an external kernel instead of creating one
- Remove unnecessary With* duplicates that already exist for Kernel from AgentBuilder
- Make the AgentBuilder.BuildAsync method more DI-friendly. DI does not allow calling async methods from factories in .AddTransient, .AddSingleton, etc... methods
- Migrate SK agent to new Azure SDK Assistance API
- Rename the IAgent.InvokeAsync extension method to align with the Kernel.InvokeStreamingAsync method name, which performs invocation with streaming.

**Comment by crickman** [comment]
This task addresses modifying the existing assistant agants.  The current trajectory is to spin-up something brand-new along-side the initial "assistant" agents and eventually deprecate / delete the initial "assistant" agents.
