### ISSUE TITLE
.Net [Agents] Agents collaboration

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#4832]
- Add support for agents collaboration via plugins
- Ideally, the AsPlugin() method should be written once and work for all agents inherited from the Agent class
- The AsPlugin() method should register input variables from prompt template config as the plugin parameters
- Implement CollaborationChat, and TurnBasedCollaborationChat see the [ADR](https://github.com/microsoft/semantic-kernel/blob/cd4a4ada6933edacd635db156eb513344c12dc18/docs/decisions/0031-agents.md) for more details. [Low priority] [Out Of Scope?]

**Comment by crickman** [comment]
This has been superceded by the current work on the agent framework.
