### ISSUE TITLE
.Net: FunctionCallingStepwisePlanner should return result when token limit reached, not just throw

### ISSUE THREAD

**Issue by gitri-ms** [microsoft/semantic-kernel#4834]
Currently, if the `MaxTokens` limit is reached in the `FunctionCallingStepwisePlanner`, a `KernelException` is thrown which interrupts/ends execution. The caller is unable to inspect the chat history to see exactly what happened and when/why the limit was reached.

Instead of throwing an exception, we should consider just bailing out of the planner loop and return a result object containing the chat history up until that point. Perhaps add a `FinishReason` field to the result as well.

**Comment by coolnitin157** [comment]
I agree @gitri-ms 
I have add a logging mechanism for getting the chatHistory to a blob for now, may be it will help you.
 using (MemoryStream streaminternalchat = new MemoryStream())
 {
     foreach (ChatMessageContent message in plan.ChatHistory)
     {
         if (message.Role != AuthorRole.Assistant)
         {
             string messageContent = $"\r\n\r\n{message.Role}:: {message.Content}";
             byte[] messageBytes = Encoding.UTF8.GetBytes(messageContent);

             // Write message bytes to the stream
             streaminternalchat.Write(messageBytes, 0, messageBytes.Length);
         }
         else
         {
             StringBuilder strTools = new StringBuilder();
             if (message.InnerContent != null)
             {
                 // Get the type of the innerContent object
                 Type innerType = message.InnerContent.GetType();

                 // Get the MethodInfo object for the "tools" method
                 MethodInfo methodInfo = innerType.GetMethod("get_ToolCalls", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);

                 // Check if the method exists
                 if (methodInfo != null)
                 {
                     var param = methodInfo.GetParameters();
                     object toolCalls = methodInfo.Invoke(message.InnerContent, null);
                     if (toolCalls is List<Azure.AI.OpenAI.ChatCompletionsToolCall> toolCallsList)
                     {
                         if (toolCallsList.Count > 0)
                         {
                             // Retrieve the first item from the list
                             var item = toolCallsList.First();

                             // Access properties of the item using reflection
                             var itemProperties = item.GetType().GetProperties();

                             // Iterate through properties
                             foreach (var property in itemProperties)
                             {
                                 // Get the value of each property dynamically
                                 var propertyValue = property.GetValue(item);
                                 strTools.AppendLine($"{property.Name}: {propertyValue}");

                             }
                         }
                     }
                 }
                 else
                 {
                     Console.WriteLine("InnerContent: Method 'tools' not found");
                 }
             }
             string messageContent = $"\r\n\r\n{message.Role}:: {strTools}";
             byte[] messageBytes = Encoding.UTF8.GetBytes(messageContent);

             // Write message bytes to the stream
             streaminternalchat.Write(messageBytes, 0, messageBytes.Length);
         }
     }
     streaminternalchat.Position = 0;
     string filename = string.Format("{0:yyyy-MM-dd_hh-mm-ss-tt}", DateTime.Now);
     var blobClient = await blobClientFactory.GetBlobClient(user, Constants.FOLDER_TESTING, filename);
     await blobClient.UploadAsync(streaminternalchat);
 }

**Comment by markwallace-microsoft** [comment]
Planner are obsolete
