### ISSUE TITLE
Python: 'Plan' object has no attribute '_runCode'

### ISSUE THREAD

**Issue by aayushsin** [microsoft/semantic-kernel#4836]
**Describe the bug**
I am trying to follow the steps mentioned on https://github.com/microsoft/semantic-kernel/blob/main/python/notebooks/05-using-the-planner.ipynb and getting the error 'Plan' object has no attribute '_runCode' in case of stepwise and sequential planner

**To Reproduce**
```
from semantic_kernel.planning import SequentialPlanner

planner = SequentialPlanner(kernel)
sequential_plan = await planner.create_plan(goal=ask)
result = await sequential_plan.invoke()

```

**Expected behavior**
The planner should execute the plan

**Platform**
 - OS: Windows
 - Language:Python 3.12
 - semantic-kernel           0.4.7.dev0

**Comment by aayushsin** [comment]
@moonbox3
With version 0.4.7.dev0, I was able to run via invoke_async().

However, with version 0.5.0.dev0, the object creation of sequential planner is failing

```
from semantic_kernel.planning import SequentialPlanner
planner = SequentialPlanner(kernel)
ask = """Tomorrow is Valentine's day. I need to come up with a few date ideas.
She likes Shakespeare so write using his style. She speaks French so write it in French.
Convert the text to uppercase."""
sequential_plan = await planner.create_plan(goal=ask)
```


Error screenshot is attached

**Comment by moonbox3** [comment]
Closing this issue as we're on version 0.9.6b1 now, and I am able to run through all notebooks. Please open a new issue if you do have a problem, thanks.
