### ISSUE TITLE
.Net/Python: Static Parameter Communication for Semantic Kernel Functions as OpenAI Plugins

### ISSUE THREAD

**Issue by nmoeller** [microsoft/semantic-kernel#4847]
## The Big Picture i have in mind

Semantic Kernel Planners working as orchestrator for different functions. If we stay in a C# or Python context we can exchange Parameters between functions to avoid hallucinations with the SK Context. But there are Scenarios where you would like to mix Languages because your company runs a microservice approach. To mix languages you could create multiple OpenAI Plugins and insert them into a Planner.

## The Problem
When you using OpenAI Plugins the communication is done via REST Calls, with this you lose the opportunity to exchange Parameters via the SK Context. But for some critical Scenarios like Health Care, Autonomous Driving etc. you can not afford parsing the parameters via LLM's to the API. 

When calling OpenAI Plugins an overwriting of the parameters makes probably sense for critical scenarios to ensured that the parameters are not hallucinated. When working with Planners it would make sense to have an option to overwrite Parameters that are extracted by a LLM.

## Example Scenario :

You are working with a hospital chat and you have a user id and two OpenAI Plugins to gather data, the current flow is like this :

1. User Asking for Data --> Parameters are extracted by LLM (Hallucinations Possible) --> Open AI Plugin is Called

2. User Asking for Data --> Parameters are extracted by LLM (Hallucinations Possible) --> Parameters are overwritten -->Open AI Plugin is Called

In the first scenario if a username is hallucinated you maybe get data of another Patient, in the second scenario this would not be possible.

**Comment by markwallace-microsoft** [comment]
@matthewbolanos The tool filters should help with this scenario. Thoughts?

**Comment by matthewbolanos** [comment]
Yes, I agree. Filters should help in the short-term. In the medium/Long-term, however, we need a way to mark certain parameters (e.g., patient ID) as parameters that should not be given to the LLM to populate. Instead, the user should be able to programmatically provide these fields instead.

**Comment by alliscode** [comment]
In the short term, you can use filters to support this scenario. For the long term, I've created #6846 to track the work of passing some arguments to plugins via the ambient context.

Closing this for now @nmoeller thank you for opening this. Please reopen if you have any additional questions or feedback.
