### ISSUE TITLE
Python: Support AzureOpenAIChatCompletionWithDataConfig in Python package

### ISSUE THREAD

**Issue by MitaWinata** [microsoft/semantic-kernel#4857]
Currently adding datasource in on azureOpenAiChatCompletion is only supported in .NET (https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.OpenAI/ChatCompletionWithData/AzureOpenAIChatCompletionWithDataConfig.cs#L38) . 
We need this in Python flavor as well.

**Comment by moonbox3** [comment]
Hi @MitaWinata, can you please have a look at the [following example](https://github.com/microsoft/semantic-kernel/blob/ca55eeee1b1f24f68d164294827ab3405d1717ee/python/samples/kernel-syntax-examples/azure_chat_gpt_with_data_api_function_calling.py#L30C1-L34C66) and see if it'd work for your use case in Python? As of a few SK Python versions ago, it is possible to configure your own Azure data source.

**Comment by MitaWinata** [comment]
nice, this exactly it. Sorry i missed it !
