### ISSUE TITLE
.Net MathPlugin which is dlivered with the kernel has only 2 functions

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#4866]
**Describe the bug**

The MathPlugin which is dlivered with the kernel has only 2 functions
In examples we can found implementation of the MathPlugin with many functions, but MathPlugin delivered with the kernel is so poor, why?

**Comment by dmytrostruk** [comment]
@Krzysztof318 Plugins from `Microsoft.SemanticKernel.Plugins.Core` package are marked as experimental, and most of them are for demonstration purposes only to show Semantic Kernel capabilities. As far as I know, there are no plans at the moment to maintain MathPlugin and extend it with more functionality (at least for now).

Given that now we have MathPlugin in examples, maybe at some point we could move all other Plugins to examples as well and deprecate the package. But this should be discussed with internal team.

**Comment by Krzysztof318** [comment]
@dmytrostruk I didn't know there is no plans to make plugins.core stable. Thanks for clarification.
