### ISSUE TITLE
.Net Planners with models other than openai

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#4870]
I wonder about a planners future. Now we have the handlebars planner which only works with the openai models. It utilizes system messages and chat messages which many models don't support. Old simple planners which in theory works with other models like Action Planner are supposed to be removed.

So are planners designed to work only with the openai?
Will you optimize the handlebars planner to work with other models or create some separate planners for other models?

**Comment by Krzysztof318** [comment]
@matthewbolanos I would also like to give as an example the gemini model, which will possibly one day be as important as openai. Unfortunately, although gemini handles chat, it has certain limitations:
1.  Doesn't support the system messages (handlebars p. is using them)
2.  Messages have to always alternate between the user and the assistant role (handlebars p. has two user messages in order)
3.  Last message in the chat history have to be always user message.

**Comment by matthewbolanos** [comment]
This is great feedback! (And one of the reasons we want to get Gemini and Llama enabled for Semantic Kernel as quickly as possible). This will let us run integration tests to validate all of those "gotchas".

Do you have a particular model you're wanting to use today? We can start exploring the required changes necessary for that.

**Comment by Krzysztof318** [comment]
@matthewbolanos Honestly I haven't already used planners but I look at it objectively. The gemini implementation is already complete enough so you can test planners with its. I haven't yet implemented only function calling.
Mode: gemini-pro
