### ISSUE TITLE
.Net: Assistants implementation still in the code, while "almost" identical to the new Agents implementation being used..

### ISSUE THREAD

**Issue by joslat** [microsoft/semantic-kernel#4875]
**Describe the bug**
Seemingly duplicate code still is in the code base

**To Reproduce**
1. Go https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Experimental/Assistants
2. look at the code
3.  go https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Experimental/Agents
4. look at the code
5. compare 

**Expected behavior**
There should be no /Assistants ;)

Of course, maybe you left that there for a reason but the code is mostly similar-identical for what I saw, so... It will always be in the git history, so I'd delete it. It can always be retrieved.

Unless I am missing something, which can pretty well be...

**Comment by crickman** [comment]
Should be removed in linked PR.  Thanks for callilng this out.
