### ISSUE TITLE
Python: CreateGraphRequest doesn'

### ISSUE THREAD

**Issue by Matti-Koopa** [microsoft/semantic-kernel#4876]
**Describe the bug**

https://github.com/microsoft/semantic-kernel/blob/ca55eeee1b1f24f68d164294827ab3405d1717ee/dotnet/src/Connectors/Connectors.Memory.Weaviate/Http/ApiSchema/CreateGraphRequest.cs#L23C67-L23C80

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by dmytrostruk** [comment]
Duplicate: https://github.com/microsoft/semantic-kernel/issues/4877
