### ISSUE TITLE
Python: Example for making API requests

### ISSUE THREAD

**Issue by Samartha27** [microsoft/semantic-kernel#4879]
Hi. In the [02-running-prompts-from-file.ipynb](https://github.com/microsoft/semantic-kernel/blob/main/python/notebooks/02-running-prompts-from-file.ipynb) file, you had mentioned that you will explore the functions accepting multiple variables as function parameters and invoking a function or other functions using the HTTP Plugin. Since there is no other resource online to build upon for the HTTP Plugin, I sincerely request you to provide the same either as a notebook or as a one of the kernel-syntax-examples in .py file format. Could you please make a sample example of using the HTTP plugins to make API calls

Sincerely and regards

**Comment by matthewbolanos** [comment]
In most cases, we do not recommend using the HTTP plugin to make API calls. Instead, we recommend that you create a native function that wraps API calls to your service of choice. This is the notebook where we demonstrate how to create native functions: https://github.com/microsoft/semantic-kernel/blob/main/python/notebooks/08-native-function-inline.ipynb

Here's another sample showing native functions: https://github.com/microsoft/semantic-kernel/blob/main/python/samples/documentation_examples/plugin.py

As we approach Build, we will work on adding a sample that demonstrates more clearly how to create a native function that wraps an HTTP request.

**Comment by moonbox3** [comment]
Our Sessions Python Core Plugin shows how one can use an http client to make API calls: https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/core_plugins/sessions_python_tool/sessions_python_plugin.py.
