### ISSUE TITLE
Python: semantic kernel not working properly

### ISSUE THREAD

**Issue by skim0011** [microsoft/semantic-kernel#4889]
https://github.com/microsoft/semantic-kernel/blob/main/python/notebooks/05-using-the-planner.ipynb

I'm running this example code but seeing this poor result. I didn't change the code. Any good point to debug to see what's causing this?
![image](https://github.com/microsoft/semantic-kernel/assets/156260712/7a0679a8-b077-4bef-9353-de14df2377e7)

**Comment by moonbox3** [comment]
@skim0011 we have some work to do to improve the web search plugin. This will be scheduled in the next few weeks, after we wrap up some larger changes that we're working on as we move towards v1.
