### ISSUE TITLE
.Net : ExcludedPlugins not available for the Handlebars planner, causing problems in certain cases

### ISSUE THREAD

**Issue by bbence84** [microsoft/semantic-kernel#4900]
**Describe the bug**
I have a couple of functions and Plugins that should be used in the plan. It works pretty well, except that in my case the planner functions are also added as Plugins (this was recommended in a OH session). (I have a chat based interaction). I have two functions for the planner:
1. CreateChangePlan: creates the plan using CreatePlanAsync
2. ExecutChangePlan: executes the plan using InvokeAsync

The problem is that in some cases, the created HB plan contains references to these, e.g. the HB plan contains a line that calls CreateChangePlan with a (sub)goal. This is not what I want, and I think that being able to exclude this plugin would solve this problem.

**To Reproduce**
Use Handlebars planner with multiple functions.

**Expected behavior**
ExcludedPlugins should be available for HB planner.

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#
 - Source: 1.3.0-preview for Handlebars, 0.27.240205.2 for SK

**Additional context**

**Comment by gitri-ms** [comment]
This will be resolved by #4793

**Comment by bbence84** [comment]
> This will be resolved by #4793

Thanks! And sorry, but I am not a C# expert, but just checking the changes in the PR #4793 , I don't see the ExcludedPlugins appearing as a get / set property appearing, not even in the base class... Maybe I am checking it wrong. :) Thanks!

**Comment by bbence84** [comment]
> This will be resolved by #4793

Sorry for pinging you again @gitri-ms but could you please confirm if indeed it will be possible to specify exluced functions for the HB planner via e.g. ExcludedPlugins? Thanks!
