### ISSUE TITLE
.Net: Observability within planners

### ISSUE THREAD

**Issue by nbarbettini** [microsoft/semantic-kernel#4909]
`IPromptFilter`, etc. are useful for observability, especially at development/experimentation time where it is helpful to log the exact prompt that was sent on the wire. 

Is it possible to "peek under the hood" in the same way with `HandlebarsPlanner` or `FunctionCallingStepwisePlanner`, and see the prompts that are generated by the planner?

**Comment by prajwalpyakurelMS** [comment]
Is it possible to also add detail on the steps generated by the planner like thought, action, observation, action variables, final answer, etc. in the Planner result?

**Comment by teresaqhoang** [comment]
@nbarbettini For the HB planner, you can see the prompt used for Plan Creation with the Prompt field, i.e. 

```
var plan = await planner.CreatePlanAsync(kernel, goal);
WriteLine(plan.Prompt);
```

Will defer to @matthewbolanos for stepwise planner queries

**Comment by teresaqhoang** [comment]
Closing as resolved
