### ISSUE TITLE
.Net: [Agents] Map chat agent instructions to a custom role

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#4938]
This task is created to track [the ask](https://github.com/microsoft/semantic-kernel/pull/4911#issuecomment-1934434309) in [.Net: Chat completion agent](https://github.com/microsoft/semantic-kernel/pull/4911) PR for a mapping of agent system instructions to a custom model role. For example, there could be a model out there that would use, let's say "admin" role instead of "system" role to set the behavior of LLM.

This task should be executed when the [agent abstraction/unified interface](https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0032-agents.md#unified-interface-and-data-contract) is already in place to model the customization mechanism properly.

**Comment by crickman** [comment]
Roles are explicitly defined / supported by provider (OpenAI in this case).  This isn't bound to agent framework and can be re-visited if possible and impactful.
