### ISSUE TITLE
.Net: Sample search plugins that uses Azure AI Search

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#4946]
As a developer I can reference a sample that shows how to create a custom plugin that uses Azure AI Search so that I can integrate search queries that use a custom index (schema)

See: https://github.com/microsoft/semantic-kernel/issues/3014

**Comment by dmytrostruk** [comment]
The sample was added in scope of this PR: https://github.com/microsoft/semantic-kernel/pull/5093
