### ISSUE TITLE
.Net: In `AzureAISearchMemoryStore` the private method `RunMemoryStoreOperation` does not throw exceptions

### ISSUE THREAD

**Issue by rliberoff** [microsoft/semantic-kernel#4952]
In the `AzureAISearchMemoryStore` class, some methods from the `IMemoryStore` interface, like `DoesCollectionExistAsync`, are implemented using a private method called `RunMemoryStoreOperation` and sending as operation an asynchronous function.

Sometimes those asynchronous functions throws exceptions that are not catch by the `RunMemoryStoreOperation` method.

For example, when attempting to retrieve a memory from the Azure AI Search Memory Store, if the requested element does not exist, instead of returning a `null` value as expected, the method throws a `RequestFailedException` with a status code of `HTTP 400 NOT FOUND`, but because the `RunMemoryStoreOperation` does not considers the asynchronous nature of the operation, that exception is not catch.

**To Reproduce**

1. Create an instance of `AzureAISearchMemoryStore`.
2. Invoke its method `GetAsync` with a collection name and key that does not exists.
3. The code of `GetAsync` will invoke the private method `RunMemoryStoreOperation` with an `async` function as value for its `operation` parameter.
4. In the `RunMemoryStoreOperation` method, the following code `return operation.Invoke();` returns a `Task` instead of the exception that happens inside the Azure AI Search Client.

**Expected behavior**

The exception from the Azure AI Client of type `RequestFailedException` should be catch.

**Screenshots**

N/A

**Platform**
 - OS: Windows
 - IDE: Visual Studio 2022 17.8.6
 - Language: C#
 - Source: NuGet version 1.3.0-alpha

**Additional context**

There is code already available in Semantic Kernel that address this issue. For instance there is a method called `RunRequestAsync` that can be found in `Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore` that works perfectly for this scenario. Based on that, I would like to propose the following code for the `AzureAISearchMemoryStore` class:

```
/// <summary>
/// Executes a memory store operation by invoking the provided asynchronous operation delegate.
/// </summary>
/// <typeparam name="T">The return type of the operation.</typeparam>
/// <param name="operation">The asynchronous operation delegate to be executed.</param>
/// <returns>The result of the memory store operation.</returns>
private static async Task<T> RunMemoryStoreOperationAsync<T>(Func<Task<T>> operation)
{
  try
  {
    return await operation.Invoke().ConfigureAwait(false);
  }
  catch (RequestFailedException e)
  {
    throw e.ToHttpOperationException();
  }
}
```

**Comment by dmytrostruk** [comment]
@rliberoff Thanks for reporting this issue! 
It is fixed in this PR: https://github.com/microsoft/semantic-kernel/pull/4992

**Comment by rliberoff** [comment]
@dmytrostruk Thank you!

When do you expect to release this fix?

**Comment by dmytrostruk** [comment]
> When do you expect to release this fix?

@rliberoff I expect it to be merged and released this or next week.
