### ISSUE TITLE
Python: ChromaMemoryStore currently not functioning 

### ISSUE THREAD

**Issue by alexaca79** [microsoft/semantic-kernel#4979]
**Describe the bug**
SK + Chroma Memory Store is currently unavailable to store data 

Using the  06-memory-and-embeddings.ipynb and add from semantic_kernel.connectors.memory.chroma import(ChromaMemoryStore)

and 

memory = ChromaMemoryStore(persist_directory = "chroma_e")
kernel.register_memory_store(memory_store=memory)

kernel.memory.save_information() will run into the following error 

ValueError: Expected EmbeddingFunction.__call__ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['args', 'kwargs'])
Please see https://docs.trychroma.com/embeddings for details of the EmbeddingFunction interface.
Please note the recent change to the EmbeddingFunction interface: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023  

**To Reproduce**
1. See python notebook

**Expected behavior**
Kernel.memory should save into the persisted chroma db 

**Screenshots**

**Platform**
- OS: Windows
- IDE: VS code
- Language: Python
- Source: pip
**Additional context**

Requirements.txt has the following

PyPDF2==3.0.1
nltk==3.8.1
pycryptodome==3.15.0
streamlit==1.31.0
azure-search-documents==11.4.0
semantic-kernel==0.5.1.dev0
azure-ai-formrecognizer==3.32

**Comment by bahree** [comment]
I see this too, seems Chroma signature was changed a few months ago, but Semantic Kernel hasn't kept up to it.

```
Lib\site-packages\chromadb\api\types.py", line 211, in validate_embedding_function
    raise ValueError(
ValueError: Expected EmbeddingFunction.__call__ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['args', 'kwargs'])
Please see https://docs.trychroma.com/embeddings for details of the EmbeddingFunction interface.
Please note the recent change to the EmbeddingFunction interface: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023
```

The details are in that link shared; curious if this is on the backlog?

Thanks.
