### ISSUE TITLE
Python: azure_chat_gpt_with_AI_search_data_cross_lingual

### ISSUE THREAD

**Issue by Timothyhuiyukfai** [microsoft/semantic-kernel#4995]
Hi I am having issue in getting the right answer thru SK by acquiring information thru Azure AI search,

**Expected Answer:**
Asking in Chinese or other language, "哪些公司準備拓展沙地阿拉伯的業務?" and reply back in chinese or other language by acquiring existing knowledge in Azure AI search

**Current Answer:**
"The retrieved documents do not contain information about which companies are planning 
to expand their business in Saudi Arabia. The requested information is not available in the retrieved data. Please try another query or topic."

**Reference:**
Previously, there is a repo sample in python, but it got deliberately deleted. the file name is called, "azure_chat_gpt_with_data_api_cross_lingual". SK doesnt support  'cross lingual'?

I have attached code. Thanks
[code_sample.txt](https://github.com/microsoft/semantic-kernel/files/14259052/code_sample.txt)

**Comment by moonbox3** [comment]
Our partners on the Microsoft On Your Data team pulled this kernel example as it wasn't officially supported. Tagging them for any additional follow up. cc: @sarah-widder

**Comment by sarah-widder** [comment]
Hi @Timothyhuiyukfai we are working on official support for multilingual responses - the functionality referenced by that sample is not ready for public use yet. If you’re experiencing a high frequency of “out of domain” responses, you might try reducing the strictness parameter to 1 or 2 (default is 3) to make the model more likely to generate an answer.

**Comment by sarah-widder** [comment]
You can also try putting specific instructions to respond in a particular language in the roleInformation parameter or your prompt template.

**Comment by moonbox3** [comment]
Closing this issue as an answer has been provided. Please re-open or file a new issue if you need further help. Thank you.
