### ISSUE TITLE
.Net: Discussion: Idea behind output_variable & json_schema?

### ISSUE THREAD

**Issue by arynaq** [microsoft/semantic-kernel#5012]
I am looking through the source and trying to figure out what the use case is for output_variable and the json_schema of the type (C# source, Microsoft.SemanticKernel.OutputVariable)

It is not in use anywhere that makes sense to me, is this for future-proofing for a potential scenario where the kernel abstracts enforcement of an output schema when the LLM is being used in json mode?

**Comment by matthewbolanos** [comment]
Yes, this is for future proofing. We will eventually use this information for code-based planners so that the LLM knows what the return type is for complex objects.
