### ISSUE TITLE
RestApiOperationRunner handling of 204 | No Content responses

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#5018]
Today, RestApiOperationRunner.SerializeResponseContentAsync will throw if there is no `MediaType` on the `ContentType` response header. When the response is 204 or No Content, there will not be a ContentType|MediaType available. I'm curious the SK teams thoughts on whether the behavior should be updated in this scenario to not throw and support 204 responses or if this is the expected behavior and design with OpenAPI plugins.

Example yaml:
```yaml
paths:
  /resources/{id}:
    get:
      operationId: getResource
      summary: Get the details of a resource
      parameters:
      - in: path
        name: id
        schema:
            type: string
        required: true
        description: The ID of the resource.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceResponse'
components:
  schemas:
    ResourceResponse:
      type: object
      properties:
        resources:
          type: string
          items:
            type: string
          description: The list of resources.
```

### Function execution with API giving a 204 response
**Expected:**
Empty string is returned

**Actual:**
Exception thrown - `Microsoft.SemanticKernel.Kernelexception - No media type available.`

**Comment by SergeyMenshykh** [comment]
Related - https://github.com/microsoft/semantic-kernel/issues/2648
