### ISSUE TITLE
.Net: Memory and embeddings notebook sample is misleading

### ISSUE THREAD

**Issue by mrochon** [microsoft/semantic-kernel#5027]
**Describe the bug**
The 06-memory-and-embeddings.ipynb sample creates the impression that to use the memory, the system prompt needs to be pre-loaded with all the additional data that is available: there are 5 infoN items defined in the aboutMe collection. Then the same 5 items are loaded into prompt KernelArguments as answers to questions written specifically to have the fact returned as answer. I cannot imagine anyone adding custom data to a chat application. Here are my suggested code changes:

`const string skPrompt = @"
ChatBot can have a conversation with you about any topic.
It can give explicit instructions or say 'I don't know' if it does not have an answer.

Get appropriate information from the memory by using the current user prompt:
**- {{recall $userInput}}**

Chat:
{{$history}}
User: {{$userInput}}
ChatBot: ";

var chatFunction = kernel.CreateFunctionFromPrompt(skPrompt, new OpenAIPromptExecutionSettings { MaxTokens = 200, Temperature = 0.8 });
#pragma warning disable SKEXP0052, SKEXP0003

var arguments = new KernelArguments();

// arguments["fact1"] = "what is my name?";
// arguments["fact2"] = "where do I live?";
// arguments["fact3"] = "where is my family from?";
// arguments["fact4"] = "where have I travelled?";
// arguments["fact5"] = "what do I do for work?";

arguments[TextMemoryPlugin.CollectionParam] = MemoryCollectionName;
arguments[TextMemoryPlugin.LimitParam] = "2";
arguments[TextMemoryPlugin.RelevanceParam] = "0.8";`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by markwallace-microsoft** [comment]
@mrochon Thanks for the feedback. Would you be able to create a PR with your proposed changes?
