### ISSUE TITLE
Python: When python lib release 1.0.0 ?

### ISSUE THREAD

**Issue by yale8848** [microsoft/semantic-kernel#5028]
When python lib release 1.0.0 ?

**Comment by LeonardoSanBenitez** [comment]
I'm very much looking forward for that too :)

**Comment by moonbox3** [comment]
@yale8848 we should have a beta release towards the end of the month/beginning of March. v1 will follow once the work items between the beta features cutline and the v1 cutline are completed. Here is a public [backlog](https://github.com/orgs/microsoft/projects/866/views/3?sliceBy%5Bvalue%5D=python). 

If you'd like to contribute, the more the merrier!

**Comment by moonbox3** [comment]
Closing this issue as there is no related work/follow-up required.
