### ISSUE TITLE
[Feature request] Integration of local LLMs

### ISSUE THREAD

**Issue by lightningRalf** [microsoft/semantic-kernel#503]
Hello,
with the integration of other models like gpt3.5 the first step was made by introducing the ability to make the net wider.
This was shortly discussed in #337. 

So I wanted to ask if there is a chance to widen the net further and introduce more models.
There is already an [open source project that provides an API](https://github.com/hyperonym/basaran) for this, but I dont know if you want to add dependencies.
Just wanted to share, for better understanding what I mean.

Thanks in advance.

**Comment by evchaki** [comment]
@lightningRalf check this out - https://github.com/microsoft/semantic-kernel/blob/main/samples/dotnet/kernel-syntax-examples/Example16_CustomLLM.cs it should get you started on how to do this.

**Comment by dluc** [comment]
@awharrison-28 could you help with some examples? We have some code in the repo which I think would be useful at least to start, while we improve the framework

**Comment by awharrison-28** [comment]
@lightningRalf check out https://github.com/microsoft/semantic-kernel/pull/658 - introduces huggingface models (local) for use with SK. There are a number of examples added in this PR under tests/end-to-end. 

There are still a number of edge cases and scenarios not covered in this PR, but it's a start to a set of features that will quickly grow.
