### ISSUE TITLE
Whisper live connector

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#5032]
Create connector to support live streaming with local whisper model.

**Comment by Krzysztof318** [comment]
`live-audio-streaming processing having this would enable creating real time call center ai support tools... maybe with a whisper local model...
many companies would jump on SK only for this :)
such https://github.com/collabora/WhisperLive or https://github.com/sandrohanea/whisper.net (using whisper.cpp, https://github.com/ggerganov/whisper.cpp)` from @joslat

**Comment by markwallace-microsoft** [comment]
Closing as stale

**Comment by JohnGalt1717** [comment]
Please reopen. this would be great!
