### ISSUE TITLE
.Net Update Audio Interfaces according to Models doc

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#5034]
### OpenAI

According to the Models documentation the interfaces should be names as `ITextToSpeech` and `ISpeechRecognition` accordingly. 

This issue is to keep track of this needed change, according with @matthewbolanos 

| Priority | Model                   | Status      | Interface                      | Deployment type | GitHub issue | Developer   | Reviewer |
| -------- | ----------------------- | ----------- | ------------------------------ | --------------- | ------------ | ----------- | -------- |
| P0       | Text-to-speech          | Complete    | `ITextToSpeech`                | OpenAI API      | TBD          | dmytrostruk | TBD      |
| P0       | Speech-to-text          | Complete    | `ISpeechRecognition`           | OpenAI API      | TBD          | dmytrostruk | TBD      |

**Comment by Krzysztof318** [comment]
I wonder how abstraction should have implemented real-time audio proccessing.
I think it can be done two ways:
1.  Create additional method in these interfaces, but for models which doesn't support live streaming exception will be thrown.
2.  Create ILiveTextToSpeech and ILiveSpeechRecognition
I want to implement whipser-live local models so... #5032
