### ISSUE TITLE
Python: Add Semantic-Kernel-Version header to Azure OpenAI requests for python

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#5038]
To help with debugging, the requests to OpenAI should include a Semantic-Kernel-Version header with the value "dotnet/version-number"

**Comment by moonbox3** [comment]
@matthewbolanos we have [the following](https://github.com/microsoft/semantic-kernel/blob/2322d2deda4bda6a8a49e4b980866a053325bafc/python/semantic_kernel/connectors/telemetry.py#L15) available in Python: if telemetry is enabled, we capture the SK version. Is this sufficient?

**Comment by matthewbolanos** [comment]
If we can match the header name, that'll make the queries a bit easier to run. I'm also concerned about name collisions since "version" seems pretty generic.

**Comment by eavanvalkenburg** [comment]
@matthewbolanos can you check the names and values used in the PR?
