### ISSUE TITLE
python: feature for import native skill from directory

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#505]
at the same point with #337 , I hope semantic-kernel supports native function import from directory.

@jjhenkel 
> 3. You want to be able to easily import skills that use chat backends from a directory (this is easy for functions that use a text completion backend, but not for ones using chat backends yet)

I think this makes code more clearer while initializing kernel and skills

**Comment by evchaki** [comment]
@joowon-dm-snu , thanks for the item.  Looks like a PR is in, we will take a look

**Comment by dluc** [comment]
see https://github.com/microsoft/semantic-kernel/pull/506

**Comment by joowon-dm-snu** [comment]
#506 merged
