### ISSUE TITLE
Python: Generated plan doesn't have 'function.' as node tag

### ISSUE THREAD

**Issue by HuskyDanny** [microsoft/semantic-kernel#5064]
**Describe the bug**
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/1ff6989e-19fe-43de-b7d2-ee1375bec692)
The generated plan doesn't follow the prompt instructs to, causing error on parsing functions which need 'function.' as their node tag

**To Reproduce**
gpt3.5turbo to call it with SequentialPlanner

**Expected behavior**
'function.' should be there for every functions and they all could be parsed out

**Screenshots**

**Platform**
 - OS: windows
 - IDE: VS Code
 - Language:Python
 - Source: semantic-kernel==0.4.7.dev0

**Additional context**

**Comment by evchaki** [comment]
@HuskyDanny  - have you tried this using the latest Python package 0.9? and with GPT-4?
