### ISSUE TITLE
.Net: AzureOpenAIChatCompletionService 'builder inconsistency': one of the constructors does not have the  HttpClient parameter while the others has it.

### ISSUE THREAD

**Issue by joslat** [microsoft/semantic-kernel#5065]
**Describe the bug**
When i try to invoke the AzureOpenAIChatCompletion builder, in one of them you cannot provide your custom HttpClient, so it is inconsistent with the other builders.

this is located in https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.OpenAI/OpenAIServiceCollectionExtensions.cs 
you can compare the method in line 43 vs the one in 76

**To Reproduce**

You can add an HttpClient here:
```
        var builder = Kernel.CreateBuilder();
        builder.AddAzureOpenAIChatCompletion(
            deploymentName: modelDeploymentName,
            endpoint: azureOpenAIEndpoint,
            apiKey: azureOpenAIApiKey,
            modelId: "gpt-4-32k",
            httpClient: new HttpClient { Timeout = TimeSpan.FromMinutes(5) }
        );
```

But not here:
```
        var builder = Kernel.CreateBuilder();
        builder.Services.AddAzureOpenAIChatCompletion(
            modelDeploymentName,
            azureOpenAIEndpoint,
            azureOpenAIApiKey,
            modelId: "gpt-4-32k"
        );
```

**Expected behavior**
The methods should behave in the same way, consistently.

**Comment by stephentoub** [comment]
This was a purposeful choice. The method targeting IServiceCollection is explicitly about using dependency injection, so the HttpClient is expected to come from the DI container.

**Comment by joslat** [comment]
Hi @stephentoub , thanks 1000! for responding so fast!!

I guessed that could be intended, as there is a HttpClient provider on the ServiceCollection (factory) - but in case of a lengthy operation wouldn't it be nice we could override it if we want? that's another reason i proposed that. 

I am doing now a handlebars prompt with 10+ elements and on each I am scrapping a link on each entry and with the scraped content, summarizing it.. for each one...

So if this depends on a service should I configure all HttpClients to have a 10+ minute timeout? or wouldn't be better i could override just on this point?

**Comment by frederikrosenberg** [comment]
We have a similar problem. We would like to have the HttpClient come from the DI container, however unless we setup the default client there is no way to provide the HttpClient. It would be great if we could provide a named HttpClient from DI container.

**Comment by joslat** [comment]
It is mentioned in a link above but just in case, here is the PR for this: https://github.com/microsoft/semantic-kernel/pull/5066

**Comment by stephentoub** [comment]
> So if this depends on a service should I configure all HttpClients to have a 10+ minute timeout? or wouldn't be better i could override just on this point?

Setting it here means you lose everything else related to HttpClient that comes from the DI container. If you actually have a KernelBuilder, then you can use the AddXx method on the builder that accepts a client. And if instead you're actually working with an IServiceContainer, then passing an HttpClient here means you're not factoring in anything else related to HttpClient that was configured; the concern with providing it is it's a footgun.

> We would like to have the HttpClient come from the DI container, however unless we setup the default client there is no way to provide the HttpClient.

If you want the HttpClient to come from the DI container, I don't understand how the proposed overload helps you. Can you elaborate? I'd expect you'd want to retrieve the IHttpClientFactory from the service provider, which you don't have at this point. Instead, you'd instead want to write something like this (which you can do today):
```C#
services.AddTransient<IChatCompletionService>(sp =>
{
    IHttpClientFactory httpClientFactory = sp.GetRequiredService<IHttpClientFactory>();
    return new AzureOpenAIChatCompletionService("deploymentName", "endpoint", "apikey", httpClient: httpClientFactory.CreateClient("name"));
});
```
The AddXx methods are there for the most common case. For the long tail where you want more fine-grained control, you can always do the registration yourself with such a callback that pulls whatever it needs from DI and constructs the service directly.

**Comment by joslat** [comment]
Your approach is better and makes completely sense, @stephentoub - thanks for the examples!

**Comment by frederikrosenberg** [comment]
Argh, I overlooked that, thanks for the examples!
