### ISSUE TITLE
WebSearch Results using the Bing Connector has a hard code value of count=1. We need to to return more than 1 result or should be able to pass count of result requested

### ISSUE THREAD

**Issue by Tbablani** [microsoft/semantic-kernel#508]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by evchaki** [comment]
@Tbablani , thanks for the idea, we can take a look.

**Comment by Tbablani** [comment]
Hi All

I tried to change the interface and create a method which will accept a count. SK solution complied properly but when I was trying to test it giving error when trying to initiate the kernel

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shawncal** [comment]
Fixed with https://github.com/microsoft/semantic-kernel/pull/556

**Comment by Tbablani** [comment]
For this fix , do you have the latest nuget package
________________________________

**Comment by danf25** [comment]
I have the same problem.

Thank you for your time.
Danf
