### ISSUE TITLE
Python: Handling Multiple AI Services

### ISSUE THREAD

**Issue by HuskyDanny** [microsoft/semantic-kernel#5083]
**Describe the bug**
Essentially, I want to get a clear path on how to handle different AI service, so that I could use gpt4 for semantic function A and gpt3.5 for semantif function B.

I tried a bit by having the single kernel and specifcying the service_id in the request setting. But it still uses the original default service.
**To Reproduce**
1. Adding service and set default
```
            kernel.add_chat_service(
                "azure_openai_chat35_service",
                sk_oai.AzureChatCompletion(
                    deployment_name=chat35_api_config.deployment_model_id,
                    api_key=chat35_api_config.key,
                    endpoint=chat35_api_config.endpoint,
                ),
            )

            kernel.add_chat_service(
                "azure_openai_chat4_service",
                sk_oai.AzureChatCompletion(
                    deployment_name=chat4_api_config.deployment_model_id,
                    api_key=chat4_api_config.key,
                    endpoint=chat4_api_config.endpoint,
                ),
            )
            kernel.set_default_chat_service("azure_openai_chat35_service")
```
2. Calling with settings
```
        refactor_code = self.get_semantic_function(kernel, "skills", "Generate")
        settings = AzureChatRequestSettings(
            service_id="azure_openai_chat4_service", ai_model_id="gpt4-32k"
        )
        response = await refactor_code.invoke_async(context=context, settings=settings)
```
3. It still uses 35 service to call

**Expected behavior**
chat4_service instead should be used to call

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language:  Python
 - Source: 0.4.6dev

**Additional context**

**Comment by markwallace-microsoft** [comment]
@moonbox3 here's a sample showing the pattern supported in .Net https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example61_MultipleLLMs.cs

**Comment by eavanvalkenburg** [comment]
@HuskyDanny  We have support for this incoming soon, this is already present in the feature branch that we have to get together a bunch of big changes, it has a AIServiceSelector class, that uses the service_id and settings to pick the right service (similar to how that is done in dotnet), check it out here: https://github.com/microsoft/semantic-kernel/blob/python_kernel_args_latest/python/semantic_kernel/services/ai_service_selector.py

**Comment by HuskyDanny** [comment]
sounds good, excited for the new release
