### ISSUE TITLE
Python: TypeError when save point to existing in `QdrantMemoryStore`

### ISSUE THREAD

**Issue by ytoml** [microsoft/semantic-kernel#5089]
**Describe the bug**
Encounter the error when using `save_information` to save memory on the same id.

**To Reproduce**
1. `save_information` with some id.
2. do 1 again

**Expected behavior**
The embedding is overwritten.

**Screenshots**

**Platform**
 - OS: Mac
 - IDE: VSCode
 - Language: Python 
 - Source: 0.5.0.dev0

**Additional context**

**Comment by ytoml** [comment]
I found where to fix. I will make PR.

**Comment by moonbox3** [comment]
Related to PR #5792

**Comment by moonbox3** [comment]
We're re-doing our memory abstractions, which can be see here: #6689. Assign issue to @eavanvalkenburg.

**Comment by moonbox3** [comment]
@eavanvalkenburg is this item still relevant? Can we close?
