### ISSUE TITLE
.Net: validate all Blocks at creation time for syntax, remove is_valid, improve error message, sync with Python.

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/semantic-kernel#5109]
**Describe the bug**

We noticed that some Blocks are not parsed and checked for syntax at creation time, but only for validity at runtime, this is not ideal as a issue with a variable or value block is thus not raised when first loading a template, in python we fixed this in #5014. 

This introduces regexes specific for each Block, those are used for parsing, and a extensive error message is displayed with proper info on what a valid block looks like is returned then. 

This also means that is_valid as a construct can be removed, because a Block is created validly, and other issues, like non-existing function are checked during rendering.

Several edge case tests are no longer valid for creation so they are moved to syntax error tests or removed completely. 

This behaviour should be replicated in dotnet.

**Comment by markwallace-microsoft** [comment]
@eavanvalkenburg when you have a Python fix can you transfer this issue to me and I'll handle the .Net side.

FYI @johnoliver
