### ISSUE TITLE
Python: StepwisePlanner does not work with a Llama2 instance

### ISSUE THREAD

**Issue by Ndymario** [microsoft/semantic-kernel#5124]
**Describe the bug**
When attempting to use the StepwisePlanner with an OllamaChatCompletion agent, I get a "400 Bad Request" error.

**To Reproduce**
1. Add OllamaChatCompletion to the kernel using `.add_chat_service()`
2. Create an instance of a StepwisePlanner with the kernel
3. Create a plan with the StepwisePlanner
4. Invoke the plan

**Expected behavior**
I expect a similar response that using the ChatGPT agent provides, where the AI is able to generate a plan and respond with an answer to my prompt.

**Platform**
 - OS: macOS 14.3.1 (M2)
 - IDE: VS Code
 - Language: Python
 - Source: pip using the Quickstart `semantic-kernel==0.5.1.dev0`

**Additional context**
Here is the code I am using:
```py
import asyncio
import semantic_kernel as sk
from semantic_kernel.planning.stepwise_planner import StepwisePlanner
from semantic_kernel.connectors.ai.ollama.services.ollama_chat_completion import OllamaChatCompletion
from semantic_kernel.connectors.ai.ollama.ollama_prompt_execution_settings import OllamaPromptExecutionSettings
from plugins.math_plugin import MathPlugin

async def main():
    # Initialize the kernel
    kernel = sk.Kernel()
    # Add a text or chat completion service using either:
    # kernel.add_text_completion_service()
    # kernel.add_chat_service()
    kernel.add_chat_service("chat_completion", OllamaChatCompletion(ai_model_id='llama2', url='http://localhost:11434/api/generate'))

    # Import the MathPlugin.
    kernel.import_plugin(MathPlugin(), plugin_name="MathPlugin")

    planner = StepwisePlanner(kernel)

    ask = "What is the square root of 2"

    # Create a plan
    plan = planner.create_plan(ask)

    # Execute the plan
    result = await plan.invoke()
    print("Plan results:")
    print(result)


# Run the main function
if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
```
The Math plugin is the same as found in [Python example 08](https://github.com/MicrosoftDocs/semantic-kernel-docs/blob/main/samples/python/08-Creating-Functions-For-AI/plugins/MathPlugin.py)

**Comment by juharris** [comment]
I ran into something similar with `OllamaTextCompletion`.

It might be because `ai_model_id` doesn't get passed in the Ollama API call as the `"model"` parameter.

You might need something like
```python
settings = OllamaChatPromptExecutionSettings(ai_model_id='llama2')
```

and then pass those settings into one of the method on the `kernel`.

Alternatively, a fix to SK could be that `OllamaChatCompletion` uses `self.ai_model_id` when making the `json` to pass in the request.
