### ISSUE TITLE
.Net: AgentBuilder is not working with Azure OpenAI

### ISSUE THREAD

**Issue by masonsawtell** [microsoft/semantic-kernel#5126]
**Describe the bug**
When creating an AgentBuilder, using the WithAzureOpenAIChatCompletion function with model set to the deployment name will result in a 404 error. 

**To Reproduce**
1. Initialize a new AgentBuilder
2. Call builder.WithAzureOpenAIChatCompletion(endpoint, model, apiKey).BuildAsync()
3. See error

**Expected behavior**
The AgentBuilder builds successfully with my Azure OpenAI deployment.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/107892774/f18cd8d6-3449-49ce-8e06-766aa136006d)
![image](https://github.com/microsoft/semantic-kernel/assets/107892774/4c8bd07b-ec1f-43e2-a86a-4e0cfd7059c0)

**Platform**
 - OS: Windows 11
 - IDE: VS Code
 - Language: C#
 - Source: Semantic Kernel Version 1.4.0, Semantic Kernel Agents Version 1.4.0-alpha

**Additional context**
I also tried this with other combinations of deployment id, deployment version, API version, and with both gpt-4 and gpt-3.5 models.

**Comment by crickman** [comment]
Hi @masonsawtell, thank you for reporting this.  

I've setup a repro case as follows:

```
#pragma warning disable SKEXP0101 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.

using Microsoft.SemanticKernel.Experimental.Agents;

namespace AzureAgentTest;

internal class Program
{
    static async Task Main(string[] args)
    {
        var agent =
            await new AgentBuilder()
                .WithAzureOpenAIChatCompletion(Config.AzureAI.Endpoint, Config.AzureAI.ModelName, Config.AzureAI.ApiKey)
                .BuildAsync();

        try
        {
            Console.WriteLine(agent.Id);
        }
        finally
        {
            await agent.DeleteAsync();
        }
    }
}
```

And am seeing the following output: `asst_RQxBlEy3eFaQmVrYOG0cgiDF`

Could you please verify that you are targeting an endpoint in which the Assistant API is available?

https://learn.microsoft.com/en-us/azure/ai-services/openai/assistants-quickstart

> Azure OpenAI Assistants are currently available in Sweden Central, East US 2, and Australia East.

**Comment by masonsawtell** [comment]
Hi, thanks for the reply! I tried switching the endpoint to one with Assistants enabled and it did work. Thank you, and sorry for the silly question!

**Comment by crickman** [comment]
Glad to hear.  I feel certain this will be a useful issue to have available for others.  Thanks for posting!
