### ISSUE TITLE
.Net: Plan produced by Handlebars planner doesn't follow the right format

### ISSUE THREAD

**Issue by sherylZhaoCode** [microsoft/semantic-kernel#5135]
**Describe the bug**
Plans produced by handlebars planner don't follow the right format so the results can't be parsed correctly

**To Reproduce**
Try asking some questions, and see if the plan has only one ```Handlebars ``` structure. 

**Expected behavior**
The plan produced should wrap all the plan inside the ```Handlebars ``` structure

**Screenshots**
Below are some examples of the failures
<img width="1648" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/59749074/bc3401a6-d249-4769-b687-0de56c11b8e0">
<img width="1651" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/59749074/1d6c3676-d5d5-4d0a-8bb5-3bdb9c8ed1a3">
<img width="1271" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/59749074/81eeb00d-8eca-4c3f-afe8-6ef9bafcdba7">

**Platform**
 - OS: Mac
 - Language: C#

**Additional context**

**Comment by evchaki** [comment]
@sherylZhaoCode we just put in additional handling for this.  Try to use the latest build and see if that solves your issue.
