### ISSUE TITLE
.Net: [Agents] Support FunctionCallContent

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#5153]
There are scenarios that require function calls across multiple models and agents. Today, our function calls are tied closely with the OpenAI connector, so it's difficult to reuse the same code for the Gemini connector and to allow agents to pass function calls to one another (AutoGen scenario)

This issue is to capture the work necessary to make the current implementation generic. This should include introducing a new 'FunctionCallContent' type that includes (at a minimum) the a reference to the 'KernelFunction' to be called and the arguments to call. This content type should then appear in the item collection for 'ChatMessageContent'.

As part of this change, all existing function calling behavior should still "work".

## Scenarios
As part of this issue, the following scenarios should be supported:
- **Core abstraction support** – A developer should be able to use function calls and tool results in `ChatHistory` and `ChatMessageContent` objects without relying on the OpenAI package.
- **Serialization/Deserializaion** – A developer should be able to serialize a `ChatHistory` object with function calls and tool results so they can rehydrate it in the future (and potentially run the `ChatHistory` with a different AI model).
- **Works with any model** – Any AI service (that supports tools) can consume tool calls and tool results without having service specific classes. This includes Gemini, Mistral, Anthropic, and Llama.
- **Passing function alls** – In multi-agent scenarios, one agent can create a tool call for another agent to complete it.
- **Simulated function calls** – A function call can be simulated by a developer; in other words, a developer should be able to add a `ChatMessageContent` with a tool call they created to a `ChatHistory` object and then run it with any AI model (this may require simulating tool call IDs in the case of OpenAI). This is helpful when a developer wants to templatize context and system prompts aren't working.
- ~~**YAML support for function calls** – A function call and tool result can be written in a YAML prompt template using the intermediate prompt template language. This will allow a developer to implement few shot examples for function calling within prompts. A new tag (e.g., `<FunctionCall>` is likely necessary to achieve this).~~
- ~~**YAML support for function results** – A function result can be written in a YAML prompt template as a tool message.~~
- ~~**YAML support for defining available functions** – as a prompt engineer, you should be able to state which functions are available for the LLM to call.~~

~~If possible, we should try to align the syntax with [.promptfile](https://promptfile.org/blocks). They use `<functions>` and `<function>` tags.~~

The YAML scenarios/requirements are moved to the issue -https://github.com/microsoft/semantic-kernel/issues/5632 to be prioritized separately.

**Comment by crickman** [comment]
Not agent specific...as desrcribed, this has to do with core connector framework / abstractions.

**Comment by SergeyMenshykh** [comment]
@matthewbolanos, FYI, the `AzureOpenAIChatCompletionWithDataService` does not use the current SK function-calling model as the {Azure}OpenAIChatCompletionService does. Therefore, it was suggested not supporting function call content for it now and considering it later when/if needed.
