### ISSUE TITLE
Java: Blog post for RC1/RC2/V1.0 preparations

### ISSUE THREAD

**Issue by d3r3kk** [microsoft/semantic-kernel#5166]
We will likely want a blog post to accompany the Java SK RC1/RC2/V1 releases incoming. To discuss with @karianna as well to ensure we hit all the topics our users will be curious about.

**Comment by karianna** [comment]
RC2 Blog post prepared, I'll ping you offline to get added to this project properly so I can close issues :-)

**Comment by karianna** [comment]
Internal Comms sent out - SK PM leads are figuring out which devblog to post content on.

@dsgrieve Thanks for the reviews BTW.

**Comment by karianna** [comment]
https://devblogs.microsoft.com/java/java-sdk-for-semantic-kernel-1-0-0-rc2-released-add-ai-capabilities-to-your-java-app-today/ is live
