### ISSUE TITLE
.Net: [.NET] Agent created via CreateAgentBuilder() fails when Plugin does not return a string.

### ISSUE THREAD

**Issue by HadiKotaich** [microsoft/semantic-kernel#5168]
**Describe the bug**
While following the agents collaboration sample, I was able to make it work as is, and it worked when I added to one of the agents a plugin with a function returning a string. However the sample fails when one of the agents uses a plugin which does not return a string. In my case, it was retuning a list of a custom object I defined which is "CUSTOMOBJECT". The scenario works well when I make the plugin return a string instead.

**To Reproduce**
1. Follow https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example72_AgentCollaboration.cs
2. Add a plugin to one of the agents where the plugin does not return a string, it returns a list of custom objects instead.
3. Run a query which triggers this plugin.

**Expected behavior**
My understanding is that we are not restricted that our plugins return a string.

**Screenshots**

**Platform**
 - OS: [Windows]
 - IDE: [Visual Studio]
 - Language: [C#]
 - Source:

PackageReference Include="Microsoft.SemanticKernel" Version="1.4.0" />
PackageReference Include="Microsoft.SemanticKernel.Abstractions" Version="1.4.0" />
PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.4.0" />
PackageReference Include="Microsoft.SemanticKernel.Experimental.Agents" Version="1.4.0-alpha" />
PackageReference Include="Microsoft.SemanticKernel.Planners.Handlebars" Version="1.4.0-preview" />
PackageReference Include="Microsoft.SemanticKernel.Planners.OpenAI" Version="1.4.0-preview" />
PackageReference Include="Microsoft.SemanticKernel.PromptTemplates.Handlebars" Version="1.4.0" />

**Additional context**
**ERROR:**
System.InvalidCastException: Cannot cast System.Collections.Generic.List`1[CUSTOMOBJECT] to System.String

**Stack trace:**
FunctionResult.GetValue[T]()
<<ProcessFunctionStepAsync>g__InvokeFunctionCallAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
ChatRun.ProcessFunctionStepAsync(String callId, FunctionDetailsModel functionDetails, CancellationToken cancellationToken)
ChatRun.GetResultAsync(CancellationToken cancellationToken)+MoveNext()
Boolean>.GetResult()
ChatThread.InvokeAsync(IAgent agent, String userMessage, KernelArguments arguments, CancellationToken cancellationToken)+MoveNext()
ChatThread.InvokeAsync(IAgent agent, String userMessage, KernelArguments arguments, CancellationToken cancellationToken)+MoveNext()
Boolean>.GetResult()
AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) line 49
AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) line 91
AsyncEnumerableHelpers.ToArray[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) line 16

**Comment by markwallace-microsoft** [comment]
Closing this as the Experimental Agents package has been replace with the new alpha version of Agent support
