### ISSUE TITLE
Python: `ModuleNotFoundError: No module named 'semantic_kernel.prompt_template'`

### ISSUE THREAD

**Issue by anotherkirillryzhov** [microsoft/semantic-kernel#5172]
**Describe the bug**
`from semantic_kernel.prompt_template.input_variable import InputVariable` fails with the exception `ModuleNotFoundError: No module named 'semantic_kernel.prompt_template'`

This most probably happens because of missing '__init__.py' in `https://github.com/microsoft/semantic-kernel/tree/main/python/semantic_kernel/prompt_template`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by eavanvalkenburg** [comment]
@anotherkirillryzhov what are you trying to import, I did notice that that folder does not have a __init__ file in it which causes that message, but you should be able to just import from one level deeper, like `from semantic_kernel.prompt_template..kernel_prompt_template import KernelPromptTemplate`
