### ISSUE TITLE
Java: Create tests to ensure tool call behaviour is correct

### ISSUE THREAD

**Issue by d3r3kk** [microsoft/semantic-kernel#5186]
The package:
- com.microsoft.semantickernel.orchestration

...contains few tests to ensure the functionality remains intact as we make changes.

Create unit tests (and optionally integration tests if it makes sense to do so) for this package and have them reviewed by the team to ensure we cover the most important/most complicated parts.

Consider using OpenAI to help construct these tests! 📎

**Comment by dsgrieve** [comment]
https://github.com/microsoft/semantic-kernel/pull/5268 merged
