### ISSUE TITLE
.Net: [Agents] Use ToolCallBehavior for tools calling in Agent

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#5200]
Today, the chat completion API, used by ChatCompletionAgent, uses the tool-calling mechanism, the behavior (auto/manual/list of functions) of which is regulated by the ToolCallBehavior class. The Agent class uses its own function-calling mechanism, similar to the ToolCallBehavior.Auto behavior.
   
From the consumer code perspective, it would be beneficial if all agents use the same approach to tool-calling. This way, developers wouldn't need to know the specifics of each agent regarding function-calling and could use the method they are already familiar with instead.

This issue can be related to this one - [.Net: [Agents] Support FunctionContent](https://github.com/microsoft/semantic-kernel/issues/5153)

- [ ] Come up with the design
- [ ] Share/present the design
- [ ] Implement it

**Comment by stephentoub** [comment]
We also need to generalize the tool calling stuff, which right now is mostly OpenAI-specific. But other models and services support functions/tools, so we should be looking at a more service-agnostic representation, which then presumably would also be what shows up in the agents surface area.

**Comment by markwallace-microsoft** [comment]
Related to https://github.com/microsoft/semantic-kernel/issues/5253

**Comment by markwallace-microsoft** [comment]
Closing as stale
