### ISSUE TITLE
.Net:  Reduce dependencies used by SK Abstractions project

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#5226]
Goal is the dependency list will drop to just Microsoft.Extensions.DependencyInjection.Abstractions.dll and Microsoft.Extensions.Logging.Abstractions.dll.

- [x] Remove System.Memory.Data. BinaryData is just a convenience type introduced for the Azure SDK. It's not necessary, byte[] / Stream / ReadOnlyMemory<byte>... any or all of those is fine. BinaryData was introduced as a way to accept any of those three and then present any of those three out to a consumer. - https://github.com/microsoft/semantic-kernel/pull/5229
- [ ] Copy the minimum-needed source from the JSON schema lib into the abstractions lib so that dependency can be clipped.
- [ ] Add a net6.0 (and net8.0) asset that removes the netstandard dependency and the dependency's that are effectively polyfills for things in .NET Core itself

**Comment by ihvo** [comment]
@SergeyMenshykh, are you ok if I take this issue?

**Comment by ihvo** [comment]
> @SergeyMenshykh, are you ok if I take this issue?

A bit late I guess :)

**Comment by SergeyMenshykh** [comment]
> > @SergeyMenshykh, are you ok if I take this issue?
> 
> I was a bit late I guess :)

Hi @ihvo, sorry, I already started :)
