### ISSUE TITLE
Python: AttributeError: 'Kernel' object has no attribute 'run_async'

### ISSUE THREAD

**Issue by sv-youn** [microsoft/semantic-kernel#5233]
**Describe the bug**
running await kernel.run_async(summary_function, input_str=sk_input) gives the error
**Platform**
 - OS: Windows
 - IDE: anaconda terminal
 - Language: Python

**Comment by eavanvalkenburg** [comment]
@sv-youn this was replaced by `kernel.invoke` in the latest versions, which version are you using?

**Comment by sunner** [comment]
We met exactly the same issue.

**Comment by moonbox3** [comment]
@sv-youn, @sunner in 0.5.1.dev0, it is indeed `kernel.run` (we removed the _async suffix from methods that don't have a sync counterpart). Now, as of 0.9.0b1 (our first beta release) the kernel method is `invoke`.

**Comment by sv-youn** [comment]
@moonbox3 thanks for the update. The Python tutorial doesn't align with the current version, which presents a challenge.

**Comment by moonbox3** [comment]
@sv-youn our Python notebooks/kernel examples are always updated to use the latest code. We're now on version `0.9.0b1` where the kernel uses methods like `invoke` and `invoke_stream`. Thus, one can use a poetry virtual environment, and utilize that latest code or one can install the latest pip package as shown in the notebook.

**Comment by sv-youn** [comment]
Thanks for responding @moonbox3. It seems the Python tutorial notebooks are not synchronized with the latest code version. Despite cloning the latest version (0.9.0b), I encountered an error when attempting the first notebook: semantic-kernel/python/notebooks/00-getting-started.ipynb
<img width="492" alt="error" src="https://github.com/microsoft/semantic-kernel/assets/58833784/b3c925f0-7b90-4634-aba6-b2600e74a998">

**Comment by moonbox3** [comment]
@sv-youn, thanks for the screenshot. I'll create a PR to fix the small bug that is present. To run this cell, please remove the `service_id` argument from the `import_plugin_from_prompt_directory` call.

**Comment by sv-youn** [comment]
Thanks for responding, @moonbox3. Removing that argument did indeed fix the error. However, I encountered another error in the subsequent cell.
![e2](https://github.com/microsoft/semantic-kernel/assets/58833784/baa7d6c5-5f30-40c3-98b3-7637ba07ec7f)

**Comment by moonbox3** [comment]
@sv-youn, I've got a PR out to fix that as well. :) Right now, you can update the service_id to be `default` as I have done [here](https://github.com/microsoft/semantic-kernel/pull/5328/files#diff-d6b69bd3938edd2d0ed0ed3c9d5a51a601e67c2ded53960e4255b5b129b62321R92). The sample plugins have their service_ids as 'default' so I am leaving them as default as well (one can customize the service_ids if needed).

**Comment by sv-youn** [comment]
Wow, that works. Thank you @moonbox3. I encountered another error while running cell #10 (skipping the 1st installation cell) in the 06-memory-and-embeddings notebook. 
![e1](https://github.com/microsoft/semantic-kernel/assets/58833784/cf0ea0ca-711f-44d7-ae20-feb9e3f5a90d)

**Comment by moonbox3** [comment]
@sv-youn that `create_function_from_prompt` needs a `function_name` str and a `plugin_name` str. I'll add that to the PR (and other notebooks that may be missing it). Thanks for the heads up.

**Comment by sv-youn** [comment]
Again thanks for your response @moonbox3. While working on implementing a permanent solution, is there any stopgap fix we can apply in the meantime?

**Comment by moonbox3** [comment]
Everything I have been mentioning here, you can implement it on your end. Provide a function_name/plugin_name for the `create_function_from_prompt` and it'll work. We'll make a new release in the next day or two with these fixes.

**Comment by sv-youn** [comment]
Thanks for the suggestion @moonbox3. I was able to fix it by providing names in create_function_from_prompt per your suggestion. I encounter another error. Are you able to see if we can quickly fix it? 
![e3](https://github.com/microsoft/semantic-kernel/assets/58833784/1be285eb-1da3-4650-a575-0b2bc66cea52)
