### ISSUE TITLE
.Net: Make the OpenAI connector more configurable

### ISSUE THREAD

**Issue by Nurgo** [microsoft/semantic-kernel#5238]
**Motivation:**
The OpenAI API seems to be becoming a de facto standard, with many LLM providers using or inspired by it. Making the OpenAI connector more configurable would make it easy to use for other LLMs.

**Advantages:**
- **Code reuse:** Streamlining the integration of LLMs that follow the OpenAI API structure, thus minimizing redundant development efforts.
- **Accelerated support for new LLMs:** Simplifying the support of some new LLMs, potentially reducing it to the creation of a factory that configures an OpenAI connector specifically them.

**Example:**
Consider the case of Mistral AI, whose LLMs utilize a subset of the OpenAI API and supports function calls with identical syntax. While its URL structure mirrors that of OpenAI, Mistral does not support certain settings (e.g., `FrequencyPenalty`, `PresencePenalty`, `StopSequences`) and introduces new ones (e.g., `SafeMode`), alongside specific restrictions on message roles (the 'System' role can only be used at the start of a conversation, the last message must have a 'User' role).

**Suggested Enhancements:**
To accommodate such variations, I propose exploring the possibility of making the following aspects of the OpenAI connector configurable:
- API endpoint and URL structure (already possible via a custom `HttpClient`, but could be made easier).
- Enabling/disabling specific settings.
- Addition of new settings unique to different LLMs.
- Disabling/enabling certain functionalities (e.g., function calls, vision, agents).
- Implementing restrictions on message roles (e.g., `System` role usage limited to the beginning of a conversation).

**Comment by matthewbolanos** [comment]
Unfortunately, because we have a dependency on the Azure OpenAI SDK to connect with OpenAI API models and services, we are unable to add much of this functionality. We will create a new issue to implement some of this functionality if/when the underlying Azure OpenAI SDK supports these configurations.
