### ISSUE TITLE
.Net: AzureOpenAI GetChatMessageContentsAsync does not surface finish reason properly

### ISSUE THREAD

**Issue by AieatAssam** [microsoft/semantic-kernel#5240]
**Describe the bug**
When making a call to GetChatMessageContentsAsync one receives a text-based response as well as metadata containing content filter results. However, when Azure OpenAI triggers its internal content filter, it doesn't always populate content_filter_results field, instead setting "finish_reason" to "content_filter" instead of regular "stop":
```json
{
    "id": "chatcmpl-<REDACTED>",
    "object": "chat.completion",
    "created": 1709204276,
    "model": "gpt-35-turbo",
    "prompt_filter_results": [
        {
            "prompt_index": 0,
            "content_filter_results": {
                "hate": {
                    "filtered": false,
                    "severity": "safe"
                },
                "self_harm": {
                    "filtered": false,
                    "severity": "safe"
                },
                "sexual": {
                    "filtered": false,
                    "severity": "safe"
                },
                "violence": {
                    "filtered": false,
                    "severity": "safe"
                }
            }
        }
    ],
    "choices": [
        {
            "finish_reason": "content_filter",
            "index": 0,
            "message": {
                "role": "assistant",
                "content": ""
            },
            "content_filter_results": {
                "hate": {
                    "filtered": false,
                    "severity": "safe"
                },
                "self_harm": {
                    "filtered": false,
                    "severity": "safe"
                },
                "sexual": {
                    "filtered": false,
                    "severity": "safe"
                },
                "violence": {
                    "filtered": false,
                    "severity": "safe"
                }
            },
            "logprobs": null
        }
    ],
    "usage": {
        "prompt_tokens": 510,
        "completion_tokens": 34,
        "total_tokens": 544
    },
    "system_fingerprint": "fp_<REDACTED>"
}
```
Above is a real response from the API via chat/completions?api-version=2024-02-15-preview
Content filter stop reason is not captured by SemanticKernel and when decoding the response into ChatMessageContent there is no indication of failure - response just appears to be blank.

**To Reproduce**
1. Create kernel via the following:
``` csharp
var builder = Kernel.CreateBuilder();
builder.AddAzureOpenAIChatCompletion("DEPLOYMENT", "ENDPOINT", "KEY");
// Get the chat completion service
Kernel kernel = builder.Build();
var chatService = kernel.GetRequiredService<IChatCompletionService>();
```
substituting correct values for Azure openAI parameters

2. Create history:
``` csharp
var history = new ChatHistory();
history.AddSystemMessage("Echo back user's request");
history.AddUserMessage("NAUGHTY WORD HERE");
```
Place abbreviation that can be misinterpreted into the user message placeholder. Mine triggered when analysing industry standard acronyms and coming across Water Oil Gas.
3. Execute the LLM inference:
``` csharp
var result = await chatService.GetChatMessageContentsAsync(history);
```
4. Examine __result[^1]__ and you will notice it has blank string for content but no way of determining that the issue is down to content flagging
5. Reproduce the call via POST to same Azure OpenAI endpoint in Postman with the following body:
``` json
{
  "messages": [{"role":"system","content":"Echo back user's request"},{"role":"user","content":"NAUGHTY WORD HERE"}],
  "max_tokens": 800,
  "temperature": 0.7,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "top_p": 0.95,
  "stop": null
}
```

**Expected behavior**
When finish reason is content_filter, we need to ensure either an exception is generated or ChatMessageContent has a flag identifyig this as such.

**Platform**
 - OS: Windows 11
 - IDE: VS Code
 - Language: C#
 - Source: Microsoft.SemanticKernel, 1.5.0
Microsoft.SemanticKernel.Connectors.OpenAI, 1.5.0

**Comment by matthewbolanos** [comment]
@RogerBarreto, can you confirm if this was already fixed?
