### ISSUE TITLE
.Net: Task<HandlebarsPlan>' does not contain a definition for 'InvokeAsync' and no accessible extension method

### ISSUE THREAD

**Issue by uday31in** [microsoft/semantic-kernel#5248]
**Describe the bug**

Task<HandlebarsPlan>' does not contain a definition for 'InvokeAsync' and no accessible extension method

**To Reproduce**

'''
var planner = new HandlebarsPlanner(new HandlebarsPlannerOptions() { AllowLoops = true });
var plan = planner.CreatePlanAsync(kernel, ask);
var result = (plan.InvokeAsync(kernel)).Trim();
'''

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [Mac]
 - IDE: [VS Code]
 - Language: [C#]
 - Source: [ <PackageReference Include="Microsoft.SemanticKernel" Version="1.5.0" />]

**Comment by stephentoub** [comment]
`CreatePlanAsync` returns a `Task<HandlebarsPlan>` rather than `HandlebarsPlan`. You need to `await` it:
```C#
var plan = await planner.CreatePlanAsync(kernel, ask);
```

**Comment by uday31in** [comment]
Thanks @stephentoub  for the response.

<img width="827" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/14359777/42616ef3-d3ef-4f1f-bbaf-d33f92f43b16">
Issue is

Problem is this part.

var result = (await plan.InvokeAsync(kernelWithMath)).Trim();

**Comment by matthewbolanos** [comment]
Assigning to myself to get this addressed; Thanks for filing this issue.

**Comment by matthewbolanos** [comment]
Closing as development on the handlebars planner is on pause as we develop a python planner
