### ISSUE TITLE
Text Embedding service has not been supplied - Github Repos Q&A Bot lab

### ISSUE THREAD

**Issue by bzbwqz** [microsoft/semantic-kernel#525]
Running Openai API key with text-embedding-ada-002 model and get error as attached.

Does anyone know the solution for fixing? Thanks.

**Screenshots**
<img width="424" alt="56441189d5d7448724957516e27d10b" src="https://user-images.githubusercontent.com/34880208/233049299-112a706f-18b4-4320-acb4-63c03c75384f.png">
<img width="498" alt="4edd27365c35da88ff2e1d73830b5e9" src="https://user-images.githubusercontent.com/34880208/233049505-0c01ea41-a8d3-4d91-9aef-d9413f8b60d3.png">

**Comment by dluc** [comment]
@hathind-ms @craigomatic FYI

**Comment by evchaki** [comment]
@bzbwqz thanks for sending this in, we are taking a look.

**Comment by bzbwqz** [comment]
I re-checked to set text-davinci-003 on Completion model and text-embedding-ada-002 on Embedding model, then the result is normal. 

Before I used text-embedding-ada-002 on both Completion and Embedding models to meet the above error. Thanks for your time.
