### ISSUE TITLE
Python: No module named 'semantic_kernel.core_skills'

### ISSUE THREAD

**Issue by Sarfaraz021** [microsoft/semantic-kernel#5250]
#Describe the bug
When attempting to import TimeSkill from the semantic_kernel.core_skills module, the interpreter throws a ModuleNotFoundError. This error suggests that either the module does not exist within the package or the package structure is not recognized by the interpreter.

##To Reproduce

Set up a new environment and install the semantic-kernel package.
Create a new Python file and insert the provided code snippet.
Run the file with the Python interpreter.
The ModuleNotFoundError occurs, stating: "No module named 'semantic_kernel.core_skills'".

##Expected behavior
The expected behavior would be for the TimeSkill class to be successfully imported from semantic_kernel.core_skills, allowing the script to run and execute the main function without import errors.

Platform

OS: Windows 10
IDE: VS Code
Language: Python

**Comment by moonbox3** [comment]
Hi @Sarfaraz021, which version of the Python package are you using? As of [0.4.6.dev0](https://github.com/microsoft/semantic-kernel/releases/tag/python-0.4.6.dev), we've renamed all `skill` instances to `plugin`.

**Comment by moonbox3** [comment]
Please upgrade to the latest package, for example, 0.9.0b1. Closing this as a non-issue. If you need further help, feel free to re-open.

**Comment by Sarfaraz021** [comment]
@moonbox3 Thanks for the updates, am using python-3.11.5
