### ISSUE TITLE
Concerns with Connector Classes: Improper Use of HttpClient and the Risk of Port/Socket Exhaustion

### ISSUE THREAD

**Issue by alexandrereyes** [microsoft/semantic-kernel#527]
I'm analyzing the connector classes and I'm worried about the use of HttpClient. It seems that they are not following the guidelines outlined in https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines. This could potentially cause port/socket exhaustion problems and lead to the application shutting down.

**Comment by dluc** [comment]
hi @alexandrereyes thanks for looking into this, yes we're aware of the issue and we plan on start using IHttpClientFactory shortly. The work fits into a bigger story that covers refactoring the early prototype, introducing ServiceCollection and the usual .NET DI, which will then allow to support this easily.

**Comment by matthewbolanos** [comment]
The HttpClient has been updated across the kernel; please let us know if this issue still persists.
