### ISSUE TITLE
Python: how call Kernel Memory  from semantic kernel

### ISSUE THREAD

**Issue by kill136** [microsoft/semantic-kernel#5272]
i using Kernel Memory  upload my files，using  Qdrant  embedded them，now  the problem  is how call them  from semantic kernel。all  files embedded  in one collection ，i want search with document id using Qdrant  ，not just collection name，how to do it？ thanks all

**Comment by dluc** [comment]
@kill136 here's one example to get you started: https://github.com/microsoft/kernel-memory/blob/main/examples/002-dotnet-SemanticKernel-plugin/Program.cs

**Comment by kill136** [comment]
> @kill136 here's one example to get you started: https://github.com/microsoft/kernel-memory/blob/main/examples/002-dotnet-SemanticKernel-plugin/Program.cs

thanks ，this is not what i wanted，i works  with python ， i just want using Qdrant  directly  in SemanticKernel
