### ISSUE TITLE
.Net: Support DI for memory connectors

### ISSUE THREAD

**Issue by SebastianStehle** [microsoft/semantic-kernel#5278]
In .NET Core some patterns have evolved how to use services. It is widely used in ASP.NET Core, Orleans and many third party services. In my opinion Semantic Kernel should also follow this pattern.

There are just a wide range of small mistakes, that should be avoided:

1. Inject loggers as concrete classes, aka `ILogger<T>`
2. Inject http client using `IHttpClientFactory`, do not use singleton clients.
3. Don't use custom factories, e.g. `MemoryBuilder`
4. Inject configuration using the `IOptions<T>` interface.
5. Use named registrations if you allow multiple registration.
6. Allow easy chaining, do not use `builder.Plugins.AddFromType<T>()` but `builders.AddPluginFromType<T>()`

Community PR which added DI to old Memory connectors: https://github.com/microsoft/semantic-kernel/pull/5589

**Comment by stephentoub** [comment]
> Inject loggers as concrete classes, aka ILogger<T>

Where do you see this being a mistake?

> Inject http client using IHttpClientFactory, do not use singleton clients.

By default it does use registered services, but for convenience for various scenarios it allows a singleton, which is fine, eg
https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines#recommended-use

> Don't use custom factories, e.g. MemoryBuilder

KernelBuilder is there to simplify situations where there isn't a higher-level DI container with which you're integrating. MemoryBuilder hasn't been revised yet to follow the desired scheme and is still marked [Experimental].

> Use named registrations if you allow multiple registration.

It supports keyed services. What specifically is your concern?

> Allow easy chaining

Fluency is enabled in some cases. Cases where it isn't was specifically on recommendation from key ASP.NET devs who suggested multiple API studies had found aspects of it to be confusing.

**Comment by SebastianStehle** [comment]
I think my main feedback is around the memory builder. I know that it is experimental, but it does not feel integrated yet. But perhaps I was just too impatient ;)

>> Use named registrations if you allow multiple registration.
>
> It supports keyed services. What specifically is your concern?

It is also related to the MemoryBuilder. I thought it could e made obsolete or implemented similar to the HttpClientFactory.

**Comment by stephentoub** [comment]
> I think my main feedback is around the memory builder. 

Got it. Yes, that needs to be revised.
cc: @dmytrostruk

**Comment by dmytrostruk** [comment]
Yes, `MemoryBuilder` will be revised as part of global memory-related refactoring. There could be a solution, where `MemoryBuilder` won't be needed at all and we will register all memory-related services as any other services that are used in Kernel. But it needs some further investigation, so stay tuned :)

**Comment by dmytrostruk** [comment]
Closing this issue, as DI work will be done in scope of each separate memory connector.
