### ISSUE TITLE
.Net: Text to Image service using GPT 4 Vision

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#5280]

**Comment by Krzysztof318** [comment]
Do we need special service for this since we can achieve same functionality using IChatCompletionService?

**Comment by Krzysztof318** [comment]
GPT-4V can generate images from text? I thought it can only generate text based on image input.

**Comment by 1jaj7** [comment]
________________________________

**Comment by Krzysztof318** [comment]
@1jaj7 bro what is wrong with you? you post at least 3 spam messages today in this repo.

**Comment by matthewbolanos** [comment]
Closed because GPT-4 vision only supports image-to-text
