### ISSUE TITLE
HttpClient 1m40s (100s) timeout 

### ISSUE THREAD

**Issue by arynaq** [microsoft/semantic-kernel#5310]
**Describe the bug**
The builtin httpclient is not configurable, and it falls back to the default behavior of httpclient, which is 100s timeout. This can be unreasonable during load or long context windows.

There is probably some way of circumventing this but libraries such as this that aim to be a high level wrapper should have batteries included. Resiliency has no impact as this is a retry wrapper around the client. See

```
var builder = Kernel.CreateBuilder();
        builder.Services.AddSingleton(_loggerFactory);
        builder.Services.ConfigureHttpClientDefaults(c =>
        {
            c.ConfigureHttpClient((sp, c) =>
            {
                c.Timeout = TimeSpan.FromMinutes(5);
            });
            c.AddResilienceHandler("dumbretry", b =>
            {
                b.AddRetry(new HttpRetryStrategyOptions {
                    MaxRetryAttempts = 3,
                    Delay = TimeSpan.FromSeconds(3),
                    BackoffType = DelayBackoffType.Exponential,
                });
                b.AddTimeout(TimeSpan.FromSeconds(60 * 5));
                b.Build();
            });
        });
```

The client I am configuring here is not the client being used under the hood, the timeout value for HttpClient has no impact at all. 

**To Reproduce**
1. Try GPT4 with a very long context
2. You will eventually get a socket exception bubbling up to SK (socket timeout)

**Expected behavior**
The client I configure is the client being used or I can configure the timeout via SK or resiliency or the default is higher to allow for throttle/load windows in OpenAI.

**Comment by arynaq** [comment]
Nothing? I am literally providing my own http client at this point, but the library is not using it or ends up down some call chain that does not use it, seeing the error below in production is not fun

```
Microsoft.SemanticKernel.KernelFunctionCanceledException: The invocation of function 'func5505e8747a6d4b96ab41ff9f245b88ae' was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
```

```
var client = _httpClientFactory.CreateClient("skkernel.client");
        using var activity = _activitySource.StartActivity($"Execution of function {function.Name}", ActivityKind.Internal);

        var builder = Kernel.CreateBuilder();
        builder.Services.AddSingleton(_loggerFactory);
        var kernel = builder
        .AddAzureOpenAIChatCompletion(
            deploymentName: _options.Deployment,
            apiKey: _options.ApiKey,
            endpoint: _options.Endpoint,
            httpClient: client)
        .Build();
        
```
The client
```
services.AddHttpClient("skkernel.client", client =>
        {
            client.Timeout = TimeSpan.FromMinutes(5);
        }).AddResilienceHandler("dumbretry", c =>
        {
            c.AddRetry(new HttpRetryStrategyOptions
            {
                MaxRetryAttempts = 3,
                Delay = TimeSpan.FromSeconds(3),
                BackoffType = DelayBackoffType.Exponential,
            });
            c.AddTimeout(TimeSpan.FromSeconds(60 * 5));
        });
```

What is happening? At this point I am tempted to just install handlebars and the OpenAI SDK

**Comment by arynaq** [comment]
Looking at the client here
`var client = _httpClientFactory.CreateClient("skkernel.client");` in the debugger, it clearly has a timeout of 5 minutes, so what client is SK using?

**Comment by stephentoub** [comment]
Can you please share a complete runnable repro (ie something compilable and runnable that only needs a different api key provided)?

**Comment by arynaq** [comment]
@stephentoub 
Unfortunately not without ripping out a whole lot (will take days). But I think I found the problem, in ClientCore.cs

https://github.com/microsoft/semantic-kernel/blob/a1fede6cb67d535a30a6161741074aa88e617e55/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L740

So a new option type is instantiated for use, but this option type has some defaults, including
```
public TimeSpan NetworkTimeout { get; set; } = TimeSpan.FromSeconds(100.0);
```

I think the problem stems from trying to wrap and mirror configuration done for custom HttpClients. But a simple fix would be to try and copy the timeout set on the client.

What to do until a fix is live though? Is there a pre execution hook that gives me access to the client or the underlying httpmessagehandler?

**Comment by animeshj9** [comment]
Facing the same issue on some production workloads we are running. Would appreciate some help here folks. Thanks!

**Comment by stephentoub** [comment]
> So a new option type is instantiated for use, but this option type has some defaults

I debugged through it, and I don't see NetworkTimeout being set on messages in the Azure SDK:
<img width="539" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/2642209/b4217aab-6616-4f50-b45c-a1f2550cf890">
Was this a guess or do you actually see that timeout being set somewhere? Or are you looking at a different timeout property?

**Comment by stephentoub** [comment]
Nevermind, I found what you were actually referring to. ResponseBodyPolicy.ProcessAsync uses its _networkTimeout, which defaults to 100 seconds, if the message's timeout is null.
https://github.com/Azure/azure-sdk-for-net/blob/5e9fd50aeec013eaa3d27f42c67f9ae227dcfa80/sdk/core/Azure.Core/src/Pipeline/Internal/ResponseBodyPolicy.cs#L39-L46

**Comment by markwallace-microsoft** [comment]
@animeshj9 @arynaq Stephen's fix has been merged. The change will be available via our [nightly builds](https://github.com/microsoft/semantic-kernel/blob/main/docs/FAQS.md#how-do-i-get-access-to-nightly-builds).
