### ISSUE TITLE
Python: TypeError: KernelFunction.from_prompt() missing 2 required positional arguments: 'function_name' and 'plugin_name'

### ISSUE THREAD

**Issue by silarsis** [microsoft/semantic-kernel#5313]
https://github.com/microsoft/semantic-kernel/blob/45dc8c229342cef19ae56b33bc4d893b9fa55177/python/semantic_kernel/kernel.py#L372

This line when calling kernel.invoke_prompt() with a prompt string errors out with the above error.

**Comment by moonbox3** [comment]
Thanks for reporting this, @silarsis. A fix is incoming.
