### ISSUE TITLE
Error: Invalid request: The request is not valid, HTTP status: 404. Details: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again. 

### ISSUE THREAD

**Issue by Klein88** [microsoft/semantic-kernel#5319]
I try to use AzureOpenAI in go program, and try to chat after deployment, but when I send a message to it, an error "Error: Invalid request: The request is not valid, HTTP status: 404. Details: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."
will be reported. What is the reason for this?
<img width="783" alt="截屏2024-03-05 23 38 08" src="https://github.com/microsoft/semantic-kernel/assets/116494913/d6d6021f-ad1a-419e-8924-723fe4abcb87">
<img width="784" alt="截屏2024-03-05 23 39 14" src="https://github.com/microsoft/semantic-kernel/assets/116494913/5b5d5f0b-a8db-44c0-bb83-2537ecac3e01">
I think I'm able to use the endpoint in the Azure OpenAI playground.

**Comment by matthewbolanos** [comment]
This typically means the deployment name is incorrect. Make sure you are using the deployment name instead of the model name, otherwise it won't resolve. Please reopen this issue if you're still having trouble.
