### ISSUE TITLE
.Net: The function name validation in tool call is different from the API spec

### ISSUE THREAD

**Issue by songpeidu** [microsoft/semantic-kernel#5320]
**Describe the bug**
The function name validation in SK is different from the API spec.

The definition in the documentation:
> The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
The regex used to verify: `'^[a-zA-Z0-9_-]{1,64}$'`

The regex in SK: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/InternalUtilities/src/Diagnostics/Verify.cs#L16C1-L17C1
It doesn't allow dashes and doesn't check the length.

**To Reproduce**
1. Call chat completion with tools using SK, and use the function name with dashes, SK throws an exception: `System.ArgumentException: A function name can contain only ASCII letters, digits, and underscores, 'xxx' is not a valid name`.
2. Directly call the API with the same params, and the requests succeed.

**Expected behavior**
The validation should be the same as the API spec.

**Comment by markwallace-microsoft** [comment]
@songpeidu This looks like the function name validation that OpenAI requires. Semantic Kernel supports models from different vendors hence our function name validation is different.

**Comment by songpeidu** [comment]
> @songpeidu This looks like the function name validation that OpenAI requires. Semantic Kernel supports models from different vendors hence our function name validation is different.

I see, so shall we just add the length check so it aligns with OpenAI's API spec?

**Comment by markwallace-microsoft** [comment]
Yes, you can add this in your code if you know you will only use OpenAI model
