### ISSUE TITLE
.Net: Create new Azure OpenAI service for integration tests only

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#5321]
The goal of the task is to gather all deployments/models used by SK integration tests/examples under one service.

- [ ] Create new Azure OpenAI service. Name it in a way it's clear that it's related to integration tests.
- [ ] Add required by SK integration tests deployments.
- [ ] Update local secrets to point to the new deployments' parameters - enpoint, model, apiKey, etc..
- [ ] Make sure all integration tests still work.
- [ ] Update GitHub secrets to point to the new deployments' parameters.
- [ ] Register a task to run integration against AzureOpenAI endpoints instead of OpenAI ones

**Comment by markwallace-microsoft** [comment]
This is done
