### ISSUE TITLE
Python: 00-getting-started.ipynb does not work out of the box

### ISSUE THREAD

**Issue by pranjalrajput** [microsoft/semantic-kernel#5330]
**Describe the bug**
the kernel import from prompt directory step fails

**To Reproduce**
1. Go to 00-getting-started.ipynb
2. execute all the steps till step 3
3. execute step 3
4. See error- TypeError: import_plugin_from_prompt_directory() takes 3 positional arguments but 4 were given

**Expected behavior**
The import_plugin_from_prompt_directory should load the plugin correctly without error

**Screenshots**

**Platform**
 - OS: MacOS Sonoma 14.3, Apple M1 chip
 - IDE: PyCharm, VS Code
 - Language: Python
 - Source: main branch of repository

**Additional context**
It seems the signature of import_plugin_from_prompt_directory method has changed but the notebooks were not updated to reflect it.

**Comment by moonbox3** [comment]
The fix is already in main and will be included with the release tomorrow. Closing this issue.
