### ISSUE TITLE
.Net: GetRequiredService<IChatCompletionService> System.NotSupportedException: 'Specified method is not supported.'

### ISSUE THREAD

**Issue by strikene** [microsoft/semantic-kernel#5332]
**Describe the bug**
Run 
Kernel.GetRequiredService<IChatCompletionService>()  
or  
Kernel.GetAllServices<IChatCompletionService>()
throws: System.NotSupportedException: 'Specified method is not supported.' exception

**To Reproduce**

<PackageReference Include="Azure.Data.Tables" Version="12.8.3" />
<PackageReference Include="Microsoft.SemanticKernel.Connectors.Sqlite" Version="1.5.0-alpha" />
<PackageReference Include="Microsoft.SemanticKernel.Planners.Handlebars" Version="1.5.0-preview" />
<PackageReference Include="Microsoft.SemanticKernel.Planners.OpenAI" Version="1.5.0-preview" />
<PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.2.0" />    
<PackageReference Include="Microsoft.KernelMemory.WebClient" Version="0.23.231219.1" />    
<PackageReference Include="Azure.ResourceManager.Billing" Version="1.1.0-beta.1" />
<PackageReference Include="Azure.ResourceManager.Resources" Version="1.6.0" />
<PackageReference Include="Azure.ResourceManager.Subscription" Version="1.0.1" />
<PackageReference Include="Azure.ResourceManager.Support" Version="1.0.1" />
<PackageReference Include="Microsoft.SemanticKernel" Version="1.5.0" />
<PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.5.0" />
<PackageReference Include="Microsoft.SemanticKernel.Plugins.Core" Version="1.5.0-alpha" />
<PackageReference Include="Microsoft.SemanticKernel.Plugins.Document" Version="1.5.0-alpha" />
<PackageReference Include="Microsoft.SemanticKernel.Plugins.Memory" Version="1.5.0-alpha" />
<PackageReference Include="Microsoft.SemanticKernel.Plugins.MsGraph" Version="1.5.0-alpha" />
<PackageReference Include="Microsoft.SemanticKernel.Plugins.Web" Version="1.5.0-alpha" />
<PackageReference Include="SharpToken" Version="1.2.17" />
<PackageReference Include="Azure.AI.OpenAI" Version="1.0.0-beta.14" />
<PackageReference Include="System.Text.Json" Version="9.0.0-preview.1.24080.9" />

var ker= Kernel.CreateBuilder()
.AddAzureOpenAIChatCompletion(...)
.AddAzureOpenAIChatCompletion(...)
.AddAzureOpenAIChatCompletion(...)
.AddAzureOpenAITextEmbeddingGeneration(...);
ker.GetRequiredService<IChatCompletionService>()  

**Expected behavior**
get instance of  IChatCompletionService
**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/62022463/6a678ee3-b262-48f8-863c-71a979a27753)

**Platform**
 - OS: Win11
 - IDE: VS2022
 - Language: [C#
 - Source: SK Ver1.5

**Additional context**

After I upgraded from sk 1.0 to 1.5 I got the error, I need to get the specific OpenAi instance registered to do something else. Am I missing any necessary upgrade steps?

**Comment by strikene** [comment]
> Hi @strikene, thank you for reporting the issue. Can you please share with us a simple console app that reproduces the problem? This will help us identify the root cause more quickly.
The issue has been fixed when I lowered Azure.AI.OpenAI from 14 to 13 this issue was resolved.

**Comment by strikene** [comment]
> > > Hi [@strikene](https://github.com/strikene), thank you for reporting the issue. Can you please share with us a simple console app that reproduces the problem? This will help us identify the root cause more quickly.
> > > The issue has been fixed when I lowered Azure.AI.OpenAI from 14 to 13 this issue was resolved.
> 
> It's good to hear that the issue has been resolved. I wonder how it happened that your app referenced version 14 of the Azure.AI.OpenAI library instead of version 13. Did this occur automatically, or does your app use Azure.AI.OpenAI in parallel with SK?

Hi 
This doesn't happen automatically
when i update SK1.0==>1.5 .In vs , update all packages ...

**Comment by SergeyMenshykh** [comment]
Thanks @strikene for the clarification. Closing the issue for now.

**Comment by SergeyMenshykh** [comment]
Hi @Backslider23, the issue was fixed by this PR - https://github.com/microsoft/semantic-kernel/issues/5371. Please reference the latest SK nuget package https://www.nuget.org/packages/Microsoft.SemanticKernel/1.6.1 to get it.

**Comment by markti** [comment]
@SergeyMenshykh 1.6.1 has dependency on `Microsoft.SemanticKernel.Connectors.AzureOpenAI` version `1.61.0` which has a dependency on `Azure.AI.OpenAI` version `2.2.0-beta.5` why is a stable version of semantic kernel drawing dependency on a preview version of Azure Open AI?
