### ISSUE TITLE
.Net: OpenAI connector is not compatible with third-party openai compatible endpoints

### ISSUE THREAD

**Issue by JadynWong** [microsoft/semantic-kernel#5337]
**Describe the bug**
The openai connector always serializes user messages to an array type. Some third-party models compatible with openai endpoints are not yet compatible with this format. Like [one-api](https://github.com/songquanpeng/one-api), [OpenLLM](https://github.com/bentoml/OpenLLM), etc.

**To Reproduce**
```csharp
private class ProxyOpenAIHandler(string proxyApiBase) : HttpClientHandler
{
    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        if (request.RequestUri != null && request.RequestUri.Host.Equals("api.openai.com", StringComparison.OrdinalIgnoreCase))
        {
            request.RequestUri = new Uri($"{proxyApiBase.EnsureEndsWith('/')}{request.RequestUri.PathAndQuery}");
        }
        return base.SendAsync(request, cancellationToken);
    }
}
    
var chatCompletion = new OpenAIChatCompletionService(modelId: "gpt4-turbo", apiKey: "NOKEY", httpClient: new HttpClient(new ProxyOpenAIHandler("https://proxy-openai.com")));
IKernelBuilder builder = Kernel.CreateBuilder();
builder.Services.AddTransient<IChatCompletionService>((sp) => service);
Kernel kernel = builder.Build();
var result = await kernel.InvokePromptAsync("Translate this into English:\r\n111\r\n");
```

The request body
```json
{
	"messages": [
		{
			"content": "Assistant is a large language model.",
			"role": "system"
		},
		{
			"content": [
				{
					"text": "Translate this into English:\r\n111\r\n",
					"type": "text"
				}
			],
			"role": "user"
		}
	],
	"temperature": 1,
	"top_p": 1,
	"n": 1,
	"presence_penalty": 0,
	"frequency_penalty": 0,
	"model": "gpt4-turbo"
}
```

**Expected behavior**
The request body
```json
{
	"messages": [
		{
			"content": "Assistant is a large language model.",
			"role": "system"
		},
		{
			"content": "Translate this into English:\r\n111\r\n",
			"role": "user"
		}
	],
	"temperature": 1,
	"top_p": 1,
	"n": 1,
	"presence_penalty": 0,
	"frequency_penalty": 0,
	"model": "gpt4-turbo"
}
```

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: NuGet package version 1.5.0

**Additional context**

**Comment by RogerBarreto** [comment]
@JadynWong @SergeyMenshykh I think this is not an OPenAI Connector responsibility to be compliant with other platforms.

We may need to think on letting this behavior to be flagged as optional as an execution setting when used by a custom non OpenAI provider.

**Comment by JadynWong** [comment]
>  I think this is not an OPenAI Connector responsibility to be compliant with other platforms. 
 
Your are right. But only supporting the array content is a bit strange. 

> We may need to think on letting this behavior to be flagged as optional as an execution setting when used by a custom non OpenAI provider.  

Want to find a balanced solution.
