### ISSUE TITLE
.Net: Azure API Update Compliance Issue with Microsoft.SemanticKernel Package

### ISSUE THREAD

**Issue by v-mghabin** [microsoft/semantic-kernel#5371]
We have been instructed by Microsoft Azure to implement a critical update by April 2, 2024, specifically to migrate to the latest Azure OpenAI API version labeled as 2024-02-15-preview. Our infrastructure currently utilizes the Microsoft.SemanticKernel .NET NuGet package. Despite updating the Microsoft.SemanticKernel package to its most recent version, it continues to reference an outdated version of the Azure OpenAI API (2023-12-01-preview).

Upon further investigation, it was discovered that the newest version of the SemanticKernel package (version 1.5.0) is still linked to an older version of the Azure.AI.OpenAI package (version 1.0.0-beta.13). This misalignment is causing compatibility issues between the two packages.

Attached is a screenshot of the email notification from Microsoft Azure for reference.

**Platform**
 - Language: C#

**Comment by v-mghabin** [comment]
@stephentoub Can u pls mention when this change will be reflected in Semantic.Kernel NuGet package as a minor version?

**Comment by stephentoub** [comment]
@markwallace-microsoft is the one to answer.

**Comment by v-mghabin** [comment]
@markwallace-microsoft Can u pls mention when this change will be reflected in Semantic.Kernel NuGet package as a minor version?

**Comment by stephentoub** [comment]
> @markwallace-microsoft Can u pls mention when this change will be reflected in Semantic.Kernel NuGet package as a minor version?

It was included in last week's release.
