### ISSUE TITLE
Python: notebooks: await planner.create_plan(ask, kernel) -- TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by WanlinLi2021** [microsoft/semantic-kernel#5380]
**Describe the bug**
TypeError: can only concatenate str (not "NoneType") to str

In file: python/notebooks/05-using-the-planner.ipynb

**To Reproduce**
I run the code step by step without changing anything.

In Basic Plan section. 
```basic_plan = await planner.create_plan(ask, kernel)```

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/53668767/50a6a853-ff6d-4c56-8a16-b27317c451dc)

**Platform**
 - OS: [Mac]
 - IDE: [e.g. Visual Studio]
 - Language: [Python]
 - Source: [ main branch of repository, python/notebooks/05-using-the-planner.ipynb]

**Additional context**
Thanks.

**Comment by eavanvalkenburg** [comment]
Hi, I just made some updates to that notebook, could you try again? The code behind was fixed but not yet released so you will have to install either from git or use poetry in a cloned environment or wait until the package is updated

**Comment by WanlinLi2021** [comment]
Thank you so much. I will try it later.

**Comment by kottofy** [comment]
I ran into the same error. The updated code was released with version 0.9.3b1. This notebook works after updating to that version!
