### ISSUE TITLE
.Net: Python: Do you have a Python version of the tutorial corresponding to https://github.com/microsoft/semantic-kernel/blob/main/dotnet/notebooks/07-DALL-E-3.ipynb

### ISSUE THREAD

**Issue by sv-youn** [microsoft/semantic-kernel#5383]
![image](https://github.com/microsoft/semantic-kernel/assets/58833784/ac766b72-b1ec-476e-81ec-6072d17d9ab6)

**Comment by moonbox3** [comment]
Hi @sv-youn, Python doesn't have DALL-E support yet. That work is in the backlog.

**Comment by sv-youn** [comment]
Thank you for your response @moonbox3. Looking forward to this feature implementation!

**Comment by moonbox3** [comment]
I will close this issue since we're tracking the work on our backlog.
