### ISSUE TITLE
Azure Open AI Example equivalent to AddOpenAIFiles

### ISSUE THREAD

**Issue by uday31in** [microsoft/semantic-kernel#5395]
Is there an example to upload files to Azure Open AI for assistant?

**Comment by evchaki** [comment]
@uday31in  - here is an example - https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example80_OpenAIFiles.cs

**Comment by uday31in** [comment]
does this example work for Azure Open AI?

**Comment by evchaki** [comment]
@uday31in  yes, it will work in either one.
