### ISSUE TITLE
Python: AttributeError: 'Kernel' object has no attribute 'add_text_completion_service'

### ISSUE THREAD

**Issue by abdelmalek13** [microsoft/semantic-kernel#5397]
**Describe the bug**
I followed the course presented by John Maeda on Deeplearning.ai.
In the [first lesson](https://learn.deeplearning.ai/courses/microsoft-semantic-kernel/lesson/2/semantic-kernel-is-like-your-ai-cooking-kitchen) He used a code to set the semantic kernel, I tried to follow this code on my own notebook but it fails with this error
```AttributeError: 'Kernel' object has no attribute 'add_text_completion_service'```
**To Reproduce**
I downloaded the latest version of semantic kernel using 
`pip install -U semantic-kernel` 
since no specific version was specified in the course
and ran the code that was provided in the first lessons
```
import semantic_kernel as sk
from semantic_kernel.connectors.ai.open_ai import AzureChatCompletion, OpenAIChatCompletion

kernel = sk.Kernel()

useAzureOpenAI = False

if useAzureOpenAI:
    deployment, api_key, endpoint = sk.azure_openai_openai_settings_from_dot_env()
    kernel.add_text_completion_service("azureopenai", AzureChatCompletion(deployment, endpoint, api_key))
else:
    api_key, org_id = sk.openai_settings_from_dot_env()
    kernel.add_text_completion_service("openai", OpenAIChatCompletion("gpt-3.5-turbo-0301", api_key, org_id))

print("You made a kernel")
```
**Expected behavior**
It should print "You made a kernel"

**Platform**
 - OS: Ubuntu linux
 - IDE: VsCode
 - Language: Python 3.10
 - Source: pip 22.0.2

**Comment by eavanvalkenburg** [comment]
If you are using 0.9 then that method was relaxed with just `add_service`!

**Comment by abdelmalek13** [comment]
It worked just fine, thanks it was just a newer version
