### ISSUE TITLE
.Net Remove Microsoft.SemanticKernel.Connectors.OpenAI dependency from Microsoft.SemanticKernel package

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#5398]
https://www.nuget.org/packages/Microsoft.SemanticKernel/ is dependent on https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.OpenAI/

Given that the kernel may use different models, not everyone may want to use OpenAI at all, so main package should be decoupled from OpenAI dependecy.

**Comment by dmytrostruk** [comment]
@Krzysztof318 `Microsoft.SemanticKernel` is metapackage that references `Microsoft.SemanticKernel.Core` and `Connectors.OpenAI` assemblies for quick onboarding. It's still possible to install `Microsoft.SemanticKernel.Core` directly if you want to use other connector than OpenAI.

**Comment by Krzysztof318** [comment]
@dmytrostruk I found that later, that's why I closed this issue 😅
