### ISSUE TITLE
.Net: F# strongly typed DSL instead of string handlebar or yaml formats

### ISSUE THREAD

**Issue by jkone27** [microsoft/semantic-kernel#5405]
consider using strongly typed languages with support for custom typed DSL instread of yaml for plugin definition, or handlebars for prompt templating?
as an altnerative they could maybe compile to the same objects

https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions

**Comment by markwallace-microsoft** [comment]
Closing as stale
