### ISSUE TITLE
.Net: Graduate Filters feature

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#5409]
Checklist to be completed when graduating an experimental feature

- [x] Verify the Filters feature is functionality complete (#5436)
- [x] Are we keeping filter properties on the Kernel
- [x] ​Verify API docs are complete and arrange to have them published
- [x] Make appropriate updates to Learn docs​
- [x] Make appropriate updates to Samples​​
- [x] Verify there are no serious open Issues​​
- [x] Verify there are sample implementations​ for the main use cases
- [x] Update table in EXPERIMENTS.md 
- [x] Remove SKEXP​ flag from Filters code

**Comment by dmytrostruk** [comment]
> Are we keeping filter properties on the Kernel

Based on comments, filter properties are still useful and adding new type of filters to Kernel type should not be complex: https://github.com/microsoft/semantic-kernel/issues/6085#issuecomment-2090685483.

**Comment by dmytrostruk** [comment]
> Verify API docs are complete and arrange to have them published

- [AutoFunctionInvocationContext Class](https://learn.microsoft.com/en-us/dotnet/api/microsoft.semantickernel.autofunctioninvocationcontext?view=semantic-kernel-dotnet)
- [IAutoFunctionInvocationFilter Interface](https://learn.microsoft.com/en-us/dotnet/api/microsoft.semantickernel.iautofunctioninvocationfilter?view=semantic-kernel-dotnet)
- [FunctionInvocationContext Class](https://learn.microsoft.com/en-us/dotnet/api/microsoft.semantickernel.functioninvocationcontext?view=semantic-kernel-dotnet)
- [IFunctionInvocationFilter Interface](https://learn.microsoft.com/en-us/dotnet/api/microsoft.semantickernel.ifunctioninvocationfilter?view=semantic-kernel-dotnet)
- [IPromptRenderFilter Interface](https://learn.microsoft.com/en-us/dotnet/api/microsoft.semantickernel.ipromptrenderfilter?view=semantic-kernel-dotnet)
- [PromptRenderContext Class](https://learn.microsoft.com/en-us/dotnet/api/microsoft.semantickernel.promptrendercontext?view=semantic-kernel-dotnet)

**Comment by dmytrostruk** [comment]
> Update table in EXPERIMENTS.md
Remove SKEXP​ flag from Filters code

https://github.com/microsoft/semantic-kernel/pull/7004
