### ISSUE TITLE
.Net: Adding support for native AOT compatibility

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#5411]
Complete the following:

- [x] Review this PR https://github.com/microsoft/semantic-kernel/pull/1284
- [x] Experiment to make non-alpha SK packages compatible with native AOT - Abstractions
- [x] Make Core package AOT compatible
- [x] Make Onnx package AOT compatible 
- [ ] ~~? Make SQL Lite package AOT compatible ?~~
- [x] Mark new API as experimental
- [x] Add samples to the test application demonstrating/testing AOT scenarios
- [x] Publish test application as part of GitHub workflow to uncover AOT related warnings in PRs
- [ ] ~~Document issues and list dependencies that are not native AOT compatible~~

References
- [How to make libraries compatible with native AOT - .NET Blog (microsoft.com)](https://devblogs.microsoft.com/dotnet/creating-aot-compatible-libraries/)

**Comment by SergeyMenshykh** [comment]
Packages that we need to spike on initially:
- Abstractions
- Core
- Onnx
