### ISSUE TITLE
.Net Unify samples for different vendors (OpenAI/Gemini/Mistral etc.)

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#5424]
Currently samples are configured for specific vendors.
We have examples for an OpenAI. Other set of examples for Gemini, other for mistral etc.
But many samples are similar between models.
So we should implement an additional param which user could pass when running examples to specify vendor to use.
And of course, adjust samples to use many vendors where posiible.

Thanks to that we won't have to many similar examples in repo, what could confuse end developers.

**Comment by markwallace-microsoft** [comment]
@matthewbolanos This would be a good thing to include as part of the samples refactoring work you are driving. What do you think?
