### ISSUE TITLE
Python: AttributeError: 'Kernel' object has no attribute 'add_chat_service

### ISSUE THREAD

**Issue by Sarfaraz021** [microsoft/semantic-kernel#5441]
# Code:

import semantic_kernel as sk
import logging
from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('__name__')
kernel=sk.Kernel(log=logger)

kernel.add_chat_service(
    "chat-gpt", OpenAIChatCompletion("gpt-3.5-turbo", key))

**Comment by moonbox3** [comment]
@Sarfaraz021, please note that since the beta release `add_chat_service` has been replaced with `add_service`. You can find examples [here](https://github.com/microsoft/semantic-kernel/blob/e7bc4c9c1efd6b5389ec5d42fbb9306c80b1232d/python/samples/documentation_examples/service_configurator.py#L40).
