### ISSUE TITLE
Python: AttributeError: 'Kernel' object has no attribute 'create_semantic_function'

### ISSUE THREAD

**Issue by Sarfaraz021** [microsoft/semantic-kernel#5442]
# Description:
I am trying to add 'create_semantic_function' in my simple chatbot code, but it is showing me an attribute error that 'no attribute create_semantic_function'

# Code: 
productnamer = kernel.create_semantic_function(prompt, temperature=0.9)

# Versions am using:

python==3.11.5
semantic-kernel==0.9.1b1
openai==1.13.3

![image](https://github.com/microsoft/semantic-kernel/assets/96107117/3a84d70c-20c1-4c7b-94a3-c7281a976ba5)

**Comment by moonbox3** [comment]
@Sarfaraz021, please note that since the beta release, `create_semantic_function` has been replaced with `create_function_from_prompt`. You can examples [here](https://github.com/microsoft/semantic-kernel/tree/main/python/samples/documentation_examples).

**Comment by minkyu-choi07** [comment]
Is this function depreciated it?

Can't find create_function_from_prompt from example or source code.

**Comment by moonbox3** [comment]
Hi @minkyu-choi07, please refer to our [API docs](https://learn.microsoft.com/en-us/python/api/semantic-kernel/semantic_kernel.functions.kernel_function_extension.kernelfunctionextension?view=semantic-kernel-python#semantic-kernel-functions-kernel-function-extension-kernelfunctionextension-add-function) or code samples for the latest methods. Now that we're at v1.0.0+, we won't have any more breaking changes. 

Possible methods are:
- add_function(...)
- add_functions(...)
- add_plugin(...)
- add_plugins(...)

You can find examples of this throughout our [samples](https://github.com/microsoft/semantic-kernel/tree/main/python/samples).
