### ISSUE TITLE
.Net: Plugin name inside FunctionInvokingContext in th IFunctionFilter is null

### ISSUE THREAD

**Issue by EdenTanami** [microsoft/semantic-kernel#5452]
**Describe the bug**
In the function filter we receive the FunctionInvokingContext object and inside it the kernelFunction but for some reason the pluginName attribute inside the function metadata is null 
(the kernelFunction that is registered in the kernel has valid pluginName).

**To Reproduce**
1. Write any function filter and register to the kernel.
2. Inside OnFunctionInvoking or OnFunctionInvoked the following value is null:
context.Function.Metadata.PluginName

**Expected behavior**
The plugin name will have the same value it has in the kernelFunction that is register in the kernel.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/160887465/8396e290-a4a1-446e-9989-831ad923d5b5)

![image](https://github.com/microsoft/semantic-kernel/assets/160887465/3cece40e-7a0e-4fc3-bc48-4c1d34a1f779)

**Platform**
 - OS: Windows
 - IDE: Visual Studio,
 - Language: C#
 - Source: SK NuGet package version 1.5.0

**Comment by dmytrostruk** [comment]
I think this issue should be fixed by this PR: https://github.com/microsoft/semantic-kernel/pull/5422.
@markwallace-microsoft please confirm.

**Comment by markwallace-microsoft** [comment]
This issue is being handled by #4706
