### ISSUE TITLE
.NET: function calling seems not working when gpt-4-vision-preview on Azure is used

### ISSUE THREAD

**Issue by rcoccia** [microsoft/semantic-kernel#5465]
function calling seems not working when gpt-4-vision-preview on Azure is used

I use the latest version of semantic kernel 1.0.6 and set up a simple kernel with math plugin

IKernelBuilder kernelBuilder = Kernel.CreateBuilder();
kernelBuilder.Plugins.AddFromType<Microsoft.SemanticKernel.Plugins.Core.TimePlugin>();
kernelBuilder.AddAzureOpenAIChatCompletion(
    deploymentName: GptVisionModelDeployment,
    endpoint: GptVisionModelEndpoint,
    apiKey: GptVisionApiKey);
var kernel = kernelBuilder.Build();

//start of request
var chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();
var chatHistory = new ChatHistory("you are a math assistant");
chatHistory.AddUserMessage(new ChatMessageContentItemCollection
{
    new TextContent("what is the result of 1+1*2"),
});
OpenAIPromptExecutionSettings settings = new OpenAIPromptExecutionSettings()
{
    ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions,
    Temperature = 0.0,
    MaxTokens = 500,
};
var reply = await chatCompletionService.GetChatMessageContentAsync(chatHistory, settings, kernel);

Console.WriteLine(reply.Content);

if i use a deployment of type GPT-4-1106 preview everything works fine
if i use a deployment of type gpt-4-vision preview , I receive the following error from SK
------------------------------------------------------------------------------------------------
2 validation errors for Request
body -> tool_choice
  extra fields not permitted (type=value_error.extra)
body -> tools
  extra fields not permitted (type=value_error.extra)
Status: 400 (model_error)

Content:
{"error":{"message":"2 validation errors for Request\nbody -> tool_choice\n  extra fields not permitted (type=value_error.extra)\nbody -> tools\n  extra fields not permitted (type=value_error.extra)","type":"invalid_request_error","param":null,"code":null}}

Headers:
request-id: 24d2ecd6-36dd-493a-b617-7b25108f51ed
X-Content-Type-Options: REDACTED
apim-request-id: REDACTED
x-ms-region: REDACTED
X-Request-ID: REDACTED
ms-azureml-model-error-reason: REDACTED
ms-azureml-model-error-statuscode: REDACTED
x-ms-client-request-id: 03e7abbf-a3aa-4def-b250-9fb1bf928c66
Strict-Transport-Security: REDACTED
azureml-model-session: REDACTED
api-supported-versions: REDACTED
x-envoy-upstream-service-time: REDACTED
x-ratelimit-remaining-requests: REDACTED
x-ratelimit-remaining-tokens: REDACTED
Date: Wed, 13 Mar 2024 18:28:15 GMT
Content-Length: 257
Content-Type: application/json; charset=utf-8
---------------------------------------------------------------------------------------
expected behavior is that the same code has wo work with both models

i attach the dump of the http body sent to the chat completion endpoint
POST https://XXXXX.openai.azure.com/openai/deployments/gpt-4-vision-preview/chat/completions?api-version=2024-02-15-preview
[dump_http_body.json](https://github.com/microsoft/semantic-kernel/files/14592221/dump_http_body.json)

**Comment by evchaki** [comment]
@rcoccia - 4-V does not support function calling at this time - https://platform.openai.com/docs/guides/vision

**Comment by rcoccia** [comment]
thank you very much for the clarification
