### ISSUE TITLE
Python  - Basic Planner Error

### ISSUE THREAD

**Issue by kinfey** [microsoft/semantic-kernel#5469]
**Describe the bug**
I define Native function 

`from semantic_kernel.functions import kernel_function

class CustomAPIPlugin:
    """
    Description: api plugin for planner
    """
    @kernel_function(
        description = "Get news from the web",
        name = "NewsPlugin",
    )
    def get_news_api(self,location:str) -> str:
        return """Get news from the """ + location + """."""
    
    @kernel_function(
            description="Search Weather in a city",
            name="WeatherFunction",
        )
    def ask_weather_function(self,city: str) -> str:
        return city + "’s weather is 30 celsius degree , and very hot."
    
    @kernel_function(
            description="Search Docs",
            name="DocsFunction",
        )
    def ask_docs_function(self,docs: str) -> str:
        return "ask docs :" + docs` 

when I use Basic Planner in python show errors

<img width="1162" alt="Screenshot 2024-03-14 at 07 09 54" src="https://github.com/microsoft/semantic-kernel/assets/93169410/99e88341-088b-423e-8f70-2e74f6686295">

maybe we need to set 

`available_functions_string += "description: " + str(description) + "\n"`

**Comment by moonbox3** [comment]
Thanks for filing the issue. This is the same as #5309. A fix is already in main and will be included in the next release.
