### ISSUE TITLE
.Net: Allow async IFunctionFilter and IPromptFilters

### ISSUE THREAD

**Issue by frederikrosenberg** [microsoft/semantic-kernel#5476]
The interface `IFunctionFilter` and `IPromptFilter` does not provide async methods. This is limiting when for example needing to update token usage based on function execution.

Suggestion, since the place where the filters are called from are already async make the filters ansyc.

**Comment by dmytrostruk** [comment]
@frederikrosenberg Thanks for reporting this issue. Yes, at some point we will probably have to add async version of filters as well, which should allow to support async scenarios in filters. 

My initial proposal is to introduce `IAsyncFunctionFilter` and `IAsyncPromptFilter` which will work in the same way as current filters, but in async scope. ASP.NET Core uses similar approach.

@matthewbolanos Should we add this to filters graduation scope of work or deliver it as separate feature?
