### ISSUE TITLE
.Net: Error When Adding Semantic Kernel C# .Net Package To Http Trigger Azure Function

### ISSUE THREAD

**Issue by raeesgillani** [microsoft/semantic-kernel#5478]
**Describe the bug**
I run into the following error when func start an Azure Function locally after adding the Microsoft.SemanticKernel dotnet package:

Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

The Azure Function works fine when that package is removed, however when it is added, it brings up that error. Adding the Microsoft.Extensions.Logging.Abstractions package does not resolve the error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open VSCode (Version 1.87), create a new Azure Function app. C#, dotnet 6 LTS, HTTPTrigger
2. Run the function, note it runs fine.
3. Add the Microsoft.SemanticKernel dotnet package (version `1.6.2, although have experienced the same issue with other versions as well)
4. Attempt the run the function and note the error: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

**Expected behaviour**
The Azure Function should run fine and display the default message of a New Function in the web browser.

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#
 - Source: NuGet Package Manager v1.1.6

**Comment by stephentoub** [comment]
See https://github.com/microsoft/semantic-kernel/issues/4472#issuecomment-1876062375.

**Comment by markwallace-microsoft** [comment]
Closing this based on the resolution in #4472
