### ISSUE TITLE
.Net: thread.InvokeAsync breaking change

### ISSUE THREAD

**Issue by dcostea** [microsoft/semantic-kernel#5485]
**Describe the bug**
Starting with v1.6 I have identified a breaking change calling thread.InvokeAsync(someAgent, someMessage)
This issue didn't reproduce before (for example with v1.4)

When I call thread.InvokeAsync I get HttpOperationException 400 Bad Request with ResponseContent as follows: 
```
{
  "error": {
    "message": "Invalid schema for function 'JackSparrowDialogAgent-Ask': 'String[]' is not valid under any of the given schemas.",
    "type": "invalid_request_error",
    "param": "tools[0]",
    "code": null
  }
}
```

**To Reproduce**
Call thread.InvokeAsync as follows:
```
try
{
    thread = await dialogWriterAgent.NewThreadAsync();
    foreach (var messages in scriptSteps.Select(m => thread!.InvokeAsync(dialogWriterAgent, m)))
    {
        await foreach (var message in messages)
        {
            Console.WriteLine(message!);
        }
    }
}
catch (HttpOperationException ex)
{
    Log.Error("Exception: {message}." , ex.ResponseContent);
}
```

**Expected behavior**
I'm expecting a valid response (200 OK)

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/15055082/bdafbcb7-2c75-403b-a53e-7fd9725020df)

**Platform**
 - Windows
 - Visual Studio
 - C#
 - version 1.6

**Comment by crickman** [comment]
Hi @dcostea, thank you for this clear and timely issue.  I also ran into this in my testing and was able to push a fix yesterday:

https://github.com/microsoft/semantic-kernel/pull/5481

We should have an updated package soon!

**Comment by crckman** [comment]
@dcostea - Have you been able to verify the fix addresses your issue?

**Comment by crickman** [comment]
I'm not sure it was every working properly.

**Comment by dcostea** [comment]
It works nicely!
I'm afraid I have responded already on another issue.
