### ISSUE TITLE
.Net: KernelMemoryBuilder: Unknown field 'embedding' in vector field list. Status: 400 (Bad Request) ErrorCode: InvalidRequestParameter

### ISSUE THREAD

**Issue by nssidhu** [microsoft/semantic-kernel#5487]
**Describe the bug**
var verification = await kernelMemory.SearchAsync("what is my Decutible?");

Result in the following error.

```
Unknown field 'embedding' in vector field list.
Status: 400 (Bad Request)
ErrorCode: InvalidRequestParameter
```

**To Reproduce**

```
var AZURE_SEARCH_ENDPOINT = _configuration.GetSection("AzureSearchAI:EndPoint").Value!;
                var AZURE_SEARCH_API_KEY = _configuration.GetSection("AzureSearchAI:ApiKey").Value!;
                var AZURE_SEARCH_INDEX_NAME = _configuration.GetSection("AzureSearchAI:IndexName").Value!;

#pragma warning disable SKEXP0001, SKEXP0010 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.

                var embeddingConfig = new AzureOpenAIConfig
                {
                    APIKey = _configuration.GetSection("AzureOpenAI:ApiKey").Value!,
                    Deployment = _configuration.GetSection("AzureOpenAI:EmbeddingModelName").Value!,
                    Endpoint = _configuration.GetSection("AzureOpenAI:EndPoint").Value!,
                    APIType = AzureOpenAIConfig.APITypes.EmbeddingGeneration,
                    Auth = AzureOpenAIConfig.AuthTypes.APIKey
                };

                var chatConfig = new AzureOpenAIConfig
                {
                    APIKey = _configuration.GetSection("AzureOpenAI:ApiKey").Value!,
                    Deployment = _configuration.GetSection("AzureOpenAI:DeploymentModelName").Value!,
                    Endpoint = _configuration.GetSection("AzureOpenAI:EndPoint").Value!,
                    APIType = AzureOpenAIConfig.APITypes.ChatCompletion,
                    Auth = AzureOpenAIConfig.AuthTypes.APIKey
                };

                var searchConfig = new AzureAISearchConfig
                {
                    APIKey = _configuration.GetSection("AzureSearchAI:ApiKey").Value!,
                    Endpoint = _configuration.GetSection("AzureSearchAI:EndPoint").Value!,
                    Auth = AzureAISearchConfig.AuthTypes.APIKey,
                };


                var memoryConfig = new KernelMemoryConfig
                {
                    DefaultIndexName = AZURE_SEARCH_INDEX_NAME,
                };

                var kernelMemory = new KernelMemoryBuilder()
                    .With(memoryConfig)
                    .WithAzureOpenAITextGeneration(chatConfig)
                    .WithAzureOpenAITextEmbeddingGeneration(embeddingConfig)
                    .WithAzureAISearchMemoryDb(searchConfig)
                    .WithSearchClientConfig(new SearchClientConfig { MaxAskPromptSize = 5000, AnswerTokens = 4096 })
                    .Build<MemoryServerless>();

```

My additional question here is, that i want to use this a Plugin.
I will set

```
   OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
   {
       ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions
   };
```

But my question here is how will Semantic kernel find out that it need to execute this Plugin for the Question asked ?
When we are creating our custom plugin, we do describe about it and that is what is used by semantic kernel to decide if it should call this plugin? Where would i provide the description in this case ?

**Expected behavior**
It should search the configured index and return appropriate results.

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by dmytrostruk** [comment]
@nssidhu It looks like you are using `KernelMemory` package. Both Semantic Kernel and Kernel Memory packages don't support custom Azure AI Search index schema at the moment. We are working on design of memory-related abstractions to allow support of custom schema, but as for now, your index should have the same schema as defined in packages (including `embedding` field).

If you want to use custom schema in Azure AI Search, here is an example of such SK plugin:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example84_AzureAISearchPlugin.cs


> But my question here is how will Semantic kernel find out that it need to execute this Plugin for the Question asked ?
> When we are creating our custom plugin, we do describe about it and that is what is used by semantic kernel to decide if it should call this plugin? Where would i provide the description in this case ?

When you register a Plugin in Semantic Kernel, you can call your function directly from prompt. For example, if you define a function in plugin with name `Search`, you can call it directly like this:
```csharp
var result = await kernel.InvokePromptAsync("{{search 'my query'}}");
```

But if you want to use AI to decide whether you need to call it or not, you need to enable function calling `ToolCallBehavior.AutoInvokeKernelFunctions` and you need to provide meaningful description for your function so AI will be able to call it when needed. To describe your function, you can use `Description` attribute at place of function definition. For example:
https://github.com/microsoft/semantic-kernel/blob/043e49b6c51500150f578323c422cf6790fab3a5/dotnet/samples/DocumentationExamples/Plugin.cs#L104-L106

**Comment by nssidhu** [comment]
@dmytrostruk My Second question is related to using AzureAISearch with kernel memory and not the custom function.
Say you got the fix for custom schema, How would semantic kernel decide it has to use or invoke the Azure Search AI for the question asked. I don't want to invoke (`var result = await kernel.InvokePromptAsync("{{search 'my query'}}");`) i am using 
  ```
 OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
   {
       ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions
   };
```
Most of my Azure Search AI schemas were created from the portal.
Any time lines on when the schema fix will be available ?

**Comment by dmytrostruk** [comment]
> My Second question is related to using AzureAISearch with kernel memory and not the custom function.

My apologies, probably I didn't get it right.

> Say you got the fix for custom schema, How would semantic kernel decide it has to use or invoke the Azure Search AI for the question asked.

As for now, all memory-related features are registered in Semantic Kernel as Plugins. Which means that when you enable function calling (e.g. `ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions`), AI model will decide whether to call your Plugin (i.e. make a request to Azure AI Search) based on Plugin description and your prompt. For example, if your prompt contains an ask to find some information, and memory plugin has description, that it is responsible for finding some information, then most probably AI model will call the Plugin, which means it will make a request to Azure AI Search.
I'm not sure how memory will be integrated into Semantic Kernel in the future, but as for now memory in SK is registered as Plugin.

> Most of my Azure Search AI schemas were created from the portal.
> Any time lines on when the schema fix will be available ?

Taking into account, that memory in SK is registered as Plugin, in order to work with your custom schema, you can define your own Plugin, that will work with Azure AI Search and desired schema. I shared an example above, it should help you to achieve this scenario without waiting for schema fix.

**Comment by evchaki** [comment]
@nssidhu - please post this over to the Kernel Memory repo - https://github.com/microsoft/kernel-memory/issues
