### ISSUE TITLE
Python: Text splitters assume ASCII punctuation and don't support Chinese or Japanese

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/semantic-kernel#5490]
**Describe the bug**

The text splitters in Semantic Kernel assume ASCII punctuation. Languages that use full-width Unicode punctuation or ideographic punctuation (Chinese and Japanese being the most common) won't split correctly.

Test sentence: 
`田中の猫はかわいいですね。日本語上手。` doesn't split on the full-stop because it is the Unicode ideographic full-stop (the main one used in Japanese and Chinese text).

See [this article](https://tonybaloney.github.io/posts/cjk-chinese-japanese-korean-llm-ai-best-practices.html#text-splitting) for more details. 

I've tested this on both Python and .NET APIs.

Python: https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/text/text_chunker.py#L14-L38

In langchain you can override the separators and supply a list of [ideographic and full-width characters](https://www.w3.org/TR/jlreq/#character_classes)

```python
SEPARATORS = [
    "\n\n", ".",  # Paragraph boundary and ASCII full stop
    "。", "．",     # Logographic and full width full stop
    "!", "！",    # ASCII and full width exclamation mark
    "?", "？",     # ASCII and full width question mark
    ",", "、", "，", # ASCII, logographic, and full width comma
]
```

**Comment by tonybaloney** [comment]
Submitted a PR for the .NET library #5489

**Comment by evchaki** [comment]
@tonybaloney, thanks for entering the issue at the .net repo.  I will close this for now, until this is updated in .Net
