### ISSUE TITLE
Add an Include List Parameter for OpenAPI Function Execution

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#5505]
### Description
 
To optimize the performance and reduce the overhead of parsing OpenAPI specifications, we would like to request the addition of an include list parameter for OpenAPI function execution in Semantic Kernel. This would complement the existing exclusion list and allow us to specify which functions should be included during the parsing process.
### Proposed Changes
 
Add an OperationsToInclude property to the OpenApiFunctionExecutionParameters class, similar to the existing OperationsToExclude property:

```cs
/// <summary>  
/// OpenAPI function execution parameters.  
/// </summary>  
public class OpenApiFunctionExecutionParameters  
{  
    /// <summary>  
    /// Optional list of HTTP operations to include when importing the OpenAPI document.  
    /// </summary>  
    public IList<string> OperationsToInclude { get; set; }  
  
    /// <summary>  
    /// Optional list of HTTP operations to skip when importing the OpenAPI document.  
    /// </summary>  
    public IList<string> OperationsToExclude { get; set; }  
}  
 ```

### Benefits
 
This feature will help us:
Reduce the parsing overhead and associated costs by only including specified functions.
Improve the long-term efficiency of parsing OpenAPI specs.
Simplify the management of included and excluded functions during parsing.
### Additional Considerations
 
Please ensure that the proposed include list functionality is compatible with the existing exclusion list feature and does not introduce breaking changes.

Thank you for considering this feature request. We believe that adding an include list parameter will significantly improve the parsing process and provide valuable benefits to the Semantic Kernel library.

**Comment by zengin** [comment]
@lemillermicrosoft, APIManifest plugin allows selecting a subset of operations from an OpenAPI file: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example83_ApiManifest.cs

PR description here contains the motivation behind introducing APIManifest plugins: https://github.com/microsoft/semantic-kernel/pull/4961

Could this be something that addresses the issue?

**Comment by matthewbolanos** [comment]
+1 to @zengin's comment, the goal of the API Manifest plugins is to explicitly help with these types of slicing operations. @lemillermicrosoft, can you confirm if that address your needs? If not, please reopen this issue.
