### ISSUE TITLE
.Net: Add Support for x-openai-isConsequential Property in Semantic Kernel

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#5506]
### Description    
We would like to request the addition of support for the `x-openai-isConsequential` property in Semantic Kernel. This property is used in the OpenAPI specification to mark certain endpoints as "consequential" and affects the way user confirmation and "always allow" buttons are handled. By implementing this feature, we can better control user interactions with actions and ensure a more consistent user experience.  
https://platform.openai.com/docs/actions/getting-started/consequential-flag
  
### Proposed Changes  
  
1. Update the parsing process in Semantic Kernel to recognize the `x-openai-isConsequential` property in the OpenAPI specification.  
2. Update the generated function models to include a boolean property indicating whether the operation is consequential or not.  
3. Adjust the confirmation behavior based on the value of the `x-openai-isConsequential` property:  
   - If `true`, always prompt the user for confirmation before running and do not show the "always allow" button.  
   - If `false`, show the "always allow" button.  
   - If the property is not present, default all GET operations to `false` and all other operations to `true`.  
  
### Benefits  
  
Adding support for the `x-openai-isConsequential` property will:  
  
- Improve user control over actions.  
- Ensure a more consistent user experience.  
- Enhance compatibility with the OpenAI platform.  
  
### Additional Considerations  
  
Please ensure that the proposed implementation is compatible with the existing features in Semantic Kernel and does not introduce breaking changes.  
  
Thank you for considering this feature request. We believe that adding support for the `x-openai-isConsequential` property will enhance the overall capabilities of Semantic Kernel and provide a more consistent experience for users interacting with actions.

**Comment by matthewbolanos** [comment]
Assigning this to myself to answer the following questions...
- What is the attribute name for `KernelFunction`s to hold this info
- Should it be binary, enum, collection of attributes?
- How is this flag set for native functions
- Where should this be set? By the API author or the API consumer?
- What other types of these things do we need?
- What is the E2E scenario with hooks/filters?

**Comment by westey-m** [comment]
Merged the changes.  See an example of usage here:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example23_OpenAPIPlugin.cs
