### ISSUE TITLE
Kernel Memory not searching using the registered Azure AI Plugin

### ISSUE THREAD

**Issue by nssidhu** [microsoft/semantic-kernel#5508]
**Describe the bug**
I uploaded and indexed "Northwind_Health_Plus_Benefits_Details.pdf" using  kernel memory   
`await kernelMemory.ImportDocumentAsync(filePath: path, documentId:"NASA001");`
I verified that index was created successfully on Azure Search.

Now i am trying to search using the following code.

What is my Deductible?
 Search

Assistant :

To assist you with finding information about your deductible, I'll need some context. Could you please specify which deductible you are referring to? For instance, are you asking about a health insurance, auto insurance, home insurance, or another type of insurance policy deductible? Additionally, I may need more details about your policy to provide accurate information. If you have a specific policy or document that details your coverage, sharing that would be helpful.

**To Reproduce**
 ```
              var AZURE_SEARCH_ENDPOINT = _configuration.GetSection("AzureSearchAI:EndPoint").Value!;
              var AZURE_SEARCH_API_KEY = _configuration.GetSection("AzureSearchAI:ApiKey").Value!;
              var AZURE_SEARCH_INDEX_NAME = _configuration.GetSection("AzureSearchAI:IndexName").Value!;

    #pragma warning disable SKEXP0001, SKEXP0010 // Type is for evaluation purposes only and is subject to change or removal in 
    future updates. Suppress this diagnostic to proceed.
                var embeddingConfig = new AzureOpenAIConfig
                {
                    APIKey = _configuration.GetSection("AzureOpenAI:ApiKey").Value!,
                    Deployment = _configuration.GetSection("AzureOpenAI:EmbeddingModelName").Value!,
                    Endpoint = _configuration.GetSection("AzureOpenAI:EndPoint").Value!,
                    APIType = AzureOpenAIConfig.APITypes.EmbeddingGeneration,
                    Auth = AzureOpenAIConfig.AuthTypes.APIKey
                };

                var chatConfig = new AzureOpenAIConfig
                {
                    APIKey = _configuration.GetSection("AzureOpenAI:ApiKey").Value!,
                    Deployment = _configuration.GetSection("AzureOpenAI:DeploymentModelName").Value!,
                    Endpoint = _configuration.GetSection("AzureOpenAI:EndPoint").Value!,
                    APIType = AzureOpenAIConfig.APITypes.ChatCompletion,
                    Auth = AzureOpenAIConfig.AuthTypes.APIKey
                };

                var searchConfig = new AzureAISearchConfig
                {
                    APIKey = _configuration.GetSection("AzureSearchAI:ApiKey").Value!,
                    Endpoint = _configuration.GetSection("AzureSearchAI:EndPoint").Value!,
                    Auth = AzureAISearchConfig.AuthTypes.APIKey,
                };


                var memoryConfig = new KernelMemoryConfig
                {
                    DefaultIndexName = IndexName,
                
                };


                var kernelMemory = new KernelMemoryBuilder()
                    .With(memoryConfig)
                    .WithAzureOpenAITextGeneration(chatConfig)
                    .WithAzureOpenAITextEmbeddingGeneration(embeddingConfig)
                    .WithAzureAISearchMemoryDb(searchConfig)
                    .WithSearchClientConfig(new SearchClientConfig { MaxAskPromptSize = 5000, AnswerTokens = 4096 })
                    .Build<MemoryServerless>();

                  var plugin = new MemoryPlugin(kernelMemory, waitForIngestionToComplete: true);
 		 kernel.ImportPluginFromObject(plugin,pluginName: "AzureAI_Search_MemoryPlugin");


---------------------------------------------------------------------------------------------------------------------------------------------
   chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();

   chatMessages.AddUserMessage(inputText);

   // Enable auto function calling
   OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
   {
       ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions
   };

 // Get the response from the AI
 ChatMessageContent result = await chatCompletionService.GetChatMessageContentAsync(
     chatMessages,
     executionSettings: openAIPromptExecutionSettings,
     kernel: kernel);

```

**Expected behavior**
It should have initiated a searching using the provided plugin. and returned the data from the PDF that use indexed.

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by dmytrostruk** [comment]
@nssidhu Which AI model you are using for this scenario? I noticed you are adding text generation model with this line: `WithAzureOpenAITextGeneration(chatConfig)`. Here is a list of models that support function calling:
<img width="589" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/13853051/62375116-2bde-4f7d-bc9a-61589d562b45">

Also, could you share the code where you initialize `kernel` instance? It will definitely help to understand the issue by checking how kernel was registered. Chat completion model, that supports function calling, should be registered on semantic kernel level.

Another thing that I noticed that you are getting `IChatCompletionService` instance and using `GetChatMessageContentAsync` method directly. My recommendation would be to use kernel directly:
```csharp
OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
{
    ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions
};

var result = await kernel.InvokePromptAsync("What is my Deductible?");
```

You could also try to be more specific in your prompt, just to be sure that MemoryPlugin is called correctly: `What is my Deductible? Use memory to answer this question`. 

In case if it still doesn't work, you could also create an issue in KernelMemory repository, because the issue can be related to kernel memory logic itself:
https://github.com/microsoft/kernel-memory/issues

Thank you!

**Comment by nssidhu** [comment]
Here is the code for kernel , the value for _userAzureOpenAI is hardcoded to true

```
var builder = Kernel.CreateBuilder();
if (_userAzureOpenAI)
{
    builder = Kernel.CreateBuilder()
           .AddAzureOpenAIChatCompletion(AzureOpenAIDeploymentName, AzureOpenAIEndPoint, AzureOpenAIKey);
}
else
{
    builder.AddOpenAIChatCompletion(OpenAIDeploymentName, OpenAIKey, OpenOrgId);
}

 var kernel = builder.Build();
 return kernel;


builder.Services.AddLogging(c => c.SetMinimumLevel(LogLevel.Debug).AddConsole().AddDebug());
```

Inerestigly i have tried that as well, like asking it to use specifc plugin, but that did not work either.


![Azure Open AI Model Screen shot](https://github.com/microsoft/semantic-kernel/assets/3267605/648606c0-fe7f-4a0a-98cf-44de8ed5c5ea)
![Azure Open AI Config Values](https://github.com/microsoft/semantic-kernel/assets/3267605/5bcc34d0-f3e3-4f8c-b3a2-675aa20146bc)

![Azure AI Sample Forcing to use pligin 2](https://github.com/microsoft/semantic-kernel/assets/3267605/733d0837-f131-496f-9f85-1c6538d913c8)
![Azure AI Sample List of Registered Plugins](https://github.com/microsoft/semantic-kernel/assets/3267605/166c8619-2720-4574-b7dd-b6a521e6d9c5)

I also noticced very high usage of Token for simple one liner question.

![Azure AI  Sample Very high usage of Tokens](https://github.com/microsoft/semantic-kernel/assets/3267605/611c2a77-3638-4bff-8849-c87212e7fa1e)

![Azure Open AI Very high use of Tokens](https://github.com/microsoft/semantic-kernel/assets/3267605/5a5528c8-3d1c-41fb-8ded-12b62bf751cb)

Here are few more screen shots.
I am not sure if there is issue with the Index itself, how can i rule that out ?

I used the following code to upload the document.
```
                var kernelMemory = await GetKernelMemory("BlazorMemory");

                await kernelMemory.ImportDocumentAsync(filePath: path, documentId:"NASA001");
```

**Comment by nssidhu** [comment]
To further experiment, I tried some more thing, like directly accessing kernel memory

  var kernel = await GetKernel(true);
  var memory = await GetKernelMemory("blazormemory");
  Microsoft.KernelMemory.SearchResult searchResults = await memory.SearchAsync(searchquery);
  Console.WriteLine(searchResults);
  if(!searchResults.NoResult)
  {
      foreach(var item in searchResults.Results)
      {
          Console.WriteLine(item.SourceName + " : " + item.SourceUrl + item.Link );
          foreach(var partition in item.Partitions)
          {
              Console.WriteLine(partition.Text + " : " + partition.Relevance);
          }
      }
  }

//The code above just pulls every partition which has reference to deductible. that is not much useful. but that just verifies that there should at be nothing wrong with the index.

  Microsoft.KernelMemory.MemoryAnswer searchResults1 = await memory.AskAsync(searchquery);
  Console.WriteLine(searchResults1);

  if(!searchResults1.NoResult)
  {
      Console.WriteLine(searchResults1.Result + " : " + searchResults1.RelevantSources);
     
  }

//The code above does not retrieve anything. this looks like to be the problem area. why nothing is being pulled out.

**Comment by evchaki** [comment]
@nssidhu - please post this issue over on the Kernel Memory repo - https://github.com/microsoft/kernel-memory/issues 

@dluc for a FYI
