### ISSUE TITLE
Python: ImportError: cannot import name 'ChromaMemoryStore' from 'semantic_kernel.memory.semantic_text_memory' 

### ISSUE THREAD

**Issue by Sarfaraz021** [microsoft/semantic-kernel#5510]
![image](https://github.com/microsoft/semantic-kernel/assets/96107117/08a3662b-a2e8-4e82-a449-7dcf1e70c673)

**Comment by eavanvalkenburg** [comment]
The specific memory stores need to be imported from those paths, so by design you can't use this, should be something like `from semantic_kernel.connectors.memory.chromadb import ChromaMemoryStore` (on my phone so the exact names might be slightly different)
