### ISSUE TITLE
Python: Passing outputs of functions sequentially when invoking

### ISSUE THREAD

**Issue by Chris-hughes10** [microsoft/semantic-kernel#5529]
Hi,

I am trying to run two functions sequentially, passing the output from the first into the second. I have been unable to find an example of this in the documentation. This was possible in previous versions, by taking advantage of the stateful context being overridden.

A simple example of what I am trying to do is:

` result = await kernel.invoke([function_1, function_2], arguments=KernelArguments(input=function_1_input)`

Where the desired behaviour is:
` function_2(function_1(function_1_input))`

Is this possible?

**Comment by markwallace-microsoft** [comment]
@Chris-hughes10 We have the following example which shows how to implement a pipeline of functions https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Getting_Started/Step8_Pipelining.cs

We made this into a sample rather than core functionality because we are expecting developers to want support for different scenarios and we want to allow for the freedom to implement what suits best for each developers use case.

**Comment by Chris-hughes10** [comment]
Thanks for the quick response! Do you have a corresponding Python sample?

**Comment by markwallace-microsoft** [comment]
@moonbox3 Do you have a pipelining sample for Python?

**Comment by moonbox3** [comment]
@Chris-hughes10 in Python this can be done with function handlers, but I believe you're already aware of that (based on your blog post). Are the function handlers not working properly?

**Comment by Chris-hughes10** [comment]
Hi @moonbox3, this issue actually pre-dates the blog post update. Function handlers do work for this, but I was wondering if this is the recommended approach, or if there is a more elegant way to do it; I implemented the function handler method after going through the source code, as I couldn't find any docs or samples addressing this.

**Comment by moonbox3** [comment]
Thanks for your response, @Chris-hughes10. We're working to make some improvements around how one can do this more elegantly. We don't have an exact timeline on it, but I would imagine it would land around the time we release v1 (mid-May).
