### ISSUE TITLE
Python: Chat service will always put the first message as system message, how to handle it with text completion?

### ISSUE THREAD

**Issue by HuskyDanny** [microsoft/semantic-kernel#5547]
**Describe the bug**
GPT4 has no text completion capability and I used it for single text completion at previous version, which was working fine. For the new beta version, the chat_history will always put the first message as system role instead of user role.
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/42811273-3ddb-4665-9d76-0fa50d90b7ec)

**To Reproduce**
```
            kernel.add_service(
                AzureChatCompletion(
                    service_id="azure_openai_chat4_service",
                    deployment_name=chat4_api_config.deployment_model_id,
                    ad_token_provider=get_bearer_token_provider(
                        DefaultAzureCredential(),
                        "https://cognitiveservices.azure.com/.default",
                    ),
                    endpoint=chat4_api_config.endpoint,
                )
              
        execution_settings = AzureChatPromptExecutionSettings(
            service_id="azure_openai_chat4_service",
        )
        query_expansion = self.get_semantic_function(kernel, "skills", "QueryExpansion")
        result = await query_expansion.invoke(
            kernel=kernel, input=condensed_question, settings=execution_settings
        )
              
```
              
**Expected behavior**
The first message should be user role. Or we should be able to configure the system message in config.json or skprompt.txt.

**Screenshots**

**Platform**
OS: Windows
IDE: VS Code
Language: Python
Source: semantic-kernel==0.9.2b1

**Additional context**

**Comment by HuskyDanny** [comment]
Right now I figured a work arounds for single prompt shot is to add a dummy user message:
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/ca70d22b-d494-43ef-8c1b-8e8bb4cb0d48)
Wondering if this is the only way to do it? It adds extra redundancy

**Comment by moonbox3** [comment]
Hi @HuskyDanny, I am working on responding to your other post in the Q&A section, but wanted to respond to this here. Can you help me understand something important: the title of this issue says you want to handle a system message for text completion? In your code snippet you're create an AI service for `AzureChatCompletion` and not `AzureTextCompletion`. Is that intentional? Text completion does not deal with chat history, it takes a [prompt](https://github.com/microsoft/semantic-kernel/blob/f0b1d0df783d0420904a7e07c4957c5ce7d00c48/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_completion_base.py#L37C9-L37C15) only.

**Comment by HuskyDanny** [comment]
Hi @moonbox3, thanks for replying. So I am using gpt4 and gpt3.5turbo which only supports chat completion. But I have some functionalities like summary or query rewrite which will use these models like text completion. If I go to text completion class, the api will return not supported error. So I could only go with chat completion for these 2 models. 

And I see the first message will be automatically set as system role, so I intentionally add chat_history and add one dummy user message, so that the chat_history will divide the prompt into system + user message and roles will be assigned correctly.

To illustrate:

Prompt:
Instruction: You are a summarizer to summarize the below input  ---> system message
{{$chat_history}} --->Add dummy user message
Input: {{$input}} ---> user message

**Comment by moonbox3** [comment]
Thanks for your reply, @HuskyDanny. Can you please try 0.9.4b1? We made the update to have the single message (without a chat history) to have the user role instead of the system role.

**Comment by HuskyDanny** [comment]
Hey @moonbox3, this is awesome to react this quick to fix it. I am trying with the new version. There are some breaking changes, I used to get over with it by the blog showing the summary and examples of these breaking changes. I am wondering if there is such one for this change? And what is the general recommendation for us to deal with the breaking changes? (Dedicated blog section for breaking changes etc..)

**Comment by HuskyDanny** [comment]
With the new version, I could not intentionally add system message. Both system and user message will be combined as a single user message:
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/3872224e-c7a9-4203-a918-3c1019a86489)

The root cause seems to be the from_rendered_prompt of chat_history, where it failed to parse the XML prompt. This exposes internal logic on how to handle prompt, not sure if this is user's responsibility to construct the prompt with XML tags? so posting here to see if this should be fixed.

![image](https://github.com/microsoft/semantic-kernel/assets/40053881/3691f4b5-b44d-4be5-b9f1-76eeb023e40c)

**Comment by moonbox3** [comment]
> Hey @moonbox3, this is awesome to react this quick to fix it. I am trying with the new version. There are some breaking changes, I used to get over with it by the blog showing the summary and examples of these breaking changes. I am wondering if there is such one for this change? And what is the general recommendation for us to deal with the breaking changes? (Like dedicated blog section for breaking changes? etc..)

Since we're still in beta, there may be further breaking changes until we get to v1.0 in May. We're working fast to try and get the breaking changes out of the way ASAP; however, things are still in flux before we get to v1, when we don't want any breaking changes. We're putting more focus on code velocity right now, and we're doing our best to document larger changes as we go. We are working on updating the docs, and when we land at v1, the docs will reflect a healthy state.

**Comment by moonbox3** [comment]
> With the new version, I could not intentionally add system message. Both system and user message will be combined as a single user message: ![image](https://private-user-images.githubusercontent.com/40053881/317154663-3872224e-c7a9-4203-a918-3c1019a86489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDUxMTgsIm5iZiI6MTcxMTU0NDgxOCwicGF0aCI6Ii80MDA1Mzg4MS8zMTcxNTQ2NjMtMzg3MjIyNGUtYzdhOS00MjAzLWE5MTgtM2MxMDE5YTg2NDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEzMDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkM2IwNmYxZDBjNzdhMzI5ODFiZjczZWQ0Yzk3MGZhMjA2YTU2MWFkYWVjMDdhMTFhMTNjMjk5MmI4OWEyOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YUiuw5Xwif6XwvLVV3ZK22L9Xq4YgdzNm5ZW6ay04gI)
> 
> The root cause seems to be the from_rendered_prompt of chat_history, where it failed to parse the XML prompt. Should we have a XML invalid or special token removal so that the retrieved content will not interfere the flow?
> 
> ![image](https://private-user-images.githubusercontent.com/40053881/317156045-3691f4b5-b44d-4be5-b9f1-76eeb023e40c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDUxMTgsIm5iZiI6MTcxMTU0NDgxOCwicGF0aCI6Ii80MDA1Mzg4MS8zMTcxNTYwNDUtMzY5MWY0YjUtYjQ0ZC00YmU1LWI5ZjEtNzZlZWIwMjNlNDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEzMDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMGQ5Y2I4MmEwNDM4MzFmMWRiMzA2ZmE2ZTc5OWUzNzI3Zjg5MGU3NWVjNjliNDgyNjg0NjNhMGQ1MjViNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O1UmsYrKOqieUj50PJPGIvY-2gxnQ5ICLcnlMSlhZBQ)

You can use XML as you see to generate a prompt with a system tag. You can use a chat history that can be explicitly set with a system message, like `chat_history = ChatHistory(system_message="<some message>")` or `chat_history.add_system_message("")`.

Could you help me understand why couldn't structure your prompt in the following way (as an example?

```
chat_function = kernel.create_function_from_prompt(
    prompt="""{{$chat_history}}{{$user_input}}""",
    function_name="chat",
    plugin_name="chat",
    prompt_execution_settings=req_settings,
)

history = ChatHistory()
history.add_system_message("You are a summarizer to summarize the below input.")

answer = await kernel.invoke(
        chat_function,
        user_input=user_input,
        chat_history=history,
    )
```

This gets parsed into two distinct messages that will be sent to the model -- one system and one user.

**Comment by HuskyDanny** [comment]
Yes, I did structure this way, in my case, one more piece is the CONTEXTS, which pulls the data from vector db.
So the prompt is like """{{$chat_history}}{{$contexts}}{{$user_input}}""". And I have confirmed the contexts's some special character could break the XML parse, like adding the extra "<>" in the content.

So by leveraging XML parse library, it introduces a point of failure especially for RAG system where the retrieval might have special characters for XML. Will the semantic kernel consider handling it?

**Comment by moonbox3** [comment]
Thanks for your reply, @HuskyDanny. Tagging @eavanvalkenburg so we can chat about this.

**Comment by moonbox3** [comment]
@HuskyDanny are you still having issues with this?

**Comment by moonbox3** [comment]
@HuskyDanny, haven't heard back from you in a while. Closing this issue. If needed, please re-open or create a new one. Thank you.
