### ISSUE TITLE
Python: Action Planner breaking when parameters are not explicitly given in the ask

### ISSUE THREAD

**Issue by ArfiArfath21** [microsoft/semantic-kernel#5583]
**Describe the bug**
When we change the ask in the action planner example to something that doesnt explicitly mention the parameters, it fails to generate any response and breaks down.

**To Reproduce**
1. Go to 'semantic-kernel/python/samples/kernel-syntax-examples/action_planner.py'
2. change the "ask" in line 29 to something generic. Ex: ask="What is the date today?"
3. Run the script.

**Expected behavior**
It should have given a proper response like 

**Screenshots**
Error:
![image](https://github.com/microsoft/semantic-kernel/assets/76872284/0c3247ff-d069-427f-ab7e-9a017f4e8dd1)
Expected:
![image](https://github.com/microsoft/semantic-kernel/assets/76872284/a1fe357c-6cac-4d86-9f58-ada03d62c359)

**Platform**
 - OS: MacOS Sonoma 14.3.1
 - IDE: VS Code
 - Language: Python

**Comment by moonbox3** [comment]
Closing as the fix is in main. Will be included in the next release.
