### ISSUE TITLE
bug running book creator sample

### ISSUE THREAD

**Issue by giannik** [microsoft/semantic-kernel#559]
Running locally the book creator sample I get the following error when creating the  book : 
![image](https://user-images.githubusercontent.com/1516981/233338111-bd58a30c-c6c2-4a4c-a8cb-45afd7312ed5.png)

**Comment by evchaki** [comment]
@giannik can you provide any additional details on when this is happening. Can you also look in the dev tools to see if there are any errors.

**Comment by craigomatic** [comment]
This can sometimes happen as the model is non-deterministic and based on the default token length we specify, it may cut off the end of the JSON we are asking it to return. 

In addition to what Evan asks above, if you try running the sample a few times do you always hit this error?

We did just roll out some changes to planner that may impact this also, I will investigate.

**Comment by giannik** [comment]
I just tried with latest source code and it works! 
Thank you.
