### ISSUE TITLE
Python/samples/kernel-syntax-examples/openapi_example does not work due to deprecation of ContextVariables

### ISSUE THREAD

**Issue by ColtonBehannon** [microsoft/semantic-kernel#5604]
**Describe the bug**
The sample file will not run as it still makes use of ContextVariables which have been deprecated

**To Reproduce**
1. Go to python/samples/kernel-syntax-examples/openapi_example
2. Follow the instructions in the README.md
3. See error when running openapi_client.py

**Expected behavior**
The file should run as expected from the README

**Error Message**
AttributeError: module 'semantic_kernel' has no attribute 'ContextVariables'

**Platform**
 - OS: Ubuntu
 - IDE: VS Code (via WSL2)
 - Language: Python
 - Source: main branch of repository

**Comment by moonbox3** [comment]
Hi @ColtonBehannon thanks for raising the issue. I'm working on getting this updated right now, actually, and am adding support to be able to import and run OpenAI plugins as well (with auth). This is my priority right now, and should be done soon.

**Comment by ColtonBehannon** [comment]
That's great to hear! I actually found a related bug that should probably be in its own issue, but I wanted to bring it up while you're working on this.

The prepare_request method of the RestApiOperation class in kernel_openapi.py incorrectly parses URLs with more than one slash as a result of using urljoin. 

### Example ###
OpenAPI Server URL: https://api.website.com/domain/field
OpenAPI Path: /v1/endpoint
Correct full endpoint: https://api.website.com/domain/field/v1/endpoint
What the code returns: https://api.website.com/v1/endpoint

### How to identify/reproduce: ###
```
url = urljoin(self.server_url, path)
print(f"URL being used for request: {self.server_url}")
print(f"Path being used for request: {path}")
print(f"Full URL being used for request: {url}")
```

I have replaced the urljoin line with the code below. It has not been tested against various endpoints but it works with the one that I am using (though I'm sure there is a more elegant solution).
```
if not self.server_url.endswith("/"):
    self.server_url += "/"
if path.startswith("/"):
    path = path.lstrip("/")
url = self.server_url + path
```

**Comment by moonbox3** [comment]
Sorry you had to spend time on this -- I found that during my testing and just fixed it. :)
