### ISSUE TITLE
.Net: Integrate SSE Parser for AIService streaming

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#5610]
See: https://github.com/microsoft/semantic-kernel/pull/5548#discussion_r1530297204

**Comment by stephentoub** [comment]
@jeffhandley, @ericstj, fyi re https://github.com/dotnet/runtime/issues/98105

**Comment by Krzysztof318** [comment]
Related to #5574

**Comment by Krzysztof318** [comment]
@markwallace-microsoft I need specialized SSE parser for Claude 3, because claude utilizes events, not only data. So you can assign it to me and I take care for that.

**Comment by MediVik333** [comment]
I'm working at the moment I'll be back later after 22:00 and I'll tex you


вс, 31 мар. 2024 г., 16:26 Krzysztof Kasprowicz ***@***.***>:
