### ISSUE TITLE
.Net: Not able to add files to already created Agent

### ISSUE THREAD

**Issue by nssidhu** [microsoft/semantic-kernel#5611]
**Describe the bug**
I get error when i try to add file (either already uploaded file or newly uploaded file) to an assistant that is already created.
If i create new assistance i can add files before creating instance assistant, but not after it is created.

 ```
systemPrompt = "You are a helpful assistant that can visually describe the data from files you know about. Write and run code to answer questions.";
 var options = new AssistantCreationOptions(AzureOpenAIDeploymentModelName)
 {
     Name = AssistantName,
     Instructions = systemPrompt,
     Tools = { new RetrievalToolDefinition(), new CodeInterpreterToolDefinition() },
 };

 if(fileIds != null)
 {
     foreach (var fileId in fileIds)
     {
         options.FileIds.Add(fileId);
     }
 }

 assistantResponse = await _AssistantClient.CreateAssistantAsync(options);
 _Assistant = assistantResponse.Value;
```
 
The step above works, becuase i am adding files before creating instance of Agent/Assistant.

But if i want to add additonal files to this agent.

I upload a file using the code below.
 ```
Response<OpenAIFile> uploadAssistantFileResponse = await _AssistantClient.UploadFileAsync(
  localFilePath: path,
  purpose: OpenAIFilePurpose.Assistants);
  
  and then add file to the agent  i get error.
  
   _AssistantClient.LinkAssistantFile(_Assistant.Id, uploadAssistantFileResponse.Value.Id);
  
```
I get the following Error.

`Azure.RequestFailedException: Failed to index file: Unsupported file file-12puXpk3pLSCku0yISVefHlj type: text/csv error_code: unhandled_mimetype Status: 400 (Bad Request) Content: { "error": { "message": "Failed to index file: Unsupported file file-12puXpk3pLSCku0yISVefHlj type: text/csv error_code: unhandled_mimetype", "type": "invalid_request_error", "param": null, "code": null } } Headers: Date: Fri, 22 Mar 2024 13:38:54 GMT Connection: keep-alive openai-version: REDACTED openai-organization: REDACTED X-Request-ID: REDACTED openai-processing-ms: REDACTED Strict-Transport-Security: REDACTED CF-Cache-Status: REDACTED Set-Cookie: REDACTED Server: cloudflare CF-RAY: REDACTED Alt-Svc: REDACTED Content-Type: application/json Content-Length: 226 at Azure.Core.HttpPipelineExtensions.ProcessMessage(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken) at Azure.AI.OpenAI.Assistants.AssistantsClient.LinkAssistantFile(String assistantId, RequestContent content, RequestContext context) at Azure.AI.OpenAI.Assistants.AssistantsClient.LinkAssistantFile(String assistantId, String fileId, CancellationToken cancellationToken) at AIChatWebApp.Components.Pages.Assitant.UploadFiles(InputFileChangeEventArgs e) in`

  

**To Reproduce**

**Expected behavior**
I should be able to add either existing files or newly uploaded file to already created instance of an Assistant.

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by evchaki** [comment]
@crickman can you take a look?

**Comment by crickman** [comment]
Thanks for posting this question @nssidhu.  I'll investigate and respond by monday, at the latest.

.csv is only supported for code-interpreter, not retrieval:  https://platform.openai.com/docs/assistants/tools/supported-files

FYI: you are posting in the SemanticKernal repo for issues related to the Azure Assistant Client:

https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/openai/Azure.AI.OpenAI.Assistants

**Comment by crckman** [comment]
Have you considered posting to the code-owner repo?

https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/openai/Azure.AI.OpenAI.Assistants

**Comment by nssidhu** [comment]
Yes i did that
https://github.com/Azure/azure-sdk-for-net/issues/42931
