### ISSUE TITLE
Python: Azure OpenAI on your data API version

### ISSUE THREAD

**Issue by gbaeke** [microsoft/semantic-kernel#5620]
**Describe the bug**
Azure OpenAI on your data in combination with Semantic Kernel seems to only support version 2023-12-01-preview. That version will be retired soon.

**To Reproduce**
Simply try to run the sample at https://github.com/microsoft/semantic-kernel/blob/main/python/samples/kernel-syntax-examples/azure_chat_gpt_with_data_api.py with another API version later than 2023-12-01-preview.

**Expected behavior**
Azure OpenAI on your data should work with API versions more recent than 2023-12-01-preview.

**Additional information**
Azure AI on your data in combination with function calling does not work either. The error message is that the API version does not support function calling. The sample https://github.com/microsoft/semantic-kernel/blob/main/python/samples/kernel-syntax-examples/azure_chat_gpt_with_data_api_function_calling.py can be used to verify that. I have not been able to get that to work potentially also due to API version issues.

**Comment by moonbox3** [comment]
Hi @gbaeke, thanks for raising the issue. We're working with the OYD team to get their code updated to use the latest API. There are some breaking changes, and we will have this in before the API deprecation date.
