### ISSUE TITLE
.Net: Support FunctionCallContent in YAML prompts

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#5632]
These requirements have been moved from the https://github.com/microsoft/semantic-kernel/issues/5153 issue to this one, as they are not necessarily needed for the implementation of the FunctionCallContent feature but can instead be built on top of it:

- YAML support for function calls – A function call and tool result can be written in a YAML prompt template using the intermediate prompt template language. This will allow a developer to implement few shot examples for function calling within prompts. A new tag (e.g., <FunctionCall> is likely necessary to achieve this).
- YAML support for function results – A function result can be written in a YAML prompt template as a tool message.
- YAML support for defining available functions – as a prompt engineer, you should be able to state which functions are available for the LLM to call.

If possible, we should try to align the syntax with [.promptfile](https://promptfile.org/blocks). They use `<functions>` and `<function>` tags.

**Comment by deepinderdeol** [comment]
@markwallace-microsoft is it possible to specify function calls in a YAML prompt?
