### ISSUE TITLE
.Net: Response ContentType Checking Logic too Restrictive

### ISSUE THREAD

**Issue by ppotash** [microsoft/semantic-kernel#5636]
**Describe the bug**
In reference to the 3 lines of code here https://github.com/microsoft/semantic-kernel/blob/9ab95132b5f460f1bf9a1d1e387fb18453a037f4/dotnet/src/Functions/Functions.OpenApi/Extensions/RestApiOperationResponseExtensions.cs#L37 `ContentType` can be slightly more complicated than what is expected in this switch statement. For example, I'm running a plugin where the following `ContentType` is returned:
![image](https://github.com/microsoft/semantic-kernel/assets/4130298/6157af13-56ac-49d4-86d8-f751e582cf19)
I propose to modify the checking login to be slightly more broad by using `Contains` to work for the above case. I can draft a PR to modify the referenced lines.

**Comment by markwallace-microsoft** [comment]
@ppotash Thanks for the issue, can you create a PR for the proposed change and we'll take a look

**Comment by ppotash** [comment]
https://github.com/microsoft/semantic-kernel/pull/5642
