### ISSUE TITLE
Python: Repository splitting

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/semantic-kernel#5656]
Currently, we placed all the support across languages/frameworks in one repo, is it possible to split by language?

As a dotnet developer, I only care about the dotnet-related changes, and no need to download the python/java implementations, but since it's all in one repo, I had to fetch them all.

Besides, there are more and more connectors, is it possible to split non-core connectors into another repository/solution? So that we could maintain the core framework and functions easily, and extensions in another or extensions in another solution file?

For multiple languages/frameworks support, I like the open-telemetry repository organization. https://github.com/open-telemetry

They put up the Specifications in a repo, and for the language-specific implementation, separate into different repositories, and core implementation for the spec in one repository, some extensions out of spec maintained in another repo.

Thoughts?

**Comment by RogerBarreto** [comment]
@markwallace-microsoft Good opportunity for an ADR on our decisions for keeping all in once.

**Comment by moonbox3** [comment]
[This](https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0030-branching-strategy.md) ADR goes into the decisions to keep it in one repo right now.

**Comment by moonbox3** [comment]
Going to close this issue right now as the ADR I linked to is where we currently stand. Thanks for asking, @WeihanLi.

**Comment by WeihanLi** [comment]
seeing https://github.com/microsoft/semantic-kernel/pull/6820, maybe worth another decision
