### ISSUE TITLE
.Net Gemini Connector - Allow Version Selection and Base Url overriding.

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#5659]
> The `v1beta` part of the URL is going to change and there may be times when multiple versions will be supported at the same time.

> We should have:

> A central place where the default API version is set
> We should consider if we want to allow developers to change this. We do allow this in Azure OpenAI. It's a risky thing for a developer to do but that doesn't mean someone may have a good reason and we don't necessarily want to block them.

Basically when using `AddGeminiChatCompletion` we should be able to specify the target version in the service `Settings`, this will be adjusting the correct Uri of the client `v1beta` or `v1`, etc.

Not very sure about be able to override the `endpoint` as I don't see a potential mock or virtualization of `GCP` to be targetted (edge case).

**Comment by Krzysztof318** [comment]
I also think creating custom endpoint overload doesn't make sense.
