### ISSUE TITLE
All skills reported TypeError: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by twwch** [microsoft/semantic-kernel#566]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac m1 pro
 - IDE: VS Code
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**
![image](https://user-images.githubusercontent.com/44161003/233518268-6995d083-48d7-4ffb-aa39-ad435607581b.png)

**Comment by craigomatic** [comment]
@markwallace-microsoft

**Comment by markwallace-microsoft** [comment]
Hi @twwch 
can you go to the developer tools console (Help -> Toggle Developer Tools) and grab the full error and stacktrace from there?

**Comment by twwch** [comment]
![image](https://user-images.githubusercontent.com/44161003/233835377-9f64c0e1-779c-47a2-8034-c608180fdad1.png)
![image](https://user-images.githubusercontent.com/44161003/233835388-94b593fc-9cf9-4184-a6d3-1eb9713f97c5.png)

**Comment by evchaki** [comment]
@markwallace-microsoft  can you close this if it is complete
