### ISSUE TITLE
Python: Function Calling Stepwise Planner - Max Tokens Ignored after First Call

### ISSUE THREAD

**Issue by kevin-m-kent** [microsoft/semantic-kernel#5661]
**Describe the bug**
I've been experimenting with the Function Calling Stepwise Planner in python (really awesome, thanks for implementing this). I noticed that the first chat completion call respects the max_completion_tokens setting given in the FunctionCallingStepwisePlannerOptions config. However, all the subsequent calls seem to pull from the default from OpenAIPromptExecutionSettings and for me this meant it defaulted back to 256. Function calling seems to consistently require more tokens for its response so this results in responses that terminate with a finish_reason of 'length' and the function call isn't in the right format and things break. Experimenting locally I tweaked the default OpenAIPromptExecutionSettings's max_tokens and I could see that this is what is being followed after the first chat completion. 

**To Reproduce**
1. Use the Function Calling Stepwise Planner with a max_completion_tokens setting other than 256. 
2. Execute any ask (for me I even saw this when the ask was 'hi')
3. Look at the logs, observe the first and subsequent max_token settings. 
4. Observe the max_completion_tokens setting only honored on the first call.

**Expected behavior**
FunctionCallingStepwisePlannerOptions's max_completion_tokens followed for all calls.

**Screenshots**
N/A

**Platform**
 - OS: Mac
 - IDE: Vs Code
 - Language:Python
 - Source: main branch of this repo

**Additional context**
If I have time I can try to investigate further, but right now this is the best I can do!
I was using gpt4 for these tests.

**Comment by moonbox3** [comment]
Hi @kevin-m-kent, thank you for reporting this issue. I'll have a look and get a fix in ASAP.

**Comment by moonbox3** [comment]
@kevin-m-kent, I've got a PR out for this. Funny enough, we weren't even setting the max_tokens / max_auto_invoke_attemps if configured as part of the function calling stepwise planner options. Thanks for catching this.

I stepped through both of the OpenAI/AzureOpenAI Chat Completions for this planner and confirmed that based on my options, the prompt_execution_settings.max_tokens = 400 were used for all calls. Could you have a look, please? Thanks.

**Comment by kevin-m-kent** [comment]
great to hear, thanks! I do see that setting that execution setting does work, but for some reason I only see it on every call after the first (the first for me still defaults to 256). maybe I'm doing something wonky. this is how I'm setting it:

```
    options = FunctionCallingStepwisePlannerOptions(
        execution_settings=
            AzureChatPromptExecutionSettings(
                max_tokens=400
            )

    ) 
```

**Comment by kevin-m-kent** [comment]
actually I think my issue with the first call is likely some local version conflict. so I think it's good.

**Comment by moonbox3** [comment]
With the change I am proposing, it will give precedence to the FunctionCallingStepwisePlannerOptions `max_completion_tokens` attribute, if set, and if not, it will use whatever is configured in the `OpenAIChatPromptExecutionSettings`. Therefore, if you can do one of these:

```
options = FunctionCallingStepwisePlannerOptions(
    max_iterations=10,
    execution_settings=kernel.get_service(service_id).get_prompt_execution_settings_class()(
        service_id=service_id,max_tokens=1000,
    ),
)
```
or
```
    options = FunctionCallingStepwisePlannerOptions(
        max_iterations=10,
        max_tokens=6500,
        execution_settings=kernel.get_service(service_id).get_prompt_execution_settings_class()(
            service_id=service_id,
        ),
    )
```
Based on the init logic in the planner options, the token usage is computed via some specified/default ratio.

**Comment by kevin-m-kent** [comment]
Ah I see ok, I was missing the bit about the init logic. Thanks for explaining

**Comment by moonbox3** [comment]
No problem. In any case, I think it's good to establish this order of precedence for setting `max_tokens`, so it was a great call out by you. Thank you again. As we work on the documentation for v1, we will make sure this gets called out and is clear so all users understand how the configuration needs to be.

**Comment by kevin-m-kent** [comment]
great! looking forward to the release.
