### ISSUE TITLE
Python: ChatInterface multimodal, files are List[str] not List[Dict]

### ISSUE THREAD

**Issue by yolo661798** [microsoft/semantic-kernel#5674]
ChatInterface multimodal bug

in gradio/chat_interface.py
line 468, in _append_multimodal_history
    history.append([(x["path"],), None])
TypeError: string indices must be integers

**Comment by hherb** [comment]
I get the same error - only started happening after a recent update

**Comment by moonbox3** [comment]
Hello @yolo661798 and @hherb, could you give us a little bit more information about what code you have that is then failing? I see `gradio` is a dependency in our `poetry.lock` file. The more detail you can provide, the better we can help you. Thanks.

**Comment by metal3d** [comment]
I've got exactly the same, the code to reproduce is simply having:

```python
demo = gr.ChatInterface(
   fn=response,
   multimodal=True,
)
demo.launch()
```

The `response` function: `def(inp, hist):` doesn't manipulate the history (only read to recreate the prompt). The error happens before the `response` function is called.

**Comment by metal3d** [comment]
To give precision: the `inp` argument receives a dict : 
`
{ "text": "the user text is here", "files": ['/path/to/the/image']}
`

The file is stored in `/tmp`.

That means that the `ChatInterface` fails to get the "files" value (list), but seems to use the entire input (dict)

**Comment by MediVik333** [comment]
I try to understand how it works , all information is in Microsoft

**Comment by metal3d** [comment]
the bug is in `_append_multimodal_history` function, the "input" format is not well interpreted

**Comment by MediVik333** [comment]
Thanks

**Comment by metal3d** [comment]
This has been fixed here: https://github.com/gradio-app/gradio/pull/7875

This will be OK in the next release (or install the main branch from the project)

**Comment by MediVik333** [comment]
Sorry, go to sleep  for a few hours and come back to try fix it

**Comment by moonbox3** [comment]
Closing this as it isn't exactly related to SK Python.
