### ISSUE TITLE
Python: BadRequestError: Unsupported data type

### ISSUE THREAD

**Issue by DavidHWWang** [microsoft/semantic-kernel#5697]
**Describe the bug**
When manually adding memories, encounter
`ServiceResponseException: ("<class 'semantic_kernel.connectors.ai.open_ai.services.azure_text_embedding.AzureTextEmbedding'> service failed to generate embeddings", BadRequestError('Unsupported data type'))`

I've deployed text-embedding-ada-002 on Azure openai studio, and changed deployment_name in notebook.

**To Reproduce**
1. Go to 'python\notebooks\06-memory-and-embeddings.ipynb'
2. Run `await populate_memory(memory)`

**Platform**
 - OS: Windows 11
 - IDE: VS Code
 - Language: Python 3.11.5
 - Source: semantic-kernel==0.9.4b1

**Comment by DavidHWWang** [comment]
Hi @moonbox3 . I found out that I set the wrong endpoint. Thanks.

**Comment by moonbox3** [comment]
Glad you got it figured out! Will close the issue.

**Comment by StrideIT** [comment]
@moonbox3 hint fixed my issue. Endpoint var was missing. Thank you

**Comment by abnermusonda** [comment]
> Hi [@DavidHWWang](https://github.com/DavidHWWang), could you please verify your model deployment? I am running the following, and it works well for me:
> 
> ![image](https://github.com/microsoft/semantic-kernel/assets/35585003/73e51049-e1e4-470a-8ea0-f62e3857ad44)
> 
> ![image](https://github.com/microsoft/semantic-kernel/assets/35585003/a4b84102-e1d7-41f8-affc-642264be9ae0)

Thanks this also fixed my issue -this is what it looks like in the latest code.

![Image](https://github.com/user-attachments/assets/1fc361ba-b850-4011-bfa6-78d289c3cc5b)
