### ISSUE TITLE
Python: __kernel_function_parameters__ still treat argument as class<str> even though Annotated with List[str]

### ISSUE THREAD

**Issue by HuskyDanny** [microsoft/semantic-kernel#5704]
**Describe the bug**
My text memeory plugins want to take a list of queries instead of a single query, so I annotated with List[str], but the kernel still treat it as str, which break the downstream flow.
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/1663dd4c-b03a-4959-840d-40e7ed08d8a8)
You can see here the kernel treats the "queries" as str.
Event though I have updated it to List[str] here
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/dd41279b-1e7a-49c9-a0fd-526616a2dd65)

**To Reproduce**
Have a new class which extends the default TextMemoryPlugin, overwrite the recall function with queries annotated as List[str].

Then call the function with a list of str. Due to the wrong type cast, the list will be casted into string representation.

**Expected behavior**
If I annotated with List[str], the queries should be a list of str instead of string representation of list
**Screenshots**

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: Python
 - Source: semantic-kernel==0.9.4b1
**Additional context**

**Comment by moonbox3** [comment]
Thanks for filing the issue, @HuskyDanny. I believe @eavanvalkenburg caught this already and it will be fixed as part of this large typing fix PR (#5613).

**Comment by eavanvalkenburg** [comment]
@HuskyDanny have you had a chance to try this with the latest package?
