### ISSUE TITLE
.Net: Update instructions in CONTRIBUTING.md

### ISSUE THREAD

**Issue by hsm207** [microsoft/semantic-kernel#5711]
**Describe the bug**

From the CONTRIBUTING.md file under Development Scripts for .NET we have:

> Build/Test: run build.cmd or bash build.sh
> Linting (auto-fix): dotnet format

but running `bash build.sh` throws an error

**To Reproduce**
1. Clone the repo
2. In the project's root folder, run `bash build.sh`. This will throw:

>     bash: build.sh: No such file or directory

3. Run `cd dotnet` and then `bash build.sh`.  This will throw:

>  build.sh: line 8: cd: dotnet: No such file or directory

**Expected behavior**
It should build/test the project successfully

**Screenshots**
NA

**Platform**
 - OS: Debian GNU/Linux 11 (bullseye)
 - IDE: VS Code
 - Language: C#
 - Source: main branch (dfd866b9adf51397a1d5b12bb0a0545adad1002d)

**Additional context**
NA

**Comment by glahaye** [comment]
@hsm207 Using Ubuntu, it just works for me.

What happens if you go in the dotnet folder and then enter the following command:
**dotnet build --configuration Release --interactive**

**Comment by hsm207** [comment]
@glahaye If go to the `dotnet` folder and run `dotnet build --configuration Release --interactive`, the build fails with this error:

> /usr/share/dotnet/sdk/7.0.406/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(221,5): error : Could not find a part of the path '/workspaces/semantic-kernel/dotnet/nuget'. [/workspaces/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj]

The build is succesful if I run:

`dotnet build --configuration Debug  --interactive`

**Comment by MediVik333** [comment]
How to do now ?   Can I go  for some rest ?
