### ISSUE TITLE
Python: code coverage GH action shouldn't fail if required status checks aren't run

### ISSUE THREAD

**Issue by moonbox3** [microsoft/semantic-kernel#5712]
**Describe the bug**
Right now, if a community member creates a PR, the Python test coverage GH action fails because the other required GH actions steps aren't run yet. The test coverage step shouldn't fail, but should wait to run as well.

**Expected behavior**
The user shouldn't see a failure on the GH actions if their required checks haven't run yet.

**Comment by MediVik333** [comment]
> **Describe the bug**
> Right now, if a community member creates a PR, the Python test coverage GH action fails because the other required GH actions steps aren't run yet. The test coverage step shouldn't fail, but should wait to run as well.
> 
> **Expected behavior**
> The user shouldn't see a failure on the GH actions if their required checks haven't run yet.

How?

**Comment by moonbox3** [comment]
> > **Describe the bug**
> > Right now, if a community member creates a PR, the Python test coverage GH action fails because the other required GH actions steps aren't run yet. The test coverage step shouldn't fail, but should wait to run as well.
> > **Expected behavior**
> > The user shouldn't see a failure on the GH actions if their required checks haven't run yet.
> 
> How?

Here's an example of a PR where this is happening: #5686.

![image](https://github.com/microsoft/semantic-kernel/assets/35585003/481719fb-99ec-4df5-8dc9-e87ff8d29ce6)
