### ISSUE TITLE
.Net: Support for consequential attribute and HTTP method attributes for KernelFunction

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#5724]
For #5506 and #5694

## Context

Today, `KernelFunction` has a metadata property that includes the following information:

```csharp
public sealed class KernelFunctionMetadata {	
        public KernelFunctionMetadata(string name);
        public KernelFunctionMetadata(KernelFunctionMetadata metadata);
        public string Description { get; init; }
        public string Name { get; init; }
        public IReadOnlyList<KernelParameterMetadata> Parameters { get; init; }
        public string? PluginName { get; init; }
        public KernelReturnParameterMetadata ReturnParameter { get; init; }
}
```

## User story

This metadata doesn't have a way to add additional information that can be used elsewhere in the system to determine if a function is "consequential" (i.e., requires customer approval). This metadata would be most useful within the `FunctionInvokingEventArgs` so a developer can request human approval for functions.

For example, knowing the HTTP method of an OpenAPI imported function could be helpful to provide approval functionality (e.g., GET requests wouldn't require approval, but PUT and POST could).

## Options

There are a couple options for handling this. Several of these options can be used together to address short comings.

### Option 1: add a boolean value for `IsConsequential` in `KernelFunctionMetadata`

With a `bool IsConsequential` property on the metadata, an app developer could provide a boolean on whether a function requires approval or not.

*Pro:* This is very simple and maps to the is-consequential flag. Could be easily set with a decorator.
*Con:* This is not scalable to other metadata (like HTTP methods).

### Option 2: add a metadata property to `KernelFunctionMetadata`

With a `Dictionary<string, object> Metadata` property on the metadata, an app developer could provide any arbitrary data that could be accessed elsewhere in the system. There could be a reserved key for `IsConsequential` so that helper methods and decorators can be provided. HTTP methods could live under a key called `Method`, for example...

```json
{
    "method": "POST"
}
```

*Pro:* This can scale to any future attributes that we need to store.
*Con:* The logic to determine if something "is consequential" is forced to be included in each of the filters, which makes it difficult to reuse filters across functions with different attributes.

### Option 3: add an `IsConsequential()` method

Add a `bool IsConsequential()` method on `KernelFunction`. This would allow a developer to customize the business logic for each function. What's less clear is _how_ this method would be defined. There should likely be default behavior (e.g., if the is-consequential flag is set) and a way to set the method during import time.

*Pro:* The logic for is consequential can be fully customized and is tied directly with the function.
*Con:* Unclear how to set the method

### Option 4: override isConsequential in `IFunctionFilter`

Update

```
public class SecondFunctionFilter : IFunctionFilter
{
    public void OnFunctionInvoking(FunctionInvokingContext context) =>
    {
        context.IsConsequential = true
    }
}
```

*Pro:* The logic for is consequential can be fully customized with existing filters.
*Con:* The developer must guarantee that all of the function filters that determine `IsConsequential` happen before any filters that act on the `IsConsequential` flag.

### Option 5: provide a Filter that determines if a function Is Consequential

Provide a custom filter that determines if a function Is Consequential. This filter would be called before the `FunctionInvoking` filter. In the filter, the developer could use the metadata to return a true / false value that could then be used by the `FunctionInvoking` filter.

```
public class ConsequentialFilterExample : IIsConsequentialFilter
{
    public void IsConsequential(IsConsequentialContext context)
    {
        context.IsConsequential = true
    }
}
```

*Pro:* The logic for is consequential can be fully customized and multiple is consequential filters can be used before the `FunctionInvoking` filter is triggered (which would show the approval UX).
*Con:* Separates the business logic from the actual plugin

**Comment by matthewbolanos** [comment]
This will definitely require an ADR to explore more options and to land on a preferred approach. I'm current leaning towards combining Option 2 and Option 4.

**Comment by darrelmiller** [comment]
I like Option 2.  Being able to pass through x- headers into SK functions would be great.

**Comment by westey-m** [comment]
Merged the changes.  See an example of usage here:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example23_OpenAPIPlugin.cs
