### ISSUE TITLE
.Net: Optional parameters in KernelArguments and Plans

### ISSUE THREAD

**Issue by arnabg1985** [microsoft/semantic-kernel#5778]
Issue: We are creating the plans using the KernelArguments. Also we are using the OpenAPI specification for the plugin for which we are generating the Handlebar Plan. However in the generated plan there is no way to identify the parameters which are optional in nature. Can you please help.

Example: The parameter param_3 is optional in the below example. However, there is no indicator present in the generated plan to identify param_3 as an optional parameter.

IDictionary<string, object> nameValuePairs = new Dictionary<string, object>();
nameValuePairs.Add("param_1", "value_1");
nameValuePairs.Add("param_2", "value_2");
nameValuePairs.Add("param_3", "value_3");

var handlebarsArguments = new KernelArguments(nameValuePairs);
HandlebarsPlanner handlebarsPlanner = new HandlebarsPlanner();
HandlebarsPlan handlebarsPlan;
handlebarsPlan = handlebarsPlanner.CreatePlanAsync(kernel, goal, initialContext).Result;

Sample Generated Plan:

[!-- Step 1: Set predefined variables --]
{{set "racfid" @root.param_1}}
{{set "faldEnt" (array @root.param_1)}}
{{set "fald" (array @root.param_3)}}
{{set "symbols" (array @root.param_2)}}

[!-- Step 2: Call getPositionCrossReference function --]
{{set "getPositionData" (PositionCrossReferencePlugin.getPositionCrossReference racfid=racfid faldEnt=faldEnt fald=fald symbols=symbols)}}

**Comment by teresaqhoang** [comment]
Closing as resolved
