### ISSUE TITLE
.Net: Agent Naming

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#5780]
In the `AgentFramework`  there are numerous opportunities to explore naming alignment.

## Core Concepts

- Agent: A discrete actor that can participate with other actors in a nexus
- Nexus: Agents interacting in a common context / conversation
- Channel: The protocol used by an agent to communicate with the nexus

![image](https://github.com/microsoft/semantic-kernel/assets/66376200/32cd7ba6-f46a-48c7-9f8c-2987d9da1493)

https://github.com/microsoft/semantic-kernel/blob/adr_agent_architecture/docs/decisions/0039-agent-interactions.md

Current naming convention:

Class Name|Parent Class|Role|Modality|Note
-|-|-|-|-
Agent|-|Agent|Abstraction|Root agent abstraction
ILocalAgent|-|Agent|Abstraction|Polymorphic contract to enable definition of LocalKernelAgent
KernelAgent|Agent|Agent|Abstraction|Includes `Kernel` services and plug-ins
LocalKernelAgent|KernelAgent,ILocalAgent|Agent|Abstraction|Base class for agents that manage chat-history locally (not o
NexusAgent|Agent|Agent|Utility|`Agent` adapter based on `AgentNexus`
ChatCompletionAgent|KernelAgent|Agent|SemanticKernel|A functional agent based on `IChatCompletionService`
OpenAIAssistantAgent|KernelAgent|Agent|Assistant API|A functional agent based on *OpenAI Assistant API*
AgentChannel|-|Channel|Abstraction|Allows an agent to participate in a nexus.
LocalChannel|AgentChannel|Channel|Utility|Concrete channel for agents based on local chat-history.
OpenAIAssistantChannel|AgentChannel|Channel|Assistant API|Channel associated with `OpenAIAssistantAgent`
AgentNexus|-|Nexus|Abstraction|Provides core capabilities for agent interactions.
AgentChat|AgentNexus|Nexus|Utility|Strategy based nexus
GroupChat|AgentNexus|Nexus|AutoGen.Net|AutoGen.Net nexus implementation

## Decision Point

Class Name|Final Name
-|-
Agent|Agent
ILocalAgent|???
KernelAgent|KernelAgent
LocalKernelAgent|???
NexusAgent|???
ChatCompletionAgent|ChatCompletionAgent
OpenAIAssistantAgent|OpenAIAssistantAgent
AgentChannel|???
LocalChannel|???
OpenAIAssistantChannel|OpenAIAssistantChannel
AgentNexus|???
AgentChat|???
GroupChat|GroupChat

**Comment by markwallace-microsoft** [comment]
@crickman descriptions of the classes/interfaces would help in determining the correct naming. I've taken a pass below but could you add these with corrections to you table above?

Class Name|Final Name|Description
-|-|-
ILocalAgent|???|Interface which is implemented by `Agent`'s which can interact using a `ChatHistory`
LocalKernelAgent|???|Class which represents a `KernelAgent` which can interact using a `ChatHistory`
NexusAgent|???|What is this?
AgentChannel|???|Class which represents the communication channel for an `Agent`
LocalChannel|ChatHistoryChannel|Class which represents a `ChatHistory` based communication channel for an `Agent`
AgentNexus|AgentRelay AgentHub|Class which represents the interaction between one or more `Agent`'s
AgentChat|ChatHistoryAgentRelay ChatHistoryAgentHub|Class which represents a `ChatHistory` based interaction between one or more `Agent`'s

**Comment by matthewbolanos** [comment]
Class / Interface Name | V1 Name                        | Description
-----------------------|--------------------------------|------------
Agent                  | Agent                  (no-op) | Root agent abstraction
ILocalAgent            | IChatHistoryHandler            | Interface which is implemented by `Agent`'s which can interact using a `ChatHistory`
KernelAgent            | KernelAgent            (no-op) | Includes `Kernel` services and plug-ins
LocalKernelAgent       | ChatHistoryKernelAgent         | Class which represents a `KernelAgent` which can interact using a `ChatHistory`
NexusAgent             | AggregatorAgent                | Allows a group of agents to express themselves as a single agent via a coordinator (i.e., an AgentNexus).
ChatCompletionAgent    | ChatCompletionAgent    (no-op) | A functional agent based on `IChatCompletionService`
OpenAIAssistantAgent   | OpenAIAssistantAgent   (no-op) | A functional agent based on *OpenAI Assistant API*
AgentChannel           | AgentChannel           (no-op) | Allows an agent to participate in a nexus.
LocalChannel           | ChatHistoryChannel             | Concrete channel for agents based on local chat-history.
OpenAIAssistantChannel | OpenAIAssistantChannel (no-op) | Channel associated with `OpenAIAssistantAgent`
AgentNexus             | AgentChat                      | Provides core capabilities for agent and user interactions.
AgentChat              | AgentGroupChat                 | Class which represents an interaction between one or more `Agent`'s; can include a custom "strategy" for handling a conversation between agents.
