### ISSUE TITLE
Python: Existing functions not working

### ISSUE THREAD

**Issue by shwetalodha** [microsoft/semantic-kernel#5786]
**Describe the bug**
Both the functions kernel.import_plugin(...) and kernel.import_plugin_from_object(...) are not working. I'm getting an error in Python code "'Kernel' object has no attribute 'import_plugin'"

**To Reproduce**
Code written in this notebook is not working: https://github.com/microsoft/semantic-kernel/blob/main/python/notebooks/08-native-function-inline.ipynb

**Comment by moonbox3** [comment]
Hi @shwetalodha. What version of SK Python are you using? I just ran through the whole notebook (08) without problems. Can you please make sure you don't have any conflict between pip packages if you're installing SK that way? I recommend following the [poetry approach](https://github.com/microsoft/semantic-kernel/blob/main/python/DEV_SETUP.md#using-poetry), if possible.

**Comment by shwetalodha** [comment]
Hi @moonbox3, thanks for responding. I'm using 0.9.5b1 of SK Python.

**Comment by moonbox3** [comment]
@shwetalodha please check your envionrment/package installation. I am not able to repro. I am using the same version.

**Comment by shwetalodha** [comment]
Looks like some mismatch was there in versions. Now, it is working alright. Thanks @moonbox3

**Comment by checkshi** [comment]
I am on version 1.27.0 and 'import_plugin_from_object' doesn't work anymore. I wonder if it is replaced with something else or my code has a problem. I am trying to Imports the skill into the kernel and registers the function as a plugin.

**Comment by moonbox3** [comment]
@checkshi that method hasn’t existed for about a year. Please check our latest code samples or docs:

https://learn.microsoft.com/en-us/semantic-kernel/get-started/quick-start-guide?pivots=programming-language-python
