### ISSUE TITLE
.Net: Gemini function calling throws error when a kernel function with `Enum` parameter is available

### ISSUE THREAD

**Issue by HillPhelmuth** [microsoft/semantic-kernel#5796]
**Describe the bug**
When using function calling with Gemini `ToolCallBehavior` set to `GeminiToolCallBehavior.AutoInvokeKernelFunctions`, and the Kernel instance has a plugin function with an `Enum` parameter, the Gemini request will return a 400 (bad request) error.

**To Reproduce**
1. Create `Kernel` instance with a plugin containing a function with enum parameter (`TimePlugin` is simple example to test).
2. Create `GeminiPromptExecutionSettings` with `ToolCallBehavior = GeminiToolCallBehavior.AutoInvokeKernelFunctions`
3. See error when running `InvokePromptAsync` that includes the execution settings.

**Expected behavior**
Similar to current OpenAI function calling, the Gemini connector should handle necessary type changes when converting kernel functions to gemini function definitions to avoid these errors

**Platform**
 - OS: Windows
 - IDE: Visual Studio 2022
 - Language: C#
 - Source: Version 1.7.1 and 1.7.1-alpha

**Additional context**
[Created example that demonstrates the issue](https://github.com/HillPhelmuth/GeminiFunctionCallErrorExample/blob/main/GeminiFunctionCallErrorExample/Program.cs) - uses `TimePlugin` which causes error and `TimePlugin` with `DateMatchingLastDayName` function removed, which does not cause the error.

**Comment by cisionmarkwalls** [comment]
I get errors even when no enum parameters are used with AutoInvokeKernelFunctions.

As an example:
```
...
kernel.ImportPluginFromFunctions("HelperFunctions",
[
    kernel.CreateFunctionFromMethod(() => DateTime.UtcNow.ToString("R"), "GetCurrentUtcTime", "Retrieves the current time in UTC."),            
]);
GeminiPromptExecutionSettings settings = new() {
    ToolCallBehavior = GeminiToolCallBehavior.AutoInvokeKernelFunctions
};
try
{
    FunctionResult result = await kernel.InvokePromptAsync(
       "What is the current time?", new(settings));

    // Display results
    var geminiMetadata = result.Metadata as GeminiMetadata;
...
```
Gives me a 500 error from Gemini for gemini-1.0-pro-002 and gemini-1.5-pro-preview-0409

**Comment by cisionmarkwalls** [comment]
> You should check at first in google docs do selected versions of models support function calling.

Yes, both of those models have function calling. If I change GeminiToolCallBehavior.AutoInvokeKernelFunctions to GeminiToolCallBehavior.EnableKernelFunctions it does the function calling correctly.

**Comment by Krzysztof318** [comment]
I am checking google ai documentation [link](https://ai.google.dev/gemini-api/docs/models/gemini) and I don't see models you tried to use.
You can use gemini-1.0-pro-001 and via alias gemini-1.0-pro or gemini-1.5-pro-latest.
