### ISSUE TITLE
.Net: Add Function arguments to activity

### ISSUE THREAD

**Issue by glennc** [microsoft/semantic-kernel#5814]
Just after an activity is created during KernelFunction invocation here https://github.com/microsoft/semantic-kernel/blob/b00a705a9a4132e54fa4d21e7cb28612611e9892/dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs#L299 I would like to add a tag containing the arguments, something  like this:

```csharp
activity?.AddTag("Arguments", JsonSerializer.Serialize(arguments));
```

That way when using OTel I can see at a glance what is happening when a tool is invoked multiple times with strange arguments and I need to give more context. For example this trace is invoking the same function several times with different arguments all resulting in a call to an API that returns an error before it figures out what to do:

<img width="1812" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/234688/94e496f7-9cee-49c9-b717-313b00edeebf">

can become something like this:

<img width="1816" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/234688/77492bfe-5d6e-4a6f-bc9c-424b6129a02d">

and I can see both what is going on with the invocation and what type of bug/missing context I might have without having to dig further into logs or change verbosity in order to get the logger to give me the same information.

Happy to send the PR but wanted to ask if there was a reason not to do it before I did that.

**Comment by noahfalk** [comment]
> @noahfalk, @tarekgh, @CodeBlanch, what do we recommend folks do when they want to include additional user-provided information as tags but that information could possibly be sensitive?

I'm not convinced we have the right patterns nailed yet, but I think the broad strokes look something like:
1. Determine which data is potentially sensitive
2. Design APIs/config settings that let app developers decide what portions of that data are appropriate to expose in their scenario.
3. Data that doesn't flow either gets omitted entirely, or replaced with some sentinel value indicating it was redacted.

These examples aren't explicitly about tags, but they are in the general area of refining what data gets emitted in telemetry:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.httplogging.httploggingoptions.requestheaders?view=aspnetcore-8.0
https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.redactloggedheaders?view=dotnet-plat-ext-8.0
https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Telemetry.Abstractions/Http/HttpRouteParameterRedactionMode.cs#L9
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-8.0#developer-exception-page

> Or is the general stance that choosing to export this data is signing up for it?

I think different users have different expectations and judgements vary depending on how sensitive the data is likely to be. I think it is perfectly reasonable for cases with a mixture of sensitive and non-sensitive data to only enable the non-sensitive portions initially and force some additional explicit opt-in to include the sensitive portions.

In this case it looks like the authors of this convention thought the same thing:
https://github.com/open-telemetry/semantic-conventions/pull/825/files#diff-72369cbec5da92c01143061b1f74d700eba3fc8f559f47fc70331dbf1bf702feR29-R35

**Comment by matthewbolanos** [comment]
@TaoChenOSU, assigning this to you since you'll be looking at the new telemetry patterns. I'm curious how (if at all) this is supported with the proposed AI telemetry.

**Comment by CodeBlanch** [comment]
What we have done on the OTel side (typically) is offer an options class in our instrumentation packages where users can opt-into capturing things which may contain sensitive data. For example, for `SqlCommand.CommandText` we have: https://github.com/open-telemetry/opentelemetry-dotnet/blob/9261a679e6325346aa1d0abcd19ed6b277286e13/src/OpenTelemetry.Instrumentation.SqlClient/SqlClientTraceInstrumentationOptions.cs#L95

We also typically expose an "Enrich" delegate on these options classes where users can add (or remove) things as needed: https://github.com/open-telemetry/opentelemetry-dotnet/blob/9261a679e6325346aa1d0abcd19ed6b277286e13/src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreTraceInstrumentationOptions.cs#L62

**Comment by danmoseley** [comment]
The opt-in part seems key here.

**Comment by glennc** [comment]
As Dan said it sounds like the first task is an SK specific pattern for how we would turn on/off individual potentially PII (like the telemetryoptions type linked to) and we should establish that, then we can do features like this and it is unlikely to need significant rework as OTel stuff advances more generically. Unless an options type class already exists? Does that sound right?

For the point about logging prompts, do we need to need to support something like https://microsoft.github.io/presidio/ to optionally do our best to sanitize the prompt.

**Comment by luisquintanilla** [comment]
> As Dan said it sounds like the first task is an SK specific pattern for how we would turn on/off individual potentially PII (like the telemetryoptions type linked to) and we should establish that, then we can do features like this and it is unlikely to need significant rework as OTel stuff advances more generically. Unless an options type class already exists? Does that sound right?
> 
> For the point about logging prompts, do we need to need to support something like https://microsoft.github.io/presidio/ to optionally do our best to sanitize the prompt.

Following up on Glenn's Presidio comment. 

Here's an example of how it fits into the flow

https://www.llamaindex.ai/blog/pii-detector-hacking-privacy-in-rag
