### ISSUE TITLE
.Net: Auto Function Calling Planner Replacing hyphen (–) with newline character (\n) in ToolCall Arguments.

### ISSUE THREAD

**Issue by bmtreuherz** [microsoft/semantic-kernel#5823]
**Describe the bug**
We are using Open API plugins with automatic function calling. We have noticed a strange behavior where the planner cannot generate tool call arguments that contain an "en dash" (–) (U+2013). This character is always replaced in the tool call arguments with a newline character.

**To Reproduce**
1. Import a plugin to the kernel which accepts a parameter (e.g. ProductName).
2. Invoke chat completions automatic function calling with a user message that contains a value for that parameter that contains an "en dash" (–). (e.g. "Show me my total earnings for the product 'Core – Modern'")
3. Observe the tool call arguments. From our observations, the parameter will always be set to 'Core \n Modern'.

NOTE: This behavior was observed whileusing Open API style plugins and invoking the plugins via the ChatCompletions service (with automatic functional calling enabled). 
![image](https://github.com/microsoft/semantic-kernel/assets/8550902/a6c6bad6-6779-418c-95b8-6cf791fdcadd)
![image](https://github.com/microsoft/semantic-kernel/assets/8550902/d2adc04c-b695-40de-8190-1d17e9d01066)

**Expected behavior**
I would expect that the argument would reflect the value provided by the user. (e.g. in the example above we should see productName = "Core – Modern". 

**Screenshots**
User Query:
![image](https://github.com/microsoft/semantic-kernel/assets/8550902/4a598ccc-8402-4c15-a9c9-dafd1266ab46)

ToolCall Arugments:
![image](https://github.com/microsoft/semantic-kernel/assets/8550902/f42c4175-c161-4f0d-a657-f7976d59fb76)

Final Response"
![image](https://github.com/microsoft/semantic-kernel/assets/8550902/0a8ee666-06e1-4749-9884-0cc87236b519)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: I have tested with both NuGet package version 1.3.1 and 1.7.1. and observed the same results. 

**Additional context**
This behavior does not appear to be present with other "dash" variants, however, the "en dash" is always replaced with a newline. The model is able to return this character correctly in message content, but never in a ToolCall argument. We are using GPT4 and have observed this behavior across several GPT 4 versions (1106 and 0613).

**Comment by markwallace-microsoft** [comment]
@bmtreuherz My initial thinking is that this is a GPT 4 issue. Can you try invoking the OpenAI REST API directly to see can you reproduce the issue in this way? If the answer is yes you could try using prompt engineering to correct the problem.

**Comment by markwallace-microsoft** [comment]
We are working on filters which can be triggered when the LLM triggers a function call. We will investigate using the filters to correct badly formed tool call requests so that developers can work around this issue until OpenAI fix it.

**Comment by markwallace-microsoft** [comment]
Here is the item to track https://github.com/microsoft/semantic-kernel/issues/5957

**Comment by bmtreuherz** [comment]
@markwallace-microsoft  I have confirmed that this is in fact a bug with the model itself as this is reproducible when going directly to the AOAI APIs. 
![image](https://github.com/microsoft/semantic-kernel/assets/8550902/c50662aa-462d-4067-8055-032ad3c24d9b)


It appears that there is a known issue with the 1106 model version where certain characters (primarily but not exclusively from non-English alphabets) have the wrong UTF-8 encoding in function call parameters.   I found others experiencing this issue on the openai forums:
- https://community.openai.com/t/gpt-4-1106-preview-messes-up-non-ascii-characters-in-functions-calls/478468
- https://community.openai.com/t/gpt-4-1106-preview-is-not-generating-utf-8/482839
- https://community.openai.com/t/support-of-unicode-in-gpt4-1106-preview/482695
- https://community.openai.com/t/gpt-4-1106-preview-messes-up-function-call-parameters-encoding/478500

Open AI has acknowledged this and indicated that the 0125 model versions of GPT 4 and 35 turbo have fixed this. 
![image](https://github.com/microsoft/semantic-kernel/assets/8550902/b9f6c9ba-205a-4806-9e19-a6a9e1504b25)
![image](https://github.com/microsoft/semantic-kernel/assets/8550902/80c2198f-64b8-4a40-91ad-6f29d3611a11)

I have attempted to repro this issue with the GPT-4-0125 model version and it does indeed appear to be resolved:
![image](https://github.com/microsoft/semantic-kernel/assets/8550902/0d5a113f-1fca-421a-91bf-2651732d98e7)
