### ISSUE TITLE
.Net: Function names are triggering errors on Azure OpenAI

### ISSUE THREAD

**Issue by brandonh-msft** [microsoft/semantic-kernel#5825]
**Describe the bug**
When I am using Plugins & Function Calling w/in my setup, I am getting occasional errors from Azure OpenAI:

```
'functions.TBAAgent-GetEventsByDateRange' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.4.tool_calls.0.function.name' Status: 400 (model_error)  Content: {
  "error": {
    "message": "'functions.TBAAgent-GetEventsByDateRange' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.4.tool_calls.0.function.name'",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**To Reproduce**
1. Add a Plugin from a Class that defines multiple `[KernelFunction]`-decorated methods.
2. Run a Chat session that executes one/more of the functions in the defined plugin against an Azure OpenAI model - I am using gpt-4-32k v01613

**Expected behavior**
Functions should execute as required by the LLM based on the prompt

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#,
 - Source: Nuget v1.7.1

**Comment by dviry** [comment]
Just to add - I am having the same issue (also using latest 1.7.1), but with a more common function (happens randomly):
```
Microsoft.SemanticKernel.HttpOperationException: 'functions.Memory-Ask' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.7.tool_calls.0.function.name'
```

**Comment by dviry** [comment]
FYI - seems related to #4447 - specifically with the [GPT-4 Model](https://github.com/microsoft/semantic-kernel/issues/4447#issuecomment-1912052299)

**Comment by markwallace-microsoft** [comment]
We are working on filters which can be triggered when the LLM triggers a function call. We will investigate using the filters to correct badly formed tool call requests so that developers can work around this issue until OpenAI fix it.

**Comment by markwallace-microsoft** [comment]
Here is the item to track https://github.com/microsoft/semantic-kernel/issues/5957
