### ISSUE TITLE
.Net: ToolCallBehavior AutoInvokeKernelFunctions not present while using kernel.InvokeAsync

### ISSUE THREAD

**Issue by animeshj9** [microsoft/semantic-kernel#5841]
**Describe the bug**

**To Reproduce**
1. Create Kernel and add a plugin (e.g. Math Plugin)
2. Create a complex prompt plugin that would need Math Plugin to be invoked 
3. kernel.InvokeAsync(kernelFunction ....)
4. Method does not take in a ToolCallBehavior or PromptExecutionSettings as a parameter.

**Expected behavior**
When I add a plugin (e.g. MathPlugin) to the kernel and then run a prompt that needs to use the plugin, AutoInvokeKernelFunctions  should be present as a parameter so that the MathPlugin can be invoked via GPT4s function calling.

**Platform**
 - Language: C#
 - Source: NuGet, version 1.6.3

**Additional context**
I wasn't sure if its a bug or a feature request. But the ability to use GPT4s auto function calling while running prompt based plugins would be greatly helpful.

**Comment by stephentoub** [comment]
InvokeAsync accepts a KernelArguments. That's how you pass arguments into the invocation, including a PromptExecutionSettings, e.g. `new KernelArguments(executionSettings)`.

**Comment by animeshj9** [comment]
Thanks @stephentoub . Will try out today and update here.

**Comment by animeshj9** [comment]
Works. Thanks!
