### ISSUE TITLE
Java: How to `buildInnerNonAzureOpenAIClient()` with custom `OPEN_AI_ENDPOINT`

### ISSUE THREAD

**Issue by bx-h** [microsoft/semantic-kernel#5849]
Hi, All.

I am a Java user. I want to build a NON azure client with custom endpoint. For example, In python: 
```python
from openai import OpenAI
client = OpenAI(
    api_key = "xxx",
    base_url = "xxx"
)
```
But In the Java source code, I can't find a configuration for OPEN_AI_ENDPOINT.

<img width="924" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/22412942/c3c0b5d9-ac1f-4d3b-bf3f-7378afed6132">
<img width="896" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/22412942/8b517074-2cdc-4dfb-b3e5-4fb0752e8a2a">
<img width="697" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/22412942/57614ba3-a528-4417-b8c4-5785004b3237">

How to fix it?

**Comment by bx-h** [comment]
I don't think it's a good idea to hard-code the `OPEN_AI_ENDPOINT` and set it as `final`.

**Comment by xixiha5230** [comment]
i have the same problem
