### ISSUE TITLE
.Net: StepwiserPlanner: Final Answer is empty

### ISSUE THREAD

**Issue by elagunas** [microsoft/semantic-kernel#5869]
**Describe the bug**
I have an application that use StepwisePlanner. 
The plan is generated correctly but the final answer is empty, becasuse never require me the mandatory parameters or sometimes openai asumme the values of thes parameters.

**To Reproduce**
Have a function like this:
```
 [KernelFunction]

 [Description("Gets the information to install an extractor bell in a location")]
 [return: Description("Installation information for an an extractor bell in a location")]
 public async Task<string> GetInformationToInstall(
     [Description(@"Location of installation. Required.")] string location,
     [Description(@"Type of extractor bell. Required.")] string extractorType)
 {
     var result = await Task.FromResult($"Installation information is location: {location} - extractorType: {extractorType}");
     return result;
 }
```

**Expected behavior**
Final answer must to be contain a message with required parameters

**Screenshots**
The plan is generated OK
![image](https://github.com/microsoft/semantic-kernel/assets/36204781/0aa95612-dda8-40cc-96a6-7f06d3b95b91)
The plan loop until max iterarions, and never answer with the final answer
![image](https://github.com/microsoft/semantic-kernel/assets/36204781/658ebc7e-9a2c-431c-af40-fc779a6fec89)
Finally FinalAnswer is empty
![image](https://github.com/microsoft/semantic-kernel/assets/36204781/7f004afb-aad6-4910-8120-cd7e9ad097bd)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: 
  ```
  <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.7.1" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.7.1" />
    <PackageReference Include="Microsoft.SemanticKernel.Planners.Handlebars" Version="1.7.1-preview" />
    <PackageReference Include="Microsoft.SemanticKernel.Planners.OpenAI" Version="1.7.1-preview" />
```
 - Open AI: GTP-4 Sweden Central 
 
**Additional context**

**Comment by matthewbolanos** [comment]
If you need the LLM to respond back to you to ask questions to get additional details (e.g., required input parameters), we would recommend that you not use the stepwise planner. Instead, we recommend that you use automatic function calling within Semantic Kernel.

Let us know if that addresses your need, and if not, please reopen the issue.

**Comment by elagunas** [comment]
Thanks @matthewbolanos, it works as expected.
