### ISSUE TITLE
Python: Incorrect package version

### ISSUE THREAD

**Issue by shwetalodha** [microsoft/semantic-kernel#5876]
**Describe the bug**
[This ](https://github.com/microsoft/semantic-kernel/blob/main/python/notebooks/11-streaming-completions.ipynb) NB is using version semantic-kernel==0.9.6b1, which doesn't exist. Could you please validate, if this version is correct in given notebook?

**Comment by matthewbolanos** [comment]
The package is now live.

**Comment by shwetalodha** [comment]
Thanks for fixing this
