### ISSUE TITLE
Python: Failed to specify embedding dimensions

### ISSUE THREAD

**Issue by sinyubonnie-ho** [microsoft/semantic-kernel#5882]
**Describe the bug**

I would like to use the embedding model text-embedding-3-small and text-embedding-3-large, and specify the dimensions. I tried to specify the param dimensions in AzureTextEmbedding and got a type error:

AzureTextEmbedding(
TypeError: __init__() got an unexpected keyword argument 'dimensions')

Please instruct how to specify the embedding dimensions in semantic kernel - python. Many thanks!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by eavanvalkenburg** [comment]
hi @sinyubonnie-ho we indeed have not yet added support for that, if you are up for it you could create a PR to fix it, should be a matter of adding the field with None as default here: https://github.com/microsoft/semantic-kernel/blob/e416946567c39f7c8b867d517a218f226f978d39/python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/open_ai_prompt_execution_settings.py#L76
