### ISSUE TITLE
AddGoogleAIGeminiChatCompletion Api return as empty

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/semantic-kernel#5918]
**Describe the bug**
To utilize the AddGoogleAIGeminiChatCompletion API for integrating with the Google Gemini it consistently returns empty responses.

**To Reproduce**
Use AddGoogleAIGeminiChatCompletion API

**Expected behavior**
Return values should not be empty or null.

**Platform**
 - OS: Windows 
 - IDE: Visual Studio
 - Language: C#
 - Source: Microsoft.SemanticKernel.Connectors.Google - 1.7.1-alpha version

**Comment by Krzysztof318** [comment]
Could you show us your code? Have you checked the finish reason in metadata?

**Comment by rvinothrajendran** [comment]
Config issue & has been fixed.
