### ISSUE TITLE
.Net: Replace HttpClient with IHttpClientFactory in OpenAIFunctionExecutionParameters

### ISSUE THREAD

**Issue by JohanYman** [microsoft/semantic-kernel#5927]
While working with the OpenAIFunctionExecutionParameters class within the Microsoft.SemanticKernel.Plugins.OpenApi namespace, I've observed that it currently accepts a HttpClient instance directly within the constructor.
Current Implementation:
csharp

```
public OpenAIFunctionExecutionParameters(HttpClient? httpClient = null, ...)
{
    ...
}
```
**Problem**: Directly using HttpClient can lead to socket exhaustion and lacks the benefits of centralized configuration and management provided by IHttpClientFactory.
Proposed Enhancement: I propose refactoring the class to accept an IHttpClientFactory for creating HttpClient instances.

**Detailed Proposal**:
Change the constructor parameter from HttpClient? to IHttpClientFactory?:
csharp

```
public OpenAIFunctionExecutionParameters(IHttpClientFactory? httpClientFactory = null, ...)
{
    ...
}
```
Use the factory to create HttpClient instances within the using blocks where HTTP calls are made.

**Benefits**:
- Avoids potential socket exhaustion issues.
- Enables the use of named and typed HTTP client configurations.
- Aligns with Microsoft's recommended practices.

**Impact**: This change would necessitate updating areas of the codebase that instantiate or use OpenAIFunctionExecutionParameters to now work with IHttpClientFactory.

I believe this enhancement will improve the scalability and robustness of HTTP client usage within our code. I look forward to the team's feedback and am ready to collaborate on this improvement.

**Comment by dmytrostruk** [comment]
@JohanYman Please check this issue and comments: https://github.com/microsoft/semantic-kernel/issues/4400
