### ISSUE TITLE
.Net: DescriptionAttribute in complex object not working as expected

### ISSUE THREAD

**Issue by elagunas** [microsoft/semantic-kernel#5930]
**Describe the bug**
I have a model with nested properties and child classes which include DescriptionAttribute but most of time, this information is ignored.

This model is the input parameter of a native function kernel, that is invoked automatically from IChatCompletionService.

When a property is an Enum type, I think that description attribute is ignored. I need give a description to avoid naming enum values which complex naming,

When a property is a Child class, properties of this class with description, I think are ignored.

When I have a property that is a boolean like HasConduit I Have two cases:

Case 1: **HasConduit** is false, **ConductType** is required
Case2: **HasConducti** is true, **Conduct** properties I want are required in based **ConductType** value.

I try to indicate that **ConductType** is always required, but don't works for me.

Some description in top of **ExtractorBell** working randomly. Other never works.

Only when I naming a property with his unit, works as expected like **ConductLongInMeter** 

**To Reproduce**
```

 [Description(@"
         Diameter only applied when ConductType of Conduct is Circular; 
         Width and Height only applied when ConductType of Conduct is Rectangular.")]
 public class ExtractorBell
 {
     [Required]
     [Description("Type of installation of extractor bell.")]
     public InstallationType InstallationType { get; set; }

     public bool HasConduit { get; set; }

     public Conduct Conduit { get; set; }
 }

 [JsonConverter(typeof(JsonStringEnumConverter))]
 public enum InstallationType
 {
     Kitchen,
     Barbacue
 }

 public class Conduct
 {
     public ConductType ConductType { get; set; }
     public double ConductLongInMeter { get; set; }
     [Description("Number of elbows (0-10)")]
     public int ElBowNumber { get; set; }
     [Description("Diameter")]
     public double? Diameter { get; set; }
     [Description("Height.")]
     public double? Height { get; set; }
     [Description("Width")]
     public double? Width { get; set; }
 }
```

**Expected behavior**
If I have a complex object like this, How I define my rules correctly?

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#,
 - Source: 
        ` <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.7.1" />
          <PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.7.1" />`

- Open AI: GTP-4 Sweden Central

Additional context
I see this issue https://github.com/microsoft/semantic-kernel/issues/5757
But, when I try to alter the range, works randomly or ignore the range value.

**Comment by markwallace-microsoft** [comment]
@elagunas  It's possible the LLM is getting confused because you are using "Conduct" and "Conduit". You should also try adding descriptions to all properties as the more information the LLM has then it can make better decisions.

I put together the sample below and when I run it my function is called with the correct values and I get this response. 

You can also take a look at our sample here: [Step2_Add_Plugins.cs](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Getting_Started/Step2_Add_Plugins.cs)

```json
{
  "Type": "Circular",
  "Length": 3.5
}
```


```csharp
// Copyright (c) Microsoft. All rights reserved.

using System.ComponentModel;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Examples;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.OpenAI;
using Xunit;
using Xunit.Abstractions;

namespace GettingStarted;

/// <summary>
/// This example shows how to load a <see cref="KernelPlugin"/> instances.
/// </summary>
public sealed class PluginSample(ITestOutputHelper output) : BaseTest(output)
{
    /// <summary>
    /// Shows different ways to load a <see cref="KernelPlugin"/> instances.
    /// </summary>
    [Fact]
    public async Task RunAsync()
    {
        // Create a kernel with OpenAI chat completion
        IKernelBuilder kernelBuilder = Kernel.CreateBuilder();
        kernelBuilder.AddOpenAIChatCompletion(
                modelId: TestConfiguration.OpenAI.ChatModelId,
                apiKey: TestConfiguration.OpenAI.ApiKey);
        kernelBuilder.Plugins.AddFromType<ConduitFactory>();
        Kernel kernel = kernelBuilder.Build();

        OpenAIPromptExecutionSettings settings = new() { ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions, ResponseFormat = "json_object" };
        WriteLine(await kernel.InvokePromptAsync("Create three and a half metres of round profile conduit. Return the conduit details in JSON format.", new(settings)));
    }

    /// <summary>
    /// A plugin that creates conduit.
    /// </summary>
    public class ConduitFactory
    {
        [KernelFunction]
        [Description("Creates conduit with the specified type and length")]
        public Conduit CreateWidget([Description("The type of conduit to be created")] ConduitType conduitType, [Description("The length of conduit to be created")] double length)
        {
            return new()
            {
                Type = conduitType,
                Length = length
            };
        }
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ConduitType
    {
        [Description("A conduit that has a circular profile.")]
        Circular,

        [Description("A conduit that has a rectangular profile.")]
        Rectangular
    }

    public class Conduit
    {
        [Description("The conduit type. This will be either Rectangular or Circular.")]
        public ConduitType Type { get; init; }
        [Description("The length of the conduit measured in meters.")]
        public double Length { get; init; }
    }
}
```

**Comment by elagunas** [comment]
Hello Mark,

The example I put is not correct, I was changing from conduct to conduit, but always I use the same word.

I've attached another example about the description of enum type

![image](https://github.com/microsoft/semantic-kernel/assets/36204781/2624f4a3-5766-40db-a454-9982cda40445)

![image](https://github.com/microsoft/semantic-kernel/assets/36204781/3360965d-c757-4f63-8eb7-a33bfb065efb)

LLM ignore description type, only when I've declared my enum with a name more descriptive like these I get a better description in the response

 public enum ExtractorLocation
 {
     [Description("Attached to one wall")]
     AttachedToOneWall,
     [Description("Attached to two walls")]
     AttachedToTwoWalls,
     [Description("Attached to three walls")]
     AttachedToThreeWalls,
     Island
 }

**Comment by elagunas** [comment]
I add aditional information about other things that I commented in the initial post

Like in Enum types only when I naming a property with more descriptive, LLM give the information better, but it's strange that i have to naming a variable with additional informatión like meters o centimeters not?

![image](https://github.com/microsoft/semantic-kernel/assets/36204781/980e67f4-060f-4505-9c35-f8352b05e3cd)

![image](https://github.com/microsoft/semantic-kernel/assets/36204781/98b3580b-0374-46c5-8397-7ae58dd86d29)

And the other and If I have a condition to set a value it is ignored. How I say to LLM about this condition ?

![image](https://github.com/microsoft/semantic-kernel/assets/36204781/59bcc9b8-467a-4ec1-88eb-dba7e1471ab6)

![image](https://github.com/microsoft/semantic-kernel/assets/36204781/cc360ba4-7f51-4269-ba3f-924426a214e0)

Thanks a lot Mark!

**Comment by markwallace-microsoft** [comment]
Closing as stale
