### ISSUE TITLE
.Net: HandlebarPlanner - Does not check Finish Reason before trying to parse output, throwing spurious errors instead of readable Token Limit Reached.

### ISSUE THREAD

**Issue by NickDrouin** [microsoft/semantic-kernel#5934]
I'm new to using Semantic Kernal and Planners.  All of the samples are authored with: 
 
```csharp
var planner = new HandlebarsPlanner();
```

However, these samples all throw when trying to run them.

The exception bubbles up a truncated plan thrown by error from within `dotnet\src\Planners\Planners.Handlebars\Handlebars\HandlebarsPlanner.cs` here:

```csharp
throw new KernelException($"[{HandlebarsPlannerErrorCodes.InvalidTemplate}] Could not find the plan in the results. Additional helpers or input may be required.\n\nPlanner output:\n{modelResults.Content}");
```

However, the plan is not missing, as much as incomplete due to lack of tokens.

It took me most of a day to install the repo and step through to find that hidden within `modelResults.Metadata["FinishReason"]`  we could get a hint that there needs to be tokens explicitly allotted.

ASK 1:

The samples should all be changed to demonstrate the need for tokens: 

```csharp
var planner = new HandlebarsPlanner(new HandlebarsPlannerOptions()
{
    ExecutionSettings = new OpenAIPromptExecutionSettings
    {
        MaxTokens = 3000
    },
});
```

ASK 2: 

The core lib code should be improved to deal with `GetChatMessageContentAsync` results for all types of `FinishReason`.

I was able to quickly validate by adding in a specific throw for `FinishReason==length`.  

```csharp
            // Get the chat completion results
            var chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();
            modelResults = await chatCompletionService.GetChatMessageContentAsync(chatMessages, executionSettings: this._options.ExecutionSettings, cancellationToken: cancellationToken).ConfigureAwait(false);

            if (modelResults.Metadata != null && modelResults.Metadata.TryGetValue("FinishReason", out var finishReason))
            {
                if (string.Equals(finishReason as string, "length", StringComparison.OrdinalIgnoreCase))
                {
                    throw new KernelException($"[{HandlebarsPlannerErrorCodes.FinishedWithTokenLimitReached}] Check tokens and throughput.\n\nFinish Reason: {finishReason}\n\nPlanner output:\n{modelResults.Content}");
                }
            }
```

Type checking could be added with [CompletionsFinishReason](https://learn.microsoft.com/en-us/dotnet/api/azure.ai.openai.completionsfinishreason?view=azure-dotnet-preview), which is not currently linked.  It also looks like there is a Verify pattern used within the code, which is probably more readable, and could be used across the Planners and more generally.

The following all seemed related to users hitting up against spurious token-limits, or finish reasons, and then not bubbling the core causes across the code base:

https://github.com/microsoft/semantic-kernel/issues/4621
https://github.com/microsoft/semantic-kernel/issues/4834
https://github.com/microsoft/semantic-kernel/issues/5240

There is probably a design pattern that needs implementing for these various areas of the code.

**Comment by matthewbolanos** [comment]
Closing since work on the Handlebars planner is paused as we start investing in a python planner
