### ISSUE TITLE
.Net: Cannot resolve symbol 'CreateFunctionFromPromptYAML'

### ISSUE THREAD

**Issue by vicperdana** [microsoft/semantic-kernel#5939]
https://github.com/microsoft/semantic-kernel/blob/917b790b663d72b03aa607c134e5c23ad0e83433/dotnet/samples/DocumentationExamples/SerializingPrompts.cs#L49

Hi team, this doesn't seem to resolve in `1.7.1.` is this a known issue?

Tagging @matthewbolanos

**Comment by vicperdana** [comment]
Missed the [package](https://www.nuget.org/packages/Microsoft.SemanticKernel.Yaml). Is this going to remain as a separate package or is there a plan to include this into the main package?

**Comment by markwallace-microsoft** [comment]
We are going to keep this as a seperate package because it depends on YamlDotNet. Our goal is to have minimal dependencies in the main Semantic Kernel packages.
