### ISSUE TITLE
How to use a kernel memory plugin with other plugins

### ISSUE THREAD

**Issue by rborosak** [microsoft/semantic-kernel#5943]
Hi, 
I was able to implement a memory kernel plugin.  The idea is to have a chatbot that answers only to questions from internal documents. If the user ask something that is not related to our documents the bot replies "I don't know".

I have registered the memory plugin and my prompt looks something like this. My project is based on this blog entry [https://www.developerscantina.com/p/semantic-kernel-memory/](url)

```
var prompt = $@"
Question to Kernel Memory: {question}

Kernel Memory Answer: {{memory.ask}}

If the answer is empty say 'I don't know', otherwise reply with the answer.
";
```

This works as expected.

Now I would like to add a new plugin so the users can book an appointment. 
I have registered this new plugin but when the user asks something like "How can I make an appointment" or "I would like to make an appointment" the answer is "I don't know" because it was not found in memory. 

How should I change my prompt so that the bot can answer ONLY questions based on our internal documents and still use another plugin (and check if all the input arguments are provided by the user like time, date, place for the appointment)?

Can this be done in a single project or do I need to have two chatbot?

Thank you.

**Comment by dmytrostruk** [comment]
@rborosak In your example, you are triggering `memory` plugin and `ask` function manually. If you want one chatbot that will be able to either find an information within internal documents or book an appointment, you should consider using automatic function calling. Please check following example:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example59_OpenAIFunctionCalling.cs

In this case, you register `memory` plugin and `booking` plugin in Kernel. Then, you pass user request to LLM so it can decide, whether to call memory plugin to find some information or call `booking` plugin to book an appointment. If you see that LLM doesn't want to call specific plugin, you can control that behaviour by using `Description` attribute on plugin functions to describe in more detail the purpose of specific function. You can also use `OpenAIPromptExecutionSettings.ChatSystemPrompt` to provide more instructions to LLM when to call specific plugin/function.

Let me know if this information is helpful. Thanks!

**Comment by rborosak** [comment]
Thank you for the reply.
I have changed my prompt to something like this


```
var prompt = $@"You help users with queries about [mytopic]
DO NOT answer queries related to other topics.
In addition to answering queries, you also help users with reservation.

Don't make assumptions about what values to plug into functions.
Tools Available:

Memory Plugin: ALWAYS use this tool when answering queries related to [myTopic]
Booking Plugin: Use this tool to help with and execute reservations. 
Always answer using English language.
Bonus: You'll get $20 if you get this right.
User query: {question}";
```


This is currently working but often times the bot ask for time, date and place for booking and if the user does not provide all three parameters at once, bot just makes up the values of missing parameters. 
When it does not make the values up it asks for the missing ones but then asks for the parameters provided by the user in the previous entry. 

How can I fix this? Should I add a few shots in my prompt? Should I make a description of the function more versatile?

```
settings = new()
{
    ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions,
    ModelId = "gpt-3.5-turbo"
};

var prompt = //see above

 _chatHistory.AddMessage(AuthorRole.User, prompt); //user message along with the instructions for chatbot ???

 var result = await _completionService.GetChatMessageContentAsync(_chatHistory, settings, _semanticKernel);
 
   _chatHistory.AddMessage(AuthorRole.Assistant, result.Content); 
```

Can you please explain what should one put in `OpenAIPromptExecutionSettings.ChatSystemPrompt` as opposed to a message in user prompt?
Is it wrong to put a instructions with user message every time the user interacts with a chat bot? Should that be in ChatSystemPrompt
Every question toward the bot uses 1k+ tokens.

Best regards

**Comment by dmytrostruk** [comment]
> This is currently working but often times the bot ask for time, date and place for booking and if the user does not provide all three parameters at once, bot just makes up the values of missing parameters. When it does not make the values up it asks for the missing ones but then asks for the parameters provided by the user in the previous entry.
> 
> How can I fix this? Should I add a few shots in my prompt? Should I make a description of the function more versatile?

@rborosak In this case, you should update your prompt and let LLM know that in case if some parameter is missing, it should ask user to provide it. Few-shots prompt should help as well. You should also update your `chatHistory` object with all responses so LLM will have context about previously provided parameters. Description of function will also help. Together with function description, you can also use `Description` attribute on each function parameter. The more information you will provide to LLM - the better will be the results. You can also try to change `OpenAIPromptExecutionSettings.Temperature` and see if model works better.

> Is it wrong to put a instructions with user message every time the user interacts with a chat bot? Should that be in ChatSystemPrompt
> Every question toward the bot uses 1k+ tokens.

I think you answered your question :) 
All the prompt that you currently store in `prompt` variable could go to instructions (i.e. `ChatSystemPrompt`) except `User query: {question}"` part. You can receive `question` from user and add it directly to `chatHistory` as user message. In this way, LLM should be able to handle user ask based on initial instructions you provided, and you don't have to insert these instructions in every message. Although, keep in mind that in longer conversations LLM can lose the context and forget about initial instructions. In this case, you can still add `system` message in the middle of conversation using `AuthorRole.System` as a role.

**Comment by rborosak** [comment]
@dmytrostruk Thank you. You are very helpful. 

>  Although, keep in mind that in longer conversations LLM can lose the context and forget about initial instructions.

Is there any way to know when this happens?

**Comment by dmytrostruk** [comment]
> > Although, keep in mind that in longer conversations LLM can lose the context and forget about initial instructions.
> 
> Is there any way to know when this happens?

@rborosak You can see that by response that LLM provided. For example, in your code, if you know that some plugin needs to be called, but for some reason it wasn't, and you see that conversation is already long, you can try to re-send the same request with system instructions to "refresh" LLM knowledge and see if that fixes an issue. 

But it also depends on the use-case. If your scenario can be achieved within short conversation, then I would suggest resetting `chatHistory` and maintain it for short conversations only. In this case, you shouldn't have any problems with initial instructions.
