### ISSUE TITLE
Function calling step events

### ISSUE THREAD

**Issue by kbeaugrand** [microsoft/semantic-kernel#5952]
When using the function calling planner, I'ld like to have events triggered once step are starting/ended, especially for tool_calls... This is really interesting to provide to user more information about how the Stepwise is running.

- By having the possibility to cancel tool call in case of any security risk for example (by interfacing a security checker function),
- Using model reasoning sentences to give feedback to user, 
- ... 

This could also enhance the UX while giving real time messages...

**Comment by markwallace-microsoft** [comment]
@kbeaugrand We have some new filters functionality which will be released this week which should help here. 

@dmytrostruk can you add a link to the Blog post when it's published.

**Comment by dmytrostruk** [comment]
@kbeaugrand Here are some links with information that should help to achieve your scenarios:
- [Filters in Semantic Kernel](https://devblogs.microsoft.com/semantic-kernel/filters-in-semantic-kernel/)
- [Code example for tool calls](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Concepts/Filtering/AutoFunctionInvocationFiltering.cs)

**Comment by matthewbolanos** [comment]
@kbeaugrand, I believe the new filter's capability will address your needs so I'm going to go ahead and close this issue. Please reopen this issue if that's not the case.

**Comment by kbeaugrand** [comment]
Thank you very much guys for the update, and also for this feature. I'll try that now and give a feedback on this great feature!
