### ISSUE TITLE
.Net Demo Using Time Plugin Auto Function Calling

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#5958]
## Requirements 

An AI must be able to perform searches with a time plugin and get back “results” of the correct time to the user.  

## Scenarios 

The user wants to ask about the time and get the correct response back from AI.  

## Proposal: 

For .NET utilize current function calling sample to reuse what’s already there for [date and time](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example59_OpenAIFunctionCalling.cs).

**Comment by stephentoub** [comment]
The current time plugin is problematic. It has a _ton_ of APIs on it, to the point where the current models appear to rarely choose the best one for the job. Having a built-in plugin for time is good, but before it's made stable I think we need to take a hard look at making it more minimalistic.

**Comment by RogerBarreto** [comment]
Dropping this in favor of getting a detailed description for the Getting Started Steps.
