### ISSUE TITLE
Python: vscode extension: allow to ignore folders

### ISSUE THREAD

**Issue by jmservera** [microsoft/semantic-kernel#5972]
When using the extension in a Python project that contains a virtual environment folder (.venv) the extension shows the functions defined inside the python libraries:
![image](https://github.com/microsoft/semantic-kernel/assets/8036360/a5c9f606-1483-40e4-a00c-51899c07bdd9)

It will be very handy to have a way of ignoring some folders, just like .gitignore works.
thx.

**Comment by markwallace-microsoft** [comment]
Closing as stale
