### ISSUE TITLE
.Net Google Connector - Version `Latest` as Default

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#5974]
@Krzysztof318 
Add `Default` as version option for the APIs to minimize coding maintenance during version updates from the provider. 

⚠️ Clearly call out in the XML doc for the parameter that it will always default to the latest, so that consumers know that they need to specify the version if they do not wish to be upgraded silently with a package version update.

**Comment by Krzysztof318** [comment]
I take care for that this week

**Comment by markwallace-microsoft** [comment]
Closing as already done
