### ISSUE TITLE
Python: Cannot use multiple `execution_settings` with different `service_id`

### ISSUE THREAD

**Issue by bastbu** [microsoft/semantic-kernel#5977]
**Describe the bug**

I have defined a plugin as a file similar to [the documentation](https://learn.microsoft.com/en-us/semantic-kernel/prompts/saving-prompts-as-files?tabs=Csharp#configuring-the-function-in-the-configjson-file). Consider the following `execution_settings`:

```json
{
  "gpt-3.5-turbo": {
    "ai_model_id": "gpt-3.5-turbo-0613",
    "max_tokens": 4000,
    "temperature": 0.1
  },
  "gpt-4": {
    "ai_model_id": "gpt-4-1106-preview",
    "max_tokens": 8000,
    "temperature": 0.3
  }
}
```

I would expect that by specifying the `service_id` on the registered `TextCompletionService`/`ChatCompletionService` it would automatically select the appropriate execution settings based on the specified `service_id`.

For example, if I register a `ChatCompletionService` with `service_id=gpt-3.5-turbo`, the request completes successfully. However, if I register a `ChatCompletionService` with `service_id=gpt-4`, the following error is raised:

```
File "/workspaces/.venv/lib/python3.11/site-packages/semantic_kernel/functions/kernel_function.py", line 227, in invoke_stream
    async for partial_result in self._invoke_internal_stream(kernel, arguments):
  File "/workspaces/.venv/lib/python3.11/site-packages/semantic_kernel/functions/kernel_function_from_prompt.py", line 247, in _invoke_internal_stream
    service, execution_settings = kernel.select_ai_service(self, arguments)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/.venv/lib/python3.11/site-packages/semantic_kernel/kernel.py", line 719, in select_ai_service
    return self.ai_service_selector.select_ai_service(self, function, arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/.venv/lib/python3.11/site-packages/semantic_kernel/services/ai_service_selector.py", line 44, in select_ai_service
    service = kernel.get_service(service_id, type=(TextCompletionClientBase, ChatCompletionClientBase))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/.venv/lib/python3.11/site-packages/semantic_kernel/kernel.py", line 763, in get_service
    raise KernelServiceNotFoundError(f"Service with service_id '{service_id}' does not exist")
semantic_kernel.exceptions.kernel_exceptions.KernelServiceNotFoundError: Service with service_id 'gpt-3.5-turbo' does not exist
```

It appears that the `AIServiceSelector` forces the registered service to have an ID matching the key of the _first_ registered `execution_settings`, as `get_service` will throw if no service with the given name is found:

https://github.com/microsoft/semantic-kernel/blob/3cb279774af13ca1c2e8bb17a4536f736972f5cc/python/semantic_kernel/services/ai_service_selector.py#L43-L47

This would defeat the purpose of allowing to specify multiple `execution_settings`, as the service must always match the first one defined. How is this intended to work?

**To Reproduce**

Follow the instructions in the description.

**Expected behavior**

It should not matter whether I specify `gpt-4` or `gpt-3.5-turbo`, as long as I have a matching service registered, the request should succeed.

**Platform**
 - OS: WSL2 on Windows 11
 - IDE: VS Code
 - Language: Python
 - Source: pip package `0.9.6b1`

**Comment by moonbox3** [comment]
Hi @bastbu, thank you for filing this issue. I've created a PR (#6149) to fix this.

**Comment by bastbu** [comment]
Thanks! As a corollary, I noticed the following unexpected behavior due to the special-casing of `default`:

If my execution settings are defined as:

```
{
  "default": {
    "ai_model_id": "gpt-3.5-turbo-0613",
    "max_tokens": 4000,
    "temperature": 0.1
  },
  "gpt-4": {
    "ai_model_id": "gpt-4-1106-preview",
    "max_tokens": 8000,
    "temperature": 0.3
  }
}
```

and I specify `gpt-4`, the `default` execution settings are taken. If I reverse the order to


```
{
  "gpt-4": {
    "ai_model_id": "gpt-3.5-turbo-0613",
    "max_tokens": 4000,
    "temperature": 0.1
  },
  "default": {
    "ai_model_id": "gpt-4-1106-preview",
    "max_tokens": 8000,
    "temperature": 0.3
  }
}
```

and specify `gpt-4`, the settings for `gpt-4` are used.

I would have expected that `default` takes the _lowest_ precedence. Is this perhaps something that should be addressed as well?

**Comment by moonbox3** [comment]
Hi @bastbu, if you desire that behavior, we recommend you can implement your own class. Our current class is meant to provide a basic service selector and for any customization one should create a custom implementation.
