### ISSUE TITLE
.Net: Create a classifiable Kernel Function logger.

### ISSUE THREAD

**Issue by jichulu** [microsoft/semantic-kernel#5989]
In file `semantic-kernel/dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs` when create logger, add a prefix to the name of the Logger for logging filtering.

line 160 and line 303.

make `ILogger logger = kernel.LoggerFactory.CreateLogger(this.Name) ?? NullLogger.Instance;`
to `ILogger logger = kernel.LoggerFactory.CreateLogger("Microsoft.SemanticKernel.KernelFunction." + this.Name) ?? NullLogger.Instance;`

So we can easy to filter logging via config
```
{
    "Logging": {
        "LogLevel": {
            "Microsoft.SemanticKernel.KernelFunction": "Warning"
        }
    }
}
```

**Comment by RogerBarreto** [comment]
I think that makes a lot of sense, +1. 👍🏻
