### ISSUE TITLE
.Net: Update Ollama Client in Ollama Connector to use OllamaSharp

### ISSUE THREAD

**Issue by luisquintanilla** [microsoft/semantic-kernel#5993]
Currently, the Ollama connector implements its [own client](https://github.com/microsoft/semantic-kernel/tree/feature-connectors-ollama/dotnet/src/Connectors/Connectors.Ollama/Client).

Consider replacing the current implementation with [OllamaSharp](https://github.com/awaescher/OllamaSharp). 

Related samples

- https://elbruno.com/2024/04/01/%f0%9f%93%8e-extending-semantickernel-using-ollamasharp-for-chat-and-text-completion/
- https://www.luisllamas.es/en/how-to-use-llama3-with-ollama-sharp/

**Comment by feiyun0112** [comment]
nuget OllamaSharp only support net5.0, can not install in project
```
Package OllamaSharp 1.1.1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package OllamaSharp 1.1.1 supports: net5.0 (.NETCoreApp,Version=v5.0)
```

**Comment by matthewbolanos** [comment]
Now that Ollama supports the OpenAI API standard, we may not even need a specialized Ollama connector (since a user will simply be able to use the OpenAI connector, when we pick this issue up, we will validate that this is the case and proceed accordingly

**Comment by SteveSandersonMS** [comment]
> Now that Ollama supports the OpenAI API standard, we may not even need a specialized Ollama connector (since a user will simply be able to use the OpenAI connector, when we pick this issue up, we will validate that this is the case and proceed accordingly

FYI even though Ollama does have that feature, it's currently [buggy](https://github.com/ollama/ollama/issues/4446), so unless the external issues are fixed it's still necessary to use the native Ollama protocol. Longer term there also no reason to assume the OpenAI API spec will cover all possible future Ollama features, so it would be a bit of a gamble to rely on the OpenAI protocol exclusively.

**Comment by markwallace-microsoft** [comment]
Done
