### ISSUE TITLE
.Net: OpenAI file service throws exception on `GetFilesAsync` for some valid `purpose` values

### ISSUE THREAD

**Issue by HillPhelmuth** [microsoft/semantic-kernel#6000]
**Describe the bug**
The `OpenAIFileService` method `GetFilesAsync` throws exception when an available file has a `purpose` value of `fine-tune-results`
```
 Microsoft.SemanticKernel.KernelException: Unknown OpenAIFilePurpose: fine-tune-results.
         at Microsoft.SemanticKernel.Connectors.OpenAI.OpenAIFileService.ConvertPurpose(String purpose)
         at Microsoft.SemanticKernel.Connectors.OpenAI.OpenAIFileService.ConvertFileReference(FileInfo result)
         at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
         at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
         at Microsoft.SemanticKernel.Connectors.OpenAI.OpenAIFileService.GetFilesAsync(CancellationToken cancellationToken)
```
The enum that represents this value, `OpenAIFilePurpose` only contains the fields that are valid for file upload purposes. There are additional valid values for the list or get file return objects. See [The file object](https://platform.openai.com/docs/api-reference/files/object).
**To Reproduce**
1. Create an instance of `OpenAIFileService` with an api key associated with an OpenAI User or Project that contains a file stored with `purpose` value of `fine-tune-results` (or presumably with a value of `assistants_output`)
2. Run `GetFilesAsync` 
3. See error

**Expected behavior**
Ideally, all `purpose` values would be supported and all files would be returned without error. 
Though I do see how this might present a problem since it appears that this service is largely to support OpenAI Assistant behavior, and adding additional fields to `OpenAIFilePurpose` could be confusing. I think it would be fine if those files were ignored when listing all files. Alternatively, supporting the optional `purpose` parameter in the OpenAI [List files operation](https://platform.openai.com/docs/api-reference/files/list) would also allow OpenAI users or projects to filter for supported purposes.
Current behavior prevents some users from calling `GetFilesAsync` altogether.

**Platform**
 - OS: Windows
 - IDE:Visual Studio
 - Language: C#,
 - Source: NuGet package version 1.8.0

**Comment by markwallace-microsoft** [comment]
@crickman Could you take a look at this issue?
