### ISSUE TITLE
Python: Cannot import name 'PromptTemplateConfig' from 'semantic_kernel.prompt_template' (unknown location)

### ISSUE THREAD

**Issue by tejasingle19** [microsoft/semantic-kernel#6001]
Error Message and Stack Trace (if applicable)
Exception has occurred: ImportError
cannot import name 'PromptTemplateConfig' from 'semantic_kernel.prompt_template' (unknown location)
File "C:\Users\TINGLE\Downloads\1\import asyncio.py", line 4, in
from semantic_kernel.prompt_template import PromptTemplateConfig
ImportError: cannot import name 'PromptTemplateConfig' from 'semantic_kernel.prompt_template' (unknown location)

Getting this error while trying to import the below libraries:
import asyncio
from semantic_kernel import Kernel as sk
from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion, AzureChatCompletion
from semantic_kernel.prompt_template import PromptTemplateConfig
from semantic_kernel.utils.settings import openai_settings_from_dot_env, azure_openai_settings_from_dot_env

**Comment by eavanvalkenburg** [comment]
Which version are you using? You need the latest one!

**Comment by alliscode** [comment]
Closing this for now, @tejasingle19 please reopen if you still have issues with the latest version.
