### ISSUE TITLE
.Net: Support for embedding dimensions

### ISSUE THREAD

**Issue by marcominerva** [microsoft/semantic-kernel#6026]
**Azure.AI.OpenAI** NuGet package supports the `Dimensions` property for embeddings, to set the number of dimensions the resulting output embeddings should have. I see that the latest version of [AzureOpenAITextEmbeddingGenerationService](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.OpenAI/TextEmbedding/AzureOpenAITextEmbeddingGenerationService.cs) in **Microsoft.SemanticKernel.Connectors.OpenAI** does not provide a way to specify this value.

Is there any ETA about when will this feature be available?

**Comment by stephentoub** [comment]
cc: @dmytrostruk
