### ISSUE TITLE
.Net: The method for adding a message for AgentGroupChat should align with ChatHistory

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6035]
For `ChatHistory`, to add the message, you do this:

```csharp
history.AddMessage(
        AuthorRole.User,
        Console.ReadLine()!
    );
```

For `AgentGroupChat`, to add the message, you do this:

```csharp
chat.AddChatMessage(new ChatMessageContent(AuthorRole.User, Console.ReadLine()!));
```

Ideally `AgentGroupChat` aligns on `AddMessage` that accepts the role and message.

**Comment by crickman** [comment]
This is the pattern Mark proposed on code-review.  Apparently the `ChatHistory.AddMessage()` method you identified is extraneous (Toub); although, I'm not 100% clear on what changes are planned.

**Comment by matthewbolanos** [comment]
In that case, `ChatHistory` should have `AddChatMessage`. Either way, there should be some parallelism between the two.

**Comment by crickman** [comment]
The equivalent is the `Add` method on `List`:

![image](https://github.com/microsoft/semantic-kernel/assets/66376200/5da1d47e-f789-4882-ae10-093f627843c2)
