### ISSUE TITLE
.Net: [BUG] When working with Semantic Kernel, while invoking ChatCompletion API, unable to specify data sources

### ISSUE THREAD

**Issue by jsquire** [microsoft/semantic-kernel#6061]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#43783](https://github.com/Azure/azure-sdk-for-net/issues/43783).

### Library name and version

Microsoft.SemanticKernel, Microsoft.SemanticKernel.ChatCompletion

### Describe the bug

When calling the OpenAI's chat completion API, the SDK doesn't provide an option to specify extra field such as "data_sources"

https://learn.microsoft.com/en-us/azure/ai-services/openai/references/on-your-data?tabs=rest#context

### Expected behavior

the SKD should support additional parameter to chat completions API

### Actual behavior

the SKD doesn't support additional parameter to chat completions API

### Reproduction Steps

```csharp
Microsoft.SemanticKernel.ChatCompletion.IChatCompletionService.GetStreamingChatMessageContentsAsync()
```

This method doesn't accept additional parameters to query data on custom data sources

### Environment

VS 2022
.NET 6.0
Windows

**Comment by jsquire** [comment]
Thanks, @rupeshtech, but as stated, I am just the person who transferred this issue to the proper repository.   You'll want to discuss with @chetan-d-mahajan, the author of the original issue.

**Comment by Rtoribiog** [comment]
hello @rupeshtech ,   thanks for the comment we are going to give a try and we will let you know.  @chetan-d-mahajan

**Comment by chetan-d-mahajan** [comment]
Hi @rupeshtech 

Thanks for your comment.

I tried with your suggestion and it doesn't work, the response from OpenAI API is empty which means that it isn't able to connect & fetch the data from the Azure AI search index.

Seems like the .NET SKD doesn't support data source yet.
https://github.com/microsoft/semantic-kernel/issues/6112

<img width="391" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/26963448/0e0ae393-c893-4cf1-8d2c-4fd1f470e2cb">

@Rtoribiog
