### ISSUE TITLE
Python Redis Memory Connector should be able to take existing redis connection, not just connection string

### ISSUE THREAD

**Issue by engt21** [microsoft/semantic-kernel#6084]
Python redis memory connector should be able to take an existing redis connection. For example, some enterprises require/have other methodologies to connect to redis beyond the default connection string and those connections require additional parameters that cannot work with the default connection string. 

Since connecting via the connection string also returns a redis.Redis object and sets it to the memory connector's database attribute, passing in an existing redis connector to set to that attribute should also work. 

Have already discussed this briefly with a member of the team.

I will provide the implementation/fix that worked in my enterprise in PR.

**Comment by engt21** [comment]
Please let me know if/when/what next steps are before I can raise a PR. Thanks!

**Comment by moonbox3** [comment]
As of SK Python 1.5.0 the `redis_store` supports creating the object with an existing Redis database.
