### ISSUE TITLE
.Net: Publish symbols for Microsoft.SemanticKernel.*.dll

### ISSUE THREAD

**Issue by jdrobison** [microsoft/semantic-kernel#6090]
**Describe the bug**
Code that references this package will generate a SymbolCheck error when verifying that symbols are available for Microsolft.SemanticKernel.*.dll

See https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2047053

**Comment by matthewbolanos** [comment]
I noticed that one of the warnings/errors was referring to the ActionPlanner. Can you confirm which version of Semantic Kernel you are on? That appears to be a pre-1.0 release of Semantic Kernel.

**Comment by jdrobison** [comment]
The current version is `0.15.231219.1-preview`, so your supposition appears to be correct.
