### ISSUE TITLE
.Net: Agents - Review Logging Levels / Practices

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#6095]
Review use of DEBUG / INFORMATION / ERROR

Refer to `KernelFunctionLogMessages` as possible reference.

**Comment by markwallace-microsoft** [comment]
We should refer to this guidance https://learn.microsoft.com/en-us/dotnet/core/extensions/logging-library-authors

**Comment by crickman** [comment]
Yes this is all good.  I was discussing the `LogMessages` approach with Dmytro.  I think we nailed the other aspects outlined in this article.  Was there something specific on your mind to call out?
