### ISSUE TITLE
Python: Add save_information_batch to SemanticTextMemory class

### ISSUE THREAD

**Issue by sinyubonnie-ho** [microsoft/semantic-kernel#6115]
Currently I am using save_information in the memory (https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/memory/semantic_text_memory.py) which only allows me to create embedding and save the record one by one. I want to do it in batch to speed up the process. I will work on adding the function save_information_batch  to the SemanticTextMemory class and create PR. Thanks!

**Comment by alliscode** [comment]
Hi @sinyubonnie-ho, thank you for this. We are moving to a new design for our memory connectors which you can see the details of in #5887. I'm closing this issue for now but please feel free to reopen if needed. Thanks!
