### ISSUE TITLE
Basic planner returns String instead of a FunctionResult as the response

### ISSUE THREAD

**Issue by sachithaabey** [microsoft/semantic-kernel#6128]
In Basic planner (/python/semantic_kernel/planners/basic_planner.py), it returns a String value as the response. Is it possible to return the FunctionResult object as it is without converting it into a String? Because in my case, I am trying to return an object of another class. Since the returning value is a string, I am unable to return it. It only returns the object name and the address as a string. But without the string conversion, it returns the FunctionResult and can access the object or whatever the returning content via the returned object.
`plan = await planner.create_plan(request, self.kernel)`
`resp = await planner.execute_plan(plan, self.kernel)`
`print(f"Strategy Code2: {resp.value.strategy_code}")`

Original Implementation:
<img width="512" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/161709746/a67276ea-df05-45b1-a3a2-d1e1497fa3b1">

After str conversion:
<img width="525" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/161709746/85ee21be-a019-41ab-a2da-e9b12ec5c53d">

**Comment by moonbox3** [comment]
Hi @sachithaabey, we're going to be deprecating this planner in the next week or so, before we get to a Python v1 SDK. This planner is not supported in dotnet, and we're working towards parity. Please be aware that the action planner and stepwise planner will also be deprecated. Please have a look at the function calling stepwise planner in the meantime.

**Comment by sachithaabey** [comment]
I'm currently developing a stepwise planner for function calling. Here's a simple plugin I'm using to prompt the user for a new account ID and update it in the ask_obj object.
```
@kernel_function(
        description="If the user needs to update or change the account id, please identify the specific account id mentioned in the user input. Once identified, proceed to update the corresponding account id within the AskAssetteIntegration object.",
        name="update_acount_id"
    )
    def update_acount_id(self):

        result = "Please provide a valid account id."
        result = self.helper.get_more_human_like_text(result)
        print(f"Assistant > {result}\n")
        self.history.add_assistant_message(str(result))

        account_id = input("User > ")
        self.history.add_user_message(account_id)
        if str(ac_id).lower() != "none":
            ac_id = self.helper.get_account_id(account_id)
            self.ask_obj.account_id = ac_id
        return self.ask_obj
```
 Similarly, I have another plugin to update the strategy code, which functions in a similar manner. When the user requests to change both the account ID and the strategy code, I need to invoke the aforementioned plugins. Although the generated plan displays a perfect step-by-step approach, it fails to call any of the implemented plugins. I'm seeking to resolve this issue.

**Generated Plan** :
```
To achieve the goal of changing the account ID and the as of date, the following plan can be executed using the provided functions:

1. **Identify the New Account ID and As of Date**: Before any changes can be made, it's necessary to know what the new account ID and as of date are. This information should be provided by the user. If the information is not yet provided, use the `chat_plugin-Chat` function to ask the user for the new account ID and the as of date.

2. **Update the Account ID**: Once the new account ID is identified, use the `AskAssettePlugin-update_acount_id` function to update the account ID in the AskAssetteIntegration object. This step requires the specific account ID mentioned by the user.

3. **Update the As of Date**: After updating the account ID, use the `AskAssettePlugin-update_as_of_date` function to update the as of date in the AskAssetteIntegration object. This step requires the specific as of date mentioned by the user.

4. **Confirm Changes**: After both the account ID and the as of date have been updated, use the `chat_plugin-Chat` function to inform the user that the changes have been made successfully and to confirm 
```
