### ISSUE TITLE
Python Redis Memory Connector should allow for filtering when searching

### ISSUE THREAD

**Issue by engt21** [microsoft/semantic-kernel#6159]
As related to my investigations of the Python redis memory connector in https://github.com/microsoft/semantic-kernel/issues/6084 and https://github.com/microsoft/semantic-kernel/issues/6088, the redis memory connector by default only goes *=> to do the search. This will return all the keys in the store. However, there should be an option for the user to allow them to provide a key to filter on, much like in native redis. Although you can pass in the collection name, this allows for greater granularity and accuracy of RAG, especially for large applications that have similar values and many k-v pairs stored.

We found that when we had key value pairs with similar or nearly identical values, even when passing the collection name in, we got poor performance, unless we modified the filter.

**Comment by matthewbolanos** [comment]
@westey-m, adding you here so that you have context of some of the requests coming in for memory (in case it helps with creating the abstraction).
