### ISSUE TITLE
Operators on ScoredValue produce inconsistent answers

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#616]
`ScoredValue<T>` contains both a `T` and a `double`.  Its `==` and `!=` operators factor in equality of both the `T` and the `double`, but its `<`, `<=`, `>=`, and `>` operators only factor in the `double`.  That means, for example, `<=` might return true in situations where `==` returns false, if the `T` in the two instances being compared isn't equal.

**Comment by dluc** [comment]
@awharrison-28 FYI

**Comment by awharrison-28** [comment]
@dmytrostruk

**Comment by dmytrostruk** [comment]
Thanks, I added this issue to our backlog.
