### ISSUE TITLE
Token usage stats from responses should be returned to the client.

### ISSUE THREAD

**Issue by SOE-YoungS** [microsoft/semantic-kernel#618]
OpenAI / Azure OpenAI both return token stats with responses.

These are useful for tracking usage etc... on a case by case basis for things like "inter-departmental billing" etc...

Currently SK only supports returning the completion (string), meaning token usage is not accessible to the end user & unavailable for future evaluation / tracking.

SK, should return an object containing token stats & completion string.

Example use case(s):

1. A large enterprise (parent company pays the bills) with subsidiaries (AI implementation end users). The parent will want to track token usage by each subsidiary to ensure cross charging for usage is correct.
1. Stored as a statistic in an end users account. This allows the end user to see & be aware of token usage over time VS individual queries.

**Comment by evchaki** [comment]
@SOE-YoungS , great idea, we will take a look at getting this added.
