### ISSUE TITLE
.Net: Null properties crash Handlebars plans

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6187]
### Discussed in https://github.com/microsoft/semantic-kernel/discussions/6098

<div type='discussions-op-text'>

<sup>Originally posted by **preezie-yasir** May  2, 2024</sup>
When i use {{set "variable_name" null}} and pass variable_name as a parameter to a function call, it throws an error passing in i guess an empty string. Is there a way we can do this? Im using C#'s Semantic Kernel library Handlebars planners txt files</div>

**Comment by Kee2u** [comment]
Im interested in this issue as well Im working with the code interpreter sample https://github.com/microsoft/semantic-kernel/blob/main/python/samples/concepts/plugins/azure_python_code_interpreter.py and the upload_file function here requires some optional arguments as is evident from this line in the SessionsPythonTool class:
"""

    if data and local_file_path:
        raise ValueError("data and local_file_path cannot be provided together")
        
But if I dont provide data and just provide the local_file_path, it errors out saying the data field is required

**Comment by markwallace-microsoft** [comment]
Planners are obsolete
