### ISSUE TITLE
.Net: There should be a non-async CreateOpenApiPlugin method if the OpenApi JSON is a local resource

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6192]
There should be a method that accepts a JSON string if the developer has a local copy of a swagger file to avoid needing to download the swagger file from a URI. With this feature, we should also allow a developer to synchronously add OpenAPI plugins while using the kernel builder.

**Comment by SergeyMenshykh** [comment]
Additionally, it should be possible to create OpenAPI plugins once and reuse them with transient kernels. This will require an API that does not require a kernel as a parameter, similar to the markdown and YAML function factories - KernelFunctionMarkdown and KernelFunctionYaml.

**Comment by markwallace-microsoft** [comment]
Can do this with the existing method which takes a stream
