### ISSUE TITLE
Python: semantic_kernel.connectors.ai.open_ai.OpenAIChatCompletion is missing endpoint property

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6202]
In .NET, when constructing an OpenAIChatCompletion, you can provide an optional endpoint property to connect to local models and other services that use the OpenAI API specification.

**Comment by alliscode** [comment]
@TaoChenOSU I believe this can be closed with the work you are doing to support local models on python. Can you verify?
