### ISSUE TITLE
Java: Unable to find maven package for OpenAI services

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6209]
According to these docs https://github.com/microsoft/semantic-kernel/blob/java-v1/java/PACKAGES.md, there should be a semantickernel-connectors-ai-openai package, but it does not appear to be available on Maven.

**Comment by johnoliver** [comment]
the package you are looking for is:

```
            <dependency>
                <groupId>com.microsoft.semantic-kernel</groupId>
                <artifactId>semantickernel-aiservices-openai</artifactId>
            </dependency>
```

**Comment by matthewbolanos** [comment]
Worked after doing `mvn clean install -U`
