### ISSUE TITLE
Java: Building Java package locally fails

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6210]
It appears that the new location of the prompts is causing build failures for the Java library.

<img width="1115" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1409190/d36d6237-cbf0-4a5d-aa8d-498ab7becf52">

**Comment by johnoliver** [comment]
This looks like you are building from the main branch, we are working from the `java-development` branch
