### ISSUE TITLE
Add support for latest OpenAI chat completion settings

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#6244]
Check [here](https://platform.openai.com/docs/api-reference/chat/create)
- [stream_options](https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options)

**Comment by jungwookim** [comment]
Could you share any updates or plans?

**Comment by RogerBarreto** [comment]
Setting this property currently is not possible as this property is `internal` in `OpenAI` SDK.

Currenlty this property is always set to `true` in `OpenAI` SDK 

See: 
https://github.com/openai/openai-dotnet/blob/539172fc699d29c3a812c848b07dc7e67fc7630f/src/Custom/Chat/ChatCompletionOptions.cs#L49

and set to `false` in `Azure OpenAI` SDK.

See: 
- https://github.com/microsoft/semantic-kernel/issues/9420
- https://github.com/Azure/azure-sdk-for-net/issues/46407
- https://github.com/Azure/azure-sdk-for-net/issues/44237
