### ISSUE TITLE
.Net: Dotnet notebooks not working out of the box

### ISSUE THREAD

**Issue by eamon-keane** [microsoft/semantic-kernel#6247]
**Describe the bug**
Getting started notebook does not work as is. DirectoryPath is incorrect for the plugins

**To Reproduce**
Run the notebooks in order

**Expected behavior**
Notebooks load plugins correctly

**Screenshots**

**Platform**
 - OS: Windows
 - IDE:VS Code
 - Language: C#

**Additional context**
Need to update the path to this:

var funPluginDirectoryPath = Path.Combine(System.IO.Directory.GetCurrentDirectory(), "..", "..", "prompt_template_samples", "FunPlugin");

**Comment by MichaelHomme** [comment]
Hello everyone,

I am not sure if this warrants a new issue, as it is closely related to the current one. 

In the C# notebooks [02-running-prompts-from-file.ipynb](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/notebooks/02-running-prompts-from-file.ipynb), the references to the `samples` folder and the `JokeFunction`-function are not pointing to the correct paths. 

I would be happy to make the necessary changes to fix both notebooks and submit a PR. 

Alternatively, if you deem it necessary, I can create a new issue.

**Comment by MichaelHomme** [comment]
Hello everyone,

I am not sure if this warrants a new issue, as it is closely related to the current one. In the C# notebooks [02-running-prompts-from-file.ipynb](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/notebooks/02-running-prompts-from-file.ipynb), the reference to the `samples` folder and the `JokeFunction` is not pointing to the correct path. I would be happy to make the necessary changes to fix both notebooks. Alternatively, if you deem it necessary, I can create a new issue.

Thank you.

**Comment by dmytrostruk** [comment]
@eamon-keane @MichaelHomme thanks for reporting this issue. I fixed path issues and also updated version of SK in notebooks to `1.11.1` in this PR: https://github.com/microsoft/semantic-kernel/pull/6273

**Comment by eamon-keane** [comment]
Excellent 👌

**Comment by MichaelHomme** [comment]
Great, thanks 👍
