### ISSUE TITLE
OpenAI token authentication fails in AzureUSGovernment cloud

### ISSUE THREAD

**Issue by ebclark2** [microsoft/semantic-kernel#6255]
**Describe the bug**
OpenAI token authentication fails in AzureUSGovernment cloud with invalid token/audience error.

**To Reproduce**
In AzureUSGovernment configure OpenAI Auth type to "AzureIdentity" and provide a valid idenitty.

**Expected behavior**
OpenAI calls authenticate successfully.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/819812/87e2cd1d-f676-48b4-a85f-d444a14c8925)

**Platform**
 - OS: All
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**
See [OpenAIClient Issue](https://github.com/Azure/azure-sdk-for-net/issues/44021)

**Comment by markwallace-microsoft** [comment]
@ebclark2 Thanks for creating the issue. Does this scenario work if you use the [Azure OpenAI SDK](https://www.nuget.org/packages/Azure.AI.OpenAI/1.0.0-beta.17) directly?

**Comment by ebclark2** [comment]
No, it does not.  I was able to confirm the problem is the token scope.  It
works if I build a new version of the openai SDK with the correct scope.
