### ISSUE TITLE
Python: FunctionCallContent and FunctionResultContent should have plugin_name and function_name

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6258]
Today, each class only has `name`. `name` should be split out into its component parts

**Comment by eavanvalkenburg** [comment]
we did that through methods in python, `.split_name` and `.split_name_dict`, we could create properties from there to mitigate, would that work?

**Comment by matthewbolanos** [comment]
Yes, that'd be great
