### ISSUE TITLE
.Net: Add Support for "dall-e-3" Model in OpenAITextToImageService Class

### ISSUE THREAD

**Issue by Nurgo** [microsoft/semantic-kernel#6269]
Hi,

I propose we add support for the "dall-e-3" model within the OpenAITextToImageService class. The integration seems straightforward and the benefit to the users would be substantial.

Thank you for considering this request.

**Comment by dmytrostruk** [comment]
@Nurgo Please check these notebooks, they use "dall-e-3" model as example for image generation:
- https://github.com/microsoft/semantic-kernel/blob/main/dotnet/notebooks/07-DALL-E-3.ipynb
- https://github.com/microsoft/semantic-kernel/blob/main/dotnet/notebooks/08-chatGPT-with-DALL-E-3.ipynb

**Comment by Nurgo** [comment]
Hi @dmytrostruk , thank you for your reply. These notebooks only use "dall-e-3" if `AddAzureOpenAIChatCompletion` is used, and not `AddOpenAITextToImage`. From what I can see in the code, `OpenAITextToImageService` still uses "dall-e-2". Moreover, the image formats supported (256x256, 512x512, 1024x1024) are those of "dall-e-2".

**Comment by dmytrostruk** [comment]
@Nurgo Got it. Yes, looks like `dall-e-3` is only implemented in `AzureOpenAITextToImageService` class, but not in `OpenAITextToImageService`.

**Comment by aghimir3** [comment]
Hello,

I am interested in adding support for dall-e-3 in OpenAITextToImageService. 

The most straightforward way I can think of is by changing the `GenerateImageAsync` from (a) to (b) in `OpenAITextToImageService.cs`:

(a): Current version

```csharp
public Task<string> GenerateImageAsync(string description, int width, int height, Kernel? kernel = null, CancellationToken cancellationToken = default)
{
    Verify.NotNull(description);
    if (width != height || (width != 256 && width != 512 && width != 1024))
    {
        throw new ArgumentOutOfRangeException(nameof(width), width, "OpenAI can generate only square images of size 256x256, 512x512, or 1024x1024.");
    }

    return this.GenerateImageAsync(this._modelId, description, width, height, "url", x => x.Url, cancellationToken);
}
```

(b): Added support for dall-e-3 image sizes based on documentation available at [DALL·E 3 API](https://platform.openai.com/docs/guides/images/usage)

```csharp
public Task<string> GenerateImageAsync(string description, int width, int height, Kernel? kernel = null, CancellationToken cancellationToken = default)
{
    Verify.NotNull(description);

    if (this._modelId == "dall-e-3")
    {
        if (!((width == 1024 && height == 1024) || (width == 1024 && height == 1792) || (width == 1792 && height == 1024)))
        {
            throw new ArgumentOutOfRangeException(nameof(width), width, "DALL·E 3 can generate only images of size 1024x1024, 1024x1792, or 1792x1024.");
        }
    }
    else
    {
        if (width != height || (width != 256 && width != 512 && width != 1024))
        {
            throw new ArgumentOutOfRangeException(nameof(width), width, "OpenAI can generate only square images of size 256x256, 512x512, or 1024x1024.");
        }
    }

    return this.GenerateImageAsync(this._modelId, description, width, height, "url", x => x.Url, cancellationToken);
}
```

Additionally, I was wondering if we should continue hardcoding the image sizes within the method, or if there might be a better approach, such as using configuration somewhere to manage these values. Any advice on this would be greatly appreciated. 
Thank you for your consideration.

**Comment by RogerBarreto** [comment]
The changes we made for the new OpenAI and AzureOpenAI Connectors will bring full support for the dall-e-3 models using OpenAI's TextToImageService. 

https://github.com/microsoft/semantic-kernel/blob/feature-connectors-openai/dotnet/src/Connectors/Connectors.OpenAI/Services/OpenAITextToImageService.cs

You can expect a release candidate to be soon release this or next week.

Follow that on our [feature-connectors-openai](https://github.com/microsoft/semantic-kernel/tree/feature-connectors-openai) branch.
