### ISSUE TITLE
.Net: Invoking kernel function directly with auto invoke enabled results in multiple nested calls to the function

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/semantic-kernel#6281]
**Describe the bug**
When a kernel function is invoked directly via
```C#
public async Task<TResult?> InvokeAsync<TResult>(
        string? pluginName,
        string functionName,
        KernelArguments? arguments = null,
        CancellationToken cancellationToken = default)
```
, and with auto invoke enabled, it may result in multiple calls to the function, which means multiple calls to the model, causing unnecessary round trips. 

**To Reproduce**
1. Create a simple console app.
2. Copy the [`WriterPlugin`](https://github.com/microsoft/semantic-kernel/tree/main/prompt_template_samples/WriterPlugin) to the project root.
3. Do the following:
```C#
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.OpenAI;
using System;
using System.IO;
using System.Threading.Tasks;

public sealed class Program
{
    /// <summary>
    /// The main entry point for the application.
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static async Task Main()
    {
        var loggerFactory = new NullLoggerFactory();
        var kernel = GetKernel(loggerFactory);

        OpenAIPromptExecutionSettings settings = new() { ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions };
        KernelArguments arguments = new(settings);
        arguments["input"] = "Write a poem about John Doe.";
        var poem = await kernel.InvokeAsync<string>(
            "WriterPlugin",
            "ShortPoem",
            arguments
        );
        Console.WriteLine($"Poem:\n{poem}\n");
    }

    private static Kernel GetKernel(ILoggerFactory loggerFactory)
    {
        IKernelBuilder builder = Kernel.CreateBuilder();

        builder.Services.AddSingleton(loggerFactory);
#pragma warning disable SKEXP0001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
        builder.Services.AddSingleton<IFunctionInvocationFilter, FirstFunctionFilter>();
#pragma warning restore SKEXP0001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
        builder.AddAzureOpenAIChatCompletion(
            deploymentName: "...",
            modelId: "...",
            endpoint: "...",
            apiKey: "...");

        builder.Plugins.AddFromPromptDirectory(Path.Combine("./", "WriterPlugin"));

        return builder.Build();
    }

#pragma warning disable SKEXP0001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
    private sealed class FirstFunctionFilter() : IFunctionInvocationFilter
    {
        public async Task OnFunctionInvocationAsync(FunctionInvocationContext context, Func<FunctionInvocationContext, Task> next)
        {
            Console.WriteLine($"FunctionInvoking - {context.Function.PluginName}.{context.Function.Name}");
            await next(context);
            Console.WriteLine($"FunctionInvoked - {context.Function.PluginName}.{context.Function.Name}");
        }
    }
#pragma warning restore SKEXP0001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
}
```
4. Run the app and you will see more than one outputs of `FunctionInvoking - WriterPlugin.ShortPoem` in the terminal.

**Expected behavior**
A single invocation of the `ShortPoem` function, regardless if `AutoInvokeKernelFunctions` is enabled.

With auto invoke disabled, you will see the filter being run only once:
![image](https://github.com/microsoft/semantic-kernel/assets/12570346/c171640c-8445-4ae5-ae15-dda20f78bf52)

**Screenshots**
Multiple invocations:
![image](https://github.com/microsoft/semantic-kernel/assets/12570346/1fd79e16-7a60-46bc-8f56-3a9913f75e09)

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#, Python
 - Source: main branch

**Additional context**
Tested on GPT-4 and GPT-4 turbo

**Comment by markwallace-microsoft** [comment]
In the above code `WriterPlugin.ShortPoem` is called directly but also providing it as a function to the model for it to invoke and expecting it to call it. The `ShortPoem` prompt starts with `Generate a short funny poem` and the input also has `Write a poem about John Doe` so it looks like this triggers the model to call the function again.

There are a few things that could help here:

1. Call `var poem = await kernel.InvokePromptAsync` with the input and allow the model decide if it needs to call the function 
1. Change the input to just `John Doe`

**Comment by TaoChenOSU** [comment]
The sample just shows how to reproduce the issue. In reality, the execution settings with auto invoke enabled could come from somewhere else, such as a service selector. It's fairly easy for someone to have auto invoke enabled by default in their apps and still invoke registered functions using `InvokeAsync`, which could silently result in multiple round trips to the model.

I suggest we have a list of anti-patterns somewhere if we don't suggest users to have auto invoke on and still plan to invoke registered functions directly.

**Comment by TaoChenOSU** [comment]
Say someone has set up a service selector that returns some default settings with auto invoke enabled.
```
bool TrySelectAIService<T>(
        Kernel kernel,
        KernelFunction function,
        KernelArguments arguments,
        [NotNullWhen(true)] out T? service,
        out PromptExecutionSettings? serviceSettings) where T : class, IAIService;
```
And in their apps, they wouldn't notice anything different but in reality, they could be consuming more tokens they need and their apps will be slower.

**Comment by markwallace-microsoft** [comment]
Agreed. Possibly we shouldn't advertise the current function to the model, I'm not sure if that would ever be useful.

We have a task to provide more control over what kernel functions are advertised to the model, I can include this use case as part of that.

**Comment by moonbox3** [comment]
@TaoChenOSU @markwallace-microsoft is this issue still needed?

**Comment by TaoChenOSU** [comment]
> @TaoChenOSU @markwallace-microsoft is this issue still needed?

Are we still advertising the current function to the model? If so, we still have the issue.

**Comment by markwallace-microsoft** [comment]
We have provided more control over which functions get advertised to the model, see: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Concepts/FunctionCalling/FunctionCalling.cs
