### ISSUE TITLE
Include errors from function call failures during automatic function calling in SK telemetry

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#6285]
https://github.com/microsoft/semantic-kernel/pull/6263#discussion_r1602982777

Do this consistently across all of the connectors that support function calling

**Comment by dmytrostruk** [comment]
I think we are already logging it, but it's something that worth to include into function calling abstraction logic as well.

OpenAI:
https://github.com/microsoft/semantic-kernel/blob/f9247dab0c588dca5fb6422fe6c1b4754e752136/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L1446-L1451

Mistral:
https://github.com/microsoft/semantic-kernel/blob/f9247dab0c588dca5fb6422fe6c1b4754e752136/dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs#L923-L928

**Comment by dmytrostruk** [comment]
Based on my investigation, it looks like all current connectors, which support function calling, already log errors from function call failures. 

For connectors that use SK `FunctionCallsProcessor` (e.g. OpenAI):
https://github.com/microsoft/semantic-kernel/blob/ca5e2859a498ab7c504ebfb8633916b819f4a970/dotnet/src/InternalUtilities/connectors/AI/FunctionCalling/FunctionCallsProcessor.cs#L277-L281

For connectors that use M.E.AI `FunctionInvokingChatClient` (e.g. Ollama):
https://github.com/dotnet/extensions/blob/c86b7ead537a3534eb7fbc748384417b6a552bf0/src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClient.cs#L616-L619

Mistral AI:
https://github.com/microsoft/semantic-kernel/blob/ca5e2859a498ab7c504ebfb8633916b819f4a970/dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs#L925-L930

Google Gemini:
https://github.com/microsoft/semantic-kernel/blob/ca5e2859a498ab7c504ebfb8633916b819f4a970/dotnet/src/Connectors/Connectors.Google/Core/Gemini/Clients/GeminiChatCompletionClient.cs#L496-L499

**Comment by dmytrostruk** [comment]
Closing this issue as per comment above.
