### ISSUE TITLE
Tool call information missing in Model Diagnostics for Mistral streaming

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/semantic-kernel#6316]
**Describe the bug**
Tool call information in model diagnostics when using Mistral streaming.

**Expected behavior**
Tool call information should be presented in model diagnostics when using Mistral streaming.

**Comment by markwallace-microsoft** [comment]
@TaoChenOSU can we close this issue?

**Comment by TaoChenOSU** [comment]
Will do another round of testing.

**Comment by TaoChenOSU** [comment]
Tool calls from MistralAI will be contained entirely in a single chunk returned from their streaming API, thus it doesn't require buffering during streaming and concatenation after streaming to reassemble the complete tool call. That being said, the current implementation of the MistralAI streaming chat completion service in .Net SK doesn't need any modification to have tool calls appear in the prompt span events. 
![Image](https://github.com/user-attachments/assets/74cbd260-74f9-4c27-9b14-e4c683ffc96f)
Note: we are not sure if MistralAI supports parallel function calling and if it does how will multiple tool calls get streamed back to the client.
