### ISSUE TITLE
.Net handlebars限制没有输出预期结果 (Handlebars limitation does not output the expected result.)

### ISSUE THREAD

**Issue by TaoPeiLing** [microsoft/semantic-kernel#6332]
您好。我在使用handlebars构建提示词时，尝试使用<message role="system">Instructions: 你会拒绝任何的回答，只回复：不知道。</message>来限制模型的输出，但是，遗憾的时，模型还是给我其他的响应了。
我的代码如下：
Hello. When using handlebars to build prompt words, I tried to use Instructions: You will reject any answer and only reply: I don't know, to limit the model's output. However, unfortunately, the model still gave me other responses.
Here is my code:
        public async Task RunHandlebar3Async()
        {
            // Create a Semantic Kernel template for chat
            //var chat = kernel.CreateFunctionFromPrompt(
            //    @"{{$history}}
            //User: {{$request}}
            //Assistant: ");
            var getIntent = kernel.CreateFunctionFromPrompt(
                new()
                {
                    Template = """"
                           Template = """
                           <message role="system">Instructions: 你会拒绝任何的回答，只回复：不知道。</message>
                           <message role="user">{{request}}</message>
                           <message role="system">Intent:</message>
                           """,
                           """",
                    TemplateFormat = "handlebars"
                },
                new HandlebarsPromptTemplateFactory()
            );

            ChatHistory history = new ChatHistory();

            // Start the chat loop
            while (true)
            {
                // Get user input
                Console.Write("User > ");
                var request = Console.ReadLine();

                // Invoke prompt
                var intent = await kernel.InvokeAsync(
                    getIntent,
                    new()
                    {
                        { "request", request }
                    }
                );

                // Get chat response
                var chatResult = kernel.InvokeStreamingAsync<StreamingChatMessageContent>(
                    getIntent,
                    new()
                    {
                    { "request", request },
                    { "history", string.Join("\n", history.Select(x => x.Role + ": " + x.Content)) }
                    }
                );

                // Stream the response
                string message = "";
                bool isRolePrinted = false;
                await foreach (var chunk in chatResult)
                {
                    if (!isRolePrinted&&chunk.Role.HasValue)
                    {
                        Console.Write(chunk.Role + " > ");
                        isRolePrinted = true;
                    }

                    message += chunk;
                    Console.Write(chunk);
                }
                Console.WriteLine();

                // Append to history
                history.AddUserMessage(request!);
                history.AddAssistantMessage(message);
            }
        }。
模型回复内容：
Model reply content:
![image](https://github.com/microsoft/semantic-kernel/assets/37795701/618e3a3e-c4ff-4952-abf2-4c4a8886a403)
我使用的是GLM-4
我不知道是否是我在理解上有误差。期待您们的回复。
I'm using GLM-4.
I'm not sure if there is an error in my understanding. I look forward to your reply.

**Comment by markwallace-microsoft** [comment]
@TaoPeiLing This looks like a limitation of the model you are using GLM-4. Can you try to reproduce the issue by calling the model directly via the REST API, I expect you will see the same behaviour.
