### ISSUE TITLE
Python: Does not support timeout in httpx.

### ISSUE THREAD

**Issue by yuichiromukaiyama** [microsoft/semantic-kernel#6338]
**Describe the bug**
The following issue arises from using httpx as the HTTP client: it is not possible to change this parameter. The problem is that the default timeout duration is set to 5 seconds, which is relatively short. For instance, when an agent calls another agent or a RAG  database, if it takes some time, the connection is quickly terminated. While a 5-second response time might be sufficient for general APIs, for generative AI, a longer timeout duration is often desirable.

AsIs: https://github.com/microsoft/semantic-kernel/blob/3e197853bf54e7cfc42fc22c019ea1157db6eae1/python/semantic_kernel/connectors/openapi_plugin/openapi_manager.py#L602
```python
response = await client.request(
    method=operation.method,
    url=url,
    headers=merged_headers,
    json=json.loads(payload) if payload else None,
)
```

**To Reproduce**

```python
# Calling another agent. The response will take 5-10 seconds.
await kernel.add_plugin_from_openai(
    plugin_name="Example",
    plugin_url="http://localhost:3001/.well-known/ai-plugin.json",
)

settings.tool_choice = "auto"
settings.function_call_behavior = FunctionCallBehavior.AutoInvokeKernelFunctions()

history = ChatHistory()
history.add_user_message("please get current todos. user name is john.")

response = await service.get_chat_message_contents(
    chat_history=history,
    settings=settings,
    kernel=kernel,
    arguments=KernelArguments(settings=settings),
)

content = response[0]
print(content)
```

**Expected behavior**
To be able to set an appropriate timeout duration.

**Screenshots**
none

**Platform**
 - OS: Mac OS X
 - IDE: VS Code
 - Language: Python
 - Source: pip 23.2.1, Python 3.11.7, semantic kernel 1.0.0rc1

**Additional context**
ToBe: It would be beneficial to be able to pass arguments flexibly as shown below, or to have a sufficiently long timeout setting, or to be able to specify it through environment variables.

```python
response = await client.request(
    method=operation.method,
    url=url,
    headers=merged_headers,
    json=json.loads(payload) if payload else None,
   **kwargs,
)
```

**Comment by moonbox3** [comment]
@yuichiromukaiyama let me have a look today. It is possible to pass in a custom httpx.AsyncClient. Would that help your use case?

**Comment by yuichiromukaiyama** [comment]
@moonbox3 

Thank you! Yes, it would be helpful if we could change settings like timeout. In our use case, we are developing an agent that calls multiple RAGs and LLMs from the semantic kernel. When calling LLMs, especially through plugins, it can take a long time to get the initial response. These plugins can have slightly longer wait times, so being able to set timeouts ourselves would be extremely beneficial. Additionally, we are implementing a use case similar to Autogen, where one Agent (Semantic Kernel) calls another Agent (Semantic Kernel). In such cases, having a longer timeout would be beneficial as well.

**Comment by moonbox3** [comment]
@yuichiromukaiyama please go ahead and configure your custom httpx.AsyncClient as part of the [OpenAPIFunctionExecutionParameters](https://github.com/microsoft/semantic-kernel/blob/2b96abfb2fb5d3cc3295cd9aec1ef689befb722d/python/semantic_kernel/connectors/openapi_plugin/openapi_function_execution_parameters.py#L21C5-L21C16). That will give you the flexability to set the timeout and any other properties on the client. That client is passed all the way to the `run_operation`'s [fetch](https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/connectors/openapi_plugin/openapi_manager.py#L609) method.

**Comment by moonbox3** [comment]
Closing this as a custom httpx.AsyncClient can be configured and passed through to the fetch method.

**Comment by yuichiromukaiyama** [comment]
Sorry. I didn't realize the feature existed. Thank you!
