### ISSUE TITLE
Error while saving to Semantic Memory using NoSQL

### ISSUE THREAD

**Issue by sandeepsnairms** [microsoft/semantic-kernel#6379]
I am trying to store into Semantic Memory using below code

```
public async Task SaveEmbeddingsAsync(string data, string id)
{
    try
    {
        await meomoryWithCosmosNoSQL.SaveReferenceAsync(
            collection: MemoryCollectionName,
            text: data,
            externalId:id,
            externalSourceName:"RecipeApp"
            );


    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.ToString());   
    }
}
```
I am getting the below exception and can’t make out what it refers to as input name.

"Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 76cf2457-164b-49c0-b249-6e929bef8dfc; Reason: (Message: {\"Errors\":[\"The input name '' is invalid. 

@Pilchie

**Comment by Pilchie** [comment]
I believe this is because the Cosmos NoSQL connector uses the `key` as a partition key, but `SaveReferenceAsync` doesn't pass in a `key`. I'll take a look probably tomorrow.
