### ISSUE TITLE
Vector Database solution

### ISSUE THREAD

**Issue by kborowiec-mag** [microsoft/semantic-kernel#638]
Hello,
We are looking for Vector Database solution and would like to use Azure resource for that purpose. 

Is Redis Cache proper solution, what your thoughts about that?
 
I heard about following products which can help but would prefer to use Azure one: 

- FAISS (Facebook AI Similarity Search)
- Milvus
- Pinecone

**Comment by timlaverty** [comment]
Hi, 

I have not looked at FAISS.  

Here’s an example of using Qdrant from SK - https://github.com/microsoft/semantic-kernel/blob/main/samples/dotnet/kernel-syntax-examples/Example19_Qdrant.cs.  SK uses the Qdrant Docker container local and hosts it on AKS as well.

There’s support in the repo for in ram, sqlite, cosmos, and Qdrant.  Chroma and Pinecone support are in PR (from community members): https://github.com/microsoft/semantic-kernel/issues/449, https://github.com/microsoft/semantic-kernel/pull/610.  

These and others will shortly come in (status here): https://github.com/microsoft/semantic-kernel/blob/main/FEATURE_MATRIX.md#connectors-and-skill-libraries.
