### ISSUE TITLE
Python: planners should work like in C#

### ISSUE THREAD

**Issue by benceblaske** [microsoft/semantic-kernel#6386]
In the C# SDK, all planners have a seperate CreatePlanAsync and InvokeAsync functions. I am building apps where there should be a possibility for the end user to refine / approve the created plan before it gets executed.
I also visualize the plan e.g. via just printing it or converting it to a Mermaid chart.
See my C# implementation for getting an idea on the workflow: https://github.com/bbence84/semantic_kernel_copilot_demo

I would like to implement the same in Python: create and execute plans separately, be able to get the plan string to be able to show it to the user first, and visualize via Mermaid chart.

**Comment by markwallace-microsoft** [comment]
Here's the task https://github.com/microsoft/semantic-kernel/issues/6745 which tracks how to migrate
