### ISSUE TITLE
Python: Facing issues in executing the notebooks in semantic kernel

### ISSUE THREAD

**Issue by Gayatrimurali** [microsoft/semantic-kernel#6387]
**Describe the bug**
Base URL or Endpoint Required

**To Reproduce**
1. Navigate to semantic-kernel/python/samples/getting_started/00-getting-started.ipynb
2. Facing error while executing Option:2 - using Azure OpenAI
Even after adding the path as mentioned in the description, we are facing baseurl or endpoint required issue.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/139850907/3dc64cd6-802e-487b-bdb1-5214b2aa3412)

**Comment by moonbox3** [comment]
Hi @Gayatrimurali, per your screenshot you're showing you are providing the `env_file_path=".env"`. It needs to be a file path and not a relative file path. Can you please try an absolute file path? Note: if you are using [Poetry with SK](https://github.com/microsoft/semantic-kernel/blob/main/python/DEV_SETUP.md#using-poetry) (which we highly recommend), Poetry will load your .env file variables into env vars when you start up an IDE like VSCode.

**Comment by alliscode** [comment]
Closing this for now. @Gayatrimurali please re-open if this is still an issue. Thanks!
