### ISSUE TITLE
Python: In v1.0.2 it's not possible to have lists or dictionaries as fields of a KernelBaseModel

### ISSUE THREAD

**Issue by q-stefanmuscalu** [microsoft/semantic-kernel#6388]
**Describe the bug**
I am writing a native python plugin and I have this code 
```python
class Profile(KernelBaseModel):
    first_name: str
    last_name: str
    phone_numbers: list[str]

class ProfilePlugin:
    @kernel_function(name="GetPersonProfile", description="Gets a person's profile given their id.")
    def get_profile(self, person_id: str) -> Profile:
        return Profile(first_name="John", last_name="Doe")
```
My app fails to start up.  Stuff breaks because of the `phone_numbers`. If I comment out the `phone_numbers` then my app works fine.

Error:
```text
    if issubclass(parameter_type, KernelBaseModel):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 123, in __subclasscheck__
TypeError: issubclass() arg 1 must be a class
```

The problem is in the `KernelJsonSchemaBuilder`. The `issubclass` method is called with `list[str]`, which is not a class

This line:
`if issubclass(parameter_type, KernelBaseModel):`

should be replaced with:
`if isinstance(parameter_type, KernelBaseModel):`

**To Reproduce**
Described above.

**Expected behavior**
Described above.

**Screenshots**
NA

**Platform**
 - OS: [Mac]
 - IDE: [VS Code]
 - Language: [Python]
 - Source: [v1.0.2]

**Additional context**
NA

**Comment by moonbox3** [comment]
@q-stefanmuscalu Good find, thank you. We appreciate your help. Will have a PR out for this soon.
