### ISSUE TITLE
.Net: Planners fallback function?

### ISSUE THREAD

**Issue by luismanez** [microsoft/semantic-kernel#6395]
Is there any way to configure a Planner to execute a function/helper if is not able to find any other function that suits better? In other words, what I'd like to have is an option to tell planner "if you don't find any better function, just pass the query to the LLM".

Imagine I have 2 plugins added to a planner: GetRandomNumber and SendEmail. If user's goal is "write an email to my boss about xyz", then the planner will call SendEmail plugin. However, if the query is "Translate this sentence to spanish", as there's no Plugin suitable, I want to call the chat endpoint.

I've tried this, but works only sometimes:

```csharp
var planner = new HandlebarsPlanner(
            new HandlebarsPlannerOptions()
            {
                AllowLoops = true,
                GetAdditionalPromptContext = () => Task.FromResult("If you cannot find any better helper to achieve user's goal, just call the LLM")
            });
```

I've read about ```CreatePlanPromptHandler``` but I don't think is what I need.

Thanks.

**Comment by dmytrostruk** [comment]
@luismanez Have you considered function calling functionality instead of planner? I tested your scenario and it works as expected:
```csharp
public class Program
{
    public static async Task Main(string[] args)
    {
        var kernel = Kernel
            .CreateBuilder()
            .AddOpenAIChatCompletion("gpt-4", "<api_key>")
            .Build();

        kernel.ImportPluginFromType<Program>();

        var settings = new OpenAIPromptExecutionSettings
        {
            ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions
        };

        Console.WriteLine(await kernel.InvokePromptAsync(Console.ReadLine()!, new(settings)));
    }

    [KernelFunction]
    public static int GetRandomNumber() => new Random().Next(0, 100);

    [KernelFunction]
    public static void SendEmail() => Console.WriteLine("SendEmail function was executed.");
}
```

With this code, you will always send a request to LLM, and in some cases it will respond with information about function to call, but if there is no suitable plugin/function imported, it will just provide plain response based on user ask. Please let me know if this covers your scenario. Thanks!

**Comment by luismanez** [comment]
Thanks @dmytrostruk 
That's a valid point. However, you need "extra code" to call the function if the model says so. Also, another advantage of the Planners, is that it can manage multiple steps "in one query/goal" (imagine the goal is: get the revenue of this month, create a bar chart report and send it to the Business development team). 

I'd like to have just a planner, so if my goal is achievable combining multiple custom skills, Planner will solve it, otherwise, just ask the model.

**Comment by dmytrostruk** [comment]
> That's a valid point. However, you need "extra code" to call the function if the model says so.

@luismanez In the code I shared above, the function will be called automatically, if the model says so, no "extra code" is required, unless you use custom chat completion service. But if you use OpenAI, Google Gemini or Mistral connectors, function calling should be performed automatically.

> Also, another advantage of the Planners, is that it can manage multiple steps "in one query/goal" (imagine the goal is: get the revenue of this month, create a bar chart report and send it to the Business development team).

Same here, multiple steps are supported in function calling functionality. Basically, we have a loop, which will call LLM, call functions, send results to LLM and repeat that until the goal will be reached:
https://github.com/microsoft/semantic-kernel/blob/65515468f8aba286ed012d0407e8b56b877e2a14/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L389

> I'd like to have just a planner, so if my goal is achievable combining multiple custom skills, Planner will solve it, otherwise, just ask the model.

You can use a planner, but based on our tests, function calling functionality works more reliable. We also have some additional features for automatic function calling like Filters, which allow you to control execution process, observe function arguments, result, terminate an execution if needed etc. 

I highly recommend exploring auto function calling in more detail, and if you see something, that can be achieved with Planner, but not auto function calling, just let us know and we will try to handle that case. But based on your problem description, it looks like it should be achievable with function calling with small amount of code.

**Comment by luismanez** [comment]
Sounds really interesting. I'll give it a try and let you know if I find something I can't do with auto-function (I'm preparing a session for a community event about SK and KM).
Thanks a lot for your help!
