### ISSUE TITLE
Python: Prompt execution settings are not loaded correctly from `config.json` when settings are created manually

### ISSUE THREAD

**Issue by mku-wedoai** [microsoft/semantic-kernel#6398]
**Describe the bug**

I have the following code snippet:
```
class CustomTextPromptExecutionSettings(PromptExecutionSettings):
    options: Optional[Dict[str, Any]] = None

kernel = sk.Kernel()

kernel.add_service(CustomTextCompletion())

kernel.add_plugin(parent_directory=PLUGINS_DIRECTORY, plugin_name="custom_plugin")

prompt_exec_settings = kernel.get_prompt_execution_settings_from_service_id("default") // CustomTextCompletion is defined as "default" service

prompt_exec_settings.options = {"one": 1}

kernel_args = KernelArguments(settings=prompt_exec_settings , subject="aaa", content="bbb")
result = await kernel.invoke(plugin_name="custom_plugin", function_name="suggest_stuff", arguments=kernel_args)
```

When execution reaches `get_text_contents` function from `CustomTextCompletion` service, the object of type `CustomTextPromptExecutionSettings` which is passed to that function does not contain parameters of function from `custom plugin` from `config.js file` in the `extension_data` field. Instead, `extension_data` contains property 'options': {'one': 1}.

**Expected behavior**
In the case above, settings passed to `get_text_contents`  should contain  `extension_data` field populated with plugin's function `config.json` content and `options` should be passed as they were defined.

**Platform**
 - OS: Windows 11 PRO
 - IDE: VS Code 1.89.1
 - Language: Python 3.11
 - Source:  pip package version 1.0.2,

**Comment by eavanvalkenburg** [comment]
Does your custom completion class override the `get_prompt_execution_settings_class` method?

**Comment by mku-wedoai** [comment]
> Does your custom completion class override the `get_prompt_execution_settings_class` method?

Yes, I did override the `get_prompt_execution_settings_class` method.

**Comment by mku-wedoai** [comment]
@eavanvalkenburg I went through the code with the help of the debugger as you suggested and I've found that if execution settings are provided for a service in `KernelArguments` then they will not be overwritten by the execution settings that have been read from the `config.json` of plugin function that has been called.

C# version of the `ai_service_selector` behaves in the same way.

**Comment by eavanvalkenburg** [comment]
ok, and there are execution settings in the function definition in your case? It might be good then to create your own service selector and add that to your kernel where the behavior is different!

**Comment by eavanvalkenburg** [comment]
@mku-wedoai have you been able to get it working the way you want?

**Comment by mku-wedoai** [comment]
@eavanvalkenburg Yes, I wrote my own `AiServiceSelector` which merges the extension data of execution settings from `KernelArguments` and 'KernelFunction'.
