### ISSUE TITLE
.Net: Running Semantic Kernel light switch plugin sample is not working with the OLLAMA with Phi3

### ISSUE THREAD

**Issue by dmytrostruk** [microsoft/semantic-kernel#6399]
### Discussed in https://github.com/microsoft/semantic-kernel/discussions/6397

<div type='discussions-op-text'>

<sup>Originally posted by **madhub** May 26, 2024</sup>
I am trying to see whether Semantic Kernel with light switch plugin sample works with OLLAMA with Phi3.
Ollama is running on **http://127.0.0.1:11434**
```shell
ollama.exe run phi3
```
![image](https://github.com/microsoft/semantic-kernel/assets/8907962/b82ef2cb-0ab2-477d-bd65-105d8dfe0009)

Uses `AddOpenAIChatCompletion("phi3", new Uri("http://127.0.0.1:11434"),"apikey");`

Here is the sample code
```csharp
// See https://aka.ms/new-console-template for more information
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.ChatCompletion;
using Microsoft.SemanticKernel.Connectors.OpenAI;
using SemanticPluginDemo;
using System.Net;

using var loggerFactory = LoggerFactory.Create(builder =>
{
    // Add OpenTelemetry as a logging provider
    builder.AddConsole();
    builder.SetMinimumLevel(LogLevel.Warning);
});

#pragma warning disable SKEXP0010 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
var builder = Kernel.CreateBuilder()
                    .AddOpenAIChatCompletion("phi3", new Uri("http://127.0.0.1:11434"),"apikey");
#pragma warning restore SKEXP0010 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
builder.Plugins.AddFromType<LightPlugin>();
builder.Services.AddLogging(c => c.AddDebug().SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace));
Kernel kernel = builder.Build();


// Create chat history
var history = new ChatHistory();

// Get chat completion service
var chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();

// Start the conversation
Console.Write("User > ");
string? userInput;
while ((userInput = Console.ReadLine()) != null)
{
    // Add user input
    history.AddUserMessage(userInput);

    // Enable auto function calling
    OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
    {
        ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions
    };

    // Get the response from the AI
    var result = await chatCompletionService.GetChatMessageContentAsync(
        history,
        executionSettings: openAIPromptExecutionSettings,
        kernel: kernel);

    // Print the results
    Console.WriteLine("Assistant > " + result);

    // Add the message from the agent to the chat history
    history.AddMessage(result.Role, result.Content ?? string.Empty);

    // Get user input again
    Console.Write("User > ");
}



using Microsoft.SemanticKernel;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SemanticPluginDemo;
public class LightPlugin
{
    public bool IsOn { get; set; } = false;

#pragma warning disable CA1024 // Use properties where appropriate
    [KernelFunction]
    [Description("Gets the state of the light.")]
    public string GetState() => IsOn ? "on" : "off";
#pragma warning restore CA1024 // Use properties where appropriate

    [KernelFunction]
    [Description("Changes the state of the light.'")]
    public string ChangeState(bool newState)
    {
        this.IsOn = newState;
        var state = GetState();

        // Print the state to the console
        Console.WriteLine($"[Light is now {state}]");

        return state;
    }
}
```
![image](https://github.com/microsoft/semantic-kernel/assets/8907962/a9086a84-b2b1-47c2-88dc-35dd9d98b03f)
</div>

**Comment by madhub** [comment]
> Does Phi-3 support function calling?

I don't know, I assumed it supports. Is there way to find out ?

Is llama3, mistrel or Gemma models support this capability ?

**Comment by dmytrostruk** [comment]
@madhub Our connectors (OpenAI, Mistral, Gemini) support function calling functionality, but not each model from specific AI provider supports it. You need to check official documentation from AI provider about concrete model you would like to use and its capabilities.

It looks like Phi-3 doesn't support function calling out-of-the-box. Although, I think it's possible to fine-tune it to support that. 

For light switch plugin sample, we recommend using AI model that supports function calling out-of-the-box for quick onboarding. 

Here is a list of available models, their features and available regions in Azure OpenAI:
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models

I'm going to close this issue, since it's not related to light switch plugin. Feel free to open a new one in case you see any other issues. Thank you!

**Comment by madhub** [comment]
> @madhub Our connectors (OpenAI, Mistral, Gemini) support function calling functionality, but not each model from specific AI provider supports it. You need to check official documentation from AI provider about concrete model you would like to use and its capabilities.
> 
> It looks like Phi-3 doesn't support function calling out-of-the-box. Although, I think it's possible to fine-tune it to support that. 
> 
> For light switch plugin sample, we recommend using AI model that supports function calling out-of-the-box for quick onboarding. 
> 
> Here is a list of available models, their features and available regions in Azure OpenAI:
> https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models
> 
> I'm going to close this issue, since it's not related to light switch plugin. Feel free to open a new one in case you see any other issues. Thank you!

I am looking for the model that can be hosted/ ran locally for function calling,. Links provided are cloud hosted.

**Comment by dmytrostruk** [comment]
> I am looking for the model that can be hosted/ ran locally for function calling,. Links provided are cloud hosted.

@madhub Since you are using Ollama, I can see that `mistral` supports function calling. Could you try to use this model and see if function calling works as expected?
https://ollama.com/library/mistral
![image](https://github.com/microsoft/semantic-kernel/assets/13853051/6dd2c0f2-9dc6-43e9-b990-9b9fae044b3e)

**Comment by madhub** [comment]
> > I am looking for the model that can be hosted/ ran locally for function calling,. Links provided are cloud hosted.
> 
> @madhub Since you are using Ollama, I can see that `mistral` supports function calling. Could you try to use this model and see if function calling works as expected? https://ollama.com/library/mistral ![image](https://private-user-images.githubusercontent.com/13853051/335257038-6dd2c0f2-9dc6-43e9-b990-9b9fae044b3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzczMjYsIm5iZiI6MTcxNzE3NzAyNiwicGF0aCI6Ii8xMzg1MzA1MS8zMzUyNTcwMzgtNmRkMmMwZjItOWRjNi00M2U5LWI5OTAtOWI5ZmFlMDQ0YjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE3MzcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwOTQxNmNiNjZjMmU1NzA3YjkyMTVjNTE2NzRjYjEyZjdkYWZkN2RlNWU3MWQ5ZTgwMGI4YzY0NmIwNWYwNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VyDVuuMWaXcp8dEdUrCqLPEz0v0HFwq6K8Cxl6Kq5LU)

I have tried, it does not work
![image](https://github.com/microsoft/semantic-kernel/assets/8907962/6b4c6f7a-c62b-4e2f-9587-74c2f0a807ab)



![image](https://github.com/microsoft/semantic-kernel/assets/8907962/5941043c-78bd-453a-8a1b-6278ed4c96f9)

**Comment by vgibilmanno** [comment]
@madhub have a look at this project https://github.com/Jenscaasen/UniversalLLMFunctionCaller. Through prompt templating it tries to mimic native function calling. I tried with ollama and phi3 mini, llama3 and it worked pretty well.

**Comment by madhub** [comment]
> @madhub have a look at this project https://github.com/Jenscaasen/UniversalLLMFunctionCaller. Through prompt templating it tries to mimic native function calling. I tried with ollama and phi3 mini, llama3 and it worked pretty well.

Ok thanks
