### ISSUE TITLE
Python: 'Kernel' object has no attribute 'import_native_plugin_from_directory'

### ISSUE THREAD

**Issue by kuljotSB** [microsoft/semantic-kernel#6400]
I am trying to make use of native functions in semantic kernel into my code and am using the 1.0.2 version of the semantic kernel SDK.
```
import asyncio
import os
from dotenv import load_dotenv
from semantic_kernel.connectors.ai.open_ai import AzureChatCompletion
from semantic_kernel import Kernel
kernel = Kernel()
load_dotenv()

service_id = "default"
kernel.add_service(
    AzureChatCompletion(service_id=service_id,
                        api_key=os.getenv("AZURE_OPENAI_API_KEY"),
                        deployment_name=os.getenv("AZURE_OPENAI_CHAT_COMPLETION_MODEL"),
                        endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
    )
)

math_plugin = kernel.import_native_plugin_from_directory("../plugins/native_plugins/", "mathPlugin")

sqrt_function = math_plugin["Sqrt"]

async def square_root():
    return await kernel.invoke(sqrt_function, number1=4 )

print(asyncio.run(square_root()))
```
![vs](https://github.com/microsoft/semantic-kernel/assets/147621230/19409e97-479d-42b5-87a9-94c4444b6440)

but whenever I run the file, it gives me the following error:
**AttributeError: 'Kernel' object has no attribute 'import_native_plugin_from_directory'**

**Comment by eavanvalkenburg** [comment]
that is old syntax, replaced with `add_plugin`. Where is this script coming from?

**Comment by eavanvalkenburg** [comment]
you need to use named args, something like `parent_directory="../plugins/native_plugins/", plugin_name="mathPlugin"`

**Comment by moonbox3** [comment]
The solution -- using named args for the `add_plugin` method -- has been provided. Closing this issue.
