### ISSUE TITLE
.Net: Terminate auto function invocation with streaming does not return last function response

### ISSUE THREAD

**Issue by AssafYo** [microsoft/semantic-kernel#6404]
When calling termination of automatic function invocation, we've noticed an inconsistency between the results of GetChatMessageContentAsync and GetStreamingChatMessageContentsAsync.
GetChatMessageContentAsync is functioning as expected and returns the last function call result. However, GetStreamingChatMessageContentsAsync does not include the last function call result in its response.

You could consider adding something like: 

"yield return new OpenAIStreamingChatMessageContent(chat.Last().Role, chat.Last().Content);" 

before the:
"yield break;" 

https://github.com/microsoft/semantic-kernel/blob/65515468f8aba286ed012d0407e8b56b877e2a14/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L870

**Comment by markwallace-microsoft** [comment]
We need to ensure this behaviour is consistent across Google and Mistral connectors also

**Comment by HillaPeter** [comment]
@SergeyMenshykh can u update when you will release a new version with this fix?

**Comment by SergeyMenshykh** [comment]
Hi @HillaPeter, we plan to create a new release early next week.

**Comment by SergeyMenshykh** [comment]
Hi @HillaPeter, the fix has been released and available in the latest version of SK - https://www.nuget.org/packages/Microsoft.SemanticKernel/1.14.0
