### ISSUE TITLE
Java: Return response from OpenAPI functions differ between Python and .NET

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6429]
In .NET, responses from OpenAPI functions get wrapped in a `RestApiOperationResponse` object. This does not happen in Python or Java. Because of this, the behavior between the languages differs.

There should be a test to validate that the responses from OpenAPI function are identical and a proposal should be provided to align the two SDKs.

**Comment by moonbox3** [comment]
Java repo moved, will check if this is still the case.
