### ISSUE TITLE
.Net: `GetTextContentAsync` extension method expects single output from `textGenerationService.GetTextContentsAsync`.

### ISSUE THREAD

**Issue by mku-wedoai** [microsoft/semantic-kernel#6434]
**Describe the bug**
`GetTextContentAsync` extension method expects single output from `textGenerationService.GetTextContentsAsync`.

See https://github.com/microsoft/semantic-kernel/blob/246b84357ff6e0415fe5cb7fd97b622fb9bc9032/dotnet/src/SemanticKernel.Abstractions/AI/TextGeneration/TextGenerationExtensions.cs#L34

I think that the `Single()` is not necessary here. Also, Python version of SK allows returning multiple instances of `TextContent` from `get_text_contents` method.

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio 17.10.0
 - Language: C#
 - Source: NuGet package version 1.13.0

**Comment by OrellBuehler** [comment]
The same would apply for the `GetChatMessageContentAsync` in the `ChatCompletionServiceExtensions`:

https://github.com/microsoft/semantic-kernel/blob/02145d9705fa1dbcc03330b0a2ea3ee112852d28/dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatCompletionServiceExtensions.cs#L57

Also the return type description does not fit the actual return type:

https://github.com/microsoft/semantic-kernel/blob/246b84357ff6e0415fe5cb7fd97b622fb9bc9032/dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatCompletionServiceExtensions.cs#L56

**Comment by mku-wedoai** [comment]
@markwallace-microsoft I would like to kindly ask if there is any possibility of prioritising this issue?

**Comment by dmytrostruk** [comment]
Hi @mku-wedoai , here is PR: https://github.com/microsoft/semantic-kernel/pull/6590

**Comment by mku-wedoai** [comment]
Hey @dmytrostruk, thank you for the contribution! 

I have a question - after your change extension methods still return one element. I think that the solution would be to return all generated elements. `ITextGenerationService` allows to return multiple instances of `TextContent` from `GetTextContentsAsync`, so why somewhere in the SK code these results are cut to a single element?

**Comment by mku-wedoai** [comment]
@dmytrostruk No worries :) Yes, in the big picture I'd like `kernel.InvokeAsync` to return multiple values.
