### ISSUE TITLE
Is there any way to define the system/user/assistant messages in the prompt file with the `OpenAIChatCompletion`, but not call the `add_system_message`/`add_user_message`/`add_assistant_message` in code?

### ISSUE THREAD

**Issue by littleGnAl** [microsoft/semantic-kernel#644]
Is there any way to define the system/user/assistant messages in the prompt file with the `OpenAIChatCompletion`, but not call the `add_system_message`/`add_user_message`/`add_assistant_message` in code?

**Comment by whosthatguylol** [comment]
Hey, any update? :(

**Comment by sbaidachni** [comment]
+1

We are working at a project where this feature is very important. If you have a mature MLOps process, you will need to host system message/prompts separately from code. add_system_message doesn't allow me to do that.

**Comment by vJenny** [comment]
+1 

I'm curious why the experience working with Text Completions and Chat Completions isn't consistent across the framework. Seems like it's a very helpful tool for prompt experimentation and versioning. Also given that OpenAI is moving from text completions to chat completions
 (https://openai.com/blog/gpt-4-api-general-availability), this feature makes a lot of sense to me.

**Comment by lemillermicrosoft** [comment]
Related to #2068

**Comment by nacharya1** [comment]
@RogerBarreto: can you look into this during this current sprint
