### ISSUE TITLE
.Net Will SK(Current 1.13.0) support the use of local image/file data in GPT4T/O in the future?

### ISSUE THREAD

**Issue by strikene** [microsoft/semantic-kernel#6443]
It seems that the AzureOpenAi SDK already supports local data uploads.
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/README.md#chat-with-images-using-gpt-4-turbo

In sk 1.13.0 .I tried the following code  Azure.AI.OpenAI(1.0.0-beta.15,1.0.0-beta.16)

        var fs = System.IO.File.ReadAllBytes(@"C:\Pictures\Screenshots\Screenshot 2024-05-30 114500.png");

        chatHistory.AddUserMessage(
        [
            new TextContent("What’s in this image?"),
            new ImageContent(data: new ReadOnlyMemory<byte>(  fs) ) ,
        ]);

        var reply = await chatCompletionService.GetChatMessageContentAsync(chatHistory);

I got error 
![image](https://github.com/microsoft/semantic-kernel/assets/62022463/f9eb23fc-7fc8-4338-9ff9-36dfe04a7df8)

In sk 1.13.0 . Azure.AI.OpenAI(1.0.0-beta.17)
![image](https://github.com/microsoft/semantic-kernel/assets/62022463/ead30498-a22c-4ea0-af10-73e346ddd3e6)

**Comment by mihail-vladov** [comment]
@dmytrostruk  Thank you for the fast implementation. I saw that the PR is approved. When can we expect an update on the nuget? preview or beta version is also OK for us.

**Comment by dmytrostruk** [comment]
> When can we expect an update on the nuget? preview or beta version is also OK for us.

@mihail-vladov I think we will do next release to NuGet next week. But we are doing nightly builds on GitHub, and the build with this fix will be available today.

Here is information how to access nightly builds:
https://github.com/microsoft/semantic-kernel/blob/main/docs/FAQS.md

**Comment by dmytrostruk** [comment]
@mihail-vladov Here is a link to nightly build with fix: 
https://github.com/microsoft/semantic-kernel/pkgs/nuget/Microsoft.SemanticKernel/223654454

**Comment by mihail-vladov** [comment]
Thank you Dmytro.

**Comment by yeungxh** [comment]
why i still get the error when using 1.15.1

**Comment by yeungxh** [comment]
chatHistory.AddAssistantMessage("Please extract and summarize the image content user uploaded");
 byte[] fileBytes = System.IO.File.ReadAllBytes(@"C:\Other\Web capture_17-1-2024_13147_wow.hkexpress.com.jpeg");



 var chatMsg = new ChatMessageContentItemCollection
 {
     new ImageContent(data: new ReadOnlyMemory<byte>(fileBytes), "image/jpeg")
 };

 chatHistory.AddUserMessage(chatMsg);

 var chatMessageContents = await chat.GetChatMessageContentsAsync(chatHistory);
