### ISSUE TITLE
.Net: Cannot specify apiVersion on AzureOpenAIChatCompletion 

### ISSUE THREAD

**Issue by MitaWinata** [microsoft/semantic-kernel#6446]
If i am not mistaken , currently apiService is not yet open as a param yet in AzureOpenAIChatCompletion.

In AzureOpenAIChatCompletionService.cs
```c#
    public AzureOpenAIChatCompletionService(
        string deploymentName,
        string endpoint,
        string apiKey,
        string? modelId = null,
        HttpClient? httpClient = null,
        ILoggerFactory? loggerFactory = null)
    {
        this._core = new(deploymentName, endpoint, apiKey, httpClient, loggerFactory?.CreateLogger(typeof(AzureOpenAIChatCompletionService)));

        this._core.AddAttribute(AIServiceExtensions.ModelIdKey, modelId);
    }
```
or in OpenAIServiceCollectionExtensions,cs

``` c#
  public static IKernelBuilder AddAzureOpenAIChatCompletion(
      this IKernelBuilder builder,
      string deploymentName,
      string endpoint,
      string apiKey,
      string? serviceId = null,
      string? modelId = null,
      HttpClient? httpClient = null)
  {
...
}
```

We would like to be able to specify which version of the api we want to use. 
```
        public AzureOpenAIChatCompletionService(
        string deploymentName,
        string endpoint,
        string apiKey,
        string? modelId = null,
        **string? apiVersion= null,**
        HttpClient? httpClient = null,
        ILoggerFactory? loggerFactory = null)
    {
        this._core = new(deploymentName, endpoint, apiKey, httpClient, loggerFactory?.CreateLogger(typeof(AzureOpenAIChatCompletionService)));

        this._core.AddAttribute(AIServiceExtensions.ModelIdKey, modelId);

       **this._core.AddAttribute(AIServiceExtensions.ApiVersionKey, apiVersion);**
    }
```
and 

```
 public static IKernelBuilder AddAzureOpenAIChatCompletion(
      this IKernelBuilder builder,
      string deploymentName,
      string endpoint,
      string apiKey,
      string? serviceId = null,
      string? modelId = null,
     **string? apiVersion = null,**
      HttpClient? httpClient = null)
  {
...
}
```

**Comment by dmytrostruk** [comment]
@MitaWinata Thanks for reporting this issue!

Since the number of possible parameters is growing, I would probably handle this issue after we introduce `Options` classes for service classes and extension methods: https://github.com/microsoft/semantic-kernel/issues/6081

**Comment by MitaWinata** [comment]
Thanks @dmytrostruk for replying. 
Is there any ETA on when this will be introduced?

**Comment by dmytrostruk** [comment]
@MitaWinata `Options` classes are not prioritized at the moment, but we will try to resolve it in upcoming weeks. After this, it should be relatively easy to add new `ApiVersion` property.

In theory, you should be able to specify API version today in different way, by providing your own `HttpClient` in `AzureOpenAIChatCompletionService` constructor/extension method. Since API version is a query parameter (e.g. `/completions?api-version=2024-02-01`), you can try to modify request URL by adding API version to it. Would it be possible for you to test this approach and see if it works?

**Comment by dmytrostruk** [comment]
Closing this issue, since this functionality was recently added:
https://github.com/microsoft/semantic-kernel/blob/d63de9032c8f31b19955e3139584f44930ae5f85/dotnet/samples/Concepts/ChatCompletion/OpenAI_StructuredOutputs.cs#L203-L209
