### ISSUE TITLE
Support Managed Identity for AzureOpenAI and AI Search

### ISSUE THREAD

**Issue by nhandangms** [microsoft/semantic-kernel#6452]
Hi Team,

Our AI service is using Semantic Kernel (SK) for retrieval part with Azure Cognitive Search (AI Search) memory and for generation part with AzureOpenAI. We are going to move from authentication using access key to managed identity as soon as possible.

Have SK support Managed Identity Authentication for AI Search and AzureOpenAI yet? If yes, can we get more details on how to set it up, please? If not, can we get some ETA plan on when this feature can be delivered, please?

Thank you, 
Nhan Dang

**Comment by dmytrostruk** [comment]
@nhandangms Both `AzureOpenAIChatCompletionService` and `AzureAISearchMemoryStore` accept `TokenCredential` as constructor parameter. All auth information is passed to underlying Azure .NET SDK:
https://github.com/Azure/azure-sdk-for-net/tree/49b0ace48d35cb4b2ace93b517036b660fc12ca4/sdk/openai/Azure.AI.OpenAI#create-openaiclient-with-an-azure-active-directory-credential

With `TokenCredential` parameter, you can use different authentication methods, including [ManagedIdentityCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential). 

Here is a full list of them:
https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication/?tabs=command-line#exploring-the-sequence-of-defaultazurecredential-authentication-methods

Let me know if that helps. Thank you!

**Comment by nhandangms** [comment]
Great, thank you so much for your prompt reply.

**Comment by dluc** [comment]
@nhandangms the AI Search connector supports Managed Identities too, using the same approach. Here's the ctor signature, where you can pass in a `new DefaultAzureCredential()`:

```csharp
public AzureAISearchMemoryStore(string endpoint, TokenCredential credentials)
        : this(new SearchIndexClient(new Uri(endpoint), credentials, GetClientOptions()))
    {
    }
```
