### ISSUE TITLE
.Net Unnecesary kernel verbosity in GetChatMessageContentAsync :)

### ISSUE THREAD

**Issue by joslat** [microsoft/semantic-kernel#6468]
**Describe the bug**
When I get the chatService from a kernel, why do I need to specify again the kernel when using it? 
IMHO it should use the kernel it is bound to (was generated from it) by default.

**To Reproduce**
Create a new .net console app, add the following code:
```
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.ChatCompletion;
using Microsoft.SemanticKernel.Connectors.OpenAI;

Console.WriteLine("Hello, Semantic Kernel!");

var modelDeploymentName = "gpt-4o";
var azureOpenAIEndpoint = Environment.GetEnvironmentVariable("AZUREOPENAI_ENDPOINT");
var azureOpenAIApiKey = Environment.GetEnvironmentVariable("AZUREOPENAI_APIKEY");

Kernel kernel = Kernel.CreateBuilder()
    .AddAzureOpenAIChatCompletion(
        modelDeploymentName,
        azureOpenAIEndpoint,
        azureOpenAIApiKey)
    .Build();
kernel.ImportPluginFromType<WhatDateIsIt>();

var chatService = kernel.GetRequiredService<IChatCompletionService>();
ChatHistory chatHistory = new();

var executionSettings = new OpenAIPromptExecutionSettings
{
    ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions
};


bool exitnow = false;
while (exitnow == false)
{
    Console.WriteLine("Enter your question or type 'exit' to quit:");
    var userInput = Console.ReadLine();
    chatHistory.AddUserMessage(userInput);

    var response = await chatService.GetChatMessageContentAsync(
        chatHistory, 
        executionSettings);
    
    Console.WriteLine(response.ToString());
    chatHistory.Add(response);
}

public class WhatDateIsIt
{
    [KernelFunction, Description("Get the current UTC date")]
    public string Date(IFormatProvider? formatProvider = null) =>
        DateTimeOffset.UtcNow.ToString("D", formatProvider);
}
```

**Expected behavior**
I would like that it does use function calling properly, but it cannot.

For this to happen you have to specify the kernel when the ChatCompletionService is used, when it was created from that same kernel. It's like telling it every single time who his "father" is ;)

For this to work I should use:
```
    var response = await chatService.GetChatMessageContentAsync(
        chatHistory, 
        executionSettings,
        kernel);
```

**Screenshots**
N/A

**Platform**
Anywhere

**Additional context**

**Comment by tyler-suard-parker** [comment]
I made a comment too about unnecessary verbosity.

**Comment by markwallace-microsoft** [comment]
> When I get the chatService from a kernel, why do I need to specify again the kernel when using it?
> IMHO it should use the kernel it is bound to (was generated from it) by default.

@joslat 
Our thinking is that the lifecycle of an AI service and a Kernel instance are typically different. E.g. I may instantiate an AI service to be used for the duration of my application whereas the Kernel instance may live for the duration of a request (with the AI service being injected into it). 

We previously had the AI service and Kernel linked and this provided problematic because of the different lifecycles so we changed the behaviour. We find the current pattern works well when using DI. 

We may need a Blog post for this, let me chat with the team. Thanks for the feedback.

**Comment by joslat** [comment]
I always think of it as the HttpClient, due to my experience bias ;) https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines
whereas the client is the same I expect each request to hand over a "connection" from the pool to avoid resource exhaustion...
I understand that when you refer to an AI service you mean a connection to it, right? in this case I fully agree, a connection should be made for a single request and then disposed/cleaned and recycled into the connection pool...

When I think on the Kernel I have an abstract idea of having an HttpClient on it with its IHttpClientFactory that can deliver connections, which a new one will be instantiated per request.

Unless a connection instance is bound to the kernel, but this migth be an issue/antipattern IMHO.
