### ISSUE TITLE
Python: Poor Naming Conventions

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/semantic-kernel#6474]
**Describe the bug**
Names used throughout the program are not very user-friendly.

Only 1.3% of the US workforce is software developers.  Of that 1.3%, I would wager about half know what a system kernel is.  Because only 0.65% of the US population understands the concept of a kernel, and your repo is meant for users who understand what a kernel is, this repo would be difficult to use for all but 0.65% of the US population.  It is, in my opinion, not a very good idea to base your program on an analogy that users will have to take an online course to understand. 
 
Also, there is some verbose, unnecessary syntax for some things that could be much simpler.  For example:

from semantic_kernel.core_plugins.text_plugin import TextPlugin
txt = kernel.import_plugin_from_object(TextPlugin(), "MyPlugin")

Reading it out, it says:
from semantic kernel dot core plugins dot text plugin import text plugin,
which is a mouthful and hard to read, and a little bit confusing.  It adds unnecessary cognitive load to the reader.

It could be simplified like this:

from semantic_kernel import TextPlugin
txt = TextPlugin("MyPlugin")

I know you have your code organized in a certain way, but the user doesn't really need to know about the organization of your code, just how to use it.  I hope you take my feedback as constructive criticism, I really would like to see your repo succeed, but I find it difficult to understand and use.

**Comment by moonbox3** [comment]
Hi @tyler-suard-parker,

Thank you for taking the time to provide feedback on our repository. We appreciate your interest and your desire to see our project succeed.

I'd like to address a couple of points you raised to help clarify our approach and design decisions:

- **Understanding of a Kernel**: While it's true that the term "kernel" might not be universally understood, our project [documentation and resources](https://learn.microsoft.com/en-us/semantic-kernel/overview/?tabs=Csharp) are designed to help bridge that knowledge gap. We aim to make our tools accessible, but some foundational understanding of certain concepts is necessary for effective use. However, we'll consider adding more introductory material to help new users get up to speed more quickly.

- **Import Statements**: The import statement you mentioned (`from semantic_kernel.core_plugins.text_plugin import TextPlugin`) is structured this way to reflect the organization of our codebase. This organization helps maintain a clean and modular structure, making it easier to manage and extend the code. Here’s why we use this approach:
  - Clarity and Maintainability: By specifying the full path, it's clear where each component resides within the project. This helps in large projects where similar names might be used in different contexts.
  - Namespace Management: Python’s import system relies on module paths to avoid conflicts and ensure the correct modules are used. This explicit pathing helps prevent issues that could arise from more ambiguous imports.
Your suggestion for simplification (from semantic_kernel import TextPlugin) could indeed make the code more concise. However, it assumes that TextPlugin is defined directly in semantic_kernel, which isn’t the case in our structure. We’ll consider ways to improve our import paths if we can maintain clarity and avoid conflicts.

- **Cognitive Load**: We understand that long import statements can seem verbose, but they are intended to improve readability and manageability in the long term, especially for users who work extensively with our library. We strive to balance simplicity with clarity and maintainability.

Your feedback is invaluable to us, and we'll take it into consideration as we continue to improve the project. If you have any other specific suggestions or need further clarification, please feel free to reach out.

P.S. Please also note that if you're referring to our v1.0.0+ code, you won't find the convention `txt = kernel.import_plugin_from_object(TextPlugin(), "MyPlugin")` present. We've simplified it to be `kernel.add_plugin(plugin_name="MyPlugin", plugin=TextPlugin())`. We're currently working on fixing old learn resources/documentation so if you found the old way of doing it somewhere, we apologize for the confusion. We recommend having a look at our notebooks and concept samples for the most up-to-date code.

**Comment by eavanvalkenburg** [comment]
To add to this, we've decided in a pattern where the only level 1 import `from semantic_kernel import...` is Kernel itself. The rest can mostly be imported at level 2, such as `from semantic_kernel.functions import kernel_function` or `from semantic_kernel.core_plugins import TextMemoryPlugin`, and only connectors use one more level such as `from semantic_kernel.connectors.ai import openai`. This is to strike the balance between importing everything, which is bad for performance and deep importing which is annoying for a dev as you point out. I think we have all our samples following this pattern as well, but I'll take a note to document this more.

**Comment by tyler-suard-parker** [comment]
@moonbox3 Thank you for the explanation.  I am glad to hear that your team is prioritizing maintainabilit, and the folder structure makes much more sense now.
