### ISSUE TITLE
"InvalidRequest: The request is not valid, HTTP status: 400" When running Jupiter notebooks

### ISSUE THREAD

**Issue by mkulisic** [microsoft/semantic-kernel#649]
**Describe the bug**
I am trying to get started using sematic kernel but I keep running into the same exception "InvalidRequest: The request is not valid, HTTP status: 400" when running the "00-getting-started.ipynb" notebook for dotnet. 

**To Reproduce**
1. Created a azure openai instance and deployed a model called gpt-4
2. Installed .Net 7 and polyglot as stated by the notebook [00-getting-started.ipynb](https://github.com/microsoft/semantic-kernel/blob/main/samples/notebooks/dotnet/00-getting-started.ipynb)
3. Edited the config/settings.json file to contain my endpoint, model name and key: 
![image](https://user-images.githubusercontent.com/31263950/234417629-b7782d82-eae8-49d7-9a6e-0991644f8870.png)
4. Changed step 2 to use AzureOpenAi 
![image](https://user-images.githubusercontent.com/31263950/234417699-ad002a33-5758-4d51-8e2a-3686f873bdb7.png)
5. Changed the service id in step 3 (unclear if this matters)
![image](https://user-images.githubusercontent.com/31263950/234417808-9763396c-0a47-453e-a08f-71ed24c79a07.png)
6. Ran the code

**Expected behavior**
I would expect this to return an answer using the "Joke" skill the notebook uses, but instead I get an exception. 

**Screenshots**
![image](https://user-images.githubusercontent.com/31263950/234417949-8ddbf2e7-9ffd-4f49-8bef-da4d97bc57c3.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IDE: Visual studio code
 - NuGet Package Version: Microsoft.SemanticKernel, 0.12.207.1-preview"

**Additional context**
I got the same error when I attempted to configure the visual studio code extension as stated in the documentation.

**Comment by ankiga-MSFT** [comment]
I am facing similar issue. The error that I got - 

The chatCompletion operation does not work with the specified model, text-davinci-003. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.
Status: 400 (Bad Request)
ErrorCode: OperationNotSupported

**Comment by mkulisic** [comment]
@ankiga-MSFT You may be running into a different problem than me. I just tested with "text-davinci-003" and with this model I can actually get this to work. Most likely the schema has changed for gpt4 and that is why I couldn't get it to work before. I'll be closing this issue.

**Comment by anandaganesh84** [comment]
I am getting the same issue with gpt-35-turbo
