### ISSUE TITLE
ChatHistory is missing  ChatCompletionsFunctionToolCall and ChatRequestToolMessage

### ISSUE THREAD

**Issue by MalteFries** [microsoft/semantic-kernel#6495]
As the title suggest, it is not possible to add  historic Tool/PluginCalls.
That way the model forgets previous tool calls and their arguments, which results in duplicated queries for plugins.

**Comment by moonbox3** [comment]
Hi @MalteFries, thanks for filing the issue. Are you experiencing trouble in dotnet, Python, or Java?

**Comment by dmytrostruk** [comment]
As for .NET, it should be possible to achieve this scenario with this syntax:
https://github.com/microsoft/semantic-kernel/blob/e9b140721b859db4c22dd4064466a700ed1bd467/dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIToolsTests.cs#L228-L231

**Comment by MalteFries** [comment]
Thanks @dmytrostruk thats what I was looking for :)
