### ISSUE TITLE
Python: Verify that Ollama and LLM Studio work with OpenAI Connector

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#6498]
Ollama and LLM Studio should work with the current OpenAI connector but we need to verify this.

**Comment by moonbox3** [comment]
This is a good opportunity to update our connector to use the Ollama Python SDK, which we aren't using right now.

**Comment by moonbox3** [comment]
https://github.com/ollama/ollama-python

**Comment by TaoChenOSU** [comment]
> This is a good opportunity to update our connector to use the Ollama Python SDK, which we aren't using right now.

Item that tracks the migration: https://github.com/microsoft/semantic-kernel/issues/6841#issue-2363075660
