### ISSUE TITLE
Python: Add Gemini AI Connector

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#6500]

**Comment by mokano51** [comment]
Hello,I'm looking forward to this update.
Will this connector utilize the Vertex AI Gemini API, rather than Google AI?
https://cloud.google.com/vertex-ai/generative-ai/docs/migrate/migrate-google-ai#google-ai

**Comment by TaoChenOSU** [comment]
> Hello,I'm looking forward to this update. Will this connector utilize the Vertex AI Gemini API, rather than Google AI? https://cloud.google.com/vertex-ai/generative-ai/docs/migrate/migrate-google-ai#google-ai

Hello!

Yes, the Vertex AI is a work in progress and should be available soon: https://github.com/microsoft/semantic-kernel/pull/7481
