### ISSUE TITLE
Python: Add Anthropic AI Connector

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#6501]

**Comment by andrewldesousa** [comment]
@alliscode I can pickup this task if it's still free. are you able to assign this ticket to if this currently isn't being worked on?

**Comment by eavanvalkenburg** [comment]
Go for it @andrewldesousa

**Comment by andrewldesousa** [comment]
Cool. @alliscode @eavanvalkenburg I created a draft pull request but have to finalize a few things (https://github.com/microsoft/semantic-kernel/pull/7851). Specifically, I need to make a few adjustments to the streaming functionality and complete the rest of the unit tests.

two quick questions:
- will someone on the SK team be able to configure the Anthropic env variables used by the integration tests?
- Anthropic uses these finish reasons which aren't the same as the finish reasons from OpenAI https://github.com/microsoft/semantic-kernel/pull/7851/files#:~:text=%23%20anthropic%20finish%20reasons,%3D%20%22tool_use%22. any other chat apis that use different finish reasons?

**Comment by moonbox3** [comment]
> Cool. [@alliscode](https://github.com/alliscode) [@eavanvalkenburg](https://github.com/eavanvalkenburg) I created a draft pull request but have to finalize a few things ([#7851](https://github.com/microsoft/semantic-kernel/pull/7851)). Specifically, I need to make a few adjustments to the streaming functionality and complete the rest of the unit tests.
> 
> two quick questions:
> 
> * will someone on the SK team be able to configure the Anthropic env variables used by the integration tests?
> * Anthropic uses these finish reasons which aren't the same as the finish reasons from OpenAI https://github.com/microsoft/semantic-kernel/pull/7851/files#:~:text=%23%20anthropic%20finish%20reasons,%3D%20%22tool_use%22. any other chat apis that use different finish reasons?

We're tracking down an API key to be able to exercise the connector via integration tests.

**Comment by andrewldesousa** [comment]
Thanks, finished the streaming implementation and testing. I've moved the PR to ready for review
