### ISSUE TITLE
.Net: AzureOpenAIChatCompletionWithDataService does not use correct form of request URI for API versions post 2023-12-01 (e.g. 2024-02-15)

### ISSUE THREAD

**Issue by robch** [microsoft/semantic-kernel#6503]
**Describe the bug**
AzureOpenAIChatCompletionWithDataService does not use correct form of request URI for API versions post 2023-12-01 (e.g. 2024-02-15)

**To Reproduce**
1. Run `ai` CLI (in development branch) using `ai dev new sk-chat-streaming-with-data --csharp`
2. Examine source code produced is valid sample following same pattern as `dotnet\samples\Concepts\ChatCompletion\AzureOpenAIWithData_ChatCompletion.cs`
```
var dataConfig = new AzureOpenAIChatCompletionWithDataConfig
{
    CompletionModelId = AZURE_OPENAI_CHAT_DEPLOYMENT!,
    CompletionEndpoint = AZURE_OPENAI_ENDPOINT!,
    CompletionApiKey = AZURE_OPENAI_API_KEY!,
    CompletionApiVersion = AZURE_OPENAI_API_VERSION!,
    DataSourceEndpoint = AZURE_AI_SEARCH_ENDPOINT!,
    DataSourceApiKey = AZURE_AI_SEARCH_KEY!,
    DataSourceIndex = AZURE_AI_SEARCH_INDEX_NAME!
};

// Create a kernel with the Azure OpenAI chat completion service
var builder = Kernel.CreateBuilder();
builder.AddAzureOpenAIChatCompletion(dataConfig);

builder.AddAzureOpenAITextEmbeddingGeneration(
    AZURE_OPENAI_EMBEDDING_DEPLOYMENT,
    AZURE_OPENAI_EMBEDDING_ENDPOINT,
    AZURE_OPENAI_API_KEY!);

var kernel = builder.Build();
```
3. Try running sample once all environment variables are set

**Expected behavior**
It should function as expected, and do an "on your data" look up from the appropriate data via AI Search

**Screenshots**
Instead, it throws an exception:
```
Unhandled exception. Microsoft.SemanticKernel.HttpOperationException: Response status code does not indicate success: 404 (Resource Not Found).
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Resource Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.SemanticKernel.Http.HttpClientExtensions.SendWithSuccessCheckAsync(HttpClient client, HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.SemanticKernel.Http.HttpClientExtensions.SendWithSuccessCheckAsync(HttpClient client, HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Http.HttpClientExtensions.SendWithSuccessCheckAsync(HttpClient client, HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.OpenAI.AzureOpenAIChatCompletionWithDataService.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.OpenAI.AzureOpenAIChatCompletionWithDataService.InternalGetChatStreamingContentsAsync(ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.AzureOpenAIChatCompletionWithDataService.InternalGetChatStreamingContentsAsync(ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
```

**Platform**
 - OS: Windows
 - IDE: VS Code (although, that's irrelevant for this)
 - Language: C#
 - Source: NuGet package 1.13.0

**Additional context**
Contact robch@microsoft.com for further information if needed.

**Comment by dlmotter** [comment]
It also does not format the data sources in the request body properly.

The correct way looks like:
```json
"data_sources": [{
		"parameters": {
			"authentication": {
				"key": "<AI Search API key>",
				"type": "api_key"
			},
			"endpoint": "<AI Search Endpoint>",
			"index_name": "<AI Search Index>",
			"query_type": "simple"
		},
		"type": "azure_search"
	}
]
```

But it is sending the data sources as:

```json
"dataSources": [{
		"type": "AzureCognitiveSearch",
		"parameters": {
			"endpoint": "<AI Search Endpoint>",
			"key": "<AI Search API key>",
			"indexName": "<AI Search Index>"
		}
	}
]
```

Note the snake vs pascal casing, the `type` being wrong, the `parameters` needing an `authentication` child object, etc.

**Comment by dmytrostruk** [comment]
Azure `chat completion with data` functionality had breaking changes, so current `WithData` classes are not compatible. In recent PRs we marked these classes as `Obsolete` in favor of `AzureChatExtensionsOptions` from Azure .NET SDK. Here is usage example:
https://github.com/microsoft/semantic-kernel/blob/e9b140721b859db4c22dd4064466a700ed1bd467/dotnet/samples/Concepts/ChatCompletion/AzureOpenAIWithData_ChatCompletion.cs

**Comment by dlmotter** [comment]
Thanks for the reply. I will get my code ready for the next .NET release of SK that incorporates those changes.

So in the future, it is **not** recommended to add AI Search functionality when building the kernel (in `builder.AddAzureOpenAIChatCompletion`), but rather when invoking it through the `OpenAIPromptExecutionSettings`? Thanks.

**Comment by dmytrostruk** [comment]
>  I will get my code ready for the next .NET release of SK that incorporates those changes.

@dlmotter Just for your information, it's possible to experiment with nightly build, if you want to start doing those changes earlier.
- How to access nightly builds: https://github.com/microsoft/semantic-kernel/blob/main/docs/FAQS.md
- Build with new changes for `with data` functionality: https://github.com/microsoft/semantic-kernel/pkgs/nuget/Microsoft.SemanticKernel/223654454

> So in the future, it is not recommended to add AI Search functionality when building the kernel (in builder.AddAzureOpenAIChatCompletion), but rather when invoking it through the OpenAIPromptExecutionSettings?

That's correct. In the future, we could also expose new AI Search settings through `AddAzureOpenAIChatCompletion` as additional option, but as for now you can use `OpenAIPromptExecutionSettings`.

**Comment by markwallace-microsoft** [comment]
@dmytrostruk Can this be closed?
