### ISSUE TITLE
.Net: Update Cosmos DB Memory Connector to new Memory Design

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#6522]
Memory ADR is here: https://github.com/microsoft/semantic-kernel/issues/5887

- [x] Implement new abstractions
- [x] Unit tests
- [x] Integration tests
- [x] Implement search abstractions
- [x] Add support for generic data model
- [x] Document any limitations in the implementation
- [ ] Implement a basic RAG samples
- [ ] Work with Sofia on a new Blog post
- [ ] Obsolete the old implementation
- [ ] Create task to graduate the Memory Connector

**Comment by dmytrostruk** [comment]
Issues for remaining tasks:
- https://github.com/microsoft/semantic-kernel/issues/9179
- https://github.com/microsoft/semantic-kernel/issues/9180
