### ISSUE TITLE
.Net: Plan for Models As A Service AI Connector

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#6530]
- Create an ADR defining the scope of work
- Create a task breakdown

**Comment by TaoChenOSU** [comment]
Currently supported:
1. Chat Completion
2. Embedding generation

Will be supported:
1. Image generation

May not be supported:
1. Text completion

**Comment by TaoChenOSU** [comment]
Naming of the connector:
1. Azure
2. AzureAI
3. AzureAIInference
4. ...

**Comment by RogerBarreto** [comment]
Tasks created:

- #7957
- #7958
