### ISSUE TITLE
Python: Setting temperature for FunctionCallingStepwisePlanner 

### ISSUE THREAD

**Issue by emilia-szymanska** [microsoft/semantic-kernel#6534]
Hi hi! I am using FunctionCallingStepwisePlanner and I really need the system to be responding in the same way to the same questions. I hoped that setting the temperature to 0 (as I did below) would solve it. However, sometimes I get different plans generated by the planner, even though the question is exactly the same, and the plugins prompts were not changed at all. How can I address it? Thanks in advance for help!

Here is a piece of my code:
```python
kernel = Kernel()
deployment, api_key, endpoint = azure_openai_settings_from_dot_env()
service_id = "default"
kernel.add_service(
    AzureChatCompletion(
       service_id=service_id,
       deployment_name=deployment,
       endpoint=endpoint,
       api_key=api_key,
    ),
)
options = FunctionCallingStepwisePlannerOptions(
    max_iterations=10,
    min_iteration_time_ms=2000,
    max_tokens=10000,
    execution_settings=AzureChatPromptExecutionSettings(temperature=0.0),
)
planner = FunctionCallingStepwisePlanner(
    service_id=service_id,
    options=options,
)
kernel.add_plugin(my_plugin1, plugin_name="plugin1")
kernel.add_plugin(my_plugin2, plugin_name="plugin2")

result = await planner.invoke(kernel, question)
```

**Comment by moonbox3** [comment]
Hi @emilia-szymanska, the settings to create the plan are defined in this [yaml file](https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/planners/function_calling_stepwise_planner/generate_plan.yaml). Are you using this particular yaml file or do you have a custom one? I would expect that if the temp is set to 0.0 for those settings then you should be getting a more deterministic plan.

We are providing guidance to devs that using vanilla function calling can be more stable than using planners -- you can then customize behavior in your app using filters. Once a plan (via the planner) is created, there's no way to interject or change input/output on-the-fly.

**Comment by emilia-szymanska** [comment]
Hi @moonbox3! Thanks for the fast reply. I believe I am using whatever the default for the FunctionCallingStepwisePlanner is, which seems to be the one you linked - I have not specified any yaml file myself. Don't get me wrong, the planner is not randomly calling different plugins each time, but the plans seem to vary if I ran the script a couple of times. 

I don't think I need these on-the-fly changes. I went with the planner as the easiest way to address my application. I am now in the testing phase of my system and I would like to say "My system does its job correctly for X questions out of Y", but now if I run my system again, the plan may change and I get different results, which is why I look for a "stable" solution.

**Comment by moonbox3** [comment]
@matthewbolanos / @markwallace-microsoft do you have any thoughts from the dotnet side of things about how this is handled?

**Comment by matthewbolanos** [comment]
Even if you set the temperature to zero and set the seed, OpenAI does not guarantee that the results will be identical every time. If you do need more deterministic behavior, you likely need to use something like semantic caching to retrieve the previous "answer" and return it exactly as is.
