### ISSUE TITLE
Co-pilot chat sample app fails to invoke createChat call

### ISSUE THREAD

**Issue by ADegitz** [microsoft/semantic-kernel#656]
**Describe the bug**
When the webapp is launched and I log in with my Microsoft account, the createChat call returns a 400 error saying that the "ask" field is required. This is after a clean install and using an OpenAI account. The webpage then displays an error because no data has been returned. As you see in the second screenshot (webapi log), the last call fails with a 400 error when localhost:3000 is refreshed.

**To Reproduce**
1. Start the webapi server and ensure that it has started successfully by navigating to https://localhost:40443/probe
2. Start the webapp
3. Click on "sign in with Microsoft"
4. Enter your credentials and click sign in

**Expected behavior**
I'd expect to see the home page of the chat app.

**Screenshots**
![image](https://user-images.githubusercontent.com/104044172/234429583-c5e270c8-2308-4c5d-9d11-7d93c8da1f6d.png)
![image](https://user-images.githubusercontent.com/104044172/234430195-42a7afd4-f42d-4c38-8a3b-8e1f367683ff.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IDE: Visual Studio 2022

**Additional context**

**Comment by evchaki** [comment]
@ADegitz - can you check your AppID is setup correctly in .env file.  It looks like it is hitting the service, but the auth is failing.  The readme has additional details that might help unblock you.

**Comment by craigomatic** [comment]
Checking back in on this - @ADegitz  if you have a moment would you mind letting us know if you're still blocked here? 

There have been many changes to the copilot chat sample, so I would suggest pulling the latest version before trying again.
