### ISSUE TITLE
.Net: .Net Release notes include changes from _all_ platforms (greedy)

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#6563]
**Describe the bug**
Including changes for every language or repo file in the dotnet release notes greatly obscures message and historical review.

Python releases appear to include only python changes: https://github.com/microsoft/semantic-kernel/releases/tag/python-1.0.4

**To Reproduce**
1. Go to https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-1.14.0

**Expected behavior**
Only describes changes to dotnet package.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/66376200/c15d3223-0dfc-4706-8bae-6f3e3562aaa5)

**Platform**
 - Language: Any

**Comment by markwallace-microsoft** [comment]
@crickman This is a known issue. Our process is to manually delete changes that are not relevant, I missed doing this for the 1.14.0 release.
