### ISSUE TITLE
Python: Cog Search connector is looking for index properties with Title-cased names

### ISSUE THREAD

**Issue by pjirsa** [microsoft/semantic-kernel#6565]
**Describe the bug**
They python cog search connector is using title-cased index property names, but the indexes created by kernel memory service are all lower-case.

**To Reproduce**
1. Run python getting-started example 6

**Expected behavior**
Should either not care about casing or should be consistent with generated index property names.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/2207109/4c0f632b-6a10-4c91-8d8e-563bac90d786)

**Comment by alliscode** [comment]
@TaoChenOSU would you please take a look at this one. Thanks.

**Comment by alliscode** [comment]
Closing this as it's an issue with old memory connectors.
