### ISSUE TITLE
.Net: dotnet: CreatePluginFromEmbeddedResource

### ISSUE THREAD

**Issue by mahomedalid** [microsoft/semantic-kernel#6569]
When creating a dotnet library that includes prompts in files (ex. skprompt.txt) usually such prompts get inserted as Embedded assembly resources. These libraries are useful for reusing code, and as underlying layers of APIs, CLIs, etc. or simply as projects that could be unit-tested.

A helper/utility method similar to CreatePluginFromPromptDirectory and CreatePluginFromObject would be useful.  Such helper methods are already implemented, and its usefulness validated, for example:

dotnet/src/Planners/Planners.OpenAI/Utils/EmbeddedResource.cs
dotnet/src/InternalUtilities/samples/InternalUtilities/EmbeddedResource.cs
dotnet/src/Experimental/Orchestration.Flow/EmbeddedResource.cs

which at the same time duplicates code. Having this as a core function would help other developers to implement and follow similar approaches.

**Comment by markwallace-microsoft** [comment]
Closing as stale
