### ISSUE TITLE
.Net: Add support to upload a file (image, pdf, audio, video...) to Google Gemini

### ISSUE THREAD

**Issue by heinsenberg82** [microsoft/semantic-kernel#6570]
The content of this request is similar to this one (https://github.com/microsoft/semantic-kernel/issues/6443), I guess, but related to Google Gemini. Using Google AI Studio, it is possible to upload files and ask questions about their content. It would be interesting if this feature could be triggered in Semantic Kernel.

**Comment by markwallace-microsoft** [comment]
Closed based on previous comment
