### ISSUE TITLE
Python: Running Jupyter notebooks with pip package doesn't have proper cwd

### ISSUE THREAD

**Issue by moonbox3** [microsoft/semantic-kernel#6588]
**Describe the bug**
If running SK Python Jupyter notebooks after installing the pip package, the following import will fail:

`from samples.service_settings import ServiceSettings` due to a missing module error. Using the pip package alone without further directory configuration will cause this to fail.

**To Reproduce**
1. Go to a Jupyter notebook
2. Run the pip install (do not use Poetry as it will work)
3. Run the first few cells
4. See the module not found error

**Expected behavior**
The Jupyter notebooks should be able to run OOB.

**Screenshots**

**Platform**
 - OS: Any
 - IDE: VScode
 - Language: Python
 - Source: pip 1.0.5

**Comment by juandmi** [comment]
![module not found](https://github.com/microsoft/semantic-kernel/assets/17732919/a36e0ad3-5007-4ca2-9f6a-3c42e8b94b3d)

**Comment by shahramjoon** [comment]
in my azure environment, i have a notebook. 

my 
pip show semantic-kernel

command returns 

Name: semantic-kernel
Version: 1.15.0
Summary: Semantic Kernel Python SDK
Home-page: 
Author: 
Author-email: Microsoft <SK-Support@microsoft.com>
License: 
Location: /anaconda/envs/azureml_py38/lib/python3.10/site-packages
Requires: aiohttp, azure-identity, cloudevents, defusedxml, jinja2, nest-asyncio, numpy, openai, openapi_core, opentelemetry-api, opentelemetry-sdk, prance, pybars4, pydantic, pydantic-settings
Required-by: 

i am getting the error 

from samples.service_settings import ServiceSettings
from running Users
semantic-kernel/python/samples/getting_started/00-getting-started.ipynb
