### ISSUE TITLE
[USER STORIES] E2E Dev Ops Sample

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6601]
There should be a GitHub project that demonstrates how an AI and app development team can work together in a single mono-repo to create an enterprise application. The following process should be shown:

1. AI developers can author prompts, agents, and descriptions for OpenAPI plugins using the VS Code extension (future)
2. AI developers can perform offline ingestion of documents into a vector DB
3. When the AI developer creates a PR, integration tests should run evaluations using benchmark data
4. If the integration tests pass, the PR can be merged in
5. App developers should be able to test the new AI assets in their code instantly
6. App developers can use out-of-the-box reports to detect if non-functional requirements like performance are negatively impacted by the new AI assets using OpenTelemetry
7. The enterprise app developers should have the ability to easily deploy the app to top Microsoft services: Azure Functions, Azure App Services, Azure Container Apps, etc.
8. Once the app is live, they should be able to observe the same data using OpenTelemetry

**Comment by markwallace-microsoft** [comment]
Closing as obsolete
