### ISSUE TITLE
[USER STORIES] Bot Framework example

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6602]
The existing Semantic Kernel in a Box sample should be updated to include the following enhancements:

- Update to latest Semantic Kernel version
- Move to automatic function calling
- Add the python plugin
- Add support for adaptive cards for approvals and complex form input by the user

**Comment by moonbox3** [comment]
@alliscode is this work item still needed? Thanks.

**Comment by markwallace-microsoft** [comment]
Closing as obsolete
