### ISSUE TITLE
.Net: "Use for function calling" attribute for functions

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6607]
There are some functions that should _only_ be used in prompt templates. For example, all of the new history reducer plugins (top N, summarize previous conversation, retrieve relevant messages, etc.) should _not_ be used by the AI.

To control this logic, there should be an attribute that can be added to a function to prevent the AI from ever calling this functions.

**Comment by markwallace-microsoft** [comment]
Closing as stale
