### ISSUE TITLE
.Net: Add a function that accepts a chat history and retrieves "relevant" messages

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6612]
The following handlebars template should be possible...

`{{messages (searchMessages chatHistory)}}`

This would print out the relevant messages from the chat history

> [!Note]
> this probably needs to be thought through more. You likely want sort the messages, get messages before and after the search results to provide more context, and provide transition system messages between each group of search results.

**Comment by markwallace-microsoft** [comment]
Closing as stale
