### ISSUE TITLE
.Net: Provide a way to pass in a chat history object into a prompt without loading the _entire_ chat history in memory

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6613]
The value of the history reducer plugin is to reduce the tokens required for the LLM to use extremely large chat histories. This implies we don't want to load the entire chat history into memory. There should be an extension of the chat history class that allows the system to pull _just_ the messages it needs from an external store (e.g., a vector DB)

**Comment by markwallace-microsoft** [comment]
Closing as stale
