### ISSUE TITLE
.Net: Support for Type B plugins

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6614]
Mustafa has a PR for this so we just need to review this

**Comment by SergeyMenshykh** [comment]
Related? PR: https://github.com/microsoft/semantic-kernel/pull/9436

**Comment by baywet** [comment]
> Related? PR: [#9436](https://github.com/microsoft/semantic-kernel/pull/9436)

yes! I didn't know an issue was open. Updated the PR description so it closes this issue once merged.
