### ISSUE TITLE
.Net: Graduate embeddings service

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6618]
It is in the experimental phase, and I would like to see embeddings being fully integrated into C# SK. 
Is it on the roadmap for being completed soon?

I would have used the Azure.AI.OpenAI API, but it seems it is being developed fast without providing any documentation (atleast as of last week). I think SK will be developed more robustly, so I am betting on y'all!

Let me know if you need any help, thanks

- [ ] Notify PM's and EM's that feature is ready for graduation
- [ ] Contact PM for list of sample use cases
- [ ] Verify there are sample implementations​ for each of the use cases
- [ ] Verify telemetry and logging are complete
- [ ] ​Verify API docs are complete and arrange to have them published
- [ ] Make appropriate updates to Learn docs​
- [ ] Make appropriate updates to Concept samples
- [ ] Make appropriate updates to Blog posts
- [ ] Verify there are no serious open Issues​​
- [ ] Update table in EXPERIMENTS.md
- [ ] Remove SKEXP​ flag from the experimental code

**Comment by markwallace-microsoft** [comment]
Using M.E.AI abstractions
