### ISSUE TITLE
sk_function.invoke_async(input=context) seems to have an empty prompt

### ISSUE THREAD

**Issue by Enteli** [microsoft/semantic-kernel#662]
**Describe the bug**
When running this [sample](https://github.com/microsoft/semantic-kernel/blob/main/samples/notebooks/python/04-context-variables-chat.ipynb), the notebook cell below always returns `Hi there! What would you like to talk about?` as if the prompt is empty no matter what the user_input is set to
```
context["user_input"] = "Hi, I'm looking for book suggestions"
bot_answer = await chat_function.invoke_async(input=context)
print(bot_answer)
```
On the other hand, this works as expected 

```
context["user_input"] = "Hi, I'm looking for book suggestions"
bot_answer = await kernel.run_on_vars_async(context, chat_function)
print(bot_answer)
```
Therefore something is not right with `invoke_async()`

**To Reproduce**
1. Go to this [sample](https://github.com/microsoft/semantic-kernel/blob/main/samples/notebooks/python/04-context-variables-chat.ipynb) 
2. Run the 6th cell
3. Scroll down to
```
context["user_input"] = "Hi, I'm looking for book suggestions"
bot_answer = await chat_function.invoke_async(input=context)
print(bot_answer)
```
6. See the output always being "Hi, I'm looking for book suggestions" no matter what the user_input is set to

**Expected behavior**
An output changing in relation with the user_input

**Screenshots**
<img width="719" alt="Screenshot 2023-04-25 at 9 23 22 PM" src="https://user-images.githubusercontent.com/26262833/234469529-cc064e0a-5463-420d-acd5-56ecacc02ecc.png">
**Desktop (please complete the following information):**
 - OS: MacOSX
 - IDE: VS Code, Jupyter Notebook

**Additional context**

**Comment by alexchaomander** [comment]
Known issue! A few things, make sure you have the latest code and latest pip. We don't have the `run_on_vars_async` anymore.

For this example invoke_async needs to be called with variables=context
so `chat_function.invoke_async(variables=context)`

Will update the notebooks soon with this!

**Comment by awharrison-28** [comment]
Closed by https://github.com/microsoft/semantic-kernel/pull/672

**Comment by evchaki** [comment]
Closing due to #672 being done.
