### ISSUE TITLE
.Net: Support function-calling content classes for Mistral streaming API

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#6622]
This item tracks the work required to add a connector-agnostic function-calling model for the streaming API to the Mistral AI connector.

Related issues for the OpenAI connector - https://github.com/microsoft/semantic-kernel/issues/5818 and Gemini one - https://github.com/microsoft/semantic-kernel/issues/6621

**Comment by markwallace-microsoft** [comment]
Adopt M.E.AI
