### ISSUE TITLE
Python - Required Functions do not work correctly

### ISSUE THREAD

**Issue by smj389** [microsoft/semantic-kernel#6626]
**Describe the bug**
When making a required tool choice, the OpenAI spec says that the format of the tool choice field should be as follows:
```json
{
    "type": "function",
    "function" : {
        "name":  // function name
     }
}
```
At the moment, the source code in python/semantic_kernel/connectors/ai/open_ai/services/utils.py is as follows:

```python
        settings.tool_choice = function_call_configuration.required_functions[
            0
        ].fully_qualified_name
```
It should be:
```python
        settings.tool_choice = {
              "type": "function,
               "function": {
                     "name":  function_call_configuration.required_functions[
                                      0
                                       ].fully_qualified_name
                      }
                }
```

While settings.tool_choice can be a string, it can only be one of "auto","none" or "required".

Using the required_function call as implemented leads to the chat completion request being rejected as malformed by the OpenAI / Azure OpenAI endpoint.

**Comment by smj389** [comment]
You can see the correct serialization behaviour here in the Azure SDK for .net:

https://github.com/Azure/azure-sdk-for-net/blob/187380b2603d6861169d426cbb9343237890ce75/sdk/openai/Azure.AI.OpenAI/src/Custom/ChatCompletions/ChatCompletionsToolChoice.Serialization.cs

**Comment by eavanvalkenburg** [comment]
@moonbox3  you were looking at this code already, right?

**Comment by moonbox3** [comment]
Yes, I am currently working in this code and will fix it as part of an upcoming PR. Thank you for filing @smj389.

**Comment by smj389** [comment]
Thank You @moonbox3
