### ISSUE TITLE
.Net: Issues when using SK 1.14.1 with Azure.AI.OpenAI 2.0.0-beta-1

### ISSUE THREAD

**Issue by essenbee2** [microsoft/semantic-kernel#6631]
**Describe the bug**
I installed SK 1.14.1 and Azure.AI.OpenAI 2.0.0-beta-1. The following lines of code now have red underlining for the calls to .AddAzureOpenAITextEmbeddingGeneration() and .AddAzureOpenAIChatCompletion():

                kernelBuilder = kernelBuilder.AddAzureOpenAITextEmbeddingGeneration(embeddingModelName, endpoint, tokenCredential ?? new DefaultAzureCredential());
                kernelBuilder = kernelBuilder.AddAzureOpenAIChatCompletion(deployedModelName, endpoint, tokenCredential ?? new DefaultAzureCredential());

The error for both lines in the same and as follows:

![image](https://github.com/microsoft/semantic-kernel/assets/72655107/7a7e2ee4-1d3c-4381-87a6-a97467c8fe01)

**Expected behaviour**
SK should work with the AzureOpenAIClient that is part of Azure.AI.OpenAI 2.0.0-beta-1

**Platform**
 - OS: Windows
 - IDE: Visual Studio 2022
 - Language: C#
 - Source: SK 1.14.1, Azure.AI.OpenAI 2.0.0-beta-1

**Comment by trrwilson** [comment]
Thanks, @essenbee2! And sorry for the hassle--this is a pain, but one we're hoping to consolidate into a one-time irritation.

As implied with the major version bump from v1.0.0-beta.17 and v2.0.0-beta.1, the new .NET library will require some migration steps; in that regard, SK is in the same boat as directly using the OpenAI SDK. Please stick with the v1.0.0-beta* libraries until all the dependency integration is complete.

**Comment by rliberoff** [comment]
Hello,

Do you have any ETA when this will be available?  When SK will use the v2.0.0-beta* of Azure OpenAI SDK?

Thank you.

**Comment by JasonYeMSFT** [comment]
I also wonder if you have an ETA on when the dependency will be upgraded. I come from this issue which is blocking our development. https://github.com/Azure/azure-sdk-for-net/issues/43952 Since there is a new version of the package, I think we should see if the new version has already fixed the issue and then decide on how to fix the issue.

**Comment by RogerBarreto** [comment]
All those errors are mitigated with our new `1.18.0-rc` package with the latest OpenAI Connectors using the latest `Azure` and `OpenAI` underlying official SDKs.

Please let us know if you are able to use them for your current scenarios.

We also added a dedicated `Migration Guideline` in our [learn site in here](https://learn.microsoft.com/en-us/semantic-kernel/support/v2-openai-migration-guide)
