### ISSUE TITLE
.Net: Manual function calling c# sample does not work

### ISSUE THREAD

**Issue by MSFTJim** [microsoft/semantic-kernel#6634]
I added the code from RunNonStreamingPromptWithManualFunctionCallingAsync() to a console app to test it out but the code as written does not appear to work.  It runs successfully but the LLM does not return any functions to call and in its response states how it would answer the prompt.

I changed the inline functions approach to a separate class file and added it to the builder with the following:  builder.Plugins.AddFromType<TimeandWeather>();

After this change, the LLM returns 2 functions to call and then answers the prompt appropriately.

**Comment by markwallace-microsoft** [comment]
@MSFTJim Thanks for reporting this issue

I'm testing locally and it's working in my environment as you can see below the LLM requests both functions
![image](https://github.com/microsoft/semantic-kernel/assets/127216156/df79f0de-ead9-4eb4-9d81-9dbaef521446)

Do all of the samples fail using "ImportPluginFromFunctions" for you?

**Comment by MSFTJim** [comment]
Thanks for the reply.  I did not test the others, only the manual sample and to do that I pulled out just the code from that method and the CreateBuilder.  Additionally, two other items to mention.... I am not using OAI, but AOAI and I am using model gpt-35-turbo-16k, 0613.  Not sure if that matters.

But if it is working fine for you, then perhaps the sample is ok and I did something wrong.  Thanks for getting back to me.

**Comment by MSFTJim** [comment]
I tested OAI Turbo model 1106 and it works with the code using inline functions.  If I switched to OAI Turbo model 613 it does not work!  So that seems to be what I was running into.  Interesting that 613 does work when using a different approach to add functions!

**Comment by markwallace-microsoft** [comment]
Thanks @MSFTJim, I'll look more into this, there must be some difference in the payload between the two approaches.
