### ISSUE TITLE
.Net: HuggingFace Embedding : Unable Deserlization for certain models

### ISSUE THREAD

**Issue by N-E-W-T-O-N** [microsoft/semantic-kernel#6635]
**Describe the bug**
HuggingFace Embedding Interface API: Issue related to Deserialization
So I was using  [BAAI/bge-large-en](https://huggingface.co/BAAI/bge-large-en) embedding model from huggingface Interface API .The code execution produces the following error:

``
The JSON value could not be converted to System.Collections.Generic.List`1[System.ReadOnlyMemory`1[System.Single]]. Path: $[0][0] | LineNumber: 0 | BytePositionInLine: 23.
``

**To Reproduce**

1. Use the [BAAI/bge-large-en](https://huggingface.co/BAAI/bge-large-en) embedding model.
2. Execute the embedding code.

Based on the output, it was clear that this issue was related to Json Deserilaztion .First, I check what the expected datatype. 
`
internal sealed class TextEmbeddingResponse : List<List<List<ReadOnlyMemory<float>>>>;
`
The the HuggingFace Embedinng Expected `ist<List<List<ReadOnlyMemory<float>>>>` & then return [0][0].ToList()
Then I check in Postman what is the response coming from the embedding
![BAAI](https://github.com/microsoft/semantic-kernel/assets/38786893/391d7b5b-8371-4988-976b-71490f5ae273)

So it was clear that APi is sending  List<ReadOnlyMemory<float>> while services expects a list<list<list<ReadOnlyMemory<float>>> .

I tested for other models and got the same response .

**Screenshots**

[MxBai](https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1)
![image](https://github.com/microsoft/semantic-kernel/assets/38786893/4dd486dd-d8f1-4f6d-9e7b-af41c1c6dc91)

[All-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2)
![Screenshot 2024-06-02 162430](https://github.com/microsoft/semantic-kernel/assets/38786893/ec2f352a-791f-403a-afdb-511f33567e28)

[Jina](https://huggingface.co/jinaai/jina-embeddings-v2-base-en)
![Screenshot 2024-06-02 162628](https://github.com/microsoft/semantic-kernel/assets/38786893/e5bb04ac-e7c2-4c0a-883d-3ec9399f0f53)

Finally I tested with the following embedding  [LaBSE](https://huggingface.co/cointegrated/LaBSE-en-ru) .Able to get the expected response . 
![Screenshot 2024-06-02 162657](https://github.com/microsoft/semantic-kernel/assets/38786893/898dbad6-9077-4e3b-8325-4c1f680da69e)

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version Latest ]
-  Embedding : HuggingfaceEmbedding
- Vector Database : Qdrant

**Comment by N-E-W-T-O-N** [comment]
I suggest adding a condition check for the type coming from the API response to handle the deserialization process more gracefully.

**Comment by markwallace-microsoft** [comment]
@N-E-W-T-O-N Thanks for creating the issue. Would you be interested in creating a PR with the fix for this?

**Comment by N-E-W-T-O-N** [comment]
Happy to do that.

**Comment by N-E-W-T-O-N** [comment]
Hello @markwallace-microsoft  . I have created a Pull Request #6673 as Asked
Please review my PR

**Comment by dmytrostruk** [comment]
Resolved in this PR: https://github.com/microsoft/semantic-kernel/pull/6673
