### ISSUE TITLE
.Net: Support function-calling content classes for Gemini non-streaming API

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#6641]
Two new types - FunctionCallRequestContent and FunctionCallResultContent have been added to support connector-agnostic function calling model for non-streaming API: Requirements: https://github.com/microsoft/semantic-kernel/issues/5153. PR: https://github.com/microsoft/semantic-kernel/pull/5800

This item tracks the work required to add a connector-agnostic, function-calling model for the non-streaming API to the Gemini AI connector.

**Comment by markwallace-microsoft** [comment]
Adopt M.E.AI
