### ISSUE TITLE
.Net: Add support for custom endpoints with Bearer token authentication

### ISSUE THREAD

**Issue by koteus** [microsoft/semantic-kernel#6653]
I am trying to add a service from a provider that has OpenAI compatible API. Here is my code snippet:
```
kernelBuilder.AddOpenAIChatCompletion(
    serviceId: "llama-3-8b",
    modelId: config.GetValue<string>("MY_MODEL_LLAMA-3-8B")!,
    openAIClient: new OpenAIClient(
        endpoint: new Uri(config.GetValue<string>("MY_ENDPOINT")!),
        tokenCredential: new BearerTokenCredential(
            config.GetValue<string>("MY_SECRET_KEY")!
        ),
        options: new OpenAIClientOptions
        {
            Transport = new HttpClientTransport(httpClient),
        }
    )
);
```

There is no constructor that can accept bearer token and a custom endpoint, if I use the one that accepts `apiKey` then it puts this key to custom header `api-key: xxx` instead of `Authorization: Bearer xxx`. 

So I tried this one by providing an instance of OpenAIClient, but in this case it uses Azure related endpoints. There is a PR on Azure SDK (https://github.com/Azure/azure-sdk-for-net/pull/44179) that suggests to add new constructors that would fix this issue but it seems that that code is refactored  on the main branch and they removed `OpenAIClient` definition and started to use the new version of the official one from OpenAI (https://github.com/openai/openai-dotnet/blob/OpenAI_2.0.0-beta.3/src/Custom/OpenAIClient.cs).

My suggestion is that Semantic Kernel should also separate Azure's OpenAIClient and official OpenAIClient, allowing custom endpoints and bearer token auth.

Any suggestions for this use-case? Do I understand the problem correctly?

Thanks!

**Comment by dmytrostruk** [comment]
> There is no constructor that can accept bearer token and a custom endpoint

@koteus There is a method that accepts custom endpoint, but `apiKey` probably won't be used as `Authorization` header:
https://github.com/microsoft/semantic-kernel/blob/01e826ddc1a35ae53a7134e46642297919ed79aa/dotnet/src/Connectors/Connectors.OpenAI/OpenAIServiceCollectionExtensions.cs#L1115-L1134

While we are investigating this, as quick suggestion, `AddOpenAIChatCompletion` method also accepts custom `HttpClient`, did you try to use it? In theory, it should be possible to set default `Authorization` header with your key on `HttpClient` level (as well as endpoint), but I'm not sure if it won't be ignored by Azure SDK. If you could try to check this approach on your side, that would be very helpful. Thanks a lot!

**Comment by koteus** [comment]
@dmytrostruk It sets the header if I do it in a custom HttpClient and the header is preserved — it is not stripped away by Azure SDK. But in my case I have another issue, I also need to provide `Content-Type: application/json` with every request, otherwise the custom endpoint that I am using is not recognizing the request body. Here is curl example 
```
curl -s -k -X POST \
  -H "Authorization: Bearer xxx" \
  -H "Content-Type: application/json" \
  --url "https://custom-server.dev/v1/chat/completions" \
  --data '{"model": "meta/llama-3-8b", "messages": [{"role": "system", "content": "You are a helpful, respectful and honest assistant."},{"role": "user", "content": "How can I use large language models to improve my customer service?"}], "max_tokens": 200, "temperature": 0.7, "stream": false}'
``` 
this works and when I remove `-H "Content-Type: application/json" \` it fails with error saying that request body is missing some required keys like `model` and `messages`. And no matter how I try to add default `Content-Type` it seems to be always stripped away by Azure SDK. I suppose it is meant to only be set on per-request level. Maybe it is a good idea to add it when we call `GetStreamingChatMessageContentsAsync` of completion service?

**Comment by dmytrostruk** [comment]
@koteus curl which you provided above, is it returning any results? You can also try to send a request directly from your `HttpClient` just to make sure that it's not a problem on server side. 

We have an example of different OpenAI compatible API providers, do you use some of these or you use something different?
https://github.com/microsoft/semantic-kernel/blob/dd7236e9599bdfe26a867430410917051cb20a03/dotnet/samples/Concepts/LocalModels/MultipleProviders_ChatCompletion.cs#L34-L37

There could be a case that this API is not OpenAI compatible after all. We are working on separating OpenAI and Azure OpenAI functionality, but this won't fix such problems for custom/local models. If you see that there are some differences between OpenAI and custom API, you can implement your custom `IChatCompletionService` with correct communication logic and use it for your purposes. Here is an example with custom `ITextGenerationService` implementation, but the same can be done with `IChatCompletionService`:
https://github.com/microsoft/semantic-kernel/blob/dd7236e9599bdfe26a867430410917051cb20a03/dotnet/samples/Concepts/TextGeneration/Custom_TextGenerationService.cs

**Comment by koteus** [comment]
Hi @dmytrostruk thanks for your response! We are using Scaleway service they claim that they have openai compatibility https://www.scaleway.com/en/docs/ai-data/managed-inference/reference-content/openai-compatibility/

I will try to make a test request to `/v1/chat/completions` like you suggested using my instance of HttpClient and I will let you know

**Comment by koteus** [comment]
It works with this simple script 
```
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

public class Prog
{
    static async Task Main(string[] args)
    {
        var myHttpClient = new HttpClient(new MyHttpMessageHandler(new HttpClientHandler()));

        // Example request
        var request = new HttpRequestMessage(HttpMethod.Post, new Uri("https://my-server.scw.cloud/v1/chat/completions"));

        request.Headers.Add("Authorization", $"Bearer xxx");

        request.Content = new StringContent(
            """
                {"model": "meta/llama-3-8b-instruct:bf16", "messages": [{"role": "system", "content": "You are a helpful, respectful and honest assistant."},{"role": "user", "content": "How can I use large language models to improve my customer service?"}], "max_tokens": 200, "temperature": 0.7, "stream": false}
                """,
            Encoding.UTF8, "application/json");

        request.Content!.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");

        var response = await myHttpClient.SendAsync(request);
        Console.WriteLine($"Response: {response.StatusCode}");

        if (response.IsSuccessStatusCode)
        {
            await ReadSseStreamAsync(response, logger);
        }
        else
        {
            logger.LogError($"Request failed with status code: {response.StatusCode}");
        }
    }

    private static readonly ILogger<Prog> logger = LoggerFactory.Create(builder =>
    {
        builder.AddConsole();
    }).CreateLogger<Prog>();


    private static async Task ReadSseStreamAsync(HttpResponseMessage response, ILogger logger)
    {
        using var stream = await response.Content.ReadAsStreamAsync();
        using var reader = new StreamReader(stream);

        while (!reader.EndOfStream)
        {
            var line = await reader.ReadLineAsync();

            if (!string.IsNullOrWhiteSpace(line))
            {
                logger.LogInformation($"Received SSE event: {line}");
                ProcessSseEvent(line, logger);
            }
        }
    }

    private static void ProcessSseEvent(string sseEvent, ILogger logger)
    {
        // Process the SSE event (e.g., parse data, handle event types, etc.)
        // This is a simple example, adjust according to your SSE event structure
        logger.LogInformation($"Processing SSE event: {sseEvent}");
    }
}
```
I can see SSE events in the logged in the terminal: 
```
base ❯ dotnet run
Building...
Sending HTTP request to https://my-server.scw.cloud/v1/chat/completions, headers: Authorization: Bearer xxx
, contentHeaders: Content-Type: application/json
, body: System.Net.Http.StringContent
Response: OK
info: Prog[0]
      Received SSE event: {"id":"6fec41e4-6ecf-40d4-91f5-7d39fcda3686","choices":[{"index":0,"message":{"content":"Large language models can be a game-changer for customer service. Here are some ways to leverage them:\n\n1. **Chatbots**: Integrate a chatbot into your website or application. The chatbot can respond to basic customer queries, freeing up human agents to focus on more complex issues.\n2. **Conversational AI**: Use conversational AI to enhance the customer experience. For example, you can use AI-powered chatbots to offer personalized product recommendations or to provide customers with information about their orders.\n3. **Language Understanding**: Leverage large language models to improve language understanding in customer service. For example, you can use AI-powered language understanding to automatically categorize customer inquiries or to provide customers with information about their orders.\n4. **Sentiment Analysis**: Use large language models to analyze customer sentiment and identify areas for improvement. For example, you can use AI-powered sentiment analysis to automatically categorize customer feedback as positive, negative, or neutral.\n5. **Integrate with CRM**:","role":"assistant","name":""},"finish_reason":"length"}],"created":1718128288,"model":"meta/llama-3-8b-instruct:bf16","system_fingerprint":"fp-0a1b2c3d4e","object":"chat.completion","usage":{"prompt_tokens":0,"completion_tokens":200,"total_tokens":200}}
info: Prog[0]
      Processing SSE event: {"id":"6fec41e4-6ecf-40d4-91f5-7d39fcda3686","choices":[{"index":0,"message":{"content":"Large language models can be a game-changer for customer service. Here are some ways to leverage them:\n\n1. **Chatbots**: Integrate a chatbot into your website or application. The chatbot can respond to basic customer queries, freeing up human agents to focus on more complex issues.\n2. **Conversational AI**: Use conversational AI to enhance the customer experience. For example, you can use AI-powered chatbots to offer personalized product recommendations or to provide customers with information about their orders.\n3. **Language Understanding**: Leverage large language models to improve language understanding in customer service. For example, you can use AI-powered language understanding to automatically categorize customer inquiries or to provide customers with information about their orders.\n4. **Sentiment Analysis**: Use large language models to analyze customer sentiment and identify areas for improvement. For example, you can use AI-powered sentiment analysis to automatically categorize customer feedback as positive, negative, or neutral.\n5. **Integrate with CRM**:","role":"assistant","name":""},"finish_reason":"length"}],"created":1718128288,"model":"meta/llama-3-8b-instruct:bf16","system_fingerprint":"fp-0a1b2c3d4e","object":"chat.completion","usage":{"prompt_tokens":0,"completion_tokens":200,"total_tokens":200}}
```
The url subdomain and bearer token are different of course, and MyHttpMessageHandler is the same as before.

**Comment by dmytrostruk** [comment]
@koteus In this case, I'm not sure we can do anything else on our side. Maybe it's worth to contact Scaleway service team and check with them if they will be compatible with existing Azure OpenAI SDK or new OpenAI SDK. Meanwhile, you can use your code and implement custom `IChatCompletionService`, which will work exactly like already existing OpenAIChatCompletionService, but with your modifications. Let me know what you think about it.

**Comment by koteus** [comment]
I did more investigation putting more logs and using debugger with "breakpoint on all exceptions" checked. I found that the error is when I enumerate on response stream:
```
Exception thrown: 'System.ArgumentOutOfRangeException' in System.Private.CoreLib.dll: 'Specified argument was out of the range of valid values.'
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.MemoryExtensions.AsMemory(String text, Int32 start, Int32 length)
   at Azure.Core.Sse.SseLine.get_FieldName()
   at Azure.Core.Sse.SseAsyncEnumerator`1.<EnumerateFromSseStream>d__0.MoveNext()
   at Azure.Core.Sse.SseAsyncEnumerator`1.<EnumerateFromSseStream>d__0.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetStreamingChatMessageContentsAsync>d__36.MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetStreamingChatMessageContentsAsync>d__36.MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetStreamingChatMessageContentsAsync>d__36.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
```

the last chunk of SSE from Scaleway is `[DONE]` and from Azure OpenAI it is `data: [DONE]` so it looks like SSE parser fails to read field name `at Azure.Core.Sse.SseLine.get_FieldName()`. So it is indeed the issue of Scaleway because just `[DONE]` is not a valid SSE.

Moreover, it looks like this configuration just works, it adds bearer token and json content type headers correctly:
```
kernelBuilder.AddOpenAIChatCompletion(
    serviceId: "llama-3-8b",
    endpoint: new Uri(config.GetValue<string>("SCALEWAY_ENDPOINT")!),
    modelId: config.GetValue<string>("SCALEWAY_MODEL_LLAMA-3-8B")!,
    apiKey: config.GetValue<string>("SCALEWAY_SECRET_KEY")!
);
```
So when providing apiKey it is added as bearer token. And the reason why I did not see "Content-Type: application/json" in the logs is because I was logging `request.Headers` but it exists on `request.Content.Headers`.

I will try to contact Scaleway to ask to fix this issue with SSE, but meanwhile if you have any idea how I could monley-patch this issue I would really appreciate it :)

Thanks for your help @dmytrostruk !

**Comment by dmytrostruk** [comment]
@koteus Thanks for all the information, good to know the root cause of this problem. 

> I will try to contact Scaleway to ask to fix this issue with SSE, but meanwhile if you have any idea how I could monkey patch this issue I would really appreciate it :)

I'm thinking about updating SSE content on the fly using `DelegatingHandler`, something like this:
```csharp
protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
{
    var response = await base.SendAsync(request, cancellationToken);
    
    var originalContent = await response.Content.ReadAsStreamAsync();
    var modifiedContent = new MemoryStream();

    using (var reader = new StreamReader(originalContent))
    using (var writer = new StreamWriter(modifiedContent))
    {
        string line;
        while ((line = await reader.ReadLineAsync()) != null)
        {
            if (line == "[DONE]")
            {
                line = "data: [DONE]";
            }
            await writer.WriteLineAsync(line);
            await writer.FlushAsync();
        }
    }

    modifiedContent.Seek(0, SeekOrigin.Begin);

    response.Content = new StreamContent(modifiedContent);

    return response;
}
```

But keep in mind that it's just an example, I'm not sure it's the best solution in terms of performance. It looks like you are using streaming methods, I'm wondering whether you considered non-streaming methods? At least until this issue will be handled by responsible team. Thanks again!

**Comment by koteus** [comment]
You patch works with some modifications. In case it will be useful for someone I will provide the source code
```csharp

public class ScalewaySsePatchHandler : DelegatingHandler
{
    private readonly ILogger<DelegatingHandler> _logger;

    public ScalewaySsePatchHandler(ILogger<DelegatingHandler> logger)
    {
        _logger = logger;
        InnerHandler = new HttpClientHandler();
    }

    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        _logger.LogInformation($"Sending HTTP request to {request.RequestUri}");

        var response = await base.SendAsync(request, cancellationToken);

        using var originalContent = await response.Content.ReadAsStreamAsync(cancellationToken);
        var modifiedContent = new MemoryStream();

        using var reader = new StreamReader(originalContent);
        var writer = new StreamWriter(modifiedContent);

        string? line;
        while ((line = await reader.ReadLineAsync()) != null)
        {
            if (line == "[DONE]")
            {
                line = "data: [DONE]";
            }
            await writer.WriteLineAsync(line);
            await writer.FlushAsync();
        }

        modifiedContent.Seek(0, SeekOrigin.Begin);

        // Create a new StreamContent to replace the original content
        var newContent = new StreamContent(modifiedContent);

        // Copy headers from the original content to the new content
        foreach (var header in response.Content.Headers)
        {
            newContent.Headers.TryAddWithoutValidation(header.Key, header.Value);
        }

        response.Content = newContent;

        return response;
    }
}
```
The Scaleway team responded that they will fix this issue in the next release. 

**I will close this issue, thanks again for great support!** 🚀
