### ISSUE TITLE
.NET Pinecone: migrate to new API

### ISSUE THREAD

**Issue by maumar** [microsoft/semantic-kernel#6678]
Old Pinecone API has been deprecated in April 2024 (https://docs.pinecone.io/guides/operations/migrate-to-the-new-api) , SK Pinecone connector should move to the new API

**Comment by maumar** [comment]
I will do the work, feel free to assign me to the issue, per contribution guidelines. Ideally, this would involve breaking changes, as the API change on the Pinecone side is itself breaking. /cc @SamMonoRT @luisquintanilla

**Comment by maumar** [comment]
proposed breaks:

- remove environment from PineconeMemoryStore and PineconeClient ctors.
old:

```cs
    public PineconeMemoryStore(
        string pineconeEnvironment,
        string apiKey,
        ILoggerFactory? loggerFactory = null)

public PineconeClient(string pineconeEnvironment, string apiKey, ILoggerFactory? loggerFactory = null, HttpClient? httpClient = null)
```

new:

```cs
    public PineconeMemoryStore(
        string apiKey,
        ILoggerFactory? loggerFactory = null)

public PineconeClient(string apiKey, ILoggerFactory? loggerFactory = null, HttpClient? httpClient = null)
```

Add CreateServerlessIndexAsync and CreatePodBasedIndexAsync, remove current method CreateIndexAsync.


old:
```cs
public async Task CreateIndexAsync(IndexDefinition indexDefinition, CancellationToken cancellationToken = default)
```

new:

```cs
    public async Task CreateServerlessIndexAsync(
        string name,
        int dimension,
        IndexMetric metric,
        ServerlessIndexCloud cloud,
        string region,
        CancellationToken cancellationToken = default)

    public async Task CreatePodBasedIndexAsync(
        string name,
        int dimension,
        IndexMetric metric,
        string environment,
        PodType podType = PodType.P1X1,
        int pods = 1,
        int? replicas = 1,
        int? shards = 1,
        MetadataIndexConfig? metadataConfig = null,
        string? sourceCollection = null,
        CancellationToken cancellationToken = default)
```

change return type of ListIndexesAsync

old:

```cs
public async IAsyncEnumerable<string?> ListIndexesAsync([EnumeratorCancellation] CancellationToken cancellationToken = default)
```

new:

```cs
public async IAsyncEnumerable<PineconeIndex> ListIndexesAsync([EnumeratorCancellation] CancellationToken cancellationToken = default)
```

PineconeIndex class adjusted to reflect new shape, no longer taking parameter object in the ctor.

old:

```cs
public sealed class PineconeIndex
{
    public PineconeIndex(IndexDefinition configuration, IndexStatus status)
    public IndexDefinition Configuration { get; set; }
    public IndexStatus Status { get; set; }
}
```

new:

```cs
public sealed class PineconeIndex
{
    public PineconeIndex(string name, int dimension, IndexMetric metric, string? host, IndexSpec spec, IndexStatus status)
    public string Name { get; set; }
    public int Dimension { get; set; } = 1536;
    public IndexMetric Metric { get; set; } = IndexMetric.Cosine;
    public string? Host { get; set; }
    public IndexSpec Spec { get; set; }
    public IndexStatus Status { get; set; }
}
```

**Comment by SamMonoRT** [comment]
@markwallace-microsoft  - please assign the above issue to @maumar for accurate tracking. Thanks.

**Comment by dmytrostruk** [comment]
> new:
> 
> ```cs
> public PineconeMemoryStore(
>     string apiKey,
>     ILoggerFactory? loggerFactory = null)
> 
> public PineconeClient(string apiKey, ILoggerFactory? loggerFactory = null, HttpClient? httpClient = null)
> ```

I think it's good timing to add these breaking changes in scope of memory redesign work. Use following links for more information and implementation examples:
- https://github.com/microsoft/semantic-kernel/pull/6364
- https://github.com/microsoft/semantic-kernel/pull/6585
