### ISSUE TITLE
.Net Gemini Connector - Make `bearerTokenProvider` return `ValueTask<string>` instead of `Task<string>`

### ISSUE THREAD

**Issue by ledjon-behluli** [microsoft/semantic-kernel#6679]
The `ClientBase` abstract class, under `Microsoft.SemanticKernel.Connectors.Google.Core` has a constructor which accepts a `Func<Task<string>>`. Whatever func that we provide will most of the time provide back the same value for the token, question is: why can't the provider func be of type `Func<ValueTask<string>>` in order to avoid unnecessary `Task` allocations on every call?

I understand the "dont await a `ValueTask` twice" rule, but when a `ValueTask` is wrapped in a `Func`, each invocation of the `Func` returns a new instance of the `ValueTask`, so it would be a safe operation.

**Comment by RogerBarreto** [comment]
@ledjon-behluli, yes that makes sense!
