### ISSUE TITLE
.Net: Bug: Model Specification in InvokePromptAsync Not Overriding Default Model

### ISSUE THREAD

**Issue by VivienMAN** [microsoft/semantic-kernel#6695]
I am encountering an issue where the InvokePromptAsync method does not use the specified model gpt-3.5-turbo, but instead defaults to gpt-4o. I have configured AddOpenAIChatCompletion with the gpt-4o model by default. However, I would like to use gpt-3.5-turbo for specific tasks, such as summarizing a message, by passing it as a parameter. Unfortunately, the specified model is not being utilized.

**Service Configuration:**
```
context.Services.AddTransient<Kernel>(serviceProvider =>
{
    Kernel k = new(serviceProvider);
    k.ImportPluginFromType<HelperPlugin>();
    return k;
});
context.Services.AddOpenAIChatCompletion(modelId: "gpt-4o",
    apiKey: "XXXXXXXXXXXX");

```

**Using InvokePromptAsync with Specified Model:**
```
KernelArguments args = new KernelArguments(new OpenAIPromptExecutionSettings()
    { MaxTokens = maxtokenSortieConversationTitle, ModelId = "gpt-3.5-turbo" });
var summary = await _kernel.InvokePromptAsync(prompt, args);
return summary.ToString();
```
Despite specifying gpt-3.5-turbo, the InvokePromptAsync method uses the default gpt-4o.

**Using Default Model with GetStreamingChatMessageContentsAsync:**
```
var result = _openAiChatCompletionService.GetStreamingChatMessageContentsAsync(
    history,
    executionSettings: openAiPromptExecutionSettings,
    kernel: _kernel);
```
This method correctly uses the default gpt-4o model as expected.

**Expected Behavior**
The InvokePromptAsync method should use the model specified in the KernelArguments (gpt-3.5-turbo), overriding the default model set in AddOpenAIChatCompletion.

**Actual Behavior**
The InvokePromptAsync method defaults to gpt-4o even when gpt-3.5-turbo is specified in the KernelArguments.

**Steps to Reproduce**
Configure the Kernel and OpenAIChatCompletion with gpt-4o as shown in the code above.
Attempt to use InvokePromptAsync with gpt-3.5-turbo specified in KernelArguments.
Observe that gpt-4o is used instead of gpt-3.5-turbo.

**Comment by markwallace-microsoft** [comment]
@VivienMAN 

You will need to register both models that you want to use

```
context.Services.AddOpenAIChatCompletion(modelId: "gpt-4o",
    apiKey: "XXXXXXXXXXXX");
context.Services.AddOpenAIChatCompletion(modelId: "gpt-3.5-turbo",
    apiKey: "XXXXXXXXXXXX");
```

The code just searches through the models that have been explicitly registered on the Kernel.

Here is our sample: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Concepts/ChatCompletion/Connectors_WithMultipleLLMs.cs

**Comment by VivienMAN** [comment]
Thx @markwallace-microsoft 

I tried to do this, following my issue but the behavior is the same.

```
        context.Services.AddOpenAIChatCompletion(modelId: "gpt-4o",
            apiKey: "XX);
        context.Services.AddOpenAIChatCompletion(modelId: "gpt-3.5-turbo",
            apiKey: "XX");
```

**Comment by VivienMAN** [comment]
I find a solution : 

```
    public GptService(Kernel kernel, IEnumerable<IChatCompletionService> openAiChatCompletionService,
        IFeatureChecker featureChecker)
    {
        _kernel = kernel;
        //Select the good IChatCompletionService
        _openAiChatCompletionService =
            openAiChatCompletionService.SingleOrDefault(x => x.Attributes["ModelId"]?.ToString() == GptNameConst.Gpt4)
            ?? throw new InvalidOperationException("No valid IChatCompletionService found.");

        _featureChecker = featureChecker;
    }
```
