### ISSUE TITLE
How to add a vector database for the python bindings?

### ISSUE THREAD

**Issue by hsm207** [microsoft/semantic-kernel#670]
Hello,

I would like to help add a vector database for the python bindings and could not find anything in the [docs](https://learn.microsoft.com/en-gb/semantic-kernel/whatissk) that describes the steps to do it.

Is implementing the [MemoryStoreBase](https://github.com/microsoft/semantic-kernel/blob/c9b9220333ad1bf10c76e6506628f01dd26fa5eb/python/semantic_kernel/memory/memory_store_base.py) class sufficient?

Any pointers and references would be highly appreciated 😀

**Comment by awharrison-28** [comment]
Hi @hsm207 here is the PR I mentioned - https://github.com/microsoft/semantic-kernel/pull/684

Would you like to see additional documentation for how to extend the memory connectors?

**Comment by hsm207** [comment]
Hi @awharrison-28 , 

Thanks for linking to the PR. Looking at it, I think having a write up on how to go about making the changes would be very useful. For example, the docarray project has step by step  [walkthrough](https://docarray.jina.ai/advanced/document-store/extend/) that walks users through the steps to add a new document store into the project.
