### ISSUE TITLE
Python: double check if unit tests cover all creation paths

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/semantic-kernel#6700]
**Describe the bug**
We had a regression in the settings of the AI search connector, this want caught with unit tests, hence we want to make sure that we do have that for all ways of setting up. Will partially be solved when we further expand test coverage to include all memory services.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by moonbox3** [comment]
Stale. Closing. Re-open if needed.
