### ISSUE TITLE
.Net: Bug:  [Dotnet] Serialization Error: `top_p` Value Loses Decimal Point in JSON Payload

### ISSUE THREAD

**Issue by sangyuxiaowu** [microsoft/semantic-kernel#6712]
**Describe the bug**

When integrating `AddOpenAIChatCompletion`, the server returns an error due to the `top_p` parameter in the JSON payload being serialized as an integer (1) instead of a floating-point number (1.0). The exact error message from the server is: "Microsoft.SemanticKernel.HttpOperationException: 'Range of top_p should be (0.0, 1.0).' This indicates that the `top_p` value does not adhere to the expected floating-point format.

**To Reproduce**

1. Configure the `AddOpenAIChatCompletion` with a `top_p` value set to 1.0.
2. Trigger the completion request that sends the JSON payload to the server.
3. Observe the error in the server response indicating the `top_p` value issue.

**Expected behavior**

The `top_p` value should be serialized as a floating-point number (e.g., 1.0) in the JSON payload, adhering to the expected range and format, thus avoiding the server-side error.

**Screenshots**

```
 ---> Azure.RequestFailedException: Range of top_p should be (0.0, 1.0)
Status: 400 (Bad Request)
ErrorCode: invalid_parameter_error

Content:
{"error":{"code":"invalid_parameter_error","param":null,"message":"Range of top_p should be (0.0, 1.0)","type":"invalid_request_error"}}
```

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language:  C#

**Additional context**
The issue seems to stem from the JSON serialization process where the double value of `top_p` is being serialized as an integer (1) instead of a floating-point number (1.0). This is evident in the logs showing the settings payload sent to the server:

```
TRACE Log Show Settings: {"temperature":0.6,"top_p":1,"presence_penalty":0,"frequency_penalty":0,"max_tokens":100,"stop_sequences":null,"results_per_prompt":1,"seed":null,"response_format":null,"chat_system_prompt":null,"token_selection_biases":null,"ToolCallBehavior":null,"User":null,"logprobs":null,"top_logprobs":null,"model_id":null}
```

A potential workaround or fix might involve ensuring that double values are always serialized with their decimal points, even when the decimal value is zero, to comply with the expected format for floating-point numbers in JSON payloads.

**Comment by emtabiraobarias** [comment]
Hi @sangyuxiaowu, are you able to share the code snippet that led to this bug?

**Comment by dmytrostruk** [comment]
@sangyuxiaowu I just tested it locally with `top_p` value set to `1.0` and it works as expected for me. I'm wondering if you are using `AddOpenAIChatCompletion` with one of OpenAI models or you use local/custom model that is compatible with OpenAI API?

**Comment by sangyuxiaowu** [comment]
@dmytrostruk  
Thank you for your response.

1. I am using a third-party service that is compatible with OpenAI's API. This service has strict data type requirements, and the `top_p` value must be `1.0` instead of `1`.
2. Through packet analysis, including the TRACE log display, I have confirmed that the `semantic-kernel` ultimately submits the value `1` instead of `1.0` to the server. Below is the relevant portion from the TRACE log in the console, showing the settings payload sent to the server:

```bash
TRACE Log Show Settings: {"temperature":0.6,"top_p":1,"presence_penalty":0,"frequency_penalty":0,"max_tokens":100,"stop_sequences":null,"results_per_prompt":1,"seed":null,"response_format":null,"chat_system_prompt":null,"token_selection_biases":null,"ToolCallBehavior":null,"User":null,"logprobs":null,"top_logprobs":null,"model_id":null}
```

**Comment by sangyuxiaowu** [comment]
@emtabiraobarias  The code is not particularly special because of the strict restrictions imposed by the other party's server. But the problem is indeed that when JSON is serialized, it changes double to int.
```cs
var llmConfig = config.GetSection(nameof(LLMConfig)).Get<LLMConfig>();
services.AddKernel();
#pragma warning disable SKEXP0010
services.AddOpenAIChatCompletion(llmConfig.Model, new Uri(llmConfig.Url + "/chat/completions"), llmConfig.Key);
```
....

```cs
var content = _kernel.InvokePromptStreamingAsync("hello");
```

**Comment by markwallace-microsoft** [comment]
I have tested and for the following code:

```csharp
var chatHistory = new ChatHistory
{
    new ChatMessageContent(AuthorRole.User, "Hello World?")
};

var settings = new OpenAIPromptExecutionSettings()
{
    Temperature = 1.2,
    TopP = 0.8
};

await sut.GetChatMessageContentAsync(chatHistory, settings);
```
 The payload looks like this:

```
{
    "messages": [
        {
            "content": "Hello World?",
            "role": "user"
        }
    ],
    "temperature": 1.2,
    "top_p": 0.8,
    "n": 1,
    "presence_penalty": 0,
    "frequency_penalty": 0,
    "model": "gpt-3.5-turbo"
}
```

So the decimal part of `top_p` is not lost.

For the case where `top_p=1.0` it is serialised as `"top_p": 1` but that is functionally equivalent to `"top_p": 1.0` and the OpenAI and Azure OpenAI services don't have an issue. If the third party service is claiming API compatibility then it should really behave the same. I suggest creating an issue with that service.
