### ISSUE TITLE
.Net: Inherit & override the parent function choice behavior in SK prompts

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#6743]
Form the ADR - https://github.com/microsoft/semantic-kernel/pull/6083

SK prompts may have one or more entries, one per service, of execution settings to describe service-specific configurations in a prompt. Considering that each section is deserialized to an instance of the PromptExecutionSettings class and that class is used by the corresponding service, it makes sense to specify the function behavior in each service configuration section. On the other hand, this may introduce unnecessary duplication because all services might need exactly the same choice behavior. Additionally, there could be scenarios where 2 out of 3 services use the same choice behavior configuration, while the remaining one uses a different one.
```json
"function_choice_behavior":{
    ...
},
"execution_settings": {
   "default": {
     "temperature": 0,
     "function_choice_behavior":{
        ...
     }
   },
   "gpt-3.5-turbo": {
     "model_id": "gpt-3.5-turbo-0613",
     "temperature": 0.1,
     "function_choice_behavior":{
        ...
     }
   },
   "gpt-4": {
     "model_id": "gpt-4-1106-preview",
     "temperature": 0.3,
     "function_choice_behavior":{
        ...
     }
   }
 }
```
To accommodate the scenarios above, it makes sense to introduce an inheritance mechanism that would inherit the parent function choice behavior configuration, if specified. Regardless of whether the parent has a function choice behavior configuration specified or not, it should be possible to specify or override the parent's configuration at each service entry level.

**Comment by markwallace-microsoft** [comment]
Closing as stale
