### ISSUE TITLE
.Net: Support function choice behavior in Prompty YAML files

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#6756]
It should be possible to specify function choice behavior in Prompty YAML files. This may require creating and using type converters, similar to the ones introduced in this PR - [PromptExecutionSettingsTypeConverter](https://github.com/microsoft/semantic-kernel/pull/6083/files#diff-308d42bfd7541eb1639aa2dccf64a1337874fa6bdcba6d327c3cc489bd5542be) to deserialize the YAML files.

**Comment by markwallace-microsoft** [comment]
Closing as stale
