### ISSUE TITLE
Support semantic SKFunctions for chat completion backends

### ISSUE THREAD

**Issue by danpere** [microsoft/semantic-kernel#676]
Currently semantic functions are only compatible with text completion backends. That is, `IKernel.RunAsync()` can be given a semantic function that will fill in a template and call sub-skills before making a call to `ITextCompletion.CompleteAsync()`, but there's no mechanism to get it to call `IChatCompletion.GenerateMessageAsync()` to use a chat completion backend other than writing an adapter to make the chat completion backend pretend to be a text completion backend and therefore not take advantage of chat-specific features like providing the history in a structured way.

The straightforward version of this I would expect is that a semantic function computed prompt should be added to the chat history as the user message and return the assistant response. The chat history would be kept around by the kernel. [This branch](https://github.com/microsoft/semantic-kernel/compare/main...danpere:semantic-kernel:exp/skfunction-chatcompletion) implements that change... but is not at all ready to merge because the use of `ITextCompletion` is tied into the `ISKFunction` interface. In that branch, I just replaced those references with `IChatCompletion`, but more likely the desired behavior would be to support both, and I'm not sure exactly what that should look like.

Also, there's more possible ways the API client might want to manipulate the chat history. For instance, maybe subskills should include the history in the requests but not add the back-and-forth to the chat history. Or maybe the client may want to summarize or filter the history to keep it shorter or on-topic. The latter is supported in my PR by making the history setter `public`, but that might not be the best way to do that.

**Comment by dluc** [comment]
hi @danpere we added this a couple of weeks ago: https://github.com/microsoft/semantic-kernel/blob/main/samples/dotnet/kernel-syntax-examples/Example26_SemanticFunctionsUsingChatGPT.cs

allowing to use chat endpoints for semantic functions, e.g.

```csharp
kernel.Config.AddAzureChatCompletionService("id", "gpt-35-turbo", "https://....openai.azure.com/", "...API KEY...");

var func = kernel.CreateSemanticFunction(
            "List the two planets closest to '{{$input}}', excluding moons, using bullet points.");

var result = await func.InvokeAsync("Jupiter");
```

does it provide the functionality you were looking for?

**Comment by dluc** [comment]
The solution above hides the fact you're dealing with a chat history, object, in fact the history is created from scratch every time. About the second part, where functions interact with a chat history, I would use traditional native functions, passing the chat object around, and invoking semantic functions manually, when needed.

**Comment by danpere** [comment]
I think it looks like that would be possibly by making our own implementation of `IKernel` that intercepts `IKernel.RegisterSemanticFunction()`, although that feels hacky. And doesn't provide a clear way to customize how different skills interact with the history.

I can see if we can fit what we want to do into that to get a better understanding of what we want out of SemanticKernel.

**Comment by jcfontecha** [comment]
Are file-backed semantic skills intended to be supported by chat completion backends? Happy to start a different issue since I'm using Python but this seemed related. Right now whenever I add a chat backend to the kernel and try to import skills from my directory I get `ValueError: TextCompletionClientBase backend with service_id 'None' not found` so I was curious if I was going against a pattern here or its just something in the backlog (I'm pretty new to the framework)

**Comment by danpere** [comment]
After further discussion, it sounds like `IKernel` is not the appropriate API for what we want to do, and it makes more sense to generate prompts using the template engine and send those to the chat completion backend ourselves outside of SemanticKernel.
