### ISSUE TITLE
.Net: allow use of OpenAIAssistantAgent without needing to use GroupChat

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6760]
It's currently possible to invoke the `ChatCompletionAgent` with the `InvokeAsync` method. It should be possible to do the same with the Assistants implementation of agents for getting started experiences.

1. It should be possible to provide an entire chat history that 1) creates a new thread and 2) has the agent perform a run on the new thread
2. It should be possible to provide a thread that the agent can perform a run on

For #2, we likely need to provide user's the ability to create/manage their own thread. It should ideally inherit from `ChatHistory` so that it behaves identically. Exceptions should be thrown if the user attempts to do something that's not possible with Threads (i.e., add a system message in the middle of the thread).

**Comment by crickman** [comment]
FYI - This change is predicated on https://github.com/microsoft/semantic-kernel/pull/6933
