### ISSUE TITLE
Python: Add support for kernel.InvokePromptAsync similar to C# counterpart.

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#6804]
Currently we have Kernel examples that are very simple using C#:

```csharp
Kernel kernel = Kernel.CreateBuilder()
            .AddOpenAIChatCompletion(modelId: “gpt-4o”, apiKey: “…”)
            .Build();

Console.WriteLine(await kernel.InvokePromptAsync("Why is the sky blue?"));
```

In python there's no way to use it as `function_name` and `plugin_name` are required arguments and need to be created manually with a `prompttemplateconfig`.

Desired but not supported today
```python
kernel = Kernel()
kernel.add_service(OpenAIChatCompletion(ai_model_id="gpt-4o", api_key="..."))

print(asyncio.run(kernel.invoke_prompt("Why is the sky blue")))
```
Currently to achieve a result all those lines are required in python:

```python
kernel = Kernel()
kernel.add_service(OpenAIChatCompletion(ai_model_id="gpt-4o", api_key="..."))
prompt_template_config = PromptTemplateConfig(template="why is the sky blue")
tldr_function = kernel.add_function(function_name="tldrFunction",plugin_name="tldrPlugin", prompt_template_config = prompt_template_config)
result = asyncio.run(kernel.invoke(tldr_function))
print(result)
```

**Comment by moonbox3** [comment]
Hi @RogerBarreto, we have the `invoke_prompt` functionality today. You can see it in use in [this](https://github.com/microsoft/semantic-kernel/blob/3e8a93616f5f9215d84d71644c233d62182bb326/python/samples/concepts/plugins/openai_function_calling_with_custom_plugin.py#L71) concept sample.

![image](https://github.com/microsoft/semantic-kernel/assets/35585003/126b7bb4-cfd7-4547-adef-5cdd3560bb19)

**Comment by RogerBarreto** [comment]
@moonbox3, yes and no `function_name`, `plugin_name` and `settings` are required for that.
