### ISSUE TITLE
Python: Ollama Function Calling

### ISSUE THREAD

**Issue by last-Programmer** [microsoft/semantic-kernel#6805]
I can see that in python langchain we have this https://python.langchain.com/v0.2/docs/integrations/chat/ollama_functions/

How can we do the same with Ollama local LLM and kernel functions?

Thanks

**Comment by alliscode** [comment]
Hi @last-Programmer and thanks for creating this issue. Currently the only thing we have that attempts to impose function calling on models that don't support it, are our action and sequential planners. We are working on a new python-based planner that will fill this purpose and is being tracked with #6854. Closing this issue for now, but feel free to reopen if needed.
