### ISSUE TITLE
.Net Agents: Should InvokeAsync for ChatCompletionAgent return an IAsyncEnumerable?

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6808]
Once we have the streaming version of agents, shouldn't `ChatCompletionAgent` just return a list of chat messages?

**Comment by crickman** [comment]
This decision point might not be necessarily linked to streaming support.

**Comment by RogerBarreto** [comment]
Curious to know if the streaming version of agents provide a new API call for streaming or the whole agent is stream. This question relates to how we do in SK services where we do provide two APIs for Streaming and Not-Streaming scenarios in the same service.

```mermaid
graph LR
Agent --> InvokeAsync
Agent --> InvokeStreamingAsync
```

OR

```mermaid
graph LR
Agent --> InvokeAsync_
StreamingAgent --> InvokeAsync 
```

**Comment by crickman** [comment]
@RogerBarreto - Likely the former.  Do you have thoughts / suggestions?

**Comment by crickman** [comment]
@matthewbolanos - Signature modification also indicated for https://github.com/microsoft/semantic-kernel/issues/6813.

**Comment by crickman** [comment]
@matthewbolanos - For the Open AI Assistant case, a run can produce multiple messages which are sometimes separated by tool calls that might have latency (i.e. code-interpreter).  `IAsyncEnumerable` enables earlier messages to be accessed while the run proceeds.  Returning the messages in a syncronous fashion may increase the percieved latency.  

This consideration may also be applicable to chat-completion scenarios.

**Comment by crickman** [comment]
Already is!
