### ISSUE TITLE
.Net: Blog post for OpenAI V2 SDK

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#6866]
Work with PM of a Blog describing the change, what the expected outcome, benefits and impact for developers will be.

Below are some suggested sections for the Blog post

**Background**
Semantic Kernel v1 has a dependency on Azure.AI.OpenAI v1, more specifically Microsoft.SemanticKernel.Connectors.OpenAI v1.x depends on Azure.AI.OpenAI v1.x. OpenAI are introducing an official [OpenAI client library for .NET](https://www.nuget.org/packages/OpenAI/2.0.0-beta.5). Microsofts Azure.AI.OpenAI has been updated to depend on the OpenAI package so that it can take full advantage of new features as they emerge. These changes impact Semantic Kernel and the purpose of this Blog post is the explain the long term benefits developers will gain and also the short term impact was we make this transition.

Provide links to the new NuGet packages and the associated projects.

**What this means for Semantic Kernel Developers**
1. This is a very positive step as Semantic Kernel will be better positioned to keep up-to-date with the latest developments from OpenAI. We've already seen the benefits of this in Semantic Kernel for Python which has been able to use the latest OpenAI API's from day one because we use the official OpenAI Python library.
2. Some code migration will be required, this is unavoidable as the underlying dependencies are changing. For developers who don't use the underlying `OpenAIClient` the changes will be minimal. We will provide support by way of a migration guide and early access to see the changes to help developers with the transition.

**Our Plan**
1. Explain future state i.e. adding new Azure OpenAI specific package
2. Explain how the update will be rolled in a Semantic Kernel release and the expected time frame. This will be based on the Azure.AI.OpenAI and OpenAI release plans.
3. Explain the supports that will be provided for developers.
4. Explain how to learn more and see the changes as they evolve i.e. point to feature branch.
5. Link to the plan in our backlog so developers can keep track of progress.

PRs to update samples:
- https://github.com/microsoft/semantic-kernel/pull/7233
- https://github.com/microsoft/semantic-kernel/pull/7334
- https://github.com/microsoft/semantic-kernel/pull/7353

**Comment by matthewbolanos** [comment]
Should also identify and link to any other comms around this change from the Azure AI team
