### ISSUE TITLE
.Net:  Create new Microsoft.SemanticKernel.Connectors.AzureOpenAI project

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#6867]
Task Breakdown

- [x] Move reusable code from existing `Microsoft.SemanticKernel.Connectors.OpenAI` project to the new project
- [x] Create `Microsoft.SemanticKernel.Connectors.AzureOpenAI` unit test project and move tests
- [x] Upgrade to use `Azure.AI.OpenAI` v2
- [x] Test the `WithData` functionality still works 
- [x] Test coverage must be >80%
- [x] Integration tests must cover all key scenarios

**Comment by SergeyMenshykh** [comment]
Done
