### ISSUE TITLE
.NET: Create specialized TextChunker plugin

### ISSUE THREAD

**Issue by Kevdome3000** [microsoft/semantic-kernel#688]
I'd like the ability to use specialized chunkers based on the file type to ingest data. A great example use case is the GitHub qa sample app, which only parses markdown files to summarize a repository. That assumes proper documentation. But if it could parse say .cs, .py  or the other language file extensions, the GithubSkill would be a lot more powerful because it isn't reliant on robust documentation. 

I can provide a starting point for chunkers for both .cs and .py files, it's just not clear where in the SDK they belong

**Comment by evchaki** [comment]
@shawncal can you reply what folder would be the best place to put chunkers

**Comment by Kevdome3000** [comment]
this was meant for .Net just FYI

**Comment by Kevdome3000** [comment]
bump

Also wondering if extending DocumentSkill would be a better place to implement chunkers

**Comment by microsoftShannon** [comment]
@dluc Can we look into this for the backlog?

**Comment by matthewbolanos** [comment]
> Also wondering if extending DocumentSkill would be a better place to implement chunkers

I like the idea of making chunkers plugins/functions

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.

**Comment by williambohrmann3** [comment]
LangChain has the ability to [chunk code](https://python.langchain.com/v0.2/docs/how_to/code_splitter/) by [programming language](https://api.python.langchain.com/en/latest/base/langchain_text_splitters.base.Language.html). This would be a great feature to have in SK, as I would like to add code chunks into a vector database for various languages like Swift/Kotlin/C#.

**Comment by evchaki** [comment]
@williambohrmann3  - I like the idea.  Can you describe the use case for this for your users?

**Comment by williambohrmann3** [comment]
@evchaki for a "chat with doc & codebase" feature (implemented w/ RAG). We have code samples in various programming languages already chunked, but I think there's room for more variety in chunking strategies. An intelligent chunker might chunk by constructors and class definitions, or simply take advantage of language-specific delimiters. The hope is to improve semantics of chunks containing code to better ground an LLM.
