### ISSUE TITLE
Improve copilot-sample-app exception handling when handling speechToken

### ISSUE THREAD

**Issue by cchighman** [microsoft/semantic-kernel#689]
By default, the appsettings config leaves Region parameter blank for AzureSpeech.
![image](https://user-images.githubusercontent.com/659214/234762955-0aaf984d-1191-4d4c-b9ff-48c4b2d52dfb.png)

The webapp makes a call by default to fetch a speech token.
![image](https://user-images.githubusercontent.com/659214/234762647-5657637d-dbb6-45f8-98d6-0e04cb31d419.png)

No validation is in place and, because the param is blank by default, it will result in a malformed URL.
![image](https://user-images.githubusercontent.com/659214/234762895-372b3383-70df-40ec-8a64-54dc34f636f4.png)

It's really a trivial thing for a sample app but perhaps a way I could contribute to help improve provided this sample app has been very helpful to get me going.

Is there any appetite to contribute back to the sample apps in efforts to improve experience ?

**Comment by evchaki** [comment]
@cchighman , thanks for catching this, we would love a PR to help catch this blank scenario. @amsacha

**Comment by amsacha** [comment]
We merged in a fix for this 2 days ago, https://github.com/microsoft/semantic-kernel/pull/652. But yes we would love contributions from the community.
