### ISSUE TITLE
.Net: Remove the OpenApiFunctionExecutionParameters.OperationsToExclude property

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#6892]
The OpenAPI operations can be filtered/excluded/modified by OpenAPI function filters - https://github.com/microsoft/semantic-kernel/issues/6890.

**Comment by markwallace-microsoft** [comment]
We've introduced a new way that uses predicates/callback to filter out OpenAPI operations before they parsed. It's only available when using the parser directly. Over the time we will propagate the callback to the settings class and will obsolete the OperationsToExclude property when people will start asking about it. So, the task is not needed anymore and can be closed.
