### ISSUE TITLE
Python: KernelArguments should be optional if there are no arguments

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#6930]
When there are no arguments the developer wants to pass in, the arguments parameter should be optional

This is what it looks like today

```python
result = (await chat_completion.get_chat_message_contents(
    chat_history=history,
    settings=execution_settings,
    kernel=kernel,
    arguments=KernelArguments(),
))[0]
```

I should be able to write instead...

```python
result = (await chat_completion.get_chat_message_contents(
    chat_history=history,
    settings=execution_settings,
    kernel=kernel,
))[0]
```

**Comment by eavanvalkenburg** [comment]
@matthewbolanos they are actually only needed when doing auto invoke function, calling, changing that to use a default when not supplied.
