### ISSUE TITLE
Inconsistent handling in QdrantVectorDbClient results in copilot-sample-app to fail when qdrant is used for Memories

### ISSUE THREAD

**Issue by cchighman** [microsoft/semantic-kernel#694]
**Describe the bug**
When MemoriesStore is set to qdrant, copilot-sample-app is non-functional due to handling of ISemanticTextMemory.SearchAsync when existing results are not found.  SearchAsync returns an IAsyncEnumerable object but will throw if a result is not found in the underlying source in all places where _response.EnsureSuccessStatusCode()_ is not being implicitly caught.

Currently, for copilot-sample-app, it is impacted due to the Qdrant Skill as seen in this list below where this response method is used.
![image](https://user-images.githubusercontent.com/659214/234844230-9aca825e-3c96-4984-b6ca-80c7d315e84e.png)

There is an inconsistency across _QdrantVectorDbClient_ source for how _response.EnsureSuccessStatusCode()_ is handled when performing a search.  Here is an example where it's being caught and tracing "not found" which I believe is the ideal way to handle this provided a collection is returned.  **GOOD**
![image](https://user-images.githubusercontent.com/659214/234844895-5931b914-d409-4703-869d-7726458f3c3e.png)

_SearchAsync()_ for Qdrant uses _FindNearestInCollectionAsync()_ to return back a collection.  In the example below, there isn't the same try/catch handling and just below, you'll see a check for _Any()_.  The code inside that block is unreachable as if there were not any results returned, _response.EnsureSuccessStatusCode()_ would throw.    **BAD**
![image](https://user-images.githubusercontent.com/659214/234845440-942ee5a4-f5ed-41fc-a9f0-c3bd9fabd5cb.png)

For the interim, I changed the semantics around how _SearchAsync()_ is used in copilot-sample-app similar to below where its catching when _SearchAsync()_ throws having a 404 not found.  
![image](https://user-images.githubusercontent.com/659214/234847648-a5ae1857-f801-4caf-91b6-cf4f555e5322.png)

The current handling in copilot-sample-app assumes _SearchAsync()_ will not throw.  Because it does throw, it bubbles itself all the way up and fails the completion which resulted in this skill to be executed.  I believe this handling below is correct so long as we correctly ensure that _SearchAsync()_  will not throw if results are not found like the other operations in that class.
![image](https://user-images.githubusercontent.com/659214/234854637-17c5abd5-132e-45a0-9010-5849c775b91f.png)

The ideal change that should occur, in my opinion, is to make the handling in _QdrantVectorDbClient_ consistent when performing a search by adding the try/catch semantics to _FindNearestInCollectionAsync()_ to match each other search operation which does the same.  This would mitigate the issues observed in the copilot-sample-app.  

Looking at the definition for the method in question, there doesn't appear to be any intent to throw when a search doesn't return any results.  As mentioned above, other cases of vector search in the same class which return the same collection are explicit in catching to make sure an exception is not thrown. 
![image](https://user-images.githubusercontent.com/659214/234850322-8dff5cb8-0bda-4a45-9cb3-3b8f1426406e.png)

The risk with this change would mean any consumers who are using qdrant and working around this issue by explicitly catching a 404 error as opposed to simply checking if the object has any results would need to update handling by switching from using a try/catch to checking if the collection returned has any results.  This is in line with all other search capabilities in this class.

If its thought that we should not make this handling consistent in the way described above, I would then propose that we add tags to the method to indicate the exception thrown and accept a pull request to convert copilot-sample-app handling to use the try/catch method I showed above as today its attempting to check if the resulting collection has _Any()_.

Aside from any added tests, the change itself would amount to 4-5 lines, and also resolves current failures in copilot-sample-app when using qdrant.

**I would like to submit a pull request to resolve this issue.**

**To Reproduce**
1. Apply settings as specified in README for copilot-sample-app.
2. Change MemoriesStore in webapi appsettings.json from "volatile" to "qdrant".
3. dotnet run in webapi folder and yarn start in webapp folder.
4. Send a prompt in the web UI..
5. Observe Error in web UI.

**Expected behavior**
When a result isn't found in the vector database, it should create a new collection, and not result in an overall failure.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IDE:  [VS Code]

**Comment by evchaki** [comment]
@cchighman , thanks for finding this.  @adrianwyatt  is this the PR you are working on to fix this issue?

**Comment by cchighman** [comment]
> @cchighman , thanks for finding this. @adrianwyatt is this the PR you are working on to fix this issue?

Sure thing.  Let me know if there is an opportunity here where I could make a contribution.  Very interested in getting involved.

**Comment by cchighman** [comment]
If @adrianwyatt hasn't already covered this scenario, it's trivial change to make. I notice we dont have any unit tests for QdrantVectorDBClient either.  I'm open to add some to sweeten the deal.    :)

**Comment by cchighman** [comment]
It looks like @adrianwyatt's commit is targeting behavior from IAsyncEnumerators when yielding that's not supported based on a documented upstream issue which is different from the behavior outlined above that occurs when an exception is thrown that's not expected.
