### ISSUE TITLE
Python: Create a sample showing how to perform function calling with a local model

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#6944]
Use Nexus Raven as the model for these samples

- [ ] Single function
- [ ] Parallel calls
- [ ] No calls
- [ ] Multiple functions
- [ ] Nested functions

**Comment by eavanvalkenburg** [comment]
will have to follow #6496 and maybe also #6498 #6841 or #6761 since we currently do not support any local models that can support function calling, with the possible exection of Ollama, but there are tasks to further refine Ollama.
