### ISSUE TITLE
.Net: Python: Learn Site `Getting Started with Notebooks` Python steps include dotnet as well

### ISSUE THREAD

**Issue by moonbox3** [microsoft/semantic-kernel#6954]
The "[Getting Started with Notebooks](https://learn.microsoft.com/en-us/semantic-kernel/get-started/quick-start-guide?pivots=programming-language-python#quickly-get-started-with-notebooks)" section, with Python code selected shows steps for both Python and dotnet. If you select the dotnet programming language, the steps do not show up.

Selecting Python code:

![image](https://github.com/microsoft/semantic-kernel/assets/35585003/fbf99d74-f13d-4eb9-8bad-1492ac1a2fee)

**Comment by MohMaz** [comment]
@moonbox3  are you still able to see this issue? I wasn't able to reproduce, probably they have fixed it already?
<img width="897" alt="image" src="https://github.com/user-attachments/assets/31f02209-22d8-4214-8994-2a5053083e49">

**Comment by moonbox3** [comment]
Hi @MohMaz, thanks for reaching out. We updated the links a few weeks ago, and hadn't closed this issue. Closing it now. Thanks.
