### ISSUE TITLE
.Net: Move Qdrant connector to use Qdrant.Client

### ISSUE THREAD

**Issue by timheuer** [microsoft/semantic-kernel#6977]
Similar to Milvus, the Qdrant connector should consider moving to use the Qdrant.Client 
- https://github.com/qdrant/qdrant-dotnet
- https://www.nuget.org/packages/Qdrant.Client/

**Comment by stephentoub** [comment]
cc: @roji

**Comment by dmytrostruk** [comment]
FYI: `Qdrant.Client` is already used in new connector implementation: https://github.com/microsoft/semantic-kernel/pull/6904

**Comment by markwallace-microsoft** [comment]
@timheuer thanks for creating this issue. I am going to close this as this is in progress as part of our Memory Connector update.

**Comment by timheuer** [comment]
This is great! I have one question but will ask on the merged item!
