### ISSUE TITLE
Python: Bug: FunctionChoiceBehavior.NoneInvoke() / 'none' is not working as expected

### ISSUE THREAD

**Issue by nmoeller** [microsoft/semantic-kernel#7020]
**Describe the bug**
When setting the `FunctionChoiceBehavior.None()` in `OpenAIChatPromptExecutionSettings` the Model does not respond with Funcion Calls anymore.

This is probably due to these [lines of code](https://github.com/microsoft/semantic-kernel/blob/775994e6c8f6a3f9dff331a4c94f56b8929bb7ae/python/semantic_kernel/connectors/ai/function_calling_utils.py#L29)

These Lines forwarding the Type of the behavior to the API, but when forwarding `none` it will result in no more function calls.
[Source](https://github.com/openai/openai-openapi/blob/0df12d7b3ac997517fda38842f41d99a8e7f4e6a/openapi.yaml#L7625) 

**To Reproduce**
1. Go to `/python/samples/concepts/auto_function_calling/chat_gpt_api_function_calling.py`
2. Change the FunctionChoiceBehavior to 'none' or to 'NoneInvoke()'
3. Ask the Bot Question for the Time Plugin
4. The bot is not able to use the TimePlugin because the api cannot give back function calls in the response

**Expected behavior**

The expected behavior is that the Model should return the FunctionCall Result. Since the Behaviors is made to give back only the function calls.

**Comment by moonbox3** [comment]
Hello @nmoeller. This is not a bug. We're providing abstractions to the model that allow for the following: `Auto`, `None` and `Required`. The choice `None` means that you advertise the functions in the kernel (or a subset of them) to the model and it can talk about how it would use those functions if were to. 

You can see the behavior described in OpenAI's docs [here](https://platform.openai.com/docs/guides/function-calling/function-calling-behavior): "To disable function calling and force the model to only generate a user-facing message."
