### ISSUE TITLE
.Net: New Feature: Cancel token generation

### ISSUE THREAD

**Issue by Tyler-R-Kendrick** [microsoft/semantic-kernel#7027]
Based on the discussion [here](https://github.com/microsoft/semantic-kernel/discussions/7006), I'd like to be able to cancel the llm request from the function filter (ideally using a cancellation token).

I can see two solutions that make sense here.

1.) The cancellation token from the originating HttpRequest is passed through the context as a new property.
2.) The "Result" property cancels the originating request when it is a Task or IAsyncEnumerable that has been cancelled.

**Comment by dmytrostruk** [comment]
Closing this issue as per internal discussion:
1. It's possible to stop a request to LLM from filter by throwing an exception at specific point.
2. Cancellation token is still required to monitor for cancellations and pass original token to subsequent async operations inside filters. PR: https://github.com/microsoft/semantic-kernel/pull/7033
