### ISSUE TITLE
.Net Agents Assistants V2 - Establish project structure / dependencies

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#7031]
Establish feature branch that specific V2 features may target.

Unable to layer / stage individual features onto the existing `Microsoft.SemanticKernel.Agents.OpenAI` project / package due to dependency conflicts.

**Comment by Esalguero007** [comment]
What does this do specifically?

**Comment by crickman** [comment]
@Esalguero007 - This is an initial dev task to setup the framework for switching dependencies to `Azure.AI.OpenAI` V2 and Open AI Assistant V2 features.
