### ISSUE TITLE
.Net Docs GettingStartedWithAgents Example links needs updating. Bad link

### ISSUE THREAD

**Issue by aaronba** [microsoft/semantic-kernel#7032]
On this file: https://github.com/microsoft/semantic-kernel/tree/main/dotnet/samples/GettingStartedWithAgents/README.md

Step7_OpenAIAssistant	How to create an Open AI Assistant agent.
Returns a 404 when pointing to https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/GettingStartedWithAgents/Step7_OpenAIAssistant.cs

More Info:
 
Step 7 is now Logging (Step7_Logging.cs)
And Step 8 is OpenAIAssistant. (Step8_OpenAIAssistant.cs)

**Comment by aaronba** [comment]
Seems to be related to recent
https://github.com/microsoft/semantic-kernel/pull/6933 updates

**Comment by RogerBarreto** [comment]
Paths are fixed
