### ISSUE TITLE
Python: Bug: sk_function_context_parameter

### ISSUE THREAD

**Issue by minkyu-choi07** [microsoft/semantic-kernel#7092]
**Describe the bug**
What's the equivalent method or decorator of `sk_function_context_parameter` in the newer release. I can't fund the good example from samples.

I do understand we now use `kernel_function`. However, passing arguments to the function is still unknown.

**Comment by eavanvalkenburg** [comment]
@minkyu-choi07 the equivalent is the usage of Annotated for a parameter, you can see that here: https://github.com/microsoft/semantic-kernel/blob/e77ffdf84a29311ac66ecb227c4421f10fb1fbad/python/samples/concepts/plugins/openai_function_calling_with_custom_plugin.py#L23 and also all core_plugins have been moved to that model!

**Comment by moonbox3** [comment]
Closing as the solution has been provided.
