### ISSUE TITLE
Verify that OpenAI execution settings can be used with Azure OpenAI Connectors

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#7110]
At the moment `OpenAIPromptExecutionSettings` work for OpenAI and Azure OpenAI services. After the upgrade to OpenAI and Azure.AI.OpenAI V2 SDK's this behaviour should still work

While testing, pay attention to the serialization/deserialization aspect of working with prompt execution settings. E.g. - https://github.com/microsoft/semantic-kernel/pull/7102#discussion_r1666509479

**Comment by SergeyMenshykh** [comment]
This PR fixes a serialization issue identified while verifying whether the `AzureOpenAIChatCompletionService` can work with `OpenAIPromptExecutionSettings` or not. - https://github.com/microsoft/semantic-kernel/pull/7265/files#r1678277558
