### ISSUE TITLE
.Net: Bug: Hard dependency on Microsoft.Extensions.DependencyInjection.Abstractions 8.0.1

### ISSUE THREAD

**Issue by johnholliday** [microsoft/semantic-kernel#7124]
**Describe the bug**
The nuget package fails to resolve because of the hard dependency on the 8.0.1 version of the Microsoft.Extensions.DependencyInjection.Abstractions module, when even the Microsoft.Extensions.DependencyInjection module is declared as (>= 8.0.0).

**To Reproduce**
1. Create a project and add the Microsoft.Extensions.DependencyInjection module version 8.0.0.
2. Create a separate dependent project and add the Microsoft.SemanticKernel module.
3. Run the main project

**Expected behavior**
The Microsoft.SemanticKernel module should depend on Microsoft.Extensions.DependencyInjection.Abstractions (>= 8.0.0) instead of (>= 8.0.1).

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: Visual Studio 2022
 - Language: C#
 - Source: Microsoft.SemanticKernal 1.15.1

**Additional context**

**Comment by johnholliday** [comment]
Has there been any progress on this issue?  If not, then can someone suggest a workaround?

**Comment by markwallace-microsoft** [comment]
@johnholliday I followed your instructions are tried to reproduce this with the very latest SK release. Things seem to work fine for me, can you take a look and let me know if you are doing something different?

![image](https://github.com/user-attachments/assets/46b17a1d-e1bc-432a-be65-a62cf1ea5097)

**Comment by markwallace-microsoft** [comment]
Closing as the issue cannot be reproduced
