### ISSUE TITLE
.Net Gemini response grounding with Google Search

### ISSUE THREAD

**Issue by TRybina132** [microsoft/semantic-kernel#7145]
&nbsp;&nbsp;&nbsp;Google gemini model has response grounding with Google Search feature, which allows prevent hallucinations when generating response and generate responses based on information found on internet. [Here is more information about grounding](https://cloud.google.com/vertex-ai/generative-ai/docs/grounding/overview#ground-public)
<br/>
You need to include `googleSearchRetrieval` tool in `tools` inside request body to use grounding with google search. 
<img width="903" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/98330987/6053ae9a-5ce9-4981-ad9e-f63c8ddd6c7f">
[Full gemini grounding documentation](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/ground-gemini)
<br/>
It can be implemented by allowing to add tools to the `GeminiPromptExecutionSettings`. For example new property with list of these tools can be created in `GeminiPromptExecutionSettings`. If there any other way how gemini grounding can be used in Semantic kernel connector, please let me know.

**Comment by robertsonh** [comment]
Why is this closed?

**Comment by jmcjm** [comment]
It would be really nice and useful if SK had support for URL context and googleSearchRetrieval Tools
