### ISSUE TITLE
New Feature: Add custom fields into actual model request.

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/semantic-kernel#7147]
From time to time, I need to add some options to the final request, like here.
I can't get into the request right now.

Can be related to:
#7015 #7145

![image](https://github.com/microsoft/semantic-kernel/assets/4385716/d16088ca-054c-4b2b-8678-f65c0a6fba3d)

This is easier to change manually than to change the integration with the model every time.

**Comment by markwallace-microsoft** [comment]
@KSemenenko thanks for the issue. Are you using the Google connector here? If yes, are we missing options in our execution settings?

**Comment by markwallace-microsoft** [comment]
Will use https://github.com/microsoft/semantic-kernel/issues/7145 for tracking
