### ISSUE TITLE
.Net: OpenAI Migration Breaking Changes

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#7197]
These are the breaking changes that have been made to `OpenAIChatCompletionService` and its associated classes during the migration to OpenAI SDK v2. The list should be reviewed to minimize the number of breaking changes.

- `OpenAIChatCompletionService`
  - Metadata:  https://github.com/microsoft/semantic-kernel/issues/7066
    - The `Created` key is renamed to `CreatedAt`.
    - The `Usage` metadata type has changed from `CompletionsUsage` to `ChatTokenUsage`.
    - The `FinishReason` metadata string has changed: stop to Stop, tool_calls to ToolCalls, etc.
    - The `LogProbabilityInfo` type has changed from `ChatChoiceLogProbabilityInfo` to `IReadOnlyList<ChatTokenLogProbabilityInfo>`.
    - The `FinishDetails`, `Index`, and `Enhancements` metadata have been removed.
 
- `OpenAIChatMessageContent`
  - The `Tools` property type has changed from `IReadOnlyList<ChatCompletionsToolCall>` to `IReadOnlyList<ChatToolCall>`.
  - Inner content type has changed from `ChatCompletionsFunctionToolCall` to `ChatToolCall`.
  - Metadata:
    - Type of `ChatResponseMessage.FunctionToolCalls` metadata has changed from `IEnumerable<ChatCompletionsFunctionToolCall>` to `IEnumerable<ChatToolCall>` https://github.com/microsoft/semantic-kernel/issues/7055

- `OpenAIStreamingChatMessageContent`.
  - The `FinishReason` property type has changed from `CompletionsFinishReason` to `FinishReason`.
  - The `ToolCallUpdate` property has been renamed to `ToolCallUpdates` and its type has changed from `StreamingToolCallUpdate?` to `IReadOnlyList<StreamingChatToolCallUpdate>?`.
  - The `AuthorName` property is not initialized because it's not provided by the underlying library anymore

- `OpenAIPromptExecutionSettings`
  - The `ResultsPerPrompt` property has beed removed

- `OpenAIFunction`
  - Return type of the `ToFunctionDefinition()` method has changed from `FunctionDefinition` to `ChatTool`.

- `OpenAITextGenerationService`
  - The service has not been migrated because it's not supported by the new version of the Azure SDK.

- `OpenAITextEmbeddingGenerationService`
  - `KernelBuilder` extension `AddOpenAITextEmbeddingGeneration`
    - Optional parameter `Uri? endpoint` added between `serviceId` and `httpClient`.
- `OpenAITextToImageService`
  - `KernelBuilder` non-breaking glass extension `AddOpenAITextToImage` parameters reordered, following other extension patterns
 
     | | 1st | 2nd | 3rd | 4th | 5th  | 6th |
     | --- | --- | --- | --- | --- | --- | --- |
     | Old | apiKey | orgId | modelId | serviceId | httpClient | -- | 
     | New | modelId | apiKey | orgId | serviceId | endpoint | httpClient |

- `OpenAITextToAudioService`

- `OpenAIAudioToTextService`
  - `OpenAIAudioToTextExecutionSettings`
    - Metadata:
      - The `Segments` metadata type has changed from `IReadOnlyList<AudioTranscriptionSegment>` to `IReadOnlyList<TranscribedSegment>`.

- `OpenAIFileService`
  - Deprecated - Recommended usage of {Azure}OpenAI SDK File Client.
  
## Additions (Non-Breaking)

- `OpenAITextEmbeddingGenerationService`
  - Added optional `Uri? endpoint` to non-breaking glass extension methods as last parameter. 
    - Not throwing/verifying when apiKey is not provided via extension method (this check is done by the `ClientCore`

- `OpenAITextToImageService`
  - Added new constructor for Breaking Glass, accepting `OpenAIClient`
  - Added extension method `AddOpenAITextToImage(OpenAIClient)` for both `IServiceCollection` and `IKernelBuilder` for breaking glass scenario.

**Comment by Rickcau** [comment]
I am leveraging the ResultsPerPrompt for a quorum pattern for intent recognition.   So is that some other approach that can be used?
