### ISSUE TITLE
Semantic Kernel VS Code extension select AOAI endpoint should allow AAD tenant selection

### ISSUE THREAD

**Issue by PlagueHO** [microsoft/semantic-kernel#720]
In the Visual Studio Code SK extension, when selecting an Azure OpenAI Service endpoint, it is not possible to select subscriptions that are not in the default tenant.

This prevents using AOAI endpoints that are in Azure subscriptions that the logged in user account is an external user in.

**Comment by evchaki** [comment]
@PlagueHO , thanks for using the extension!  Good idea, for the short term you would need to change your user account in the Azure extension to flip between the two (which is not ideal).

**Comment by markwallace-microsoft** [comment]
Hi @PlagueHO can you try to run the "Add AI Endpoint" command. This allows you to configure an Azure OpenAI or OpenAI endpoint without being logged in. 

If you have the details of an Azure OpenAI endpoint that you want to use
- Type "Add AI Endpoint" and you will be prompted for the following information:
    - Endpoint type, select "completion"
    - Completion label, the default of "Completion" is fine
    - Completion AI Service, select AzureOpenAI
    - Completion deployment or model id e.g., text-davinci-003
    - Completion endpoint URI e.g., https://contoso-openai.azure.com/
    - Completion endpoint API key (this will be stored in VS Code secure storage)

**Comment by microsoftShannon** [comment]
@PlagueHO, can you let us know if Mark's suggestion worked?  Thanks!
