### ISSUE TITLE
.Net: Bug: Blazor WASM is not totally supported from version >= 1.7,1

### ISSUE THREAD

**Issue by antonio8101** [microsoft/semantic-kernel#7201]
**Describe the bug**
Microsoft.SemanticKernel.Connectors.OpenAI version 1.8 or greater is throwing: <mark>Microsoft.SemanticKernel.HttpOperationException: Invalid value for 'content': expected a string, got null.</mark> when used in a Blazor WebAssembly application

**To Reproduce**
1. Create a new Blazor application with WebAssembly as Interactive Render Mode
2. Install Semantic Kernel and Microsoft.SemanticKernel.Connectors.OpenAI with a version greater than 1.7.1
3. Build a Semantic Kernel with AddAzureOpenAIChatCompletion and Provide as a Singleton Service to the WebAssemblyHostBuilder
4. Using either kernel.InvokeAsync or chatCompletionService.GetChatMessageContentAsync will not work

**Expected behavior**
Should work the same as with Microsoft.SemanticKernel.Connectors.OpenAI 1.7.1

**Platform**
- OS: Windows
- IDE: Visual Studio
- Language: C#
- Source: Microsoft.SemanticKernel.Connectors.OpenAI Version > 1.7,1

**Additional context**
I want to use Semantic Kernel and Kernel Memory, new versions of Kernel Memory requires a newer version of Microsoft.SemanticKernel.Connectors.OpenAI.

**Comment by markwallace-microsoft** [comment]
@antonio8101 Is this still an issue?

**Comment by antonio8101** [comment]
@markwallace-microsoft I can now update to version `1.30.0` without any issue. Then I think We can close it.
