### ISSUE TITLE
Invalid character in plan

### ISSUE THREAD

**Issue by dedalo** [microsoft/semantic-kernel#721]
**Describe the bug**
The plan has invalid XML character and fails with exception 
System.Xml.XmlException: '<', hexadecimal value 0x3C, is an invalid attribute character.

**To Reproduce**
using the sequencial planner, with gpt 35, if you add a parameter to a skill like userId, it injects a value <USER_ID> in the plan.

**Expected behavior**
plan should be valid XML

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Compiling from master

**Additional context**
OPENAI

**Comment by microsoftShannon** [comment]
@lemillermicrosoft can you take a look at this?

**Comment by lemillermicrosoft** [comment]
Can you confirm @dedalo whether the exception thrown is PlanningException.InvalidPlan (which then wraps the XML exception you note) or not? This was done in #707. 

However yeah, gpt35 is failing in this case, something potential with this planner strategy. Try including skills that can be used to retrieve the userid to see if it performs better.

**Comment by dedalo** [comment]
mmm the exception was an unhandled exeption, cannot reproduce enymore becouse all is migrated to actionplan, and it uses json now (have other issues with that)

In general I think is model issues. At least in my case action planner did most of the trick.
