### ISSUE TITLE
ValidationException name conflicts with .NET exception type

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#722]
System.ComponentModel.DataAnnotations already has a type named "ValidationException".  If someone is using both "System.ComponentModel.DataAnnotations" and "Microsoft.SemanticKernel.Diagnostics", they'll get ambiguity errors when they try to reference "ValidationException". 
```
CS0104	'ValidationException' is an ambiguous reference between 'Microsoft.SemanticKernel.Diagnostics.ValidationException' and 'System.ComponentModel.DataAnnotations.ValidationException'
```

Also if someone isn't importing Microsoft.SemanticKernel.Diagnostics and use VS's auto-fixes to import the right namespace, they'll be presented with multiple options for which namespace to import, and the .NET one will be first in the list.

 We should rename "ValidationException".  Or... we should get rid of it entirely, and use standard exceptions for corresponding conditions, e.g. DirectoryNotFoundException instead of ValidationException with ValidationException.ErrorCodes.DirectoryNotFound.

**Comment by microsoftShannon** [comment]
@shawncal can you take a look at this?

**Comment by stephentoub** [comment]
The exception has actually now been removed as of https://github.com/microsoft/semantic-kernel/pull/749
