### ISSUE TITLE
New Feature: Agents story - Support Different Chat Models

### ISSUE THREAD

**Issue by joslat** [microsoft/semantic-kernel#7240]
Enable custom chat management to support various types of interactions such as 1-1, group, sequential, round robin, etc., through a flexible extensibility model. 
Yes, again the Plug-in model trough an interface (IoC/Strategy pattern) 
It is essential to integrate this capability into the core of the SDK rather than relying on an ad-hoc AutoGen implementation to ensure robust and versatile chat management. 

Then any framework can use SK (Semantic Kernel) to implement their Agent implementations and constructs. Or provide a nuget package to enable it to run in SK.

**Comment by crickman** [comment]
We already support an extensible selection-strategy that covers: 1-1, group, sequential, and round robin.  Now that the process framework is online, we have the ability to coordinate other complex patterns, as described in:

- https://github.com/microsoft/semantic-kernel/issues/7242
- https://github.com/microsoft/semantic-kernel/issues/7241
- https://github.com/microsoft/semantic-kernel/issues/7238
