### ISSUE TITLE
New Feature: Agents story - EPIC - Enhance Base Agent & chat workflows Functionality

### ISSUE THREAD

**Issue by joslat** [microsoft/semantic-kernel#7248]
Enhancing the base agent functionality is essential for implementing various current and future AutoGen agent & chat constructs. 
This foundational improvement will allow the SDK to support a wider range of capabilities and use cases, ensuring it remains versatile and future-proof.

This is a container for all the other sub features:
- https://github.com/microsoft/semantic-kernel/issues/7247
- https://github.com/microsoft/semantic-kernel/issues/7246
- https://github.com/microsoft/semantic-kernel/issues/7245
- https://github.com/microsoft/semantic-kernel/issues/7244
- https://github.com/microsoft/semantic-kernel/issues/7243
- https://github.com/microsoft/semantic-kernel/issues/7242
- https://github.com/microsoft/semantic-kernel/issues/7241
- https://github.com/microsoft/semantic-kernel/issues/7240
- https://github.com/microsoft/semantic-kernel/issues/7239
- https://github.com/microsoft/semantic-kernel/issues/7238

**Comment by joslat** [comment]
Please add "enhancements" tag :)

**Comment by crickman** [comment]
Individual tasks exist
