### ISSUE TITLE
Link to reporting issues in CONTRIBUTING.md is broken

### ISSUE THREAD

**Issue by bkrabach** [microsoft/semantic-kernel#725]
Link to the issues page in the CONTRIBUTING.md is pointing to https://github.com/semantic-kernel/issues instead of https://github.com/microsoft/semantic-kernel/issues

**Comment by poweihuang0817** [comment]
https://github.com/microsoft/semantic-kernel/pull/746
hi, this PR is solving it.

**Comment by poweihuang0817** [comment]
PR is merged
