### ISSUE TITLE
kernel.CreateSemanticFunction functionName is marked optional, but is not optional

### ISSUE THREAD

**Issue by bkrabach** [microsoft/semantic-kernel#726]
**Describe the bug**
If using the overload for kernel.CreateSemanticFunction that takes a PromptTemplateConfig, the functionName is marked optional, but if you execute the code it will throw an exception that functionName is not optional.

If you use the overload that takes just a promptTemplate (everything else optional), then you omit the functionName and when executing it will work, despite not having a functionName defined.

@shawncal

**Comment by dluc** [comment]
#849 should fix this too

**Comment by craigomatic** [comment]
Closing given #849 - please reopen if needed!
