### ISSUE TITLE
.Net: All dotnet/src/Functions/Functions.OpenApi/Model/RestApiXXX.cs should be internal

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#7281]
**Describe the bug**
All dotnet/src/Functions/Functions.OpenApi/Model/RestApiXXX.cs should be internal because they are only used by internal implementations

**Comment by atiq-bs23** [comment]
@markwallace-microsoft Can I create a pull request for this?

**Comment by SergeyMenshykh** [comment]
It's not relevant anymore because we are going to expose RestApiOperation class and all its dependencies via KernelFunction metadata.
