### ISSUE TITLE
Python: Bug:  Broken link in tutorial - semantic-kernel/python/samples/getting_started/05-using-the-planner.ipynb

### ISSUE THREAD

**Issue by SeryioGonzalez** [microsoft/semantic-kernel#7284]
**Describe the bug**
One step in the tutorial points to a broken link

**To Reproduce**
See the block:

The sequential planner is an XML-based step-by-step planner. You can see the prompt used for it here (https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/planning/sequential_planner/Plugins/SequentialPlanning/skprompt.txt)

**Expected behavior**
Update the link:

(https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/planners/sequential_planner/Plugins/SequentialPlanning/skprompt.txt)

See the path planning has been renamed to planners in the code, but not in the link above

**Comment by moonbox3** [comment]
@SeryioGonzalez, thanks for filing. Would you like to create a PR to fix it?

**Comment by moonbox3** [comment]
> Sure! I actually tried pushing you a PR, but realize had no permits

The PR must be generated from a fork of the repo.
