### ISSUE TITLE
.Net: New Feature: IChatCompletionService to expose token count api

### ISSUE THREAD

**Issue by colombod** [microsoft/semantic-kernel#7289]
---

Having access top the tokenizer that is appropriate for the underlying LLM of an IChatCompletionService instance would simplify a lot the user code for handling content size correctly.

---

**Comment by matthewbolanos** [comment]
Are you able to share what scenarios you're wanting to light up with a tokenizer on the `IChatCompletionService`? Is this for telemetry needs or something else?
