### ISSUE TITLE
.Net: ContextVariables.Set vs ContextVariables.Update - confusion in context-variables-chat dotnet notebook sample

### ISSUE THREAD

**Issue by bkrabach** [microsoft/semantic-kernel#729]
**Describe the bug**
There does not appear to be any documentation for how ContextVariables work (if there is somewhere, I could not find it - would be great if there were links to relevant docs inline in the markdown in the sample), so not sure if this is a bug or just confusing.

Re: https://github.com/microsoft/semantic-kernel/blob/main/samples/notebooks/dotnet/04-context-variables-chat.ipynb

In most cases throughout the sample, `context.Set` is being used to set values to specific context properties.  In one case, and only one case, `context.Update` is being called instead.  From what I've been told (had to ask someone, wasn't clear due to lack of documentation or comments), the `context.Update` is equivalent to `context.Set("input", value)`?

If this is the correct understanding, it's not clear why `context.Update` is being called in the sample?  I had to ask (again, not clear), but `Constole.WriteLine(context)` returns `context.Result`, so is this use of `context.Update` being made only to allow the next `Console.WriteLine(context)` to display the value?

The rest of the sample uses `context.Set` to update the "history" value.  From my understanding (and this was not clear and took a lot of thinking through), the end result of "context" values looks something like this?

{
  "input": "\nHuman: {human_input}\nMelody: {bot_answer}\n", // first value entered
  "human_input", "could you list some more books I could read about the topic(s) you mentioned?", // last value entered
  "history": ".... full history of conversation ...",
}

And `context.Result` would return what?  Is `context.Result` a totally separate value?  Does `context.Update` affect the `context.Result` and does `kernel.RunAsync` similarly perform a `context.Update` under the hood?

As a developer, without documentation or comments describing the behavior it is hard to infer what I should expect from this sample - or more importantly, how I should expect it to work in my own code.

**Comment by craigomatic** [comment]
Do you feel that any of the updates made to the sample make ContextVariables easier for a new dev to grok @bkrabach ? 

The call to Update is still there, and I agree it seems to exist so that the next call to WriteLine drops it to the console.

**Comment by bkrabach** [comment]
The dictionary approach that replaces the prior use of `context.Set` seems to be clear (although switching from `context.Set("history", history)` to `context["history"] = history` doesn't seem to make it any easier, any real difference, etc. - just a syntax change), but it's still not clear why `context.Variables.Update(history)` is called in one case and `context["history"] = history` is used in the other two cases.  If there is a reason for this, it'd likely be helpful to add some comments to the sample at least to explain how it is different (or not) and why each is being used (use cases).

**Comment by markwallace-microsoft** [comment]
PR will be merged this week
