### ISSUE TITLE
Python: Bug: Kernel functions do not handle list and dict arguments well.

### ISSUE THREAD

**Issue by q-stefanmuscalu** [microsoft/semantic-kernel#7300]
**Describe the bug**
I am writing a kernel function where one of the parameters is a list. I have to annotate it, otherwise SK builds invalid metadata. Even after annotating the argument, the items in the list remain dictionaries and I have to transform them into instances of my class manually.

**To Reproduce**
1. Define this plugin
```python
class SearchRequest(KernelBaseModel):
    first_name: str
    last_name: str


class SearchPlugin:

    @kernel_function(
        name="Search",
        description="Search for people",
    )
    def find_person(
        self,
        queries: list[SearchRequest], "The search queries",
    ) -> str:
        for query in queries:
            print(f"Query: {query} of TYPE {type(query)}")
        return "nothing found"
```
2. Ask the agent to _search for john doe_
3. Observe the error _array schema missing items_
The error happens because the metadata sent to the `/chat/completions` endpoint looks like this:
```json
{
    "type": "function",
    "function": {
        "name": "SearchPlugin-Search",
        "description": "Search for people",
        "parameters": {
            "type": "object",
            "properties": {
                "queries": {
                    "type": "array"
                }
            },
            "required": [
                "queries"
            ]
        }
    }
}
```

4. Annotate the list to fix the error above
```python
queries: Annotated[list[SearchRequest], "The search queries"]
```
5. Ask the agent to _search for john doe_
6. Observe the output `Query: {'first_name': 'John', 'last_name': 'Doe'} of TYPE <class 'dict'>`

**Expected behavior**
I would expect the correct metadata if I don't annotate my lists. I would expect the items in the list to be objects of type `SearchRequest`, not dictionaries.

**Screenshots**

**Platform**
 - OS: Mac
 - IDE: PyCharm
 - Language: Python
 - Source: semantic kernel 1.2.0, python 3.11, Azure Open AI

**Additional context**

**Comment by eavanvalkenburg** [comment]
@moonbox3 could you have a look at this one?

**Comment by moonbox3** [comment]
Hi @q-stefanmuscalu, when you say "Observe the output `Query: {'first_name': 'John', 'last_name': 'Doe'} of TYPE <class 'dict'>`" where are you observing this?

**Comment by moonbox3** [comment]
@q-stefanmuscalu never mind, I see it's what the model outputs. Investigating.

**Comment by moonbox3** [comment]
I am seeing the following now, @q-stefanmuscalu:

```
User:> Find John Doe, Jane Smith, and Steve Smith
Mosscap:> Query: first_name='John' last_name='Doe' of TYPE <class '__main__.SearchRequest'>
Query: first_name='Jane' last_name='Smith' of TYPE <class '__main__.SearchRequest'>
Query: first_name='Steve' last_name='Smith' of TYPE <class '__main__.SearchRequest'>
```

Interestingly, the model (gpt-4o) isn't sending back a list of names in one function call like:

`[{"first_name":"John", "last_name": "Doe"}, {"first_name:"Jane", "last_name": "Smith"}, ...]`

but it rather makes individual function calls with:

`[{"first_name":"John", "last_name": "Doe"}]`
...
`[{"first_name:"Jane", "last_name": "Smith"}]`

**Comment by q-stefanmuscalu** [comment]
Thanks for investigation @moonbox3 . I'm using `gpt-4`. I guess making separate function  calls is a valid use of the api. Probably editing the descriptions and prompts would guide the model to make a single call
