### ISSUE TITLE
.Net: [Bing Skill] allow additional parameters like site restriction

### ISSUE THREAD

**Issue by iMicknl** [microsoft/semantic-kernel#733]
It would be good to allow more parameters to the [`BingConnector`](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Skills/Skills.Web/Bing/BingConnector.cs), so that for example the internet search can be limited to a single domain. See [Getting results from a specific site
](https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/filter-answers#getting-results-from-a-specific-site).

For enterprise search purposes, you would want to limit the skill to only your company website e.g.

[Advanced search keywords](https://support.microsoft.com/en-us/topic/advanced-search-keywords-ea595928-5d63-4a0b-9c6b-0b769865e78a)

**Comment by microsoftShannon** [comment]
This is a great suggestion, we'll add it to our backlog.  Of course, we're always open to contributions from the community.

**Comment by evchaki** [comment]
@iMicknl , feel free to do a PR also to add more parameters to the connector.

**Comment by Hariom98** [comment]
I am a .NET developer and have been working on LLM (OpenAI) for over a year, using both .NET and Python 3. I am new to open-source contributions, and this will be my first one.

May I pick up issue `[#733](https://github.com/microsoft/semantic-kernel/issues/733)`?

I will implement these [Advanced Search Keywords](https://support.microsoft.com/en-us/topic/advanced-search-keywords-ea595928-5d63-4a0b-9c6b-0b769865e78a) in `BingConnector.cs`.

**Comment by evchaki** [comment]
Closing for now, feel free to do a PR on this.
