### ISSUE TITLE
Python: Bug: Chat history serializing error

### ISSUE THREAD

**Issue by nguyena2** [microsoft/semantic-kernel#7340]
**Describe the bug**
I have a user message and an azure open ai assistant message in the chat history. I'm trying to serialize the chat history object to a json string so I can save it. When I try to use the serialize function in the chat history class, I get the error below.

"Error: Unable to serialize ChatHistory to JSON: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'"

**To Reproduce**

**Expected behavior**
Get a json string

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: Python
 - Source: pip package version 1.1.2

**Additional context**

**Comment by moonbox3** [comment]
Hi @nguyena2 are you able to provide us with more information (possibly the entire chat history if it doesn't contain sensitive info) about what is contained in the chat history and why the serialize/model dump would be failing?

**Comment by moonbox3** [comment]
> @moonbox3 @markwallace-microsoft I can confirm that we are seeing this issue (or something similar) as well.
> 
> `pf.flow.test failed with UserErrorException: PydanticSerializationError: Execution failure in 'agent': (PydanticSerializationError) Error serializing to JSON: PydanticSerializationError: Unable to serialize unknown type: <class 'type'>`
> 
> I am able to replicate this in the function calling stepwise planner starting in Semantic Kernel 1.2.0 simply by adding the SK Core Time Plugin to the kernel and asking a question that invokes any of those functions.
> 
> At the end of the process we use `ChatHistory.model_dump_json()` (same as is being called in `ChatHistory.Serialize()`) to output the steps taken by the planner and this is what is triggering the error. I am able to successfully use the `ChatHistory.model_dump()` to explore the Chat History object and I have not been able to identify anything about the payload itself that would be causing the serialization error.
> 
> I have replicated the behavior in Python 3.11 and 3.12, and can confirm that the issue can be resolved by moving the project back to Semantic Kernel 1.1.2.
> 
> If y'all feel that this is a separate issue, I am happy to document it in another Github Issue and I am available to demonstrate my example if so desired.

Thanks for the extra context, @denny-nolan-kochcc. Tagging @eavanvalkenburg for visibility.

**Comment by eavanvalkenburg** [comment]
@nguyena2  and @denny-nolan-kochcc the issue is caused by a change we made so that the `result` in a FunctionResultContent can now be any type, instead of before where we cast everything to a string, which was limiting other use cases, so could you check the types used internally that are being put in there, you might also do `[msg.to_dict() for msg in chat_history.messages]` for inspection purposes, while I work on a fix.

**Comment by nguyena2** [comment]
> @nguyena2 and @denny-nolan-kochcc the issue is caused by a change we made so that the `result` in a FunctionResultContent can now be any type, instead of before where we cast everything to a string, which was limiting other use cases, so could you check the types used internally that are being put in there, you might also do `[msg.to_dict() for msg in chat_history.messages]` for inspection purposes, while I work on a fix.

![image](https://github.com/user-attachments/assets/8b0ff64e-8488-423f-9409-4dc400247e06)

**Comment by eavanvalkenburg** [comment]
> > @nguyena2 and @denny-nolan-kochcc the issue is caused by a change we made so that the `result` in a FunctionResultContent can now be any type, instead of before where we cast everything to a string, which was limiting other use cases, so could you check the types used internally that are being put in there, you might also do `[msg.to_dict() for msg in chat_history.messages]` for inspection purposes, while I work on a fix.
> 
> ![image](https://private-user-images.githubusercontent.com/103773120/351035666-8b0ff64e-8488-423f-9409-4dc400247e06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjY0NTAsIm5iZiI6MTcyMTcyNjE1MCwicGF0aCI6Ii8xMDM3NzMxMjAvMzUxMDM1NjY2LThiMGZmNjRlLTg0ODgtNDIzZi05NDA5LTRkYzQwMDI0N2UwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwOTE1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTIwNTQyZTY1MzlmYzBmNjE1YmJhY2E2YjQ5YTc1NjhjNTA1MGY2Y2ZkZjQwNzM4ZTY5NGU2MDg4YTcyNzdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wZ-QmHYGx6iPLXxSVSlTPnrGXzNaE3tk6PCfDikokz4)

what are we looking at in this screen @nguyena2 ?

**Comment by bssoufo** [comment]
Hello, could you tell us when you are going to fix that?
Thanks,
