### ISSUE TITLE
Most links in https://pypi.org/project/semantic-kernel/ are broken. 

### ISSUE THREAD

**Issue by manashty** [microsoft/semantic-kernel#735]
**Describe the bug**
Most links in https://pypi.org/project/semantic-kernel/ are broken. 

**To Reproduce**
1. Go to '[...](https://pypi.org/project/semantic-kernel/)'
2. Scroll down to the end
3. Click on any of following links:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/7827482/235284068-f5c338f6-d5dd-4109-a3a7-4c1592f19d04.png">

Semantic Kernel Notebooks
The repository contains a few Python and C# notebooks that demonstrates how to get started with the Semantic Kernel.

Python notebooks:

[Getting started with Semantic Kernel](https://pypi.org/project/samples/notebooks/python/00-getting-started.ipynb)
[Loading and configuring Semantic Kernel](https://pypi.org/project/samples/notebooks/python/01-basic-loading-the-kernel.ipynb)
[Running AI prompts from file](https://pypi.org/project/samples/notebooks/python/02-running-prompts-from-file.ipynb)
[Creating Semantic Functions at runtime (i.e. inline functions)](https://pypi.org/project/samples/notebooks/python/03-semantic-function-inline.ipynb)
[Using Context Variables to Build a Chat Experience](https://pypi.org/project/samples/notebooks/python/04-context-variables-chat.ipynb)
[Building Memory with Embeddings](https://pypi.org/project/samples/notebooks/python/06-memory-and-embeddings.ipynb)
SK Frequently Asked Questions
How does Python SK compare to the C# version of Semantic Kernel?
The two SDKs are compatible and at the core they follow the same design principles. Some features are still available only in the C# version, and being ported Refer to the [FEATURE MATRIX](https://pypi.org/project/FEATURE_MATRIX.md) doc to see where things stand in matching the features and functionality of the main SK branch. Over time there will be some features available only in the Python version, and others only in the C# version, for example adapters to external services, scientific libraries, etc. 

<img width="918" alt="image" src="https://user-images.githubusercontent.com/7827482/235284079-15ea6b84-a7e4-4c37-ae84-0cb3e139fbf9.png">

We looked everywhere but couldn't find this page
Search PyPI
Search projects
Search
Error code 404

**Comment by alexchaomander** [comment]
Thanks for bringing this up! We'll work to fix this!

**Comment by microsoftShannon** [comment]
@dluc please take a look

**Comment by dluc** [comment]
Fix: https://github.com/microsoft/semantic-kernel/pull/852

**Comment by dluc** [comment]
fixed, thanks!
