### ISSUE TITLE
.Net: Retrieve Final Rendered Prompt String Value

### ISSUE THREAD

**Issue by tamer-abdulghani** [microsoft/semantic-kernel#7359]
I am currently working on a project where I utilize the Semantic Kernel with a plugins directory and multiple skills. My ultimate goal is to develop a workflow to evaluate my SK prompts using the Prompt Flow SDK. To achieve this, I need a way to access the final prompt string value.

Any idea how to achieve this ?

**Comment by dmytrostruk** [comment]
@tamer-abdulghani You can implement and register `PromptRenderFilter`, which will contain rendered prompt after calling `next(context)` delegate/callback. You can get an access to rendered prompt using `context.RenderedPrompt` and you can also modify it if needed.

C# version:
https://github.com/microsoft/semantic-kernel/blob/496d31ea184c99f09b22ca458c33d4d43759734c/dotnet/samples/Concepts/Filtering/PromptRenderFiltering.cs#L60-L72

Python version: 
https://github.com/microsoft/semantic-kernel/blob/496d31ea184c99f09b22ca458c33d4d43759734c/python/tests/unit/functions/test_kernel_function_from_prompt.py#L378-L381

**Comment by dmytrostruk** [comment]
Examples of prompt evaluation logic in C# using prompt render filter:
- https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Demos/ContentSafety/Filters/TextModerationFilter.cs
- https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Demos/ContentSafety/Filters/AttackDetectionFilter.cs

**Comment by dmytrostruk** [comment]
@tamer-abdulghani Based on provided response in previous comment, I'm going to close this issue. In case you have additional questions, feel free to re-open this issue or create a new one. Thanks a lot!
