### ISSUE TITLE
.Net: Add Semantic Kernel to user agent and Semantic Kernel Version header to OpenAPI plugin requests

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#7363]
To allow downstream applications know that Semantic Kernel made an HTTP request from an OpenAPI plugin, we should provide the same headers and user agent as we do for Azure OpenAI

**Comment by moonbox3** [comment]
We do this today in Python: https://github.com/microsoft/semantic-kernel/blob/0fda22e8f547e100e4dd9b8b1307142af42a251a/python/semantic_kernel/connectors/openapi_plugin/openapi_runner.py#L154C9-L157C1

**Comment by matthewbolanos** [comment]
@SergeyMenshykh, do we already do this in .NET?
