### ISSUE TITLE
.Net: Bug: Does SK 1.x .NET work with Azure OpenAI beta 2?

### ISSUE THREAD

**Issue by markjbrown** [microsoft/semantic-kernel#7378]
**Describe the bug**
I am upgrading an existing project using SK 1.4 and Azure OpenAI .NET SDK to 2.0.0-beta.2. When I did the update, I started getting this error below. Updating to SDK 1.6 did not fix the issue. I've tried everything I can think of. Not finding a way to get this to compile.

Error (active)	CS7069	Reference to type 'OpenAIClient' claims it is defined in 'Azure.AI.OpenAI', but it could not be found	

Does this combination work? I cannot find any definitive answer in GH Issues. Seems odd to me that it's complaining about an OpenAI client when this is calling AddAzureOpenAIChatCompletion().

**To Reproduce**
1. Update an existing .NET SK project to Azure Open AI 2.0.0-beta.2
2. Compile

**Screenshots**
Attached to issue. 
![image](https://github.com/user-attachments/assets/596ce761-ea49-49af-a429-cf3455b95244)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: Nuget versions, "Azure.AI.OpenAI" Version="2.0.0-beta.2", "Microsoft.SemanticKernel" Version="1.16.0", "Microsoft.SemanticKernel.Plugins.Core" Version="1.12.0-alpha"

**Comment by markjbrown** [comment]
ok, maybe not? https://github.com/microsoft/semantic-kernel/issues/7083

**Comment by markwallace-microsoft** [comment]
@markjbrown We are in the process of upgrading Semantic Kernel to use Azure OpenAI .NET SDK v2.0.0-beta.N and also OpenAI SDK vv2.0.0-beta.N. Here is the feature branch: https://github.com/microsoft/semantic-kernel/tree/feature-connectors-openai if you would like to see progress and also the back log is available here: https://github.com/orgs/microsoft/projects/866/views/59?sliceBy%5Bvalue%5D=.net by looking at the OpenAI V2 SDK bucket. The changes should be available in the next couple of weeks.

**Comment by VaibhaveS** [comment]
What is the highest version which works with the SK?

**Comment by ystvan** [comment]
> What is the highest version which works with the SK? @markjbrown / @markwallace-microsoft

Azure.AI.OpenAI Version="2.0.0-beta.4"  works with  Microsoft.SemanticKernel Version="1.18.1-rc"
