### ISSUE TITLE
New Feature: Add Oracle memory connector to docs

### ISSUE THREAD

**Issue by Giorgi** [microsoft/semantic-kernel#7392]
[Oracle Database 23ai](https://www.oracle.com/database/23ai/#ai-ml) introduced vector types and vector similarity search. Using this features, I built a memory connector on top of it: [SemanticKernel.Connectors.Oracle](https://github.com/Giorgi/SemanticKernel.Connectors.Oracle)

Would be nice to have this listed at [Available connectors to vector databases](https://learn.microsoft.com/en-us/semantic-kernel/integrations/#available-connectors-to-vector-databases). The page content isn't editable for outside contributors so I can't send a PR for it.

CC @RogerBarreto

**Comment by matthewbolanos** [comment]
Thanks for letting us know! Do you mind submitting a PR here? https://github.com/microsoftdocs/semantic-kernel

**Comment by Giorgi** [comment]
Done! The https://learn.microsoft.com/en-us/semantic-kernel/integrations/#available-connectors-to-vector-databases page doesn't have a "pencil" icon so I didn't know it was possible to send a PR for it.
