### ISSUE TITLE
.Net: Bug: AgentGroupChat Arguments 

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/semantic-kernel#7412]
**Describe the bug**

I have defined three agents: `principalAgent` (who gives final approval), `EnglishAgent`, and `MathsAgent` (who verify the answers).

In `AgentGroupChat`, I passed the agents in the following order: `EnglishAgent`, `MathsAgent`, and `principalAgent` (as the last agent). This setup works well.

```AgentGroupChat chat =
     new(mathsAgent, englishAgent, principalAgent)
     {
         ExecutionSettings =
             new()
             {
                 TerminationStrategy =
                     new ApprovalTerminationStrategy()
                     {
                         Agents = [principalAgent],
                         MaximumIterations = 5,
                     }
             }
     };
````

<img width="859" alt="image" src="https://github.com/user-attachments/assets/0db8b374-7f1e-422e-9cde-7d5d2f311a5b">

<BR><BR>

However, if I pass `principalAgent`(who gives final approval) as the first argument, it not works as expected.
````
  AgentGroupChat chat =
      new(principalAgent,mathsAgent, englishAgent)
      {
          ExecutionSettings =
              new()
              {
                  TerminationStrategy =
                      new ApprovalTerminationStrategy()
                      {
                          Agents = [principalAgent],
                          MaximumIterations = 5,
                      }
              }
      };
````
<img width="862" alt="image" src="https://github.com/user-attachments/assets/710823cd-39dc-4631-9f0b-e914ef4a4edf">

Are there any specific rules for the order in which agents should be passed to `AgentGroupChat`?

---

**To Reproduce**

please find the source code [here](https://github.com/rvinothrajendran/MicrosoftSemanticKernelSamples/tree/main/SKSampleCSharp/SKAgent) 

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac] Windows 
 - IDE: [e.g. Visual Studio, VS Code] VS
 - Language: [e.g. C#, Python] C#
 - Source: Microsoft.SemanticKernel.Agents.Core1.16.0-alpha

**Comment by crickman** [comment]
Hi @rvinothrajendran - When using the (default) `SequentialSelectionStrategy` the sequence of selection is indeed based on the order in which the agents have joined the chat.

Based on your input, perhaps it makes sense to allow an optional strategy level override to specified the desired ordering:

```c#
           AgentGroupChat chat =
                new(mathsAgent, englishAgent, principalAgent)
                {
                    ExecutionSettings =
                        new()
                        {
                            SelectionStrategy =
                                new SequentialSelectionStrategy
                                {
                                    Agents = [mathsAgent, englishAgent, principalAgent],
                                },
                            TerminationStrategy =
                                new ApprovalTerminationStrategy()
                                {
                                    Agents = [principalAgent],
                                    MaximumIterations = 5,
                                }
                        }
                };
```

Since agents are allowed to join the chat after instantiation, I do wonder on how avoid skipping newly added agents if adopting this approach.

I've gone ahead and assigned this to the SK project and Agents bucket to maintain visibility and will consider how this pattern might be improved.  In the meantime, I'm certainly open to your input / thoughts on the matter.

**Comment by rvinothrajendran** [comment]
@crickman Thank you for the detailed information.

**Comment by crickman** [comment]
Hi @rvinothrajendran - I recently added the ability to (optionally) specify which agent goes first:

https://github.com/microsoft/semantic-kernel/pull/8299
