### ISSUE TITLE
.Net Agents - Investigate extensibility of ChatCompletionAgent for purposes of history management / truncation

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#7416]
Until we can formally support truncation for all users of the _Agent Framework_, it is important to provide a timely solution for _Industry AI_ to address this as part of their _Copilot SDK_ when using `AgentChat`.

Unsealing `ChatCompletionAgent` may be one part of the solution here, but more critically: what is the appropriate articulation point to manage a truncation strategy for the history?

**Comment by EdenTanami** [comment]
@crickman From our investigation it seems like the method CreateChannelAsync inside ChatHistoryKernelAgent should be unsealed and not internal, and the same for InvokeAsync inside ChatHistoryChannel.
If ChatCompletionAgent will be unsealed as well it could improve our implementation.
