### ISSUE TITLE
.Net: ONNX connector requires MaxTokens is set

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#7435]
**Describe the bug**
ONNX connector doesn't work unless you indeed specify `MaxTokens` on `OnnxRuntimeGenAIPromptExecutionSettings`
... if you don't (which the API pattern allows not using execution settings), the ONNX impl w/ Phi-3 at least fails with a very obscure message.

**Comment by markwallace-microsoft** [comment]
Created this issue so we investigate what is happening here and what the correct behaviour should be. **If the expectation** is that we include default values in the request for all models we may have to set a default in our prompt execution settings.

**Comment by RogerBarreto** [comment]
According to the ONNX Runtime team, by default the MaxTokens if not provided is set to the current model maximum capacity.

I'm closing this thread as any investigation on the details of the error is being taken care offline.
