### ISSUE TITLE
.Net: Ollama LocalModels FunctionCalling Support

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#7442]
Update Ollama Connector to allow usage of the pattern for function calling using the `Ollama’s raw mode.`

Reference:
- [Mistral FunctionCalling](https://ollama.com/library/mistral)

**Comment by anktsrkr** [comment]
As LLamaSharp support Tooling, will this bring changes in overall Ollam Connector or is it specific to Mistral?

**Comment by taha-ghadirian** [comment]
Hello @RogerBarreto, Is there any update on this issue?

**Comment by RogerBarreto** [comment]
@taha-ghadirian this feature is coming in the following week. 

Thanks for the interest!

**Comment by taha-ghadirian** [comment]
> @taha-ghadirian this feature is coming in the following week. 
> 
> Thanks for the interest! 

Thanks for your answer.
I'm eagerly waiting for ollama, 
Does this imolemantion also supports function calling as are available in AzureAi and OpenAi?

**Comment by Vijay-Braidable** [comment]
Hey,

Any update on this functionality?

Thanks!

**Comment by muqeet-khan** [comment]
@RogerBarreto is there an ETA on #9488 to be included in a published package? I believe the current 1.28.0-alpha does not have that.

**Comment by RogerBarreto** [comment]
@muqeet-khan As this is already part of `main`, it will be available as soon we publish our next release. Which normally happens on Tuesday or Wednesday's.

**Comment by eeadie** [comment]
[Ollama Chat Completion not invoking plugin functions](https://github.com/microsoft/semantic-kernel/discussions/9547)
