### ISSUE TITLE
Bug: GeminiChatCompletionClient isn't using AutoFunctionInvocationFilters

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#7449]
Both the OpenAI and MistralAI chat completion clients are respecting AutoFunctionInvocationFilters. There's no code in Gemini implementation that pays attention to it at all.

**Comment by dmytrostruk** [comment]
My initial idea was to add it only to OpenAI connector first to verify the abstractions and functionality in general and then move it to place where extracted function calling will work for all connectors. But then it was added to MistralAI during the implementation which kind of forces now to add it to Google connector as well. 

I was hoping to implement it in one place only to avoid code duplication and the same set of tests for each connector. But if we think it's worth to add it to all connectors separately and then extract it and move to one place, then we should do it.

**Comment by JadynWong** [comment]
> move it to place where extracted function calling will work for all connectors  

Hopefully it can be realized in this way. Moving the logic of the auto-execute function to the kernel for reuse makes it easier to simplify the implementation of the custom connector logic.
