### ISSUE TITLE
Python: Qdrant memory store connector should also support using the Qdrant  cloud (taking the API Key to initialize the connection)

### ISSUE THREAD

**Issue by anirudhgarg** [microsoft/semantic-kernel#745]
Currently the Qdrant memory store connector only supports local installation and thus asking for the port and the endpoint. It should also support the Qdrant cloud service taking the API Key and the endpoint - see here: 
https://pypi.org/project/qdrant-client/#:~:text=To%20connect%20to%20Qdrant%20server%2C%20simply%20specify%20host,with%20docker%3A%20docker%20run%20-p%206333%20%3A6333%20qdrant%2Fqdrant%3Alatest

**Comment by microsoftShannon** [comment]
Thanks anirudhgarg, we'll look into adding this into the backlog, but of course we are open to contributions from the community as well.

**Comment by anirudhgarg** [comment]
Thanks for considering it. The reason for supporting this is then this allows folks to deploy their application using Semantic Kernel which inturn uses Qdrant cloud - as a service.

**Comment by x3haloed** [comment]
Can't this be achieved in the current design by passing an instance of HttpClient with your own handler in:

```
var httpClient = new HttpClient();
// add request-modification logic here to add the api key to request headers on this HttpClient instance.

var qdrantMemoryStore = new QdrantMemoryStore(
    new QdrantVectorDbClient(endpoint, vectorSize, httpClient: httpClient));
```

**Comment by evchaki** [comment]
@tawalke can you take a look at this issue

**Comment by glahaye** [comment]
@adrianwyatt This is supported now, isn't it?

**Comment by breakstring** [comment]
Looks qdrant memory store just use the qdrant python sdk, but need more parameters in __init__ function of QdrantMemoryStore.

So, I just set the _qdrantclient field with a  qdrant_client object to set the api-key for now.

<img width="779" alt="qc" src="https://github.com/microsoft/semantic-kernel/assets/14105911/2a3ea8fd-3343-403c-84a7-fbecade4e4f2">

**Comment by moonbox3** [comment]
This issue is very stale. If this item is still needed, please feel free to re-open the issue with the appropriate comment; otherwise, please file a new issue.
