### ISSUE TITLE
.Net: Unsupported chat message content type 'Microsoft.SemanticKernel.AudioContent'.Bug: 

### ISSUE THREAD

**Issue by kgrosvenor** [microsoft/semantic-kernel#7462]
**Describe the bug**
When using AudioContent class, getting exception 
`Unsupported chat message content type 'Microsoft.SemanticKernel.AudioContent`

Expected that AudioContent would be supported on 4o

**To Reproduce**
Use GPT-4o azure service

**Expected behavior**
AudioContent files to be supported, if they are would love to know if there is work around 

**Screenshots**

**Platform**
Windows, Wav blob  via AudioContent
**Additional context**

Code context

```c#
foreach (var mediaItem in mediaRequest.Items)
{
    // Limit of 500 kilobytes, if performance issues start arising on server or client side.
    // This solution may need to use Cloud storage for retrieval of documents in the future
    if (StaticDataUriReaderService.GetSizeInBytes(mediaItem.DataUri) > 500000)
    {
        history.AddSystemMessage($"You were unable to process the file type {StaticDataUriReaderService.GetMimeType(mediaItem.DataUri)} because it was too large.");
        continue; // Fail silently
    }
    
    switch (mediaItem.Type)
    {
        case MediaTypeEnum.Audio:
            collection.Add(new AudioContent(mediaItem.DataUri));
            break;
        case MediaTypeEnum.Image:
            collection.Add(new ImageContent(mediaItem.DataUri));
            break;
        default:
            // Enum value passed currently not supported
            throw new ArgumentOutOfRangeException();
    }
    
    mediaItemsToStore.Add(new ChatMessageMedia()
    {
        Type = mediaItem.Type,
        MimeType = StaticDataUriReaderService.GetMimeType(mediaItem.DataUri),
        FileBytes = StaticDataUriReaderService.ConvertDataUriToBytes(mediaItem.DataUri),
        TotalSizeBytes = StaticDataUriReaderService.GetSizeInBytes(mediaItem.DataUri),
    });
}
```

Latest SDK's on C# 

Kind regards

**Comment by RogerBarreto** [comment]
Currently OpenAI documentation does not supports sending contents that aren't images.

![image](https://github.com/user-attachments/assets/710a4f83-2d84-4e53-aa42-633463526fcc)

**Comment by RogerBarreto** [comment]
@brandonh-msft, not sure what you mean by `we should remove it`. 
This type is used in our `ITextToAudio` and `IAudioToText` abstractions and our abstractions are inclusive for multi modalities implementations and we will be ready as soon as any Model supports MultiModalities that includes BinaryData (PDFs), Audio, etc.
