### ISSUE TITLE
.Net - VectorStore Bug Bash: Should vector-store-service constructors pattern align with ai-service constructors?

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#7466]
This is more of a design consideration.

Public constructor for `AzureAISearchVectorStore` (and all other implementations) requires caller to instantiate the appropriate client.  Other AI services have overrides for the configuration parameters.  The lines of code exist anyway, its just a matter of where they are situated...sure there may be a few extra pass-through extension methods on for `IKernelBuilder`.  Personally, I'd consider the builder extensions syntactic sugar only.

Impact: A customer may opt for a DI pattern that isn't pre-packaged in the `IKernelBuilder` extensions.  Exposing convenience constructors in alignment with the AI services reduces the complexity and dependencies for grappling with such a case.

AI Service Example: 
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.OpenAI/ChatCompletion/OpenAIChatCompletionService.cs#L32

Compare to:
https://github.com/microsoft/semantic-kernel/blob/feature-memory-service/dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStore.cs#L35

**Platform**
 - Language: C#
 - Source: Branch `feature-memory-service`

**Comment by westey-m** [comment]
Discussed this further with the team, and the pattern on the ai connectors causes issues, where we have a lot of complex constructors that are hard to understand and maintain, and breaks when the underlying sdk changes.  So keeping it simple for now and following the worse is better approach.  We can always extend these in future to add more overloads if the lack of this becomes an issue.
