### ISSUE TITLE
.Net: Bug When Serializing `ChatMessageContent` type from a `object?` throws error.

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#7478]
**Describe the bug**
When attempting to serialize `ChatMessageContent` from any object that stores it as an `object?`, an exception is thrown.

**To Reproduce**

```csharp
using System.Text.Json;
using Microsoft.SemanticKernel;

var msg = new ChatMessageContent();

msg.Items.Add(new TextContent("text"));

public class A
{
    public object? Message { get; set; }
};

var a = new A { Message = msg };
var dic = new Dictionary<string, object?>() { ["foo"] = msg };

JsonSerializer.Serialize(a); // Throws.
JsonSerializer.Serialize(dic); // Throws.
```

**Comment by dluc** [comment]
the issue is likely related to this code:
https://github.com/microsoft/semantic-kernel/blob/68b21b81df441fabfdebdb6c5867265308175950/dotnet/src/SemanticKernel.Abstractions/Contents/KernelContent.cs#L12
