### ISSUE TITLE
GitHub Repo Q&A Bot sample app is badly broken

### ISSUE THREAD

**Issue by yoDon** [microsoft/semantic-kernel#752]
**Describe the bug**
I pointed the GitHub Repo Q&A bot (using `text-embedding-ada-002`) at a small NextJS TypeScript repo that uses fetch to interact with gpt-3.5-turbo.

When I asked the bot `"Does this repo use Python?"`, instead of responding with some variant of `"No"`, the bot replied 

```Yes,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,Python,```

When I asked the bot `"what chat-gpt model does this repo use?"`, instead of responding with some variant of `"it uses gpt-3.5-turbo"`, the bot responded 

```
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
1, 1, 1, 1, 1, 1, 1, 1,
, 1,, 1,, 1,, 1,

, 1, 1, 1, 1, 1,, 1,, 1, 1, 1, 1,
, 1, 1, 1, 1, 1,

, 1, 1, 1,, 1,

, 1, 1, 1,,,,,,,,,,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
```

All questions I tried asking the app resulted in similarly useless, incorrect, and poorly formed answers.

**Expected behavior**
A clear and concise correct response to the asked question.

**Desktop (please complete the following information):**
 - OS: OSX
 - IDE: VSCode

**Comment by evchaki** [comment]
@hathind-ms, @microsoftShannon can you take a look .

**Comment by craigomatic** [comment]
I've been trying to repro this without any success so far and need a little more info...

1. Which of Open AI or Azure Open AI you are using? 
2. Can you please share a link to the repo you were trying to query?
3. Are you on M1 mac or Intel mac?

**Comment by yoDon** [comment]
The steps I posted provide a 100% repro for this issue. I strongly suspect the problem is that devs on the project are using undocumented Completion Model and Embedding Model selections that must be chosen to enable the sample to work. 

There is no documentation I can find on what models to use for the example.

There are dozens of choices for each, so >100 combined possibilities to sift through. Assuming I'm correct that model choice is the root of the issue then without guidance there's needlessly bad odds that people not on the Semantic-Kernel team can get this to work.

**Comment by craigomatic** [comment]
Apologies for the slow reply here, step 12 is your issue `text-embedding-ada-002` is only supported as an embedding model, not completion. Try using `text-davinci-003` for completion (we are going to switch all samples over to use the chat completion models such as gpt-3.5-turbo soon)

If you're able to confirm this resolves the issue for you we will work on improving the readme. Thank you for giving SK a try :)

**Comment by craigomatic** [comment]
> (we are going to switch all samples over to use the chat completion models such as gpt-3.5-turbo soon)

This has now happened, so please use something like gpt-3.5-turbo if you are working off the latest code in the repository.

**Comment by yoDon** [comment]
If I select gpt-3.5-turbo in the first dropdown per your suggestion, I get a red error message and a disabled "Save" button. 

<img width="624" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1760705/898d8753-3be2-428e-b08d-e7eb4f4bac95">

If instead I select text-davinci-003 in the first dropdown as you previously suggested I get an error popup.

<img width="744" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1760705/3e19059f-3954-4917-8ed1-f60e135773d2">

This seems like a fairly important sample for developers to be able to read and run to understand how to use Semantic Kernel.

**Comment by alliscode** [comment]
Hi @yoDon, [this change](https://github.com/microsoft/semantic-kernel/pull/1305) should fix the issue and has now been merged into main. Let us know if you still see this issue with the latest code.

**Comment by alliscode** [comment]
We are in the process of simplifying our samples to better demonstrate using the core SK features and as such we are not adding more to this sample. We really appreciate your feedback and contributions, stay tuned for the improved samples :).
