### ISSUE TITLE
New Feature: Auto-instrumentation with opentelemetry?

### ISSUE THREAD

**Issue by HuskyDanny** [microsoft/semantic-kernel#7571]
Hi Team,

We are adding the telemetry to our service. There are auto-instrumentations to Redis or Http request, each invoke on them would automatically start a new span, I am wondering do we have such an automation for semantic-kernel? So every plugin or semantic function would automatically have a new span?

Thanks,
Allen

**Comment by markwallace-microsoft** [comment]
@TaoChenOSU can you look at this and check if this already works?

**Comment by TaoChenOSU** [comment]
Hi @HuskyDanny,

Yes, Semantic Kernel .Net has instrumentation set up for all kernel functions. You simply need to subscribe to the source in your application. You can read more about it here: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/docs/TELEMETRY.md#tracing. 

And here is a sample on how to set up telemetry with Application Insights: https://github.com/microsoft/semantic-kernel/tree/main/dotnet/samples/Demos/TelemetryWithAppInsights.

Don't hesitate to post more questions here if you have any :)

**Comment by HuskyDanny** [comment]
Thanks for the pointer here @TaoChenOSU. My inquiry is on python stack, do we have it?

**Comment by TaoChenOSU** [comment]
For Python, we don't have that yet. It will be added very soon.

**Comment by HuskyDanny** [comment]
Don’t mean to be pushy here, just want to have a full picture for planning. May I know the ETA and how this will be implemented? Will it be the same as the .net where adding the namespace of semantic kernel to trace provider is enough? I see python has its own way of adding auto instrumentation which is to add package under opentelemetry.contrib.

**Comment by TaoChenOSU** [comment]
We don't have the full details of how this will be implemented yet. In terms of the timeline, we are aiming for end of this month to early September if nothing changes.

**Comment by moonbox3** [comment]
Tracking this work in #6855. Closing this current issue.
