### ISSUE TITLE
.Net : Is there a way to disable the final response that the AI generates ​​and return the value of the invoked plugin

### ISSUE THREAD

**Issue by minhquangkid** [microsoft/semantic-kernel#7582]
I want to use the AI to invoke the plugin and return exactly the value of it, but the AI always generate the final response. I don't know how to turn it off, please help me!
Here is how I use it :

`
public async Task<ChatHistory> GetImageCakes(string userRequest, ChatHistory chat)
{

    ChatCompletionAgent agent =
        new()
        {
            Name = "Seller",
            Instructions = "You are a seller of a bakery, talk to customer",
            Kernel = this.CreateKernelWithChatCompletion(),
            ExecutionSettings = new OpenAIPromptExecutionSettings() { ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions },
        };

    KernelPlugin plugin = KernelPluginFactory.CreateFromType<NposPlugin>();
    agent.Kernel.Plugins.Add(plugin);

    // Respond to user input
    await InvokeAgentAsync(userRequest);

    return chat;

    // Local function to invoke agent and display the conversation messages.
    async Task InvokeAgentAsync(string input)
    {
        chat.Add(new ChatMessageContent(AuthorRole.User, input));

        Console.WriteLine($"# {AuthorRole.User}: '{input}'");

        await foreach (ChatMessageContent content in agent.InvokeAsync(chat))
        {
            chat.Add(content);

            Console.WriteLine(value: $"# {content.Role} - {content.Content}");

        }
    }
}
`

And this is my plugin. My goal is to return an array containing the image URLs and no other information.

` 
[KernelFunction("get_list_cake_image"), Description("Provide a list of images of specific cakes in store")]
 [System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1024:Use properties where appropriate", Justification = "Too smart")]
 public async Task<List<string>> GetListImageAsync(
     [Description("The type of cake.")]
     string typeOfCake
 )
 {
     List<string> listImage = [];

     //Console.WriteLine($"Your type of cake : {typeOfCake}");

     var options = new RestClientOptions("https://mba.dotnets.org");

     var client = new RestClient(options);
     var request = new RestRequest($"/api/Attachment/get-list-image/{this.shopId}?pageSize={this.pageSize}&pageNumber={this.pageNumber}&text={typeOfCake}", Method.Get);

     request.AddParameter("text/plain", ParameterType.RequestBody);
     RestResponse response = await client.ExecuteAsync(request);

     List<ImageResponse> listResponse = JsonConvert.DeserializeObject<List<ImageResponse>>(response.Content);

     listResponse.ForEach(image =>
     {
         listImage.Add(image.Url);
     });

     return listImage;
 }
`
 
 Here is an example :
 
![image](https://github.com/user-attachments/assets/21f773ec-b243-4ed1-a1f7-0fb7c8926325)

**Comment by dmytrostruk** [comment]
@minhquangkid Thanks for reporting this issue!
I would recommend trying `IAutoFunctionInvocationFilter`, where you can terminate auto function calling process earlier with this flag:
https://github.com/microsoft/semantic-kernel/blob/7997e79bb9dd352c6dafbbd1a92a3634f43500de/dotnet/samples/Concepts/Filtering/AutoFunctionInvocationFiltering.cs#L144

This should help you to avoid sending additional request to LLM to generate final response and instead return the value of the invoked plugin. Let us know if this helps to handle your scenario. Thanks!

**Comment by minhquangkid** [comment]
@dmytrostruk  thank you so much! That's exactly what I need

**Comment by minhquangkid** [comment]
@dmytrostruk  I found the new Bug, When I used IAutoFunctionInvocationFilter for the first time, I worked. But when I continue to run it again, It returns the error :
"Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'"

Here is my filter :
`
        #pragma warning disable SKEXP0001 // Disable the specific experimental feature warning
        public class CustomFilterNpos : IAutoFunctionInvocationFilter
        {
            public CustomFilterNpos() {}

            public async Task OnAutoFunctionInvocationAsync(AutoFunctionInvocationContext context, Func<AutoFunctionInvocationContext, Task> next)
            {
                if (context.Function.PluginName == "NposPlugin" && context.Function.Name == "get_list_cake_image")
                {
                   
                        context.Kernel.Plugins.TryGetPlugin("NposPlugin", out KernelPlugin _nposPlugin);
                        _nposPlugin.TryGetFunction("get_list_cake_image", out KernelFunction _getListImageAsyncFunc);
                        context.Result = await _getListImageAsyncFunc.InvokeAsync(context.Kernel, context.Arguments); // return the list of image's URLs

                       context.Terminate = true; 

                       return;


                }
            }
        }
        #pragma warning restore SKEXP0001 // Re-enable the warning
`

And here are the results :
![image](https://github.com/user-attachments/assets/30f2ec44-4c84-45b1-98c4-bba1f4545085)
![image](https://github.com/user-attachments/assets/f2c77a75-3b69-4bd5-a009-5cd216c34fb8)

Please help me!

**Comment by dmytrostruk** [comment]
> But when I continued to run it again, It returned the error :
"Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'"

@minhquangkid This error message means that `ChatHistory` object contains messages in invalid order or missing some required pieces. When LLM responds with function calling (i.e. `tool_calls`), in chat history this message should be followed by function result (i.e. message with author role `tool`). If this requirement is not completed, OpenAI API will respond with this error. 

So, chat history should look like this:
1. Message with AuthorRole `User`
2. Message with AuthorRole `Assistant` with `ToolCalls`
3. Message with AuthorRole `Tool`.
4. Message with AuthorRole `Asisstant`. 
and so on. 

Before you send a request, check ChatHistory object if this requirement is respected. If not, then we will need to find a root cause why this is happening based on your code. Thanks!

**Comment by crickman** [comment]
@minhquangkid:

For the original code you shared, can you please try this when using `Terminate = true`:

**Original:**
```c#
    await foreach (ChatMessageContent content in agent.InvokeAsync(chat))
    {
        chat.Add(content);

        Console.WriteLine(value: $"# {content.Role} - {content.Content}");

    }
```
**Updated:**
```c#
    await foreach (ChatMessageContent content in agent.InvokeAsync(chat))
    {
          if (!content.Items.Any(i => i is FunctionCallContent || i is FunctionResultContent))
          {
              chat.Add(content);
          }

        Console.WriteLine(value: $"# {content.Role} - {content.Content}");

    }
```

When using `Terminate=true` using using `IAutoFunctionInvocationFilter` or any pattern that yields a message with `Items` collection that contains `FunctionCallContent` or `FunctionResultContent` as part of the content returned by `Agent.InvokeAsync`...this message is already present in the `ChatHistory`.  Re-adding such a message results in duplication and can violate the expected structure of `ChatHistory`.

This is the case when using `IChatCompletionService` directly (outside of the _Agent Framework_) and also applies when using `ChatCompletionAgent` (which, in turn, invokes a `IChatCompletionService` instance).

If you are still experiencing the same issue after attempting this change, can you please:

1. Share the model name and version you are targeting 
2. Examine `Items` collection in the _assistant_ message that contains the `FunctionCallContent` and share how many items are present?

Thank you.  Looking forward to your feedback.

**Comment by minhquangkid** [comment]
Hi @crickman
Thanks for your guide:
```
if (!content.Items.Any(i => i is FunctionCallContent || i is FunctionResultContent))
{
chat.Add(content);
}
```

It really solved my problem! I will close this issue here, thanks again

**Comment by shopwood** [comment]
I've just spent 2 days on this same problem. This is not an obvious solution to someone using the library.
