### ISSUE TITLE
Python: Bug: Python Parameters Not Found When Invoking Plugin Imported With add_plugin_from_openapi 

### ISSUE THREAD

**Issue by bbednarski9** [microsoft/semantic-kernel#7586]
**Describe the bug**
version: semantic-kernel==python-1.3.0
I am running into an error when running sample code at /python/samples/concepts/plugins/openapi/. Running the server without error. When I run the client, I get the following error:

_Something went wrong in function invocation. During function invocation: 'openApiPlugin-helloWorld'. Error description: 'Parameter name is required but not provided in the arguments.'_

 **"path_params": '{"name": "mark"}',** is not being passed through to the /{name} function invocation by the kernel. Able to circumvent by defining 'name' as an attribute of the KernelArguments instance as follows:

```
import asyncio

import semantic_kernel as sk
from semantic_kernel.functions.kernel_arguments import KernelArguments

async def main():
    """Client"""
    kernel = sk.Kernel()

    openapi_plugin = kernel.add_plugin_from_openapi(plugin_name="openApiPlugin", openapi_document_path="./openapi.yaml")

    arguments = {
        "request_body": '{"input": "hello world"}',
        "path_params": '{"name": "mark"}',
        "query_params": '{"q": "0.7"}',
        "headers": '{"Content-Type": "application/json", "Header": "example"}',
    }

    kernel_arguments = KernelArguments(**arguments)
    
    kernel_arguments['name'] = "mark"

    result = await kernel.invoke(openapi_plugin["helloWorld"], arguments=kernel_arguments)

    print(result)

if __name__ == "__main__":
    asyncio.run(main())

```

However, the output is still missing the query parameters and request_body:

_Hello, mark: q=, body={}, headers=<CIMultiDictProxy('Host': 'localhost:8080', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', 'semantic-kernel-version': 'python/1.3.0', 'User-Agent': 'semantic-kernel-python/1.3.0', 'Content-Type': 'application/json', 'Content-Length': '2')>_

**To Reproduce**
1. Create fresh conda env with python 3.10
2. conda install poetry
3. poetry build (sk 1.3.0)
4. pip install dist/semantic_kernel-1.3.0-py3-none-any.whl --force-reinstall
5. cd semantic-kernel/python/samples/concepts/plugins/openapi/
6. python ./openapi_server.py
7. new terminal
8. cd semantic-kernel/python/samples/concepts/plugins/openapi/
9. python ./openapi_client.py

**Expected behavior**
Expected resultant print statement in the client to have name from the path_params, have values from query params, and have request body

**Screenshots**

**Platform**
 - OS: Mac
 - IDE: VS Code
 - Language: Python
 - Source: semantic_kernel-1.3.0-py3-none-any.whl

**Additional context**
NA

**Comment by moonbox3** [comment]
Apologies for the long delay on this. Have you tried using a more recent SK Python version? We're on 1.11.0 now. Please re-open this issue if you continue to experience an issue.
