### ISSUE TITLE
.Net: VectorStore - Add GettingStarted project with step by step instructions

### ISSUE THREAD

**Issue by westey-m** [microsoft/semantic-kernel#7606]
Create a getting started project for using the new VectorStore implementations.

Use https://github.com/microsoft/semantic-kernel/pull/7604 as created by @markwallace-microsoft as a starting point.

**Comment by markwallace-microsoft** [comment]
Here are the steps that I'd like to see:

1. `Step1_VectorStore_CRUD` - Using InMemory introduce the core concepts i.e.
     1. Create a Data Model
     2. Create a record collection to store instances of your Data Model
     3. Perform CRUD operations against the record collection
     4. Perform paging over data
2. `Step2_VectorStore_Search` - Using InMemory show how to perform search
     1. Basic search
     2. Search filters
3. `Step3_VectorStore_Configuration` - Show how to switch between different Vector Stores and what gotchas exist
    1. Go from InMemory for local development to a real Vector DB 
5. `Step4_VectorStore_Advanced_DataModels` - Dynamic data models, custom mappers, ...
