### ISSUE TITLE
AuthError.ts:49  Uncaught (in promise) BrowserAuthError: interaction_in_progress

### ISSUE THREAD

**Issue by fanheshe** [microsoft/semantic-kernel#785]
**Describe the bug**

https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/copilot-chat-app

I read and completely followed the readme.md instructions. Finally, I ran the webapp and clicked on authorization to log in. I saw this error from the browser console, but I couldn't click to complete the authorization process

  I still get this prompt when running in a new environment, and I haven't opened any extra browsers, only edges, and there are no other unnecessary authorization pages or pop-up windows. Unfortunately, I can't find any solution for such a simple authorization, including using AI tools, new binding, and chatGPT 4. Seek a solution

**To Reproduce**
dotnet run
yarn start

browser : http://localhost:3000

Browser development tool console output
logs：
AuthError.ts:49  Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (AuthError.ts:49:1)
    at new BrowserAuthError (BrowserAuthError.ts:199:1)
    at BrowserAuthError.createInteractionInProgressError (BrowserAuthError.ts:280:1)
    at BrowserCacheManager.setInteractionInProgress (BrowserCacheManager.ts:1305:1)
    at ClientApplication.preflightInteractiveRequest (ClientApplication.ts:907:1)
    at ClientApplication.preflightBrowserEnvironmentCheck (ClientApplication.ts:890:1)
    at PublicClientApplication.<anonymous> (ClientApplication.ts:284:1)
    at step (pluginsSlice.ts:61:1)
    at Object.next (pluginsSlice.ts:61:1)
    at pluginsSlice.ts:61:1

**Comment by windmemory** [comment]
@fanheshe how did you resolve this problem? I am running into the same problem today.

**Comment by windmemory** [comment]
I finally got my problem solved:

I was not able to install the deps with `yarn`, so I use `npm` to install these deps, then I use `npm start` to run the webapp, seems like there are some problem with `npm`, I switched to `yarn start`, and the webpage started to work.

**Comment by sidecus** [comment]
@hunk-fe make sure the new env file is named exactly as ".env", and has your application id configured correctly. An incorrect file name or incorrect application id can cause this issue.

**Comment by hunk-fe** [comment]
Ah, thanks a lot, I missed the step to create the .env file. By creating that, I solved the problem.
