### ISSUE TITLE
The ChatCompletionService.GetChatMessageContentAsync method should be extended

### ISSUE THREAD

**Issue by sophialagerkranspandey** [microsoft/semantic-kernel#7857]
### Discussed in https://github.com/microsoft/semantic-kernel/discussions/7403

<div type='discussions-op-text'>

<sup>Originally posted by **takashiuesaka** July 22, 2024</sup>
In my opinion, when communicating with an LLM using SemanticKernel, there are two main methods to use:

1. ChatCompletionService.GetChatMessageContentAsync
2. Kernel.InvokePromptAsync

The first is used when utilizing ChatHistory, while the second is used when not utilizing it.

However, GetChatMessageContentAsync has an overload that accepts a string instead of ChatHistory, making both methods almost identical in usage. I believe this situation can be quite confusing.

In my view, the current partial implementation of both methods is problematic.

- Issues with ChatCompletionService.GetChatMessageContentAsync:

  1. IPromptRenderFilter is not called.
  2. There is no overload that accepts KernelArguments when taking a string as a prompt.

- Issues with Kernel.InvokePromptAsync:

  1. There is no overload that accepts ChatHistory.

My suggestion is to either add an overload to ChatCompletionService.GetChatMessageContentAsync that accepts KernelArguments and ensure it calls IPromptRenderFilter, or plan to deprecate the overload that accepts a string as a prompt. This is because it would be unnatural to create an overload for Kernel.InvokePromptAsync that accepts ChatHistory, an object meant for chat completion.</div>

**Comment by markwallace-microsoft** [comment]
Team plan's to proceed with this approach: https://github.com/microsoft/semantic-kernel/issues/8885
