### ISSUE TITLE
.Net: Bug: .NET Google Gimini connector Issue

### ISSUE THREAD

**Issue by sshrishipwc** [microsoft/semantic-kernel#7904]
**Describe the bug**

Google Gimini connector error when we pass custom http client. The API is exposed from GIF.

**To Reproduce**

Code block Google Gimini connector using below code

GoogleAIGeminiChatCompletionService chatCompletionService = new(
     modelId: "chat-bison:predict",
     apiKey: .xxxxxxx,
     apiVersion: GoogleAIVersion.V1,
     httpClient: httpClient
);
 
var resultdata = await chatCompletionService.GetChatMessageContentsAsync(chat, chatRequestSettings, Kernel.CreateBuilder().Build());

**Expected behavior**
As the service is setup through GIF it should user token from HTTP client and authenticate API

Error details

Microsoft.SemanticKernel.HttpOperationException: 'Response status code does not indicate success: 401 (Unauthorized).'

**Comment by RogerBarreto** [comment]
Thanks for the issue!

Not fully sure what is the use case in this issue.

1. I'm assuming also that `GIF` means `Gateway Integration Framework` correct here if I'm wrong.
   If this is correct, in theory your Gateway should ignore any provided header content and override it in the middle of the request.

2. If there's no Gateway, from my understanding when using your custom `HttpClient` you should be able to override the header thru a Custom `DelegatingHandler` overriding the `SendAsync` with the request Header you want.

    [Custom Http Handler Example](https://github.com/microsoft/semantic-kernel/blob/7b8ac8abf54c3c0e98c9e3f7653f44b0bb7565d3/dotnet/samples/Concepts/Memory/HuggingFace_TextEmbeddingCustomHttpHandler.cs#L43)

**Comment by sshrishipwc** [comment]
Yes it’s Gateway Integrated Framework. This is working fine for all Azure Open AI models but getting 401 for Gimini.

We verified the API call with Postman and it’s working as expected.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
