### ISSUE TITLE
Why does SkillCollection differentiate semantic vs native in its APIs?

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#791]
SkillCollection duplicates its surface area, once for semantic functions and once for native functions.  Why does SkillCollection care about the distinction at all?  It ends up storing them all in the same dictionary, so it already doesn't support having two different functions with the same name, and in any scenario where a consumer cares to only get a semantic vs native function, they can just check the resulting function's IsSemantic (it's also not clear to me in what situation a consumer would actually care).

cc: @shawncal

**Comment by evchaki** [comment]
@stephentoub thanks for bringing this up, we will take a look

**Comment by dluc** [comment]
It's part of the journey from internal prototypes written a year ago when we first started using "AI functions". We're going through another set of design polish tasks and this was one of the TODO, there's a few PRs coming and a couple in particular touching this area.
