### ISSUE TITLE
Save messages for each user

### ISSUE THREAD

**Issue by HuskyDanny** [microsoft/semantic-kernel#7950]
Hi Team,

I would like to check if there is some examples for saving messages to traditional database and use it for each request received from client.

Thanks!

**Comment by RogerBarreto** [comment]
There are no examples of such in the current repo as this can be achieved in many different ways depending on your own database model.

Normally assuming the most simplistic scenario in a MS SQL SERVER.

UserMessages:
| UserId | Role | Content | TimeStamp |
| -- | -- | -- | -- |
| | | | |

Retrieving the last 10 messages in the conversation

```tsql
SELECT TOP 10 Role, Message FROM UserMessages WHERE UserId = {UserId} ORDER BY TimeStamp DESC
```

```csharp
// Initialize the kernel...
var chatCompletion = kernel.GetRequiredService<IChatCompletionService>();

// Retrieve Messages
var records = RetrieveFromDatabase(userId);
chatHistory chatHistory = [];
foreach (var record in records);
    chatHistory.Add(new ChatMessage(new AuthorRole(record.Role), record.Content));

var userInput = Console.ReadLine();
var userMessage = new ChatMessage(AuthorRole.User, userInput);
var assistantMessage = chatCompletion.GetChatMessageContentsAsync(chatHistory);

// Persist back the new messages
PersistMessagesIntoDatabase([userMessage, assistantMessage]);
```
