### ISSUE TITLE
.Net: Issue with transitive dependencies

### ISSUE THREAD

**Issue by gladiatorAsh** [microsoft/semantic-kernel#7964]
I am working on a Stepwise Planner solution and rely on the following version of Semantic Kernel - 1.12.0

Microsoft.KernelMemory.Core transitively refers to many packages like Npgsql which may not end up being used. I currently have a requirement where I am unable to use this package as my build pipelines while using dotnet restore task raise a security issue for a version of this package. Even going forward, I do not want to take the responsibility of updating all package versions for any security issues that may occur.

**How do I mark  this transitive dependency as not needed to be downloaded? Or any other way to bypass this issue?**

**Comment by JadynWong** [comment]
I think it's more related to [kernel-memory](https://github.com/microsoft/kernel-memory/issues)?

My personal opinion. 
Unless kernel-memory modifies the dependencies, there's probably not much that can be done.
Or you can just quote the source code and remove the dependencies.

The project references in `Microsoft.KernelMemory.Core` are frankly a bit counter-intuitive. `Microsoft.KernelMemory.Core` should be a minimal dependency library.
A separate 'Microsoft.KernelMemory' project should be created to depend on `Microsoft.KernelMemory.Core` and existing extensions. Just like `Microsoft.SemanticKernel.Core` and `Microsoft.SemanticKernel`.

**Comment by markwallace-microsoft** [comment]
@gladiatorAsh I agree with the above comment that this should be report in the [kernel-memory issues](https://github.com/microsoft/kernel-memory/issues). I'm going to close this issue, can you please create a new issue?

FYI @dluc
