### ISSUE TITLE
Python Agents - Add 'EnableFileSearch' option to Asistant Agent definition

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#7965]
There's a common case where teh assistant won't have a vector-store-id assigned, but it will be provided to the thread and the assistant needs the tool enabled.

Initial design relied on the presence of vector-store-id on the assistant to enable.

**Comment by crickman** [comment]
I think this may already be present.

**Comment by moonbox3** [comment]
This is handled today: https://github.com/microsoft/semantic-kernel/blob/6f3642e2dfd47bd702d07dbb3d45eaff14e801fd/python/samples/concepts/agents/openai_assistant_agent_file_search.py#L44C13-L44C37
