### ISSUE TITLE
Get the tokens in the response

### ISSUE THREAD

**Issue by EashShow** [microsoft/semantic-kernel#802]
I want to get the tokens per call.
Just like calling the Azure OpenAI, I can get the total tokens and the prompt tokens.

Thanks!

**Comment by evchaki** [comment]
@EashShow thanks for bringing this up.  We are looking at it.

**Comment by littlebeer** [comment]
Same problem, waiting for reply

**Comment by guillaumeKoban** [comment]
This would be amazing for us too

**Comment by EashShow** [comment]
Let me fix this?
