### ISSUE TITLE
Copilot chat sample app - readme steps aren't working - webapp error clicking signin

### ISSUE THREAD

**Issue by TomShirley** [microsoft/semantic-kernel#806]
Can't seem to get the copilot chat app to run locally. 

https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/copilot-chat-app

I followed the readme.md instructions and when attempting yarn start on the webapp, it launches http://localhost:3000. Clicking on the signin button doesn't do anything and I get an error in the console (below).

Is there setup steps missing for the webapp? When debugging clicking on the sign-in button it appears config for msal-browser is empty (see screenshot) but maybe this is unrelated..

**To Reproduce**
* follow readme steps with openai instead of azure open ai
* start the api 
* start the web app with yarn start

browser opens up : http://localhost:3000/

When clicking on the sign-in button the error is:
```
thError.ts:49 Uncaught (in promise) ClientConfigurationError: empty_url_error: URL was empty or null.
    at ClientConfigurationError.AuthError [as constructor] (AuthError.ts:49:1)
    at ClientConfigurationError.ClientAuthError [as constructor] (ClientAuthError.ts:222:1)
    at new ClientConfigurationError (ClientConfigurationError.ts:111:1)
    at ClientConfigurationError.createUrlEmptyError (ClientConfigurationError.ts:164:1)
    at new UrlString (UrlString.ts:28:1)
    at Authority.transformCIAMAuthority (Authority.ts:801:1)
    at Function.<anonymous> (AuthorityFactory.ts:40:1)
    at step (MathUtils.ts:23:1)
    at Object.next (MathUtils.ts:23:1)
    at MathUtils.ts:23:1
```

**Expected behavior**
Signin should launch the oauth flow

**Screenshots**
![image](https://user-images.githubusercontent.com/5934398/236204172-1537d4ab-3089-422b-b11e-589d446cd027.png)

**Desktop**
 - OS: Windows 10
 - node 20.1.0

**Comment by evchaki** [comment]
@craigomatic  can you take a look at this one?

**Comment by cchighman** [comment]
Based on the local variables you shared above, it looks like you dont have your appsettings configured correctly.  For example, a clientid isn't set.  

This is what it should look like:
![image](https://user-images.githubusercontent.com/659214/236576806-f89efd25-2d92-4055-a4ba-da35fa0b90bd.png)

I've setup the copilot a handful of times now and the readme is pretty complete.  It's easy to overlook the fact that you have config settings needed in both webapi and webapp as well as Azure as part of the setup.  Make sure those are set and it should be seamless.

**Comment by cchighman** [comment]
Ah, I just realized its more than likely that you didn't set the .env file in the webapp.

See this from the readme:
![image](https://user-images.githubusercontent.com/659214/236578014-3b55e26d-5452-4b36-912b-fa149d3e965c.png)

Mine looks like this, I only had to change the value for ClientId:
![image](https://user-images.githubusercontent.com/659214/236578119-87f32959-d3bc-4018-b4a9-0fe83af60e67.png)

Because the values are null, I'm assuming the sample file above was not renamed to ".env"

**Comment by TomShirley** [comment]
ah you're right the .env was the issue after all (messed up the renaming step)
