### ISSUE TITLE
.Net: Bug: OpenAIFunctionParameter.ParameterType is null for integer and number types

### ISSUE THREAD

**Issue by sunnymitramsft** [microsoft/semantic-kernel#8087]
**Describe the bug**
OpenAIFunctionParameter.ParameterType is null for integer and number types.
![image](https://github.com/user-attachments/assets/9d531def-f294-4b6f-8d86-3da0ae6ca4c1)

**To Reproduce**
Sample parameter json:
```json
"startAt": {
  "description": "The index of the first item to return in a page of results (page offset).",
  "type": "integer",
  "format": "int32",
  "default": 0
}
```
Here's the full swagger file (check `searchForIssuesUsingJql` API)
[openapi.json](https://github.com/user-attachments/files/16597788/openapi.json)

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: Nuget version 1.16.1

**Additional context**
We parse the swagger file using:
`await this.kernel.ImportPluginFromOpenApiAsync(cacheKey, pluginStream, parameters, cancellationToken)`

Note: We are not seeing this issue for `string` type parameters!

**Comment by SergeyMenshykh** [comment]
Hi @sunnymitramsft, thanks for reporting the issue. We plan to fix it this week.
