### ISSUE TITLE
.Net: Implement Entity Framework Connector using new Memory Design

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#8090]
Memory ADR is here: https://github.com/microsoft/semantic-kernel/issues/5887

- [ ] Implement new abstractions
- [ ] Unit tests
- [ ] Integration tests
- [ ] Document any limitations in the implementation
- [ ] Implement a basic RAG samples
- [ ] Work with Sofia on a new Blog post
- [ ] Obsolete the old implementation
- [ ] Create task to graduate the Memory Connector

**Comment by dmytrostruk** [comment]
Closing as not planned based on this ADR:
https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0051-entity-framework-as-connector.md
