### ISSUE TITLE
.Net: Create PowerShell scripts to provision required resources for integration tests

### ISSUE THREAD

**Issue by dmytrostruk** [microsoft/semantic-kernel#8101]
Based on https://github.com/microsoft/semantic-kernel/pull/8065#discussion_r1714962486.

In scope of this task, PowerShell script should be provided to provision following resources:
- [ ] Azure CosmosDB for MongoDB
- [ ] Azure CosmosDB for NoSQL

**Comment by N-E-W-T-O-N** [comment]
@dmytrostruk 
Do you want Something Like this 
`
# Azure Cosmos DB for MongoDB Provisioning Script

# Parameters
param(
    [Parameter(Mandatory=$true)]
    [string]$resourceGroupName,

    [Parameter(Mandatory=$true)]
    [string]$accountName,

    [Parameter(Mandatory=$false)]
    [string]$location = "eastus",  # Default value set to "eastus"

    [Parameter(Mandatory=$true)]
    [ValidateSet("Eventual", "Session", "BoundedStaleness", "Strong")]
    [string]$consistencyLevel,

    [Parameter(Mandatory=$false)]
    [int]$maxStalenessPrefix = 100000,

    [Parameter(Mandatory=$false)]
    [int]$maxIntervalInSeconds = 300
)

# Ensure the Az module is installed
if (-not (Get-Module -ListAvailable -Name Az)) {
    Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser
}

# Connect to Azure (you may need to sign in)
Connect-AzAccount

# Create resource group if it doesn't exist
New-AzResourceGroup -Name $resourceGroupName -Location $location -ErrorAction SilentlyContinue

# Create Cosmos DB account
$cosmosDbParams = @{
    ResourceGroupName = $resourceGroupName
    Name = $accountName
    Location = $location
    ApiKind = "MongoDB"
    EnableAutomaticFailover = $true
    DefaultConsistencyLevel = $consistencyLevel
}

if ($consistencyLevel -eq "BoundedStaleness") {
    $cosmosDbParams.MaxStalenessPrefix = $maxStalenessPrefix
    $cosmosDbParams.MaxIntervalInSeconds = $maxIntervalInSeconds
}

New-AzCosmosDBAccount @cosmosDbParams

Write-Output "Azure Cosmos DB for MongoDB account '$accountName' has been provisioned in resource group '$resourceGroupName'."
`

**Comment by N-E-W-T-O-N** [comment]
```
# Azure Cosmos DB for NoSQL Provisioning Script

# Parameters
param(
    [Parameter(Mandatory=$true)]
    [string]$resourceGroupName,

    [Parameter(Mandatory=$true)]
    [string]$location,

    [Parameter(Mandatory=$true)]
    [string]$accountName,

    [Parameter(Mandatory=$true)]
    [string]$databaseName,

    [Parameter(Mandatory=$true)]
    [string]$containerName,

    [Parameter(Mandatory=$true)]
    [string]$partitionKeyPath,

    [Parameter(Mandatory=$false)]
    [int]$throughput = 400
)

# Login to Azure (uncomment if not already logged in)
# Connect-AzAccount

# Create Resource Group if it doesn't exist
New-AzResourceGroup -Name $resourceGroupName -Location $location -ErrorAction SilentlyContinue

# Create Cosmos DB Account
$cosmosDBProperties = @{
    "DatabaseAccountOfferType" = "Standard"
    "Locations" = @(
        @{
            "LocationName" = $location
            "FailoverPriority" = 0
        }
    )
    "ConsistencyPolicy" = @{
        "DefaultConsistencyLevel" = "Session"
    }
}

New-AzCosmosDBAccount `
    -ResourceGroupName $resourceGroupName `
    -Name $accountName `
    -Location $location `
    -ApiKind "NoSQL" `
    -EnableAutomaticFailover:$false `
    -Properties $cosmosDBProperties

# Create Database
New-AzCosmosDBSqlDatabase `
    -ResourceGroupName $resourceGroupName `
    -AccountName $accountName `
    -Name $databaseName

# Create Container
New-AzCosmosDBSqlContainer `
    -ResourceGroupName $resourceGroupName `
    -AccountName $accountName `
    -DatabaseName $databaseName `
    -Name $containerName `
    -PartitionKeyPath $partitionKeyPath `
    -Throughput $throughput

Write-Host "Azure Cosmos DB for NoSQL provisioning completed successfully."
```

**Comment by dmytrostruk** [comment]
@N-E-W-T-O-N Thanks for providing the scripts! I will use them when start working on this item. Thanks again!

**Comment by markwallace-microsoft** [comment]
This is no longer needed
