### ISSUE TITLE
Python: openai.types.beta.AssistantResponseFormat has been replaced to support Structured Response Format

### ISSUE THREAD

**Issue by tarockey** [microsoft/semantic-kernel#8103]
https://github.com/microsoft/semantic-kernel/blob/7e2bca7c98ec7b38babc266267d5f0d1960a508b/python/semantic_kernel/agents/open_ai/open_ai_assistant_base.py#L13

The AssistantResponseFormat has been replaced by AssistantResponseFormatOptions as of at least 1.40.0 of the openai python SDK, in order to support structured response formats.

This causes an import issue when using OpenAI Assistants as agents.

Fix would be to either pin the OpenAI SDK version to the latest working one, or to update the imports in agents.

**Comment by moonbox3** [comment]
Thank you, this is fixed as of our release today of 1.51.0.
