### ISSUE TITLE
Python: Not able to run the semantic similarity serach on https://github.com/microsoft/semantic-kernel/blob/main/python/samples/getting_started/06-memory-and-embeddings.ipynb

### ISSUE THREAD

**Issue by safdar23** [microsoft/semantic-kernel#8115]
**Describe the bug**
I am working with the repo file :
[semantic-kernel/python/samples/getting_started/06-memory-and-embeddings.ipynb at main · microsoft/semantic-kernel · GitHub](https://github.com/microsoft/semantic-kernel/blob/main/python/samples/getting_started/06-memory-and-embeddings.ipynb)
. I am able to run the file successfully but semantic similarity search with memory is not working, it does not return any result
**To Reproduce**
1. Go to '.emantic-kernel/python/samples/getting_started/06-memory-and-embeddings.ipynb'
2. Click on 'Run the notebook'
3. Scroll down to 'semantic similiratity search'
5Although memory is populated but running the below cell does not provide the serach results

await chat("What is my budget for 2024?")

**Expected behavior**
The cell should provide me the search results from memory 
**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by moonbox3** [comment]
We worked together offline to get you unblocked. Closing this issue.
