### ISSUE TITLE
.Net: Models with unsupported tools fails.

### ISSUE THREAD

**Issue by tennaito** [microsoft/semantic-kernel#8165]
Guys, I think this line is causing the process to always put a tool object inside final json body. 

When testing semantic-kernel with Ollama and Phi3 (model that does not have tools) it fails even if the settings OpenAIPromptExecutionSettings settings = new() { ToolCallBehavior = null } is set.

Reference: https://github.com/microsoft/semantic-kernel/blame/9e59698d0d72f1aebfdff5c1ad046d9d6c864b93/dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs#L1137C18-L1137C18

Version 1.17.1 (client from azuresdk) does not create tool property inside the final json.

**Comment by RogerBarreto** [comment]
This is a not supported scenario. (Using OpenAI against Ollama services)
Today our `Ollama` Connector doesn't have support for function calling and is the ideal option for non-function-calling supported models.
Ollama Connector will support function calls and we will take care for this scenarios.
