### ISSUE TITLE
Bug: Facing issue with chat completion streaming option using GPT4O and GPT4V model with Azure SDK V2

### ISSUE THREAD

**Issue by AmanDogra1989** [microsoft/semantic-kernel#8189]
**Describe the bug**
Getting below error with GPT4O and GPT4V model in Azure SDK V2 using chat completion stream = true. Also, parallel function/tool call doesn't seem to work with GPT4O and GPT4_Turbo models with or without streaming option enabled:

HTTP 400 (invalid_request_error: unknown_parameter)
Parameter: stream_options

Unknown parameter: 'stream_options'.

**Comment by markwallace-microsoft** [comment]
Hi @AmanDogra1989 for Azure SDK v2 issues please create the issue in this repository https://github.com/Azure/azure-sdk-for-net/issues. This repository is just for the Semantic Kernel. Thanks!
