### ISSUE TITLE
how to create customized functions in the planner

### ISSUE THREAD

**Issue by Bdl-1989** [microsoft/semantic-kernel#819]

**Comment by timlaverty** [comment]
@lemillermicrosoft

**Comment by evchaki** [comment]
@Bdl-1989 , tell me more about what you would like planner to do for you?

**Comment by Bdl-1989** [comment]
> @Bdl-1989 , tell me more about what you would like planner to do for you?

![image](https://github.com/microsoft/semantic-kernel/assets/48614612/7a343e5b-e9ca-4bbb-8af7-ff3c50647893)
for example, the 3rd function should be build-in function, just for demo. I want to customize it to get my real address from my outlook.

**Comment by lemillermicrosoft** [comment]
There is a set of skills available for interacting with MSGraph and a few CoreSkills in the kernel. If the ask is for a specific kind of skill/plugin to be created, please open a new issue with that request. Thanks!
