### ISSUE TITLE
.Net: How To Get KernelFunction Name from `IChatCompletionService.GetStreamingChatMessageContentsAsync`

### ISSUE THREAD

**Issue by nor0x** [microsoft/semantic-kernel#8220]
**Describe the bug**
I'm developing several KernelFunctions which are invoked from a client. Is there a way to retrieve metadata from the function in the streaming responses in `GetStreamingChatMessageContentsAsync` from `IChatCompletionService` ? 
The function name would already help me with my usecase.

Currently the FunctionName in the response `InnerContent` is empty eventhough the function was called correctly:
![image](https://github.com/user-attachments/assets/92dea92f-d198-43c3-904f-b2912f47ce4e)

I have already tried adding a Filter to intercept the response after the function result was created:

```csharp
public class FunctionsFilter : IFunctionInvocationFilter, IAutoFunctionInvocationFilter
{
	public async Task OnAutoFunctionInvocationAsync(AutoFunctionInvocationContext context, Func<AutoFunctionInvocationContext, Task> next)
	{
		Debug.WriteLine($"Invoking {context.Function.Name}");

		await next(context);

		var result = context.Result;

		context.Result = new FunctionResult(context.Function, result.ToString(), metadata: new Dictionary<string, object>
		{
			{ "function", context.Function.Name }
		});
....
```

there I wanted to add `context.Function.Name` as MetaData to the context, but as you can see on the screenshot the MetaData is not present in the response

**Expected behavior**
`IChatCompletionService.GetStreamingChatMessageContentsAsync` reponse should contain information or metadata about which KernelFunctions were called

I'm using the Microsoft.SemanticKernel NuGet package version 1.17.1

**Comment by SergeyMenshykh** [comment]
Closing the issue for now. @nor0x, feel free to reopen it if neither of the solutions works for you.

**Comment by nor0x** [comment]
thank you! works just fine 🥳
