### ISSUE TITLE
CC: webapp documentation around AAD setup insufficient

### ISSUE THREAD

**Issue by IanNorris** [microsoft/semantic-kernel#825]
**Describe the bug**
When setting up the app for the first time with AAD authentication, a new AAD application is required. Please document the required settings, and for example what redirect URLs are required for the application.

Likewise the models required to be deployed should be listed for Azure OpenAI so they're in one place.

**To Reproduce**
Deploy a new local instance with a new AAD app and note missing info in the docs.

**Expected behavior**
The setup instructions should document all necessary steps to get the application running.

**Comment by cchighman** [comment]
Hi IAmNorris, did you follow the steps in the README and the inline documentation within appsetttings?

In README, I followed these instructions for AAD which includes redirects:
![image](https://user-images.githubusercontent.com/659214/236578600-9ed4a8e7-3299-4270-9743-003d28dabb34.png)

From the appsettings file in webapi, I followed guidance shown here and chose gpt-35-turbo for completions and text-embedding-ada-002 for embeddings based on the examples mentioned.  (Scrambled my endpoint and key)
![image](https://user-images.githubusercontent.com/659214/236578829-eba2f573-8ccc-4095-ad6f-69189e2a007a.png)

**Comment by IanNorris** [comment]
Thanks @evchaki, I'd managed to miss the bit about redirect URIs in the docs, I'm not sure how I missed it. However even when configured as described I'm now getting a 401 from the backend, with the error: `Bearer error="invalid_token", error_description="The signature is invalid"`.

For the time being I've disabled Authorization. If anyone on the dev team has seen this error before it may be useful to document it here for others searching for the issue as well.

**Comment by glahaye** [comment]
Note that, as a mitigation while we make the doc better and your 401's are figured out, you can use an API key to auth to the Copilot Chat:
[Authorization](https://github.com/glahaye/semantic-kernel/tree/main/samples/apps/copilot-chat-app/webapi/DeploymentTemplates#authorization) instead of being wide open.

**Comment by glahaye** [comment]
Chat Copilot is moving to its own repo.  Closing this issues but opening a corresponding one in the new repo:
https://github.com/microsoft/chat-copilot/issues/38
