### ISSUE TITLE
.Net Bug: OpenAPI descriptions overriding path parameters in operations are not supported

### ISSUE THREAD

**Issue by calebkiage** [microsoft/semantic-kernel#8269]
**Describe the bug**
According to the [OpenAPI spec](https://spec.openapis.org/oas/v3.0.3#fixed-fields-7), parameters in the operation object that match parameters in the path item object should override the path item object descriptions. Semantic Kernel currently only uses parameters under the operation object.

An example OpenAPI:

```json
{
  "openapi": "3.0.3",
  "info": {
    "title": "Test Schema",
    "version": "0"
  },
  "servers": [
    {"url": "https://localhost:3000"}
  ],
  "paths": {
    "/users/{userId}": {
      "get": {
        "operationId": "getUserById",
        "responses": {
          "default": {
            "description": ""
          }
        },
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ]
      },
      "parameters": [
        {
          "name": "userId",
          "in": "path",
          "required": true
        }
      ]
    }
  }
}
```

**Expected behavior**
Semantic kernel should consider path item parameters as well as operation parameters when building a plugin. If a parameter appears in both the path item and the operation item, the operation item path should be used. In the above OpenAPI, the `userId` parameter should have a schema with type integer.

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#
 - Source: main branch of repository

**Additional context**
Related to #8268

**Comment by markwallace-microsoft** [comment]
Hi @calebkiage thanks for creating this issue. Is this a blocking issue for you and if yes, can you  provide some detail on the impact to help us to prioritise this.

**Comment by markwallace-microsoft** [comment]
The SK Open API support does not cover 100% of the Open API specification. As features are requested we aim to provide a functionality very quickly, typically this happens in time for our next weekly release. Closing this issue until we get a customer request where this is a blocking issues.
