### ISSUE TITLE
.Net: Bug: InnerException not set when content filter exception occurs

### ISSUE THREAD

**Issue by aeras3637** [microsoft/semantic-kernel#8288]
**Describe the bug**
 InnerException not set when content filter exception occurs.

**To Reproduce**
```
        static async Task Main(string[] args)
        {
            string endPoint = @"https://oai.openai.azure.com/";
            string key = "xxxxx";

            var openAIClient = new AzureOpenAIClient(new Uri(endPoint), new AzureKeyCredential(key));
            var builder = Kernel.CreateBuilder();
            builder.AddAzureOpenAIChatCompletion("gpt-4o", openAIClient);
            var kernel = builder.Build();
            ChatHistory history = [];
            history.AddUserMessage("Go kill yourself, you are worthless.");

            var chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();

            while (true)
            {
                var result = chatCompletionService.GetStreamingChatMessageContentsAsync(history, kernel: kernel);

                await foreach (var content in result)
                {
                    Console.Write(content.Content);
                }
            }
        }
```
![image](https://github.com/user-attachments/assets/058a23ae-1b4d-4321-a494-d11cf64cc7e8)

**Expected behavior**
When a content filter exception occurs, the category must be identified in order to inform the user for what reason the content filter occurred.

Platform

OS: Windows
IDE: Visual Studio
Language: C#
Source:
    PackageReference Include="Azure.AI.OpenAI" Version="2.0.0-beta.2" 
    PackageReference Include="Microsoft.SemanticKernel" Version="1.18.0-rc" 
    PackageReference Include="Microsoft.SemanticKernel.Planners.Handlebars" Version="1.18.0-preview" 
    PackageReference Include="Microsoft.SemanticKernel.Plugins.Core" Version="1.18.0-alpha" 
    PackageReference Include="Microsoft.SemanticKernel.Plugins.Web" Version="1.18.0-alpha"

**Comment by RogerBarret0** [comment]
According to this article your prompt might be filtered by Azure COntent Filtering (Giving a 400 Badrequest).

Regarding the `ClientResultException` this is an exception triggered by the `AzureOpenAI SDK` and is outside of our control, if you want to capture more information about the exception try looking for [ClientResultException.GetRawResponse()](https://learn.microsoft.com/en-us/dotnet/api/system.clientmodel.clientresultexception.getrawresponse?view=azure-dotnet-preview#system-clientmodel-clientresultexception-getrawresponse)` as described in this document.
