### ISSUE TITLE
.Net: Bug: .Net Function calling Stepwise Planner not adhering to openai.yaml request format specified when calling plugins behind easyauth

### ISSUE THREAD

**Issue by gladiatorAsh** [microsoft/semantic-kernel#8310]
**Describe the bug**
We have multiple plugins deployed and working in Azure which connect to different data sources, All of them have easyAuth enabled and have no issues being called directly from Postman etc. with the correct token.

When we import these plugins in Function calling Stepwise Planner code to orchestrate them for a specific result, we see different results when we enable easyAuth than when we do it without.

When easyAuth is disabled, plugins are called by planner and we see expected results in most cases. But when we enable easyAuth, we see mostly 500s and sometimes 200s seemingly randomy, as planner makes API calls to these plugin endpoints in a format which is not as per the openapi.yaml specification of the plugins. We see empty requests being made without values leading to issues and no content returned. 

**To Reproduce**
1. Import already working plugins in Function Calling Stepwise Planner
2. Disable easy Auth and planner is able to orchestrate and provide expected results.
3. Enable easy Auth for apps with correct token and aud verified, no 401s but plugins are hit with requests in the invalid format leading to 500s there.
**Expected behavior**
No difference when easyAuth is enabled than when it is not.

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: Semantic Kernel 1.16.1

**Additional context**

**Comment by markwallace-microsoft** [comment]
@gladiatorAsh We are advising customers to stop using the Function Calling planner in favour of direct Function Calling. We have created the following two articles to help customers transition away from the current planners.

1. [The future of Planners in Semantic Kernel](https://devblogs.microsoft.com/semantic-kernel/the-future-of-planners-in-semantic-kernel/)

1. [Planning with Semantic Kernel using Automatic Function Calling](https://devblogs.microsoft.com/semantic-kernel/planning-with-semantic-kernel-using-automatic-function-calling/)
