### ISSUE TITLE
.Net: Bug: AssistantChatMessage has no Participant Property

### ISSUE THREAD

**Issue by method-marco** [microsoft/semantic-kernel#8325]
**Describe the bug**
Kernel.InvokePromptStreamingAsync throws System.MissingMethodException
--> 'Method not found: 'Void OpenAI.Chat.AssistantChatMessage.set_ParticipantName(System.String)'.'

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: NuGet Package Microsoft.SemanticKernel 1.18.0-rc

**Additional context**
Checking the Source Code on Branch dotnet-1.18.0 reveals the following code:
[new AssistantChatMessage(message.Content) { ParticipantName = message.AuthorName }];

**Comment by method-marco** [comment]
switching form .net 6 to .net 8 resolves the issue

**Comment by matthewbolanos** [comment]
@RogerBarreto, could you validate that there's nothing lurking here that we should be concerned about?

**Comment by RogerBarret0** [comment]
@matthewbolanos @method-marco 
Please confirm which version of `OpenAI` package are you using in the solution?

As far as I understand we support only `OpenAI-beta.5` any attempt on using a different OpenAI package version may cause conflicts.

This might be related with their [recent changes from `init` to `set` in this property](https://github.com/openai/openai-dotnet/commit/58f93c8d5ea080adfee8b37ae3cc034ebb06c79f#diff-0b6bfbb86ea2fca40f6c3441ee583b5c4e7a2527af4fde04462c22c47b3ad768R109).

Please provide more context on the versions used and code for reproduction.

**Comment by RogerBarreto** [comment]
@method-marco Small correction from my part the error is expected when you run the `.Net 6`

We do not support `.net 6` for Semantic Kernel since our 1.0 release.
