### ISSUE TITLE
Bug: Microsoft.SemanticKernel.Connectors.Onnx does not contain an implementation of ITextGenerationService

### ISSUE THREAD

**Issue by Barshan-Mandal** [microsoft/semantic-kernel#8329]
Bug: Microsoft.SemanticKernel.Connectors.Onnx does not contain an implementation of ITextGeneration service.Add this implementtation as without it,we cant use kernel memory

**Comment by Barshan-Mandal** [comment]
REQUIRES FOR USING MICROSOFT.KERNEL MEMORY

**Comment by evchaki** [comment]
@dluc - can you look at this?

**Comment by arafattehsin** [comment]
I think it's a pretty valid scenario and I encountered a similar issue hence landed here.

**Comment by arafattehsin** [comment]
https://arafattehsin.com/give-local-memories-to-your-local-ai-agents/ I have tried to solve this problem by writing something of my own but I still believe it's not optimised and we need a better way to do it. Hopefully it may solve immediate problems for others.

**Comment by markwallace-microsoft** [comment]
Closing as stale
