### ISSUE TITLE
Python: Bug: Python package does not specify the license

### ISSUE THREAD

**Issue by brycecutt-msft** [microsoft/semantic-kernel#8341]
**Describe the bug**
The pyproject.toml and PyPi hosted Python package do not list a license for the semantic-kernel package.

**To Reproduce**
1. Confirm LICENSE file in repo indicates the MIT license is in use:
   - https://github.com/microsoft/semantic-kernel/blob/main/LICENSE
2. Review PyPi page and pyproject.toml file and notice that no license is specified:
   - https://pypi.org/project/semantic-kernel/
   - https://github.com/microsoft/semantic-kernel/blob/main/python/pyproject.toml
3. Ask pip to show details for the package and notice that the License field is empty:
```bash
$ pip show semantic-kernel
Name: semantic-kernel
Version: 1.8.0
Summary: Semantic Kernel Python SDK
Home-page: https://learn.microsoft.com/en-us/semantic-kernel/overview/
Author: Microsoft
Author-email: SK-Support@microsoft.com
License: 
Location: /home/vscode/.local/lib/python3.11/site-packages
Requires: aiohttp, defusedxml, jinja2, nest-asyncio, numpy, openai, openapi_core, opentelemetry-api, opentelemetry-sdk, pandas, prance, pybars4, pydantic, pydantic-settings
Required-by: REDACTED
```

**Expected behavior**
PyPi page and pip show output specify the same license as the LICENSE file in the repo.

**Platform**
 - OS: Linux
 - IDE: VS Code
 - Language: Python
 - Source: pip package version 1.8.0

**Additional context**
clearlydefined PR for this package:
https://github.com/clearlydefined/curated-data/pull/28405

**Comment by evchaki** [comment]
@eavanvalkenburg can you update this?
