### ISSUE TITLE
.Net Bug: Bing Connector and Azure AI Search Issue

### ISSUE THREAD

**Issue by Cobra86** [microsoft/semantic-kernel#8347]
**Describe the bug**
When using the Web Search Engine plugin and Bing Connector in combination with Azure AI Search in the same request, I occasionally encounter a 400 Bad Request error, although it works at other times.

Error Message: "Invalid chat message detected: message content must be string"

**Platform**
- AI Model: Azure OpenAI GPT4o
- OS: Windows
- IDE: Visual Studio
- Language: C#
- Source: NuGet package version 1.17.1

**Comment by evchaki** [comment]
@Cobra86 can you provide more details on this?

**Comment by evchaki** [comment]
@markwallace-microsoft  - FYI
