### ISSUE TITLE
CC: Allow plugins within Copilot chat to be easily configured

### ISSUE THREAD

**Issue by dedalo** [microsoft/semantic-kernel#837]
Action planner skills should be configurable, maybe by directory in the appsettings, or a namelist, at this moment the skills are hardtiped.

**Comment by evchaki** [comment]
@dedalo , good suggestion. Feel free to change the code as needed.  I think this is a good one to make it easier for everyone to configure in the future.

**Comment by ebigunso** [comment]
I second this.
By handing custom skill sets to an action planner, the planner can be used not only as a global top level planner, but more easily used as a module in a pipeline as well.

A related suggestion:
Skills should be able to be sorted into skill groups, or have group tags attached to them. When creating custom skill sets as in this use case, that would make life much easier.
(Maybe this should be separated into a different issue?)

**Comment by matthewbolanos** [comment]
Closing since this is now possible
