### ISSUE TITLE
Python: Bug: Failed to find function 'WriterPlugin.ShortPoem' in planner notebook using GPT-4o-mini

### ISSUE THREAD

**Issue by ark-kairu** [microsoft/semantic-kernel#8395]
**Describe the bug**
I'm running the planner Python [notebook](https://github.com/microsoft/semantic-kernel/blob/main/python/samples/getting_started/05-using-the-planner.ipynb) using the OpenAI service and GPT-4o-mini model. I was running this block under the **Sequential Planner** section:

`sequential_plan = await planner.create_plan(goal=ask)`

And I ran into this error:

`PlannerInvalidPlanError: Failed to find function 'WriterPlugin.ShortPoem'.`

I printed `plan_result_string` as defined on line 113 in `semantic_kernel/planners/sequential_planner/sequential_planner.py` and noticed that all other functions were formatted as `<Plugin>-<Function>` within a hyphen separating plugin and function names. However, `WriterPlugin` and `ShortPoem` were separated by a period, which likely caused the planner to throw the above error.

When I switched to GPT-3.5-Turbo, the planner correctly formatted the function calls and the issue went away.

**To Reproduce**
1. Set environment variables as follows:
```
export OPENAI_API_KEY="sk-..."
export GLOBAL_LLM_SERVICE="OpenAI"
export OPENAI_ORG_ID="org-..."
export OPENAI_CHAT_MODEL_ID="gpt-4o-mini"
export OPENAI_TEXT_MODEL_ID="gpt-4o-mini"
export OPENAI_EMBEDDING_MODEL_ID="text-embedding-ada-002"
```
2. Run the planner notebook (linked above) up to and including the block that creates the plan:
`sequential_plan = await planner.create_plan(goal=ask)`
3. "Fix" the issue by replacing the model ID environment variables with `gpt-3.5-turbo`.

**Expected behavior**
Ideally, 4o-mini would format the function calls correctly.

**Platform**
 - OS: Mac
 - IDE: VS Code
 - Language: Python
 - Source: semantic-kernel v1.8.0

**Comment by evchaki** [comment]
@ark-kairu - check out function calling, it should be a better option here. This could also be helpful - https://devblogs.microsoft.com/semantic-kernel/the-future-of-planners-in-semantic-kernel/

**Comment by moonbox3** [comment]
Closing this item as we are recommending that devs use function calling instead of planners. The notebook will be cleaned up when the planner code is finally deprecated.
