### ISSUE TITLE
Java: .Net: New Feature: rate limit metadata

### ISSUE THREAD

**Issue by mku-wedoai** [microsoft/semantic-kernel#8421]
Raw Azure OpenAi chat completion response contains additional headers, which contain information about rate limits: 
`x-rate-limit-remaining-requests` and `x-ratelimit-remaining-tokens`. Would it be possible to add these values to the `Metadata` dictionary in both `OpenAIStreamingChatMessageContent` and `OpenAIChatMessageContent` class? I find rate limit information useful, but in current .Net implementation there is no way to access it.

**Comment by markwallace-microsoft** [comment]
@d3r3kk @johnoliver @moonbox3 We should implement this in Java and Python also
