### ISSUE TITLE
Copilot-chat Add SignalR support for real-time status and message updates in backend

### ISSUE THREAD

**Issue by dedalo** [microsoft/semantic-kernel#843]
In order to enhance the user experience and provide real-time status updates to clients while the ChatSkill is processing messages, I propose the addition of SignalR support to the backend code. This feature would allow the backend to communicate with connected clients efficiently, sending progress updates and other relevant information as events unfold.

The proposed changes include:

Integrate SignalR into the existing backend codebase.
Refactor the ChatSkill class to include optional SignalR support, so that status updates can be sent to clients if the ChatHub instance is available.
These changes will enhance the overall user experience by providing real-time feedback on the progress of the chatbot's processing, allowing users to stay informed and engaged while interacting with the system.
Also will improve UX streaming the message back to the user, in the chat-gpt fashion.

this is a demo of a signalr client with status and message stream with copilot backend.
![SK_signalr_stream](https://user-images.githubusercontent.com/1019542/236675774-93a8ea85-b818-4d70-b3a0-7b9287130fa6.gif)

**Comment by evchaki** [comment]
@dedalo , good idea, we are working on bringing in SignalR into a sample app.

**Comment by hathind-ms** [comment]
Yes, we are bringing this into our Copilot chat sample: https://github.com/microsoft/semantic-kernel/pull/930

**Comment by dedalo** [comment]
@hathind-ms I see the branches are deleted and the PR closed, is this being continued somewhere else?

**Comment by hathind-ms** [comment]
Yes, it is still in works, looks like original PR was closed, but @amsacha and @TaoChenOSU are actively working on adding this support.

**Comment by alliscode** [comment]
This has been integrated into the Copilot sample app. We're closing this issue but please feel free to let us know if you see an issues. Thank you!
