### ISSUE TITLE
DeleteCollectionAsync is not deleting the collection, even if collection exists.

### ISSUE THREAD

**Issue by Jawahar-Mariappan** [microsoft/semantic-kernel#845]
**Describe the bug**
I reckon, the function 'DeleteCollectionAsync'
in "\semantic-kernel\dotnet\src\Connectors\Connectors.Memory.Qdrant\QdrantMemoryStore.cs" is having the logical error.

If collection exists then I reckon, we should delete them. The function '_qdrantClient.DoesCollectionExistAsync' returns true, if the collection exists. However, the conditional statement is having the not check so not deleting the collection, even if it exists.

**Comment by evchaki** [comment]
@Jawahar-Mariappan , thanks for bringing this up, we are looking into it.

**Comment by craigomatic** [comment]
Fixed in #1025
