### ISSUE TITLE
.Net: [documentation] about native code plugins ' document to what json schema property a c# attribute maps to 

### ISSUE THREAD

**Issue by sabbadino** [microsoft/semantic-kernel#8456]
in this link
https://learn.microsoft.com/en-us/semantic-kernel/concepts/plugins/adding-native-plugins?pivots=programming-language-csharp

its not clear how can have SK to generate a json schema where a property is marked as required see here for an openai example (https://platform.openai.com/docs/guides/function-calling)

**Comment by markwallace-microsoft** [comment]
@sabbadino SK will generate the schema for native plugins automatically. Take a look at this Blog Post for more information: https://devblogs.microsoft.com/semantic-kernel/diving-into-function-calling-and-its-json-schema-in-semantic-kernel-net/
