### ISSUE TITLE
Sample Python Notebook Application Error

### ISSUE THREAD

**Issue by nsteblay** [microsoft/semantic-kernel#846]
**Describe the bug**
There is an error in 00-getting-started.ipynb

**To Reproduce**
The line: kernel.add_text_completion_service("dv", OpenAITextCompletion("text-davinci-003", api_key, org_id))
Should be: kernel.config.add_text_completion_service("dv", OpenAITextCompletion("text-davinci-003", api_key, org_id))

Merge KernelConfig with Kernel (https://github.com/microsoft/semantic-kernel/pull/731) is culprit.  The notebooks were not tested apparently.  Since this is an introduction to the Semantic Kernel I would recommend that the code published actually works if at all possible.

**Comment by mkarle** [comment]
The pip package wasn’t updated yet, so when the notebook tries to install from `requirements.txt`, the change to kernel config reflected. To get around this until the pip package has been updated, uncomment `!python -m pip install ../../../python` in the first cell of the notebook, and comment out `!python -m pip install -r requirements.txt`

**Comment by shawncal** [comment]
New pip packages released:
https://pypi.org/project/semantic-kernel/0.2.7.dev0/

Closing as the pip packages now match the documentation. Thanks again for raising this!
