### ISSUE TITLE
Python: Feature Request: Implement ADR 0032 for Python

### ISSUE THREAD

**Issue by evmin** [microsoft/semantic-kernel#8509]
**Describe the bug**

When implementing a multi agent code sample from [0032-agents.md](https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0032-agents.md)ADR :

```python
# Create chat
chat = AgentGroupChat()
...
await write_message(chat.get_history())
```
[1 - Direct code link](https://github.com/microsoft/semantic-kernel/blob/cc63d56895ceea00f45315453935969b61b1bf4b/docs/decisions/0032-agents.md?plain=1#L405)

I receive the error:

```
AttributeError: 'AgentGroupChat' object has no attribute 'get_history'
```

**Expected behavior**
Ability to get the history from the chat as per documentation.

**Screenshots**

**Platform**
 - OS: Mac
 - IDE: VS Code
 - Language: Python

**Comment by moonbox3** [comment]
Hi @evmin, it looks like the ADR may be a bit stale and/or the implementation has deviated a bit. I looked in the dotnet code, and the behavior is similar to what is present in Python. In Python, the `get_history` method is an abstract method defined as part of the `AgentChannel` abstract class. The `AgentChat` class is accessing the history via the channel as shown here: 

https://github.com/microsoft/semantic-kernel/blob/cc63d56895ceea00f45315453935969b61b1bf4b/python/semantic_kernel/agents/group_chat/agent_chat.py#L88C21-L88C53

You would want to call `chat.get_chat_messages(...)` https://github.com/microsoft/semantic-kernel/blob/cc63d56895ceea00f45315453935969b61b1bf4b/python/semantic_kernel/agents/group_chat/agent_chat.py#L76 or follow a pattern similar to this, for the chat history:

https://github.com/microsoft/semantic-kernel/blob/main/python/samples/concepts/agents/chat_completion_function_termination.py

**Comment by moonbox3** [comment]
The answer has been provided, closing out. Please ping on this again if you need assistance, thanks.
