### ISSUE TITLE
Add samples showing how to manage Chat History

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#8518]
Provide some samples to address the following questions:

1. What are the strategies to manage chat history when it goes out of context?
2. How to manage buffer and condensate informations?

**Comment by jonpopa** [comment]
Hi there, here are a couple of annotations based on the previous questions:

**Q1**. When chat history grows too long, and responses start becoming irrelevant or confusing, we need strategies to maintain coherent context by either truncate the history or summarize older parts of the conversation. 
In this case:
 - How do we handle older chat history to keep it relevant for long conversations?
 - How can we reintroduce older context if a user suddenly refers back to it?
 
 **Q2**. We'd like to use a buffer system where the recent N messages are stored for context, while older messages are either summarized or archived for future reference.
 - How could we ensure important context isn’t lost when condensing long conversations?
 - How could we dynamically adjust the buffer size when the user shifts topics frequently?
 
 Thanks in advance!
 Ion
