### ISSUE TITLE
.Net: Bug: HTTP 404 - POST /chat/completions

### ISSUE THREAD

**Issue by johnholliday** [microsoft/semantic-kernel#8525]
**Describe the bug**
Exception thrown: 'Microsoft.SemanticKernel.HttpOperationException' in mscorlib.dll
Exception thrown: 'System.AggregatException' in mscorlib.dll
HTTP 404 (invalid_request_error: unknown_url)

Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.
HTTP 404 (invalid_request_error: unknown_url)

**To Reproduce**
```
var builder = Kernel.CreateBuilder();
builder.AddOpenAIChatCompletion("gpt-4o", OPENAI_APIKEY);
var _kernel = builder.Build();

var service = _kernel.GetRequiredService<IChatCompletionService>();

var settings = new OpenAIPromptExecutionSettings
{
    Temperature = 1.05F,
    TopP = 1F,
    MaxTokens = 4096,
    ResponseFormat = "json_object"
};

var chat = new ChatHistory();
var ct = new CancellationTokenSource();
chat.AddUserMessage("tell me something good");
var content = await service.GetChatMessageContentsAsync(chat, settings, _kernel, ct.Token);
```

**Expected behavior**
'content' variable contains the message result.

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio 2022
 - Language: C#
 - Source: Microsoft.SemanticKernel v 1.18.2

**Additional context**
Was working, then suddenly started throwing this exception.

**Comment by johnholliday** [comment]
Exception:
```
HTTP 404 (invalid_request_error: unknown_url)

Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.
```

Inner Exception StackTrace:
```
   at OpenAI.ClientPipelineExtensions.<ProcessMessageAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenAI.Chat.ChatClient.<CompleteChatAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenAI.Chat.ChatClient.<CompleteChatAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<RunRequestAsync>d__65`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetChatMessageContentsAsync>d__15.MoveNext()
```

RequestUri:
![image](https://github.com/user-attachments/assets/1eb8a81a-4b34-4e58-a5f7-b97f30ebc00f)

**Comment by evchaki** [comment]
@dmytrostruk - can you quickly look into this.  Seems like something might have changed during the last update.

**Comment by evchaki** [comment]
@johnholliday - I tried this also and did not get any errors.  One thing to try locally is to hard code your model and key into AddOpenAIChatCompletion to see if there is something broken in the variables you currently have.

**Comment by RogerBarreto** [comment]
Just one observation when updating to the new `OpenAI SDK` for our `OpenAI Connector` we had a limitation that was enforced from their SDK where the SDK will enforce the endpoints to end with `v1/chat/completions`, before endpoints that finished with `chat/completions` where enough.

Another observation is that the connector expects the BaseAddress to be provided by an `endpoint` or by the `httpClient`, if you are providing an httpClient that is being shared across different tests and nullifying it's BaseAddress you may be getting this error.

**Comment by CesarEContreras** [comment]
I just recently started a new project and wanted to try it out. First run and got the same error.

```
Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.
---> System.ClientModel.ClientResultException: HTTP 404 (invalid_request_error: unknown_url)

Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.
    at OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
    at OpenAI.Chat.ChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)
    at OpenAI.Chat.ChatClient.CompleteChatAsync(IEnumerable 1 messages, ChatCompletionOptions options, CancellationToken cancellationToken)
    at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func1 request)
--- End of inner exception stack trace ---
```

**Comment by RogerBarreto** [comment]
Please confirm if you are using `OpenAI.beta10` or `OpenAI.beta11` versions. This may happen if you are using the `beta11` against `1.18.2` or `1.19.0` which is targetting `OpenAI.beta10`. The URL behavior in `beta11` changed, and we have a PR to update our connectors to the latest version.

**Comment by daverant** [comment]
@RogerBarreto I think that'll be it. Thanks for the replies folks, apologies for the delayed response! Here's a repro:

```
    <PackageVersion Include="Microsoft.SemanticKernel.Abstractions" Version="1.19.0" />
    <PackageVersion Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.19.0" />
    <PackageVersion Include="Microsoft.SemanticKernel.Core" Version="1.19.0" />
    <PackageVersion Include="OpenAI" Version="2.0.0-beta.11" />
```
```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.ChatCompletion;

internal class ChatCompletionServiceTests
{
    [Test]
    public async Task AddKernelToServiceCollection_CredentialsAreValid_ReturnsResponse()
    {
        var services = new ServiceCollection();
        services.AddKernel();
        services.AddOpenAIChatCompletion("gpt-4o", Environment.GetEnvironmentVariable("OpenAIApiKey")!, Environment.GetEnvironmentVariable("OpenAIOrgId")!);
        var provider = services.BuildServiceProvider();
        var chatService = provider.GetRequiredService<IChatCompletionService>();
        var kernel = provider.GetRequiredService<Kernel>();
        _ = await chatService.GetChatMessageContentAsync("How much wood can a woodchuck chuck?", kernel: kernel);
    }
}
```

**Comment by RogerBarreto** [comment]
Yeah, that make sense and prove the point, for now use the `OpenAI.beta10` and you will be fine.

Semantic Kernel 1.17 didn't use the `OpenAI SDK` yet. (New Connectors arrived in 1.18.2+)

**Comment by RogerBarreto** [comment]
Will close this as soon we have the related PR merged.
