### ISSUE TITLE
Python: Issue: openai.BadRequestError: Unsupported data type

### ISSUE THREAD

**Issue by sheelaj123** [microsoft/semantic-kernel#8529]
**openai.BadRequestError: Unsupported data type**

Hi Team ,

I'm trying to debug Azure Assistant- Agent , path : -semantic-kernel\python\samples\getting_started_with_agents\step7_assistant.py 
then I'm getting below issue-

Exception has occurred: BadRequestError
Unsupported data type
httpx.HTTPStatusError: Client error '400 model_error' for url ()

please suggest me any idea how to resolve this issue.

thanks,

**Comment by moonbox3** [comment]
Hello @sheelaj123, can you please provide some more details/context here so we can help? Do you have your .env file populated with the correct Azure OpenAI values (endpoint, api key, api version, etc)? 

Are you simply trying to run the step7_assistant.py sample and this error occurs? Do you have a larger stack trace you can send? Thanks.

**Comment by sheelaj123** [comment]
Hello @moonbox3 ,

Actually first I've describe a class inside this my Azure credentials something looks like given below- 

class AzureOpenAIConfig:
    CHAT_SERVICE_ID = "default"
    API_KEY="XXXXXXXXXXXXXXXXXXXXXXXXX"
    DEPLOYMENT_NAME="My_Model"
    END_POINT="XXXXXXXXXXX"
    AGENT_SERVICEID="agent"
    
after that I've defined agent in this way--

 def add_azure_assistant_agent(knl:Kernel)->AzureAssistantAgent:
    knl.add_service(
                AzureChatCompletion(
                    service_id=config.CHAT_SERVICE_ID,
                    api_key= config.API_KEY,
                    deployment_name=config.DEPLOYMENT_NAME,
                    endpoint=config.END_POINT))
    return kernel
    
    now finally when we try to debug then its throwing me "Unsupported data type"
    
    please let me know if you can solve this issue.

**Comment by moonbox3** [comment]
Thanks for your response @sheelaj123. I'm not seeing any definition for an `AzureAssistantAgent` in the code you provided (the only thing I see for `AzureAssistantAgent` is the return type hint for your `add_azure_assistant_agent` method). You're adding an `AzureChatCompletion` AI Service to the kernel, but that is for a chat completion (agent) and not for an OpenAI assistant agent. 

Please do a favor and enable debug logging in your script with the following:

```python
import logging
```

and then below the imports:

```
logging.basicConfig(level=logging.DEBUG)
```

PLEASE NOTE: this logging will include your API KEY as part of the output -- PLEASE do not include the API key or other sensitive information when providing the debug logging. With this logging, it should help us understand what may be happening.

Additionally, if you can supply your entire script, I can try and reproduce it.
