### ISSUE TITLE
Python SDK: 'Kernel' object has no attribute 'add_text_completion_service'

### ISSUE THREAD

**Issue by FlorianPydde** [microsoft/semantic-kernel#854]
**Describe the bug**
When I try to use the function "add_text_completion_service" python raises the no attribute error.

**To Reproduce**
Simply following the notebook instructions: https://github.com/microsoft/semantic-kernel/tree/main/python

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[15], line 12
     10 # Alternative using Azure:
     11 deployment, api_key, endpoint = sk.azure_openai_settings_from_dot_env()
---> 12 kernel.add_text_completion_service("dv", AzureTextCompletion(deployment, endpoint, api_key))
     13 # sk.azure_openai_settings_from_dot_env(include_deployment=True)

AttributeError: 'Kernel' object has no attribute 'add_text_completion_service'

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE:  VS Code
 - Semantic Kernel version:  0.2.6.dev0

**Comment by lovettchris** [comment]
I get the same problem with "semantic-kernel 0.2.6.dev0"

**Comment by shawncal** [comment]
New pip packages released:
https://pypi.org/project/semantic-kernel/0.2.7.dev0/

Closing as the pip packages now match the documentation. Thanks again for raising this!

**Comment by lovettchris** [comment]
hi Shawn, works great now, thanks :-)
