### ISSUE TITLE
.Net: Bug: Typo in Default History Summarization prompt: summarizion should be summarization

### ISSUE THREAD

**Issue by jb-ross-bingham** [microsoft/semantic-kernel#8545]
**Describe the bug**
There is a minor misspelling of **summarization** in the default summarization prompt, which is sent to the LLM. Clearly, the LLM understands the prompt, even with the misspelling, but I'm pointing it out in case it helps.

[Line in github](https://github.com/microsoft/semantic-kernel/blob/821968a2631e4c3ce41fb953bbad1e52ac8a9eed/dotnet/src/Agents/Core/History/ChatHistorySummarizationReducer.cs#L32)

....`concise and complete summarizion`... should read ....`concise and complete summarization`... 

````
    public const string DefaultSummarizationPrompt =
        """
        Provide a concise and complete summarizion of the entire dialog that does not exceed 5 sentences

        This summary must always:
        - Consider both user and assistant interactions
        - Maintain continuity for the purpose of further dialog
        - Include details from any existing summary
        - Focus on the most significant aspects of the dialog

        This summary must never:
        - Critique, correct, interpret, presume, or assume
        - Identify faults, mistakes, misunderstanding, or correctness
        - Analyze what has not occurred
        - Exclude details from any existing summary
        """;
````

**To Reproduce**
I apologize if this isn't technically a bug. There are no steps to reproduce, the misspelling is in the source code, linked above.

**Expected behavior**
(no expected behavior)

**Screenshots**
(no screenshots)

**Platform**
N/A

**Additional context**
Apologies if this wasted someone's time. Just pointing it out in case it helps.

**Comment by evchaki** [comment]
@jb-ross-bingham - thanks for finding this.  Feel free to submit a PR to fix it and we will push it in.

**Comment by evchaki** [comment]
@Niladri24dutta you sure can!  Thank you.

**Comment by Niladri24dutta** [comment]
@evchaki  I have already opened a PR, Can you please let me know if it looks fine?
