### ISSUE TITLE
.Net: Azure AI Inference Participant Name Support

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#8591]
The current Azure AI Inference COnnector does not support extended response properties, and without that we can't capture the `ParticipantName` information that may be available when running against OpenAI models with the connector.

Creating this ticket to keep track of issue below and apply the fix when this is available.
- https://github.com/Azure/azure-sdk-for-net/issues/45415

**Comment by markwallace-microsoft** [comment]
Closing as stale
