### ISSUE TITLE
.Net: Bug: try to run HomeAutomation

### ISSUE THREAD

**Issue by shashankms9** [microsoft/semantic-kernel#8593]
**Describe the bug**
 I'm trying to use the demo code https://github.com/microsoft/semantic-kernel/tree/main/dotnet/samples/Demos/HomeAutomation

When I try to HomeAutomation through **dotnet build** and **dotnet run** It throws an issue Microsoft.Extensions.Options.OptionsValidationException: DataAnnotation validation failed for 'AzureOpenAIOptions' members: 'ChatDeploymentName' with the error: 'The ChatDeploymentName field is required.'.; DataAnnotation validation failed for 'AzureOpenAIOptions' members: 'Endpoint' with the error: 'The Endpoint field is required.'.; DataAnnotation validation failed for 'AzureOpenAIOptions' members: 'ApiKey' with the error: 'The ApiKey field is required.'.

Even though we have updated the appsetting.json  file

![image](https://github.com/user-attachments/assets/93cf8ffc-db60-4f3c-a5a8-56c53259b5a2)

**Comment by evchaki** [comment]
@shashankms9 - make sure you setup keys, it looks like these are missing which is why you are getting the error.

**Comment by shashankms9** [comment]
@evchaki, I have tried both approach methods mentioned in the readme.md file still throwing the same error

**Comment by evchaki** [comment]
@markwallace-microsoft  can you take a look?

**Comment by shashankms9** [comment]
@markwallace-microsoft can you please help in resolving this issue?

**Comment by shashankms9** [comment]
Hi @evchaki, the issue has been resolved after updating 

- The `appsetting.json` file with AzureOpenAIOption it was AzureOpenAI as in AzureOpenAIOptions.cs file provided class name as AzureOpenAIOptions

    ![image](https://github.com/user-attachments/assets/61df712c-dfe9-4fca-b978-86d31721a2ce)

- Updated the `Program.cs` files to use Azure OpenAI option and IOption to AzureOpenAIOption from AzureOpenAI
![image](https://github.com/user-attachments/assets/0b8ee02f-dcdc-4377-8026-8e2e2bbfaca3)

- After updating this I was able to run the application without any issue

**Comment by RogerBarreto** [comment]
@Niladri24dutta go ahead, I would like to take a look on the PR, and suggest or approve it. THanks.
