### ISSUE TITLE
.Net: Bug: Auth headers for Phi 3.5 and AzureOpenAIChatCompletion

### ISSUE THREAD

**Issue by tfsjohan** [microsoft/semantic-kernel#8624]
**Describe the bug**
Using Semantic Kernel with Phi 3.5 Vision Instruct model hosted as server less on Azure fails to add proper auth headers.

**To Reproduce**
I'm using the .net SDK for Semantic Kernel with AddAzureOpenAIChatCompletion. I'm trying to use Phi 3.5 Vision Instruct hosted on Azure as a serverless model. When I run the code it fails to authenticate. It doesn't matter which of the available endpoints I use. 

Using the exact same code with a GPT4o endpoint works fine. 

**Expected behavior**
Expected auth headers to be set correctly. 

**Error message**
```json
"type": "https://tools.ietf.org/html/rfc9110#section-15.6.1",
    "title": "Microsoft.SemanticKernel.HttpOperationException",
    "status": 500,
    "detail": "Service request failed.\nStatus: 400 (Missing Authorization header)\n",
    "traceId": "00-90c0e66ab6897371b76f44ed440de804-01bfbe0b6243cafc-00",
    "exception": {
        "details": "Microsoft.SemanticKernel.HttpOperationException: Service request failed.\nStatus: 400 (Missing Authorization header)\n\n ---> System.ClientModel.ClientResultException: Service request failed.\nStatus: 400 (Missing Authorization header)\n\n   at Azure.AI.OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)\n   at Azure.AI.OpenAI.Chat.AzureChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)\n   at OpenAI.Chat.ChatClient.CompleteChatAsync(IEnumerable`1 messages, ChatCompletionOptions options, CancellationToken cancellationToken)\n   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func`1 request)\n   --- End of inner exception stack trace ---\n   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func`1 request)\n   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetChatMessageContentsAsync(String targetModel, ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)\n   at Microsoft.SemanticKernel.ChatCompletion.ChatCompletionServiceExtensions.GetChatMessageContentAsync(IChatCompletionService chatCompletionService, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)\n   at 
[....]
```

**Comment by evchaki** [comment]
@RogerBarreto - can you take a look at this?

**Comment by RogerBarreto** [comment]
By the nature of your error seems to be related to how you setup your authentication. Ensure this endpoint matches your authentication form.

AFAIK Azure AI Studio deployments currently only support KeyBased authentication, if you code is using TokenAuthentication it may fail due to this reason.

Moving forward we also recommend to use the `Azure AI Inference` connector, planned to launch this week against Azure AI Studio Non-OpenAI Deployments.

Let me know if you manage to fix it.

**Comment by RogerBarreto** [comment]
Closing this as no response was given, assume the problem was resolved with the provided suggestion.
