### ISSUE TITLE
.Net: Bug: main branch build failed

### ISSUE THREAD

**Issue by gaoconggit** [microsoft/semantic-kernel#8651]
**Describe the bug**
C:\Program Files\dotnet\sdk\8.0.400\NuGet.targets(174,5): error : 当文件已存在时，无法创建该文件。 [E:\prj\semantic-kernel\dotnet\SK-dotnet.sln]

生成失败

**To Reproduce**
1. cmd run build.cmd

**Expected behavior**
   0 个警告 0 个错误

**Screenshots**

**Platform**
 - OS: Windows 10 x64

**Comment by gaoconggit** [comment]
![image](https://github.com/user-attachments/assets/f2cd6e88-96e2-4ea3-8d76-478bcf4247b1)

**Comment by markwallace-microsoft** [comment]
Hi @gaoconggit 
I believe the error messages says "You can't create a file when it already exists.". We're not seeing this issue in our CI/CD pipelines so I think this may be something in your local environment. Can you try cloning the repo to a different local and running the build again.

**Comment by markwallace-microsoft** [comment]
Closing as stale
