### ISSUE TITLE
.Net: AzureOpenAI/OpenAI connector v1.18.2 missing MemoryBuilder extensions methods

### ISSUE THREAD

**Issue by akordowski** [microsoft/semantic-kernel#8658]
I have seen that with the `v1.18.2` the Azure part of the `Microsoft.SemanticKernel.Connectors.OpenAI` connector was moved into the `Microsoft.SemanticKernel.Connectors.AzureOpenAI` connector. With that two `WithAzureOpenAITextEmbeddingGeneration` extension methods for the `MemoryBuilder` have been deleted from the [`OpenAIMemoryBuilderExtensions`](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.OpenAI/Extensions/OpenAIMemoryBuilderExtensions.cs) class but not provided in the `Microsoft.SemanticKernel.Connectors.AzureOpenAI` connector.

As the method signature differs from the `WithOpenAITextEmbeddingGeneration` extension method it would be great if they could be provied in the `AzureOpenAI` connector.

**Comment by markwallace-microsoft** [comment]
@akordowski We are in the process of updating the Semantic Kernel memory abstractions. The `MemoryBuilder` is the old way of doing things and our plan will be to obsolete these once the new abstractions are ready to graduate. So we don't want to add code that will eventually be removed to the new `AzureOpenAI` connector. If you are free to join our [community office hours](https://github.com/microsoft/semantic-kernel/blob/main/COMMUNITY.md) we will be discussing the new memory connectors today and likely every week or two for the next while.

**Comment by akordowski** [comment]
Thank you for the response and the explanation! I will close then the issue.

**Comment by aherrick** [comment]
so what project did the extension method move to? I can't upgrade my code since I'm using "WithAzureOpenAITextEmbeddingGeneration"

**Comment by akordowski** [comment]
They don't move anywhere. I just copied the code and created my own extension method 🤷‍♂️

**Comment by aherrick** [comment]
@akordowski  ahh ok TY

**Comment by aherrick** [comment]
this is what i came up with:

```
               .WithTextEmbeddingGeneration(
                   (loggerFactory, httpClient) =>
                   {
                       return new AzureOpenAITextEmbeddingGenerationService(
                           deploymentName,
                           endpoint,
                           apiKey,
                           httpClient: httpClient,
                           loggerFactory: loggerFactory
                       );
                   }
               )
```

**Comment by akordowski** [comment]
Yes, that's the same I have.
