### ISSUE TITLE
.Net: MongoClient reference error (v2.27.0 vs. 2.28.0) compile error

### ISSUE THREAD

**Issue by akordowski** [microsoft/semantic-kernel#8676]
**Describe the bug**
After updating the `Microsoft.SemanticKernel.Connectors.AzureCosmosDBMongoDB` and `Microsoft.SemanticKernel.Connectors.MongoDB` NuGet packages to Version `1.19.0-alpha` I get the following compile error:

`The type 'MongoClient' is defined in an assembly that is not referenced. You must add a reference to assembly 'MongoDB.Driver, Version=2.27.0.0, Culture=neutral, PublicKeyToken=null'.`

As you can see in the screenshots the version `2.28.0`is loaded. Cleaning all `bin/obj` didn't helped.

**Expected behavior**
The project should compile.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/b9277684-5ee2-4732-8c0c-d809564ab3d6)

![grafik](https://github.com/user-attachments/assets/e8e779af-0c84-4819-a54c-c6cbb4ec2b2f)

**Platform**
 - OS: Windows
 - IDE: Visual Studio 17.11.2
 - Language: C#

**Comment by akordowski** [comment]
Found the cause, the error occours after adding `KernelMemory` to the same solution has a dependecy to `v2.28.0` of the `MongoDB.Driver`. I tried to downgrade the Mongo packages but they are rollbacked. Is there a way to solve this issue?

**Comment by markwallace-microsoft** [comment]
@dluc Can Kernel Memory be upgraded to the latest Semantic Kernel releases?

**Comment by markwallace-microsoft** [comment]
@akordowski could you create an issue [here](https://github.com/microsoft/kernel-memory/issues). Thanks.

**Comment by akordowski** [comment]
@markwallace-microsoft Sorry for the late response. As I have seen KM is already updated to use SK 1.20.0.
