### ISSUE TITLE
.Net: Streaming Issue with AggregatorAgent in Nested Mode in version 1.19.0-alpha

### ISSUE THREAD

**Issue by slimktari** [microsoft/semantic-kernel#8677]
**Describe the bug**
When using AggregatorAgent in Nested mode with Semantic Kernel version 1.19.0-alpha, the AgentGroupChat streaming functionality with InvokeStreamingAsync does not work. The inner agents of the AggregatorAgent (which are ChatCompletionAgents inside an AgentGroupChat) are not triggered, and the method does not iterate over the agents as expected.

However, when the AggregatorAgent is switched to Flat mode, or when the outer AgentGroupChat containing the AggregatorAgent is removed, the InvokeStreamingAsync method works as expected, returning responses from the inner agents.

**To Reproduce**
1. Update Semantic Kernel to version 1.19.0-alpha.
2. Use the InvokeStreamingAsync method on an AgentGroupChat containing an AggregatorAgent in Nested mode.
3. The AggregatorAgent contains another AgentGroupChat with agents.
4. Note that the InvokeStreamingAsync function returns nothing.
`await foreach (var response in groupChat.InvokeStreamingAsync())
{
    if (string.IsNullOrEmpty(response.Content))
    {
        continue;
    }
    yield return response.Content;
}`

**Expected behavior**
I expected the InvokeStreamingAsync method to work with AggregatorAgent in Nested mode.

**Platform**
 - OS: Windows - OS: [e.g. Windows, Mac]
 - IDE: Visual Studio
 - Language: C#
 - Source: NuGet package version 1.19.0-alpha

**Comment by crickman** [comment]
@slimktari - Thank you for reporting this issue.  I'll dig into what's happening.

**Comment by anshul-rohilla** [comment]
Facing similar issue function not invoked when using InvokeStreamingAsync. Any workaround?

**Comment by slimktari** [comment]
@anshul-rohilla With an AgentGroupChat and two agents, the InvokeStreamingAsync method worked for me. Maybe we’re not using the same type of agents. In my case, my agents are of type ChatCompletionAgent. For reference, I use a selection and termination strategy of type KernelFunctionSelectionStrategy, which might make a difference.

The flat mode is specific to the AggregatorAgent. Essentially, you need an outer AgentGroupChat with the AggregatorAgent in flat mode and an inner AgentGroupChat with your two agents. You can see an example at this [link](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Concepts/Agents/ComplexChat_NestedShopper.cs), you would just need to change Nested to Flat.

But honestly, if the two agents directly in the AgentGroupChat don’t work, I think even with the AggregatorAgent, you’ll get the same result. Feel free to share the outcome if you do more tests in this direction.

**Comment by slimktari** [comment]
I just updated to Semantic Kernel version 1.20, and I still have the same issue.
