### ISSUE TITLE
Python: Bug: OpenAI Assistants Bad Request Error Expected tool outputs for call_ids

### ISSUE THREAD

**Issue by corytomlinson** [microsoft/semantic-kernel#8701]
**Describe the bug**
Will periodically get the following bad request error from OpenAI using Assistants...

`ERROR:root:OpenAI Bad Request Error: Error code: 400 - {'error': {'message': "Expected tool outputs for call_ids ['call_rVUDeHG5PsVJWQtIxNFyOF2e', 'call_c99StHnkSfOJAOqFcpDJxSu7', 'call_YERLpHqRWdbMiOE74rNn7Pjj', 'call_oBF2TANeA84hGAY4zciMWS60', 'call_a6Jx3NyOXx1U9I2L8yfCAEa5'], got ['call_rVUDeHG5PsVJWQtIxNFyOF2e']", 'type': 'invalid_request_error', 'param': None, 'code': None}}`

**To Reproduce**
1. Unsure how to recreate on demand. It happens frequently but not consistently

**Expected behavior**
No error

**Platform**
 - OS: Ubuntu in WSL2
 - IDE: VS Code
 - Language: Python 3.12
 - Source: pip semantic-kernel 1.8.3 / openai 1.45.0

**Additional context**
Debug logging provides no additional information about the cause of the error

**Comment by corytomlinson** [comment]
Without having much to go on is it possible that SK is not handling parallel tool calls correctly? The error seems to indicate multiple calls ids being expected, but only 1 being received. This could explain the intermittent behavior as well perhaps.

**Comment by corytomlinson** [comment]
Definitely a bug here. And almost certainly related to parallel tool call handling. It's a showstopper for me so hopefully can get some attention soon.

I've tried setting `parallel_tool_calls_enabled=False` in `AzureAssistantAgent` but that has no effect.

**Comment by moonbox3** [comment]
Will look at this today @corytomlinson.

**Comment by moonbox3** [comment]
> Thanks @moonbox3. FYI there was someone else on discord dealing with the same issue. I'm blocked so happy to help in any way I can.

Appreciate the support. I've already pinpointed the issue, so will have a fix out shortly. We're planning to make a release today as well, so this will be included.

**Comment by corytomlinson** [comment]
Thank you for the quick turnaround!
