### ISSUE TITLE
Java: Bug: 

### ISSUE THREAD

**Issue by Cheung-Z** [microsoft/semantic-kernel#8707]
**Describe the bug**
An error occurred while adding other AI service like Qwen API, according https://learn.microsoft.com/en-us/semantic-kernel/concepts/ai-services/chat-completion/?tabs=csharp-AzureOpenAI%2Cpython-other%2Cjava-AzureOpenAI&pivots=programming-language-python
TypeError: OpenAIChatCompletion.__init__() got an unexpected keyword argument 'base_url'

**To Reproduce**
`from semantic_kernel import Kernel

kernel = Kernel()
kernel.add_service(OpenAIChatCompletion(
    ai_model_id="my-deployment",
    api_key="my-api-key",
    base_url="https://my-custom-deployment.net", # Used to point to your service
))`

**Platform**
 - OS: Linux
 - IDE: Visual Studio
 - Language:  Python 3.12.4
 - Source: semantic-kernel 1.8.2

**Comment by markwallace-microsoft** [comment]
@Cheung-Z Thanks for reporting this issue. The Java version has been moved to it's own repository, can you create the issue here: https://github.com/microsoft/semantic-kernel-java/issues

**Comment by Cheung-Z** [comment]
In fact, i don't know why the github-actions bot changed the title to Java, this is a python problem actually.
I doubt the version of semantic-kernel caused this bug.
Looking forward to your reply.
