### ISSUE TITLE
copilot-chat-app can't build

### ISSUE THREAD

**Issue by lone1y-51** [microsoft/semantic-kernel#871]
**Describe the bug**
I refer to https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/README.md this article, want to run copilot-chat-app, but can not successfully build project
```
/path/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/Diagnostics/Verify.cs(20,90): error CS0103: 当前上下文中不存在名称“obj” [/path/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj]
/path/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/Diagnostics/Verify.cs(29,102): error CS0103: 当前上下文中不存在名称“str” [/path/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj]
/path/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/Diagnostics/Verify.cs(65,114): error CS0103: 当前上下文中不存在名称“text” [/path/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj]
```

**To Reproduce**
1. cd `/path/semantic-kernel/samples/apps/copilot-chat-app/webapi`
2. run `dotnet build`

**Expected behavior**
build success

**Desktop (please complete the following information):**
 - OS: mac  13.0 (22A380)  apple m1
 - dotnet sdk: 6.0.408

**Comment by erphao** [comment]
the same error!

**Comment by suxiao0102** [comment]
I also encountered the same problem，when run dotnet build 
https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/README.md

centos 7，dotnet 6.0.408 

commit 7ed26eacaa51182e51ff96ff4e04201c97fe450c

/root/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/Diagnostics/Verify.cs(20,90): error CS0103: The name 'obj' does not exist in the current context [/root/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj]
/root/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/Diagnostics/Verify.cs(29,102): error CS0103: The name 'str' does not exist in the current context [/root/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj]
/root/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/Diagnostics/Verify.cs(65,114): error CS0103: The name 'text' does not exist in the current context [/root/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj]

**Comment by zcsctc** [comment]
the same error!
win11

**Comment by Saber-CC** [comment]
me too!

**Comment by alon-qianyue** [comment]
me too

**Comment by digianycom** [comment]
me too.

**Comment by huangdehong** [comment]
dotnet 7 is ok

**Comment by digianycom** [comment]
> dotnet 7 is ok

Let me try.

**Comment by lazyeo** [comment]
dotnet7 can build but can't run
```
You must install or update .NET to run this application.

App: /home/xxx/semantic-kernel/samples/apps/copilot-chat-app/webapi/bin/Debug/net6.0/CopilotChatApi
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /snap/dotnet-sdk/199

The following frameworks were found:
  7.0.5 at [/snap/dotnet-sdk/199/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=ubuntu.20.04-x64
```

**Comment by wqyliyang** [comment]
> dotnet7 can build but can't run
> 
> ```
> You must install or update .NET to run this application.
> 
> App: /home/xxx/semantic-kernel/samples/apps/copilot-chat-app/webapi/bin/Debug/net6.0/CopilotChatApi
> Architecture: x64
> Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
> .NET location: /snap/dotnet-sdk/199
> 
> The following frameworks were found:
>   7.0.5 at [/snap/dotnet-sdk/199/shared/Microsoft.NETCore.App]
> 
> Learn about framework resolution:
> https://aka.ms/dotnet/app-launch-failed
> 
> To install missing framework, download:
> https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=ubuntu.20.04-x64
> ```

me too. dotnet7 can build but can't run

**Comment by zcsctc** [comment]
> 

After reinstalling[ .net 7.0](https://dotnet.microsoft.com/zh-cn/download/dotnet/7.0), running`dotnet build` and `dotnet run` succeeds.
Make sure that your verion is right
`dotnet --version`
![image](https://user-images.githubusercontent.com/56668272/237055314-2ebeb5b0-e9ff-4dfa-8e90-225ba00de3f1.png)

**Comment by lazyeo** [comment]
> > 
> 
> After reinstalling[ .net 7.0](https://dotnet.microsoft.com/zh-cn/download/dotnet/7.0), running`dotnet build` and `dotnet run` succeeds. Make sure that your verion is right `dotnet --version` ![image](https://user-images.githubusercontent.com/56668272/237055314-2ebeb5b0-e9ff-4dfa-8e90-225ba00de3f1.png)

![image](https://user-images.githubusercontent.com/3772226/237056933-c5b1d515-7d2b-47a0-a259-2d46fd3d5642.png)
Actually I've reinstalled several times , still the same
Ubuntu 20.04

**Comment by qiluo** [comment]
I've successfully build with dotnet 7, but failed to run the web app

` Content root path: /Users/qiluo/Dev/semantic-kernel/samples/apps/copilot-chat-app/webapi/
info: SemanticKernel.Service.Program[0]
      Health probe: https://localhost:40443/probe
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:40443/ - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:40443/ - - - 404 0 - 31.6169ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]`

**Comment by evchaki** [comment]
@lone1y-51 , thanks for bringing this up.  We are looking into it.

**Comment by adrianwyatt** [comment]
Fix: https://github.com/microsoft/semantic-kernel/pull/901
