### ISSUE TITLE
Bug: The latest version of the C # SDK cannot use CancellationToken properly

### ISSUE THREAD

**Issue by 2023pfm** [microsoft/semantic-kernel#8718]
Here is our calling code:
![image](https://github.com/user-attachments/assets/3bd89e67-fb88-4a05-9521-0a3ef9aabfed)
![image](https://github.com/user-attachments/assets/d872c076-6e08-47a0-a240-8e5d42a6b381)

**Comment by RogerBarreto** [comment]
This seems to be a bug related to `OpenAI SDK`, I have opened an issue to keep track of it.

- https://github.com/openai/openai-dotnet/issues/213

**Comment by 2023pfm** [comment]
How to cancel a task based on the Azure OpenAIC hatCompletionService library.
As shown in the code below, I triggered the cancel operation, and the prompt also said that the task has been canceled, but the text is still continuously outputting. How can I solve this problem? Thank you.
![image](https://github.com/user-attachments/assets/eebdf1a1-4638-4153-ab36-3bc5b54fa05d)
![image](https://github.com/user-attachments/assets/510199bd-0987-4bf6-b6df-1ae2a354f2d1)
![image](https://github.com/user-attachments/assets/b0613436-0b6e-48ce-8a9d-9659fc23aa57)
