### ISSUE TITLE
logprobs, best_of and echo parameters are not available on gpt-35-turbo model

### ISSUE THREAD

**Issue by loshammo** [microsoft/semantic-kernel#875]
![图片](https://user-images.githubusercontent.com/20267952/237057575-d880e9b5-1198-4d02-89f0-fad42d6ee721.png)

logprobs, best_of and echo parameters are not available on gpt-35-turbo models
How to solve this problem?
I am using azure openai

**Comment by feiyun0112** [comment]
you use wrong service, please see

#650

**Comment by loshammo** [comment]
> you use wrong service, please see
> 
> #650

大神，怎么切换到ChatCompletionService ？ 
![图片](https://github.com/microsoft/semantic-kernel/assets/20267952/421dfc4c-c0f4-412a-971f-99544ff6eea8)

我是执行这个例子时报的错

**Comment by evchaki** [comment]
@loshammo , good call out here.  The Simple chat summary, book creator, auth and api and GitHub repo Q&A does require the use of a text completion model.  You will need to use something like d-003 for the model.

**Comment by loshammo** [comment]
> @loshammo , good call out here. The Simple chat summary, book creator, auth and api and GitHub repo Q&A does require the use of a text completion model. You will need to use something like d-003 for the model.

Well, I tried the text avinci-003 model and it works.

Does this repo not consider compatibility with the gpt-35 turbo model? Gpt-35 turbo has sufficient capabilities in most scenarios and is relatively inexpensive

**Comment by feiyun0112** [comment]
> > ，好在这里呼唤。简单聊天摘要、书籍创建者、身份验证和 API 以及 GitHub 存储库问答确实需要使用文本完成模型。您需要为模型使用 d-003 之类的东西。
> 
> 好吧，我尝试了文本 avinci-003 模型，它可以工作。
> 
> 这个回购不考虑与 gpt-35 涡轮增压模型的兼容性吗？GPT-35涡轮增压器在大多数情况下具有足够的能力，并且相对便宜

you can use this sample [Copilot Chat Sample Application](https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/README.md)

**Comment by JadynWong** [comment]
> > 您使用了错误的服务，请参阅。
> > #650
> 
> 大神，怎么切换到ChatCompletionService ？ ![图片](https://user-images.githubusercontent.com/20267952/237146851-421dfc4c-c0f4-412a-971f-99544ff6eea8.png)
> 
> 我是执行这个例子时报的错

See

https://github.com/microsoft/semantic-kernel/blob/6afcbe25b9aa63d9952f63936962784ee4434510/samples/dotnet/kernel-syntax-examples/Example27_SemanticFunctionsUsingChatGPT.cs#L19-L28

**Comment by loshammo** [comment]
> 

Thank you very much. I understand the problem now
