### ISSUE TITLE
.Net: Bug: Time to wait on 429 only in text

### ISSUE THREAD

**Issue by BartNetJS** [microsoft/semantic-kernel#8821]
I'm encountering an issue when attempting to use the WaitAndRetryAsync method with a Policy<FunctionResult> on a 429 in my C# project. 
I try to grab the time i have to wait as noted in the error message:
--
Requests to the ChatCompletions_Create Operation under Azure OpenAI API version 2024-07-01-preview have exceeded token rate limit of your current OpenAI S0 pricing tier. Please retry after 51 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.
--

Can the time to wait be added as a property HttpOperationException (in Data?) or in the inner exception System.ClientModel.ClientResultException?

The calling function is: await kernel.InvokeAsync(promptFunc, kernelArgs);

**Expected behavior**
To add the time to wait to a property or in the data list

**Screenshots**
![image](https://github.com/user-attachments/assets/0bade4fc-93e8-444c-8cee-fdc68db0ea16)

**Platform**
 - Source: Microsoft.SemanticKernel version 1.19.0

**Comment by markwallace-microsoft** [comment]
I think the data is available in the response headers, will investigate to confirm.

**Comment by BartNetJS** [comment]
I think also, but it is throwing an exception, and i don't see how i then can pickup the header

**Comment by markwallace-microsoft** [comment]
@BartNetJS You should eb able to do something like this:

1. `HttpOperationException.InnerException` which should be a `ClientResultException`
2. `ClientResultException.GetRawResponse()` will be a `PipelineResponse?`
3. `PipelineResponse.Headers` will be `PipelineResponseHeaders`

See also: https://learn.microsoft.com/en-us/dotnet/api/system.clientmodel.primitives.pipelineresponse.headers?view=azure-dotnet-preview#system-clientmodel-primitives-pipelineresponse-headers

**Comment by markwallace-microsoft** [comment]
Hi @BartNetJS 
can you using the standard resilience handler. The code below is what we use in our integration tests.

If the `ShouldRetryAfterHeader` property is set to true then the generator will resolve the delay based on the Retry-After header rules, otherwise it will return null and the retry strategy delay will generate the delay based on the configured options.

```csharp
var builder = Kernel.CreateBuilder();
builder.Services.ConfigureHttpClientDefaults(c =>
{
    c.AddStandardResilienceHandler().Configure(o =>
    {
        o.Retry.ShouldRetryAfterHeader = true;
        o.Retry.ShouldHandle = args => ValueTask.FromResult(args.Outcome.Result?.StatusCode is HttpStatusCode.TooManyRequests);
    });
});
```

**Comment by BartNetJS** [comment]
Hi @markwallace-microsoft ,

Great, makes it a lot simpler.

I now hit the default timeouts of 30 second.
I tried to increase it here, but still got a timeout after 30 seconds:
```
    builder.Services.ConfigureHttpClientDefaults(c =>
    {
        ....
        c.ConfigureHttpClient((sp, client) =>
        {
            client.Timeout = TimeSpan.FromSeconds(120);
        });
    });
```

Any idea how to implement it?
