### ISSUE TITLE
.Net: Add Support for File types in Open API Connector

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#8850]
### Discussed in https://github.com/microsoft/semantic-kernel/discussions/8834

<div type='discussions-op-text'>

<sup>Originally posted by **neel015** September 17, 2024</sup>
Hello SK team!

We have been using the package `Microsoft.SemanticKernel.Plugins.OpenApi` , it works well with API requests accepting JSON.
However, we have an API which accepts file, for that it is not working. 
While taking a look at the [repo](https://github.com/microsoft/semantic-kernel/blob/9529652d5d36903170660f02228744220e72f466/dotnet/src/Functions/Functions.OpenApi/OpenApi/OpenApiDocumentParser.cs#L68)  we can see that only `application/json` and `text/plain` are supported.

It would be nice to support file types in API requests.

</div>

**Comment by Arup-Chauhan** [comment]
Hi @markwallace-microsoft @evchaki , if no one is working on this issue, I would like to collaborate with my peer @rahulmansharamani14 to give this a shot.

I assume co-authored PRs should be fine. We have our grad sem underway so sharing work would be nice!?

Looking forward to hear back :D

**Comment by SergeyMenshykh** [comment]
Hi @neel015, regarding the discussion you started some time ago at https://github.com/microsoft/semantic-kernel/discussions/8834, could you please share more details about the scenario in which you need to send a file using SK OpenAPI functionality, if it's still relevant?

@Arup-Chauhan, could you provide details about your scenario as well?

**Comment by SergeyMenshykh** [comment]
Closing for now. @neel015, @Arup-Chauhan feel free to reopen the issue if you want us to look into it.

**Comment by Arup-Chauhan** [comment]
@SergeyMenshykh , sure, I am a little caught up in wrapping up my semester, will open and work on this over winter break, hope that's okay :)
