### ISSUE TITLE
.Net: Ollama StreamingChatMessageContent is missing FinishReason in the last message

### ISSUE THREAD

**Issue by akordowski** [microsoft/semantic-kernel#8888]
While working with the **Ollama** connector I discovered that the last `StreamingChatMessageContent` from the [`GetStreamingChatMessageContentsAsync()`](https://github.com/microsoft/semantic-kernel/blob/38902ea2df4984324e9652003f49225b47aa1d88/dotnet/src/Connectors/Connectors.Ollama/Services/OllamaChatCompletionService.cs#L116) method in the `OllamaChatCompletionService` don't contain `FinishReason = "STOP"` in the metadata as the other connectors provide.

**Comment by akordowski** [comment]
I provided a PR #8889 for this issue. Thank you for consideration.

**Comment by RogerBarreto** [comment]
@akordowski This change is not necessary as `Ollama` does not have `FinishReason` on its naming convention and currently you can get this information using the `InnerContent`.

The field you are looking for is `DoneReason`, and the `InnerContent` type may differ if you are using a `Streaming` or `Non-Streaming` API.

I co-authored your PR and altered it to add those examples as part of the Ollama ChatCompletion Concepts.

Ollama Response for `Done_Reason` and `Done` behavior.

![image](https://github.com/user-attachments/assets/110d12aa-4f06-4253-a770-ae971e6aa164)

**Comment by akordowski** [comment]
@RogerBarreto Thank you for the explanation.
