### ISSUE TITLE
.Net Agents - History for Prompt Based Strategies being Encoded

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#8898]
Encoded history results in significantly more token usage and can also obscure debugging or diagnostics.

Embedding JSON within a plain text file shoudn't require encoding.

Investigate how this occurring and simplify.

```
History:
[{&quot;Role&quot;:{&quot;Label&quot;:&quot;assistant&quot;},&quot;Items&quot;:[{&quot;$type&quot;:&quot;TextContent&quot;,&quot;Text&quot;:&quot;Hello! How can I help you today?&quot;}]},{&quot;Role&quot;:{&quot;Label&quot;:&quot;user&quot;},&quot;Items&quot;:[{&quot;$type&quot;:&quot;TextContent&quot;,&quot;Text&quot;:&quot;I want to upload a file&quot;}]}]
```

**Comment by dotnetprofessional** [comment]
I'm running into this issue. Its a waste of tokens and at present we can't control the history making it worse. So this needs addressing.
