### ISSUE TITLE
.Net Agents - No ability to maniplate history for KernelFunction based strategies

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#8914]
Customer Reported:

Always including the entire history can waste tokens, and unnecessarily increase operational cost.

In addition, the history may eventually exceed the token limit.

**Comment by dotnetprofessional** [comment]
This is a pain point for me right now. Need to control what history is part of the executed prompt to reduce ambiguity (ie LLM has too much context, so will get confused), save tokens. Looking forward to this being resolved.
