### ISSUE TITLE
.Net: Memory builder extension function `WithAzureOpenAITextEmbeddingGeneration` missing

### ISSUE THREAD

**Issue by sukesh-ak** [microsoft/semantic-kernel#8926]
I found that this function `WithOpenAITextEmbeddingGeneration` is available in `OpenAI` but not in `AzureOpenAI`.

Did the API's change?

https://github.com/microsoft/semantic-kernel/blob/be90d239117dd9d035f9c8c897b2cce6069ecb4c/dotnet/src/Connectors/Connectors.OpenAI/Extensions/OpenAIMemoryBuilderExtensions.cs#L27

**Comment by markwallace-microsoft** [comment]
@sukesh-ak We are in the process of changing our abstractions for dealing with Vector databases and also search. The new abstractions are documented here: https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/?pivots=programming-language-csharp. Our goal is to have these complete by Ignite and non experimental soon after that.

You could create the `WithAzureOpenAITextEmbeddingGeneration` extension method yourself if you want to stick with the old memory abstractions but our recommendation will be to move to the new ones.

**Comment by sukesh-ak** [comment]
@markwallace-microsoft Thank you.
My apologies. Missed out responding. Will check the new way of doing things. Hope the API's will be completed soon.
