### ISSUE TITLE
.Net: Bug: Regression for ChatCompletion with OpenAPI plugin

### ISSUE THREAD

**Issue by MaxiPigna** [microsoft/semantic-kernel#8983]
**Describe the bug**
I implemented a ChatCompletion Kernel with some OpenAPI plugins. Solution is working with version 1.16.2 of Semantic Kernel but stopped working after upgrading Semantic Kernel to one of the versions 1.18.2, 1.19.0, 1.20.0.

This is the Exception I get
![image](https://github.com/user-attachments/assets/356cc72c-4ad5-43b5-9672-d6c79f61de5b)

with the detailed stack trace
![image](https://github.com/user-attachments/assets/e39519ca-03f3-4679-868e-ea85627db8dc)

It seems this should be the line throwing the exception
![image](https://github.com/user-attachments/assets/90e1373f-feb0-4630-93a3-780f659b3a6f)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: Semantic Kernel 1.18.2, 1.19.0, 1.20.0 

**Additional context**
Swagger has been shared privately.

@markwallace-microsoft @SergeyMenshykh

**Comment by SergeyMenshykh** [comment]
Fixed - https://github.com/microsoft/semantic-kernel/pull/8988
