### ISSUE TITLE
Python: Token usage from Azure OpenAI streaming chat completion

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/semantic-kernel#8996]
Currently, OpenAI provides the functionality to return token usage through their Streaming Chat Completion API. However, this feature has not yet been incorporated into Azure OpenAI. Upon experimenting with the `stream_options` parameter with the OpenAI Python SDK, I noticed that using this parameter may lead to errors when using the latest Azure OpenAI GA API version: 2024-06-01.

This issue has been created to monitor their progress, enabling us to implement the feature within our Azure OpenAI connector as soon as the Azure team integrates support for this functionality.

**Comment by schneidenbach** [comment]
Curious if there's been any update - and will a separate issue be opened for the .NET library?

**Comment by RogerBarreto** [comment]
@schneidenbach , yes our latest update to use the beta.2 of Azure.AI.OpenAI package resolves their issue.

Our tracking issue was:

- https://github.com/microsoft/semantic-kernel/issues/9420
- https://github.com/Azure/azure-sdk-for-net/issues/44237
