### ISSUE TITLE
Bug: Microsoft.SemanticKernel.KernelException:“Required service of type Microsoft.SemanticKernel.TextGeneration.ITextGenerationService not registered.”

### ISSUE THREAD

**Issue by anan1213095357** [microsoft/semantic-kernel#8999]
**Describe the bug**
Microsoft.SemanticKernel.KernelException:“Required service of type Microsoft.SemanticKernel.TextGeneration.ITextGenerationService not registered.”
**To Reproduce**

**Expected behavior**
Example of AIModelRouter in Warehouse

**Screenshots**
![image](https://github.com/user-attachments/assets/74725d9d-5f35-4ec5-8a07-a9892d9abdc2)

**Platform**
win11

**Additional context**
`        ```
services.AddKernel().AddOllamaChatCompletion(
            serviceId: "ollama",
            modelId: "qwen2.5:3b",
            endpoint: new Uri("http://localhost:11434"));
````

**Comment by RogerBarreto** [comment]
When using `ServiceId` registering services they need to be got from a `ServiceProvider` using the `serviceProvider.GetKeyedService` or thru `GetRequiredService` from `kernel`.

```csharp
serviceProvider.GetKeyedService<IChatCompletionService>("ollama")
```

One thing that doesn't add up on your exception is the `ITextGeneration` in the error message.

When you add `ChatCompletion` get services should match `IChatCompletionService` if you are adding a ChatCompletion service.

Please provide a replicable code (more details) to replicate the error, we couldn't replicate it.

**Comment by RogerBarreto** [comment]
Considering it done, if that's not the case, please feel free to reopen.
