### ISSUE TITLE
.Net: Streaming content for token usage 

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#9005]
Only needed for OpenAI

ADR [Streaming Contents for Token Usage Information](https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0056-python-streaming-content-for-token-usage.md)

Link to the Python implementation: https://github.com/microsoft/semantic-kernel/pull/8902

**Comment by JadynWong** [comment]
Azure OpenAI already support it.

https://learn.microsoft.com/zh-cn/azure/ai-services/openai/api-version-deprecation#changes-between-2024-09-01-preview-and-2024-08-01-preview

**Comment by RogerBarreto** [comment]
As this task refers to support for OpenAI, its completed.
