### ISSUE TITLE
Copilot Chat 导入文档后，在对话中没有从文档内容检索

### ISSUE THREAD

**Issue by cl13142006** [microsoft/semantic-kernel#902]
1、导入自己的txt文件
2、提问prompt的问题和文档问题一致
3、给出的答案是大模型的 不是embedding导入的文档

使用的是Azure OpenAi 

请问这个是哪出现的问题呢？

**Comment by linjin200** [comment]
是的我也一样怎么处理这个

**Comment by evchaki** [comment]
@cl13142006 can you pull the latest and try again.

**Comment by cl13142006** [comment]
目前可以了，更新了一下代码，可能之前代码有问题

**Comment by cl13142006** [comment]
> 是的我也一样怎么处理这个

更新下代码试试，5.11号更新了新的代码

**Comment by cl13142006** [comment]
> 更新下代号考试，5.11号更新了新的代号

更新下代号考试，5.11号更新了新的代号

> @cl13142006 can you pull the latest and try again.

The code released on May 11th has been updated, but there were issues with the previous code that caused
