### ISSUE TITLE
Python: Bug: AzureChatCompletion is not working 'out-of-the-box' with semantic-kernel 1.10.0

### ISSUE THREAD

**Issue by nmoellerms** [microsoft/semantic-kernel#9029]
**Describe the bug**
After installing semantic-kernel 1.10.0 and importing the AzureChatCompletion does not work out of the box anymore.
With the introduction of the EntraID Authentication it's mandatory to install `azure-identity` to import the Connector.
`azure-identity` is part of the optional dependencies, so it has to be installed separately and is not installed when installing SK.

Not sure if this is intended, but maybe this can break people.

![image](https://github.com/user-attachments/assets/f2241c15-440e-4af3-b99e-05117f88a7d9)

**To Reproduce**
1. `python -m venv .venv` --> Install fresh python version
2. `.venv\Scripts\Activate.ps1` --> Activate Venv
3. `pip install semantic-kernel==1.10.0` --> Install newest SK Release
4. `python` --> Start a python console
5. `from semantic_kernel.connectors.ai.open_ai import AzureChatCompletion` --> Try import AzureChatCompletion

**Expected behavior**
Not sure what is the expected behavior, but i think the AzureChatCompletion should work out of the Box

**Possible Solution**
![image](https://github.com/user-attachments/assets/a3a7aa01-a4f1-4c97-b64f-01d61f97fb2e)

**Comment by moonbox3** [comment]
Fixed #9031
