### ISSUE TITLE
Python: Bug: 05-using-the-planner.ipynb sample has dead links

### ISSUE THREAD

**Issue by beman9** [microsoft/semantic-kernel#9041]
**Describe the bug**
05-using-the-planner sample has a dead [link](https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/planning/plan.py) in the section about the plan object model as well as right after in the sequential planner section.

**To Reproduce**
1. Go to 05-using-the-planner.ipynb
2. Click on the links in the 'The Plan Object Model' and 'Sequential Planner'
3. See error

**Expected behavior**
The links work

**Platform**
 - Language: Python

**Comment by moonbox3** [comment]
@beman9 Thanks for reporting. We are working on deprecating the planners. We will get this cleaned up when that work is handled.
