### ISSUE TITLE
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

### ISSUE THREAD

**Issue by wqyliyang** [microsoft/semantic-kernel#905]
After the deployment is successful, the front-end page fails to display redirection

invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

**Comment by xkbear** [comment]
me too

**Comment by doolachen** [comment]
you can use 'http' instead of 'https' as your redirect_uri

**Comment by atodniAr** [comment]
> you can use 'http' instead of 'https' as your redirect_uri

In my case this fixed the error.

**Comment by joisonwk** [comment]
> > you can use 'http' instead of 'https' as your redirect_uri
> 
> In my case this fixed the error.

Excuse me, which file and line is this modification in? Can you point it out for me? Thank you.

**Comment by xkbear** [comment]
> > 你可以使用 'http' 而不是 'https' 作为你的 redirect_uri
> 
> 在我的例子中，这修复了错误。

appreciate! solved

**Comment by xkbear** [comment]
> > > > 你可以使用 'http' 而不是 'https' 作为你的 redirect_uri
> > > 
> > > 
> > > 在我的例子中，这修复了错误。
> > 
> > 
> > 请问这个修改在哪个文件和行？你能帮我指出来吗？谢谢。
> 
> 在您输入 redirect_uri 的 Microsoft Azure Active Directory (ADD) 应用程序面板中。 <img alt="图像" width="1129" src="https://user-images.githubusercontent.com/53148827/237322521-8e224299-b12c-42a5-8104-ba76ff8e5c0e.png">

great! my chat has run!
