### ISSUE TITLE
Unable to generate bot response. Details: Error: 400: => Runtime error: Function `ChatSkill.ExtractUserMemories` execution failed. Microsoft.SemanticKernel.AI.AIException: Access denied: The request is not authorized, HTTP status: 403

### ISSUE THREAD

**Issue by Julian-Chou** [microsoft/semantic-kernel#906]
**Describe the bug**
When I open the chatbot and type to chat, I get an error message: Unable to generate bot response. Details: Error: 400: => Runtime error: Function `ChatSkill.ExtractUserMemories` execution failed. Microsoft.SemanticKernel.AI.AIException: Access denied: The request is not authorized, HTTP status: 403

I used postman to try is normal

**Screenshots**
my chat bot screen: 
![image](https://github.com/microsoft/semantic-kernel/assets/78351058/b8fa1708-9470-4d81-a863-ac4a1d34a06e)
my console screen:
![image](https://github.com/microsoft/semantic-kernel/assets/78351058/81c51807-d4e7-4835-a61c-fdbfb77fe708)
used the postman to try to call API
![image](https://github.com/microsoft/semantic-kernel/assets/78351058/796c6319-ec1b-44c9-87ff-852e34bd6b0e)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by evchaki** [comment]
@Julian-Chou can you pull the latest and try this again.

**Comment by Julian-Chou** [comment]
@hathind-ms  I use OpenAI as AI completion service, it can ignore Endpoint value. My json file is below, please let me know if I misunderstood you, thanks.
![image](https://github.com/microsoft/semantic-kernel/assets/78351058/1d512bf5-fe99-4850-82cc-4fd4944424ae)

**Comment by TaoChenOSU** [comment]
> @hathind-ms I use OpenAI as AI completion service, it can ignore Endpoint value. My json file is below, please let me know if I misunderstood you, thanks. ![image](https://user-images.githubusercontent.com/78351058/238806183-1d512bf5-fe99-4850-82cc-4fd4944424ae.png)

Hello Julian, you will have to use an embedding model for this. The one you have `gtp-3.5-turbo` is a completion model.
