### ISSUE TITLE
Authentication Problem: Unable to sign in with a Microsoft Account

### ISSUE THREAD

**Issue by jansennrw** [microsoft/semantic-kernel#907]
**Describe the bug/Problem**

I have followed the step as per the [README.MD](https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/README.md) but on the final step, I'm unable to authenticate accordingly. Can please help?

_Additional info:_

- Dotnet 6 and 7 installed
- OS: Windows 10

====================================
**Screenshot**
**1. http://localhost:3000/ preview**
![image](https://github.com/microsoft/semantic-kernel/assets/89891358/9e4d0db6-0fee-4081-b6ac-4f53d4bb629e)

(The Authentication button is not clickable)

**2. Dotnet run as per intended**
![image](https://github.com/microsoft/semantic-kernel/assets/89891358/67a9e4c2-010c-46e1-8139-d3bbd106af0a)

**3. Yarn run as per intended**
![image](https://github.com/microsoft/semantic-kernel/assets/89891358/c04ddc47-91d5-4151-99fd-441ca280b2a4)

**Comment by suxiao0102** [comment]
me too

**Desktop 
OS：Centos 7
commit 6afcbe25b9aa63d9952f63936962784ee4434510
donet 6
yarn --version
1.22.19
node  -v
v16.18.1

![image](https://github.com/microsoft/semantic-kernel/assets/52738468/64cdcdad-a6fb-4bd9-8e89-a6d6a3207d9c)
AuthError.ts:49  Uncaught (in promise) BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: Cannot read properties of undefined (reading 'digest')
    at BrowserAuthError.AuthError [as constructor] (AuthError.ts:49:1)
    at new BrowserAuthError (BrowserAuthError.ts:199:1)
    at BrowserAuthError.createPkceNotGeneratedError (BrowserAuthError.ts:211:1)
    at PkceGenerator.<anonymous> (PkceGenerator.ts:67:1)
    at step (pluginsSlice.ts:61:1)
    at Object.throw (pluginsSlice.ts:61:1)
    at rejected (pluginsSlice.ts:61:1)

**Comment by jansennrw** [comment]
Ah, I just realized that the problem is on .env file...

Need to follow this step carefully:
============================================
Open a terminal and navigate to samples/apps/copilot-chat-app/webapp Copy **env.example** into a new file **.env** and update the REACT_APP_AAD_CLIENT_ID with the AAD application (Client) ID created above. For example:

REACT_APP_BACKEND_URI=https://localhost:40443/
REACT_APP_AAD_CLIENT_ID={Your Application (client) ID}
REACT_APP_AAD_AUTHORITY=https://login.microsoftonline.com/common

**Comment by evchaki** [comment]
I will close this out.
