### ISSUE TITLE
All my services have started normally, but I cannot log in to Microsoft.

### ISSUE THREAD

**Issue by xkbear** [microsoft/semantic-kernel#908]
![image](https://github.com/microsoft/semantic-kernel/assets/128206938/08fa4524-de41-41bb-9f14-69ce6561c400)

I can access the login page normally, but I get an error below after clicking on login.

unauthorized_client: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.

**Comment by spongermba** [comment]
me too

**Comment by 13bbjxwz** [comment]
I am unable to click and I would like to ask how you configured to launch the web application front-end application

**Comment by xkbear** [comment]
> I am unable to click and I would like to ask how you configured to launch the web application front-end application

create a file named .env , with content below:
REACT_APP_BACKEND_URI=https://localhost:40443/
REACT_APP_AAD_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(your Azure client ID)
REACT_APP_AAD_AUTHORITY=https://login.microsoftonline.com/common

**Comment by xkbear** [comment]
I change the "https://localhost:3000" into "http://localhost:300" in Microsoft Azure Application Registration. Solved

![image](https://github.com/microsoft/semantic-kernel/assets/128206938/8d688546-5240-48ea-9e17-1b2b477e781a)

![image](https://github.com/microsoft/semantic-kernel/assets/128206938/90b5e96d-37ed-44b8-9332-9679b18cb756)
