### ISSUE TITLE
Python: Bug: python/samples/getting_started/01-basic-loading-the-kernel.ipynb

### ISSUE THREAD

**Issue by AnandTiwari83** [microsoft/semantic-kernel#9085]
**Describe the bug:**

I am encountering an issue when trying to run my code using the Semantic Kernel plugin. Specifically, when invoking the `Joke` function, the following error is raised:

**File Path**

https://github.com/CloudLabsAI-Azure/semantic-kernel/blob/main/python/samples/getting_started/01-basic-loading-the-kernel.ipynb

**Code:**

```python
from semantic_kernel.functions import KernelArguments

joke_function = plugin["Joke"]

joke = await kernel.invoke(
    joke_function,
    KernelArguments(input="time travel to dinosaur age", style="super silly"),
)
print(joke)
```

**Error:**

```
Something went wrong in function invocation. During function invocation: 'FunPlugin-Joke'. Error description: 'Error occurred while invoking function Joke: ("<class 'semantic_kernel.connectors.ai.open_ai.services.azure_chat_completion.AzureChatCompletion'> service failed to complete the prompt", NotFoundError('No valid deployments to route to. Please check that the endpoint has at least one deployment with positive weight values or use a deployment specific header to route. [https://docs.microsoft.com/en-us/azure/machine-learning/how-to-safely-rollout-managed-endpoints#deploy-a-new-model-but-send-it-no-traffic-yet]\nPlease check this guide to understand why this error code might have been returned \nhttps://docs.microsoft.com/en-us/azure/machine-learning/how-to-troubleshoot-online-endpoints#http-status-codes'))
```

```
KernelInvokeException: Error occurred while invoking function: 'FunPlugin-Joke'
```

**Attempts to Resolve:**

I tried adding extra headers to ensure the request is routed to the correct model deployment, but the issue still persists.

**Additional Code:**

```python
from openai import OpenAI

client = OpenAI(
    base_url="", 
    api_key=""
)

response = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Who is the most renowned French painter? Provide a short answer.",
        }
    ],
    model="meta/llama-3.1-8b-instruct",
    extra_headers={
        "azureml-model-deployment": "llama-3-8b-nim-deployment-aml-2"
    }
)

print(response.choices[0].message.content)
```

**Comment by evchaki** [comment]
@AnandTiwari83 - thanks for reporting this, we will take a look - @moonbox3

**Comment by moonbox3** [comment]
@AnandTiwari83 this looks to be related to a config issue. Are you trying to use the AzureChatCompletion/OpenAIChatCompletion class to point to a local model? Or you're trying to point to a hosted model deployed with AzureML? 

The error seems to provide some useful information:

NotFoundError('No valid deployments to route to. Please check that the endpoint has at least one deployment with positive weight values or use a deployment specific header to route. [https://docs.microsoft.com/en-us/azure/machine-learning/how-to-safely-rollout-managed-endpoints#deploy-a-new-model-but-send-it-no-traffic-yet]\nPlease check this guide to understand why this error code might have been returned \nhttps://docs.microsoft.com/en-us/azure/machine-learning/how-to-troubleshoot-online-endpoints#http-status-codes')

If you're trying to target an online deployment via Azure, you'll need to make sure you either pass in the `endpoint` param, or have your .env file contain AZURE_OPENAI_ENDPOINT along with the AZURE_OPENAI_API_KEY, and/or deployment name.

Please do provide more context on your desired model config/deployment so we can best help. Thanks.

**Comment by moonbox3** [comment]
We haven't heard back from you in some time. Please ping back on this issue if you still need help, thanks.

**Comment by ssuthar-insight** [comment]
If anyone still having same issue, add this in you .env file, if you are using the Azure Open AI

AZURE_OPENAI_API_VERSION="<your open api version>"
