### ISSUE TITLE
.Net: Bug: OpenAI content filters are being bypassed by Semantic Kernel

### ISSUE THREAD

**Issue by drewbrown27** [microsoft/semantic-kernel#9092]
**Describe the bug**
Through SK we are using a GPT4o model hosted in Azure OpenAI. We created a content filter and applied it to the model. When using the chat playground in the Open AI studio it will flag malicious/negative rhetoric correctly. However in our application which uses the SK SDK (.NET to call the model for chat completion

**To Reproduce**
1. Apply content filter (with low threshold so it should flag everything) to a model in Azure OpenAI studio
2. Call that model through SK SDK using language that should be flagged

**Expected behavior**
I would expect the call to raise an exception like the code said

**Comment by evchaki** [comment]
@drewbrown27 - thanks for reporting this, we will take a look and try to repro this.

**Comment by RogerBarreto** [comment]
Not necessarily it should flag everything, ensure when you are testing:

1. The content doesn't fall into safe scenarios like described in [here](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/content-filter?tabs=definitions%2Cuser-prompt%2Cpython-new#risk-categories)
2. The model you are targeting with deploymentName is the same you applied the filters.

I configured our internal model to flag `ContentFiltering` with everything in low and was provided with the expected result using Semantic Kernel.

![Image](https://github.com/user-attachments/assets/77b5b4c9-b019-4386-94d9-b68e8787d0db)
