### ISSUE TITLE
do not have corresponding PackageVersion

### ISSUE THREAD

**Issue by coopliu** [microsoft/semantic-kernel#913]
When I run dotnet build under the samples/apps/copilot-chat-app/webapi directory, it prompts:
/root/semantic-kernel/dotnet/src/Skills/Skills.Web/Skills.Web.csproj : error NU1010: The PackageReference items Google.Apis.CustomSearchAPI.v1 do not have corresponding PackageVersion. [/root/semantic-kernel/ dotnet/SK-dotnet.sln]

console output：

Failed to restore /root/semantic-kernel/dotnet/src/Skills/Skills.Web/Skills.Web.csproj (in 8 ms).
  The project /root/semantic-kernel/dotnet/src/Skills/Skills.UnitTests/Skills.UnitTests.csproj is using CentralPackageVersionManagement, a NuGet preview feature.
  Restored /root/semantic-kernel/dotnet/src/Skills/Skills.UnitTests/Skills.UnitTests.csproj (in 84 ms).
  The project /root/semantic-kernel/dotnet/src/Skills/Skills.OpenAPI/Skills.OpenAPI.csproj is using CentralPackageVersionManagement, a NuGet preview feature.
  Restored /root/semantic-kernel/dotnet/src/Skills/Skills.OpenAPI/Skills.OpenAPI.csproj (in 16 ms).
  The project /root/semantic-kernel/dotnet/src/Skills/Skills.MsGraph/Skills.MsGraph.csproj is using CentralPackageVersionManagement, a NuGet preview feature.
  Restored /root/semantic-kernel/dotnet/src/Skills/Skills.MsGraph/Skills.MsGraph.csproj (in 93 ms).
  The project /root/semantic-kernel/dotnet/src/Skills/Skills.Grpc/Skills.Grpc.csproj is using CentralPackageVersionManagement, a NuGet preview feature.
  Restored /root/semantic-kernel/dotnet/src/Skills/Skills.Grpc/Skills.Grpc.csproj (in 438 ms).
  The project /root/semantic-kernel/dotnet/src/Skills/Skills.Document/Skills.Document.csproj is using CentralPackageVersionManagement, a NuGet preview feature.
  Restored /root/semantic-kernel/dotnet/src/Skills/Skills.Document/Skills.Document.csproj (in 7 ms).
  Restored /root/semantic-kernel/samples/dotnet/KernelHttpServer/KernelHttpServer.csproj (in 6.64 sec).

Build FAILED.

/root/semantic-kernel/dotnet/src/Skills/Skills.Web/Skills.Web.csproj : error NU1010: The PackageReference items Google.Apis.CustomSearchAPI.v1 do not have corresponding PackageVersion. [/root/semantic-kernel/dotnet/SK-dotnet.sln]

**Comment by benjamin-code** [comment]
Same error when build

**Comment by coopliu** [comment]
dotnet7 is ok, but How to modify localhost to 0.0.0.0, I am deploying on the public network

**Comment by evchaki** [comment]
@coopliu , thanks for bringing this up.  We are fixing this now. @shawncal
