### ISSUE TITLE
.Net: [QUERY] How to retrive data from Semantic Kernel vector store?

### ISSUE THREAD

**Issue by jsquire** [microsoft/semantic-kernel#9141]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#46443](https://github.com/Azure/azure-sdk-for-net/issues/46443).

### Library name and version

Microsoft.SemanticKernel.Core

### Query/Question

I am able to ingest the data in the semantic kernel vector store.
But I am exactly not sure how to retrive it. I am builing a web application using .net 8. I am injecting kernel in dependency injection.
Referring to this document
https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/out-of-the-box-connectors/volatile-connector?pivots=programming-language-csharp

**Comment by westey-m** [comment]
Hi @dotcom-gosahi, thanks for the question.

I assume you mean how do you do vector searches?  I realize that is still a big gap, but we are still working on it, and we are aiming to release that functionality next week with documentation, so keep an eye out for our release next week.

If you are interested in seeing what we have been doing, you can check out our feature branch here:
https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors

And here is a link to one of the samples:
https://github.com/microsoft/semantic-kernel/blob/feature-vector-search/dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiStore_Common.cs

**Comment by dotcom-gosahi** [comment]
Thanks @westey-m. Yes, I was looking for this only, how to perform vectorized search on these stores.
This is that piece of code.
![image](https://github.com/user-attachments/assets/d7052331-b15a-4e3d-9553-b082b5b0fb25)

Right now I am getting error in this line
var searchResult = await collection.VectorizedSearchAsync(searchVector, new() { Top = 1 });
![image](https://github.com/user-attachments/assets/8fdd67b6-51ef-4d91-9637-2b366c3be4d9)

Just to be sure, after release next week, this gap will be addressed?

**Comment by westey-m** [comment]
@dotcom-gosahi, yes, this gap will be closed with next week's release.  You are getting the because we haven't released this code to the public nuget yet.

**Comment by dotcom-gosahi** [comment]
Thanks @westey-m

**Comment by westey-m** [comment]
@dotcom-gosahi,
This code has now been released, and you should be able to use it by importing the latest version of any of the memory connector packages
See https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/out-of-the-box-connectors/

Also check out this page for more information on how to do vector search:
https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/vector-search?pivots=programming-language-csharp
