### ISSUE TITLE
Semantic kernel Tools with chat completion model

### ISSUE THREAD

**Issue by JadynWong** [microsoft/semantic-kernel#916]
I can use gpt-35-turbo with `AddAzureChatCompletionService`, but when I use the VS Code extension `Semantic Kernel Tools`, it does not work with gpt-35-turbo.

I also can't find the source code for this extension. When will it support chat completion model, like gpt-35-turbo, gpt4?

**Comment by evchaki** [comment]
@JadynWong , this will be coming soon.  I will close out this issue and leave your other open on the same topic.
