### ISSUE TITLE
Python: Intermittent issue with AzureChatCompletion

### ISSUE THREAD

**Issue by kozhikkota** [microsoft/semantic-kernel#9171]
While using the Semantic Kernel Python version 1.5.0, we are receiving an intermittent error like below 

` ERROR:semantic_kernel.kernel:Something went wrong in function invocation. During function invocation: '<FunctionName>'. Error description: 'Error occurred while invoking function <Function_Name>: ("<class 'semantic_kernel.connectors.ai.open_ai.services.azure_chat_completion.AzureChatCompletion'> service failed to complete the prompt", AttributeError("'str' object has no attribute 'usage'"))'`

I have checked the response object and ensured that there is the usage element present. 

Have anyone noticed this, also please note this is an intermittent issue, there are lot of requests which have successfully processed, but in between you receive these sort of an error.

**Comment by moonbox3** [comment]
Hello, @kozhikkota. The latest SK Python version is 1.11.0. There have been some improvements, IIRC, on handling this attribute. Haven't seen any error like that for a while. Can you please try to upgrade and let us know?

**Comment by moonbox3** [comment]
Please upgrade to the latest version. If you continue to experience an issue you can re-open this. Thanks.
