### ISSUE TITLE
.Net: Bug: Azure AI Inference connector "index out of range" error when running chat completion (only .NET Standard 2.0)

### ISSUE THREAD

**Issue by Kialarr** [microsoft/semantic-kernel#9190]
**Describe the bug**
When trying to run chat completion (GetChatMessageContentAsync) with Azure AI Inference connector, a 400 Bad Request error is always returned, but only when getting Semantic Kernel package for .NET Standard. Works fine on .NET 8, in the Semantic Kernel samples repository and when trying to run the request in Postman.

**To Reproduce**
1. Create a clean console project with target framework v.4.7.1
2. Get Microsoft.SemanticKernel and Microsoft.SemanticKernel.Connectors.AzureAIInference from NuGet
3. Write code to run simple chat completions (can be the same as in samples)

```
         var chatService = new AzureAIInferenceChatCompletionService(
                    endpoint: new Uri(TestConfiguration.AzureAIInference.Endpoint),
                    apiKey: TestConfiguration.AzureAIInference.ApiKey);

        Console.WriteLine("Chat content:");
        Console.WriteLine("------------------------");

        var chatHistory = new ChatHistory("You are a librarian, expert about books");

        // First user message
        chatHistory.AddUserMessage("Hi, I'm looking for book suggestions");

        // First assistant message
        var reply = await chatService.GetChatMessageContentAsync(chatHistory);
```

5. Run the application

Result message:

```
Microsoft.SemanticKernel.HttpOperationException: {"object":"error","message":"list index out of range","type":"BadRequestError","param":null,"code":400}
Status: 400 (Bad Request)
ErrorCode: Bad Request

Content:
{"error":{"code":"Bad Request","message":"{\"object\":\"error\",\"message\":\"list index out of range\",\"type\":\"BadRequestError\",\"param\":null,\"code\":400}","status":400}}
```

**Expected behavior**
Proper response should be returned. 

**Environment**
 Semantic Kernel Azure AI Inference v. 1.22.0-beta, when using .NET Standard 2.0 library
The called model was Phi-3-small-8k-instruct

**Additional context**
I found out this issue when trying to run the completion from a Unity application, then narrowed it down by creating 2 clear console projects - one using .net 8 and other .net 4.7.1. I run the request to the same endpoint, same code. The "index out of range" error appears only in the latter.

**Comment by RogerBarreto** [comment]
Using the latest packages and the provided `reproduction code above` I was unable to reproduce the error

Tried with both .Net Framework 4.6.2 and 4.7.1 versions.

![Image](https://github.com/user-attachments/assets/8f4c65fa-f14b-496e-bb56-5bbaddc7e96d)

Recommend updating your package to latest version.
