### ISSUE TITLE
Java: allow to inject skill store

### ISSUE THREAD

**Issue by Bryan-Roe** [microsoft/semantic-kernel#9211]
https://github.com/Bryan-Roe/semantic-kernel/blob/3a7c96cd6021c6ad7ad0adf441ecaed8061d872d/java/extensions/semantickernel-planners/src/main/java/com/microsoft/semantickernel/planner/actionplanner/Untitled-1.md#L3

**Comment by moonbox3** [comment]
Please open your SK Java issue here: https://github.com/microsoft/semantic-kernel-java/issues
