### ISSUE TITLE
Bug: How to integrate Azure OpenAIChatCompletionService into the o1 model

### ISSUE THREAD

**Issue by 2023pfm** [microsoft/semantic-kernel#9244]
How to integrate Azure OpenAIChatCompletionService into the o1 model? The code I wrote is as follows. Currently, Azure OpenAiPomptExecutionSettings do not have the MaxOutputTokenCount parameter, which causes an error when I call it. I should modify it as follows. Thank you.
![Image](https://github.com/user-attachments/assets/6f938834-3a8b-4d5b-90e2-6c400a102ae7)

**Comment by RogerBarreto** [comment]
@2023pfm This problem should not be happening for the latest SK versions 1.22+.

The OpenAI SDK 2.1-beta already use the new max token property.

Please confirm which SK version are you experiencing this.

**Comment by RogerBarreto** [comment]
Since I had no more updates on this issue I assume the provided details resolved it on your side. THanks!
