### ISSUE TITLE
.Net: Where is IVectorSearch?

### ISSUE THREAD

**Issue by lilhoser** [microsoft/semantic-kernel#9280]
[This page](https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/vector-search?pivots=programming-language-csharp) states:

```
The VectorizedSearchAsync method allows searching using data that has already been vectorized.

This method takes a vector and an optional VectorSearchOptions class as input. This method is available on the following interfaces:

IVectorizedSearch<TRecord>
IVectorStoreRecordCollection<TKey, TRecord>
Note that IVectorStoreRecordCollection<TKey, TRecord> inherits from IVectorizedSearch<TRecord>.
```

And [this unit test](https://github.com/microsoft/semantic-kernel/blob/e23d6364578dcd40ce380b57e176a48d3c7c3e61/dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantKernelBuilderExtensionsTests.cs#L109) confirms that by grabbing `IVectorSearch` off the collection interface:

```
var collection = kernel.Services.GetRequiredService<IVectorStoreRecordCollection<ulong, TestRecord>>();
Assert.NotNull(collection);
Assert.IsType<QdrantVectorStoreRecordCollection<TestRecord>>(collection);
var vectorizedSearch = kernel.Services.GetRequiredService<IVectorizedSearch<TestRecord>>();
```

However, I'm using `Microsoft.SemanticKernel.Connectors.Qdrant` version `1.22.0-alpha` and the reference is not resolved:

![Image](https://github.com/user-attachments/assets/31b98746-ff1f-4ba4-be16-368f3b117aac)

And the source does not show `IVectorStoreRecordCollection` inheriting from `IVectorizedSearch`:

```
[Experimental("SKEXP0001")]
#pragma warning disable CA1711 // Identifiers should not have incorrect suffix
public interface IVectorStoreRecordCollection<TKey, TRecord>
#pragma warning restore CA1711 // Identifiers should not have incorrect suffix
    where TKey : notnull
    where TRecord : class
{
```

**Comment by lilhoser** [comment]
Dupe of https://github.com/microsoft/semantic-kernel/issues/9141

Not sure why docs are released before the code is ready.

**Comment by westey-m** [comment]
@lilhoser, the packages are now published and contains the new vector search capabilities. Apologies again for the delay and confusion.
Check out version 1.24.1 of any of the out of the box connectors, e.g.

https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.InMemory/1.24.1-preview
https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.AzureAISearch/1.24.1-preview
https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.Redis/1.24.1-preview
etc.

Also, see here for a full list:
https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/out-of-the-box-connectors/

Note that the Pinecone connector is the only one that doesn't have VectorSearch implemented yet, as documented in limitations [here](https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/out-of-the-box-connectors/pinecone-connector?pivots=programming-language-csharp#limitations), but this will follow soon.
