### ISSUE TITLE
.Net: New Feature:

### ISSUE THREAD

**Issue by nhandangms** [microsoft/semantic-kernel#9320]
---
Structured output as JSON for Azure OpenAI

---

Hi teams, we are interested in whether you support for structured output for .NET using Azure OpenAI at this time. We would like to get more information and resources to utilize this feature.

**Comment by evchaki** [comment]
@nhandangms  here is a blog post on the topic also - https://devblogs.microsoft.com/semantic-kernel/using-json-schema-for-structured-output-in-net-for-openai-models/
