### ISSUE TITLE
.Net: Bug: Could not load file or assembly Microsoft.Extensions.VectorData.Abstractions Exception raised.

### ISSUE THREAD

**Issue by aeras3637** [microsoft/semantic-kernel#9321]
**Describe the bug**
Bing_FunctionCallingWithTextSearch.FunctionCallingWithBingTextSearchIncludingCitationsAsync in a local environment, an exception occurs.

Could not load file or assembly 'Microsoft.Extensions.VectorData.Abstractions, Version=1.24.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3'. 指定されたファイルが見つかりません。
   場所 Microsoft.SemanticKernel.Plugins.Web.Bing.BingTextSearch.BuildQuery(String query, TextSearchOptions searchOptions)
   場所 Microsoft.SemanticKernel.Plugins.Web.Bing.BingTextSearch.<SendGetRequestAsync>d__16.MoveNext()
   場所 Microsoft.SemanticKernel.Plugins.Web.Bing.BingTextSearch.<ExecuteSearchAsync>d__15.MoveNext()
   場所 Microsoft.SemanticKernel.Plugins.Web.Bing.BingTextSearch.<GetTextSearchResultsAsync>d__2.MoveNext()
   場所 Microsoft.SemanticKernel.Data.TextSearchExtensions.<>c__DisplayClass4_0.<<CreateGetTextSearchResults>g__GetTextSearchResultAsync|0>d.MoveNext()
   場所 Microsoft.SemanticKernel.KernelFunctionFromMethod.<>c__DisplayClass17_0.<<GetReturnValueMarshalerDelegate>b__11>d.MoveNext()
   場所 System.Threading.Tasks.ValueTask`1.get_Result()
   場所 Microsoft.SemanticKernel.KernelFunction.<>c__DisplayClass21_0.<<InvokeAsync>b__0>d.MoveNext()
   場所 Microsoft.SemanticKernel.Kernel.<InvokeFilterOrFunctionAsync>d__34.MoveNext()
   場所 Microsoft.SemanticKernel.Kernel.<OnFunctionInvocationAsync>d__33.MoveNext()
   場所 Microsoft.SemanticKernel.KernelFunction.<InvokeAsync>d__21.MoveNext()
   場所 Microsoft.SemanticKernel.Connectors.FunctionCalling.FunctionCallsProcessor.<>c__DisplayClass6_1.<<ProcessFunctionCallsAsync>b__1>d.MoveNext()
   場所 Microsoft.SemanticKernel.Connectors.FunctionCalling.FunctionCallsProcessor.<InvokeFilterOrFunctionAsync>d__9.MoveNext()
   場所 AOAI.AutoFunctionExceptionHandlingFilter.<OnAutoFunctionInvocationAsync>d__1.MoveNext() (D:\sandbox\AOAI\Program.cs):行 72

**To Reproduce**
```
    internal class Program
    {
        static async Task Main(string[] args)
        {
            IKernelBuilder builder = Kernel.CreateBuilder()
                .AddAzureOpenAIChatCompletion(
                );
            builder.Services.AddSingleton<IAutoFunctionInvocationFilter, AutoFunctionExceptionHandlingFilter>();
            var kernel = builder.Build();

            // Create a search service with Bing search
            var textSearch = new BingTextSearch(new("key"));
            // Build a text search plugin with Bing search and add to the kernel
            var searchPlugin = textSearch.CreateWithGetTextSearchResults("SearchPlugin");
            kernel.Plugins.Add(searchPlugin);

            // Invoke prompt and use text search plugin to provide grounding information
            OpenAIPromptExecutionSettings settings = new() { ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions };
            KernelArguments arguments = new(settings);
            Console.WriteLine(await kernel.InvokePromptAsync("What is the Semantic Kernel? Include citations to the relevant information where it is referenced in the response.", arguments));
        }
    }
    internal sealed class AutoFunctionExceptionHandlingFilter() : IAutoFunctionInvocationFilter
    {
        public async Task OnAutoFunctionInvocationAsync(AutoFunctionInvocationContext context, Func<AutoFunctionInvocationContext, Task> next)
        {
            try
            {
                await next(context);
            }
            catch (Exception exception)
            {
                Console.Write(exception.Message);
                throw;
            }
        }
    }
```

**Expected behavior**

**Screenshots**

**Platform**
 - OS:Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: NuGet package version 1.24.0
 - 
**Additional context**
Adding Microsoft.Extensions.VectorData.Abstractions -Version 9.0.0-preview.1.24515.1 still causes an exception.

**Comment by dflyingliu** [comment]
Any updates on this, get the same issue now :(

**Comment by dmytrostruk** [comment]
We are working on it and will create another release soon.

**Comment by markwallace-microsoft** [comment]
@dflyingliu @aeras3637 please switch https://www.nuget.org/packages/Microsoft.SemanticKernel/1.24.1
