### ISSUE TITLE
Replace openai's model with local offline llm?

### ISSUE THREAD

**Issue by dulibubai** [microsoft/semantic-kernel#9322]
Hi! How can I replace openai's model with local offline llm? Look forward to your replay!

**Comment by dflyingliu** [comment]
Use an LLM that supports OpenAI-compatible APIs or overload the HttpClient for the AddOpenAIChatCompletion method to automatically handle interface requests for the local LLM

**Comment by evchaki** [comment]
@dulibubai - here a few links to get you started:
- Blog - https://devblogs.microsoft.com/semantic-kernel/?p=3263 
- Blog - https://devblogs.microsoft.com/semantic-kernel/introducing-new-ollama-connector-for-local-models/
- Samples - .NET - https://github.com/microsoft/semantic-kernel/tree/main/dotnet/samples/Concepts/LocalModels
- Samples - Python - https://github.com/microsoft/semantic-kernel/tree/main/python/samples/concepts/local_models
