### ISSUE TITLE
Bug: AzureSearchChatDataSource doesn't include citation

### ISSUE THREAD

**Issue by kondzikwawa** [microsoft/semantic-kernel#9325]
Hi,
I'm trying to set up RAG for getting answers based on my internal documents. Generally it works fine but unfortunately I can not see citations.
I mean I'm getting an answer based on my internal documents but without citations.

var dataSource = GetAzureSearchDataSource(documentsConfigName);

AzureOpenAIPromptExecutionSettings promptExecutionSettings = new()
{
              MaxTokens = Convert.ToInt32(_configuration.GetSection("AzureOpenAi:Regions:SwedenCentral:Deployments:Gpt-4o:Settings:MaxTokens").Value),
              Temperature = double.Parse(_configuration.GetSection("AzureOpenAi:Regions:SwedenCentral:Deployments:Gpt-4o:Settings:Temperature").Value!, CultureInfo.InvariantCulture),
              AzureChatDataSource = dataSource
};

var response = await _chat.GetChatMessageContentAsync(_history, promptExecutionSettings);

-----------------------------------------------------------------------------------------------------------------
  private AzureSearchChatDataSource GetAzureSearchDataSource(string indexConfigurationPath)
  {
      return new AzureSearchChatDataSource
      {
          Endpoint = new Uri(_configuration.GetSection("AzureAiSearch:Endpoint").Value ?? string.Empty),
          Authentication = DataSourceAuthentication.FromApiKey(_configuration.GetSection("AzureAiSearch:ApiKey").Value ?? string.Empty),
          IndexName = _configuration.GetSection($"AzureAiSearch:{indexConfigurationPath}:IndexName").Value ?? string.Empty,
          Strictness = 3,
          TopNDocuments = 5
      };
  }

**Comment by evchaki** [comment]
Here is a link to sample code for Citations - https://github.com/microsoft/semantic-kernel/blob/a3a69c89abfb249bca745965ccef982390ca008a/dotnet/samples/GettingStartedWithTextSearch/Step4_Search_With_VectorStore.cs#L83

**Comment by kondzikwawa** [comment]
Thanks, but actually it's odd. Azure AI Search returns a list of citations. I don't understand why I'm not getting it when I use the following method:

_chat.GetChatMessageContentAsync(_history, promptExecutionSettings);

Especially that in AzureSearchChatDataSource we can specify what shoud be return e.g. 
![Image](https://github.com/user-attachments/assets/7bcf672f-29d4-4b21-a62c-b6ba9583e59b)

**Comment by evchaki** [comment]
@westey-m - can you take a look at this?

**Comment by dmytrostruk** [comment]
@kondzikwawa Meanwhile you should be able to use following snippet as a workaround:

```csharp
var chatService = Kernel.GetRequiredService<IChatCompletionService>();
var chatMessage = await chatService.GetChatMessageContentAsync(chat, executionSettings);

var openAiChatCompletion = content.InnerContent as OpenAI.Chat.ChatCompletion;
var context = openAiChatCompletion.GetMessageContext();
```

**Comment by kondzikwawa** [comment]
@dmytrostruk thank you!
