### ISSUE TITLE
.Net: Bug: Null status/error code from GetChatMessageContentAsync exception

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#9381]
[**Describe the bug**
When ChatCompletion service is down or inaccessible, GetChatMessageContentAsync() exception returns a null status code. It gives out an AggregateException (for the use case I am testing locally with an incorrect URL) and all of the inner exception(s) do not have any error/status codes. The exception message has a status code and trying to get a status code from the message doesn't sound reliable.

Trying to failover to another region when there is an exception and handle use cases based on status codes.

**Expected behavior**
Exception message should clearly indicate there was a connection issue.

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**
https://github.com/microsoft/semantic-kernel/discussions/9349

**Comment by RogerBarreto** [comment]
@Rohit-Juluru can you please provide more context on what was the connector you were attempting to use with the `GetChatMessageContentAsync` ?

**Comment by Rohit-Juluru** [comment]
@RogerBarreto Please find the code I've been using

```c#
var builder = Kernel.CreateBuilder();
var azureOpenAISetting = _connectionSettings;
var azureOpenAIClient = new OpenAIClient(New Uri(azureOpenAISetting.Endpoint), new DefaultAzureCredential(_credentials));
builder = builder.AddAzureOpenAIChatCompletion(azureOpenAISetting.DeploymentId, azureOpenAIClient);

// Added some services to builder

var kernel = builder.Build();

var chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();

// Nothing other than the basic chatHistory and settings
var result = await chatCompletionService.GetChatMessageContentAsync(chatHistory, openAIPromptExecutionSettings, kernel);
``` 

When the service is down, I saw the error in catch block with a 502 status message but the statusCode/errorCode property is null.

Let me know if you need additional info.

Thanks.

> [@Rohit-Juluru](https://github.com/Rohit-Juluru) can you please provide more context on what was the connector you were attempting to use with the `GetChatMessageContentAsync` ?
> 
> If possible can you also provide the a code to reproduce the error, that would be super helpful.

**Comment by RogerBarreto** [comment]
Hi @Rohit-Juluru thanks for providing the context, I tried to replicate the error in a test and could not find the problem you are mentioning, see below (status are filled correctly) both in the exception and `InnerException`:

![Image](https://github.com/user-attachments/assets/b971e202-2c12-4d89-9c48-1b04d6747c73)

Can you confirm if you are using the most recent versions of Semantic Kernel?

**Comment by Rohit-Juluru** [comment]
@RogerBarreto We are using a few versions older SK. There were some breaking changes, so we did not update. Let me resolve them in a few days here and provide an update. Thanks.

**Comment by RogerBarreto** [comment]
@Rohit-Juluru, closing this, if you find the problem in the recent versions feel free to reopen.

Thanks!
