### ISSUE TITLE
HTTP 400 error "Invalid 'response_format.json_schema.name'" when generic type is used for ResponseFormat

### ISSUE THREAD

**Issue by asvishnyakov** [microsoft/semantic-kernel#9416]
**Describe the bug**
OpenAI API fails with error if generic type is used for `ResponseFormat`:

> HTTP 400 (invalid_request_error: invalid_value)
> Parameter: response_format.json_schema.name
> 
> Invalid 'response_format.json_schema.name': string does not match pattern. Expected a string that matches the pattern '^[a-zA-Z0-9_-]+$'.

**To Reproduce**
Use any generic type as ResponseFormat. For example:
```csharp
public class Cart<T>
{
   public decimal Total { get; set; }
   public List<T> LineItems { get; set; }
}

public class LineItem 
{
   public class ProductName { get; set; }
   public int Quantity { get; set; }
}
```

**Expected behavior**
This issue is caused by use of `GetType().Name` at https://github.com/microsoft/semantic-kernel/blob/c304c8beca4770d295135e721f64e99df388024b/dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs#L560
which results into ``Cart`1`` json schema name with `` ` `` symbol, while OpenAI API allows only alphanumberic values and `_` or `-` symbols.

**Platform**
 - Language: C#
 - Source: dotnet-1.25.0

**Comment by evchaki** [comment]
@asvishnyakov - thanks for reporting this.  We have a PR open to fix this you can check out #9490
