### ISSUE TITLE
Unable to log in to Microsoft account

### ISSUE THREAD

**Issue by cooptest** [microsoft/semantic-kernel#944]
I built it on a public network server, dotnet and yarn run successfully, but the front end cannot log in, and the click does not respond
<img width="889" alt="1" src="https://github.com/microsoft/semantic-kernel/assets/133195857/f6f1bc85-caab-4d07-8157-b846d43ba639">

My redirection ip in Azure is public IP: https://x.x.x.x:3000

<img width="644" alt="2" src="https://github.com/microsoft/semantic-kernel/assets/133195857/48e89ba5-826f-408f-bf1d-31260d0ba97a">

Azure does not support https://x.x.x.x:3000

I set it to http://localhost:3000/https://localhost:3000/https:x.x.x.x:3000 and I can’t log in

_Originally posted by @cooptest in https://github.com/microsoft/semantic-kernel/discussions/943_

**Comment by PolarPeak** [comment]
me tooI'm the same, I hope to get an official answer as well.

**Comment by cooptest** [comment]
I copied the .env file, and edited it like this:

REACT_APP_BACKEND_URI=https//0.0.0.0:40443/
REACT_APP_AAD_AUTHORITY=https://login.microsoftonline.com/common
REACT_APP_AAD_CLIENT_ID=7284df12-1d8f-4b7c-xxxx-xxxxxxxxxxx
<img width="365" alt="1" src="https://github.com/microsoft/semantic-kernel/assets/133195857/2e04074e-3517-41dd-b7cf-fe65c007cba2">

<img width="401" alt="2" src="https://github.com/microsoft/semantic-kernel/assets/133195857/4299ba19-1d3a-4cca-a8f8-91a97fee06df">

**Comment by wyz9616** [comment]
我也有同样的疑惑：
1.我的.env与必须带前缀，不然会报错
<img width="142" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/86828004/3e0eb000-c069-4121-9b74-3bcc0d6a37a0">
<img width="241" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/86828004/1daef916-f1a5-4f1b-898f-e67b91f52a9e">
2.我右击登陆会发现是一张图片。。。
<img width="547" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/86828004/878806cb-0294-44b1-a69f-944ca235fa5c">

**Comment by PolarPeak** [comment]
me too

**Comment by suxiao0102** [comment]
Is there a solution?

![image](https://github.com/microsoft/semantic-kernel/assets/52738468/15e83981-c947-476f-a81a-01c584ad9697)

**Comment by suxiao0102** [comment]
Is there a solution for logging in?

![image](https://github.com/microsoft/semantic-kernel/assets/52738468/2b37093a-04f6-4735-a8d6-8daf0d01ea2c)

**Comment by craigomatic** [comment]
May I ask how you have setup the AAD app? The PKCE error makes me wonder if maybe you did not configure as an SPA?

https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration#redirect-uri-msaljs-20-with-auth-code-flow

**Comment by teresaqhoang** [comment]
> 我也有同样的疑惑： 1.我的.env与必须带前缀，不然会报错 <img alt="image" width="142" src="https://user-images.githubusercontent.com/86828004/237854586-3e0eb000-c069-4121-9b74-3bcc0d6a37a0.png"> <img alt="image" width="241" src="https://user-images.githubusercontent.com/86828004/237854641-1daef916-f1a5-4f1b-898f-e67b91f52a9e.png"> 2.我右击登陆会发现是一张图片。。。 <img alt="image" width="547" src="https://user-images.githubusercontent.com/86828004/237854851-878806cb-0294-44b1-a69f-944ca235fa5c.png">

@wyz9616 your file should be named just `.env` not `env.env`

**Comment by teresaqhoang** [comment]
Hi @cooptest, @PolarPeak , @Suevivian, apologies for a delayed reply.

You'll have to enable the webapp to use HTTPS for local development. I've outlined steps on how to do this here: https://github.com/microsoft/semantic-kernel/blob/1f753fb648c29baeeaa79c492c7a1c774bf06082/samples/apps/copilot-chat-app/webapp/README.md#how-to-use-https-for-local-development

Since you're using your own public IP address, I would recommend using `mkcert` to generate the necessary certificates, and then you should be able to add your `https://x.x.x.x:3000` as a single page application (SPA) redirect URL in your AAD app registration.

**Comment by teresaqhoang** [comment]
> Is there a solution for logging in? Now,can only be used on localhost `http://localhost:3000`
> 
> if use `ip:3000`，will not be able to log in normally
> 
> for example： http://20.34.19.11:3000
> 
> error： bundle.js:24299 Uncaught (in promise) BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: Cannot read properties of undefined (reading 'digest')
> 
> ![image](https://user-images.githubusercontent.com/52738468/238267225-2b37093a-04f6-4735-a8d6-8daf0d01ea2c.png)

@Suevivian, AAD has a restriction such that redirect URIs must begin with the scheme https. There are some [exceptions for localhost](https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions) redirect URIs, so if you want to use a specific IP address, you have to use `https` and follow the steps outlined in this [README](https://github.com/microsoft/semantic-kernel/blob/1f753fb648c29baeeaa79c492c7a1c774bf06082/samples/apps/copilot-chat-app/webapp/README.md#how-to-use-https-for-local-development) to configure your local environment accordingly. 

See more about redirect URL restrictions here: https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url
