### ISSUE TITLE
Unable to generate bot response. Details: Error: 400 Something went wrong: New-line characters are not allowed in header values.

### ISSUE THREAD

**Issue by jansennrw** [microsoft/semantic-kernel#950]
Hi All,

I'm having problem where bot unable to generate response properly due.
Error message as per the picture:
_**Something went wrong: New-line characters are not allowed in header values.**_

![image](https://github.com/microsoft/semantic-kernel/assets/89891358/b5344821-c2b9-4e2c-b088-5cd5e055b8e0)

Can please help? 🙏🏻

**Comment by microsoftShannon** [comment]
Hi @jansennrw - we released a set of updates this morning to the repo - can you try this again and tell us if it works now?  thanks!

**Comment by jansennirwana** [comment]
Hi,

Have tried this again but unfortunately the problem still happened...

**Comment by jansennirwana** [comment]
Hi @microsoftShannon is there any update on this issue?

Tried to use the most updated repo and still not working...
![image](https://github.com/microsoft/semantic-kernel/assets/29532728/a628a0cb-9000-4ef2-9263-ffd1ac6e7330)

**Comment by craigomatic** [comment]
The error message may be referring to the model names you have entered. Are you using OpenAI or Azure OpenAI models?

To troubleshoot, please check your appsettings.json and double check that the model names, endpoints, etc are correct and that there are not any new lines anywhere in the values

**Comment by jansennirwana** [comment]
Somehow solved with the latest repo, thanks @craigomatic ...

**Comment by craigomatic** [comment]
Great!
