### ISSUE TITLE
.Net: New Feature: GeminiPromptExecutionSettings is missing optional parameter audioTimestamp

### ISSUE THREAD

**Issue by jamescarter-le** [microsoft/semantic-kernel#9500]
Missing parameter `audio_timestamp` on `GeminiPromptExecutionSettings` is preventing accurate transcription of longer audio files.

```
Suggested Property:

[JsonPropertyName("audioTimestamp")]
public bool? AudioTimestamp { get; set; }
```

Google documentation: 
https://cloud.google.com/vertex-ai/generative-ai/docs/reference/rest/v1/GenerationConfig

**Comment by evchaki** [comment]
@RogerBarreto - can you take a look at this?  @jamescarter-le - thanks for submitting this, we will take a look at updating this.

**Comment by shethaadit** [comment]
Hi @markwallace-microsoft / @RogerBarreto, can we close this since the PR is merged?
