### ISSUE TITLE
How to concatenate StreamChatMessageContent into a complete ChatMessageContent?

### ISSUE THREAD

**Issue by liujiyuan** [microsoft/semantic-kernel#9535]
How to concatenate StreamChatMessageContent into a complete ChatMessageContent so that FunctionCallContent.GetFunctionCalls(chatMessageContent) can retrieve the corresponding functions?

**Comment by moonbox3** [comment]
Hi @liujiyuan, are you working with SK C# or SK Python?

**Comment by liujiyuan** [comment]
Hi @moonbox3, I am working with SK c#. Thanks.

**Comment by SergeyMenshykh** [comment]
Hi @liujiyuan, you need to use the [FunctionCallContentBuilder](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel.Abstractions/Contents/FunctionCallContentBuilder.cs) to construct function call contents out of streamed function call bits, as it's shown in this sample: [RunStreamingChatCompletionApiWithManualFunctionCallingAsync](https://github.com/microsoft/semantic-kernel/blob/238c26d2cd6c532d6c93f24748f361946bb15056/dotnet/samples/Concepts/FunctionCalling/FunctionCalling.cs#L285)

**Comment by liujiyuan** [comment]
There is a bug.
When the code reaches var functionResult = await functionCall.InvokeAsync(kernel);, an error is reported: “The plugin collection does not contain a plugin and/or function with the specified names. Plugin name - ‘’, function name - ‘’.” I initially suspected that FunctionCallContentBuilder is resetting the previously assigned name to empty. The erroneous code is as follows:
`        if (update.Name is string name)
        {
            (functionNamesByIndex ??= [])[update.FunctionCallIndex] = name;
        }`
