### ISSUE TITLE
Bug: The bug where FunctionCallContentBuilder constructs a FunctionName as empty.

### ISSUE THREAD

**Issue by liujiyuan** [microsoft/semantic-kernel#9567]
**Describe the bug**
When the code reaches 
‘var functionResult = await functionCall.InvokeAsync(kernel);’, 

an error is reported: “The plugin collection does not contain a plugin and/or function with the specified names. Plugin name - ‘’, function name - ‘’.” 

I initially suspected that FunctionCallContentBuilder is resetting the previously assigned name to empty. The erroneous code is as follows:
       ‘ if (update.Name is string name) { (functionNamesByIndex ??= [])[update.FunctionCallIndex] = name; }’

For more details, see: https://github.com/microsoft/semantic-kernel/issues/9535

**Comment by liujiyuan** [comment]
The code belowd works.
`        if (update.Name is string name && !string.IsNullOrEmpty(name))
        {
            (functionNamesByIndex ??= [])[update.FunctionCallIndex] = name;
        }`

**Comment by liujiyuan** [comment]
The issue with the ID is the same problem.
The code belowd works.
`        if (update.CallId is string id && !string.IsNullOrEmpty(id))
        {
            (functionCallIdsByIndex ??= [])[update.FunctionCallIndex] = id;
        }
`

**Comment by markwallace-microsoft** [comment]
Hi @liujiyuan 
thanks for creating the issue and for investigating the problem.

You suggested fix makes sense. However I'm unable to reproduce the issue using our current sample [RunStreamingChatCompletionApiWithManualFunctionCallingAsync](https://github.com/microsoft/semantic-kernel/blob/238c26d2cd6c532d6c93f24748f361946bb15056/dotnet/samples/Concepts/FunctionCalling/FunctionCalling.cs#L285). We also have unit tests [FunctionCallContentBuilderTests.cs](https://github.com/microsoft/semantic-kernel/blob/238c26d2cd6c532d6c93f24748f361946bb15056/dotnet/src/SemanticKernel.UnitTests/Contents/FunctionCallBuilder/FunctionCallContentBuilderTests.cs).

Can you provide some additional information to help me to reproduce the problem?

**Comment by liujiyuan** [comment]
My key code is as follow:
` _kernel.Plugins.Add(KernelPluginFactory.CreateFromFunctions("FunctionCalling", new[]
        {
            _kernel.CreateFunctionFromMethod(GetWeather, "GetWeather", "Get the weather of a city."),
        }));

        var chatCompletionService = _kernel.GetRequiredService<IChatCompletionService>();

        var chatHistory = new ChatHistory();
        string ask = "What is the weather like in Hong Kong today?";
        chatHistory.AddUserMessage(ask);

        // OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new() 
        // { 
        //     FunctionChoiceBehavior = Microsoft.SemanticKernel.FunctionChoiceBehavior.Auto(autoInvoke: false) 
        // };

        OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new() 
        {
             ToolCallBehavior = ToolCallBehavior.EnableKernelFunctions
        };

        var chatCompletionResult = chatCompletionService.GetStreamingChatMessageContentsAsync(chatHistory, openAIPromptExecutionSettings, _kernel);
        
        ChatMessageContent? chatMessageContent = null;
        try
        {
            string completeContent = "";
            AuthorRole? role = null;
            string? modelId = null;
            object? innerContent = null;
            Encoding? encoding = null;
            IReadOnlyDictionary<string, object?>? metadata = null;

            var fccBuilder = new FunctionCallContentBuilder2();
            await foreach (var streamingContent in chatCompletionResult)
            {
                completeContent += streamingContent.Content;
                role = role ?? streamingContent.Role;
                modelId = modelId ?? streamingContent.ModelId;
                innerContent = streamingContent.InnerContent ?? innerContent;
                encoding = encoding ?? streamingContent.Encoding;
                metadata = metadata ?? streamingContent.Metadata;
                fccBuilder.Append(streamingContent);
            }

            chatMessageContent = new ChatMessageContent(
                role ?? AuthorRole.Assistant,
                completeContent,
                modelId!,
                innerContent,
                encoding,
                metadata
            );

            chatHistory.Add(chatMessageContent);

            var functionCallResults = fccBuilder.Build();
            foreach (var functionCall in functionCallResults)
            {
                chatMessageContent.Items.Add(functionCall);
                FunctionResultContent resultContent = await functionCall.InvokeAsync(_kernel);

                chatHistory.Add(resultContent.ToChatMessage());
            }
        }
        catch (Exception ex)
        {
            throw ex;
        }`

The code for the class FunctionCallContentBuilder2 is written based on the code from FunctionCallContentBuilder.
Here is the modified part in TrackStreamingFunctionCallUpdate .
`if (update.CallId is string id && !string.IsNullOrEmpty(id))
        {
            (functionCallIdsByIndex ??= [])[update.FunctionCallIndex] = id;
        }

        // Ensure we're tracking the function's name.
        if (update.Name is string name && !string.IsNullOrEmpty(name))
        {
            (functionNamesByIndex ??= [])[update.FunctionCallIndex] = name;
        }`
