### ISSUE TITLE
.Net: Bug:Error when saving data to Pinecone with Ollama

### ISSUE THREAD

**Issue by budgier** [microsoft/semantic-kernel#9569]
**Describe the bug**

Error when saving data to Pinecone

'Microsoft.SemanticKernel.HttpOperationException' occurred in System.Private.CoreLib.dll 
Response status code does not indicate success: 400 (Bad Request).

**To Reproduce**

using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.Pinecone;
using Microsoft.SemanticKernel.Embeddings;
using Microsoft.SemanticKernel.Memory;

var endpoint = new Uri("http://localhost:11434");
var modelId = "gemma2:27b";

var kernelBuilder = Kernel.CreateBuilder().AddOllamaTextGeneration(modelId: modelId, endpoint: endpoint)
                                          .AddOllamaTextEmbeddingGeneration(modelId, endpoint);
                                    
				                         
var kernel = kernelBuilder.Build();

var embeddingGenerator = kernel.GetRequiredService<ITextEmbeddingGenerationService>();

var memoryWithCustomDb = new MemoryBuilder()
            .WithTextEmbeddingGeneration(embeddingGenerator)
            .WithPineconeMemoryStore("gcp-starter", "xxxx")
            .Build();

var chatFunction = kernel.CreateFunctionFromPrompt("bla bla");
var response = await chatFunction.InvokeAsync(kernel, new KernelArguments() { });

await memoryWithCustomDb.SaveInformationAsync("test",response.ToString(),"ID12454");

**Expected behavior**

http code 200

**Platform**

 - OS: Windows 11
 - IDE: Visual Studio
 - Language: C#
 - Sources:  "Microsoft.SemanticKernel" Version="1.26.0"
                   "Microsoft.SemanticKernel.Connectors.Ollama" Version="1.27.0-alpha"
                   "Microsoft.SemanticKernel.Connectors.Pinecone" Version="1.27.0-preview"

**Comment by markwallace-microsoft** [comment]
Hi @budgier 
we have introduced new VectorData connectors to replace the experimental Memory functionality. Our plan is to mark the current experimental Memory functionality as obsolete and we are encouraging developer to switch to using the VectorData functionality.

Here are some links to help you to get started:
- https://github.com/markwallace-microsoft/semantic-kernel/tree/main/dotnet/samples/GettingStartedWithVectorStores
- https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/?pivots=programming-language-csharp
- https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/code-samples?pivots=programming-language-csharp

**Comment by budgier** [comment]
thanks , i made it work
