### ISSUE TITLE
Process Framework: Agent Sample - Basic

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#9572]

**Comment by joslat** [comment]
What do you have in mind  @alliscode ? 
A super-simple, simplest, interaction with an Agent with 1 or 2 tools?
step 1 user input --> Step 2 Agent
Step 2 Agent --> uses tool X
Step 2 Agent --> uses tool Y
Step 2 Agent --> Step 3 Response Output
Step 3 Response Output --> End

Something like that maybe? :)
