### ISSUE TITLE
Python: ProcessStepEdgeBuilder.send_event_to handles ProcessStepBuilder but type is only ProcessFunctionTargetBuilder

### ISSUE THREAD

**Issue by Druid-of-Luhn** [microsoft/semantic-kernel#9605]
The `ProcessStepEdgeBuilder.send_event_to` method's `target` parameter has the type `ProcessFunctionTargetBuilder`, but the implementation accepts a `ProcessStepBuilder`, and the samples call it with a `ProcessStepBuilder`.

Type-checking tools such as pydantic complain when passing a `ProcessStepBuilder` into the function, since it is not of type `ProcessFunctionTargetBuilder`.

I suggest that the `send_event_to` method's `target` parameter be updated to `Union[ProcessFunctionTargetBuilder, ProcessStepBuilder]` or `ProcessFunctionTargetBuilder | ProcessStepBuilder`, to accurately reflect the implementation of the method.

**Comment by moonbox3** [comment]
Hi @Druid-of-Luhn, thanks for filing and for catching this. We'll get this updated ASAP.

**Comment by moonbox3** [comment]
This fix is included in the recently released v1.14.0 package.
