### ISSUE TITLE
New Feature: implementation of custom ai connectors

### ISSUE THREAD

**Issue by malacoding** [microsoft/semantic-kernel#9607]
---
name: Feature request
about: Suggest an idea for this project

---

Enable the implementation of custom AI connectors, e.g. hosted LLMs on a server with custom API structure/parameters.
In my current use case, a LLM is hosted on a server providing a dedicated endpoint for access. 
The request structure of this endpoint differs from the ones provided within the semantic kernel framework (e.g. OpenAI, ...).
This implies my need to create a custom connector to correctly access and use this my API endpoint.

Thanks and best regards!

**Comment by RogerBarreto** [comment]
@malacoding, Semantic Kernel was built with this customization in mind.

All you need  to create your custom connector is to import our `Microsoft.SemanticKernel.Abstractions` package and implement your `ChatCompletion` service using our `IChatCompletionService` interface and many other interfaces depending on your model modalities.

Example for `ITextGenerationService`

https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Concepts/TextGeneration/Custom_TextGenerationService.cs
