### ISSUE TITLE
Python: Refactor integration tests

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/semantic-kernel#9615]
We should consider further refactoring our integration test pipeline to improve the speed and reliability. Below is a list of items we work on:
- Set a timeout on the tests so that they don't hang and block the merge queue.
- Split the test into multiple jobs so that they can run in parallel. Currently, we run the tests in groups sequentially. For instance, tests on completion and tests on memory can run in parallel.
- Run the jobs in larger runners so that test that require local resource become less flaky.
- Instead of running all the tests in every single PR merge, we can group a set of less important test to be run less frequently. For example, we can run the tests on the samples once per day at midnight.

**Comment by eavanvalkenburg** [comment]
First iteration done, already better, next is looking better at infra

**Comment by eavanvalkenburg** [comment]
Closing for now, tests are improved, will revisit.
