### ISSUE TITLE
.Net: Bug: Exception in Azure OpenAI GPT-4 ResponseFormat

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/semantic-kernel#9634]
**Describe the bug**
In Azure OpenAI, I created a deployment using the GPT-4 model based on version 2024-08-06, with a URI ending in api-version=2024-08-01-preview. When using the AddAzureOpenAIChatCompletion API with ResponseFormat in the kernel object, it threw an exception stating that the model does not support ResponseFormat.

**To Reproduce**
Version : Microsoft.SemanticKernel 1.28.0

**Expected behavior**

**Screenshots**
-

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: NuGet package version  1.28.0

**Additional context**
**Workaround**: I used an HTTP client with the URI (including api-version=2024-08-01-preview) and applied it in the kernel object. Now, the AddAzureOpenAIChatCompletion API works as expected.

**Comment by RogerBarreto** [comment]
When using the `AddAzureOpenAIChatCompletion` for a dedicated version you need to specify as an extra parameter:

`apiVersion` with the version you want in this case `2024-08-01-preview`.

```csharp
builder.AddAzureOpenAIChatCompletion(apiVersion: "2024-08-01-preview", ...);

```
