### ISSUE TITLE
Python: Adding DiskANN Vector Index Type to Azure Cosmos DB Mongo vCore

### ISSUE THREAD

**Issue by SelinaTang21** [microsoft/semantic-kernel#9676]
Add a new vector index type diskann to Azure Cosmos DB Mongo vCore vector store. Paper of DiskANN can be found here [DiskANN: Fast Accurate Billion-point Nearest Neighbor Search on a Single Node](https://proceedings.neurips.cc/paper_files/paper/2019/file/09853c7fb1d3f8ee67a61b6bf4a7f8e6-Paper.pdf).

**Comment by eavanvalkenburg** [comment]
Please see this comment: https://github.com/microsoft/semantic-kernel/pull/9677#issuecomment-2473297168
