### ISSUE TITLE
Bug: Ollama connector does not send the tools/agents/functions list

### ISSUE THREAD

**Issue by raffaeler** [microsoft/semantic-kernel#9682]
**Describe the bug**
I am using Semantic Kernel with Ollama and llama 3.2.

When I use the Ollama connector, the functions are not added to http request.
The same code and prompt using Azure OpenAI works correctly.

**To Reproduce**
OllamaFunctionCalling sample.

**Expected behavior**
I expect the functions being called.

**Platform**
 - OS: Windows 11
 - IDE: VS2022
 - Language: C# / .NET 9
 - Source: 1.28 alpha / preview

**Details**
I tried the same prompt on GPT and then on Ollama hosted locally.
When I use Ollama I specify the following settings:

```
KernelFunction[] functions = kernel.Plugins
                .SelectMany(p => p).ToArray();
FunctionChoiceBehavior functionOptions = FunctionChoiceBehavior.Required(functions, true); 

OllamaPromptExecutionSettings ollamaPromptExecutionSettings =
    new()
    {
        FunctionChoiceBehavior = functionOptions,
        ModelId = modelName,
        //...
    }
```
I also tried `FunctionChoiceBehavior.Auto()` wit no success.

I then passed my own HttpClient with a handler which logs all the http traffic. This is the result:

```json
{"model":"llama3.2","messages":[{"role":"system","content":"","images":null,"tool_calls":null},{"role":"user","content":"What's the weather like in Genoa right now?","images":null,"tool_calls":null}],"options":{"temperature":0.85,"top_p":0.9},"stream":true,"tools":null,"CustomHeaders":{}}
```

**Comment by raffaeler** [comment]
BTW what are the capabilities of this connector? It looks like it does not support multimodality.
In other words, a new prompt contains the image but the http message does not.

**Comment by shethaadit** [comment]
Hi @markwallace-microsoft, I will work on this and try to raise PR soon. :)

**Comment by nonoc** [comment]
Any news about that?
Thanks
