### ISSUE TITLE
.Net: New Feature: Provide additional messages when invoking the agent run.

### ISSUE THREAD

**Issue by sandrohanea** [microsoft/semantic-kernel#9685]
---
name: Provide additional messages when invoking the agent run.
about: Suggest an idea for this project

---

Similar with https://github.com/microsoft/semantic-kernel/issues/8715
[OpenAIAssistantInvocationOptions](https://github.com/microsoft/semantic-kernel/blob/4a92f34c17cd7a09f3bb14890c7b116f35882e13/dotnet/src/Agents/OpenAI/OpenAIAssistantInvocationOptions.cs) is not exposing all the properties available in [RunCreationOptions](...)

The missing property includes: 
 - [AdditionalMessages](https://github.com/openai/openai-dotnet/blob/539172fc699d29c3a812c848b07dc7e67fc7630f/src/Custom/Assistants/RunCreationOptions.cs#L52)

 - [ToolOverrides](https://github.com/openai/openai-dotnet/blob/539172fc699d29c3a812c848b07dc7e67fc7630f/src/Custom/Assistants/RunCreationOptions.cs#L101)

Without this option, we are forced to execute multiple calls to the API (to add the user message + separate to create the assistant run when we can do it with a single call).

**Comment by crickman** [comment]
Hi @sandrohanea - Thank you for the input / suggestions.

For `ToolOverrides`, this may be accomplished for code-interpreter or file-search via the either:
- `OpenAIAssistantInvocationOptions.EnableCodeInterpreter `  https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Agents/OpenAI/OpenAIAssistantInvocationOptions.cs#L31
_or_
- `OpenAIAssistantInvocationOptions.EnableFileSearch `  https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Agents/OpenAI/OpenAIAssistantInvocationOptions.cs#L37

For function overrides, the agent always advertises the available functions based on its associated `Kernel`:  `OpenAIAssistantAgent.Kernel` - https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Agents/Abstractions/KernelAgent.cs#L37

The collection of available plugins may be directly managed on the `Kernel` itself at any point:

```c#
agent.Kernel.Plugins.Add(...);
agent.Kernel.Plugins.Remove(...);
```

We currently support `AdditionalMessages` when creating a thread:  https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Agents/OpenAI/OpenAIThreadCreationOptions.cs

I can certainly add it to the `OpenAIAssistantInvocationOptions` also.
