### ISSUE TITLE
Python: Confusion between Automatic function calling and Planner

### ISSUE THREAD

**Issue by rakshahulle** [microsoft/semantic-kernel#9699]
I am now confused between  Automatic function calling and Planner concepts function_calling_stepwise_planner, SequentialPlanner. As mentioned Planner is deprecated and an automatic function calling is used for planning. Reference: https://learn.microsoft.com/en-us/semantic-kernel/concepts/planning?pivots=programming-language-python

**Comment by moonbox3** [comment]
We will be deprecating the planners in the near future. The guidance is to use automatic function calling instead.

**Comment by rakshahulle** [comment]
Why will it be deprecating? How Auto Function Calling is better than
planners?

**Comment by moonbox3** [comment]
Please see this blog post: https://devblogs.microsoft.com/semantic-kernel/planning-with-semantic-kernel-using-automatic-function-calling/
