### ISSUE TITLE
IMemoryStore.RemoveAsync

### ISSUE THREAD

**Issue by EashShow** [microsoft/semantic-kernel#970]
**Describe the bug**
An error will occur when call IMemoryStore.RemoveAsync

**Expected behavior**
Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Microsoft.SemanticKernel.Connectors.Memory.Qdrant.Http.ApiSchema.QdrantResponse'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.

**Desktop (please complete the following information):**
 - OS:  Windows
 - IDE: Visual Studio 2022
 - NuGet Package Version 0.13.442.1-preview

**Additional context**
the vector database is Qdrant

**Comment by craigomatic** [comment]
@tawalke any thoughts here?

**Comment by EashShow** [comment]
Let me fix this?

**Comment by craigomatic** [comment]
Closing as we ended up fixing this over at #1025 - thank you for the PR in any case :)

**Comment by Sam--Shan** [comment]
![image](https://github.com/microsoft/semantic-kernel/assets/10590637/2dabfc96-74c2-43b8-b1cb-e67f2908c708)
Hi @craigomatic, I am still encountering an error with version 0.19.230804.2-preview in NuGet. Has the fix been released for this version?

**Comment by craigomatic** [comment]
> ![image](https://user-images.githubusercontent.com/10590637/259907514-2dabfc96-74c2-43b8-b1cb-e67f2908c708.png) Hi @craigomatic, I am still encountering an error with version 0.19.230804.2-preview in NuGet. Has the fix been released for this version?

Hmm, it was fixed in a prior version, maybe a regression has snuck in. If you are using Qdrant, internally it's doing deserialisation via https://github.com/microsoft/semantic-kernel/blob/4ea1d48dfcbe0d1594351b6d946d60f2b9dd60a6/dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorDbClient.cs#L203

Would you mind opening a new issue and we will investigate?
