### ISSUE TITLE
No working: GetMessageContext:  Invalid URI: The format of the URI could not be determined

### ISSUE THREAD

**Issue by bpw320** [microsoft/semantic-kernel#9708]
in your example: 

 private static IReadOnlyList<ChatCitation> GetCitations(ChatMessageContent chatMessageContent)
 {
     var message = chatMessageContent.InnerContent as OpenAI.Chat.ChatCompletion;

     var messageContext = message.GetMessageContext();
         
        

     return messageContext.Citations;
 }

     var messageContext = message.GetMessageContext();
 return an error: Invalid URI: The format of the URI could not be determined

I am not sure if it is a bug or not, but it did not work

Thanks

**Comment by dmytrostruk** [comment]
@bpw320 Thanks for your question! Could you please specify what do you mean by index values? 

If you are interested in getting actual property values from Azure AI Search index, I'm not sure if it's possible to receive it directly from `ChatCitation`, but it should be possible to get an index data by using Azure AI Search directly in combination with `ChatCitation.ChunkId`. Please let me know if that helps.

Thanks!

**Comment by bpw320** [comment]
Thanks for this.
