### ISSUE TITLE
Unable to generate bot response. Details: TypeError: Failed to fetch Please check that your backend is running and that it is accessible by the app

### ISSUE THREAD

**Issue by Newday235** [microsoft/semantic-kernel#971]
**Describe the bug**
It seems I have started the program seccessfully. But when I try to talk to the bot, it could not answer.

**To Reproduce**
1. Go to : http://localhost:3000/
2. talk to copilot bot
3. no response
4. See error 1(on the web): Unable to generate bot response. Details: TypeError: Failed to fetch Please check that your backend is running and that it is accessible by the app
5. See error 2(windows terminal，dotnet run): fail: Microsoft.AspNetCore.Server.Kestrel[13] Connection id "0HMQIM1UJD5D4", Request id "0HMQIM1UJD5D4:00000019": An unhandled exception was thrown by the application.

**Expected behavior**
can talk to copilot bot

**Screenshots**
please see attached 2 pictures.
<img width="905" alt="pilot chat" src="https://github.com/microsoft/semantic-kernel/assets/133124929/8466894e-5778-44ce-bc98-6995aabc8830">
<img width="876" alt="dotnet dun" src="https://github.com/microsoft/semantic-kernel/assets/133124929/fdfdf928-b57b-464c-858f-d181b24263ec">

**Desktop (please complete the following information):**
 - OS: Windows11
 - IDE: VS Code
 - NuGet Package Version ?

**Additional context**

**Comment by lextm** [comment]
It's likely that you are testing again `OpenAI` instead of `AzureOpenAI`, then make sure you replaced all `AzureOpenAI` settings in [the config file](https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/webapi/appsettings.json).

If you missed one of them, then this error above is expected.

**Comment by Newday235** [comment]
> It's likely that you are testing again `OpenAI` instead of `AzureOpenAI`, then make sure you replaced all `AzureOpenAI` settings in [the config file](https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/webapi/appsettings.json).
> 
> If you missed one of them, then this error above is expected.

Thank you! Do you mean the 3 places I have replaced? Are there any other places I need to replace?
![微信图片_20230513161113](https://github.com/microsoft/semantic-kernel/assets/133124929/1760b7af-3f7c-47e5-aa32-5ff2cc8d83de)
![微信图片_20230513161109](https://github.com/microsoft/semantic-kernel/assets/133124929/64b267c6-9fb3-4eb0-976a-70504386897c)
![微信图片_20230513161058](https://github.com/microsoft/semantic-kernel/assets/133124929/e713ac0d-d5fd-4dee-82cb-852114ada0ba)

**Comment by Newday235** [comment]
thank you. fixed the bug.

**Comment by hathind-ms** [comment]
Closing since this is resolved.
