### ISSUE TITLE
Unable to generate bot response. Details: Error: 400: => Throttling: Too many requests, HTTP status: 429

### ISSUE THREAD

**Issue by cooptest** [microsoft/semantic-kernel#973]
I get no response no matter what message I send

![1](https://github.com/microsoft/semantic-kernel/assets/133195857/c0d3e7dd-8674-42f8-9d7d-82c29a79abc0)

**Comment by lextm** [comment]
Which API key are you using? You need a valid API key from either OpenAI or Azure OpenAI Service so as to fix that 429 error.

Specific to OpenAI, you should move to the pay-as-you-go plan when you free credit expired.

**Comment by cooptest** [comment]
@lextm I am using gpt plus

**Comment by lextm** [comment]
@cooptest You will have to tell more about it. Are you on a pay-as-you-go plan, or not? Please log into https://platform.openai.com/account/billing/overview and take a look.

**Comment by cooptest** [comment]
Thank you very much for your answer, because my api has expired, it will be fine to re-open the paid plan.

Another question, have you successfully deployed on the Internet? I want to deploy on the Internet, but I don't know how to set up the jump (http://localhost:3000) in Azure.

**Comment by teresaqhoang** [comment]
> Same for me, got always: warn: Microsoft.SemanticKernel.IKernel[0] Error executing action [attempt 1 of 1]. Reason: TooManyRequests. Will retry after 2000ms
> 
> To solve the issue I hade to add my credit card in the: https://platform.openai.com/account/billing/payment-methods After that is done it took some time before it work. I think about 10-15 minutes. The API payment is not included in the Premium, so if you pay for Premium, you must still pay for you API usage, separate, by adding a payment card. After adding the card, remember to adjust your usage limits, so you have control: https://platform.openai.com/account/billing/limits

Closing as a OpenAI Throttling issue -to remedy, adjust your usage limits as @snerting described above.

**Comment by comichael** [comment]
Tutorials should inform that you need to enter a payment method for your API key to work.

**Comment by teresaqhoang** [comment]
@comichael Opened new issue to add this detail into our samples here: https://github.com/microsoft/semantic-kernel/issues/1755
