### ISSUE TITLE
.Net: Bug: Support for Multiple LLMs at Runtime - Does Not Work as Documented

### ISSUE THREAD

**Issue by GregorBiswanger** [microsoft/semantic-kernel#9756]
**Describe the bug**  
I want to dynamically use different LLMs at runtime with various connectors, including AzureOpenAI. For example, it should be possible to start a conversation with GPT-3.5 and switch to GPT-4 at specific points. However, the provided code sample in your repository does not work as expected:  
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Concepts/ChatCompletion/Connectors_WithMultipleLLMs.cs  

Specifically, I am having issues with setting the `ModelID` and `ServiceId`. Additionally, `ServiceId` is marked as deprecated, adding further confusion.  
Currently, the last registered connector is always used, regardless of the specified `ModelID` or `ServiceId`.  

This is a critical issue for me, as using expensive models like GPT-4 unnecessarily increases costs and energy consumption due to the faulty implementation.  

I analyzed the communication using Burp Suite and noticed that the backend always calls the last registered connector, regardless of the `ModelID` configuration.

---

**To Reproduce**  
1. Start a project using the `Connectors_WithMultipleLLMs.cs` sample from your repository.  
2. Register multiple connectors, including AzureOpenAI with different models (e.g., GPT-3.5 and GPT-4).  
3. Attempt to switch between models during a conversation by setting `ModelID` or `ServiceId`.  
4. Observe that the last registered connector is always used, regardless of the configuration.  

---

**Expected behavior**  
I expect the desired connector to be dynamically selected at runtime based on the `ModelID`. Specifying a `ModelID` should ensure that the appropriate LLM connector is invoked without overlapping or defaulting to the last registered connector.  

---

**Screenshots**  
(Not applicable)

---

**Platform**  
- **OS:** Windows 11  
- **IDE:** Visual Studio 2022  
- **Language:** C#  
- **Source:** Latest main branch of the repository  

---

**Additional context**  
I used Burp Suite for analysis and observed that the backend always invokes the last registered connector, ignoring the `ModelID`. This makes it difficult to selectively use models like GPT-4 for specific scenarios, leading to unnecessary costs and inefficiencies.

**Comment by RogerBarreto** [comment]
@GregorBiswanger Thanks for your feedback.

Initially I did thought similar to you, where I could reuse the same service and override the modelId thru the settings. but this is not the actual behavior of our APIs. According to the design, each service is associated to one model only (early configuration), so, when you provide the `modelId` in the settings it will pick the service that was added to the kernel for that model. 

To have the behavior you expect, (having gpt3.5 and gpt-4) you need to register two `OpenAI` services for each, and the modelId setting will find the service for your configured model.

> Additionally, ServiceId is marked as deprecated

ServiceID is not deprecated is currently experimental and is on track to be promoted. `The experimental` attribute [sometimes is wrongly understood by the IDE as a Obsolete attribute](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-12.0/experimental-attribute#obsoleteattribute-and-deprecatedattribute).
