### ISSUE TITLE
Bug: Plugin created by VectorStoreTextSearch.CreateWithGetTextSearchResults is not returning the results from the IVectorStore

### ISSUE THREAD

**Issue by thomashauser** [microsoft/semantic-kernel#9762]
**Describe the bug**
The method VectorizableTextSearchAsync is returning to document chunks, but the plugin said it is empty.

**To Reproduce**
ITextEmbeddingGenerationService textEmbeddingGenerationService = new OpenAITextEmbeddingGenerationService("text-embedding-small", openAiClient);
IVectorStore vectorStore = new SqlServerVectorStore(connectionString)
	.UseTextEmbeddingGenerationService(textEmbeddingGenerationService);

var globalVectorStoreRecordCollection = vectorStore.GetCollection<int, DocumentRecord>("Global");
await globalVectorStoreRecordCollection.CreateCollectionIfNotExistsAsync();
var chatVectorStoreRecordCollection = vectorStore.GetCollection<int, DocumentRecord>($"Chat{chatId}");
await chatVectorStoreRecordCollection.CreateCollectionIfNotExistsAsync();

var globalSearch = new VectorStoreTextSearch<DocumentRecord>(globalVectorStoreRecordCollection, textEmbeddingGenerationService);
var chatSearch = new VectorStoreTextSearch<DocumentRecord>(chatVectorStoreRecordCollection, textEmbeddingGenerationService);

var builder = Kernel.CreateBuilder();
builder.AddAzureOpenAIChatCompletion(MODEL, azureOpenAIClient: openAiClient);
builder.Services.AddLogging(services => services.AddConsole().SetMinimumLevel(LogLevel.Trace));

var kernel = builder.Build();

// Add the plugin to the kernel
kernel.Plugins.Add(globalSearch.CreateWithGetTextSearchResults(nameof(globalSearch)));
kernel.Plugins.Add(chatSearch.CreateWithGetTextSearchResults(nameof(chatSearch)));

// Retrieve the chat completion service
var chatCompletionService = kernel.Services.GetRequiredService<IChatCompletionService>();

**Expected behavior**
The kernel should receive the two found document chunks.

**Screenshots**
![Image](https://github.com/user-attachments/assets/816bb212-f46d-4424-95ed-b5153ee7bcfa)
![Image](https://github.com/user-attachments/assets/5ff8120a-8aca-4d52-a24e-18be672c002a)

**Platform**
 - OS: Windows
 - IDE: Visual Studio 2022 17.12.0
 - Language: C#
 - Azure OpenAI: gpt-4o (2024-08-06), text-embedding-3-small
 - Source: 
    Azure.AI.DocumentIntelligence: 1.0.0-beta.3
    Microsoft.Extensions.Configuration.Json: 9.0.0
    Microsoft.Extensions.Configuration.UserSecrets: 9.0.0
    Microsoft.Extensions.DependencyInjection: 9.0.0
    Microsoft.Extensions.Logging.Console: 9.0.0
    Microsoft.Extensions.VectorData.Abstractions: 9.0.0-preview.1.24523.1
    Microsoft.SemanticKernel: 1.29.0
    Microsoft.SemanticKernel.Connectors.SqlServer: 1.29.0-alpha
    Microsoft.SemanticKernel.Plugins.Core: 1.29.0-alpha
    Microsoft.SemanticKernel.Plugins.Document: 1.29.0-alpha
    Microsoft.SemanticKernel.Plugins.Memory: 1.29.0-alpha
    Microsoft.Data.SqlClient: 5.2.2
    Microsoft.SemanticKernel.Abstractions: 1.29.0
    Microsoft.SemanticKernel.Connectors.AzureOpenAI: 1.29.0
    Microsoft.SemanticKernel.Connectors.OpenAI: 1.29.0
    System.Linq.Async: 6.0.1

**Comment by inQuantum** [comment]
Objects from VectorSearch Results should be transformed/mapped to TextSearchResult. This should solve issue.

```c#

var result = new VectorStoreTextSearch<DataModel>(vectorStoreRecordCollection, textEmbeddingGeneration, stringMapper, resultMapper);


protected sealed class DataModelTextSearchStringMapper : ITextSearchStringMapper
{
    /// <inheritdoc />
    public string MapFromResultToString(object result)
    {
        if (result is DataModel dataModel)
        {
            return dataModel.Text;
        }
        throw new ArgumentException("Invalid result type.");
    }
}

/// <summary>
/// Result mapper which converts a DataModel to a TextSearchResult.
/// </summary>
protected sealed class DataModelTextSearchResultMapper : ITextSearchResultMapper
{
    /// <inheritdoc />
    public TextSearchResult MapFromResultToTextSearchResult(object result)
    {
        if (result is DataModel dataModel)
        {
            return new TextSearchResult(value: dataModel.Text) { Name = dataModel.Key.ToString(), Link = dataModel.Link };
        }
        throw new ArgumentException("Invalid result type.");
    }
}
```

**Comment by thomashauser** [comment]
> Hi @thomashauser 
> we have this sample [VectorStore_TextSearch.cs](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Concepts/Search/VectorStore_TextSearch.cs) which shows this working with our in-memory store. Can you reproduce the error by changing this sample?
> 
> Did you create your own `SqlServerVectorStore` implementation?

Yes, it's my own implementation. There is currently no version that supports IVectoreStore and not the deprecated kernel memory, right?

**Comment by thomashauser** [comment]
> Objects from VectorSearch Results should be transformed/mapped to TextSearchResult. This should solve issue.
> 
> ```c#
> 
> var result = new VectorStoreTextSearch<DataModel>(vectorStoreRecordCollection, textEmbeddingGeneration, stringMapper, resultMapper);
> 
> 
> protected sealed class DataModelTextSearchStringMapper : ITextSearchStringMapper
> {
>     /// <inheritdoc />
>     public string MapFromResultToString(object result)
>     {
>         if (result is DataModel dataModel)
>         {
>             return dataModel.Text;
>         }
>         throw new ArgumentException("Invalid result type.");
>     }
> }
> 
> /// <summary>
> /// Result mapper which converts a DataModel to a TextSearchResult.
> /// </summary>
> protected sealed class DataModelTextSearchResultMapper : ITextSearchResultMapper
> {
>     /// <inheritdoc />
>     public TextSearchResult MapFromResultToTextSearchResult(object result)
>     {
>         if (result is DataModel dataModel)
>         {
>             return new TextSearchResult(value: dataModel.Text) { Name = dataModel.Key.ToString(), Link = dataModel.Link };
>         }
>         throw new ArgumentException("Invalid result type.");
>     }
> }
> ``` 

Awesome that worked. Thanks
