### ISSUE TITLE
Plugin samples using DI

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#9769]
Create a sample that uses a plugin which depends on a service made available using dependency injection

- [ ] Native function
- [ ] Open API function

**Comment by RogerBarreto** [comment]
- [x] Native functions

We do have a sample in the getting started Step (Dependency Injection), injecting ILoggerFactory in a plugin.

https://github.com/microsoft/semantic-kernel/blob/c022cf96ed97132040003f2ca2214e9a3df4dc76/dotnet/samples/GettingStarted/Step4_Dependency_Injection.cs#L53

HomeAutomation Demo also uses DI with plugins, injecting plugins within plugins.

https://github.com/microsoft/semantic-kernel/blob/c022cf96ed97132040003f2ca2214e9a3df4dc76/dotnet/samples/Demos/HomeAutomation/Program.cs#L58

and here

https://github.com/microsoft/semantic-kernel/blob/c022cf96ed97132040003f2ca2214e9a3df4dc76/dotnet/samples/Demos/HomeAutomation/Plugins/MyAlarmPlugin.cs#L12
