### ISSUE TITLE
OpenAI config sample no need to pass the service name

### ISSUE THREAD

**Issue by michaelslz23** [microsoft/semantic-kernel#978]
**Describe the bug**
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/README.md sample codes for OpenAI
// Alternative using OpenAI
// kernel.Config.AddOpenAITextCompletionService(**"davinci-openai",**
//     "text-davinci-003",               // OpenAI Model name
//     "...your OpenAI API Key..."       // OpenAI API Key
// );

"davinci-openai" is not needed here.  Otherwise you'll get 401 permission error.

**Comment by craigomatic** [comment]
Good catch! 

Would you be interested in sending a PR that fixes this? If not, no worries, we can take care of it.

**Comment by michaelslz23** [comment]
@craigomatic Thanks.   I'm not sure if I did it right or not, pull request is here, https://github.com/microsoft/semantic-kernel/pull/1078.

**Comment by craigomatic** [comment]
Looks like there were overlapping PRs to fix this one and another member of the community was slightly faster at clicking the button to resolve. 

Thank you in any case, closing this for now :)
