### ISSUE TITLE
.Net: Bug: Update packages to .NET 9

### ISSUE THREAD

**Issue by sant11h** [microsoft/semantic-kernel#9802]
Hello guys!
I was upgrading our project to the latest .NET version and I found that you have dependency on packages from version 8.. for that reason we cannot upgrade. Below I state the error that I have. Thanks!

**Describe the bug**
Application.csproj: Warning NU1608 : Detected package version outside of dependency constraint: Microsoft.SemanticKernel.Prompty 1.30.0-alpha requires Microsoft.Extensions.FileProviders.Physical (>= 8.0.0 && < 9.0.0) but version Microsoft.Extensions.FileProviders.Physical 9.0.0 was resolved.

**Expected behavior**
The solution should build.

**Comment by evchaki** [comment]
@sant11h - you should see a fix for this in this week's package 1.31.0.  Thanks for reporting it.  @markwallace-microsoft  is going to work on this.

**Comment by stephentoub** [comment]
Setting upper bounds on package references like this is very much discouraged:
https://github.com/microsoft/semantic-kernel/blob/b8680fa599b6b7dacad17e67c94904c1c2dbf5eb/dotnet/Directory.Packages.props#L84-L85
