### ISSUE TITLE
.Net: New Feature: MistralAI - Multi-Modal Chatcompletion Support

### ISSUE THREAD

**Issue by tntwist** [microsoft/semantic-kernel#9806]
---
name: MistralAI - Multi-Modal Chatcompletion Support
about: Add support for multimodal chat completion for the MistralAI connector.

---

Hey there,

i played a bit with the .Net Connector for MistralAI and noticed that the connector does not support multi modal chat completion.
It would be nice to have this be supported by the connector.

Best regards

**Comment by evchaki** [comment]
@tntwist - thanks for bringing this up.  Do you need this ASAP for a project, or more to just try it out?  @markwallace-microsoft - can you take a look.

**Comment by tntwist** [comment]
@evchaki - thanks for you fast response. I plan to use sk in a project that requires to use Mistral with multi modal chat completion. So ASAP would be great. ❤ Also implementation is nearly finished for the use case in my project. Just stumbled on this when testing.

**Comment by markwallace-microsoft** [comment]
Hi @tntwist 
can you share which multi-modal scenario you are trying?

**Comment by tntwist** [comment]
Image description.
The user adds some images and asks to describe the images.

So the issue is that the semantic kernal connector is not sending the images to mistral.

**Comment by tntwist** [comment]
@markwallace-microsoft 

Seems like base64 encoded images does not work.
When i try to add an image from a stream i get an exception.
I think its releated to this line:
https://github.com/microsoft/semantic-kernel/blob/88635e177a1175357d3bcc990127a43b18d6106d/dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs#L787C1-L794C14

This is the way i create the image content to be added:
```
using var imageContentStream = await GetImageContentMemoryStreamAsync(content);

return new ImageContent(imageContentStream.ToArray(), MimeTypes.GetMimeType(content.FileName));
```

As is see the Uri Property of the ImageContent is not set then. 
![Image](https://github.com/user-attachments/assets/291b9e6d-d25a-430a-bd13-0aae03a03c1c)

Maybe i´m wrong but does it needs to be set even when the image is being added as base64 uri and DataUri is set?
