### ISSUE TITLE
Python: Bug: Process Framework KernelProcessStep.on_activate is never called

### ISSUE THREAD

**Issue by Druid-of-Luhn** [microsoft/semantic-kernel#9829]
**Describe the bug**

The abstract class [`KernelProcessStep`](https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/processes/kernel_process/kernel_process_step.py) has an [`on_activate`](https://github.com/microsoft/semantic-kernel/blob/bead9ef49e7166ab4b25cbafbe2c7b9f66850907/python/semantic_kernel/processes/kernel_process/kernel_process_step.py#L25) method, which one would assume is called when the step is activated, but the method is never called.

**To Reproduce**

1. Create a `KernelProcessStep` subclass that overrides the `on_activate` method,
2. Put the step into a process,
3. Run the process: the `on_activate` method is never called.

**Expected behavior**

The `KernelProcessStep.on_activate` method would be called when a step is activated, in both the local and Dapr runtimes. This would act as a form of zero-argument init method for when a step is activated.

**Screenshots**

Result of the code search showing that `on_activate` is never called.

![Image](https://github.com/user-attachments/assets/b998c779-3a4e-4256-bd76-72069046c140)

**Platform**

 - OS: Windows
 - IDE: gVim + PowerShell
 - Language: Python
 - Source: pip package version 1.16.0

**Additional context**

n/a

**Comment by evchaki** [comment]
@eavanvalkenburg - can you take a look?

**Comment by evchaki** [comment]
@Druid-of-Luhn - thanks for reporting this!

**Comment by eavanvalkenburg** [comment]
@Druid-of-Luhn  thanks for calling this out, turns out that was a leftover from a previous iteration, it was surpassed by the `activate` function that also sets up state, I have created a PR that removes it from both the KernelProcessStep and the sample.
