### ISSUE TITLE
.Net: New Feature: Add missing optional parameter responseMimeType to GeminiPromptExecutionSettings to allow for valid JSON output

### ISSUE THREAD

**Issue by Millmer** [microsoft/semantic-kernel#9863]
---
name: Add missing optional parameter `responseMimeType` to `GeminiPromptExecutionSettings`

about:  The optional API parameter `responseMimeType` is missing from the `GeminiPromptExecutionSettings` which is preventing the ability to have valid JSON responses returned from requests to Gemini (similar to OpenAI's `response_format: "json_object"`). This allows you to set the appropriate response type to avoid unintended behaviours.

---

Suggested Property:
```csharp
[JsonPropertyName("responseMimeType")]
[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
public string? ResponseMimeType { get; set; }
```

Available values are:
- application/json: JSON response in the candidates.
- text/plain (default): Plain text output.
- text/x.enum: For classification tasks, output an enum value as defined in the response schema.

Google documentation:
https://cloud.google.com/vertex-ai/generative-ai/docs/reference/rest/v1/GenerationConfig
https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference

Ideally the `responseSchema` property should also be incorporated to allow for "[controlled generation](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/control-generated-output)", as Google call it (the same as Structured Output with OpenAI), but that's a much larger implementation. Adding `responseMimeType` would be a great start and seems like a low handing fruit, I may be wrong though... 🤔 It looks like this has been added on the Python version already.

**Comment by shethaadit** [comment]
Hi @markwallace-microsoft, @moonbox3, I will work on this and raise PR soon. :)
