### ISSUE TITLE
Please add (optional) ServiceId argument to CreateSemanticFunction

### ISSUE THREAD

**Issue by PederHP** [microsoft/semantic-kernel#989]
The CreateSemanticFunction extension methods (from InlineFunctionsDefinitionExtension) are great convenience methods for creating Semantic Functions on the fly, but it would be very useful to have an optional ServiceId (or better a Func providing it) to allow binding to a different Kernel service than the defeault behavior of always binding to the "Embedding" or "Completion" services registered with the Kernel.

This can be achieved manually by getting an alternative the service by name from the KernelConfig and setting it via the SetAIService method of the ISKFunction returned by CreateSemanticFunction. For convenience, it would be nice if this could happen in CreateSemanticFunction via the provided optional argument.

Kernels already support registering multiple AI service backends, so adding convenient mapping to these would be a useful feature.

**Comment by sneha-afk** [comment]
Hello, me and two teammates (@am831 and @SebasX5) would like to work on this, could we be assigned to this? Thank you!

**Comment by shawncal** [comment]
Good extension method candidate!

**Comment by markwallace-microsoft** [comment]
We now support this, see https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Functions/Functions.UnitTests/SemanticFunctions/SemanticFunctionTests.cs#L145
