### ISSUE TITLE
Python: New Feature: Support Foundry SDK in Python

### ISSUE THREAD

**Issue by johnsinco** [microsoft/semantic-kernel#9899]
---
### Support Foundry SDK in Python

---

The recently released Azure AI Foundry Python SDK supports retrieving Azure OpenAI connections from your Foundry project.  This improves project security as you are not dealing with the AOAI endpoints and secret keys.  I have not been able to find an integration point where I can initialize the SK-Python `Kernel` object in such a way to utilize the Foundry initialized AOAI instance.

#### Proposed Change
Allow the AOAI instance `openai.AzureOpenAI` to be injected similar to the below...

```
from azure.identity import DefaultAzureCredential
from azure.ai.projects import AIProjectClient
from semantic_kernel import Kernel
import openai.AzureOpenAI

project_connection_string="<<AI Foundry connection string>>"

project = AIProjectClient.from_connection_string(conn_str=project_connection_string, credential=DefaultAzureCredential())  # or Managed Identity, etc.

# retrieve the AOAI instance from the Foundry project
injected_aoai_client = project.inference.get_azure_openai_client(api_version="2024-06-01")  # this is an openai.AzureOpenAI object

# Create the Kernel object and add the existing AOAI service retrieved from the Foundry Project
kernel = Kernel(services={"azure_openai": injected_aoai_clieint})

**Comment by moonbox3** [comment]
Hi @johnsinco, thanks for opening this item. I was looking for the code for the `get_azure_openai_client` method and it returns an `AsyncAzureOpenAI` client:

```python
async def get_azure_openai_client(self, *, api_version: Optional[str] = None, **kwargs) -> "AsyncAzureOpenAI":
    ...
```

You could inject this custom client into our `AzureChatCompletion` class like:

```python
azure_custom_client = AzureChatCompletion(
    async_client=<your_custom_client>
)
```
