### ISSUE TITLE
Python: New Feature: token usage in metrics

### ISSUE THREAD

**Issue by Druid-of-Luhn** [microsoft/semantic-kernel#9909]
---
name: Feature request
about: Suggest an idea for this project

---

Currently, the only metrics produced by Semantic Kernel (at least in Python) are function call durations. 

The [observability documentation](https://learn.microsoft.com/en-us/semantic-kernel/concepts/enterprise-readiness/observability/?pivots=programming-language-python) does indeed mention this:

Telemetry | Description
-- | --
Metric | Semantic Kernel captures the following metrics from kernel functions:<ul><li>`semantic_kernel.function.invocation.duration` (Histogram) - function execution time (in seconds)</li><li>`semantic_kernel.function.streaming.duration` (Histogram) - function streaming execution time (in seconds)</li></ul>

However, above that it also says (emphasis mine):

> __Metrics:__ Semantic Kernel emits metrics from kernel functions and AI connectors. You will be able to monitor metrics such as the kernel function execution time, __the token consumption of AI connectors__, etc.

From that I understand that the feature is planned but not yet implemented. It feels like token usage would be a very helpful one to get as a metric (I can see that it is already logged), since it is a common question for solutions that use LLMs.

For the moment, is it possible for me to create some kind of filter or something and track the metric myself? Or does this depend on a more internal implementation?

I have also seen this issue: https://github.com/microsoft/semantic-kernel/issues/6489

**Comment by alliscode** [comment]
@TaoChenOSU could you look at this please.

**Comment by TaoChenOSU** [comment]
@Druid-of-Luhn Thank you for bringing this up!

Currently in Python, we are not tracking the token usage per connector as a metric. In .Net, it depends on the specific implementation of the connector. For example, the OpenAI connector emits 3 metrics to track token consumption while the Bedrock connector doesn't.

To answer your question on if it's possible for you to create the metrics yourself, the answer is yes. We do include the token usage information (when it's available) as part of the metadata on the return object when you call a chat completion service. Depending on how you use the AI service, you can create the metrics differently. If you are calling the service directly, you can create the metrics along with where you are calling the service. If you are using a kernel function, you can create the metrics in a filter.

Feel free to post further questions :)

**Comment by TaoChenOSU** [comment]
Yes, we do have plans to reach parity: https://github.com/microsoft/semantic-kernel/issues/6750
