### ISSUE TITLE
.Net: New Feature: configure the agents with functions by name

### ISSUE THREAD

**Issue by sorin-costea** [microsoft/semantic-kernel#9934]
---
name: configure the agents with functions by name

about: Today to create a ChatCompletionAgent I can give it a 
FunctionChoiceBehavior = FunctionChoiceBehavior.Required(someListOfKernelFunctions)
But that means I must program the finding by hand of the functions, and the build of that list parameter. But the agent can already find them by name - like I see in the prompt template (MyPlugin-MyFunction). So how about configuring the list of functions with the string list of names? Or only functions from a certain plugin? Some filtering would make my code much cleaner (I call this less boilerplate).

Of course I can use FunctionChoiceBehavior = FunctionChoiceBehavior.Required() then everything and the kitchen sink will be available, but right now my agents for some reason got the bad habit to call EVERY functions they can, so I'd rather filter that in some way.

---

**Comment by SergeyMenshykh** [comment]
Hi @sorin-costea, there are a few options to do it and you can use any of them:
```csharp
// Option 1 - use only one function
KernelFunction getWeatherFunction = kernel.Plugins.GetFunction("HelperFunctions", "GetWeatherForCity");
OpenAIPromptExecutionSettings settings = new() { FunctionChoiceBehavior = FunctionChoiceBehavior.Required(functions: [getWeatherFunction]) };

// Option 2 - use all plugin functions
IEnumerable<KernelFunction> allPluginFunctions = kernel.Plugins["HelperFunctions"];
OpenAIPromptExecutionSettings settings = new() { FunctionChoiceBehavior = FunctionChoiceBehavior.Required(functions: allPluginFunctions) };

// Option 3 - use a few plugin functions
IEnumerable<KernelFunction> functions = kernel.Plugins["HelperFunctions"].Where(f => f.Name is "GetWeatherForCity" or "GetCurrentUtcDateTime");
OpenAIPromptExecutionSettings settings = new() { FunctionChoiceBehavior = FunctionChoiceBehavior.Required(functions: functions) };

// Option 4 - specify functions by their FQNs
RequiredFunctionChoiceBehavior behavior = (RequiredFunctionChoiceBehavior)FunctionChoiceBehavior.Required();
behavior.Functions = ["HelperFunctions-GetWeatherForCity", "HelperFunctions-GetCurrentUtcDateTime"];
OpenAIPromptExecutionSettings settings = new() { FunctionChoiceBehavior = behavior };
```

The options 1, 2, and 3 would allow your code to fail fast and detect misconfiguration(either a plugin or a function is not registered) early at the plugin/function lookup line. Option 4 will inform you about misconfiguration at a later stage when you prompt the AI model. 

Options 1, 2, and 3 were designed to be used from code, while option 4 was designed to narrow downs the list of advertised functions from JSON/YAML prompt templates.

Our advice would be to use options 1, 2, or 3 to detect misconfiguration as early as possible.

**Comment by sorin-costea** [comment]
Thank you so much for the examples, now I can really start!

**Comment by sorin-costea** [comment]
Oops maybe I shouldn't have closed it? In any case, for ME it's solved thank you :)
