### ISSUE TITLE
The TXT file was uploaded successfully, but Copilot indicates that the file cannot be accessed

### ISSUE THREAD

**Issue by PolarPeak** [microsoft/semantic-kernel#994]
I uploaded the txt file through here, but when I asked it to help me summarize and analyze the content of the txt file, it prompted me that I could not analyze it because I did not have the ability to connect to the Internet. Or it prompts that there is no ability to access the contents of the file

![image](https://github.com/microsoft/semantic-kernel/assets/44831329/136128c7-b90e-462f-98e0-3988da6fe23e)

![image](https://github.com/microsoft/semantic-kernel/assets/44831329/75b8da3d-f97c-41ab-ae3e-5e95c320925d)

![image](https://github.com/microsoft/semantic-kernel/assets/44831329/6dc19e18-e3eb-4f20-91d7-32f592ffef89)

**Comment by PolarPeak** [comment]
Prompt that the upload was successful, I updated the latest code and it seems to be ready to use. But it can't help me analyze the contents of the file. It may be that the request response token is too short, which makes it impossible to fully analyze the log file I gave him.

**Comment by TaoChenOSU** [comment]
Hello!

Yes, you're right. Copilot Chat has limited capacity and cannot analyze the entire files if they are very large. You might want to try to ask the bot more specific questions. For example, you can ask "Please find as many dangerous entries as possible in the log file I provided and summarize them for me?".

**Comment by PolarPeak** [comment]
> 你好！
> 
> 你是对的。Copilot Chat 的容量有限，如果文件非常大，则无法分析整个文件。您可能想尝试向机器人询问更具体的问题。例如，你可以问“请在我提供的日志文件中尽可能多地找出危险的条目，并为我总结一下？”。

Maybe so, I'll give it a try. Today I gave him a 220k txt file. I hope it can help me analyze which logs in this file are safe and which are not safe. It can print out part of the logs for me, but only part of them, such as I tell it the second log, when I tell it the 10th log it doesn't know. Maybe I need your tips and help, how can I operate better in this situation? Do you use openai for analyzing logs? What does coploit chat do in this process? Can the default dialogue return to Chinese?

**Comment by PolarPeak** [comment]
I tried a 20k text log file and it doesn't parse well and give results, which I think is a pity. We need this kind of scene very much, can we optimize it?

**Comment by PolarPeak** [comment]
> 

How can I try other chunking strategies in the document import controller? How can I change the prompt words to Chinese? Do you need to modify the source code? I use Chinese to ask questions, and the response is also in English. Generally speaking, I will ask coploit to make it return in Chinese, which is okay.

**Comment by TaoChenOSU** [comment]
Closing now as it appears this issue has been resolved. Please reopen as needed.
