### ISSUE TITLE
.Net: Json serialization issue when using SK Streaming chat completion in ASP.net Core minimal Api

### ISSUE THREAD

**Issue by HeKeHenryZhang** [microsoft/semantic-kernel#9941]
I find that JsonSerializerIsReflectionEnabledByDefault is required to be enabled when using Streaming chat completion with ASP.net Core minimal Api. Is it an expected behavior of using SK? 
SK is Aot Compatible, why should we still enable JsonSerializerIsReflectionEnabledByDefault explicitly.

Streaming chat completion
To use streaming chat completion, you can use the following code to generate a response from the AI agent.

```C#

Copy
ChatHistory history = [];
history.AddUserMessage("Hello, how are you?");

var response = chatCompletionService.GetStreamingChatMessageContentsAsync(
    chatHistory: history,
    kernel: kernel
);

//OpenAI.ModelSerializationExtensions' threw an exception. ---> System.InvalidOperationException: 
//Reflection-based serialization has been disabled for this application. 
//Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property
await foreach (var chunk in response)
{
   yield return chunk.Content ?? string.Empty;
}

**Comment by SergeyMenshykh** [comment]
Hi @HeKeHenryZhang, I presume you don't use the ONNX AI connector, right? At the moment, we have only three Native-AOT packages: Abstractions, Core, and the ONNX AI connector, but we have plans to make more SK packages AOT-friendly.   
  
Tasks to make {Azure} OpenAI AI connectors AOT compatible - https://github.com/microsoft/semantic-kernel/issues/9972   
  
SK AOT-compatible packages - https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Demos/AotCompatibility/README.md

**Comment by HeKeHenryZhang** [comment]
> Hi [@HeKeHenryZhang](https://github.com/HeKeHenryZhang), I presume you don't use the ONNX AI connector, right? At the moment, we have only three Native-AOT packages: Abstractions, Core, and the ONNX AI connector, but we have plans to make more SK packages AOT-friendly.
> 
> Tasks to make {Azure} OpenAI AI connectors AOT compatible - [#9972](https://github.com/microsoft/semantic-kernel/issues/9972)
> 
> SK AOT-compatible packages - https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Demos/AotCompatibility/README.md

Thanks @SergeyMenshykh .  I'm using Core + AzureOpenAI connector.

**Comment by SergeyMenshykh** [comment]
Closing the issue for now. The work will be tracked in the https://github.com/microsoft/semantic-kernel/issues/9972 issue.
