### ISSUE TITLE
.Net: Bug: Unable to use Semantic Kernel on .Net Framework 4.8

### ISSUE THREAD

**Issue by pvillads** [microsoft/semantic-kernel#9966]
**Describe the bug**
It is not possible to use the SK on .NET framework.

**To Reproduce**
1. Create a console application for .NET FW 4.8
2. Install the Microsoft.SemanticKernel nuget package. Version 1.32 is selected.
3. This will fail with this message
Unable to find a version of 'Azure.AI.OpenAI' that is compatible with 'Microsoft.SemanticKernel.Connectors.AzureOpenAI 1.32.0 constraint: Azure.AI.OpenAI (= 2.1.0-beta.2)'.

**Expected behavior**
This should work, so that I can build semantic kernel applications on the .NET FW. You are shipping the code as .NET standard 2.0, so this should work?

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: Nuget version 1.32 of MicrosoftSemanticKernel

**Additional context**
Normally I would build with .NET, not the FW, but there are important constraints that force me to use FW (must run inside Visual Studio).

**Comment by pvillads** [comment]
Installing the Azure.AI.OpenAI nuget prior to the semantic kernel does not fix the issue.

**Comment by RogerBarret0** [comment]
@pvillads , have a look on this issue.

- https://github.com/microsoft/semantic-kernel/issues/9755

Installing previously the Azure.AI.OpenAI should fix the problem, but make sure you are installing the pre-release (2.1.0-beta), not the GA (2.0.0).

You may also receive similar notification for other packages like in the issue above.

**Comment by pvillads** [comment]
Thank you. I will give it a spin.

However, I would not like to ship anything with preview or beta versions for customers. I am hoping these issues go away as the preview and beta items transform into GA versions.

BR PV

**Comment by adv12** [comment]
Did this get fixed or just closed?  Folks at work just tried to integrate SK 1.39.0 into a Framework webapp to no avail.  How can you advertise .NET Standard 2.0 support if people have to jump through undocumented hoops to get a working version?

**Comment by cdeisler** [comment]
Calling from .net 4.8 asp.net into .NETStandard v2.0 class library (hosting SK) gives me this error on every version of SemanticKernel back to 1.0.1

`System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.SemanticKernel.Abstractions, Version=1.0.1.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3' or one of its dependencies. The system cannot find the file specified.'`

**Comment by knazeri** [comment]
Any update on this?

**Comment by pino-aino** [comment]
Still no news... no workaround :-(
