### ISSUE TITLE
UI in chatapp will not show input correctly when input is in state

### ISSUE THREAD

**Issue by poweihuang0817** [microsoft/semantic-kernel#998]
**Describe the bug**
Sample UI should get input from state as fallback.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

```[tasklist]
### Tasks
- [ ] Function inputs should be marked as Parameters, not part of the state.
```

**Comment by poweihuang0817** [comment]
![image](https://github.com/microsoft/semantic-kernel/assets/131632377/a108f913-b90d-464a-aef5-4c9675bbbeea)

**Comment by lemillermicrosoft** [comment]
This seems like an ActionPlanner bug. It is placing `SoP_High_Memory` into the Plan.State which gets overridden by the input when the plan is executed (`Yes, proceed`). LIke `SequentialPlanner`, this should be a `Parameter` on the step where this should be input.

https://github.com/microsoft/semantic-kernel/blob/f1448c9a0759947256af7f4c6b940c9eab06ea91/dotnet/src/Extensions/Planning.ActionPlanner/ActionPlanner.cs#L123

**Comment by lemillermicrosoft** [comment]
I believe this has been resolved. Please re-activate or open a new issue if still experiencing issues. cc @teresaqhoang to confirm.

**Comment by teresaqhoang** [comment]
Hey @poweihuang0817, there's a fix in my PR here to show INPUT variables when the value is not empty. https://github.com/microsoft/semantic-kernel/pull/1506

It's a one-line change in [PlanStepCard ](https://github.com/microsoft/semantic-kernel/pull/1506/files#diff-bffe49db4d0ff8cd485a518923a53c214dacd05e8249ed9b44a23f76e65a30c9)to fix this, feel free to copy it over locally so you don't have to wait for the PR to merge
![image](https://github.com/microsoft/semantic-kernel/assets/125500434/ea4f6815-7b3c-4c6d-b681-3475debf7491)

**Comment by teresaqhoang** [comment]
Fix merged here https://github.com/microsoft/semantic-kernel/pull/1555
