### ISSUE TITLE
Sample app response is slow like 10-20s sometimes

### ISSUE THREAD

**Issue by poweihuang0817** [microsoft/semantic-kernel#999]
**Describe the bug**
Sample app response is slow like 10-20s sometimes. Even though I've used paid account with openAI, probably too many round trip.

      Request finished HTTP/2 POST https://localhost:40443/skills/ChatSkill/functions/Chat/invoke application/json 1132 - 200 - application/json;+charset=utf-8 103352.8697ms

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by craigomatic** [comment]
It looks like you're using the Copilot Chat sample - for the moment, to speed things up you can edit appsettings.json and set `Planner:Enabled` to false. While will disable plugins and some other interesting features, you will get a faster response. 

We are continuing to explore strategies to improve the response and will likely add chat streaming in to copilot chat in the near future (#829 added streaming support to SK)

**Comment by poweihuang0817** [comment]
But with planner disabled, could we still invoke custom skill? Would we be able to select one skill from many? Looks like no?

**Comment by adrianwyatt** [comment]
We recently removed the planner:enabled setting and it now automatically disables if the user on the frontend has not enabled any plugins. https://github.com/microsoft/semantic-kernel/pull/1151

**Comment by adrianwyatt** [comment]
The lag in chat responses has to do with the chat app running 1-2 round trips with the AI (3 if a plugin/planner is enabled). We also use the AI /embeddings endpoints to create long-term memories which adds at least one more round trip. After the /Build conference we are taking a look at how we might be able to bring this response time down through parallelization and a different memories architecture.
